### PR TITLE
Add logging when quitting or crashing

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds logging for when a subprocess of the GUI exits unexpectedly.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 299 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133#-Mp66XUlEIxhga5yl3ir:-Mp66XUmBkK9NJkgF32Y:bdu14ib) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5e3e9dd2cc70e4d3fc02c847f985e9a2b1785d6/gui/src/main/index.ts#L299)):*
> ```XML
>       );
>     });
>     app.on('child-process-gone', (_event, details) => {
> ```

`details` is guaranteed to be provided right?

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 299 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133#-Mp66XUlEIxhga5yl3ir:-Mp6Yc9T3WV7W4lGI11u:bbidugk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5e3e9dd2cc70e4d3fc02c847f985e9a2b1785d6/gui/src/main/index.ts#L299)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`details` is guaranteed to be provided right?
</blockquote></details>

According to the type definitions it is and the docs doesn't say anything about it not always being provided.

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133#-:-MpLRRz_9f7K0Z4dVCYn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
