### PR TITLE
Add DAITA V2 support for wireguard-go

### PR DESCRIPTION
**Pull request by dlon**
This PR enables DAITA V2 for all platforms that use wireguard go (except on iOS).

Related PR: https://github.com/mullvad/wireguard-go/pull/18.

Fix DES-1386.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 3 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158)* status: 13 of 18 files reviewed, all discussions resolved

**Review by MarkusPettersson98 — DISMISSED** [review]
> Reviewed 1 of 8 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-tunnel-config-client/src/lib.rs` line 249 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158#-ODpt6qzAuTRTenOhGS5:-ODpt6qzAuTRTenOhGS6:b-qjdri8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7390f59bd6d0196b8479934acdaf2eaa3e79a2dd/talpid-tunnel-config-client/src/lib.rs#L249)):*
> ```XML
>         proto::DaitaPlatform::IosWgGo
>     }
> }
> ```

:pick: Consider re-writing this function using a combination of `const` and `if-else` in conjunction with `cfg!` instead. It will play nicer with people's editors, it is shorter and we can customize the compilation error message :blush:

```rust
const fn get_platform() -> proto::DaitaPlatform {
    use proto::DaitaPlatform;
    const PLATFORM: DaitaPlatform = if cfg!(windows) {
        DaitaPlatform::WindowsNative
    } else if cfg!(target_os = "linux") {
        DaitaPlatform::LinuxWgGo
    } else if cfg!(target_os = "macos") {
        DaitaPlatform::MacosWgGo
    } else if cfg!(target_os = "android") {
        DaitaPlatform::AndroidWgGo
    } else if cfg!(target_os = "ios") {
        DaitaPlatform::IosWgGo
    } else {
        panic!("This platform does not support DAITA V2!")
    };
    PLATFORM
}
```

Which results in the following compiler error if we try to compile the crate on a platform where `get_platform` is not implemented:
```bash
error[E0080]: evaluation of constant value failed
   --> talpid-tunnel-config-client/src/lib.rs:234:9
    |
234 |         panic!("This platform does not support DAITA V2!")
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'This platform does not support DAITA V2!', talpid-tunnel-config-client/src/lib.rs:234:9
    |
    = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
   --> talpid-tunnel-config-client/src/lib.rs:236:5
    |
236 |     PLATFORM
    |     ^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
error: could not compile `talpid-tunnel-config-client` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```



_Code quote:_
```XML
#[cfg(all(unix, not(target_os = "ios")))]
fn get_platform() -> proto::DaitaPlatform {
    #[cfg(windows)]
    {
        proto::DaitaPlatform::WindowsNative
    }

    #[cfg(target_os = "linux")]
    {
        proto::DaitaPlatform::LinuxWgGo
    }

    #[cfg(target_os = "macos")]
    {
        proto::DaitaPlatform::MacosWgGo
    }

    #[cfg(target_os = "android")]
    {
        proto::DaitaPlatform::AndroidWgGo
    }

    #[cfg(target_os = "ios")]
    {
        proto::DaitaPlatform::IosWgGo
    }
}
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158)* status: 17 of 20 files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`talpid-tunnel-config-client/src/lib.rs` line 249 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158#-ODpt6qzAuTRTenOhGS5:-ODqR2LAEb7_N4dv0GpO:bagrtdr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7390f59bd6d0196b8479934acdaf2eaa3e79a2dd/talpid-tunnel-config-client/src/lib.rs#L249)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: Consider re-writing this function using a combination of `const` and `if-else` in conjunction with `cfg!` instead. It will play nicer with people's editors, it is shorter and we can customize the compilation error message :blush:

```rust
const fn get_platform() -> proto::DaitaPlatform {
    use proto::DaitaPlatform;
    const PLATFORM: DaitaPlatform = if cfg!(windows) {
        DaitaPlatform::WindowsNative
    } else if cfg!(target_os = "linux") {
        DaitaPlatform::LinuxWgGo
    } else if cfg!(target_os = "macos") {
        DaitaPlatform::MacosWgGo
    } else if cfg!(target_os = "android") {
        DaitaPlatform::AndroidWgGo
    } else if cfg!(target_os = "ios") {
        DaitaPlatform::IosWgGo
    } else {
        panic!("This platform does not support DAITA V2!")
    };
    PLATFORM
}
```

Which results in the following compiler error if we try to compile the crate on a platform where `get_platform` is not implemented:
```bash
error[E0080]: evaluation of constant value failed
   --> talpid-tunnel-config-client/src/lib.rs:234:9
    |
234 |         panic!("This platform does not support DAITA V2!")
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'This platform does not support DAITA V2!', talpid-tunnel-config-client/src/lib.rs:234:9
    |
    = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
   --> talpid-tunnel-config-client/src/lib.rs:236:5
    |
236 |     PLATFORM
    |     ^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
error: could not compile `talpid-tunnel-config-client` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```
</blockquote></details>

Nice suggestion!

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
