### PR TITLE
Share endpoint data between all relays

### PR DESCRIPTION
**Pull request by dlon**
Essentially, this PR simplifies the structure of the relay list. All relays of a particular "type" are taken to have the same valid port ranges, transport protocols, etc. Aside from removing duplication and simplifying relay selection overall, this makes it easier to list or reject certain ports in frontends.

Changes overall:

* `RelayList` contains all of the shared endpoint data (valid ports, etc.) for each "types" (WireGuard, OpenVPN, or "bridge").
* Each `Relay` simply contains an enum value specifying the "relay type", and, optionally, data specific for that relay, such as the wg public key.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684)* status: 8 of 19 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`gui/src/main/daemon-rpc.ts` line 740 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684#-N6IUYks-H-Cf3SuzXgf:-N6IUYks-H-Cf3SuzXgg:bjq5eui) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/678cd9554691c2c261cafa603c0ad0281adb3a26/gui/src/main/daemon-rpc.ts#L740)):*
> ```XML
>   const protocolMap: Record<grpcTypes.Relay.RelayType, RelayEndpointType> = {
>     [grpcTypes.Relay.RelayType.OPENVPN]: 'openvpn',
>     [grpcTypes.Relay.RelayType.BRIDGE]: 'bridge',
> ```

Why are the keys within arrays here?
___
*[`mullvad-api/src/relay_list.rs` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684#-N6IVYkQ76SDiMvrfKCP:-N6IVYkQ76SDiMvrfKCQ:b-9s56pl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/678cd9554691c2c261cafa603c0ad0281adb3a26/mullvad-api/src/relay_list.rs#L111)):*
> ```XML
>         let openvpn = Self::add_openvpn_relays(&mut countries, openvpn);
>         let wireguard = Self::add_wireguard_relays(&mut countries, wireguard);
>         let bridge = Self::add_bridge_relays(&mut countries, bridge);
> ```

These functions might well be free standing and renamed to `extract_openvpn_relays` or be functions implemented _on_ the `OpenVpnEndpointData` and similar data types.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 5 of 13 files at r1, 2 of 7 files at r2, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-api/src/relay_list.rs` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684#-N6IVYkQ76SDiMvrfKCP:-N6N-8vX5HfGor4l3iCY:bz3wroq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/678cd9554691c2c261cafa603c0ad0281adb3a26/mullvad-api/src/relay_list.rs#L111)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Good idea. I implemented them on `OpenVpn` instead of `OpenVpnEndpointData`, etc. Do you think that this is good?
</blockquote></details>

Yep, looks better! It could also do with moving the method calls into the struct definition, so that the variables are not shadowed, if the lifetimes allow for it.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684)* status: 18 of 19 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[`mullvad-api/src/relay_list.rs` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684#-N6IVYkQ76SDiMvrfKCP:-N6NYq9oC_rA9RIcSOak:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/678cd9554691c2c261cafa603c0ad0281adb3a26/mullvad-api/src/relay_list.rs#L111)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yep, looks better! It could also do with moving the method calls into the struct definition, so that the variables are not shadowed, if the lifetimes allow for it.
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3684)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
