### PR TITLE
Update changelog and version

### PR DESCRIPTION
**Pull request by eriklarko**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/62)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62)*

**Comment by faern** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 31 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62#-L5NzfLLIHw7T0o-QcYi:-L5NzfLMNmnvxzHkzGz8:b51o311) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfaf93933e954ece3ff3dbe73ddfa4351ca1e117/CHANGELOG.md#L31)):*
> ```Markdown
> ### Security
> - Update the CRL with newly revoked server certificates.
> ```

There should be two empty lines between releases. To distinguish it from the space between headers within a release. Not a format requirement we have written down somewhere, but I have made sure we have kept it until now.

---

*[package.json, line 3 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62#-L5Nw9n9eTrH9ZeiLuNn:-L5Nw9n9eTrH9ZeiLuNo:bndf6k0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfaf93933e954ece3ff3dbe73ddfa4351ca1e117/package.json#L3)):*
> ```JSON
> {
>   "name": "mullvad-vpn",
>   "version": "2018.1.0-beta10",
> ```

This is the last time this should be bumped manually and in a PR like this. We have the script, `prepare_release.sh` in place to do exactly this for us. But since this version bump belongs to a branched off release that's in the past, compared to where master is now we have to do this one of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62)*

**Comment by eriklarko** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 31 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62#-L5NzfLLIHw7T0o-QcYi:-L5erbMgw8pHf5BGEzbd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfaf93933e954ece3ff3dbe73ddfa4351ca1e117/CHANGELOG.md#L31)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

There should be two empty lines between releases. To distinguish it from the space between headers within a release. Not a format requirement we have written down somewhere, but I have made sure we have kept it until now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/62#-:-L5ezrYe_7w0D00banmD:bnfp4nl)*

**Pull request closed without merging**
