### PR TITLE
Add problem report

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Add view controller for problem report input and review controller for previewing the logs.
1. Add `ConsolidatedApplicationLog` to form the body of the problem report.
1. Add `CustomNavigationController` subclass of `UINavigationController` that intercepts the "Back" button _and_ pop gesture (swipe back) in navigation controllers and enables the subclasses to prevent the controller from being dismissed.
1. Add `StatusImageView` to categorise the common images used for indicating the status of Login & Problem report submission.
1. Extract Objective-C method swizzling into a shared helper

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 0 of 22 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/CustomNavigationController.swift, line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MU87eGtAZ3H7UIFuK7m:-MU87eGtAZ3H7UIFuK7n:bcxz6pa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3dada60a19bb1d633f9103d2bee692e81c1a9d2f/ios/MullvadVPN/CustomNavigationController.swift#L38)):*
> ```Swift
>         _ = Self.classInit
> 
>         popGestureRecognizerDelegate = CustomPopGestureRecognizerDelegate(navigationController: self, systemGestureRecognizerDelegate: interactivePopGestureRecognizer?.delegate)
> ```

FYI This just adds the interstitial delegate that proxies all of the delegate calls to the system delegate, however intercepts a few others to adjust the gesture recogniser behaviour 
___
*[ios/MullvadVPN/CustomNavigationController.swift, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MU87t_U0vv0I9hpaq6z:-MU87t_U0vv0I9hpaq7-:bgqoila) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3dada60a19bb1d633f9103d2bee692e81c1a9d2f/ios/MullvadVPN/CustomNavigationController.swift#L79)):*
> ```Swift
>     }
> 
>     override func forwardingTarget(for aSelector: Selector!) -> Any? {
> ```

FYI basically leveraging the Objective-C runtime message forwarding here and forward all of the calls to the system delegate, however intercept `gestureRecognizerShouldBegin()` to customise when the gesture recogniser is allowed to start gesture recognition.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 0 of 22 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/CustomNavigationController.swift, line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MU89FgC07NCvgfFW3Ot:-MU89FgDC08hxgfh8Pbo:b-wn6ots) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3dada60a19bb1d633f9103d2bee692e81c1a9d2f/ios/MullvadVPN/CustomNavigationController.swift#L26)):*
> ```Swift
>         swizzleMethod(
>             aClass: CustomNavigationController.self,
>             originalSelector: #selector(UINavigationBarDelegate.navigationBar(_:shouldPop:)),
> ```

FYI Although `UINavigationController` implements `UINavigationBarDelegate`, there is no way to properly override the delegate methods in Swift due to some weird name collision bug in Swift, reported here: https://bugs.swift.org/browse/SR-13788

So I use swizzling in order to be able to call the `super` implementation.

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 10 of 22 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 12 of 24 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/NSRegularExpression+IPAddress.swift, line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUAp88xBCMFLHrNPaRp:-MUAp88xBCMFLHrNPaRq:b-8u4p6e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/NSRegularExpression+IPAddress.swift#L48)):*
> ```Swift
>             (25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])           # 2001:db8:3:4::192.0.2.33  64:ff9b::192.0.2.33 (IPv4-Embedded IPv6 Address)
>             )
>         """#
> ```

I don't mind using regular expressions, but isn't there some Swift library that does the validation already?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 12 of 24 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/MullvadVPN/NSRegularExpression+IPAddress.swift, line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUAp88xBCMFLHrNPaRp:-MUDIu3f7n2RSe5XHBGT:bn4oqhu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/NSRegularExpression+IPAddress.swift#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I don't mind using regular expressions, but isn't there some Swift library that does the validation already?
</blockquote></details>

It's not for validation but for replacing IPs in the problem reports.

**Review by jvff — COMMENTED** [review]
> Reviewed 5 of 22 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 18 of 24 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/NSRegularExpression+IPAddress.swift, line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUEHWt-0TRg094KM1k_:-MUEHWt-0TRg094KM1ka:bcjixaa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/NSRegularExpression+IPAddress.swift#L40)):*
> ```Swift
>             [0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|       # 1::3:4:5:6:7:8   1::3:4:5:6:7:8  1::8
>             :((:[0-9a-fA-F]{1,4}){1,7}|:)|                     # ::2:3:4:5:6:7:8  ::2:3:4:5:6:7:8 ::8       ::
>             fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|     # fe80::7:8%eth0   fe80::7:8%1     (link-local IPv6 addresses with zone index)
> ```

FYI: Just a warning, this line matches `fe80::::%eth0`, which AFAICT is invalid. Not an issue here, because it will just redact something that's an invalid address, but still good to be aware.
___
*[ios/MullvadVPN/SettingsViewController.swift, line 167 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUEx_piBH-VfFCDOoc4:-MUEx_pjEEscgF_unXuA:b-v19mn6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/SettingsViewController.swift#L167)):*
> ```Swift
>         let bottomSection = StaticTableViewSection()
> 
>         let problemReportRow = StaticTableViewRow(reuseIdentifier: CellIdentifier.basicCell.rawValue) { (indexPath, cell) in
> ```

Nit: `indexPath` isn't used, right? Does it make sense to make it `_` so that it's the same as the `versionRow` declaration?

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 3 of 22 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 23 of 24 files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/CustomNavigationController.swift, line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUFDWUUBBInn6fAYsxA:-MUFDWUW2jfPjKhmngab:b8aou71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/CustomNavigationController.swift#L54)):*
> ```Swift
>         if shouldPop {
>             // Call super implementation
>             return customNavigationController_navigationBar(navigationBar, shouldPop: item)
> ```

Just to make sure I understood: this would normally lead to a recursive call, but since the methods were swapped, it actually calls the original method (i.e., the implementation in the super class) instead. Is this correct?
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUFlmbZA1gK6fBFHRkE:-MUFlmb_7aW2NaL_eD3B:bfh72jp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L46)):*
> ```Swift
>                     let emailText = String(format: NSLocalizedString("If needed we will contact you on %@", comment: ""), email)
>                     let emailAttributedString = NSMutableAttributedString(string: emailText)
>                     if let emailRange = emailText.range(of: email) {
> ```

Just a funny thought I had: if the user types `If needed` or something from the label as the email address, it will highlight the wrong part :joy: But I don't think there's an easy solution for this, and this is barely an issue.
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 108 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGJnxEEZW3bwEMo9BZ:-MUGJnxFAtSZ3dMsu4va:b-68xkci) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L108)):*
> ```Swift
>         button.translatesAutoresizingMaskIntoConstraints = false
>         button.setTitle(NSLocalizedString("Edit message", comment: ""), for: .normal)
>         button.addTarget(self, action: #selector(handleEditButton), for: .touchUpInside)
> ```

This might be a silly question, but does handling `.touchUpInside` mean that one can press down somewhere else, slide and release over the button and it will execute the action?
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 135 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGPDHh7gHdR-gkwM7o:-MUGPDHj1MxhKhCTv7iH:b-5fdx1p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L135)):*
> ```Swift
>     private func addSubviews() {
>         // Add a spacer view that's used to push the bodyLabel from the bottom when buttons stack
>         // when it's not visible.
> ```

This comment is a bit confusing due to the two `when`s.
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 169 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGT0m_91W9dgtY4awc:-MUGT0m_91W9dgtY4awd:benblf9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L169)):*
> ```Swift
>             spacerView.leadingAnchor.constraint(equalTo: layoutMarginsGuide.leadingAnchor),
>             spacerView.trailingAnchor.constraint(equalTo: layoutMarginsGuide.trailingAnchor),
>             spacerView.bottomAnchor.constraint(equalTo: layoutMarginsGuide.bottomAnchor),
> ```

Souldn't this be `equalTo: buttonStackView.topAnchor`?

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: all files reviewed, 8 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 291 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGjCk88zAwpVWu8cD4:-MUGjCkAA_Id0wIq6n3l:bp2l3j3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L291)):*
> ```Swift
>         let nextButton: UIBarButtonItem
> 
>         if #available(iOS 13, *) {
> ```

Nit: Just an idea, but would it make sense to create a `makeKeyboardNavigationItem` helper, so that this method calls it twice (once for each item)? The main idea would be to reduce a bit the repeated code.
___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 384 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmnW_4vxzCB3L4S0-:-MUGmnW_4vxzCB3L4S00:b-r3u5du) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L384)):*
> ```Swift
> 
>             // Move the text view above scroll view
>             view.addSubview(self.messageTextView)
> ```

Don't you have to remove the view from `textFieldsHolder`? Or does adding it to another parent remove it from it's previous parent?
___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 386 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmTisAMU_imD_P2jx:-MUGmTisAMU_imD_P2jy:b-3omnb4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L386)):*
> ```Swift
>             view.addSubview(self.messageTextView)
> 
>             // Re-add old constraints
> ```

Why is re-adding the old constraints necessary?

**Comment by axti** [comment]
@pronebird what do you think about splitting this PR?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: all files reviewed, 8 unresolved discussions (waiting on @jvff and @pronebird)

___
*[ios/MullvadVPN/CustomNavigationController.swift, line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUFDWUUBBInn6fAYsxA:-MUITobm5Jm_9muDd-NY:b-yhawx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/CustomNavigationController.swift#L54)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Just to make sure I understood: this would normally lead to a recursive call, but since the methods were swapped, it actually calls the original method (i.e., the implementation in the super class) instead. Is this correct?
</blockquote></details>

That's correct. Weird world of method swizzling in Objective-c. Wish I could avoid that mess, but sometimes it's a necessary evil to patch a few things up.
___
*[ios/MullvadVPN/NSRegularExpression+IPAddress.swift, line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUEHWt-0TRg094KM1k_:-MUIUuPT4T5zJ4sb1rPq:b-rnhblc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/NSRegularExpression+IPAddress.swift#L40)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

FYI: Just a warning, this line matches `fe80::::%eth0`, which AFAICT is invalid. Not an issue here, because it will just redact something that's an invalid address, but still good to be aware.
</blockquote></details>

Probably yeah. We have the same regex in mullvad-problem-report so at least we will be consistent in our mistakes
https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-problem-report/src/lib.rs#L504
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUFlmbZA1gK6fBFHRkE:-MUIV_8U7Q_OBVjHYCZ0:b-1qdgq8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L46)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Just a funny thought I had: if the user types `If needed` or something from the label as the email address, it will highlight the wrong part :joy: But I don't think there's an easy solution for this, and this is barely an issue.
</blockquote></details>

You're right. It's possible to deface the displayed message this way. But there is no easy fix for that as attributed strings do not support formatting. I think we should just ignore this issue for now.
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 108 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGJnxEEZW3bwEMo9BZ:-MUIXUud5WiWOXc2_HlU:bsl2m9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L108)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This might be a silly question, but does handling `.touchUpInside` mean that one can press down somewhere else, slide and release over the button and it will execute the action?
</blockquote></details>

`.touchUpInside` means the touch was released within the bounds of the control. If you touch then slide then the action won't be registered. This is a fairly standard way of handling button touches on iOS.
___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 135 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGPDHh7gHdR-gkwM7o:-MUIYKjdDKRKPvNhmnsu:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L135)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This comment is a bit confusing due to the two `when`s.
</blockquote></details>

Fixed.
___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 291 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGjCk88zAwpVWu8cD4:-MUIg5Sj-s46_v-2X8US:bhctgy7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L291)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Just an idea, but would it make sense to create a `makeKeyboardNavigationItem` helper, so that this method calls it twice (once for each item)? The main idea would be to reduce a bit the repeated code.
</blockquote></details>

Good idea! Moved this into a separate extension on `UIBarButtonItem` as I believe we may use it in other views too in the future.
___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 384 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmnW_4vxzCB3L4S0-:-MUIo4JG5D0KdPcLrHCz:bji5d7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L384)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Don't you have to remove the view from `textFieldsHolder`? Or does adding it to another parent remove it from it's previous parent?
</blockquote></details>

Yes. It's automatically removed from the active parent view when reparenting.
___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 386 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmTisAMU_imD_P2jx:-MUIoHc41ODAswTh1L3-:bb6lbdj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L386)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Why is re-adding the old constraints necessary?
</blockquote></details>

The constraints are automatically removed when the view is being removed from its parent or being re-parented.

In order to maintain the same visual position on screen, it's necessary to re-add the old constraints after re-parenting the view.
___
*[ios/MullvadVPN/SettingsViewController.swift, line 167 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUEx_piBH-VfFCDOoc4:-MUIt0lqEMD1GGdOO9t4:b-bnmi93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/SettingsViewController.swift#L167)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: `indexPath` isn't used, right? Does it make sense to make it `_` so that it's the same as the `versionRow` declaration?
</blockquote></details>

TBH very often Xcode pre-fills the arguments during auto-completion. I am not very hard on unused variables in Swift as it's usually more work to fight Xcode.

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 22 of 25 files reviewed, 3 unresolved discussions (waiting on @jvff and @pronebird)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 21 of 25 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift, line 169 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGT0m_91W9dgtY4awc:-MUItxme9SeTxZUVeNBW:b-okii7p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift#L169)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Souldn't this be `equalTo: buttonStackView.topAnchor`?
</blockquote></details>

Actually, I realised that we don't need it. So I removed it!

**Review by pronebird — COMMENTED** [review]
@axti the PR is already reviewed, so even if there is some sense in doing so, I think it's a little too late for that.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-:-MUIyKVrAsj7DlcExdzv:b-uvfiwl)* status: 21 of 25 files reviewed, 3 unresolved discussions (waiting on @jvff)

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 386 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmTisAMU_imD_P2jx:-MUIyaMh7Jy1U1sGjHbG:by18ri5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L386)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The constraints are automatically removed when the view is being removed from its parent or being re-parented.

In order to maintain the same visual position on screen, it's necessary to re-add the old constraints after re-parenting the view.
</blockquote></details>

So, this is for properly animating from the old position (not-expanded) to the new position (expanded) while having a different parent during the animation, right?

Should this be done when collapsing from expanded to "normal" state as well?
___
*[ios/MullvadVPN/UIBarButtonItem+KeyboardNavigation.swift, line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUIyGBGCoGYmGMWYXSk:-MUIyGBGCoGYmGMWYXSl:bpyrpxt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd5a48283a5fb736204c82776ae9cfdf863264c8/ios/MullvadVPN/UIBarButtonItem+KeyboardNavigation.swift#L53)):*
> ```Swift
>             spacer.width = 8
> 
>             configurationBlock(prevButton, nextButton)
> ```

Shouldn't this call be made outside the `if #available(iOS 13, *)`?

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 23 of 25 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 386 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmTisAMU_imD_P2jx:-MUJBrX92WX2Ms3kkhwk:b-24cc92) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L386)):*
> So, this is for properly animating from the old position (not-expanded) to the new position (expanded) while having a different parent during the animation, right?

Correct

> Should this be done when collapsing from expanded to "normal" state as well?

When going expanded -> collapsed, reparenting happens in reverse, i.e after animations. It makes sense because we don't want to explore the scrollable area. It also seems that we don't have to re-activate constraints twice in that case as based on UI debugger, the constraints remain active after moving sub-view down the tree.
___
*[ios/MullvadVPN/UIBarButtonItem+KeyboardNavigation.swift, line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUIyGBGCoGYmGMWYXSk:-MUJDQj4BY6EKMaM8L_a:bsf3kxl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd5a48283a5fb736204c82776ae9cfdf863264c8/ios/MullvadVPN/UIBarButtonItem+KeyboardNavigation.swift#L53)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Shouldn't this call be made outside the `if #available(iOS 13, *)`?
</blockquote></details>

Glad to have you reviewing this code. Thanks for catching this. Fixed.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497)* status: 23 of 25 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/ProblemReportViewController.swift, line 386 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-MUGmTisAMU_imD_P2jx:-MUJDaRU2hTBu1vXYKEv:b-y7p0dy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7a4c788be304d283eeab407214e54e433ce548/ios/MullvadVPN/ProblemReportViewController.swift#L386)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

> So, this is for properly animating from the old position (not-expanded) to the new position (expanded) while having a different parent during the animation, right?

Correct

> Should this be done when collapsing from expanded to "normal" state as well?

When going expanded -> collapsed, reparenting happens in reverse, i.e after animations. It makes sense because we don't want to explore the scrollable area. It also seems that we don't have to re-activate constraints twice in that case as based on UI debugger, the constraints remain active after moving sub-view down the tree.
</blockquote></details>

typo: /explore/explode/

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2497#-:-MUJFux09DZfbhVNc70b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
