### PR TITLE
Add iOS test verifying API can be reached in blocked state

### PR DESCRIPTION
**Pull request by niklasberglund**
Implemented test verifying that API can still be reached when the app is in blocked state. A change affected the screenshot test so did a tiny modification of it as well.

To test the changes in this PR run `testAPIReachableWhenBlocked` under `ConnectivityTests`. Also `testScreenshots` was affected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)

### CODE REVIEW

**Review by acb-mv — COMMENTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Pages/AccountPage.swift` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw4LGl33gRSg-q-eAnK:-Nw4LGl33gRSg-q-eAnL:bq0oorp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/Pages/AccountPage.swift#L49)):*
> ```Swift
>         guard let deviceName = deviceNameLabel.value as? String else {
>             XCTFail("Failed to read device name from label")
>             return String()
> ```

Is returning an empty String a common pattern in our codebase? To me, using an in-band value to represent out-of-band conditions feels like a code smell, and using a `String?` would be better. Are there ergonomic reasons for doing it this way?

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @acb-mv and @niklasberglund)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9JIul53YkETMMn3o1:-Nw9JIul53YkETMMn3o2:b6a5o54) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPN/View%20controllers/Settings/SettingsHeaderView.swift#L34)):*
> ```Swift
>     let collapseButton: UIButton = {
>         let button = UIButton(type: .custom)
>         button.accessibilityIdentifier = .expandButton
> ```

Why change it to `expandButton` if its default position is `collapsed` ?
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9JyY91GRY7hntrX0M:-Nw9JyY91GRY7hntrX0N:b-jshwwp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L49)):*
> ```Swift
>     }
> 
>     /// Get the app into a blocked state by connecting to a relay then applying a filter which don't find this relay, then verify that app can still communicate by logging out and verifying that the device was successfully removed
> ```

nit
I'm surprised the comment length didn't trigger any linter violation :thinking: 
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9JjRh5EssyQLjVIxH:-Nw9JjRh5EssyQLjVIxI:b-i0tujk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L65)):*
> ```Swift
>             .tapApplyButton()
> 
>         // Select the first country, it's first city and it's first relay
> ```

nit
`its` instead of `it's` (the city / relay belongs to the parent item)
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9KIa68HtQ4x8h_xMQ:-Nw9KIa771znoqusaYlW:bo3at6k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L67)):*
> ```Swift
>         // Select the first country, it's first city and it's first relay
>         SelectLocationPage(app)
>             .tapCountryLocationCellExpandButton(withIndex: 0)
> ```

nit
while it's rather unlikely to happen, we should probably have some logic to guarantee we don't select a relay that's deactivated
___
*[`ios/MullvadVPNUITests/Pages/AccountPage.swift` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw4LGl33gRSg-q-eAnK:-Nw9KgdA450au62vnR22:b4hwnn1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/Pages/AccountPage.swift#L49)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Is returning an empty String a common pattern in our codebase? To me, using an in-band value to represent out-of-band conditions feels like a code smell, and using a `String?` would be better. Are there ergonomic reasons for doing it this way?
</blockquote></details>

@acb-mv I think the return value here is just to satisfy the compiler since we mandate returning a string.
The execution of the test won't continue after this failure. 

That being said, we can improve this function like so (and we can even include a custom error message if we want to be explicit about failure)
```swift
    func getDeviceName() throws -> String {
        let deviceNameLabel = app.otherElements[AccessibilityIdentifier.accountPageDeviceNameLabel]
        return try XCTUnwrap(deviceNameLabel.value as? String)
    }
```

**Review by acb-mv — COMMENTED** [review]
> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: all files reviewed, 5 unresolved discussions (waiting on @niklasberglund)

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9JIul53YkETMMn3o1:-NwJIgn41-IR_g38_ewX:bclkb7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPN/View%20controllers/Settings/SettingsHeaderView.swift#L34)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why change it to `expandButton` if its default position is `collapsed` ?
</blockquote></details>

If it's in a collapsed state then the button will expand its content
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9JyY91GRY7hntrX0M:-NwJIpFhEcItx5YVkAoY:b6k8ys0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L49)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I'm surprised the comment length didn't trigger any linter violation :thinking:
</blockquote></details>

Me too!
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9JjRh5EssyQLjVIxH:-NwJZSHIDezHuWZnLIj2:b-1wlver) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L65)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
`its` instead of `it's` (the city / relay belongs to the parent item)
</blockquote></details>

Haha, to this day I thought "its" and "it's" was the other way around so I've been using them the wrong way most of the time 😄
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9KIa68HtQ4x8h_xMQ:-NwJYpBE68fDEvVT2HUA:b-kcboz1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L67)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
while it's rather unlikely to happen, we should probably have some logic to guarantee we don't select a relay that's deactivated
</blockquote></details>

Yes probably. This applies to other tests also. Been intentionally ignoring this flaw but maybe shouldn't for too long.
___
*[`ios/MullvadVPNUITests/Pages/AccountPage.swift` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw4LGl33gRSg-q-eAnK:-NwJXiDTB71hapzCL_Jz:b-lce9jc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/Pages/AccountPage.swift#L49)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

@acb-mv I think the return value here is just to satisfy the compiler since we mandate returning a string.
The execution of the test won't continue after this failure. 

That being said, we can improve this function like so (and we can even include a custom error message if we want to be explicit about failure)
```swift
    func getDeviceName() throws -> String {
        let deviceNameLabel = app.otherElements[AccessibilityIdentifier.accountPageDeviceNameLabel]
        return try XCTUnwrap(deviceNameLabel.value as? String)
    }
```
</blockquote></details>

Yes exactly - don't want to return an optional here because it adds complexity without improving anything because the test has already failed and we're not trying to recover from being unable to read device name. I really should be using `XCTUnrwap` more. It's a good improvement, have implemented it 👍

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-Nw9KIa68HtQ4x8h_xMQ:-NwOWR9N5zZJzqjTTxi1:b-5hvr7o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/816e01cebbe7d692fb2a59694e7788d4cf3303b3/ios/MullvadVPNUITests/ConnectivityTests.swift#L67)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Yes probably. This applies to other tests also. Been intentionally ignoring this flaw but maybe shouldn't for too long.
</blockquote></details>

Created a Linear ticket for this https://linear.app/mullvad/issue/IOS-654/handle-servers-being-down-in-end-to-end-tests

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154#-:-NxCWjnD2lG0Ir0KqHEA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)

**Review by buggmagnet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

**Review by acb-mv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by acb-mv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
