### PR TITLE
Clarify things in the changelog and clean up obsolete entries

### PR DESCRIPTION
**Pull request by faern**
Making some clarifications and cleanups to the changelog prior release. Some entries have been made obsolete by other later changes. Some entries I thought could simply be made a bit clearer, or were better suited for another category of changes.

But you know more about the details of the changes than me. So double check my changes and give feedback!

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318#-:-MNOsByp8INU97B_DS2D:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318#-:-MNOt-aO1UU3rQII4WuF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CHANGELOG.md, line 104 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318#-MNOt2HXCifbRmZE_1sR:-MNOt2HYDskmBEv_bF2w:b-82jztw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/440b30cee60d57f4d3df53ca24a973ac94517295/CHANGELOG.md#L104)):*
> ```Markdown
>   non-tunnel interface.
> - Fix issues managing DNS when dnsmasq is used with NetworkManager.
> - Fix issues with managing kernel WireGuard device via NetworkManager
> ```

There's a `.` missing at the end of this line.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318#-:-MNOwBI0Aygppzdn9dlh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
