### PR TITLE
Remove Split tunneling disabled description

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060#-NudPFtO8bdsizIPDNOT:-NudPFtO8bdsizIPDNOU:b-7xy92x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f033728652d596637253e5ed4f7155a73be1b6a8/android/lib/resource/src/main/res/values/strings.xml#L158)):*
> ```XML
>     <string name="select_location_description">While connected, your real location is masked with a private and secure location in the selected region.</string>
>     <string name="split_tunneling_description">Lets you select apps that should access the Internet directly without going through the VPN tunnel.</string>
>     <string name="split_tunneling_description_warning">Attention: Split tunneling is a privacy risk.</string>
> ```

We should make sure this doesn't get translated.



_Code quote:_
```XML
Split tunneling
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060#-NudPFtO8bdsizIPDNOT:-Nuxme3eEVHcBXzglM3h:b6t38p5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f033728652d596637253e5ed4f7155a73be1b6a8/android/lib/resource/src/main/res/values/strings.xml#L158)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We should make sure this doesn't get translated.
</blockquote></details>

After internal discussion we have decided on try and fix directly on crowdin

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 21 of 22 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060#-:-Nv0wIbqAVceIPjjPeLj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 21 of 22 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060#-:-Nv18EAXAPVRr10FKnNe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
