### PR TITLE
Format desktop translations with HTML

### PR DESCRIPTION
**Pull request by raksooo**
This PR changes the format for desktop translations from markdown to HTML. Currently we only support the `<b></b>` tag. Additionally I've:
- Updated the log out string on Android.
- Added HTML validity check to translations verification script.
- Moved logic for verifying translations to `script/localization` to make it possible to run locally.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 45 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066)* status: 45 of 46 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`scripts/localization` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066#-NEo9qesBrnH_TvUTzxx:-NEo9qesBrnH_TvUTzxy:bo42fi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85bb9567ada7aa34c93078a6fb633bab68687668/scripts/localization#L18)):*
> ```
>         verify) verify;;
>         "")
>             echo "Available subcommands: prepare, upload, download and sync-local-files"
> ```

Add `verify` here and mention in the translation readme.



_Code quote:_
```
Available subcommands
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066)* status: 44 of 46 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`scripts/localization` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066#-NEo9qesBrnH_TvUTzxx:-NEoO8oJ6-_ulcu7507-:b4855pb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85bb9567ada7aa34c93078a6fb633bab68687668/scripts/localization#L18)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Add `verify` here and mention in the translation readme.
</blockquote></details>

Thanks! Done.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066)* status: 45 of 46 files reviewed, all discussions resolved

___
*[`scripts/localization` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066#-NEo9qesBrnH_TvUTzxx:-NEoRUXB5G6RIshFs48V:b-fg7aqo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85bb9567ada7aa34c93078a6fb633bab68687668/scripts/localization#L18)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Thanks! Done.
</blockquote></details>

Perhaps also mention in the README where the other subcommands are explained? :slightly_smiling_face: 

https://github.com/mullvad/mullvadvpn-app/blob/master/gui/locales/README.md

**Review by hankolsen — APPROVED** [review]
> Reviewed 1 of 46 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`scripts/localization` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066#-NEo9qesBrnH_TvUTzxx:-NEtUpxU-76MA9wPqsuc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85bb9567ada7aa34c93078a6fb633bab68687668/scripts/localization#L18)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps also mention in the README where the other subcommands are explained? :slightly_smiling_face: 

https://github.com/mullvad/mullvadvpn-app/blob/master/gui/locales/README.md
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4066#-:-NEtUx2WAGDP1Ynq4nWM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
