### PR TITLE
Add UI for DAITA in VPN settings

### PR DESCRIPTION
**Pull request by mojganii**
This PR introduces the ability to toggle `Daita` in settings:
<table width = "200">
  <tr>
    <th>before</th>
    <th>after</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
</table>

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667)

### CODE REVIEW

**Review by rablador — DISMISSED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 643 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5DTg5JAqEuBGtZgenB:-O5DTg5JAqEuBGtZgenC:bud7x44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L643)):*
> ```Swift
>             } onDiscard: { [weak self] in
>                 guard let self else { return }
>                 tableView?.reloadData()
> ```

Why do we need to manually reload the tableView here?
___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 449 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5DXCxw7fIqJHvzrA0X:-O5DXCxw7fIqJHvzrA0Y:b-ncbhhd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L449)):*
> ```Swift
>         await fulfillment(of: [stopMonitorExpectation], timeout: .UnitTest.timeout)
>     }
> ```

Leftover?

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 192 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5IH0bKBA7oZ-nHxWZx:-O5IH0bKBA7oZ-nHxWZy:b-ajkl5u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L192)):*
> ```Swift
>             tableName: "DAITA",
>             value: """
>             DAITA (Defence against AI-guided Traffic Analysis) hides patterns in your encrypted VPN traffic.\
> ```


The text needs some spaces here and there.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 235 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5IHh6PCP-89xEVPLT6:-O5IHh6PCP-89xEVPLT7:b95euhk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L235)):*
> ```Swift
>                     tableName: "DAITA",
>                     value: """
>                     This feature isn't available on all servers.\
> ```


Same here, the text needs some extra spaces 
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5IICKrAmNq0H-IWoFF:-O5IICKrAmNq0H-IWoFG:bby3pkr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L107)):*
> ```Swift
>             keyPolicy: connState.keyPolicy,
>             networkReachability: connState.networkReachability,
>             recoveryTask: startRecoveryTaskIfNeeded(reason: reason),
> ```

Why are we adding this here ?

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 643 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5DTg5JAqEuBGtZgenB:-O5Mrsdz97cUhoP4rNKk:ba3txgu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L643)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we need to manually reload the tableView here?
</blockquote></details>

To turn the `toggle` off if user taps `back` button in the dialog.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 192 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5IH0bKBA7oZ-nHxWZx:-O5Mt0ok4D4jr7_lJWYu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L192)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>


The text needs some spaces here and there.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 235 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5IHh6PCP-89xEVPLT6:-O5Mt1b7EBNLk2wvev5A:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L235)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>


Same here, the text needs some extra spaces
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5IICKrAmNq0H-IWoFF:-O5Mt4Je4LsLf2xU6ejR:bk2hd8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L107)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why are we adding this here ?
</blockquote></details>

the branch must be rebased with `main`. now it's updated and resolved
___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 449 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-O5DXCxw7fIqJHvzrA0X:-O5MtWRvCwZSjx-YWDtR:bths9hg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/488c8d4445eea1f4036d9c19879b34ef0c4ae226/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L449)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Leftover?
</blockquote></details>

Solved.

**Review by buggmagnet — APPROVED** [review]
Dismissing @rablador so we can merge the PR as all his claims have been adressed

> Dismissed @rablador from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667#-:-O5NwXk53t4-Hb1v6eLJ:b-qfvi4)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
