### PR TITLE
Send API address to TSM directly

### PR DESCRIPTION
**Pull request by pinkisemils**
The daemon can get into a deadlock if it's _awaiting_ on a response from the REST service if the REST service needs to rotate to a new API address. I've fixed this by bypassing the daemon in the change handler for the address cache and just sending the new API IP over to the TSM directly.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 513 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWCUDT14yTj7h_rZ29:-MRWCUDU4VmiB7a6cPRh:b-1lqpf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L513)):*
> ```Rust
>                     );
>                     let _ = tx.send(tunnel_command).await;
>                     result_rx.await.map_err(|_| ())
> ```

This will block forever if `tx.send` fails.
___
*[mullvad-daemon/src/lib.rs, line 621 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWC_1u3oKGoDI1_Hjk:-MRWC_1u3oKGoDI1_Hjl:bjx4812) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L621)):*
> ```Rust
>         let tsm_api_address_change_tx = Arc::downgrade(&tunnel_command_tx);
>         tokio::spawn(async move {
>             while let Some(address_change) = address_change_rx.next().await {
> ```

Not blocking: This task doesn't seem to stop on its own.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 513 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWCUDT14yTj7h_rZ29:-MRZPEAw3OckXg4o_Izn:b-hmqjus) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L513)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This will block forever if `tx.send` fails.
</blockquote></details>

Scratch that. This is fine.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 513 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWCUDT14yTj7h_rZ29:-MRZTiL21zTBZuNPmvPR:bj6h8js) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L513)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Scratch that. This is fine.
</blockquote></details>

I think the issue is that the callback is not synchronous. I'll make it return a boxed future instead.
___
*[mullvad-daemon/src/lib.rs, line 621 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWC_1u3oKGoDI1_Hjk:-MRZS_IW2ss84RykKvF6:b-irohyo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L621)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not blocking: This task doesn't seem to stop on its own.
</blockquote></details>

`address_change_rx` should receive a `None` when `address_change_tx` is received. It also stops if the address change fails to get sent.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 513 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWCUDT14yTj7h_rZ29:-MRZb-AW9-XPZ5aJvVlV:b-hu9vr2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L513)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think the issue is that the callback is not synchronous. I'll make it return a boxed future instead.
</blockquote></details>

Err, making it asynchronous is very hard because of the mutex. I think I'll leave this as is.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 621 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404#-MRWC_1u3oKGoDI1_Hjk:-MRZWN4i0Vkbd_ILdxpi:b-ihui2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b904f6a754ef8bc3a051f8874ff630a73ea2574f/mullvad-daemon/src/lib.rs#L621)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`address_change_rx` should receive a `None` when `address_change_tx` is received. It also stops if the address change fails to get sent. 
</blockquote></details>

It seems `address_change_tx` is not being dropped then, for whatever reason.

**Pull request merged**
