### PR TITLE
Add konsist tests

### PR DESCRIPTION
**Pull request by Rawa**
This PR adds a bunch of konsist test to ensure we adhere to nice code standards.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
> Reviewed 32 of 33 files at r1, 42 of 43 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 33 of 43 files at r2, 2 of 3 files at r4, 35 of 35 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214)* status: 75 of 76 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ArchitectureTests.kt` line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-NfkPdgk9b1ID02Yyku2:-NfkPdgk9b1ID02Yyku3:b6mm2g0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14040bed47d5b2fba560e0f4e840cd50304415e8/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ArchitectureTests.kt#L11)):*
> ```Kotlin
> 
>     @Test
>     fun `domain layer depends on nothing`() {
> ```

I believe we should to refer to these as model(s) (or perhaps combine it somehow with "domain") until we've settled on a architectural long-term plan



_Code quote:_
```Kotlin
domain
```
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/GeneralTests.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-NfkOpKoDEQYV3CZn2fJ:-NfkOpKoDEQYV3CZn2fK:bwuri6t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14040bed47d5b2fba560e0f4e840cd50304415e8/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/GeneralTests.kt#L12)):*
> ```Kotlin
>     @Test
>     fun `package name must match file path`() {
>         Konsist.scopeFromProject().packages.assert { it.hasMatchingPath }
> ```

Replace with the existing `projectScope()` extension. The same applies to the other test functions in this class



_Code quote:_
```Kotlin
Konsist.scopeFromProject()
```
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/extensions/KonsistExtensions.kt` line 1 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-NfkP-OP-OLHTz2_KMGa:-NfkP-OQ1G1aovdAoHkN:b-r98un5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14040bed47d5b2fba560e0f4e840cd50304415e8/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/extensions/KonsistExtensions.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.test.arch.extensions
> ```

I'm not sure whether this file is necessary or not. I believe it would be easiest to understand the code if we add all/most of the scope calls or none of them here to avoid a mix. Perhaps we can discuss this further outside of GH/Reviewable.

**Review by sabercodic — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 15 of 35 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214)* status: 63 of 76 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @sabercodic)

___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ArchitectureTests.kt` line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-NfkPdgk9b1ID02Yyku2:-NfkbLnh7yZpPKd8c5DV:b-orumjy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14040bed47d5b2fba560e0f4e840cd50304415e8/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ArchitectureTests.kt#L11)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we should to refer to these as model(s) (or perhaps combine it somehow with "domain") until we've settled on a architectural long-term plan
</blockquote></details>

Good point
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/GeneralTests.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-NfkOpKoDEQYV3CZn2fJ:-NfkbQR27_2XTNkdlsA5:b-2xl0f3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14040bed47d5b2fba560e0f4e840cd50304415e8/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/GeneralTests.kt#L12)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Replace with the existing `projectScope()` extension. The same applies to the other test functions in this class
</blockquote></details>

Aligned all tests
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/extensions/KonsistExtensions.kt` line 1 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-NfkP-OP-OLHTz2_KMGa:-NfkbWi8DmL3QF8UciLR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14040bed47d5b2fba560e0f4e840cd50304415e8/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/extensions/KonsistExtensions.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm not sure whether this file is necessary or not. I believe it would be easiest to understand the code if we add all/most of the scope calls or none of them here to avoid a mix. Perhaps we can discuss this further outside of GH/Reviewable.
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 43 files at r2, 1 of 3 files at r4, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214#-:-Nfkcsqs96mBS1MmHgoF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5214)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
