### PR TITLE
Investigate crash in DiffableDataSource

### PR DESCRIPTION
**Pull request by mojganii**
This PR fixes the carsh we have on UITableViewDiffableDataSource.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
Is there any way we  can unit test concurrent updates? Spawn two queues, both thrashing their own updates to the data source?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBCFqrL9Uj1YU5POG4Q:bdyen34)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBCFQK480rAG3w0zdJG:-OBCFQK480rAG3w0zdJH:bnnyih4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70b7f8c909098159fe029eec06c9d19b79c86d25/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L13)):*
> ```Swift
> import MullvadTypes
> import UIKit
> ```

How did this file ever work without having these imports?
Also, _are we_ using Combine here? I can't identify anything Combine specific in the changes here, and I was under the impression we were not using Combine anywhere in our code.

**Review by rablador — APPROVED** [review]
The crash seems to be fixed! I have found two other things though:

1. When first showing the location view, the selected location is not centered on screen.

2. When selecting items between custom list and all locations, the snapshot state is sometimes lost. I believe this is related to not letting the `LocationNode` tree be the one source of truth. When toggling and updating selection the snapshot keeps a working state that doesn't reflect the node tree. It may be possible to make it work this way, but I doubt it will be completely reliable. What keeps track of expanded status is the `showsChildren` attribute on the node, but right now we don't update expanded status when toggling cells visible, which is a miss/bug from the original implementation. We should fix this and explicitly reapply the expanded status on the whole data set when data is reloaded (when creating snapshot items somewhere in `setRelays`). Ie. we only look at the node tree for data/structure and recreate the whole snapshot based on that.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBP3fUW09YMxrDvsz5N:b-kh9l50)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBCFQK480rAG3w0zdJG:-OBP1UcyEiBFEGOEZ-uK:b-lodk4c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70b7f8c909098159fe029eec06c9d19b79c86d25/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L13)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

How did this file ever work without having these imports?
Also, _are we_ using Combine here? I can't identify anything Combine specific in the changes here, and I was under the impression we were not using Combine anywhere in our code.
</blockquote></details>

They have been duplicated and a copy can be found a few lines below. This part should be removed.

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBQ3ukmEc-15zLOj2ql:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBCFQK480rAG3w0zdJG:-OBVQxjk5Lu4SvFl0jWz:b-ake7ju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70b7f8c909098159fe029eec06c9d19b79c86d25/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L13)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

They have been duplicated and a copy can be found a few lines below. This part should be removed.
</blockquote></details>

Yeah, this duplication should be removed.

**Review by mojganii — COMMENTED** [review]
@rablador it seems my recent changes will solve the problem you've mentioned above. just we need to add some more uint test for that, which I'll do that in a bit. let me know if you found any new issue with that.
for checking and simulating  concurrency issue you can get help from this snippet code :

        let concurrentQueue = DispatchQueue(label: "LocationDataSource.concurrentQueue", attributes: .concurrent)

        let letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

        let numberOfConcurrentTasks = 1000

        let maxWordLength = 100

        for \_ in 0 ..< numberOfConcurrentTasks {

            concurrentQueue.async {

                let randomText = String((0 ..< maxWordLength).compactMap { \_ in

                    letters.randomElement()!

                })

                if (0..<maxWordLength).randomElement()! % 2 == 0 {

                    self.dataSource?.setRelays(relaysWithLocation, selectedRelays: self.selectedRelays)

                } else {

                    self.dataSource?.filterRelays(by: randomText)

                }

            }

        }

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBW4CQi1VUwdcnkVEy5:b9e14v8)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @buggmagnet, @pinkisemils, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBCFQK480rAG3w0zdJG:-OBW44HLBGV7wkNez8v_:bjszmeo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70b7f8c909098159fe029eec06c9d19b79c86d25/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L13)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yeah, this duplication should be removed.
</blockquote></details>

that was my mistake. it's removed.

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pinkisemils)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift` line 42 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBdeLE3-OahRYwCKLEz:-OBdeLE3-OahRYwCKLF-:bwrm5oe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40cf8de6ef7238f69edb21fc3eeb0ab7f999fe3/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift#L42)):*
> ```Swift
>     }
> 
>     func toggledItems(for cell: LocationCell, completion: (() -> Void)? = nil) {
> ```

Since this function no longer returns anything we should call it `toggleItems` instead.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 114 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBdgDU20s8vX7DRWRNE:-OBdgDU20s8vX7DRWRNF:b-vyh958) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40cf8de6ef7238f69edb21fc3eeb0ab7f999fe3/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L114)):*
> ```Swift
>         setUpSegmentedControl()
>         addSubviews()
>         entryLocationViewController.flatMap {
> ```

Although nifty we decided some time ago that we should not use `flatMap` in this way.

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> Dismissed @pinkisemils from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBe-4jE3Ul90hCBI7x3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift` line 42 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBdeLE3-OahRYwCKLEz:-OBdt5veEUKFvnqhB7XQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40cf8de6ef7238f69edb21fc3eeb0ab7f999fe3/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift#L42)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Since this function no longer returns anything we should call it `toggleItems` instead.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 114 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-OBdgDU20s8vX7DRWRNE:-OBdt6Sz2cuUNk2MXAjt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40cf8de6ef7238f69edb21fc3eeb0ab7f999fe3/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L114)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Although nifty we decided some time ago that we should not use `flatMap` in this way.
</blockquote></details>

Done.

**Review by mojganii — COMMENTED** [review]
@pinkisemils Unit testing for this will be addressed in a separate task. Here is the link: [Testing Location DataSource for Stability](https://linear.app/mullvad/issue/IOS-935/testing-location-datasource-for-stability)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBeBMC-4n5u7y55OZX7:b-2kx1b2)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @rablador)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r4, 3 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150#-:-OBejab31XXI_3JfMeCg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
