### PR TITLE
Fix `doc list item missing indentation`

### PR DESCRIPTION
**Pull request by Serock3**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506#-:-O2eN5nxAiFouyGGQkjP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`mullvad-types/src/version.rs` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506#-O2eNWop9am16ULdy_Qe:-O2eNWop9am16ULdy_Qf:b-3u0bdm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0bc2c9856cce342f9550932347522b9dbafdafc/mullvad-types/src/version.rs#L24)):*
> ```XML
>     /// * Software bundled with this version, such as OpenVPN or OpenSSL, has known security
>     ///   issues, so using it is no longer recommended. The user should really upgrade when this is
>     ///   false.
> ```

    /// * Software bundled with this version, such as OpenVPN or OpenSSL, has known security
    ///   issues, so using it is no longer recommended.
    ///
    /// The user should really upgrade when this is false.



_Code quote:_
```XML
    /// * Software bundled with this version, such as OpenVPN or OpenSSL, has known security
    ///   issues, so using it is no longer recommended. The user should really upgrade when this is
    ///   false.
```

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506#-:-O2hybuj5le1u84iqD-z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
