### PR TITLE
[Don't merge] Windows split tunneling UI

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds communication and handling of the state for split tunneling on Windows to the frontend. This includes:
* Calls and listeners for the management interface
* IPC communication between the two frontend processes
* Handling of the state in the main process and in Redux in the renderer.

This PR doesn't build as is but will do when the updates to the management interface has been merged.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1169 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeiocEAXWHte0Q9MPp:-MYeiocFED5GONk5FcWs:bz4xc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/main/index.ts#L1169)):*
> ```XML
>       if (windowsSplitTunneling) {
>         return windowsSplitTunneling.getApplications({
>           updateCache,
> ```

Isn't the parameter actually called `updateCaches`?
___
*[gui/src/renderer/components/SplitTunnelingSettings.tsx, line 318 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYejPSx0tDMuePs8WiB:-MYejPSx0tDMuePs8WiC:b-2ldrbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/components/SplitTunnelingSettings.tsx#L318)):*
> ```XML
> 
>     if (fromCache) {
>       const { applications } = await getWindowsSplitTunnelingApplications(true);
> ```

Is there a reason for checking `fromCache`? Why not call `getWindowsSplitTunnelingApplications(true);` unconditionally?
___
*[gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx, line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeFZ853Q63gQCTHQlx:-MYeFZ853Q63gQCTHQly:bx1jhjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx#L17)):*
> ```XML
>   right: 0,
>   bottom: 0,
>   backgroundColor: '#000000',
> ```

Would it make sense to add `colors.black`?
___
*[gui/src/renderer/redux/settings/actions.ts, line 142 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeQ-Mt7huoEgGkn3Gf:-MYeQ-Mt7huoEgGkn3Gg:b-dvw5er) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/redux/settings/actions.ts#L142)):*
> ```XML
>   | IWireguardKeyVerifiedAction
>   | IUpdateDnsOptionsAction
>   | ISplitTunnelingEnableExclusions
> ```

Out-of-scope question: Shouldn't all (or none) of these type names end with `Action`?
___
*[gui/src/renderer/redux/settings/actions.ts, line 295 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeQEMm4f-BvdmvvYn0:-MYeQEMm4f-BvdmvvYn1:b-jy3e9e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/redux/settings/actions.ts#L295)):*
> ```XML
> }
> 
> function updateSplitTunneling(enabled: boolean): ISplitTunnelingEnableExclusions {
> ```

`updateSplitTunnelingState` might be slightly clearer. I realize that I've named the setting poorly in the proto file, though.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: 15 of 21 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[gui/src/main/index.ts, line 1169 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeiocEAXWHte0Q9MPp:-MYiERTf0ZCbcA5MbJOD:b-ayp6xp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/main/index.ts#L1169)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Isn't the parameter actually called `updateCaches`?
</blockquote></details>

Done. Yes, when importing with `require` the typechecker doesn't work apparently.
___
*[gui/src/renderer/components/SplitTunnelingSettings.tsx, line 318 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYejPSx0tDMuePs8WiB:-MYiEi9r5bd1rUlN_fW0:bkiaice) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/components/SplitTunnelingSettings.tsx#L318)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is there a reason for checking `fromCache`? Why not call `getWindowsSplitTunnelingApplications(true);` unconditionally?
</blockquote></details>

Updating the cache is pretty slow so the current solution loads everything from cache first and then loads it again but first updates the caches.

The exception to this is the first time the view is loaded, then it will have updated the cache and the first call updates the cache.
___
*[gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx, line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeFZ853Q63gQCTHQlx:-MYiFD3I8RvPlCdkNSNE:b60r506) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx#L17)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Would it make sense to add `colors.black`?
</blockquote></details>

Yes, done.
___
*[gui/src/renderer/redux/settings/actions.ts, line 142 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeQ-Mt7huoEgGkn3Gf:-MYiFFFvDz_jVmTLFwSf:b71t08z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/redux/settings/actions.ts#L142)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Out-of-scope question: Shouldn't all (or none) of these type names end with `Action`?
</blockquote></details>

Yes, we're already a bit inconsistent with this, but that's not a reason to not do it. Done.
___
*[gui/src/renderer/redux/settings/actions.ts, line 295 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MYeQEMm4f-BvdmvvYn0:-MYiFNZMAQq8Pumqdqcv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41b285f04b1ab10db7ca3d8247755e1ee2fac111/gui/src/renderer/redux/settings/actions.ts#L295)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`updateSplitTunnelingState` might be slightly clearer. I realize that I've named the setting poorly in the proto file, though.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/windows-split-tunneling.ts, line 39 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-MamvegQDKb1mq1Am7uC:-MamvegQDKb1mq1Am7uD:b-jb99eo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/378d1912af71b9958f536959727a485578ccbd11/gui/src/main/windows-split-tunneling.ts#L39)):*
> ```XML
> // Some applications might be falsely filtered from the application list. This allow-list specifies
> // apps that are falsely filtered but should be included.
> const APPLICATION_ALLOW_LIST = [
> ```

I wonder how sustainable this is. There's got to be a lot of programs that are falsely excluded? Is this because they don't directly depend on Winsock?
___
*[gui/src/main/windows-split-tunneling.ts, line 215 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-Mamvvlg3uG89sGSPpSm:-Mamvvlg3uG89sGSPpSn:b-wmwkw2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/378d1912af71b9958f536959727a485578ccbd11/gui/src/main/windows-split-tunneling.ts#L215)):*
> ```XML
> 
> async function retrieveIcon(exe: string) {
>   const icon = await app.getFileIcon(exe, { size: 'large' });
> ```

According to [this](https://www.electronjs.org/docs/api/app#appgetfileiconpath-options), the size is identical for `normal` (the default?) and `large`. But I assume that the documentation is wrong.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/main/windows-split-tunneling.ts, line 215 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-Mamvvlg3uG89sGSPpSm:-ManE_o52yvrR4VtUUNh:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/378d1912af71b9958f536959727a485578ccbd11/gui/src/main/windows-split-tunneling.ts#L215)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I saw that too but there was definitely a noticeable difference:



</blockquote></details>

:+1:

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/windows-split-tunneling.ts, line 100 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671#-Mcrpd7-CgHzsn6hI0WR:-Mcrpd7-CgHzsn6hI0WS:bzet1v4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17d762a6a5e8b1be6bc29f8e6bc151ce2a990644/gui/src/main/windows-split-tunneling.ts#L100)):*
> ```XML
>   if (parsedPath.ext === '.lnk') {
>     const shortcutDetiails = shell.readShortcutLink(path.resolve(applicationPath));
>     const realpath = await fs.promises.realpath(shortcutDetiails.target);
> ```

`realpath` seems to resolve symbolic/hard links as well. That might not be ideal if they're eventually supported.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2671)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Pull request merged**
