### PR TITLE
Get data directory value at app startup (Android)

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Remove `APP_PATH` from `mullvad-paths` on Android since it should not be a constant value. Instead, it is passed down from the Android app startup. As it turns out, it is really ever used for pointing to the RPC socket in use.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
@albin-mullvad mentioned that we also should update the README.md since it describes the "hard-coded" path.

See:
https://github.com/mullvad/mullvadvpn-app?tab=readme-ov-file#file-paths-used-by-mullvad-vpn-app

Data Directory (usually, `/data/data/net.mullvad.mullvadvpn/`)
https://developer.android.com/reference/android/content/Context#getDataDir()

Files Directory (usually, `/data/data/net.mullvad.mullvadvpn/files`)
https://developer.android.com/reference/android/content/Context#getFilesDir()

Cache Directory (usually, `/data/data/net.mullvad.mullvadvpn/cache`)
https://developer.android.com/reference/android/content/Context#getCacheDir()

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-:-O-BWMea5_TLv9LjJhOc:b-sqsc04)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-jni/src/lib.rs` line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-BOHiyAfWVqUvb3HWU:-O-BOHiyAfWVqUvb3HWV:b1lmnf7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6aed7d5c52151cfbf5926667612d7d03daf4ad9/mullvad-jni/src/lib.rs#L244)):*
> ```XML
>         data_dir,
>         cache_dir,
>         files_dir,
> ```

Just a small remark, should these be in the same order as above? data, files, cache.
or does it conflict with how it works on other platforms?

**Review by Rawa — CHANGES_REQUESTED** [review]
The paths might be different depending on the device, but this is in broad terms for the normal use case correct. However, if the user make use of work profiles or similar features the paths can be different.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-:-O-BXiAq9Ber8Kq_JMf7:b-hbirye)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`mullvad-jni/src/lib.rs` line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-BOHiyAfWVqUvb3HWU:-O-BmkQ8AHByR16iXwkq:bgxxdg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6aed7d5c52151cfbf5926667612d7d03daf4ad9/mullvad-jni/src/lib.rs#L244)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Just a small remark, should these be in the same order as above? data, files, cache.
or does it conflict with how it works on other platforms?
</blockquote></details>

They might as well :blush:

**Review by dlon — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98 and @Rawa)

___
*[`mullvad-daemon/src/management_interface.rs` line 1042 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-Bs2hDB9MwiD0c_fEb:-O-Bs2hDB9MwiD0c_fEc:by6ykj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/348838999d8f8ba747a2d3ecea56bcc3062e3b78/mullvad-daemon/src/management_interface.rs#L1042)):*
> ```XML
>                 server_abort_rx.into_future().await;
>             },
>             &rpc_socket_path,
> ```

Nit: I think  `&` can be removed.
___
*[`mullvad-paths/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-BsjOiD9PoWVyDSl-5:-O-BsjOiD9PoWVyDSl-6:bvrmbio) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/348838999d8f8ba747a2d3ecea56bcc3062e3b78/mullvad-paths/src/lib.rs#L75)):*
> ```XML
> }
> 
> #[cfg(not(target_os = "android"))]
> ```

Do we not only ever use `mullvad_paths` for `get_rpc_socket_path`? Could we not conditionally compile all of this code and just define the socket path in the one module where it's called on Android?

**Review by Rawa — COMMENTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @dlon and @Rawa)

___
*[`mullvad-daemon/src/management_interface.rs` line 1042 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-Bs2hDB9MwiD0c_fEb:-O-GWyKh8IKheJa-eS2y:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/348838999d8f8ba747a2d3ecea56bcc3062e3b78/mullvad-daemon/src/management_interface.rs#L1042)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: I think  `&` can be removed.
</blockquote></details>

Done
___
*[`mullvad-paths/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-BsjOiD9PoWVyDSl-5:-O-GX-EX-cA1yVjN-pU3:bmkuqbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/348838999d8f8ba747a2d3ecea56bcc3062e3b78/mullvad-paths/src/lib.rs#L75)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we not only ever use `mullvad_paths` for `get_rpc_socket_path`? Could we not conditionally compile all of this code and just define the socket path in the one module where it's called on Android?
</blockquote></details>

Solved this by not compiling `mullvad-paths` for Android at all. Instead, the path to the RPC socket is passed from the Android client, which means that the daemon does not have to care about it at all :blush:

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-:-O-HPNH43dDz-GpuJTT_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`mullvad-paths/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-BsjOiD9PoWVyDSl-5:-O-HP_DSBskRdSGYuMYb:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/348838999d8f8ba747a2d3ecea56bcc3062e3b78/mullvad-paths/src/lib.rs#L75)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Solved this by not compiling `mullvad-paths` for Android at all. Instead, the path to the RPC socket is passed from the Android client, which means that the daemon does not have to care about it at all :blush:
</blockquote></details>

Nice!

**Review by dlon — COMMENTED** [review]
> Reviewed 7 of 9 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`README.md` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-HsYbg61E9TrRzMW1S:-O-HsYbh2TN5QPakL5xH:bjsoyug) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc6ec0c8e7c6ae3e4699d024935bfe95a89004/README.md#L357)):*
> ```Markdown
> | macOS | `/Library/Caches/mullvad-vpn/` |
> | Windows | `C:\ProgramData\Mullvad VPN\cache` |
> | Android | [`getFilesDir()`](https://developer.android.com/reference/android/content/Context#getFilesDir())  |
> ```

Is `filesDir` correct? I think we use the cache dir in this case?

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`README.md` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-HsYbg61E9TrRzMW1S:-O-I1GLY7RkRw0LNv6qg:b-8uhdy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc6ec0c8e7c6ae3e4699d024935bfe95a89004/README.md#L357)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is `filesDir` correct? I think we use the cache dir in this case?
</blockquote></details>

Nope, getCacheDir() should be the one

**Review by Rawa — APPROVED** [review]
Besides the getCacheDir remark it lgtm

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-:-O-I37CBCgVftU8FUZDr:b-9pihp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`README.md` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342#-O-HsYbg61E9TrRzMW1S:-O-LniaOAEsKhrtujBD_:b-cdba5k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc6ec0c8e7c6ae3e4699d024935bfe95a89004/README.md#L357)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nope, getCacheDir() should be the one
</blockquote></details>

Since @MarkusPettersson98 is on vacay, I pushed a fix for this.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
