### PR TITLE
Use SEA for test executable instead of pkg

### PR DESCRIPTION
**Pull request by dlon**
Since the latter is deprecated.

Fix DES-949.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`.github/workflows/desktop-e2e.yml` line 248 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-Nxm2AIr3PjobRJWeysw:-Nxm2AIr3PjobRJWeysx:b-oi5yq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/.github/workflows/desktop-e2e.yml#L248)):*
> ```YAML
>         with:
>           token: ${{ secrets.GITHUB_TOKEN }}
>           node-version: 20
> ```

We should use the `node-version-file` in this workflow as well! This workflow must have been forgotten when we switched to Volta :thinking: 
___
*[`.github/workflows/translations.yml` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-Nxm2OzA1glAVuO4o0OE:-Nxm2OzA1glAVuO4o0OF:btuoe4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/.github/workflows/translations.yml#L29)):*
> ```YAML
>         uses: actions/setup-node@v4
>         with:
>           node-version: ${{ steps.volta.outputs.node }}
> ```

We should use the `node-version-file` here as well!
___
*[`gui/standalone-tests.ts` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxmBiUk1fzz25WnHhm1:-NxmBiUk1fzz25WnHhm2:bgxvl9t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/gui/standalone-tests.ts#L79)):*
> ```XML
> 
>   if (process.platform === 'darwin') {
>     child_process.spawnSync('/usr/bin/codesign', ['--sign', '-', nodeBin]);
> ```

Do we really need to sign it? When I ran the `hello` example on my mac it worked fine without a signature?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[`.github/workflows/translations.yml` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-Nxm2OzA1glAVuO4o0OE:-NxmEH_PDK-pNxl4Px8W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/.github/workflows/translations.yml#L29)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We should use the `node-version-file` here as well!
</blockquote></details>

Done.
___
*[`.github/workflows/translations.yml` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxmEI_UB5gXAxfJS26s:-NxmEI_UB5gXAxfJS26t:bgrvluy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59c50a71271dc65ac83d9b38e44e3f7093e61312/.github/workflows/translations.yml#L34)):*
> ```YAML
> 
>       - name: Update NPM
>         run: npm i -g npm@${{ steps.volta.outputs.npm }}
> ```

Do you know why we explicitly updated npm here? I suspect it's unnecessary, but I might be wrong.
___
*[`gui/standalone-tests.ts` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxmBiUk1fzz25WnHhm1:-NxmENHsDsl1IuADc1fH:b-itiivl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/gui/standalone-tests.ts#L79)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Do we really need to sign it? When I ran the `hello` example on my mac it worked fine without a signature?
</blockquote></details>

I had to sign it. Otherwise, macOS would kill the process. I think this requirement is stricter on arm Macs.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[`.github/workflows/desktop-e2e.yml` line 248 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-Nxm2AIr3PjobRJWeysw:-NxmHTXo39cCGaxAODo-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/.github/workflows/desktop-e2e.yml#L248)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We should use the `node-version-file` in this workflow as well! This workflow must have been forgotten when we switched to Volta :thinking:
</blockquote></details>

Done.
___
*[`.github/workflows/translations.yml` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxmEI_UB5gXAxfJS26s:-NxmGUr97qLIznU3TwO4:bucq9gu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59c50a71271dc65ac83d9b38e44e3f7093e61312/.github/workflows/translations.yml#L34)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do you know why we explicitly updated npm here? I suspect it's unnecessary, but I might be wrong.
</blockquote></details>

It might be that we were using the wrong `npm` (somewhere in `PATH`). `shell: bash` seemed to fix this.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`.github/workflows/translations.yml` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxmEI_UB5gXAxfJS26s:-NxrEWRg33FVQ7pcqZ90:b-ecaqw0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59c50a71271dc65ac83d9b38e44e3f7093e61312/.github/workflows/translations.yml#L34)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It might be that we were using the wrong `npm` (somewhere in `PATH`). `shell: bash` seemed to fix this.
</blockquote></details>

I'm pretty sure we updated NPM because we don't always use the npm version corresponding to the Node version installed. But maybe that is solved automatically now with `node-version-file`.
___
*[`gui/standalone-tests.ts` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxmBiUk1fzz25WnHhm1:-NxrEov32Lj3o3pn75O7:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8f3d9cd7df2da41cb1aba85fd2e2725ae0928f/gui/standalone-tests.ts#L79)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I had to sign it. Otherwise, macOS would kill the process. I think this requirement is stricter on arm Macs.
</blockquote></details>

Okay :+1:
___
*[`gui/scripts/build-test-executable.sh` line 29 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxrF9-uAWaH2hO0YjVn:-NxrF9-uAWaH2hO0YjVo:b-mpjssp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1aa48a19f775092ac152338a2d1f366506f1d249/gui/scripts/build-test-executable.sh#L29)):*
> ```Shell
>     local temp_output="./build/temp-test-executable$bin_suffix"
>     local output="../dist/app-e2e-tests-$PRODUCT_VERSION-$TARGET$bin_suffix"
>     local node_copy_path="./build/test/node$bin_suffix"
> ```

We probably shouldn't put anything like node in the `build` directory. I think it will be packaged into the Electron app by electron-builder :thinking:

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/scripts/build-test-executable.sh` line 29 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxrF9-uAWaH2hO0YjVn:-NxrKJ593GN-a9hdlAaP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1aa48a19f775092ac152338a2d1f366506f1d249/gui/scripts/build-test-executable.sh#L29)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We probably shouldn't put anything like node in the `build` directory. I think it will be packaged into the Electron app by electron-builder :thinking:
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/scripts/build-test-executable.sh` line 38 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-NxrSj8Y5zm1Sn_ALqIF:-NxrfdhNBuKmhGgNbzAy:b-snl9v6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31fa917129c48bd7106d421cb977e037e0609be/gui/scripts/build-test-executable.sh#L38)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This should go in `$temp_dir` as well right?
</blockquote></details>

Preferably not, since the asset path needs to be specified in `standalone-tests.sea.json`.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242#-:-NxwMZGVAQ_s8JEe5e3v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dlon and @raksooo)

**Pull request merged**
