### PR TITLE
Use encrypted dns proxy code in mullvad ios ios 818

### PR DESCRIPTION
**Pull request by pinkisemils**
With these changes, we are practically finishing off the encrypted DNS proxy work. These changes make use of the FFI exposed in `mullvad-ios::encrypted_dns_proxy` to implement the transport provider for our MullvadRest module in Swift. Most of the great work here has been done by @buggmagnet.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadREST/Transport/TransportProvider.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7hviCQEokmHaZUChv9:-O7hviCQEokmHaZUChvA:b6hah62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f08f1e540eaafd918fed23f7bc76c785e7c405ec/ios/MullvadREST/Transport/TransportProvider.swift#L20)):*
> ```Swift
>     private var currentTransportType: TransportStrategy.Transport
>     private let parallelRequestsMutex = NSLock()
>     private let encryptedDNSTransport: EncryptedDNSTransport!
> ```

Remove exclamation mark. A let constant that is assigned in an init function will always be non-optional.
___
*[`ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7hx3uTE-G9Xdy71MtM:-O7hx3uTE-G9Xdy71MtN:bszux8k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f08f1e540eaafd918fed23f7bc76c785e7c405ec/ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift#L21)):*
> ```Swift
>     private let encryptedDnsProxy: EncryptedDNSProxy
>     private let dispatchQueue = DispatchQueue(label: "net.mullvad.EncryptedDNSTransport")
>     private var dnsProxyTask: URLSessionTask!
> ```

Should be optional since it's nilled in `stop()`.

**Review by rablador — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @rablador)

___
*[`ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7hxmiV715QA2cZ7xtS:-O7hxmiV715QA2cZ7xtT:bza4iv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f08f1e540eaafd918fed23f7bc76c785e7c405ec/ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift#L67)):*
> ```Swift
>                     }
>                     // Do not call the completion handler if the request was cancelled in flight
>                     if let cancelledError = maybeError as? URLError, cancelledError.code == .cancelled {
> ```

Nit: Prefer a guard here, since we're returning early.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Transport/TransportProvider.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7hviCQEokmHaZUChv9:-O7i1F7JCJ8uh3Fqs2ir:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f08f1e540eaafd918fed23f7bc76c785e7c405ec/ios/MullvadREST/Transport/TransportProvider.swift#L20)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Remove exclamation mark. A let constant that is assigned in an init function will always be non-optional.
</blockquote></details>

Done
___
*[`ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7hx3uTE-G9Xdy71MtM:-O7i14eC400Asol_ngkS:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f08f1e540eaafd918fed23f7bc76c785e7c405ec/ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift#L21)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Should be optional since it's nilled in `stop()`.
</blockquote></details>

Done
___
*[`ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7hxmiV715QA2cZ7xtS:-O7i6KYr2jgv-BapY3TS:b-n9qo7x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f08f1e540eaafd918fed23f7bc76c785e7c405ec/ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift#L67)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Prefer a guard here, since we're returning early.
</blockquote></details>

We discussed this offline and came to the conclusion that the current construction is fine as is.

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-:-O7iEs9h3dSd3f3RDeQh:bnfp4nl)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @rablador)

___
*[`ios/MullvadREST/Transport/TransportProvider.swift` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874#-O7i8kCP9hgIr7LDisgX:-O7i8kCP9hgIr7LDisgY:bb5dvkq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/939548efbc69e25cac8a6edf7dbd76c0d95f1263/ios/MullvadREST/Transport/TransportProvider.swift#L58)):*
> ```Swift
> 
>         if strategy == transportStrategy {
>             if strategy.connectionTransport() == .encryptedDNS {
> ```

nit : we are doing to stop proxy in different  ways, somewhere in `deinit` and some like here we calling that directly. maybe we need to unify them in one place.

**Comment by pinkisemils** [comment]
WAT https://github.com/mullvad/mullvadvpn-app/actions/runs/11051418946/job/30701257215?pr=6874#step:11:1995

**Review by rablador — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6874)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @buggmagnet, @pinkisemils, and @rablador)

**Pull request closed without merging**
