### PR TITLE
Init Koin as DI for android project

### PR DESCRIPTION
**Pull request by axti**
In this PR we added Koin as main dependency injection tool and configure first and basic module.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637)

### CODE REVIEW

**Review by jvff — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-MXCeKhF56zoLgEiLxXt:-MXCeKhGEleUfc3eEDtv:b-h0h8ka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c51283ac02bbc43dd5cdedbc0c56c0009da4bf3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L27)):*
> ```Kotlin
>     }
> }
> const val APPS_SCOPE = "APPS_SCOPE"
> ```

Nit: I was wondering if it would make sense with the split process work to have a `UI_SCOPE` and `SERVICE_SCOPE`, but that's probably something to discuss in a separate PR :thinking: 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-MXCdz_l6i3Hzol4sBBR:-MXCdz_m1bBHXFCcy_YN:b2magwf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c51283ac02bbc43dd5cdedbc0c56c0009da4bf3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L28)):*
> ```Kotlin
> }
> const val APPS_SCOPE = "APPS_SCOPE"
> const val SELF_PACKAGE = "SELF_PACKAGE"
> ```

Nit: Maybe this should be called `APP_PACKAGE` or `APP_PACKAGE_NAME`?

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-MXCeKhF56zoLgEiLxXt:-MXDRX9F9Qa3QcoMChSm:b-voknmx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c51283ac02bbc43dd5cdedbc0c56c0009da4bf3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L27)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: I was wondering if it would make sense with the split process work to have a `UI_SCOPE` and `SERVICE_SCOPE`, but that's probably something to discuss in a separate PR :thinking: 
</blockquote></details>

Yeah, We can have different scope later on. Here I have tried to define scope for apps - split tunnelling feature.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-MXCdz_l6i3Hzol4sBBR:-MXDRrnR1P1X-WMNFCEz:b-votrl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c51283ac02bbc43dd5cdedbc0c56c0009da4bf3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Maybe this should be called `APP_PACKAGE` or `APP_PACKAGE_NAME`?
</blockquote></details>

I can change to `SELF_PACKAGE_NAME` but it just string nave for variable. I think `APP_PACKAGE` or `APP_PACKAGE_NAME` doesn't tell which package name, like more abstract.

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-MXCdz_l6i3Hzol4sBBR:-MXEYdE926ECGlhmdBJq:b-d2dxf5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c51283ac02bbc43dd5cdedbc0c56c0009da4bf3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L28)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

I can change to `SELF_PACKAGE_NAME` but it just string nave for variable. I think `APP_PACKAGE` or `APP_PACKAGE_NAME` doesn't tell which package name, like more abstract.
</blockquote></details>

Yeah, I think that makes sense :+1:

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-MXCdz_l6i3Hzol4sBBR:-MXa6mpf00Kp90wWVMjj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c51283ac02bbc43dd5cdedbc0c56c0009da4bf3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yeah, I think that makes sense :+1:
</blockquote></details>

Done.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637#-:-MXbBuYxAdncAwVWfj4A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
