### PR TITLE
Test updating between app versions and nightly test runs

### PR DESCRIPTION
**Pull request by niklasberglund**
This PR adds tests for verifying that settings are successfully migrated when updating from an older app version to the current app version. Also nightly test runs have been configured.

For running settings migration tests there's a new workflow iOS settings migration tests(`ios-end-to-end-tests-settings-migration.yml`). It installs an old app version, runs test changing settings, installs current app version and runs a test verifying that the settings are still changed. Since custom DNS cannot be set when DNS blockers are activated there has to be two runs where settings are changed and it's verified that they're still changed on new app version - one run for "use custom DNS" setting and one run for all other settings.

All tests are scheduled to run nightly(`ios-end-to-end-tests.yml` and `ios-end-to-end-tests-settings-migration.yml`)

The easiest way to test these changes is to trigger the workflow for settings migration(`ios-end-to-end-tests-settings-migration.yml`) on my mullvadvpn-app fork which will execute the tests on my computer and phone, but requires some coordination. The tests themselves can be tested locally by:
1. Check out commit `db8e804996fbbbd6fe500e62785a7e81c8a68a5c`
2. Run `MullvadVPNUITestsChangeDNSSettings` test plan
3. Check out latest commit in PR branch
4. Run `MullvadVPNUITestsVerifyDNSSettingsChanged` test plan
5. Check out commit `db8e804996fbbbd6fe500e62785a7e81c8a68a5c`
6. Run `MullvadVPNUITestsChangeSettings `
7. Check out latest commit in PR branch
8. Run `MullvadVPNUITestsVerifySettingsChanged` test plan

Note that if you want to run the tests locally there's a new configuration parameter in `UITests.xcconfig` which needs to be added:
```
SHOULD_BE_REACHABLE_DOMAIN = mullvad.net
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 20 of 26 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 21 of 26 files reviewed, 6 unresolved discussions (waiting on @niklasberglund)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-NtyufB3Dlvx3JfbKhg-:b-mbjpng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
> ```YAML
>     steps:
>       - name: Update Rust toolchain
>         run: rustup update
> ```

This probably will not work since the changes made last friday.
Here's what we want to do instead
```yaml
run: |
  rustup default stable
  rustup update stable
```
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyvCYVA5CfEk1KoAll:-NtyvCYVA5CfEk1KoAlm:b-jw67kj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L22)):*
> ```YAML
>     steps:
>       - name: Update Rust toolchain
>         run: rustup update
> ```

```yaml
run: |
  rustup default stable
  rustup update stable
```



_Code quote:_
```YAML
run: rustup update
```
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 620 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyvvVh5w4HtpQdInRd:-NtyvvVh5w4HtpQdInRe:b9qgaj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPN.xcodeproj/project.pbxproj#L620)):*
> ```
> 		8529693A2B4F0238007EAD4C /* TermsOfServicePage.swift in Sources */ = {isa = PBXBuildFile; fileRef = 852969392B4F0238007EAD4C /* TermsOfServicePage.swift */; };
> 		8529693C2B4F0257007EAD4C /* Alert.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8529693B2B4F0257007EAD4C /* Alert.swift */; };
> 		852A26462BA9C9CB006EB9C8 /* DNSSettingsPage.swift in Sources */ = {isa = PBXBuildFile; fileRef = 852A26452BA9C9CB006EB9C8 /* DNSSettingsPage.swift */; };
> ```

Don't forget to "Sort By Name" on the "Pages" folder
___
*[`ios/MullvadVPNUITests/README.md` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtywcUN3MNMCxME6Fh7:-NtywcUN3MNMCxME6Fh8:b-rqc0tf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPNUITests/README.md#L17)):*
> ```Markdown
>  - `sudo installer -pkg yeetd-normal.pkg -target yeetd`
> 6. Install ios-deploy
>   - `brew install ios-deploy`
> ```

Are we actually using this ?
___
*[`ios/MullvadVPNUITests/Pages/DNSSettingsPage.swift` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtytLy57-EMvXpxdKZg:-NtytLy57-EMvXpxdKZh:blon0cm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPNUITests/Pages/DNSSettingsPage.swift#L19)):*
> ```Swift
>     }
> 
>     private func assertSwitchOn(accessibilityIdentifier: AccessibilityIdentifier) {
> ```

Can't we have this return `self` so that all the functions using it can avoid returning ?
It would look like this 
```swift
    @discardableResult private func assertSwitchOn(accessibilityIdentifier: AccessibilityIdentifier) -> Self {
        let switchElement = app.cells[accessibilityIdentifier]
            .switches[AccessibilityIdentifier.customSwitch]

        guard let switchValue = switchElement.value as? String else {
            XCTFail("Failed to read switch state")
            return self
        }

        XCTAssertEqual(switchValue, "1")
        return self
    }
```

```swift
    @discardableResult func verifyBlockAdsSwitchOn() -> Self {
        assertSwitchOn(accessibilityIdentifier: .blockAdvertising)
    }

```
___
*[`ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift` line 124 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyuJu_4d9P6e4BX4w0:-NtyuJu_4d9P6e4BX4w1:bw0nfu3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift#L124)):*
> ```Swift
>     @discardableResult func verifyCustomWireGuardPortSelected(portNumber: String) -> Self {
>         let cell = app.cells[AccessibilityIdentifier.wireGuardCustomPort]
>         XCTAssert(cell.isSelected)
> ```

```swift
XCTAssertTrue(cell.isSelected)
```



_Code quote:_
```Swift
XCTAssert(cell.isSelected)
```

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 21 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-Nu-9mucEWyD5Qp9mxzc:bc0pfp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This probably will not work since the changes made last friday.
Here's what we want to do instead
```yaml
run: |
  rustup default stable
  rustup update stable
```
</blockquote></details>

It should really be
```yaml
      - name: Configure Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-ios-sim
```

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 21 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-Nu-bOiD3DYAGd4R_zsZ:-Nu-bOiD3DYAGd4R_zs_:b-xo7t46) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L77)):*
> ```YAML
>       - name: Change all other settings on old app version
>         uses: ./.github/actions/ios-end-to-end-tests
>         if: always()
> ```

What does this line do?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 17 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-Nu-VCSU0QaxrLKaq9kU:bmtkyg4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It should really be
```yaml
      - name: Configure Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-ios-sim
```
</blockquote></details>

Should it always be the latest Rust toolchain or should 1.77.0 be specified? In other workflows a version is specified.

```
      - name: Configure Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.0
          override: true
          target: aarch64-apple-ios-sim
```
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-Nu-bOiD3DYAGd4R_zsZ:-Nu-c3ON5IdiOt2-XdA6:b-543sjw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L77)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What does this line do?
</blockquote></details>

By default a step won't run if any previous step has failed. I believe the default condition is `success()`, so by specifying `always()` it will run even if any previous step failed.

So I specified that all four tests(changing settings and validating settings) should run even if anything has failed. The reason I think they should always run is because for example maybe something fails when setting custom DNS server, but then it's still meaningful to run the tests for all other settings.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 620 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyvvVh5w4HtpQdInRd:-Nu-_k9cC0_E5OCmseyX:b5v1kns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPN.xcodeproj/project.pbxproj#L620)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Don't forget to "Sort By Name" on the "Pages" folder
</blockquote></details>

Sorted now
___
*[`ios/MullvadVPNUITests/README.md` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtywcUN3MNMCxME6Fh7:-Ntz8ZKQCmJhT7z7n3H5:by9h58v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPNUITests/README.md#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Are we actually using this ?
</blockquote></details>

`ios-deploy` is added as a dependency for uninstalling the app in `ios-end-to-end-tests-settings-migration.yml`. By the way let me know if the team have another preferred tool that can uninstall apps.
___
*[`ios/MullvadVPNUITests/Pages/DNSSettingsPage.swift` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtytLy57-EMvXpxdKZg:-Nu-aGBPEYLBzb3eK35Z:b-ti10zp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPNUITests/Pages/DNSSettingsPage.swift#L19)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can't we have this return `self` so that all the functions using it can avoid returning ?
It would look like this 
```swift
    @discardableResult private func assertSwitchOn(accessibilityIdentifier: AccessibilityIdentifier) -> Self {
        let switchElement = app.cells[accessibilityIdentifier]
            .switches[AccessibilityIdentifier.customSwitch]

        guard let switchValue = switchElement.value as? String else {
            XCTFail("Failed to read switch state")
            return self
        }

        XCTAssertEqual(switchValue, "1")
        return self
    }
```

```swift
    @discardableResult func verifyBlockAdsSwitchOn() -> Self {
        assertSwitchOn(accessibilityIdentifier: .blockAdvertising)
    }

```
</blockquote></details>

Ah yes that's better. Updated to use this approach.
___
*[`ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift` line 124 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyuJu_4d9P6e4BX4w0:-Nu-aPGr3_q9BcGIL6pk:b-ht4o0h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift#L124)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

```swift
XCTAssertTrue(cell.isSelected)
```
</blockquote></details>

Updated to use `XCTAssertTrue`

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 17 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-Nu3N0jg7hOp72XneSEI:bvnvmfq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Should it always be the latest Rust toolchain or should 1.77.0 be specified? In other workflows a version is specified.

```
      - name: Configure Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.0
          override: true
          target: aarch64-apple-ios-sim
```
</blockquote></details>

The toolchain version should still be `stable`, as discussed offline.
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-Nu-bOiD3DYAGd4R_zsZ:-Nu3Mvkr-KOEvNud8qty:brxp9sd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L77)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

By default a step won't run if any previous step has failed. I believe the default condition is `success()`, so by specifying `always()` it will run even if any previous step failed.

So I specified that all four tests(changing settings and validating settings) should run even if anything has failed. The reason I think they should always run is because for example maybe something fails when setting custom DNS server, but then it's still meaningful to run the tests for all other settings.
</blockquote></details>

Sounds good!

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 16 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-Nu3MpoBBngOuJxExwwC:bvlkhnm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The toolchain version should still be `stable`, as discussed offline.
</blockquote></details>

See updated step. I don't understand what `override` is for though. The documentation says "Set installed toolchain as an override for the current directory" and the default value is `false`. Do you know what it does?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 16 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-Nu3dlLUEFLtucElUkd8:b-16ihbc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

See updated step. I don't understand what `override` is for though. The documentation says "Set installed toolchain as an override for the current directory" and the default value is `false`. Do you know what it does?
</blockquote></details>

It ensures that any other config is overridden. It's just a precaution to ensure that the toolchain that is installed by default doesn't get used.

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 16 of 26 files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyufB293cewxgy-A5d:-NuSsqQT7ZDSkB88rRJb:b-geelfm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests.yml#L31)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It ensures that any other config is overridden. It's just a precaution to ensure that the toolchain that is installed by default doesn't get used.
</blockquote></details>

Ah thanks, makes sense its enabled then 👍
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NtyvCYVA5CfEk1KoAll:-NuSt0yQ1V0B1-vmWJqQ:be8gpjl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79649d226bbca5ac1caf8e995d5c84e3a4a9d36a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L22)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

```yaml
run: |
  rustup default stable
  rustup update stable
```
</blockquote></details>

See discussion and changes above

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 21 of 26 files at r1, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift` line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NuTk_Ws9iBRQuHqN251:-NuTk_Ws9iBRQuHqN252:b-788n11) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38da44d2bfe156e05ac710ab9e22cfd1d6a45ebf/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSViewController.swift#L51)):*
> ```Swift
>         )
> 
>         let editDoneButton = editButtonItem
> ```

You have explained why this is necessary before, but perhaps it would be good to add a comment in the code as well.
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 66 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NuTmgVHEosNvTovelgm:-NuTmgVHEosNvTovelgn:b-gwft80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38da44d2bfe156e05ac710ab9e22cfd1d6a45ebf/ios/MullvadVPNUITests/Networking/Networking.swift#L66)):*
> ```Swift
>     }
> 
>     /// Get configured ad serving domain as URL object
> ```

Is this only used for testing? Perhaps it could live in a private Networking extension there instead?

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 5 of 26 files at r1, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-:-NuYDlSA3FnuwJDrjNk4:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @niklasberglund)

**Review by rablador — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-:-NuYg6045draTc-W6Kl_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: 23 of 26 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift` line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NuTk_Ws9iBRQuHqN251:-NuZlO6k7sFXGu5RtMUq:bu06kn0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38da44d2bfe156e05ac710ab9e22cfd1d6a45ebf/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSViewController.swift#L51)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

You have explained why this is necessary before, but perhaps it would be good to add a comment in the code as well.
</blockquote></details>

I'm not buying my explanation so had another look at this and it is possible to use a more straigh forward approach so modified it
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 66 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022#-NuTmgVHEosNvTovelgm:-Nuc7kQK4QpCg9sCnek5:b-kn9oo9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38da44d2bfe156e05ac710ab9e22cfd1d6a45ebf/ios/MullvadVPNUITests/Networking/Networking.swift#L66)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is this only used for testing? Perhaps it could live in a private Networking extension there instead?
</blockquote></details>

Removed this function - it is unused and was removed as part of another PR but don't know what happened, maybe a merge conflict brought it back.

**Review by rablador — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by rablador — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6022)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
