### PR TITLE
Disable selectable text

### PR DESCRIPTION
**Pull request by mojganii**
This PR makes the entire text in InfoHeaderView clickable and disables text selection.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)

### CODE REVIEW

**Review by rablador — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/InfoHeaderView.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247#-OCm8Ein2ePCXi1VWB7O:-OCm8Ein2ePCXi1VWB7P:b79xhdz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0825b852880c8e92621e6a3b22da5afb9cb4f/ios/MullvadVPN/Views/InfoHeaderView.swift#L84)):*
> ```Swift
>     private func addTapGestureRecognizer() {
>         let tapGesture = UITapGestureRecognizer(target: self, action: #selector(handleTextViewTap))
>         textView.addGestureRecognizer(tapGesture)
> ```

This change breaks accessibility and makes it impossible to open the link with voice reader on.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Views/InfoHeaderView.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247#-OCm8Ein2ePCXi1VWB7O:-OCnE00B5uWIjcFhqnLr:brv86hb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0825b852880c8e92621e6a3b22da5afb9cb4f/ios/MullvadVPN/Views/InfoHeaderView.swift#L84)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This change breaks accessibility and makes it impossible to open the link with voice reader on.
</blockquote></details>

I tested it out by voiceover and it worked, If you mean that.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/InfoHeaderView.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247#-OCm8Ein2ePCXi1VWB7O:-OD5Kl4I9_pPY-8nNRNJ:bomadnk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0825b852880c8e92621e6a3b22da5afb9cb4f/ios/MullvadVPN/Views/InfoHeaderView.swift#L84)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I tested it out by voiceover and it worked, If you mean that.
</blockquote></details>

I meant the screen reader, sorry.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Views/InfoHeaderView.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247#-OCm8Ein2ePCXi1VWB7O:-OD5ZzPY32KWpstPVMT9:bfxx1y1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0825b852880c8e92621e6a3b22da5afb9cb4f/ios/MullvadVPN/Views/InfoHeaderView.swift#L84)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I meant the screen reader, sorry.
</blockquote></details>

aren't they the same?
[Untitled.mp4](https://files.reviewableusercontent.io/images/reviewable/129863230/M26B3s14OONtkrlFf-flblHk/Untitled.mp4)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247#-:-ODFIBaa1zUQCtWvKlH6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
