### PR TITLE
Update rust and java code to expose wireguard port settings

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`mullvad-types/src/relay_constraints.rs` line 579 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsOpR67ateu7fdORtw:-NYsOpR67ateu7fdORtx:bzaeyuw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L579)):*
> ```XML
>         let port: Constraint<Port> = Constraint::from_java(env, object);
> 
>         let port_value = match port {
> ```

You can use `Constraint::map` here instead of a match expression: `port.map(|port| port.value as u16)`
___
*[`mullvad-types/src/relay_constraints.rs` line 586 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsP27L8AkrrhRh9oNP:-NYsP27L8AkrrhRh9oNQ:b-qmdwx8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L586)):*
> ```XML
>         WireguardConstraints {
>             port: port_value,
>             ip_version: WireguardConstraints::default().ip_version,
> ```

This looks a bit strange. You don't need to construct a new default value for each field:
```rust
WireguardConstraints {
    port: port.map(|port| port.value as u16),
    ..Default::default()
}
```
___
*[`mullvad-types/src/relay_constraints.rs` line 616 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsQ1Jd05fvG0mpY2Tt:-NYsQ1Jd05fvG0mpY2Tu:b-pb52pd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L616)):*
> ```XML
> 
> /// Used for jni conversion.
> #[derive(Debug, Default, Clone, Eq, PartialEq, Deserialize, Serialize)]
> ```

I believe you don't need to derive `Deserialize` and `Serialize` here, since `WireguardConstraints` doesn't actually use this struct. Also, `serde(default)` can be removed.
___
*[`mullvad-types/src/relay_constraints.rs` line 620 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsP_su8Nz8sItPSjDE:-NYsP_su8Nz8sItPSjDF:b-67giv8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L620)):*
> ```XML
> #[cfg_attr(target_os = "android", jnix(package = "net.mullvad.mullvadvpn.model"))]
> #[serde(default)]
> pub struct Port {
> ```

Is it possible to make this struct private (remove `pub`) here? That would make sense since we don't actually want this to be visible in outside this module.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/relay_constraints.rs` line 579 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsOpR67ateu7fdORtw:-NYvt8ai85MSronVph32:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L579)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You can use `Constraint::map` here instead of a match expression: `port.map(|port| port.value as u16)`
</blockquote></details>

Done.
___
*[`mullvad-types/src/relay_constraints.rs` line 586 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsP27L8AkrrhRh9oNP:-NYvt9SW5FAj3YCjy3k5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L586)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This looks a bit strange. You don't need to construct a new default value for each field:
```rust
WireguardConstraints {
    port: port.map(|port| port.value as u16),
    ..Default::default()
}
```
</blockquote></details>

Done.
___
*[`mullvad-types/src/relay_constraints.rs` line 616 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsQ1Jd05fvG0mpY2Tt:-NYvtCDo7yJBRwxqTjBG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L616)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I believe you don't need to derive `Deserialize` and `Serialize` here, since `WireguardConstraints` doesn't actually use this struct. Also, `serde(default)` can be removed.
</blockquote></details>

Done.
___
*[`mullvad-types/src/relay_constraints.rs` line 620 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsP_su8Nz8sItPSjDE:-NYvtFNsDo-lJJ0cLbJH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L620)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is it possible to make this struct private (remove `pub`) here? That would make sense since we don't actually want this to be visible in outside this module.
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)* status: 7 of 9 files reviewed, all discussions resolved

___
*[`mullvad-types/src/relay_constraints.rs` line 586 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NYsP27L8AkrrhRh9oNP:-NYw9l-zB6ZQtkC22eRJ:bo5cpot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87e0442d9ff45e4663dde86a571366ebe551acb0/mullvad-types/src/relay_constraints.rs#L586)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice :)

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`mullvad-types/src/relay_constraints.rs` line 609 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829#-NZ0OCyD2bVoGd6mTthr:-NZ0OCyECquk-YhdjIYO:bvctrrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/365abc0a9fb6aeb205a4894ab1d182633284c588/mullvad-types/src/relay_constraints.rs#L609)):*
> ```XML
> 
> /// Used for jni conversion.
> #[derive(Debug, Default, Clone, Eq, PartialEq)]
> ```

Kind of a nitpick, but we should probably conditionally compile this whole struct. I think you could change the attributes to this:

```rust
#[cfg(target_os = "android")]
#[derive(Debug, Default, Clone, Eq, PartialEq, FromJava, IntoJava)]
#[cfg(jnix(package = "net.mullvad.mullvadvpn.model"))]
```

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4829)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
