### PR TITLE
Backport translations

### PR DESCRIPTION
**Pull request by raksooo**
Backport of the recent batch of translations.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4022)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 40 of 60 files at r1, 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> Reviewed 3 of 60 files at r1, 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 60 files at r4, 1 of 61 files at r5, 60 of 60 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 61 files at r5, 60 of 60 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4022)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
