### PR TITLE
Show "Changes" in app after upgrades

### PR DESCRIPTION
**Pull request by pronebird**
- Add auto layout builder to simplify constraints creation. Most common constraints we have is pinning edges of one view to the parent or the other
- Show changelog when the app starts with contents of `changes.txt` file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/Assets/changes.txt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRIxDeo2CLu2k8nkF8P:-NRIxDeo2CLu2k8nkF8Q:b-eodl3o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/Assets/changes.txt#L1)):*
> ```help
> • Add built in Mullvad device management - this simplifies managing the devices on your Mullvad account. 📱
> ```

We should probably not commit the actual changes here to `main`. On desktop we only have the instructions for how to fill out the file in `main` and then we populate it with actual changes on release branches. That's easier to maintain.
___
*[`ios/Assets/changes.txt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRIx4ea-ukJryZLmefP:-NRIx4ea-ukJryZLmefQ:bzh3f7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/Assets/changes.txt#L6)):*
> ```help
> • Improved tunnel connection stability 🕵️
> • Fixed bugs and crashes 💥
> • Deprecate iOS 12 🚮
> ```

Do the `•` actually need to be in the file? On desktop it automatically makes a bullet list with each line from this file as a separate bullet.

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)* status: all files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Extensions/UIView+AutoLayoutBuilder.swift` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRIwwKV9KUPVzxgEgd2:-NRIwwKV9KUPVzxgEgd3:bd5zbjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/Extensions/UIView%2BAutoLayoutBuilder.swift#L19)):*
> ```Swift
>         insets: NSDirectionalEdgeInsets = .zero,
>         excludingEdges: NSDirectionalRectEdge = []
>     ) -> [NSLayoutConstraint] {
> ```

It feels a little strange specifying eg. a bottom inset and at the same time excluding it. Instead of NSDirectionalEdgeInsets, maybe we could provide an object with optional edges, thus only acting on the ones supplied. We could even add cases for .all(), .horisontal(), .vertical() as well.



_Code snippet (i):_
```Swift
struct EdgeInsets {
    enum Edge {
        case top(CGFloat)
        case bottom(CGFloat)
        case leading(CGFloat)
        case trailing(CGFloat)
    }

    let edges: [Edge]

    init(_ edges: Edge...) {
        self.edges = edges
    }
}
```



_Code snippet (ii):_
```Swift
pinEdgesTo()
...
insets.forEach { inset in
    switch inset {
    case let .top(margin):
        // Add constraint.
    }
}
...
```



_Code snippet (iii):_
```Swift
pinEdgesTo(view, insets: .init(.top(8), .leading(16), .trailing(24)))
```
___
*[`ios/MullvadVPN/Extensions/UIView+AutoLayoutBuilder.swift` line 184 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRJFmyUDeKrO4D07aOA:-NRJFmyUDeKrO4D07aOB:b-ygmabt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/Extensions/UIView%2BAutoLayoutBuilder.swift#L184)):*
> ```Swift
>  view.addSubview(subview)
> 
>  NSLayoutConstraint.activate {
> ```

Although I like this, one could go even further and create a UIView extension that takes one or more views, adds them as subviews, sets mask and then returns a closure for adding constraints.



_Code snippet (i):_
```Swift
extension UIView {
    func addConstrainedSubviews(_ subviews: [UIView], @AutoLayoutBuilder builder: () -> [NSLayoutConstraint]) {
        subviews.forEach { subview in
            subview.translatesAutoresizingMaskIntoConstraints = false
            addSubview(subview)
        }

        NSLayoutConstraint.activate(builder())
    }
}
```



_Code snippet (ii):_
```Swift
view.addConstrainedSubviews([subview]) {
    subview.pinEdgesToSuperview(
        insets: NSDirectionalEdgeInsets(top: 8, leading: 16, bottom: 8, trailing: 24),
        excludingEdges: .bottom
    )
    subview.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor)
}
```
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogContentView.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRJ3Ci6EbOHtqwKNbd4:-NRJ3Ci6EbOHtqwKNbd5:b-pa2d0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogContentView.swift#L15)):*
> ```Swift
>         let titleLabel = UILabel()
>         titleLabel.translatesAutoresizingMaskIntoConstraints = false
>         titleLabel.font = UIFont.systemFont(ofSize: 24, weight: .bold)
> ```

"UIFont" may be omitted in favor of type inference.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Extensions/UIView+AutoLayoutBuilder.swift` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRIwwKV9KUPVzxgEgd2:-NRXT2qn4u39yg9Daf3i:b-cxri5g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/Extensions/UIView%2BAutoLayoutBuilder.swift#L19)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It feels a little strange specifying eg. a bottom inset and at the same time excluding it. Instead of NSDirectionalEdgeInsets, maybe we could provide an object with optional edges, thus only acting on the ones supplied. We could even add cases for .all(), .horisontal(), .vertical() as well.
</blockquote></details>

How would you rewrite this example with your proposal?

```swift
titleLabel.pinEdgesToMargins(self, excludingEdges: .bottom)
```
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogContentView.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRJ3Ci6EbOHtqwKNbd4:-NRX9BSO1YkN4ZfXVE8d:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogContentView.swift#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"UIFont" may be omitted in favor of type inference.
</blockquote></details>

Done.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @faern and @rablador)

___
*[`ios/Assets/changes.txt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRIxDeo2CLu2k8nkF8P:-NRXcCPf1icvzQsoxaEP:b-3txo25) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/Assets/changes.txt#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should probably not commit the actual changes here to `main`. On desktop we only have the instructions for how to fill out the file in `main` and then we populate it with actual changes on release branches. That's easier to maintain.
</blockquote></details>

Is it automated for TestFlight builds too?
___
*[`ios/Assets/changes.txt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRIx4ea-ukJryZLmefP:-NRXNnGJAoEqCjkDMWUR:b-iqp4yx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/Assets/changes.txt#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do the `•` actually need to be in the file? On desktop it automatically makes a bullet list with each line from this file as a separate bullet.
</blockquote></details>

The document is displayed as a plain text without any modifications. Any reason why we should limit changelog to a bullet list that's automatically formed and not to be able to include additional message for instance if/when needed?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @faern and @rablador)

___
*[`ios/MullvadVPN/Extensions/UIView+AutoLayoutBuilder.swift` line 184 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRJFmyUDeKrO4D07aOA:-NRXcJeC1GRTjghf6gbg:bufj9g8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/Extensions/UIView%2BAutoLayoutBuilder.swift#L184)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Although I like this, one could go even further and create a UIView extension that takes one or more views, adds them as subviews, sets mask and then returns a closure for adding constraints.
</blockquote></details>

I'll play with it.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @faern and @pronebird)

___
*[`ios/MullvadVPN/Extensions/UIView+AutoLayoutBuilder.swift` line 184 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479#-NRJFmyUDeKrO4D07aOA:-NRXj8Oh79HiMUYFgM1r:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e21d3fc7d91d40e1269851351f408d75240ef44/ios/MullvadVPN/Extensions/UIView%2BAutoLayoutBuilder.swift#L184)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'll play with it.
</blockquote></details>

👍

**Pull request merged**
