### PR TITLE
Update the UI to indicate that the tunnel is post-quantum

### PR DESCRIPTION
**Pull request by acb-mv**
This adds information on post-quantum status to TunnelState and displays it in the UI, in the format as in the desktop app. Additionally, unit tests have been created for TunnelState.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
It's almost there but there are a couple of issues still.
1) The header bar should be green when we are in the connecting state
2) The label "creating quantum secure connection" is truncated, we should make it fit (see screenshot number 3, from the desktop client)
3) When we are in the connecting state, we should be seeing which relay we are connecting to, at the moment we are not showing anything. This information should be available from the connection state.
4) Running on the simulator should reflect whether the connection is supposedly post quantum or not. 

The current post quantum connection flow


The non post quantum connection flow


The desktop client connection flow (Please ignore the part that says "blocking internet" for now)


> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-:-NxBnp7y2EWaDnDasdsL:bz8mb)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadSettings/QuantumResistanceSettings.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxBm6hd3yaUo9aFMyPR:-NxBm6hd3yaUo9aFMyPS:b-cm1956) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadSettings/QuantumResistanceSettings.swift#L17)):*
> ```Swift
> }
> 
> public extension TunnelQuantumResistance {
> ```

nit
I think we can put it directly in the enum without the extension
___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift` line 187 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxBljo9C1w64ax7Wawe:-NxBljo9C1w64ax7Wawf:b-q56v7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift#L187)):*
> ```Swift
>                     transportLayer: .udp,
>                     remotePort: selectedRelay.endpoint.ipv4Relay.port,
>                     isPostQuantum: false
> ```

I know the simulator doesn't run the network extension, but since we use it to generate screenshots for the AppStore submission,
we still want it to reflect the would-be connection state.

i.e. We should try to make it reflect here that a post quantum secure connection is established if possible.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelStateTests.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxBnEM95ZCsp5NdoZQb:-NxBnEM95ZCsp5NdoZQc:b-rez0n1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelStateTests.swift#L13)):*
> ```Swift
> import XCTest
> 
> final class TunnelStateTests: XCTestCase {
> ```

Very nice !

**Review by acb-mv — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-:-NxD5Iw82vsBPCqji1Jd:bb6un1j)* status: 10 of 13 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/QuantumResistanceSettings.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxBm6hd3yaUo9aFMyPR:-NxD5LsD8rFLLjUqg_zY:b8dyc1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadSettings/QuantumResistanceSettings.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I think we can put it directly in the enum without the extension
</blockquote></details>

I prefer to put derived values in an extension, to separate them from the core of the type, but that's just me. I can change it if it's a matter of policy.
___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift` line 187 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxBljo9C1w64ax7Wawe:-NxD5Vug9d-BHiRqMQOR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift#L187)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I know the simulator doesn't run the network extension, but since we use it to generate screenshots for the AppStore submission,
we still want it to reflect the would-be connection state.

i.e. We should try to make it reflect here that a post quantum secure connection is established if possible.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxD-0eWEiI_eYyFdAeK:-NxD5iVP7JtOFtOV6D6o:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L52)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think it's alright. I don't think we need to specifically specify that we're negotiating keys as part of the connection flow.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 145 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxD-JRe82S05W2xGK3_:-NxDBY5xByuJAal8qL8h:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L145)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Should be same as the `.connecting`, `.reconnecting` etc states I'd say.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 156 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxD-iEAAu7n1yeWi3df:-NxDETOf8ikU4pBZ9QtD:b-rfoznv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L156)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Shouldn't these indicate quantum resistance as well?
</blockquote></details>

Done. (I didn't change the reconnecting one, as it doesn't mention security and rephrasing it is probably beyond the scope of this PR.)
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelStateTests.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxBnEM95ZCsp5NdoZQb:-NxDFT4iC4AXlXGh4v9g:b-hay2ix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelStateTests.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Very nice !
</blockquote></details>

Thanks!

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-:-NxGny6aE_OUJBn6MtXd:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxD-0eWEiI_eYyFdAeK:-NxGnZm1-1PdwVxwbX4f:b-jnrpsv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L52)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I left those TODOs to make sure we wouldn't forget them, that's on me !
But thanks for taking care of those :thumbsup: 
___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 156 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214#-NxD-iEAAu7n1yeWi3df:-NxGnmHP1bujXIg9KZkv:b-v3kxip) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e457fd9852f65375496ce40046bb14af05c79080/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L156)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Done. (I didn't change the reconnecting one, as it doesn't mention security and rephrasing it is probably beyond the scope of this PR.)
</blockquote></details>

Let's match what the deskop shows in terms of reconnecting IMHO
But also we can have that in another PR if needs be.

**Review by rablador — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6214)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
