### PR TITLE
Add time left properly displayed test

### PR DESCRIPTION
**Pull request by niklasberglund**
Implemented test verifying that time left is properly displayed. To test the changes in this PR run the test `testTimeLeft` under `AccountTests`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by acb-mv — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Pages/AccountPage.swift` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049#-Nv7WXiF0b_bl50569sF:-Nv7WXiF0b_bl50569sG:bcuc751) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c26aa2f6ca0e95a0f738d43801245766527e7b3c/ios/MullvadVPNUITests/Pages/AccountPage.swift#L57)):*
> ```Swift
>         let paidUntilLabelText = app.staticTexts[AccessibilityIdentifier.accountPagePaidUntilLabel].label
>         let dateFormatter = DateFormatter()
>         dateFormatter.dateFormat = "d MMM yyyy 'at' H:mm"
> ```

We should not use custom date formats if we can avoid it, this should probably be `iso8601` 
___
*[`ios/MullvadVPNUITests/Pages/AccountPage.swift` line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049#-Nv7WWP38whKwWFz8TVV:-Nv7WWP38whKwWFz8TVW:b-tip3jk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c26aa2f6ca0e95a0f738d43801245766527e7b3c/ios/MullvadVPNUITests/Pages/AccountPage.swift#L64)):*
> ```Swift
>         }
> 
>         print(paidUntilLabelDate)
> ```

Let 's remove this

**Review by buggmagnet — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
