### PR TITLE
Move changelog to settings

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/InAppNotificationController.kt` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989#-O9JEGou8L31omxCtg4N:-O9JEGou8L31omxCtg4O:bhhf36q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90cbd8cad4f5815f90e26389cd26a68c1c0bd75b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/InAppNotificationController.kt#L65)):*
> ```Kotlin
>         combine(
>                 tunnelStateNotificationUseCase().onEach {
>                     Logger.d("tunnelStateNotificationUseCase: $it")
> ```

Excessive logging?

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt` line 115 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989#-O9JGBJ1DWAFoZZz1Q54:-O9JGBJ1DWAFoZZz1Q55:b-op1kv3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90cbd8cad4f5815f90e26389cd26a68c1c0bd75b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt#L115)):*
> ```Kotlin
>                                 context.resources
>                                     .getString(R.string.download_url)
>                                     .appendHideNavOnPlayBuild(state.isPlayBuild)
> ```

This is never true so could be removed

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989)* status: all files reviewed, 1 unresolved discussion

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/InAppNotificationController.kt` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989#-O9JEGou8L31omxCtg4N:-O9JXn2e29JoyIZEnnyb:bu07j2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90cbd8cad4f5815f90e26389cd26a68c1c0bd75b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/InAppNotificationController.kt#L65)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Excessive logging?
</blockquote></details>

Mistake, removed it now. It was left when fixing `accountExpiryInAppNotificationUseCase`.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6989#-:-O9TU6iw1kPma-Flu0na:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
