### PR TITLE
Fix flaky tests caused by messed up daemon environment

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
## What? :detective:
This PR addresses an issue in the test framework where some test would mess with the daemon's environment variables without resetting them to their expected default values. 
## Why? 🤔
This could lead to subsequent tests failing for unforeseen reasons, which was very confusing.
## How? :hammer:  :carpentry_saw: 
After each test is finished, we check whether the daemon's environment variables deviate from the one's specified by the current test configuration. If so, we restart the daemon with the 'expected values'. This all happens in the existing clean up routine, which means that no tests *should* have to clean up this particular mess themselves.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
Good stuff!

> Reviewed 9 of 11 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-:-NvEZX6jAoZtQWnkpofH:beuyiaz)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/mullvad_daemon.rs` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvDkmT006EArUNJ6pxg:-NvDkmT006EArUNJ6pxh:b-qb1ztz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-manager/src/mullvad_daemon.rs#L61)):*
> ```XML
> impl RpcClientProvider {
>     /// Whether a [test case](test_macro::test_function) needs a [`MullvadProxyClient`].
>     pub async fn mullvad_client(&self, client_type: MullvadClientVersion) -> MullvadClientArgument {
> ```

Maybe there's no real point to `MullvadClientArgument` now. It could probably be removed in favor of `Option`, and the caller could be expected to call `Self::new_client`
___
*[`test/test-manager/src/tests/mod.rs` line 149 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvE_MnoDUB-mVtefHfh:-NvE_MnoDUB-mVtefHfi:bwqjf1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-manager/src/tests/mod.rs#L149)):*
> ```XML
>         rpc.set_daemon_environment(default_env).await?;
>     }
>     let mullvad_client = rpc_provider.new_client().await;
> ```

Contradicting myself, probably, but maybe we should pass the client to `cleanup_after_test`, and do `mem::replace(client, rpc_provider.new_client().await)` here if the daemon had to be restarted.
___
*[`test/test-runner/src/sys.rs` line 462 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvEYsRZA6gCLK5le4W3:-NvEYsRZA6gCLK5le4W4:b5fhv6c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-runner/src/sys.rs#L462)):*
> ```XML
>         .await
>         .map_err(|e| test_rpc::Error::Service(e.to_string()))?
>         .write_all(override_content.as_bytes())
> ```

Nit: `fs::write` would be simpler.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/mullvad_daemon.rs` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvDkmT006EArUNJ6pxg:-NvGKVmS0EYyoi0fjxXQ:bvyrkc8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-manager/src/mullvad_daemon.rs#L61)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe there's no real point to `MullvadClientArgument` now. It could probably be removed in favor of `Option`, and the caller could be expected to call `Self::new_client`
</blockquote></details>

I agree that `MullvadClientArgument` is not strictly necessary, but I think it serves as better documentation compared to using an `Option`. _If and when_ we expect the caller to invoke `RpcClientProvider::new_client` themselves, then I'm all for removing `MullvadClientArgument` :blush:
___
*[`test/test-runner/src/sys.rs` line 462 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvEYsRZA6gCLK5le4W3:-NvGKNzFC-ePbkiiVzeK:b-qiachz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-runner/src/sys.rs#L462)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: `fs::write` would be simpler.
</blockquote></details>

Done Nice, definitely using that! :blush:

**Review by dlon — APPROVED** [review]
> Reviewed 5 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/mullvad_daemon.rs` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvDkmT006EArUNJ6pxg:-NvGRKYGD51CN108n5PX:b-8qvd9j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-manager/src/mullvad_daemon.rs#L61)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I agree that `MullvadClientArgument` is not strictly necessary, but I think it serves as better documentation compared to using an `Option`. _If and when_ we expect the caller to invoke `RpcClientProvider::new_client` themselves, then I'm all for removing `MullvadClientArgument` :blush:
</blockquote></details>

All right! Let's keep it for now.
___
*[`test/test-manager/src/tests/mod.rs` line 149 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvE_MnoDUB-mVtefHfh:-NvGQm7PDnkVCiJqf6Su:bpp0mjs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50161a5dd8b9813dc53481c03784a6712781c30b/test/test-manager/src/tests/mod.rs#L149)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Contradicting myself, probably, but maybe we should pass the client to `cleanup_after_test`, and do `mem::replace(client, rpc_provider.new_client().await)` here if the daemon had to be restarted.
</blockquote></details>

I'm overcomplicating this. Could we not just create the client after calling `restart_daemon` and return `Ok(())` here?

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-runner/src/sys.rs` line 659 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGRhdT5KAuqc96B7SL:-NvGRhdT5KAuqc96B7SM:bj90gko) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df111c2d7dfa26f5739690e3a9b3a08fe6c14da7/test/test-runner/src/sys.rs#L659)):*
> ```XML
>         })
>         .await
>         .map_err(test_rpc::Error::from_tokio_join_error)??;
> ```

I slightly prefer panicking, as this should only panic if the task itself panics anyway, right?

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`test/test-runner/src/sys.rs` line 659 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGRhdT5KAuqc96B7SL:-NvGpr4P1ist1BQaeohZ:b5h34le) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df111c2d7dfa26f5739690e3a9b3a08fe6c14da7/test/test-runner/src/sys.rs#L659)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should we bring down the entire `test-runner` because one call to `get_daemon_environment` panics? Imo, we should leave that decision to the `test-manager` (or some other supervisor), because we will halt the test execution in place if we panic :blush:
</blockquote></details>

I totally agree that panicking should not halt the test runner. :slightly_smiling_face:  We definitely shouldn't panic if a "recoverable" error occurs. I think that isn't that case here, because `JoinHandle` only fails if the task itself panics, which it shouldn't.

So I'm thinking that this is handling a specific panic without solving the general problem. We're effectively wrapping a single piece of code in `catch_unwind`, but not handling panics that occur outside of this call to `spawn_blocking`, etc. IMO, the general solution might just be to restart `test-runner` if it crashes, or even catch panics at some point. :see_no_evil: 

Anyway, this isn't that important. :smile:

**Review by hulthe — COMMENTED** [review]
> Reviewed 6 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/mod.rs` line 141 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGxqCo9OtQYidB7e82:-NvGxqCp-dFQfC2pavf3:bjtpvax) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0225384fb9c67c14c535f00559352b53bdbbbe/test/test-manager/src/tests/mod.rs#L141)):*
> ```XML
> }
> 
> /// Conditonally restart the running daemon
> ```

Nit: Conditionally
___
*[`test/test-runner/src/sys.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvCkPgi0weifkGzMWSh:-NvCkPgi0weifkGzMWSi:be7menq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7abfe34fae91317a56e2ea93219d3c24dc26a2/test/test-runner/src/sys.rs#L1)):*
> ```XML
> use std::collections::HashMap;
> ```

BTW seems everything in this file seems to be target specific, maybe we should consider splitting into one file per target. Not strictly related to this PR of course.
___
*[`test/test-runner/src/sys.rs` line 641 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGffxiA3clzr8ITzWU:-NvGffxiA3clzr8ITzWV:b4lklmv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df111c2d7dfa26f5739690e3a9b3a08fe6c14da7/test/test-runner/src/sys.rs#L641)):*
> ```XML
>                 string
>                     .trim_start_matches('"')
>                     .trim_end_matches('"')
> ```

Tip: [trim_matches](https://doc.rust-lang.org/std/primitive.str.html#method.trim_matches)
___
*[`test/test-runner/src/sys.rs` line 423 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGieVr6sY6lHYMRv0v:-NvGieVr6sY6lHYMRv0w:bq06aw9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0225384fb9c67c14c535f00559352b53bdbbbe/test/test-runner/src/sys.rs#L423)):*
> ```XML
>             }
>             _ => Err(error),
>         }
> ```

Hmm.. this only parses a subset of ways to specify environment variables. Might be worth considering the cost of handling those cases vs the risk of this parsing breaking down, at a later date.
___
*[`test/test-runner/src/sys.rs` line 601 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGwXtVAv6oFE8VBg6f:-NvGwXtVAv6oFE8VBg6g:b-wpcr2s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0225384fb9c67c14c535f00559352b53bdbbbe/test/test-runner/src/sys.rs#L601)):*
> ```XML
>             .map_err(|err| test_rpc::Error::FileSystem(err.to_string()))?;
>         buf
>     };
> ```

Tip: `tokio::fs::read_to_string` does all of this

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: all files reviewed, 2 unresolved discussions

___
*[`test/test-manager/src/tests/mod.rs` line 141 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGxqCo9OtQYidB7e82:-NvH7t6REbG6g67HRotW:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0225384fb9c67c14c535f00559352b53bdbbbe/test/test-manager/src/tests/mod.rs#L141)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Nit: Conditionally
</blockquote></details>

Done
___
*[`test/test-runner/src/sys.rs` line 641 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGffxiA3clzr8ITzWU:-NvH9f3W7Xsk_QV8s7Lz:b-tovvud) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df111c2d7dfa26f5739690e3a9b3a08fe6c14da7/test/test-runner/src/sys.rs#L641)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Tip: [trim_matches](https://doc.rust-lang.org/std/primitive.str.html#method.trim_matches)
</blockquote></details>

Done Nice!
___
*[`test/test-runner/src/sys.rs` line 601 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGwXtVAv6oFE8VBg6f:-NvH7zMkCoB0-Enx0KP5:b-4gyknk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0225384fb9c67c14c535f00559352b53bdbbbe/test/test-runner/src/sys.rs#L601)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Tip: `tokio::fs::read_to_string` does all of this
</blockquote></details>

:raised_hands: Nice, thought that their ought to exists something similar already :blush:

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: all files reviewed, 2 unresolved discussions (waiting on @hulthe)

___
*[`test/test-runner/src/sys.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvCkPgi0weifkGzMWSh:-NvHKH4L4N6wXmjS0LjG:b-eigf3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5a7abfe34fae91317a56e2ea93219d3c24dc26a2/test/test-runner/src/sys.rs#L1)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

BTW seems everything in this file seems to be target specific, maybe we should consider splitting into one file per target. Not strictly related to this PR of course.
</blockquote></details>

Yes, we definitely should! This PR has already grown a bit past its intended scope, so lets clean this up in another PR :blush: 
___
*[`test/test-runner/src/sys.rs` line 659 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGRhdT5KAuqc96B7SL:-NvHJyhT9VNiztBQrGE_:b-xe3tye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df111c2d7dfa26f5739690e3a9b3a08fe6c14da7/test/test-runner/src/sys.rs#L659)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I totally agree that panicking should not halt the test runner. :slightly_smiling_face:  I'll try to translate my thoughts into words.

We definitely shouldn't panic if a "recoverable" error occurs. I think that isn't that case here, because `JoinHandle` only fails if the task itself panics, which it shouldn't.

So I'm thinking that this is handling a specific panic without solving the general problem. We're effectively wrapping a single piece of code in `catch_unwind`, but not handling panics that occur outside of this call to `spawn_blocking`, etc. IMO, the general solution might just be to restart `test-runner` if it crashes, or even catch panics at some point. :see_no_evil: 

Anyway, this isn't that important. :smile:
</blockquote></details>

Yes, we should have a more in-depth discussion on this topic / the architecture of `test-runner` to see what approach is the most fitting :blush:

If it's okay, I'll keep it as it is. Otherwise, I'll just go ahead and add back the `unwrap`s :blush:

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)* status: all files reviewed, 2 unresolved discussions (waiting on @hulthe)

___
*[`test/test-runner/src/sys.rs` line 423 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGieVr6sY6lHYMRv0v:-NvHKh5R8ClxidwV97kP:b-egzse5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0225384fb9c67c14c535f00559352b53bdbbbe/test/test-runner/src/sys.rs#L423)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Hmm.. this only parses a subset of ways to specify environment variables. Might be worth considering the cost of handling those cases vs the risk of this parsing breaking down, at a later date.
</blockquote></details>

Yes, the parsing is limited. I think it is okay for now, as we also control the way that the environment variables are written to the override file :blush:

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-:-NvHW-JAEf-ZclL9i-2c:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @hulthe)

___
*[`test/test-runner/src/sys.rs` line 659 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108#-NvGRhdT5KAuqc96B7SL:-NvHVvsJA3_cf5sZfaJY:b-r9szl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df111c2d7dfa26f5739690e3a9b3a08fe6c14da7/test/test-runner/src/sys.rs#L659)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Yes, we should have a more in-depth discussion on this topic / the architecture of `test-runner` to see what approach is the most fitting :blush:

If it's okay, I'll keep it as it is. Otherwise, I'll just go ahead and add back the `unwrap`s :blush:
</blockquote></details>

That's fine!

**Pull request merged**
