### PR TITLE
Add daita and multihop pages to the root of the settings view

### PR DESCRIPTION
**Pull request by rablador**
Adds the new settings pages for both DAITA and multhop to the settings view.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232)

### CODE REVIEW

**Review by acb-mv — DISMISSED** [review]
> Reviewed 44 of 61 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift` line 244 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OCYwI3X-d7Xfq0GUrFe:-OCYwI3X-d7Xfq0GUrFf:bsg8wdn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/efa6e2c8e48eb6d88c60217269ebf9d496e56de5/ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift#L244)):*
> ```Swift
>     /// - Parameter route: the route for which to request the new view controller or child coordinator.
>     /// - Returns: a result of creating a child for the route.
>     // swiftlint:disable:next function_body_length
> ```

Perhaps it's a good time to break this up into multiple functions and calling them, i.e., 
```
case .multihop:
    return makeMultihopViewController(tunnelManager:interactorFactory.tunnelManager)
case .daita:
  ...
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232)* status: 43 of 70 files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift` line 244 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OCYwI3X-d7Xfq0GUrFe:-OCbXZJEAet1PjIlV7_t:bqog80t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/efa6e2c8e48eb6d88c60217269ebf9d496e56de5/ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift#L244)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Perhaps it's a good time to break this up into multiple functions and calling them, i.e., 
```
case .multihop:
    return makeMultihopViewController(tunnelManager:interactorFactory.tunnelManager)
case .daita:
  ...
```
</blockquote></details>

Agreed

**Review by buggmagnet — CHANGES_REQUESTED** [review]
The new images added for Daita and Multihop appear quite pixelated (especially the internet icon somehow)


> Reviewed 40 of 61 files at r1, 15 of 27 files at r4, 10 of 14 files at r5, 6 of 10 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-:-OD6KAlp7hZXec92R3Oz:bfnvc69)* status: 69 of 72 files reviewed, 3 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OD6aCMJ7J-3qcnw3nLX:-OD6aCMJ7J-3qcnw3nLY:by510ly) (no related file):*
We are using the incorrect image for the multihop illustration, this should be a phone, not a desktop 

___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift` line 16 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OD6ScjL9iEM1_E4yO93:-OD6ScjL9iEM1_E4yO94:bruqmz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4715420d44ccf9cdacc10734d436b19b9a7481f9/ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift#L16)):*
> ```Swift
> struct SettingsViewControllerFactory {
>     /// The result of creating a child representing a route.
>     enum MakeChildResult {
> ```

nit
If it's intended to be a `Result`, why not simply use the `Swift.Result` type ?
This would avoid leaking `SettingsViewControllerFactory.MakeChildResult` in `SettingsCoordinator`

**Review by rablador — COMMENTED** [review]
Fixed!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-:-OD6jv6y-2LcDArN5Hlg:bt2vr0y)* status: 68 of 72 files reviewed, 3 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OD6aCMJ7J-3qcnw3nLX:-OD6ju6n0AYC4Acln4UE:bt2vr0y) (no related file):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We are using the incorrect image for the multihop illustration, this should be a phone, not a desktop 

</blockquote></details>

Fixed!
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift` line 16 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OD6ScjL9iEM1_E4yO93:-OD6lLoH3rMn_gHY7Z-d:b-8du7ql) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4715420d44ccf9cdacc10734d436b19b9a7481f9/ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
If it's intended to be a `Result`, why not simply use the `Swift.Result` type ?
This would avoid leaking `SettingsViewControllerFactory.MakeChildResult` in `SettingsCoordinator`
</blockquote></details>

Sometimes we return a viewcontroller, sometimes a coordinator. How would we help the compiler know which is which? I'm guessing that's why `MakeChildResult` was introduced in the first place (I simply refactored it).

**Review by acb-mv — COMMENTED** [review]
> Reviewed 3 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232)* status: 65 of 86 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift` line 16 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-OD6ScjL9iEM1_E4yO93:-ODBaKp22IN1kS8Q73Jd:bd3vfg7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4715420d44ccf9cdacc10734d436b19b9a7481f9/ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift#L16)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Sometimes we return a viewcontroller, sometimes a coordinator. How would we help the compiler know which is which? I'm guessing that's why `MakeChildResult` was introduced in the first place (I simply refactored it).
</blockquote></details>

Not every result is a `Result`. 

Another option would be to call it a `MakeChildProduct` or similar, omit `.failed` and wrap it in an optional or `Result` (or a throwing call) if it's failable

**Review by buggmagnet — APPROVED** [review]
> Reviewed 3 of 10 files at r6, 21 of 21 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

**Comment by pinkisemils** [comment]
We should update the changelog here, otherwise looks good to me.

**Review by rablador — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-:-ODG5AKV09Lkh1DFXwe1:b-896fix)* status: 47 of 87 files reviewed, all discussions resolved (waiting on @acb-mv and @buggmagnet)

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7232#-:-ODGflN2BOUgPBRHEzke:bnfp4nl)* status: 48 of 87 files reviewed, all discussions resolved (waiting on @acb-mv and @buggmagnet)

**Pull request merged**
