### PR TITLE
Fix many small bugs

### PR DESCRIPTION
**Pull request by rablador**
Many small bugs were squashed:

- [IOS-706 : Can use the `Done` button to escape from the account view during payment](https://linear.app/mullvad/issue/IOS-706/can-use-the-done-button-to-escape-from-the-account-view-whilst-making)
- [IOS-126 : Change and add text in Content blockers informational dialog](https://linear.app/mullvad/issue/IOS-126/change-and-add-text-in-content-blockers-informational-dialog)
- [IOS-697 : Truncated text on successful import of Server IP override](https://linear.app/mullvad/issue/IOS-697/truncated-text-on-successful-import-of-server-ip-override)
- [IOS-709 : Colours fade too much when testing API access methods](https://linear.app/mullvad/issue/IOS-709/colours-fade-too-much-when-testing-api-access-methods)
- [IOS-124 : Remove disable text when DNS content blockers list is collapsed](https://linear.app/mullvad/issue/IOS-124/remove-disable-text-when-dns-content-blockers-list-is-collapsed)

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304)* status: 0 of 8 files reviewed, 8 unresolved discussions

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pSyWEyiMCh0lSv2b:-Nz8pSyWEyiMCh0lSv2c:b-htpmji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift#L0)):*
[IOS-697 : Truncated text on successful import of Server IP override​](https://linear.app/mullvad/issue/IOS-697/truncated-text-on-successful-import-of-server-ip-override)
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatusView.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pPyf3Kzo3f843F-o:-Nz8pPyf3Kzo3f843F-p:b-htpmji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatusView.swift#L0)):*
[IOS-697 : Truncated text on successful import of Server IP override​](https://linear.app/mullvad/issue/IOS-697/truncated-text-on-successful-import-of-server-ip-override)
___
*[`ios/MullvadVPN/UI appearance/UIColor+Palette.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pMjmD5ste4_YMqD9:-Nz8pMjmD5ste4_YMqDA:bllqnc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/UI%20appearance/UIColor%2BPalette.swift#L0)):*
[IOS-709 : Colours fade too much when testing API access methods​](https://linear.app/mullvad/issue/IOS-709/colours-fade-too-much-when-testing-api-access-methods)
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pKgQAgcjIIdq8U8K:-Nz8pKgQAgcjIIdq8U8L:b1usr7l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L0)):*
[IOS-706 : Can use the \`Done\` button to escape from the account view whilst making a payment​](https://linear.app/mullvad/issue/IOS-706/can-use-the-done-button-to-escape-from-the-account-view-whilst-making)
___
*[`ios/MullvadVPN/View controllers/Alert/AlertViewController.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pIoy1z7NxNwnE-rW:-Nz8pIoy1z7NxNwnE-rX:bo8u74q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/View%20controllers/Alert/AlertViewController.swift#L0)):*
[IOS-126 : Change and add text in Content blockers informational dialog​](https://linear.app/mullvad/issue/IOS-126/change-and-add-text-in-content-blockers-informational-dialog)
___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8p93t8V6zo7Btq-2P:-Nz8p93t8V6zo7Btq-2Q:bz6jge3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSDataSource.swift#L0)):*
[IOS-124 : Remove disable text when DNS content blockers list is collapsed​](https://linear.app/mullvad/issue/IOS-124/remove-disable-text-when-dns-content-blockers-list-is-collapsed)
___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pBhiA412f-jjFVIE:-Nz8pBhiA412f-jjFVIF:bo8u74q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSViewController.swift#L0)):*
[IOS-126 : Change and add text in Content blockers informational dialog​](https://linear.app/mullvad/issue/IOS-126/change-and-add-text-in-content-blockers-informational-dialog)
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-Nz8pDsvANr2xca20Dkl:-Nz8pDsvANr2xca20Dkm:bz6jge3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ef506ed119328d746629306709bbc291dce1ec7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewModel.swift#L0)):*
[IOS-124 : Remove disable text when DNS content blockers list is collapsed​](https://linear.app/mullvad/issue/IOS-124/remove-disable-text-when-dns-content-blockers-list-is-collapsed)

**Review by buggmagnet — APPROVED** [review]
Wasn't that testing spinner + text centered before ? (It is in centered the figma file, but the regression is already present on the latest AppStore release)



> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-:-O--w7cP0ys37-uEZZjr:bb3w5tm)* status: all files reviewed, 8 unresolved discussions

**Review by rablador — COMMENTED** [review]
Centered how? Do you have a link to the designs? This part hasn't changed for a long time, so I'm thinking it might have been there from first release.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-:-O-0tRfW3fOtPCW6BcPN:ba71zdq)* status: all files reviewed, 8 unresolved discussions

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304)* status: 7 of 8 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Alert/AlertViewController.swift` line 255 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-NzXSisz5odrDMZWuX3-:-NzXSisz5odrDMZWuX30:b-vd9588) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84eb35c945c4dfbe6f61f23335e5fc09359b4585/ios/MullvadVPN/View%20controllers/Alert/AlertViewController.swift#L255)):*
> ```Swift
>         let attributeRange = NSRange(location: 0, length: message.length)
>         message.removeAttribute(.paragraphStyle, range: attributeRange)
>         message.addAttribute(.paragraphStyle, value: style, range: attributeRange)
> ```

what was the reason behind that? once we remove the current paragraph style and then add ours. is there any state which string has own attributed before sending to alert view? 
___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift` line 566 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6304#-O-1Pp288F9_mN26jRNx:-O-1Pp288F9_mN26jRNy:b-iv7gme) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84eb35c945c4dfbe6f61f23335e5fc09359b4585/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSDataSource.swift#L566)):*
> ```Swift
>         var snapshot = snapshot
> 
>         if snapshot.itemIdentifiers(inSection: .contentBlockers).isEmpty {
> ```

I had hard time to understand what these conditions are chasing. that would be great if we have some comments for them

**Pull request merged**
