### PR TITLE
Create info confirm dialog base component

### PR DESCRIPTION
**Pull request by kl**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6947)

### CODE REVIEW

**Review by Rawa — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6947)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — COMMENTED** [review]
Is it possible to also make `DiscardChangesDialog` also inherit from `InfoConfirmationDialog` ?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6947#-:-O8gWV6b-RK9RfLpXul2:bvm79vq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kl — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6947#-:-O8k2oPO38jmcPcUX4gk:bb6un1j)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Rawa)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6947#-:-O8k3y34DtVd017iqK1k:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Pururun and @Rawa)

**Pull request merged**
