### PR TITLE
Add in app banner message for a new device

### PR DESCRIPTION
**Pull request by Rawa**
- Rework how notifications work and introduce a InAppNotificationController
- Add New Device notification for when the user logs in, informing the user about the newly added device.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> Reviewed 5 of 68 files at r1, 76 of 76 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt` line 90 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgsyTE52rHZ3CmQM_va:-NgsyTE52rHZ3CmQM_vb:b-dp1boz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt#L90)):*
> ```Kotlin
> ) {
>     val previous = rememberPrevious(current = notification, shouldUpdate = { _, _ -> true })
>     // Fix for animating t hide
> ```

Nit: to hide
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 161 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgszkOP8rHakdpOzyY4:-NgszkOP8rHakdpOzyY5:b-jn3vbm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/lib/resource/src/main/res/values/strings.xml#L161)):*
> ```XML
>     <string name="vpn_permission_error_notification_title">VPN permission error</string>
>     <string name="vpn_permission_error_notification_message">Always-on VPN might be enabled for another app</string>
>     <string name="new_device_notification_title">NEW DEVICE CREATED</string>
> ```

I'm not sure about this, do we want to set all caps in the code or have all caps in the strings?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt` line 90 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgsyTE52rHZ3CmQM_va:-NgxDvoIDEYntJuJ62zY:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt#L90)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Nit: to hide
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryNotificationUseCase.kt` line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-Ngt-mCs9z9th57_r2_R:-NgxDdgBEajEV09V1SiC:b-fr04ao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryNotificationUseCase.kt#L31)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This magic number should be a constant.
</blockquote></details>

Yeah, I agree, this was from the previous implementation, I've moved it into constants now
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 161 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgszkOP8rHakdpOzyY4:-NgxDT7_1W5HEY50ZQkv:b-syro8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/lib/resource/src/main/res/values/strings.xml#L161)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I'm not sure about this, do we want to set all caps in the code or have all caps in the strings?
</blockquote></details>

Not sure, but it was all caps in `messages.po`, I'm unsure if that is case sensitive? Maybe @albin-mullvad has an opinion?

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`-- commits` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgxpCgJCpUB--18ruLq):*
Should probably be merged into "Rework notifications"

Also should also update the change log.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 161 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgszkOP8rHakdpOzyY4:-NgxpTWp6R1JfRynZ_tb:bbityaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/lib/resource/src/main/res/values/strings.xml#L161)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure, but it was all caps in `messages.po`, I'm unsure if that is case sensitive? Maybe @albin-mullvad has an opinion?
</blockquote></details>

If it is the text we get from `messages.po` I think we should keep it.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`-- commits` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgxpCgJCpUB--18ruLq):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should probably be merged into "Rework notifications"

Also should also update the change log.
</blockquote></details>

Added them to the respective commits now :+1:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`-- commits` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgxpCgJCpUB--18ruLq):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Added them to the respective commits now :+1:
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-:-Nh0XziC9aE_wXHfWY-S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 161 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgszkOP8rHakdpOzyY4:-Nh5rHEd8vlgtAB3fDxw:biz5uke) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/lib/resource/src/main/res/values/strings.xml#L161)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

If it is the text we get from `messages.po` I think we should keep it.
</blockquote></details>

I think we should avoid all caps in our strings (and template) since no other notification titles are in all-caps in our strings (template). Would be nice to change/align this with desktop.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 161 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-NgszkOP8rHakdpOzyY4:-Nh6ftV25haMQ9Rmu9hn:bb53m4h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb00f078f74a5117e8879af7453b28606f3c4378/android/lib/resource/src/main/res/values/strings.xml#L161)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I think we should avoid all caps in our strings (and template) since no other notification titles are in all-caps in our strings (template). Would be nice to change/align this with desktop.
</blockquote></details>

Actually some of the notification titles are all caps:
    <string name="update_available">UPDATE AVAILABLE</string>
    <string name="unsupported_version">UNSUPPORTED VERSION</string>

but yes some are not:
    <string name="account_credit_expires_soon">Account credit expires soon</string>
    <string name="blocking_internet">Blocking internet</string>

Spoke with Desktop, they make all the titles all caps in translation for title but also capitalize all the strings. They also mentioned that if there is a quirk for some languages it makes sense to capitalize them in strings only (but this isn't they case right now). 

For our consistency I think it would be nice to have a new task refactor the notification names so they all end with `_notification_title` ( like desktop has msgctxt of `in-app-notifications`) and are written in all caps.

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5257#-:-NhCQFycBmkBNEkJ7Tq9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
