### PR TITLE
Currently in use api access method should be visible in UI

### PR DESCRIPTION
**Pull request by rablador**
The API access method that is currently in use isn't marked as such in the list. We need to make sure that the user can see which method it is.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 20 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735)* status: 20 of 22 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Transport/TransportStrategy.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpOSpIp02BO1YoOn4Am:-NpOSpIp02BO1YoOn4An:b3uvolh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d75a04c6a8176b45c294c3b83b17f72a1b3b985/ios/MullvadREST/Transport/TransportStrategy.swift#L14)):*
> ```Swift
> import MullvadTypes
> 
> public class TransportStrategy: Equatable {
> ```

This needs to be turned back into a `struct`, otherwise we're violating the guarantees that `TransportProvider` won't be switching strategy for 2 requests mid flight
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpOR-KX3ywdDnCmJb7l:-NpOR-KX3ywdDnCmJb7m:b-rnqr9u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d75a04c6a8176b45c294c3b83b17f72a1b3b985/ios/MullvadRESTTests/TransportStrategyTests.swift#L55)):*
> ```Swift
> 
>     override func tearDownWithError() throws {
>         userDefaults.removePersistentDomain(forName: Self.suiteName)
> ```

If we get rid of `UserDefaults` we can rid of this and of its setup

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735)* status: 18 of 22 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/Transport/TransportStrategy.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpOSpIp02BO1YoOn4Am:-NpOXInt39qtem02ojxv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d75a04c6a8176b45c294c3b83b17f72a1b3b985/ios/MullvadREST/Transport/TransportStrategy.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This needs to be turned back into a `struct`, otherwise we're violating the guarantees that `TransportProvider` won't be switching strategy for 2 requests mid flight
</blockquote></details>

Done.
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpOR-KX3ywdDnCmJb7l:-NpOXILG26Iwqs0cxqbG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d75a04c6a8176b45c294c3b83b17f72a1b3b985/ios/MullvadRESTTests/TransportStrategyTests.swift#L55)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If we get rid of `UserDefaults` we can rid of this and of its setup
</blockquote></details>

Done.

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735)* status: 18 of 22 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpPCRVB8RkTP3JEg1C0:-NpPCRVC5IYd49EE9C7v:bliy2nr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30fc5e5049c7bcd1bdcb2c2519970ddb98f6b3ac/ios/MullvadSettings/AccessMethodRepository.swift#L35)):*
> ```Swift
>     }
> 
>     private let lastReachableAccessMethodSubject: CurrentValueSubject<PersistentAccessMethod?, Never> = .init(nil)
> ```

indeed it cannot be optional.it returns `direct` if there is no cached value.moreover you can use `PassthroughSubject` when there is no default value.



_Code snippet:_
```Swift
 private func readApiAccessMethodStore() -> PersistentAccessMethodStore {
        let parser = makeParser()

        do {
            let data = try SettingsManager.store.read(key: .apiAccessMethods)
            return try parser.parseUnversionedPayload(as: PersistentAccessMethodStore.self, from: data)
        } catch {
            logger.error("Could not load access method store: \(error)")
            return PersistentAccessMethodStore(lastReachableAccessMethod: directAccess, accessMethods: [])
        }
    }
    
    
    /// Persistent access method container model.
public struct PersistentAccessMethodStore: Codable {
    /// The last successfully reached access method.
    public var lastReachableAccessMethod: PersistentAccessMethod

    /// Persistent access method models.
    public var accessMethods: [PersistentAccessMethod]
}
```
___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpPFUgu3N8NtMYLyl-a:-NpPFUgu3N8NtMYLyl-b:b2qxarx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30fc5e5049c7bcd1bdcb2c2519970ddb98f6b3ac/ios/MullvadSettings/AccessMethodRepository.swift#L35)):*
> ```Swift
>     }
> 
>     private let lastReachableAccessMethodSubject: CurrentValueSubject<PersistentAccessMethod?, Never> = .init(nil)
> ```

for the consistency please use this way to initialise for both :



_Code snippet:_
```Swift
 private let lastReachableAccessMethodSubject = CurrentValueSubject<PersistentAccessMethod?, Never>(nil)
 
 private let accessMethodsSubject = CurrentValueSubject<[PersistentAccessMethod], Never>([])
 
```

**Review by buggmagnet — APPROVED** [review]
:lgtm: nice one !

> Reviewed 2 of 22 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-:-NpPX0Ge8byxz-_K4hXf:b-kgdyp9)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

**Review by mojganii — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpPCRVB8RkTP3JEg1C0:-NpPcErPCH7YryGYC-gZ:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30fc5e5049c7bcd1bdcb2c2519970ddb98f6b3ac/ios/MullvadSettings/AccessMethodRepository.swift#L35)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

indeed it cannot be optional.it returns `direct` if there is no cached value.moreover you can use `PassthroughSubject` when there is no default value.
</blockquote></details>

Fixed.
___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5735#-NpPFUgu3N8NtMYLyl-a:-NpPdowe0HYw_Mx_xBzS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30fc5e5049c7bcd1bdcb2c2519970ddb98f6b3ac/ios/MullvadSettings/AccessMethodRepository.swift#L35)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

for the consistency please use this way to initialise for both :
</blockquote></details>

Done.

**Pull request merged**
