### PR TITLE
Show error and troubleshoot dialog when lacking full disk access

### PR DESCRIPTION
**Pull request by raksooo**
Split tunneling on macOS requires the app to have "Full Disk Access". This PR adds an error informing the user when it is off and a troubleshoot dialog with instructions for how to enable it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301#-:-Nz7Wyg6BJKsqTLna_k-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`gui/src/shared/notifications/error.ts` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301#-Nz7X8nM9XTT9agknomW:-Nz7X8nM9XTT9agknomX:b-yxrbt4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8001578a8d3dff68fa36d13da2ea0ccc8d2aa15/gui/src/shared/notifications/error.ts#L293)):*
> ```XML
>           details: messages.pgettext(
>             'troubleshoot',
>             'Failed to enable split tunneling. This is usually caused by the mullvad daemon lacking file system permissions. Fix this by:',
> ```

I would remove "usually" here, since we know the exact reason in this case.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/locales/messages.pot` line 1094 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301#-Nz7i3Ib92Ps67VJBYGF:-Nz7i3Ib92Ps67VJBYGG:b-yl6pw6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/510d69d6cfd8e9a08b4d24204a18d6af671186bb/gui/locales/messages.pot#L1094)):*
> ```pot
> 
> msgctxt "notifications"
> msgid "Failed to enable split tunneling. Please try again or disable it."
> ```

"Try reconnecting"?

**Review by raksooo — COMMENTED** [review]
I added a condition that prevents the split tunneling troubleshoot dialog from being available on macOS since the description doesn't apply. Let's see if that error is common enough before spending time on an troubleshoot dialog.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301#-:-NzCi19UBYuTYhxJBgdj:b-goqfk3)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`gui/locales/messages.pot` line 1094 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301#-Nz7i3Ib92Ps67VJBYGF:-NzCiFYp51I3vD0RZLyQ:b4a8mb8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/510d69d6cfd8e9a08b4d24204a18d6af671186bb/gui/locales/messages.pot#L1094)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

"Try reconnecting"?
</blockquote></details>

Done. I also replaced "it" with "split tunneling".

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
