### PR TITLE
Add server ip overrides feature

### PR DESCRIPTION
**Pull request by Rawa**
This PR adds IP Overrides feature

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 57 of 57 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: all files reviewed, 13 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGfVcODwQiYKsRm-pL:-NtGfVcODwQiYKsRm-pM:b-w9rmee) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt#L16)):*
> ```Kotlin
>         Icon(
>             painter = painterResource(id = R.drawable.icon_info),
>             contentDescription = null,
> ```

This should probably be a parameter
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGf6pE9N5J5QhVdOh7:-NtGf6pE9N5J5QhVdOh8:b-acadvp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt#L17)):*
> ```Kotlin
>             painter = painterResource(id = R.drawable.icon_info),
>             contentDescription = null,
>             tint = MaterialTheme.colorScheme.onPrimary
> ```

Is this always used on primary? Otherwise this should be set as a parameter
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ServerIpOverridesCell.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGfhuY2NKhYwJqf4tu:-NtGfhuY2NKhYwJqf4tv:bqjpbev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ServerIpOverridesCell.kt#L42)):*
> ```Kotlin
>     inactiveColor: Color = MaterialTheme.colorScheme.error,
> ) {
>     Row(
> ```

Is there a reason this does not use `BaseCell` ?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGfxOYERulXP0NQLkL:-NtGfxOYERulXP0NQLkM:bs8p8z6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt#L36)):*
> ```Kotlin
>     AlertDialog(
>         containerColor = MaterialTheme.colorScheme.background,
>         confirmButton = {
> ```

This should be a confirm button and a dismiss button
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGg24N4pAMusz2wRb5:-NtGg24N4pAMusz2wRb6:blg621u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt#L54)):*
> ```Kotlin
>             Text(
>                 text = stringResource(id = R.string.server_ip_overrides_reset_title),
>                 color = MaterialTheme.colorScheme.onPrimary
> ```

This should be on background
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGglAfBQC5A9b8cWr9:-NtGglAfBQC5A9b8cWrA:b-alktem) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L120)):*
> ```Kotlin
> 
>     importByTextResult.OnNavResultValue(vm::importText)
>     clearAllOverrides.OnNavResultValue { vm.clearAllOverrides() }
> ```

I am not sure how we want to do this, but in custom lists I put this call in the delete confirmation dialog.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGhY1v0YPTfI4PBG-d:-NtGhY1v0YPTfI4PBG-e:bbimgjj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L173)):*
> ```Kotlin
>         actions = {
>             TopBarActions(
>                 state.overridesActive,
> ```

This could be a named argument as well?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGhkpzEetfYVYgpE2n:-NtGhkpzEetfYVYgpE2o:bc0irgz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L190)):*
> ```Kotlin
> 
>         Column(
>             modifier = modifier.animateContentSize(),
> ```

:clap: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Snackbar.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGiOtEAQryjSJ7xP2X:-NtGiOtEAQryjSJ7xP2Y:b6id1i5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Snackbar.kt#L8)):*
> ```Kotlin
> import kotlinx.coroutines.launch
> 
> suspend fun SnackbarHostState.showSnackBarDirect(
> ```

The name of this function is a bit confusing, do we show it with a delay usually?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGimMe0OAyCsN8QBRr:-NtGimMe0OAyCsN8QBRs:boxbl8y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L106)):*
> ```Kotlin
>     suspend fun applySettingsPatch(json: String) =
>         withContext(Dispatchers.IO) {
>             val deferred = async { messageHandler.events<ApplyJsonSettingsResult>().first() }
> ```

Is deferred really necessary here? What would happen without it?

Also we are using `Dispatchers.IO` here, but there is a dispatcher in the constructor.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGj4FK0Br6D3LkMOel:-NtGj4FK0Br6D3LkMOem:bm46qq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L99)):*
> ```Kotlin
> 
>         // Ensure we are responding to the correct request
>         if (requestCode == 0) {
> ```

Magical number?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ServerIpOverridesViewModel.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGjkzv-I_0PT0wYjYK:-NtGjkzv-I_0PT0wYjYL:b-c0fj0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ServerIpOverridesViewModel.kt#L57)):*
> ```Kotlin
>     private suspend fun applySettingsPatch(json: String) {
>         // Wait for daemon to come online since we might be paused
>         val connResult =
> ```

Is there a specific reason why we are waiting for connection result here? It is not required anywhere else.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 339 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGkZIO5RIBHxOtR9C8:-NtGkZIO5RIBHxOtR9C9:b-7f5d5s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/lib/resource/src/main/res/values/strings.xml#L339)):*
> ```XML
>     <string name="import_overrides_bottom_sheet_override_warning">Importing new overrides might replace some previously imported overrides.</string>
>     <string name="patch_not_matching_specification">Patch not matching specification</string>
>     <string name="settings_patch_error_invalid_or_missing_value">Invalid or missing value: \'%1$s\'</string>
> ```

Maybe more of a design question, but in custom lists I used normal quotation marks like "".

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: all files reviewed, 12 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGfVcODwQiYKsRm-pL:-NtGmXWACT3UfpXeDyAl:bz6pwqo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt#L16)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should probably be a parameter
</blockquote></details>

Good idea! Fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGf6pE9N5J5QhVdOh7:-NtGm__oAGUrRW6eAuzd:b-j4skz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/InfoIconButton.kt#L17)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is this always used on primary? Otherwise this should be set as a parameter
</blockquote></details>

True, fixing!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ServerIpOverridesCell.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGfhuY2NKhYwJqf4tu:-NtGnLCK9Vr93y3p38vC:bcf5hl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ServerIpOverridesCell.kt#L42)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is there a reason this does not use `BaseCell` ?
</blockquote></details>

Nope! Fixed!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGfxOYERulXP0NQLkL:-NtGr-To6Aymyv8FbSwt:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be a confirm button and a dismiss button
</blockquote></details>

Fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGg24N4pAMusz2wRb5:-NtGnWF61bC7AlM23nnB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIpOverridesConfirmationDialog.kt#L54)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be on background
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGhY1v0YPTfI4PBG-d:-NtGr_Dj6dpdPhysO7nI:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L173)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This could be a named argument as well?
</blockquote></details>

Fixed!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Snackbar.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGiOtEAQryjSJ7xP2X:-NtGrswRDpxsi80UGYrY:b-1q3ero) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Snackbar.kt#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

The name of this function is a bit confusing, do we show it with a delay usually?
</blockquote></details>

Discussed and fixed!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGimMe0OAyCsN8QBRr:-NtGshHH1ZWNw1QCakWo:b-wgawg5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L106)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is deferred really necessary here? What would happen without it?

Also we are using `Dispatchers.IO` here, but there is a dispatcher in the constructor.
</blockquote></details>

Probably wouldn't do much of a difference if we do not do deferred, but it feels more correct do listen before we execute the send. Otherwise if some one adds code in between at a later stage that takes time we might miss the message. E.g following scenario
- Send message
- Receive response
- Start listen, and wait forever.

Good catch! Thanks! :clap: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGj4FK0Br6D3LkMOel:-NtGtWty1myN5Aupztgi:b-6wy1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L99)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number?
</blockquote></details>

Yes! Reused from below, we should clearly define it. Fixed!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ServerIpOverridesViewModel.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGjkzv-I_0PT0wYjYK:-NtGu9ir7fCs8WsYaYdH:b-y0aaxs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ServerIpOverridesViewModel.kt#L57)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is there a specific reason why we are waiting for connection result here? It is not required anywhere else.
</blockquote></details>

Yes! There is, because we launch intent to open the FilePicker, which is not part of our activity, it means we will get paused, and also kill our connection to the daemon. So sending the message right away would mean that the Daemon is not connected to the UI and message would get lost. I'll clarify it in the the comment.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 339 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGkZIO5RIBHxOtR9C8:-NtGvLyX3hNC1nIP0emF:bol89of) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/lib/resource/src/main/res/values/strings.xml#L339)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe more of a design question, but in custom lists I used normal quotation marks like "".
</blockquote></details>

I'll switch over to `"` for now. :+1:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: 46 of 60 files reviewed, 12 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGglAfBQC5A9b8cWr9:-NtGySSU7i_YprnBX4FC:bvrm37w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L120)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I am not sure how we want to do this, but in custom lists I put this call in the delete confirmation dialog.
</blockquote></details>

Yeah, I think you are correct. If we ever want to introduce an error this would not be a nice experience. I've migrated it and created a new ViewModel for it.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIPOverridesConfirmationDialogTest.kt` line 34 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtH2toK5kC9gn_JyCOf:-NtH2toK5kC9gn_JyCOg:bb70w76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1be222fa7178da131c752ada7a78eb4de2f8e502/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/ResetServerIPOverridesConfirmationDialogTest.kt#L34)):*
> ```Kotlin
> 
>             // Assert
>             onNodeWithText(DELETE_TITLE.format(name)).assertExists()
> ```

Nice
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreenTest.kt` line 54 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtH350qBL_M63S-6S16:-NtH350r5lXEnGxvit3X:bg1vlm4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1be222fa7178da131c752ada7a78eb4de2f8e502/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreenTest.kt#L54)):*
> ```Kotlin
> 
>     @Test
>     fun testOverridesInactive() =
> ```

Why does all the tests start with `test`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ServerIpOverridesViewModel.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtGjkzv-I_0PT0wYjYK:-NtH3ojT6pPRr-k_5a79:b-1uepta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3522efc9ced223177a6698ce2b63378eeff4b574/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ServerIpOverridesViewModel.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yes! There is, because we launch intent to open the FilePicker, which is not part of our activity, it means we will get paused, and also kill our connection to the daemon. So sending the message right away would mean that the Daemon is not connected to the UI and message would get lost. I'll clarify it in the the comment.
</blockquote></details>

Ah that's understandable. :)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: 52 of 64 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreenTest.kt` line 54 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtH350qBL_M63S-6S16:-NtM4lI-DZwVas1KtQr6:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1be222fa7178da131c752ada7a78eb4de2f8e502/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreenTest.kt#L54)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Why does all the tests start with `test`?
</blockquote></details>

Fixed!

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-:-NtM6NTD68XBHNq_P960:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 57 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: 63 of 64 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`mullvad-jni/src/daemon_interface.rs` line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtMEwBA2DLV1RqBkysk:-NtMEwBA2DLV1RqBkysl:bq8bp4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c33e7045ceb5cfcabca3740a6302f80004ad0c/mullvad-jni/src/daemon_interface.rs#L34)):*
> ```XML
> 
>     #[error("Patch error")]
>     Patch(#[source] patch::Error),
> ```

You could replace `#[source]` with `#[from]` to get the `From<patch::Error for Error` for free :blush: 



_Code quote:_
```XML
    #[error("Patch error")]
    Patch(#[source] patch::Error),
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969)* status: 62 of 64 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98 and @Pururun)

___
*[`mullvad-jni/src/daemon_interface.rs` line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtMEwBA2DLV1RqBkysk:-NtMHNvE3z7TH8pWAyHR:b-70zze0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c33e7045ceb5cfcabca3740a6302f80004ad0c/mullvad-jni/src/daemon_interface.rs#L34)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

You could replace `#[source]` with `#[from]` to get the `From<patch::Error for Error` for free :blush:
</blockquote></details>

:raised_hands: thanks! Fixed now! :)

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-:-NtMIEZA88g-uCMmFMgl:bnfp4nl)* status: 63 of 64 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`mullvad-jni/src/daemon_interface.rs` line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5969#-NtMEwBA2DLV1RqBkysk:-NtMI9-337KuX-X2LLeM:bdeavht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c33e7045ceb5cfcabca3740a6302f80004ad0c/mullvad-jni/src/daemon_interface.rs#L34)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

:raised_hands: thanks! Fixed now! :)
</blockquote></details>

:fire:

**Pull request merged**
