### PR TITLE
Add iOS test making sure app functioning when API is down

### PR DESCRIPTION
**Pull request by niklasberglund**
Implemented test verifying that app is still functioning and can connect to a relay when the API is down. The simulation of API being down is not optimal. We have discussed it and decided to go for this way of simulating it for now. Might be improved in the future.

To test the changes run the test `testAppStillFunctioningWhenAPIDown` under `ConnectivityTests`. To simulate the the API being down all access methods are disabled and then a dummy access method is created to make API unreachable.

Duo to the extra setup and teardown steps the test function violates `function_body_length`(function body shouldn't be over 50 lines of code) so it is disabled for this test function.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 8 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: 8 of 26 files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nvl7kH4-FX4fCErZ-0k:-Nvl7kH4-FX4fCErZ-0l:b-1iti72) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17dc511a1764956a4264489033ae45204f94309f/ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift#L29)):*
> ```Swift
>     override func viewDidLayoutSubviews() {
>         super.viewDidLayoutSubviews()
>         navigationItem.backBarButtonItem?.accessibilityIdentifier = "asdasd"
> ```

Is this a good accessibility identifier name?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: 7 of 26 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nvl7kH4-FX4fCErZ-0k:-Nvq7RlDDXIiEjRtxgNU:b-1nwh25) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17dc511a1764956a4264489033ae45204f94309f/ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift#L29)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this a good accessibility identifier name?
</blockquote></details>

Was probably testing something out and forgot to remove 😄 Have removed the accessibility identifier, it was unused

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 23 of 26 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 6 unresolved discussions (waiting on @niklasberglund and @pinkisemils)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift` line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nvqog4zA5361MCb60UK:-Nvqog4zA5361MCb60UL:bpbpofq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift#L80)):*
> ```Swift
>         switchContainer.transform = CGAffineTransform(scaleX: 0.85, y: 0.85)
> 
>         if let accessibilityIdentifier = actualConfiguration.accessibilityIdentifier {
> ```

`accessibilityIdentifier` can be optional, so no need to check for existence.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3638 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nvqp90b9zTYdY9AC8JS:-Nvqp90b9zTYdY9AC8JT:byijcbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPN.xcodeproj/project.pbxproj#L3638)):*
> ```
> 				85C7A2E82B89024B00035D5A /* SettingsTests.swift */,
> 				85D039972BA4711800940E7F /* SettingsMigrationTests.swift */,
> 				8588F5C42BCD7FB000374D0B /* XCUIElement+Extensions.swift */,
> ```

Seems to be a duplicate.
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NvqpZp4-FPZeYhfPrBe:-NvqpZp52QlU2QOUf4Od:b-669maw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/ConnectivityTests.swift#L46)):*
> ```Swift
> 
>     // swiftlint:disable function_body_length
>     /// Test that the app is functioning when API is down. To simulate API being down we create a dummy access
> ```

Nit: "... method"?
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 127 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NvqqG7q4yBsr_qSQXx0:-NvqqG7q4yBsr_qSQXx1:b5q9ids) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/ConnectivityTests.swift#L127)):*
> ```Swift
> 
>     /// Toggle enabled switch for all existing access methods. It is a precondition that the app is currently showing API access view.
>     private func toggleAllAccessMethodsEnabledSwitch() {
> ```

Nit: The name is a little ambiguous. Reading the code and comment it's obvious what it does, but the name could suggest that you want to toggle all switches to be enabled.
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nw3a_3a3Y1odc3VpQQ_:-Nw3a_3a3Y1odc3VpQQa:b-2j5kh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L56)):*
> ```Swift
>     }
> 
>     func allowLocalNetworkAccess() {
> ```

This and the function below do almost the same thing. Are both necessary?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: 21 of 26 files reviewed, 6 unresolved discussions (waiting on @pinkisemils and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3638 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nvqp90b9zTYdY9AC8JS:-Nw56Er1BmJj48_-9zl7:b-f713kz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPN.xcodeproj/project.pbxproj#L3638)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Seems to be a duplicate.
</blockquote></details>

Ah yes. Removed duplicate reference.
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NvqpZp4-FPZeYhfPrBe:-Nw56L3y0eIpbGVTHxwr:b-vq5kk8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/ConnectivityTests.swift#L46)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: "... method"?
</blockquote></details>

Yes 😄 Added " method"
___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 127 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NvqqG7q4yBsr_qSQXx0:-Nw56S5m8O0bMb7hsDrT:b-xzoo29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/ConnectivityTests.swift#L127)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: The name is a little ambiguous. Reading the code and comment it's obvious what it does, but the name could suggest that you want to toggle all switches to be enabled.
</blockquote></details>

Agree, "enabled" is very close to "enable". It is the switch for toggling the "enable method" though. Would adding "method" in the name and documentation make it more clear? `toggleAllAccessmethodsEnableAccessMethodSwitch()` and documentation saying `Toggle enable method switch for all existing access methods. It is a precondition that the app is currently showing API access view.`

___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-Nw3a_3a3Y1odc3VpQQ_:-Nw57VOr4RPCRvx1831R:b6m7w0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L56)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This and the function below do almost the same thing. Are both necessary?
</blockquote></details>

Hmmmm good point. Actually its not used, only the conditional `allowLocalNetworkAccessIfAsked()` is used by test cases. Same goes for `allowAddVPNConfigurations` and `allowAddVPNConfigurationsIfAsked`.

The idea was that it's good to strictly make sure it is shown when we know it should be. But we never know.

**Review by rablador — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund and @pinkisemils)

___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 127 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NvqqG7q4yBsr_qSQXx0:-NwPfOUB0qcAVVAoyCZ8:b-ha6cvb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5eb7975a5ed3f0c96bbc0d9a4344a197ac2d08e/ios/MullvadVPNUITests/ConnectivityTests.swift#L127)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Agree, "enabled" is very close to "enable". It is the switch for toggling the "enable method" though. Would adding "method" in the name and documentation make it more clear? `toggleAllAccessmethodsEnableAccessMethodSwitch()` and documentation saying `Toggle enable method switch for all existing access methods. It is a precondition that the app is currently showing API access view.`

</blockquote></details>

I think perhaps adding rewording to `[...]Switches` would make it clearer, since we're toggling more than one.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NxDIPS-B_sGKoj3m0d_:-NxDIPS-B_sGKoj3m0da:b-xw6wto) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e6d57e21731428a062234886dfe034f67f0a5c5/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
This file should be reverted.

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: 25 of 26 files reviewed, 1 unresolved discussion (waiting on @pinkisemils and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NxDIPS-B_sGKoj3m0d_:-NxWT0dv5w2ZK92CR2Kt:b-px1yua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e6d57e21731428a062234886dfe034f67f0a5c5/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This file should be reverted.
</blockquote></details>

Reverted now

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 61 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NxX6C0MEUbPfaWhaHu2:-NxXEhcl4cZ0X_zYgTUw:b-x7h82o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d765a0cdc6c2de63f175794821346e1cc5a3a01/ios/MullvadVPNUITests/ConnectivityTests.swift#L61)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is not reliable since ownership and relay list can change in the future.
</blockquote></details>

What type of changes would break the test? The test connects to any(the first) Mullvad-owned relay the applies filter for rented only so that the connected relay is not part of the filter.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/ConnectivityTests.swift` line 61 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133#-NxX6C0MEUbPfaWhaHu2:-NxXo-mAETuPczNMeTOi:b-gfcmnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d765a0cdc6c2de63f175794821346e1cc5a3a01/ios/MullvadVPNUITests/ConnectivityTests.swift#L61)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

What type of changes would break the test? The test connects to any(the first) Mullvad-owned relay the applies filter for rented only so that the connected relay is not part of the filter.
</blockquote></details>

Ah, my bad, I missed that you filter owned relays first. Nevermind!

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6133)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
