### PR TITLE
Use ticker flow for Android system notifications

### PR DESCRIPTION
**Pull request by kl**
This PR makes the Android system notifications reactive by using the `AccountExpiryTicker.tickerFlow` which is also used for the in-app notifications.

Before this change there was an issue where the app would not post any account time expiry warning notifications if the app was on in the background without being restarted (e.g. when the always on VPN feature is used).

The Android notifications now work as follows:

1. The user has more time left than the account expiry warning threshold (currently 3 days) == no notification is posted.
2. The user's time goes within the account expiry warning threshold == a user visible notification is posted.
3. (alternative A) The user **does not cancel (swipe away)** the notification, and the update interval time is passed (currently 24 hours) == the existing notification remaining time text is silently updated in the background 
4. (alternative B) The user **cancels (swipes away)** the notification, and the update interval time is passed (currently 24 hours) == a new user visible notification is posted.
5. The user adds more time their account == the existing notification is cancelled
6. The user's remaining time is within the warning threshold and the user logs out/force closes the app and then logs in/restarts the app == when in the logged out state/terminated app state no notification is shown, and when coming back to the  logged in state/started app state a new user visible notification is posted.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177#-OBf5vme1UzbEWrHhhV9:-OBfPDwQCpBnzTYQhC_t:b-896fix):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Don't forget to add a entry in our Changelog :pray:
</blockquote></details>

Done.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177#-OBdz0xm1rj7D9RonC_F:-OBfPFkPChKyNfQ95mIm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b28ef44ab4fc81921851fd44d80f53f24fddf32/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

A bit hidden a way imo, looks like this is only used once we might as well put it directly into the place where it is used.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177#-:-OBiiJjCCKZjgKf7OePz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
