### PR TITLE
Add transform-builtin-extend babel plugin to allow extending Error class

### PR DESCRIPTION
**Pull request by pinkisemils**
The root cause for not displaying the window on startup when the app can't _autologin_ is that the error handling code was trying to assert `e instanceof BackendError` before displaying the window. Since `BackendError` extends `Error`, by default any instance of `BackendError` will have the class metadata of `Error`, or so I understand it. To fix this, I've added a babel plugins that enables the behaviour we expect, as instructed by @pronebird.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/134)

### CODE REVIEW

**Comment by pinkisemils** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[.babelrc, line 7 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134#-LAO4DJL1qN6_HC41taY:-LAO4DJL1qN6_HC41taZ:b-gsumm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a266647ae20d622f233f25b0b2314cdc4d512e8c/.babelrc#L7)):*
> ```JSON5
>       "plugins": ["transform-runtime", "inline-react-svg", ["transform-builtin-extend", { "globals": ["Error"] }]]
>     },
>     "development": {
> ```

Is this environment used at all?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134)*

**Comment by pronebird** [comment]
Just verify that `instanceof` really works. You can create `new BackendError(..)` manually if needed for testing.  :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134#-:-LAO9KuDAibrgEiM6Kr-:bug7qa2)*

**Comment by pinkisemils** [comment]
I did check it on startup and it does work.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134#-:-LAOA7MH6K7psuLR5qc3:b-12q3tu)*

**Comment by faern** [comment]
Awesome if this fixes the problem :+1:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134#-:-LAOI67R3hpe9vf7Em7P:b-7g3cu0)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134)*

**Comment by pronebird** [comment]
:lgtm_strong:  is strong

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134#-:-LAPZXFFCYP69E1Syk3H:b-gatqcg)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/134)*

**Pull request merged**
