### PR TITLE
Add relay ip override e2e tests

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028)

### CODE REVIEW

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028#-:-Nu-8ZTl-91orZw5vwOl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`test/test-manager/src/tests/relay_ip_overrides.rs` line 352 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028#-NuTi-y-5fFBBx22j8ua:-NuTi-y0CU18Ytp7RUBk:bkpzrb3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/121af32ca609489bfea1b7b22c134a2c74b1fc08/test/test-manager/src/tests/relay_ip_overrides.rs#L352)):*
> ```XML
> /// Returns a handle that will stop the proxy when dropped.
> async fn spawn_tcp_proxy(destination: SocketAddr, port: u16) -> anyhow::Result<AbortOnDrop<()>> {
>     let socket = TcpListener::bind((Ipv4Addr::UNSPECIFIED, port)).await?;
> ```

On further inspection, I don't think that we should bind to [_all local interfaces_](https://www.man7.org/linux/man-pages/man7/ip.7.html) - just the temporary bridge interface created for running the tests.

On Linux, there is this constant network called `test_manager::vm::network::linux::TEST_SUBNET` which could be used to only bind to the bridge interface on the host. The caveat is that this constant is not available on macOS,  but a hacky way to define it would be to let it equal `NON_TUN_GATEWAY`.

Anyway, I suggest changing `Ipv4Addr::UNSPECIFIED` to `TEST_SUBNET`:
```rust
let socket = TcpListener::bind((TEST_SUBNET.ip(), port)).await?;
```

This comment is true for the UDP-socket created in `spawn_udp_proxy` as well :blush:



_Code quote:_
```XML
let socket = TcpListener::bind((Ipv4Addr::UNSPECIFIED, port)).await?;
```

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/relay_ip_overrides.rs` line 352 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028#-NuTi-y-5fFBBx22j8ua:-NuUOMg15l35Kf_7ZqRf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/121af32ca609489bfea1b7b22c134a2c74b1fc08/test/test-manager/src/tests/relay_ip_overrides.rs#L352)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

On further inspection, I don't think that we should bind to [_all local interfaces_](https://www.man7.org/linux/man-pages/man7/ip.7.html) - just the temporary bridge interface created for running the tests.

On Linux, there is this constant network called `test_manager::vm::network::linux::TEST_SUBNET` which could be used to only bind to the bridge interface on the host. The caveat is that this constant is not available on macOS,  but a hacky way to define it would be to let it equal `NON_TUN_GATEWAY`.

Anyway, I suggest changing `Ipv4Addr::UNSPECIFIED` to `TEST_SUBNET`:
```rust
let socket = TcpListener::bind((TEST_SUBNET.ip(), port)).await?;
```

This comment is true for the UDP-socket created in `spawn_udp_proxy` as well :blush:
</blockquote></details>

Done.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028#-:-NuXuH4X5WIh-Z9JD_cw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`test/test-manager/src/tests/relay_ip_overrides.rs` line 352 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028#-NuTi-y-5fFBBx22j8ua:-NuXuDwz9VhGOoXW0P0e:bcjygnp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/121af32ca609489bfea1b7b22c134a2c74b1fc08/test/test-manager/src/tests/relay_ip_overrides.rs#L352)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice! :fire:

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028#-:-Nuwwlie-FFf5Md7yKZQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
