### PR TITLE
Improve changelog dialog

### PR DESCRIPTION
**Pull request by Pururun**
- Replace hardcoded font sizes and colors
- Place it within AppTheme so that corner radius are the same as other dialogs.
- Make it scrollable
- Change some text styles to be more in line with design

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-Net2AbW1UcANJcZkqfv:b-7u4wc8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fd9c4b98b0282461cb0b9610990b903d3f1aaba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
> ```Kotlin
> private fun ChangeListItem(text: String) {
> 
>     ConstraintLayout {
> ```

Did you consider switching from `ConstraintLayout` when cleaning up the code? @Rawa has shared some good reasons for why it might be good to avoid `ConstraintLayout` and instead work with more Compose-native Composables. Not saying saying it's a must for this PR though!



_Code quote:_
```Kotlin
ConstraintLayout
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-NetFQd24HROcV3k29vw:bughr9n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fd9c4b98b0282461cb0b9610990b903d3f1aaba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Did you consider switching from `ConstraintLayout` when cleaning up the code? @Rawa has shared some good reasons for why it might be good to avoid `ConstraintLayout` and instead work with more Compose-native Composables. Not saying saying it's a must for this PR though!
</blockquote></details>

No I did not, but I think it would be good idea :)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-NeveDOo6lgTgEL1NzmT:b-ehmkdo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f1bc7693f58da1ce7eac6b47ebd3ef61690726c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

No I did not, but I think it would be good idea :)
</blockquote></details>

Yeah, usually ConstraintLayout is overkill in compose, there are places were it makes sense but most things are possible to accomplish without them.

**Review by sabercodic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-:-New3lVG2gKTEvz_pJMb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-New3YUOCxAV8ox_FVYQ:be51voh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f1bc7693f58da1ce7eac6b47ebd3ef61690726c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yeah, usually ConstraintLayout is overkill in compose, there are places were it makes sense but most things are possible to accomplish without them.
</blockquote></details>

Nice improvement! Just make sure it looks the same as before.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-New97PR2fki0aM7xfMt:b-dph30w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f1bc7693f58da1ce7eac6b47ebd3ef61690726c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nice improvement! Just make sure it looks the same as before.
</blockquote></details>

It actually looks better (more in line with design...)

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-NewA2g91lhMQ_AbDN_c:b-q7u4um) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f1bc7693f58da1ce7eac6b47ebd3ef61690726c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It actually looks better (more in line with design...)
</blockquote></details>

I don't doubt that! :smile: To clarify, I mean specifically that the bullet list gets correctly formatted, for example when an items break multiple lines such as this:

```
* This is a long changelist item
  covering mutiple lines according
  to the design spec.
```

```
* This is a long changelist item
covering mutiple lines which is
not according to the design spec.
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5177#-Net2AbW1UcANJcZkqfu:-NewFL4xDduhOsDuii6i:brifvv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f1bc7693f58da1ce7eac6b47ebd3ef61690726c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L73)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I don't doubt that! :smile: To clarify, I mean specifically that the bullet list gets correctly formatted, for example when an items break multiple lines such as this:

```
* This is a long changelist item
  covering mutiple lines according
  to the design spec.
```

```
* This is a long changelist item
covering mutiple lines which is
not according to the design spec.
```
</blockquote></details>

Ah I understand. Yes I checked that it was formatted according to design. :)

**Comment by mullmat** [comment]
Corner radius on the change log dialog looks wrong, what radius is defined? 😃

**Comment by Pururun** [comment]
> Corner radius on the change log dialog looks wrong, what radius is defined? 😃

Fixed in: https://github.com/mullvad/mullvadvpn-app/pull/5186

**Pull request merged**
