### PR TITLE
Add foundation for new connection view

### PR DESCRIPTION
**Pull request by rablador**
In order to work incrementally and in parallel we should first create a basic implementation that can act as a foundation for coming work. It doesn't have to be stateful.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3913 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODojNL33Jyi84j5j7l_:-ODojNL33Jyi84j5j7la:bv37blg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6dabbf18c8e9ca3c9b0d37955b8d1bb545c62773/ios/MullvadVPN.xcodeproj/project.pbxproj#L3913)):*
> ```
> 			sourceTree = "<group>";
> 		};
> 		7A0EAE982D01B29E00D3EB8B /* Recovered References */ = {
> ```

This should be deleted

**Review by buggmagnet — COMMENTED** [review]
Except for the hiccup in the project structure, looks good !

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-:-ODojVzl6f7aVlQb4FC9:b-95tkx0)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3913 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODojNL33Jyi84j5j7l_:-ODopVn-E5LSXRJR2lKL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7e4fd638778b6b888ffa4d309b4d485eaa7f386/ios/MullvadVPN.xcodeproj/project.pbxproj#L3913)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be deleted
</blockquote></details>

Done.

**Review by buggmagnet — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-:-ODp2ItCEH04FWD1lJDS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: all files reviewed, 13 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q:-ODotBA_0KqXZmMiRa2r:b-cawspp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L18)):*
> ```Swift
>             BlurView()
> 
>             VStack(alignment: .leading, spacing: 16) {
> ```

we already have property for that ' UIMetrics.padding16'
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotmEQBLGP0u-tM7Zr:-ODotmEQBLGP0u-tM7Zs:b-zc9wmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L22)):*
> ```Swift
>                 ButtonPanel()
>             }
>             .padding(16)
> ```

same above for the rest
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODovgoN3yt71t5_qsw1:-ODovgoN3yt71t5_qsw2:bkbgm60) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L28)):*
> ```Swift
>         // Importing UIView in SwitftUI (see BlurView) has sizing limitations, so we need to help the view
>         // understand its width constraints.
>         .frame(maxWidth: UIScreen.main.bounds.width)
> ```

does the comment imply that we can't use `.frame(width: .infinity)`
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODov4V44tpJwSJbQCop:-ODov4V44tpJwSJbQCoq:blxuapk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L36)):*
> ```Swift
>         VStack {
>             Spacer()
>             ConnectionView()
> ```

for making rendering  faster I suggest to shorten preview code with :



_Code snippet:_
```Swift
#Preview {
    ConnectionView()
        .background(UIColor.secondaryColor.color)
}
```
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODow9iv1WI6i5Rct0xC:-ODow9iv1WI6i5Rct0xD:b-u98msj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L43)):*
> ```Swift
> }
> 
> private struct BlurView: View {
> ```

I really recommend to make a separate file for this reusable class and make it public or internal.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoy0SZ0aqXkM2CQcDW:-ODoy0SZ0aqXkM2CQcDX:b-5t5ri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L60)):*
> ```Swift
>                 .font(.title3.weight(.semibold))
>                 .foregroundStyle(UIColor.successColor.color)
>                 .padding(.bottom, 4)
> ```

let's use UIMetrics's paddings when they are already there.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoyAG84xsZr6VBUXao:-ODoyAG84xsZr6VBUXap:b-865elj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L61)):*
> ```Swift
>                 .foregroundStyle(UIColor.successColor.color)
>                 .padding(.bottom, 4)
>             Text("Country, City")
> ```

don't forget to use localized string and this goes for the rest strings :



_Code snippet:_
```Swift
LocalizedStringKey("City")
```
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2J5w9fs1PUQbmKwn:-ODp2J5xCdYZTk0eTg8r:b-15mf8u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L75)):*
> ```Swift
>         VStack(spacing: 16) {
>             SplitMainButton(
>                 text: "Switch location",
> ```

`Localization` should be considered.
___
*[`ios/MullvadVPN/Views/MainButtonStyle.swift` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2svkCK6ImkwLUBdv:-ODp2svkCK6ImkwLUBdw:b-6qckve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/MainButtonStyle.swift#L20)):*
> ```Swift
>     func makeBody(configuration: Configuration) -> some View {
>         configuration.label
>             .padding(.horizontal, 8)
> ```

let's use padding we already have in UIMetrics.
___
*[`ios/MullvadVPN/Views/SplitMainButton.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp36lW1uVIAm8kulwT:-ODp36lW1uVIAm8kulwU:bi64xfi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/SplitMainButton.swift#L12)):*
> ```Swift
> 
> struct SplitMainButton: View {
>     var text: String
> ```

Localization
___
*[`ios/MullvadVPN/Views/SplitMainButton.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp3Iqm8WbhzZQN8Qcp:-ODp3Iqm8WbhzZQN8Qcq:b-1vtcst) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/SplitMainButton.swift#L35)):*
> ```Swift
>                     .resizable()
>                     .scaledToFit()
>                     .padding(4)
> ```

there is a value for that in UIMetrics
___
*[`ios/MullvadVPN/Views/MainButton.swift` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2WNBAphWDnntbwjS:-ODp2WNBAphWDnntbwjT:b3m3g6t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/MainButton.swift#L2)):*
> ```Swift
> //
> //  Untitled.swift
> ```

//  MainButton.swift
___
*[`ios/MullvadVPN/Views/MainButton.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2jyn3nzUq_PFARcK:-ODp2jyo0AC3Tk_yn4lr:bl1ecug) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/MainButton.swift#L12)):*
> ```Swift
> 
> struct MainButton: View {
>     var text: String
> ```

localization is forgotten.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: 7 of 8 files reviewed, 13 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q:-ODp60B5Dx1zA0Obd6Ro:b-nipmso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L18)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we already have property for that ' UIMetrics.padding16'
</blockquote></details>

I know, but I don't think `.padding16` helps very much. The name implies that it can never be anything but 16, which means that it's basically just a hard coded value in the form of a constant (for the sake of being a constant). If it was `UIMetrics.ConnectionViewSpacing` or similar, we could have taken advantage of it being more "dynamic" and not using hard coded values.

Also, since `ConnectionView` is not generic and reused anywhere else it doesn't matter if we use specific hardcoded values in certain places I think.

I'm not totally against making changes, but I think it deserves a discussion. What does @acb-mv @buggmagnet think?
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotmEQBLGP0u-tM7Zr:-ODp82Bb9fRv2NGXGPws:b-nrifiu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L22)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

same above for the rest
</blockquote></details>

Discussion in https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q above.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODovgoN3yt71t5_qsw1:-ODp7YQgAD_wEaT2qlrN:bxfzpes) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L28)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

does the comment imply that we can't use `.frame(width: .infinity)`
</blockquote></details>

Yes, but thanks to the snippet you sent me before we can get rid of this. It will be changed in an upcoming PR. :)
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODov4V44tpJwSJbQCop:-ODp7h3Y9uK5CpEVoWAb:b-vjte7f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L36)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

for making rendering  faster I suggest to shorten preview code with :
</blockquote></details>

We could, but it would not show the connection view at the bottom of the screen like in production. I'm fine either way and can change it if you insist. :)
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODow9iv1WI6i5Rct0xC:-ODp7vcK9TZ_A40-_Km4:b-9bofvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L43)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I really recommend to make a separate file for this reusable class and make it public or internal.
</blockquote></details>

I agree. It has been fixed in an upcoming PR.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoy0SZ0aqXkM2CQcDW:-ODp8-xU-gaIJW_PZEnx:b-nrifiu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L60)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's use UIMetrics's paddings when they are already there.
</blockquote></details>

Discussion in https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q above.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoyAG84xsZr6VBUXao:-ODp8C7A1yUQWioxg572:b-hjj2um) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L61)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

don't forget to use localized string and this goes for the rest strings :
</blockquote></details>

There's a TODO at the top of the file addressing this. All hard coded texts will be replaced with proper localized texts in an upcoming PR.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2J5w9fs1PUQbmKwn:-ODp8Lut2YOOGIaT8MOa:b-59ncl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L75)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

`Localization` should be considered.
</blockquote></details>

See https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoyAG84xsZr6VBUXao
___
*[`ios/MullvadVPN/Views/MainButton.swift` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2WNBAphWDnntbwjS:-ODp8qHgAXTj4Ow7CI4E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/MainButton.swift#L2)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

//  MainButton.swift
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Views/MainButton.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2jyn3nzUq_PFARcK:-ODp8U8o56Onj0AcXgin:b-59ncl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/MainButton.swift#L12)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

localization is forgotten.
</blockquote></details>

See https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoyAG84xsZr6VBUXao
___
*[`ios/MullvadVPN/Views/MainButtonStyle.swift` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp2svkCK6ImkwLUBdv:-ODp8kGU8J9WJaCGNyiE:b-nrifiu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/MainButtonStyle.swift#L20)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's use padding we already have in UIMetrics.
</blockquote></details>

Discussion in https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q above.
___
*[`ios/MullvadVPN/Views/SplitMainButton.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp36lW1uVIAm8kulwT:-ODp8WxX9WDE6NQyrEeN:b-59ncl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/SplitMainButton.swift#L12)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Localization
</blockquote></details>

See https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODoyAG84xsZr6VBUXao
___
*[`ios/MullvadVPN/Views/SplitMainButton.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODp3Iqm8WbhzZQN8Qcp:-ODp8l6i8d1XF4-6TNtj:b-nrifiu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/Views/SplitMainButton.swift#L35)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

there is a value for that in UIMetrics
</blockquote></details>

Discussion in https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q above.

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: 7 of 8 files reviewed, 13 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q:-ODpOvGrCTmJsEQhxauB:bgus83b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L18)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I know, but I don't think `.padding16` helps very much. The name implies that it can never be anything but 16, which means that it's basically just a hard coded value in the form of a constant (for the sake of being a constant). If it was `UIMetrics.ConnectionViewSpacing` or similar, we could have taken advantage of it being more "dynamic" and not using hard coded values.

Also, since `ConnectionView` is not generic and reused anywhere else it doesn't matter if we use specific hardcoded values in certain places I think.

I'm not totally against making changes, but I think it deserves a discussion. What does @acb-mv @buggmagnet think?
</blockquote></details>

I think `padding16` is a slightly silly name. If it's going to be a number, it should refer not to the number of pixels but something like a multiple of a grid unit or something, though if so, that would be a question for Carl.  If we're not using numbers (and arguably we shouldn't be), the name should refer to where it's used: `ConnectionViewSpacing` could be a candidate, though finding other use cases we have something in common with and naming the constant after them would be better.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: 7 of 8 files reviewed, 13 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q:-ODpaKRoAJAIKe8ZHO-N:b1b4ir6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L18)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

I think `padding16` is a slightly silly name. If it's going to be a number, it should refer not to the number of pixels but something like a multiple of a grid unit or something, though if so, that would be a question for Carl.  If we're not using numbers (and arguably we shouldn't be), the name should refer to where it's used: `ConnectionViewSpacing` could be a candidate, though finding other use cases we have something in common with and naming the constant after them would be better.
</blockquote></details>

At some point in the past, we decided that if a magic number appears in a single file, and within a specific context, we should leave it as that, since it's usually self explanatory.

Semantics are usually important, and I think calling a spacing "padding" would be semantically incorrect, therefore I agree that we should not use `padding 16` 

@acb-mv we came up with the nomenclature `paddingX` (where X is a number) to add some context instead of using said number as a result of a discussion where we didn't want to have magic numbers peppered through the codebase. 

I agree that the name is not the best, but sometimes we do need a generic number that we reuse in different contexts where `ConnectionViewSpacing` would be misleading instead of a more generic `paddingX` 

Overall, I think we can leave that as is.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)* status: 7 of 8 files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODov4V44tpJwSJbQCop:-ODprU3h1PmObNBnPHQ2:bduy7xq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L36)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I don't insist but I think for subviews we shouldn't have cared about the position it's gonna take in the future
</blockquote></details>

I changed it!

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-:-ODpwOus4hI7-0SViGmw:bnfp4nl)* status: 6 of 8 files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift` line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotmEQBLGP0u-tM7Zr:-ODpvoX65f2EO2c6x5j8:b-pp7dy2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457ae0261897818bab62dd970b4d72de54c25c41/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView.swift#L22)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Discussion in https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290#-ODotBA_0KqXZmMiRa2q above.
</blockquote></details>

I'm fully aware of that discussion, my point is if we are not going to use them, then we have to remove them.

**Pull request merged**
