### PR TITLE
Core listitem views

### PR DESCRIPTION
**Pull request by axti**
With this PR we create core list item views for present different types of data and handle interaction with them. 
Views will be used in lists with adapter.
Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 7 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 7 of 22 files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUn99ci3OlTNVYciilD:-MUn99cj7T7Iejw5eGhn:bweh51y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L18)):*
> ```Kotlin
>     defStyleRes: Int = 0
> ) : ConstraintLayout(context, attrs, defStyleAttr, defStyleRes) {
>     private val inflater: LayoutInflater = LayoutInflater.from(context)
> ```

Is the inflater only used once? Shouldn't it be a local variable inside `init` instead of a property?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUn9OHm3cMOdEtELGKk:-MUn9OHn-k_HYmQE-O-b:b-6sy7c9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L22)):*
> ```Kotlin
>     protected abstract val layoutRes: Int
>     @get:DimenRes
>     protected abstract val heightRes: Int?
> ```

These two properties (`layoutRes` and `heightRes`) seem to only be used inside the `init` block. Wouldn't it make more sense to have them as constructor parameters?

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUn9OHm3cMOdEtELGKk:-MUnAW9m1dgB5SlcxfCe:b-rcy5ak) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L22)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

These two properties (`layoutRes` and `heightRes`) seem to only be used inside the `init` block. Wouldn't it make more sense to have them as constructor parameters?
</blockquote></details>

I think we already had conversation about this in another PR. Let me check.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUn99ci3OlTNVYciilD:-MUnBLb38JJXgWfD0Ba6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L18)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is the inflater only used once? Shouldn't it be a local variable inside `init` instead of a property?
</blockquote></details>

Done.

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 7 of 22 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 14 of 22 files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MUtS0Ru1KPSN-kY2EHi:b5phama) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
> ```XML
>                                                 android:orientation="vertical"
>                                                 app:layout_constraintGuide_begin="@dimen/screen_vertical_margin" />
>     <androidx.constraintlayout.widget.Barrier android:id="@+id/widgetBarrier"
> ```

I don't understand why this barrier is necessary. I only see it used in `itemText`, and it seems that it could be replaced with `parent`. Is there something I'm missing?

**Review by jvff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 14 of 22 files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/res/layout/list_item_group_divider.xml, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtWmL9EJR_jr1SMC_K:-MUtWmL9EJR_jr1SMC_L:bn39kqb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_group_divider.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

This doesn't seem to be used anywhere.

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_group_divider.xml, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtWmL9EJR_jr1SMC_K:-MUtYV_47qhULoRFjitQ:b-z2ymyz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_group_divider.xml#L1)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This doesn't seem to be used anywhere.
</blockquote></details>

Forgot to push DividerGroupListItemView

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MUtZBGi-r17RkE1JI3w:bjc32xi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I don't understand why this barrier is necessary. I only see it used in `itemText`, and it seems that it could be replaced with `parent`. Is there something I'm missing?
</blockquote></details>

It is helped to manage right barrier for text or text container without extra manipulations.

**Review by jvff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 14 of 22 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/res/layout/list_item_action.xml, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtivJX7pmpXsAlglWV:-MUtivJX7pmpXsAlglWW:b-8gedsm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_action.xml#L23)):*
> ```XML
>                                                 android:orientation="vertical"
>                                                 app:layout_constraintGuide_end="@dimen/cell_right_padding" />
>     <androidx.constraintlayout.widget.Barrier android:id="@+id/widgetBarrier"
> ```

This barrier doesn't seem to be referenced anywhere in the layout. Maybe I misunderstood how barriers work, aren't they just like guidelines?
___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MUtimTK3D2T5aPt5kag:bbu5ehq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

It is helped to manage right barrier for text or text container without extra manipulations.
</blockquote></details>

What's the difference from using just `parent`?

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MUtjb3r771YxNmpthxn:b-dc31ef) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

What's the difference from using just `parent`?
</blockquote></details>

There are 3 cases I can see:
1) When we have a text and want to have end margin
2) When we have `widget` and what align text to widget if exist or to the margin
3) When we have spliced item with different actions on the item and widget (for example in RelayList), so we align container to the widget.

**Review by jvff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 14 of 22 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MUtmfLr0gsMrvgNKEYA:b-1fyknw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

There are 3 cases I can see:
1) When we have a text and want to have end margin
2) When we have `widget` and what align text to widget if exist or to the margin
3) When we have spliced item with different actions on the item and widget (for example in RelayList), so we align container to the widget.
</blockquote></details>

Do any of the three cases happen here?

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_action.xml, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtivJX7pmpXsAlglWV:-MUwPvhjB94DpQPC26Op:b-24aag3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_action.xml#L23)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This barrier doesn't seem to be referenced anywhere in the layout. Maybe I misunderstood how barriers work, aren't they just like guidelines?
</blockquote></details>

It is used from `list_item_base`

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MUwQ7SYCWqBU6DTcfOO:b-o843ot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Do any of the three cases happen here?
</blockquote></details>

Yes, since this is a base part it reused and merged into another layouts, with some extra components.

**Review by jvff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 14 of 22 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/res/layout/list_item_action.xml, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtivJX7pmpXsAlglWV:-MUwh4P466C1NwbQMB_z:b-i9k3dt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_action.xml#L23)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

It is used from `list_item_base`
</blockquote></details>

But then there are two `Barriers` with the same `widgetBarrier` ID?

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_action.xml, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtivJX7pmpXsAlglWV:-MUwvIUH5wGMqieWUj3Z:b2nign6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_action.xml#L23)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

But then there are two `Barriers` with the same `widgetBarrier` ID?
</blockquote></details>

yes

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_group_divider.xml, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtWmL9EJR_jr1SMC_K:-MUxMedw-_YKD67KYnhN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_group_divider.xml#L1)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Forgot to push DividerGroupListItemView
</blockquote></details>

Done.

**Review by jvff — COMMENTED** [review]
> Reviewed 5 of 22 files at r1, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/TwoActionListItemView.kt, line 18 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MVWqZw107AzbP20Yrr4:-MVWqZw27FH5eiALiCXG:b1lfm09) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457d2eb5bfb6978150e637e1a5ff9690e61c5f84/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/TwoActionListItemView.kt#L18)):*
> ```Kotlin
>     }
> 
>     private val container: ViewGroup = findViewById(R.id.container_without_widget)
> ```

Nit: Could we have the `container` property declared at the start of the class? Because it runs before `init`, so I think moving it avoids any confusion.
___
*[android/src/main/res/layout/list_item_action.xml, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtivJX7pmpXsAlglWV:-MUxCOt3CyvsuScnejR2:b2r3h36) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_action.xml#L23)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

yes
</blockquote></details>

As we discussed on call, I now understand that only the most specific widget gets created, so it's not a problem to have two with the same IDs in different layouts that are merged.
___
*[android/src/main/res/layout/list_item_base.xml, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MUtS0Rs0xB91sbPlFE_:-MVWTKe79OhkbTGPv-ci:bhv5sl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af8d2debe660c0626f6ce87b8f25285459256044/android/src/main/res/layout/list_item_base.xml#L36)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Yes, since this is a base part it reused and merged into another layouts, with some extra components.
</blockquote></details>

As discussed on call, I now understand that this is so we can have the widget go to the end of the view (and not until the margin).

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/res/layout/list_item_two_action.xml, line 22 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MVXH7JPCE1Wtpj1XQAp:-MVXH7JPCE1Wtpj1XQAq:b-dmndpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457d2eb5bfb6978150e637e1a5ff9690e61c5f84/android/src/main/res/layout/list_item_two_action.xml#L22)):*
> ```XML
>                  android:layout_height="0dp"
>                  android:background="?android:attr/selectableItemBackground"
>                  android:paddingStart="@dimen/cell_right_padding"
> ```

Shouldn't this be `cell_left_padding`?

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_two_action.xml, line 22 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MVXH7JPCE1Wtpj1XQAp:-MV_JdzG54beb08so3hm:b-rpghg1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457d2eb5bfb6978150e637e1a5ff9690e61c5f84/android/src/main/res/layout/list_item_two_action.xml#L22)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Shouldn't this be `cell_left_padding`?
</blockquote></details>

If we will have different padding the widget will not be centred. 
cell_right_padding = 16dp, but cell_left_padding = 22dp.
16dp is a perfect padding for the widget, but maybe I should create separate dimen alias?

**Comment by axti** [comment]
___
*[android/src/main/res/layout/list_item_two_action.xml, line 22 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MVXH7JPCE1Wtpj1XQAp:-MV_LwL9BT6S0QBPz97f:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457d2eb5bfb6978150e637e1a5ff9690e61c5f84/android/src/main/res/layout/list_item_two_action.xml#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

If we will have different padding the widget will not be centred. 
cell_right_padding = 16dp, but cell_left_padding = 22dp.
16dp is a perfect padding for the widget, but maybe I should create separate dimen alias?
</blockquote></details>

Done.

**Review by axti — COMMENTED** [review]
> Reviewed 9 of 22 files at r1, 5 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: 20 of 24 files reviewed, 1 unresolved discussion (waiting on @axti and @jvff)

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-:-MVaE-OU7y7GeLpNUjW6:bnfp4nl)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @axti)

___
*[android/src/main/res/layout/list_item_two_action.xml, line 22 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526#-MVXH7JPCE1Wtpj1XQAp:-MVaDkba42jXroqLCUts:b-xhtseo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/457d2eb5bfb6978150e637e1a5ff9690e61c5f84/android/src/main/res/layout/list_item_two_action.xml#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah that makes sense. Having it have it's own name makes it better :D

**Review by jvff — APPROVED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2526)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
