### PR TITLE
Refactor screens to use preview parameter provider

### PR DESCRIPTION
**Pull request by kl**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810)* status: all files reviewed, 4 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/FilterUiStatePreviewParameterProvider.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73JujhA4R58CNgBds-:-O73JujhA4R58CNgBds0:bi33vwh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/FilterUiStatePreviewParameterProvider.kt#L9)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.ProviderId
> 
> val PROVIDER = Provider(providerId = ProviderId("provider1"), ownership = Ownership.MullvadOwned)
> ```

Private?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/SelectLocationsUiStatePreviewParameterProvider.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73JpprDrDsFFZKNrYG:-O73JpprDrDsFFZKNrYH:b-t3obz6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/SelectLocationsUiStatePreviewParameterProvider.kt#L17)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.RelayItem
> 
> val RELAY =
> ```

Could this also be private?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/VpnSettingsUiStatePreviewParameterProvider.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73K8_L7clMhag0Cz0D:-O73K8_L7clMhag0Cz0E:b-okitfl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/VpnSettingsUiStatePreviewParameterProvider.kt#L39)):*
> ```Kotlin
>                 selectedWireguardPort = Constraint.Any,
>                 customWireguardPort = Port(PORT),
>                 availablePortRanges = listOf(PortRange(IntRange(PORT, PORT + PORT))),
> ```

PORT + PORT looks a bit weird to me. This also looks like a perfect reason to introduce the following function to our domain:
```
    operator fun rangeTo(other: Port): PortRange
```

Then we can create a PortRange from two ports, e.g:
```
val lowerPort = Port(10)
val upperPort = Port(20)
val portRange: PortRange = lowerPort..upperPort
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73MGA_DhhVi1ulxQpM:-O73MGA_DhhVi1ulxQpN:b-5eb4xb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L47)):*
> ```Kotlin
> import org.koin.androidx.compose.koinViewModel
> 
> @Preview("Default|WithoutCustomApi|WithCustomApi")
> ```

Just wondering, these are the names for the previews with the order they were passed into the preview, correct? `|` is a magical divider for preview names?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditCustomListUiState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73NxGXDfZabjfcMQj4:-O73NxGXDfZabjfcMQj5:bf3zb9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditCustomListUiState.kt#L7)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.GeoLocationId
> 
> sealed interface EditCustomListUiState {
> ```

Nice fixing these! :star:

**Review by Pururun — DISMISSED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-:-O73TIvZ5h7j-24BvANJ:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @kl)

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810)* status: all files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/FilterUiStatePreviewParameterProvider.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73JujhA4R58CNgBds-:-O73paAgBYFck41QBXOf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/FilterUiStatePreviewParameterProvider.kt#L9)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Private?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/SelectLocationsUiStatePreviewParameterProvider.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73JpprDrDsFFZKNrYG:-O73ppS--grdwU3rzhle:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/SelectLocationsUiStatePreviewParameterProvider.kt#L17)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Could this also be private?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/VpnSettingsUiStatePreviewParameterProvider.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73K8_L7clMhag0Cz0D:-O73reF88renWRxYn9Xu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/VpnSettingsUiStatePreviewParameterProvider.kt#L39)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

PORT + PORT looks a bit weird to me. This also looks like a perfect reason to introduce the following function to our domain:
```
    operator fun rangeTo(other: Port): PortRange
```

Then we can create a PortRange from two ports, e.g:
```
val lowerPort = Port(10)
val upperPort = Port(20)
val portRange: PortRange = lowerPort..upperPort
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73MGA_DhhVi1ulxQpM:-O73rhyG7Wk1m4L6YKYI:b-6jz0uo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eea725e07f818152675f87fb488428184af57525/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L47)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Just wondering, these are the names for the previews with the order they were passed into the preview, correct? `|` is a magical divider for preview names?
</blockquote></details>

`|` does not have any special meaning. There's no way to specify a preview name for an individual preview when using preview parameters so I put the all the names separated by `|` on the on the preview composable.

**Review by Rawa — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Port.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-O73xVCB53t5xwjZuLJ1:-O73xVCB53t5xwjZuLJ2:b-s746r3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c42e0ec45e96b716f66594d4a897eb108cdadb47/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Port.kt#L15)):*
> ```Kotlin
>     override fun toString(): String = value.toString()
> 
>     operator fun rangeTo(other: Port): PortRange = PortRange(value..other.value)
> ```

:star2:

**Review by Rawa — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6810#-:-O74U0T00_0tj0fvrtCL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
