### PR TITLE
Update changelog for android/2023.10-beta1

### PR DESCRIPTION
**Pull request by Pururun**
This PR aims to update the release notes for `android/2023.10-beta1`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`CHANGELOG.md` line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579#-NlOSBzK3SRowBEV8Aud:-NlORmIU30jUoqIpWd48:b-apofm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9149c03770faafd1f8dda4d5943ad3d56f55e0/CHANGELOG.md#L64)):*
I suggest rephrasing a bit:

> Fix relay selector attempting to connect to OpenVPN relays under some circumstances.



_Code quote:_
```Markdown
Fix issue with the app under some circumstances trying to connect to OpenVPN relays.
```
___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579#-NlORVJvAvfbQLPYeNLJ:-NlORVJvAvfbQLPYeNLK:b-exdavx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9149c03770faafd1f8dda4d5943ad3d56f55e0/android/src/main/play/release-notes/en-US/default.txt#L1)):*
It's probably a good idea to menion OpenVPN relay here as well since users might have seen that in the logs. I suggest to use a variant of my `CHANGELOG.md` suggestion:

> Fix an issue where the relay selector would attempt connecting to unsupported (OpenVPN) relays under some circumstances.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579#-NlORVJvAvfbQLPYeNLJ:-NlOT_HF3R3mnES6yxRX:bgnwpl1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9149c03770faafd1f8dda4d5943ad3d56f55e0/android/src/main/play/release-notes/en-US/default.txt#L1)):*
Or perhaps a shorter and less technical version:

> Fix an issue where the app would attempt connecting to unsupported (OpenVPN) relays under some circumstances.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`CHANGELOG.md` line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579#-NlOSBzK3SRowBEV8Aud:-NlOeK0lDduboXlqlOKw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9149c03770faafd1f8dda4d5943ad3d56f55e0/CHANGELOG.md#L64)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest rephrasing a bit:

> Fix relay selector attempting to connect to OpenVPN relays under some circumstances.
</blockquote></details>

Done.
___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579#-NlORVJvAvfbQLPYeNLJ:-NlOeKbN4C8wVCsPB9Zj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9149c03770faafd1f8dda4d5943ad3d56f55e0/android/src/main/play/release-notes/en-US/default.txt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Or perhaps a shorter and less technical version:

> Fix an issue where the app would attempt connecting to unsupported (OpenVPN) relays under some circumstances.
</blockquote></details>

Done.

**Pull request merged**
