### PR TITLE
Refactor the CLI (upgrade to clap 4)

### PR DESCRIPTION
**Pull request by dlon**
Some of the main changes:

* Update to clap 4, and use clap derive (which is declarative) instead of the builder.
* Wrap gRPC client so that the CLI only needs to deal with `mullvad-types`/`talpid-types`. This makes many types reusable for the CLI interface as well.
* All the individual `get` subcommands under `mullvad tunnel` have been replaced by a single subcommand `mullvad tunnel get`:

    ```
    $ mullvad tunnel get
    OpenVPN options
        mssfix:                 unset
    WireGuard options
        MTU:                    unset
        Quantum resistance:     auto
        Public key:             fake+dIWOJAOADiwaiodjoiwajd2919281=
                                Created 1900-01-31 01:01:01 +02:00
        Rotation interval:      unset
    Generic options
        IPv6:                   on
    ```

* Similarly, `mullvad split-tunnel get [--list-processes]` replaces `mullvad split-tunnel pid list` and `mullvad split-tunnel get` (Windows only).

* The settings for WireGuard multihop are more similar to those of the GUI. The entry location and state are separate:

    ```
    mullvad relay set tunnel wireguard entry-location se got
    mullvad relay set tunnel wireguard --use-multihop on
    #mullvad relay set tunnel wireguard --use-multihop off # disable

    # at the same time:
    #mullvad relay set tunnel wireguard --use-multihop on entry-location se got
    ```

Closes DES-87.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 5 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: 5 of 60 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-problem-report/src/main.rs` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTI_pnf2UpJ2bPCPs_O:-NTI_pnf2UpJ2bPCPs_P:bgi0ick) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-problem-report/src/main.rs#L1)):*
> ```XML
> #![deny(rust_2018_idioms)]
> ```

Why is this removed? Seems unrelated to the clap upgrade?
___
*[`mullvad-problem-report/src/main.rs` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTIaV9A6XcUSeDI2w6z:-NTIaV9B7jxesP6SdYyG:bd36mwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/382379b91acff293792844f6d4e0a09e73526c3b/mullvad-problem-report/src/main.rs#L46)):*
> ```XML
>         report: PathBuf,
>         /// Email to attach to the problem report
>         #[arg(long, short = 'r')]
> ```

Has same short option as `report` above. Should be `e` to maintain compatibility if possible.

I suspect this does not work at all, and especially not when called from the GUI? Or maybe the GUI uses the long options. Please do full end-to-end tests sending a problem report from the GUI to verify the compatibility of your change.
___
*[`mullvad-problem-report/src/main.rs` line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTIbcrE8OCMYrUMu09h:-NTIbcrE8OCMYrUMu09i:b-jetqed) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/382379b91acff293792844f6d4e0a09e73526c3b/mullvad-problem-report/src/main.rs#L63)):*
> ```XML
>             redact,
>         } => {
>             let expanded_output_path = output.canonicalize().unwrap_or_else(|_| output.to_owned());
> ```

Why do we canonicalize the path? As far as I can see, we didn't before. I suppose that's only so the "Problem report written to {}" output gets the full path? I'm not sure I would expect a CLI tool to do that if I gave it a relative path. But it's more of a nitpick.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: 5 of 60 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`mullvad-problem-report/src/main.rs` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTI_pnf2UpJ2bPCPs_O:-NTJFQM21Oz3AeSAjtOv:b-rdvica) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-problem-report/src/main.rs#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why is this removed? Seems unrelated to the clap upgrade?
</blockquote></details>

It shouldn't have been removed. I guess these lints are not denied by default.

Is it something that should also be added to `mullvad-daemon` and `mullvad-setup`?
___
*[`mullvad-problem-report/src/main.rs` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTIaV9A6XcUSeDI2w6z:-NTJEaNbCXzUAwk-9ewQ:bk6sshp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/382379b91acff293792844f6d4e0a09e73526c3b/mullvad-problem-report/src/main.rs#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Has same short option as `report` above. Should be `e` to maintain compatibility if possible.

I suspect this does not work at all, and especially not when called from the GUI? Or maybe the GUI uses the long options. Please do full end-to-end tests sending a problem report from the GUI to verify the compatibility of your change.
</blockquote></details>

Good catch! I don't think I have end-to-end tested problem reports in particular, but the UI uses the long names.
___
*[`mullvad-problem-report/src/main.rs` line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTIbcrE8OCMYrUMu09h:-NTJE7RhE4D-2fkULf_S:b8hvsp0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/382379b91acff293792844f6d4e0a09e73526c3b/mullvad-problem-report/src/main.rs#L63)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why do we canonicalize the path? As far as I can see, we didn't before. I suppose that's only so the "Problem report written to {}" output gets the full path? I'm not sure I would expect a CLI tool to do that if I gave it a relative path. But it's more of a nitpick.
</blockquote></details>

We did canonicalize it (only) when printing the path before. So yes, it is probably in order to print the full path. But I agree that it probably shouldn't.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: 4 of 60 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`mullvad-problem-report/src/main.rs` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTI_pnf2UpJ2bPCPs_O:-NTJxmSk0-Kg_g9RgCUW:b-gktr1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-problem-report/src/main.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It shouldn't have been removed. I guess these lints are not denied by default.

Is it something that should also be added to `mullvad-daemon` and `mullvad-setup`?
</blockquote></details>

Reversed this.
___
*[`mullvad-problem-report/src/main.rs` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTIaV9A6XcUSeDI2w6z:-NTJxjLJ8FZlU22tDZYS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/382379b91acff293792844f6d4e0a09e73526c3b/mullvad-problem-report/src/main.rs#L46)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Good catch! I don't think I have end-to-end tested problem reports in particular, but the UI uses the long names.
</blockquote></details>

Done.

**Review by Jontified — CHANGES_REQUESTED** [review]
> Reviewed 54 of 60 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: all files reviewed, 10 unresolved discussions (waiting on @dlon and @faern)

___
*[`mullvad-cli/src/cmds/bridge.rs` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTmQQnQAc4r1_RHsrkI:-NTmQQnQAc4r1_RHsrkJ:b-oprbo3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/bridge.rs#L38)):*
> ```XML
>     /// Set hosting provider(s) to select relays from. The 'list'
>     /// command shows the available relays and their providers.
>     Providers {
> ```

The old command is `provider` rather than `providers` is it a concern that we're breaking backwards compatibility in the CLI?
___
*[`mullvad-cli/src/cmds/relay.rs` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrToNs-SDpdR6VR_ht:-NTrToNs-SDpdR6VR_hu:b-trrbex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L58)):*
> ```XML
>                                 )
>                                 .arg(
>                                     clap::Arg::new("addr")
> ```

Changing `addr` to `tunnel_ip` is another breaking change. Perhaps it's worth it for the added clarity, but I'm noting it down so we can make sure this is what we want. This is a vec, shouldn't it be `tunnel_ips`?
___
*[`mullvad-cli/src/cmds/relay.rs` line 92 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrUDTeBVPijHGPTcAO:-NTrUDTfBAqnCiUn8Bgc:b-d6bios) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L92)):*
> ```XML
>                                 )
>                                 .arg(
>                                     clap::Arg::new("protocol")
> ```

Changed from `protocol` to `transport_protocol`
___
*[`mullvad-cli/src/cmds/relay.rs` line 116 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrSYH84nrCnI8RiEn_:-NTrSYH84nrCnI8RiEna:bs4lzqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L116)):*
> ```XML
>                     )
>                     .subcommand(
>                         clap::App::new("provider")
> ```

This used to be `provider` now it's `providers`. Backwards compatibility issue?
___
*[`mullvad-cli/src/cmds/relay.rs` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrSiJA5MoXLEBzWETz:-NTrSiJA5MoXLEBzWEU-:buo9nmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L120)):*
> ```XML
>                                    command shows the available relays and their providers.")
>                             .arg(
>                                 clap::Arg::new("provider")
> ```

Same here
___
*[`mullvad-cli/src/cmds/relay.rs` line 583 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrjqEWEAvbsPlicHsz:-NTrjqEWEAvbsPlicHt-:b-ny2rpi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/relay.rs#L583)):*
> ```XML
>         (port, Constraint::Any) => {
>             if port.is_only() {
>                 println!("The port constraint was set to 'any'");
> ```

In the old code we were not allowed to set `Only` as a constraint for the port while also setting `Any` as the constraint for the protocol. In the new code we don't error out on this but instead just set the constraint to `Any`. Why the change? I guess the print makes it not confusing for users.

I don't think this is an issue, just want to check in.
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTs6whx8Uh_H9Z22Kna:-NTs6whx8Uh_H9Z22Knb:b-ae8d37) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/tunnel.rs#L131)):*
> ```XML
>         .subcommand(
>             clap::App::new("set").arg(
>                 clap::Arg::new("policy")
> ```

Changed from `policy` to `state` but I guess this isn't really a problem since we're already modifying the interface in a non-backwards compatible way.
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 169 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTsADOxCKm4oY9Ys2e4:-NTsADOxCKm4oY9Ys2e5:b-vgq7ju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/tunnel.rs#L169)):*
> ```XML
>             Some(("key", matches)) => match matches.subcommand() {
>                 Some(("check", _)) => Self::process_wireguard_key_check().await,
>                 Some(("regenerate", _)) => Self::process_wireguard_key_generate().await,
> ```

WG key regeneration is removed, is this what we want?
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTsAEhADkrvjtlS_4C1:-NTsAEhADkrvjtlS_4C2:b48g2m8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/tunnel.rs#L190)):*
> ```XML
> 
>             #[cfg(windows)]
>             Some(("use-wireguard-nt", matches)) => match matches.subcommand() {
> ```

Use wireguard NT option is removed, is this what we want?
___
*[`mullvad-cli/src/cmds/split_tunnel/windows.rs` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTspx6i-3sA1RzRXIe9:-NTspx6i-3sA1RzRXIeA:b-u6ahsc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/split_tunnel/windows.rs#L35)):*
> ```XML
> pub enum App {
>     #[command(hide = true)]
>     List,
> ```

Is this command necessary if basically the same thing can be listed (with 1 additional prefixed line) by using the get command? Does this stay in order to not break backwards compatibility?

**Review by Jontified — COMMENTED** [review]
There hasn't been a change to the changelog, I guess you're planning on doing that later. Just leaving a note here so we don't forget that.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-:-NTsqT7m7Z9ZJEi1cJBb:b-nofqz3)* status: all files reviewed, 10 unresolved discussions (waiting on @dlon and @faern)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: all files reviewed, 10 unresolved discussions (waiting on @faern and @Jontified)

___
*[`mullvad-cli/src/cmds/bridge.rs` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTmQQnQAc4r1_RHsrkI:-NU0q-QoCqn7zs5a2zo0:bouruaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/bridge.rs#L38)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

The old command is `provider` rather than `providers` is it a concern that we're breaking backward compatibility in the CLI?
</blockquote></details>

I'll rename it to provider.
___
*[`mullvad-cli/src/cmds/relay.rs` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrToNs-SDpdR6VR_ht:-NU0oVSdDuL_tOlQuKNw:b-6l4bm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L58)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Changing `addr` to `tunnel_ip` is another breaking change. Perhaps it's worth it for the added clarity, but I'm noting it down so we can make sure this is what we want. This is a vec, shouldn't it be `tunnel_ips`?
</blockquote></details>

Not relevant since it's a positional argument.
___
*[`mullvad-cli/src/cmds/relay.rs` line 92 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrUDTeBVPijHGPTcAO:-NU0oQs_D4A8hfFPnWUD:b-6l4bm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L92)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Changed from `protocol` to `transport_protocol`
</blockquote></details>

Not relevant since it's a positional argument.
___
*[`mullvad-cli/src/cmds/relay.rs` line 116 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrSYH84nrCnI8RiEn_:-NU0ob722YxhP7VzkRJ_:bouruaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L116)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

This used to be `provider` now it's `providers`. Backwards compatibility issue?
</blockquote></details>

I'll rename it to provider.
___
*[`mullvad-cli/src/cmds/relay.rs` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrSiJA5MoXLEBzWETz:-NU0ojE340wHz0PXI6Mk:bouruaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L120)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Same here
</blockquote></details>

I'll rename it to provider.
___
*[`mullvad-cli/src/cmds/relay.rs` line 583 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrjqEWEAvbsPlicHsz:-NU0owVN-cXS2Oe5-d9I:bhr5qm9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/relay.rs#L583)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

In the old code we were not allowed to set `Only` as a constraint for the port while also setting `Any` as the constraint for the protocol. In the new code we don't error out on this but instead just set the constraint to `Any`. Why the change? I guess the print makes it not confusing for users.

I don't think this is an issue, just want to check in.
</blockquote></details>

It should work the same way. See the removed if statement above.
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 169 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTsADOxCKm4oY9Ys2e4:-NTwkuIi5mcxv8iAozDO:b-lqfiui) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/tunnel.rs#L169)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

WG key regeneration is removed, is this what we want?
</blockquote></details>

I will add this back.
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTsAEhADkrvjtlS_4C1:-NTwkfM0-RHi2eJWJg8L:b-wbvu0x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/tunnel.rs#L190)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Use wireguard NT option is removed, is this what we want?
</blockquote></details>

This should be alright. We no longer have the automatic fallback and haven't seen any problems caused by that.
___
*[`mullvad-cli/src/cmds/split_tunnel/windows.rs` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTspx6i-3sA1RzRXIe9:-NU0pgW71w6kE-3NyZvz:b-nvwqr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/split_tunnel/windows.rs#L35)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Is this command necessary if basically the same thing can be listed (with 1 additional prefixed line) by using the get command? Does this stay in order to not break backwards compatibility?
</blockquote></details>

For backwards compatibility. Since that's not too relevant, I'll consider removing this. But note that the command is hidden anyway.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: 55 of 60 files reviewed, 7 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-cli/src/cmds/bridge.rs` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTmQQnQAc4r1_RHsrkI:-NU0rzO6CGrVcYIXwKgU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/bridge.rs#L38)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'll rename it to provider.
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 116 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrSYH84nrCnI8RiEn_:-NU0sETp09kTHsn4CFeY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L116)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'll rename it to provider.
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTrSiJA5MoXLEBzWETz:-NU0sFKD4RwoXQR_KgCZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/relay.rs#L120)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'll rename it to provider.
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 169 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTsADOxCKm4oY9Ys2e4:-NU0sJsl9gbOpaj9YJLe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/mullvad-cli/src/cmds/tunnel.rs#L169)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I will add this back.
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/split_tunnel/windows.rs` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTspx6i-3sA1RzRXIe9:-NU0sMxYBjO-H4WEDCBA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e34dcd56907f6f0c61be820abfa7715d390d43f9/mullvad-cli/src/cmds/split_tunnel/windows.rs#L35)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

For backwards compatibility. Since that's not too relevant, I'll consider removing this. But note that the command is hidden anyway.
</blockquote></details>

Done.
___
*[`mullvad-problem-report/src/main.rs` line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NTIbcrE8OCMYrUMu09h:-NU0rtyCC_O7OUJKqohP:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/382379b91acff293792844f6d4e0a09e73526c3b/mullvad-problem-report/src/main.rs#L63)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We did canonicalize it (only) when printing the path before. So yes, it is probably in order to print the full path. But I agree that it probably shouldn't.
</blockquote></details>

Removed.

**Review by dlon — COMMENTED** [review]
I've made the changelog entries more detailed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-:-NUQyKhY4ozm-XfhZS4x:b-azhqzp)* status: 59 of 60 files reviewed, 1 unresolved discussion (waiting on @Jontified)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: all files reviewed, 1 unresolved discussion

___
*[`CHANGELOG.md` line 47 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519#-NURZOGW4BmyOXu_0Toj:-NURgSym4WGzpfp9RuKi:bexbmcn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b455e9cfcd43ab7158d55291faf6bc06af9f8106/CHANGELOG.md#L47)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These Android entries don't belong here. Some error during rebase?
</blockquote></details>

The `Windows` heading was screwed up. It seems correct to me now.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: 53 of 61 files reviewed, 1 unresolved discussion (waiting on @dlon and @Jontified)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: 54 of 61 files reviewed, all discussions resolved (waiting on @Jontified)

**Review by Jontified — APPROVED** [review]
> Reviewed 7 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4519)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
