### PR TITLE
Keep key information up to date

### PR DESCRIPTION
**Pull request by raksooo**
This PR makes sure that the "Key generated" value is up to date by:
* Updating the value when the app is opened if the `WireguardKeys` view is the current view
* Every minute as long as the view is visible

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144)

### CODE REVIEW

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[gui/src/renderer/components/WireguardKeys.tsx, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144#-MHz__2c3gO7ACQ5Gjcz:-MHz__2c3gO7ACQ5Gjd-:b-dtjubw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc6d98c35d12d25dea127de62651eb9049959c29/gui/src/renderer/components/WireguardKeys.tsx#L70)):*
> ```XML
>   public componentDidMount() {
>     this.verifyKey();
>     window.addEventListener('focus', this.setAgeOfKeyStringState);
> ```

I don't know if the `focus` event on `window` is the best way to detect if the app is opened. The other idea I had was to somehow notify the renderer when the `show` function was called in the main process but that would be a lot more complicated. Are there any other alternatives?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/WireguardKeys.tsx, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144#-MHz__2c3gO7ACQ5Gjcz:-MHzdOGy4H4P7v3e4Rxb:b-9gj7t9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc6d98c35d12d25dea127de62651eb9049959c29/gui/src/renderer/components/WireguardKeys.tsx#L70)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't know if the `focus` event on `window` is the best way to detect if the app is opened. The other idea I had was to somehow notify the renderer when the `show` function was called in the main process but that would be a lot more complicated. Are there any other alternatives?
</blockquote></details>

I think the best way is to use IPC from the main process & then just save the visibility status to `userInterface` subkey in redux.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/WireguardKeys.tsx, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144#-MHz__2c3gO7ACQ5Gjcz:-MI-AKD43D5nov_7bUNp:b-el989i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc6d98c35d12d25dea127de62651eb9049959c29/gui/src/renderer/components/WireguardKeys.tsx#L70)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think the best way is to use IPC from the main process & then just save the visibility status to `userInterface` subkey in redux.
</blockquote></details>

I agree. Done.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144#-:-MI3JCHF8JheERrLM3Dj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Pull request merged**
