### PR TITLE
Update to React 17 and Styled Components 5.2

### PR DESCRIPTION
**Pull request by raksooo**
This PR updates React to version 17 and Styled Components to 5.2.

Changelog for React 17:
https://reactjs.org/blog/2020/10/20/react-v17.html

Changelog for Styled Components 5.2:
https://github.com/styled-components/styled-components/releases/tag/v5.2.0

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247#-MLTfNzM68752b_Xi4eh:-MLTfNzM68752b_Xi4ei:b-3sepff) (no related file):*
BTW No migration or changes needed after updating to React 17 & Styled components 5.2?

---

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247#-MLTfNzM68752b_Xi4eh:-MLg-pH18OF9cco3wsJx:b-x4ll6y) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

BTW No migration or changes needed after updating to React 17 & Styled components 5.2?
</blockquote></details>

Nope, there is almost no breaking changes in React 17 since they are saving them for 17.1. Nothing that affects us.

---

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2247#-:-MLhInTC2VnEIUgiQ-6D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
