### PR TITLE
Add `daita` as a custom config name

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR adds support for gating DAITA behind a cfg option. This makes it _way_ easier to track what code is strictly DAITA-related, as well as enabling DAITA support on other platforms down the line.

This PR also changes the build chain of the app on Android, Linux and macOS. 
* On Linux and macOS, `libwg` is now distributed as a shared library, which is how wireguard-go currently is built for Android.
* On all of the above platforms, wireguard-go is now a submodule in the app repository. This means that it has to be checkout out in order to build the app on these platforms. This has been detailed in [the general build instructions](https://github.com/mullvad/mullvadvpn-app/blob/add-daita-cfg-flag/README.md#checking-out-the-code).

This fixes DES-937.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)

### CODE REVIEW

**Review by Serock3 — CHANGES_REQUESTED** [review]
One big concern with making DAITA a feature is that you would not be able to use `--all-features` (on platforms without DAITA) anymore. The DAITA feature would have to be enabled on Windows and Linux and disabled on other platforms, and it would be up to the developer to know which platforms have the feature, otherwise the app will not build.

It seems that features simply cannot be specified per platform, it is a fundamental limitation of cargo. You cannot specify which features exists or are enabled by default per platform. It is not possible to get around this using `build.rs` either, as feature resolution is done before the build scripts are run. You can set cfg variables like we do with `wireguard_go` in `talpid-wireguard`, but this can't affect which features are enabled in dependencies.

I have thought a lot about how to get around this, but it may be the case that the only proper solution is to simply abandon this PR and keep the raw `#[cfg(any(target_os = "windows", target_os = "linux"))]` gates, unfortunately.

**Review by hulthe — COMMENTED** [review]
> Reviewed 64 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 5 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-management-interface/build.rs` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_JZIa-AIE0jMfUtZ0:-Ny_JZIa-AIE0jMfUtZ1:b1y3rwh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/mullvad-management-interface/build.rs#L7)):*
> ```XML
> 
>     // Enable Daita by default on Linux and Windows.
>     println!("cargo:rustc-check-cfg=cfg(daita)");
> ```

should be double `:`s, i thought it would reject the single-color syntax since check-cfg is a newly added thing :thinking: 
___
*[`mullvad-relay-selector/build.rs` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_KJGDAXyhgqJIOztk:-Ny_KJGDAXyhgqJIOztl:bn8ma5b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/mullvad-relay-selector/build.rs#L5)):*
> ```XML
> 
>     // Enable Daita by default on Linux and Windows.
>     println!("cargo:rustc-check-cfg=cfg(daita)");
> ```

scobido doubleido, etc
maybe do a search replace
___
*[`talpid-wireguard/src/lib.rs` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny__mtv7zcNX72Tf1T0:-Ny__mtv7zcNX72Tf1T1:b3m55p7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/talpid-wireguard/src/lib.rs#L70)):*
> ```XML
> 
> /// TODO: Document
> /// TODO: Rename
> ```

:eye: :lips: :eye: 
___
*[`wireguard-go-rs/Cargo.lock` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_ctVr7stPPR5oY2fq:-Ny_ctVr7stPPR5oY2fr:b-kdjxl7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/wireguard-go-rs/Cargo.lock#L1)):*
> ```TOML
> # This file is automatically @generated by Cargo.
> ```

wgrs is part of the workspace, this file should be deleted
___
*[`wireguard-go-rs/libwg/wireguard-go` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_de1t9BOPdpapMp8i:-Ny_de1t9BOPdpapMp8j:b-zfj9s9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/wireguard-go-rs/libwg/wireguard-go#L1)):*
> ```
> Subproject commit 1e3bc447c174e243df151cf668ba8eab36739ce0
> ```

I guess update this after the other PR is merged

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 5 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-management-interface/build.rs` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_JZIa-AIE0jMfUtZ0:-Ny_kFmu3f_lY9iS1J9O:b-vnsohq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/mullvad-management-interface/build.rs#L7)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

should be double `:`s, i thought it would reject the single-color syntax since check-cfg is a newly added thing :thinking:
</blockquote></details>

Done. That's a bit weird aye, but good catch!
___
*[`mullvad-relay-selector/build.rs` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_KJGDAXyhgqJIOztk:-Ny_kM271Q7tcBZ3gla3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/mullvad-relay-selector/build.rs#L5)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

scobido doubleido, etc
maybe do a search replace
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/lib.rs` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny__mtv7zcNX72Tf1T0:-Ny_klqx5WDjB238fNqE:b-vi84mw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/talpid-wireguard/src/lib.rs#L70)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

:eye: :lips: :eye:
</blockquote></details>

Lmao, reverting this
___
*[`wireguard-go-rs/Cargo.lock` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_ctVr7stPPR5oY2fq:-Ny_kVEO0e0cIxMjYRZM:b-fn8mpi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/wireguard-go-rs/Cargo.lock#L1)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

wgrs is part of the workspace, this file should be deleted
</blockquote></details>

:facepalm: 
___
*[`wireguard-go-rs/libwg/wireguard-go` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-Ny_de1t9BOPdpapMp8i:-Ny_kXlG9KeblpKWsqPB:b2nhtan) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/255fe1adab40a5ce073799b664219dd54f589d0c/wireguard-go-rs/libwg/wireguard-go#L1)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I guess update this after the other PR is merged
</blockquote></details>

Yup

**Review by Serock3 — COMMENTED** [review]
> Reviewed 4 of 6 files at r2, 21 of 22 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 9 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

___
*[`mullvad-daemon/build.rs` line 40 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX2j6w-kHhiohuAos8:-NzX2j6w-kHhiohuAos9:b-eldxqp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/mullvad-daemon/build.rs#L40)):*
> ```XML
>     }
> 
>     // when development, configure rpath to facilitate linking with libwg.so
> ```

"when development"?
___
*[`wireguard-go-rs/build.rs` line 43 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX3iXw4XHXlUA8n51t:-NzX3iXw4XHXlUA8n51u:brupakd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build.rs#L43)):*
> ```XML
>     // NOTE: Link to libwg dynamically on all platforms.
>     //
>     // LTO breaks when statically linking to libwg & Go programs does not
> ```

Great that you documented this. Perhaps we could even be more specific about the double symbol issue, to make it easier for future devs to find other solutions.
___
*[`wireguard-go-rs/build-wireguard-go.sh` line 51 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX4JQ11y9HpMzOj6Sg:-NzX4JQ11y9HpMzOj6Sh:b8gw13v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build-wireguard-go.sh#L51)):*
> ```Shell
> 
> function build_unix {
>     # TODO: consider using `log_header` here
> ```

I left this comment, though it's a very inconsequential style issue. We should remove the comment or implement it.
___
*[`wireguard-go-rs/build-wireguard-go.sh` line 97 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX5Agl7_R5GlUjRSNK:-NzX5Agl7_R5GlUjRSNL:bxhiidv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build-wireguard-go.sh#L97)):*
> ```Shell
>         go build -v -o "$BUILD_DIR/lib/$TARGET/libwg.so" -buildmode c-shared
>     fi
>     # Copy libwg to `OUT_DIR` so that we may refer to it via `OUT_DIR` in `build.rs`, which might be handy.
> ```

Do we need two copies of the object file? Is it not ok to just move it instead?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: 66 of 67 files reviewed, 8 unresolved discussions (waiting on @hulthe and @Serock3)

___
*[`mullvad-daemon/build.rs` line 40 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX2j6w-kHhiohuAos8:-NzXL4fTEUqD0nKmIm32:b-qk2rwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/mullvad-daemon/build.rs#L40)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

"when development"?
</blockquote></details>

Done Updated the text
___
*[`wireguard-go-rs/build.rs` line 43 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX3iXw4XHXlUA8n51t:-NzXM65n2Laqhxo6ok5I:b-qk0ki0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build.rs#L43)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Great that you documented this. Perhaps we could even be more specific about the double symbol issue, to make it easier for future devs to find other solutions.
</blockquote></details>

Done clarified that part :blush:
___
*[`wireguard-go-rs/build-wireguard-go.sh` line 51 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX4JQ11y9HpMzOj6Sg:-NzXMI7uCyvhk_z2N7lC:bnjjyhm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build-wireguard-go.sh#L51)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I left this comment, though it's a very inconsequential style issue. We should remove the comment or implement it.
</blockquote></details>

Since the output most likely will be consumed by `cargo`, and would seldom be seen by a human, I think it's fine to just not implement it here. At least for now :blush:
___
*[`wireguard-go-rs/build-wireguard-go.sh` line 97 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX5Agl7_R5GlUjRSNK:-NzXMhKb9hi2wydH55I5:b-46lbuu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build-wireguard-go.sh#L97)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Do we need two copies of the object file? Is it not ok to just move it instead?
</blockquote></details>

Kind of, yes. :cry: `cargo` won't look outside of `target` for stuff that we want to link against, which we let `cargo` know about via the [`rustc-link-search`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-search) instruction. This is needed to do to make debug builds / `cargo test` work as expected. However, `OUT_DIR` changes between compilations, which means that rebuilding the project becomes kind of expensive (since we have to build `wireguard-go` each time we hit `cargo check/build/test`. Thus, it is cheaper to dump it into a known location `build/lib/<arch>` and copy it from there to `OUT_DIR` as needed.

**Review by Serock3 — COMMENTED** [review]
> Reviewed 24 of 24 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 5 unresolved discussions (waiting on @hulthe)

___
*[`wireguard-go-rs/build.rs` line 43 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX3iXw4XHXlUA8n51t:-NzbU3iIBZ4U3v1rv2oZ:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build.rs#L43)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Done clarified that part :blush:
</blockquote></details>

Nice!
___
*[`wireguard-go-rs/build-wireguard-go.sh` line 51 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX4JQ11y9HpMzOj6Sg:-NzbU7Mo9D5hBqcQPnub:bb74ce2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build-wireguard-go.sh#L51)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Since the output most likely will be consumed by `cargo`, and would seldom be seen by a human, I think it's fine to just not implement it here. At least for now :blush:
</blockquote></details>

Sure
___
*[`wireguard-go-rs/build-wireguard-go.sh` line 97 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzX5Agl7_R5GlUjRSNK:-NzbUDPbE_-09qYkXfbH:b-6sgjyb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc9295fe7a58b8cbc57da991551f5d31d7f6e7bc/wireguard-go-rs/build-wireguard-go.sh#L97)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Kind of, yes. :cry: `cargo` won't look outside of `target` for stuff that we want to link against, which we let `cargo` know about via the [`rustc-link-search`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-search) instruction. This is needed to do to make debug builds / `cargo test` work as expected. However, `OUT_DIR` changes between compilations, which means that rebuilding the project becomes kind of expensive (since we have to build `wireguard-go` each time we hit `cargo check/build/test`. Thus, it is cheaper to dump it into a known location `build/lib/<arch>` and copy it from there to `OUT_DIR` as needed.
</blockquote></details>

Thanks for clarifying :blush:

**Review by Serock3 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-:-NzbV4HY54YU0U9sMslq:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @hulthe)

**Review by Serock3 — APPROVED** [review]
> Reviewed 15 of 15 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 6 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

___
*[`ci/buildserver-build.sh` line 166 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-NzcQHJr9_fgcnaxV1Tt:-NzcQHJr9_fgcnaxV1Tu:b-y7kzjy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8aa69c118cbc92297dba979704784bcda2f97e62/ci/buildserver-build.sh#L166)):*
> ```Shell
>     git checkout "$ref"
>     git submodule update
>     git submodule update --init --recursive --depth=1 wireguard-go-rs || true
> ```

What does the `|| true` part do? My guess is that it swallows error non-zero exit codes. Would it not be equivalent to add a`;`?

**Review by Serock3 — APPROVED** [review]
> Reviewed 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 6 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

**Review by Serock3 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202)* status: all files reviewed, 7 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

___
*[`talpid-wireguard/src/lib.rs` line 825 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6202#-O-1kZ-lEwV7DCEMxGIn:-O-1kZ-lEwV7DCEMxGIo:b-zhddrr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/935e21f33ae251e8b700a7a07dc1c03a70853a4d/talpid-wireguard/src/lib.rs#L825)):*
> ```XML
> 
>     /// Configure and start a Wireguard-go tunnel.
>     fn open_wireguard_go_tunnel(
> ```

Missing a `#[cfg(wireguard_go)]` here

**Pull request merged**
