### PR TITLE
Improve divider usage and replace deprecated divider

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892#-NsC9rwb5BbIfN7pzXBU:-NsC9rwb5BbIfN7pzXBV:b-vjfuoq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7022d7ad950716e987444f753e3ad95a9b012d56/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt#L28)):*
> ```Kotlin
>     items(items = items, key = key, contentType = contentType) { item ->
>         itemContent(item)
>         HorizontalDivider()
> ```

Should a divider always be rendered after the last item?



_Code quote:_
```Kotlin
HorizontalDivider()
```

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892#-NsC9rwb5BbIfN7pzXBU:-NsCwz4tC8jhO9dnwGyK:b-vkttbp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7022d7ad950716e987444f753e3ad95a9b012d56/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt#L28)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should a divider always be rendered after the last item?
</blockquote></details>

Note: Removing the HorizontalDivider on last might change how the `key` work because the last item would be different from the other ones.

Also another alternative would be to make the function more dynamic (I've not taken the `key` thing into consideration). This way we can pass another divider if needed.

```
inline fun <T> LazyListScope.itemsWithDivider(
    items: List<T>,
    noinline key: ((item: T) -> Any)? = null,
    noinline contentType: (item: T) -> Any? = { null },
    crossinline divider: @Composable LazyItemScope.(item: T) -> Unit = { HorizontalDivider() }
    crossinline itemContent: @Composable LazyItemScope.(item: T) -> Unit
) {
    itemsIndexed(items = items, key = key, contentType = contentType) { index, item ->
        itemContent(item)

        if (index < itemsList.lastIndex)
            divider()
    }
}
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892#-NsC9rwb5BbIfN7pzXBU:-Nsgrvg5AWRg6v-XdYjH:bwpu2wd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7022d7ad950716e987444f753e3ad95a9b012d56/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt#L28)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Note: Removing the HorizontalDivider on last might change how the `key` work because the last item would be different from the other ones.

Also another alternative would be to make the function more dynamic (I've not taken the `key` thing into consideration). This way we can pass another divider if needed.

```
inline fun <T> LazyListScope.itemsWithDivider(
    items: List<T>,
    noinline key: ((item: T) -> Any)? = null,
    noinline contentType: (item: T) -> Any? = { null },
    crossinline divider: @Composable LazyItemScope.(item: T) -> Unit = { HorizontalDivider() }
    crossinline itemContent: @Composable LazyItemScope.(item: T) -> Unit
) {
    itemsIndexed(items = items, key = key, contentType = contentType) { index, item ->
        itemContent(item)

        if (index < itemsList.lastIndex)
            divider()
    }
}
```
</blockquote></details>

@Pururun any thoughts on the above? If we always want to render a divider after the last element (like I realized we already do in `itemsIndexedWithDivider`) this looks good, otherwise we might want to add some boolean flag argument or consider making it more dynamic as suggested by @Rawa

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892#-NsC9rwb5BbIfN7pzXBU:-Nsgum3vEop9sRf995QQ:biqg2xg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7022d7ad950716e987444f753e3ad95a9b012d56/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt#L28)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@Pururun any thoughts on the above? If we always want to render a divider after the last element (like I realized we already do in `itemsIndexedWithDivider`) this looks good, otherwise we might want to add some boolean flag argument or consider making it more dynamic as suggested by @Rawa
</blockquote></details>

Me and @Rawa discussed this and we reached the conclusion that since it does some magic under the hood it is better to preserve the behavior that all items with the same key and type have the same content than not rendering the last divider.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892#-:-NsgvYA56FyZSu_PE6Oo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5892#-NsC9rwb5BbIfN7pzXBU:-NsgvUDR3dWRJDrr3dLC:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7022d7ad950716e987444f753e3ad95a9b012d56/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt#L28)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Me and @Rawa discussed this and we reached the conclusion that since it does some magic under the hood it is better to preserve the behavior that all items with the same key and type have the same content than not rendering the last divider.
</blockquote></details>

Alright :thumbsup:

**Pull request merged**
