### PR TITLE
Linux DNS backup

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Linux version not yet released.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEXqEh8_n5bJlUuvF4:-LFEXqEiEYh7DTsFsgRC:bq9v0ne) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L17)):*
I notice you use `static` here. I almost always use `const` for my this type of constants. The old Rust book has a paragraph on when to choose which one to use: https://doc.rust-lang.org/book/first-edition/const-and-static.html#which-construct-should-i-use

> Almost always, if you can choose between the two, choose const. It’s pretty rare that you actually want a memory location associated with your constant, and using a const allows for optimizations like constant propagation not only in your crate but downstream crates.

---

*[talpid-core/src/firewall/linux/dns.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEZ8Q9BCLc1Cr-p45p:-LFEZ8Q9BCLc1Cr-p45q:b-a6smnm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L54)):*
> ```Rust
> impl DnsSettings {
>     pub fn new() -> Result<Self> {
>         restore_backup_file()?;
> ```

Should this maybe be lifted a bit higher? For me it feels unclear to have `DnsSettings::new()` restore settings. I think it should only prepare an object for manipulating the settings.

The backup restore

---

*[talpid-core/src/firewall/linux/dns.rs, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEZtMAAyZtbtw-DRSl:-LFEZtMAAyZtbtw-DRSm:b-9xqthw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L182)):*
> ```Rust
> fn backup_config() -> Result<Config> {
>     fs::rename(RESOLV_CONF_PATH, RESOLV_CONF_BACKUP_PATH)
>         .chain_err(|| ErrorKind::BackupResolvConf)?;
> ```

Are you sure we want to *move* the file? This leaves the system in an intermediate state where there is no `/etc/resolv.conf` file at all. I think we want to avoid that. We should probably copy the original and then overwrite it it feels like.

---

*[talpid-core/src/firewall/linux/dns.rs, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFE_WcR44nLMp4lSL54:-LFE_WcR44nLMp4lSL55:bhg61b8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L215)):*
> ```Rust
> 
>     if backup_path.exists() {
>         fs::rename(backup_path, RESOLV_CONF_PATH).chain_err(|| ErrorKind::RestoreResolvConf)?;
> ```

I think the act of restoring a backup like this deserves an `info!` log entry.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by pinkisemils** [comment]
I was under the impression that the whole reason for `talpid-core/src/firewall/system_state.rs` to exist was to consolidate some of the code you've added here :) The only thing that `SystemStateWriter` lacks is the ability to take a full path to the backup file, which is a change I can make to accommodate this use case.

---

Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEZ8Q9BCLc1Cr-p45p:-LFGV0Fb2n1qT5G7a7vR:b6rv4rk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L54)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ooops. Did not finish this post.

Problem is that if the restore fails with current code we don't get any `DnsSettings` instance back and we will fail to start all together. Is that what we want? I got the impression from @pinkisemils that we aimed at continue as if nothing happened on restore failure, but log the error.

If we expose the restore upwards and add to the `Firewall` trait something like
```rust
trait Firewall {
    /// Checks if there is some persisted state saved to disk. If so try to restore it
    /// and return `Ok(true)` in case of success. No persisted state returns `Ok(false)`.
    fn restore_persisted_state(&mut self) -> Result<()>;
}
```
But likely with better documentation. I just drafted something.
The point is that then the `Daemon` can execute `match firewall.restore_persisted_state() {...}` and do some high level action, `Err(e)` can error log it.

Or am I the only one who thinks making `Firewall::new()`, and by extensions `DnsSettings::new()`, perform restore actions is a bit inappropriate? :)
</blockquote></details>

This is what I've done in the`WinDNS` branch - I added a `restore_system_state` function to the `Firewall` trait.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-:-LFGVSV71GuJyYGv0jL3:b-q2syp3)*

**Comment by faern** [comment]
We would probably also like to keep strict types where possible. So where the Windows impl just sends around binary blobs, Linux could send around `resolv-conf::Config` objects to be backed up?

---

Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-:-LFHKbQv9wXsgh4fdaUf:b-af0iyf)*

**Comment by faern** [comment]
... If they were to be using the same backup facilities that is. We have also talked about just having the different OSes implement backup by themselves if that is simpler.

---

Review status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-:-LFHLJPE7x9kJxKPKOI_:bnf71s8)*

**Comment by pinkisemils** [comment]
Review status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 214 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFIMRoc0MfragTprd_N:-LFIMRoc0MfragTprd_O:be9dk7a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f78d05feb1eadfc5f6dbb818da27e78b5bf960d7/talpid-core/src/firewall/linux/dns.rs#L214)):*
> ```Rust
>     let backup_path = Path::new(RESOLV_CONF_BACKUP_PATH);
> 
>     if backup_path.exists() {
> ```

In the case that this path is not accessible, this function will just return false. Just making sure this is the behaviour we want :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r3.
Review status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/system_state.rs, line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFLq6jR4zdF2Tk7Vbbr:-LFLq6jR4zdF2Tk7Vbbs:b6m8z7p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/system_state.rs#L62)):*
> ```Rust
> 
> #[cfg(test)]
> mod tests {
> ```

I believe some of these tests are no longer working. I've got it working in 956a0da0d98a80254bbb53489ab59ac32b17b780, you should be able to just cherry pick that :).

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by faern** [comment]
Sorry for being pessimistic about the abstraction. But it feels like it adds more code than it saves (a lot of new `state_writer: &SystemStateWriter` arguments for example) and it removes the benefit of being able to tailor the code to each platform.

---

Review status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/system_state.rs, line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMP84L4gijnJ3Ki_a3:-LFMP84L4gijnJ3Ki_a4:b-58zsvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/system_state.rs#L10)):*
> ```Rust
> /// This struct is responsible for saving a binary blob to disk. The binary blob is intended to
> /// store system state that should be resotred when the security policy is reset.
> pub struct SystemStateWriter {
> ```

Unless I'm missing some part, all this struct does is to hold a path and basically just provide `write`, `read_and_remove` and `remove`? It's very generic and does not add a whole lot of abstraction? Except some logging which makes it sound more focused :)

---

*[talpid-core/src/firewall/linux/dns.rs, line 74 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMQNt-6FvS6--6tcUI:-LFMQNt-6FvS6--6tcUJ:bs6dxts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L74)):*
> ```Rust
>         if let Some(backup) = backup {
>             info!("Restoring DNS state from backup");
>             fs::write(RESOLV_CONF_PATH, &backup).chain_err(|| ErrorKind::RestoreResolvConf)?;
> ```

I'm not sure how this adds any value over just `fs::rename(RESOLV_CONF_BACKUP_PATH, RESOLV_CONF_PATH).chain_err(|| ...)?;`

One downside of this is that instead of doing it atomically, which a filesystem move usually is, we read the content into memory, remove the backup file and then write the new file.

---

*[talpid-core/src/firewall/linux/dns.rs, line 105 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMRDBf7RSN0HgZ7EsE:-LFMRDBf7RSN0HgZ7EsF:b-h89m0z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L105)):*
> ```Rust
>         if let Some(state) = self.lock_state().take() {
>             if !self.restore_system_backup()? {
>                 write_config(&state.backup)?;
> ```

I have been under the impression that the goal was to only use the persisted backup when we start the daemon and find out there was a persisted backup. All other `reset`s should restore what's in memory? So the persisting of backup state to disk is only for "disaster recovery". Otherwise we would not need to store the backup in memory at all I think?

Storing the backup to disk feels like a last resort and not to be used by default?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-:-LFMRkTKAIGQak51ADyd:b-guj2tl)*

**Comment by faern** [comment]
Review status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 74 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMQNt-6FvS6--6tcUI:-LFMW0qP2DRghMizLFPb:bsekzmk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L74)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure how this adds any value over just `fs::rename(RESOLV_CONF_BACKUP_PATH, RESOLV_CONF_PATH).chain_err(|| ...)?;`

One downside of this is that instead of doing it atomically, which a filesystem move usually is, we read the content into memory, remove the backup file and then write the new file.
</blockquote></details>

Or, well. To go more in depth. We might have a problem since the backups are taken from another thread etc.

But if we make sure to only ever write to the backup from the other thread watching the `notify` events, and we only restore the backup from this thread, and only when the daemon starts up, it should be safe?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by faern** [comment]
Review status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 105 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMRDBf7RSN0HgZ7EsE:-LFMX8BF0MUXrtjdWj64:b-io6o47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L105)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I have been under the impression that the goal was to only use the persisted backup when we start the daemon and find out there was a persisted backup. All other `reset`s should restore what's in memory? So the persisting of backup state to disk is only for "disaster recovery". Otherwise we would not need to store the backup in memory at all I think?

Storing the backup to disk feels like a last resort and not to be used by default?
</blockquote></details>

I think that we might want to invert the relationship we have here. `reset` should just `take()` the state and write the in-memory backup to the system if one exists. But `restore_system_backup` should probably make sure we are first in the resetted state. Would be strange to be in the active DNS monitoring state and doing a `restore_system_backup` then.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by pinkisemils** [comment]
Review status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFNau2C07770HH0RZWK:-LFNau2C07770HH0RZWL:b-lg1rfn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L17)):*
> ```Rust
> 
> const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";
> const RESOLV_CONF_BACKUP_PATH: &str = "/etc/resolv.conf.mullvadbackup";
> ```

This path should be a parameter, and not a constant. Otherwise, multiple instances of this library will certainly clash.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by faern** [comment]
Review status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFNau2C07770HH0RZWK:-LFNksG0CSE1NK4Jlvyb:b-tf5pxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L17)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This path should be a parameter, and not a constant. Otherwise, multiple instances of this library will certainly clash.
</blockquote></details>

Multiple instances of a `DnsSettings` would clash no matter what. Because what they do is monitor `/etc/resolv.conf` for changes and as soon as it changes it rewrites it with the DNS IPs it holds. Would be true for all other platforms as well, since they compete on setting the global system DNS settings and they all detect instant changes and force in their own ones.

So multiple ones of these would create an infinite loop with writes to `/etc/resolv.conf`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by jvff** [comment]
Review status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEXqEh8_n5bJlUuvF4:-LFIB5Lb3iSN55RezMN3:biyfe3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L17)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I notice you use `static` here. I almost always use `const` for my this type of constants. The old Rust book has a paragraph on when to choose which one to use: https://doc.rust-lang.org/book/first-edition/const-and-static.html#which-construct-should-i-use

> Almost always, if you can choose between the two, choose const. It’s pretty rare that you actually want a memory location associated with your constant, and using a const allows for optimizations like constant propagation not only in your crate but downstream crates.

</blockquote></details>

Done, thanks :)

---

*[talpid-core/src/firewall/linux/dns.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEZ8Q9BCLc1Cr-p45p:-LFIwyhzBJzFDA1c0gaE:bn57th) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L54)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is what I've done in the`WinDNS` branch - I added a `restore_system_state` function to the `Firewall` trait.
</blockquote></details>

I'm assuming that if we can't restore the state, we should fail so that the user knows. This is the kind of error that messes up the system configuration, so the user should get a loud error IMO.

Let me know if this should change.

---

*[talpid-core/src/firewall/linux/dns.rs, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFEZtMAAyZtbtw-DRSl:-LFIxBJ24Ai2CcgFtr5y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L182)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Are you sure we want to *move* the file? This leaves the system in an intermediate state where there is no `/etc/resolv.conf` file at all. I think we want to avoid that. We should probably copy the original and then overwrite it it feels like.
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFE_WcR44nLMp4lSL54:-LFIDTzvAnqHycbphzPg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/322bf3ce1eabe2aa5bcc9d3741b6b905c1c7fc7b/talpid-core/src/firewall/linux/dns.rs#L215)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think the act of restoring a backup like this deserves an `info!` log entry.
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 214 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFIMRoc0MfragTprd_N:-LFIxrJ6BLf9-o4oSRrt:b-1bx642) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f78d05feb1eadfc5f6dbb818da27e78b5bf960d7/talpid-core/src/firewall/linux/dns.rs#L214)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

In the case that this path is not accessible, this function will just return false. Just making sure this is the behaviour we want :)
</blockquote></details>

Does this still happen in the new code?

---

*[talpid-core/src/firewall/linux/dns.rs, line 74 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMQNt-6FvS6--6tcUI:-LFSIZ44DKn5Ve1ZOVDQ:bte9mic) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L74)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Or, well. To go more in depth. We might have a problem since the backups are taken from another thread etc.

But if we make sure to only ever write to the backup from the other thread watching the `notify` events, and we only restore the backup from this thread, and only when the daemon starts up, it should be safe?
</blockquote></details>

Reverted to not use `SystemStateWriter` because in this case I can control the order of operations so that it is:

1. read backup file
2. write resolv.conf with persisted state
3. remove backup file

This is not as atomic as a rename, but it works well and it also works for when `resolv.conf` is a special "mounted" file (as it is in Docker containers), when renames don't work.

---

*[talpid-core/src/firewall/linux/dns.rs, line 105 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMRDBf7RSN0HgZ7EsE:-LFSJ5Mh6sgQylfDov6f:b-kkyooq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/linux/dns.rs#L105)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Eh. I should maybe stop discussing things with myself in PRs. I did not finish thinking. A `reset` would of course also have to remove the persisted backup, as a reboot after a `reset` should not restore anything.
</blockquote></details>

As we discussed on Slack, the plan is to call the `restore_persisted_state` once in the constructor. Done.

---

*[talpid-core/src/firewall/system_state.rs, line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFMP84L4gijnJ3Ki_a3:-LFMgwTzC24ufUDiKoXs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/system_state.rs#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Unless I'm missing some part, all this struct does is to hold a path and basically just provide `write`, `read_and_remove` and `remove`? It's very generic and does not add a whole lot of abstraction? Except some logging which makes it sound more focused :)
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/system_state.rs, line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFLq6jR4zdF2Tk7Vbbr:-LFMgx0p3rp84jpKZ94s:bj1pav3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/655243c7fe5a23892dfb57f53d8ffeb8cd4226f8/talpid-core/src/firewall/system_state.rs#L62)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I believe some of these tests are no longer working. I've got it working in 956a0da0d98a80254bbb53489ab59ac32b17b780, you should be able to just cherry pick that :).
</blockquote></details>

As discussed above, I reverted the usage of `SystemStateWriter`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r4.
Review status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 214 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFIMRoc0MfragTprd_N:-LFTQRxB2_K4Oo7Qae45:b752e1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f78d05feb1eadfc5f6dbb818da27e78b5bf960d7/talpid-core/src/firewall/linux/dns.rs#L214)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Does this still happen in the new code?
</blockquote></details>

Sort of, kind of. See my other comment.

---

*[talpid-core/src/firewall/linux/dns.rs, line 107 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFTPH5U3wSSUIAgdJkO:-LFTPH5U3wSSUIAgdJkP:b-k7g8m0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad1b5483637586d03a80a3dba8b2349e1f5628c/talpid-core/src/firewall/linux/dns.rs#L107)):*
> ```Rust
>         let backup_file = PathBuf::from(RESOLV_CONF_BACKUP_PATH);
> 
>         if backup_file.exists() {
> ```

`backup_file.exists()` will silently return false if for instance the file exists but it's not readable due to permissions errors or any other case. Of course, in that case, maybe there's not much we can do anyway?  I'll leave it up to you to decide if we care about an error like this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 110 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFU60EY1BkM_UtrtVVw:-LFU60EY1BkM_UtrtVVx:b-206zi1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad1b5483637586d03a80a3dba8b2349e1f5628c/talpid-core/src/firewall/linux/dns.rs#L110)):*
> ```Rust
>             info!("Restoring DNS state from backup");
>             let backup =
>                 fs::read_to_string(&backup_file).chain_err(|| ErrorKind::RestoreResolvConf)?;
> ```

If we just use `fs::read` we don't put the UTF-8 restriction on the content here. Maybe `resolv-conf` has the restriction or something, but no need to apply it here if we don't need to

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by jvff** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

---

*[talpid-core/src/firewall/linux/dns.rs, line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFT8b3d6qEopXwS-XEl:-LFX1spB9I8eS2VALqzo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad1b5483637586d03a80a3dba8b2349e1f5628c/talpid-core/src/firewall/linux/dns.rs#L105)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this needs to be an owned `PathBuf`? Looks like it's only used as a reference later, so I suspect `Path` would suffice?
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 107 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFTPH5U3wSSUIAgdJkO:-LFX4Fio7CW0mZij-5Bf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad1b5483637586d03a80a3dba8b2349e1f5628c/talpid-core/src/firewall/linux/dns.rs#L107)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

When it comes to fallible operations of this sort I usually prefer the "just try" approach and handling errors. That usually works around the problem you are describing. It also solves some race conditions. Like here, even if it exists in the if, it can be gone before we try to read it.

So maybe just directly try to read it, and if it returns `NotFound` we are happy. Any other error and we throw it upwards.
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 110 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFU60EY1BkM_UtrtVVw:-LFX4I9gDzeSz6IgzvJV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad1b5483637586d03a80a3dba8b2349e1f5628c/talpid-core/src/firewall/linux/dns.rs#L110)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If we just use `fs::read` we don't put the UTF-8 restriction on the content here. Maybe `resolv-conf` has the restriction or something, but no need to apply it here if we don't need to
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: 0 of 1 files reviewed, all discussions resolved (waiting on @pinkisemils and @faern)

---

*[talpid-core/src/firewall/linux/dns.rs, line 107 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-LFTPH5U3wSSUIAgdJkO:-LFXZqPs4mlknuWdQauv:b3n7p9t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad1b5483637586d03a80a3dba8b2349e1f5628c/talpid-core/src/firewall/linux/dns.rs#L107)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:clap: I like this version of the implementation a lot

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220#-:-LFX_A4mBfQ0m71OE2TK:bnfp4nl)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)*

**Pull request merged**
