### PR TITLE
Fix port selection algorithm

### PR DESCRIPTION
**Pull request by rablador**
Currently, ports are selected randomly. Instead, we should loosely follow what the app does on desktop. Ie,
the target port alternates between a random one every two attempts, and port 53 for the next 2 attempts. And so on.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 447 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUadA3tA8pcJGf7HWtr:-NUadA3tA8pcJGf7HWts:b-nwv6e6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffe3ffbcd670af1cd0366a333b31038af0799c37/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L447)):*
> ```Swift
>     case deviceState = "DeviceState"
>     case lastUsedAccount = "LastUsedAccount"
>     case shouldWipeSettings = "ShouldWipeSettings"
> ```

This setting has not yet been released, so it should be fine to change name in accordance to the other names.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 1 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/RelaySelector/RelaySelector.swift` line 223 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUayhoz21uR9zVxXjtH:-NUayhoz21uR9zVxXjtI:b-8g0qez) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/RelaySelector/RelaySelector.swift#L223)):*
> ```Swift
> }
> 
> private extension Array {
> ```

Can we document this ?

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/RelaySelector/RelaySelector.swift` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUbD_f8CMi5AJDL5nZE:-NUbD_f8CMi5AJDL5nZF:bp0ob1g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/RelaySelector/RelaySelector.swift#L100)):*
> ```Swift
>         // 2. The next two should pick port 53.
>         // 3. Repeat steps 1 and 2.
>         let pairsOfFailedAttempts = Array(1 ..< max(numberOfFailedAttempts, 1)).pairs()
> ```

One way to tackle this is to use modulo operator and then simply map it to array of values which should provide a decision whether to use port 53 or random, i.e:

```swift
var use53 = [false, false, true, true]

func shouldUsePort53(_ i: Int) -> Bool {
    return use53[i % use53.count]
}

for i in (0...10) {
    print("Attempt \(i), use 53? \(shouldUsePort53(i))")
}
```

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUbHOUH9O6VUmCR1Smg:-NUbHOUH9O6VUmCR1Smh:b-9fl4l6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
You didn't mean to do that. It's what Xcode does when you switch branches.
___
*[`ios/RelaySelector/RelaySelector.swift` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUbD_f8CMi5AJDL5nZE:-NUbIMOX8LTlDQ3xbwhx:bdernkn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/RelaySelector/RelaySelector.swift#L100)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

One way to tackle this is to use modulo operator and then simply map it to array of values which should provide a decision whether to use port 53 or random, i.e:

```swift
var use53 = [false, false, true, true]

func shouldUsePort53(_ i: Int) -> Bool {
    return use53[i % use53.count]
}

for i in (0...10) {
    print("Attempt \(i), use 53? \(shouldUsePort53(i))")
}
```
</blockquote></details>

Or as you probably figured out by now, this works too:

```swift
let shouldUse53 = i % 4 == 2 || i % 4 == 3
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUbHOUH9O6VUmCR1Smg:-NUf94592lSxXMvud7Gn:b50wspk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You didn't mean to do that. It's what Xcode does when you switch branches.
</blockquote></details>

Indeed 🫠
___
*[`ios/RelaySelector/RelaySelector.swift` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUbD_f8CMi5AJDL5nZE:-NUfBeAr3MMlsQQ7LgA7:bnu6m29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/RelaySelector/RelaySelector.swift#L100)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Or as you probably figured out by now, this works too:

```swift
let shouldUse53 = i % 4 == 2 || i % 4 == 3
```
</blockquote></details>

Went with second suggestion.
___
*[`ios/RelaySelector/RelaySelector.swift` line 223 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-NUayhoz21uR9zVxXjtH:-NUf8raD7z0SA_hH6EKE:bm8yn3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79e36e286262c95263ee584dd9531bfb3c03ce2c/ios/RelaySelector/RelaySelector.swift#L223)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we document this ?
</blockquote></details>

Removed it and used a better approach courtesy of @pronebird.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4653#-:-NUgF6ia0Nmd8w2Fi6sT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
