### PR TITLE
Refactor Linux DNS errors

### PR DESCRIPTION
**Pull request by jvff**
While testing the app on Linux, I ran into some DNS errors during initialization. From the error alone, it was hard to find out what was going wrong, so this PR attempts to refactor the errors so that finding the point of failure becomes easier.

Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Linux version not released yet.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGPJv70Ck2w3Xe0KCEx:-LGPJv7157_W9YGwvSaQ:b-txj2w1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L238)):*
> ```Rust
>     let contents = fs::read_to_string(RESOLV_CONF_PATH).chain_err(|| ErrorKind::ReadResolvConf)?;
> 
>     fs::write(RESOLV_CONF_BACKUP_PATH, contents.as_bytes()).chain_err(|| ErrorKind::WriteBackup)?;
> ```

Can't this write be replaced by a call to `update_backup`? If the parsing is done before the writing. Thus we only write to the backup file in one location. Also makes the written backup always be a stringified instance of a `Config` rather than sometimes be that and sometimes a verbatim copy of what was in `/etc/resolv.conf`.

Also parsing before writing the backup stops us from writing a backup of something that is unparseable anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGPJv70Ck2w3Xe0KCEx:-LGPKPU09_iHT0ZKIfAi:b-46ejiy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L238)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can't this write be replaced by a call to `update_backup`? If the parsing is done before the writing. Thus we only write to the backup file in one location. Also makes the written backup always be a stringified instance of a `Config` rather than sometimes be that and sometimes a verbatim copy of what was in `/etc/resolv.conf`.

Also parsing before writing the backup stops us from writing a backup of something that is unparseable anyway.
</blockquote></details>

And then probably rename `update_backup` to `write_backup` since basically what it does is to write a `Config` to a hardcoded path. Used both for updates and initial backups.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGQ4fIt02CXQR4N1qE5:-LGQ4fIt02CXQR4N1qE6:bcqatnk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L61)):*
> ```Rust
>         }
> 
>         WriteBackup {
> ```

Will the caller change it's behaviour depending on whether we fail with `WriteBackup` and `UpdateBackup`?

I think external errors should be defined in their respective `foreign_links` and `links` blocks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGQ4fIt02CXQR4N1qE5:-LGQ6Pcg2H66VHMqBKMF:b-2s745f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L61)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Will the caller change it's behaviour depending on whether we fail with `WriteBackup` and `UpdateBackup`?

I think external errors should be defined in their respective `foreign_links` and `links` blocks.
</blockquote></details>

That depends on the context I would say. Basically almost all errors in this module are `io::Error`s. But just exposing them directly would not provide much help. If one calls `DnsSettings::set_dns()` it's good to be able to know if taking a backup failed or if writing the new settings failed. But in general I agree some of the errors here can be merged, yes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGQ4fIt02CXQR4N1qE5:-LGQ7eCd8MutLRdYWcc7:b260kjz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L61)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

That depends on the context I would say. Basically almost all errors in this module are `io::Error`s. But just exposing them directly would not provide much help. If one calls `DnsSettings::set_dns()` it's good to be able to know if taking a backup failed or if writing the new settings failed. But in general I agree some of the errors here can be merged, yes.
</blockquote></details>

It's fairly unlikely that they will implement different behavior depending on the error given by `set_dns()` (example), but the error chain will provide better details when printed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by pinkisemils** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGQ4fIt02CXQR4N1qE5:-LGQ7RfzCd6AK_d4IQkh:b-48ph95) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L61)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's fairly unlikely that they will implement different behavior depending on the error given by `set_dns()` (example), but the error chain will provide better details when printed.
</blockquote></details>

Would there be any information gained? I'm OK with discriminating different cases when it brings more information. In this case, and in in the `set_dns()` example, it would.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[talpid-core/src/firewall/linux/dns.rs, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGQ4fIt02CXQR4N1qE5:-LGQHgQSA69_M0Dwce5d:bi4at7a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L61)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would there be any information gained? I'm OK with discriminating different cases when it brings more information. In this case, and in in the `set_dns()` example, it would.
</blockquote></details>

I would say the `io::Error` just provides info as to why a low level operation failed. It will for example just say `Permission denied` or `File not found`. Not which file or if it tried to read or write it etc.

So one layer above `io::Error` or equivalent error not originating in this module, one can have two generic errors on that that are `WriteFile(path: PathBuf)` and `ReadFile(path: PathBuf)` that allow adding the data on which file failed. Or one can have four errors `WriteResolvConf`, `WriteBackup`, `ReadResolvConf`, `ReadBackup`. I don't think the latter add's any value really, it just omits having to pass the path to the error.
Other errors on this layer includes `ResolvConfParseError` to chain something on top of the error from that crate. As well as an error when unable to watch a path with `notify`.

Above this one might want to have a third layer adding which generic operation failed. Such as `BackupDnsError` that underneath can be either reading the original file, parsing it or writing the backup file. So from a `set_dns` operation one can either get a `BackupDnsError` or an error that writing the new settings failed.

That's just a verbose way of how I build the chains in my head :P

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by jvff** [comment]
Yeah, it's hard finding the right balance between the information present in the errors and the information the user of the module has to deal with when using the error types.

Here's another attempt. This time, I isolated the errors that the module "exports", i.e., the error types that external modules might use. The other errors have been contained in this module, and have had their types replaced with pure messages.

The idea is to preserve the (extra) amount of error information in the chain without burdening the external users with that information.

---

Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

---

*[Cargo.lock, line 768 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGSIi4h8T9f2ubsMSd7:-LGSIi4h8T9f2ubsMSd8:bre4tz2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/Cargo.lock#L768)):*
> ```TOML
> [[package]]
> name = "mullvad-cli"
> version = "2018.2.0-beta1"
> ```

I actually don't know why I got this. Shouldn't this have been included previously? Or should I remove this?

---

*[talpid-core/src/firewall/linux/dns.rs, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGQ4fIt02CXQR4N1qE5:-LGSG2c0-71oxM-YemZ3:b-euy54r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L61)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I would say the `io::Error` just provides info as to why a low level operation failed. It will for example just say `Permission denied` or `File not found`. Not which file or if it tried to read or write it etc.

So one layer above `io::Error` or equivalent error not originating in this module, one can have two generic errors on that that are `WriteFile(path: PathBuf)` and `ReadFile(path: PathBuf)` that allow adding the data on which file failed. Or one can have four errors `WriteResolvConf`, `WriteBackup`, `ReadResolvConf`, `ReadBackup`. I don't think the latter add's any value really, it just omits having to pass the path to the error.
Other errors on this layer includes `ResolvConfParseError` to chain something on top of the error from that crate. As well as an error when unable to watch a path with `notify`.

Above this one might want to have a third layer adding which generic operation failed. Such as `BackupDnsError` that underneath can be either reading the original file, parsing it or writing the backup file. So from a `set_dns` operation one can either get a `BackupDnsError` or an error that writing the new settings failed.

That's just a verbose way of how I build the chains in my head :P
</blockquote></details>

I've attempted to reduce the types of errors to the minimal set that's meaningful to the outside modules. I tried to keep all the detail by chaining the extra information as a normal message.

---

*[talpid-core/src/firewall/linux/dns.rs, line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGPJv70Ck2w3Xe0KCEx:-LGSIc8M7cKfCe_3-qEv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaf831a56d4fa7e7fbc986fb387063a4f7e5499c/talpid-core/src/firewall/linux/dns.rs#L238)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

And then probably rename `update_backup` to `write_backup` since basically what it does is to write a `Config` to a hardcoded path. Used both for updates and initial backups.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-:-LGSFNCf3cP2BtFT0Ra7:b-2dizdq)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r2.
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[Cargo.lock, line 768 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGSIi4h8T9f2ubsMSd7:-LGUO2OT6C3I9wSuhT3b:b-42iczg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/Cargo.lock#L768)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I actually don't know why I got this. Shouldn't this have been included previously? Or should I remove this?
</blockquote></details>

Maybe we commited `Cargo.toml` files when we bumped the versions but not the lock files? I think it's OK to commit these.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by faern** [comment]
Review status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[Cargo.lock, line 768 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGUvOif9xtP1FRNnKFD:-LGUvOig5EHGwCV_q4_T:b7yx836) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/Cargo.lock#L768)):*
> ```TOML
> [[package]]
> name = "mullvad-cli"
> version = "2018.2.0-beta1"
> ```

This has been updated in another PR already.

---

*[talpid-core/src/firewall/linux/dns.rs, line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGUvnU9AF-cOC5NunlD:-LGUvnU9AF-cOC5NunlE:bit7rf7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/talpid-core/src/firewall/linux/dns.rs#L45)):*
> ```Rust
> impl DnsSettings {
>     pub fn new() -> Result<Self> {
>         Self::restore_persisted_state().chain_err(|| ErrorKind::RestoreResolvConf)?;
> ```

The method `restore_persisted_state()` is already a oneliner that chains this same error. So you will always get two layers of the same error here?

Also, can't that method be directly inlined here since it's just a oneliner anyway?

---

*[talpid-core/src/firewall/linux/dns.rs, line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGUwE1u633bIdSCbJqp:-LGUwE1v0M_xOuybFBfE:b-qk3jcv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/talpid-core/src/firewall/linux/dns.rs#L60)):*
> ```Rust
>         let new_state = match state.take() {
>             None => State {
>                 backup: backup_config().chain_err(|| ErrorKind::BackupResolvConf)?,
> ```

Kind of the same as the above comment. The implementation of `backup_config` consists of just two lines of code, both of which already chain with this error, `BackupResolvConf`. So in the case of an error you will always get two layers of the same error. Probably better to not chain in `backup_config` but only here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by jvff** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

---

*[talpid-core/src/firewall/linux/dns.rs, line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGUvnU9AF-cOC5NunlD:-LGUxx47CygdPitTU_Hk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/talpid-core/src/firewall/linux/dns.rs#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The method `restore_persisted_state()` is already a oneliner that chains this same error. So you will always get two layers of the same error here?

Also, can't that method be directly inlined here since it's just a oneliner anyway?
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGUwE1u633bIdSCbJqp:-LGVbXMf6-Zd4YnKXZ6N:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/talpid-core/src/firewall/linux/dns.rs#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Kind of the same as the above comment. The implementation of `backup_config` consists of just two lines of code, both of which already chain with this error, `BackupResolvConf`. So in the case of an error you will always get two layers of the same error. Probably better to not chain in `backup_config` but only here.
</blockquote></details>

Done.

---

*[Cargo.lock, line 768 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGUvOif9xtP1FRNnKFD:-LGUx-S33PMCC--DO40X:b-wn64bb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f991509f1a89f3c3eae8df3c7ed46406b0b7f584/Cargo.lock#L768)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This has been updated in another PR already.
</blockquote></details>

Done, rebased.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Comment by jvff** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

---

*[talpid-core/src/firewall/linux/dns.rs, line 195 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGZMjhn3j07MsjYIPjk:-LG_aeMs5P-fa2_BETyO:b-qkfit4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd82c9a53364728b4191f416bbe2f67eaa037601/talpid-core/src/firewall/linux/dns.rs#L195)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Both `fs::read_to_string` and `fs::remove_file` should accept anything `AsRef<Path>` so I don't think we need to create a `Path` at all here. In all other places in this module we use the const directly.

I know this code was just moved and not changed, so sorry for that. But I guess we could improve a little bit while at it?
</blockquote></details>

Done. Improvements are always welcome :)

---

*[talpid-core/src/firewall/linux/dns.rs, line 208 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262#-LGZNKhC6SkVUfpOLOSX:-LG_ayqH6riafi6YZygq:b-mvbnxe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd82c9a53364728b4191f416bbe2f67eaa037601/talpid-core/src/firewall/linux/dns.rs#L208)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Regarding not wanting to see it by default. Yes, currently the daemon is executed with `-v` so it would be visible by default. But if we should ever be able to change that we must implement log levels as they are intended, not as we currently use them :P
The daemon currently run with `-v` because we are always debugging it :)
</blockquote></details>

Done, that makes sense indeed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)*

**Pull request merged**
