### PR TITLE
Make the Voucher view more comforming to designs

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR makes the voucher view closer to the originally intended design.
A title has been added, a switch for a `compactMode` where the view is now shown fully (when presented from the account view) 
Fonts and font weights have been changed, as well as some margins.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
The margins in compact mode are not correct, they should be aligned with alert margins. See https://mullvad.slack.com/archives/C052D9X882U/p1694419482421749 for discussion and https://reviewable.io/reviews/mullvad/mullvadvpn-app/5152 for a possible solution.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-:-NemUQ_f43gXPrTqXDLL:buavzfy)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 133 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-NemQwyfDsH3gzkTXlp-:-NemQwyg-wVHn3-afCTP:b-v0pp3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bc8ca5142f32f3530b61b9ce3deaf2e18092118/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L133)):*
> ```Swift
>     static let padding4: CGFloat = 4
>     static let padding8: CGFloat = 8
>     static let padding10: CGFloat = 10
> ```

This isn't a criticism of the newly added padding10 but rather of the whole idea of having a corresponding number for each conceivable padding. This will not contribute to a layout with standardised margins and padding, but rather a more cumbersome free-for-all.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-NemSu_D7GMDwkg707S1:-NemSu_D7GMDwkg707S2:b-axf4x3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bc8ca5142f32f3530b61b9ce3deaf2e18092118/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L44)):*
> ```Swift
>             comment: ""
>         )
>         label.textColor = .white
> ```

No need to disable translatesAutoresizingMaskIntoConstraints explicitly. This happens automatically when view is added to a stack view. Same goes for all the other views below.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-NemTyoP5Y8B3RRWkBgU:-NemTyoP5Y8B3RRWkBgV:b-hvndfw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bc8ca5142f32f3530b61b9ce3deaf2e18092118/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L52)):*
> ```Swift
>     private let enterVoucherLabel: UILabel = {
>         let label = UILabel()
>         label.font = .systemFont(ofSize: 15, weight: .semibold)
> ```

Why not use preferredFont here? (and everywhere) We even have an extension with support for weight.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 133 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-NemQwyfDsH3gzkTXlp-:-NemYMel-9c-DtliN_lj:bxtc0a4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bc8ca5142f32f3530b61b9ce3deaf2e18092118/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L133)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This isn't a criticism of the newly added padding10 but rather of the whole idea of having a corresponding number for each conceivable padding. This will not contribute to a layout with standardised margins and padding, but rather a more cumbersome free-for-all.
</blockquote></details>

I agree, but that's what the designs specify, and I didn't want to introduce a magic number
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-NemSu_D7GMDwkg707S1:-Nem__OHBFrrrsDcyYwZ:b-7jihcw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bc8ca5142f32f3530b61b9ce3deaf2e18092118/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L44)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No need to disable translatesAutoresizingMaskIntoConstraints explicitly. This happens automatically when view is added to a stack view. Same goes for all the other views below.
</blockquote></details>

That's good to know, I'll modify those
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-NemTyoP5Y8B3RRWkBgU:-NemZfdZ7AyGIZd3eG6D:b-5r3f4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bc8ca5142f32f3530b61b9ce3deaf2e18092118/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L52)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why not use preferredFont here? (and everywhere) We even have an extension with support for weight.
</blockquote></details>

Because I couldn't get it to look like the designs. However, I can do this 
`label.font = .preferredFont(forTextStyle: .body, weight: .semibold).withSize(15)` Which is visually the same as `systemFont` so I'll go with that

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 280 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165#-Nen20ms0SVOUk6zBtng:-Nen20mt4xei7JxKWfwV:bxybelu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6693f690c0e8aad9be1f19f5c601b757aca0bb1/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L280)):*
> ```Swift
>     private func configureUI() {
>         addConstrainedSubviews([scrollView]) {
>             scrollView.pinEdgesToSuperviewMargins(.all(configuration.layoutMargins))
> ```

`scrollView.pinEdgesToSuperviewMargins(.all(configuration.layoutMargins))` will fix the last layout margin inconsistency in compact mode.

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
