### PR TITLE
Update screenshots to use post quantum tunnel

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281)

### CODE REVIEW

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 435 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-NyyDLvuEJqTlrpZGHaS:-NyyDLvuEJqTlrpZGHaT:bgv3t53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0a2a7e53042f6efce950f43f42b1658cd359e30/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L435)):*
> ```Swift
>     private func setNotificationControllerParent(isPrimary: Bool) {
>         // We can't close banners in the screenshot tests due to how the NotificationController view
>         // is overridden, so we need this horrible workaround to make sure that no banners are visible.
> ```

do we wanna prevent showing any type of notifications when target is `screenshots`? if `yes` then we can do that in `setupNotifications()` at `AppDelegate`

**Review by niklasberglund — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 435 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-NyyPstg78aQbjCIr6px:-NyyPstg78aQbjCIr6py:bm8f89m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0a2a7e53042f6efce950f43f42b1658cd359e30/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L435)):*
> ```Swift
>     private func setNotificationControllerParent(isPrimary: Bool) {
>         // We can't close banners in the screenshot tests due to how the NotificationController view
>         // is overridden, so we need this horrible workaround to make sure that no banners are visible.
> ```

The workaround is a bit sad but understandable since its a pain to make accessibility identifiers work for this view controller. Is there/should there be a Linear ticket for making it work?
___
*[`ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift` line 134 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-NyyPSyi0mTur2Pzzo45:-NyyPSyj9lNLR2r4snEw:b-qrsa11) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0a2a7e53042f6efce950f43f42b1658cd359e30/ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift#L134)):*
> ```Swift
>         app.buttons[AccessibilityIdentifier.disconnectButton.rawValue].tap()
>         app.buttons[AccessibilityIdentifier.secureConnectionButton.rawValue].tap()
>         snapshot("QuantumResistantConnectionSecured")
> ```

This might be prone to timing issues. There is an accessibility identifier `connectionStatusConnectedLabel` that you could wait for. It is set for the secure connection label when tunnel status is `.connected`.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @mojganii and @niklasberglund)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 435 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-NyyDLvuEJqTlrpZGHaS:-NyyYTaY4zCKCV5-FUGu:b-83qnvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0a2a7e53042f6efce950f43f42b1658cd359e30/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L435)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do we wanna prevent showing any type of notifications when target is `screenshots`? if `yes` then we can do that in `setupNotifications()` at `AppDelegate`
</blockquote></details>

Ah, much better!
___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 435 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-NyyPstg78aQbjCIr6px:-NyyYWBo7b3IfIooYmKE:bo4ltem) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0a2a7e53042f6efce950f43f42b1658cd359e30/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L435)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

The workaround is a bit sad but understandable since its a pain to make accessibility identifiers work for this view controller. Is there/should there be a Linear ticket for making it work?
</blockquote></details>

It would probably mean a lot of refactoring. I have created a ticket for it: https://linear.app/mullvad/issue/IOS-704/make-notifications-accessible
___
*[`ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift` line 134 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-NyyPSyi0mTur2Pzzo45:-NyyYqIY3geZNGQOr2IX:b-6sozws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0a2a7e53042f6efce950f43f42b1658cd359e30/ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift#L134)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

This might be prone to timing issues. There is an accessibility identifier `connectionStatusConnectedLabel` that you could wait for. It is set for the secure connection label when tunnel status is `.connected`.
</blockquote></details>

Done. Not using the `BaseUITestCase` constants here since they're not available and we'll rewrite this whole class soon anyway.

**Review by niklasberglund — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6281#-:-Nyz4H97EqtDkgeY1kTS:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Comment by rablador** [comment]
Replaced by https://linear.app/mullvad/issue/IOS-645/update-location-view-screenshot-automation.

**Pull request closed without merging**
