### PR TITLE
Fix `wireguard-go-rs` build for different Android targets

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR addresses several issues with building `libwg.so` for the supported Android targets. It removes `wireguard-go-rs/libwg/build-android.sh` in favor of `wireguard-go-rs/build.rs`.

The biggest change is that only the actual target is built, and not all 4 Android targets which was the case for `build-android.sh`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-:-O5SwZo8AvZB-OsTYTsv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`wireguard-go-rs/build.rs` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5Sx90j-gzsElU2Lu7T:-O5Sx90j-gzsElU2Lu7U:box5uag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L166)):*
> ```XML
> /// Compile libwg as a dynamic library for android and place it in `OUT_DIR`.
> // NOTE: We use dynamic linking as Go cannot produce static binaries specifically for Android.
> fn build_android_dynamic_lib(daita: bool) -> anyhow::Result<()> {
> ```

Does it make sense to toggle daita? I don't think we adapt the UI to this feature flag, so it might be problems if we generate a binary without the daita support while UI thinks we do have it?
___
*[`wireguard-go-rs/build.rs` line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5SwN0eD1ws-yshDZDy:-O5SwN0eD1ws-yshDZDz:b-nnq002) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L226)):*
> ```XML
>     };
> 
>     // Create the directory with RWX permissions for all users so that the build server can clean
> ```

Do we need `RWX`, would `RW-` be enough?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`wireguard-go-rs/build.rs` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5Sx90j-gzsElU2Lu7T:-O5T55zg595mw0KPWqIV:b-69477x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L166)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Does it make sense to toggle daita? I don't think we adapt the UI to this feature flag, so it might be problems if we generate a binary without the daita support while UI thinks we do have it?
</blockquote></details>

I mostly did it like this to be in line with how `libwg` is built for linux and macOS (see `build_static_lib`). Since adding support for DAITA is not part of this PR, the `daita: bool` argument is just preparatory work for https://github.com/mullvad/mullvadvpn-app/pull/6684. Either the argument is simply set to `true` in that PR, or we remove this argument and make the subsequent changes https://github.com/mullvad/mullvadvpn-app/pull/6684 such that we always assume that `libwg` should be compiled with DAITA :blush:
___
*[`wireguard-go-rs/build.rs` line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5SwN0eD1ws-yshDZDy:-O5T6Ueg0FAKm3SxNKA7:b-5wyqnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L226)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we need `RWX`, would `RW-` be enough?
</blockquote></details>

`RW-` ought to be enough, but I would prefer if we didn't need to muck with permissions at all :thinking:

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-:-O5T8coc9O2-SqAw2D6c:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by albin-mullvad — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-:-O5TBNxU2AOyqcIzNa4b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`wireguard-go-rs/build.rs` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TBR0jAQE1gAbRYp0f:-O5TBR0jAQE1gAbRYp0g:bs18xua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dfc044e63b9db27be8de83b3b4a7ef33efcb765/wireguard-go-rs/build.rs#L59)):*
> ```XML
>             "armv7-linux-androideabi" => Ok(Armv7),
>             "i686-linux-android" => Ok(I686),
>             _ => bail!("{input} is not a support android target!"),
> ```

typo: -> `supported`



_Code quote:_
```XML
support
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`wireguard-go-rs/build.rs` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TBR0jAQE1gAbRYp0f:-O5TD0gl4XaDSQ4Oi1CE:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dfc044e63b9db27be8de83b3b4a7ef33efcb765/wireguard-go-rs/build.rs#L59)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

typo: -> `supported`
</blockquote></details>

Done

**Review by Rawa — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`wireguard-go-rs/build.rs` line 221 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TEtVG3qsPnZyce-va:-O5TEtVG3qsPnZyce-vb:b2czymd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05a4750dcd98b08b9012cd1c90e73e9ea255ce0b/wireguard-go-rs/build.rs#L221)):*
> ```XML
> /// Note: This function will create the parent directory/directories to `output` if necessary.
> fn android_move_binary(binary: &Path, output: &Path) -> anyhow::Result<()> {
>     // Create the directory with RWX permissions for all users so that the build server can clean
> ```

Should we remove/update the comment?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`wireguard-go-rs/build.rs` line 221 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TEtVG3qsPnZyce-va:-O5TGbVJ3H0q6ijNaQx7:bfv77gt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f0e6547c478250ebdd27712c5e76871e3882f47/wireguard-go-rs/build.rs#L221)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should we remove/update the comment?
</blockquote></details>

:facepalm: 
Fixed!

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98 and @Rawa)

___
*[`wireguard-go-rs/build.rs` line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TGAd08iOw3BkcFvSL:-O5TGAd08iOw3BkcFvSM:b8s57gb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L210)):*
> ```XML
> 
>     // If daita is enabled, also enable the corresponding rust feature flag
>     if daita {
> ```

since daita isn't implemented yet I think we should `bail!` here just to make that clear
___
*[`wireguard-go-rs/libwg/Android.mk` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TEoiy4Fs9hgsibf8L:-O5TEoiz9-3Xc_Px6IwO:b-ytqvf2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f0e6547c478250ebdd27712c5e76871e3882f47/wireguard-go-rs/libwg/Android.mk#L7)):*
> ```Makefile
> DESTDIR ?= $(OUT_DIR)
> CARGO_TARGET_DIR ?=
> TARGET ?=
> ```

What is `TARGET` and `CARGO_TARGET_DIR` used for?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @hulthe and @Rawa)

___
*[`wireguard-go-rs/build.rs` line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TGAd08iOw3BkcFvSL:-O5THbnS5p3ItGIMzuzs:b3yufgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L210)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

since daita isn't implemented yet I think we should `bail!` here just to make that clear
</blockquote></details>

While you are right, it will be enabled in https://github.com/mullvad/mullvadvpn-app/pull/6684 so the window of potential confusion is rather small :blush:

Do you think I should remove the bool?
___
*[`wireguard-go-rs/libwg/Android.mk` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TEoiy4Fs9hgsibf8L:-O5THW4A422ZPL3pWg37:b-qt2md0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f0e6547c478250ebdd27712c5e76871e3882f47/wireguard-go-rs/libwg/Android.mk#L7)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

What is `TARGET` and `CARGO_TARGET_DIR` used for?
</blockquote></details>

Preparatory work, could be pushed to https://github.com/mullvad/mullvadvpn-app/pull/6684 I suppose :shrug:

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98 and @Rawa)

___
*[`wireguard-go-rs/build.rs` line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TGAd08iOw3BkcFvSL:-O5TIKPEE633mRAPScKS:b-ihd7sl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/238740cc9f049a9e9ea60484d159cee5176e2af8/wireguard-go-rs/build.rs#L210)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

While you are right, it will be enabled in https://github.com/mullvad/mullvadvpn-app/pull/6684 so the window of potential confusion is rather small :blush:

Do you think I should remove the bool?
</blockquote></details>

Ah ok, If it's going to be fixed soon then I don't mind
___
*[`wireguard-go-rs/libwg/Android.mk` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-O5TEoiy4Fs9hgsibf8L:-O5TIRqu7okoBWPi6KVQ:b-ihd7sl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f0e6547c478250ebdd27712c5e76871e3882f47/wireguard-go-rs/libwg/Android.mk#L7)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Preparatory work, could be pushed to https://github.com/mullvad/mullvadvpn-app/pull/6684 I suppose :shrug:
</blockquote></details>

Ah ok, If it's going to be fixed soon then I don't mind

**Review by hulthe — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6701#-:-O5TO5mdCPh9PMFoEdy-:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Rawa)

**Pull request merged**
