### PR TITLE
Add toggle tunnel Siri intent to iOS app

### PR DESCRIPTION
**Pull request by nchlscs**
## Motivation
iOS does not support split tunneling. But there is a workaround using Siri Shortcuts app. Automation allows you to perform specific actions when opening and closing selected applications. This Pull Request adds Siri Shortcuts integration to the Mullvad iOS app.

## Example
Let's say we want to turn off the tunnel while using maps and calendar.
1. Open Shortcuts
2. Tap on "Automation"
3. Tap on "Create Personal Automation"
4. Choose "App"
5. Choose "Maps" and "Calendar"
6. Select "Is Opened" option
7. Tap on "Next"
8. Tap on "Search for apps and actions"
9. Type and select "Toggle VPN Connection" from Mullvad
10. Set "Off" state
11. Tap on "Next"
12. Turn off "Ask Before Running" and "Notify When Run"
13. Tap on "Done"

Follow the same steps by selecting "Is Closed" in step 6 and "On" in step 10. Now, when opening maps or calendar, the tunnel will turn off and turn back on when changing the application.

## Availability
The minimum version is iOS 13. iOS 15.4 allows you to disable Automation notifications, which makes it less annoying to use.

## Git checklist

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3489)

### CODE REVIEW

**Comment by pronebird** [comment]
Hi,

I think the reason why this workaround works is because existing connections are not terminated when VPN comes back up. We do plan to implement [includeAllNetworks](https://developer.apple.com/documentation/networkextension/nevpnprotocol/3131931-includeallnetworks) which should tackle this, however we had a few obstacles in enabling that specific setting on iOS. I don't think this PR offers a reliable solution.

I wish I could accept that PR, but sadly not this time. 

Note that we also had another [request](https://github.com/mullvad/mullvadvpn-app/issues/2897) to add intents to start or stop VPN with Siri, but that would only work if we were to implement the intents handling inside the main bundle, since we'd have to turn off the on-demand setting in VPN configuration to prevent the tunnel from coming back up. Intents extension simply does not have sufficient permissions to persist VPN configuration changes. So if we were to implement intents, then we'd probably handle them inside the main bundle.

**Comment by nchlscs** [comment]
@pronebird 
I know it’s closed, just want to share some observations about Intents extensions. Most likely, extensions have the same permissions as the main app to modify VPN configurations. There is, though, an undocumented behaviour ([or a bag](https://developer.apple.com/forums/thread/96020)), that does not allow to modify configurations created by another bundle (doesn’t matter, was it the main app or an extension). Meanwhile, if you make an exact copy of that configuration, it’ll be saved successfully, and allows us to toggle on-demand setting from the extension. I’ve updated this [pull request on my fork](https://github.com/nchlscs/mullvadvpn-app/pull/1/files#diff-99a899c76a44c7aebc6322f5da8fc5ffcedcdf6bf9b07bf86e69461fd19e9786) to demonstrate how it works, if you are interested.

By the way, do you have any plans to implement intents handling, or don't you see this feature in your roadmap?

**Comment by pronebird** [comment]
@nchlscs Sorry for a late reply. I must have missed your message. Interesting approach, however I think it's probably more reliable to use intents eligible for in-app handling (#3807). There intents to control the VPN tunnel should become available with the next release. (Also see: https://github.com/mullvad/mullvadvpn-app/issues/2897)

**Comment by nchlscs** [comment]
@pronebird 
Thanks for a reply. I missed the fact there is the background handling starting iOS 14, thought it was a privilege of an extension only. Agree that keeping this in the main app is more reliable and maintainable. I tried the latest master, works like a charm. The only thing I’m missing now is to be able to add shortcuts via `INUIEditVoiceShortcutViewController` from the app so no need to configure them manually on each device. Arguable, but I think this is a more obvious way to add shortcuts for the most users. I was going to suggest this small feature with the new PR, but if you say this is redundant functionality, I’ll do nothing.

**Pull request closed without merging**
