### PR TITLE
Fix button spacing on android

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
Nice job :lgtm: 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388#-:-Ni4iDtc0Lgywa-3WxPu:b-w8412l)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388#-Ni4i1pR5l9i1sZDclvq:-Ni4i1pR5l9i1sZDclvr:b-ga69vr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca3b21afd871169afc25f9b055ed36b77c05cecd/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L12)):*
> ```Kotlin
>     val bigIconSize: Dp = 44.dp,
>     val buttonHeight: Dp = 44.dp,
>     val buttonSeparation: Dp = 12.dp,
> ```

This is something new, but maybe we can call it `buttonSpacing`?

**Review by Rawa — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @Rawa)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388#-Ni4i1pR5l9i1sZDclvq:-Ni4kZtE02a-xK98fEpS:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca3b21afd871169afc25f9b055ed36b77c05cecd/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This is something new, but maybe we can call it `buttonSpacing`?
</blockquote></details>

Done

**Review by Rawa — COMMENTED** [review]
> Reviewed 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388)* status: 11 of 12 files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 12 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
