### PR TITLE
Android splash screen

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U1eHYA6UNk5SKaEMz:-O0U1eHYA6UNk5SKaEN-:bk0rjk8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L143)):*
> ```Kotlin
>     single { FilteredRelayListUseCase(get(), get()) }
>     single { LastKnownLocationUseCase(get()) }
>     single { SplashCompleteRepository() }
> ```

nit: move to other repositories
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SplashCompleteRepository.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U1ZyB3OhkmuY-RHbv:-O0U1ZyB3OhkmuY-RHbw:bdqjq5d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SplashCompleteRepository.kt#L6)):*
> ```Kotlin
> 
> class SplashCompleteRepository {
>     private val _splashComplete = MutableStateFlow(false)
> ```

Does this need to be a stateflow?
___
*[`android/lib/resource/src/main/res/values-v33/styles.xml` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U2HOe3jaM1cXoo7Ob:-O0U2HOe3jaM1cXoo7Oc:b-69ibed) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/lib/resource/src/main/res/values-v33/styles.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
> ```

We might need to update the paths in `android/scripts/tidy.sh` for this PR. Please double check!
___
*[`android/lib/resource/src/main/res/values-v33/styles.xml` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U1snpE29-OKIGPHFk:-O0U1snpE29-OKIGPHFl:bmlu83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/lib/resource/src/main/res/values-v33/styles.xml#L17)):*
> ```XML
>         <item name="android:windowSplashScreenBehavior">icon_preferred</item>
>     </style>
> </resources>
> ```

Bad EOF?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplashViewModel.kt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U3ziGE4kb9ZBvsoVe:-O0U3ziH0ynTyplpgRQX:busjqyk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplashViewModel.kt#L35)):*
> ```Kotlin
>     }
> 
>     private val _mutableUiState = MutableStateFlow<SplashScreenState>(SplashScreenState(false))
> ```

nit: `_uiState`



_Code quote:_
```Kotlin
_mutableUiState
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424)* status: 5 of 15 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SplashCompleteRepository.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U1ZyB3OhkmuY-RHbv:-O0iHq5r8ueQr5gGyB8J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SplashCompleteRepository.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does this need to be a stateflow?
</blockquote></details>

Done.
___
*[`android/lib/resource/src/main/res/values-v33/styles.xml` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-O0U1snpE29-OKIGPHFk:-O0iHxMV6BuDyqc30RrW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c1feb232e6e30fe753491895785b93dc62f4289/android/lib/resource/src/main/res/values-v33/styles.xml#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Bad EOF?
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6424#-:-O0x5Je087ULtfqRFz1_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
