### PR TITLE
Prevent clogging the server key list during key rotation

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

Previously, the app would create a new private key during each key rotation. However we noticed that the REST request may fail with timeout error even though the server received the new key. 

In order to prevent clogging the server key list, the next key is stored in Keychain and used in key rotation and key regeneration requests until the successful response received from API.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311)

### CODE REVIEW

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 8 of 8 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-:-MuuL3LH9lYCzDpteuYG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-MutmJHm0TuHWoCmLyu4:-MutmJHm0TuHWoCmLyu5:b-xy9qxl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc728fbf6a0a346cacb32681ce7e811d88d82aaf/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L84)):*
> ```Swift
>             if interfaceSettings.addresses.isEmpty {
>                 if let newPrivateKey = interfaceSettings.nextPrivateKey {
>                     replaceOldAccountKey(
> ```

Both `replaceOldAccountKey` and `pushNewAccountKey` look pretty similar to `ReplaceKeyOperation`. Is there any reason to not reuse it here?

**Review by pronebird — COMMENTED** [review]
I have updated `SetAccountOperation` and WireGuard keys should be replaced if the next key is found in the tunnel settings. 

This should tackle situations when people uninstall the app before the next key is sent to server and then reinstall the app and log-in with the same account token, which should recover the old tunnel settings from Keychain.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-:-MuuRHPnBGSUCA7rHVdU:bfscox9)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-MutmJHm0TuHWoCmLyu4:-MuuMrt976dwZhLcr475:b-tjhd8g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc728fbf6a0a346cacb32681ce7e811d88d82aaf/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L84)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Both `replaceOldAccountKey` and `pushNewAccountKey` look pretty similar to `ReplaceKeyOperation`. Is there any reason to not reuse it here?
</blockquote></details>

It felt that the gain was minimal hence I opt-in for duplicating the REST call and then the rest of code is shared with "push" anyway.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

___
*[ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-MutmJHm0TuHWoCmLyu4:-MuuWjtH50tID5YOzbeo:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc728fbf6a0a346cacb32681ce7e811d88d82aaf/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L84)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It felt that the gain was minimal hence I opt-in for duplicating the REST call and then the rest of code is shared with "push" anyway.
</blockquote></details>

Okay :+1:
___
*[ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, line 84 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-Muu_PgM4CY26BAdDdc-:-Muu_PgM4CY26BAdDdc0:b7obs1z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96bbaac7a37d7bf647ef763be9844dd9f023ab5d/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L84)):*
> ```Swift
>             if let newPrivateKey = interfaceSettings.nextPrivateKey {
>                 // Replace key if key rotation had failed.
>                 replaceOldAccountKey(
> ```

What happens if the API call fails due to the key already being removed (or never added)? I can't find where that's caught. Will it just fail to login?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, line 84 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-Muu_PgM4CY26BAdDdc-:-MuugCsY0w5UBrb1KeQ1:bkbrhdx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96bbaac7a37d7bf647ef763be9844dd9f023ab5d/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L84)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

What happens if the API call fails due to the key already being removed (or never added)? I can't find where that's caught. Will it just fail to login?
</blockquote></details>

API adds the new key in all those cases.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-:-Muv2gnPBZM0M5lCwW3g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, line 84 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3311#-Muu_PgM4CY26BAdDdc-:-Muv2hfP1Jn2ETgMp_8l:b-3pa4xa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96bbaac7a37d7bf647ef763be9844dd9f023ab5d/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L84)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

API adds the new key in all those cases.
</blockquote></details>

Ah okay :+1:

**Pull request merged**
