### PR TITLE
Force WG handshake each time the config is updated

### PR DESCRIPTION
**Pull request by dlon**
Fix DES-1563

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-wireguard/src/connectivity/mod.rs` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348#-OEF3trn5JQXaHEmDwED:-OEF3trn5JQXaHEmDwEE:buzuynr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30ecf4cce7c16e350ba177ae7229356759c0994/talpid-wireguard/src/connectivity/mod.rs#L9)):*
> ```XML
> mod pinger;
> 
> pub use check::Cancellable;
> ```

:pick: Technically this should be gated on `android` _or_ `force_wireguard_handshake`? :melting_face: 



_Code quote:_
```XML
pub use check::Cancellable;
```

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-wireguard/src/ephemeral.rs` line 122 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348#-OEJFUPT86toCnxFkAru:-OEJFUPT86toCnxFkArv:bm59kcf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40765cab33d57c36577d851f74ed7b8e8a31e73/talpid-wireguard/src/ephemeral.rs#L122)):*
> ```XML
> ) -> Result<(), CloseMsg> {
>     #[cfg(force_wireguard_handshake)]
>     let _ = establish_tunnel_connection(tunnel, connectivity).await;
> ```

Would be nice with an explicit comment about why the return value is discarded. Obviously we care about the side effect of calling `establish_tunnel_connection` only.



_Code quote:_
```XML
    #[cfg(force_wireguard_handshake)]
    let _ = establish_tunnel_connection(tunnel, connectivity).await;
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-wireguard/src/ephemeral.rs` line 122 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348#-OEJFUPT86toCnxFkAru:-OENpNzXBb2SEtZTeXIW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40765cab33d57c36577d851f74ed7b8e8a31e73/talpid-wireguard/src/ephemeral.rs#L122)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice with an explicit comment about why the return value is discarded. Obviously we care about the side effect of calling `establish_tunnel_connection` only.
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/connectivity/mod.rs` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348#-OEF3trn5JQXaHEmDwED:-OENpQ4B59xVyOKmtN_u:b17lomb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30ecf4cce7c16e350ba177ae7229356759c0994/talpid-wireguard/src/connectivity/mod.rs#L9)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: Technically this should be gated on `android` _or_ `force_wireguard_handshake`? :melting_face:
</blockquote></details>

(Merged them as suggested.)

**Review by MarkusPettersson98 — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348#-:-OENr-Ma68GRim4BFv-L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348#-:-OENw0eHAJI4a7nFzw3D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
