### PR TITLE
Automatic MTU detection linux

### PR DESCRIPTION
**Pull request by Serock3**
Fixes DES-581.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 7 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-wireguard/src/unix.rs` line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpUn74Z04ZQPbJ_G1DZ:-NpUn74Z04ZQPbJ_G1D_:b7fkx7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e212e1ddf17bef70886302a392d0464c6e002029/talpid-wireguard/src/unix.rs#L37)):*
> ```XML
>     if unsafe { libc::ioctl(sock.as_raw_fd(), libc::SIOCSIFMTU, &ifr) } < 0 {
>         let e = std::io::Error::last_os_error();
>         log::error!("{}", e.display_chain_with_msg("libc::ioctl failed"));
> ```

Nit: Could be more specific, e.g. "SIOCSIFMTU failed".

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 1070 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqxGy5olaBg1Oz38F:-NpYqxGy5olaBg1Oz38G:b-itatp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/lib.rs#L1070)):*
> ```XML
>         // todo!("Handle manual MTU lower that minimum")
>     }
>     let in_between = ((x_start + 1)..x_end).filter(|x| x % step_size == 0);
> ```

Could probably use `step_by` here?
___
*[`talpid-wireguard/src/ping_monitor/icmp.rs` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqeliAeftGgVDqujg:-NpYqeliAeftGgVDqujh:bvqpjr4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/ping_monitor/icmp.rs#L65)):*
> ```XML
>     /// Creates a new `Pinger`.
>     ///
>     /// `mtu_discover` sets the `IP_MTU_DISCOVER` flag for the socker, implying no fragementation is
> ```

I guess this is no longer relevant.

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-wireguard/src/lib.rs` line 1070 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqxGy5olaBg1Oz38F:-NpZ-Hp88pPz9-BPUut7:bn9kupk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/lib.rs#L1070)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could probably use `step_by` here?
</blockquote></details>

That will not produce evenly divisible numbers, which I think looks nicer. Since you're starting at 576 you would get 596, 616, 636 and so on.
___
*[`talpid-wireguard/src/unix.rs` line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpUn74Z04ZQPbJ_G1DZ:-NpZ-m9JDKWfV5ew84QU:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e212e1ddf17bef70886302a392d0464c6e002029/talpid-wireguard/src/unix.rs#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Could be more specific, e.g. "SIOCSIFMTU failed".
</blockquote></details>

Done!
___
*[`talpid-wireguard/src/ping_monitor/icmp.rs` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqeliAeftGgVDqujg:-NpZ011S-WB3lDIN0tlp:bnipf2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/ping_monitor/icmp.rs#L65)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I guess this is no longer relevant.
</blockquote></details>

Missed that, good catch! Fixed.

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, 1 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 1070 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqxGy5olaBg1Oz38F:-Npe8tg6AfYSIhq372xk:b1rc7tm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/lib.rs#L1070)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

That will not produce evenly divisible numbers, which I think looks nicer. Since you're starting at 576 you would get 596, 616, 636 and so on.
</blockquote></details>

Do they really need to be divisible? A bit wasteful to compute the `mod` for every single number, IMO. :)

How about

```
let x_start = step_size + x_start - (x_start % step_size);
```

, plus `step_by`?
___
*[`talpid-wireguard/src/ping_monitor/icmp.rs` line 77 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-Npe6OBHBBAsog8drKCi:-Npe6OBHBBAsog8drKCj:b2rm6rj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f53cc3b2635aed70346ba75dff4b96d3d1c4630f/talpid-wireguard/src/ping_monitor/icmp.rs#L77)):*
> ```XML
>             .map_err(Error::SocketOp)?;
> 
>         // nix::sys::socket::setsockopt(fd, opt, val) // TODO: deleteme
> ```

Don't forget to remove this as well.

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`talpid-wireguard/src/lib.rs` line 1070 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqxGy5olaBg1Oz38F:-NpeJlwb5S5ZqxZdeaFo:b-ilc3ou) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/lib.rs#L1070)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do they really need to be divisible? A bit wasteful to compute the `mod` for every single number, IMO. :)

How about

```
let x_start = step_size + x_start - (x_start % step_size);
```

, plus `step_by`?
</blockquote></details>

I think they should be divisible, otherwise it looks lite the MTU detection honed in on some very specific number when in reality it checks in 20 bytes steps. Also, I think it is more likely that the true max MTU is a round number.

I think I found a nice solution though, have a look in the diff.
___
*[`talpid-wireguard/src/ping_monitor/icmp.rs` line 77 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-Npe6OBHBBAsog8drKCi:-NpeMhhg0M6TiZuq9DZh:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f53cc3b2635aed70346ba75dff4b96d3d1c4630f/talpid-wireguard/src/ping_monitor/icmp.rs#L77)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Don't forget to remove this as well.
</blockquote></details>

Done

**Review by Serock3 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-:-NpeMyCW2Ienlj0ww_GM:bnfp4nl)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @dlon)

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-wireguard/src/lib.rs` line 1070 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpYqxGy5olaBg1Oz38F:-NpsIV7E9eu5vR11F7yx:bh8ufr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56f9487b5052ec8a547f8fee8deef35ee456083d/talpid-wireguard/src/lib.rs#L1070)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I think they should be divisible, otherwise it looks lite the MTU detection honed in on some very specific number when in reality it checks in 20 bytes steps. Also, I think it is more likely that the true max MTU is a round number.

I think I found a nice solution though, have a look in the diff.
</blockquote></details>

That is nice!

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: all files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 1041 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptAVTgEH7fmfpAl1V0:-NptAVTgEH7fmfpAl1V1:b-m6u8ej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55e445d0577e77ca2c0775bd628f03cc24f68c49/talpid-wireguard/src/lib.rs#L1041)):*
> ```XML
>         .map_ok(|(packet, _rtt)| {
>             let surge_ping::IcmpPacket::V4(packet) = packet else {
>                 panic!("ICMP ping response was not of IPv4 type");
> ```

I think `unreachable!` would be *slightly* clearer.
___
*[`talpid-wireguard/src/lib.rs` line 1052 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptAIfi5E4XsYDKOUKa:-NptAIfi5E4XsYDKOUKb:bc0n5mw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55e445d0577e77ca2c0775bd628f03cc24f68c49/talpid-wireguard/src/lib.rs#L1052)):*
> ```XML
>         .next()
>         .await
>         .expect("At least one pings should be sent")
> ```

Probably a bit nitpicky and subjective, but you could use `map_err` here instead of `match`.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 1052 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptBFZw8XwWd_GAFWo_:-NptBFZw8XwWd_GAFWoa:bfvjifh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55e445d0577e77ca2c0775bd628f03cc24f68c49/talpid-wireguard/src/lib.rs#L1052)):*
> ```XML
>         .next()
>         .await
>         .expect("At least one pings should be sent")
> ```

I should have thought about this earlier, but is it really safe to unwrap here? Will this not panic if the first ping fails for whatever reason?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: all files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 1052 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptBFZw8XwWd_GAFWo_:-NptCa358zMft71iOf1F:b-4vuhx7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55e445d0577e77ca2c0775bd628f03cc24f68c49/talpid-wireguard/src/lib.rs#L1052)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I should have thought about this earlier, but is it really safe to unwrap here? Will this not panic if the first ping fails for whatever reason?
</blockquote></details>

Never mind, this looks fine.

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
Very nice work! Please see my comments, they should be easily resolvable :blush: 

> Reviewed 1 of 10 files at r1, 1 of 3 files at r5, 1 of 2 files at r7, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-:-NptpjGY8r6V1SeCDar0:bawts8p)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`talpid-tunnel/src/lib.rs` line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-Np_GE1O7Lvy7eFnQJTT:-Np_GE1O7Lvy7eFnQJTU:bc6219l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74c7d1d81dc24ffc8f8aeca4443b22b61f0a1a72/talpid-tunnel/src/lib.rs#L28)):*
> ```XML
> pub const MIN_IPV4_MTU: u16 = 576;
> /// Smallest allowed MTU for IPv6 in bytes
> pub const MIN_IPV6_MTU: u16 = 1280;
> ```

I feel like this is general+useful enough to define in `talpid-types` to promote re-use / easier refactoring. A lot more of our crates depend on `talpid-types` compared to `talpid-tunnel` :blush: 



_Code quote:_
```XML
/// Size of IPv4 header in bytes
pub const IPV4_HEADER_SIZE: u16 = 20;
/// Size of IPv6 header in bytes
pub const IPV6_HEADER_SIZE: u16 = 40;
/// Size of wireguard header in bytes
pub const WIREGUARD_HEADER_SIZE: u16 = 40;
/// Size of ICMP header in bytes
pub const ICMP_HEADER_SIZE: u16 = 8;
/// Smallest allowed MTU for IPv4 in bytes
pub const MIN_IPV4_MTU: u16 = 576;
/// Smallest allowed MTU for IPv6 in bytes
pub const MIN_IPV6_MTU: u16 = 1280;
```
___
*[`talpid-wireguard/src/lib.rs` line 418 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptnMg8AYKp0HTQgg03:-NptnMg8AYKp0HTQgg04:bs7ivfl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5446a665151491a9af378a4c6bf800d1cc6b11/talpid-wireguard/src/lib.rs#L418)):*
> ```XML
>                         };
>                     } else {
>                         log::info!("MTU {verified_mtu} verified to not drop packets");
> ```

I think it would be fine to lower the log level here to either `debug` or `trace` :blush: 



_Code quote:_
```XML
log::info!("MTU {verified_mtu} verified to not drop packets");
```
___
*[`talpid-wireguard/src/lib.rs` line 993 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-Nptno8O5gKmLVyVnTg6:-Nptno8O5gKmLVyVnTg7:bvcokhm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5446a665151491a9af378a4c6bf800d1cc6b11/talpid-wireguard/src/lib.rs#L993)):*
> ```XML
> ///
> /// The detection works by sending evenly spread out range of pings between 576 and the given
> /// current tunnel MTU, and returning the maximum packet size that war returned within a timeout.
> ```

Typo: was



_Code quote:_
```XML
war
```
___
*[`talpid-wireguard/src/lib.rs` line 1031 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-Nptoqui86VFyyaYB-1Z:-Nptoqui86VFyyaYB-1_:b-amehg2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5446a665151491a9af378a4c6bf800d1cc6b11/talpid-wireguard/src/lib.rs#L1031)):*
> ```XML
>                 log::trace!("Sending ICMP ping of total size {mtu}");
>                 client
>                     .pinger(IpAddr::V4(gateway), PingIdentifier(111)) //? Is a static identified ok, or should we randomize?
> ```

Could we resolve this question at this point? :blush: 



_Code quote:_
```XML
.pinger(IpAddr::V4(gateway), PingIdentifier(111)) //? Is a static identified ok, or should we randomize?
```
___
*[`talpid-wireguard/src/lib.rs` line 1062 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptpQ4L36sl6rXNGHw9:-NptpQ4L36sl6rXNGHwA:bn4q6eo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5446a665151491a9af378a4c6bf800d1cc6b11/talpid-wireguard/src/lib.rs#L1062)):*
> ```XML
> 
>     ping_stream
>         .timeout(PING_OFFSET_TIMEOUT) // Start a new, sorter, timeout
> ```

Typo: shorter*



_Code quote:_
```XML
sorter
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-wireguard/src/lib.rs` line 418 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NptnMg8AYKp0HTQgg03:-Nptukty-cLxvjWJwm6P:b-6rosfi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5446a665151491a9af378a4c6bf800d1cc6b11/talpid-wireguard/src/lib.rs#L418)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think it would be fine to lower the log level here to either `debug` or `trace` :blush:
</blockquote></details>

Changed it to debug
___
*[`talpid-wireguard/src/lib.rs` line 1031 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-Nptoqui86VFyyaYB-1Z:-NptuEpF6aicQq4DLXNH:b-aj7q4d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5446a665151491a9af378a4c6bf800d1cc6b11/talpid-wireguard/src/lib.rs#L1031)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Could we resolve this question at this point? :blush:
</blockquote></details>

Done. Also changed identifier to be zero.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-wireguard/Cargo.toml` line 84 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-NpymmzE5yxee5HIKWU9:-NpymmzE5yxee5HIKWUA:b92v4jh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afc9fb89255ca827056209e90f16b50f658a0d2a/talpid-wireguard/Cargo.toml#L84)):*
> ```TOML
> 
> [dev-dependencies]
> proptest = "1.4"
> ```

Seems like there are some trailing characters here :blush:



_Code quote:_
```TOML
proptest = "1.4"
```

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736#-:-Npz6sax-YzW6rel9anz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Review by MarkusPettersson98 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
