### PR TITLE
Add search to location list and refactor select location view

### PR DESCRIPTION
**Pull request by raksooo**
This PR:
* Refactors everything related to the select location view
* Adds a search bar to the select location view

The refactoring consists of:
* Moving all source files related to the view into `gui/src/renderer/components/select-location`.
* Move all sorting/filtering/modifications of relay list into `gui/src/renderer/components/select-location/RelayListContext.tsx`. This means that `gui/src/main/relay-list.ts` could be removed.
* Simplify the components preparing and rendering the list items.
* Split the `SelectLocation` component up into multiple parts.
* Move to functional components and hooks.
* Probably more

Since most of the code has been changed/rewritten I would suggest reviewing everything in `gui/src/renderer/components/select-location` as new files instead of just the changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163)

### CODE REVIEW

**Review by hankolsen — CHANGES_REQUESTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/components/select-location/LocationRow.tsx` line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163#-NHZmCBf9__d0jSNn8IV:-NHZmCBf9__d0jSNn8IW:bfnzjmr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ac01583b51b32b9ba35758aa0411f7c4944041/gui/src/renderer/components/select-location/LocationRow.tsx#L178)):*
> ```XML
>             selected={props.source.selected}
>             disabled={props.source.disabled}
>             location={props.source.location}
> ```

Does StyledLocationRowIcon need a location prop?
___
*[`gui/src/renderer/components/select-location/RelayListContext.tsx` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163#-NHZo7re7JUPfmprj6m2:-NHZo7re7JUPfmprj6m3:bx0c399) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ac01583b51b32b9ba35758aa0411f7c4944041/gui/src/renderer/components/select-location/RelayListContext.tsx#L84)):*
> ```XML
>   const relayListForSearch = useMemo(() => {
>     // It shouldn't search for just one letter
>     if (searchTerm.length === 1) {
> ```

It appears a bit odd if you type two characters and see the list change, then delete one, but the list is still showing the same result as if you had entered two characters.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163)* status: 34 of 39 files reviewed, 2 unresolved discussions (waiting on @hankolsen)

___
*[`gui/src/renderer/components/select-location/LocationRow.tsx` line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163#-NHZmCBf9__d0jSNn8IV:-NH_OhWkCJ-C9jzryXKc:b-dibmrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ac01583b51b32b9ba35758aa0411f7c4944041/gui/src/renderer/components/select-location/LocationRow.tsx#L178)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Does StyledLocationRowIcon need a location prop?
</blockquote></details>

This isn't very clear but `StyledLocationRowIcon` is based on `buttonColor` which requires it.



_Code quote:_
```XML
interface IButtonColorProps {
  selected: boolean;
  disabled?: boolean;
  location?: RelayLocation;
}
```
___
*[`gui/src/renderer/components/select-location/RelayListContext.tsx` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163#-NHZo7re7JUPfmprj6m2:-NH_OwKV1JqiXt_6GtdQ:b-54iex9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ac01583b51b32b9ba35758aa0411f7c4944041/gui/src/renderer/components/select-location/RelayListContext.tsx#L84)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

It appears a bit odd if you type two characters and see the list change, then delete one, but the list is still showing the same result as if you had entered two characters.
</blockquote></details>

Done. It now handles this scenario as if the search string is empty.

**Review by hankolsen — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163#-:-NHeDgJ16jZev6NsOcqK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hankolsen — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4163)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
