### PR TITLE
Remove lots of dependencies from mullvad relay selector

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR is one in a series of PRs which aims to make working with the relay selector easier.

The goal of this PR is to strip the relay selector of some dependencies & code where possible, trying to focus its purpose.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-relay-selector/src/lib.rs` line 959 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-Nr6DKNb6aFi718hYKRA:-Nr6DKNb6aFi718hYKRB:b-ib4rlk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aecacc4ac0e139a88a32942bb40957581ca16dc5/mullvad-relay-selector/src/lib.rs#L959)):*
> ```XML
>     pub fn get_bridge_forced(&self) -> Option<CustomProxy> {
>         let relay_settings = {
>             let config = self.config.lock().unwrap();
> ```

Releasing this lock multiple times potentially introduces race conditions.
___
*[`mullvad-relay-selector/src/lib.rs` line 1079 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-Nr6E9ZR5aIeKYBHDfr3:-Nr6E9ZR5aIeKYBHDfr4:b-jz48nq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aecacc4ac0e139a88a32942bb40957581ca16dc5/mullvad-relay-selector/src/lib.rs#L1079)):*
> ```XML
>         };
>         relay.and_then(|relay| {
>             let bridge = {
> ```

Is there a reason to clone here? We could probably just pass the borrowed relays to `pick_random_bridge`. Are you worried about deadlocks?
___
*[`mullvad-relay-selector/src/lib.rs` line 135 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-Nr6F_EH5ae6PjTaXEPK:-Nr6F_EH5ae6PjTaXEPL:b-cymz91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/924e029bdce973c19f070fdc26a398f40d2857c0/mullvad-relay-selector/src/lib.rs#L135)):*
> ```XML
>         // prefer the resource path's relay list if the cached one doesn't exist or was modified
>         // before the resource one was created.
>         let cached_relays = Self::from_file(cache_path, overrides);
> ```

Are the filenames missing here? Otherwise, if it expects paths, the function should probably not be called `from_dir`.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-relay-selector/src/lib.rs` line 959 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-Nr6DKNb6aFi718hYKRA:-Nr6JeTx5mz4XXfpe0eG:b-e6wh2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aecacc4ac0e139a88a32942bb40957581ca16dc5/mullvad-relay-selector/src/lib.rs#L959)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Releasing this lock multiple times potentially introduces race conditions.
</blockquote></details>

You are right, the lock is now held in the entire scope of `get_bridge_forced`
___
*[`mullvad-relay-selector/src/lib.rs` line 1079 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-Nr6E9ZR5aIeKYBHDfr3:-Nr6I7LMC_QR6dTJjxJq:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aecacc4ac0e139a88a32942bb40957581ca16dc5/mullvad-relay-selector/src/lib.rs#L1079)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is there a reason to clone here? We could probably just pass the borrowed relays to `pick_random_bridge`. Are you worried about deadlocks?
</blockquote></details>

Done
___
*[`mullvad-relay-selector/src/lib.rs` line 135 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-Nr6F_EH5ae6PjTaXEPK:-Nr6HyCU-CBmwSq1WIOJ:b-tsnhwk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/924e029bdce973c19f070fdc26a398f40d2857c0/mullvad-relay-selector/src/lib.rs#L135)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are the filenames missing here? Otherwise, if it expects paths, the function should probably not be called `from_dir`.
</blockquote></details>

This function was refactored to expect file paths instead of directories, so the name should indeed be changed. Nice catch

**Review by dlon — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837#-:-Nr6KhHwBa2ZI9Zy_6mp:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
