### PR TITLE
Design system PR 1

### PR DESCRIPTION
**Pull request by Pururun**
- Set default theme as dark instead of light
- Move to a color token system instead of colors in the theme
- Replace some theme colors with alpha with normal colors
- Remove some usage of color resource

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-NfVwSWbAeqB9DwcXFvn:-NfVwSWbAeqB9DwcXFvo:by93jtc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b20b238f886a2a505ee713d550bc117b5b28494/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L172)):*
> ```Kotlin
>             relay.type == RelayItemType.City ->
>                 MaterialTheme.colorScheme.primary
>                     .copy(alpha = Alpha40)
> ```

I believe this is some transition step, but long we should look into avoiding all these Alpha's together. Maybe the result of
```  MaterialTheme.colorScheme.primary
                    .copy(alpha = Alpha40)
                    .compositeOver(MaterialTheme.colorScheme.background)
```
Is a candidate of being the Secondary color?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-NfVvs1D1vc8GQjjgDAj:-NfVvs1D1vc8GQjjgDAk:baknqkt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b20b238f886a2a505ee713d550bc117b5b28494/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt#L112)):*
> ```Kotlin
>                     ButtonDefaults.buttonColors(
>                         containerColor = MaterialTheme.colorScheme.primary,
>                         contentColor = MaterialTheme.colorScheme.onPrimary
> ```

This looks so nice :star_struck: 
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-NfVw8_lC-XE0qazKigg:-NfVw8_lC-XE0qazKigh:b-orqn3w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b20b238f886a2a505ee713d550bc117b5b28494/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L73)):*
> ```Kotlin
>         //scrim = md_theme_dark_scrim,
>     )
> ```

Idea is to slowly transition there all over?

**Review by Rawa — COMMENTED** [review]
Nice work! :star_struck:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-:-NfVwu068wwhFOdtXL0_:bfc7dwt)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @Pururun)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-NfVvs1D1vc8GQjjgDAj:-NfWM-CwCO119f2kDbGx:b-upynyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b20b238f886a2a505ee713d550bc117b5b28494/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt#L112)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This looks so nice :star_struck:
</blockquote></details>

Indeed! :smile: :thumbsup:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-NfVwSWbAeqB9DwcXFvn:-NfWVHnKEFp6Txnz53CW:b7hq7ia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b20b238f886a2a505ee713d550bc117b5b28494/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L172)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe this is some transition step, but long we should look into avoiding all these Alpha's together. Maybe the result of
```  MaterialTheme.colorScheme.primary
                    .copy(alpha = Alpha40)
                    .compositeOver(MaterialTheme.colorScheme.background)
```
Is a candidate of being the Secondary color?
</blockquote></details>

Yes will add compositeOver.
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210#-NfVw8_lC-XE0qazKigg:-NfWVSzNB5rBmvcoJLkk:buf54gg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b20b238f886a2a505ee713d550bc117b5b28494/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Idea is to slowly transition there all over?
</blockquote></details>

Yes the idea is to take a few colors at a time.

**Comment by Pururun** [comment]
Split this PR into 3 other PRs instead:
https://github.com/mullvad/mullvadvpn-app/pull/5216
https://github.com/mullvad/mullvadvpn-app/pull/5215
https://github.com/mullvad/mullvadvpn-app/pull/5211

**Review by sabercodic — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5210)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

**Pull request closed without merging**
