### PR TITLE
Expose flexible ipc message handling

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to expose flexible message handling that works in parallel with the existing message handling. It also migrates the account repository and data source to use this new message handling. This is an intermediate approach to moving away from the big `ServiceConnectionContainer` class.

Fixes: DROID-414

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgrnuFi-Bjsewl9hfXV:-NgrnuFi-Bjsewl9hfXW:b-r273v3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6bc3ecd2e4f9fe01c8db6bae4b4f7b40f21f9c8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L11)):*
> ```Kotlin
>     val accountCreationResult =
>         messageHandler.events.filterIsInstance(Event.AccountCreationEvent::class).map { it.result }
>     // TODO: We previously also sent a Request here. How should we handle it now?
> ```

This TODO needs to be addressed before merging this PR.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298)* status: 0 of 10 files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgrnuFi-Bjsewl9hfXV:-NgsTyTE4IucF60wQeII:b-lu8lab) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6bc3ecd2e4f9fe01c8db6bae4b4f7b40f21f9c8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L11)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This TODO needs to be addressed before merging this PR.
</blockquote></details>

To avoid fetching too often, I've moved the fetch logic to the main activity and account vm. Apart from that, there are also fetch loops in the out-of-time view and welcome view.

**Review by Pururun — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/MessageHandler.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgsXO1e6JohXVm5w5Cx:-NgsXO1e6JohXVm5w5Cy:b-e9qu7c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/MessageHandler.kt#L8)):*
> ```Kotlin
> 
> interface MessageHandler {
>     val events: Flow<Event>
> ```

I wonder if we should add another way to get filtered events somehow, either here or as some kind of extension function as we otherwise will get a lot `filterIsInstance` everywhere.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgsY3fT5gPu1AUoj1aS:-NgsY3fT5gPu1AUoj1aT:b-otilcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L10)):*
> ```Kotlin
> class ServiceConnectionAccountDataSource(private val messageHandler: MessageHandler) {
>     val accountCreationResult =
>         messageHandler.events.filterIsInstance(Event.AccountCreationEvent::class).map { it.result }
> ```

See comment above.

**Review by Rawa — COMMENTED** [review]
I started looking through this, but feel I don't have enough insight on the daemon communication to have much certainty in my remarks. Maybe this is a step in the right direction, but currently I don't have the insights to say.

I feel we should have some architectural meeting/planning about how the daemon communication should work (maybe we also need some prototyping etc.), then plan some work package on this during 2024 Q1. I believe there is a lot of improvements to be made, and that it can be simplified and made more clear (E.g removing `spawnActor`, use of GlobalScope and all the enum Commands).

 Also if we all have the same view of the future it might be easier to see if we are heading in the right direction. 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-:-NgsbPA_5hqKEamamiur:bhztui1)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-Ngsb5OTCy0Cq9SdSN2S:-Ngsb5OTCy0Cq9SdSN2T:blyv5g2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L8)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.ipc.Request
> 
> class ServiceConnectionAccountDataSource(private val messageHandler: MessageHandler) {
> ```

I'm not sure what this class adds compared to what `AccountRepository` seems like Account repository just basically is a chim calling the functions in here. Could they be one?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-Ngsbr4R-_U52QzH2nDV:-Ngsbr4R-_U52QzH2nDW:b-wunnaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L28)):*
> ```Kotlin
>     fun fetchAccountHistory() = messageHandler.trySendRequest(Request.FetchAccountHistory)
> 
>     fun clearAccountHistory() = messageHandler.trySendRequest(Request.ClearAccountHistory)
> ```

Personally I don't really like this open approach with trySendRequest. I believe we should try and only ever expose suspending functions unless it makes sense not to.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-:-NgsoB0V3SEoiV60lHsJ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
@Rawa good input! Let's continue that discussion in another forum.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-:-Ngssitz0djhSdWNsvcA:b-31k7ns)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/MessageHandler.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgsXO1e6JohXVm5w5Cx:-Ngse2CYEG_Pe77vRajB:b-le456b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/MessageHandler.kt#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I wonder if we should add another way to get filtered events somehow, either here or as some kind of extension function as we otherwise will get a lot `filterIsInstance` everywhere.
</blockquote></details>

Improved the ergonomics, please have a look!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-Ngsb5OTCy0Cq9SdSN2S:-NgseuuNDfOxSDHxiv0v:b10te9j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm not sure what this class adds compared to what `AccountRepository` seems like Account repository just basically is a chim calling the functions in here. Could they be one?
</blockquote></details>

The main purpose was previously that the `ServiceConnectionAccountDataSource` was tightly coupled to each service connection session whereas the repository wasn't. I've removed it now since we no longer have that coupling!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgsY3fT5gPu1AUoj1aS:-Ngse9MW5rcJCcZYIluK:b1r7vnk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So instead of `events.filterIsInstance(Event.AccountCreationEvent::class)` we will have `events(Event.AccountCreationEvent::class)`. Not sure if super important.
</blockquote></details>

Yes, did this combined with an `inline` function :thumbsup:
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-Ngsbr4R-_U52QzH2nDV:-NgseSdk5XwLm3hNF87O:b3guy3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt#L28)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Personally I don't really like this open approach with trySendRequest. I believe we should try and only ever expose suspending functions unless it makes sense not to.
</blockquote></details>

Yes, that would make sense, but I would say that's a different task/scope than this PR. The main purpose of this PR is to allow for Message send/receive in our Google Play Billing implementation.

**Review by Pururun — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/MessageHandler.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5298#-NgsXO1e6JohXVm5w5Cx:-NgstWGM5e7VVv3ArhJ_:b-vs1prh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85387d7a3b8eb43f94be243a947326beea0f4885/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/MessageHandler.kt#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Improved the ergonomics, please have a look!
</blockquote></details>

Looks good!

**Pull request merged**
