### PR TITLE
Add disconnect button to Welcome Screen

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375#-O-jOrTF-HFI2MChKcLe:-O-jOrTG5m35LPrm4CqP:b-aaxp1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/786bcd14f965e0deeaf44aef119c86f64b5e881c/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt#L36)):*
> ```Kotlin
>     }
> 
>     fun showDisconnectButton(): Boolean =
> ```

The only difference from `isSecured` seem to be `actionAfterDisconnect`, right? Are we sure these two functions should be the same (in other words skip this one)?

Also, I'm not sure this function in it's current state belongs in the model since the usage is UI specific (in comparison to the other convenience functions).

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375#-O-jOrTF-HFI2MChKcLe:-O-kDCK0EBV8y-c62G8_:b-y3u8b5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/786bcd14f965e0deeaf44aef119c86f64b5e881c/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The only difference from `isSecured` seem to be `actionAfterDisconnect`, right? Are we sure these two functions should be the same (in other words skip this one)?

Also, I'm not sure this function in it's current state belongs in the model since the usage is UI specific (in comparison to the other convenience functions).
</blockquote></details>

I checked the desktop app and they do not seems to care about `actionAfterDisconnect` so I will just use `isSecured`instead.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375#-O-jOrTF-HFI2MChKcLe:-O-kFWXJ4PN8Ub7hVJFx:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/786bcd14f965e0deeaf44aef119c86f64b5e881c/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I checked the desktop app and they do not seems to care about `actionAfterDisconnect` so I will just use `isSecured`instead.
</blockquote></details>

Done

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375#-:-O-kTUY89mw4nnmTi1AP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375#-O-jOrTF-HFI2MChKcLe:-O-kTPDS5hIlN_uja2rd:b-9m7pm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/786bcd14f965e0deeaf44aef119c86f64b5e881c/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Great! :thumbsup:

**Pull request merged**
