### PR TITLE
Add CI workflows for `test` workspace

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
The testing framework living in `test/` historically had no CI checks. It didn't use to have it while it was developed in a separate repository, nor did it get any during its adoption into the app repository.

This PR introduces some basic CI checks when application logic is touched in the `test` workspace:
- `rustfmt --check` is run on all Rust source files
- `clippy` is run with the same configuration as the main app
- `test-runner` is compiled for all supported platforms (Linux, Windows & macOS)
- `test-manager` is compiled for all supported host platforms (Linux & macOS)

This should hopefully stabilize the development done to the testing framework. There is still more to be done on the CI front in the testing framework, but this is a good start.

Fixes DES-502

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: all files reviewed, 7 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`.github/workflows/clippy-test.yml` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOO0U--K0XNa-IU5nx:-NlOO0U--K0XNa-IU5ny:b9q096) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/clippy-test.yml#L7)):*
> ```YAML
>   pull_request:
>     paths:
>       - 'test/**/*.rs'
> ```

This should probably include the workflow itself.
___
*[`.github/workflows/rustfmt-test.yml` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOOfqQ0LWLFyWK8Ey7:-NlOOfqQ0LWLFyWK8Ey8:b2nreh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/rustfmt-test.yml#L7)):*
> ```YAML
>   pull_request:
>     paths:
>       - 'test/**/*.rs'
> ```

Same as above.
___
*[`.github/workflows/rustfmt-test.yml` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOOn9c4U1YRk6rttgR:-NlOOn9c4U1YRk6rttgS:babkrcu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/rustfmt-test.yml#L19)):*
> ```YAML
>         uses: actions-rs/toolchain@v1.0.6
>         with:
>           toolchain: stable
> ```

I know it's taken from `rustfmt.yml`, but surely "Install nightly Rust" isn't correct here? :)
___
*[`.github/workflows/test-runner.yml` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOQQSQAoBAhoUw7KXA:-NlOQQSQAoBAhoUw7KXB:bqn7jhv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/test-runner.yml#L1)):*
> ```YAML
> # Compile the test runner
> ```

Nit: We build `test-manager` as well here. Maybe the jobs should also be renamed from `build-test-runner...` to build-test-framework`.
___
*[`.github/workflows/test-runner.yml` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOP3Rt8W58kab_GBt4:-NlOP3Rt8W58kab_GBt5:b-jpq0tt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/test-runner.yml#L7)):*
> ```YAML
>   pull_request:
>     paths:
>       - "test/**"
> ```

Same as above about including the workflow itself.
___
*[`.github/workflows/test-runner.yml` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOPCp07E_yG1Q64ie_:-NlOPCp07E_yG1Q64iea:bvmjk8y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/test-runner.yml#L8)):*
> ```YAML
>     paths:
>       - "test/**"
>       # Maybe we should check if changes to the app code (mullvad-management-interface) will break the test runner
> ```

That seems sensible! We use far more crates than just `mullvad-management-interface`, though. Would it be crazy to run this on the same conditions as `daemon.yml`? That does seem like the right thing to do.
___
*[`.github/workflows/test-runner.yml` line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOQi4w5B-IfHb0Q7C8:-NlOQi4x7OyFwVRQj5E_:b-5qyb4t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/test-runner.yml#L52)):*
> ```YAML
>       - name: Build test runner
>         working-directory: test
>         run: cargo build --release -p test-runner --target ${{ matrix.target }}
> ```

Maybe we could squeeze in the `test-manager` build here by adding a condition:

```
if: matrix.target != 'x86_64-pc-windows-gnu'
```

And building the `test-runner` in a step afterwards, unconditionally.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`.github/workflows/test-runner.yml` line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlOQi4w5B-IfHb0Q7C8:-NlSDNf_6RzXhDOcL7RA:b-mdcqwc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/test-runner.yml#L52)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Makes sense :blush:
</blockquote></details>

I solved this by instead splitting up the build process into three distinct jobs: `build-test-framework-linux`, `build-test-framework-macos` & `build-test-runner-windows` :blush:

**Review by dlon — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/test-framework.yml` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlSTgXq-jUpAtIp17LR:-NlSTgXq-jUpAtIp17LS:bxw6xkb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f08d095a684dbb7e26e050301fd24a567f572d5/.github/workflows/test-framework.yml#L8)):*
> ```YAML
>     paths:
>       - "test/**"
>       - .github/workflows/test-framework.yml
> ```

These two should already be included by the paths below now.
___
*[`.github/workflows/android-app.yml` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlSU0UeDGSxS-bNSUFd:-NlSU0UeDGSxS-bNSUFe:b3u68rc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/android-app.yml#L16)):*
> ```YAML
>       - '!gui/**'
>       - '!ios/**'
>       - '!test/**'
> ```

This one probably could be kept.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`.github/workflows/android-app.yml` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlSU0UeDGSxS-bNSUFd:-NlSbe3j0dA2exeKSaWB:b6zrrk4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dfd1359a9f9385543f5b2406d908566fcbe6ad70/.github/workflows/android-app.yml#L16)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This one probably could be kept.
</blockquote></details>

Good catch!
___
*[`.github/workflows/test-framework.yml` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlSTgXq-jUpAtIp17LR:-NlSawq24oqULYMbASxz:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f08d095a684dbb7e26e050301fd24a567f572d5/.github/workflows/test-framework.yml#L8)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

These two should already be included by the paths below now.
</blockquote></details>

done

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @dlon)

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-:-NlXdVCcBHfFl4Ad4Sbg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/testframework.yml` line 3 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlXdGHRAYEq0bp_eTmC:-NlXdGHRAYEq0bp_eTmD:b-gt1h6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1caa0b50c6de3147c25f47aedb9fdb3f3d19a07c/.github/workflows/testframework.yml#L3)):*
> ```YAML
> # Compile the test framework
> ---
> name: DES Testframework - Build
> ```

Nit: Should probably be two words: test framework. Also, why not "Desktop"?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`.github/workflows/testframework.yml` line 3 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575#-NlXdGHRAYEq0bp_eTmC:-NlYg5HA3Z6bSBK-6_tp:bhdofz9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1caa0b50c6de3147c25f47aedb9fdb3f3d19a07c/.github/workflows/testframework.yml#L3)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Should probably be two words: test framework. Also, why not "Desktop"?
</blockquote></details>

Makes sense. I used the Linear convention (DES), but "Desktop" is aligned better with the current naming convention of other workflows.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
