### PR TITLE
Device name and time left should be closer together on large devices

### PR DESCRIPTION
**Pull request by mojganii**
The gap between the two look good on a phone, but on eg. an iPad the gap is very wide.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577)

### CODE REVIEW

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJOoS14pxZgk2bVknA:-NTJOoS14pxZgk2bVknB:bhsrtgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L19)):*
> ```Swift
>     ///
>     /// 1. Intervals of two years or more are formatted in years quantity.
>     /// 2. Intervals between 23h 30m - 23h 59m are rounded to 1 day to fix the iOS SDK bug which
> ```

The description needs to be updated.
___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJOpy6AfRh2b2dWCEM:-NTJOpy6AfRh2b2dWCEN:b-xodlkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L48)):*
> ```Swift
>             formatter.allowedUnits = [.year]
>             return formatter.string(from: dateComponents)
>         } else if days == 0, hours == 23, minutes >= 30 {
> ```

Are we sure this condition should be removed? Double-check with Emils.
___
*[`ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJP3nu4Fj9rLlY8tWL:-NTJP3nv71-WHPK6g0Cb:bcity4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift#L46)):*
> ```Swift
>     }
> 
>     func testCloseToOneDayFormatting() throws {
> ```

As with the comment above, check with Emils if this condition should be removed.

**Comment by mojganii** [comment]
> > Reviewed 3 of 3 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577)_ status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)
> 
> _[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJOoS14pxZgk2bVknA:-NTJOoS14pxZgk2bVknB:bhsrtgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L19)):_
> 
> > ```swift
> >     ///
> >     /// 1. Intervals of two years or more are formatted in years quantity.
> >     /// 2. Intervals between 23h 30m - 23h 59m are rounded to 1 day to fix the iOS SDK bug which
> > ```
> 
> The description needs to be updated.
> 
> _[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJOpy6AfRh2b2dWCEM:-NTJOpy6AfRh2b2dWCEN:b-xodlkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L48)):_
> 
> > ```swift
> >             formatter.allowedUnits = [.year]
> >             return formatter.string(from: dateComponents)
> >         } else if days == 0, hours == 23, minutes >= 30 {
> > ```
> 
> Are we sure this condition should be removed? Double-check with Emils.
> 
> _[`ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJP3nu4Fj9rLlY8tWL:-NTJP3nv71-WHPK6g0Cb:bcity4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift#L46)):_
> 
> > ```swift
> >     }
> > 
> >     func testCloseToOneDayFormatting() throws {
> > ```
> 
> As with the comment above, check with Emils if this condition should be removed.

Emils asked me to change our time formatter

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4577#-NTJP3nu4Fj9rLlY8tWL:-NTJX5m61s1wt3uhuUTA:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/406514453a3687d1233749d50862863d4cd5d31b/ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift#L46)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Emils asked me to change our time formatter
</blockquote></details>

👍

**Pull request closed without merging**
