### PR TITLE
Retry fetching out IP DES-118

### PR DESCRIPTION
**Pull request by Serock3**
Add periodic retry for `GetCurrentLocation`.

~~I can not reproduce the original error so I haven't been able to make the new code actually run. We need to see if this fixes the problem, and decide what an appropriate retry interval and max attempts are.~~

I tested by blocking traffic to am.i.mullvad.net, and it seems to work as expected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)* status: all files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`mullvad-daemon/src/lib.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkFgpVt5ghY7Bj6ZMXT:-NkFgpVt5ghY7Bj6ZMXU:bz85efm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/645f870cedcf0ae79ec0314d5f67abbb121adce0/mullvad-daemon/src/lib.rs#L97)):*
> ```XML
> /// Retry interval for fetching location
> const RETRY_LOCATION_STRATEGY: ConstantInterval =
>     ConstantInterval::new(Duration::from_secs(2), Some(3));
> ```

The reason for setting the interval to `0` in other cases is that there's also a timeout interval on the REST requests themselves. It's a bit confusing, but that means that it's already only retrying once every few seconds, if the request fails due to a timeout/network error.

So it should be fine do so the same thing here.
___
*[`mullvad-daemon/src/lib.rs` line 1394 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkFgu-31u9CXZgWTqku:-NkFgu-31u9CXZgWTqkv:bzdklp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/645f870cedcf0ae79ec0314d5f67abbb121adce0/mullvad-daemon/src/lib.rs#L1394)):*
> ```XML
>         let use_ipv6 = self.settings.tunnel_options.generic.enable_ipv6;
>         let api_handle = self.api_handle.availability.clone();
>         retry_future(
> ```

We should avoid blocking the daemon from handling further commands here. So it would be better to spawn a new tokio task here and handle the requests there.

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-api/src/lib.rs` line 355 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkGHDPT07Bv1ZR-uifM:-NkGHDPT07Bv1ZR-uifN:bl0gmjg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57a1c4ce5535299e3ca659f69d1aa0b6f6adcfd0/mullvad-api/src/lib.rs#L355)):*
> ```XML
> 
>     /// Returns a new request service handle
>     pub async fn rest_handle(&mut self) -> rest::RequestServiceHandle {
> ```

This change is really unrelated, but I snuck it in.
___
*[`mullvad-daemon/src/lib.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkFgpVt5ghY7Bj6ZMXT:-NkFybsm2bW09LPRHs7G:b-2mcmwx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/645f870cedcf0ae79ec0314d5f67abbb121adce0/mullvad-daemon/src/lib.rs#L97)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The reason for setting the interval to `0` in other cases is that there's also a timeout interval on the REST requests themselves. It's a bit confusing, but that means that it's already only retrying once every few seconds, if the request fails due to a timeout/network error.

So it should be fine do so the same thing here.
</blockquote></details>

Alright. After some testing it feels like the REST API adds ~5 secs on its own, which should do.

This may be another argument for writing how retrys work (in addition to handling the `Reply-after` header`). The delay timer you give should be respected.
___
*[`mullvad-daemon/src/lib.rs` line 1394 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkFgu-31u9CXZgWTqku:-NkFyHaZ8jKMcb4pzDgX:b-btx1a8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/645f870cedcf0ae79ec0314d5f67abbb121adce0/mullvad-daemon/src/lib.rs#L1394)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We should avoid blocking the daemon from handling further commands here. So it would be better to spawn a new tokio task here and handle the requests there.
</blockquote></details>

I knew the nested future that I removed had some purpose! Good catch. I have made the RPC non-blocking again, but hopefully with a slightly more readable implementation. I also tested that the daemon remains responsive (through the CLI) while it is performing the retrys.

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`mullvad-daemon/src/lib.rs` line 1394 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkFgu-31u9CXZgWTqku:-NkGh8ZpAPGlcZT2n-MM:bg7igkv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/645f870cedcf0ae79ec0314d5f67abbb121adce0/mullvad-daemon/src/lib.rs#L1394)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I knew the nested future that I removed had some purpose! Good catch. I have made the RPC non-blocking again, but hopefully with a slightly more readable implementation. I also tested that the daemon remains responsive (through the CLI) while it is performing the retrys.
</blockquote></details>

:lgtm: 
___
*[`mullvad-daemon/src/lib.rs` line 1407 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkGhJKz1qxgT_QuB5Le:-NkGhJKz1qxgT_QuB5Lf:bje0qp2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c035bd5b19726e7d08d005fa74b2a2d597c81b63/mullvad-daemon/src/lib.rs#L1407)):*
> ```XML
>         log::debug!("Fetching GeoIpLocation");
>         match retry_future(
>             move || geoip::send_location_request(rest_service.clone(), use_ipv6),
> ```

I wonder if we shouldn't move the retry logic into `geoip`. Just a thought.

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/lib.rs` line 1407 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486#-NkGhJKz1qxgT_QuB5Le:-NkKGLOeEZ2aP4TH9rwM:bzicnis) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c035bd5b19726e7d08d005fa74b2a2d597c81b63/mullvad-daemon/src/lib.rs#L1407)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I wonder if we shouldn't move the retry logic into `geoip`. Just a thought.
</blockquote></details>

I agree. I moved the retry logic  to `geoip` and refactored `mullvad-daemon/lib` a bit to make it a bit more concise. The behavior should be the same, but you may have to look at it again.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
