### PR TITLE
Fix some unit tests not running after adding flavors

### PR DESCRIPTION
**Pull request by albin-mullvad**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5274)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5274)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5274#-:-NgXmeKR3fF3zTrLd9su:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5274)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5274#-:-NgY6LQU9b-67iSRp58z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
