### PR TITLE
Travis maintenance

### PR DESCRIPTION
**Pull request by eriklarko**
I broke the travis build, this PR fixes that breakage and also updates our test environment to node 8 and 9 which is the LTS and the latest versions.

This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/13)

### CODE REVIEW

**Comment by eriklarko** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 58 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-L2-nOHQMDz_usKblSFG:-L20gM7H8PfSAzLyOT5D:b-7rrmvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38ed192e809cc2490064a54690de5cd17cb67d72/.travis.yml#L58)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Does `exit 1` mean something?
</blockquote></details>

debug

---

*[app/components/styled/Button.js, line 13 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-L2-nXBuMaiUMNjDx8Xe:-L20gLO5FSnh_klgTEsV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38ed192e809cc2490064a54690de5cd17cb67d72/app/components/styled/Button.js#L13)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

~second argument~ second value in an array to `Styles.combine`, i.e:

```
ReactXP.Styles.combine([defaultStyle, style]);
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13)*

**Comment by pronebird** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 32 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-L20sAY5vNiFrFLMPCQm:-L20sAY5vNiFrFLMPCQn:bidi34q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/565319e103d8eeaa1b07fc4acd6618acc3a0f7f6/.travis.yml#L32)):*
> ```YAML
> 
>     - language: node_js
>       node_js: '9'
> ```

Our Electron 1.8 runs Node 7.9, the next Electron will run Node 8, but Node 9 is too far in future IMO. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13)*

**Comment by eriklarko** [comment]
*[.travis.yml, line 32 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-L20sAY5vNiFrFLMPCQm:-L20uA-REdoHk9k75CVG:b-yqg1sh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/565319e103d8eeaa1b07fc4acd6618acc3a0f7f6/.travis.yml#L32)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Our Electron 1.8 runs Node 7.9, the next Electron will run Node 8, but Node 9 is too far in future IMO. :)
</blockquote></details>

Alright, cool. I'll change it back to 7 and 8 then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13)*

**Comment by pronebird** [comment]
Not sure what this PR is about anymore. The `Button.js` change is valid though!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-:-L2KpdKvRktfqqIrNRZ2:b-lvooo1)*

**Comment by eriklarko** [comment]
It just removes node 6 and fixes the linting issues on master

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-:-L2L1scahH8vlga_cs9-:blxynie)*

**Comment by pronebird** [comment]
Ah yes sorry, I looked at the wrong revision :)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-:-L2L6RCjaSVuwZx2QnfH:bj75mx8)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/13#-:-L2L6WqFsQmZ9ZxmGHlD:bnfp4nl)*

**Pull request merged**
