### PR TITLE
Migrate PreferencesDataSource from traditional to diffable

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/PreferencesCellFactory.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdP5j3A3E1dAPXMd91:-NQdP5j3A3E1dAPXMd92:b-hgfkh2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesCellFactory.swift#L11)):*
> ```Swift
> import UIKit
> 
> protocol PreferencesCellFactoryDelegate: AnyObject {
> ```

Classic delegates in Objective-C often used to share their instance with the delegate that's why all methods used to start with subject, i.e: 

```swift
func <subject>(_ subject: Subject, did<Action>: Action)
```

I'd say since you don't share the cell factory with delegate, just omit that and go with plain object like this:


```swift
protocol PreferencesCellEventHandler {
   func didChangeState(for item: PreferencesDataSource.Item, isOn: Bool)
   func didChangeDNSEntry(with identifier: UUID, in cell: SettingsDNSTextCell)
   func addDNSEntry()
}
```

Also you probably don't have to share `SettingsDNSTextCell` with delegate, for example you could change it to return `Bool` and then wire up validation internally, i.e:

```swift
func didChangeDNSEntry(with identifier: UUID, inputString: String) -> Bool
```

Then somewhere in cell factory:

```swift
cell.isValidInput = delegate.didChangeDNSEntry(
      with: dnsIdentifier, 
     inputString: cell.textField.text ?? ""
)
```
___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 256 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdNr_67yK1In1HYHag:-NQdNr_79QMfeG_ofrDz:byu4f3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L256)):*
> ```Swift
> 
>     func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
>         let sectionIdentifier = snapshot().sectionIdentifiers[section]
> ```

You can use `self. sectionIdentifier(for: section)` instead
___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 520 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdOitY0Eah0a6e8Vjg:-NQdOitY0Eah0a6e8Vjh:b-oxqj6o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L520)):*
> ```Swift
>         reload(item: .useCustomDNS)
> 
>         let sectionIndex = snapshot().indexOfSection(.customDNS)!
> ```

You can use `self.index(for: .customDNS)` instead as `UITableViewDiffableDataSource` supports that. I'll share the link to documentation so it's easy to glance at what methods it implements: https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdTc1CDkGtXuZyC01w:-NQdTc1CDkGtXuZyC01x:blfr74o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L293)):*
> ```Swift
>         toProposedIndexPath proposedDestinationIndexPath: IndexPath
>     ) -> IndexPath {
>         let sectionIdentifier = snapshot().sectionIdentifiers[sourceIndexPath.section]
> ```

`self.sectionIdentifier(for: Int)`

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 234 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdTtX2AVE_cNQmZV3D:-NQdTtX2AVE_cNQmZV3E:b970ory) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L234)):*
> ```Swift
> 
>     func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
>         let sectionIdentifier = snapshot().sectionIdentifiers[section]
> ```

`self.sectionIdentifier(for: section)`

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/PreferencesViewModel.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdU6f96kpySWUys3Nh:-NQdU6f96kpySWUys3Ni:bkqzdh2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesViewModel.swift#L89)):*
> ```Swift
>     private(set) var enableCustomDNS: Bool
>     var customDNSDomains: [DNSServerEntry]
>     var isEditing = false
> ```

Is it used anywhere? Because data source has `isEditing` flag too.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/PreferencesCellFactory.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdP5j3A3E1dAPXMd91:-NQdWPYR0Fx9xEDqbkWR:b-5h19jh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesCellFactory.swift#L11)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Classic delegates in Objective-C often used to share their instance with the delegate that's why all methods used to start with subject, i.e: 

```swift
func <subject>(_ subject: Subject, did<Action>: Action)
```

I'd say since you don't share the cell factory with delegate, just omit that and go with plain object like this:


```swift
protocol PreferencesCellEventHandler {
   func didChangeState(for item: PreferencesDataSource.Item, isOn: Bool)
   func didChangeDNSEntry(with identifier: UUID, in cell: SettingsDNSTextCell)
   func addDNSEntry()
}
```

Also you probably don't have to share `SettingsDNSTextCell` with delegate, for example you could change it to return `Bool` and then wire up validation internally, i.e:

```swift
func didChangeDNSEntry(with identifier: UUID, inputString: String) -> Bool
```

Then somewhere in cell factory:

```swift
cell.isValidInput = delegate.didChangeDNSEntry(
      with: dnsIdentifier, 
     inputString: cell.textField.text ?? ""
)
```
</blockquote></details>

I see! Well, agreed, will make changes.
___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 234 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdTtX2AVE_cNQmZV3D:-NQdVgQ5E4rdvTbR456X:b-pwav19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L234)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`self.sectionIdentifier(for: section)`
</blockquote></details>

Although diffable data source is available since iOS 13, this function isn't available before iOS 15.
___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 256 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdNr_67yK1In1HYHag:-NQdVyoP7OB_D-XiN6Nv:b4jnodh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L256)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You can use `self. sectionIdentifier(for: section)` instead
</blockquote></details>

Only iOS 15 and later.
___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdTc1CDkGtXuZyC01w:-NQdW0LY64t05dmF393u:b4jnodh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L293)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`self.sectionIdentifier(for: Int)`
</blockquote></details>

Only iOS 15 and later.
___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 520 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdOitY0Eah0a6e8Vjg:-NQdW2Za1myXTT1WzYW8:b-sszjg2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L520)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You can use `self.index(for: .customDNS)` instead as `UITableViewDiffableDataSource` supports that. I'll share the link to documentation so it's easy to glance at what methods it implements: https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource
</blockquote></details>

Same as with self.sectionIdentifier(for: Int), this is only available in iOS 15 and later.
___
*[`ios/MullvadVPN/PreferencesViewModel.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdU6f96kpySWUys3Nh:-NQdWDWm4ngxR_52Mf9g:b-nbzvan) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesViewModel.swift#L89)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Is it used anywhere? Because data source has `isEditing` flag too.
</blockquote></details>

No, this is a leftover from when I was testing something. Will remove it.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-:-NQiTkhd-jW1Smk68sJ-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 234 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446#-NQdTtX2AVE_cNQmZV3D:-NQiTYmi1axiuphnHN2D:b-yy0a1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f8423d89331b44ab254a0aedba01b0bb5da6ee38/ios/MullvadVPN/PreferencesDataSource.swift#L234)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Although diffable data source is available since iOS 13, this function isn't available before iOS 15.
</blockquote></details>

Oh boy. I see. Alright then.

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
