### PR TITLE
Add toggle to enable smart routing

### PR DESCRIPTION
**Pull request by rablador**
A toggle to disable smart routing should be placed below the DAITA toggle. The toggle should be named Direct only.  It should also have a footer explaining how, by default, enabling DAITA overrides multihop and an info icon that leads to an explanation for how smart routing works. When Direct only is toggled, the relay selector must honor user location constraints, allowing the user to end up in the blocked state. When turning on Direct only, if the user will end up in the blocked state, the user should be shown a pop-up explaining so - as it should already be working when toggling DAITA.

When DAITA is turned off, the Direct only toggle state shouldn't be affected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
Note: Waiting for a text in the "Direct only" info dialog.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-:-O8gS0fD5WfcED4jZsf9:b-ranrqo)* status: 0 of 21 files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-:-O8qes8R0D6nmdfEDDaB:b-896fix)* status: 0 of 23 files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919)* status: 19 of 23 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInfoButtonItem.swift` line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-O8udyuABWe6YnxVBwAL:-O8vA8-p6famlp3K2ptM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d560cf56f2c414223115b70a65fdf2dd5dd1ce3/ios/MullvadVPN/View%20controllers/Settings/SettingsInfoButtonItem.swift#L22)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should use the british english spelling of "Defence"
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInfoButtonItem.swift` line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-O8ueDxg70INXShsP-yU:-O8vA8WF3pBVW3DOxEwS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d560cf56f2c414223115b70a65fdf2dd5dd1ce3/ios/MullvadVPN/View%20controllers/Settings/SettingsInfoButtonItem.swift#L29)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That last line is irrelevant on iOS, we only support WireGuard, we should remove it.
</blockquote></details>

Done.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919)* status: 19 of 23 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInteractor.swift` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-O8ulQwA6JpV6_ZPQkbM:-O8vFOfV1joZr2tvKLCM:b-4jwv5a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d560cf56f2c414223115b70a65fdf2dd5dd1ce3/ios/MullvadVPN/View%20controllers/Settings/SettingsInteractor.swift#L55)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure how I feel about this false dichotomy where the exit can be nil, since `selectRelay` _cannot_ return a nil exit. 

What do you think about this ? 
```swift

        guard let selectedRelays = try? tunnelManager.selectRelays(tunnelSettings: tunnelSettings) else {
            return multihopEnabled ? .multihop : .singlehop
        }

        /// `selectRelays` *cannot* return a `nil` exit, therefore, either the entry is `nil`, or there is no error.
        return selectedRelays.entry == nil ? .multihop : nil
```
</blockquote></details>

You're right, but we don't even need look at entry. Either `selectedRelays` is nil or it's correct.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift` line 105 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-O8undBm1S4UXtMryCDc:-O8vAARh4xK2IGPIS-85:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d560cf56f2c414223115b70a65fdf2dd5dd1ce3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInfoButtonItem.swift#L105)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please revert this
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-:-O8vRjKF09dfU9HGB-ih:bnfp4nl)* status: 21 of 23 files reviewed, 1 unresolved discussion

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6919#-:-O8v_ZlyBSRcHyIcVY34:bnfp4nl)* status: 22 of 23 files reviewed, all discussions resolved

**Pull request merged**
