### PR TITLE
Make Account a functional component

### PR DESCRIPTION
**Pull request by hankolsen**
This PR makes Account a functional component

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026)* status: all files reviewed, 1 unresolved discussion (waiting on @hankolsen)

___
*[`gui/src/renderer/components/Account.tsx` line 240 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NE9zHeM-LllzCcZq6qI:-NE9zHeM-LllzCcZq6qJ:bu1khun) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/431f726b59abb17a6629f117a0dab8045c33f276/gui/src/renderer/components/Account.tsx#L240)):*
> ```XML
> 
>   const [logoutDialogStage, setLogoutDialogStage] = useState<LogoutDialogStage>();
>   const [logoutDialogVisible, setLogoutDialogVisible] = useState(false);
> ```

There's a custom hook in `/gui/src/renderer/lib/utilityHooks.ts` called `useBoolean` which wraps `useState` but instead of the setter it returns three methods. One that sets it to true, one that sets it to false and one that toggles it. I guess we don't need the last one here though. It could be used like this:
```
const [dialogVisible, showDialog, hideDialog] = useBoolean(false);
```

Also, now that this logic is isolated to a context specific to the logout process, it wouldn't hurt to shorten the names a bit and remove `logout` from them. Although `onTry` might not be expressive enough :slightly_smiling_face: 
___
*[`gui/src/renderer/components/Account.tsx` line 250 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NE7FZzR-yB5-mXPuLW5:-NE7FZzR-yB5-mXPuLW6:b-gdi04m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/431f726b59abb17a6629f117a0dab8045c33f276/gui/src/renderer/components/Account.tsx#L250)):*
> ```XML
>     setLogoutDialogVisible(true);
>     setLogoutDialogStage('checking-ports');
>     prepareLogout();
> ```

I don't know if `react-redux` promises that `dispatch`, which is used in `useActions`, never changes. If we can't be sure about this then we should add it to the dependency array.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/Account.tsx` line 250 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NE7FZzR-yB5-mXPuLW5:-NEADach2uJlPgIMFgMW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/431f726b59abb17a6629f117a0dab8045c33f276/gui/src/renderer/components/Account.tsx#L250)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't know if `react-redux` promises that `dispatch`, which is used in `useActions`, never changes. If we can't be sure about this then we should add it to the dependency array.
</blockquote></details>

Done.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026)* status: all files reviewed, 2 unresolved discussions (waiting on @hankolsen)

___
*[`-- commits` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NEAFsBK6dQ76xZsl6ox):*
Could you rebase and squash/fixup the fixes with the commits that introduced the code that needed fixing. We have some guidelines here: https://github.com/mullvad/coding-guidelines/#history
___
*[`gui/src/renderer/components/Account.tsx` line 231 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NEAFZDY34HHFGLSMS9P:-NEAFZDY34HHFGLSMS9Q:b-s1ongp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220e2ab3ad5f15ebb4f92dfce9880bea9860c0f6/gui/src/renderer/components/Account.tsx#L231)):*
> ```XML
> 
> const LogoutContextProvider = ({ children }: { children: ReactNode }) => {
>   const onHideLogoutConfirmationDialog = () => hideDialog();
> ```

This function definition is pretty redundant now and can be removed and its uses be replaced with `hideDialog` :slightly_smiling_face:

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`-- commits` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NEAFsBK6dQ76xZsl6ox):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Could you rebase and squash/fixup the fixes with the commits that introduced the code that needed fixing. We have some guidelines here: https://github.com/mullvad/coding-guidelines/#history
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/Account.tsx` line 231 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NEAFZDY34HHFGLSMS9P:-NEAwMoL2q4JsxCDKKdG:b-n74vmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220e2ab3ad5f15ebb4f92dfce9880bea9860c0f6/gui/src/renderer/components/Account.tsx#L231)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This function definition is pretty redundant now and can be removed and its uses be replaced with `hideDialog` :slightly_smiling_face: 
</blockquote></details>

Haha, true!

**Review by raksooo — APPROVED** [review]
Great work :lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-:-NEG8gwl764wydYNvM3W:bgsrtlp)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4026#-NEAFsBK6dQ76xZsl6ox):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks great! :+1:

**Pull request merged**
