### PR TITLE
Refactor backend error types

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Internal refactor, not user visible.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/lib/backend.js, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyh9_j5a3UHRlFB8X-:-LEyh9_j5a3UHRlFB8X0:bg67ttw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6040481a2f95ed21128d36603e16d99482bb8b87/app/lib/backend.js#L215)):*
> ```JavaScript
>       }
>     } else if (e instanceof TimeOutError) {
>       return new CommunicationError('api.mullvad.net');
> ```

Since we don't really have any other communication errors right now,  I think we could skip passing `api.mullvad.net`, esp. given that it's hardcoded in javascript.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Reviewed 4 of 6 files at r1.
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/lib/backend.js, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyh9_j5a3UHRlFB8X-:-LEyiVsY-3bNy1ZCmyut:bvhgd0a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6040481a2f95ed21128d36603e16d99482bb8b87/app/lib/backend.js#L215)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Since we don't really have any other communication errors right now,  I think we could skip passing `api.mullvad.net`, esp. given that it's hardcoded in javascript.
</blockquote></details>

I mean we can just have `CommunicationError` without any arguments that would always tell that we have issues with api.mullvad.net

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @pronebird, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/lib/backend.js, line 208 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyl_sMBKiWm_wV3SBh:-LEyl_sMBKiWm_wV3SBi:b-cx6vo8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/698c6a54b34e309a220d82bb9fd76c83f774a690/app/lib/backend.js#L208)):*
> ```JavaScript
>           return new InvalidAccountError();
>         case -32603: // Internal error
>           // We treat all internal backend errors as the user cannot reach
> ```

Maybe we should start reporting the internal errors?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by jvff** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/lib/backend.js, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyh9_j5a3UHRlFB8X-:-LEzHi5-BK6Doda5huEZ:b-qejhjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6040481a2f95ed21128d36603e16d99482bb8b87/app/lib/backend.js#L215)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I mean we can just have `CommunicationError` without any arguments that would always tell that we have issues with api.mullvad.net
</blockquote></details>

Done. I also saw I wasn't setting the `_hostname` field :/

---

*[app/lib/backend.js, line 208 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyl_sMBKiWm_wV3SBh:-LEzHjYgE7eSZmwckHCw:b-5b5adr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/698c6a54b34e309a220d82bb9fd76c83f774a690/app/lib/backend.js#L208)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Maybe we should start reporting the internal errors?
</blockquote></details>

I think so. But I need to figure out what internal errors occur and how they are sent back. The original authentication failure PR used a separate channel, but it wouldn't work in this case. Maybe this should be done in a separate PR?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by faern** [comment]
Review status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/app.js, line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LF-CUOfD_45D8KMksuz:-LF-CUOfD_45D8KMksv-:b53migj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e341065d533f08056126f78d93177c5c8d5a390/app/app.js#L37)):*
> ```JavaScript
>   } catch (e) {
>     if (e instanceof NoAccountError) {
>       log.debug('No user set in the backend, showing window');
> ```

I was not assigned in this PR. But just happened to stumble on the diff. I see this message is not changed in this PR, but we should be consistent in calling it the "account" (or even "account number") and never the "user". Could we get that fixed at the same time? Or is that something that exists in many places and thus deserve its own PR?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/lib/backend.js, line 208 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyl_sMBKiWm_wV3SBh:-LF1yAsw7QVx4eqdFV06:b99jfqg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/698c6a54b34e309a220d82bb9fd76c83f774a690/app/lib/backend.js#L208)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think so. But I need to figure out what internal errors occur and how they are sent back. The original authentication failure PR used a separate channel, but it wouldn't work in this case. Maybe this should be done in a separate PR?
</blockquote></details>

Hmmm ok, i have no idea either. But we had some issues when we reported invalid errors back and that seems to be the case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/lib/backend.js, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyh9_j5a3UHRlFB8X-:-LF1yONOCF4-2uGRfJID:b-q3elko) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6040481a2f95ed21128d36603e16d99482bb8b87/app/lib/backend.js#L215)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. I also saw I wasn't setting the `_hostname` field :/
</blockquote></details>

OK. Well, I gave you example with hostname initially to show you that we can include meaningful info along with errors. 

Anyway, that's not necessary here. I realize that flexibility where it's not needed does more harm than helps.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @pronebird, and @jvff)

---

*[app/app.js, line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LF-CUOfD_45D8KMksuz:-LF1z_UGBe4Ss-T0qiXx:b-4lx9qy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e341065d533f08056126f78d93177c5c8d5a390/app/app.js#L37)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I was not assigned in this PR. But just happened to stumble on the diff. I see this message is not changed in this PR, but we should be consistent in calling it the "account" (or even "account number") and never the "user". Could we get that fixed at the same time? Or is that something that exists in many places and thus deserve its own PR?
</blockquote></details>

Probably in many places but we can fix the occurrence you spotted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, @faern, and @jvff)

---

*[app/lib/backend.js, line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LF1zf0yErL7wX3s5ZIi:-LF1zf0yErL7wX3s5ZIj:b-5lzu0n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e341065d533f08056126f78d93177c5c8d5a390/app/lib/backend.js#L69)):*
> ```JavaScript
>   }
> 
>   get hostname(): string {
> ```

Well since we don't use the `hostname` anywhere, you can entirely remove it from `CommunicationError`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @pronebird, @faern, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by jvff** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @pronebird, @pinkisemils, and @faern)

---

*[app/app.js, line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LF-CUOfD_45D8KMksuz:-LF2GfQ62hRhBud2DuIa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e341065d533f08056126f78d93177c5c8d5a390/app/app.js#L37)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Probably in many places but we can fix the occurrence you spotted.
</blockquote></details>

Done.

---

*[app/lib/backend.js, line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyh9_j5a3UHRlFB8X-:-LF2GUnt4ryis2P9CnCB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6040481a2f95ed21128d36603e16d99482bb8b87/app/lib/backend.js#L215)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

OK. Well, I gave you example with hostname initially to show you that we can include meaningful info along with errors. 

Anyway, that's not necessary here. I realize that flexibility where it's not needed does more harm than helps.
</blockquote></details>

Done.

---

*[app/lib/backend.js, line 208 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyl_sMBKiWm_wV3SBh:-LF2GWfv4ATKu_xCoBIa:bg7glqc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/698c6a54b34e309a220d82bb9fd76c83f774a690/app/lib/backend.js#L208)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Hmmm ok, i have no idea either. But we had some issues when we reported invalid errors back and that seems to be the case.
</blockquote></details>

Understood. I can tackle that issue next.

---

*[app/lib/backend.js, line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LF1zf0yErL7wX3s5ZIi:-LF2GQ8rA0BZI7LbBm-q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e341065d533f08056126f78d93177c5c8d5a390/app/lib/backend.js#L69)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Well since we don't use the `hostname` anywhere, you can entirely remove it from `CommunicationError`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @pronebird, @pinkisemils, and @faern)

---

*[app/app.js, line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LF-CUOfD_45D8KMksuz:-LF2fPNN8rdLoSaMpU7S:b-mjsibv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e341065d533f08056126f78d93177c5c8d5a390/app/app.js#L37)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am really looking forward merging this and even if this wording is not sufficient enough we can refine it at any time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
Review status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @pronebird, @pinkisemils, and @faern)

---

*[app/lib/backend.js, line 208 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-LEyl_sMBKiWm_wV3SBh:-LF2fj_35WhSZupQdZfM:b-luz2sl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/698c6a54b34e309a220d82bb9fd76c83f774a690/app/lib/backend.js#L208)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Understood. I can tackle that issue next.
</blockquote></details>

I mark it satisfied and you can solve in the follow up PR if you wish. Probably needs some actual testing to simulate internal error. :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)*

**Comment by pronebird** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @pronebird, and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217#-:-LF2g-ZX2IkY1hwB7x3h:bnfp4nl)*

**Pull request merged**
