### PR TITLE
Migrate tests to JUnit5

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 16 of 21 files at r1, 15 of 67 files at r2, 62 of 67 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601)* status: 78 of 83 files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt` line 38 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncbnM4-87jza__jNIr:-NncbnM4-87jza__jNIs:b-xfo6uy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11e85709cab1b54f7cab9c9a516bfa90b50bca80/android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt#L38)):*
> ```Kotlin
>             Relay(name = "se9-wireguard", location = mockk(), locationName = "mock", active = false)
> 
>         Assertions.assertTrue(RelayNameComparator.compare(relay9a, relay9b) == 0)
> ```

nit: would be nice to skip. applies to the rest of this file as well.



_Code quote:_
```Kotlin
Assertions.
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 82 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncdK3-0_T4DTMCxp87:-NncdK3-0_T4DTMCxp88:b-iafl16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11e85709cab1b54f7cab9c9a516bfa90b50bca80/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L82)):*
> ```Kotlin
> 
>             // Assert
>             Assertions.assertEquals(
> ```

nit: skip?



_Code quote:_
```Kotlin
Assertions.
```
___
*[`android/test/arch/src/test/resources/junit-platform.properties` line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-Nnc7iAP0OStKsaOF3mw:-Nnc7iAP0OStKsaOF3mx:bidj86z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ff341e63ac5af0a0b080e50a684167d5002022d/android/test/arch/src/test/resources/junit-platform.properties#L4)):*
> ```INI
> junit.jupiter.execution.parallel.mode.default=concurrent
> junit.jupiter.execution.parallel.config.strategy=dynamic
> junit.jupiter.execution.parallel.config.dynamic.factor=0.95
> ```

What's the default values and is there a reason we use these specific values? Specifically the dynamic factor `0.95`. A link or comment would be nice.



_Code quote:_
```INI
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.config.strategy=dynamic
junit.jupiter.execution.parallel.config.dynamic.factor=0.95
```
___
*[`android/test/e2e/build.gradle.kts` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-Nncaob30eRFuMDMvORU:-Nncaob30eRFuMDMvORV:b-yfs89e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11e85709cab1b54f7cab9c9a516bfa90b50bca80/android/test/e2e/build.gradle.kts#L105)):*
> ```Kotlin
>     implementation(Dependencies.junitApi)
>     implementation(Dependencies.junitAndroidTestCore)
>     implementation(Dependencies.junitAndroidTestRunner)
> ```

Move these above `implementation(Dependencies.Kotlin.stdlib)` to keep the order alphabetical



_Code quote:_
```Kotlin
    implementation(Dependencies.junitAndroidTestExtensions)
    implementation(Dependencies.junitApi)
    implementation(Dependencies.junitAndroidTestCore)
    implementation(Dependencies.junitAndroidTestRunner)
```
___
*[`android/test/mockapi/build.gradle.kts` line 81 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncbKef7WSU3fnqfbtS:-NncbKef7WSU3fnqfbtT:b-tpeu5m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11e85709cab1b54f7cab9c9a516bfa90b50bca80/android/test/mockapi/build.gradle.kts#L81)):*
> ```Kotlin
>     implementation(Dependencies.junitApi)
>     implementation(Dependencies.junitAndroidTestCore)
>     implementation(Dependencies.junitAndroidTestRunner)
> ```

Move these to keep the order alphabetical



_Code quote:_
```Kotlin
    implementation(Dependencies.junitAndroidTestExtensions)
    implementation(Dependencies.junitApi)
    implementation(Dependencies.junitAndroidTestCore)
    implementation(Dependencies.junitAndroidTestRunner)
```
___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LogoutMockApiTest.kt` line 35 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncbR9FEe9HivFsAlWB:-NncbR9FEe9HivFsAlWC:brpgz9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11e85709cab1b54f7cab9c9a516bfa90b50bca80/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LogoutMockApiTest.kt#L35)):*
> ```Kotlin
> 
>         // Assert
>         Assertions.assertNotNull(device.findObjectWithTimeout(By.text("Login")))
> ```

nit: would be nice to skip this



_Code quote:_
```Kotlin
Assertions.
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601)* status: all files reviewed, 6 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncoRex2mfhMTjBYT85):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is the goal to merge these commits as-is or to cleanup/squash something?
</blockquote></details>

Yeah goal is to cleanup
___
*[`-- commits` line 11 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncoDWy99RqJUUf1BSw):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be clarified? Which tests?
</blockquote></details>

See above, goal is to cleanup commits when everything else have been solved.
___
*[`-- commits` line 13 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-Nncobip25WiU_bxmQWo):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I assume this is referring to `mockapi` and `e2e`? In that case it should be clarified by the commit message
</blockquote></details>

See above, goal is to cleanup commits when everything else have been solved.
___
*[`-- commits` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncosImBAyHpHs4xc24):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

"again"?
</blockquote></details>

See above, goal is to cleanup commits when everything else have been solved.
___
*[`android/buildSrc/src/main/kotlin/Dependencies.kt` line 68 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncnbKy-MY9aaGL2Jf8:-Nnhcanx-dhkmDKAXL0D:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9110c8592eca7f2ab1f79f01e43f4f445be95fe/android/buildSrc/src/main/kotlin/Dependencies.kt#L68)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: order alphabetically
</blockquote></details>

Done
___
*[`android/buildSrc/src/main/kotlin/Dependencies.kt` line 137 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncnYmE885vzKQHh5HL:-Nnhcbm31aV52E5eJ7Mn:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9110c8592eca7f2ab1f79f01e43f4f445be95fe/android/buildSrc/src/main/kotlin/Dependencies.kt#L137)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: order alphabetically
</blockquote></details>

Done
___
*[`android/buildSrc/src/main/kotlin/Versions.kt` line 21 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-Nncnkkq8CeXeJVv_V4s:-Nnhcr6e6LCdvRajjhf4:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9110c8592eca7f2ab1f79f01e43f4f445be95fe/android/buildSrc/src/main/kotlin/Versions.kt#L21)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: order alphabetically
</blockquote></details>

Done
___
*[`android/buildSrc/src/main/kotlin/Versions.kt` line 60 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncnkJe1Ziqvi3dNllK:-Nnhcrg75aPYMgkyaJ3J:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9110c8592eca7f2ab1f79f01e43f4f445be95fe/android/buildSrc/src/main/kotlin/Versions.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: order alphabetically
</blockquote></details>

Done
___
*[`android/lib/billing/build.gradle.kts` line 4 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NnckipBBjFtyfs0NwoX:-Nnhdi4f63VxdobPzytV:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9110c8592eca7f2ab1f79f01e43f4f445be95fe/android/lib/billing/build.gradle.kts#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Move up to keep alphabetical sorting
</blockquote></details>

Done
___
*[`android/lib/billing/build.gradle.kts` line 64 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-NncnsPV71kbQMUXYU3v:-NnhdijYAf1r4VTnkNgP:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9110c8592eca7f2ab1f79f01e43f4f445be95fe/android/lib/billing/build.gradle.kts#L64)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest moving this one above the `testImplementation` calls
</blockquote></details>

Done
___
*[`android/test/arch/src/test/resources/junit-platform.properties` line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-Nnc7iAP0OStKsaOF3mw:-NnhZab-8eg7HGAPlZeW:b-gapuuj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ff341e63ac5af0a0b080e50a684167d5002022d/android/test/arch/src/test/resources/junit-platform.properties#L4)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It was recommended by konsist, I will add a link.
</blockquote></details>

https://docs.konsist.lemonappdev.com/advanced/additional-junit5-setup
I added it as a comment in the file as well.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 70 files at r8, 67 of 67 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601)* status: all files reviewed, 4 unresolved discussions

___
*[`android/test/arch/src/test/resources/junit-platform.properties` line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-Nnc7iAP0OStKsaOF3mw:-Nnmh6bjE07O3wHRh98-:b-dl13u1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ff341e63ac5af0a0b080e50a684167d5002022d/android/test/arch/src/test/resources/junit-platform.properties#L4)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

https://docs.konsist.lemonappdev.com/advanced/additional-junit5-setup
I added it as a comment in the file as well.
</blockquote></details>

Nice! :thumbsup:

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601#-:-Nno6dR24M_cR1iTdFvj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 31 of 31 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5601)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
