### PR TITLE
Remove superfluous async functions

### PR DESCRIPTION
**Pull request by pinkisemils**
New clippy dropped sometime last month, this is the aftermath. Mostly reverting needlessly async functions back to being synchronous.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058#-:-NcwY3yX9ihbUal7uRrD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by pinkisemils** [comment]
Added more clippy fixes still.

**Review by dlon — APPROVED** [review]
> Reviewed 12 of 14 files at r3, 3 of 3 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/tunnel/mod.rs` line 125 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058#-Nd05ZcKAsfPCywU8tv8:-Nd05ZcL3t9G1hhnC9Oa:b3eph2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d460dc12b9750c183797556dd122b850d68d2cf/talpid-core/src/tunnel/mod.rs#L125)):*
> ```XML
>     fn start_wireguard_tunnel<L>(
>         #[cfg(not(any(target_os = "linux", target_os = "windows")))]
>         params: &wireguard_types::TunnelParameters,
> ```

Isn't this a bit over the top? I'd prefer a parameter being mutable in general even if it's only actually mutated on two platforms.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/tunnel/mod.rs` line 125 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058#-Nd05ZcKAsfPCywU8tv8:-Nd5ezfP6Ey4Q7vdlz66:b1v9pmr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d460dc12b9750c183797556dd122b850d68d2cf/talpid-core/src/tunnel/mod.rs#L125)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Isn't this a bit over the top? I'd prefer a parameter being mutable in general even if it's only actually mutated on two platforms.
</blockquote></details>

It's either this, or a `[cfg_attr()]` to disable the lint on some platforms, which I find to be strictly worse.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
