### PR TITLE
Fix flaky wireguard key rotation test

### PR DESCRIPTION
**Pull request by Serock3**
Fixes DES-774.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`test/test-manager/src/tests/account.rs` line 298 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-Nv14YiI7hVroK7iy5nN:-Nv14YiI7hVroK7iy5nO:b2nom5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d0f5e8f3686a2975e6635021d65dec363883477/test/test-manager/src/tests/account.rs#L298)):*
> ```XML
>         .expect("Could not stop system service");
> 
>     log::info!("Mutating device.json change created field to more than 7 days ago");
> ```

This log message is a bit weird, maybe shorten it a bit?
```rust
log::info!("Changing created field of `device.json` to more than 7 days ago");
```



_Code quote:_
```XML
log::info!("Mutating device.json change created field to more than 7 days ago");
```
___
*[`test/test-manager/src/tests/account.rs` line 318 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-Nv15jraCkOZRPxDn-Rv:-Nv15jraCkOZRPxDn-Rw:b-18lrr1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1667b62ed0d8f8a2c1d2deff937ad9d75b4bc381/test/test-manager/src/tests/account.rs#L318)):*
> ```XML
> 
>     // Check if the key rotation has already occurred when connected to the daemon, otherwise
>     // listen for device daemon events until we se the change. We have to register the event
> ```

we see the change*

_or_

we observe the change*



_Code quote:_
```XML
we se the change
```
___
*[`test/test-manager/src/tests/account.rs` line 331 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-Nv15tK25s8BH6bgD5nU:-Nv15tK25s8BH6bgD5nV:b-y0s2e2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1667b62ed0d8f8a2c1d2deff937ad9d75b4bc381/test/test-manager/src/tests/account.rs#L331)):*
> ```XML
> 
>     // Current key not yet updated
>     if new_key == old_key {
> ```

Should this comment be somewhere else?:)



_Code quote:_
```XML
    // Current key not yet updated
    if new_key == old_key {
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090)* status: 21 of 22 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/account.rs` line 318 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-Nv15jraCkOZRPxDn-Rv:-Nv17o9W0rGtbU-3_JWM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1667b62ed0d8f8a2c1d2deff937ad9d75b4bc381/test/test-manager/src/tests/account.rs#L318)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

we see the change*

_or_

we observe the change*
</blockquote></details>

Done.
___
*[`test/test-manager/src/tests/account.rs` line 331 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-Nv15tK25s8BH6bgD5nU:-Nv17odR3i-pxgPJPXPo:blipx3z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1667b62ed0d8f8a2c1d2deff937ad9d75b4bc381/test/test-manager/src/tests/account.rs#L331)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should this comment be somewhere else?:)
</blockquote></details>

Done. Rephrased the comment.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-:-Nv19ltA885M_rKzPVRR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/test-manager/src/tests/account.rs` line 332 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-Nv1f7cp9UHWACHFRztK:-Nv1f7cp9UHWACHFRztL:bilgn9f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82518bd5fd683e429740e4f32a91f40c370dc2a7/test/test-manager/src/tests/account.rs#L332)):*
> ```XML
>     if new_key == old_key {
>         log::info!("Listening for device daemon event");
>         // Verify rotation has happened within a minute
> ```

100 != a minute

**Comment by dlon** [comment]
I suspect that this problem is *actually* caused by API overrides not being cleaned up. As with the API access method tests.

**Review by dlon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090#-:-NvBpNPc5SBeVQZj6R-B:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Pull request merged**
