### PR TITLE
Add scroll to privacy disclaimer screen

### PR DESCRIPTION
**Pull request by sabercodic**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-Nha2Fhm7wreQzzy5t14:-Nha2Fhn1KPKodSCNufp:b-vrthga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32b41e23145d6175bc9a795cfe90cdcab32c83d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L69)):*
> ```Kotlin
>             Column(
>                 modifier =
>                     Modifier.padding(bottom = Dimens.privacyPolicyBottomPadding)
> ```

Instead of adding a new weird margin we can a constraint instead.

`bottom.linkTo(actionButtons.top, margin = sideMargin)`

And fix the height

`height \= Dimension.fillToConstraints`

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-:-Nhad5Xw1ciKXp0XsA7k:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-NhacnlQ5dmTBBE663we:-NhacnlQ5dmTBBE663wf:b-97bbhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32b41e23145d6175bc9a795cfe90cdcab32c83d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L70)):*
> ```Kotlin
>                 modifier =
>                     Modifier.padding(bottom = Dimens.privacyPolicyBottomPadding)
>                         .verticalScroll(rememberScrollState())
> ```

We should also add the `drawVerticalScrollbar()`

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-Nha2Fhm7wreQzzy5t14:-NhgQFvADXGvbHTZkw8z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32b41e23145d6175bc9a795cfe90cdcab32c83d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L69)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Instead of adding a new weird margin we can a constraint instead.

`bottom.linkTo(actionButtons.top, margin = sideMargin)`

And fix the height

`height \= Dimension.fillToConstraints`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-NhacnlQ5dmTBBE663we:-NhjzsUL8fhsHOYTo1_W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32b41e23145d6175bc9a795cfe90cdcab32c83d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L70)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should also add the `drawVerticalScrollbar()`
</blockquote></details>

Done.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-NhacnlQ5dmTBBE663we:-NhkFnt54chhisSJNvpq:bij4xnt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32b41e23145d6175bc9a795cfe90cdcab32c83d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L70)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Current implementation does not show the scroll bar since `drawVerticalScrollbar` needs to be before `verticalScroll`.
Also if you do manage to get the scrollbar to show it is shown in the wrong place since the margins are applied at the wrong place.

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-NhacnlQ5dmTBBE663we:-NhkUHa27XWSHHl5WxDr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32b41e23145d6175bc9a795cfe90cdcab32c83d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L70)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Current implementation does not show the scroll bar since `drawVerticalScrollbar` needs to be before `verticalScroll`.
Also if you do manage to get the scrollbar to show it is shown in the wrong place since the margins are applied at the wrong place.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355#-:-NhlZit02YO5vCjuq9rP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
