### PR TITLE
Improve daemon connection error handling

### PR DESCRIPTION
**Pull request by raksooo**
This PR prevent disconnecting from daemon on exit when not connected, and also catch connection error instead of letting it propagate.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)* status: 0 of 1 files reviewed, all discussions resolved

___
*[gui/src/main/index.ts, line 701 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104#-MoY6UJ6AebeZjRunstX:-MoY6UJ6AebeZjRunstY:b-8c2ff0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf31633a970ec413c5dff1ba94875e668a3120/gui/src/main/index.ts#L701)):*
> ```XML
>   }
> 
>   private recoverFromBootstrapError(_error?: Error) {
> ```

FYI just noticed this method that used to attempt the reconnect to the daemon but it does nothing anymore, so seems really odd that it's still around. Maybe it should be renamed or inlined.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 698 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104#-MoY79x-6rSZFWFGMjxj:-MoY79x-6rSZFWFGMjxk:b-vd6xxp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf31633a970ec413c5dff1ba94875e668a3120/gui/src/main/index.ts#L698)):*
> ```XML
>     void this.daemonRpc
>       .connect()
>       .catch((error) => log.error(`Unable to connect to daemon: ${error.message}`));
> ```

Quick question, do we send the `onDaemonDisconnected` with error when we fail to connect to daemon or does it simply throw an error right away?

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 698 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104#-MoY79x-6rSZFWFGMjxj:-MohGBBlE89-SS1u1J4M:bm6j6e5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf31633a970ec413c5dff1ba94875e668a3120/gui/src/main/index.ts#L698)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Quick question, do we send the `onDaemonDisconnected` with error when we fail to connect to daemon or does it simply throw an error right away?
</blockquote></details>

I can't say for sure since errors can be thrown in different parts of the connect process. But from what I've seen both this `catch` and `onDaemonDisconnected` will be called.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 701 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104#-MoY6UJ6AebeZjRunstX:-MohJkKt9S9cSWkPrw-a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf31633a970ec413c5dff1ba94875e668a3120/gui/src/main/index.ts#L701)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI just noticed this method that used to attempt the reconnect to the daemon but it does nothing anymore, so seems really odd that it's still around. Maybe it should be renamed or inlined.
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
