### PR TITLE
Implement UDP-over-TCP e2e test

### PR DESCRIPTION
**Pull request by niklasberglund**
Implementation of UDP-over-TCP test and firewall client. The test itself is quite verbose without POP.

Fixes: DROID-1552, DROID-1563

Related issues with improvements:
 * https://linear.app/mullvad/issue/DROID-1595
 * https://linear.app/mullvad/issue/DROID-1423

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-:-OChitKp3ryl34wMCQ52:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ObfuscationModeCell.kt` line 61 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OChu1z11vq2WxuvvqsO:-OChu1z11vq2WxuvvqsP:b-zi6cbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74a0aabb2093545d1b4edcbca47ff54d383d5c59/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ObfuscationModeCell.kt#L61)):*
> ```Kotlin
>     onSelected: (ObfuscationMode) -> Unit,
>     onNavigate: () -> Unit = {},
>     testTag: String = "",
> ```

No empty test tag, maybe optional?
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/ForgetAllVpnAppsInSettingsTestRule.kt` line 65 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm2YR-5oriOSwyfkRO:-OCm2YR-5oriOSwyfkRP:b-o1xlws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/ForgetAllVpnAppsInSettingsTestRule.kt#L65)):*
> ```Kotlin
> 
>         private const val FORGET_VPN_VPN_BUTTON_TEXT = "Forget VPN"
>         private const val FORGET_VPN_BUTTON_TEXT = "Forget"
> ```

Add comment what device and android verison that has this button. Now when it is starting to become a bigger list of combinations it would be nice to just add a comment so we can later rework this if there is a better way.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/ClearFirewallRules.kt` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm5XW_6JWk5PdOTuMb:-OCm5XW_6JWk5PdOTuMc:bn173sy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/ClearFirewallRules.kt#L15)):*
> ```Kotlin
>         override fun beforeTestExecution(context: ExtensionContext?) {
>             runBlocking {
>                 val firewallClient = FirewallClient()
> ```

Why do we recreate the client each time?

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm7KM-2IKip_LAFoO8:-OCm7KM-2IKip_LAFoO9:bwxt5wj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L53)):*
> ```Kotlin
>     @OptIn(ExperimentalSerializationApi::class)
>     @Serializable
>     data class FirewallRule
> ```

Is this some specific kind of firewall rule? Drop?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 10 of 15 files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ObfuscationModeCell.kt` line 61 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OChu1z11vq2WxuvvqsO:-OCn5gWu6QNywb_tVSA9:b-p4zsvy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74a0aabb2093545d1b4edcbca47ff54d383d5c59/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ObfuscationModeCell.kt#L61)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

No empty test tag, maybe optional?
</blockquote></details>

See change
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/ForgetAllVpnAppsInSettingsTestRule.kt` line 65 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm2YR-5oriOSwyfkRO:-OCn1zW72n1Zw2vrrCUZ:bgl2f39) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/ForgetAllVpnAppsInSettingsTestRule.kt#L65)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Add comment what device and android verison that has this button. Now when it is starting to become a bigger list of combinations it would be nice to just add a comment so we can later rework this if there is a better way.
</blockquote></details>

Added this info 👍
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/ClearFirewallRules.kt` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm5XW_6JWk5PdOTuMb:-OCn25D_2oxTZN5mTdXI:byjb02b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/ClearFirewallRules.kt#L15)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we recreate the client each time?
</blockquote></details>

Wasn't sure how this works under the hood, but instantiating it in member declaration now 👍
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm7KM-2IKip_LAFoO8:-OCn21Og8k7AURImFxoA:b-ewhxr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L53)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is this some specific kind of firewall rule? Drop?
</blockquote></details>

See update, renamed to `FirewallDropRule`

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCm7KM-2IKip_LAFoO8:-OCnLQmmDESv7QOmVF0k:b2q3f36) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2305f9ad5c2a3dde865a7ff3d69ed2ba3ad4a3dc/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L53)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

See update, renamed to `FirewallDropRule`
</blockquote></details>

I think we can make these more clear:

```
sealed interface FirewallRule {
    data class Drop(...): FirewallRule
}
```

So when creating the rule it would look something like this: `FirewallRule.Drop(...)`

Also move this class out from `FirewallClient`. It looks weird when we create it through the client which has yet not been created:
```
            // Block UDP traffic to the relay
            val firewallRule = FirewallClient.FirewallDropRule.blockUDPTrafficRule(relayIpAddress)
            val firewallClient = FirewallClient()
            firewallClient.createRule(firewallRule)

```

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 10 of 15 files reviewed, 4 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 128 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCnM23T7H8tmohUWoAh:-OCnM23T7H8tmohUWoAi:byztyah) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/221e4a0dd3e392b7bc0a0537149739cf494b11c4/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L128)):*
> ```Kotlin
>             // Block UDP traffic to the relay
>             val firewallRule = FirewallClient.FirewallDropRule.blockUDPTrafficRule(relayIpAddress)
>             val firewallClient = FirewallClient()
> ```

Can there be one instance for all tests?

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 10 of 15 files reviewed, 7 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/e2e.properties` line 4 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCnO_gf5_fPGKZzNJNi:-OCnO_gf5_fPGKZzNJNj:biocgvt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/221e4a0dd3e392b7bc0a0537149739cf494b11c4/android/test/e2e/e2e.properties#L4)):*
> ```INI
> TRAFFIC_GENERATION_IP_ADDRESS=45.83.223.209
> PACKET_CAPTURE_API_HOST=192.168.105.1
> FIREWALL_API_HOST=192.168.105.1
> ```

Merge into same
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 57 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCnMlyfBMYbOgLfaAK4:-OCnMlyfBMYbOgLfaAK5:b-8f7ik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/221e4a0dd3e392b7bc0a0537149739cf494b11c4/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L57)):*
> ```Kotlin
>         val from: String,
>         val to: String,
>         val src: String,
> ```

Move `src` & `dst` to body.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 86 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OCnPRiB3Vn5MPaNQ6MH:-OCnPRiB3Vn5MPaNQ6MI:b66izxw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/221e4a0dd3e392b7bc0a0537149739cf494b11c4/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L86)):*
> ```Kotlin
>     companion object {
>         @SuppressLint("HardwareIds")
>         fun sessionIdentifierFromDeviceIdentifier(): String {
> ```

Create `SessionIdentifier` value class, and then let it have a function on Companion object that says `fun createFromDevice`

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 5 files at r7, 5 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OD6MF-bBd-OV0YyTbPY:-OD6MF-bBd-OV0YyTbPZ:b-awsuc9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6dfbc590daac23c91d2256352b57a06925b4aad/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.test.e2e.misc
> ```

This is a lot of logic to just be in the `misc` package. We should move it to another one. `router.firewall`?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 53 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OD6LJ14CS_SZc_GAjrl:-OD6LJ14CS_SZc_GAjrm:b1mkamm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6dfbc590daac23c91d2256352b57a06925b4aad/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L53)):*
> ```Kotlin
>     @JvmInline
>     @Serializable
>     value class SessionIdentifier(val value: String) {
> ```

We should move these classes (SessionIdentifier, DropRule, NetworkingProtocol) outside the FirewallClient class.

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 12 of 22 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OD6MF-bBd-OV0YyTbPY:-OD6kPZW-c4V1pTwmuLX:bb4oc0p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6dfbc590daac23c91d2256352b57a06925b4aad/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L1)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This is a lot of logic to just be in the `misc` package. We should move it to another one. `router.firewall`?
</blockquote></details>

Created packages `router` and `router.firewall`. Also moved `PacketCaptureClient` into `router`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt` line 53 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-OD6LJ14CS_SZc_GAjrl:-OD6kUy-Ejl4yzgMMRTS:b-mx5xo2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b6dfbc590daac23c91d2256352b57a06925b4aad/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/FirewallClient.kt#L53)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should move these classes (SessionIdentifier, DropRule, NetworkingProtocol) outside the FirewallClient class.
</blockquote></details>

Moved to `router.firewall` package

**Review by Rawa — APPROVED** [review]
> Reviewed 7 of 10 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/NetworkingProtocol.kt` line 7 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-ODBNTgTDX7zZ59IwvRG:-ODBNTgTDX7zZ59IwvRH:b-8bldoe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80a29e3dfb57c5469c207929c5687e78384205d5/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/NetworkingProtocol.kt#L7)):*
> ```Kotlin
> 
> @Serializable
> enum class NetworkingProtocol {
> ```

Is this the same type as used in `Stream` and packet capture?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: 17 of 27 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/DropRule.kt` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-ODBNEUi6zISX3huAO8x:-ODBpbKd7kcgexrEsIIA:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80a29e3dfb57c5469c207929c5687e78384205d5/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/DropRule.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Useless constructor keyword.
</blockquote></details>

Removed
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/NetworkingProtocol.kt` line 7 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222#-ODBNTgTDX7zZ59IwvRG:-ODBpEcVC_HwRMblrTiM:b-oa5je) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80a29e3dfb57c5469c207929c5687e78384205d5/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/NetworkingProtocol.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is this the same type as used in `Stream` and packet capture?
</blockquote></details>

It wasn't the same, but now it `NetworkingProtocol` is used by both

**Review by Rawa — APPROVED** [review]
> Reviewed 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7222)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
