### PR TITLE
Fix view logs crash

### PR DESCRIPTION
**Pull request by Rawa**
Fixes crash that could happen if we render too many lines in the textfield.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
This fixes the issue, however we no longer give the user the ability to download or copy the app logs. So I guess someone with more knowledge about how the users uses or are expected to use the app should confirm that we are not removing an expected feature.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-Nhk77crE-wJ25LDwuNh:b4eiat1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
That is correct, but considering that some users can't copy because it would crash immediately it might be our only way? We could also consider offering a copy button or similar to that.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-NhzaHOI33aSvJ1unWQW:b-tpw5q)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
I think we should raise the issue with Matilda and propose to add a button that allows the user to share/download the logs.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-Nj7HDhpDapMAVDFm8PE:b-pfz0nv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
I've messages design now, to see how they feel about resolving this.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-NjCIyOpBkko_c8yXa8g:bdr5pjk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
After internal discussions we have now added a share button that has the option to copy and share the content of the logs.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-NjHvU60ATZ3VV4oAfsG:b-n0h61z)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Nice improvement with the share button!

> Reviewed 1 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-NjI6fla7nOtdFKIt6QX:b-tbmgoj)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-NjI6Q4A3Go30XgZWi24:-NjI6Q4B8R3sgic2AQla:b-3v1jhv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97694a6842b3a826f05e569f2ea1406721df8ec5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt#L71)):*
> ```Kotlin
>                 navigationIcon = { NavigateBackIconButton(onBackClick) },
>                 actions = {
>                     IconButton(onClick = { shareLogs(uiState.allLines.joinToString("\n")) }) {
> ```

Do we need to make this call both here and in the `shareLogs` function or can we call it in a single place?



_Code quote:_
```Kotlin
uiState.allLines.joinToString("\n")
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-NjI6Q4A3Go30XgZWi24:-NjIAS_DE-0-QwMkSeX7:b-4gdj5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97694a6842b3a826f05e569f2ea1406721df8ec5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt#L71)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need to make this call both here and in the `shareLogs` function or can we call it in a single place?
</blockquote></details>

Nice catch, my mistake, I was suppose to use `uiState.text()` I fixed this issue and refactored out `shareLogs` function

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-NjICEmR0LUEuCWd9wwn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-:-NjIDZDtEUPKHkjiEwjq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373#-NjI6Q4A3Go30XgZWi24:-NjIDSlS2Kin0CSgTKeB:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97694a6842b3a826f05e569f2ea1406721df8ec5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt#L71)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice catch, my mistake, I was suppose to use `uiState.text()` I fixed this issue and refactored out `shareLogs` function
</blockquote></details>

:thumbsup:

**Pull request merged**
