### PR TITLE
Remove unused code related to old ui

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270#-:-NgTzXXJ9nJybRyZVMyL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270#-NgU7i6M4KS0yowJbLU2):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be changed to `Remove usused classes and resources`?
</blockquote></details>

Of course. Done.

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5270)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
