### PR TITLE
Upgrade build script and what version is printed from the daemon

### PR DESCRIPTION
**Pull request by faern**
First commit changes what `mullvad-daemon --version` will print. Up until now it has printed the useless `mullvad-daemon 0.1.0` string. But since we never bump the version that does not say very much. Now it will use the same `git describe` output that is used when logging the backend version. I did this partly so it would be easy to print the built version from the build script, so one can quickly see if they built the wrong version or something.

Then I go on and do the change that Erik started in #48. Only, this time I remove the relays.json file from git completely and I add an instruction in the readme about how to obtain it for people who check this out without doing a release build.

I also added conditional `yarn pack`. But for me it does not work on Linux, so I left that commented out, in order to skip the yarn part on Linux for now. Should it work? Maybe it's just my setup that is broken.

This script intentionally ignores Windows for now. I'm not sure what parts must be fixed there in order to make it work. So I thought that could be left as an exercise for when we know how to build a release on Windows. This at least does not make the situation worse on windows(?)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/53)

### CODE REVIEW

**Comment by faern** [comment]
It would be awesome if we could unify the version information into only being `git describe`, and not duplicated in `package.json`. The benefits would be:
1) No place to update in order to make a release, just tag the commit you are on.
2) Development builds will automatically have the nice `-<number>-<hash>` that uniquely describes what code it was built from.

**Comment by faern** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 45 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4LzKo-M_Cv0nZaOATY:-L4LzKo034XtISqT5RFD:b8vcn90) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88a3bb8e30ad1a02aba3f32e742be60a27f63069/build.sh#L45)):*
> ```Shell
> case "$(uname -s)" in
>     #Linux*)     yarn pack:linux;;
>     Darwin*)    yarn pack:mac;;
> ```

We should likely do a `yarn install` first as well? In order to make sure all the correct stuff is installed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by faern** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 45 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4LzKo-M_Cv0nZaOATY:-L4M4D-WmoboQ8SGxEgO:b-8k6xye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88a3bb8e30ad1a02aba3f32e742be60a27f63069/build.sh#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should likely do a `yarn install` first as well? In order to make sure all the correct stuff is installed?
</blockquote></details>

I went ahead and added that in the script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by eriklarko** [comment]
There's no obvious way to have electron builder read the version from anywhere other than package.json,but we could modify that in the script! 

---

Reviewed 8 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[build.sh, line 9 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4Lz0k6Vh97H7JTQa7r:-L4Lz0k6Vh97H7JTQa7s:bb7lbs2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88a3bb8e30ad1a02aba3f32e742be60a27f63069/build.sh#L9)):*
> ```Shell
>         echo "Dirty working directory!"
>         echo "You should only build releases in clean working directories in order to make it easier to reproduce the same build."
>         echo "Use --allow-dirty to skip this check."
> ```

nice

---

*[build.sh, line 45 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4LzKo-M_Cv0nZaOATY:-L4LzgGIKtNUbNJA8Xt_:b-grj3ws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88a3bb8e30ad1a02aba3f32e742be60a27f63069/build.sh#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should likely do a `yarn install` first as well? In order to make sure all the correct stuff is installed?
</blockquote></details>

Was just about to comment on that. `yarn install` will make sure the `./node_modules/` and `./yarn.lock` agree which is important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-:-L4M0nfgehCo0EVaGUy1:bhqpgmo)*

**Comment by faern** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 103 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4M4MnJbKSlkJ4cdN2e:-L4M4MnJbKSlkJ4cdN2f:b-ezbd8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a022beb34bb912cc6ce8b97f8eff65260bd11f46/README.md#L103)):*
> ```Markdown
> 
> 
> ## Making a release
> ```

Please give feedback on these steps. It feels like for every release we are like "Oh, so what steps was it we had to do again?"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by faern** [comment]
But then our working directory would be dirty. Which the script checks if it is or not :)
But if having the version in `package.json` is the only way, then I guess we could have a `prepare_release.sh` script that does this and some other sanity checking?

Releasing is basically two steps no matter what anyway:
1) Fixing metadata and everything else in the repo and getting that reviewed and merged (CHANGELOG & version)
2) Signing the release commit and building the artifact.

So it would make sense if there is one script for each of the steps. They can't be one script, because there has to be human intervention between the steps (code review and merge.)

---

Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-:-L4M4VsWshWH-flOxUs3:bumewzb)*

**Comment by faern** [comment]
Step 1 can maybe be kind of optimized out. If people correctly fix the changelog in their feature PRs that would automatically be done when it's time for a release. And if we make release build script automatically update `package.json`, commit the change, sign-tag the commit and then continue on with the building, then it can basically be completely automated. Or am I missing something? :)

---

Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-:-L4M5ldx8PCBMGfHifQs:b-93k5p7)*

**Comment by faern** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[build_release.sh, line 40 at r4](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4MP0r4nYX_hVI16NYi:-L4MP0r5T485c9jME--4:bwcn8m3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47873543ecf15c115920db44ac64c7bfaceb1a53/build_release.sh#L40)):*
> ```Shell
> 
> echo "Tagging current git commit with release tag $VERSION..."
> git tag -s $VERSION -m $VERSION
> ```

NOOOO! I realize now that we don't have the gpg keys on the same computer as we do build artifacts on.. That sucks.

So we will have to do the tag signing manually until we have some automatic build system running on a trusted server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by faern** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[build_release.sh, line 40 at r4](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4MP0r4nYX_hVI16NYi:-L4N5nXu5TaFLLrpSHW5:b-9cb50g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47873543ecf15c115920db44ac64c7bfaceb1a53/build_release.sh#L40)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

NOOOO! I realize now that we don't have the gpg keys on the same computer as we do build artifacts on.. That sucks.

So we will have to do the tag signing manually until we have some automatic build system running on a trusted server.
</blockquote></details>

The fix can simply be to not call `./build_release.sh` from this script and rename it to `prepare_release.sh` or similar. So this script is executed in a trusted environment with gpg keys. It makes the repository ready for the release by updating the version and adding the git tag.

Then on the different machines where we build the various architecture artifacts we just run the other script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by faern** [comment]
Review status: 6 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[prepare_release.sh, line 40 at r4](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4MP0r4nYX_hVI16NYi:-L4NBugiGP14leA-w71q:b-6oakq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47873543ecf15c115920db44ac64c7bfaceb1a53/prepare_release.sh#L40)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The fix can simply be to not call `./build_release.sh` from this script and rename it to `prepare_release.sh` or similar. So this script is executed in a trusted environment with gpg keys. It makes the repository ready for the release by updating the version and adding the git tag.

Then on the different machines where we build the various architecture artifacts we just run the other script.
</blockquote></details>

Ok. Done. I think this will work. I don't think we can simplify the release procedure any more. And I don't see the need to, this should be super simple now I hope!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by faern** [comment]
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[prepare_release.sh, line 17 at r5](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53#-L4NCmGhemqHNyPAdxlH:-L4NCmGiKA1VetOu7aFe:bwnpkol) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ea02755df4c6b8d832927c15125008ee7009e15/prepare_release.sh#L17)):*
> ```Shell
> if [[ $(echo $VERSION | egrep '^[0-9]{4}\.[0-9]+(-(beta|alpha)[0-9]+)?$') == "" ]]; then
>     echo "Invalid version format. Please specify version as:"
>     echo "<YEAR>.<NUMBER>[-(beta|alpha)<NUMBER>]"
> ```

In this script I try to be as strict as possible with all checks. And no flags to override them. Remember that this script is only used when we build an official release that is going out to customers. For internal office releases one should only use `./build.sh`, that can produce builds from dirty working dirs and whatnot.

I also wanted to add a safety check that `master` was the currently checked out branch. But since I think Erik still does not have local branches, that won't work with everyone's workflow, so I skipped that. We could possibly check if `origin/master` point to the currently checked out commit, that could work, but not super important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by pronebird** [comment]
Reviewed 6 of 8 files at r1, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/53)*

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/53#-:-L4g-Tdk0gfe6cde-Jiv:bnfp4nl)*

**Pull request merged**
