### PR TITLE
Set hostname constraint directly in the CLI

### PR DESCRIPTION
**Pull request by dlon**
As the title says. The command is `mullvad relay set relay <hostname>`. This can make setting the location constraints more convenient.

Additionally, output a warning if a relay in cannot be found when using `mullvad relay set location ...`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-cli/src/cmds/relay.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009#-MFV-y7oE95ErEucnazt:-MFV-y7oE95ErEucnazu:bj07mh5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52e78aacb94e3b3db3dbe385ba2ade99bae51dc1/mullvad-cli/src/cmds/relay.rs#L379)):*
> ```Rust
>             let countries = Self::get_filtered_relays().await?;
>             for country in &countries {
>                 if country.code != location_constraint.country {
> ```

This loop feels awfully similar to what the daemon does when it tries to match relays strictly. Maybe the logic from there could be lifted to `mullvad-types` and reused here?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-cli/src/cmds/relay.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009#-MFV-y7oE95ErEucnazt:-MFVY_YBESd5QUatILDG:b-fpt0xo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52e78aacb94e3b3db3dbe385ba2ade99bae51dc1/mullvad-cli/src/cmds/relay.rs#L379)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This loop feels awfully similar to what the daemon does when it tries to match relays strictly. Maybe the logic from there could be lifted to `mullvad-types` and reused here?
</blockquote></details>

Partly updated. The CLI does not use types from `mullvad-types` (yet), so I haven't made any changes to this code, though.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009#-:-MFW7fEn-fUV_o8wimzu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
