### PR TITLE
Bump libwfp to fix memory leak

### PR DESCRIPTION
**Pull request by dlon**
Related PR: https://github.com/mullvad/libwfp/pull/29

This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)

### CODE REVIEW

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[windows/winfw/src/winfw/sessioncontroller.cpp, line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298#-MMw0D6l-73jT1Z-1TcP:-MMw0D6l-73jT1Z-1TcQ:bzgpadi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c91e0fa2d874e8d7b71b35c36a5c580459386392/windows/winfw/src/winfw/sessioncontroller.cpp#L157)):*
> ```cpp
> 	{
> 		m_records.swap(m_transactionRecords);
> 		m_transactionRecords.clear();
> ```

This would be better placed right below this `if`?

What are the implications for surrounding code? As I recall, `m_transactionRecords` is only relevant/valid for the duration of the current function execution.

Possibly it would be even better to add this statement to the scope destructor.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[windows/winfw/src/winfw/sessioncontroller.cpp, line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298#-MMw0D6l-73jT1Z-1TcP:-MMzDN6Q0kvchbDHaKFP:b-y4pmfz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c91e0fa2d874e8d7b71b35c36a5c580459386392/windows/winfw/src/winfw/sessioncontroller.cpp#L157)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This would be better placed right below this `if`?

What are the implications for surrounding code? As I recall, `m_transactionRecords` is only relevant/valid for the duration of the current function execution.

Possibly it would be even better to add this statement to the scope destructor.
</blockquote></details>

Done. It does make sense to clear it even if `Execute` fails.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
