### PR TITLE
Simplify DNS management on Windows

### PR DESCRIPTION
**Pull request by dlon**
Changes:
* Write to `HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{adapter-guid}\NameServer` and flush the DNS cache directly instead of using `netsh`. This works even when the `dnscache` service is disabled, and when the `hosts` file is (ab)used for adblocking. `netsh` fails in the former case, and hangs in the latter case.
* Don't touch the NRPT at all. It was previously used for globally overriding DNS, but it breaks local name resolution for a lot of people.
* Remove the `WinDns` module.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 28 of 32 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: 29 of 34 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/windows/mod.rs` line 378 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3xlFsOBSkXonI0oEiv:-N3xlFsOBSkXonI0oEiw:b-sbqbp3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2f41098bddfba7c0d5eff3bbe61c3ce4eb99d533/talpid-core/src/windows/mod.rs#L378)):*
> ```XML
>             .to_string()
>     } else {
>         "".to_string()
> ```

I think this should return either an `Option`, `Result` or panic.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: 29 of 34 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`talpid-core/src/windows/mod.rs` line 378 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3xlFsOBSkXonI0oEiv:-N3xrTS88qoNgbM14Tu8:boi2j18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2f41098bddfba7c0d5eff3bbe61c3ce4eb99d533/talpid-core/src/windows/mod.rs#L378)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think this should return either an `Option`, `Result` or panic.
</blockquote></details>

Done. It can only fail if `buffer` is too small, which it never is. So it should be infallible, IMO.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 3 of 32 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/dns/windows/mod.rs` line 62 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3y-u_14IvGmFm82VDI:-N3y-u_14IvGmFm82VDJ:bu4qzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d9206c7e83a548ea572819aed494f4212a11937/talpid-core/src/dns/windows/mod.rs#L62)):*
> ```XML
>     fn reset(&mut self) -> Result<(), Error> {
>         if let Some(guid) = self.current_guid.take() {
>             return set_dns(&guid, &[]).and(flush_dns_cache());
> ```

Should the cache be flushed even if `set_dns` fails? I think it'd make sense to have a `and_then(|_| flush_dns_cache())`; 
___
*[`talpid-core/src/dns/windows/mod.rs` line 142 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3y0PThBQX20mX783f-:-N3y0PTiB-iRuFG0QUzV:buzox8l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d9206c7e83a548ea572819aed494f4212a11937/talpid-core/src/dns/windows/mod.rs#L142)):*
> ```XML
>     if let Err(error) = adapter_key.set_value("EnableMulticast", &0u32) {
>         log::error!(
>             "{}\nService: {service}",
> ```

Is the service identifier personally identifiable information? Would it not allow us to link a customer log with a specific customer machine?
___
*[`talpid-core/src/windows/mod.rs` line 378 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3xlFsOBSkXonI0oEiv:-N3y-aaM74oL1-yqiTr2:b1fjc9j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2f41098bddfba7c0d5eff3bbe61c3ce4eb99d533/talpid-core/src/windows/mod.rs#L378)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. It can only fail if `buffer` is too small, which it never is. So it should be infallible, IMO.
</blockquote></details>

If it's infallible, then making it panic if an assertion is invalid is the correct thing to do here.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: 32 of 34 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`talpid-core/src/dns/windows/mod.rs` line 62 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3y-u_14IvGmFm82VDI:-N3y4eRD27Ln1bU2Xysa:boq4iej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d9206c7e83a548ea572819aed494f4212a11937/talpid-core/src/dns/windows/mod.rs#L62)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should the cache be flushed even if `set_dns` fails? I think it'd make sense to have a `and_then(|_| flush_dns_cache())`; 
</blockquote></details>

I think it makes sense to try to clear it regardless. All we can do 
___
*[`talpid-core/src/dns/windows/mod.rs` line 142 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3y0PThBQX20mX783f-:-N3y4x7J4pkf4C--1iZ7:bgn7uzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d9206c7e83a548ea572819aed494f4212a11937/talpid-core/src/dns/windows/mod.rs#L142)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is the service identifier personally identifiable information? Would it not allow us to link a customer log with a specific customer machine?
</blockquote></details>

No, this only logs whether the operation failed for IPv4 or IPv6.
___
*[`talpid-core/src/windows/mod.rs` line 378 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3xlFsOBSkXonI0oEiv:-N3y90pwEh3ktzCQp55N:b-jcklao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2f41098bddfba7c0d5eff3bbe61c3ce4eb99d533/talpid-core/src/windows/mod.rs#L378)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If it's infallible, then making it panic if an assertion is invalid is the correct thing to do here.
</blockquote></details>

True. I've updated it.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: 32 of 34 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`talpid-core/src/dns/windows/mod.rs` line 62 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629#-N3y-u_14IvGmFm82VDI:-N3y9j-K4nQCN2uUTGRv:b-l8tds9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d9206c7e83a548ea572819aed494f4212a11937/talpid-core/src/dns/windows/mod.rs#L62)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it makes sense to try to clear it regardless. All we can do 
</blockquote></details>

All we (can) do if this fails is log the error, but it's better for the cache to be cleared than not.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3629)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
