### PR TITLE
Align internal and external notification expiry

### PR DESCRIPTION
**Pull request by kl**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822)

### CODE REVIEW

**Review by Rawa — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822#-:-O7D335C5wlOGMs7MFUK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822#-O7Da7diEt2h9FWMdreM:-O7Da7diEt2h9FWMdreN:bl8nsyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e52d56971d93cef4a5bb37bb8267b94bfa8669ed/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt#L62)):*
> ```Kotlin
> 
>     companion object {
>         private val REMAINING_TIME_FOR_REMINDERS = Duration.standardDays(3)
> ```

I think that we either should reference the other constant or use the same since otherwise it is quite easy to forget that they should be the same.

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822#-O7Da7diEt2h9FWMdreM:-O7Yfv_l21LvAEeyxNZA:b-xy259w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e52d56971d93cef4a5bb37bb8267b94bfa8669ed/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt#L62)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

I agree but `ACCOUNT\_EXPIRY\_CLOSE\_TO\_EXPIRY\_THRESHOLD` is defined in the main module file `AccountExpiryConstant.kt` and `REMAINING_TIME_FOR_REMINDERS` is defined in the service module.  So we cannot use the `ACCOUNT\_EXPIRY\_CLOSE\_TO\_EXPIRY\_THRESHOLD` constant in the `AccountExpiryNotificationProvider` file. Should we move the `AccountExpiryConstant.kt` file to the service module and have the use case reference the constants from there?
</blockquote></details>

I think that is fine. Ideally we should have some common constant module similar to the model module, but that is beyond the scope of this PR.

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822#-O7Da7diEt2h9FWMdreM:-O7cLKq-DG2jCEC4AhBW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e52d56971d93cef4a5bb37bb8267b94bfa8669ed/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt#L62)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think that is fine. Ideally we should have some common constant module similar to the model module, but that is beyond the scope of this PR.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822#-:-O7cOr9u5fhkv55y1ce7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
