### PR TITLE
Warn if user is running daemon as a non-root user

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/85)

### CODE REVIEW

**Comment by jvff** [comment]
I found two ways of checking if the user is root:

- check the meta-data of the created file;
- use the C `getuid` function.

None of them looked ideal to me. The second seemed more intuitive and clear what the intentions are, but it requires `libc` and an `unsafe` call. The first is safe but seems like a weird hack.

I ended up choosing the second option, but suggestions and feedback accepted :)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/85#-:-L6gWqKk1bRc9l7sk2jx:b46fj6g)*

**Comment by jvff** [comment]
Found another way:

- use `users::get_current_uid`.

The downside is adding another dependency to do exactly what is currently done (`unsafe { libc::getuid() }`).

Any opinions on this?

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/85#-:-L6gYkPp9S0F0Fv8x8p0:b-buso30)*

**Comment by pronebird** [comment]
ps: Since we use reviewable please assign reviewers under" assignees" as opposed to reviewers. It may sound as abuse but reviewable does not seem to integrate properly with reviews. :)

**Comment by faern** [comment]
@jvff I moved everyone over from "Reviewers" to "Assignees". That way plays nicer with reviewable and it's what we usually do. Will look at the code shortly :ok_hand:

**Comment by faern** [comment]
Awesome that you picked up this task. The implementation itself looks nice and all :ok_hand:, just a few comments on naming and placement of the code.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[mullvad-daemon/Cargo.toml, line 18 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pOCUHW6gJjZEkkAj9:-L6pOCUIFWyTAdBy0qEF:bc5p8kf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/Cargo.toml#L18)):*
> ```TOML
> serde = { version = "1.0", features = ["derive"] }
> serde_json = "1.0"
> libc = "0.2"
> ```

Can be moved to under `[target.'cfg(unix)'.dependencies]` to slightly reduce compile time, but also to make it clear what is used where.

---

*[mullvad-daemon/src/rpc_info.rs, line 52 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pNhWZ-qYk_PfeFuFE:-L6pNhWZ-qYk_PfeFuFF:btd2iqr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/src/rpc_info.rs#L52)):*
> ```Rust
> 
> fn open_file(path: &Path) -> io::Result<File> {
>     if !user_is_root() {
> ```

Sorry about nitpicking, but since `root` is a unix specific term and this method is called on all platforms it might be better to use `admin`? Also `user_is` might be a bit ambiguous as to which user we are talking about? `running_as_admin()` maybe?

---

*[mullvad-daemon/src/rpc_info.rs, line 53 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pNAQai__pyWGYNtRH:-L6pNAQbDGsVZQyjR3cw:ba0con6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/src/rpc_info.rs#L53)):*
> ```Rust
> fn open_file(path: &Path) -> io::Result<File> {
>     if !user_is_root() {
>         warn!("Running daemon as a non-root user, clients might refuse to connect");
> ```

What makes this related to opening the RPC file? Running as non-root have more implications than the permission of the RPC file. It will also fail to initialize the firewall and to run OpenVPN correctly. Since many parts of the daemon is dependent on running as the admin user I would say this should probably go very early in either `main` or `Daemon::new` instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-:-L6pOLcWqK0aZBtPEARW:b-ckoery)*

**Comment by jvff** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[mullvad-daemon/Cargo.toml, line 18 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pOCUHW6gJjZEkkAj9:-L6pfMieAiIf1NeBJsmR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/Cargo.toml#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can be moved to under `[target.'cfg(unix)'.dependencies]` to slightly reduce compile time, but also to make it clear what is used where.
</blockquote></details>

Done.

---

*[mullvad-daemon/src/rpc_info.rs, line 52 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pNhWZ-qYk_PfeFuFE:-L6pfTlqpU2WVPMWnqYy:b-qs1rkc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/src/rpc_info.rs#L52)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Sorry about nitpicking, but since `root` is a unix specific term and this method is called on all platforms it might be better to use `admin`? Also `user_is` might be a bit ambiguous as to which user we are talking about? `running_as_admin()` maybe?
</blockquote></details>

No worries. I think it's good for me to get as much feedback as possible, to allow me to be more consistent with the team development style.

---

*[mullvad-daemon/src/rpc_info.rs, line 53 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pNAQai__pyWGYNtRH:-L6pfUbxxUSwyZrmMRi8:bfa94gb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/src/rpc_info.rs#L53)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What makes this related to opening the RPC file? Running as non-root have more implications than the permission of the RPC file. It will also fail to initialize the firewall and to run OpenVPN correctly. Since many parts of the daemon is dependent on running as the admin user I would say this should probably go very early in either `main` or `Daemon::new` instead.
</blockquote></details>

Done. Moved it into `main()`, right after logging has been initialized and the app version has been printed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85)*

**Comment by pronebird** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-:-L6q--x1_koJmxDTZimX:bnfp4nl)*

**Comment by faern** [comment]
Nice change! Good to have this warning in place. I just merged my PR that also fixes the changelog. So please rebase and we are soon done here :)

---

Reviewed 1 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-daemon/src/rpc_info.rs, line 52 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-L6pNhWZ-qYk_PfeFuFE:-L6qAoQ3_ncmiGlza8Br:bkstc2o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d167599c7680161477e48e6ad59f2c73bf834f3/mullvad-daemon/src/rpc_info.rs#L52)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

No worries. I think it's good for me to get as much feedback as possible, to allow me to be more consistent with the team development style.
</blockquote></details>

Awesome :ok_hand: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-:-L6qAvflhDn7tZPNr5jq:b-xrf16r)*

**Comment by eriklarko** [comment]
Reviewed 2 of 5 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/85)*

**Comment by eriklarko** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/85)*

**Comment by eriklarko** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/85#-:-L6rCPCvCy1NOHfZsHxe:bnfp4nl)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/85#-:-L6s0i5FCHcuA8BPH2GM:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/85)*

**Pull request closed without merging**
