### PR TITLE
Add Android device list UI

### PR DESCRIPTION
**Pull request by albin-mullvad**
Adds the device list ui to the Android app.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`CHANGELOG.md` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674#-N50FeFn2sSMkKiHOBzc:-N50FeFn2sSMkKiHOBzd:b-bx8fth) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/747b0838ce913fb8f16dcde0c5a5ec4238bca751/CHANGELOG.md#L38)):*
I think we should avoid saying "already 5 connected". That can very easily be confused with amount of active VPN tunnels, which is not what this is about. Instead I suggest something like:

> the option to log other devices out when the account already has five devices.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`CHANGELOG.md` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674#-N50FeFn2sSMkKiHOBzc:-N50GuGt0Q4faJ_Zonaf:bgjkdxa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/747b0838ce913fb8f16dcde0c5a5ec4238bca751/CHANGELOG.md#L38)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should avoid saying "already 5 connected". That can very easily be confused with amount of active VPN tunnels, which is not what this is about. Instead I suggest something like:

> the option to log other devices out when the account already has five devices.
</blockquote></details>

Alright, will fix, this was a copy-paste from desktop =)

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: 1 of 37 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`CHANGELOG.md` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674#-N50FeFn2sSMkKiHOBzc:-N50N-Dq9PUquHU5joHt:b-mjmbux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/747b0838ce913fb8f16dcde0c5a5ec4238bca751/CHANGELOG.md#L38)):*
Now it says "log out other devices out", which is wrong I think.

> this was a copy-paste from desktop =)

I see that now. No need to repeat past sins. We have since seen users being confused about this. Would be nice to update the old changelog entry also to clarify :see_no_evil:

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: 1 of 38 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 14 of 37 files at r1, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: 16 of 38 files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`CHANGELOG.md` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674#-N50FeFn2sSMkKiHOBzc:-N55RNob67a42ybS6Iwl:b-w6ld0d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/747b0838ce913fb8f16dcde0c5a5ec4238bca751/CHANGELOG.md#L38)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Now it says "log out other devices out", which is wrong I think.

> this was a copy-paste from desktop =)

I see that now. No need to repeat past sins. We have since seen users being confused about this. Would be nice to update the old changelog entry also to clarify :see_no_evil: 
</blockquote></details>

Fixed :slightly_smiling_face:

**Review by pinkisemils — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3674)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
