### PR TITLE
Fix test matrix

### PR DESCRIPTION
**Pull request by Serock3**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/test-manager/src/tests/mod.rs` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219#-OCE4peXDGninf3FFWTB:-OCE4peXDGninf3FFWTC:ba32uzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73fbdd2dbd246b0dd7d6d5b28bee17c99536ea96/test/test-manager/src/tests/mod.rs#L89)):*
> ```XML
> pub fn should_run_on_os(targets: &[Os], os: Os) -> bool {
>     targets.is_empty() || targets.contains(&os)
> }
> ```

Would it make sense to tie this to the `TestDescription` struct? There is a logical connection to a specific test whenever `should_run_on_os` is invoked I presume, but currently that connection is not expressed in this type signature :blush:



_Code quote:_
```XML
pub fn should_run_on_os(targets: &[Os], os: Os) -> bool {
    targets.is_empty() || targets.contains(&os)
}
```
___
*[`test/test-manager/src/tests/mod.rs` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219#-OCE5CkY6KxHqnCq-lmo:-OCE5CkZ0Deaek5t2HqE:b-xtz8vz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73fbdd2dbd246b0dd7d6d5b28bee17c99536ea96/test/test-manager/src/tests/mod.rs#L105)):*
> ```XML
>         name: "test_upgrade_app",
>         targets: &[],
>     };
> ```

:pick: Would it make sense to briefly explain why this test is added here, and this workaround could potentially be removed in the future? :blush:



_Code quote:_
```XML
    let test_upgrade_app = TestDesciption {
        priority: None,
        name: "test_upgrade_app",
        targets: &[],
    };
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/mod.rs` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219#-OCE4peXDGninf3FFWTB:-OCEE6E3A0nARQeLNoGr:bm49tqk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73fbdd2dbd246b0dd7d6d5b28bee17c99536ea96/test/test-manager/src/tests/mod.rs#L89)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would it make sense to tie this to the `TestDescription` struct? There is a logical connection to a specific test whenever `should_run_on_os` is invoked I presume, but currently that connection is not expressed in this type signature :blush:
</blockquote></details>

Some context: I added `TestDescription` to avoid having to instantiate`TestMetadata` for `test_upgrade_app` (see the the first commit). It contained parameters that I didn't want to provide, like a function handle.

This function was tied to the `TestMetadata` before, but now it needs to be available to both it and `TestDescription`.  I would need a trait, or to duplicate the method, to attach it to the types.
___
*[`test/test-manager/src/tests/mod.rs` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219#-OCE5CkY6KxHqnCq-lmo:-OCEEe_R7cLFHdjMLfKf:byegjik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73fbdd2dbd246b0dd7d6d5b28bee17c99536ea96/test/test-manager/src/tests/mod.rs#L105)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: Would it make sense to briefly explain why this test is added here, and this workaround could potentially be removed in the future? :blush:
</blockquote></details>

Sure, I added some documentation. Needing `TestDescription` in the first place is kind of a hack, but the proper solution needs a larger refactoring. I elaborated on that in a comment.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`test/test-manager/src/tests/mod.rs` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219#-OCE4peXDGninf3FFWTB:-OCI49kd2ZEQ1DWp7QRd:b-a63sog) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73fbdd2dbd246b0dd7d6d5b28bee17c99536ea96/test/test-manager/src/tests/mod.rs#L89)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Some context: I added `TestDescription` to avoid having to instantiate`TestMetadata` for `test_upgrade_app` (see the the first commit). It contained parameters that I didn't want to provide, like a function handle.

This function was tied to the `TestMetadata` before, but now it needs to be available to both it and `TestDescription`.  I would need a trait, or to duplicate the method, to attach it to the types.
</blockquote></details>

Hmm, sad :( Oh well, it is what it is :blush:

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r3, 1 of 3 files at r4, 1 of 3 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219#-:-OCImYauAL2YxI9jDPQQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
