### PR TITLE
Make sure to query app version every 24 hours

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)

### CODE REVIEW

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/version_check.rs` line 360 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvIYCAk4_QFLcUF9vGR:-NvVs9ac3IZDI7-xGWpF:b-c3jss1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L360)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think that this needs to be a checked subtraction, or it might panic.
</blockquote></details>

Right, forgot std durations can't be negative. Made it a saturating_sub instead :+1: 
___
*[`mullvad-daemon/src/version_check.rs` line 413 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvIaoJ774mBkLoANdoF:-NvVzwvx4p_Ku_v0qnDQ:beo3msd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L413)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Perhaps this function should only run version check if the current cache is actually stale (either `None` or too old), and otherwise just return the last known version. Then I believe we could get rid of `app_version_info` from `Daemon`.
</blockquote></details>

Good thought, I'll look into it
___
*[`mullvad-daemon/src/version_check.rs` line 417 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvIYUx47JJdVYfIFSBW:-NvVxIb_5GnwHZEZKjXT:bmi8ppe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L417)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yes. :)
</blockquote></details>

:100: 
___
*[`mullvad-daemon/src/version_check.rs` line 452 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvIc_vcCjwfLRMEGjmS:-NvVxGCc8JevSz4NFov8:bqog80t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L452)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we handle responding to `self.run_version_check_responder` in the `Ok` case instead of in `self.update_version_info`? It feels too spaghetti.
</blockquote></details>

Agreed
___
*[`mullvad-daemon/src/version_check.rs` line 475 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvI_UAc6vfW_S5qBS87:-NvVrpH44zI8CQSD1MSw:b-whtqfi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L475)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are there no circumstances under which this can fail except that one?
</blockquote></details>

[Yes](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.modified), which is a bit weird tbh. I would expect that method to not be available at all on those platforms. :shrug:

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/version_check.rs` line 413 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvIaoJ774mBkLoANdoF:-NvXRnBK9YojmFBVWKil:b-ytz0u9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L413)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Good thought, I'll look into it
</blockquote></details>

there. @dlon whaddya think?

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/version_check.rs` line 413 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvIaoJ774mBkLoANdoF:-NvYD8BXAIWNu8o36p7n:b-sey37t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd9f828c7b593f8d103ce5e1291e98c3c0c1646/mullvad-daemon/src/version_check.rs#L413)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

there. @dlon whaddya think?
</blockquote></details>

I think it turned out better. Nice!
___
*[`mullvad-daemon/src/version_check.rs` line 445 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvYIyCsA3y9jqRCbtgV:-NvYIyCsA3y9jqRCbtgW:bal75sc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cecc5cd897bc26f22a3fc995146fb277912a33a1/mullvad-daemon/src/version_check.rs#L445)):*
> ```XML
>                                     version_check = self.do_version_check().fuse();
>                                 }
>                                 self.get_version_info_responders.push(done_tx);
> ```

Should we also `retain` only senders that aren't closed here? Maybe this is just me being paranoid.

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`mullvad-daemon/src/version_check.rs` line 445 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-NvYIyCsA3y9jqRCbtgV:-NvawOWb1g0HeJn08cGB:b-q6w8jg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cecc5cd897bc26f22a3fc995146fb277912a33a1/mullvad-daemon/src/version_check.rs#L445)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we also `retain` only senders that aren't closed here? Maybe this is just me being paranoid.
</blockquote></details>

Paranoid or not, it's only a single line so I went ahead and added it :)

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-:-NvcXxLB-Tf5HomJrEVa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119#-:-NvfwoquEDpz02PeG73u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
