### PR TITLE
Bump gradle plugin

### PR DESCRIPTION
**Pull request by axti**
Update gradle plugin to latest stable.
Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2453)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2453)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/gradle/wrapper/gradle-wrapper.properties, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2453#-MTB9uz9BOAym9b3rCUb:-MTB9uzA4njnON7q4jov:bany7g4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e2997b51a48996360bc5b5d5a2bd78f3f917cf83/android/gradle/wrapper/gradle-wrapper.properties#L1)):*
> ```INI
> #Wed Feb 10 10:05:42 CET 2021
> ```

Is this added by IDEA? It seems to me that having the time and date in the Git commit and in the file is redundant :/

**Comment by axti** [comment]
___
*[android/gradle/wrapper/gradle-wrapper.properties, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2453#-MTB9uz9BOAym9b3rCUb:-MTBJhjK2OBED_yhs0q3:b-xzpx6f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e2997b51a48996360bc5b5d5a2bd78f3f917cf83/android/gradle/wrapper/gradle-wrapper.properties#L1)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is this added by IDEA? It seems to me that having the time and date in the Git commit and in the file is redundant :/
</blockquote></details>

yes. It's added by IDEA. I will remove it.

**Comment by axti** [comment]
___
*[android/gradle/wrapper/gradle-wrapper.properties, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2453#-MTB9uz9BOAym9b3rCUb:-MTEpudr4Xrg0uRqGSic:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e2997b51a48996360bc5b5d5a2bd78f3f917cf83/android/gradle/wrapper/gradle-wrapper.properties#L1)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

yes. It's added by IDEA. I will remove it.
</blockquote></details>

Done.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2453#-:-MTG4yO44eZWP1HNI8nJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
