### PR TITLE
Add `wireguard-go-rs` crate

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR adds the `wireguard-go-rs` crate, which is a thin, safe Rust-wrapper around `libwg`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 33 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330)* status: 0 of 40 files reviewed, 2 unresolved discussions

___
*[`talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs` line 131 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-0pnmUEboqH1ADObtm:-O-0pnmUEboqH1ADObtn:brv4a38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c62881d849aa8505519039c9d04390e998f8f69/talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs#L131)):*
> ```XML
>     }
> 
>     // TODO: We shouldn't force `NetlinkTunnel` to implement `start_daita`
> ```

TODO
Should this be labelled as `HACK:` or `FIXME:` instead?



_Code quote:_
```XML
 // TODO: We shouldn't force `NetlinkTunnel` to implement `start_daita`
```
___
*[`talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs` line 117 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-0pzx_BQD8cYI-fx56:-O-0pzx_BQD8cYI-fx57:brv4a38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c62881d849aa8505519039c9d04390e998f8f69/talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs#L117)):*
> ```XML
>     fn start_daita(&mut self) -> std::result::Result<(), TunnelError> {
>         unreachable!("NetworkManager tunnel does not support DAITA")
>     }
> ```

TODO
Should this be labelled as `HACK:` or `FIXME:` instead?



_Code quote:_
```XML
    // TODO: We shouldn't force `NetworkManagerTunnel` tunnel to implement `start_daita`
    fn start_daita(&mut self) -> std::result::Result<(), TunnelError> {
        unreachable!("NetworkManager tunnel does not support DAITA")
    }
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330)* status: 0 of 40 files reviewed, all discussions resolved

___
*[`talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs` line 131 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-0pnmUEboqH1ADObtm:-O-156cmBh9TOWNwDBM0:bb5gy8y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c62881d849aa8505519039c9d04390e998f8f69/talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs#L131)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

TODO
Should this be labelled as `HACK:` or `FIXME:` instead?
</blockquote></details>

Nvm, this is addressed in the `add-daita-cfg-flag` PR
___
*[`talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs` line 117 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-0pzx_BQD8cYI-fx56:-O-15Mj59i_TX4NdmUcV:bb5gy8y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c62881d849aa8505519039c9d04390e998f8f69/talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs#L117)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

TODO
Should this be labelled as `HACK:` or `FIXME:` instead?
</blockquote></details>

Nvm, this is addressed in the `add-daita-cfg-flag` PR

**Review by Serock3 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-wireguard/src/lib.rs` line 825 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-1lGSF4177hSHUfTGk:-O-1lGSF4177hSHUfTGl:b-bs22rc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba7f8caf9e09697fa63da0203a8b496deeb17c7f/talpid-wireguard/src/lib.rs#L825)):*
> ```XML
> 
>     /// Configure and start a Wireguard-go tunnel.
>     fn open_wireguard_go_tunnel(
> ```

Missing `#[cfg(wireguard_go)]`

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 825 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-1lGSF4177hSHUfTGk:-O-1sMzE2LRqIX31Cmth:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba7f8caf9e09697fa63da0203a8b496deeb17c7f/talpid-wireguard/src/lib.rs#L825)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Missing `#[cfg(wireguard_go)]`
</blockquote></details>

Done

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 3 of 40 files at r1, 13 of 57 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330)* status: 16 of 82 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98 and @Serock3)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-6ioxD9Q274TiH-Fno:-O-6ioxD9Q274TiH-Fnp:b8ujcd4) (no related file):*
The GUI runs `mullvad-daemon --launch-daemon-status`, but its working directory seems to differ from that of `mullvad-daemon`, so it doesn't seem to find `libwg.so`:

```
[2024-06-11 16:33:06.591][error] Error while checking launch daemon authorization status.
                Stdout:
                Stderr: dyld[93807]: Library not loaded: libwg.so
  Referenced from: <41270484-D4AD-3697-8D6C-80C8A44D4D24> /Applications/Mullvad VPN.app/Contents/Resources/mullvad-daemon
  Reason: tried: 'libwg.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibwg.so' (no such file), 'libwg.so' (no such file), '//libwg.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS//libwg.so' (no such file), '//libwg.so' (no such file)

[2024-06-11 16:33:06.871][info] Skip autoconnect because GUI setting is disabled
```

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6330#-O-6q96X-qaw1fe3QsLV:-O-6q96Y095wQREES6i2:b-1mr6gl) (no related file):*
Some of the install/removal scripts (e.g. `postinstall`, and probably `before-remove.sh`, etc.) seem to suffer from the same issue, since they run `mullvad-setup` and `mullvad-daemon`.

___

**Pull request merged**
