### PR TITLE
Replace GoString with our own function to fix mte issue

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6727)

### CODE REVIEW

**Comment by hulthe** [comment]
Looks like it should work, but it should definitely come with a big comment explaining why we do this

**Comment by Pururun** [comment]
> Looks like it should work, but it should definitely come with a big comment explaining why we do this

Good point! I have added a comment.

**Comment by Pururun** [comment]
Tested and it works fine!

**Review by MarkusPettersson98 — APPROVED** [review]
:tada:
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6727#-:-O66XhzcCoaTgdtxEEls:bnjzbbv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6727)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
