### PR TITLE
Remove `block_when_disconnected` setting on Android

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)

### CODE REVIEW

**Review by hulthe — DISMISSED** [review]
> Reviewed 1 of 15 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/management_interface.rs` line 289 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007#-O9xjmlI47HzGS1xZ8vv:-O9xjmlI47HzGS1xZ8vw:brh5yl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80aa1e3d075829e4def5fa62efe6ec06d37f35ec/mullvad-daemon/src/management_interface.rs#L289)):*
> ```XML
>     }
> 
>     #[cfg(target_os = "android")]
> ```

Wonder if this function should return an error instead? To make it clear that you should not call it on android.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)* status: 10 of 16 files reviewed, 1 unresolved discussion (waiting on @hulthe and @Pururun)

___
*[`mullvad-daemon/src/management_interface.rs` line 289 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007#-O9xjmlI47HzGS1xZ8vv:-OAHCAeW62j7Ma_bu9Oj:brca4uj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80aa1e3d075829e4def5fa62efe6ec06d37f35ec/mullvad-daemon/src/management_interface.rs#L289)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Wonder if this function should return an error instead? To make it clear that you should not call it on android.
</blockquote></details>

That's a lovely suggestion, it is better to fail loudly if this ever is called :blush:

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007#-:-OAHV6FC4HrJtH8FaJbN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by hulthe — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
