### PR TITLE
Add filter for ownership and providers

### PR DESCRIPTION
**Pull request by MaryamShaghaghi**
In this screen, users can select ownership and providers to customize their experience. The selected preferences take effect in the 'Select Location' screen upon clicking 'Apply'.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-:-NkG6qh36xDrFVHU2HhC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-:-NkJhqqQ3cunfHQq6H-X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Good job! :star2: I just have a few small comments.

> Reviewed 40 of 43 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-:-NkZyo7A5vJ1_8SVvdyb:bshuixh)* status: all files reviewed, 4 unresolved discussions (waiting on @MaryamShaghaghi)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt` line 80 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZsIPI3uOjEGzQmCVY:-NkZsIPJ0UzBdSp6XvKh:bg65r5f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt#L80)):*
> ```Kotlin
>         composeTestRule.apply {
>             onNodeWithText("Ownership").performClick()
>             onNodeWithText("Mullvad owned only").performClick()
> ```

This should probably be `assertExists()` which is used in for example `testIsRentedCellShowing`?



_Code quote:_
```Kotlin
performClick()
```
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt` line 167 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZsfRL-f6oqLlUIuUi:-NkZsfRL-f6oqLlUIuUj:bxee296) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt#L167)):*
> ```Kotlin
>                 Provider("techfutures", false),
>                 Provider("Tzulo", false),
>                 Provider("xtom", false)
> ```

I think it would be better to not use real provider names here, but we can probably address that later.



_Code quote:_
```Kotlin
                Provider("31173", true),
                Provider("100TB", false),
                Provider("Blix", true),
                Provider("Creanova", true),
                Provider("DataPacket", false),
                Provider("HostRoyale", false),
                Provider("hostuniversal", false),
                Provider("iRegister", false),
                Provider("M247", false),
                Provider("Makonix", false),
                Provider("PrivateLayer", false),
                Provider("ptisp", false),
                Provider("Qnax", false),
                Provider("Quadranet", false),
                Provider("techfutures", false),
                Provider("Tzulo", false),
                Provider("xtom", false)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 177 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZ_HmK-bJAsVRsGlKZ:-NkZ_HmK-bJAsVRsGlK_:buksmh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L177)):*
> ```Kotlin
>     }
> 
>     fun openFilter() {
> ```

Is there a reason for including this function in the activity? Seems like it could be part of the fragment :thinking: 



_Code quote:_
```Kotlin
openFilter
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModelTest.kt` line 34 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZxMqW1UIuLnNy0Rde:-NkZxMqW1UIuLnNy0Rdf:bkgznek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModelTest.kt#L34)):*
> ```Kotlin
>     private val selectedOwnership =
>         MutableStateFlow<Constraint<Ownership>>(Constraint.Only(Ownership.MullvadOwned))
>     private val mockAllProviders =
> ```

This name is a bit misleading since it's not a mock. I suggest renaming to something like `dummyListOfAllProviders`



_Code quote:_
```Kotlin
mockAllProviders
```
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZqN_j7tJOnFxUMDgK:-NkZqN_j7tJOnFxUMDgL:bxs3jvi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L37)):*
> ```Kotlin
>     val dialogIconSize: Dp = 48.dp,
>     val expandableCellChevronSize: Dp = 30.dp,
>     val filterTittlePadding: Dp = 4.dp,
> ```

nit: typo



_Code quote:_
```Kotlin
tt
```

**Review by MaryamShaghaghi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt` line 80 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZsIPI3uOjEGzQmCVY:-Nk_fjo03urH5rE-6CAB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt#L80)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should probably be `assertExists()` which is used in for example `testIsRentedCellShowing`?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 177 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZ_HmK-bJAsVRsGlKZ:-Nk_cf01-EWUY8K8ukSO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L177)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a reason for including this function in the activity? Seems like it could be part of the fragment :thinking:
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModelTest.kt` line 34 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506#-NkZxMqW1UIuLnNy0Rde:-Nk_d-j76ufXDLICRB9g:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27fe90ec73b3c498d7cc73edaeaf7dee6a3cc9d7/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModelTest.kt#L34)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This name is a bit misleading since it's not a mock. I suggest renaming to something like `dummyListOfAllProviders`
</blockquote></details>

Done.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5506)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
