### PR TITLE
Migrate wfpctl

### PR DESCRIPTION
**Pull request by mvd-ows**
Added all wfpctl code and dependencies under `wfpctl/`. Code not specific to our project is referenced as a submodule and placed at `wfpctl/libwfp/`.

For the purpose of only using the module, build using `wfpctl/wfpctl.sln` and grab the output from `wfpctl/bin/...`

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/120)

### CODE REVIEW

**Comment by pinkisemils** [comment]
I've rebased on top of this and adjusted my scripts in `wfp-integration` and everything works out. Nicely done!

---

Reviewed 89 of 89 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120#-:-L9jXHas2bFrteYU-mAO:b-1fjqls)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[.gitmodules, line 6 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120#-L9jiXe2C_rW-NkmPnQ9:-L9jiXe2C_rW-NkmPnQA:b-vgetq4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7ab7674ed9d37f44ed2a3fb0e4aeb3812e9f058/.gitmodules#L6)):*
> ```
> [submodule "wfpctl/libwfp"]
> 	path = wfpctl/libwfp
> 	url = git@github.com:mullvad/libwfp
> ```

This must be changed to the https url to make cloning possible without having github credentials (relevant to for example travis)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120)*

**Comment by mvd-ows** [comment]
*[.gitmodules, line 6 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120#-L9jiXe2C_rW-NkmPnQ9:-L9nkH7xCoLzTITTNaOQ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7ab7674ed9d37f44ed2a3fb0e4aeb3812e9f058/.gitmodules#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This must be changed to the https url to make cloning possible without having github credentials (relevant to for example travis)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120)*

**Comment by faern** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/120)*

**Pull request merged**
