### PR TITLE
Remove unused DNS monitor backup writer

### PR DESCRIPTION
**Pull request by dlon**
This thing has been here since time immemorial, but it doesn't actually do anything, at least not anymore. So let's remove it.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087)

### CODE REVIEW

**Review by mvd-ows — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/dns/windows/mod.rs, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087#-MneTQTG2S32eqKkvoKE:-MneTQTG2S32eqKkvoKF:b-4zxm9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32ab14041eff0f1f4e77dfb4fd21e0ece0f80543/talpid-core/src/dns/windows/mod.rs#L49)):*
> ```XML
>     type Error = Error;
> 
>     fn new(_handle: tokio::runtime::Handle, _cache_dir: impl AsRef<Path>) -> Result<Self, Error> {
> ```

Do you anticipate requiring either of these arguments in the future? If not, perhaps they can be removed instead.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[talpid-core/src/dns/windows/mod.rs, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087#-MneTQTG2S32eqKkvoKE:-MnjMbis86Ir6-N166uy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32ab14041eff0f1f4e77dfb4fd21e0ece0f80543/talpid-core/src/dns/windows/mod.rs#L49)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Do you anticipate requiring either of these arguments in the future? If not, perhaps they can be removed instead.
</blockquote></details>

Done.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3087)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
