### PR TITLE
Use rule-based routing on Linux

### PR DESCRIPTION
**Pull request by dlon**
This gets rid of a lot of route parsing and monitoring. The mirroring of the main table in the `mullvad_exclusions` table in particular has been bug-prone. Except when Shadowsocks is used, there is also no need to keep track of which (non-tunnel) default route to use. Three static routing rules are used instead.

The main table is mostly unmodified now, though a single static route is added to it so that DNS requests can be made via the tunnel when using `mullvad-exclude`. The default route via the tunnel interface is instead added to its own routing table.

Additionally, a bug was fixed where `mullvad-exclude` would "leak" into the tunnel if there was no default IPv6 non-tunnel route, which caused it to match on the `::/1 dev wg-mullvad` route entry. The earlier [firewall update](https://github.com/mullvad/mullvadvpn-app/pull/2274) already prevented this from occurring, even though the routing was incorrect.

Related PRs: #2274, #2254

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282#-MMpLyrn20tL22QzY6KY:-MMpLyro7sN8nPOE1uuj:bvfxuho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/840ba4d750dbdf5f475389aed9e6a22c70f29808/talpid-core/src/tunnel/wireguard/mod.rs#L244)):*
> ```Rust
>                 if allowed_ip.prefix() == 0 {
>                     if allowed_ip.is_ipv4() {
>                         vec!["0.0.0.0/1".parse().unwrap(), "128.0.0.0/1".parse().unwrap()]
> ```

These two can be replaced with a single default route.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282#-MMpLyrn20tL22QzY6KY:-MMp_Rpr58wvjJPBiznB:b-d7q43k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/840ba4d750dbdf5f475389aed9e6a22c70f29808/talpid-core/src/tunnel/wireguard/mod.rs#L244)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

These two can be replaced with a single default route.
</blockquote></details>

This doesn't have to be replaced, this code can just be removed now, and the `allowed_ips` can be used as is.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282)* status: 5 of 11 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282#-MMpLyrn20tL22QzY6KY:-MMpfu9BD6NE8L7vtMqs:b9psuy2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/840ba4d750dbdf5f475389aed9e6a22c70f29808/talpid-core/src/tunnel/wireguard/mod.rs#L244)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This doesn't have to be replaced, this code can just be removed now, and the `allowed_ips` can be used as is.
</blockquote></details>

Ah, of course.

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2282#-:-MMtmmtPDPKAhz96fPBA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
