### PR TITLE
Logging xp

### PR DESCRIPTION
**Pull request by anderklander**
Moving logging to platform.js (because of issues with conditional imports using electron-log and react-native at the same time) and renaming open -> openLink to enable openItem (file).

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/30)

### CODE REVIEW

**Comment by pronebird** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/platform.android.js, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30#-L2tHRSSTInH_EDxaUkj:-L2tHRSSTInH_EDxaUkk:b-4sker2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/43bf96925e357b06bf3bc7c5d3d096cc70228ab9/app/lib/platform.android.js#L5)):*
> ```JavaScript
> import { MobileAppBridge } from 'NativeModules';
> 
> const log = console.log;
> ```

Not now but later on we'll have to save the log somewhere because it's attached as a part of problem report. Not important now :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[app/lib/platform.js, line 3 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30#-L2tHbfDvudWwOQJ9jlB:-L2tHbfDvudWwOQJ9jlC:b-j2csov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/43bf96925e357b06bf3bc7c5d3d096cc70228ab9/app/lib/platform.js#L3)):*
> ```JavaScript
> // @flow
> import { remote } from 'electron';
> import { shell } from 'electron';
> ```

I think you could combine electron imports:

```
import { remote, shell } from 'electron';
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30)*

**Comment by pronebird** [comment]
Looks ace! :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30#-:-L2tHoomT6lNVBM_X9eU:b-nrxzjx)*

**Comment by anderklander** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/platform.android.js, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30#-L2tHRSSTInH_EDxaUkj:-L2tMcH2Jk3qlJCyYBaw:b-lxn20i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/43bf96925e357b06bf3bc7c5d3d096cc70228ab9/app/lib/platform.android.js#L5)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Not now but later on we'll have to save the log somewhere because it's attached as a part of problem report. Not important now :)
</blockquote></details>

React-native writes this to the standard android logs, which can be saved. But the log handling for sure needs to be worked. Focusing on removing stuff that breaks things rather than verifying function at the moment.

---

*[app/lib/platform.js, line 3 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30#-L2tHbfDvudWwOQJ9jlB:-L2tvppNfHUfhJvd3Jwn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/43bf96925e357b06bf3bc7c5d3d096cc70228ab9/app/lib/platform.js#L3)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I think you could combine electron imports:

```
import { remote, shell } from 'electron';
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/30)*

**Pull request merged**
