### PR TITLE
Paint status bar after screen enter animation end

### PR DESCRIPTION
**Pull request by sabercodic**
Color phone status bar after fragment transition in following screens:
- select location screen
- account screen
- settings screen

This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKUKHBMUk-UD83J7g:-NbnKUKHBMUk-UD83J7h:b4mzosw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt#L54)):*
> ```Kotlin
>         }
>     }
>     LaunchedEffect(isCollapsable) {
> ```

I would use `Unit` instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKXuY2oxXN0FHqUFb:-NbnKXuY2oxXN0FHqUFc:b4mzosw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L78)):*
> ```Kotlin
>         }
>     }
>     LaunchedEffect(isCollapsable) {
> ```

I would use `Unit` instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKqt_8RUhi9lOs3cL:-NbnKqt_8RUhi9lOs3cM:b17whov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L75)):*
> ```Kotlin
> ) {
>     val context = LocalContext.current
>     val isCollapsable by remember { mutableStateOf(false) }
> ```

This could be removed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKumy7L9T-d2O2HC7:-NbnKumy7L9T-d2O2HC8:b-d1ka8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L80)):*
> ```Kotlin
> 
>     LaunchedEffect(Unit) { uiCloseAction.collect { onBackClick() } }
>     LaunchedEffect(isCollapsable) {
> ```

Could be replaced with `Unit`.

**Comment by albin-mullvad** [comment]
Please clarify the PR title. It would also be nice with a brief description.

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKUKHBMUk-UD83J7g:-NcXMIseBYv51LJHBlpc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt#L54)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I would use `Unit` instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKXuY2oxXN0FHqUFb:-NcXMMXp6MGC6Mm8VTq4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L78)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I would use `Unit` instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKqt_8RUhi9lOs3cL:-NcXM6jDDjWmXRI2-pgr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L75)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This could be removed.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NbnKumy7L9T-d2O2HC7:-NcXM6XpBioH577v4FGS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c31f26bf06645eb0a2722244a280f70fa86fc31e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L80)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Could be replaced with `Unit`.
</blockquote></details>

Done.

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NcXQjzoDakC6hfc1QL-):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Clarify this commit message
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-NcXRGMgCZdn2mau8IB8:-NcXTMIr8-np5JnAuEeg:b-el4d0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/978c4344ecfcb8995ed3016d77dd931b5c49d41e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt#L55)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we should use a constant instead since it's easier to use in compose and we're moving away from resources for most other similar things (font styling, colors etc).
</blockquote></details>

Done, I

**Review by Pururun — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt` line 55 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-Ncabc0z9YWdVloQGmwO:-Ncabc0z9YWdVloQGmwP:b-mrh343) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45e268b6fb0b08b5c7612756b57c9c2c4a1036b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt#L55)):*
> ```Kotlin
>     }
>     LaunchedEffect(Unit) {
>         delay(SCREEN_ENTER_TRANSITION)
> ```

Is there no way of triggering a callback when the animation/transition is complete rather using a `delay`? It seems like that would make more sense, especially for cases such as disabled animations (in system settings).

If having a proper callback is simplified by using Compose Navigation and the animation/transition support added in `2.7.0` it might be worth skipping this for now.



_Code quote:_
```Kotlin
delay
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt` line 55 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-Ncabc0z9YWdVloQGmwO:-Nd07ZY32EiuHDFEH5dB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45e268b6fb0b08b5c7612756b57c9c2c4a1036b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt#L55)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there no way of triggering a callback when the animation/transition is complete rather using a `delay`? It seems like that would make more sense, especially for cases such as disabled animations (in system settings).

If having a proper callback is simplified by using Compose Navigation and the animation/transition support added in `2.7.0` it might be worth skipping this for now.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by sabercodic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-:-Nd5bU4OAmXxP9-bOsYy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 13 of 16 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003#-:-NeCXNX0CB4PD2MaVEJu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
