### PR TITLE
Fix or report all current small Swiftlint warnings in xcode

### PR DESCRIPTION
**Pull request by rablador**
This PR fixes all smaller lint warnings we have in the project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103)* status: 0 of 34 files reviewed, 5 unresolved discussions

___
*[`ios/MullvadVPN/AppDelegate.swift` line 408 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZrMyOEsZ0N5DB_yEM:-NdZrMyOEsZ0N5DB_yEN:b5wcdcm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/MullvadVPN/AppDelegate.swift#L408)):*
> ```Swift
>         let initTunnelManagerOperation = AsyncBlockOperation(dispatchQueue: .main) { finish in
>             self.tunnelManager.loadConfiguration { error in
>                 // TODO: avoid throwing fatal error and show the problem report UI instead.
> ```

Reported separately in Linear.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZrZc28mKgsCEZBJb_:-NdZrZc28mKgsCEZBJba:b8vngfz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L120)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next function_body_length
> ```

Having a hard time shaving off more code from this function. It's certainly doable by eg. moving all localizable string creations outside, but there seems little point in doing so.
___
*[`ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZrslU9uZ5p_AaoPLa:-NdZrslU9uZ5p_AaoPLb:b2zwvay) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/MullvadVPN/View%20controllers/ProblemReport/ProblemReportInteractor.swift#L20)):*
> ```Swift
>     private lazy var consolidatedLog: ConsolidatedApplicationLog = {
>         let securityGroupIdentifier = ApplicationConfiguration.securityGroupIdentifier
> ```

Seems we redact all 16-digit numbers, so I'm assuming this is already taken care of.
___
*[`ios/MullvadVPN/View controllers/Tunnel/ConnectionPanelView.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZs4aG-NOjqvENmhOb:-NdZs4aG-NOjqvENmhOc:btix4i3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/View%20controllers/Tunnel/ConnectionPanelView.swift#L78)):*
> ```Swift
>         outAddressRow.translatesAutoresizingMaskIntoConstraints = false
> 
>         // Remove this line when we have out address
> ```

Reported to Linear. Kept this line to make it easy to find when fixing.
___
*[`ios/MullvadVPN/Views/AppButton.swift` line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZsE9pEtKtYROITBup:-NdZsE9pEtKtYROITBuq:b6v1s1z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/Views/AppButton.swift#L289)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next cyclomatic_complexity
> ```

The switch is what's causing the warning. I think it's fine to keep it as-is and disable the warning.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 29 of 34 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103)* status: 36 of 38 files reviewed, 15 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 495 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddTADx4VY9XZuUdZBJ:-NddTADx4VY9XZuUdZBK:b-n8m74f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/AppDelegate.swift#L495)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

We should definitely have a Linear issue for this file (if we don't already)
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 179 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddYdbv7wlQ-OSlNpLo:-NddYdbv7wlQ-OSlNpLp:bnpze4m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L179)):*
> ```Swift
>     private static func redactAccountNumber(string: String) -> String {
>         redact(
>             // swiftlint:disable:next force_try
> ```

Instead of manually using regexes to redact stuff, we should entirely get rid of this system and instead use 
the [OSLogPrivacy](https://developer.apple.com/documentation/os/oslogprivacy) feature of the logging system to not log sensitive information in the first place.

Now that we've dropped iOS 13, we can use it everywhere without having to backport the API.

I will create a Linear issue about this
___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 844 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddZWS-79sGqi9OUCw8:-NddZWS04ihuRf52ZfXx:b-5krage) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L844)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

We should have a Linear issue about this.
___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 983 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddZZEfEEfPlLXZvR0T:-NddZZEfEEfPlLXZvR0U:b-n3cn1g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L983)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

We should have a Linear issue about this
___
*[`ios/MullvadVPN/Notifications/NotificationManager.swift` line 210 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Ndd_Ixr7EIkZwG7pOpU:-Ndd_Ixr7EIkZwG7pOpV:b-7dhh01) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Notifications/NotificationManager.swift#L210)):*
> ```Swift
>         }
> 
>         invalidateInAppNotification(notificationProvider)
> ```

Simple, but efficient, love it !
___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProvider.swift` line 426 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Ndd_VIiBdQQ5gVAEr8J:-Ndd_VIiBdQQ5gVAEr8K:byv6duh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProvider.swift#L426)):*
> ```Swift
> }
> 
> // swiftlint:disable:next file_length
> ```

There are a lot of classes in this file that merit being in their own files, and we should do that instead.
This should get rid of this warning.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 757 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddaec56qQuM7vq8YRk:-Nddaec56qQuM7vq8YRl:b9q2boq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L757)):*
> ```Swift
>                 }
> 
>             case .invalid:
> ```

Why was this TODO removed ? Do we not want to handle this anymore ?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZrZc28mKgsCEZBJb_:-Nddb-CnCBM5ka3F_IxK:b-9vlgon) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L120)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Having a hard time shaving off more code from this function. It's certainly doable by eg. moving all localizable string creations outside, but there seems little point in doing so.
</blockquote></details>

The Localisation of the app has been a pet peeve of mine for a long while, we should definitely spend some time working on that, this adds so much visual noise for no good reason. 
___
*[`ios/MullvadVPN/Views/AppButton.swift` line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZsE9pEtKtYROITBup:-NddfTGT6vRP7vXmtQ1M:b-x2uiro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/Views/AppButton.swift#L289)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The switch is what's causing the warning. I think it's fine to keep it as-is and disable the warning.
</blockquote></details>

I think still think this could be rewritten to remove this omega switch. 
But ain't nobody go'time fo'dat
___
*[`ios/MullvadVPNTests/DeviceCheckOperationTests.swift` line 571 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddfhhq-WJo_Z2kDx_M:-Nddfhhq-WJo_Z2kDx_N:b-gxzz5o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPNTests/DeviceCheckOperationTests.swift#L571)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

Lots of non test code in this file that should be moved somewhere else.
I will create a Linear issue about this
___
*[`ios/Operations/AsyncOperation.swift` line 427 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddg1Ol4LQpQcXbTU_f:-Nddg1Ol4LQpQcXbTU_g:b-vpfryd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/Operations/AsyncOperation.swift#L427)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

If we instead move the `OperationBlockObserverSupport` definition and extension to its own file, this should get rid of the warning
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 767 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddg9V24GbRGTQQc7_M:-Nddg9V24GbRGTQQc7_N:b-rsik4o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/PacketTunnel/PacketTunnelProvider.swift#L767)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

I think we already have a Linear issue about this, but I will create one if there isn't

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103)* status: 37 of 38 files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Views/AppButton.swift` line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZsE9pEtKtYROITBup:-Ndj8VVx-02NTMyRJo8Q:bczxfrk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/Views/AppButton.swift#L289)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think still think this could be rewritten to remove this omega switch. 
But ain't nobody go'time fo'dat
</blockquote></details>

One iOS version away from `UIButton.Configuration`
___
*[`ios/MullvadVPNTests/DeviceCheckOperationTests.swift` line 571 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddfhhq-WJo_Z2kDx_M:-Ndj8v084EJYQFzop1B0:bxzqa7d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPNTests/DeviceCheckOperationTests.swift#L571)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Lots of non test code in this file that should be moved somewhere else.
I will create a Linear issue about this
</blockquote></details>

If someone is going to pick up on async support for device check then it's possible that a lot of stuff will go away from here.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103)* status: 37 of 38 files reviewed, 14 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 495 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddTADx4VY9XZuUdZBJ:-Ndjg6aG68kDHsYZfsrO:b-os018i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/AppDelegate.swift#L495)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should definitely have a Linear issue for this file (if we don't already)
</blockquote></details>

We have a general issue for all file lenghts.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 179 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddYdbv7wlQ-OSlNpLo:-NdjgFql1iVH5zkDTaGl:b2ol6p7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L179)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Instead of manually using regexes to redact stuff, we should entirely get rid of this system and instead use 
the [OSLogPrivacy](https://developer.apple.com/documentation/os/oslogprivacy) feature of the logging system to not log sensitive information in the first place.

Now that we've dropped iOS 13, we can use it everywhere without having to backport the API.

I will create a Linear issue about this
</blockquote></details>

 👍
___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 844 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddZWS-79sGqi9OUCw8:-NdjgQq093UFlYiGFYxg:b-os018i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L844)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should have a Linear issue about this.
</blockquote></details>

We have a general issue for all file lenghts.
___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 983 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NddZZEfEEfPlLXZvR0T:-NdjgRIG0ydB1L5fd_Ti:b-os018i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L983)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should have a Linear issue about this
</blockquote></details>

We have a general issue for all file lenghts.
___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProvider.swift` line 426 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Ndd_VIiBdQQ5gVAEr8J:-NdjtXnHEUbyoRCIOg2s:bhjyvjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProvider.swift#L426)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There are a lot of classes in this file that merit being in their own files, and we should do that instead.
This should get rid of this warning.
</blockquote></details>

Done, will be handled in a separate PR.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 757 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddaec56qQuM7vq8YRk:-NdjtbG_11s5BXwKRAgR:b-1wfygy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L757)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why was this TODO removed ? Do we not want to handle this anymore ?
</blockquote></details>

It has been there for some time and I didn't think it had a clear purpose. We can add a Linear issue if you insist.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZrZc28mKgsCEZBJb_:-Ndjuxlr67YHRM7m9AO0:b-3kx1p4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L120)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The Localisation of the app has been a pet peeve of mine for a long while, we should definitely spend some time working on that, this adds so much visual noise for no good reason.
</blockquote></details>

Sure thing, but let's keep that in another PR for now :)
___
*[`ios/Operations/AsyncOperation.swift` line 427 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddg1Ol4LQpQcXbTU_f:-Ndjxafe7T5yIsszwS-A:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/Operations/AsyncOperation.swift#L427)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If we instead move the `OperationBlockObserverSupport` definition and extension to its own file, this should get rid of the warning
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103)* status: 36 of 39 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 757 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-Nddaec56qQuM7vq8YRk:-Ndk41hF4o_a0Krlc_UL:boh4yrh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/220ee2b554010e1e3005b88ee88d73d353bb78c1/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L757)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It has been there for some time and I didn't think it had a clear purpose. We can add a Linear issue if you insist.
</blockquote></details>

Not necessarily, I was just being curious. I would have suggested to leave it instead, but I'm not strung up on it either.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5103#-NdZrZc28mKgsCEZBJb_:-Ndk4nEhC7cM1BBdqMLG:b-8q2mri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bafb04ff6412ca0ebac51287dce618dd76a07eb8/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L120)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Sure thing, but let's keep that in another PR for now :)
</blockquote></details>

Oh yes absolutely, I'm sorry if it seemed like I suggested to do it here, definitely not the intent !

**Pull request merged**
