### PR TITLE
Add a vocabulary section to the README

### PR DESCRIPTION
**Pull request by faern**
Adding a vocabulary of common terms to the readme. My intention is that the vocabulary should include words that by themselves and without context could mean virtually anything, so we need to give them definitions in the context of our product.

We have changed words used for different components over the history of this project and both the code and the documentation is probably still wrong in many places. We also use different words when talking to each other and it can quite easily cause confusion. So my plan was to debate and discuss this vocabulary and get it merged. Then we can refer to this and try to stick to the defined words when we code and when we talk to each other.

Adding the entire team as assignees since it's important that we are all synced and up to date with what words we use.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/101)

### CODE REVIEW

**Comment by jvff** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-:-L82sBxF6L8Bcbq9bQOX:bnfp4nl)*

**Comment by mvd-ows** [comment]
*[README.md, line 188 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82sKts4dCZV-wrhT5Q:-L82sKts4dCZV-wrhT5R:brfsl0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L188)):*
> ```Markdown
> ## Vocabulary
> 
> Explanations for some common words used in the documentation and code in this repositry.
> ```

repo, spelling

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by anderklander** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101#-:-L82sNl6UruubfGP4UK8:bnfp4nl)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 191 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82rbEPDfdx2JdbJ0P3:-L82rbEPDfdx2JdbJ0P4:be2zea1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L191)):*
> ```Markdown
> 
> - **App** - This entire product (everything in this repository) is the "Mullvad VPN App", or App for
>   short.
> ```

This term, the "app" I feel is already pretty set in stone. We have referred to the entire product as the "Mullvad VPN App" in our PR material, blog content etc since day one more or less. I think it would be confusing to use the word "app" for anything else than the entire product by now.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L82s4dOAVzG7KBHbVzl:bpx190v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
> ```Markdown
>   - **Frontend** - Term used for any program or component that connects to the daemon management
>     interface and allows a user to control the daemon.
>     - **GUI** - The Electron + React program that is a graphical frontend for the Mullvad VPN App.
> ```

This might be the term we agree the least on? I don't find a better term for the Electron based GUI though. Suggestions welcome.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 188 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82sKts4dCZV-wrhT5Q:-L82sXNN71W-beeVcRB4:b9cql6i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L188)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

repo, spelling
</blockquote></details>

Thanks. Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by mvd-ows** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L82slTi-sU8DVMP7jGr:b-lymku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This might be the term we agree the least on? I don't find a better term for the Electron based GUI though. Suggestions welcome.
</blockquote></details>

IIRC typically in OS vocabulary it's called a "shell". But that's also a very misused word, so I would probably go against it.

Would it make sense to call them all "user interfaces" instead of "frontends"? Then we have "CLUI" (?), "Electron UI", etc.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L82tezG7RTaNww2n0fF:bf1wou5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

IIRC typically in OS vocabulary it's called a "shell". But that's also a very misused word, so I would probably go against it.

Would it make sense to call them all "user interfaces" instead of "frontends"? Then we have "CLUI" (?), "Electron UI", etc.
</blockquote></details>

I opened this thread on the word GUI, not Frontend. But we can discuss frontend indeed. Which OS calls these things shells? When I hear shell I think of a terminal/console program, i.e. bash is a shell.

Yes they are user interfaces as well. They are both frontends and user interfaces.

Regarding "Electron UI"; I was trying to avoid implementation and technical details in the terms themselves. I don't think it's important that the graphical user interface is written with Electron really. Like how Slack refers to their desktop client as the "desktop app" not their "Electron app" or their "Electron UI" for example.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by jvff** [comment]
*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L82xJUy2F2a0R91_0r6:b-u129l9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I opened this thread on the word GUI, not Frontend. But we can discuss frontend indeed. Which OS calls these things shells? When I hear shell I think of a terminal/console program, i.e. bash is a shell.

Yes they are user interfaces as well. They are both frontends and user interfaces.

Regarding "Electron UI"; I was trying to avoid implementation and technical details in the terms themselves. I don't think it's important that the graphical user interface is written with Electron really. Like how Slack refers to their desktop client as the "desktop app" not their "Electron app" or their "Electron UI" for example.
</blockquote></details>

On Windows (at least back to Win9x), the desktop + task bar was called a shell IIRC. Can't remember if KDE/Gnome used the same nomenclature.

How about "Desktop UI"? Might not be a good idea, since it contrasts with "Mobile UI", unless we will have a unified notion of "Mobile UI".

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L82yAyY8TnmP2XNvNMn:b-srhm62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

On Windows (at least back to Win9x), the desktop + task bar was called a shell IIRC. Can't remember if KDE/Gnome used the same nomenclature.

How about "Desktop UI"? Might not be a good idea, since it contrasts with "Mobile UI", unless we will have a unified notion of "Mobile UI".
</blockquote></details>

The thing I refer to as the GUI, the electron + react app/program, was meant to mean the GUI we run on both desktop and mobile, which is why I could not have "desktop" or "mobile" in the name. But maybe those will be two different programs/components?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by anderklander** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 196 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L8372SwqTg-SHCgeIB4:bblcr6d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The thing I refer to as the GUI, the electron + react app/program, was meant to mean the GUI we run on both desktop and mobile, which is why I could not have "desktop" or "mobile" in the name. But maybe those will be two different programs/components?
</blockquote></details>

It looks like there will be 99% the same code for _UI_ on both mobile and desktop so from a dev point of view i guess its best with one name for all react-stuff even if there is a bigger difference in the JS-files that don't handle the UI directly but is a part of the "app" directory (rename possible/desirable?). 

Might be interesting to find a word for the "deamon"-equivalent or the java/android-specific stuff that will run on android. Best suggestion i can come up with right now would be something like android-service, which could include both rust and java parts. In android terminology it seems more fit than android-deamon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101)*

**Comment by pinkisemils** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 196 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L83Ac_epUvAHh5B6QW0:b-s1b0n1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

It looks like there will be 99% the same code for _UI_ on both mobile and desktop so from a dev point of view i guess its best with one name for all react-stuff even if there is a bigger difference in the JS-files that don't handle the UI directly but is a part of the "app" directory (rename possible/desirable?). 

Might be interesting to find a word for the "deamon"-equivalent or the java/android-specific stuff that will run on android. Best suggestion i can come up with right now would be something like android-service, which could include both rust and java parts. In android terminology it seems more fit than android-deamon.
</blockquote></details>

GUI makes sense to me. Shell is usually used to describe an interface to an operating system or it's services, whereas our command-line interface and graphical user interface _interface_ with the daemon itself. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101#-:-L83CD1su4TZp5nPTWNB:bnfp4nl)*

**Comment by jvff** [comment]
*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L83CZzABWws9i-NJwfW:b-3bf2ra) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

GUI makes sense to me. Shell is usually used to describe an interface to an operating system or it's services, whereas our command-line interface and graphical user interface _interface_ with the daemon itself. 
</blockquote></details>

From the discussion, I'm tending to think that currently GUI is the best name for it. Frontend could be changed, but alternatives are lacking.

Regarding the android part, "service" seems an appropriate suffix. The question would be what would the full name be:

- "android-service" (too generic?);
- "mullvad-service" (too ambiguous?);
- "mullvad-android-service" (initially looks separate from the daemon);
- "daemon-service" (too generic?);
- "android-daemon-service" (no mention of mullvad?)
- "mullvad-daemon-service" (too long? Could be interpreted as part of the daemon?)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L83ELtk8AD3A5Q7q2Nf:bohvbfz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

From the discussion, I'm tending to think that currently GUI is the best name for it. Frontend could be changed, but alternatives are lacking.

Regarding the android part, "service" seems an appropriate suffix. The question would be what would the full name be:

- "android-service" (too generic?);
- "mullvad-service" (too ambiguous?);
- "mullvad-android-service" (initially looks separate from the daemon);
- "daemon-service" (too generic?);
- "android-daemon-service" (no mention of mullvad?)
- "mullvad-daemon-service" (too long? Could be interpreted as part of the daemon?)
</blockquote></details>

@jvff "daemon" and "service" are just synonyms IMO. Different platforms use different words but they mean the same. Headless background programs carrying out tasks in a non-interactive way. So with that assumption it would not make much sense to use both "daemon" and "service". I lean towards "daemon" since that is the word I'm personally most used to plus it's already named that so it would be a lot of work to rename it and it would not add much value IMO.

"android-service" is just for one platform, I'm looking for a term that covers what the `mullvad-daemon` program is responsible for on all platforms, see previous post to this thread.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L83GKAM4qtZ2Lzln7ep:bmbl7qf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

@jvff "daemon" and "service" are just synonyms IMO. Different platforms use different words but they mean the same. Headless background programs carrying out tasks in a non-interactive way. So with that assumption it would not make much sense to use both "daemon" and "service". I lean towards "daemon" since that is the word I'm personally most used to plus it's already named that so it would be a lot of work to rename it and it would not add much value IMO.

"android-service" is just for one platform, I'm looking for a term that covers what the `mullvad-daemon` program is responsible for on all platforms, see previous post to this thread.
</blockquote></details>

This thread has now started to include three of the proposed terms in the vocabulary. If we want to discuss these further I suggest taking it on mumble tomorrow, that will be way faster.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/101#-:-L84o7n3a5ZqmHkzSbIN:bnfp4nl)*

**Comment by jvff** [comment]
*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L8727Mv8RBVipl4oZzc:br5sgaz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This thread has now started to include three of the proposed terms in the vocabulary. If we want to discuss these further I suggest taking it on mumble tomorrow, that will be way faster.
</blockquote></details>

What I meant was how to name the Android service (which I'm assuming will spawn the daemon). I think we might be talking about different things. I assume "mullvad-daemon" is already agreed on, but there was a mention in the discussion about the Android part, and my point was that "Service" is a known and specific term in Android, which will apply well to the Java code that will run in the background and control the "mullvad-daemon".

But since the Android isn't mentioned in this file yet, perhaps deciding on its name is better left for a separate PR?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L87Sa2-8tcXEfizJZzb:b-38axfw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
Ok. I did not understand you were talking about a future term, I thought we were debating "daemon".

Yes, hard enough to agree on the terms we already have. I think we can leave the future for later :) But yes, I agree we should probably use platform specific terms. So something like I wrote above:
> So I'm thinking something like the following "Our Android service is some Java code that spawn the Mullvad daemon and keeps it running"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 196 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101#-L82s4dOAVzG7KBHbVzk:-L87c5J_7jYwMdQuU09C:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4d55a70e203fe631c5491ccd9119a3ff56fa94/README.md#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ok. I did not understand you were talking about a future term, I thought we were debating "daemon".

Yes, hard enough to agree on the terms we already have. I think we can leave the future for later :) But yes, I agree we should probably use platform specific terms. So something like I wrote above:
> So I'm thinking something like the following "Our Android service is some Java code that spawn the Mullvad daemon and keeps it running"
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/101)*

**Pull request merged**
