### PR TITLE
Fix copy button scaling issue

### PR DESCRIPTION
**Pull request by sabercodic**
Fixed: DROID-240, DROID-241

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
This results in just 12 dots being shown on my OnePlus 6T, which is not the intended behavior. I believe the number/dots should be scaled down if they don't fit.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-:-Naq68kXA17EKv3MDxvA:b2rop2a)* status: 0 of 3 files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-xvnv3a8h1HewrN55:-Nb-xvnv3a8h1HewrN56:bgfvad8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L73)):*
> ```Kotlin
>     maxLines: Int = Int.MAX_VALUE,
> ) {
>     var fontSizeValue by remember { mutableStateOf(maxTextSize.value) }
> ```

Change to `adjustedFontSize`



_Code quote:_
```Kotlin
fontSizeValue
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 74 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-xYcw6UJ2q4sVo_-A:-Nb-xYcw6UJ2q4sVo_-B:b-wwk9jm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L74)):*
> ```Kotlin
> ) {
>     var fontSizeValue by remember { mutableStateOf(maxTextSize.value) }
>     var readyToDraw by remember { mutableStateOf(false) }
> ```

Change to `isReadyToDraw`



_Code quote:_
```Kotlin
readyToDraw
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 82 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-yA5nEDAwgm2bVRgk:-Nb-yA5nEDAwgm2bVRgl:bq3rlw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L82)):*
> ```Kotlin
>         fontSize = fontSizeValue.sp,
>         onTextLayout = {
>             if (it.didOverflowHeight && !readyToDraw) {
> ```

Change to `.not()`



_Code quote:_
```Kotlin
!
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-yJrT1fA1H5Slky5e:-Nb-yJrU5NR9lrc9rG2q:b-6w6o9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L83)):*
> ```Kotlin
>         onTextLayout = {
>             if (it.didOverflowHeight && !readyToDraw) {
>                 val nextFontSizeValue = fontSizeValue - DEFAULT_TEXT_STEP.value
> ```

This should be a function argument



_Code quote:_
```Kotlin
DEFAULT_TEXT_STEP.value
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-xvnv3a8h1HewrN55:-Nb08KpZ6b0E-WXziYAA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L73)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `adjustedFontSize`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 74 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-xYcw6UJ2q4sVo_-A:-Nb08PyW5heI1-gh4AS0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L74)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `isReadyToDraw`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 82 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-yA5nEDAwgm2bVRgk:-Nb08W50BLcfZ2cpATza:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L82)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `.not()`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-Nb-yJrT1fA1H5Slky5e:-Nb08uLH5rmjGVU_1Sjl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d4481e709df4a5be8a1c9c2727462d3d6c6cbb4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L83)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should be a function argument
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951#-:-NbE-RMW6KPCE5ZUhJE2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
