### PR TITLE
Fix text color in account view

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226#-Nftedt1-Y40bcjnGAoF:-Nftedt24CIKViqAQ_xA:bs9ky0k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b995f6d052946afb728f1dda21bfc800acf7456c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L83)):*
> ```Kotlin
>         maxLines = maxLines,
>         style = style,
>         color = MaterialTheme.colorScheme.onSurface,
> ```

Should probably be `onBackground` since it will be on top of `background` in the account screen.
Or we expose it all the way and set it to `onBackground` in the screen.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226#-Nftedt1-Y40bcjnGAoF:-NfuWZLMA7BUHYPHXUs_:b-gzhb41) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d0d853921d042233d77f21e0aa4dfe7e85b9fc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt#L83)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should probably be `onBackground` since it will be on top of `background` in the account screen.
Or we expose it all the way and set it to `onBackground` in the screen.
</blockquote></details>

Ah yes, correct. Fixed

**Review by sabercodic — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226#-:-Nfu_weZDFuPNM_UY43V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226#-:-Nfv7urNDiU_SRuPhTga:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
