### PR TITLE
Add support for quantum resistant tunneling

### PR DESCRIPTION
**Pull request by Pururun**
- Show if quantum resistant tunneling is used in connect fragment
- Add Options (Auto, On, Off) for quantum resistant tunneling in VPN Settings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 19 of 20 files at r2, 6 of 16 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: 41 of 43 files reviewed, 4 unresolved discussions (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: 15 of 43 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @dlon)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/model/WireguardTunnelOptions.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NWh8asC40ELrEOuIX66:-NX9dBcq-Bq5TMz8cmmC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcef29dd3262ba8205da3ddcd0440bee2d93bc4c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/model/WireguardTunnelOptions.kt#L7)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does this need to be nullable? Same applies for setting it.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 182 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NWqhfz689bRuK0W7nJN:-NX9dCPYA72zw0JYNQwr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcef29dd3262ba8205da3ddcd0440bee2d93bc4c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L182)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does this have to be nullable?
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: 14 of 43 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @dlon)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectionStatus.kt` line 41 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NWh9C3R0BNVGaP1qNFD:-NX9ecLn3rEcOgP2_xyf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcef29dd3262ba8205da3ddcd0440bee2d93bc4c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectionStatus.kt#L41)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest: `isQuantumResistant`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectionStatus.kt` line 54 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NWh9J5RCejHvr_3DD2a:-NX9eck05yRb0ELxyb71:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcef29dd3262ba8205da3ddcd0440bee2d93bc4c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectionStatus.kt#L54)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest: `isQuantumResistant`
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> Reviewed 22 of 26 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: 36 of 43 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 6 files at r5, 4 of 26 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 583 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB4xLh2NXhBgfDuAgq:-NXB4xLh2NXhBgfDuAgr:b20bitv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L583)):*
> ```Kotlin
> 
>         // Assert
>         composeTestRule.onNodeWithText("On").assertExists()
> ```

Can this match be made more specific? It seems like this potentially can result in false-positives when adding more settings.



_Code quote:_
```Kotlin
"On"
```
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 604 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB4Vtc4cLw-4F6cUBG:-NXB4Vtc4cLw-4F6cUBH:b1zgoga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L604)):*
> ```Kotlin
>         composeTestRule
>             .onNodeWithTag(LAZY_LIST_TEST_TAG)
>             .performScrollToNode(hasTestTag(LAZY_LIST_LAST_ITEM_TEST_TAG))
> ```

We probably want to use another tag in this and some of the other tests to avoid scrolling too far in the list.



_Code quote:_
```Kotlin
LAZY_LIST_LAST_ITEM_TEST_TAG
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 40 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB5TLE-LVFfc8yxTPS:-NXB5TLF6KWlDCi2G0LX:b-wzf4t4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L40)):*
> ```Kotlin
>     private val mockResources: Resources = mockk()
> 
>     // Flows
> ```

nit: I suggest skipping this comment since it doesn't seem to add much value here



_Code quote:_
```Kotlin
// Flows
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB79zQ9tpjC8f5k3UC:-NXB79zQ9tpjC8f5k3UD:b-snnx5a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L43)):*
> ```Kotlin
>     private val mockSettingsUpdate = MutableStateFlow<Settings?>(null)
> 
>     private lateinit var testSubject: VpnSettingsViewModel
> ```

nit: I suggest renaming to `viewModel` since that's what we use in most other similar tests like this.



_Code quote:_
```Kotlin
testSubject
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 82 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB7OP-704W_NVdJtDb:-NXB7OP-704W_NVdJtDc:b-t0ktfx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L82)):*
> ```Kotlin
> 
>     @Test
>     fun test_update_quantum_resistant_update_state() = runTest {
> ```

Is all this mocking necessary? Isn't it enough to mock the settings repository?

Also, would be nice to add newlines between the sections of this function.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: 39 of 45 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 583 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB4xLh2NXhBgfDuAgq:-NXJHb06AivH3u7eAO7C:b8pr7kl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L583)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this match be made more specific? It seems like this potentially can result in false-positives when adding more settings.
</blockquote></details>

Used tags instead.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 604 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB4Vtc4cLw-4F6cUBG:-NXJHqFU457E1SxZd7SE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L604)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We probably want to use another tag in this and some of the other tests to avoid scrolling too far in the list.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 82 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742#-NXB7OP-704W_NVdJtDb:-NXJHsIq-4b21h4Snig2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7ae82e3724080e2d6927b72cde954a101b6b072/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L82)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is all this mocking necessary? Isn't it enough to mock the settings repository?

Also, would be nice to add newlines between the sections of this function.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4742)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
