### PR TITLE
Move my and Andrei's forks over to the Mullvad organization

### PR DESCRIPTION
**Pull request by eriklarko**
We don't really want forks of packages on our private accounts, so I have forked the three forks we had to the mullvad organization instead. This PR updates package.json to point to the new forks .

Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

Not worth mentioning in the changelog.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/93)

### CODE REVIEW

**Comment by pronebird** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/93#-:-L79INo0COFcVUFbzgXe:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/93)*

**Comment by pronebird** [comment]
Actually I think we could transfer repos instead of forking.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/93#-:-L79MGRcB589O6rh7e9D:b-gr3s7j)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/93#-:-L79ZZbKjDwsJ5mM76WK:bnfp4nl)*

**Pull request merged**
