### PR TITLE
Disable e2e tests for PR updates

### PR DESCRIPTION
**Pull request by niklasberglund**
Don't trigger instrumented e2e tests by PR updates.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018#-:-O9nNV8g19ozhke4qpTD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`.github/workflows/android-app.yml` line 493 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018#-O9oP497DYcfeTOqQZFo:-O9od7drAA0lrytorq4B:b-g4uv32) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c492f26a31ea394ca827844ec9268ba85f7a4588/.github/workflows/android-app.yml#L493)):*
> This if-statement is starting to get a bit complex and would be much nicer if it only had a simple value check, but I guess that could be a future improvement.

Agree, but the `if` condition for the step would also be completely removed when https://linear.app/mullvad/issue/DROID-1433/break-out-workflows-using-reusable-actions is in place.

> One thing I noticed is that the parenthesis probably should be moved to wrap the `e2e_test_repeat` check and `pull_request` check since the latter (`pull_request`) never can be `true` if the left most part (`schedule`) was `true`.

Hmmm I think the `github.event_name == 'schedule'` check could even be removed?

```
github.event.inputs.e2e_test_repeat != '0' && github.event_name != 'pull_request'
```

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`.github/workflows/android-app.yml` line 493 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018#-O9oP497DYcfeTOqQZFo:-O9on8zp-QdgLelr7J9o:bs2qrzc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c492f26a31ea394ca827844ec9268ba85f7a4588/.github/workflows/android-app.yml#L493)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

> This if-statement is starting to get a bit complex and would be much nicer if it only had a simple value check, but I guess that could be a future improvement.

Agree, but the `if` condition for the step would also be completely removed when https://linear.app/mullvad/issue/DROID-1433/break-out-workflows-using-reusable-actions is in place.

> One thing I noticed is that the parenthesis probably should be moved to wrap the `e2e_test_repeat` check and `pull_request` check since the latter (`pull_request`) never can be `true` if the left most part (`schedule`) was `true`.

Hmmm I think the `github.event_name == 'schedule'` check could even be removed?

```
github.event.inputs.e2e_test_repeat != '0' && github.event_name != 'pull_request'
```
</blockquote></details>

I thought so as well first, but wouldn't that combination disable it for nightly jobs since `e2e_test_repeat != '0'` would be `false`?

Regarding the other improvement we can wait until those upcoming issues :thumbsup:

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`.github/workflows/android-app.yml` line 493 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018#-O9oP497DYcfeTOqQZFo:-O9sIHuJ9FZRYEoC6yYX:b7ay490) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c492f26a31ea394ca827844ec9268ba85f7a4588/.github/workflows/android-app.yml#L493)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I thought so as well first, but wouldn't that combination disable it for nightly jobs since `e2e_test_repeat != '0'` would be `false`?

Regarding the other improvement we can wait until those upcoming issues :thumbsup:
</blockquote></details>

Ah yes you're right

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018#-:-O9tC1t_7CRRkfIfC5yl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
