### PR TITLE
Improve animation duration calculation

### PR DESCRIPTION
**Pull request by Rawa**
This PR implements a new algorithm to evaluate the distance between two location that is then used to decide which type of animation we are using.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRLARHA7zHLXxG8uIl:-NtRLARHA7zHLXxG8uIm:bg95ou8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt#L100)):*
> ```Kotlin
> }
> 
> private fun Float.toAnimationDuration() =
> ```

This is just a preference, but since we are doing some kind of conversion from float to int here, could we set the return type explicitly here so that if we do for some reason change this function and the return type becomes int it will show an error immediately?
___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRM-tc9Xw49LltooHB:-NtRM-tc9Xw49LltooHC:b-krgpl7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L4)):*
> ```Kotlin
> 
> import kotlin.math.sqrt
> import kotlin.test.assertTrue
> ```

Use jupiter assertTrue

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRLARHA7zHLXxG8uIl:-NtRQBUQASbwnce68n3Z:b-8p84el) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt#L100)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is just a preference, but since we are doing some kind of conversion from float to int here, could we set the return type explicitly here so that if we do for some reason change this function and the return type becomes int it will show an error immediately?
</blockquote></details>

Good point! I'll add it.
___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRM-tc9Xw49LltooHB:-NtRQDMnCy7Pa2X4ooW8:bgfw283) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L4)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Use jupiter assertTrue
</blockquote></details>

:pray: Thanks!

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtV6dIq2ygaLDANTHj_:-NtV6dIq2ygaLDANTHja:bgsewmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a50f835899c9401f7f611fff2df0eadf599cc1/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt#L100)):*
> ```Kotlin
> }
> 
> private fun Float.toAnimationDuration(): Int =
> ```

I suggest renaming to `toAnimationDurationMillis` to avoid any risk of confusion



_Code quote:_
```Kotlin
toAnimationDuration
```
___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRM-tc9Xw49LltooHB:-NtV7-U8B60Y8zaPo0BS:bokadvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L4)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

:pray: Thanks!
</blockquote></details>

Was this detected by Detekt? Otherwise it might be a good idea to such a rule
___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtV7Z561rysTmSBv8qg:-NtV7Z561rysTmSBv8qh:b-7ilvfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a50f835899c9401f7f611fff2df0eadf599cc1/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L23)):*
> ```Kotlin
> 
>     @Test
>     fun `ensure seppDistance respects lateral value is respected`() {
> ```

typo?



_Code quote:_
```Kotlin
respects lateral value is respected
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRM-tc9Xw49LltooHB:-NtVARNs9yK505zt5kjc:b-ey33ot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Was this detected by Detekt? Otherwise it might be a good idea to such a rule
</blockquote></details>

Unfortunately not :( , I'll add an issue to add a Konsist rule:
https://linear.app/mullvad/issue/DROID-804/add-konsist-rule-to-block-usage-of-kotlintestasserttrue
___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtV7Z561rysTmSBv8qg:-NtVBie80yhGKof8YGhY:b-iz9uyx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a50f835899c9401f7f611fff2df0eadf599cc1/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Yes! Thanks!

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRM-tc9Xw49LltooHB:-NtVcu-J8f-7cEjZCqre:b-bb3892) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L4)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Unfortunately not :( , I'll add an issue to add a Konsist rule:
https://linear.app/mullvad/issue/DROID-804/add-konsist-rule-to-block-usage-of-kotlintestasserttrue
</blockquote></details>

Nice :thumbsup:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-NtRM-tc9Xw49LltooHB:-NtWLGtR7t_S9JkaEPxV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad1a721776b18ea9abd078e2c0b082fe1eb3fcc0/android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nice :thumbsup:
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991#-:-Nt_9RY36wi86gitCJOi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
