### PR TITLE
Fix problem report

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR fixes:

1. Bumps timeout for problem-report tool from 1s to 10s. I have observable delay (up to 4s) before the response arrives
2. Funnels the entire account history into problem-report collection tool.
3. A rewrite of `collectProblemReport` that fixes a memory leak in IPC
4. Renames `.report` logs back to `.log` since macOS does not recognize the `report` extension and unable to determine the right program to open such extension.

@faern  Ping me if you're going to update `CHANGELOG` or me.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/77)

### CODE REVIEW

**Comment by faern** [comment]
Great fixes. I can't really review the JS in detail, but sounds like good stuff.

Regarding the changelog, please add a `## changed` entry in a separate commit explaining that we now redact all account numbers in the history. Because we still need this entry in the master branch changelog. When I cherry pick this to the release I'll ignore that commit and copy the content since it has to go under another header there.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-:-L6M_7H5r2L8tfAtWOJA:bdgeew8)*

**Comment by faern** [comment]
Probably good to also add under `## Fixed` that you fixed a memory leak and that you renamed the file to make it open smoother. Those are the stuff that might affect users.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/77#-:-L6Mf-AO-Ok6_L2gx_A5:bm8ne8z)*

**Comment by faern** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 19 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-L6MnQe5ukrkIuH84an-:-L6MnQe5ukrkIuH84an0:b5002vw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5d9cbd3df3e2e6ed2a4636e510d61b05e360c6c/CHANGELOG.md#L19)):*
> ```Markdown
> 
> ### Changed
> - All account numbers from the account history are now being used to redact logs.
> ```

Maybe add ".. Instead of only the currently used" to make it explicit what it changed *from*.

To make it sound like our other entries it should maybe be formulated as "Redact all account numbers in the account number history from problem reports instead of only the currently logged in one"

---

*[CHANGELOG.md, line 20 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-L6MnHCQ36Nw_BmhXbdv:-L6MnHCRWvBDzZlno-L1:b-w85k7z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5d9cbd3df3e2e6ed2a4636e510d61b05e360c6c/CHANGELOG.md#L20)):*
> ```Markdown
> ### Changed
> - All account numbers from the account history are now being used to redact logs.
> - Increased a timeout for problem report collection to fix a timeout error on slower machines.
> ```

If this was indeed a problem, as it seems to have been, then I would argue it should go under `### Fixed` instead.

---

*[CHANGELOG.md, line 24 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-L6MnjKBeRfBXJLHyKim:-L6MnjKCLb6fILQdJflM:bqz5tda) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5d9cbd3df3e2e6ed2a4636e510d61b05e360c6c/CHANGELOG.md#L24)):*
> ```Markdown
> ### Fixed
> - Fixed a memory leak in the problem report collection routine.
> - Fixed an issue when viewing a problem report brought up a dialog
> ```

If I should be picky we try to stick to the imperative form here, "Fix" instead of "Fixed", just as we do with git commit messages. https://chris.beams.io/posts/git-commit/#imperative

Same goes for "Increased" -> "Increase" in previous bullet.

I know we have previous instances where we have not followed this, but not really an argument to continue :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 19 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/77#-L6MnQe5ukrkIuH84an-:-L6MrxoI8txdPYXshQEU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5d9cbd3df3e2e6ed2a4636e510d61b05e360c6c/CHANGELOG.md#L19)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe add ".. Instead of only the currently used" to make it explicit what it changed *from*.

To make it sound like our other entries it should maybe be formulated as "Redact all account numbers in the account number history from problem reports instead of only the currently logged in one"
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 20 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/77#-L6MnHCQ36Nw_BmhXbdv:-L6MryJl1XlGBYe9REsM:bfb39d2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5d9cbd3df3e2e6ed2a4636e510d61b05e360c6c/CHANGELOG.md#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If this was indeed a problem, as it seems to have been, then I would argue it should go under `### Fixed` instead.
</blockquote></details>

Done. This whole changed vs fixed thing is inherently wrong.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/77)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77)*

**Comment by eriklarko** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/lib/problem-report.js, line 22 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-L6Mv39Ymn_OKZx7By_W:-L6Mv39Z04TpVKukJroa:b7zu5o7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ed2002a9ce896f5e9a6fd9f79ce3597b019fadf/app/lib/problem-report.js#L22)):*
> ```JavaScript
>       log.error(`Timed out when collecting a problem report`);
>       reject(new Error('Timed out'));
>     }, 10000);
> ```

The UI does not indicate that it is working when the problem reports take this long. The previous timeout was set to be low enough to not need a spinner in the UI but still work for real customers, even if we devs might run into the timeout error. I would prefer if this timeout isn't increased without the UI being updated with a spinner too. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77)*

**Comment by eriklarko** [comment]
*[app/lib/problem-report.js, line 22 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-L6Mv39Ymn_OKZx7By_W:-L6MxCSkA9U9Yu19Qkq9:byrlfoy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ed2002a9ce896f5e9a6fd9f79ce3597b019fadf/app/lib/problem-report.js#L22)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

The UI does not indicate that it is working when the problem reports take this long. The previous timeout was set to be low enough to not need a spinner in the UI but still work for real customers, even if we devs might run into the timeout error. I would prefer if this timeout isn't increased without the UI being updated with a spinner too. 
</blockquote></details>

Or wth. Let's deal with that issue when we come to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77)*

**Comment by eriklarko** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77#-:-L6MxL_0atYugKkS2kWm:bnfp4nl)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77)*

**Comment by eriklarko** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/77)*

**Pull request merged**
