### PR TITLE
Add start on boot feature for android TVs

### PR DESCRIPTION
**Pull request by sabercodic**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUPNJDR9ueYibzJ15:-NlOUPNJDR9ueYibzJ16:b-edi58b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt#L15)):*
> ```Kotlin
>     val mtu: String,
>     val isAutoConnectEnabled: Boolean,
>     val isConnectOnBootEnabled: Boolean?,
> ```

Just for clarification, when is it null?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUSr69EYLaAcGhrJp:-NlOUSr69EYLaAcGhrJq:b-u2bqp8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L12)):*
> ```Kotlin
> 
> private const val IS_CONNECT_ON_BOOT_ENABLED_KEY = "is_connect_on_boot_enabled"
> private const val TAG = "AAAAAAAAAAAABootBroadCast"
> ```

Should be removed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOWdAT5qLhem_DLnhT:-NlOWdAT5qLhem_DLnhU:b-ic14lj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L16)):*
> ```Kotlin
> class BootCompletedReceiver : BroadcastReceiver() {
> 
>     override fun onReceive(context: Context?, mBootIntent: Intent?) {
> ```

This is from Java land I believe, is it possible to check if we can assume Context not to be `null`, or inject application context in some way? Kind of weird that we silently don't do anything if we don't have a context. 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUUSx0ve0cwDJgtNa:-NlOUUSx0ve0cwDJgtNb:b81ifj5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L28)):*
> ```Kotlin
>                 } else {
> 
>                     Log.d(TAG, "AAAAA @Boot  isConnectOnBootEnabled is false:")
> ```

Should probably clean up these logs/comments?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUrR49EMtP8oVtEhk:-NlOUrR5Ea5y6OR5yche:btp36iq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L40)):*
> ```Kotlin
>     }
> 
>     private fun toggleTunnel(context: Context) {
> ```

toggle seems like the wrong name because the action is `KEY_CONNECT_ACTION`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUkHb9DxBmKQ_C5FT:-NlOUkHc8AhAlOIDyNW_:bp8ui7k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L47)):*
> ```Kotlin
>             }
> 
>         // Always start as foreground in case tile is out-of-sync.
> ```

Is this comment correct or copy-pasted from MullvadTileService? How are they connect?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOV3Rf3vTi7D2ZT5ng:-NlOV3Rf3vTi7D2ZT5nh:b-3xpzdr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L98)):*
> ```Kotlin
>         SettingsRepository(
>             get(),
>             androidContext().getSharedPreferences(APP_PREFERENCES_NAME, Context.MODE_PRIVATE),
> ```

See we do the same thing above, shouldn't it be possible to create one instance of shared prefs and then directly inject that one?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 87 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOVZb1Ck8DgckD-6Ve:-NlOVZb1Ck8DgckD-6Vf:b-lq6pd3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L87)):*
> ```Kotlin
>     fun setConnectOnBoot(isEnabled: Boolean) {
>         sharedPreferences.edit().putBoolean(IS_CONNECT_ON_BOOT_ENABLED_KEY, isEnabled).apply()
>         isConnectOnBootEnabled.value = isEnabled
> ```

This duplicate storage of value is worth discussing internally. Kind of weird that we don't have a single source of truth. E.g with DataStore we could directly get a flow of the latest value.

**Review by Pururun — COMMENTED** [review]
Would it be possible to use DataStore instead of SharedPreferences? I have used it in a hackney project and it just feels way better. I can show you my implementation if you want.

> Reviewed 12 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-:-NlSEo447-YR6E62xELt:bdlhakd)* status: all files reviewed, 8 unresolved discussions (waiting on @sabercodic)

**Review by sabercodic — COMMENTED** [review]
sure

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-:-NlSf1JjAt_EzdGrXIUo:bb7oryy)* status: all files reviewed, 8 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUPNJDR9ueYibzJ15:-NlSf5vAB2vlSRfD7sDF:bpeb0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt#L15)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Just for clarification, when is it null?
</blockquote></details>

On all the devices except for TVs
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUSr69EYLaAcGhrJp:-NlSfCuAB8JmHAy-cRuD:bt3645t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should be removed?
</blockquote></details>

All will remove before converting to actual PR
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUUSx0ve0cwDJgtNa:-NlStXfY3721jwRu5UYZ:bnj7hl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L28)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should probably clean up these logs/comments?
</blockquote></details>

same as above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUrR49EMtP8oVtEhk:-NlStf6B3no8xoVX5jTT:b-7ql1td) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L40)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

toggle seems like the wrong name because the action is `KEY_CONNECT_ACTION`
</blockquote></details>

fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUkHb9DxBmKQ_C5FT:-NlTBi4z436MjtPjDSMV:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/BootCompletedReceiver.kt#L47)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is this comment correct or copy-pasted from MullvadTileService? How are they connect?
</blockquote></details>

Removed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 87 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOVZb1Ck8DgckD-6Ve:-NlTBT383d7X0RZTnu3f:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L87)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This duplicate storage of value is worth discussing internally. Kind of weird that we don't have a single source of truth. E.g with DataStore we could directly get a flow of the latest value.
</blockquote></details>

Fixed

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566)* status: 11 of 13 files reviewed, 11 unresolved discussions (waiting on @Pururun, @Rawa, and @sabercodic)

___
*[`android/app/src/main/AndroidManifest.xml` line 101 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlXTbMl0nbk070rv0m1:-NlXTbMm6eLFl63RpQfD:b-s9b6q6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be342cf162ef41f05307dc6d2f29755534381bcd/android/app/src/main/AndroidManifest.xml#L101)):*
> ```XML
>                        android:resource="@xml/provider_paths" />
>         </provider>
>         <receiver android:name="net.mullvad.mullvadvpn.compose.util.BootCompletedReceiver"
> ```

The boot receiver is not compose specific so it should be placed in another package.



_Code quote:_
```XML
compose
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 147 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlXUZs63_w84kDwI7au:-NlXUZs79lT7c-2qcMEA:bw3s9lg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be342cf162ef41f05307dc6d2f29755534381bcd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L147)):*
> ```Kotlin
>     onCancelMtuDialogClick: () -> Unit = {},
>     onToggleAutoConnect: (Boolean) -> Unit = {},
>     onToggleConnectOnBoot: (Boolean) -> Unit = {},
> ```

We probably need to discuss how these two interact and work together. For example, will "connect on boot" require the daemon "auto-connect" setting to be enabled?



_Code quote:_
```Kotlin
    onToggleAutoConnect: (Boolean) -> Unit = {},
    onToggleConnectOnBoot: (Boolean) -> Unit = {},
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlOUPNJDR9ueYibzJ15:-NlXTu3iAwapdKXHSzf1:b-8r8qla) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2ca5b0dede55438c9c78665e1e41162b02a228e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt#L15)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

On all the devices except for TVs
</blockquote></details>

Would be nice to wrap it in some well-defined sealed class etc to make that clear
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5566#-NlXUAn166df-gNZYGn1:-NlXUAn166df-gNZYGn2:b-8z7td7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be342cf162ef41f05307dc6d2f29755534381bcd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L33)):*
> ```Kotlin
>     private val serviceConnectionManager: ServiceConnectionManager,
>     private val sharedPreferences: SharedPreferences,
>     packageManager: PackageManager,
> ```

The`SettingsRepository` has hisotrically be used specifically for daemon settings, so we should probably not add `SharedPreferences` and `PackageManager` here.



_Code quote:_
```Kotlin
    private val sharedPreferences: SharedPreferences,
    packageManager: PackageManager,
```

**Comment by albin-mullvad** [comment]
Closing this for now since we need to take some internal decisions around this PR before we can continue the implementation.

**Pull request closed without merging**
