### PR TITLE
Reorganize settings

### PR DESCRIPTION
**Pull request by raksooo**
This pull request reorganizes the settings views into three categories: Interface settings, VPN settings and Support. While doing this I also refactored the settings views into functional components where each setting has its own component which simplifies the code a lot.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 37 of 57 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759)* status: 37 of 57 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/Support.tsx` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759#-N7V4x6cCNbEbZhkAZEF:-N7V4x6cCNbEbZhkAZEG:b-1jy9nh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6bcad544ed213fa68cdf306f4b6d039a294fa70/gui/src/renderer/components/Support.tsx#L54)):*
> ```XML
>                   {
>                     // TRANSLATORS: Title label in navigation bar
>                     messages.pgettext('support-nav', 'Support')
> ```

Seems like a mistake, the context should be `support-view`

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759)* status: 35 of 58 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`gui/src/renderer/components/Support.tsx` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759#-N7V4x6cCNbEbZhkAZEF:-N7VmIHa3egZkEYW91aM:b6ymc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6bcad544ed213fa68cdf306f4b6d039a294fa70/gui/src/renderer/components/Support.tsx#L54)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Seems like a mistake, the context should be `support-view`
</blockquote></details>

I think we do it like that in some views, but I don't get why so I've changed it :) Done.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759#-:-N7VwxOUAAkOgv4H4TAi:bnfp4nl)* status: 37 of 58 files reviewed, all discussions resolved (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3759)* status: 38 of 58 files reviewed, all discussions resolved

**Pull request merged**
