### PR TITLE
Add api level check to request Notification permission

### PR DESCRIPTION
**Pull request by sabercodic**
Fix lint warning related to notification permission minimum api level.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Please use proper formatting in the description (punctuation, capitalization etc). Also, this PR is about fixing the issue rather than suppressing it, right?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-:-NfoJM2z4L3UhDWu0BmO:b1h9ulj)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-NfoJmme96VCbreCS_vz:-NfoJmmf8KomMMtONOuG:b-oyl52e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a00db5fc44a9d4ad86c2ddfd7cd864ffc5f4704d/android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt#L27)):*
> ```Kotlin
>     }
> 
>     fun Context.notificationPermissionIsNotGranted(): Boolean {
> ```

Why do we need to (more or less) duplicate the above function? And can you elaborate on why this fixes the issue. Seems like it might be more of a issue with the lint tool itself.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 355 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nfu2v801Ek_-XjrnlGQ:-Nfu2v801Ek_-XjrnlGR:b-a4yujt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d36ce0668762f2bf7fc02e556c3de2b94ca6e79f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L355)):*
> ```Kotlin
> 
>     private fun checkForNotificationPermission() {
>         if (!isNotificationPermissionGranted().not()) {
> ```

Why is there a double negative (`! .. .not()`)?



_Code quote:_
```Kotlin
!isNotificationPermissionGranted().not()
```

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 3 unresolved discussions (waiting on @sabercodic)

___
*[`android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt` line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh14y-JBTB6D6bV54J4:-Nh14y-KCt7ZScP-CrpD:b-osaavz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90a2b63188f59f8d580b51d7d9b10e5f3b76b8b8/android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt#L28)):*
> ```Kotlin
> 
>     fun getNotificationPermissionResource(): String? {
>         return if ((Build.VERSION.SDK_INT > Build.VERSION_CODES.TIRAMISU)) {
> ```

Redundant parenthesis?

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 355 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nfu2v801Ek_-XjrnlGQ:-NgIbQ8z76IVtAHceVdK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d36ce0668762f2bf7fc02e556c3de2b94ca6e79f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L355)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why is there a double negative (`! .. .not()`)?
</blockquote></details>

Done.
___
*[`android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-NfoJmme96VCbreCS_vz:-NgIbUGv9cMpAs-ZLunf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a00db5fc44a9d4ad86c2ddfd7cd864ffc5f4704d/android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why do we need to (more or less) duplicate the above function? And can you elaborate on why this fixes the issue. Seems like it might be more of a issue with the lint tool itself.
</blockquote></details>

Done.
___
*[`android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt` line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh14y-JBTB6D6bV54J4:-Nh1BBlE6QB1UsGOvC_S:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90a2b63188f59f8d580b51d7d9b10e5f3b76b8b8/android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt#L28)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Redundant parenthesis?
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-Nh2FHYJCGCd6Vj_bw-M:b-5qhtcg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
> ```Kotlin
>     private fun checkForNotificationPermission() {
>         if (isNotificationPermissionGranted().not()) {
>             getNotificationPermissionResource()?.let {
> ```

Looks kind of weird to be that we do the `requestNotificationPermissionLauncher` thingy given that we get a resource. 

I think it would be more clear to just say:
```
if (Build.VERSION.SDK_INT > Build.VERSION_CODES.TIRAMISU) {
    requestNotificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
    
}
```

or maybe it can also be more integrated into isNotificationPermission granted? Because that should also require the same API level?

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nisqjdg0Ub3MeZ5dVFp):*
Please clarify in the commit and PR title what lint issue this fixes. "InlinedApi" doesn't say much.



_Code quote:_
```
Fix InlinedApi lint issue
```

**Review by sabercodic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-:-Nitlnd_CyUaBPdXNTry:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nisqjdg0Ub3MeZ5dVFp):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please clarify in the commit and PR title what lint issue this fixes. "InlinedApi" doesn't say much.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-NitmHsj4GIwYNbSGFyB:b831dix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Looks kind of weird to be that we do the `requestNotificationPermissionLauncher` thingy given that we get a resource. 

I think it would be more clear to just say:
```
if (Build.VERSION.SDK_INT > Build.VERSION_CODES.TIRAMISU) {
    requestNotificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
    
}
```

or maybe it can also be more integrated into isNotificationPermission granted? Because that should also require the same API level?
</blockquote></details>

We try to keep all the sdk check inside SDKUtil, @albin-mullvad what is your idea here?

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa and @sabercodic)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nisqjdg0Ub3MeZ5dVFp):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The PR title is still the same, I asked for both to be updated
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-Nj6eGlx7eVM720wMOjz:b-8he6bj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

We try to keep all the sdk check inside SDKUtil, @albin-mullvad what is your idea here?
</blockquote></details>

After looking a bit at the documentation, I think that we would want to make use of the `ChecksSdkIntAtLeast` annotation (https://developer.android.com/reference/androidx/annotation/ChecksSdkIntAtLeast). I tried it out, but for some reason it doesn't seem to work. Perhaps due to the classes being part of different modules. Here's how it could look: https://github.com/mullvad/mullvadvpn-app/commit/0425a9bb9d0f57b47330eee91a4214b3fe69be33

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nisqjdg0Ub3MeZ5dVFp):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The PR title is still the same, I asked for both to be updated
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-NkLCMos8t9vOYse2H_G:bpyjla4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

After looking a bit at the documentation, I think that we would want to make use of the `ChecksSdkIntAtLeast` annotation (https://developer.android.com/reference/androidx/annotation/ChecksSdkIntAtLeast). I tried it out, but for some reason it doesn't seem to work. Perhaps due to the classes being part of different modules. Here's how it could look: https://github.com/mullvad/mullvadvpn-app/commit/0425a9bb9d0f57b47330eee91a4214b3fe69be33
</blockquote></details>

Is it ok to add new dependencies to basic modules?

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-NlRxXI29kLs3uy45iP3:bx6aj39) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Is it ok to add new dependencies to basic modules?
</blockquote></details>

I don't see why it would be a problem if it is a dependency we need and it seems reliable. What dependency are you thinking about?

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-NlcUjsU0woALr6hMOVf:byuqdvy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I don't see why it would be a problem if it is a dependency we need and it seems reliable. What dependency are you thinking about?
</blockquote></details>

@albin-mullvad I tested this by creating temp util file in app module and it worked fine but when I moved it to other module, as you said it was not working. 

@Rawa I was talking about adding `ChecksSdkIntAtLeast` (androidx.annotation:annotation-jvm) to the 'lib' module

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 357 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-Nh2FHYJCGCd6Vj_bw-L:-NlwQ7GR7ABuUpFOyikN:b8nqe6c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0998e0a1b9f673aec76431c8d4ec9268a480dad3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L357)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

@albin-mullvad I tested this by creating temp util file in app module and it worked fine but when I moved it to other module, as you said it was not working. 

@Rawa I was talking about adding `ChecksSdkIntAtLeast` (androidx.annotation:annotation-jvm) to the 'lib' module
</blockquote></details>

It's completely fine to add that dependency, especially since it's part of androidx. Unfortunate that it doesn't seem to work though. @sabercodic can see if there's a way to make it work?

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r11, 2 of 6 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-:-NnwqhEA5hLtymElZl-q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/lib/common/build.gradle.kts` line 32 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-NnwqEh4CJCAmqMG3-0j:-NnwqEh4CJCAmqMG3-0k:b-8mdjvl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dd07d9ecb2cfeddfe9247b723f742cd3494c1ed/android/lib/common/build.gradle.kts#L32)):*
> ```Kotlin
>     implementation(project(Dependencies.Mullvad.talpidLib))
> 
>     implementation(Dependencies.AndroidX.appcompat)
> ```

We should probably have a discussion/create a meeting in regards to how we want to structure the app and what the different modules should do. But for now I guess this is fine.

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/common/build.gradle.kts` line 32 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5221#-NnwqEh4CJCAmqMG3-0j:-Nnx-mQz54VZR5v4eMVG:bowzb5p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dd07d9ecb2cfeddfe9247b723f742cd3494c1ed/android/lib/common/build.gradle.kts#L32)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

We should probably have a discussion/create a meeting in regards to how we want to structure the app and what the different modules should do. But for now I guess this is fine.
</blockquote></details>

Yes, will do that!

**Pull request merged**
