### PR TITLE
Fix the dpad navigation & dialog styles

### PR DESCRIPTION
**Pull request by Rawa**
- Fixes DPAD navigation in dialogs
 - Aligns dialog designs to use Alert Dialog
 - Introduces mullvadDarkTextFieldColors
 - Fixes textfield width on wide devices

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5307)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
Tested it and it works much better. However when I try with dpad on an emulator there is inconsistent behaviour when comparing the input field of redeem voucher and all other dialogues. Is this intended and can you see this different behaviour on the TV?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5307#-:-Nh0b57p7c5hKldVMQEM:b-xui0ck)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
A great remark, there was a box surrounding the RedeemVoucherDialog, does it work better now? :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5307#-:-Nh1cicg4BeoFNIb3OTu:b3llhdy)* status: 1 of 10 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
Works great. :)
:lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5307#-:-NhCToCoBM8HvKSACiOU:b-9t7u0b)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5307)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
