### PR TITLE
Colouring StatusBar and NavigationBar

### PR DESCRIPTION
**Pull request by axti**
On this PR we colouring StatusBar based on connection status and on which fragment we are. Also, we colouring NavigationBar on some certain fragments to match the background colour.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521)* status: all files reviewed, 8 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, line 134 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUhyVtK9N91SiLFc5_0:-MUhyVtLEwJz1K_wqQU0:bpv8tx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt#L134)):*
> ```Kotlin
>     }
> 
>     override fun onResume() {
> ```

Nit: I usually order the lifecycle methods in the execution order (i.e., `onCreate`, `onStart`, `onResume`, `onPause`, `onStop`, `onDestroy`) to make it easier to find them.

We don't have to follow the rule every time, but do you think it might be a good idea to put the `onResume` between the `onSafelyStart` and the `onSafelyStop` so it's easier to find?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt, line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi15iZ70oDV3he7kgx:-MUi15iZ70oDV3he7kgy:bwhk6c9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt#L137)):*
> ```Kotlin
>     }
> 
>     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
> ```

Nit: Same comment as in the `ConnectFragment`. Would it make sense to move this to be between `onSafelyCreateView` and `onSafelyStart` and move `onResume` to be between `onSafelyStart` and `onSafelyStop`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi3pRz7my6CEIWfY7f:-MUi3pRz7my6CEIWfY7g:bgyiohi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L79)):*
> ```Kotlin
>     }
> 
>     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
> ```

I don't understand why this is needed if `onResume` does the same thing.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 88 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi1kbW4TW4mwgPROUv:-MUi1kbXBCooYocO5zXK:biiskfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L88)):*
> ```Kotlin
>     }
> 
>     override fun onResume() {
> ```

Nit: Same comment as in the `ConnectFragment` file, would it make sense to move the `onResume` so that it's between `onStart` and `onStop`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/StatusBarPainter.kt, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi-b5wAGKKg8htcgCp:-MUi-b5wAGKKg8htcgCq:bk5h9lw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/StatusBarPainter.kt#L9)):*
> ```Kotlin
> 
> fun StatusBarPainter.paintStatusBar(@ColorInt color: Int) {
>     (getContext() as Activity?)?.window?.statusBarColor = color
> ```

Just an idea: would it make sense to replace the extension method with a property in the interface? That means we wouldn't have to import the method together with the interface.

Not sure if this is 100% correct, but something like:

```
interface StatusBarPainter : SystemPainter {
    @ColorInt
    var statusBarColor: Int?
        get() = window?.statusBarColor
        set(color: Int) { window?.statusBarColor = color } 
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt, line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUhzldjCyRyk95J32sO:-MUhzldjCyRyk95J32sP:b-2t90bw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt#L6)):*
> ```Kotlin
> 
> interface SystemPainter {
>     fun getContext(): Context?
> ```

Just so that I understand. This method was added because `Activity` already have this method implemented?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi--t_D4qcnGzcRUyt:-MUi--ta7efb27cRTvWX:bsstnsz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt#L7)):*
> ```Kotlin
> interface SystemPainter {
>     fun getContext(): Context?
> }
> ```

Just an idea: would it make sense to add a property to the interface that already returns the window? Something like:

```
val activity: Activity?
    get() = (getContext() as Activity?)?.window
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi0L9j9xC5_QOMs27T:-MUi0L9j9xC5_QOMs27U:b7xx169) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt#L23)):*
> ```Kotlin
>     defStyleRes: Int = 0
> ) : LinearLayout(context, attributes, defStyleAttr, defStyleRes), StatusBarPainter {
>     private val container = LayoutInflater.from(context).inflate(R.layout.header_bar, this)
> ```

Nice! This makes it a lot simpler :D
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt, line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi0fTG4YEBVfp7wPni:-MUi0fTG4YEBVfp7wPnj:b7id3lq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt#L59)):*
> ```Kotlin
> 
>     override fun onDetachedFromWindow() {
>         findViewById<View>(R.id.settings)?.setOnClickListener(null)
> ```

I don't understand why this is needed :/

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521)* status: 17 of 18 files reviewed, 8 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, line 134 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUhyVtK9N91SiLFc5_0:-MUiDAbK0_-BMt743-es:bc74mc0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt#L134)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: I usually order the lifecycle methods in the execution order (i.e., `onCreate`, `onStart`, `onResume`, `onPause`, `onStop`, `onDestroy`) to make it easier to find them.

We don't have to follow the rule every time, but do you think it might be a good idea to put the `onResume` between the `onSafelyStart` and the `onSafelyStop` so it's easier to find?
</blockquote></details>

So if we agreed on this rule then we have to move `onSafelySaveInstanceState` before `onSafelyDestroyView` because it is called before. I put it below because I have seen block of overridden methods and just append. 
I would say let's reorder it in separate PR, what do you think?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi3pRz7my6CEIWfY7f:-MUiEFsW5UaglzHXlcq5:b-p8x0b7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L79)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I don't understand why this is needed if `onResume` does the same thing.
</blockquote></details>

No it is different. When fragment onResume we colouring navBar and fragment animated from the bottom to the top, and at the end of animation we colouring statusBar. 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/StatusBarPainter.kt, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi-b5wAGKKg8htcgCp:-MUiEot811XUqcjkdnre:bcfckvu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/StatusBarPainter.kt#L9)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Just an idea: would it make sense to replace the extension method with a property in the interface? That means we wouldn't have to import the method together with the interface.

Not sure if this is 100% correct, but something like:

```
interface StatusBarPainter : SystemPainter {
    @ColorInt
    var statusBarColor: Int?
        get() = window?.statusBarColor
        set(color: Int) { window?.statusBarColor = color } 
}
```
</blockquote></details>

This is just a painting method that used as a shortcut and yes, it looks like and extension. 
Second point is that on interface you able to override, but I don't want to give this possibility.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt, line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUhzldjCyRyk95J32sO:-MUiFDeQ8Nk98l9QuHBt:b69rh02) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt#L6)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Just so that I understand. This method was added because `Activity` already have this method implemented?
</blockquote></details>

yes, it is shadowed method. And not only `Activity`. Also, `Fragment` and `View` has it.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi--t_D4qcnGzcRUyt:-MUiFqVY3bAF89jYcqcj:b-c1kqae) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Just an idea: would it make sense to add a property to the interface that already returns the window? Something like:

```
val activity: Activity?
    get() = (getContext() as Activity?)?.window
```
</blockquote></details>

If we do this, then it is require your interface implementation. I think it is kind of limitations. Because in java interface has only methods.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt, line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi0fTG4YEBVfp7wPni:-MUiNFRbCyEwEsdrRhjG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt#L59)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I don't understand why this is needed :/
</blockquote></details>

Done.

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521)* status: all files reviewed, 4 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, line 134 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUhyVtK9N91SiLFc5_0:-MUj-7Ck5PNC0_Iq0BJY:bfj0584) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt#L134)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

So if we agreed on this rule then we have to move `onSafelySaveInstanceState` before `onSafelyDestroyView` because it is called before. I put it below because I have seen block of overridden methods and just append. 
I would say let's reorder it in separate PR, what do you think?
</blockquote></details>

Sounds good! Yeah, the `onSafelySaveInstanceState` not being in the correct location is likely a mistake on my part. We can fix and check everything later :+1:
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi3pRz7my6CEIWfY7f:-MUizhIh2TwLq_B7d9Ub:b-yskj2z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L79)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

No it is different. When fragment onResume we colouring navBar and fragment animated from the bottom to the top, and at the end of animation we colouring statusBar. 
</blockquote></details>

Ah! That makes sense! But wouldn't it make sense to move this method's body into `onResume` as well? I mean, shouldn't this run every time `onResume` is called?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi--t_D4qcnGzcRUyt:-MUizB4xAKb1bi2dzcGl:bjx3vj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt#L7)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

If we do this, then it is require your interface implementation. I think it is kind of limitations. Because in java interface has only methods.
</blockquote></details>

But doesn't that just map to Java methods with default implementations? Because Kotlin doesn't allow properties in interfaces to have backing fields (which I assumed is because it's impossible to map data to a Java interface, but the getter and setter can be mapped to Java methods with default implementations).

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi3pRz7my6CEIWfY7f:-MUj98LE0pc_O5Hv995b:b-9ejcv4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L79)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Ah! That makes sense! But wouldn't it make sense to move this method's body into `onResume` as well? I mean, shouldn't this run every time `onResume` is called?
</blockquote></details>

`Launches and runs the given block when the Lifecycle controlling this LifecycleCoroutineScope is at least in Lifecycle.State.RESUMED state.`

`The returned Job will be cancelled when the Lifecycle is destroyed.`

https://developer.android.com/reference/kotlin/androidx/lifecycle/LifecycleCoroutineScope#launchWhenResumed(kotlin.coroutines.SuspendFunction1)

So, is suppose to run once. And second transitionFinishedFlow will emit only **one** item and closed.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi--t_D4qcnGzcRUyt:-MUjALHW2PT7ubvaxxCF:bvmzup9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

But doesn't that just map to Java methods with default implementations? Because Kotlin doesn't allow properties in interfaces to have backing fields (which I assumed is because it's impossible to map data to a Java interface, but the getter and setter can be mapped to Java methods with default implementations).
</blockquote></details>

Yes, it has default implementation on Java, but on Kotlin it behave differently. I checked your proposal.

**Review by jvff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521)* status: all files reviewed, 3 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi3pRz7my6CEIWfY7f:-MUjH0k80vMlzqfTnLAa:b-vbdcv7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L79)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

`Launches and runs the given block when the Lifecycle controlling this LifecycleCoroutineScope is at least in Lifecycle.State.RESUMED state.`

`The returned Job will be cancelled when the Lifecycle is destroyed.`

https://developer.android.com/reference/kotlin/androidx/lifecycle/LifecycleCoroutineScope#launchWhenResumed(kotlin.coroutines.SuspendFunction1)

So, is suppose to run once. And second transitionFinishedFlow will emit only **one** item and closed.
</blockquote></details>

Right, and shouldn't it run every time the fragment is resumed? :thinking:

**Review by jvff — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-:-MUjNRWX192Y-ozLOg1G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521#-MUi3pRz7my6CEIWfY7f:-MUjNFz3DIi7h_I7DNnw:bmr5f6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a6c292d6b0b3dda325865f5218896d6dfaa26c5/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L79)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Right, and shouldn't it run every time the fragment is resumed? :thinking: 
</blockquote></details>

As we discussed on private chat, we don't need to run it every time the fragment resumes because the value is automatically saved.

**Pull request merged**
