### PR TITLE
Use rustfmt preview component

### PR DESCRIPTION
**Pull request by faern**
Trying out using the new precompiled rustup component release of rustfmt.

I removed the entire `format.sh` script now. It's so easy to just install rustfmt via rustup anyway and just run it with `cargo fmt`. And the fairly new setting `required_version = "0.3.8"` will make sure developers don't accidentally format with something old.. I hope. I have not fully understood all aspects of how this works, but that is the plan.

I can't guarantee this is the correct way to go already. But it builds way faster at least. We have to test to know, and if it causes trouble we can just revert to the old method.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/63)

### CODE REVIEW

**Comment by faern** [comment]
Since we don't install a specific, hardcoded, rustfmt version any longer I think `rustup component add rustfmt-preview` will automatically install the latest one at all times. Thus we will get automatic updates. That means PRs will start failing as soon as there is a new version that requires some re-formatting. If that works, that would be awesome, one type of manual upgrade PRs less to worry about.

We likely have to bump the minimum require version in `rustfmt.toml` at times, but not for every release really.

**Comment by faern** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 35 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5SjVYbAbNnzElJXBQu:-L5SjVYcQBiTfrzLTXe8:b-xwf2kr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a577bd314ef9e51d140fb99ba928f4f338618bb/.travis.yml#L35)):*
> ```YAML
> 
> 
>     # Daemon - macOS
> ```

Reworded. @pronebird and I had a discussion about BE/FE being bad names for the two components for a number of reasons. I'm not sure what we should call the FE, but the BE can naturally be called the daemon. This will stop it being ambiguous with the "backend" in the FE and with the "backend" meaning our API server.

We surely have the BE/FE terms spread out in more places. But this PR is not mainly about doing that renaming, it's just that these two instances were close at hand now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by faern** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 42 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5Sm_rI3eHofAbeCuUo:-L5Sm_rI3eHofAbeCuUp:b-xh7pwx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6d4b3a2370fa6feeaaf33f0425127753e93039e/.travis.yml#L42)):*
> ```YAML
> 
>       before_script: &rust_before_script
>         - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
> ```

Checking the output of `env` on a build made me realize these paths are already in `PATH` by default now. So this manual edit was just some legacy thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by pronebird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 35 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5SjVYbAbNnzElJXBQu:-L5T1VHcB7gvDFKWMaQs:b-8axuqe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a577bd314ef9e51d140fb99ba928f4f338618bb/.travis.yml#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Reworded. @pronebird and I had a discussion about BE/FE being bad names for the two components for a number of reasons. I'm not sure what we should call the FE, but the BE can naturally be called the daemon. This will stop it being ambiguous with the "backend" in the FE and with the "backend" meaning our API server.

We surely have the BE/FE terms spread out in more places. But this PR is not mainly about doing that renaming, it's just that these two instances were close at hand now.
</blockquote></details>

Maybe call it "the app" since it's user facing..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by pronebird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 43 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5T1fTXjMyJfmuWDZG3:-L5T1fTXjMyJfmuWDZG4:brlel37) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6d4b3a2370fa6feeaaf33f0425127753e93039e/.travis.yml#L43)):*
> ```YAML
>       before_script: &rust_before_script
>         - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
>         - env
> ```

What's the use of running `env`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by pronebird** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 35 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/63#-L5SjVYbAbNnzElJXBQu:-L5T6nyKDk1ZcaaYxu6f:bh9mfj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a577bd314ef9e51d140fb99ba928f4f338618bb/.travis.yml#L35)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Maybe call it "the app" since it's user facing..
</blockquote></details>

or electron app 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/63)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 35 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5SjVYbAbNnzElJXBQu:-L5TNqvRlbYKTrAxZtvw:b-smmnzb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a577bd314ef9e51d140fb99ba928f4f338618bb/.travis.yml#L35)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

or electron app 
</blockquote></details>

I prefer if we use "app" do describe the entire product. That is what we have done so far in all marketing.
Can't we just call it the gui? The daemon, the gui and the cli, seems like three component names that fit well together.

---

*[.travis.yml, line 43 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5T1fTXjMyJfmuWDZG3:-L5TOE8LYTUweZdMWECl:b-op3zgp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6d4b3a2370fa6feeaaf33f0425127753e93039e/.travis.yml#L43)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

What's the use of running `env`?
</blockquote></details>

Just debugging. When something goes wrong it's nice to be able to inspect the entire environment in the build log. That's for example what allowed me to find `export PATH=...` was superfluous :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 35 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5SjVYbAbNnzElJXBQu:-L5TOdPopf9UrB4At_qz:b-2j79bv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a577bd314ef9e51d140fb99ba928f4f338618bb/.travis.yml#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I prefer if we use "app" do describe the entire product. That is what we have done so far in all marketing.
Can't we just call it the gui? The daemon, the gui and the cli, seems like three component names that fit well together.
</blockquote></details>

We don't have to make this a super long discussion here and now. It's definitely not in scope for this PR as long as we agree to rename BE to daemon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 43 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5T1fTXjMyJfmuWDZG3:-L5TP-rWa9YIiGUl_0nV:b-pdl3cm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6d4b3a2370fa6feeaaf33f0425127753e93039e/.travis.yml#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Just debugging. When something goes wrong it's nice to be able to inspect the entire environment in the build log. That's for example what allowed me to find `export PATH=...` was superfluous :)
</blockquote></details>

Now when `before_script` is virtually empty we could move `- env` to `script` and simplify this config a bit. But there might just as well be new `before_script` steps later so does not feel very needed IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 35 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-L5SjVYbAbNnzElJXBQu:-L5TQJPU5D_vDsruiV9h:bpidq13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a577bd314ef9e51d140fb99ba928f4f338618bb/.travis.yml#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We don't have to make this a super long discussion here and now. It's definitely not in scope for this PR as long as we agree to rename BE to daemon.
</blockquote></details>

the GUI itself stands for graphical user interface, but the electron app we have does more than that. I don't want to have a lengthy discussion about it either so whatever works for you I'll adapt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63)*

**Comment by pronebird** [comment]
Works and compiles on Windows 7 32-bit. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-:-L5TQyM46lVzSFwqpiJk:b-ninrao)*

**Comment by faern** [comment]
I still don't want it to break on appveyor. I'll wait over the weekend and see if it fixes itself, otherwise I'll dig into the compile error. Need to wait for Erik's approval of the PR anyway.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-:-L5T_jAIMGgjCvyJHpRf:b6evvkv)*

**Comment by faern** [comment]
I have now experienced the same compiler crash on Linux. But it happens randomly, I can't reproduce it deterministically. Anyway, now appveyor builds successfully so if this becomes accepted I will merge.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-:-L5YFFOVdKu-Lmiqx8Hg:bxjjjbr)*

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/63#-:-L5erDrCiu-Y_B79MlNp:bnfp4nl)*

**Pull request merged**
