### PR TITLE
Upgrade mockk version to 1.13.8

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5409)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5409#-:-NioB_-81cNIQ5JcfEf_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5409)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5409#-:-NioCq0D7hv5WRn5oyts:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5409#-:-NisAtYR3veqSg8ZYknn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
