### PR TITLE
Add YAML linting to CI

### PR DESCRIPTION
**Pull request by faern**
We have extremely mixed indentation in our YAML files. And even if I go and manually fix it all, we will introduce new inconsistencies in the future. So experimenting with having a linter tell us when we do something bad!

You can see the output here if you are interested in what it complains about (mostly invalid indentation): https://github.com/mullvad/mullvadvpn-app/actions/runs/3903309451/jobs/6667502188

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)

### CODE REVIEW

**Comment by albin-mullvad** [comment]
Sounds like a good improvement :+1:

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[`.yamllint` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274#-NLaZbSk9z-WMlD4gLzf:-NLaZbSk9z-WMlD4gLzg:b-1sy5x9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/780c9203912d1efc07c81865d949b663a09b11d2/.yamllint#L6)):*
> ```
> rules:
>   line-length:
>     max: 120
> ```

We simply had too many lines that were too long. So I did not bother trying to split them right now. If we think 120 is too wide, we have to figure out how to nicely split those.
___
*[`.yamllint` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274#-NLaZjPyE4-tiU_y-l4w:-NLaZjPyE4-tiU_y-l4x:bsek76s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/780c9203912d1efc07c81865d949b663a09b11d2/.yamllint#L8)):*
> ```
>     max: 120
>   indentation:
>     spaces: 2
> ```

I went with 2 both since it's a slight personal preference of mine, and it was leading the slack poll (for a while at least) and lastly, it will trip up the `line-length` lint less.

`yamllint` itself does not seem to have an opinionated default. It accepts whatever indentation amount as long as each file is **consistent**. But I feel like we can do better than being consistent in individual files. That makes it easier to copy paste between files.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`.github/workflows/rust-unused-dependencies.yml` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274#-NLeR_181aQdDzQ8F104:-NLeR_181aQdDzQ8F105:bweihd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8696caeda76ed70d42083f93c8adaaee4813412/.github/workflows/rust-unused-dependencies.yml#L35)):*
> ```YAML
>     runs-on: ubuntu-latest
>     container:
>       image: ${{ needs.prepare-linux.outputs.container_image }}
> ```

:thinking: 



_Code quote:_
```YAML
    cargo-udeps-linux:
      needs: prepare-containers
      runs-on: ubuntu-latest
      container:
        image: ${{ needs.prepare-containers.outputs.container_image_linux }}

  cargo-udeps-linux:
    needs: prepare-linux
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.prepare-linux.outputs.container_image }}
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`.github/workflows/rust-unused-dependencies.yml` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274#-NLeR_181aQdDzQ8F104:-NLeW5MR18eiEi5jEI8p:bgbhr14) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8696caeda76ed70d42083f93c8adaaee4813412/.github/workflows/rust-unused-dependencies.yml#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

:thinking: 
</blockquote></details>

Ooops! Git merge conflict fuckup on my end. I did not catch it since when the yaml became invalid the CI job simply did not run :cry:

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`.github/workflows/rust-unused-dependencies.yml` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274#-NLeR_181aQdDzQ8F104:-NLeX-H62sa3xO7W7AS-:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8696caeda76ed70d42083f93c8adaaee4813412/.github/workflows/rust-unused-dependencies.yml#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ooops! Git merge conflict fuckup on my end. I did not catch it since when the yaml became invalid the CI job simply did not run :cry: 
</blockquote></details>

Done!

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274#-:-NLeXqlEC1D4w8TjXyMK:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Review by albin-mullvad — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
