### PR TITLE
Fix inability to set location constraint to 'any'

### PR DESCRIPTION
**Pull request by dlon**
This also removes the `RelaySettingsUpdate` type.

Fix DES-432.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 8 of 36 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376)* status: 14 of 42 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`gui/src/main/daemon-rpc.ts` line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlRyst48rc6MVZKZbH:-NhlRyst48rc6MVZKZbI:bdfjvq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/gui/src/main/daemon-rpc.ts#L301)):*
> ```XML
> 
>   // TODO: Custom tunnel configurations are not supported by the GUI.
>   public async updateRelaySettings(relaySettings: RelaySettings): Promise<void> {
> ```

This should also be changed to `setRelaySettings`.
___
*[`gui/src/renderer/components/select-location/select-location-hooks.ts` line 76 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlSm1X4rfhgBaG45Ky:-NhlSm1Y0eS8zKeca0V8:b-1du49n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/gui/src/renderer/components/select-location/select-location-hooks.ts#L76)):*
> ```XML
> 
> function useOnSelectLocation() {
>   const { setRelaySettings: updateRelaySettings } = useAppContext();
> ```

I must have missed this one. It should just be `{ setRelaySettings }` and then the usage needs to be updated as well.

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 27 of 36 files at r1, 6 of 6 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/tests/tunnel.rs` line 244 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlXwbz2Oy2jtQP2WnM:-NhlXwbz2Oy2jtQP2WnN:b-ievigx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/tunnel.rs#L244)):*
> ```XML
> 
>     let relay_settings = RelaySettings::Normal(RelayConstraints {
>         location: helpers::into_constraint(&exit).unwrap(),
> ```

When would this `unwrap` cause a panic? If there is no suitable exit-relay? Could we swap out the `unwrap` for `expect` and explicit error message?:)



_Code quote:_
```XML
.unwrap()
```
___
*[`test/test-manager/src/tests/tunnel.rs` line 314 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlYFGQ2PhhiuAdk6RZ:-NhlYFGQ2PhhiuAdk6R_:bb7eybp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/tunnel.rs#L314)):*
> ```XML
>     };
>     let (entry, exit) = helpers::random_entry_and_exit(&mut mullvad_client, relay_filter).await?;
>     let exit_constraint = helpers::into_constraint(&exit).unwrap();
> ```

dito



_Code quote:_
```XML
unwrap()
```
___
*[`test/test-manager/src/tests/tunnel.rs` line 317 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlYGX-87fX4QZcM4b0:-NhlYGX-87fX4QZcM4b1:bb7eybp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/tunnel.rs#L317)):*
> ```XML
>     let wireguard_constraints = WireguardConstraints {
>         use_multihop: true,
>         entry_location: helpers::into_constraint(&entry).unwrap(),
> ```

dito



_Code quote:_
```XML
.unwrap
```
___
*[`test/test-manager/src/tests/ui.rs` line 99 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlYUCtBL6RPZWsqXdI:-NhlYUCtBL6RPZWsqXdJ:bb7eybp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/ui.rs#L99)):*
> ```XML
>     // The test expects us to be disconnected and logged in but to have a specific relay selected
>     let relay_settings = RelaySettings::Normal(RelayConstraints {
>         location: helpers::into_constraint(&entry).unwrap(),
> ```

dito



_Code quote:_
```XML
unwrap()
```

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhznzyEAyE6Ng9xkoMw:-NhznzyEAyE6Ng9xkoMx:b-t0fzuj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt#L92)):*
> ```Kotlin
>         val currentRelayConstraints = getCurrentRelayConstraints()
> 
>         // TODO Fix so that we do not send null from the app when we want to set location constraint
> ```

This TODO is no longer valid. It is no longer possible to send null from the app.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376)* status: 21 of 44 files reviewed, 7 unresolved discussions (waiting on @MarkusPettersson98, @Pururun, and @raksooo)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhznzyEAyE6Ng9xkoMw:-Ni1dCGU-h6G9Q5hgKHM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt#L92)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This TODO is no longer valid. It is no longer possible to send null from the app.
</blockquote></details>

Done.
___
*[`gui/src/main/daemon-rpc.ts` line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlRyst48rc6MVZKZbH:-Ni1dD3N5N-ucwK4HRRq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/gui/src/main/daemon-rpc.ts#L301)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This should also be changed to `setRelaySettings`.
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/select-location/select-location-hooks.ts` line 76 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlSm1X4rfhgBaG45Ky:-Ni1dGFh7WRuCRJzpigB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/gui/src/renderer/components/select-location/select-location-hooks.ts#L76)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I must have missed this one. It should just be `{ setRelaySettings }` and then the usage needs to be updated as well.
</blockquote></details>

Done.
___
*[`test/test-manager/src/tests/tunnel.rs` line 244 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlXwbz2Oy2jtQP2WnM:-Ni1dHuw1V-MVaICS0AJ:b35vzo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/tunnel.rs#L244)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

When would this `unwrap` cause a panic? If there is no suitable exit-relay? Could we swap out the `unwrap` for `expect` and explicit error message?:)
</blockquote></details>

Done. This value should always be present.
___
*[`test/test-manager/src/tests/tunnel.rs` line 314 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlYFGQ2PhhiuAdk6RZ:-Ni1dKBn5DX-N9GuxvuW:b35vzo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/tunnel.rs#L314)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done. This value should always be present.
___
*[`test/test-manager/src/tests/tunnel.rs` line 317 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlYGX-87fX4QZcM4b0:-Ni1dKvsEbYXSOVr-rTP:b35vzo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/tunnel.rs#L317)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done. This value should always be present.
___
*[`test/test-manager/src/tests/ui.rs` line 99 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-NhlYUCtBL6RPZWsqXdI:-Ni1dMOT2Nnqc-sG6293:b35vzo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/071a0a6ca149b431007ba591e80efd8e049a3f28/test/test-manager/src/tests/ui.rs#L99)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done. This value should always be present.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 20 files at r4, 7 of 7 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-:-Ni3myFK8t7fHAwFGi6D:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun and @raksooo)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5376#-:-Ni4nSTo32zyp6G0cKoH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
