### PR TITLE
Add escape hatch

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds an escape hatch which navigates back to the main view when escape is pressed.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)

### CODE REVIEW

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: 0 of 9 files reviewed, 1 unresolved discussion

___
*[gui/src/renderer/transitions.ts, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKBhUpN6JeO1OZtuXV7:-MKBhUpOAUIixN2xqzY0:bmqpcoj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/transitions.ts#L51)):*
> ```XML
>   r('/settings', '/settings/support', transitions.push),
>   r(/.*/, /\/settings.*/, transitions.slide),
>   r(/.*/, '/select-location', transitions.slide),
> ```

I tried a few different ways to allow animating from everything in settings back to the main view and finally came to this solution with allowing regular expressions for the paths. The only negative aspect that I see is that all subviews in settings need to have a path beginning with `/settings/`.

Another solution could be to allow `to` to be `null` as well but that has some unwanted effects such as that the app would animate between `/connect` and `/` with a slide animation.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 5 unresolved discussions (waiting on @raksooo)

___
*[CHANGELOG.md, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKE_1Zy6WmgLlK1vdcB:-MKE_1Zy6WmgLlK1vdcC:b-jbem7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/CHANGELOG.md#L30)):*
> ```Markdown
> - Add `--wait` flag to `connect`, `disconnect` and `reconnect` CLI subcommands to make the CLI wait
>   for the target state to be reached before exiting.
> - Add escape hatch that navigates back to the main view when escape is pressed in the desktop app.
> ```

Buzzwords in changelog. It would be much simpler to say that pressing Escape takes user to the main view.
___
*[gui/src/renderer/transitions.ts, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKBhUpN6JeO1OZtuXV7:-MKEPrFhEpWKiajMWiA_:bi2tbvj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/transitions.ts#L51)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I tried a few different ways to allow animating from everything in settings back to the main view and finally came to this solution with allowing regular expressions for the paths. The only negative aspect that I see is that all subviews in settings need to have a path beginning with `/settings/`.

Another solution could be to allow `to` to be `null` as well but that has some unwanted effects such as that the app would animate between `/connect` and `/` with a slide animation.
</blockquote></details>

This is not really needed in my opinion, as we never go from anywhere to sub-path under `/settings`.
___
*[gui/src/renderer/components/EscapeHatch.tsx, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKET0p78e48XHpIPLqp:-MKET0p78e48XHpIPLqq:b-eqd4mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L10)):*
> ```XML
> }
> 
> export default function EscapeHatchT(props: IEscapeHatchProps) {
> ```

FYI I see where the name comes from, but really, why not `KeyboardNavigation`? This is all what it is, it's plain simple.
___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-MKETQtm72gYIsuM0gWF:b-h79n6j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
> ```XML
>           history.push('/');
>         } else if (loggedIn) {
>           history.push('/connect');
> ```

Here is where you have to be careful. The way it's organised, when you push an item to history, you make it possible to come back to the preceding item. `NavigationBar` back buttons & close button (indirectly) use `history.goBack()`.

Look at `app.tsx`. `memoryHistory.replace()` is used exclusively when navigating to things like `/` or `/login`. There is no path from `/connect` to `/login`. The `/login` page is only accessibly programatically and there is no way to go forward from `/login` page t `/connect` once you logged out.

What I would do instead is `history.goBack(-n)` where `n` is the number of components that we have to pop before coming back to `/connect`, `/login` or `/`, whatever. It may not work flawlessly when trying to pop from the sub-page under `/settings/<sub_page>` but then you'd have to see what the history listener gives to `TransitionContainer` & perhaps either let it queue up the transitions or skip the sub-transitions.

The simplest solution would be to pop one item off history entries if `history.length > 1`, this way you would have more generic solution.

Also it's worth to note that while browser's history does not expose `history.entries`, we use `MemoryHistory` which in fact does, but it's a private API, however you may find some use of it if needed.
___
*[gui/src/renderer/components/Modal.tsx, line 224 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKEZHqiC0UY2xD7HODv:-MKEZHqiC0UY2xD7HODw:b-8w78kb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/Modal.tsx#L224)):*
> ```XML
>   private handleKeyPress = (event: KeyboardEvent) => {
>     if (event.key === 'Escape') {
>       event.stopPropagation();
> ```

FYI one reason why we might consider upgrading modals to the routes to be able to participate in container transitions. But that's something for the future perhaps.
___
*[gui/src/renderer/lib/transition-rule.ts, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKEZgBZCWk7Dslf3Mt8:-MKEZgBZCWk7Dslf3Mt9:b-yczq7i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/lib/transition-rule.ts#L21)):*
> ```XML
> 
>   constructor(from: string | RegExp, to: string | RegExp, private fork: ITransitionFork) {
>     this.from = typeof from === 'string' ? new RegExp(from) : from;
> ```

A dangerous game of wrapping any random string into `RegExp`. What can go wrong?
___
*[gui/src/renderer/redux/userinterface/reducers.ts, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKEbDhT1z_9elxk8GHI:-MKEbDhU75JWD1DJwrH3:b-2rv87n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/redux/userinterface/reducers.ts#L15)):*
> ```XML
>   windowFocused: boolean;
>   scrollPosition: Record<string, [number, number]>;
>   connectedToDaemon: boolean;
> ```

Not needed as the `EscapeHutch` should be able to navigation without much structural knowledge of the app.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/transitions.ts, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKBhUpN6JeO1OZtuXV7:-MKEig8fEpu8tQ52sGBE:bmukhmc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/transitions.ts#L51)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is not really needed in my opinion, as we never go from anywhere to sub-path under `/settings`.
</blockquote></details>

We will probably need to go from a subpath under `/settings` to `/`/`/login`/`/connect`
___
*[gui/src/renderer/components/EscapeHatch.tsx, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKET0p78e48XHpIPLqp:-MKEgN0F-Od1I921aYl-:b-34eurc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L10)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I see where the name comes from, but really, why not `KeyboardNavigation`? This is all what it is, it's plain simple.
</blockquote></details>

I thought the name was more widely used for this type of feature, just did a search and only found a few pages using this naming. I'm fine with `KeyboardNavigation` :+1:
___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-MKEgx758-MbQ5IeRlkM:bz36b42) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
I first tried this using `entries` but figured I had to do it some other way since it's not public on `history`. Nice to know that it's public on `memoryHistory`! How do you suggest using `memoryHistory`? Passing it as a prop? Or just casting `history` to `memoryHistory`? I agree that `history.go(-n)` would be a way better solution.

> The simplest solution would be to pop one item off history entries if history.length > 1, this way you would have more generic solution.

Could you elaborate? I don't understand what you're suggesting.
___
*[gui/src/renderer/components/Modal.tsx, line 224 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKEZHqiC0UY2xD7HODv:-MKEgmFj-bAPAbrkVckq:b-ebtrgl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/Modal.tsx#L224)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI one reason why we might consider upgrading modals to the routes to be able to participate in container transitions. But that's something for the future perhaps.
</blockquote></details>

What do you mean with "be able to participate in container transitions"?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-MKEnCWD-Ej8iroQRBHQ:b-9pe4nf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
> I first tried this using entries but figured I had to do it some other way since it's not public on history. Nice to know that it's public on memoryHistory! How do you suggest using memoryHistory? Passing it as a prop? Or just casting history to memoryHistory? I agree that history.go(-n) would be a way better solution.

I merely highlighted that as a possibility. Doesn't mean you have to do that but in short yes `let memoryHistory = history as MemoryHistory`.

That's how it's initialised in `app.tsx`:

```
 private memoryHistory = createMemoryHistory();
 private reduxStore = configureStore(this.memoryHistory);
```

Technically your task can be solved with one line of code, i.e:

```
history.goBack(history.length - 1);
```

> Could you elaborate? I don't understand what you're suggesting.

What I suggested is to navigate one step back as opposed to trying to take the user to the main view.

```
history.goBack()
```
___
*[gui/src/renderer/components/Modal.tsx, line 224 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKEZHqiC0UY2xD7HODv:-MKEta7H9how1rw0705p:bl1qwt3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/Modal.tsx#L224)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

What do you mean with "be able to participate in container transitions"?
</blockquote></details>

So that modals are animated as other containers within routes. This could also simplify the components that are currently holding those modals inside. 

There is a missing link between the static routes & dynamically displayed modals though. But with a bit of creativity, I think it's not impossible to make dynamic routes.

What else comes to my mind is that `History` API offers `state`, so it would technically be possible to display modal as a sub-route and give it some `state`, the `state` can be anything, including callbacks or whatever.

You get it?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-MKEybfxDmAdZ8fIbLwM:btb866f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

> I first tried this using entries but figured I had to do it some other way since it's not public on history. Nice to know that it's public on memoryHistory! How do you suggest using memoryHistory? Passing it as a prop? Or just casting history to memoryHistory? I agree that history.go(-n) would be a way better solution.

I merely highlighted that as a possibility. Doesn't mean you have to do that but in short yes `let memoryHistory = history as MemoryHistory`.

That's how it's initialised in `app.tsx`:

```
 private memoryHistory = createMemoryHistory();
 private reduxStore = configureStore(this.memoryHistory);
```

Technically your task can be solved with one line of code, i.e:

```
history.goBack(history.length - 1);
```

> Could you elaborate? I don't understand what you're suggesting.

What I suggested is to navigate one step back as opposed to trying to take the user to the main view.

```
history.goBack()
```
</blockquote></details>

Edit: `history.goBack(1 - history.length);` the number has to be negative obviously.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-MKEvltx1YhgLoB3rjK1:boejp5q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
> Technically your task can be solved with one line of code, i.e:

Unfortunately it's not that simple. When we call `history.replace('/login')` for example, it just replaces the current entry. After going to the account view and logging out the list of entries looks something like this:
```
[
  {
    "pathname": "/connect",
    "search": "",
    "hash": "",
    "key": "myktmk"
  },
  {
    "pathname": "/settings",
    "search": "",
    "hash": "",
    "key": "d20ixt"
  },
  {
    "pathname": "/login",
    "search": "",
    "hash": "",
    "key": "pedn51"
  }
]
```

It's of course possible to go back to the previous entry that has the pathname `/`/`/login`/`/connect`. Or maybe make sure the list of entries is emptied when we replace a path.

> What I suggested is to navigate one step back as opposed to trying to take the user to the main view.

The aim is to go back to the main view. That's the conclusion Matilda came to and in my opinion that behavior makes the most sense.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/transitions.ts, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKBhUpN6JeO1OZtuXV7:-MKEynd_6VsaH6SXTTXT:b-4vzsf1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/transitions.ts#L51)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We will probably need to go from a subpath under `/settings` to `/`/`/login`/`/connect`
</blockquote></details>

I think that the history stack should contain all of the information needed to go back without introducing additional rules.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-MKF20KZ3TdX05pu1Mi_:b-hkjb0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

> Technically your task can be solved with one line of code, i.e:

Unfortunately it's not that simple. When we call `history.replace('/login')` for example, it just replaces the current entry. After going to the account view and logging out the list of entries looks something like this:
```
[
  {
    "pathname": "/connect",
    "search": "",
    "hash": "",
    "key": "myktmk"
  },
  {
    "pathname": "/settings",
    "search": "",
    "hash": "",
    "key": "d20ixt"
  },
  {
    "pathname": "/login",
    "search": "",
    "hash": "",
    "key": "pedn51"
  }
]
```

It's of course possible to go back to the previous entry that has the pathname `/`/`/login`/`/connect`. Or maybe make sure the list of entries is emptied when we replace a path.

> What I suggested is to navigate one step back as opposed to trying to take the user to the main view.

The aim is to go back to the main view. That's the conclusion Matilda came to and in my opinion that behavior makes the most sense.
</blockquote></details>

Yeah that's unfortunate, I had impression that `replace` wiped the stack. Either way, we're not obliged to use `memoryHistory`, we can roll out our own, nothing wrong with managing the application history the way that suits us the best?

https://github.com/ReactTraining/history/blob/master/packages/history/index.ts#L996

I think that it would also be better if `history.go(-2)` gave the listener all entries that are being removed off the stack. This way it would be easy to pick the right transition from the last item without doing much heuristics or running regex or any of that.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 6 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/EscapeHatch.tsx, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKET0p78e48XHpIPLqp:-MKFDBNx5Z-F7wfxUKEm:b-brhqmo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L10)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I thought the name was more widely used for this type of feature, just did a search and only found a few pages using this naming. I'm fine with `KeyboardNavigation` :+1:
</blockquote></details>

I think it would make it easier for anyone joining the team to get familiar with the codebase if we used the names that better convey the meaning.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[CHANGELOG.md, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKE_1Zy6WmgLlK1vdcB:-ML79v-k85Hx-qQacLxs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/CHANGELOG.md#L30)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Buzzwords in changelog. It would be much simpler to say that pressing Escape takes user to the main view.
</blockquote></details>

Done.
___
*[gui/src/renderer/transitions.ts, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKBhUpN6JeO1OZtuXV7:-ML7AUu16sF8pJhIP9iu:b-9ocec6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/transitions.ts#L51)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think that the history stack should contain all of the information needed to go back without introducing additional rules.
</blockquote></details>

Now with the custom history implementation we still need to be able to navigate from any subpath under `/settings` to `/`/`/login`/`/connect`. I see a few alternatives:
1. The solution above
2. Allow `to` to be `null` and specifying the transitions as
```
r('/', null, transition.slide),
r('/connect', null, transition.slide),
r('/login', null, transition.slide),
```
3. Look at `history.entries` and use the location at `index + 1` or `index - 1` depending on the situation. This seems a lot more error prone though.

Do you have any other ideas? What do you think about these three?
___
*[gui/src/renderer/components/EscapeHatch.tsx, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKETQtm72gYIsuM0gWE:-ML7A56TCOIr7BcFHDZV:b-myh2fe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/components/EscapeHatch.tsx#L24)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Yeah that's unfortunate, I had impression that `replace` wiped the stack. Either way, we're not obliged to use `memoryHistory`, we can roll out our own, nothing wrong with managing the application history the way that suits us the best?

https://github.com/ReactTraining/history/blob/master/packages/history/index.ts#L996

I think that it would also be better if `history.go(-2)` gave the listener all entries that are being removed off the stack. This way it would be easy to pick the right transition from the last item without doing much heuristics or running regex or any of that.
</blockquote></details>

It's now using our own history implementation
___
*[gui/src/renderer/redux/userinterface/reducers.ts, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKEbDhT1z_9elxk8GHI:-ML7AJUMA38lQWbZfCRL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/redux/userinterface/reducers.ts#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not needed as the `EscapeHutch` should be able to navigation without much structural knowledge of the app.
</blockquote></details>

Done.

**Review by pronebird — COMMENTED** [review]
> Reviewed 5 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/transitions.ts, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-MKBhUpN6JeO1OZtuXV7:-ML7CPB0198lKyGvly-U:b-424vbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e36471a3750e6738c5bf6e86151328fc8d7bca6/gui/src/renderer/transitions.ts#L51)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Now with the custom history implementation we still need to be able to navigate from any subpath under `/settings` to `/`/`/login`/`/connect`. I see a few alternatives:
1. The solution above
2. Allow `to` to be `null` and specifying the transitions as
```
r('/', null, transition.slide),
r('/connect', null, transition.slide),
r('/login', null, transition.slide),
```
3. Look at `history.entries` and use the location at `index + 1` or `index - 1` depending on the situation. This seems a lot more error prone though.

Do you have any other ideas? What do you think about these three?
</blockquote></details>

Suppose we're at `/settings/advanced` & we want to go back to `/connect`.

Navigation stack before the call to `history.reset()`:

- `/connect`
- `/settings`
- `/settings/advanced`

Navigation stack after calling to `history.reset()`:

- `/connect`
- ~`/settings`~
- ~`/settings/advanced`~

IMO reverse the transition from `/settings` to `/connect` and use it to animate from `/settings/advanced` to `/connect`.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

**Review by pronebird — APPROVED** [review]
> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/KeyboardNavigation.tsx, line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-ML8LG_n5an8tHuaChZE:-ML8LG_n5an8tHuaChZF:b-41ur2h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4619e4a5b8951d6ddc7a981efb47b007c0873782/gui/src/renderer/components/KeyboardNavigation.tsx#L5)):*
> ```XML
> import History from '../lib/history';
> 
> interface IEscapeHatchProps {
> ```

Minor naming convention. Seems like this was not renamed.

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @pronebird)

___
*[gui/src/renderer/components/KeyboardNavigation.tsx, line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-ML8LG_n5an8tHuaChZE:-ML8QY-n3hSE6IwFIzXm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4619e4a5b8951d6ddc7a981efb47b007c0873782/gui/src/renderer/components/KeyboardNavigation.tsx#L5)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Minor naming convention. Seems like this was not renamed.
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202#-:-ML8aT3DC3Zm91iThLo4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
