### PR TITLE
Improve string escaping in Android translations converter tool

### PR DESCRIPTION
**Pull request by jvff**
Previously, the custom Android translations convert tool we have would not properly handle escaping in some cases. More specifically, plural resources weren't escaped at all, and string resources didn't escape XML characters (`&`, `<` and `>`). This PR fixes that.

A new `StringValue`  wrapper type was created so that the escaping code could be shared between `StringResource` and `PluralResource`. The new type also now handles escaping the XML characters.

The PR also updates the translations.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)

### CODE REVIEW

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: 0 of 38 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7iTdt93bZGYNbpNQ_:-MT7iTdu-KAlMbM5kvin:b3ijh3g) (no related file):*
Should this PR have a changelog entry?

---

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 37 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: 37 of 38 files reviewed, 2 unresolved discussions (waiting on @jvff)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7iTdt93bZGYNbpNQ_:-MT7kJRg5zz0iTuQOH9i:b-wtpjt4) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Should this PR have a changelog entry?
</blockquote></details>

I don't think so.

---
___
*[android/translations-converter/src/android.rs, line 320 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7xECEEXq_oQ67U4I5:-MT7xECF-u36MMn_b5ut:b-f1x5c8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e765b4a33228a7d09cc4a85e9f58aad5f33ebfa/android/translations-converter/src/android.rs#L320)):*
> ```XML
>     ///
>     /// Makes it possible to compare the Android strings with the gettext messages.
>     pub fn normalize(&mut self) {
> ```

Wouldn't it make more sense to return a value that's comparable to gettext messages rather than modifying this value in place?

**Comment by axti** [comment]
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7iTdt93bZGYNbpNQ_:-MTAEoPP2CyRIfnTxbgr:b-stooc3) (no related file):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I don't think so.
</blockquote></details>

We update translation and improve labels, so could be potentially user aware changes and be included to change log.

---

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/translations-converter/src/android.rs, line 332 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MTAVBs46fQ4VoWzDZMM:-MTAVBs46fQ4VoWzDZMN:by2zfwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e765b4a33228a7d09cc4a85e9f58aad5f33ebfa/android/translations-converter/src/android.rs#L332)):*
> ```XML
>         let value = LESS_THANS.replace_all(&value, "<");
>         // Unescape greater thans
>         let value = GREATER_THANS.replace_all(&value, ">");
> ```

Also, aren't there crates that would do the escaping for us? That'd be much better than relying on regexes IMO https://crates.io/crates/html-escape

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: 37 of 40 files reviewed, 3 unresolved discussions (waiting on @axti and @pinkisemils)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7iTdt93bZGYNbpNQ_:-MTB8qYd7HH5cS2Gw-p-:bivu089) (no related file):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

We update translation and improve labels, so could be potentially user aware changes and be included to change log.
</blockquote></details>

That's a good point, but the changelog usually only contains translation related entries when adding/removing languages or doing important fixes. It's common to update all translations on almost every release

---
___
*[android/translations-converter/src/android.rs, line 320 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7xECEEXq_oQ67U4I5:-MTB7yIz4Z3C-7GWdsp_:bbagyoo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e765b4a33228a7d09cc4a85e9f58aad5f33ebfa/android/translations-converter/src/android.rs#L320)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Wouldn't it make more sense to return a value that's comparable to gettext messages rather than modifying this value in place?
</blockquote></details>

I'm not so sure. The value would be thrown away in `main` after the conversion anyway.
___
*[android/translations-converter/src/android.rs, line 332 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MTAVBs46fQ4VoWzDZMM:-MTB7v6n2R8bvKaOAeDx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e765b4a33228a7d09cc4a85e9f58aad5f33ebfa/android/translations-converter/src/android.rs#L332)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Also, aren't there crates that would do the escaping for us? That'd be much better than relying on regexes IMO https://crates.io/crates/html-escape
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/translations-converter/src/android.rs, line 320 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7xECEEXq_oQ67U4I5:-MTBSbcwDQYN6pNfFcSG:bwmckgh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e765b4a33228a7d09cc4a85e9f58aad5f33ebfa/android/translations-converter/src/android.rs#L320)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm not so sure. The value would be thrown away in `main` after the conversion anyway.
</blockquote></details>

Yes, but then the user of this type always has to remember that it is no longer valid to output it after you've called `normalize()`.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/translations-converter/src/android.rs, line 320 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449#-MT7xECEEXq_oQ67U4I5:-MTBTOv23KzOpdeVAqEX:bl2wbfs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e765b4a33228a7d09cc4a85e9f58aad5f33ebfa/android/translations-converter/src/android.rs#L320)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yes, but then the user of this type always has to remember that it is no longer valid to output it after you've called `normalize()`. 
</blockquote></details>

Ok, I can change it in a separate PR.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2449)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
