### PR TITLE
Exclude build folder from Swiftlint

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
Also includes some refactoring to remove lint errors.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-:-NioqgjL92ZqO3ji4y6v:b-mkd4fs)* status: 0 of 4 files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-Nioydg1Ej0UNE7pdejX:-Nioydg1Ej0UNE7pdejY:b-l9ajup) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf2aac9530f2d4201222f3dc3a3b7c92e9e65c93/ios/MullvadVPN/AppDelegate.swift#L118)):*
> ```Swift
>         addressCache.loadFromFile()
> 
>         setUpProxies(containerURL: containerURL)
> ```

It's hard enough to follow what's going on. Perhaps it would be easier if the call to `setUpProxies()` wouldn't be nested in `setUpCaches()` and instead would follow the call to `setUpCaches()`?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 334 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-NiouoGdDQrH8h94tTmG:-NiouoGdDQrH8h94tTmH:b-8vv59e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf2aac9530f2d4201222f3dc3a3b7c92e9e65c93/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L334)):*
> ```Swift
> 
>     /**
>      Create a connection state.
> ```

`connectedState()` doesn't describe particularly well what this method does. It's not even used when the actor is in connected state. The documentation for this method does not describe it either. 

Since this method is only used when in `initial` or `error` state, it seems that this call is a precursor to `[re]connecting` state rather than `connected` state.

It would be more appropriate to call it something along the lines that produces a connection state for connection attempt. Or maybe simply mark it as `makeConnectionStateInner()` and document what it does. 
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 337 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-NiosspJ-3zSC5h9ARBm:-NiosspJ-3zSC5h9ARBn:bvw9xb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf2aac9530f2d4201222f3dc3a3b7c92e9e65c93/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L337)):*
> ```Swift
> 
>      - Parameters:
>      - nextRelay: next relay to connect to.
> ```

Nit: Parameters listed under the "- Parameters:" should be indented with two spaces, I think... Xcode has a bug where it doesn't do that for block comments but it does that for `///` comments.

For example:

```
- Parameters:
  - paramA: <description>
  - paramB: <description> 
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-Nioydg1Ej0UNE7pdejX:-Nj70_JL8ws7a43E4KT_:bwdktdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf2aac9530f2d4201222f3dc3a3b7c92e9e65c93/ios/MullvadVPN/AppDelegate.swift#L118)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It's hard enough to follow what's going on. Perhaps it would be easier if the call to `setUpProxies()` wouldn't be nested in `setUpCaches()` and instead would follow the call to `setUpCaches()`?
</blockquote></details>

I cannot follow the call since `setUpProxies()` creates the `apiProxy` that's used inside `setUpCaches()`. And neither can it precede it. I simply reverted this part and created a smaller refactor of TunnelManager creation intead. I'm not looking for real improvement here, mostly just fix the swiftlint error.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 334 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-NiouoGdDQrH8h94tTmG:-Nj7foZdA_o6EI_sWG_A:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf2aac9530f2d4201222f3dc3a3b7c92e9e65c93/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L334)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`connectedState()` doesn't describe particularly well what this method does. It's not even used when the actor is in connected state. The documentation for this method does not describe it either. 

Since this method is only used when in `initial` or `error` state, it seems that this call is a precursor to `[re]connecting` state rather than `connected` state.

It would be more appropriate to call it something along the lines that produces a connection state for connection attempt. Or maybe simply mark it as `makeConnectionStateInner()` and document what it does.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 337 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412#-NiosspJ-3zSC5h9ARBm:-Nj7_Vsp1OJLTGKGnFs7:b94vo4h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf2aac9530f2d4201222f3dc3a3b7c92e9e65c93/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L337)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: Parameters listed under the "- Parameters:" should be indented with two spaces, I think... Xcode has a bug where it doesn't do that for block comments but it does that for `///` comments.

For example:

```
- Parameters:
  - paramA: <description>
  - paramB: <description> 
```
</blockquote></details>

The rest of the file uses four spaces for comments, so I changed to that.

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @pronebird)

**Pull request merged**
