### PR TITLE
Add end to end connection tests for multihop ios 778

### PR DESCRIPTION
**Pull request by mojganii**
This PR adds an end-to-end test for Multihop and fixes minor issues, such as the shrinking of the collapse button in the connection view. Additionally, after changing the data type for the collapse view, we forgot to update the UI tests to ensure compatibility in finding elements.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)

### CODE REVIEW

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 8 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 269 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914#-O8bR7wfDTgAlJLsE02y:-O8bR7wgDr2YSl3z_TEg:bva5h2n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5b7105b3fad9562eff67c77be4ce16ceb783e6/ios/MullvadVPNUITests/RelayTests.swift#L269)):*
> ```Swift
>         VPNSettingsPage(app)
>             .tapMultihopSwitch()
>             .swipeDownToDismissModal()
> ```

Interestingly enough, if I run this code on an iPhone SE, it doesn't dismiss the settings. 
I think we should replace this by tapping the back, and done buttons respectively instead.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 269 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914#-O8bR7wfDTgAlJLsE02y:-O8bWnTmElv-kN6CckAy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5b7105b3fad9562eff67c77be4ce16ceb783e6/ios/MullvadVPNUITests/RelayTests.swift#L269)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Interestingly enough, if I run this code on an iPhone SE, it doesn't dismiss the settings. 
I think we should replace this by tapping the back, and done buttons respectively instead.
</blockquote></details>

Done.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
