### PR TITLE
Do not show a toast after dismissing the dns dialog

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
Logic does unfortunately not work coherently. 

E.g 
- Add the 1.1.1.1 (see the toast)
- Toggle off ( = will show toast)
- Toggle on ( = will show toast)
- Remove 1.1.1.1, will toggle off but not show toast

What if we instead use the NavResult of dns dialog, and we can use value to indicate that the value has changed. If it has changed we can show the snackbar.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986#-:-NtR-vAlBaG4QsIhDbtQ:b-r00qyc)* status: 0 of 1 files reviewed, all discussions resolved

**Review by Pururun — COMMENTED** [review]
Fixed

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986#-:-Nt_Db1y5VIlYLG9ejNA:b-886gsx)* status: 0 of 4 files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt` line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986#-NtaDlVcEJlv5N61cgFY:-NtaDlVcEJlv5N61cgFZ:b35q89y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef7561ed47a0aa5cbb2a9db43656408fb08dde4e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt#L131)):*
> ```Kotlin
>         if (enable && vmState.value.customDnsList.isEmpty()) {
>             viewModelScope.launch { _uiSideEffect.send(VpnSettingsSideEffect.NavigateToDnsDialog) }
>         } else if (showToast) {
> ```

Shouldn't this suffice? I don't think showToast parameter is needed.
```
        } else if (vmState.value.customDnsList.isNotEmpty()) {
            showApplySettingChangesWarningToast()
        }
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt` line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986#-NtaDlVcEJlv5N61cgFY:-NtaSMTJ8ZeCe-eORHYY:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef7561ed47a0aa5cbb2a9db43656408fb08dde4e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt#L131)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Shouldn't this suffice? I don't think showToast parameter is needed.
```
        } else if (vmState.value.customDnsList.isNotEmpty()) {
            showApplySettingChangesWarningToast()
        }
```
</blockquote></details>

Done

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
