### PR TITLE
Prevent loading when logging out

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzbR2bp-QxTcHpEa5m4:-NzbR2bp-QxTcHpEa5m5:bxw7mfn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fc0b40c3b6089a126bee6fa2c16d0844163aa4a/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt#L293)):*
> ```Kotlin
>     companion object {
>         private const val DUMMY_DEVICE_NAME = "fake_name"
>         private const val DUMMY_ACCOUNT_NUMBER = "fake_number"
> ```

Maybe should be called account token as well?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcCwo46TwxSUb460GU:-NzcCwo46TwxSUb460GV:b-5d2jvk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3c120e88fd7ecd30700e45583fdbfb5af1c13771/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L41)):*
> ```Kotlin
>                 deviceRepository.deviceState.filterIsInstance<DeviceState.LoggedIn>(),
>                 accountRepository.accountData
>                     .scan(accountRepository.accountData.value) {
> ```

Can you clarify what this does? It is a bit to understand from the code.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcLjgg33GmdaZcfAAJ:-NzcLjgg33GmdaZcfAAK:b4bxj1h) (no related file):*
Why is this PR changing from "account number" to "account token"? Makes it harder to review since there are many unrelated changes. Also, I believe we mostly should stick with "account number" where possible since "account token" is more of legacy naming.  

___

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcLjgg33GmdaZcfAAJ:-Nznq06i9twi8_EFW8sX:bh3uvey) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why is this PR changing from "account number" to "account token"? Makes it harder to review since there are many unrelated changes. Also, I believe we mostly should stick with "account number" where possible since "account token" is more of legacy naming.
</blockquote></details>

I raised this internally and we should strive towards using "account number" where possible to have a common lingo. Here's another PR to ensure we instead use "account number" throughout the kotlin code base: https://github.com/mullvad/mullvadvpn-app/pull/6333

___
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzbR2bp-QxTcHpEa5m4:-NznpsDH9531N7yqj8kC:b-mlnzkn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fc0b40c3b6089a126bee6fa2c16d0844163aa4a/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt#L293)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe should be called account token as well?
</blockquote></details>

:stop_sign:

(https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcLjgg33GmdaZcfAAJ)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzbR2bp-QxTcHpEa5m4:-O--yyxOD8UEfFEj1Bta:bzehc3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fc0b40c3b6089a126bee6fa2c16d0844163aa4a/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt#L293)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

:stop_sign:

(https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcLjgg33GmdaZcfAAJ)
</blockquote></details>

:scream_cat:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: all files reviewed, 2 unresolved discussions

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzbR2bp-QxTcHpEa5m4:-O-06wZKB9wd-Hdsj1Uz:b-iss8k5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fc0b40c3b6089a126bee6fa2c16d0844163aa4a/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt#L293)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

:scream_cat:
</blockquote></details>

I used AccountToken since that is what is specified in the proto file, I'm open to using AccountNumber instead, it feels for correct.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcCwo46TwxSUb460GU:-O-07X6-40_wzDRlvUAn:b-va18ml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3c120e88fd7ecd30700e45583fdbfb5af1c13771/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L41)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Can you clarify what this does? It is a bit to understand from the code.
</blockquote></details>

It is basically the same as filterNotNull along with onStart, I refactored it to make it more readable. :+1:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcLjgg33GmdaZcfAAJ:-O-07xDk1WVNb-UZV6-P:b-e0rg9d) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I raised this internally and we should strive towards using "account number" where possible to have a common lingo. Here's another PR to ensure we instead use "account number" throughout the kotlin code base: https://github.com/mullvad/mullvadvpn-app/pull/6333
</blockquote></details>

I'll await that PR and rebase on it. :+1: 

___

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcLjgg33GmdaZcfAAJ:-O-0J0aT9soXHhD1miTa:b-vo3p1q) (no related file):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'll await that PR and rebase on it. :+1:
</blockquote></details>

The other PR was just merged!

___

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-:-O-0NjTI8inr1FtVcZ0S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt` line 293 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzbR2bp-QxTcHpEa5m4:-O-0NQhA1jbfPZW53gYC:btz19r8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fc0b40c3b6089a126bee6fa2c16d0844163aa4a/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt#L293)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I used AccountToken since that is what is specified in the proto file, I'm open to using AccountNumber instead, it feels for correct.
</blockquote></details>

I think we should use `AccountNumber` here
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-NzcCwo46TwxSUb460GU:-O-0Nep6-dzRCYwGdqLK:bcv502w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3c120e88fd7ecd30700e45583fdbfb5af1c13771/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L41)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It is basically the same as filterNotNull along with onStart, I refactored it to make it more readable. :+1:
</blockquote></details>

Nice :+1:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 42 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-O-0u9O36hkMs8zn-St3:-O-5485U9OUsMC-jrzyh:b-xhw3lp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/996113793a95ffb194ef197782bb37644174b0ec/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L42)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need these parenthese? :thinking:
</blockquote></details>

Nice catch, fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 43 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-O-0se8X-nLIF3E7USFs:-O-5473VAdMrqfOtFut1:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/996113793a95ffb194ef197782bb37644174b0ec/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L43)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we move this out of the `combine` call to improve readability?
</blockquote></details>

Fixed!

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318#-:-O-5LHgEDacyg4ky_2OE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
