### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by b068931cc450442b63f5b3d276ea4297**
Proposals to changes the subsequent translations:
- "Netzwerk-Traffic" to "Netzwerkverkehr"
- "VPN-Tunnel-Status" to "Status des VPN-Tunnels"
- "Kundennummer" to "Kontonummer"
- "Immer VPN erfordern" to "VPN immer erforderlich"
- "Kontozeiterinnerungen" to "Erinnerungen an die Kontozeit"

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2508)

### CODE REVIEW

**Comment by faern** [comment]
It's very hard for us to accept third party contributions to language changes. We have no way of verifying their correctness. So currently we only bring in translations from a paid third party service. The downside can be that they are not very familiar with computer networking or VPNs possibly :/

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Thank you for your reply. Do you have the possibility to ask other people/acquaintances who speak the respective language or to show the suggested changes to the paid translators?

**Comment by faern** [comment]
I surely can add this as suggestions to the translators and see what they say. Thanks for the improvements.

**Comment by faern** [comment]
But doing so involves a lot of work for us per translation. So it's nothing we can routinely do. I can make an exception for these five strings.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Thank you I can understand that.

**Comment by faern** [comment]
I have sent these suggestions to our translators. This or some variation of this might end up in the next release, we'll have to see what they say. But the PR as is won't be merged as translations upgrades are automated with scripts at the last stage of a release. So I'm closing this. But thank you for your contribution!

**Comment by faern** [comment]
We can now accept third party translation suggestions! There is a google docs spreadsheet where users can suggest improvements. Please see our new section in the contribution guidelines! https://github.com/mullvad/mullvadvpn-app/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
