### PR TITLE
Move "Content blockers" closer to "Custom Dns" setting

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334#-:-NhRQa-TEqhjcUgXNT6y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334#-Ni-TIi84PSosDdBWd9A:-Ni-TIi84PSosDdBWd9B:bj2mbji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e964efcaf36f32220d1b5eef5543700f06e1da/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L268)):*
> ```Kotlin
>             )
>         }
>         //        composeTestRule
> ```

This should removed no?
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 394 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334#-Ni-TSFTBEquxm2KpSyc:-Ni-TSFU1EGvU9ZX0dDD:b-q64pkt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e964efcaf36f32220d1b5eef5543700f06e1da/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L394)):*
> ```Kotlin
>             )
>         }
>         //        composeTestRule
> ```

See above.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334#-Ni-TIi84PSosDdBWd9A:-Ni-wrGB3VxavSEspzfr:b-gx9wu9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e964efcaf36f32220d1b5eef5543700f06e1da/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L268)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should removed no?
</blockquote></details>

Correct, thanks!
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 394 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334#-Ni-TSFTBEquxm2KpSyc:-Ni-ws8B12IbvbRgRS2H:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e964efcaf36f32220d1b5eef5543700f06e1da/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L394)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334#-Ni-TIi84PSosDdBWd9A:-Ni-wu_g0IgfH51V3NJi:bs7wumx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e964efcaf36f32220d1b5eef5543700f06e1da/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L268)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Correct, thanks!
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
