### PR TITLE
Update view model when switching between entry and exit location

### PR DESCRIPTION
**Pull request by rablador**
This PR contains two closely related issues:

1. https://linear.app/mullvad/issue/IOS-631/update-view-model-when-switching-between-entry-and-exit-location

The view location selection view must be able to work with both entry and exit locations. If a user has selected a single relay as an entry, the user should not be able to select the same relay as an exit, and vice versa. Edge cases around countries/cities containing a single relay don't have to be accounted for.

2. https://linear.app/mullvad/issue/IOS-610/allow-selecting-entry-location

The user must be able to specify what locations should be used for the entry relay when multi-hop is enabled. The UI for this should follow the design from [IOS-504](https://linear.app/mullvad/issue/IOS-504/design-ui-for-toggling-multihop). 

The first time you enter the location view after enabling multi-hop, the user should be directed to the entry view so to onboard the user. Afterwards, entering the location view would direct the user to the exit view.

When showing the exit tab, the selected entry location should be marked as (Entry) and if it's a relay it should be greyed out. Same goes for the selected Exit point if you're in the entry view. Furthermore you should be able to click an already selected list item in order to get to the next step of the flow (Entry to Exit, Exit to Main view).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 219 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O--t9zqCqqyMotteXPI:-O--t9zqCqqyMotteXPJ:b-omrd7t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L219)):*
> ```Swift
>         // Multihop selection doesn't apply to anything but single hosts.
>         guard
>             selectedRelays?.locations.count == 1,
> ```

Looks like we're not checking for custom lists, it really feels like we should have unit tests for this data source to prevent further bugs.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 219 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O--t9zqCqqyMotteXPI:-O-0rk6PDfC0pH95AZUv:b-9hytia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L219)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Looks like we're not checking for custom lists, it really feels like we should have unit tests for this data source to prevent further bugs.


</blockquote></details>

This is not a bug. I didn't think about the fact that both all locations and custom list should be marked for multihop (entry/exit) selection. Just checked the desktop app and it seems they mark both. I will make the change.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 219 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O--t9zqCqqyMotteXPI:-O-0soQ7BfHCsE_86s4s:bgjfa4t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L219)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is not a bug. I didn't think about the fact that both all locations and custom list should be marked for multihop (entry/exit) selection. Just checked the desktop app and it seems they mark both. I will make the change.
</blockquote></details>

*marked at the same time for multihop

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5ID8ODAotDBb1I0zN:-O-5BNpXBswcmrZKqGzY:bd54ilq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L249)):*
> ```Swift
> 
>     private func statusIndicatorColor() -> UIColor {
>         if isDisabled && !isMultipHopSelection {
> ```

when the relay is `inactive`  regardless if it's multi-hop selected or not then the indicator should be red.this condition defects  the priority of disabling to multi-hop.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 348 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5BgUb43iNXXWMMBWk:-O-5BgUb43iNXXWMMBWl:b-om4o2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L348)):*
> ```Swift
> 
>     func setMultihopSelection(_ context: RelaySelection.MultihopContext?) {
>         if let context {
> ```

I think the style for this state should be managed individually when we are controlling state via `isMultipHopSelection` variable instead of changing disable and multihop state values to reach the style.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5JrUI7t70bW71H4UF:-O-5JrUI7t70bW71H4UG:b-ias6fa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd719540f817c3734677dd51acd69dca7ba74c53/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCellViewModel.swift#L30)):*
> ```Swift
>             lhs.section == rhs.section &&
>             lhs.isSelected == rhs.isSelected &&
>             lhs.indentationLevel == rhs.indentationLevel
> ```

two objects are equal when all properties are equal.what was the reason to eliminate that?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5UDgm9TZ8MYVVkSiz:-O-5UDgm9TZ8MYVVkSj-:b-xxt2jq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L215)):*
> ```Swift
>     private func mapMultihopSelection(
>         from selectedRelays: UserSelectedRelays?,
>         context: RelaySelection.MultihopContext
> ```

I think `currentContext` and the rest parts are working with it, isn't a part of `RelaySelection`.I think the whole thing which `RelaySelection` keeps are `entry` and `exit`. these controls should be kept in another place like `LocationDataSource` like below.


from of my point of view, `LocationDataSource` is responsible to return `userSelectedRelay` without understanding if it's entry or exit just exclude entry from exit or vs.



_Code snippet:_
```Swift
final class LocationDataSource:
    UITableViewDiffableDataSource<LocationSection, LocationCellViewModel>,
    LocationDiffableDataSourceProtocol {
    private var currentSearchString = ""
    private var dataSources: [LocationDataSourceProtocol] = []
    // The selected cell.
    private var userSelectedRelay: LocationCellViewModel?
    // When multihop is enabled, this is the "inverted" selected cell, ie. entry
    // if in exit mode and exit if in entry mode.
    private var excludeRelay: LocationCellViewModel?
    let tableView: UITableView
    let sections: [LocationSection]

    var didSelectRelayLocations: (((UserSelectedRelays)) -> Void)?
    
    
    func setRelays(_ response: REST.ServerRelaysResponse, selectedRelays: RelaySelection, filter: RelayFilter) {}
}
```

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5UDgm9TZ8MYVVkSiz:-O-5_MVL3ARUT4_zxmaQ:b-vorqnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L215)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think `currentContext` and the rest parts are working with it, isn't a part of `RelaySelection`.I think the whole thing which `RelaySelection` keeps are `entry` and `exit`. these controls should be kept in another place like `LocationDataSource` like below.


from of my point of view, `LocationDataSource` is responsible to return `userSelectedRelay` without understanding if it's entry or exit just exclude entry from exit or vs.
</blockquote></details>

having the logics if `multihop` is enabled or not can be placed in `LocationIntreactor` to make a proper data source for segments and exclude one from the other.

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5UDgm9TZ8MYVVkSiz:-O-5aO3C-4Idkow6rWRU:b-4g1snl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L215)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

having the logics if `multihop` is enabled or not can be placed in `LocationIntreactor` to make a proper data source for segments and exclude one from the other.
</blockquote></details>

this is a part of `LocationViewControllerWrapper`

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 2 of 11 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5ID8ODAotDBb1I0zN:-O-ASZe76aNd0Rx6rEQS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L249)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

when the relay is `inactive`  regardless if it's multi-hop selected or not then the indicator should be red.this condition defects  the priority of disabling to multi-hop.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 348 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5BgUb43iNXXWMMBWk:-O-AT40j1VJByTUuHA06:brxly93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L348)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think the style for this state should be managed individually when we are controlling state via `isMultipHopSelection` variable instead of changing disable and multihop state values to reach the style.
</blockquote></details>

Changed and not applicable anymore.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5JrUI7t70bW71H4UF:-O-5w2Lc1nu2pp-HLiev:bv762t7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd719540f817c3734677dd51acd69dca7ba74c53/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCellViewModel.swift#L30)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

two objects are equal when all properties are equal.what was the reason to eliminate that?
</blockquote></details>

Indentation level isn't relevant to this equality check and does nothing right now. We're not using full equality here anyway (multihopContext missing), so I think we should only check equality on things that are relevant.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-5UDgm9TZ8MYVVkSiz:-O-GRZFE4v1p7wvPZWUI:b-grj6h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L215)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

this is a part of `LocationViewControllerWrapper`
</blockquote></details>

Done. Made the data source unknowing of multihop.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 219 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O--t9zqCqqyMotteXPI:-O-GX4sT7mKBe6JY2cg1:b-xpa7ta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd8ddf8ae1a392ffab86e4e95bf25422cc4123d9/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L219)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

*marked at the same time for multihop
</blockquote></details>

BTW, change is not done here, but in `tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath)`.

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 2 of 11 files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-LIn9U9e0qBG7XmbV6:-O-LIn9U9e0qBG7XmbV7:bim20wl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L144)):*
> ```Swift
>     func setSelectedRelays(_ selectedRelays: RelaySelection) {
>         selectedLocation = mapSelection(from: selectedRelays.selected)
>         excludedLocation = mapMultihopSelection(from: selectedRelays.excluded)
> ```

I think now, datasource doesn't know about multihop having a function with this name doesn't make sense.I think we can go with this solution and eliminate this function:



_Code snippet:_
```Swift
  func setSelectedRelays(_ selectedRelays: RelaySelection) {
        selectedLocation = mapSelection(from: selectedRelays.selected)
        if selectedRelays.shouldExcluded {
            excludedLocation = mapSelection(from: selectedRelays.excluded)
            excludedLocation?.excludedRelayTitle = selectedRelays.excludedTitle
        }
        tableView.reloadData()
    }


struct RelaySelection {
    var selected: UserSelectedRelays?
    var excluded: UserSelectedRelays?
    var excludedTitle: String?
    
    var shouldExcluded: Bool {
        if excluded?.locations.count == 1,
           case .hostname = excluded?.locations.first {
            return true
        }
        return false
    }
}
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-Kz9Jm0v5IS5H76GCK:-O-Kz9Jm0v5IS5H76GCL:bdcil3t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L36)):*
> ```Swift
>     private var multihopContext: MultihopContext = .exit
> 
>     private let entryTitle = NSLocalizedString(
> ```

I suggest to put the description in `MultihopContext` :



_Code snippet:_
```Swift
    enum MultihopContext: Int,CaseIterable, CustomStringConvertible {
        case entry, exit
        
        var description: String {
            switch self {
            case .entry:
                NSLocalizedString(
                    "MULTIHOP_ENTRY",
                    tableName: "SelectLocation",
                    value: "Entry",
                    comment: ""
                )
            case .exit:
                NSLocalizedString(
                    "MULTIHOP_EXIT",
                    tableName: "SelectLocation",
                    value: "Exit",
                    comment: ""
                )
            }
        }
    }
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 173 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-Kx_3U0bDnc2atcqxi:-O-Kx_3U0bDnc2atcqxj:bbhizde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L173)):*
> ```Swift
>     @objc
>     private func segmentedControlDidChange(sender: UISegmentedControl) {
>         switch segmentedControl.selectedSegmentIndex {
> ```

we can make it shorter if we conform `CaseIterable` for `MultihopContext`  :



_Code snippet:_
```Swift
multihopContext = .allCases[segmentedControl.selectedSegmentIndex]
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-LDifhBDL3VSQcSfFc:-O-LDifhBDL3VSQcSfFd:bbbiwd0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L185)):*
> ```Swift
>     }
> 
>     func swapViewController() {
> ```

it can be shorter for the clarification 



_Code snippet:_
```Swift
    private func swapViewController()  {
        locationViewContainer.arrangedSubviews.forEach { view in
            view.removeFromSuperview()
        }

        let (selectedRelay, viewController, currentViewController) = switch multihopContext {
        case .entry:
            (
                RelaySelection(
                    selected: selectedEntry,
                    excluded: selectedExit,
                    excludedTitle: MultihopContext.exit.description
                ),
                exitLocationViewController,
                entryLocationViewController
            )
        case .exit:
            (
                RelaySelection(
                    selected: selectedExit,
                    excluded: selectedEntry,
                    excludedTitle: MultihopContext.entry.description
                ),
                exitLocationViewController,
                entryLocationViewController
            )
        }

        currentViewController?.removeFromParent()
        viewController.setSelectedRelays(selectedRelay)
        addChild(viewController)
        viewController.didMove(toParent: self)
        locationViewContainer.addArrangedSubview(viewController.view)
    }
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 2 of 11 files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-LIn9U9e0qBG7XmbV6:-O-LsG2D6VJF69xnYb_k:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L144)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think now, datasource doesn't know about multihop having a function with this name doesn't make sense.I think we can go with this solution and eliminate this function:
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-Kz9Jm0v5IS5H76GCK:-O-LslAI2HTbbHHexSE-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L36)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I suggest to put the description in `MultihopContext` :
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 173 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-Kx_3U0bDnc2atcqxi:-O-LuFCs5Yr2ENNi6-LU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L173)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can make it shorter if we conform `CaseIterable` for `MultihopContext`  :
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-LDifhBDL3VSQcSfFc:-O-LvpS72b6lLfkaS7EG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c23a91c7333ad20b333f80c67d47240b4c1ef33e/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L185)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it can be shorter for the clarification
</blockquote></details>

Done.

**Review by acb-mv — APPROVED** [review]
> Reviewed 4 of 8 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: all files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by buggmagnet — CHANGES_REQUESTED** [review]
I am still able to select an entry relay that should not be able to be selected. 

[ScreenRecording\_06-17-2024 15-54-08\_1.MP4](https://files.reviewableusercontent.io/images/reviewable/129761703/fjXm3wbC8e0n7bB07RNzFaFv/ScreenRecording_06-17-2024%2015-54-08_1.mp4)

> Reviewed 4 of 8 files at r2, 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-:-O-aWq2u0NFONt4-h30O:b-liulov)* status: all files reviewed, 10 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-aW_wD1GdNaVzRHJCM:-O-aW_wD1GdNaVzRHJCN:b-jz8wzv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift#L25)):*
> ```Swift
> 
>     override func tearDownWithError() throws {
>         try? fileManager.removeItem(at: directoryPath)
> ```

Why was this made an optional ?

**Review by buggmagnet — COMMENTED** [review]
(Video doesn't seem to show on reviewable, it was sent to @rablador in a PM)
Screenshot for evidence: 



> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-:-O-aX0lfElXxHVAaqw1z:b-8bps72)* status: all files reviewed, 10 unresolved discussions (waiting on @mojganii and @rablador)

**Review by rablador — COMMENTED** [review]
Custom lists makes it tricky since their items should be both identical to their counterparts in "all locations" and not, at the same time. Not in terms of selecton, but when marking entry/exit.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-:-O-a_khT-ylJb4MKM3JU:b-pi2hr)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-aW_wD1GdNaVzRHJCM:-O-aa9r8-n51u6dkzKPF:b-aq8xa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why was this made an optional ?
</blockquote></details>

It made tests fail sometimes. The tests do not fail, but the forced removal does.

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 258 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-eaW9r9aVRbFSOmjHh:-O-eaW9r9aVRbFSOmjHi:b-ydbpww) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L258)):*
> ```Swift
>         // Compare nodes on name rather than whole node in order to match relays in both .customLists
>         // and .allLocations.
>         if itemIdentifier(for: indexPath)?.node.name == excludedLocation?.node.name {
> ```

`LocationCellViewModel` is already comforming `Hashable` which has `Equatable` inside itself. then we can compare two nodes together.



_Code snippet:_
```Swift
    if itemIdentifier(for: indexPath) == excludedLocation {
            cell.setExcludedRelayTitle(excludedLocation?.excludedRelayTitle)
    }
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-ebGnQDR3p9-aefI6w:-O-ebGnQDR3p9-aefI6x:bsnjrqt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L301)):*
> ```Swift
>     func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool {
>         guard let item = itemIdentifier(for: indexPath) else { return false }
>         return (item.node != excludedLocation?.node) && item.node.isActive
> ```

the above comment goes for here.



_Code snippet:_
```Swift
   return (item != excludedLocation) && item.node.isActive
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-ec21k60fM__sFtsL0:-O-ec21k60fM__sFtsL1:b-sa3n00) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L17)):*
> ```Swift
>     func navigateToCustomLists(nodes: [LocationNode])
>     func navigateToFilter()
>     func didSelectEntryRelays(relays: UserSelectedRelays)
> ```

`relays` is redundant.



_Code snippet:_
```Swift
func didSelectEntryRelays(_ relays: UserSelectedRelays)
func didSelectExitRelays(_ relays: UserSelectedRelays)
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: 7 of 12 files reviewed, 8 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 258 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-eaW9r9aVRbFSOmjHh:-O-ejN3M-5K-YKBK0HBU:bp12qrw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L258)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

`LocationCellViewModel` is already comforming `Hashable` which has `Equatable` inside itself. then we can compare two nodes together.
</blockquote></details>

The idea with the name comparison is to make the comparison "softer". If we compare viewmodel to viewmodel, then all items will be strictly unique and only match one location. We want to match all items with the same name as the excluded item in order to put "entry"/"exit" text on all items in both "all locations" section and any custom list.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-ebGnQDR3p9-aefI6w:-O-ekJKW8F6uzmK0ppW1:b-ic08pl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L301)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the above comment goes for here.
</blockquote></details>

After some recent changes, this follows the same idea as the comment above (name matching).
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-O-ec21k60fM__sFtsL0:-O-ekXaz7InqlBN83gsP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7448e59026d8b18501b772384f4904269fadf7ff/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L17)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

`relays` is redundant.
</blockquote></details>

Done.

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 1 of 7 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-:-O09XJIPA4REx3mxAb70:bnfp4nl)* status: all files reviewed, 6 unresolved discussions

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6224#-:-O0DbtzGDjPYromZ8iY5:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

**Pull request merged**
