### PR TITLE
Add info dialog for device name

### PR DESCRIPTION
**Pull request by sabercodic**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmGGCC2L_uB5vmjvr:-NcSmGGCC2L_uB5vmjvs:b-ccl72p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt#L38)):*
> ```Kotlin
> ) {
>     return if (content.isNotEmpty()) {
> ```

This is probably unnecessary to have in this commit.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceNameInfoDialog.kt` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmTTM63H9f-mnxMvP:-NcSmTTM63H9f-mnxMvQ:bwn9u7k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceNameInfoDialog.kt#L15)):*
> ```Kotlin
>                 appendLine(stringResource(id = R.string.device_name_info_part1))
>                 appendLine(stringResource(id = R.string.device_name_info_part2))
>                 appendLine(stringResource(id = R.string.device_name_info_part3))
> ```

Any specific reason on why this needed to be split up in three parts?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 151 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmjF5C0i0oYHJM9ha:-NcSmjF5C0i0oYHJM9hb:b-3zoux7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L151)):*
> ```Kotlin
>                     painter = painterResource(id = R.drawable.icon_info),
>                     contentDescription = null,
>                     tint = MullvadWhite
> ```

User material colors.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmoC15MCXTKqueeI2:-NcSmoC15MCXTKqueeI3:bsqzn4d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L10)):*
> ```Kotlin
>     val accountExpiry: DateTime?
> 
>     data class DefaultUiState(
> ```

Is there a better way to do this?
I know that we use it in VpnSettings, but it feels like it just creates a lot of duplicate code.
Maybe adding a parameter that is called dialogState?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-NcSnmol41PEoLRLrNhI:bors86h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.model.DeviceState
> 
> data class AccountViewModelState(
> ```

Do we need a ViewModel state? Seems like it is adding unneeded complexity.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 151 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmjF5C0i0oYHJM9ha:-NcXvh2s2aEVmLuOVm4I:bfpp871) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L151)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

User material colors.
</blockquote></details>

`MullvadWhite` and other colors have been marked as `Deprecated` or `internal` as of #5034 and should therefore not be used. Instead material colors should be used as mentioned by @Pururun . If not possible we'll discuss it on a case-to-case basis.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcXwvg8E7Lhgp5Sl018:-NcXwvg8E7Lhgp5Sl019:bhr4zu6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38599daaf7a79b46041510486bb084c75c69cfbd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L143)):*
> ```Kotlin
>                 )
>                 val horizontalPadding = Dimens.mediumPadding
>                 val verticalPadding = Dimens.infoButtonVerticalPadding
> ```

Are these `val`s necessary?



_Code quote:_
```Kotlin
                val horizontalPadding = Dimens.mediumPadding
                val verticalPadding = Dimens.infoButtonVerticalPadding
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceNameInfoDialog.kt` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmTTM63H9f-mnxMvP:-NcakCkn6JVm5s-Au0hA:br0s6y3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceNameInfoDialog.kt#L15)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Any specific reason on why this needed to be split up in three parts?
</blockquote></details>

to be same as desktop
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 151 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmjF5C0i0oYHJM9ha:-NcanuDWEKJgVDlfdksB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L151)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

`MullvadWhite` and other colors have been marked as `Deprecated` or `internal` as of #5034 and should therefore not be used. Instead material colors should be used as mentioned by @Pururun . If not possible we'll discuss it on a case-to-case basis.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcXwvg8E7Lhgp5Sl018:-Ncanm2G5N0kyITOLNEq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38599daaf7a79b46041510486bb084c75c69cfbd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L143)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are these `val`s necessary?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmoC15MCXTKqueeI2:-NcaqqK_1hypK_IlqNjM:bxxxzil) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is there a better way to do this?
I know that we use it in VpnSettings, but it feels like it just creates a lot of duplicate code.
Maybe adding a parameter that is called dialogState?
</blockquote></details>

I did it to keep integrity on our architecture, should I change it?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmGGCC2L_uB5vmjvr:-NcakFhg01n5kXSD9cy7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt#L38)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is probably unnecessary to have in this commit.
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcavKxH00vDylCuE-7q:-NcavKxH00vDylCuE-7r:b-l06j1q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8768709174de52866b1514092c94c3c7aad978c8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L136)):*
> ```Kotlin
>                 modifier = Modifier.padding(start = Dimens.sideMargin, end = Dimens.sideMargin)
>             )
>             Row {
> ```

Out of curiosity, why did you have to add this `Row`?



_Code quote:_
```Kotlin
Row {
```

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcavKxH00vDylCuE-7q:-NcaweBf3lXQyHjCW7gd:b-um22lc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8768709174de52866b1514092c94c3c7aad978c8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L136)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Out of curiosity, why did you have to add this `Row`?
</blockquote></details>

to place info icon next to the device name

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-NcbMphfECiBTLfUn-Jy:bxxxzil) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Do we need a ViewModel state? Seems like it is adding unneeded complexity.
</blockquote></details>

I did it to keep integrity on our architecture, should I change it?

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmoC15MCXTKqueeI2:-Ncc7TAEAB2rxk0nHm_r:b-pftwc7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L10)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

I did it to keep integrity on our architecture, should I change it?
</blockquote></details>

I was thinking we should use something else, since when we have used it in VpnSettings it has caused a lot of easy to miss bugs. More or less states are not kept when the dialog is showing.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-Ncc7glW8F7WLzyEbbbl:b-otilcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

I did it to keep integrity on our architecture, should I change it?
</blockquote></details>

See comment above.

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmoC15MCXTKqueeI2:-Nd_NTLy2PnnCIzWWT-s:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I was thinking we should use something else, since when we have used it in VpnSettings it has caused a lot of easy to miss bugs. More or less states are not kept when the dialog is showing.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-Nd_NUQq3jT7hFA98NER:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Done.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmoC15MCXTKqueeI2:-Nd_ckABBtmkS2NtG8Hp:bl5vl7y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L10)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice, I think it's an improvement. I guess from a future-proof perspective I think it could be even better if instead of a boolean for every dialog we could have some kind of dialogState.
So something like this:
```
sealed interface AccountDialogState
data object None: AccountDialogState
data object DeviceInfoDialog: AccountDialogState
```

And then we can add
`val dialogState: AccountDialogState` to `AccountUiState`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-Nd_dqejA-HRoLXlYKqY:b6vpktv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not sure why we need a ui state and a view model state when they are the same. I guess we could move the `dialogState` idea from the view model state here?

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSmoC15MCXTKqueeI2:-Ndk1sdM8ozjkUqQGulv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Nice, I think it's an improvement. I guess from a future-proof perspective I think it could be even better if instead of a boolean for every dialog we could have some kind of dialogState.
So something like this:
```
sealed interface AccountDialogState
data object None: AccountDialogState
data object DeviceInfoDialog: AccountDialogState
```

And then we can add
`val dialogState: AccountDialogState` to `AccountUiState`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-Ndk1tIe924xUuW7M_CF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Still not sure why we need a ui state and a view model state when they are the same. I guess we could move the `dialogState` idea from the view model state here?
</blockquote></details>

Done.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-NdnucnO-3T93soe--yn:bo9mpve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice work. I think it would be better to call the single state UiState, that is what it is called before your PR.

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NcSnmok5K4jlhtgB9P_:-Ne3Jlue22RmlNdvNkLR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4edf1fa56712753053f894ca477b436a397c0469/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelState.kt#L7)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Nice work. I think it would be better to call the single state UiState, that is what it is called before your PR.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-:-Ne3KwBYBuXRSHpXKgXg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 2 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 134 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NeC_cpM4BxZMSzLCf1I:-NeC_cpM4BxZMSzLCf1J:b-na7vdn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7dee1d9555087f61fd6c4447872cf3258f0eaf1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L134)):*
> ```Kotlin
>                 modifier = Modifier.padding(start = Dimens.sideMargin, end = Dimens.sideMargin)
>             )
>             uiState.deviceName?.let {
> ```

Why was this changed? Seems unrelated to adding the dialog. It seems like this would result in not showing the spinner if the device name is null.

This conditional check is also different from below `if (uiState.accountNumber != null) {`



_Code quote:_
```Kotlin
uiState.deviceName?.let {
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 134 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NeC_cpM4BxZMSzLCf1I:-NebHG2g1Y1XCCHMVIJJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7dee1d9555087f61fd6c4447872cf3258f0eaf1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L134)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why was this changed? Seems unrelated to adding the dialog. It seems like this would result in not showing the spinner if the device name is null.

This conditional check is also different from below `if (uiState.accountNumber != null) {`
</blockquote></details>

Done.

**Review by sabercodic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-:-NfAg_EU7l5mYFdQxaYu:bnfp4nl)* status: 4 of 29 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r8, 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 170 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NfKxseaDSir-r2yjFqF:-NfKxseaDSir-r2yjFqG:b-ictsvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9706b740c9bec48114855ca0bfc1c15e4eaaba1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L170)):*
> ```Kotlin
>             if (uiState.accountNumber != null) {
>                 CopyableObfuscationView(content = uiState.accountNumber)
>             }
> ```

Why this `if`-statement? The `CopyableObfuscationView` has a built in spinner which is supposed to be showen the the `content` is empty.



_Code quote:_
```Kotlin
            if (uiState.accountNumber != null) {
                CopyableObfuscationView(content = uiState.accountNumber)
            }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt` line 10 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NfKyzKE7wgnIMfmc_uc:-NfKyzKE7wgnIMfmc_ud:bo8o5mr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9706b740c9bec48114855ca0bfc1c15e4eaaba1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt#L10)):*
> ```Kotlin
>     val deviceName: String,
>     val accountNumber: String?,
>     val accountExpiry: DateTime?,
> ```

Is there a reason for not unifying these properties? Since they are very similar I suggest that either all or none are nullable.



_Code quote:_
```Kotlin
    val deviceName: String,
    val accountNumber: String?,
    val accountExpiry: DateTime?,
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: 26 of 29 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 170 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NfKxseaDSir-r2yjFqF:-NfL6Fcl1787higVhxDN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9706b740c9bec48114855ca0bfc1c15e4eaaba1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L170)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why this `if`-statement? The `CopyableObfuscationView` has a built in spinner which is supposed to be showen the the `content` is empty.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt` line 10 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NfKyzKE7wgnIMfmc_uc:-NfL4MKe3S8Ir0FtTBoM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9706b740c9bec48114855ca0bfc1c15e4eaaba1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a reason for not unifying these properties? Since they are very similar I suggest that either all or none are nullable.
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt` line 10 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NfKyzKE7wgnIMfmc_uc:-NfLNVwl7aLolnO2kICC:b-biv02p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9706b740c9bec48114855ca0bfc1c15e4eaaba1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt#L10)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since it's now nullable, callers should also be updated

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt` line 10 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033#-NfKyzKE7wgnIMfmc_uc:-NfLUwbs3WVb7pLrKbxv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9706b740c9bec48114855ca0bfc1c15e4eaaba1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountUiState.kt#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Since it's now nullable, callers should also be updated
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5033)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
