### PR TITLE
Bump `udp-over-tcp` to 0.2

### PR DESCRIPTION
**Pull request by dlon**
This fixes the issue where `Udp2Tcp::run` doesn't destroy sockets when dropped.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3440)

### CODE REVIEW

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3440#-:-MyvJE6PDN1vX8_cCjhj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by faern** [comment]
Regarding the failing CI. Instead of specifying the options we don't care about explicitly, make them use default, like non-Linux maybe?

```
            TcpOptions {
                fwmark: settings.fwmark,
                ..Default::default(),
            },
```
?

**Review by dlon — COMMENTED** [review]
It used to do just that! Fixed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3440#-:-MyvZWPx2Fhj8GTr96Ez:b-kz9wnj)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @faern)

**Review by faern — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3440#-:-Myvuyr6-xfPrJwBQxVy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
