### PR TITLE
Initialize firewall correctly on Windows

### PR DESCRIPTION
**Pull request by dlon**
`allowed_endpoint_ip` was dropped before a pointer to it was dereferenced. Introduced in #2356.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/firewall/windows.rs, line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373#-MQHcp6j7s1s1M1FYYTG:-MQHcp6j7s1s1M1FYYTH:b-oovmj6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/250fffb2e0f37ac7d6abf6f8f40cd9464b246970/talpid-core/src/firewall/windows.rs#L63)):*
> ```Rust
>             if let Some(allowed_endpoint) = args.allowed_endpoint {
>                 let allowed_endpoint_ip = Self::widestring_ip(allowed_endpoint.address.ip());
>                 let winfw_allowed_endpoint = Some(WinFwEndpoint {
> ```

I think the code could be rewritten so that there's a single call to `WinFW_InitializeBlocked` in this function.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[talpid-core/src/firewall/windows.rs, line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373#-MQHcp6j7s1s1M1FYYTG:-MQIRMFTA2iS0hvjIt2V:b8h875j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/250fffb2e0f37ac7d6abf6f8f40cd9464b246970/talpid-core/src/firewall/windows.rs#L63)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think the code could be rewritten so that there's a single call to `WinFW_InitializeBlocked` in this function.
</blockquote></details>

Done. There might be a simpler solution.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/firewall/windows.rs, line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373#-MQHcp6j7s1s1M1FYYTG:-MQM84gJD7TK8JJZuh52:bu5ivv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/250fffb2e0f37ac7d6abf6f8f40cd9464b246970/talpid-core/src/firewall/windows.rs#L63)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. There might be a simpler solution.
</blockquote></details>

```rust

let allowed_endpoint_ip = args.allowed_endpoint.map(|endpoint| (endpoint, widestring_ip(endpoint.ip()));
let allowed_endpoint = allowed_endpoint_ip.as_ref().map(|(endpoint, ip)|         WinFwEndpoint {
            ip: ip.as_ptr(),
            port: endpoint.address.port(),
            protocol: WinFwProt::from(endpoint.protocol),
        });
```
I kind of lament that we chose to represent IP addresses as strings instead of integer tuples.

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373#-:-MQRRPYn9Gc-ZHj6l2ss:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
