### PR TITLE
Remove forwarded ports code

### PR DESCRIPTION
**Pull request by faern**
We no longer support forwarding ports over the VPN tunnel. So the app can stop parsing the ports in the device data type. We can also stop warning the users on logout if they have forwarded ports (because they by definition can't have that, so it's a dead code path)

Fixes DES-224, DES-223

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5074)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 25 of 36 files at r1, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5074)* status: 26 of 43 files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> Reviewed 11 of 11 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5074)* status: 38 of 43 files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
Android code :lgtm:

Probably unrelated to this PR, but when testing this (still ongoing) my device didn't get revoked when expected. Probably an API issue. Investigating right now...

> Reviewed 22 of 36 files at r1, 2 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5074#-:-NdUGj52C0DsztXGOkx-:b-3fjbeh)* status: 42 of 43 files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5074)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
