### PR TITLE
Update troubleshoot instructions for block failure

### PR DESCRIPTION
**Pull request by raksooo**
After a translator pointed out that this message is a bit unclear we decided to scrap the last part.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/locales/messages.pot` line 1252 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525#-NT8WIH5CCyFlkhLWcOE:-NT8WIH5CCyFlkhLWcOF:b-wi008m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5203329b125ae276078c8a36f4a37b82c5891168/gui/locales/messages.pot#L1252)):*
> ```pot
> 
> msgctxt "troubleshoot"
> msgid "This can happen because the kernel is old."
> ```

As we're already changing the message, I believe something like the following sounds better:

`This might be caused by an outdated kernel.`
or
`This issue might be caused by an outdated kernel.`



_Code quote:_
```pot
This can happen because the kernel is old.
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`gui/locales/messages.pot` line 1252 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525#-NT8WIH5CCyFlkhLWcOE:-NTDLXVS1Do9BA1l246R:bou0pow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5203329b125ae276078c8a36f4a37b82c5891168/gui/locales/messages.pot#L1252)):*
Great idea! I ran this past Matilda as well and she suggested:
> This might be caused by an outdated kernel.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`gui/locales/messages.pot` line 1252 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525#-NT8WIH5CCyFlkhLWcOE:-NTDueRiDT9vZRQCtW-V:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5203329b125ae276078c8a36f4a37b82c5891168/gui/locales/messages.pot#L1252)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Great idea! I ran this past Matilda as well and she suggested:
> This might be caused by an outdated kernel.
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
