### PR TITLE
Add search bar to select location screen

### PR DESCRIPTION
**Pull request by Pururun**
- Filter countries, cities and relays based on search string
- Remove collapsable toolbar and replace with search bar
- Improve expand behavior for relay location cells
- Remove cirular dependency for relays

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 25 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 25 of 41 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyKzjt7RG8j2FJKSdK:-NXyKzjt7RG8j2FJKSdL:b-gpoml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L45)):*
> ```Kotlin
> @Composable
> @Preview
> private fun PreviewRelayLocationCell() {
> ```

This preview function has grown very big, so we should probably consider how to best work with previews in cases like this. We can keep it for now, but would be nice to look into potential improvements before it grows out of control :smile: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyRaB75G6v5UuNpx3V:-NXyRaB75G6v5UuNpx3W:b2xiwam) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L143)):*
> ```Kotlin
>         }
>     val selected = selectedItem == relay
>     val expanded = remember(key1 = relay.expanded.toString()) { mutableStateOf(relay.expanded) }
> ```

I have a problem where (non-selected) items are expanded after re-opening the location selection view.

Steps to reproduce (probably possible to simplify):
1. Open the location selection view.
2. Search for and select a relay.
3. Open the location selection view.
4. Select a country (not related to the previous steps).
5. Open the location selection view.
6. The items related to step 2 will still be expanded.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyUInV6O_-9wjSHgQU:-NXyUInV6O_-9wjSHgQV:b5ywubj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L54)):*
> ```Kotlin
> 
> @Composable
> fun SelectLocationScreen(
> ```

The status bar color doesn't seem to be set atm, which I believe is a regression compared to `main`.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 25 of 44 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyKzjt7RG8j2FJKSdK:-NYTEEZy3iAYlahYRBZ6:b-wr245u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This preview function has grown very big, so we should probably consider how to best work with previews in cases like this. We can keep it for now, but would be nice to look into potential improvements before it grows out of control :smile: 
</blockquote></details>

I manage to make it somewhat simpler since I removed the circular dependency, but yeah we should look into how to make it smaller.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyUInV6O_-9wjSHgQU:-NYTEQL_8xmsz5fAipmK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L54)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The status bar color doesn't seem to be set atm, which I believe is a regression compared to `main`.
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 25 of 44 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyKzjt7RG8j2FJKSdK:-NYTEtmfC92e2daLWLP9:b2aeybj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L45)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I made it somewhat simple, but yeah there should be a make it smaller.
</blockquote></details>

*I manage to make it somewhat simpler since I removed the circular dependency, but yeah we should look into how to make it smaller.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 41 files at r1, 3 of 34 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 10 of 46 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyRaB75G6v5UuNpx3V:-NZzjEj0DM_Vk8pnm_rD:b-3zaj2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L143)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I have a problem where (non-selected) items are expanded after re-opening the location selection view.

Steps to reproduce (probably possible to simplify):
1. Open the location selection view.
2. Search for and select a relay.
3. Open the location selection view.
4. Select a country (not related to the previous steps).
5. Open the location selection view.
6. The items related to step 2 will still be expanded.

</blockquote></details>

Has this been addressed?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 10 of 46 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyRaB75G6v5UuNpx3V:-N_-6Zf66gM5F0Vk7QVh:bubk64d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L143)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Has this been addressed?
</blockquote></details>

I thought changing from `rememberSaveable` to `remember` would have fixed it, but when testing it again it seems to still be there. Will fix.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 10 of 46 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-NXyRaB75G6v5UuNpx3V:-N_3A1322KU1mPOHEX6y:bql6urd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc586db6bc1fb9bfd8ff51cb8b74ad7e72eb125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L143)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I thought changing from `rememberSaveable` to `remember` would have fixed it, but when testing it again it seems to still be there. Will fix.
</blockquote></details>

Should be fixed now.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 41 files at r1, 2 of 6 files at r2, 27 of 34 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 40 of 46 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 301 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_481YF1syQfFfDPtCH:-N_481YF1syQfFfDPtCI:b-oc8tp0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff66a3545b42cd73377cf24246b598e7239985e1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L301)):*
> ```Kotlin
>                 ExpandableComposeCell(
>                     title = stringResource(R.string.dns_content_blockers_title),
>                     isExpanded = !expandContentBlockersState,
> ```

Can you elaborate on why this was removed? Was it wrong before? If it's correct, we should probably rename something to match the changed logic.



_Code quote:_
```Kotlin
!
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt` line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_47TjF2G0ADwW_EId-:-N_47TjF2G0ADwW_EId0:b4s2wda) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3880d389298387bd2bc60754bd3392685393b9b3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt#L34)):*
> ```Kotlin
>                     val backgroundColor = MaterialTheme.colorScheme.background
>                     val systemUiController = rememberSystemUiController()
>                     SideEffect {
> ```

Should `SideEffect` always be used to set the color of status/navigation bar color? In that case we should probably update in some other place immediately or create a separate issue for that.



_Code quote:_
```Kotlin
SideEffect
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 40 of 46 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 301 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_481YF1syQfFfDPtCH:-N_4ICt_5ylqfx7xgPen:bdto9nt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff66a3545b42cd73377cf24246b598e7239985e1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L301)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can you elaborate on why this was removed? Was it wrong before? If it's correct, we should probably rename something to match the changed logic.
</blockquote></details>

There was a bug in ChevronView that meant that it was turned upside down to the expected state. I fixed that in ChevronView. Since that was fixed I had to reverse the state in VpnSettingsScreen were the state was inverted for some reason. Probably to correct for the bug in ChevronView.

Will split this change into separate commit.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt` line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_47TjF2G0ADwW_EId-:-N_4MmiUBJAAQ8U5oZPt:bshs7mk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3880d389298387bd2bc60754bd3392685393b9b3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt#L34)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should `SideEffect` always be used to set the color of status/navigation bar color? In that case we should probably update in some other place immediately or create a separate issue for that.
</blockquote></details>

Will check what's the current best practice.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 36 of 48 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/SearchTextField.kt` line 55 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_4Q7oWC2YGrEQaYznI:-N_5yXtF297Si03YRqDy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a83edf4517f0cb138a4480f1d3d44289e3dfa0d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/SearchTextField.kt#L55)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming this to something like `searchTerm` to improve readability
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 63 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_4QRj89h4eU3hsCm6A:-N_5yYnVC_gc82NrHVDt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a83edf4517f0cb138a4480f1d3d44289e3dfa0d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L63)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing to something like `onSearchTermInput` to clarify that it's triggered by text input
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 29 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_4SWJ6AFLHW_io6UOr:-N_5zA61DYzcSTy3iVmt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a83edf4517f0cb138a4480f1d3d44289e3dfa0d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using a const called `EMPTY_FILTER`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 71 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_4SnKl6UJ4Nc3TZPk4:-N_5zB7j29YabUM6dEUY:b-1z2ce8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a83edf4517f0cb138a4480f1d3d44289e3dfa0d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L71)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There's a mix of `search` and `filter` to refer to this functionality/value. I believe it would be best to stick with `search`/`searchTerm` since that's what's used in our documentation and desktop implementation. Also, we will have other filters for things like ownership and provider, and it would be great to avoid any confusion between the two.

In this case I believe the following function signature would be an improvement:

```
fun onSearchTermInput(searchTerm: String)
```

This comment also applies to some other parts of this PR.
</blockquote></details>

Replaced most `filter` with `searchTerm`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt` line 9 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_4VW1T2JZ4CICK_YJZ:-N_5yb6cCsCmHYMbK-pt:btai9qm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a83edf4517f0cb138a4480f1d3d44289e3dfa0d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm aware that this isn't something new, but the duplicate naming is very confusing.
</blockquote></details>

Removed the relaylist.RelayList since it's just a wrapper around List<RelayCountry>.
Also we no longer care about keeping the internal state of the list so just moved the functions in the list to extension functions.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt` line 94 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_4VyHU6q-kAbPE0Pzo:-N_5z1umCsJK61cgEXtk:bj148pf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a83edf4517f0cb138a4480f1d3d44289e3dfa0d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt#L94)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is it possible to move this logic out of this class? I believe it would be good to keep this class as simple as possible and put complex filter/search logic etc somewhere else.
</blockquote></details>

Moved to extension functions, see motivation above.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 41 files at r1, 1 of 1 files at r7, 1 of 1 files at r8, 9 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt` line 32 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_7y-rD7R6WfYNqI81r:-N_7y-rD7R6WfYNqI81s:b-h7dcrd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28249bacc16db0a246e0c7bd8270dcf84f6b29ac/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt#L32)):*
> ```Kotlin
>                 AppTheme {
>                     val statusBarColor = MaterialTheme.colorScheme.background
>                     val navigationBarColor = MaterialTheme.colorScheme.background
> ```

I suggest using the material colors directly unless there's a good reason to define additional `val`s



_Code quote:_
```Kotlin
                    val statusBarColor = MaterialTheme.colorScheme.background
                    val navigationBarColor = MaterialTheme.colorScheme.background
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 47 of 48 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 1 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_8Kmh168jGG4OXk-SG:-N_8Kmh168jGG4OXk-SH:b-ns6zkf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c20ae87f6791512848247716d7ebbd29aeae6ca3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.relaylist
> ```

As discussed, it would be great if you can add some comments to explain some of the logic in this file since it's quite complex.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 131 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_8KhtI4m_gS0qD7RA3:-N_8KhtI4m_gS0qD7RA4:b-be0a4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c20ae87f6791512848247716d7ebbd29aeae6ca3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L131)):*
> ```Kotlin
>             }
>         }
>         return filteredCountries.values.sortedBy { it.name }
> ```

Skip redundant `return` statement
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 133 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_8KeNt4niE2PmaF6xe:-N_8KeNt4niE2PmaF6xf:b-be0a4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c20ae87f6791512848247716d7ebbd29aeae6ca3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L133)):*
> ```Kotlin
>         return filteredCountries.values.sortedBy { it.name }
>     } else {
>         return this.expandItemForSelection(selectedItem)
> ```

Skip redundant `return` statement

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: 46 of 48 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt` line 32 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_7y-rD7R6WfYNqI81r:-N_8RsKvDGT2PV0X5I17:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28249bacc16db0a246e0c7bd8270dcf84f6b29ac/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using the material colors directly unless there's a good reason to define additional `val`s
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 1 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_8Kmh168jGG4OXk-SG:-N_8RoH0CilKd2hSXIrh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c20ae87f6791512848247716d7ebbd29aeae6ca3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As discussed, it would be great if you can add some comments to explain some of the logic in this file since it's quite complex.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 131 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_8KhtI4m_gS0qD7RA3:-N_8RrYi6f38hsA5SacM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c20ae87f6791512848247716d7ebbd29aeae6ca3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L131)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip redundant `return` statement
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 133 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791#-N_8KeNt4niE2PmaF6xe:-N_8RrmS06RoaGO-tO9C:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c20ae87f6791512848247716d7ebbd29aeae6ca3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L133)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip redundant `return` statement
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 2 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4791)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
