### PR TITLE
Automatic MTU detection Windows

### PR DESCRIPTION
**Pull request by Serock3**
Fixes DES-583.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: all files reviewed, 7 unresolved discussions (waiting on @Serock3)

___
*[`talpid-core/src/tunnel/mod.rs` line 179 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-NptsiEM3jSTUJZlfQGw:-NptsiEM3jSTUJZlfQGx:b-dqzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-core/src/tunnel/mod.rs#L179)):*
> ```XML
>             .unwrap_or(default_mtu);
> 
>         #[cfg(any(target_os = "linux", windows))]
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(any(target_os = "linux", target_os = "windows"))]
```



_Code quote:_
```XML
#[cfg(any(target_os = "linux", windows))]
```
___
*[`talpid-core/src/tunnel/mod.rs` line 186 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptsehd7lcCoCuPb1iW:-Nptsehd7lcCoCuPb1iX:b-dqzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-core/src/tunnel/mod.rs#L186)):*
> ```XML
>             config,
>             params.options.quantum_resistant,
>             #[cfg(any(target_os = "linux", windows))]
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(any(target_os = "linux", target_os = "windows"))]
```



_Code quote:_
```XML
#[cfg(any(target_os = "linux", windows))]
```
___
*[`talpid-wireguard/src/lib.rs` line 272 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptsr8LAGjW8kPJORIV:-Nptsr8LAGjW8kPJORIW:b-dqzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-wireguard/src/lib.rs#L272)):*
> ```XML
>         mut config: Config,
>         psk_negotiation: bool,
>         #[cfg(any(target_os = "linux", windows))] detect_mtu: bool,
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(any(target_os = "linux", target_os = "windows"))]
```



_Code quote:_
```XML
#[cfg(any(target_os = "linux", windows))]
```
___
*[`talpid-wireguard/src/lib.rs` line 392 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-NptssVqBoNy9SxZbITg:-NptssVqBoNy9SxZbITh:b-dqzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-wireguard/src/lib.rs#L392)):*
> ```XML
>             }
> 
>             #[cfg(any(target_os = "linux", windows))]
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(any(target_os = "linux", target_os = "windows"))]
```



_Code quote:_
```XML
#[cfg(any(target_os = "linux", windows))]
```
___
*[`talpid-wireguard/src/lib.rs` line 416 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptt22B2eML63zFLeZU:-Nptt22B2eML63zFLeZV:b-e1u5o9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-wireguard/src/lib.rs#L416)):*
> ```XML
>                         #[cfg(target_os = "linux")]
>                         let res = unix::set_mtu(&iface_name_clone, verified_mtu);
>                         #[cfg(windows)]
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(target_os = "windows")]
```



_Code quote:_
```XML
#[cfg(windows)]
```
___
*[`talpid-wireguard/src/lib.rs` line 1006 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-NpttfXPCTR9d9CPq_Bv:-NpttfXPCTR9d9CPq_Bw:b-dqzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-wireguard/src/lib.rs#L1006)):*
> ```XML
> /// The detection works by sending evenly spread out range of pings between 576 and the given
> /// current tunnel MTU, and returning the maximum packet size that war returned within a timeout.
> #[cfg(any(target_os = "linux", windows))]
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(any(target_os = "linux", target_os = "windows"))]
```



_Code quote:_
```XML
#[cfg(any(target_os = "linux", windows))]
```
___
*[`talpid-wireguard/src/lib.rs` line 1083 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptu2BU7AhMQBw-eLHg:-Nptu2BU7AhMQBw-eLHh:b-dqzx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-wireguard/src/lib.rs#L1083)):*
> ```XML
> /// Creates a linear spacing of MTU values with the given step size. Always includes the given end
> /// points.
> #[cfg(any(target_os = "linux", windows))]
> ```

Nit: specify Windows compilation target with `target_os` for consistency

```rust
#[cfg(any(target_os = "linux", target_os = "windows"))]
```



_Code quote:_
```XML
#[cfg(any(target_os = "linux", windows))]
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-tunnel/src/windows.rs` line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptb_Mp1cdQYsTLVslg:-Nq1akJPELEdYyh6PgFC:bye04lv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-tunnel/src/windows.rs#L40)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could arguably be moved to `talpid-windows`.
</blockquote></details>

I may agree, but I think that the `initialize_interfaces` function above is so similar that it should also be moved in that case. What do you think about moving both of them to `talpid-windows/src/net.rs`?

**Review by Serock3 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-:-Nq1iUTaCfVtWWuMGpDn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-tunnel/src/windows.rs` line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptb_Mp1cdQYsTLVslg:-Nq9c7DY0q3y5ft8x20E:bk29pgx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-tunnel/src/windows.rs#L40)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I may agree, but I think that the `initialize_interfaces` function above is so similar that it should also be moved in that case. What do you think about moving both of them to `talpid-windows/src/net.rs`?
</blockquote></details>

The other one is bespoke: set MTU, metric, disable DAD, etc. `talpid-windows` is general. So I don't think they both belong there

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @dlon and @MarkusPettersson98)

___
*[`talpid-tunnel/src/windows.rs` line 40 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759#-Nptb_Mp1cdQYsTLVslg:-NqD8Lq59r-58AkQIxDA:b-73pf0w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f38150d997deb6eb4c0b59d01fb6bc9c996fa5d/talpid-tunnel/src/windows.rs#L40)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The other one is bespoke: set MTU, metric, disable DAD, etc. `talpid-windows` is general. So I don't think they both belong there
</blockquote></details>

I moved the function

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
