### PR TITLE
Update tonic to 0.8 and prost to 0.11

### PR DESCRIPTION
**Pull request by pinkisemils**
As per the title, updating the tonic and prost dependencies.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`Cargo.lock` line 1028 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCQQ0yj3NCnhszP-rjf:-NCQQ0yj3NCnhszP-rjg:b-qifa2g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0320056859193cc058f57380261dcc0ab1ef12b3/Cargo.lock#L1028)):*
> ```TOML
>  "slab",
>  "tokio",
>  "tokio-util 0.6.10",
> ```

Can `h2` be updated as well? To get rid of the old `tokio-util`.

**Review by pinkisemils — COMMENTED** [review]
I'll refrain from merging this until after we know that this won't bork the buildservers.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-:-NCQXAKZ1h0syHcSk3S5:b-vexhuf)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`Cargo.lock` line 1028 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCQQ0yj3NCnhszP-rjf:-NCQX7jx3fVf7MbnPAO5:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0320056859193cc058f57380261dcc0ab1ef12b3/Cargo.lock#L1028)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can `h2` be updated as well? To get rid of the old `tokio-util`.
</blockquote></details>

Done

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: 6 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`README.md` line 323 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0m28Eyu_q2tZYKD6:-NCU0m28Eyu_q2tZYKD7:b-h7nufx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L323)):*
> ```Markdown
>    ```
> 
> 1. *This can be skipped for Android builds*.
> ```

Can we please avoid this format? It's not ideal above either, so we should not duplicate it.

We really need to go ahead with ripping out the Android instructions from this document. Because this is messy. We have a card for it.
___
*[`README.md` line 325 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0sdZ-ieUarzkd4FP:-NCU0sdZ-ieUarzkd4FQ:b-s68cd6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L325)):*
> ```Markdown
> 1. *This can be skipped for Android builds*.
> 
>   A recent version of the protobuf compiler (3.15.6 works), it can be installed on most major Linux
> ```

I think it's way easier to read if formulated like "You need a ..." like how the bash, rust, go etc steps above and below are formulated. It's harder to read individual list items if you have to implicitly read out "you will need a ..." in your head before starting to read the content.
___
*[`README.md` line 327 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU1gr03AUbkOHusmYE:-NCU1gr03AUbkOHusmYF:b4v4wo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L327)):*
> ```Markdown
>   A recent version of the protobuf compiler (3.15.6 works), it can be installed on most major Linux
>   distros via the package name `protobuf-compiler`, `protobuf` on macOS, and on Windows installers
>   are available on their GitHub [page](https://github.com/protocolbuffers/protobuf/releases).
> ```

Is the homebrew version of protobuf no good any longer? Or why do we change to recommending the github releases here?

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`README.md` line 323 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0m28Eyu_q2tZYKD6:-NCU2vC2445Lcixt2inC:bt2ah8u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L323)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we please avoid this format? It's not ideal above either, so we should not duplicate it.

We really need to go ahead with ripping out the Android instructions from this document. Because this is messy. We have a card for it.
</blockquote></details>

It's also not true, as we need protoc for PQ-safe tunnels on Android as well.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`README.md` line 323 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0m28Eyu_q2tZYKD6:-NCU3jFs0hP7U-tY6Wra:b-rjxy56) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L323)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's also not true, as we need protoc for PQ-safe tunnels on Android as well.
</blockquote></details>

That's true! Not that we use it yet, but I guess we hope to introduce it soon enough that it's not worth optimizing out either.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 8 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`README.md` line 324 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCUV4vXC9C_dEpZlae8:-NCUV4vXC9C_dEpZlae9:bscok4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/363b66df95aff7b4d66d8790cd9d715ad0fad5a5/README.md#L324)):*
> ```Markdown
> 
> 1. A protobuf compiler (version 3.15.6 and up), it can be installed on most major Linux distros via
>    the package name `protobuf-compiler`, `protobuf` on macOS via Homebrew, and on Windows installers
> ```

This seems a bit vague. I don't see any "installers" for Windows. I see a bunch of zip files. I assume what you need to do is extract `protoc-*-win64.zip` somewhere and add the directory to `PATH`. I don't know how detailed our instructions need to be, though.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[`README.md` line 324 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCUV4vXC9C_dEpZlae8:-NCU_VbH8rL4l3gKKZwH:b-3oiqy3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/363b66df95aff7b4d66d8790cd9d715ad0fad5a5/README.md#L324)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This seems a bit vague. I don't see any "installers" for Windows. I see a bunch of zip files. I assume what you need to do is extract `protoc-*-win64.zip` somewhere and add the directory to `PATH`. I don't know how detailed our instructions need to be, though.
</blockquote></details>

You are correct, but I'm not sure if that's the correct place to mention this. I personally install it via `choco`, but I think there's only a handful of people doing stuff like that.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`README.md` line 325 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0sdZ-ieUarzkd4FP:-NCZSNc5C5NgdOMbfKhK:b2nhkyh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L325)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`README.md` line 325 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0sdZ-ieUarzkd4FP:-NCZsx2YDIMjlKag7V2B:b-1e7fvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L325)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

No?
</blockquote></details>

Should it be changed to "You need a protobuf compiler` ? I'm still unclear as to what changes you want to see here.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`README.md` line 325 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0sdZ-ieUarzkd4FP:-NCe9sfM4CeEI83E2MUG:bly39u9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L325)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should it be changed to "You need a protobuf compiler` ? I'm still unclear as to what changes you want to see here.
</blockquote></details>

Exactly. "A protobuf compiler" is not a complete instruction. A protobuf compiler is what? "A protobuf compiler of version at least X is needed" would be an instruction that worked, but slightly backwards written IMO.

I'd like each item in this list to be of the form "Make sure you have a ..." or "Install a ..." or similar.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`README.md` line 325 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-NCU0sdZ-ieUarzkd4FP:-NCuWynV15PShjv-gExt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729af2d5013c1e2f7859972e57d6ee505662fdd7/README.md#L325)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Exactly. "A protobuf compiler" is not a complete instruction. A protobuf compiler is what? "A protobuf compiler of version at least X is needed" would be an instruction that worked, but slightly backwards written IMO.

I'd like each item in this list to be of the form "Make sure you have a ..." or "Install a ..." or similar.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by faern — APPROVED** [review]
:lgtm: Looks good! And the build servers are ready for this now.

> Reviewed 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945#-:-NCzHK8PBtAsYIk5UrfX:b-bro2qf)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
