### PR TITLE
Improve notifications

### PR DESCRIPTION
**Pull request by raksooo**
This PR improves the notifications to make sure users don't miss important notification and to not spam users with a lot of notifications, e.g. while connecting. The changes include:
* Change notification type on macOS to banner to make it move to notification center
* Don't automatically close notifications after 4s, instead let OS move it to notification list or whatever it wants to do
* Automatically close notifications within the same category when new notification with catergory is shown
* Throttle some notifications like tunnel state to avoid showing up to three notifications within half a second
* Add severity scale to system notifications instead of `critical` bool
* Add notification dot to tray icon if notifications of severity >= medium is active

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)

### CODE REVIEW

**Review by hankolsen — APPROVED** [review]
> Reviewed 113 of 113 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/scripts/generate-menubar-icons.sh` line 167 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278#-NLtYwMd0cP_rcLC4Zuo:-NLtYwMd0cP_rcLC4Zup:byald1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa46799c00800e6c81beba9c0e1ea81640b2acc6/gui/scripts/generate-menubar-icons.sh#L167)):*
> ```Shell
> 
>     # Windows colored
>     local windows_target_path="$WINDOWS_DIR/$icon_name"
> ```

Nit:

1. I suggest renaming to `windows_target_base_path` or similar to clarify that it's a partial path.
2. As it's used for both colored and monochrome, perhaps it makes sense to group things in another way. Perhaps move all "base" path definitions to the top of the function?

This comment also applies to the sections for macos and linux in this function.



_Code quote:_
```Shell
local windows_target_path="$WINDOWS_DIR/$icon_name"
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)* status: 111 of 113 files reviewed, all discussions resolved (waiting on @hankolsen)

___
*[`gui/scripts/generate-menubar-icons.sh` line 167 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278#-NLtYwMd0cP_rcLC4Zuo:-NM40pIV0Y029fdLjEeG:bmfxgaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa46799c00800e6c81beba9c0e1ea81640b2acc6/gui/scripts/generate-menubar-icons.sh#L167)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nit:

1. I suggest renaming to `windows_target_base_path` or similar to clarify that it's a partial path.
2. As it's used for both colored and monochrome, perhaps it makes sense to group things in another way. Perhaps move all "base" path definitions to the top of the function?

This comment also applies to the sections for macos and linux in this function.
</blockquote></details>

Done :)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278#-:-NM4Fkvc-uHWjim04olZ:bnfp4nl)* status: 112 of 113 files reviewed, all discussions resolved (waiting on @hankolsen)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)* status: 20 of 163 files reviewed, 1 unresolved discussion (waiting on @hankolsen and @raksooo)

___
*[`gui/scripts/generate-menubar-icons.sh` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278#-NNGGZ638jGpxyZlkdok:-NNGGZ638jGpxyZlkdol:b-7hak7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/43d32e3eea8158c7728fde1cd3eb57ba9d161330/gui/scripts/generate-menubar-icons.sh#L50)):*
> ```Shell
> }
> 
> function generate_ico() {
> ```

As this script has grown in terms of both lines and functions, it would be great to add a short function comment describing each new and existing function (except main), like was done for some of the new functions such as `generate_rectangle`.



_Code quote:_
```Shell
function generate_ico() {
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)* status: 17 of 163 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @hankolsen)

___
*[`gui/scripts/generate-menubar-icons.sh` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278#-NNGGZ638jGpxyZlkdok:-NNaKzetBIC8LCKwFAYi:b2ifwk0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/43d32e3eea8158c7728fde1cd3eb57ba9d161330/gui/scripts/generate-menubar-icons.sh#L50)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As this script has grown in terms of both lines and functions, it would be great to add a short function comment describing each new and existing function (except main), like was done for some of the new functions such as `generate_rectangle`.
</blockquote></details>

Great idea! Done

**Review by hankolsen — APPROVED** [review]
> Reviewed 41 of 122 files at r3, 51 of 102 files at r4, 54 of 54 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

Nice job with the added comments!

> Reviewed 1 of 54 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4278#-:-NNfk1yV8opL-vOu76D-:bb71x21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
