### PR TITLE
Add key negotiation state

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR adds the ability to dynamically toggle the PQC on and off

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)

### CODE REVIEW

**Review by acb-mv — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiatior.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-NtpwLmBCZiptm94qYXd:-NtpwLmBCZiptm94qYXe:b-rs43c9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f658870d4962200ac4930eb317a25115b1f57d8/ios/MullvadPostQuantum/PostQuantumKeyNegotiatior.swift#L36)):*
> ```Swift
>             opaqueConnection
>         )
>         guard token?.hashValue != 0.hashValue else {
> ```

It looks like in Swift, `UnsafeMutableRawPointer` is not nullable, so we should probably see if we can make the FFI take an optional of this.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 8 of 19 files reviewed, 1 unresolved discussion (waiting on @acb-mv and @buggmagnet)

___
*[`.github/workflows/git-commit-message-style.yml` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nu-92CgE0U87rVP0adj:-Nu-92CgE0U87rVP0adk:b-8b815n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52690ba8c87eae3e0dfd551b41fbfb262dac9f46/.github/workflows/git-commit-message-style.yml#L32)):*
> ```YAML
>           max-subject-line-length: '72'
>           # The action's wordlist is a bit short. Add more accepted verbs
>           additional-verbs: 'restart, coalesce, tidy'
> ```

Did you ask @faern or anyone else for their opinion on this? I don't disagree with the change, but everyone should be on board with changes here :slightly_smiling_face:

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`.github/workflows/git-commit-message-style.yml` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nu-92CgE0U87rVP0adj:-Nu-DwTk8Ga0yAmV0NlG:b4v92z4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52690ba8c87eae3e0dfd551b41fbfb262dac9f46/.github/workflows/git-commit-message-style.yml#L32)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Did you ask @faern or anyone else for their opinion on this? I don't disagree with the change, but everyone should be on board with changes here :slightly_smiling_face:
</blockquote></details>

I messaged him on Slack with a link to the commit, though after the fact.

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`.github/workflows/git-commit-message-style.yml` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nu-92CgE0U87rVP0adj:-Nu-M0b95s1OpbTsa6UQ:bmhmk8l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52690ba8c87eae3e0dfd551b41fbfb262dac9f46/.github/workflows/git-commit-message-style.yml#L32)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

I messaged him on Slack with a link to the commit, though after the fact.
</blockquote></details>

He replied, and seems OK with the addition. https://mullvad.slack.com/archives/D06M20B17F0/p1711547132418499

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @acb-mv and @pinkisemils)

___
*[`.github/workflows/git-commit-message-style.yml` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nu-92CgE0U87rVP0adj:-Nu-R6Qf9RYGlSNOt6AX:b-ii4zsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52690ba8c87eae3e0dfd551b41fbfb262dac9f46/.github/workflows/git-commit-message-style.yml#L32)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

He replied, and seems OK with the addition. https://mullvad.slack.com/archives/D06M20B17F0/p1711547132418499
</blockquote></details>

Adding reasonable imperative verbs is OK! The list is not complete. However, given that I have scraped all imperative verbs from our 20k+ commit history I hope there won't be too many more :sweat_smile:.

Nit: I think you should add this in a separate PR. Separate things separate. And you can get that PR done and merged in a few minutes.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadPostQuantum/talpid-tunnel-config-client/src/ios_ffi.rs` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nu-_IRoDLOu4okHilWD:-Nu-_IRoDLOu4okHilWE:b-yt53x2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52690ba8c87eae3e0dfd551b41fbfb262dac9f46/ios/MullvadPostQuantum/talpid-tunnel-config-client/src/ios_ffi.rs#L13)):*
> ```XML
> pub unsafe extern "C" fn cancel_post_quantum_key_exchange(sender: *const c_void) {
>     // Try to take the value, if there is a value, we can safely send the message, otherwise, assume it has been dropped and nothing happens
>     let send_tx: Weak<mpsc::Sender<()>> = unsafe { Weak::from_raw(sender as _) };
> ```

We're using an `rc::Weak` whereas the pointer that is actually being passed here is pointing to an `sync::Weak`. This is not sound.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 8 of 20 files reviewed, 2 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadPostQuantum/talpid-tunnel-config-client/src/lib.rs` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nu-a9_G-hJqvWsoIx7w:-Nu-a9_G-hJqvWsoIx7x:buol0pq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52690ba8c87eae3e0dfd551b41fbfb262dac9f46/ios/MullvadPostQuantum/talpid-tunnel-config-client/src/lib.rs#L28)):*
> ```XML
>     packet_tunnel: *const c_void,
>     tcp_connection: *const c_void,
> ) -> *const c_void {
> ```

Instead of returning a `c_void`, I'd define a struct that wraps the pointer so that the Swift side can be somewhat more typesafe. Using void pointers gets confusing quickly.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 3 of 160 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`Cargo.toml` line 14 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nv0sNKF44adF_I8kkBs:-Nv0sNKGDRub8XWmkRvc:b-vkgji6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4914ec8105f777bb6d595b8648003aa7b75b3552/Cargo.toml#L14)):*
> ```TOML
>     "ios/MullvadREST/Transport/Shadowsocks/shadowsocks-proxy",
>     "ios/TunnelObfuscation/tunnel-obfuscator-proxy",
>     "ios/MullvadPostQuantum/talpid-tunnel-config-client",
> ```

Might not be ideal to have multiple Rust crates with the exact same name. If a crate is needed here, consider naming it uniquely. But if they have a relationship, make that apparent in a good way :pray:

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021)* status: 3 of 160 files reviewed, 6 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadPostQuantum/talpid-tunnel-config-client/build.rs` line 2 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nv0vQvD9MfBrou0lQ9O:-Nv0vQvD9MfBrou0lQ9P:b271wvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4914ec8105f777bb6d595b8648003aa7b75b3552/ios/MullvadPostQuantum/talpid-tunnel-config-client/build.rs#L2)):*
> ```XML
> fn main() {
>     tonic_build::compile_protos("../../../talpid-tunnel-config-client/proto/tunnel_config.proto")
> ```

There should be no reason to compile these proto files twice. This crate depend on `talpid-tunnel-config-client` and that crate alread build this proto file. Both should definitely not do it.
___
*[`ios/MullvadPostQuantum/talpid-tunnel-config-client/Cargo.toml` line 2 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6021#-Nv0vFATA489LWZXR8oT:-Nv0vFATA489LWZXR8oU:bhhge0p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4914ec8105f777bb6d595b8648003aa7b75b3552/ios/MullvadPostQuantum/talpid-tunnel-config-client/Cargo.toml#L2)):*
> ```TOML
> [package]
> name = "talpid-tunnel-config-client-proxy"
> ```

As discussed in the office. I'm very hesitant towards having this wrapper crate or whatever you want to call it. It should at least not depend on all the crypt libs *again*. There is no reason to depend on them twice.

**Pull request merged**
