### PR TITLE
Fix toggletunnel crash in tile

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 206 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5XYhP5EfYq5QkSdC69:-O5XYhP5EfYq5QkSdC6A:b-eho602) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f1d9dd3bf9dab8bd9e08daac7f36980b3c332dfb/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L206)):*
> ```Kotlin
>                 if (bindCount.get() == 0) {
>                     Logger.i("Stopping service")
>                     stopSelf()
> ```

Can we somehow document the identified behavior where we'll no longer call `stopSelf` where it logically could make sense?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 206 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5XYhP5EfYq5QkSdC69:-O5Y941_1iEZKoioIeJe:b-llmy3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f1d9dd3bf9dab8bd9e08daac7f36980b3c332dfb/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L206)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we somehow document the identified behavior where we'll no longer call `stopSelf` where it logically could make sense?
</blockquote></details>

This has been reworked now

**Review by Pururun — APPROVED** [review]
> Reviewed 4 of 19 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 19 files at r1, 15 of 15 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)* status: 18 of 19 files reviewed, 5 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 96 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YH4vx-Y_SCoZ6QLy9:-O5YH4vyBIAepi2990lg:b-nuazjz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L96)):*
nit: suggested rephrasing:

> If the service is started with a connect command and a non-blocking error occur (e.g. unable to start the tunnel) then the service is demoted from foreground.



_Code quote:_
```Kotlin
            // In cases where we start to connect but result in a non-blocking error (we wasn't able
            // to start the tunnel), we should stop the foreground notification.
```
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 110 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YGxrY3w6qtnQll2gy:-O5YGxrY3w6qtnQll2gz:bnhua55) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0c1bcc5b49aa83c80dc125980f8ab745008397e/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L110)):*
Is this check no longer needed? How do we ensure we don't add the check again in the future? Can we document it somehow? Something along the lines of:

> Promote service to foreground regardless of having the vpn permission or not due to...



_Code quote:_
```Kotlin
if (prepare(this) == null)
```
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 126 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YIYbyBk5nSpGKi-wY:-O5YIYbyBk5nSpGKi-wZ:b-igng1v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L126)):*
> ```Kotlin
> 
>             intent?.action == KEY_DISCONNECT_ACTION -> {
>                 // Tile might of launched the service with the expectancy to be in foreground, thus
> ```

nit: have?



_Code quote:_
```Kotlin
of
```
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 132 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YIecZBBZaJnI58Gbq:-O5YIecZBBZaJnI58Gbr:b7t139p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L132)):*
> ```Kotlin
> 
>                 // If disconnect intent is received and no one is using this service, simply stop
>                 // foreground.
> ```

Can we further clarify why a `stopSelf` isn't necessary? (continuation of a previous comment)



_Code quote:_
```Kotlin
                // If disconnect intent is received and no one is using this service, simply stop
                // foreground.
```
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt` line 115 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YFNAtAVaJDGC5Wy2p:-O5YFNAtAVaJDGC5Wy2q:b-qaq4a4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt#L115)):*
> ```Kotlin
>         val cause = errorState.cause
>         return when {
>             cause is ErrorStateCause.IsOffline && errorState.isBlocking ->
> ```

Why was this not enough?



_Code quote:_
```Kotlin
ErrorStateCause.IsOffline
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)* status: 18 of 19 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 110 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YGxrY3w6qtnQll2gy:-O5YMZs11G-psywq5qu-:b-mzjwt9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0c1bcc5b49aa83c80dc125980f8ab745008397e/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L110)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this check no longer needed? How do we ensure we don't add the check again in the future? Can we document it somehow? Something along the lines of:

> Promote service to foreground regardless of having the vpn permission or not due to...
</blockquote></details>

The permission check was duplicate, it still happens within startForeground. In the case where we click "connect" on the tile (and we would need to start in foreground) the permission check has already been done by the tile and the app will just open.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 126 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YIYbyBk5nSpGKi-wY:-O5YLywj-H0X0auCvvb-:b-3r5iee) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L126)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: have?
</blockquote></details>

Clarified the sentence a bit.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 132 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YIecZBBZaJnI58Gbq:-O5YMTg7-V8DzjdI8ci_:bhuu6lo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L132)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we further clarify why a `stopSelf` isn't necessary? (continuation of a previous comment)
</blockquote></details>

Clarified
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt` line 115 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-O5YFNAtAVaJDGC5Wy2p:-O5YMI5KABSODwDLOgOp:btfcsc2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33edffed0d542ef0cf1735e2e14de8125d396182/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt#L115)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why was this not enough?
</blockquote></details>

Unfortunately not, if we don't check that if we are blocking we are saying "Blocking Internet due to offline" however we don't have the VPN and are not blocking the connection

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709#-:-O5YZB1Z2O_LmzzXe9OG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
