### PR TITLE
Improve rpc file permission error message

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/86)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 20 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pQbtB-syYLqWDBj1T:-L6pQbtB-syYLqWDBj1U:bslb8ic) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/CHANGELOG.md#L20)):*
> ```Markdown
> ### Changed
> - Redact all account numbers in the account number history from problem reports instead of only the currently logged in one.
> - Add details to mullvad CLI interface error for when it doesn't trust the RPC file.
> ```

These comments are actually added under the wrong headline. Not your fault at all. The thing is we branched off for the `2018.1-betaX` releases and never added those headlines here. So the things you here see as `[Unreleased]` is actually already released. I fix this in two of my PRs, which is why I'm eager to get them merged asap to restore this problem :)

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6pR4UOEO-VC9y-GtbC:b5xr9yy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
> ```Rust
> 
> #[cfg(unix)]
> fn check_if_rpc_file_can_be_trusted(metadata: Metadata) -> Result<()> {
> ```

I think this new name became a bit too verbose. It was also far from perfect before, so not your fault. But if it's going to be renamed anyway we can correct previous problem as well :).
The `rpc_file` part of the name was a bit redundant since it's kind of given by the module already. I would describe the intention of the function as "make sure file was written by admin". Suggestion for name: `check_written_by_admin`. `check` can also be `verify`.

Replacing "trusted" with "written by admin" much more clearly conveys what the intention is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by jvff** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 20 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pQbtB-syYLqWDBj1T:-L6ppDPtbDR9TV2nIS6P:b8td1j8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/CHANGELOG.md#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These comments are actually added under the wrong headline. Not your fault at all. The thing is we branched off for the `2018.1-betaX` releases and never added those headlines here. So the things you here see as `[Unreleased]` is actually already released. I fix this in two of my PRs, which is why I'm eager to get them merged asap to restore this problem :)
</blockquote></details>

Should I create a new section, or wait until the PRs are merged to rebase the change?

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6por8IMHXtBVimpmkD:bfyzl3u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think this new name became a bit too verbose. It was also far from perfect before, so not your fault. But if it's going to be renamed anyway we can correct previous problem as well :).
The `rpc_file` part of the name was a bit redundant since it's kind of given by the module already. I would describe the intention of the function as "make sure file was written by admin". Suggestion for name: `check_written_by_admin`. `check` can also be `verify`.

Replacing "trusted" with "written by admin" much more clearly conveys what the intention is.
</blockquote></details>

Understood. Would it be an overkill to call it `check_trustworthiness`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by pronebird** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by pronebird** [comment]
Looks good except a few things that Linus outlined below.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-:-L6q0NINcBml_bxlDSV-:b-p9noxc)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 20 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pQbtB-syYLqWDBj1T:-L6q3CarIk3nsb-TtqtR:b2ymv7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/CHANGELOG.md#L20)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Should I create a new section, or wait until the PRs are merged to rebase the change?
</blockquote></details>

I would be happy if we could wait until my PRs were merged. I have fixed these problems in two PRs already and really want them merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6q3Qv4HUvJoU0NBJTO:b-ts03j4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Understood. Would it be an overkill to call it `check_trustworthiness`?
</blockquote></details>

"trustworthiness" has the same problem as "trusted" IMO, it does not convey what it means to be trusted. The end goal is that we want to make sure the RPC info we get came from admin and no one else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6q3itsq1nOijTfE1Bf:b-scdywj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"trustworthiness" has the same problem as "trusted" IMO, it does not convey what it means to be trusted. The end goal is that we want to make sure the RPC info we get came from admin and no one else.
</blockquote></details>

But yeah, I like `check_trustworthyness` much more than `check_if_rpc_file_can_be_trusted` :) It's basically a much shorter form of the exact same info. So if you don't like my suggestion I'm fine with `check_trustworthyness` as well :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-:-L6qLXRjB0hcds7vI347:bnfp4nl)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6qPlOj_y2UCe4_qMkd:bql6rqx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

But yeah, I like `check_trustworthyness` much more than `check_if_rpc_file_can_be_trusted` :) It's basically a much shorter form of the exact same info. So if you don't like my suggestion I'm fine with `check_trustworthyness` as well :)
</blockquote></details>

Updated to `ensure_written_by_admin`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6qQWtwjyKl43WVNmLC:bf8wbal) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Updated to `ensure_written_by_admin`.
</blockquote></details>

Forgot to update the windows one, so fails to build on AppVeyor ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-cli/src/rpc.rs, line 68 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-L6pR4UOEO-VC9y-GtbB:-L6q_wNJFlreY5vsqaha:b-bo8d0q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b27674709cba7813ae402161c4c6d0688b43480/mullvad-cli/src/rpc.rs#L68)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Hopefully fixed now :)
</blockquote></details>

`credibility` is another way to say trustworthiness if you're looking for that word.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86#-:-L6qa8NDhK9dfveGuwAY:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/86)*

**Pull request merged**
