### PR TITLE
Improve UI of list items in vpn settings view

### PR DESCRIPTION
**Pull request by rablador**
This PR fixes some UI quirks when expanding and retracting list items in the vpn settings view. Not perfect, but a lot better.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6265)

### CODE REVIEW

**Review by buggmagnet — APPROVED** [review]
It's better, but I can still see UI glitches :(

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6265#-:-NyOyvjL8zWwnnpxinlv:b-nb533c)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
Yes, the separator lines are visible over the selected row. Don't know how to fix that or if it's even possible. Or did you think of something else?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6265#-:-NyP4wQ397WCErsU3yyq:b46se93)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
Fixed!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6265#-:-NyPX5Na6JsfVjl9tDU8:bt2vr0y)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6265#-:-NyPYlMW3TQjHn1s_vZL:b-qcfkkb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
