### PR TITLE
Show tray icon matching expected state change

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds a call to `updateTrayIcon` when assuming what the next target state will be. The variable naming has also been changed from `ignoreTunnelStateUntil` to `optimisticTunnelState` in `index.tsx` to match `app.tsx`.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 875 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220#-MtDl_oX-jgJeGyJ-Z2S:-MtDl_oX-jgJeGyJ-Z2T:b-log9b4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60dfb24367f42aa47047be8185ce014e187730a7/gui/src/main/index.ts#L875)):*
> ```XML
>     this.updateTrayIcon(
>       this.tunnelState.state,
>       this.tunnelState.state === 'error' && this.tunnelState.details.blockFailure !== undefined,
> ```

Wouldn't it be simpler for `updateTrayIcon` to take a `TunnelState` still? This condition is duplicated in two other places now. Couldn't you just construct a `TunnelState` in `setOptimisticTunnelState`, if necessary?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon)

___
*[gui/src/main/index.ts, line 875 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220#-MtDl_oX-jgJeGyJ-Z2S:-MtE0YkF3kWPehQ8tITk:bfinp8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60dfb24367f42aa47047be8185ce014e187730a7/gui/src/main/index.ts#L875)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Wouldn't it be simpler for `updateTrayIcon` to take a `TunnelState` still? This condition is duplicated in two other places now. Couldn't you just construct a `TunnelState` in `setOptimisticTunnelState`, if necessary?
</blockquote></details>

Yes, this is much better. I initially discarded this idea since constructing the error-state felt more complicated, but now I realized that I don't need to since we only ever transition to 'connecting' and 'disconnecting' like this.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1090 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220#-MtERXCr-uijOrFJ_CYo:-MtERXCr-uijOrFJ_CYp:b-9mhkx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bdec05477713dc52c3c1d48a7961d5def1b7074b/gui/src/main/index.ts#L1090)):*
> ```XML
> 
>       case 'error':
>         if (tunnelState.details.blockFailure !== undefined) {
> ```

Is there a reason for doing this instead of simply checking whether it is falsy?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon)

___
*[gui/src/main/index.ts, line 1090 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220#-MtERXCr-uijOrFJ_CYo:-MtEi_LN3bVsj5LahmVD:bfklkn7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bdec05477713dc52c3c1d48a7961d5def1b7074b/gui/src/main/index.ts#L1090)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is there a reason for doing this instead of simply checking whether it is falsy?
</blockquote></details>

No not really. In this situation the variable name `blockFailure` could give the impression that it's a `boolean` so I think that's why I changed. But this is good as well IMO.

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220#-:-MtI4oaH0J7O83HabCj6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
