### PR TITLE
Fix missing cities and relays in custom list

### PR DESCRIPTION
**Pull request by Pururun**
Bug introduced in a previous PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147#-:-NvkVdGd121ig0ROREN5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147#-NvkWhN567kIrlsZ5Ftj:-NvkWhN567kIrlsZ5Ftk:brmtl3o) (no related file):*
Would be nice to cover this with some tests. But if this will change a lot during the gRPC work we can probably skip it for now.

___

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Rawa — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147#-NvkWhN567kIrlsZ5Ftj:-NvkXqM87ZjwmYQNi6Fr:byk3yzs) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to cover this with some tests. But if this will change a lot during the gRPC work we can probably skip it for now.
</blockquote></details>

Yeah if the logic is spread out I think it might be hard, but otherwise I think it would be nice to have. Let's discuss.

___

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147#-:-NvkXyYP2Unm0rP1Zuw0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
