### PR TITLE
Prevent `apt` from being confused about `mullvad-vpn` package version

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Sometimes, apt thinks that some installs are downgrades due to the dev version hash being lower than the baseline version hash. This PR makes the test framework add `--allow-downgrades` to `apt` when installing the app. To make sure that we are running the expected app version, a runtime check has been added to the `test_upgrade_app` test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125)

### CODE REVIEW

**Review by Serock3 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-runner/src/package.rs` line 176 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125#-OArh-f36WVskHh3iBln:-OArh-f36WVskHh3iBlo:bwguoxg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/98780cb8029990bd83fb34f2cb7ef522731d5301/test/test-runner/src/package.rs#L176)):*
> ```XML
>     cmd.args(["-o", "DPkg::Lock::Timeout=60"]);
>     cmd.arg("-qy");
>     // `apt` may sporadically consider installing a development build to be a downgrade from the baseline stable
> ```

We could be more specific about the bug behavior here just to document it somewhere, e.g. "`apt` may consider installing a development build to be a downgrade from the baseline stable if the major version is identical, in which case the ordering is incorrectly based on the git hash suffix"

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/test-runner/src/package.rs` line 176 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125#-OArh-f36WVskHh3iBln:-OAvQeYu47Hz9-i2xgXf:bx4cflj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/98780cb8029990bd83fb34f2cb7ef522731d5301/test/test-runner/src/package.rs#L176)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

We could be more specific about the bug behavior here just to document it somewhere, e.g. "`apt` may consider installing a development build to be a downgrade from the baseline stable if the major version is identical, in which case the ordering is incorrectly based on the git hash suffix"
</blockquote></details>

That's a good idea. Updated the comment, please let me know what you think :blush:

**Review by Serock3 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/install.rs` line 119 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125#-OB52xa29CwEux4q4vQA:-OB52xa29CwEux4q4vQB:b7lafrp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aba615fbbb72f36b2045bbee5d8734611b987952/test/test-manager/src/tests/install.rs#L119)):*
> ```XML
>             .app_package_filename
>             .contains(&running_daemon_version),
>         Error::DaemonVersion {
> ```

The `Error::DaemonVersion` variant is probably not needed, you could replace it with just a formatted error message.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/test-manager/src/tests/install.rs` line 119 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125#-OB52xa29CwEux4q4vQA:-OB5ZoPR36aj1ynHNTtZ:bk8x41p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aba615fbbb72f36b2045bbee5d8734611b987952/test/test-manager/src/tests/install.rs#L119)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

The `Error::DaemonVersion` variant is probably not needed, you could replace it with just a formatted error message.
</blockquote></details>

You're right! Done

**Review by Serock3 — APPROVED** [review]
:lgtm: :star2: 

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7125#-:-OBAPS-U8azGA-fUxycA:b-bn4ekl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
