### PR TITLE
Improve Linux split tunneling UI

### PR DESCRIPTION
**Pull request by raksooo**
This PR makes a few improvements to the split tunneling UI on Linux:
* Replaces `linux-app-list` with our own implementation which scans for and reads the desktop files asynchronously, scans in the correct directories in the correct order and allows for equal signs in desktop entry values (https://github.com/MusicalCreeper01/Linux-Application-List/pull/1)
* Accepts `.desktop` files in addition to executables when browsing for applications
* Shows an error dialog when an app couldn't be launched.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492)* status: 7 of 10 files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/linux-split-tunneling.ts, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492#-MU9MD-4DqqckSc1pUWD:-MU9MD-4DqqckSc1pUWE:b-2qywsd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/543cdb2b3f3f405b975c8176a949f4f39f18d69d/gui/src/main/linux-split-tunneling.ts#L37)):*
> ```XML
>       proc.once('exit', (code: number) => {
>         if (code === 1) {
>           reject('Failed to start application');
> ```

reject(new Error('...'))?

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
I've made some changes to improve the error message that is shown if an app fails to launch. I've also lowered the timeout for when a fail is considered to be during startup.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492#-:-MUDRWlY83HzX99_H_Fj:b-g3c6th)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/linux-split-tunneling.ts, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492#-MU9MD-4DqqckSc1pUWD:-MUDRDpp6MIajchD62nm:b-yz4dn0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/543cdb2b3f3f405b975c8176a949f4f39f18d69d/gui/src/main/linux-split-tunneling.ts#L37)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

reject(new Error('...'))?
</blockquote></details>

I've switched to returning an object with the error in it. I wanted to display the error in a dialog and the error message is prefixed by `Uncaught error: ` when thrown in `preload.js` and caught in the renderer.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492#-:-MUEVAHA5rhdUu1TSGUl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2492)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
