### PR TITLE
Migrate/decouple service dependent fragments

### PR DESCRIPTION
**Pull request by albin-mullvad**
Decouple fragments by no longer inheriting super fragments that handle state and service connection. 

Git checklist:

~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (refactor)
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 7 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747)* status: 7 of 29 files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ContextExtensions.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747#-N7L4hw7CXpD-X7hVs5I:-N7L4hw7CXpD-X7hVs5J:bauc0y5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/263dba5ec795dc91dd1cf44de0b7042f9ec81413/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ContextExtensions.kt#L10)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.ui.MainActivity
> 
> fun Context.openAccountPageInBrowser(authToken: String) {
> ```

Not entirely sure if this function should be in an `util` package, but it is sound.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747)* status: 7 of 29 files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ContextExtensions.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747#-N7L4hw7CXpD-X7hVs5I:-N7LCo0tBmby2P6VHFwH:b2xaqfn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/263dba5ec795dc91dd1cf44de0b7042f9ec81413/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ContextExtensions.kt#L10)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Not entirely sure if this function should be in an `util` package, but it is sound.
</blockquote></details>

Agreed. Will move it.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 13 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747)* status: 20 of 29 files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 9 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3747)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
