### PR TITLE
Do not show change log when it is empty

### PR DESCRIPTION
**Pull request by rablador**
When there are no meaningful changes we do not want to advertise anything in the app.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)

### CODE REVIEW

**Review by buggmagnet — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 998 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297#-NgszKOVCDDJlwGRJiIj:-NgszKOVCDDJlwGRJiIk:bj07k6c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d309b7adb2668c5357a707a2c1931d29045f416/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L998)):*
> ```Swift
> 
> fileprivate extension AppPreferencesDataSource {
>     var isSeenLatestChanges: Bool {
> ```

Can we rename this `hasSeenLastChanges` ?

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 998 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297#-NgszKOVCDDJlwGRJiIj:-NgszSdtAH6i4mwCi-39:booqw55) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d309b7adb2668c5357a707a2c1931d29045f416/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L998)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we rename this `hasSeenLastChanges` ?
</blockquote></details>

Or `hasSeenLastChangelog`

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 998 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297#-NgszKOVCDDJlwGRJiIj:-Ngt2UV2DpM90LDWebIx:b8hi6wg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d309b7adb2668c5357a707a2c1931d29045f416/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L998)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

With the other suggestion, we can simplify this to the following (which is IMHO way easier to understand)

```swift
var hasSeenLastChanges: Bool {
    ChangeLogInteractor().hasNewChanges() ||
    lastSeenChangeLogVersion != Bundle.main.shortVersion
}
```
</blockquote></details>

Correction
```swift
var hasSeenLastChanges: Bool {
    ChangeLogInteractor().hasNewChanges() == false &&
    lastSeenChangeLogVersion == Bundle.main.shortVersion
}
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 998 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297#-NgszKOVCDDJlwGRJiIj:-Ngt2Av35P-bMIH3gC2G:b-y689vo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d309b7adb2668c5357a707a2c1931d29045f416/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L998)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

With the other suggestion, we can simplify this to the following (which is IMHO way easier to understand)

```swift
var hasSeenLastChanges: Bool {
    ChangeLogInteractor().hasNewChanges() ||
    lastSeenChangeLogVersion != Bundle.main.shortVersion
}
```
</blockquote></details>

Indeed, much better!
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297#-Ngt-1wQ4m7hIb5uj5a1:-Ngt2oiG6Nw1rz5YhUrS:bc6sd16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d309b7adb2668c5357a707a2c1931d29045f416/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We shouldn't be exposing the guts of the `ChangeLogInteractor` for no reason.
Instead, it should say itself whether there are changes or not.

here's a suggestion

```swift
public func hasNewChanges() -> Bool {
    items.isEmpty == false
}

```
</blockquote></details>

I can meet you just past halfway.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 998 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297#-NgszKOVCDDJlwGRJiIj:-NgwRd-o4wMEUkxqNmp2:b-bz3lpb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d309b7adb2668c5357a707a2c1931d29045f416/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L998)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Indeed, much better!
</blockquote></details>

The parenthesis were not necessary. But not the end of the world.

**Pull request merged**
