### PR TITLE
Unify button appearance

### PR DESCRIPTION
**Pull request by Pururun**
- Make almost all button depend on 3 standard buttons
- Replace surface and onSurface with our own custom theme color

This is part of the design system overhaul.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 33 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nfj8dr1-YrQY_yEuh01:-Nfj8dr28BEt-7PDWxw_:bp1hss0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47aec5578c2195ce7129919491ba056a0407125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
> ```Kotlin
>     text: String,
>     modifier: Modifier = Modifier,
>     background: Color = MaterialTheme.colorScheme.background,
> ```

Would be nice if we could avoid passing backgrounds into the button. I know we overlay do alpha dance with it but, is it really necessary? Can we assume it is always `colorScheme.background` until we get rid of the alpha?

**Comment by mullmat** [comment]
Tried this out (after getting it sent to me by @Pururun ) and it was really nice to have the buttons unified! 🎉 
It was easy to use and it is makes it easier to change button details if needs be (such as padding, adding icon, etc).

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nfj8dr1-YrQY_yEuh01:-NfjYCVjB5BGYA1FZquM:b1y2pcg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47aec5578c2195ce7129919491ba056a0407125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would be nice if we could avoid passing backgrounds into the button. I know we overlay do alpha dance with it but, is it really necessary? Can we assume it is always `colorScheme.background` until we get rid of the alpha?
</blockquote></details>

I removed it for NegativeButton as it was using the default value as always, not sure about what do with the VariantButton though as it is actually used on different backgrounds.

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nfj8dr1-YrQY_yEuh01:-NfkPiD07hm54BrnIP_L:b-ui7cw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47aec5578c2195ce7129919491ba056a0407125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I removed it for NegativeButton as it was using the default value as always, not sure about what do with the VariantButton though as it is actually used on different backgrounds.
</blockquote></details>

We should let design decide on a color to use to avoid involving the transparency at all I think.

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nfj8dr1-YrQY_yEuh01:-NfkPrLVB4SQSb4lHjvK:btbzlmi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47aec5578c2195ce7129919491ba056a0407125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should let design decide on a color to use to avoid involving the transparency at all I think.
</blockquote></details>

maybe that is out of scope for now though?

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 17 of 37 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 164 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-NftaF4u0qKDsXcHVUTK:-NftaF4u0qKDsXcHVUTL:b-wfml1q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L164)):*
> ```Kotlin
>     modifier: Modifier = Modifier,
>     isEnabled: Boolean = true,
>     icon: Int? = null,
> ```

Should or BaseButton be more generic than having a fixed option of passing an Int resource? Would be nice we could slot it instead with optional lambdas.

`@Composable () -> Unit`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 175 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-NftZnM70YqXwH4EGswB:-NftZnM70YqXwH4EGswC:blma26) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L175)):*
> ```Kotlin
>         modifier =
>             modifier
>                 .height(Dimens.buttonHeight)
> ```

We should avoid setting height of button, if user sets a big font on their font the text will not render properly.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 193 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nft_oNmCaUjiWJ7nejO:-Nft_oNmCaUjiWJ7nejP:b-np06wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L193)):*
> ```Kotlin
>             )
>             icon?.let {
>                 Image(
> ```

Should maybe Icon instead of Image with a tint of contentColor? Then it would always have the same color as the text.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 13 of 39 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nfj8dr1-YrQY_yEuh01:-NfuPqgv9mXY5JEQjd66:b-ry7awi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47aec5578c2195ce7129919491ba056a0407125c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

maybe that is out of scope for now though?
</blockquote></details>

Yeah maybe.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 164 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-NftaF4u0qKDsXcHVUTK:-NfuPcQk0VnIyRs0S5wT:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L164)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should or BaseButton be more generic than having a fixed option of passing an Int resource? Would be nice we could slot it instead with optional lambdas.

`@Composable () -> Unit`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 175 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-NftZnM70YqXwH4EGswB:-NfuPdnv6d85pgWZ05kq:bujmd2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L175)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should avoid setting height of button, if user sets a big font on their font the text will not render properly.
</blockquote></details>

This seems to cause side effects that some button just take up alla available space, will try to figure out why.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 193 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Nft_oNmCaUjiWJ7nejO:-NfuPnTO2-e7UHjqxchw:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L193)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should maybe Icon instead of Image with a tint of contentColor? Then it would always have the same color as the text.
</blockquote></details>

Done

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r3, 12 of 14 files at r4, 1 of 1 files at r5, 8 of 8 files at r6, 1 of 1 files at r7, 12 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 38 of 40 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 175 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-NftZnM70YqXwH4EGswB:-NfusWNz4D-0zl_FJm5q:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d2c720d986c8380d74c85f2d5fefac10665efd1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L175)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This seems to cause side effects that some button just take up alla available space, will try to figure out why.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt` line 69 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6H_D1bYTroDdfIQZ:-Ngr6H_E5OP0AK913CY4:b-qif1q4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt#L69)):*
> ```Kotlin
>             PrimaryButton(
>                 modifier = Modifier.focusRequester(FocusRequester()),
>                 onClick = { onDismiss() },
> ```

Why this?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt` line 173 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6MaMEEXOUtkIFaXK:-Ngr6MaMEEXOUtkIFaXL:bb73xfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt#L173)):*
> ```Kotlin
>                 PrimaryButton(
>                     modifier = Modifier.padding(top = mediumPadding),
>                     onClick = { onAttemptToSave() },
> ```

Same
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt` line 181 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6OnUEVLAWKAhLIvF:-Ngr6OnUEVLAWKAhLIvG:bb73xfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt#L181)):*
> ```Kotlin
>                     PrimaryButton(
>                         modifier = Modifier.padding(top = mediumPadding),
>                         onClick = { onRemove() },
> ```

Same
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt` line 188 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6PMTEfUFdHjESNsW:-Ngr6PMTEfUFdHjESNsX:bb73xfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt#L188)):*
> ```Kotlin
>                 PrimaryButton(
>                     modifier = Modifier.padding(top = mediumPadding),
>                     onClick = { onDismiss() },
> ```

Same

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 33 of 41 files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt` line 173 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6MaMEEXOUtkIFaXK:-NgsMqMj-gAuoP0stYhH:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt#L173)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt` line 181 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6OnUEVLAWKAhLIvF:-NgsMrCM9N08H2jfOd9i:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt#L181)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt` line 188 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6PMTEfUFdHjESNsW:-NgsMs3889vrRbjEk5TO:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt#L188)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: 33 of 41 files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt` line 69 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-Ngr6H_D1bYTroDdfIQZ:-NgsN8Df1lvat9w88yMZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77351b53a500fa94b0a77cc6e2275dbda3e59a54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt#L69)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why this?
</blockquote></details>

Done.

**Review by Rawa — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217#-:-NgstXNVBHsx71-SDjC-:bnfp4nl)* status: 37 of 41 files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 4 of 4 files at r10, 13 of 16 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5217)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
