### PR TITLE
Add persistent revoked device state

### PR DESCRIPTION
**Pull request by dlon**
Main changes:
* Add a persistent "revoked" state instead of simply advertising it in events. Previously, frontends had no way of knowing that a device had been revoked if they were not running at the time.
* Make the device event simpler/more convenient for frontends.
* Enter the `revoked` state during upgrade/migration if the pubkey is not found for the account (instead of remaining logged out).

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 5 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578#-N1rrcVF2Im9kd2P1eVt:-N1rrcVR0CzfGEgKxuwF:bij3bln) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/723729ee1ef57041e90d27a7e3d9f9b46b6b3492/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt#L106)):*
> ```Kotlin
>                 }
>                 .collect { state ->
>                     accountNumberView.information = state.token()
> ```

Not sure if this change is needed.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/device/mod.rs` line 88 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578#-N1ruKABE2QAVQ-LLHJa:-N1ruKABE2QAVQ-LLHJb:b-isacxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/723729ee1ef57041e90d27a7e3d9f9b46b6b3492/mullvad-daemon/src/device/mod.rs#L88)):*
> ```XML
>     /// Returns whether the device is in the logged in state.
>     pub fn logged_in(&self) -> bool {
>         match self {
> ```

This and similar methods could use [`std::matches!`](https://doc.rust-lang.org/stable/std/macro.matches.html).

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578#-N1rrcVF2Im9kd2P1eVt:-N1rzk7QCVy9i9vloBh2:b-1d1uoc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/723729ee1ef57041e90d27a7e3d9f9b46b6b3492/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt#L106)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Not sure if this change is needed.
</blockquote></details>

Not necessary, but since it's used in the `onEach` it made sense to have it here as well. In general, I think it's good to specify explicit variable names when chaining calls.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 6 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 12 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3578)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
