### PR TITLE
Change heading and button font to Source Sans Pro and Noto Sans

### PR DESCRIPTION
**Pull request by raksooo**
This PR replaces the DIN Pro font with Source Sans Pro and Noto Sans.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2824)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
I'd appreciate the screenshot.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2824#-:-MdWNKlj53xnZqHd8DsW:b-w15wmo)* status: 0 of 11 files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2824)* status: 6 of 11 files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2824#-:-MdWOfSS5ddNVvsEd8yu:b4xu98e)* status: 6 of 11 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2824#-:-MdWyuJZCPz7mxeCQW7L:bnfp4nl)* status: 6 of 11 files reviewed, all discussions resolved

**Pull request merged**
