### PR TITLE
Implement support for custom OpenVPN socks5 bridge client in daemon

### PR DESCRIPTION
**Pull request by Jontified**
This PR is meant to make it easier for us to use a socks5 server as an obfuscation layer for OpenVPN connections.
It aims to make local socks5 servers work without having to use split tunneling, create a CLI UI to allow easily setting this up.
To set up for easy integration into the UI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 8 of 15 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: all files reviewed, 3 unresolved discussions (waiting on @Jontified)

___
*[`dist-assets/binaries` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbRXGJEKJGudrbCOvg:-NlbRXGJEKJGudrbCOvh:b-ja1qh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d1d78d7a193b7d25c42ae5199f84082e183c329e/dist-assets/binaries#L1)):*
> ```
> Subproject commit d9db5c930cb3eb1d3ee048e5546be6377dedf8ab
> ```

Accidentally committed?
___
*[`talpid-core/src/firewall/mod.rs` line 130 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbSFBx1lDuK46l6PRF:-NlbSFBx1lDuK46l6PRG:b460etm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14d914ae1cc2f32d41762a4fb431d18a56e6bd9a/talpid-core/src/firewall/mod.rs#L130)):*
> ```XML
>         /// TODO
>         #[cfg(any(target_os = "linux", target_os = "macos"))]
>         allow_all_traffic_to_peer: bool,
> ```

What do you think of replacing `peer_endpoint` with an `AllowedEndpoint`? It has the exact same purpose.

I'm not sure if the type's name would still make sense, but you'd be able to remove both `relay_client` and `allow_all_traffic_to_peer`
___
*[`talpid-core/src/firewall/mod.rs` line 146 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbRewK8jBDQ9exRbVl:-NlbRewK8jBDQ9exRbVm:blvihit) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14d914ae1cc2f32d41762a4fb431d18a56e6bd9a/talpid-core/src/firewall/mod.rs#L146)):*
> ```XML
>         /// TODO
>         #[cfg(any(target_os = "linux", target_os = "macos"))]
>         allow_all_traffic_to_peer: bool,
> ```

This should probably be moved down so it's grouped with `relay_client`.
___
*[`talpid-types/src/net/mod.rs` line 100 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbTUSj-Dxmppy07Bi4:-NlbTUSj-Dxmppy07Bi5:bi6wd63) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14d914ae1cc2f32d41762a4fb431d18a56e6bd9a/talpid-types/src/net/mod.rs#L100)):*
> ```XML
> 
>     pub fn get_openvpn_local_proxy_settings(&self) -> Option<&LocalProxySettings> {
>         match &self {
> ```

Nit: It's already borrowed

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: 6 of 36 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/firewall/mod.rs` line 130 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbSFBx1lDuK46l6PRF:-NmPbt6n0CY4MUCChU0B:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14d914ae1cc2f32d41762a4fb431d18a56e6bd9a/talpid-core/src/firewall/mod.rs#L130)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

What do you think of replacing `peer_endpoint` with an `AllowedEndpoint`? It has the exact same purpose.

I'm not sure if the type's name would still make sense, but you'd be able to remove both `relay_client` and `allow_all_traffic_to_peer`
</blockquote></details>

Done.
___
*[`dist-assets/binaries` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbRXGJEKJGudrbCOvg:-NmPU1zl5iM5Tk2ZN-Gs:b-hk4ruy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d1d78d7a193b7d25c42ae5199f84082e183c329e/dist-assets/binaries#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Accidentally committed?
</blockquote></details>

Done. Why is the old submodule not set to main though?

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 30 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: 7 of 36 files reviewed, 1 unresolved discussion

___
*[`dist-assets/binaries` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NlbRXGJEKJGudrbCOvg:-NmfN81NBa0CtI2zX2W1:bbxvrwo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d1d78d7a193b7d25c42ae5199f84082e183c329e/dist-assets/binaries#L1)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done. Why is the old submodule not set to main though?
</blockquote></details>

The most recent commit doesn't modify any artifacts, so there's no real reason to point to it.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 30 files at r3, 3 of 4 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: 14 of 37 files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`talpid-core/src/firewall/windows.rs` line 162 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NmjgwQk47MYixyJ8NeK:-NmjgwQk47MYixyJ8NeL:brarzfd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb62e2e7876f2f5b92706aea6a3984e6268f57b7/talpid-core/src/firewall/windows.rs#L162)):*
> ```XML
>         let relay_client_wstr_ptrs: Vec<*const u16> = relay_client_wstrs.iter().map(|wstr| wstr.as_ptr()).collect();
>         let relay_client_wstr_ptrs_len = relay_client_wstr_ptrs.len();
>         //let relay_client_wstr_ptr: *const u16 = if let Some(ref wstr) = relay_client_wstr {
> ```

Comments
___
*[`windows/winfw/src/winfw/winfw.cpp` line 408 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nmjhf669VYx5j9ycTSu:-Nmjhf669VYx5j9ycTSv:bvo3c3t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb62e2e7876f2f5b92706aea6a3984e6268f57b7/windows/winfw/src/winfw/winfw.cpp#L408)):*
> ```cpp
> 		}
> 
> 		auto relayClientWstrings = std::vector<std::wstring>();
> ```

Nit: `std::vector<std::wstring> relayClientWstrings;`

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 3 of 30 files at r3, 15 of 23 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: 26 of 38 files reviewed, 6 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-cli/src/cmds/api_access.rs` line 343 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nmkfxpz8fPygGI6EXGy:-Nmkfxpz8fPygGI6EXGz:b-wgsukf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-cli/src/cmds/api_access.rs#L343)):*
> ```XML
>     item: SelectItem,
>     /// Name of the API access method in the Mullvad client [All]
>     #[arg(long)]
> ```

Is it possible to specify a `group` here and for `item`? That would make the arguments mutually exclusive.
___
*[`mullvad-cli/src/cmds/api_access.rs` line 358 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nmkg8s89M0CnkG8XlDd:-Nmkg8s89M0CnkG8XlDe:bhjytlq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-cli/src/cmds/api_access.rs#L358)):*
> ```XML
>     edit_params: ProxyEditParams,
>     ///// Username for authentication [Socks5 (Remote proxy)]
>     //#[arg(long)]
> ```

The commented code should probably be removed.
___
*[`mullvad-daemon/src/management_interface.rs` line 709 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NmkopQD8NI0X8kcWV3p:-NmkopQE45tW4qk3By3b:bo8r63u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-daemon/src/management_interface.rs#L709)):*
> ```XML
>     }
> 
>     async fn get_custom_bridge(&self, _: Request<()>) -> ServiceResult<CustomBridgeSettings> {
> ```

This probably does not require a special command. This is present in the settings already.
___
*[`mullvad-daemon/src/management_interface.rs` line 726 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NmkpDvg5QnrBSotFSws:-NmkpDvg5QnrBSotFSwt:b-pi2wsu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-daemon/src/management_interface.rs#L726)):*
> ```XML
>         log::debug!("update_custom_bridge");
>         let (tx, rx) = oneshot::channel();
>         self.send_command_to_daemon(DaemonCommand::UpdateCustomBridge(
> ```

For consistency, maybe the settings should be updated using `GetSettings` + `SetCustomBridge` if a bridge is already set.

However, I'm not sure why we can't use the existing function `SetBridgeSettings` for this.
___
*[`mullvad-management-interface/proto/management_interface.proto` line 86 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NmkvXBu0Y57Y_DGR_7u:-NmkvXBu0Y57Y_DGR_7v:b3xvhfa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-management-interface/proto/management_interface.proto#L86)):*
> ```proto
> 
>   // Custom proxy
>   rpc SetCustomBridge(google.protobuf.Empty) returns (google.protobuf.Empty) {}
> ```

`Set` confused me a lot at first. I think "enable" or something might be clearer.

But this also seems redundant given that we already have a `bridge_state`.
___
*[`mullvad-types/src/settings/mod.rs` line 85 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nmkpm_h9pMpWTk2OZhp:-Nmkpm_h9pMpWTk2OZhq:b-8b9e9t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-types/src/settings/mod.rs#L85)):*
> ```XML
>     /// A potential custom bridge.
>     #[cfg_attr(target_os = "android", jnix(skip))]
>     pub custom_bridge: CustomBridgeSettings,
> ```

I found it pretty confusing to understand the purpose of having both `BridgeSettings` and `CustomBridgeSettings`. It's probably not ideal to have a duplicated "runtime-only" state in the settings.

Have you considered updating `BridgeSettings` to simply store all constraints independently of the current "bridge type"?

Instead of

```
  pub enum BridgeSettings {
      Normal(BridgeConstraints),
      Custom(ProxySettings),
  }
```

use something like

```
  enum BridgeType {
      Builtin,
      Custom,
  }

  pub struct BridgeSettings {
      bridge_type: BridgeSettingsType,
      normal: BridgeConstraints,
      custom: ProxySettings,       
  }
```

Then you won't lose the custom bridge settings when you stop using the custom bridge.

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: 9 of 58 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-cli/src/cmds/api_access.rs` line 343 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nmkfxpz8fPygGI6EXGy:-Nn8cwtQ1ZCXJkUCSfuT:b-apkhdj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-cli/src/cmds/api_access.rs#L343)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is it possible to specify a `group` here and for `item`? That would make the arguments mutually exclusive.
</blockquote></details>

I think this is far enough away from the purpose of this PR that it should be fixed somewhere else.
___
*[`mullvad-management-interface/proto/management_interface.proto` line 86 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-NmkvXBu0Y57Y_DGR_7u:-Nn8JS1t47g8qgBO0zbX:btnu6ch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-management-interface/proto/management_interface.proto#L86)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`Set` confused me a lot at first. I think "enable" or something might be clearer.

But this also seems redundant given that we already have a `bridge_state`.
</blockquote></details>

This is improved in the new other PR
___
*[`mullvad-types/src/settings/mod.rs` line 85 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nmkpm_h9pMpWTk2OZhp:-Nn8JVqS3R7eQTfxHiEQ:bm8tlku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3496ff7361308201e6c5e5d3880157f19d9304d1/mullvad-types/src/settings/mod.rs#L85)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I found it pretty confusing to understand the purpose of having both `BridgeSettings` and `CustomBridgeSettings`. It's probably not ideal to have a duplicated "runtime-only" state in the settings.

Have you considered updating `BridgeSettings` to simply store all constraints independently of the current "bridge type"?

Instead of

```
  pub enum BridgeSettings {
      Normal(BridgeConstraints),
      Custom(ProxySettings),
  }
```

use something like

```
  enum BridgeType {
      Builtin,
      Custom,
  }

  pub struct BridgeSettings {
      bridge_type: BridgeSettingsType,
      normal: BridgeConstraints,
      custom: ProxySettings,       
  }
```

Then you won't lose the custom bridge settings when you stop using the custom bridge.
</blockquote></details>

Done. This is fixed, among other things in the other PR.

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 2 of 23 files at r6, 3 of 4 files at r7, 1 of 3 files at r9, 33 of 40 files at r10, 8 of 8 files at r11, 3 of 3 files at r12, 2 of 2 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-openvpn/src/lib.rs` line 763 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nn92hEKCh-bKQi4F7Do:-Nn92hEKCh-bKQi4F7Dp:b6vzf8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66dbd9c3fcdaac399048eee1a2f0c6d4d47f6581/talpid-openvpn/src/lib.rs#L763)):*
> ```XML
>     use talpid_types::ErrorExt;
>     #[cfg(target_os = "macos")]
>     use talpid_types::ErrorExt;
> ```

Nit: No conditional compilation is needed here. `use` can be merged as well:
`use talpid_types::{net::proxy::CustomProxy, ErrorExt};`



_Code quote:_
```XML
    use talpid_types::net::proxy::CustomProxy;
    #[cfg(any(target_os = "linux", windows))]
    use talpid_types::ErrorExt;
    #[cfg(target_os = "macos")]
    use talpid_types::ErrorExt;
```
___
*[`talpid-openvpn/src/lib.rs` line 846 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587#-Nn9406D5PU9f4qAk2GU:-Nn9406D5PU9f4qAk2GV:bbw26mm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66dbd9c3fcdaac399048eee1a2f0c6d4d47f6581/talpid-openvpn/src/lib.rs#L846)):*
> ```XML
>             let mut routes = HashSet::new();
>             #[cfg(not(target_os = "linux"))]
>             if let Some(talpid_types::net::proxy::CustomProxy::Socks5Local(proxy_settings)) =
> ```

Nit: `CustomProxy` is already imported in this scope, might as well use it unqualified.



_Code quote:_
```XML
talpid_types::net::proxy::CustomProxy::Socks5Local(proxy_settings)
```

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 40 files at r16, 1 of 8 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5587)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
