### PR TITLE
WireGuard UDP-over-TCP

### PR DESCRIPTION
**Pull request by Pururun**
Add support in the android application for UDP-over-TCP.

- Add ui support in the main view to show protocol and port.
- New Obfuscation setting with the options auto, on and off.
- Implement connection between the app and the daemon. This includes support for setting the port number, but this is not yet added to the UI.

This PR is based on this other PR:
https://github.com/mullvad/mullvadvpn-app/pull/4068

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Looks good overall, I just have some minor comments

> Reviewed 10 of 16 files at r1, 1 of 3 files at r3, 1 of 39 files at r6, 1 of 1 files at r10, 37 of 37 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-:-NUufSs7C7_nKV7-WyBP:buseugx)* status: 9 of 50 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 12 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-NUbHcRX-jqfAViRUp65):*
nit: I suggest sticking with `udp2tcp` to keep it consistent throughout these commits. This also applies to the body of this commit.



_Code quote:_
```
udp over tcp
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 303 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-NUueHcH8gTCFTG94IcW:-NUueHcH8gTCFTG94IcX:b-qmnvqs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0012d1559f5df585258cd83f565cf7a55f47935b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L303)):*
> ```Kotlin
>                     title = stringResource(R.string.obfuscation_title),
>                     onInfoClicked = { onObfuscationInfoClicked() },
>                     onCellClicked = { expandContentBlockersState = !expandContentBlockersState }
> ```

Is this correct? I'm not sure this one should be expandable and regardless it probably shouldn't use the same state bool as the content blockers :thinking: 



_Code quote:_
```Kotlin
expandContentBlockersState = !expandContentBlockersState
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 329 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-NUudbQA65JVf4XC_VwJ:-NUudbQA65JVf4XC_VwK:b-6dkl3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0012d1559f5df585258cd83f565cf7a55f47935b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L329)):*
> ```Kotlin
>                     background =
>                         if (uiState.selectedObfuscation == SelectedObfuscation.Udp2Tcp) MullvadGreen
>                         else MullvadBlue20,
> ```

I suggest using curly brackets for this if-statement to improve readability



_Code quote:_
```Kotlin
                    background =
                        if (uiState.selectedObfuscation == SelectedObfuscation.Udp2Tcp) MullvadGreen
                        else MullvadBlue20,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 342 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-NUueUdf2lKfHENMLLu9:-NUueUdf2lKfHENMLLuA:b-6dkl3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0012d1559f5df585258cd83f565cf7a55f47935b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L342)):*
> ```Kotlin
>                     background =
>                         if (uiState.selectedObfuscation == SelectedObfuscation.Off) MullvadGreen
>                         else MullvadBlue20,
> ```

I suggest using curly brackets for this if-statement to improve readability



_Code quote:_
```Kotlin
                    background =
                        if (uiState.selectedObfuscation == SelectedObfuscation.Off) MullvadGreen
                        else MullvadBlue20,
```

**Review by sabercodic — COMMENTED** [review]
> Reviewed 1 of 37 files at r8, 1 of 1 files at r13, 14 of 37 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644)* status: 24 of 50 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 55 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-NUumzxVDkNsx9TJ3XsW:-NUumzxVDkNsx9TJ3XsX:bf3tubg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/058a8856b1312732f0548b59827a36d0b07b1018/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L55)):*
> ```Kotlin
>                     isAllowLanEnabled = settings?.allowLan ?: false,
>                     selectedObfuscation = settings?.selectedObfuscationSettings()
>                             ?: SelectedObfuscation.Auto,
> ```

what is the default value for this setting? it was "off" in tested dev ices
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 280 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644#-NUum9Iq6fOdHAGM1N4g:-NUum9Iq6fOdHAGM1N4h:b-gpljuj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/058a8856b1312732f0548b59827a36d0b07b1018/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L280)):*
> ```Kotlin
> 
>     fun onSelectObfuscationSetting(selectedObfuscation: SelectedObfuscation) {
>         repository.setObfuscationOptions(
> ```

I suggest to do this within view model scope like other functions

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 41 files at r12, 1 of 1 files at r13, 34 of 37 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r17, 37 of 37 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4644)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

**Pull request merged**
