### PR TITLE
Expose wireguard port ranges to the android app

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`mullvad-types/src/relay_list.rs` line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836#-NZ0NGJx6ftytzHFqTrT:-NZ0NGJx6ftytzHFqTrU:b-cz0omo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11906aa649a54598a6ed98e24f9896dca0f62693/mullvad-types/src/relay_list.rs#L154)):*
> ```XML
> #[cfg_attr(target_os = "android", derive(IntoJava))]
> #[cfg_attr(target_os = "android", jnix(package = "net.mullvad.mullvadvpn.model"))]
> struct PortRange {
> ```

Probably a nitpick, but we should conditionally compile this whole struct. I think you could change the attributes to this:

```rust
#[cfg(target_os = "android")]
#[derive(Clone, Eq, PartialEq, Hash, Debug, IntoJava)]
#[cfg(jnix(package = "net.mullvad.mullvadvpn.model"))]
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-types/src/relay_list.rs` line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836#-NZ0NGJx6ftytzHFqTrT:-NZ105fl0f14wzGCD5bn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11906aa649a54598a6ed98e24f9896dca0f62693/mullvad-types/src/relay_list.rs#L154)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Probably a nitpick, but we should conditionally compile this whole struct. I think you could change the attributes to this:

```rust
#[cfg(target_os = "android")]
#[derive(Clone, Eq, PartialEq, Hash, Debug, IntoJava)]
#[cfg(jnix(package = "net.mullvad.mullvadvpn.model"))]
```
</blockquote></details>

Done.

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4836)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
