### PR TITLE
Update README.md code block format.

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Update README.md code block format.

* [x] The change/commits follow the Mullvad coding guidelines: https://github.com/mullvad/coding-guidelines
* [x] The PR description should describe:
  * **What** some of README.md files.
  * **Why** highlight the syntax in code block.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6558)

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
Dear @MarkusPettersson98 ,

As the comment the PR https://github.com/mullvad/mullvadvpn-app/pull/6558 . Could you please help me to review this PR?

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @MarkusPettersson98 ,

Could you help me to review the PR?

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @faern ,

As the PR https://github.com/mullvad/mullvadvpn-app/pull/6670 . I have one more PR waiting to be reviewed. Would you be able to assist me in dedicating time to review it?

Thanks,
Lam

**Comment by faern** [comment]
I'm not sure this is needed. It makes no practical difference as far as I can see. For the bash blocks, I don't even see any relevant syntax highlighting on Github when rendered.

**Comment by lamtrinhdev** [comment]
Dear @faern ,

Thank you for your feedback. I will closed this PR.

Thanks,
Lam

**Pull request closed without merging**
