### PR TITLE
Add info modals to default access methods screens

### PR DESCRIPTION
**Pull request by rablador**
Changes were made to the info text for the Encrypted DNS proxy, where one of the providers was written incorrectly. Also, to show this info text, new headers have been added to each default access method screen.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8BznuW-KXtfGkswx4w:-O8BznuW-KXtfGkswx4x:bry5e2i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L90)):*
> ```Swift
>                     "DIRECT_ACCESS_METHOD_HEADER_LINK",
>                     tableName: "APIAccess",
>                     value: "About Direct method...",
> ```

It kinda reads weird like this, it should probably be "About the direct method..."
Or if we go the Apple way, we just put "Learn more..."
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 227 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8C-O5E46Iz3ta4voRz:-O8C-O5E46Iz3ta4voS-:b-1oysm0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L227)):*
> ```Swift
>                         If you are not connected to our VPN, then the Encrypted DNS proxy will use your own non-VPN IP \
>                         when connecting.
>                         The DoH servers are hosted by one of the following providers: Quad 9, CloudFlare, or Google.
> ```

"Cloudflare" (no uppercase F)
"Quad 9" should not have a space between Quad and 9

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8BznuW-KXtfGkswx4w:-O8C1UKX7vUtU5uT_kAA:bc2di3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L90)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It kinda reads weird like this, it should probably be "About the direct method..."
Or if we go the Apple way, we just put "Learn more..."
</blockquote></details>

I agree, but I have followed the copy in Figma.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 227 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8C-O5E46Iz3ta4voRz:-O8C1a6K5Zvz4DXUOhFM:b-1bfue1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L227)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

"Cloudflare" (no uppercase F)
"Quad 9" should not have a space between Quad and 9
</blockquote></details>

have followed the copy in Figma, but I guess we can change pure naming errors?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8BznuW-KXtfGkswx4w:-O8C4x3V0CSmpx9xihG0:bbs7nk7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L90)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I agree, but I have followed the copy in Figma.
</blockquote></details>

We should follow Figma here.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 227 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8C-O5E46Iz3ta4voRz:-O8C4zw56_iXBWQlthL-:b-b570i2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L227)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

have followed the copy in Figma, but I guess we can change pure naming errors?
</blockquote></details>

Nope, it should be `Quad9` and `Cloudflare`.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)* status: 14 of 15 files reviewed, 2 unresolved discussions

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 227 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8C-O5E46Iz3ta4voRz:-O8C5-H79zBuStgjdo4v:b12y0hj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L227)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

have followed the copy in Figma, but I guess we can change pure naming errors?
</blockquote></details>

Well Figma is wrong, so we need to update it there too ( :

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift` line 227 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905#-O8C-O5E46Iz3ta4voRz:-O8C5n0RA433ETn8SvQw:b-jtzfwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f3ecfb0b47fc601ea40cecda14414625c6341f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift#L227)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Well Figma is wrong, so we need to update it there too ( :
</blockquote></details>

Matilda has been notified.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6905)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

**Pull request merged**
