### PR TITLE
Replace Kyber with ML-KEM (FIPS 203) for quantum-resistant tunnel secrets

### PR DESCRIPTION
**Pull request by faern**
When adding support for Quantum-resistant tunnels, there were no standardized algorithms for post-quantum secure key encapsulation machanisms (KEM). Mullvad then implemented a scheme where we could mix multiple KEMs in such a way that *all* of them had to be broken in order to break the tunnel. We then put our bets on two promising algorithms: Classic McEliece and CRYSTALS-Kyber.

[NIST recently finished their PQ standardization effort](https://www.nist.gov/news-events/news/2024/08/nist-releases-first-3-finalized-post-quantum-encryption-standards) they have been running for quite a while. One of the new standards, ML-KEM is based off of CRYSTALS-Kyber. It is basically the same thing, but renamed and slightly revised.

It is important to point out that we have no reason to believe Kyber is insecure in any way in our current implementation of quantum-resistant tunnels. But it is nice to upgrade to the standardized KEM. This also means we can upgrade from an unmaintained Kyber dependency, to a hopefully better maintained ML-KEM dependency.

This change requires Rust 1.81 due to `hybrid-array` being very bleeding edge. We currently use Rust 1.80 everywhere. So this does not currently pass CI, nor can be built in our build containers. If we agree we want to use these dependencies, I'm going to make sure we bump everything to Rust 1.81 before this PR is ready for merge.

This is a draft PR since our servers still don't support ML-KEM. I'm still opening the PR, since that will be rolled out to servers shortly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915)* status: 0 of 12 files reviewed, 2 unresolved discussions

___
*[`talpid-tunnel-config-client/src/ml_kem.rs` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-O8HNlq2Amw05htWNRmz:-O8HNlq2Amw05htWNRn-:bsvwn6q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27486214763bdf13c5348fb5d89debb5e783773/talpid-tunnel-config-client/src/ml_kem.rs#L58)):*
> ```XML
>         log::debug!(
>             "ML-KEM decapsulation took {} ms",
>             start.elapsed().as_millis()
> ```

I intend to remove this before merging. It's just here to allow me to more easily verify in logs that I run an app with ML-KEM when testing this.
___
*[`talpid-wireguard/src/config.rs` line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-O8HNvP46-gTP3FAzXBV:-O8HNvP46-gTP3FAzXBW:b-ooxhqm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27486214763bdf13c5348fb5d89debb5e783773/talpid-wireguard/src/config.rs#L127)):*
> ```XML
>         let mut wg_conf = WgConfigBuffer::new();
>         wg_conf
>             .add::<&[u8]>("private_key", self.tunnel.private_key.to_bytes().as_ref())
> ```

This is completely unrelated. I have not yet dug into why these changes are needed. But Rustc is angry at me if I don't make them.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 12 files at r1, 8 of 8 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-:-O8MFcqD-tuIEZWT6dVF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`talpid-tunnel-config-client/src/ml_kem.rs` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-O8HNlq2Amw05htWNRmz:-O8MFPZ8EDdZSPwmgGju:b-mv5sr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27486214763bdf13c5348fb5d89debb5e783773/talpid-tunnel-config-client/src/ml_kem.rs#L58)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I intend to remove this before merging. It's just here to allow me to more easily verify in logs that I run an app with ML-KEM when testing this.
</blockquote></details>

I guess the line you originally referred to has been cleaned up already?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-tunnel-config-client/src/ml_kem.rs` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-O8HNlq2Amw05htWNRmz:-O8MJF610kU3xNsUU96O:b28mrdf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27486214763bdf13c5348fb5d89debb5e783773/talpid-tunnel-config-client/src/ml_kem.rs#L58)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I guess the line you originally referred to has been cleaned up already?
</blockquote></details>

Indeed! It was removed during some rebase and squash after I had verified this code worked on a few platforms.

**Review by MarkusPettersson98 — DISMISSED** [review]
:lgtm:

> Reviewed 8 of 8 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-:-O9E9gbC3lRqBRIrcjA6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @faern and @MarkusPettersson98)

___
*[`ios/CHANGELOG.md` line 32 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-O9EPWr_3BhJzf2GBsAx:-O9EPWr_3BhJzf2GBsAy:b-ogrwo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a420974c814179574b4928d8ef79bf109c0c944b/ios/CHANGELOG.md#L32)):*
> ```Markdown
> ### Changed
> - Replace the draft key encapsulation mechanism Kyber (round 3) with the standardized
>   ML-KEM (FIPS 203) dito in the handshake for Quantum-resistant tunnels.
> ```

Should be under `## Unreleased`.

**Review by albin-mullvad — DISMISSED** [review]
> Reviewed 1 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @faern and @MarkusPettersson98)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 3 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915)* status: 6 of 15 files reviewed, all discussions resolved (waiting on @albin-mullvad and @MarkusPettersson98)

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-:-O9Eb6Rw6XTw_L9By6tS:bnfp4nl)* status: 6 of 15 files reviewed, all discussions resolved (waiting on @albin-mullvad and @MarkusPettersson98)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6915#-:-O9EbHKq2sghnRmz4hCL:bnfp4nl)* status: 6 of 15 files reviewed, all discussions resolved (waiting on @MarkusPettersson98 and @pinkisemils)

**Pull request merged**
