### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by eriklarko**
I think these are all the implemented features and changes that were not in the changelog. I might well be missing something from the `talpid_core` repo though

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/21)

### CODE REVIEW

**Comment by faern** [comment]
If this is the release-branch, don't you also want to bump the version string?

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC42WjL83IDQWiB4q:-L2PC42XyK6q7jNXTHNQ:b1jkwf8) (no related file):*
More changes I see in the commit history:
* Autohiding scrollbars. Not sure if it's worth mentioning, but it's a change that is visible to users.
* Marking cities and countries as active/inactive with a dot in the location list. To show if they have online servers or not.

---

*[CHANGELOG.md, line 16 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC4yfnceg8CpqQ_nq:-L2PC4yfnceg8CpqQ_nr:b-ik9txn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L16)):*
> ```Markdown
> 
> 
> ## [Unreleased]
> ```

If we are planning a release after this PR then update this header accordingly (and make sure there is an empty `[unreleased]` header above it.)

---

*[CHANGELOG.md, line 28 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PAmpOGjJrM4snaSmE:-L2PAmpP8jWCYIPKLQ_M:b-jj09uf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L28)):*
> ```Markdown
>   green lock with a red dot.
> - While connecting, a message telling the user that internet accesss is blocked is shown.
> - Remove the unsafe Camellia and Seed ciphers.
> ```

Would probably fit better under the `Removed` header. Maybe also add "... from the list of allowed OpenVPN ciphers"?

---

*[CHANGELOG.md, line 29 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PAJTT-eELEpn_MOdI:-L2PAJTT-eELEpn_MOdJ:b-ffy0j2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L29)):*
> ```Markdown
> - While connecting, a message telling the user that internet accesss is blocked is shown.
> - Remove the unsafe Camellia and Seed ciphers.
> - The repository is now public on Github.
> ```

I'm not sure I would qualify this as a change to the code/product itself. But if you think it's relevant to mention this in the changelog then we can keep it. I usually aim towards describing changes that are relevant to users of the program. For example, we don't write when we change how the CI builds this project either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-:-L2P9yTFdZwWmjftIt8U:b-8b2xbn)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 28 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PAmpOGjJrM4snaSmE:-L2PD4-FJ_PA4Ng-guU2:b-5gfb2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Would probably fit better under the `Removed` header. Maybe also add "... from the list of allowed OpenVPN ciphers"?
</blockquote></details>

Since we'll soon have two VPN protocols it might be good to describe which one a change is related to was my thought :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 29 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PAJTT-eELEpn_MOdI:-L2PG4cFKh_OC6FDv1QN:b-hp7nin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L29)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure I would qualify this as a change to the code/product itself. But if you think it's relevant to mention this in the changelog then we can keep it. I usually aim towards describing changes that are relevant to users of the program. For example, we don't write when we change how the CI builds this project either.
</blockquote></details>

I don't find it product relevant either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC42WjL83IDQWiB4q:-L2PJdzTr_DLqCqNO_5p:bpyet58) (no related file):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

More changes I see in the commit history:
* Autohiding scrollbars. Not sure if it's worth mentioning, but it's a change that is visible to users.
* Marking cities and countries as active/inactive with a dot in the location list. To show if they have online servers or not.
</blockquote></details>

@faern scrollbars auto-hide feature is quite minor and the entire change is to align with the macOS behavior for scrollbars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC42WjL83IDQWiB4q:-L2PLKiY4XiqxUnEF_Ji:b7bzd98) (no related file):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

@faern scrollbars auto-hide feature is quite minor and the entire change is to align with the macOS behavior for scrollbars.
</blockquote></details>

Sure. It's just that it's very noticeable. Removing some unused ciphers is also quite minor, but worth noting. However, yeah the scrollbars don't affect the *functionality* very much. If you, who work on the FE mostly don't think it's relevant we can ignore it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC42WjL83IDQWiB4q:-L2PSLdKntbFNYkm0W_A:b-3iw4l7) (no related file):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Sure. It's just that it's very noticeable. Removing some unused ciphers is also quite minor, but worth noting. However, yeah the scrollbars don't affect the *functionality* very much. If you, who work on the FE mostly don't think it's relevant we can ignore it.
</blockquote></details>

OK we can add under CHANGED:

- Scrollbars will automatically hide when not scrolling

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by eriklarko** [comment]
I wasn't planning for this to be the release branch, but I can turn this into it

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC42WjL83IDQWiB4q:-L2PTbl85LKxuCZZlZGa:bb6un1j) (no related file):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

OK we can add under CHANGED:

- Scrollbars will automatically hide when not scrolling
</blockquote></details>

Done

---

*[CHANGELOG.md, line 16 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC4yfnceg8CpqQ_nq:-L2PTyHdh-UJn4RDyk7m:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If we are planning a release after this PR then update this header accordingly (and make sure there is an empty `[unreleased]` header above it.)
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 28 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PAmpOGjJrM4snaSmE:-L2PTfTZQXtYfLbqTWti:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since we'll soon have two VPN protocols it might be good to describe which one a change is related to was my thought :)
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 29 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PAJTT-eELEpn_MOdI:-L2PTg3qN1vP-y-3xnPZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a098e40d867e4d10d9f8ad848d20f8ec6a41b0/CHANGELOG.md#L29)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I don't find it product relevant either.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-:-L2PSlf4W3w2i-v0xnJc:bfq4fp2)*

**Comment by eriklarko** [comment]
The branch name is off, but wth

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-:-L2PUhOUjVFN_Rwcfzw9:b25u5mc)*

**Comment by pronebird** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by faern** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21#-L2PC42WjL83IDQWiB4q:-L2PiyFwVw448cpxfXFt:bou6s4f) (no related file):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Ah, great you remembered `relays.json`, I forgot about that! We really need a release checklist somewhere.
:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/21)*

**Pull request merged**
