### PR TITLE
Update data structure to support new obfuscation selection

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064)

### CODE REVIEW

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 128 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OAq_Tls5k8jAJSDrhP7:-OAq_Tls5k8jAJSDrhP8:b-s32ihp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L128)):*
> ```Swift
> 
>     public let state: WireGuardObfuscationState
>     public let udpOverTcpPort: WireGuardObfuscationUdpOverTcpPort
> ```

are we going to keep the previous state when user is changing obfuscation method?  in this architecture, if we add another state into `WireGuardObfuscationState` that has its own custom configuration then we need to add another property for that here, as well. is it the thing we will?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OAriaWsA_KDeBwtO-JK:-OAvn_30D5cyqH2CqKb8:b-4ncs6g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L56)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should not be `Optional`, we always know the real value of the port.
</blockquote></details>

We don't, since `.automatic` isn't really equal to eg. 0 we should properly represent that a port has not been explicity set.
___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 128 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OAq_Tls5k8jAJSDrhP7:-OAvmra274n16rSsb88g:bcwftrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L128)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

are we going to keep the previous state when user is changing obfuscation method?  in this architecture, if we add another state into `WireGuardObfuscationState` that has its own custom configuration then we need to add another property for that here, as well. is it the thing we will?
</blockquote></details>

I think so. Doing it this way we keep each port setting no matter what other settings the user changes, so that's according to spec I think. Unfortunately we could not - in a good way - combine state and port into a single enum. The reason for that being that we set state and port in different places at different times, which makes it really bothersome to keep track of in a viewmodel.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OArjCKY-fbKYvuXFjXc:-OAvowIC-vU4Mi91pN6X:bpv8cqg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L61)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is the reason why `portValue` shouldn't be nullable. `0` is an invalid port number in this case, and it should be impossible
to have this condition here since if the obfuscation is set to `automatic` it would either be `80` or `5001`
</blockquote></details>

That won't be true for long. This code will change when the relay selector PR goes up, and this part will handle the custom port for shadowsocks as well, which can be anything. I don't think we should be relying on an Int that's implicitly wrong if it happens to be a 0 but correct if it's a 1.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OArjCKY-fbKYvuXFjXc:-OAvwAuh0jgeJXjFsIOb:bqnx9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L61)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

That won't be true for long. This code will change when the relay selector PR goes up, and this part will handle the custom port for shadowsocks as well, which can be anything. I don't think we should be relying on an Int that's implicitly wrong if it happens to be a 0 but correct if it's a 1.
</blockquote></details>

Just to clarify, in the new code there won't be any fallbacks like this.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OAriaWsA_KDeBwtO-JK:-OAw6RCd3VWldTGe154t:bxplirk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L56)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We don't, since `.automatic` isn't really equal to eg. 0 we should properly represent that a port has not been explicity set.
</blockquote></details>

This was discussed offline.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-OArjCKY-fbKYvuXFjXc:-OAw6VNwA2XedQ7jQHVU:b-93926e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/067219c91010e7f6d63796bc7855e50c0a799ea5/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L61)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Just to clarify, in the new code there won't be any fallbacks like this.
</blockquote></details>

Sounds good then, a temporary solution is fine.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064#-:-OAwrAQ_4Wyk99IZJUrB:bnfp4nl)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Pull request merged**
