### PR TITLE
Fix mission control and workspace-related bugs in window behaviour on macOS

### PR DESCRIPTION
**Pull request by claucambra**
The tray window currently exhibits some small bugs when interacting with it in mission control and in full-screen spaces.

Since the app is intended as a menu bar panel, the window should not be presented in mission control. At the moment it is, and trying to interact with it causes it to immediately hide:

https://user-images.githubusercontent.com/70155116/222907056-ac45a660-f7a0-4a95-96a7-4b12fcc0bfa7.mov

The correct behaviour would be for it to not appear in mission control at all, hence the changes in d87514660ea16adc5aa39ebd5068d58a96e1863f which does this.

While the window correctly has set `appWindow.setVisibleOnAllWorkspaces(true);`, it does not pass the second parameter, an options object with `visibleOnFullScreen: true`. This means the app window does not have `NSWindowCollectionBehaviorFullScreenAuxiliary` set, causing buggy behaviour in full-screen spaces:

https://user-images.githubusercontent.com/70155116/222907042-679db556-de60-4f25-aff8-d586ce619ba7.mov

Hence the changes in a64ac3c98cde1b332d6c520c06563d3b7a15f1e1

EDIT: Demo of the fixed full screen behaviour

https://user-images.githubusercontent.com/70155116/223155588-751ba1e4-72b2-47ed-9920-7611cf423439.mov

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4416)

### CODE REVIEW

**Comment by raksooo** [comment]
Thanks for fixing this! I've had trouble reproducing this so it's great to get some help here! I'll review it in a moment.

**Comment by claucambra** [comment]
> Thanks for fixing this! I've had trouble reproducing this so it's great to get some help here! I'll review it in a moment.

No worries, happy to help :)

**Comment by raksooo** [comment]
I just had a look at this and realized that Electron needs to be upgraded for `hiddenInMissionControl` to be available. I'm planning on upgrading Electron very soon so I'll ping you when it's done.

**Comment by raksooo** [comment]
I've now updated Electron. Could you rebase your branch on latest `main`? The changelog line might end up in the wrong section since we've created a release  since this was last updated.

**Comment by claucambra** [comment]
Hi @raksooo branch is up to date with main, the changelog line is still under [unreleased] -- let me know if you need me to do anything further :)

**Comment by raksooo** [comment]
There are no changes here on GitHub as far as I can tell. Did you forget to push? :)

**Comment by claucambra** [comment]
> There are no changes here on GitHub as far as I can tell. Did you forget to push? :)

Sorry, I rebased on my fork 😅 fixed now

**Review by raksooo — APPROVED** [review]
Great! Thank you!

**Pull request merged**
