### PR TITLE
Remove explanatory text for Direct only in settings

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044)

### CODE REVIEW

**Review by pinkisemils — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044#-:-O9sUFprAakDO_mjy61u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044#-O9se6eC5twlCARJnLkC:-O9sgzo-0nqu737uWUO4:blfjw7u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2632a6ca677521e1e4fc7939c5e2126ba03c5c/ios/MullvadVPN/View%20controllers/Settings/SettingsDataSource.swift#L139)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can remove all three functions when we don't have footer anymore.
</blockquote></details>

The header function can indeed be removed, but unfortunately not the footer ones. Apple adds default section spacing that we don't want.

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044#-O9sf7AX4CxM6-P_PuFN:-O9shIovCAt2g6hqPDnZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2632a6ca677521e1e4fc7939c5e2126ba03c5c/ios/MullvadVPN/View%20controllers/Settings/SettingsDataSource.swift#L175)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

both can be replace by one :
</blockquote></details>

Done.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mojganii and @pinkisemils)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044#-O9se6eC5twlCARJnLkC:-O9sjYqL9ApQopBj-kmU:b4ac91s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2632a6ca677521e1e4fc7939c5e2126ba03c5c/ios/MullvadVPN/View%20controllers/Settings/SettingsDataSource.swift#L139)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The header function can indeed be removed, but unfortunately not the footer ones. Apple adds default section spacing that we don't want.

</blockquote></details>

Oh, but we can of course remedy this by setting footer height on the tableview itself. Se `tableView.sectionFooterHeight = 0` above.

**Review by mojganii — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044#-:-O9stAnEErmSD0_wOpIC:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Pull request merged**
