### PR TITLE
Cache the transportStrategy in the UserDefaults

### PR DESCRIPTION
**Pull request by buggmagnet**
This work was done in the `ios-prepare-2023.4` branch, but was never back ported to main.
This PR fixes that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)

### CODE REVIEW

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadTypes/AttemptsRecording.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgOx2bAC5ooOAvb7cNC:-NgP5vLE2S3HGQTPFJdc:bhmqqqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/MullvadTypes/AttemptsRecording.swift#L15)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This method isn't called anywhere in this diff.  Should this protocol exist?
</blockquote></details>

It shouldnt, I thought I had deleted that file.
Thanks for catching it !

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPRrhD0rUOc5HHq18A:-NgPRrhD0rUOc5HHq18B:b4rcprq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L44)):*
> ```Swift
>         let shadowsocksCache = ShadowsocksConfigurationCache(cacheDirectory: containerURL)
> 
>         // This init cannot fail as long as the security group identifier is valid
> ```

Perhaps missing:

`// swiftlint:disable:next force_cast`

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPSzjK4RTs_xhUNiid:-NgPSzjK4RTs_xhUNiie:b-ui1h5x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3bed86d9cccbf280c47a1b85fd9276981ddefec2/ios/MullvadREST/RESTTransportStrategy.swift#L2)):*
> ```Swift
> //
> //  RESTTransportStrategy.swift
> ```

Mhm I think I renamed it with "REST" prefix a while ago.
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPStF_4KxJXcxtkgry:-NgPStFa4OS01N-XQqRS:bcf38nr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/MullvadREST/RESTTransportStrategy.swift#L10)):*
> ```Swift
> 
> import Foundation
> import MullvadTypes
> ```

Probably unused import.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @pinkisemils and @pronebird)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPSzjK4RTs_xhUNiid:-NgSTfjC-J968X61OJDz:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3bed86d9cccbf280c47a1b85fd9276981ddefec2/ios/MullvadREST/RESTTransportStrategy.swift#L2)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Mhm I think I renamed it with "REST" prefix a while ago.
</blockquote></details>

Done
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPStF_4KxJXcxtkgry:-NgSTuOZE4T9_g3-KRPZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/MullvadREST/RESTTransportStrategy.swift#L10)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably unused import.
</blockquote></details>

Done.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @pinkisemils and @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPRrhD0rUOc5HHq18A:-NgSWUxOCSm_aRByygJ5:bhkk1ho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L44)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Perhaps missing:

`// swiftlint:disable:next force_cast`
</blockquote></details>

Huh that's odd, I don't get that warning either in the CLI, or in Xcode...
Thanks for catching that up. The same fix needs to be applied in AppDelegate too.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @pinkisemils and @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPRrhD0rUOc5HHq18A:-NgSaIJy5DcOGB4_uRJQ:bytcxi2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L44)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Huh that's odd, I don't get that warning either in the CLI, or in Xcode...
Thanks for catching that up. The same fix needs to be applied in AppDelegate too.
</blockquote></details>

Ok, the reason why this was not flagged up is twofold:
- This is not a `force_cast` but a `force_unwrapping` triggering example
- We did not enable `force_unwrapping` 

As this code cannot possibly fail, I will leave it as is, and I opened a discussion about our use of `force_unwrapping` for our linter rules

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-:-NgXs8AG-VMzCmfuyzTb:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262#-NgPRrhD0rUOc5HHq18A:-NgYi99Z-U5KwSfzcPb9:b-b6qf18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e85d151e73bf44d7019e3f95a0ac7849c51c68ec/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L44)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Ok, the reason why this was not flagged up is twofold:
- This is not a `force_cast` but a `force_unwrapping` triggering example
- We did not enable `force_unwrapping` 

As this code cannot possibly fail, I will leave it as is, and I opened a discussion about our use of `force_unwrapping` for our linter rules
</blockquote></details>

This can be tackled separately.

**Pull request merged**
