### PR TITLE
Don't attempt to connect if current state is 'secured'

### PR DESCRIPTION
**Pull request by pinkisemils**
Currently, if the app starts and the daemon is already connected, the app will end up showing a _connecting_ state. In these changes, I change `Backend.connect()` to not attempt to connect and reset the state if the app is already connected. At first, I was thinking about conditionally calling `backend.conenct()`, and I still feel unsure would be the best place to change this behaviour.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/135)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[app/lib/backend.js, line 481 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAPZkDW2R6Gf5rl6q41:-LAPZkDW2R6Gf5rl6q42:brlbilm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L481)):*
> ```JavaScript
> 
>   async _registerIpcListeners() {
>     log.debug('registerin ipc listeners');
> ```

A little typo

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 487 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAPZwTwC-1V4UzdZlOX:-LAPZwTwC-1V4UzdZlOY:bfagta3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L487)):*
> ```JavaScript
> 
>       const newStatus = this._securityStateToConnectionState(newState);
>       log.debug('Got newStatus: ', newStatus);
> ```

Some sort of log consolidation would be nicer. e.g. we can log once that we've got a new state from backend and then log the translated value too.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 487 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAPZwTwC-1V4UzdZlOX:-LAP_4wW3mUmqpBVncny:bq573yo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L487)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Some sort of log consolidation would be nicer. e.g. we can log once that we've got a new state from backend and then log the translated value too.
</blockquote></details>

Something like:

```
this._ipc.registerStateListener(newState => {
  let connectionState = this._securityStateToConnectionState(newState);

  log.debug(`Got new state from backend ${newState}, translated to ${connectionState}`);

  this._dispatchConnectionState(connectionState);
  this.sync();
});
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 265 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAP_iZr4STy9_0AZNbp:-LAP_iZr4STy9_0AZNbq:bwrqni9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L265)):*
> ```JavaScript
> 
>   async connect() {
>     let current_state = await this._ipc.getState();
> ```

`await` without `try {} catch {}` is likely to propagate error upwards and cause a crash in the FE. I don't have the right error handling strategy in mind at this time, but something tells me that at least we should log an error and maybe `return;` if we have no recovery strategy yet.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/lib/backend.js, line 265 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAP_iZr4STy9_0AZNbp:-LAPa9bT--SqOqNbwa6z:bhqk5b3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L265)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

`await` without `try {} catch {}` is likely to propagate error upwards and cause a crash in the FE. I don't have the right error handling strategy in mind at this time, but something tells me that at least we should log an error and maybe `return;` if we have no recovery strategy yet.
</blockquote></details>

So:

```
try {
  let currentState = let current_state = await this._ipc.getState();
} catch (e) {
  log.error(`Something went wrong: ${e.message}`);
  return;
}
```

Also please stick to camelCase since the rest of project uses it and it's common across JavaScript projects. I know sometimes switching from Rust to JS is not easy. :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/lib/backend.js, line 265 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAP_iZr4STy9_0AZNbp:-LAPac7e9uJ0LXmrispK:b-ysdijm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L265)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

So:

```
try {
  let currentState = let current_state = await this._ipc.getState();
} catch (e) {
  log.error(`Something went wrong: ${e.message}`);
  return;
}
```

Also please stick to camelCase since the rest of project uses it and it's common across JavaScript projects. I know sometimes switching from Rust to JS is not easy. :)
</blockquote></details>

Sorry the sample code I posted above is rubbish, I mean:

```
try {
  let currentState = await this._ipc.getState();
  if(currentState === 'secured') {
    log.debug('Refusing ...');  
  }
} catch (e) {
  log.error(`Something went wrong: ${e.message}`);
  return;
}
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/lib/backend.js, line 265 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-LAP_iZr4STy9_0AZNbp:-LAPauC502ID5nXfmjl8:b-kijiio) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91837b0169ced744dcf94077c2b360751a60c387/app/lib/backend.js#L265)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Sorry the sample code I posted above is rubbish, I mean:

```
try {
  let currentState = await this._ipc.getState();
  if(currentState === 'secured') {
    log.debug('Refusing ...');  
  }
} catch (e) {
  log.error(`Something went wrong: ${e.message}`);
  return;
}
```
</blockquote></details>

I hope you get the point.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
I think it's fine for now. To be fair I'd like to rewrite the `Backend` entirely.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-:-LAPb5Dr9pMPOMjPExqS:b-c97xz)*

**Comment by faern** [comment]
I'm not confident enough in this code base to say if it's correct or not. Rely on the feedback from Andrei :)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-:-LARu1uf5qHopI-8Be71:b-m6lo59)*

**Comment by faern** [comment]
...And Janito. But I can be excluded from GUI-only PRs unless it's something about overall functionality or expected behavior to discuss.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-:-LARuNFY3L8VIJqZQ_nz:bgxfjp3)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135#-:-LASEqY8CNVGv9GsoGHN:bnfp4nl)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/135)*

**Pull request closed without merging**
