### PR TITLE
Make post-quantum tunnel setting optional

### PR DESCRIPTION
**Pull request by dlon**
It should be optional since the default/auto value may change. If `quantum-resistant-tunnel` was previously set to `off`, it will now instead be set to the default/auto.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 1 of 28 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-management-interface/proto/management_interface.proto` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNftvb931mdwa60OHEV:-NNftvb931mdwa60OHEW:b-cpdfgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-management-interface/proto/management_interface.proto#L47)):*
> ```protobuf
> 	rpc SetEnableIpv6(google.protobuf.BoolValue) returns (google.protobuf.Empty) {}
> 	rpc SetQuantumResistantTunnel(google.protobuf.BoolValue) returns (google.protobuf.Empty) {}
> 	rpc ResetQuantumResistantTunnel(google.protobuf.Empty) returns (google.protobuf.Empty) {}
> ```

Do we really need two separate set methods (reset is basically a set to a defined default value)? Any reason we can't implement this the same way as `SetBridgeState`? Would be nice to have all settings that have auto/on/off as their values to be implemented in the same way IMO.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 1 of 28 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-management-interface/proto/management_interface.proto` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNftvb931mdwa60OHEV:-NNg-1AW9-lIuIsxB_Pt:b-u4xh96) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-management-interface/proto/management_interface.proto#L47)):*
Sure, that makes sense.

We should probably ask the same question for `ResetWireguardRotationInterval`.

And also whether we might just want a single function for setting all tunnel options.

> Would be nice to have all settings that have auto/on/off as their values to be implemented in the same way IMO.

Even for relay constraints, or just tunnel options?

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 9 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 10 of 28 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/wireguard.rs` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNfwKgj3oxMs_qX-MtP:-NNfwKgj3oxMs_qX-MtQ:bapudme) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-types/src/wireguard.rs#L136)):*
> ```XML
>     /// Temporary switch for wireguard-nt
>     #[cfg(windows)]
>     #[serde(default = "default_wgnt_setting")]
> ```

Is this really needed? :thinking: We have `#[serde(default)]` on the struct, so if the value is missing when deserializing it should be picked up from the `Default` impl of the struct. But maybe I'm missing some of the intricate details here :P

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 9 of 28 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/wireguard.rs` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNfwKgj3oxMs_qX-MtP:-NNgUB_n9NBfR5AM7tNe:bzif3lr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-types/src/wireguard.rs#L136)):*
Ok. We'll have to try that then. The docs for `#[serde(default)]` on **structs** says:

> When deserializing, any missing fields should be filled in from the struct's implementation of Default. Only allowed on structs.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 9 of 28 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`mullvad-types/src/wireguard.rs` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNfwKgj3oxMs_qX-MtP:-NNga11H9VjvXiWOLB9N:bm01jye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-types/src/wireguard.rs#L136)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ok. We'll have to try that then. The docs for `#[serde(default)]` on **structs** says:

> When deserializing, any missing fields should be filled in from the struct's implementation of Default. Only allowed on structs.
</blockquote></details>

You are correct! I tried it out. So I'll simplify this.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r2, 1 of 2 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 12 of 28 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/migrations/v6.rs` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNkQOA0AfoqyXXM281Q:-NNkQOA0AfoqyXXM281R:b-c6kn2x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7a940d98d4de633e112adc8b92f46d7d5908e33/mullvad-daemon/src/migrations/v6.rs#L2)):*
> ```XML
> use super::{Error, Result};
> use mullvad_types::{settings::SettingsVersion, wireguard::QuantumResistantState};
> ```

`QuantumResistantState` must be vendored into this module. It's not in the list of allowed types in `migrations/mod.rs`
___
*[`mullvad-management-interface/proto/management_interface.proto` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNftvb931mdwa60OHEV:-NNkC16eEAq_n2lS1GNa:b7tkuua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-management-interface/proto/management_interface.proto#L47)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Sure, that makes sense. I think the only 

We should probably ask the same question for `ResetWireguardRotationInterval`.

And also whether we might just want a single function for setting all tunnel options.

> Would be nice to have all settings that have auto/on/off as their values to be implemented in the same way IMO.

Even for relay constraints, or just tunnel options?
</blockquote></details>

Sounds like a scope creep. Let's not discuss those things in this thread. Marking as resolved.
___
*[`mullvad-types/src/wireguard.rs` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNfwKgj3oxMs_qX-MtP:-NNggSNJA5RfeZUXTlhe:b-ra0xjj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35b415cd441494fcf9d3c218c79051ff41efb28d/mullvad-types/src/wireguard.rs#L136)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:partying_face: 
___
*[`mullvad-types/src/wireguard.rs` line 175 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNkADpd0lU-WTDcXDUd:-NNkADpd0lU-WTDcXDUe:bpw9wii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7a940d98d4de633e112adc8b92f46d7d5908e33/mullvad-types/src/wireguard.rs#L175)):*
> ```XML
> }
> 
> impl From<TunnelOptions> for wireguard::TunnelOptions {
> ```

So this is how this ends up being used:

```rust
wireguard::TunnelOptions::from(tunnel_options.wireguard)
```

It's very hard to see that we are crossing the mullvad->talpid layer. In general I think that's a problem to follow in many places. I'm thinking that a dedicated `fn into_talpid_tunnel_options(self) -> talpid_types::...`. Then the place where it's used would look like:

```rust
tunnel_options.wireguard.into_talpid_tunnel_options()
```

What's your thought on that? :thinking:

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 10 of 28 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`mullvad-daemon/src/migrations/v6.rs` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNkQOA0AfoqyXXM281Q:-NNkd0xWDQYqT8O49dDt:bqdw6ru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7a940d98d4de633e112adc8b92f46d7d5908e33/mullvad-daemon/src/migrations/v6.rs#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`QuantumResistantState` must be vendored into this module. It's not in the list of allowed types in `migrations/mod.rs`
</blockquote></details>

I figured we probably only need to vendor it when "closing" the migration. But there should be no harm in doing it now, so done.
___
*[`mullvad-types/src/wireguard.rs` line 175 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNkADpd0lU-WTDcXDUd:-NNkf3fV00D2HXLxpp2z:b-v2wozd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7a940d98d4de633e112adc8b92f46d7d5908e33/mullvad-types/src/wireguard.rs#L175)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

So this is how this ends up being used:

```rust
wireguard::TunnelOptions::from(tunnel_options.wireguard)
```

It's very hard to see that we are crossing the mullvad->talpid layer. In general I think that's a problem to follow in many places. I'm thinking that a dedicated `fn into_talpid_tunnel_options(self) -> talpid_types::...`. Then the place where it's used would look like:

```rust
tunnel_options.wireguard.into_talpid_tunnel_options()
```

What's your thought on that? :thinking: 
</blockquote></details>

Done. That's more readable, for sure.

**Review by faern — CHANGES_REQUESTED** [review]
The PR description is not correct with regards to the setting now being a relay constraint. A bit nitpicky, but could be good to fix in order help people landing on this PR in the future.

> Reviewed 1 of 26 files at r2, 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-:-NNlSFDW7IZifk6Tu86h:bui3tik)* status: 16 of 28 files reviewed, 3 unresolved discussions (waiting on @dlon)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNlSUtM-EOOqa4UNQAT:-NNlSUtM-EOOqa4UNQAU:b4tmk5r) (no related file):*
I think you should add this change to the changelog. IMO it is a relevant change for users to know about. Since we change the off setting into auto, we are fiddling with a users (potentially explicitly set) setting

___
___
*[`mullvad-daemon/src/management_interface.rs` line 353 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNubNzY26dAyo9naVVu:-NNubNzY26dAyo9naVVv:bpfqhjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-daemon/src/management_interface.rs#L353)):*
> ```XML
>     ) -> ServiceResult<()> {
>         let state =
>             match types::quantum_resistant_state::State::from_i32(request.into_inner().state) {
> ```

Here a gRPC type leaks into `mullvad-daemon`. They should be confined to the `mullvad-management-interface` crate, right? The implementation details should not be exposed from that crate.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r4, 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 21 of 28 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-management-interface/src/types/conversions/settings.rs` line 91 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNudQQiCK7uooNVZBjB:-NNudQQj-uWAnG9iChfr:bge57ji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-management-interface/src/types/conversions/settings.rs#L91)):*
> ```XML
>                 quantum_resistant: match options.wireguard.quantum_resistant {
>                     mullvad_types::wireguard::QuantumResistantState::Auto => Some(proto::QuantumResistantState {
>                         state: i32::from(proto::quantum_resistant_state::State::Auto),
> ```

These conversions seems to be made by matching in multiple places in the codebase? Can we consider constraining this to a single place in the `mullvad-management-interface` crate and have everyone else just operate over the `mullvad_types::...::QuantumResistantState` enum?
___
*[`mullvad-types/src/wireguard.rs` line 175 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNkADpd0lU-WTDcXDUd:-NNue1YIBdSC6a8jDXRV:bmr1rxo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7a940d98d4de633e112adc8b92f46d7d5908e33/mullvad-types/src/wireguard.rs#L175)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. That's more readable, for sure.
</blockquote></details>

Great! But I'd consider removing the `From` impl also, so there is only one way of doing it. Forces the more readable way onto all callers.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 16 of 30 files reviewed, 3 unresolved discussions (waiting on @faern)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNlSUtM-EOOqa4UNQAT:-NNulVXF-2D12zAGsKK8:b-896fix) (no related file):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think you should add this change to the changelog. IMO it is a relevant change for users to know about. Since we change the off setting into auto, we are fiddling with a users (potentially explicitly set) setting
</blockquote></details>

Done.

___
___
*[`mullvad-daemon/src/management_interface.rs` line 353 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNubNzY26dAyo9naVVu:-NNukXy7C7Ijh3ual-wn:b1n32gl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-daemon/src/management_interface.rs#L353)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Here a gRPC type leaks into `mullvad-daemon`. They should be confined to the `mullvad-management-interface` crate, right? The implementation details should not be exposed from that crate.
</blockquote></details>

Done. It's not 100% like that right now, but we should definitely strive for it.
___
*[`mullvad-management-interface/src/types/conversions/settings.rs` line 91 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNudQQiCK7uooNVZBjB:-NNul44H2TRaZQPHsisZ:byph4wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-management-interface/src/types/conversions/settings.rs#L91)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These conversions seems to be made by matching in multiple places in the codebase? Can we consider constraining this to a single place in the `mullvad-management-interface` crate and have everyone else just operate over the `mullvad_types::...::QuantumResistantState` enum?
</blockquote></details>

Done. It's actually only used in one place, but the proto to mullvad conversion was used in two.
___
*[`mullvad-types/src/wireguard.rs` line 175 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNkADpd0lU-WTDcXDUd:-NNulJGhB8RMpcpzO49y:biqkm2r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7a940d98d4de633e112adc8b92f46d7d5908e33/mullvad-types/src/wireguard.rs#L175)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Great! But I'd consider removing the `From` impl also, so there is only one way of doing it. Forces the more readable way onto all callers.
</blockquote></details>

Great idea. I did consider doing that as well, so now it's done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 17 of 30 files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/migrations/v6.rs` line 44 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNuftBnENnTdp_wRB6n:-NNuftBnENnTdp_wRB6o:b-gv9xz6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-daemon/src/migrations/v6.rs#L44)):*
> ```XML
> }
> 
> fn get_wireguard_tunnel_options(
> ```

Nit: I'd put this function after `fn migrate_pq_settings` since it's used by that function. More natural flow if the definition of smaller helper functions comes after the usage.
___
*[`mullvad-daemon/src/migrations/v6.rs` line 50 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNuh-A09E5XGbY4IWBv:-NNuh-A09E5XGbY4IWBw:b5onfuu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-daemon/src/migrations/v6.rs#L50)):*
> ```XML
>         return relay_settings.get_mut("wireguard");
>     }
>     None
> ```

This function can be simplified to `settings.get_mut("tunnel_options")?.get_mut("wireguard")`

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 17 of 30 files reviewed, 4 unresolved discussions (waiting on @faern)

___
*[`mullvad-daemon/src/migrations/v6.rs` line 50 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NNuh-A09E5XGbY4IWBv:-NO8u2DH8-lMvID1MYd3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6661a8289607b7d7e1817fcb0255eeb84a2895c9/mullvad-daemon/src/migrations/v6.rs#L50)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This function can be simplified to `settings.get_mut("tunnel_options")?.get_mut("wireguard")`
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 25 of 30 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`CHANGELOG.md` line 35 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOJAvDvBl0L45jSwaOO:-NOJAvDvBl0L45jSwaOP:bm6nt0s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e12bd02baf2f2386fc08c48ebe97d05e30bc6ee6/CHANGELOG.md#L35)):*
> ```Markdown
> - Add "auto" setting for the quantum-resistant tunnel feature, and make it the default. If it was
>   previously set to off, it will now be set to auto instead. That currently means the same thing as
>   "off", but this will change in the future.
> ```

I think we should go with "might change" since nothing is decided and we should not over-promise.
___
*[`mullvad-daemon/src/migrations/v6.rs` line 57 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOiutdV1791JeXfBF0U:-NOiutdV1791JeXfBF0V:bdxt937) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/969c8991434c4e5afb73e6363564820683bd1535/mullvad-daemon/src/migrations/v6.rs#L57)):*
> ```XML
>             .as_object_mut()
>             .ok_or(Error::NoMatchingVersion)?
>             .remove("use_pq_safe_psk");
> ```

Remove returns the value, if one exists. Could you not utilize this to not have to both get the value and then remove it? Would be a bit less code and would not need repeating of the same field name.

```rust
if let Some(psk_settings) = tunnel_options.as_object_mut()...remove("use_...") {
}
```
___
*[`mullvad-daemon/src/migrations/v6.rs` line 65 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOiu5rWATaXpJqEW63e:-NOiu5rWATaXpJqEW63f:b42uqte) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/969c8991434c4e5afb73e6363564820683bd1535/mullvad-daemon/src/migrations/v6.rs#L65)):*
> ```XML
>     settings: &mut serde_json::Value,
> ) -> Option<&mut serde_json::Value> {
>     settings.get_mut("tunnel_options")?.get_mut("wireguard")
> ```

This function is only used in a single place. Does it really need its own function? Feels like it can be inlined without any noticeable readability loss?
___
*[`mullvad-management-interface/src/types/conversions/settings.rs` line 162 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOix7PnCrW_APyBGc2P:-NOix7PnCrW_APyBGc2Q:b-s3rvcg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/969c8991434c4e5afb73e6363564820683bd1535/mullvad-management-interface/src/types/conversions/settings.rs#L162)):*
> ```XML
>                     .quantum_resistant
>                     .map(mullvad_types::wireguard::QuantumResistantState::try_from)
>                     .unwrap_or(Ok(mullvad_types::wireguard::QuantumResistantState::Auto))?,
> ```

Does this silently fall back to auto if we fail to convert gRPC TunnelOptions into a mullvad_types TunnelOption? Feels like that should be a hard error. Or in what scenario can the `Ok(Auto)` code bath here be taken? I assume it's when the field is *missing*, but can that happen?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: 22 of 30 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`CHANGELOG.md` line 35 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOJAvDvBl0L45jSwaOO:-NOjpjch4FGWd5BqLT-a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e12bd02baf2f2386fc08c48ebe97d05e30bc6ee6/CHANGELOG.md#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should go with "might change" since nothing is decided and we should not over-promise.
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/migrations/v6.rs` line 57 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOiutdV1791JeXfBF0U:-NOjpllKCD97B7ab4vqK:bu6lg2o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/969c8991434c4e5afb73e6363564820683bd1535/mullvad-daemon/src/migrations/v6.rs#L57)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Remove returns the value, if one exists. Could you not utilize this to not have to both get the value and then remove it? Would be a bit less code and would not need repeating of the same field name.

```rust
if let Some(psk_settings) = tunnel_options.as_object_mut()...remove("use_...") {
}
```
</blockquote></details>

Done. Nice suggestion.
___
*[`mullvad-management-interface/src/types/conversions/settings.rs` line 162 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOix7PnCrW_APyBGc2P:-NOjqShA9CXz-8WeVG26:b-mmmo5h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/969c8991434c4e5afb73e6363564820683bd1535/mullvad-management-interface/src/types/conversions/settings.rs#L162)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this silently fall back to auto if we fail to convert gRPC TunnelOptions into a mullvad_types TunnelOption? Feels like that should be a hard error. Or in what scenario can the `Ok(Auto)` code bath here be taken? I assume it's when the field is *missing*, but can that happen?
</blockquote></details>

It can happen when a gRPC client doesn't provide a value for the field (possible since nearly everything is optional). That probably should never occur, so I've made it a hard error.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 3 of 26 files at r2, 2 of 9 files at r7, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-:-NOn5EtpAnJCMdMkHIlX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/migrations/v6.rs` line 51 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333#-NOn3Tr_9YAzGhRQ4S9a:-NOn3Tr_9YAzGhRQ4S9b:b-bg0iac) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c921c65ed5cfaf890f940f692500b98a419bdf0/mullvad-daemon/src/migrations/v6.rs#L51)):*
> ```XML
>         if let Some(psk_setting) = tunnel_options
>             .as_object_mut()
>             .ok_or(Error::NoMatchingVersion)?
> ```

This setting is renamed. I think a rebase is needed.

**Review by faern — APPROVED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4333)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
