### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR fixes new `clippy` lints from the latest release

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261#-:-OCnHHLo20ySzK7rSGiu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261#-OCnIU8s7k8Iv6hG6EfZ:-OCnIU8s7k8Iv6hG6Ef_:bxqw0kx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/213f0ef18a4ea6dbe6fac4bb91e5841f6e016909/mullvad-daemon/src/macos_launch_daemon.rs#L81)):*
> ```XML
>     /// It must be kept in sync with the path defined in
>     /// `dist-assets/pkg-scripts/postinstall`.
>     const DAEMON_PLIST_PATH: &CStr = c"/Library/LaunchDaemons/net.mullvad.daemon.plist";
> ```

:amaze: that Cippy catched this :D
___
*[`mullvad-cli/src/cmds/relay.rs` line 398 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261#-OCnIQp9844helAjGQqm:-OCnIQp9844helAjGQqn:bdhged8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/213f0ef18a4ea6dbe6fac4bb91e5841f6e016909/mullvad-cli/src/cmds/relay.rs#L398)):*
> ```XML
>     }
> 
>     // Get active relays which are not bridges.
> ```

Hue? shouldn't this be a docstring?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dlon and @hulthe)

___
*[`mullvad-cli/src/cmds/relay.rs` line 398 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261#-OCnIQp9844helAjGQqm:-OCnLGfH-75n04pl9vHY:b-mkcufu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/213f0ef18a4ea6dbe6fac4bb91e5841f6e016909/mullvad-cli/src/cmds/relay.rs#L398)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Hue? shouldn't this be a docstring?
</blockquote></details>

Yes. :see_no_evil: 
___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261#-OCnIU8s7k8Iv6hG6EfZ:-OCnLMC0-TpZ7R5Sa2iE:b-eulnr2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/213f0ef18a4ea6dbe6fac4bb91e5841f6e016909/mullvad-daemon/src/macos_launch_daemon.rs#L81)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

:amaze: that Cippy catched this :D
</blockquote></details>

So good! :sparkles:

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7261)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
