### PR TITLE
Test app relay connection

### PR DESCRIPTION
**Pull request by niklasberglund**
Implemented app relay connection test. To test this out run the `testAppConnection` under `RelayTests`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 3 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY0ZM8E0ffUweiIG4b:-NuY0ZM8E0ffUweiIG4c:b-ni4ei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
please undelete the file
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 159 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY0f0Q7fn7Bt1MQOz_:-NuY0f0Q7fn7Bt1MQOza:b-khvx8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPNUITests/Networking/Networking.swift#L159)):*
> ```Swift
>     public static func verifyConnectedThroughMullvad() {
>         let mullvadConnectionJsonEndpoint = "https://am.i.mullvad.net/json"
>         guard let url = URL(string: mullvadConnectionJsonEndpoint) else {
> ```

This should never fail, it's okay to use `let url = try XCTUnwrap(URL(string: mullvadConnectionJsonEndpoint))` in such cases
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY2vRqCaK5Sc5kssjk:-NuY2vRqCaK5Sc5kssjl:b-r9xxt0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPNUITests/Networking/Networking.swift#L181)):*
> ```Swift
> 
>             guard let data = data else {
>                 XCTFail("Unexpectedly didn't receive any data")
> ```

nit
This double negation could be worded slightly better IMHO
How about "Unexpected empty data received"

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 159 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY0f0Q7fn7Bt1MQOz_:-Nuch2sNEPvkvnLRKlCp:b-muzqe0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPNUITests/Networking/Networking.swift#L159)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should never fail, it's okay to use `let url = try XCTUnwrap(URL(string: mullvadConnectionJsonEndpoint))` in such cases
</blockquote></details>

I should probably use `XCTUnwrap` more but this function doesn't throw so I think in this instance it wouldn't simplify anything since the exception would still need to be caught?
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY2vRqCaK5Sc5kssjk:-NuchZmT00Qnb56DuWvA:bczroq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPNUITests/Networking/Networking.swift#L181)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
This double negation could be worded slightly better IMHO
How about "Unexpected empty data received"
</blockquote></details>

How about `"Didn't receive any data`? See change
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY0ZM8E0ffUweiIG4b:-Nuchsr0B-nNEfrnY5ZU:bievx1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

please undelete the file
</blockquote></details>

Don't know how I keep committing deletions of this file. It has been restored now.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-:-Nux2TuJ-wn5iENHYFHg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NuY2vRqCaK5Sc5kssjk:-Nux2SDZ8H2bJ7Ct67jG:bdnerpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/705f7acefce167b43ee96a58f2d8c0266d6b95ad/ios/MullvadVPNUITests/Networking/Networking.swift#L181)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

How about `"Didn't receive any data`? See change
</blockquote></details>

Sounds good !

**Review by acb-mv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 219 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-NvAtqQC5tYbT1ZqRmFA:-NvBCV-RBhFplRKFp2ON:b8ygsf0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a17f6f7d62c9aa027feae975381d5570eb28559/ios/MullvadVPNUITests/Networking/Networking.swift#L219)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Since this is a hardcoded string that's 100% going to work as a URL it would (in my opinion) be ok to simply force unwrap in a test. Not necessary to change, just pointing out.
</blockquote></details>

I agree. IMO in tests crashing/throwing exceptions isn't bad, it's very different from how error handling should be done in the app. I should be using `XCTUnwrap()` more though!

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961#-:-NvGOIlmApoG8AGrXhdp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by pinkisemils — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by rablador — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by rablador — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5961)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Pull request merged**
