### PR TITLE
Translate location names

### PR DESCRIPTION
**Pull request by Rawa**
Adds support for translations for different locations

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> Reviewed 29 of 34 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: 33 of 34 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/resource/src/main/res/xml/relay_locations.xml` line 152 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O3fZPDlBGWy9iDrtz4I:-O3fZPDlBGWy9iDrtz4J:bvmpmnt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5eb078077047e3403762703e8ce5af8fa6cc9db7/android/lib/resource/src/main/res/xml/relay_locations.xml#L152)):*
> ```XML
>     <string name="Valencia">Valencia</string>
>     <string name="Vancouver">Vancouver</string>
>     <string name="Vienna">Vienna</string>
> ```

Not sure if this is an error in the source data or in the translation script, but Vienna and Wien appear both, which is a bit weird.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: 7 of 34 files reviewed, all discussions resolved (waiting on @Pururun)

___
*[`android/lib/resource/src/main/res/xml/relay_locations.xml` line 152 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O3fZPDlBGWy9iDrtz4I:-O3i89pZ6q7w0ZFObrDk:b342bm0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5eb078077047e3403762703e8ce5af8fa6cc9db7/android/lib/resource/src/main/res/xml/relay_locations.xml#L152)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Not sure if this is an error in the source data or in the translation script, but Vienna and Wien appear both, which is a bit weird.
</blockquote></details>

The relay-locations.pot includes both, I've created DES-1122 to address this.

**Review by Pururun — CHANGES_REQUESTED** [review]
We should also sort the relay items based on the translated name. Currently they are sorted based on the english name so for example "Österrike" / "Österreich" will be close to the tope of the list even though it should be at the bottom.

> Reviewed 29 of 29 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-:-O3qTCbk6berVYTTGkOL:bphbr5y)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/AndroidManifest.xml` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O3qS_FG5RYNzGnz7Y11:-O3qS_FG5RYNzGnz7Y12:b3n46om) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28f7e20a2541ea04b1a615aa2c8c980aec7c68ac/android/app/src/main/AndroidManifest.xml#L3)):*
> ```XML
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>         xmlns:tools="http://schemas.android.com/tools">
> ```

I think we should not have a lot of formatting in this file?

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O3qXbh6AKhExscY-zkM:-O3qXbh6AKhExscY-zkN:bczuihd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/71d57de1447e411560a57a40900d6306d5472ed3/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L53)):*
> ```Kotlin
>                 val translation = loadRelayTranslation(xml)
> 
>                 translation.entries.associate { (id, name) -> defaultTranslation[id]!! to name }
> ```

Is there a way to get around this? I get that we have it because the keys of the default locale does not always match the string we get from the daemon, but it would be nice if did not need this step, feels like it is open for errors and crashes.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-:-O3rEIEmAB8FbUzTCzQ2:bnfp4nl)* status: 34 of 35 files reviewed, all discussions resolved (waiting on @Rawa)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 34 files at r1, 1 of 4 files at r2, 6 of 29 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: all files reviewed, 7 unresolved discussions (waiting on @Rawa)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O49d0LB5anNpnJ6Z1C2):*
nit: change to:

> Add support for translated location names



_Code quote:_
```
Add support location translations
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/broadcastreceiver/LocaleChangedBroadcastReceiver.kt` line 1 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4ftoOh9K0Lpi-SACj9:-O4ftoOh9K0Lpi-SACjA:bmqvosj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/broadcastreceiver/LocaleChangedBroadcastReceiver.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.broadcastreceiver
> ```

nit: I suggest changing to just `receiver` since it's shorter and easier to read



_Code quote:_
```Kotlin
broadcastreceiver
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/RelayListRepository.kt` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fwSNX254ee2lLZLDg:-O4fwSNX254ee2lLZLDh:by00aac) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/RelayListRepository.kt#L43)):*
> ```Kotlin
>             .stateIn(CoroutineScope(dispatcher), SharingStarted.WhileSubscribed(), emptyList())
> 
>     private fun List<RelayItem.Location.Country>.translateRelay(
> ```

I suggest changing  to `translateRelays` or `translateAllContainingLocationsAndRelays` depending on how verbose we want to be



_Code quote:_
```Kotlin
translateRelay
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 18 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fxKfgErvrw7SxNxd3:-O4fxKfgErvrw7SxNxd4:b8b5fhs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L18)):*
> ```Kotlin
> fun List<String>.trimAll() = map { it.trim() }
> 
> fun <T> List<T>.sortedByName(comparator: (T) -> String) =
> ```

I believe this function name is a bit too specific for such a generic file (`StringExtensions.kt`). Maybe the function belongs somewhere else or can be renamed?



_Code quote:_
```Kotlin
sortedByName
```
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 32 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fvPIr0b-8kpWswFG1:-O4fvPIr0b-8kpWswFG2:b-4nzw00) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L32)):*
> ```Kotlin
>             .stateIn(externalScope, SharingStarted.Eagerly, emptyMap())
> 
>     private suspend fun loadTranslations(locale: Locale?): Translations =
> ```

Isn't it better the caller handle the nullable case?



_Code quote:_
```Kotlin
Locale?
```
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 34 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fvFhsE0R5FcYTelni:-O4fvFhsE0R5FcYTelnj:b-7ilvfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L34)):*
> ```Kotlin
>     private suspend fun loadTranslations(locale: Locale?): Translations =
>         withContext(dispatcher) {
>             Logger.d("Updating translations based $locale")
> ```

typo?



_Code quote:_
```Kotlin
Updating translations based $locale
```
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fviTPDskYQvC6YUuc:-O4fviTPDskYQvC6YUud:b-vvs081) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L43)):*
> ```Kotlin
>         }
> 
>     private fun loadRelayTranslation(xml: XmlResourceParser): Map<String, String> {
> ```

Seems like this can be made a bit more readable by letting this function be an extension function for `XmlResourceParser`?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: 35 of 36 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O49d0LB5anNpnJ6Z1C2):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: change to:

> Add support for translated location names
</blockquote></details>

Done

**Review by Pururun — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/broadcastreceiver/LocaleChangedBroadcastReceiver.kt` line 1 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4ftoOh9K0Lpi-SACj9:-O4iloZn2zNPjYJIFIkU:bngt57j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/broadcastreceiver/LocaleChangedBroadcastReceiver.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest changing to just `receiver` since it's shorter and easier to read
</blockquote></details>

That is also what we use for the bootreceiver in the autostart branch so that is a good change for that reason as well.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/RelayListRepository.kt` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fwSNX254ee2lLZLDg:-O4imHcuAcI3fJezVCFf:bj82fbj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/RelayListRepository.kt#L43)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing  to `translateRelays` or `translateAllContainingLocationsAndRelays` depending on how verbose we want to be
</blockquote></details>

Changed it to `translateRelays`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 18 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fxKfgErvrw7SxNxd3:-O4imPK8D4C7JkZVMP0P:bx8cpia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L18)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe this function name is a bit too specific for such a generic file (`StringExtensions.kt`). Maybe the function belongs somewhere else or can be renamed?
</blockquote></details>

We named it as such since that is the expected behaviour when sorting something by name.

Since it is only used for relay list I moved it to `RelayListExtensions` and made it more specific.
   
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 32 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fvPIr0b-8kpWswFG1:-O4ir2On8VaXZqjBB4_Z:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Isn't it better the caller handle the nullable case?
</blockquote></details>

Done
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 34 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fvFhsE0R5FcYTelni:-O4ir3EJ6PnA17q0nfYQ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L34)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Done
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4fviTPDskYQvC6YUuc:-O4irZ7c9caE0r8YJ_in:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/RelayLocationTranslationRepository.kt#L43)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Seems like this can be made a bit more readable by letting this function be an extension function for `XmlResourceParser`?
</blockquote></details>

Done

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/broadcastreceiver/LocaleChangedBroadcastReceiver.kt` line 1 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4ftoOh9K0Lpi-SACj9:-O4ixU5eBz_27l9EMuDS:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e47ce10900acb041abc857ac6eff33efcdba790/android/app/src/main/kotlin/net/mullvad/mullvadvpn/broadcastreceiver/LocaleChangedBroadcastReceiver.kt#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

That is also what we use for the bootreceiver in the autostart branch so that is a good change for that reason as well.
</blockquote></details>

:thumbsup:

**Review by albin-mullvad — APPROVED** [review]
I suggest asking for someone with better rust knowledge to review the `translation-converter`. The rest looks good! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-:-O4kGzCmBKLPVvk9ncRD:b-xqudy1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/translations-converter/src/main.rs` line 230 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4nyaTzDLuP9dsBlSHP:-O4nyaTzDLuP9dsBlSHQ:bqufkqj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d65cb4e466f68485a785df6cb1cd34b1ed5c402/android/translations-converter/src/main.rs#L230)):*
> ```XML
>         .expect("Failed to open root locale directory")
>         .filter_map(|dir_entry_result| dir_entry_result.ok().map(|dir_entry| dir_entry.path()))
>         .filter(|dir_entry_path| dir_entry_path.is_dir())
> ```

Nit This could be split up further by introducing yet another `map`

```Rust
        .filter_map(|dir_entry_result| dir_entry_result.ok())
        .map(|dir_entry| dir_entry.path())
        .filter(|dir_entry_path| dir_entry_path.is_dir())
```



_Code quote:_
```XML
        .filter_map(|dir_entry_result| dir_entry_result.ok().map(|dir_entry| dir_entry.path()))
        .filter(|dir_entry_path| dir_entry_path.is_dir())
```
___
*[`android/translations-converter/src/main.rs` line 278 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4nzbPj0TokA-R5xjlr:-O4nzbPk8el-WecN8o7F:b-j8gckm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d65cb4e466f68485a785df6cb1cd34b1ed5c402/android/translations-converter/src/main.rs#L278)):*
> ```XML
> /// `values-en-rUS`.
> fn android_xml_directory(locale: &str) -> String {
>     let mut directory = String::from("xml-");
> ```

Nit It seems to me like the comment doesn't actually line up with the implementation. I think the comment should say ".. gets correctly mapped to the directory name `xml-en-rUS`, right? :blush:



_Code quote:_
```XML
/// This just makes sure a locale such as `en-US' gets correctly mapped to the directory name
/// `values-en-rUS`.
fn android_xml_directory(locale: &str) -> String {
    let mut directory = String::from("xml-");
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: 36 of 37 files reviewed, all discussions resolved

___
*[`android/translations-converter/src/main.rs` line 230 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4nyaTzDLuP9dsBlSHP:-O4oFYDSBpmZtJLsk0Gj:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d65cb4e466f68485a785df6cb1cd34b1ed5c402/android/translations-converter/src/main.rs#L230)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit This could be split up further by introducing yet another `map`

```Rust
        .filter_map(|dir_entry_result| dir_entry_result.ok())
        .map(|dir_entry| dir_entry.path())
        .filter(|dir_entry_path| dir_entry_path.is_dir())
```
</blockquote></details>

Done
___
*[`android/translations-converter/src/main.rs` line 278 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-O4nzbPj0TokA-R5xjlr:-O4oFgAb5UmYemWlJcPY:b-hv5qno) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d65cb4e466f68485a785df6cb1cd34b1ed5c402/android/translations-converter/src/main.rs#L278)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit It seems to me like the comment doesn't actually line up with the implementation. I think the comment should say ".. gets correctly mapped to the directory name `xml-en-rUS`, right? :blush:
</blockquote></details>

Yes I think that it was `values-en-rUS` first and then it as changed to `xml-en-rUS` later but the comment was not updated. Good find!

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-:-O4oJ47d4oOGUonf688Z:bnfp4nl)* status: 36 of 37 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574)* status: 36 of 37 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6574#-:-O4oLRP43IJAm6diDKVS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
