### PR TITLE
Add feature indicators to connect screen

### PR DESCRIPTION
**Pull request by Rawa**
This PR will rework the Connect screen and add support for feature indicators showing which features are currently active.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: 0 of 52 files reviewed, all discussions resolved

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QD5qr7jdI_QVsPDqJ):*
I'll split the commits at a later stage

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 32 of 52 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 160 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QEbmE7uBS3S1is4KO:-O6QEbmE7uBS3S1is4KP:b-n7ltpw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d090bd05f278cfe0fef7bae417b2153c8549cc15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L160)):*
> ```Kotlin
>         contentPadding =
>             if (hasIcon) {
>                 PaddingValues(horizontal = 0.dp, vertical = Dimens.buttonVerticalPadding)
> ```

IIRC this was added for a reason, I guess this works fine now?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 239 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QFck_2py7R9o2gujb:-O6QFck_2py7R9o2gujc:bfkdsim) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/540c6a1c88837eef65475dcf18ef1a433ef9ed7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L239)):*
> ```Kotlin
>         val screenHeight = configuration.screenHeightDp.dp
>         val indicatorPercentOffset =
>             if (screenHeight < 700.dp) INDICATOR_PERCENT_OFFSET_UNDER_700_DP
> ```

Magic number?
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QGMLGESQT9-QL3kKy:-O6QGMLGESQT9-QL3kKz:b-yw9dkl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/540c6a1c88837eef65475dcf18ef1a433ef9ed7e/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L138)):*
> ```Kotlin
>         small = RoundedCornerShape(4.dp),
>         medium = RoundedCornerShape(4.dp),
>         large = RoundedCornerShape(12.dp),
> ```

Should check if we are using large somewhere else, it was set `0.dp` for some reason.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QGMLGESQT9-QL3kKy:-O6QKdYB7TH23zs1M5DX:brgep5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/540c6a1c88837eef65475dcf18ef1a433ef9ed7e/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L138)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should check if we are using large somewhere else, it was set `0.dp` for some reason.
</blockquote></details>

Seems like it is not being used anywhere. Retracting.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 160 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QEbmE7uBS3S1is4KO:-O6QKdaG3SeaGI5XYqgc:b5we5nd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d090bd05f278cfe0fef7bae417b2153c8549cc15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L160)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

IIRC this was added for a reason, I guess this works fine now?
</blockquote></details>

This is the default
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 239 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6QFck_2py7R9o2gujb:-O6QKtOB67pbGIUZf-ND:b-2mqpiq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/540c6a1c88837eef65475dcf18ef1a433ef9ed7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L239)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magic number?
</blockquote></details>

Yes! Fixing

**Review by Pururun — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
Found a crash after I increased font scaling:
```
java.lang.IllegalArgumentException: Key "true40" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
```

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-:-O6uRUDZ9htz0TujK7qs:b986yav)* status: 51 of 55 files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778)* status: 51 of 55 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6ukzF73wdQ94pYpKHe:-O6ukzF73wdQ94pYpKHf:b-b6iaox) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22fc7ea993ca59a0c883aec943b1578d041bf08c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt#L77)):*
> ```Kotlin
>                 },
>         )
>         Text(
> ```

This should be single line

**Review by Rawa — COMMENTED** [review]
Great find:
https://issuetracker.google.com/issues/367440149 & https://issuetracker.google.com/issues/355003185

Apparently a limitation with how FlowRow works today, it is experimental and this will be addressed in upcoming changes according to the comment in the second issue, however it is unclear when this will be done. I guess it probably won't be until compose 1.8.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-:-O6QLbGZ971egZ2HBXoC:bk240j6)* status: 49 of 55 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-O6ukzF73wdQ94pYpKHe:-O6zOuK16pYe55ESI3Wv:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22fc7ea993ca59a0c883aec943b1578d041bf08c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt#L77)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be single line
</blockquote></details>

Fixed

**Review by Rawa — COMMENTED** [review]
I've set `maxLines` to 2 for now, alignment with design is needed before merging of this PR.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-:-O6zOwSd6H4Udpq4C9lN:b-kvzlm8)* status: 49 of 55 files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6778#-:-O74C2gnAOIYBKeClM6-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Pull request merged**
