### PR TITLE
Disable signup button after start typing

### PR DESCRIPTION
**Pull request by sabercodic**
"create account" button state in login page will change based on user's typing status

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC4BovfACrey7W8dpEe:-NC4BovfACrey7W8dpEf:b-uptc4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L43)):*
> ```Kotlin
>     private lateinit var background: View
>     private lateinit var headerBar: HeaderBar
>     private lateinit var createAccountButton: net.mullvad.mullvadvpn.ui.widget.Button
> ```

Would be nice to skip this part if possible.



_Code quote:_
```Kotlin
net.mullvad.mullvadvpn.ui.widget.
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC4AxDFAI6DncU__K07:-NC4AxDFAI6DncU__K08:b-lasu9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L92)):*
> ```Kotlin
>         // add listener to input
>         accountLogin.onInputChanged.subscribe(this) {
>             createAccountButton.isEnabled = it.trim().isEmpty()
> ```

What is the reason for trimming? Shouldn't the button be disabled regardless?

Also, please consider creating a local variable to store this value to improve readability.



_Code quote:_
```Kotlin
it.trim().isEmpty()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC49rE_7es4tICyV7yP:-NC49rE_7es4tICyV7yQ:bfd1e65) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L118)):*
> ```Kotlin
>         jobTracker.cancelAllJobs()
>         requireMainActivity().backButtonHandler = null
>         accountLogin.onInputChanged.unsubscribe(this)
> ```

The lifecycle of this subscription doesn't seem to be properly handled. The `subscribe` and `unsubscribe` should be located in matching lifecycle methods, i.e. `onStart` and `onStop`.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC49EIA5mwDc1bL2M_g:-NC49EIBB58emZbStrtz:b-1gfb0i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt#L27)):*
> ```Kotlin
> 
>     // this observable added to inform parent view about inserted user id
>     val onInputChanged = EventNotifier("")
> ```

Perhaps consider using the existing `AccountInput` `onTextChanged` `EventNotifier` directly in the LoginFragment. That way we use one less intermediate `EventNotifier`.



_Code quote:_
```Kotlin
    val onInputChanged = EventNotifier("")
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934)* status: all files reviewed, 8 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC566-F27LqK2cdTvgc):*
I suggest changing to something like: `Disable account creation while entering account number`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC57OCd5mk5L25KfHZC:-NC57OCd5mk5L25KfHZD:b-nqjl18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ca411691e1f6865ffcb67235feef0255921baa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L92)):*
> ```Kotlin
>         loginViewModel.clearState()
>         triggerAutoLoginIfAccountTokenPresent()
>         input = accountLogin.findViewById(R.id.input)!!
> ```

I wonder if we need `!!` here. It sort of makes sense, but we don't use it in other simliar places (`lateinit` + `findViewById`) as far as I'm aware.



_Code quote:_
```Kotlin
!!
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 107 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC56pvz3u3Ytw7UpKS-:-NC56pw-B6v_aCE0dNyE:bi80cgu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ca411691e1f6865ffcb67235feef0255921baa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L107)):*
> ```Kotlin
>         }
>         input.onTextChanged.subscribe(this) { ـ ->
>             val isInputEmpty = input.input.text.toString().trim().isEmpty()
> ```

I wasn't aware the this `EventNotifier` isn't providing the text value. Perhaps that can be added to improve this?



_Code quote:_
```Kotlin
input.input.text.toString().trim().isEmpty()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC56zYl77C9fM6h-JW0:-NC56zYl77C9fM6h-JW1:b-3f9ano) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ca411691e1f6865ffcb67235feef0255921baa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L109)):*
> ```Kotlin
>             val isInputEmpty = input.input.text.toString().trim().isEmpty()
>             createAccountButton.isEnabled = isInputEmpty
>             createAccountButton.alpha = if (isInputEmpty) 1f else 0.5f
> ```

I suggest adding constants for these values. Also are they aligned with the design concepts?



_Code quote:_
```Kotlin
1f else 0.5f
```

**Comment by sabercodic** [comment]
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC566-F27LqK2cdTvgc):*
> Disable account creation while entering account number

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC4BovfACrey7W8dpEe:-NC50YBDCq385S-_1aBs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L43)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to skip this part if possible.
</blockquote></details>

Done.

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC4AxDFAI6DncU__K07:-NC50XTgCpjYX46eIiMw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What is the reason for trimming? Shouldn't the button be disabled regardless?

Also, please consider creating a local variable to store this value to improve readability.
</blockquote></details>

Done.

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC57OCd5mk5L25KfHZC:-NC5CgWl4hV76TjBW0f0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ca411691e1f6865ffcb67235feef0255921baa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I wonder if we need `!!` here. It sort of makes sense, but we don't use it in other simliar places (`lateinit` + `findViewById`) as far as I'm aware.
</blockquote></details>

Done.

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 107 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC56pvz3u3Ytw7UpKS-:-NC5Cjsr707AOARweSP8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ca411691e1f6865ffcb67235feef0255921baa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L107)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I wasn't aware the this `EventNotifier` isn't providing the text value. Perhaps that can be added to improve this?
</blockquote></details>

Done.

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC56zYl77C9fM6h-JW0:-NC5947v6jMEEAyrB7mU:bflduvi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05ca411691e1f6865ffcb67235feef0255921baa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L109)):*
> isEmpty

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC49rE_7es4tICyV7yP:-NC51DXGAqrq4ELBeris:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L118)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The lifecycle of this subscription doesn't seem to be properly handled. The `subscribe` and `unsubscribe` should be located in matching lifecycle methods, i.e. `onStart` and `onStop`.
</blockquote></details>

Done.

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NC49EIA5mwDc1bL2M_g:-NC51KlI5nl913QwOlXI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c34f0440e0a3a0751d29c1fe182d0597589193/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps consider using the existing `AccountInput` `onTextChanged` `EventNotifier` directly in the LoginFragment. That way we use one less intermediate `EventNotifier`.
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 107 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NCZHq3U3aCqAfhJQ6_L:-NCZHq3U3aCqAfhJQ6_M:bxghig5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/717d775274a2ba637e8cb7865ac383e2ff42cc07/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L107)):*
> ```Kotlin
>         }
>         input.onTextChanged.subscribe(this) {
>             val isInputEmpty = it.isEmpty()
> ```

As the subscribe block has been simplified a lot since previous feedback, I suggest to now skip defining this variable and instead using `it.isEmpty()` to set the button state.



_Code quote:_
```Kotlin
val isInputEmpty = it.isEmpty()
```

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt` line 107 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934#-NCZHq3U3aCqAfhJQ6_L:-NCZIxji6GinoXFRsu9B:b-yseguo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/717d775274a2ba637e8cb7865ac383e2ff42cc07/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L107)):*
> isEmpty
Done

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
