### PR TITLE
Device in name in header bar should be capitalized

### PR DESCRIPTION
**Pull request by mojganii**
As per above, the device name in the header should be capitalised.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)

### CODE REVIEW

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-NTNuDYc-GEsUpEi7lDu:-NTNuDYc-GEsUpEi7lDv:bxooaxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d6a55cb2b3dfbca9ef2a2ee32b11db0d56d6346/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L179)):*
> ```Swift
>                 comment: ""
>             )
>             deviceName.text = .init(format: formattedDeviceName, storedDeviceData.name.capitalized)
> ```

Suggestion : How about adding `StoreDeviceData.prettyDeviceName: String` and return name.capitalized from it. Then other parts of the app can simply tap in it.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-NTNuDYc-GEsUpEi7lDu:-NTTD-oCAPVm-W0Oti0I:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d6a55cb2b3dfbca9ef2a2ee32b11db0d56d6346/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L179)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Suggestion : How about adding `StoreDeviceData.prettyDeviceName: String` and return name.capitalized from it. Then other parts of the app can simply tap in it.
</blockquote></details>

Done.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 119 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-NTTRP064zVcqy_aQOru:-NTTRP064zVcqy_aQOrv:bqtx6r4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5755e46d36f55761e9c37d057ef825e9f0e4407e/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L119)):*
> ```Swift
>         completionHandler: @escaping () -> Void
>     ) {
>         showDeleteConfirmation(deviceName: device.name.capitalized) { [weak self] shouldDelete in
> ```

Isn't it already capitalized?
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 265 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-NTTRSaRDOsmn4_bNU6N:-NTTRSaRDOsmn4_bNU6O:bp8msna) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5755e46d36f55761e9c37d057ef825e9f0e4407e/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L265)):*
> ```Swift
> struct DeviceViewModel {
>     var id: String
>     let name: String
> ```

Maybe we should maintain the same level of mutability? Either all properties are `let` or `var`. I don't mind either but for consistency.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 119 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-NTTRP064zVcqy_aQOru:-NTTfHlk2NEw9qDs0Tmw:bmbisy7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5755e46d36f55761e9c37d057ef825e9f0e4407e/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L119)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Isn't it already capitalized?
</blockquote></details>

it's view model and we filled the model with the capitalized name.I need to remove calling capitalized variable
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 265 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-NTTRSaRDOsmn4_bNU6N:-NTTfkV5A3zrFS3YA5Va:b-i0028o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5755e46d36f55761e9c37d057ef825e9f0e4407e/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L265)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we should maintain the same level of mutability? Either all properties are `let` or `var`. I don't mind either but for consistency.
</blockquote></details>

there is no need to consider them as a variable.I fixed this

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571#-:-NTTlxdL3VENyhmuA9I6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
