### PR TITLE
Fix Custom DNS auto disabling regression

### PR DESCRIPTION
**Pull request by sabercodic**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: all files reviewed, 3 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpSnX68YneyeI33HIX):*
nit: typo



_Code quote:_
```
costum
```
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpSrABEn55QMgplcYR):*
"bugs" -> "regression"



_Code quote:_
```
bugs
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpT0sBAADiybrkhxTK:-NSpT0sBAADiybrkhxTL:b-lyhw41) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf6562d59fbf92c83c6624789cda42f9e4ec0b3c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L183)):*
> ```Kotlin
>             }
>         ) {
>             DisposableEffect(key1 = null) {
> ```

Does this need to be set? :thinking: 



_Code quote:_
```Kotlin
key1 = null
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpSrABEn55QMgplcYR):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

"bugs" -> "regression"
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpT0sBAADiybrkhxTK:-NSpc9ssAzqEeuCqPCu2:b-dmntro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf6562d59fbf92c83c6624789cda42f9e4ec0b3c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L183)):*
> regression
this is the error I got when remove the parameter:



_Code snippet:_
```Kotlin
Using 'DisposableEffect(DisposableEffectScope.() -> DisposableEffectResult): Unit' is an error. DisposableEffect must provide one or more 'key' parameters that define the identity of the DisposableEffect and determine when its previous effect should be disposed and a new effect started for the new key.
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpT0sBAADiybrkhxTK:-NSpv0VkBxxhMmuN2Pfa:b-u17zvc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf6562d59fbf92c83c6624789cda42f9e4ec0b3c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L183)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

In that case it sounds like we need a proper key. Or can you elaborate on why `null` is used?
</blockquote></details>

key1 set to CollapsingToolbarScafoldScope instance, so it will be valid during it's lifecycle

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpT0sBAADiybrkhxTK:-NSpvBud3dNw3LhWk2yf:btcqbg3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf6562d59fbf92c83c6624789cda42f9e4ec0b3c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L183)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

key1 set to CollapsingToolbarScafoldScope instance, so it will be valid during it's lifecycle
</blockquote></details>

I believe it would be better to use lifecycle events (e.g. stop or pause) than the dispose function, like they show in the following sample:
https://developer.android.com/jetpack/compose/side-effects#disposableeffect


Suggested implementation:
```
// Add arg
fun AdvancedSettingScreen(
    lifecycleOwner: LifecycleOwner = LocalLifecycleOwner.current,

// Handle event and rename `onExitScreen` -> `onStopEvent`
            DisposableEffect(lifecycleOwner) {
                val observer = LifecycleEventObserver { _, event ->
                    if (event == Lifecycle.Event.ON_STOP) {
                        onStopEvent()
                    }
                }
                lifecycleOwner.lifecycle.addObserver(observer)
                onDispose {
                    lifecycleOwner.lifecycle.removeObserver(observer)
                }
            }
```


Also, can the effect be moved to the top of the function just after the initial `val`s?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 310 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpyY-d4r2EM8gdZyq-:-NSpyY-d4r2EM8gdZyq0:b-99os9i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3700b2ac34f9f835a6b6152001ca30963a90478f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L310)):*
> ```Kotlin
>     fun onExitScreen() {
>         if (vmState.value.customDnsList.isEmpty()) {
>             onToggleDnsClick(false)
> ```

I suggest creating a new `fun` called something like `private fun updateCustomDnsState(isEnabled: Boolean)` that we can call from both the `onToggleDnsClick` and `onExitScreen`/`onStopEvent`. The reason is to improve readability.



_Code quote:_
```Kotlin
onToggleDnsClick(false)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 312 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpyQf653QXslBjQGKW:-NSpyQf7CzGO0BA1e5G3:b9ydzoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3700b2ac34f9f835a6b6152001ca30963a90478f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L312)):*
> ```Kotlin
>             onToggleDnsClick(false)
>         }
>     }
> ```

Can this be moved above the private `fun`s?



_Code quote:_
```Kotlin
    fun onExitScreen() {
        if (vmState.value.customDnsList.isEmpty()) {
            onToggleDnsClick(false)
        }
    }
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpT0sBAADiybrkhxTK:-NSq1E895LU_BasSbl-X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf6562d59fbf92c83c6624789cda42f9e4ec0b3c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L183)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it would be better to use lifecycle events (e.g. stop or pause) than the dispose function, like they show in the following sample:
https://developer.android.com/jetpack/compose/side-effects#disposableeffect


Suggested implementation:
```
// Add arg
fun AdvancedSettingScreen(
    lifecycleOwner: LifecycleOwner = LocalLifecycleOwner.current,

// Handle event and rename `onExitScreen` -> `onStopEvent`
            DisposableEffect(lifecycleOwner) {
                val observer = LifecycleEventObserver { _, event ->
                    if (event == Lifecycle.Event.ON_STOP) {
                        onStopEvent()
                    }
                }
                lifecycleOwner.lifecycle.addObserver(observer)
                onDispose {
                    lifecycleOwner.lifecycle.removeObserver(observer)
                }
            }
```


Also, can the effect be moved to the top of the function just after the initial `val`s?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 310 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpyY-d4r2EM8gdZyq-:-NSq03aE5gY1zU5_rtIG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3700b2ac34f9f835a6b6152001ca30963a90478f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L310)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest creating a new `fun` called something like `private fun updateCustomDnsState(isEnabled: Boolean)` that we can call from both the `onToggleDnsClick` and `onExitScreen`/`onStopEvent`. The reason is to improve readability.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 312 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548#-NSpyQf653QXslBjQGKW:-NSq-Cn27hObLe3mFC2N:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3700b2ac34f9f835a6b6152001ca30963a90478f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L312)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be moved above the private `fun`s?
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
