### PR TITLE
Remove all direct usages of mullvad colors

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
Nice work :pray: 

> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733#-:-NpOXgbY4EuONSn2Eo_g:bevurmx)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733#-NpOXCCp2_JDAvwjdqeH:-NpOXCCp2_JDAvwjdqeI:b-2gln2n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bdf391ab5301606b51df674694fe57a501966d08/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L166)):*
> ```Kotlin
>                         .height(Dimens.searchFieldHeight)
>                         .padding(horizontal = Dimens.searchFieldHorizontalPadding),
>                 backgroundColor = MaterialTheme.colorScheme.onBackground.copy(alpha = Alpha10),
> ```

Do we need alpha here? Or is this some color not defined in our designs? (Same for below for SearchTextField preview)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733#-NpOXCCp2_JDAvwjdqeH:-NpQ8-460tHaYCdynI0-:b-8n8paq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bdf391ab5301606b51df674694fe57a501966d08/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L166)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we need alpha here? Or is this some color not defined in our designs? (Same for below for SearchTextField preview)
</blockquote></details>

The color in Zeplin is White with 10% alpha, but I agree with should replace it with a solid color.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733#-NpOXCCp2_JDAvwjdqeH:-NpUiwlZ-aF9cLsvavFg:bfe68ev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bdf391ab5301606b51df674694fe57a501966d08/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L166)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

The color in Zeplin is White with 10% alpha, but I agree with should replace it with a solid color.
</blockquote></details>

Replaced it with a solid color `tertiaryContainer` and a text color `onTertiaryContainer` that is also solid.

**Review by Rawa — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733#-:-NpsSAx674VgUsRMDOop:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
