### PR TITLE
Email confirmation

### PR DESCRIPTION
**Pull request by eriklarko**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/46)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[app/components/Support.js, line 165 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/46#-L41IuwX--ZX7NSnl__e:-L41IuwX--ZX7NSnl__f:b-ld1iin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/442a0281ecc8bd75ccbaa01e83dd49adfd230db0/app/components/Support.js#L165)):*
> ```JavaScript
>     } else {
>       footer = [
>         <Button key={1} onPress={ this.onViewLog } style={{'flex':1}} testName='support__view_logs'>
> ```

Maybe we could move the action buttons rendering into a function too and then have ternary op in footer view instead:

```
<View style={styles.support__footer}>
{ this.state.sendState === 'CONFIRM_NO_EMAIL' ?  
    this._renderNoEmailWarning() : 
     this._renderActionButtons() }
</View>
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/46)*

**Comment by pronebird** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/Support.js, line 207 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/46#-L41JwbUBmlgZUbzsQ8P:-L41JwbUBmlgZUbzsQ8Q:b-6boj3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/442a0281ecc8bd75ccbaa01e83dd49adfd230db0/app/components/Support.js#L207)):*
> ```JavaScript
>   _renderNoEmailWarning() {
>     return <View>
>       <Text style={{
> ```

Probably worth moving `style` into `SupportStyles`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/46)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/46)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/46)*

**Comment by eriklarko** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/Support.js, line 165 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/46#-L41IuwX--ZX7NSnl__e:-L450QXsoSuaQx99N3uQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/442a0281ecc8bd75ccbaa01e83dd49adfd230db0/app/components/Support.js#L165)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Maybe we could move the action buttons rendering into a function too and then have ternary op in footer view instead:

```
<View style={styles.support__footer}>
{ this.state.sendState === 'CONFIRM_NO_EMAIL' ?  
    this._renderNoEmailWarning() : 
     this._renderActionButtons() }
</View>
```
</blockquote></details>

Done.

---

*[app/components/Support.js, line 207 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/46#-L41JwbUBmlgZUbzsQ8P:-L44zC4cA3r0QnBqLuE8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/442a0281ecc8bd75ccbaa01e83dd49adfd230db0/app/components/Support.js#L207)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Probably worth moving `style` into `SupportStyles`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/46)*

**Comment by pronebird** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/46)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/46#-:-L45TkTbsp73rsYsQWNX:bnfp4nl)*

**Pull request merged**
