### PR TITLE
Refactor daemon oneshot commands

### PR DESCRIPTION
**Pull request by hulthe**
Refactor code in the daemon that handles cli boolean flags that trigger oneshot commands (i.e. commands that do something then exit, instead of starting the daemon like normal).

The flags are
- `--initialize-early-boot-firewall` (linux)
- `--run-as-service` (windows)
- `--register-service` (windows)
- `--launch-daemon-status` (macos)

This fixes issue where daemon uniqueness check interfered with these commands, and also makes the control flow and logging behaviour in main.rs a bit more obvious.

TODO: Test that CLI flags and logging is working as intended on
- [x] Linux
- [x] Windows
- [x] MacOS

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
Nice improvements!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978#-:-NtNUaOb0YJZ_DKl6H13:b-kzhh6i)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`mullvad-daemon/src/cli.rs` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978#-NtNOJlrB3pLKl2pMc9w:-NtNOJlrB3pLKl2pMc9x:bxtjh03) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75806e95580459e3658a5de8b96b2b3a37fef7c7/mullvad-daemon/src/cli.rs#L41)):*
> ```XML
>     /// Run as a system service
>     #[cfg(target_os = "windows")]
>     #[arg(long, conflicts_with = "register_service")]
> ```

I wish there were a way to express mutually exclusive flags as enums, but I guess there is not. What you think of grouping all of them like this?

```
#[derive(Parser)]
struct Cli {
    // ...
    #[command(flatten)]
    pub command: CommandFlags,
}

#[derive(Args)]
#[group(multiple = false, required = false)]
pub struct CommandFlags {
    #[arg(long)]
    run_as_service: bool,
    #[arg(long)]
    register_service: bool,
    #[arg(long)]
    initialize_early_boot_firewall: bool,
    #[arg(long)]
    launch_daemon_status: bool,
}
```

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/cli.rs` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978#-NtNOJlrB3pLKl2pMc9w:-NtQCB4643BkXI15RYA3:b-prnkzw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75806e95580459e3658a5de8b96b2b3a37fef7c7/mullvad-daemon/src/cli.rs#L41)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I guess really all of the "subcommand flags" should be mutually exclusive. I wish there were a way to express mutually exclusive flags as enums, but I guess there is not.

What you think of grouping all of them like this?

```
#[derive(Parser)]
struct Cli {
    // ...
    #[command(flatten)]
    pub command: CommandFlags,
}

#[derive(Args)]
#[group(multiple = false, required = false)]
pub struct CommandFlags {
    #[arg(long)]
    run_as_service: bool,
    #[arg(long)]
    register_service: bool,
    #[arg(long)]
    initialize_early_boot_firewall: bool,
    #[arg(long)]
    launch_daemon_status: bool,
}
```
</blockquote></details>

Nice find, done!

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)* status: all files reviewed, 1 unresolved discussion

___
*[`mullvad-daemon/src/main.rs` line 72 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978#-NtQKlsY2n-rLBR-966b:-NtQKlsY2n-rLBR-966c:b-ioxdxi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ead403023d6846fb817c66a439cec95d81eb54c8/mullvad-daemon/src/main.rs#L72)):*
> ```XML
>         #[cfg(target_os = "windows")]
>         cli::Command::RunAsService => {
>             init_logger(config, None)?;
> ```

Hmm. Do we need to do the uniqueness check here as well?

**Review by dlon — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`mullvad-daemon/src/main.rs` line 72 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978#-NtQKlsY2n-rLBR-966b:-NtQfNkP9vMAhvxO5JPa:bb5e928) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ead403023d6846fb817c66a439cec95d81eb54c8/mullvad-daemon/src/main.rs#L72)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Hmm. Do we need to do the uniqueness check here as well?
</blockquote></details>

It doesn't seem like we did this previously, but you're right.

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/main.rs` line 72 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978#-NtQKlsY2n-rLBR-966b:-NtR-bOtDfK9e00Wqdlx:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ead403023d6846fb817c66a439cec95d81eb54c8/mullvad-daemon/src/main.rs#L72)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It doesn't seem like we did this previously, but you're right.
</blockquote></details>

Fixed

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
