### PR TITLE
Show loading spinner when clicking Manage account

### PR DESCRIPTION
**Pull request by kl**
Fixes: DROID-1473

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)

### CODE REVIEW

**Review by Pururun — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by kl** [comment]
Also fixes: https://linear.app/mullvad/issue/DROID-1473/loading-state-when-clicking-log-out-button

**Review by Pururun — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066#-:-OAHJZN76miKZY_dRFkA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by kl** [comment]
fixes: DROID-1473

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 182 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066#-OAMHufPB8z7zO1Ha16a:-OAMHufPB8z7zO1Ha16b:b-odj7jh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfb45407e48e88a62c568c7f928c37705429c6c5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L182)):*
> ```Kotlin
> }
> 
> data class LoadingState(
> ```

This class feels bit unnecessary. We could just add the loading state directly into `AccountUiState`, and then introduce two StateFlow
```
private val isLoggingOut = MutableStateFlow(false)
private val isLoadingAccountPage = MutableStateFlow(false)
```

Then the update process becomes much simpler as well.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066#-OAMITiy9jlHyvxglUPc:-OAMITiy9jlHyvxglUPd:b-dgsk8f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfb45407e48e88a62c568c7f928c37705429c6c5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt#L56)):*
> ```Kotlin
>     modifier: Modifier = Modifier,
>     isEnabled: Boolean = true,
>     showSpinner: Boolean = false,
> ```

`isLoading` would be more clear.

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066#-OAMITiy9jlHyvxglUPc:-OANWYr5B2yMZIFtdxdO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfb45407e48e88a62c568c7f928c37705429c6c5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt#L56)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`isLoading` would be more clear.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 182 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066#-OAMHufPB8z7zO1Ha16a:-OANaYpm94vi3uA8DxeA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfb45407e48e88a62c568c7f928c37705429c6c5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L182)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This class feels bit unnecessary. We could just add the loading state directly into `AccountUiState`, and then introduce two StateFlow
```
private val isLoggingOut = MutableStateFlow(false)
private val isLoadingAccountPage = MutableStateFlow(false)
```

Then the update process becomes much simpler as well.
</blockquote></details>

Done.

**Review by Rawa — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066#-:-OARhe-vCNcL1dHQXyU4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
