### PR TITLE
Add timeout to the tcp connection for the pq key negotiation ios 701

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR adds an exponential backoff timeout when negotiating post quantum keys.
The timeout plays 2 important part :
- Trigger a reset of the key exchange process if the in-tunnel TCP connection does not become ready in time
- Trigger a reset of the key exchange process if it takes too long to exchange keys.

This PR was co-authored by @pinkisemils  and @buggmagnet
@MarkusPettersson98's approval is required for the rust side changes
@acb-mv's approval is required for the swift side changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)

### CODE REVIEW

**Review by acb-mv — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-FoOX4APGFPa2KcG4L:-O-FoOX4APGFPa2KcG4M:b-nnp2c8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L17)):*
> ```Swift
> 
> // swiftlint:disable function_parameter_count
> public protocol PostQuantumKeyNegotiation {
> ```

Are you sure about the name? This doesn't look like a negotiation but rather as something that negotiates. Perhaps `PostQuantumKeyNegotiating` would be a better name.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-FoOX4APGFPa2KcG4L:-O-GJyeX6AYO7qF3lw7x:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L17)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Are you sure about the name? This doesn't look like a negotiation but rather as something that negotiates. Perhaps `PostQuantumKeyNegotiating` would be a better name.
</blockquote></details>

Done

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)* status: 13 of 16 files reviewed, 8 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-Bsnqk2YRMwQWEiuo7:-O-Bsnqk2YRMwQWEiuo8:bmy0i77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L100)):*
> ```XML
>     }
>     /// Creates a `RelayConfigService` using the in-tunnel TCP Connection provided by the Packet
>     /// Tunnel Provider # Safety
> ```

Nit A bit of a weird line formatting here :nerd_face: 



_Code quote:_
```XML
   /// Tunnel Provider # Safety
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 159 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BtOmQ8xYoeAcrgY7b:-O-BtOmQ8xYoeAcrgY7c:bxrf46n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L159)):*
> ```XML
>                                     log::error!("No suitable peer was found");
>                                     swift_post_quantum_key_ready(packet_tunnel_ptr, ptr::null(), ptr::null());
>                                 }
> ```

Nit The log-statement shouldn't be in the `unsafe` block. Consider moving the `unsafe` token to the line where it is actually needed

```rust
None => {
    log::error!("No suitable peer was found");
    unsafe { swift_post_quantum_key_ready(packet_tunnel_ptr, ptr::null(), ptr::null()) };
}
```



_Code quote:_
```XML
                                None => unsafe {
                                    log::error!("No suitable peer was found");
                                    swift_post_quantum_key_ready(packet_tunnel_ptr, ptr::null(), ptr::null());
                                }
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-Bth0TDQ0h9fbAY6nq:-O-Bth0TDQ0h9fbAY6nr:bb6uiqt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L166)):*
> ```XML
>                             log::error!("Key exchange failed {}", error);
>                             swift_post_quantum_key_ready(packet_tunnel_ptr, ptr::null(), ptr::null());
>                         }
> ```

Dito



_Code quote:_
```XML
                        Err(error) => unsafe {
                            log::error!("Key exchange failed {}", error);
                            swift_post_quantum_key_ready(packet_tunnel_ptr, ptr::null(), ptr::null());
                        }
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BucD1AHdSgP4F1mUH:-O-BucD1AHdSgP4F1mUI:b-njxove) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L69)):*
> ```XML
>     /// `tcp_connection` must be pointing to a valid instance of a `NWTCPConnection`, created by the
>     /// `PacketTunnelProvider`
>     pub unsafe fn new(connection: Arc<Mutex<ConnectionContext>>) -> (Self, IosTcpShutdownHandle) {
> ```

Nit The comment says `tcp_connection`, but the function parameter is named `connection` :blush:



_Code quote:_
```XML
    /// # Safety
    /// `tcp_connection` must be pointing to a valid instance of a `NWTCPConnection`, created by the
    /// `PacketTunnelProvider`
    pub unsafe fn new(connection: Arc<Mutex<ConnectionContext>>) -> (Self, IosTcpShutdownHandle) {
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BvHiO3_X5EN40kdrX:-O-BvHiO3_X5EN40kdrY:b9ybq0f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L107)):*
> ```XML
>             std::mem::drop(context);
>         }
>     }
> ```

Nit Seems like there is an unncecessary level of indentation here?

```rust
pub fn shutdown(self) {
    let Ok(mut context) = self.context.lock() else {
        return;
    };

    context.tcp_connection = None;
    if let Some(waker) = context.waker.take() {
        waker.wake();
    }
    std::mem::drop(context);
}
```



_Code quote:_
```XML
    pub fn shutdown(self) {
        {
            let Ok(mut context) = self.context.lock() else {
                return;
            };

            context.tcp_connection = None;
            if let Some(waker) = context.waker.take() {
                waker.wake();
            }
            std::mem::drop(context);
        }
    }
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BwDJwBTkIMckPgKek:-O-BwDJwBTkIMckPgKel:b7r5xui) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L139)):*
> ```XML
>                     unsafe {
>                         swift_nw_tcp_connection_send(
>                             // self.tcp_connection,
> ```

Comment



_Code quote:_
```XML
                            // self.tcp_connection,
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 197 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BwQ8T9iVCkL74WLDH:-O-BwQ8T9iVCkL74WLDI:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L197)):*
> ```XML
>                     unsafe {
>                         // TODO
>                         swift_nw_tcp_connection_read(tcp_ptr, raw_sender as _);
> ```

TODO



_Code quote:_
```XML
                        // TODO
                        swift_nw_tcp_connection_read(tcp_ptr, raw_sender as _);
```

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)* status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @acb-mv, @MarkusPettersson98, and @pinkisemils)

___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 159 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BtOmQ8xYoeAcrgY7b:-O-Knsqw2izByC4EwYHD:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L159)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit The log-statement shouldn't be in the `unsafe` block. Consider moving the `unsafe` token to the line where it is actually needed

```rust
None => {
    log::error!("No suitable peer was found");
    unsafe { swift_post_quantum_key_ready(packet_tunnel_ptr, ptr::null(), ptr::null()) };
}
```
</blockquote></details>

Done
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-Bth0TDQ0h9fbAY6nq:-O-KntQz1MAY2KkWSGBP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L166)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Dito
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BucD1AHdSgP4F1mUH:-O-KoE18CbF7MyWCuv-J:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L69)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit The comment says `tcp_connection`, but the function parameter is named `connection` :blush:
</blockquote></details>

Done
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BvHiO3_X5EN40kdrX:-O-KoXS-BGZEhFaHbWbV:bvlti9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L107)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Seems like there is an unncecessary level of indentation here?

```rust
pub fn shutdown(self) {
    let Ok(mut context) = self.context.lock() else {
        return;
    };

    context.tcp_connection = None;
    if let Some(waker) = context.waker.take() {
        waker.wake();
    }
    std::mem::drop(context);
}
```
</blockquote></details>

Indeed ! Fixed.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BwDJwBTkIMckPgKek:-O-KofAj7FMVd9i2keJP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L139)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 197 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-O-BwQ8T9iVCkL74WLDH:-O-KozTbC-mvD8N9vlom:b-o94tcp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d76fa4007168196854818357ce4c5cab560d7de9/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L197)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

I think it's just a leftover of a different idea @pinkisemils was thinking about. 
I've removed it.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343#-:-O-_9OpQAkxYolnREVeO:bnfp4nl)* status: 11 of 16 files reviewed, 2 unresolved discussions (waiting on @acb-mv and @buggmagnet)

**Review by acb-mv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
