### PR TITLE
Remove map related code in scripts handling both geo data and translations

### PR DESCRIPTION
**Pull request by raksooo**
This PR removes the parts that handle map data and translations of relay locations from the `extract-geo-data.py` and `integrate-into-app.py` scripts. It also renames those scripts. The remaining parts are for fetching the relay list and adding all locations to the translation template (`relay-locations.pot`).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/scripts/fetch-relay-locations.py` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-NxlaQHg11A7i73NNHmi:-NxlaQHg11A7i73NNHmj:bizfmvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L52)):*
> ```Python
>     country_code, city_code = location_key.split("-")
> 
>     if country_name is None:
> ```

Can this ever be `None`? Doesn't look like it. It can be an empty string, though.
___
*[`gui/scripts/fetch-relay-locations.py` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-Nxla_ck1oBVQMYdwFbd:-Nxla_ck1oBVQMYdwFbe:bizfmvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L56)):*
> ```Python
>       continue
> 
>     if city_name is None:
> ```

Can this ever be `None`? Doesn't look like it. It can be an empty string, though.
___
*[`gui/scripts/fetch-relay-locations.py` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-Nxlb7Gc5HqP9JW9fZiF:-Nxlb7Gc5HqP9JW9fZiG:b-kp2nil) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L65)):*
> ```Python
>     country = countries[country_code]
>     cities = country["cities"]
>     if location_key != "se-bet":
> ```

Is this still a thing? I can't recall seeing any "beta" relays.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`gui/scripts/fetch-relay-locations.py` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-NxlaQHg11A7i73NNHmi:-Nxx9ACw6ajQpr1w5HYT:b-g1ec9f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L52)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can this ever be `None`? Doesn't look like it. It can be an empty string, though.
</blockquote></details>

I'm not very experienced with Python, but from my understanding this would be `None` if `location` doesn't have a country, which would only happen if the the relay list doesn't look as expected, and IMO it makes sense to account for that.

This code isn't new, it's been copied from the old scripts that did much more than what this one is doing.
___
*[`gui/scripts/fetch-relay-locations.py` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-Nxlb7Gc5HqP9JW9fZiF:-Nxx9lNL7eX-y-4rgYqX:bhh4aix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L65)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this still a thing? I can't recall seeing any "beta" relays.
</blockquote></details>

I've never read this script thoroughly enough to see this :laughing: Removed.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/scripts/fetch-relay-locations.py` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-NxxOWdi8akVN1k5N2eT:-NxxOWdi8akVN1k5N2eU:b-pzs6ms) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L42)):*
> ```Python
> 
>   for location_key in locations:
>     location = locations.get(location_key)
> ```

This can be rewritten as

```python
for location_key, location in location.items():
```



_Code quote:_
```Python
  for location_key in locations:
    location = locations.get(location_key)
```
___
*[`gui/scripts/fetch-relay-locations.py` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-NxlaQHg11A7i73NNHmi:-NxxKJT4AXiv4OEGljBj:b-ynxsye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2135ecc8c2e9422e60c4d29b88f4971cb72608a5/gui/scripts/fetch-relay-locations.py#L52)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I'm not very experienced with Python, but from my understanding this would be `None` if `location` doesn't have a country, which would only happen if the the relay list doesn't look as expected, and IMO it makes sense to account for that.

This code isn't new, it's been copied from the old scripts that did much more than what this one is doing.
</blockquote></details>

My bad, I must have gotten `country_name` and `country_code` mixed up. It would be less misleading to assign the variables immediately before checking if they're `None`:

```python
country_name = location.get('country')
if not country_name:
    ...
```

```python
city_name = location.get('city')
if not city_name:
    ...
```
___
*[`gui/scripts/fetch-relay-locations.py` line 125 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241#-NxxQ8aT6ARmBIM9BeBQ:-NxxQ8aT6ARmBIM9BeBR:b-5m2kji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9eabe74d6c9feaf5e4072d49142dc6e120b775b2/gui/scripts/fetch-relay-locations.py#L125)):*
> ```Python
>   extract_relay_translations()
> 
> main()
> ```

Not too important, but typically you only call `main()` if this is the top-level module:

```python
if __name__ == '__main__':
    main()
```

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6241)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

**Pull request merged**
