### PR TITLE
Introduce MullvadTransport and move Shadowsocks there, share Transpor…

### PR DESCRIPTION
**Pull request by buggmagnet**
Introducing `MullvadTransport`

A framework that will take care of sending network requests either directly, or with the help of Shadowsocks.
This PR streamlines the implementation into a single class `TransportProvider` that is reused across the `MullvadVPN` target and the `PacketTunnel` target.

`libshadowsocks_proxy.a` is now residing in `MullvadTransport` rather than `MullvadREST` along with `URLSessionTransport` and `ShadowsocksProxy`

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737)

### CODE REVIEW

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737)* status: 0 of 29 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 846 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737#-NWI48EF7zeQGUnG0qzl:-NWI48EF7zeQGUnG0qzm:b-53smmv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c45ca68bbeb79f15eec7b8d85ab6a7f3ce1ad7e0/ios/MullvadVPN.xcodeproj/project.pbxproj#L846)):*
> ```
> 		586A951329013235007BAF2B /* AnyIPEndpoint.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AnyIPEndpoint.swift; sourceTree = "<group>"; };
> 		586E54FA27A2DF6D0029B88B /* SendTunnelProviderMessageOperation.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SendTunnelProviderMessageOperation.swift; sourceTree = "<group>"; };
> 		586F2BE129F6916F009E6924 /* shadowsocks.h */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.h; path = shadowsocks.h; sourceTree = "<group>"; };
> ```

This probably shouldn't have changed. I will revert this

**Review by pronebird — COMMENTED** [review]
> Reviewed 13 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737)* status: 13 of 29 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 7 of 12 files at r3, 6 of 13 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737)* status: 28 of 32 files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 4 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737#-:-NWM6xWP2PLr2bW8cEtg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed 12 of 30 files at r1, 7 of 12 files at r3, 10 of 13 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4737)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
