### PR TITLE
Improve DNS64 resolution

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Add missing copyright notices in `Curve25519.swift` & `AnyIPEndpoint+DNS64.swift`
1. Refactor DNS64 resolution code and align with [the recommended approach by Apple](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-DontLinkElementID_4).

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: 0 of 4 files reviewed, all discussions resolved

___
*[ios/PacketTunnel/AnyIPEndpoint+DNS64.swift, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGicFBc6bQ4fuNJEX2H:-MGicFBd6puoujkWCQr7:b-be8eqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc4d656e9559fa816cf1ad05cc6b5296a64ac165/ios/PacketTunnel/AnyIPEndpoint+DNS64.swift#L18)):*
> ```Swift
>     /// Reference: https://developer.apple.com/support/ipv6/
>     func withResolvedIP() -> Result<AnyIPEndpoint?, Error> {
>         var hints = addrinfo()
> ```

FYI Swift automatically zeroes all of the fields in the struct.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: 0 of 4 files reviewed, all discussions resolved

___
*[ios/PacketTunnel/AnyIPEndpoint+DNS64.swift, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGiconm3mvLJ3bAvdzl:-MGiconm3mvLJ3bAvdzm:b-iid9ke) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fefd87f82d5d0cae01a6e21d6ce1d309e1ac4973/ios/PacketTunnel/AnyIPEndpoint+DNS64.swift#L28)):*
> ```Swift
> 
>         let err = getaddrinfo("\(self.ip)", "\(self.port)", &hints, &resultPointer)
>         if err != 0 || resultPointer == nil {
> ```

FYI I read the code of `getaddrinfo` from various sources but was not able to figure out if it's possible for it to return 0 results without setting the error, so I made the return value of this method to `Result<AnyIPEndpoint?, Error>` (note optional `AnyIPEndpoint`). 

The code we had before would return the obscure error if `resultPointer` is set to `nil`.

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/PacketTunnel/WireguardDevice.swift, line 315 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGiojVQ-iLsGMx91PWb:-MGiojVRDp175p1HFfd4:bm80vbt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc4d656e9559fa816cf1ad05cc6b5296a64ac165/ios/PacketTunnel/WireguardDevice.swift#L315)):*
> ```Swift
>                 logger.error("DNS64: failed to resolve the peer: \(peer.endpoint.ip). No results.")
> 
>                 return .success(resolvedPeer)
> ```

Is it okay to return `success` here?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/PacketTunnel/WireguardDevice.swift, line 315 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGiojVQ-iLsGMx91PWb:-MGiznEP9-lLiGY-VML5:bxc1n9r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc4d656e9559fa816cf1ad05cc6b5296a64ac165/ios/PacketTunnel/WireguardDevice.swift#L315)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is it okay to return `success` here?
</blockquote></details>

Mhmmmm no we should definitely error.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/PacketTunnel/AnyIPEndpoint+DNS64.swift, line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGm4WmR88fYC-7q3d9y:-MGm4WmS7VKA_SkF9OPi:bna9fxg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8e167a5952cd533e6665e41f9dc91cba6d8fde/ios/PacketTunnel/AnyIPEndpoint+DNS64.swift#L39)):*
FYI Went through a bunch of docs, basically based on [Linux docs](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html) it states that `getaddrinfo` should return one or more results:

> Given node and service, which identify an Internet host and a service, getaddrinfo() returns one or more addrinfo structures

Otherwise it returns an error. I looked at error codes and it looks like `EAI_NODATA` should be returned when `getaddrinfo` cannot emit a result:

> EAI_NODATA
> The specified network host exists, but does not have any
> network addresses defined.

So I sacrifice some safety here and pray that `getaddrinfo` sticks to its own rules.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/PacketTunnel/AnyIPEndpoint+DNS64.swift, line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGm5tfE0MKXw6jDtlIT:-MGm5tfE0MKXw6jDtlIU:btfilf2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d8e167a5952cd533e6665e41f9dc91cba6d8fde/ios/PacketTunnel/AnyIPEndpoint+DNS64.swift#L46)):*
> ```Swift
>             endpoint = .ipv6(IPv6Endpoint(ip: ipv6Address, port: port))
>         } else {
>             fatalError()
> ```

FYI same here. I think that by the time the new protocol is out there, we should be able to update our code without introducing more branching in our code. Unless both IPv4 and IPv6 parsers are broken on our side...

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/PacketTunnel/WireguardDevice.swift, line 315 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-MGiojVQ-iLsGMx91PWb:-MGm79Ej0dDibiZAQw9U:b2qtjqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc4d656e9559fa816cf1ad05cc6b5296a64ac165/ios/PacketTunnel/WireguardDevice.swift#L315)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Mhmmmm no we should definitely error.
</blockquote></details>

Reverted my code & explained the reasoning behind making `AnyIPEndpoint` non-nullable.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089#-:-MGmbkCm0UKZrHtEMtlM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
