### PR TITLE
Fix split tunneling packet loss

### PR DESCRIPTION
**Pull request by dlon**
Fixes the following error:
```
Failed to forward to tun device: Message too long (os error 40)
```

There were a couple of issues:
* The MTU of the ST utun was potentially higher than that of the VPN tunnel. We now keep track of and sync the MTUs.
* Outbound packets weren't correctly filtered. `Capture::direction` seems to handle it correctly but doesn't work on macOS 13. Instead, we must discard packets with the wrong source IP.

Close DES-1115.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 345 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-O4iLXZM-Glqfvphs5EY:-O4iLXZNBZCVRSN0ISb9:bv8udbm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b658fb7040b9846b448b53b906242cfeaef5e987/talpid-core/src/split_tunnel/macos/tun.rs#L345)):*
> ```XML
>         if details.mtu == current_mtu {
>             return;
>         }
> ```

What sort of condition is this? And why would the `mtu_updater` completely return instead of continuing to listen for new mtu updates? :blush:



_Code quote:_
```XML
        if details.mtu == current_mtu {
            return;
        }
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 361 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-O4iN42j47NGLK6qF8xi:-O4iN42j47NGLK6qF8xj:b-wn6llv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b658fb7040b9846b448b53b906242cfeaef5e987/talpid-core/src/split_tunnel/macos/tun.rs#L361)):*
> ```XML
>             log::error!("Failed to set MTU of {st_iface_name} to {mtu}: {error}");
>             return;
>         }
> ```

The `return`-statement seems excessive here - I assume it's a left over from before you refactored this piece of code into a function :blush:



_Code quote:_
```XML
        Err(error) => {
            log::error!("Failed to set MTU of {st_iface_name} to {mtu}: {error}");
            return;
        }
```
___
*[`talpid-net/src/unix.rs` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-O4iNmTmA0mNscxsPK7N:-O4iNmTmA0mNscxsPK7O:b-d4js4t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b658fb7040b9846b448b53b906242cfeaef5e987/talpid-net/src/unix.rs#L0)):*
So much `unsafe` here without `SAFETY` sections :( Would you mind adding that? :blush:

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 345 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-O4iLXZM-Glqfvphs5EY:-O4ijIYH4oQ-1BTviJsJ:b-hakueo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b658fb7040b9846b448b53b906242cfeaef5e987/talpid-core/src/split_tunnel/macos/tun.rs#L345)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

What sort of condition is this? And why would the `mtu_updater` completely return instead of continuing to listen for new mtu updates? :blush:
</blockquote></details>

Done. Nice catch!
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 361 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-O4iN42j47NGLK6qF8xi:-O4ijJhfBB68S6bxdTp0:b-hakueo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b658fb7040b9846b448b53b906242cfeaef5e987/talpid-core/src/split_tunnel/macos/tun.rs#L361)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

The `return`-statement seems excessive here - I assume it's a left over from before you refactored this piece of code into a function :blush:
</blockquote></details>

Done. Nice catch!
___
*[`talpid-net/src/unix.rs` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-O4iNmTmA0mNscxsPK7N:-O4ijRyXBIPXkAzmb5Ae:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b658fb7040b9846b448b53b906242cfeaef5e987/talpid-net/src/unix.rs#L)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

So much `unsafe` here without `SAFETY` sections :( Would you mind adding that? :blush:
</blockquote></details>

Done.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640#-:-O4jELLZ2K2kGZ4tUxPq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
