### PR TITLE
Do not fallback to making direct API connections when testing access methods

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR addresses an issue in the logic for testing access methods whre if an access methods fails to resolve to a set of connection details (e.g. if the relay selector / mullvad encrypted dns cache is empty) the daemon would fall back to making a direct API connection. The current behaviour is straight up misleading.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/api.rs` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-OAMANtx3jW2ZYPd4dA5:-OAMANtx3jW2ZYPd4dA6:b-zc5mgr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a04a016ab137c7b2bb090238d9b4f7dd690a8378/mullvad-daemon/src/api.rs#L183)):*
nit:

> Tru to resolve...

Typo?

**Review by Rawa — APPROVED** [review]
LGTM, probably good if Rust dev takes a look as well :+1: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-:-OAMClE47UNvV6zpbYAt:bwoajaj)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`mullvad-daemon/src/api.rs` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-OAMANtx3jW2ZYPd4dA5:-OAMJdC11pp6H92pk2cz:b-807aou) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a04a016ab137c7b2bb090238d9b4f7dd690a8378/mullvad-daemon/src/api.rs#L183)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

nit:

> Tru to resolve...

Typo?
</blockquote></details>

Type!

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`mullvad-daemon/src/api.rs` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-OAMANtx3jW2ZYPd4dA5:-OAMJfMxCkpuzwGMInio:bv3uzfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a04a016ab137c7b2bb090238d9b4f7dd690a8378/mullvad-daemon/src/api.rs#L183)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Type!
</blockquote></details>

Typo* Lol

**Review by hulthe — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98 and @Rawa)

___
*[`mullvad-daemon/src/api.rs` line 604 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-OAMUscODeXGFht6hWmq:-OAMUscODeXGFht6hWmr:b-tiwqj3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a04a016ab137c7b2bb090238d9b4f7dd690a8378/mullvad-daemon/src/api.rs#L604)):*
> ```XML
>                 AccessMethod::BuiltIn(BuiltInAccessMethod::Bridge) => {
>                     let Some(bridge) = relay_selector.get_bridge_forced() else {
>                         log::warn!("Received unexpected proxy settings type. Defaulting to direct API connection");
> ```

Is "Defaulting to direct API connection" still accurate?

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by Rawa — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @hulthe and @Rawa)

___
*[`mullvad-daemon/src/api.rs` line 604 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-OAMUscODeXGFht6hWmq:-OARiSArC8HjfTovfB9d:bxq604) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a04a016ab137c7b2bb090238d9b4f7dd690a8378/mullvad-daemon/src/api.rs#L604)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Is "Defaulting to direct API connection" still accurate?
</blockquote></details>

Well spotted, this log message is outdated :blush:
Fixed!

**Review by hulthe — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091#-:-OAY7wpc9L-BGBRDmIig:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
