### PR TITLE
Add mockapi test for handling too many devices

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689#-NoGjhsZAodPFQhOH2lU:-NoGjhsZAodPFQhOH2lV:b65ce93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e4d47b3b84e3c5b39fa095dbc83fab641029c1f0/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt#L58)):*
> ```Kotlin
>             "$DEVICES_URL_PATH/$DUMMY_ID_3",
>             "$DEVICES_URL_PATH/$DUMMY_ID_4",
>             "$DEVICES_URL_PATH/$DUMMY_ID_5" -> {
> ```

Can this bit be made more dynamic so that the test case can control it? I believe the same can be said for `handleDeviceListRequest`.



_Code quote:_
```Kotlin
            "$DEVICES_URL_PATH/$DUMMY_ID_1",
            "$DEVICES_URL_PATH/$DUMMY_ID_2",
            "$DEVICES_URL_PATH/$DUMMY_ID_3",
            "$DEVICES_URL_PATH/$DUMMY_ID_4",
            "$DEVICES_URL_PATH/$DUMMY_ID_5" -> {
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689#-NoGjhsZAodPFQhOH2lU:-NoSBkb05Ne9p88XAcbc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e4d47b3b84e3c5b39fa095dbc83fab641029c1f0/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt#L58)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this bit be made more dynamic so that the test case can control it? I believe the same can be said for `handleDeviceListRequest`.
</blockquote></details>

Done.
___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689#-NoQYVj488IMOOZmRF-R:-NoSBgym9ZIllPlmm7Yp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1416ac6f1cbfce8fc1c301def7790a678287665d/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Might be a good idea to make sure the test case have to explicitly set this in order to make it transparent to the test case writer/reader. I'm aware that this was more or less hard-coded before, so not really a new issue. We ofc don't want too much boiler plate either. My suggestion is to define a default device list that can be easily set in the dispatcher. This pre-defined list can be set like below or using some extension function etc:

```
apiDispatcher.apply {
    devices = DEFAULT_DEVICES
}
```
</blockquote></details>

Done.
___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt` line 36 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689#-NoQWM0s6cRswmOH3UCO:-NoSBhyN1_5GdVD7ZCFk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1416ac6f1cbfce8fc1c301def7790a678287665d/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest clarifying the name a bit and to skip the default, since that should be up to the test case. This would result in something like this:

`val devicePendingToGetCreated: Device? = null`
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689#-:-NoWEHot3MJsec0piU7l:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
