### PR TITLE
Add a list of additional accepted verbs in git commit messages

### PR DESCRIPTION
**Pull request by faern**
Follow up to #5975. We realized we also miss `queue`. Instead of adding one to two words at a time, it's probably more efficient to look at our history and see what verbs we actually do use. Turns out we used 184 unique verbs that I classify as OK imperative verbs that were not already in the list.

The list was long. So I might have made a mistake or two while going through it. Please read the list and suggest words to remove or add :pray: 

I have also submitted a PR to start getting these upstreamed. If the upstreaming goes smooth we will *hopefully* not need to maintain this list ourselves. Having it upstream has the valuable benefit of easily checking more than one repo without needing to duplicate this wordlist. https://github.com/mristin/opinionated-commit-message/pull/131

These were taken from our own git history with:
```bash
git log --format=%s | \
    awk '{print tolower($1)}' | \
    tr -cd '\n[:alnum:]._-' | \
    sort -u > first-words
```

And then filtered against the verbs the action already accepts:
```bash
for word in $(cat first-words); do
    if ! grep -x "  '$word'," mostFrequentEnglishVerbs.ts > /dev/null; then
        echo "$word";
    fi;
done
```

And then manually inspect the result, since there is lots of invalid words

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: all files reviewed, 10 unresolved discussions (waiting on @dlon and @faern)

___
*[`ci/additional-verbs.txt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCgNYBKhra2f-S7eF:-NtRCgNYBKhra2f-S7eG:bja15l7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L35)):*
> ```help
> decouple
> decrease
> dedup
> ```

There are no other abbreviations than this and "init" below. Maybe we should go for full words only?
___
*[`ci/additional-verbs.txt` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCw84CVd-XfW7mdzl:-NtRCw84CVd-XfW7mdzm:bopy4yj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L72)):*
> ```help
> infer
> inherit
> init
> ```

There are no other abbreviations than this and "dedup" above. Maybe we should go for full words only?
___
*[`ci/additional-verbs.txt` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCyqZ52XJ9a9ZKdTi:-NtRCyqZ52XJ9a9ZKdTj:b-yyh8jb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L81)):*
> ```help
> loop
> lower
> memoize
> ```

"memoRize"
___
*[`ci/additional-verbs.txt` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtR8wTXANv_5ZoSRO0V:-NtRD77L8_7qFmGVSv0I:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L116)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it's just `rearrange`
</blockquote></details>

+1
___
*[`ci/additional-verbs.txt` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtR9CAsA6JugJAwA5E4:-NtRD9O682m-BBREsLRB:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L120)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it's just `regenerate`
</blockquote></details>

+1
___
*[`ci/additional-verbs.txt` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtR9AZI-XGuTJV-YdVc:-NtRDAOF618SFX5UPMdR:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L122)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it's just `reimplement`
</blockquote></details>

+1
___
*[`ci/additional-verbs.txt` line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRB5CtCy9vA60paW9h:-NtRDCEr8jRHBJGfJoIf:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L126)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it's just `reparent`
</blockquote></details>

+1
___
*[`ci/additional-verbs.txt` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRBEU8DZoCecOxjxUs:-NtRDD7sC6jY8py1_5kB:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L128)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it's just `rerender`
</blockquote></details>

+1
___
*[`ci/additional-verbs.txt` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRDwvI4UtD0Oroylmb:-NtRDwvI4UtD0Oroylmc:b-5q3arq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L175)):*
> ```help
> uncomment
> unescape
> un-ignore
> ```

"unignore"
___
*[`ci/additional-verbs.txt` line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRBvdI77aybPCIwRK8:-NtRDUrh-HBzJfUhZ3Et:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L184)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is a noun. The verb is "work around", right?
</blockquote></details>

+1

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon and @rablador)

___
*[`ci/additional-verbs.txt` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCw84CVd-XfW7mdzl:-NtRLnH006GWQ9NssgVI:b7flx91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L72)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

There are no other abbreviations than this and "dedup" above. Maybe we should go for full words only?
</blockquote></details>

I don't have a very strong opinion. Abbreviations are fine for me. Dedup and init feels very computer related abbreviations. And I don't think we must have a complete list of all abbreviations just because we approve a few. But I'm also fine with removing them.
___
*[`ci/additional-verbs.txt` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCyqZ52XJ9a9ZKdTi:-NtRLfXi9ChjSRVXjaJK:b-jtnftz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L81)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"memoRize"
</blockquote></details>

It's not a typo, but I guess it can be argued whether or not we think memoization in verb form is OK or not :P https://en.wikipedia.org/wiki/Memoization
___
*[`ci/additional-verbs.txt` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRDwvI4UtD0Oroylmb:-NtRLNtOBzE5n80206ZF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L175)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"unignore"
</blockquote></details>

Done.
___
*[`ci/additional-verbs.txt` line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRBvdI77aybPCIwRK8:-NtRLRPQ3XfCi5J_2KEw:bsjqe29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L184)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Oops, this is a mistake for sure.

**Review by rablador — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[`ci/additional-verbs.txt` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCw84CVd-XfW7mdzl:-NtRQSNF34VoUYbMxV6z:b1rqpi1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L72)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't have a very strong opinion. Abbreviations are fine for me. Dedup and init feels very computer related abbreviations. And I don't think we must have a complete list of all abbreviations just because we approve a few. But I'm also fine with removing them.
</blockquote></details>

Yeah, I'm fine with both. I should have marked it as a nit instead.
___
*[`ci/additional-verbs.txt` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCyqZ52XJ9a9ZKdTi:-NtRQIojBGyFCdW14ZC0:b-7dudxd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's not a typo, but I guess it can be argued whether or not we think memoization in verb form is OK or not :P https://en.wikipedia.org/wiki/Memoization
</blockquote></details>

Oh! Well, it's legal as such, so I guess it can go on the list.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon and @rablador)

___
*[`ci/additional-verbs.txt` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCw84CVd-XfW7mdzl:-NtRWSbx4g0CxAcpJXa-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L72)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Yeah, I'm fine with both. I should have marked it as a nit instead.
</blockquote></details>

Done.
___
*[`ci/additional-verbs.txt` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCyqZ52XJ9a9ZKdTi:-NtRWTgdCQcBRGoB-g_S:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L81)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Oh! Well, it's legal as such, so I guess it can go on the list.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon and @rablador)

___
*[`ci/additional-verbs.txt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-NtRCgNYBKhra2f-S7eF:-NtRWZh-9DM6BU_KEmfe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/032f605136f83ffc3739fd1bfbf50fceb7d24536/ci/additional-verbs.txt#L35)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

There are no other abbreviations than this and "init" below. Maybe we should go for full words only?
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

**Review by faern — COMMENTED** [review]
Thanks for reviewing! However, I will hold off on merging this. Since the maintainer of the action seems positive towards merging all of this into upstream. If they do, we can simply pivot this PR into upgrading the action to the version with all our words :) https://github.com/mristin/opinionated-commit-message/pull/131

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992#-:-NtRdII5BF0VMqCFY1uV:bv7z4gu)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5992)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by faern** [comment]
Superseded by #6034

**Pull request closed without merging**
