### PR TITLE
Fix the path to system temp directory on windows

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR adds the system temporary directory lookup for windows: 

```
%windir%\TEMP
```

I've assigned all of you to keep you in the loop.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/72)

### CODE REVIEW

**Comment by faern** [comment]
If we would have releases for Windows then I would argue that this change should go in the changelog. But since we don't it's not important. :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72#-:-L62Ngx4gMt0RhFJn0vt:b-vw4yh5)*

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72#-:-L62_KycFE6ubXFkjpt1:bnfp4nl)*

**Comment by mvd-ows** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[app/main.js, line 115 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/72#-L63SP5U4RcmDrZBjhw3:-L63SP5VCQu0pNGyQB5J:b2mwr34) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94cfde7fffae14d35d4032073758a7e9566a2d73/app/main.js#L115)):*
> ```JavaScript
>         const logFiles = files.filter(file => file.endsWith('.log'))
>           .map(f => path.join(appDelegate._logFileLocation, f));
>         const reportPath = path.join(systemTempDir, uuid.v4() + '.report');
> ```

This is unlikely to work. The frontend is executing with low/user privileges and won't have write access to the global temp directory.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/72)*

**Comment by anderklander** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72#-:-L6GSltos6TPogJmPfm1:bnfp4nl)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/main.js, line 115 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/72#-L63SP5U4RcmDrZBjhw3:-L6GxrZX8hix1ftLRspS:bsmut24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94cfde7fffae14d35d4032073758a7e9566a2d73/app/main.js#L115)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is unlikely to work. The frontend is executing with low/user privileges and won't have write access to the global temp directory.
</blockquote></details>

This is a very good point. I have not verified myself that C:\Windows\TEMP is writable by users or not but I trust you on this. We can actually store those in local temporary directory since we run problem-report from user and so does the electron app.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/72)*

**Comment by pronebird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/main.js, line 115 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72#-L63SP5U4RcmDrZBjhw3:-L6M6RMOmu1-MxYYlyo9:b8u382t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3844ebef9351db9b1d90ba8ae52169ae018116a5/app/main.js#L115)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This is a very good point. I have not verified myself that C:\Windows\TEMP is writable by users or not but I trust you on this. We can actually store those in local temporary directory since we run problem-report from user and so does the electron app.
</blockquote></details>

I've updated problem-report to use the local temp directory whatever it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72)*

**Comment by pronebird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/main.js, line 115 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72#-L63SP5U4RcmDrZBjhw3:-L6bUT2_T3K5F30gcKg8:b3juhet) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3844ebef9351db9b1d90ba8ae52169ae018116a5/app/main.js#L115)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I've updated problem-report to use the local temp directory whatever it is.
</blockquote></details>

@mvd-ows can you confirm that this is resolved so I can merge this PR? Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72)*

**Comment by mvd-ows** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/72)*

**Pull request merged**
