### PR TITLE
Remove useless unwrap in relays.rs

### PR DESCRIPTION
**Pull request by NilsIrl**
Removes an unused unwrap.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2046)

### CODE REVIEW

**Comment by pronebird** [comment]
I think the `unwrap()` is there on purpose to crash the process if the weight based algorithm has a mistake. It acts as assertion.

**Comment by NilsIrl** [comment]
That's what I thought, however, what kind of mistake can occur? It seems to me that nothing can occur that would cause find to return `None`. It's up to you.

**Comment by pronebird** [comment]
@NilsIrl I think that `find()` can technically return `None` if it doesn't match any element, which should never happen. So again I believe it's an assertion from the developer to make sure that anyone who attempts to modify that function will hit the panic, although that doesn't stop anyone from removing that `unwrap()` either. So I somewhat agree that this `unwrap()` is superficial and subjective.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2046)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by faern** [comment]
This branch does not compile. The expected return type is `Option<&Relay>` but this PR makes it into `&Relay`.

Yes I think we want this code as is. So the panic is triggered if a bug is introduced in the logic. It's quite easy to accidentally introduce an off by one error or something like that. We don't want that to silently cause `None` to be returned, we want that to shout loud and clear that there is a bug.

**Pull request closed without merging**
