### PR TITLE
Android idea config files added

### PR DESCRIPTION
**Pull request by axti**
Added auto-generated config files for idea IDE to be able use Android Studio.
Also, added **gitignore** for idea folder with basic rules. 
Added **gradle.properties** file and updated **build.gradle** script with link for kotlin src directory.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/build.gradle, line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376#-MQRl4NJ6ZMQRUexBtAn:-MQRl4NJ6ZMQRUexBtAo:bsruv4m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/966ce8a4f17834d3adcc446fbadc17830044ae0d/android/build.gradle#L64)):*
> ```Gradle
>             }
>             java {
>                 srcDirs += 'src/main/kotlin/'
> ```

Is this necessary? The Kotlin Gradle Plugin already adds this, right?

**Comment by axti** [comment]
___
*[android/build.gradle, line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376#-MQRl4NJ6ZMQRUexBtAn:-MQRvDU63M9h6UpGO7_E:baeitd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/966ce8a4f17834d3adcc446fbadc17830044ae0d/android/build.gradle#L64)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is this necessary? The Kotlin Gradle Plugin already adds this, right?
</blockquote></details>

Yes, it is needed for Android Studio to link source from specific folder, otherwise it doesn't show in the project tree and navigation inside doesn't work.

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376#-:-MQRvydN4itZutzhBKEA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
