### PR TITLE
Migrate preferences view to compose

### PR DESCRIPTION
**Pull request by sabercodic**
Move "Auto-connect" and "Local network sharing" to Advanced page
Removing preferences menu from settings page 
Add "auto-connect" and "Local network sharing" to the Advanced setting screen
Add informational dialog to Local network sharing

Fixes: DROID-57, DROID-105

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 129 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NUwlO5c1GcbIEkdSx3Y:-NV9ijT404zFk7QO5K58:bqog7yy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66cbbbe510927775a832fcad38d666097a2899a7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L129)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is just a preference, but I think it is better if the null check is moved outside of the function?
Also if we want to keep the null-check, I would say `content?.let { ... }` is preferable.
</blockquote></details>

Agree!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NV9iokb9Jpl0xmDQanw:-NV9iokc2KnlXmHBUfw_:bpqgja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/821704c4092e372c61ed014b24535ede30710665/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L61)):*
> ```Kotlin
>             SwitchCellTitle(
>                 title = title,
>                 modifier = Modifier.alpha(if (isEnabled) AlphaActive else AlphaInactive),
> ```

Make sure to avoid adding trailing commas here and throughout these commits



_Code quote:_
```Kotlin
,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NV9qzub0aQcxmLs6JQ8:-NV9qzub0aQcxmLs6JQ9:b-g3cvj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/821704c4092e372c61ed014b24535ede30710665/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L61)):*
> ```Kotlin
>     }
> 
>     fun setAutoConnect(value: Boolean) {
> ```

Change to: `isEnabled`



_Code quote:_
```Kotlin
value
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NV9r2xR7VOZx1iQZESF:-NV9r2xR7VOZx1iQZESG:b-g3cvj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/821704c4092e372c61ed014b24535ede30710665/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L65)):*
> ```Kotlin
>     }
> 
>     fun setLocalNetworkSharing(value: Boolean) {
> ```

Change to: `isEnabled`



_Code quote:_
```Kotlin
value: Boolean
```
___
*[`android/app/src/main/res/values/strings.xml` line 200 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NV9iRuX9QYoUYB8P9W5:-NV9iRuX9QYoUYB8P9W6:b-4pudem) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/821704c4092e372c61ed014b24535ede30710665/android/app/src/main/res/values/strings.xml#L200)):*
> ```XML
>     <string name="local_network_sharing_ip_ranges">
>         <![CDATA[<ul><li>10.0.0.0/8</li><li>172.16.0.0/12</li><li>192.168.0.0/16</li><li>169.254.0.0/16</li><li>0xfe80::/10</li><li>0xfc00::/7</li></ul>]]>
>     </string>
> ```

This is related to adding the new info dialog (DROID-105), right? Please make sure to also link that issue if that's the case.



_Code quote:_
```XML
    <string name="local_network_sharing_info">This feature allows access to other devices on the local network, such as for sharing, printing, streaming, etc.</string>
    <string name="local_network_sharing_additional_info">It does this by allowing network communication outside the tunnel to local multicast and broadcast ranges as well as to and from these private IP ranges:</string>
    <string name="local_network_sharing_ip_ranges">
        <![CDATA[<ul><li>10.0.0.0/8</li><li>172.16.0.0/12</li><li>192.168.0.0/16</li><li>169.254.0.0/16</li><li>0xfe80::/10</li><li>0xfc00::/7</li></ul>]]>
    </string>
```

**Review by Pururun — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: all files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 64 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVE-GhdDcITFsnnjmTH:-NVE-GhdDcITFsnnjmTI:b-sl1kwr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/23371d72227aaada6be0a26bcae23666b9dcc592/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L64)):*
> ```Kotlin
>             )
>         },
>         subtitle = if (subtitle != null) getCellSubtitle(content = subtitle) else null,
> ```

Could be changed to `subtitle?.let { getCellSubtitle(content = subtitle) }`

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 64 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVE-GhdDcITFsnnjmTH:-NVEMX6h6xSvIXQVQmxR:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/23371d72227aaada6be0a26bcae23666b9dcc592/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L64)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Could be changed to `subtitle?.let { getCellSubtitle(content = subtitle) }`
</blockquote></details>

:thumbsup:

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
You can cherry-pick this commit to skip `UnusedResources` warnings for `strings.xml`

https://github.com/mullvad/mullvadvpn-app/commit/4098c88940c67ddbd148267985e36befe80db5d5

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-:-NVF4bRH6x9xkrPEBLzg:bcp2xfp)* status: 12 of 14 files reviewed, 6 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 55 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVF4-2k6dxh_MMzyjWv:-NVF4-2k6dxh_MMzyjWw:bb1z99a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L55)):*
> ```Kotlin
>     onInfoClicked: (() -> Unit)? = null
> ) {
>     Modifier.also {
> ```

I'm not sure this is a good idea. Do we even need this modifier since we don't seem to tweak it?



_Code quote:_
```Kotlin
Modifier.also {
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 132 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVEa4b75WMk1_PybLMW:-NVEa4b75WMk1_PybLMX:b-4frz9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L132)):*
> ```Kotlin
>     val textSize = dimensionResource(id = R.dimen.text_small).value.sp
>     return { Text(text = content, fontSize = textSize, color = MullvadWhite60) }
> }
> ```

I suggest skipping this function and including the logic in the calling function instead.



_Code quote:_
```Kotlin
@Composable
fun getCellSubtitle(content: String): @Composable (() -> Unit) {
    val textSize = dimensionResource(id = R.dimen.text_small).value.sp
    return { Text(text = content, fontSize = textSize, color = MullvadWhite60) }










}
```
___
*[`android/app/src/main/res/values/strings.xml` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVEaN55BIjrGUmZFDk3:-NVEaN55BIjrGUmZFDk4:b-yhoahd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/res/values/strings.xml#L197)):*
> ```XML
>     <string name="udp_over_tcp_port_info">Which TCP port the UDP-over-TCP obfuscation protocol should connect to on the VPN server.</string>
>     <string name="local_network_sharing_info">This feature allows access to other devices on the local network, such as for sharing, printing, streaming, etc.</string>
>     <string name="local_network_sharing_additional_info">It does this by allowing network communication outside the tunnel to local multicast and broadcast ranges as well as to and from these private IP ranges:</string>
> ```

Since we don't want to ignore the lint warning for `Unused



_Code quote:_
```XML
    <string name="local_network_sharing_info">This feature allows access to other devices on the local network, such as for sharing, printing, streaming, etc.</string>
    <string name="local_network_sharing_additional_info">It does this by allowing network communication outside the tunnel to local multicast and broadcast ranges as well as to and from these private IP ranges:</string>
```
___
*[`android/app/src/main/res/values/strings.xml` line 200 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVE_fVl51Wo4hlo-BIr:-NVE_fVl51Wo4hlo-BIs:b-gqga4r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/res/values/strings.xml#L200)):*
> ```XML
>     <string name="local_network_sharing_ip_ranges">
>         <![CDATA[<ul><li>10.0.0.0/8</li><li>172.16.0.0/12</li><li>192.168.0.0/16</li><li>169.254.0.0/16</li><li>0xfe80::/10</li><li>0xfc00::/7</li></ul>]]>
>     </string>
> ```

This should be added to `strings_non_translatable.xml` rather than `strings.xml`



_Code quote:_
```XML
    <string name="local_network_sharing_ip_ranges">
        <![CDATA[<ul><li>10.0.0.0/8</li><li>172.16.0.0/12</li><li>192.168.0.0/16</li><li>169.254.0.0/16</li><li>0xfe80::/10</li><li>0xfc00::/7</li></ul>]]>
    </string>
```
___
*[`gui/locales/messages.pot` line 1615 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVE_qviD0aKsyGLLFuz:-NVE_qviD0aKsyGLLFv-:bqddvce) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/gui/locales/messages.pot#L1615)):*
> ```pot
> 
> msgid "<ul><li>10.0.0.0/8</li><li>172.16.0.0/12</li><li>192.168.0.0/16</li><li>169.254.0.0/16</li><li>0xfe80::/10</li><li>0xfc00::/7</li></ul>"
> msgstr ""
> ```

Shouldn't be here. See my other comment regarding this string.



_Code quote:_
```pot
msgid "<ul><li>10.0.0.0/8</li><li>172.16.0.0/12</li><li>192.168.0.0/16</li><li>169.254.0.0/16</li><li>0xfe80::/10</li><li>0xfc00::/7</li></ul>"
msgstr ""
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 55 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVF4-2k6dxh_MMzyjWv:-NVF8DVOE_J51CD3A63x:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L55)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm not sure this is a good idea. Do we even need this modifier since we don't seem to tweak it?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 132 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVEa4b75WMk1_PybLMW:-NVF8sY87yHlqHZY2XPe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L132)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest skipping this function and including the logic in the calling function instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/res/values/strings.xml` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVEaN55BIjrGUmZFDk3:-NVFGMrl-PjNR_r0cdrN:b-ngsc6a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/res/values/strings.xml#L197)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Since we don't want to ignore the lint warning for `Unused
</blockquote></details>

can you please explain more
___
*[`android/app/src/main/res/values/strings.xml` line 200 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVE_fVl51Wo4hlo-BIr:-NVFG1ieEdi0edPaz6xU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/res/values/strings.xml#L200)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should be added to `strings_non_translatable.xml` rather than `strings.xml`
</blockquote></details>

Done.
___
*[`gui/locales/messages.pot` line 1615 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVE_qviD0aKsyGLLFuz:-NVFG2IU9s4mUD4r2lmb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/gui/locales/messages.pot#L1615)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Shouldn't be here. See my other comment regarding this string.
</blockquote></details>

Done.

**Review by sabercodic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-:-NVFKwfE5BMTxHUASrPd:bnfp4nl)* status: 11 of 16 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`-- commits` line 12 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVFLKnQAfGKnDMsoFzj):*
Would be great if you can move this before the first commit so it's possible to run lint on the other commits individually.



_Code quote:_
```
Ignore unused resource warning for strings
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 65 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVFKonU2Ig2wC6Vycct:-NVFKonU2Ig2wC6Vyccu:b-7ilvfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2728ccbada0472a54fc39a9e4c7662d5bd0bf997/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L65)):*
> ```Kotlin
>         },
>         subtitle =
>             subtitle?.let { { Text(text = it, fontSize = textSize, color = MullvadWhite60) } },
> ```

typo?



_Code quote:_
```Kotlin
{ {
```
___
*[`android/app/src/main/res/values/strings.xml` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVEaN55BIjrGUmZFDk3:-NVFL4DCDOJmsuiHnCkh:byrjkto) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c8713ee0d6e84f1c241503975b7269d758aed80/android/app/src/main/res/values/strings.xml#L197)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

can you please explain more
</blockquote></details>

Already retracted this (mistake) a while ago since I added another comment regarding linting instead.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 65 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVFKonU2Ig2wC6Vycct:-NVFQ4lJ-35selLgD44N:b-y31n5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2728ccbada0472a54fc39a9e4c7662d5bd0bf997/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Had another look and it's clearly not a typo, but I suggest adding `@Composable` to the inner function to improve readability. They seem to do it that way in `AlertDialog` for example:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/AlertDialog.kt;l=62?q=alertDialog%20compose

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: 15 of 17 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`-- commits` line 12 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668#-NVFLKnQAfGKnDMsoFzj):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be great if you can move this before the first commit so it's possible to run lint on the other commits individually.
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4668)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
