### PR TITLE
Add video recording of e2e tests

### PR DESCRIPTION
**Pull request by niklasberglund**
Added video recording for all end to end tests. The videos are stored in `/sdcard/Download/test-attachments/video` on the test device. To try out the changes run any test(s) and see produced videos in this directory.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8H2RANBYauekOqxNHQ:b-qrftrx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
> ```Kotlin
> 
>         job =
>             GlobalScope.launch {
> ```

Is there a way to not use GlobalScope? Then we maybe could do a cancel and run some code on completion?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8I-H2KDEUQze03IeUO:b7w7a9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is there a way to not use GlobalScope? Then we maybe could do a cancel and run some code on completion?
</blockquote></details>

Not sure I'm following. Cancel the thread instead of the process?(`pkill -2 screenrecord`)

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8LgTIs0q8SGc9N4_rv:b-421ert) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Not sure I'm following. Cancel the thread instead of the process?(`pkill -2 screenrecord`)
</blockquote></details>

Yeah exactly you can add a `OnCompletionListener` to jobs.

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8M5RdP2wiqZWbjw_sf:b-b3pp7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yeah exactly you can add a `OnCompletionListener` to jobs.
</blockquote></details>

Something like this:
```
private fun startScreenRecord(fileName: String) {
        if (File(OUTPUT_DIRECTORY).exists().not()) {
            File(OUTPUT_DIRECTORY).mkdirs()
        }

        job =
            coroutineScope.launch {
                UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
                    .executeShellCommand("screenrecord $OUTPUT_DIRECTORY/$fileName")
            }
        job.invokeOnCompletion {
            UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
                .executeShellCommand("pkill -2 screenrecord")
        }
    }
```

and

```
private fun stopScreenRecord() {
        try {
            runBlocking { job.cancelAndJoin() }
        } catch (e: Exception) {
            fail("Failed to stop screen recording")
        }
    }
```

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8_uMK--WUkDGSwsYHE:b-2dujsy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Something like this:
```
private fun startScreenRecord(fileName: String) {
        if (File(OUTPUT_DIRECTORY).exists().not()) {
            File(OUTPUT_DIRECTORY).mkdirs()
        }

        job =
            coroutineScope.launch {
                UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
                    .executeShellCommand("screenrecord $OUTPUT_DIRECTORY/$fileName")
            }
        job.invokeOnCompletion {
            UiDevice.getInstance(InstrumentationRegistry.getInstrumentation())
                .executeShellCommand("pkill -2 screenrecord")
        }
    }
```

and

```
private fun stopScreenRecord() {
        try {
            runBlocking { job.cancelAndJoin() }
        } catch (e: Exception) {
            fail("Failed to stop screen recording")
        }
    }
```
</blockquote></details>

Nice approach. I did try it but ran into that `runBlocking { job.cancelAndJoin() }` never returns because the job cannot be cancelled. Maybe `cancel()` plays too nice and cannot cancel a job with an external process?

I think the `invokeOnCompletion` callback is invoked *after* the job has been cancelled, but since it cannot be cancelled it is never invoked.

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8aCd0n7EstMtbvuTw3:b-b1kl2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Nice approach. I did try it but ran into that `runBlocking { job.cancelAndJoin() }` never returns because the job cannot be cancelled. Maybe `cancel()` plays too nice and cannot cancel a job with an external process?

I think the `invokeOnCompletion` callback is invoked *after* the job has been cancelled, but since it cannot be cancelled it is never invoked.
</blockquote></details>

Fair enough, not super important.

Should replace global scope though with a more local scope.

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-O8H2RANBYauekOqxNHP:-O8aIHPb8zpmHSieZgww:b-y46nq7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/751b2ca6d713bb4ffbec256081df1562246d39f0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L38)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Fair enough, not super important.

Should replace global scope though with a more local scope.
</blockquote></details>

Replaced `GlobalScope` with a `CoroutineScope`

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-:-O8aN3AG9l8XdoQwiCZR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-:-O8pdo6JC2vj9PIx9UFM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-:-O8pe40J3PmBlNxujedb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-:-O9F6Bnl5nYrEGoOC5_s:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912#-:-O9F8OEK0iIvvR50L3KJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
