### PR TITLE
Add preliminary settings page for relay IP overrides

### PR DESCRIPTION
**Pull request by rablador**
Currently, there is no bespoke iOS design for this, but that will not stop us. We should follow the desktop UI mockups for now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688)

### CODE REVIEW

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGTd7q3VyLJOcA7mqi:-NoGTd7q3VyLJOcA7mqj:b-opzmm3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L13)):*
> ```Swift
> import UIKit
> 
> class IPOverrideCoordinator: Coordinator, Presenting, SettingsChildCoordinator {
> ```

we can eliminate  conforming `Presenting` for now but if you think we need to present modal top of that in the future, let's keep it that
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGVBTeAMwetJRGWkWh:-NoGVBTeAMwetJRGWkWi:b-gxt5e9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L15)):*
> ```Swift
>         let view = UIStackView()
>         view.axis = .vertical
>         view.spacing = 20
> ```

try to use the values in `UIMetrics` or make the custom layout for this
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGZMej-cOGo-zNwnTE:-NoGZMej-cOGo-zNwnTF:b-j9fdda) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L62)):*
> ```Swift
>         infoButton.tintColor = .white
>         infoButton.setImage(UIImage(resource: .iconInfo), for: .normal)
>         infoButton.heightAnchor.constraint(equalToConstant: 24).isActive = true
> ```

use the padding in `UIMetrics`
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGZkpZAaq5161XrYiA:-NoGZkpZAaq5161XrYiB:b-m4fyk5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L66)):*
> ```Swift
> 
>         let headerView = UIStackView(arrangedSubviews: [label, infoButton, UIView()])
>         headerView.spacing = 8
> ```

the same goes for here

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGTd7q3VyLJOcA7mqi:-NoX58PJ01FDK-Lcm-u3:b-xs9kvj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can eliminate  conforming `Presenting` for now but if you think we need to present modal top of that in the future, let's keep it that
</blockquote></details>

We will need it in the next steps when we present document picker and text input view controller.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGVBTeAMwetJRGWkWh:-NoX5OGS2TTVm4QWuTvj:b-v4k189) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L15)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

try to use the values in `UIMetrics` or make the custom layout for this
</blockquote></details>

This is a very specific margin for this view only. Do we need to "pollute" the UIMetrics with non-generic margins? This answer goes for all the similar comments below.

**Review by mojganii — CHANGES_REQUESTED** [review]
Good job!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-:-NoGaZs-E0bUaBey8AAB:b-ov5l88)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-NoGVBTeAMwetJRGWkWh:-NokRBO4CwKgIaYUGO4V:b-50dgz7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf3e4573a2affd0cf7e17e4a337d4120dbeebe99/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is a very specific margin for this view only. Do we need to "pollute" the UIMetrics with non-generic margins? This answer goes for all the similar comments below.
</blockquote></details>

do we agree to keep specific spacings and layout constants in that view? if we are going to put shared values in `UIMetrics` then it's true. but I'm not sure if we agreed or not

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688#-:-Noquwl-5q4MnTxe7yhX:bnfp4nl)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Pull request merged**
