### PR TITLE
Version status RPCs

### PR DESCRIPTION
**Pull request by pinkisemils**
I've added a couple of RPCs to get info from the master API about app versions.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/105)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 4 of 11 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 26 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IEbipyGTiz2MHuDxm:-L8IEbipyGTiz2MHuDxn:b-8ejyz5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/CHANGELOG.md#L26)):*
> ```Markdown
> - Include the last two OpenVPN logs in problem reports instead of only the last.
> - Prevent two instances of the daemon to run at the same time.
> - Add RPCs to daemon to retrieve currently supported versions.
> ```

I'm not sure about the expression `RPCs`. How about "Fetches latest app version and checks current version support with Mullvad API"?

---

*[mullvad-cli/src/cmds/version.rs, line 24 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IGDRQivYT6e7lzue_:-L8IGDRQivYT6e7lzuea:b-uknwq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-cli/src/cmds/version.rs#L24)):*
> ```Rust
>         let version_info: version::AppVersionInfo = rpc::call("get_version_info", &[] as &[u8; 0])?;
>         println!("Supported: {}", version_info.is_supported);
>         println!("Supported versions:");
> ```

The latest versions are not really the same as our supported versions. The latest will be our latest stable and our latest unstable. But we can still support many older releases. For example, when `2018.2` is the newest stable and `2018.3-beta1` is the latest unstable we will likely still support `2018.1`.

So a better wording might be `Latest versions:`?

---

*[mullvad-daemon/src/main.rs, line 253 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IGlkOW4Ykc4C_Lne7:-L8IGlkOW4Ykc4C_Lne8:b-6t5sgq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/main.rs#L253)):*
> ```Rust
>             settings: settings::Settings::load().chain_err(|| "Unable to read settings")?,
>             version_proxy: AppVersionProxy::new(rpc_handle.clone()),
>             accounts_proxy: AccountsProxy::new(rpc_handle),
> ```

Can we keep the struct fields in the same order in the struct declaration and this place where we instantiate it? Would make it easier to find fields.

(This is one of the things I wish Rust enforced, requiring fields in the same order everywhere :)

---

*[mullvad-daemon/src/main.rs, line 499 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IHQqrtuS7oEPk9-W_:-L8IHQqrtuS7oEPk9-Wa:bomzljr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/main.rs#L499)):*
> ```Rust
>                     .is_app_version_supported(&current_version),
>             )
>             .map(move |(latest_versions, is_supported)| AppVersionInfo {
> ```

Nice usage of futures here :) :+1:

---

*[mullvad-daemon/src/version.rs, line 8 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IHia_MT4dox1ZWcnq:-L8IHia_MT4dox1ZWcnr:b-70fcve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/version.rs#L8)):*
> ```Rust
> /// Current description returns the current build date
> pub fn current_build_date() -> &'static str {
>     include_str!(concat!(env!("OUT_DIR"), "/git-commit-date.txt"))
> ```

It's actually the date of the commit, not the build. Maybe we should stick to calling it the commit date to be consistent? Also might be confusing to call it the build date since it might be built on a separate date from when the commit is done, even for official releases actually.

---

*[mullvad-types/src/version.rs, line 2 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IKlQIf9iDtju1HaoO:-L8IKlQIf9iDtju1HaoP:b-22hpjo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L2)):*
> ```Rust
> /// `LatestAppVersions` represent the current stable and the current latest release versions of the
> /// Mullvad VPN app.
> ```

There is no `LatestAppVersions` anywhere, so maybe update the docs?

---

*[mullvad-types/src/version.rs, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IJzTd9YZ0tCCMOJw9:-L8IJzTd9YZ0tCCMOJwA:bwm5xtl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L5)):*
> ```Rust
> #[derive(Debug, Clone, Serialize, Deserialize)]
> pub struct AppVersionInfo {
>     pub current_version: String,
> ```

Idea: How about you `pub type AppVersion = String;` and then use that everywhere, to make it easier to understand which strings are versions. Also makes it easier if we want to create a dedicated `AppVersion` type at some point.

---

*[mullvad-types/src/version.rs, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IKcmtJ5xPT9BR6IZz:-L8IKcmtJ5xPT9BR6I_-:b-v8h90i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L5)):*
> ```Rust
> #[derive(Debug, Clone, Serialize, Deserialize)]
> pub struct AppVersionInfo {
>     pub current_version: String,
> ```

I don't see a real reason to lump all of this into one struct. Other than the fact that it makes it easier to query in one call. Since there is a dedicated `get_current_version` maybe we can strip `current_version` from this struct?

---

*[mullvad-types/src/version.rs, line 6 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IJ_ivmuggpcDc5W9o:-L8IJ_ivmuggpcDc5W9p:b4jdxw9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L6)):*
> ```Rust
> pub struct AppVersionInfo {
>     pub current_version: String,
>     pub is_supported: bool,
> ```

Since this struct both include current and latest version maybe it would be nice to say `current_is_supported` to make that clear?

---

*[mullvad-types/src/version.rs, line 10 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IIJ4UdcK2we3IpaDu:-L8IIJ4UdcK2we3IpaDv:b-h4ngg6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L10)):*
> ```Rust
> }
> 
> /// `Latest` versions represent the latest released versions of the Mullvad VPN app.
> ```

What is `Latest` in backticks and capital L supposed to refer to here?
Maybe describe that `latest_stable` is the latest official stable release of the Mullvad VPN app and `latest` is the very latest release, including beta releases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by faern** [comment]
Review status: 4 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[mullvad-daemon/src/management_interface.rs, line 130 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8ILnHre3HwhHq4jrPK:-L8ILnHtSarX1nJZbwNh:b33wwl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/management_interface.rs#L130)):*
> ```Rust
>         /// Check if current version is supported
>         #[rpc(meta, name = "get_current_version")]
>         fn get_current_version(&self, Self::Metadata) -> BoxFuture<String, Error>;
> ```

Documentation seems outdated :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pinkisemils** [comment]
Review status: 3 of 10 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 26 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IEbipyGTiz2MHuDxm:-L8IbO_AS6Szt7No1fZ3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/CHANGELOG.md#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure about the expression `RPCs`. How about "Fetches latest app version and checks current version support with Mullvad API"?
</blockquote></details>

Done.

---

*[mullvad-cli/src/cmds/version.rs, line 24 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IGDRQivYT6e7lzue_:-L8IbPfRz0hZhXEBvUDl:bb77uci) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-cli/src/cmds/version.rs#L24)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The latest versions are not really the same as our supported versions. The latest will be our latest stable and our latest unstable. But we can still support many older releases. For example, when `2018.2` is the newest stable and `2018.3-beta1` is the latest unstable we will likely still support `2018.1`.

So a better wording might be `Latest versions:`?
</blockquote></details>

Yep!

---

*[mullvad-daemon/src/main.rs, line 253 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IGlkOW4Ykc4C_Lne7:-L8I_fEEpe7jCi6jEF5y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/main.rs#L253)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we keep the struct fields in the same order in the struct declaration and this place where we instantiate it? Would make it easier to find fields.

(This is one of the things I wish Rust enforced, requiring fields in the same order everywhere :)
</blockquote></details>

Done.

---

*[mullvad-daemon/src/management_interface.rs, line 130 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8ILnHre3HwhHq4jrPK:-L8IOBevxehEKX-vp2JR:b-hl2wdi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/management_interface.rs#L130)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Documentation seems outdated :)
</blockquote></details>

Speaking of things Rust _could_ have, the rare nice thing that Go's toolchain has is a rule that anything that's exported has to have a docstring that starts with the name of the particular entity. This proves to be a pretty ok ad-hoc way of ensuring that documentation isn't outdated.

---

*[mullvad-daemon/src/version.rs, line 8 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IHia_MT4dox1ZWcnq:-L8IVaqFPBgQ2urjwk2m:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/version.rs#L8)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's actually the date of the commit, not the build. Maybe we should stick to calling it the commit date to be consistent? Also might be confusing to call it the build date since it might be built on a separate date from when the commit is done, even for official releases actually.
</blockquote></details>

Done.

---

*[mullvad-rpc/src/lib.rs, line 44 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8Id9SoWZbRs5iDp2xh:-L8Id9SoWZbRs5iDp2xi:b-t0kkes) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fc514e4e0077fa63667e90a97bd089ec6d7bf87/mullvad-rpc/src/lib.rs#L44)):*
> ```Rust
> 
> 
> static MASTER_API_URI: &str = "https://api.mullvad.net/rpc/";
> ```

Would it be OK to make the MASTER_API_URI configurable or overridable with an environment variable?

---

*[mullvad-types/src/version.rs, line 2 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IKlQIf9iDtju1HaoO:-L8Icr9mBAHtuT54m3_3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

There is no `LatestAppVersions` anywhere, so maybe update the docs?
</blockquote></details>

Done.

---

*[mullvad-types/src/version.rs, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IJzTd9YZ0tCCMOJw9:-L8IcT-gWjeir0dvuw6Q:bq1tco0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Idea: How about you `pub type AppVersion = String;` and then use that everywhere, to make it easier to understand which strings are versions. Also makes it easier if we want to create a dedicated `AppVersion` type at some point.
</blockquote></details>

This is how I started this module out, but I wasn't sure if newtyping all the things is worth it. 

---

*[mullvad-types/src/version.rs, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IKcmtJ5xPT9BR6IZz:-L8Ic_TqtUywUW_jin8a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't see a real reason to lump all of this into one struct. Other than the fact that it makes it easier to query in one call. Since there is a dedicated `get_current_version` maybe we can strip `current_version` from this struct?
</blockquote></details>

Done.

---

*[mullvad-types/src/version.rs, line 6 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IJ_ivmuggpcDc5W9o:-L8IcS7UqxF7vaLJjesJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since this struct both include current and latest version maybe it would be nice to say `current_is_supported` to make that clear?
</blockquote></details>

Done.

---

*[mullvad-types/src/version.rs, line 10 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IIJ4UdcK2we3IpaDu:-L8ISOgxzz_6ZgE1U9Ap:b-p7v6ys) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What is `Latest` in backticks and capital L supposed to refer to here?
Maybe describe that `latest_stable` is the latest official stable release of the Mullvad VPN app and `latest` is the very latest release, including beta releases?
</blockquote></details>

`Latest` in backticks is but a mistake on my part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by faern** [comment]
Reviewed 4 of 8 files at r2, 1 of 1 files at r3.
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[mullvad-daemon/src/management_interface.rs, line 130 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8ILnHre3HwhHq4jrPK:-L8Wuiu5VpSD1u3ZRJAy:bsuv5kc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-daemon/src/management_interface.rs#L130)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Speaking of things Rust _could_ have, the rare nice thing that Go's toolchain has is a rule that anything that's exported has to have a docstring that starts with the name of the particular entity. This proves to be a pretty ok ad-hoc way of ensuring that documentation isn't outdated.
</blockquote></details>

Interesting. But I think it sounds redundant to have the name of the element also in the docs. "get_current version returns ..." over just "returns ..."

---

*[mullvad-rpc/src/lib.rs, line 44 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8Id9SoWZbRs5iDp2xh:-L8WvDfNH7EbuY5tVAL7:b-c6q5em) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fc514e4e0077fa63667e90a97bd089ec6d7bf87/mullvad-rpc/src/lib.rs#L44)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would it be OK to make the MASTER_API_URI configurable or overridable with an environment variable?
</blockquote></details>

I guess you want this for the purpose of easier testing towards a test server? Yes, sounds reasonable to make it configurable at runtime indeed. As long as we have a clear and good naming scheme for environment variables, since we don't have any environment variables yet we have to think about that when we introduce them. Just starting them with `MULLVAD_` sounds good to me.

I think the word "master" should be removed from this context all together actually. It's a word we use internally for this server and the API is not bound to be on master really.

But @jvff is working on this same part of the code with his work to rely on the IP rather than the domain, so maybe not touch too much here for now? because it will just collide with his work anyway.

---

*[mullvad-types/src/version.rs, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8IJzTd9YZ0tCCMOJw9:-L8WwM6gkn5IUIBIPymi:b6jn9t6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f33fda19b0b571156088b9c638b6e9d20eec341/mullvad-types/src/version.rs#L5)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is how I started this module out, but I wasn't sure if newtyping all the things is worth it. 
</blockquote></details>

Maybe not all things. But for this one I think it would be nice :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by faern** [comment]
Reviewed 2 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by jvff** [comment]
Reviewed 3 of 11 files at r1, 6 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 499 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8X0I5287-OIBWt2TpW:-L8X0I5287-OIBWt2TpX:brracr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-daemon/src/main.rs#L499)):*
> ```Rust
>                     .is_app_version_supported(&current_version),
>             )
>             .map(move |(latest_versions, is_supported)| AppVersionInfo {
> ```

This `move` seems unnecessary. AFAIK the compiler should automatically infer an `Fn` implementation for it, since it doesn't use anything from the environment.

---

*[mullvad-rpc/src/lib.rs, line 44 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8Id9SoWZbRs5iDp2xh:-L8WzmsQ584ST-JyUrXA:b-crquv2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fc514e4e0077fa63667e90a97bd089ec6d7bf87/mullvad-rpc/src/lib.rs#L44)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I guess you want this for the purpose of easier testing towards a test server? Yes, sounds reasonable to make it configurable at runtime indeed. As long as we have a clear and good naming scheme for environment variables, since we don't have any environment variables yet we have to think about that when we introduce them. Just starting them with `MULLVAD_` sounds good to me.

I think the word "master" should be removed from this context all together actually. It's a word we use internally for this server and the API is not bound to be on master really.

But @jvff is working on this same part of the code with his work to rely on the IP rather than the domain, so maybe not touch too much here for now? because it will just collide with his work anyway.
</blockquote></details>

After PR #97 is merged, it might be easier to test, depending on what you want to do. We can talk about what you'd like to do and see what changes would be required afterwards.

---

*[mullvad-types/src/version.rs, line 16 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8X-d3r8_OjJOmLuHzJ:b-u533i7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
> ```Rust
> }
> 
> pub type AppVersion = String;
> ```

Is there a reason to make this an alias instead of a tuple type?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pronebird** [comment]
Reviewed 1 of 11 files at r1, 2 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[mullvad-cli/src/cmds/version.rs, line 26 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8X5Qha2oNUM4Lgt2Vz:-L8X5Qha2oNUM4Lgt2W-:bdmjqa5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-cli/src/cmds/version.rs#L26)):*
> ```Rust
>         println!("Latest releases:");
>         println!("\tlatest stable: {}", version_info.latest.latest_stable);
>         println!("\tlatest: {}", version_info.latest.latest);
> ```

Does it point to the latest beta or latest any kind of release?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pronebird** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[mullvad-types/src/version.rs, line 16 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8X5vgeVGHoYyFuxOms:b-5g3xps) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is there a reason to make this an alias instead of a tuple type?
</blockquote></details>

Tuple you mean like `(major, minor, patch)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 54 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8X6OFfrqHJ_RMOi8FU:-L8X6OFfrqHJ_RMOi8FV:b-xl5jfx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-daemon/src/main.rs#L54)):*
> ```Rust
> mod settings;
> mod shutdown;
> pub mod version;
> ```

Has to be public?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pronebird** [comment]
Reviewed 1 of 11 files at r1, 4 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by jvff** [comment]
*[mullvad-types/src/version.rs, line 16 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8X7O9h4DPTDZtW4p7O:b-4ebzjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Tuple you mean like `(major, minor, patch)`?
</blockquote></details>

That's an option, maybe `(major, minor, patch, suffix)` would be more complete, but what I actually meant was something like `AppVersion(String)`, with a trivial `impl Display`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-types/src/version.rs, line 16 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8X7qy71_k8bYy0Ksm7:b-fcjkx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That's an option, maybe `(major, minor, patch, suffix)` would be more complete, but what I actually meant was something like `AppVersion(String)`, with a trivial `impl Display`.
</blockquote></details>

I don't think there is any need for `AppVersion(String)` since String itself is printable. 

At the same time we don't use `patch` and have it zeroed because of `package.json` semantic version restrictions. Normally we omit or remove it when displaying version. This shouldn't be the case with our backend since we can feed any strings we want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-types/src/version.rs, line 16 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8X8YVjBBHCt-kQZgYi:b-lvhk4h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I don't think there is any need for `AppVersion(String)` since String itself is printable. 

At the same time we don't use `patch` and have it zeroed because of `package.json` semantic version restrictions. Normally we omit or remove it when displaying version. This shouldn't be the case with our backend since we can feed any strings we want.
</blockquote></details>

Although this raises an interesting question regarding the update status if the app that we run is on beta channel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/105)*

**Comment by jvff** [comment]
*[mullvad-types/src/version.rs, line 16 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8X9d821NT0qjxD87E2:b-ti2j7d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Although this raises an interesting question regarding the update status if the app that we run is on beta channel.
</blockquote></details>

My point is that a type alias doesn't offer a new type, just a fancier way to name a type. And I think having `AppVersion` map to `String` might be a point of confusion, so I'd usually just use `String`. The advantage I see is that in a future we can have a more complex `AppVersion` type, and using the name already might reduce the code to change in the future. However, I'd rather separate the type completely, to avoid using it as a `String` later on, which would diminish the original advantage.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-cli/src/cmds/version.rs, line 26 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8X5Qha2oNUM4Lgt2Vz:-L8XKwOt4dPZDquwUVcZ:b-fk2rra) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-cli/src/cmds/version.rs#L26)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It is entirely API dependent, currently, latest is just the `latest` is the latest supported version and `latest_stable` is the latest supported version that is also stable. 
https://github.com/mullvad/mullvad-api/blob/master/core/models.py#L5
https://github.com/mullvad/mullvad-api/blob/master/rpc/methods.py#L532
</blockquote></details>

Exactly. Someone who is running a stable client should be shown the latest released version that is stable. They should never be recommended betas. But someone who is running beta should be recommended the very latest version, if the latest version is a stable release they should be recommended that one.

---

*[mullvad-rpc/src/lib.rs, line 44 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8Id9SoWZbRs5iDp2xh:-L8XLK3O1QTlmw2jBLjw:bpm1yj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fc514e4e0077fa63667e90a97bd089ec6d7bf87/mullvad-rpc/src/lib.rs#L44)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yep, I just wanted to raise the discussion somewhere.

Regarding naming, I was under the impression that master was the server _application_, not the server as in a box called master.

</blockquote></details>

Exactly why we want to not use the word "master" because it's so super generic and the source of so much confusion. *master* is a server. We also have a git repository with various random stuff running *on master*.

---

*[mullvad-types/src/version.rs, line 16 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-L8X-d3r8_OjJOmLuHzI:-L8XLbt24XucP-k9lz_I:boeugnq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28aa7e3323ef98350f9b1bd217431ea8ce17ea37/mullvad-types/src/version.rs#L16)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

In some cases, the type alias can inform the user as to what data a parameter or a field should hold. Parsing the version string doesn't yield us much currently, as we're not enforcing version locks between the CLI, the frontend and the daemon yet.
</blockquote></details>

I suggested this type alias. The pros of having it over just plainly using `String` is that one can easily see on struct fields etc that the string in question is a version. That is why I wanted an alias, `String` is just so generic.

The reason I did not recommend a newtype pattern was that then that would have to implement serialization, comparison etc etc etc. With an alias it's just for free.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105)*

**Comment by jvff** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105#-:-L8YX7ByB713w0qTlXht:bnfp4nl)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/105)*

**Pull request merged**
