### PR TITLE
Scroll to selected country

### PR DESCRIPTION
**Pull request by Rawa**
Scroll to the selected country in SelectLocationScreen

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551#-:-NkuOWdxCH-JIF5i7OTK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551#-:-Nl0Ad6NCPnmIRDXWRwe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551#-:-NlxQRY62Vr85O0XFzWs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
