### PR TITLE
Fix blocked connection text color

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058#-NuYIami0nCHoUFwNcma:-NuYIami0nCHoUFwNcmb:b-v0nbub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a91498f342ccc0a25e821445c9f0ccc6888313e6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L103)):*
> ```Kotlin
>             ),
>         color =
>             if (isBlocking) MaterialTheme.colorScheme.onBackground else MaterialTheme.colorScheme.error,
> ```

On connecting we use `onPrimary` for white text so I think this should be the same.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058#-NuYIami0nCHoUFwNcma:-NuYZUgFEh88uLASrwm9:b-86pzpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a91498f342ccc0a25e821445c9f0ccc6888313e6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L103)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

On connecting we use `onPrimary` for white text so I think this should be the same.
</blockquote></details>

Fixed! I looked into the map as well, seems like we use primay for land there as well, so it sort of makes sense I think.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058#-:-NuYlpcJD_hAkLrGIpLw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058#-:-NuZAeBp6Kyub2WWFSvg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
