### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by mvd-ows**
Seems to be working on Windows :-)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/115)

### CODE REVIEW

**Comment by faern** [comment]
This change will cause the app to be installed as `/Applications/Mullvad VPN.app` on macOS. Thus this will not overwrite the previous install, but rather install a new copy.

I think the name with the space is better (Lots of very common macOS apps have spaces in them). So we need to figure out how to do the migration. There is still some `MullvadVPN` hardcoded that I think should be changed at the same time to make the switch in one go instead of having to worry about this again:
https://github.com/mullvad/mullvadvpn-app/blob/5b0118e589b5b1fb60fd9f3ba8c132bd483db975/app/main.js#L24
https://github.com/mullvad/mullvadvpn-app/blob/5b0118e589b5b1fb60fd9f3ba8c132bd483db975/app/main.js#L36
https://github.com/mullvad/mullvadvpn-app/blob/a87c4b54d4350ed08687fb871910a1ee80fcfb0b/uninstall.sh#L18
https://github.com/mullvad/mullvadvpn-app/blob/a87c4b54d4350ed08687fb871910a1ee80fcfb0b/uninstall.sh#L21

And this last one I'm not even sure if it exists and being used?
https://github.com/mullvad/mullvadvpn-app/blob/a87c4b54d4350ed08687fb871910a1ee80fcfb0b/uninstall.sh#L9

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-:-L9F38jM5Zq1056bQsCm:bg364aa)*

**Comment by pronebird** [comment]
It removes the use of `${productName}` and replaces it with the same value that's already defined on line 3 of electron-builder config. 

Then @faern  talks about app being installed at `/Application/Mullvad VPN.app/...` but this change does not address this at all..

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-:-L9FbHID9_gtzlQwNmM9:b-y4saum)*

**Comment by mvd-ows** [comment]
*[electron-builder.yml, line 43 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-L9FaHxVC4cDT39rRuqo:-L9Fedhf9HitEWCI9gqr:b89e7sh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27b6431026d343c14c3f669739014aaa6c2fcd68/electron-builder.yml#L43)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

`${productName}` is already `MullvadVPN`. There is no point to change anything.
</blockquote></details>

Please scroll up, `${productName}` has been updated to read `Mullvad VPN` (space in-between). This affects the name of window titles, shortcuts created during installation etc.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[electron-builder.yml, line 43 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-L9FaHxVC4cDT39rRuqo:-L9G4auIAJUVG6XsCsyT:buqncjq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27b6431026d343c14c3f669739014aaa6c2fcd68/electron-builder.yml#L43)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Please scroll up, `${productName}` has been updated to read `Mullvad VPN` (space in-between). This affects the name of window titles, shortcuts created during installation etc.
</blockquote></details>

Yeah. I understand the confusion here. I was also confused. Reviewable is so terrible at some things. IT WON'T ACTUALLY SHOW THAT CHANGE! My god, so confusing. It just collapses it and says "only whitespace changes" as a link that you can use to expand it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[electron-builder.yml, line 43 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-L9FaHxVC4cDT39rRuqo:-L9G4nbl3JqMmIsomA7-:bgzivgu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27b6431026d343c14c3f669739014aaa6c2fcd68/electron-builder.yml#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yeah. I understand the confusion here. I was also confused. Reviewable is so terrible at some things. IT WON'T ACTUALLY SHOW THAT CHANGE! My god, so confusing. It just collapses it and says "only whitespace changes" as a link that you can use to expand it.
</blockquote></details>

@pronebird The thing is that we still want the installer files to not have spaces in them. Since that makes download urls etc worse. But we want the formal name of the app to be "Mullvad VPN" in shortcuts and menus etc so there should be a space in the product name.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115)*

**Comment by pronebird** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[electron-builder.yml, line 43 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-L9FaHxVC4cDT39rRuqo:-L9PJ2o3214zxA35S5jA:b-qmogzr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27b6431026d343c14c3f669739014aaa6c2fcd68/electron-builder.yml#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

@pronebird The thing is that we still want the installer files to not have spaces in them. Since that makes download urls etc worse. But we want the formal name of the app to be "Mullvad VPN" in shortcuts and menus etc so there should be a space in the product name.
</blockquote></details>

Omg. OK now I see. Thanks @faern 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115#-:-L9PLNfq20k6Dfx_g7xj:bnfp4nl)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/115)*

**Comment by mvd-ows** [comment]
Opening dedicated PR for name change.

**Pull request closed without merging**
