### PR TITLE
DNS Refactor

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/123)

### CODE REVIEW

**Comment by jvff** [comment]
This is a first attempt at refactoring the DNS setting code. I wasn't able to test the MacOS changes, so I'm not even sure it works 100% yet. The idea is to throw the idea out to gather some initial feedback, to see if I continue on this path or postpone it after all platform have at least one independent implementation.

Naming should probably be improved.

One major design difference between the original MacOS implementation and the refactored one is that AFAIU, the entry point for setting and resetting the config used a separate `SCDynamicStore` than the monitor thread, but now there's only one running on a "handler" thread, which receives events from both the monitor and from external requests to set (configure) or reset (restore) the configuration.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-:-L9rtRA58wkTDa7bAEiv:b4sd2m3)*

**Comment by faern** [comment]
Feels very dangerous to make such sweeping changes to the macOS implementation without being able to test it.

My initial feeling is; why refactor before we have a set of implementations to refactor over? And I think the three implementations will be fairly different, at least different enough to not fully be able to express their failures using one error type, for example `HandlerStopped`, we don't know if this will be relevant on more than one platform?

See my code comment. I'm thinking we can start slowly and abstract a bit instead of a complete overhaul before we know what the implementations will look like.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[talpid-core/src/dns.rs, line 45 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9smm55D6cBeUiT7twF:-L9smm55D6cBeUiT7twG:br32tlx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L45)):*
> ```Rust
> /// The only thing that matters for this module is how to read the configured name server IP
> /// addresses and how to change the them.
> pub trait DnsConfig: Clone {
> ```

Do we need this kind of complex abstraction for a config? And for interfaces and monitors as well for that matter? I thought that we could get away with something as simple as:
```rust
trait DnsSettings {
    type Error;

    fn new() -> Result<Self, Error>;

    /// Sets the system DNS to the given IPs. Should also monitor the system and make sure these IPs stay
    /// active (if the system supports it) until `reset` is called.
    fn set(&mut self, nameservers: &[Ipv4Addr]) -> Result<(), Error>;

    /// Reset the system DNS to whatever was active before `set` was called.
    fn reset(&mut self) -> Result<(), Error>;
}
```
Very similar to `Firewall`. Where each implementor can freely decide how this is implemented.
Does the monitor thing have to be a platform agnostic thing? It could just be spawn internally in the implementation of the `set` method if that given platform supports it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-:-L9sktbL5mKuk9DOFzrU:b-mtvnc0)*

**Comment by faern** [comment]
Or maybe this is a really awesome abstraction. I have not been able to grasp it yet. So if you believe this is the right approach maybe we could have a walk through on mumble?

---

Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-:-L9sp5sw2Dry65EM5bdg:bfrka0n)*

**Comment by faern** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[talpid-core/src/dns.rs, line 71 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9spjv35pieq88ImK6-:-L9spjv35pieq88ImK60:b-wfgzqe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L71)):*
> ```Rust
> ///
> /// A type implementing this interface does not need to implement `Send`.
> pub trait DnsConfigInterface: Sized {
> ```

What does "interface" mean here? Like a network interface? Not all OSes configure DNS per interface so maybe this is not suitable to abstract on an OS agnostic level?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123)*

**Comment by faern** [comment]
Since the DNS will be set and monitored in each `Firewall` (Maybe renamed to something like `SecurityPolicyManager` or something later) implementer there will be three places in the code where a `DnsManager` will be created and used. Or more specifically one for each platform. So I don't really see the gain in cramming in all DNS implementers under one interface, since they will be used separately anyway. So the three `Firewall` implementers can have different code for creating their respective `WindowsDnsManager`, `MacOsDnsManager` etc. And since the code that uses the DNS managers is different they must not have the same interface really.

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-:-L9srpjB5vqUeB2SuBEN:b-8ppyit)*

**Comment by jvff** [comment]
I agree about avoid making changes without being able to test them. I won't merge these changes without proper testing. That said, maybe splitting the PR in two, one for the abstract stuff and one for MacOS stuff, might make things more manageable.

I'll work on the Linux implementation next. Maybe it's better if we see all implementations first in order to better assess the advantages and disadvantages of this refactor?

On all `Firewall` implementations, AFAICT the usage would be to create a`DnsManager`, and only call the `configure` and `restore` methods when necessary. Are there any other platform specific requirements?

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/dns.rs, line 45 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9smm55D6cBeUiT7twF:-L9tEnIq9xwutjIoDnGf:b-t7k5vs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do we need this kind of complex abstraction for a config? And for interfaces and monitors as well for that matter? I thought that we could get away with something as simple as:
```rust
trait DnsSettings {
    type Error;

    fn new() -> Result<Self, Error>;

    /// Sets the system DNS to the given IPs. Should also monitor the system and make sure these IPs stay
    /// active (if the system supports it) until `reset` is called.
    fn set(&mut self, nameservers: &[Ipv4Addr]) -> Result<(), Error>;

    /// Reset the system DNS to whatever was active before `set` was called.
    fn reset(&mut self) -> Result<(), Error>;
}
```
Very similar to `Firewall`. Where each implementor can freely decide how this is implemented.
Does the monitor thing have to be a platform agnostic thing? It could just be spawn internally in the implementation of the `set` method if that given platform supports it.
</blockquote></details>

What you called `DnsSettings` is what I called `DnsInterface`. But I separated the monitor system into a different type, and also moved the previous state tracking code to be platform independent inside the `DnsHandler`. The `DnsConfig` type is then a way for these platform specific parts to represent what a platform specific DNS configuration state is.

It's true that the `DnsConfig` wraps the name server list, but there's also other meta-data that's being handled by the platform specific parts which don't matter to the platform independent parts. On MacOS that would be the configuration of each interface (and the "setup_path" that's stored in the `SCDynamicStore`). On Linux it would be the `resolv.conf` settings (timeout, search domain, etc.).

That said, I think I still need to see if these parts really are platform independent or not.

---

*[talpid-core/src/dns.rs, line 71 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9spjv35pieq88ImK6-:-L9tG2AoDgyIKAcIQKVB:b-rsluxx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L71)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What does "interface" mean here? Like a network interface? Not all OSes configure DNS per interface so maybe this is not suitable to abstract on an OS agnostic level?
</blockquote></details>

No, it's an abstract name for a type that bridges the platform independent parts with the platform specific calls.

I think I need to improve the documentation, and also select a clearer name perhaps?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-:-L9tA3iH8t0Pef_TnNAG:b-du4pix)*

**Comment by faern** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/dns.rs, line 71 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9spjv35pieq88ImK6-:-L9tT6r9Dv7clso_Mh9Y:b-k763gs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L71)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

No, it's an abstract name for a type that bridges the platform independent parts with the platform specific calls.

I think I need to improve the documentation, and also select a clearer name perhaps?
</blockquote></details>

I see. Yeah I would vote for changing the name. "Interface" has such a specific and well known meaning  in the context of operating system network subsystems.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123)*

**Comment by mvd-ows** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/dns.rs, line 85 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9zhWoP4ka8aQ4K2o3Z:-L9zhWoP4ka8aQ4K2o3_:bwz7xvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L85)):*
> ```Rust
> 
>     /// Read current DNS configuration.
>     fn read_config(&mut self) -> ::std::result::Result<Self::Config, Self::Error>;
> ```

Windows maintains the DNS configuration per adapter.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123)*

**Comment by jvff** [comment]
*[talpid-core/src/dns.rs, line 85 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123#-L9zhWoP4ka8aQ4K2o3Z:-LA37XdmC2MdDnxcXfQl:b-pnrs3y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d4cc487513f3d318d3dc97cd4714665d3975f09f/talpid-core/src/dns.rs#L85)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Windows maintains the DNS configuration per adapter.
</blockquote></details>

That's also the case in MacOS. There a `HashMap<String, Option<Vec<String>>>` is used to map interfaces to its DNS settings, if I understood correctly. That's also why I added `read_update`, it allows reading the settings of only the interfaces that changed (specified in the custom `Update` type), and then the `DnsConf::merge_with` can be used to update the `DnsConfig` type with all the configurations with a partial `DnsConfig` type, and `DnsConfig::merge_ignoring_nameservers` allows merging only extra metadata (if it exists, otherwise it can be left empty).

All that said, perhaps its better to leave this refactor for later? I'm not sure if it would help with writing the DNS stuff on Windows.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/123)*

**Comment by pinkisemils** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/123)*

**Comment by jvff** [comment]
I'm closing this because the refactor would have to be redone to consider all the changes since this was first started.

**Pull request closed without merging**
