### PR TITLE
Bump go version in GitHub actions

### PR DESCRIPTION
**Pull request by albin-mullvad**
Bump `setup-go` action version and go version.

TODO:
* [ ] Build docker image(s) and upload to quay.
* [ ] Update hashes/checksums in scripts relying on the built docker image(s).
* [ ] Ensure all builds/scripts are working.

Git checklist:

~* [] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (only affects GH actions)
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3537)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
I think `libwg` and the Docker image should ideally use the same version. Now the build server and GitHub actions are out of sync in that respect.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3537#-:-N0kCR8P8ZXFZvSXkUtt:b-hxkb0m)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
The actual image should also be updated (we use this in `build-wireguard-go.sh`).

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3537#-:-N0oFcp_9aL82DTGgWxV:b-yxlg9l)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
Doesn't really matter for iOS tests for as long as wg-go compiles with the given version of go but never runs. However I think we compile release builds of iOS app with 1.16.

> Reviewed 1 of 3 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3537#-:-N4Xzt-UAg6XnrUw7icZ:bxiey2l)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3537)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
