### PR TITLE
Improve random port distribution

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

- Improve random port distribution. Should be less biased towards port 53. See Rust code for reference: 
  https://github.com/mullvad/mullvadvpn-app/blob/66ff8978f94d4ad1c8c45872de9f540cbcbcf612/mullvad-daemon/src/relays/matcher.rs#L202-L238
- Replace `CloseRange<UInt16>` in relay model with `[[UInt16]]`. Parse and validate  port ranges manually in `RelaySelector`, skip invalid ranges but don't error.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/RelaySelector.swift, line 119 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493#-N-8XJwJ6Aj8SyT0iiR6:-N-8XJwJ6Aj8SyT0iiR7:bmu29mr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a244060c5c9d0454379877877f0ed020bacd80a/ios/MullvadVPN/RelaySelector.swift#L119)):*
> ```Swift
>     }
> 
>     private static func pickRandomPort(rawPortRanges: [[UInt16]]) -> UInt16? {
> ```

Wouldn't it be easier to do something like this or am I missing somehting?
```
return rawPortRanges.joined().randomElement()
```
or if that doesn't work:
```
return parseRawPortRanges(rawPortRanges).joined().randomElement()
```

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/RelaySelector.swift, line 119 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493#-N-8XJwJ6Aj8SyT0iiR6:-N-8hRzg8ClrGK34DpCZ:b-oqkaq5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a244060c5c9d0454379877877f0ed020bacd80a/ios/MullvadVPN/RelaySelector.swift#L119)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Wouldn't it be easier to do something like this or am I missing somehting?
```
return rawPortRanges.joined().randomElement()
```
or if that doesn't work:
```
return parseRawPortRanges(rawPortRanges).joined().randomElement()
```
</blockquote></details>

Port ranges are expressed as array of arrays of `UInt16` as returned from API, i.e:

```
[
  [53, 53], // single port 53
  [1024, 2048], // port range of 1024 - 2048
  // etc..
]
```

So these are not ports themselves but sequence of arrays with two elements, where the first element tells the start port and the second element is the end port of the range.

Since we have over 40k of ports overall, expressing them as array of individual port numbers would take around 100KB of memory. It's more efficient to use a range and quickly loop through it to find the port we need.

**Review by raksooo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493#-:-N-MpIlkBJu5cVoYAyT5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/RelaySelector.swift, line 119 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493#-N-8XJwJ6Aj8SyT0iiR6:-N-MnnpuEJMXpN-O6eBq:b-n21xts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a244060c5c9d0454379877877f0ed020bacd80a/ios/MullvadVPN/RelaySelector.swift#L119)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Port ranges are expressed as array of arrays of `UInt16` as returned from API, i.e:

```
[
  [53, 53], // single port 53
  [1024, 2048], // port range of 1024 - 2048
  // etc..
]
```

So these are not ports themselves but sequence of arrays with two elements, where the first element tells the start port and the second element is the end port of the range.

Since we have over 40k of ports overall, expressing them as array of individual port numbers would take around 100KB of memory. It's more efficient to use a range and quickly loop through it to find the port we need.
</blockquote></details>

Makes sense! Thanks for clarifying!
___
*[ios/MullvadVPN/RelaySelector.swift, line 125 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493#-N-MntFpBQdFNM-KJLld:-N-MntFq7PEmTMSjl3Zj:bbotuod) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a244060c5c9d0454379877877f0ed020bacd80a/ios/MullvadVPN/RelaySelector.swift#L125)):*
> ```Swift
>         }
> 
>         guard var portIndex = (0..<portAmount).randomElement() else {
> ```

How does Swift handle the conversion from range to collection and `randomElement` here? Is it lazy evaluating, or will it initialize the whole collection?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/RelaySelector.swift, line 125 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493#-N-MntFpBQdFNM-KJLld:-N-MrKI01UWPa2HQd76p:bu8jr27) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a244060c5c9d0454379877877f0ed020bacd80a/ios/MullvadVPN/RelaySelector.swift#L125)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

How does Swift handle the conversion from range to collection and `randomElement` here? Is it lazy evaluating, or will it initialize the whole collection?
</blockquote></details>

I don't think the call to `randomElement()` converts the `Range<Int>` to Collection. I think it simply produces a random number between the lower and upper bound of the range, i.e:

```

let range: Range<UInt16> = (5..<10)
var randomGenerator = SystemRandomNumberGenerator()
let randomNumber = range.lowerBound + randomGenerator.next(
  upperBound: range.upperBound - range.lowerBound
)
```

Also note that `0..<0` is an empty range, so `randomElement()` will always return `nil` in that case, hence I never check if `portAmount > 0`.

**Pull request merged**
