### PR TITLE
Always restart daemon when full-disk access message has been shown

### PR DESCRIPTION
**Pull request by dlon**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)

### CODE REVIEW

**Review by hulthe — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by raksooo — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`desktop/packages/mullvad-vpn/src/main/index.ts` line 749 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189#-OC7d8HqCdN2j4kgp155:-OC7d8HqCdN2j4kgp156:b-mrzace) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c683f14ab869e2a378680cbc26b7dbc785cde1e8/desktop/packages/mullvad-vpn/src/main/index.ts#L749)):*
> ```XML
>     this.tunnelState.handleNewTunnelState(await this.daemonRpc.getState());
>     if (newState.state === 'error' && newState.details) {
>       if (newState.details.cause === ErrorStateCause.needFullDiskPermissions) {
> ```

Nit: How about this instead?
```
if (newState.state === 'error' && newState.details?.cause === ErrorStateCause.needFullDiskPermissions) {
```

**Review by raksooo — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189#-:-OC8vXHL8Tnw9RUcM5FQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
