### PR TITLE
Build `test-manager` as a standalone executable

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)* status: all files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/scripts/build.sh` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4EnKfWAJIFqs9cu8KY:-O4EnKfWAJIFqs9cu8KZ:b-sxa8hy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/scripts/build.sh#L14)):*
> ```Shell
> build_linux() {
>     # Build the test manager
>     "$SCRIPT_DIR/container-run.sh" bash -c "cd $TEST_FRAMEWORK_ROOT; OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl cargo build -p test-manager --release"
> ```

Should we invert how `container-run` is used? That seems more consistent with how the test runner is built:


```
# ./scripts/build-manager.sh
# Statically build test-manager

export OPENSSL_STATIC=1
export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
export OPENSSL_INCLUDE_DIR=/usr/include/openssl

cargo build -p test-manager --release

...
```

```
# usage:
# ./scripts/container-run.sh ./scripts/build-manager.sh
```
___
*[`test/scripts/Dockerfile` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Eoy-Z5a3leTAuLNpB:-O4EnqVY5Yq_WuYxCziG:bv2v0dg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/scripts/Dockerfile#L15)):*
> ```Dockerfile
>     && ./configure --enable-remote=yes --enable-dbus=no --enable-shared=no \
>     && make \
>     && cp libpcap.a /usr/lib/x86_64-linux-gnu/libpcap.a
> ```

Perhaps we could remove packages/directories that are only used during compilation? Ie flex, bison, and `./libpcap`.
___
*[`test/scripts/Dockerfile` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Ep93hCsr2K-mko-kq:-O4Ep93hCsr2K-mko-kr:b-bazpwr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/scripts/Dockerfile#L15)):*
> ```Dockerfile
>     && ./configure --enable-remote=yes --enable-dbus=no --enable-shared=no \
>     && make \
>     && cp libpcap.a /usr/lib/x86_64-linux-gnu/libpcap.a
> ```

Nit: This is fine but I wonder if `make install` would work.
___
*[`test/test-manager/build.rs` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Eo0aD-PjF7ZUwcklO:-O4Eo0aD-PjF7ZUwcklP:b-pv5ntz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/test-manager/build.rs#L5)):*
> ```XML
>     println!("cargo::rerun-if-changed=../scripts/ssh-setup.sh");
> 
>     println!("cargo::rustc-link-search=native=/usr/lib/x86_64-linux-gnu");
> ```

Does this build without the container still (including on macOS)? Otherwise, maybe we could pass this in from the script instead.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test/scripts/Dockerfile` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Eoy-Z5a3leTAuLNpB:-O4EsTOECpArPbyt4c1n:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/scripts/Dockerfile#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Perhaps we could remove packages/directories that are only used during compilation? Ie flex, bison, and `./libpcap`.
</blockquote></details>

Done
___
*[`test/scripts/Dockerfile` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Ep93hCsr2K-mko-kq:-O4EsU2tCXo_aHZ23N6I:b-yhwiam) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/scripts/Dockerfile#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: This is fine but I wonder if `make install` would work.
</blockquote></details>

Done Nice catch! Worked great :)

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/build.rs` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Eo0aD-PjF7ZUwcklO:-O4EuqBy3452ZYMl21tn:b8jip9v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/test-manager/build.rs#L5)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Does this build without the container still (including on macOS)? Otherwise, maybe we could pass this in from the script instead. Or have some env var.
</blockquote></details>

Introduced `TEST_MANAGER_STATIC` and passes it from `scripts/build.sh` to link against `libpcap` statically. So a regular `cargo build` should work as before :blush:

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test/scripts/build.sh` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4EnKfWAJIFqs9cu8KY:-O4F1Pu5EEdfR6kSxEga:b-89tfct) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/scripts/build.sh#L14)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we invert how `container-run` is used? That seems more consistent with how the test runner is built:


```
# ./scripts/build-manager.sh
# Statically build test-manager

export OPENSSL_STATIC=1
export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
export OPENSSL_INCLUDE_DIR=/usr/include/openssl

cargo build -p test-manager --release

...
```

```
# usage:
# ./scripts/container-run.sh ./scripts/build-manager.sh
```
</blockquote></details>

Running `./scripts/container-run.sh ./scripts/build.sh` will now compile `test-manager`, `test-runner` and `connection-checker` inside of the container.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`test/test-manager/build.rs` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615#-O4Eo0aD-PjF7ZUwcklO:-O4ExlRf1NJdrEsKWAv6:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/193ef9387dfc806eb9ae887a661b1a73b7c8b8ae/test/test-manager/build.rs#L5)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Introduced `TEST_MANAGER_STATIC` and passes it from `scripts/build.sh` to link against `libpcap` statically. So a regular `cargo build` should work as before :blush:
</blockquote></details>

:+1:

**Review by dlon — APPROVED** [review]

**Pull request merged**
