### PR TITLE
Add rustc version check to build.sh and do more cleaning prior to build

### PR DESCRIPTION
**Pull request by faern**
I noticed that just removing the binaries prior to a build is not enough of a cleanup. The buildscript, `build.sh` is not re-executed in this case and the new build can then contain old information collected in the last build. This happened just now when I built `2018.1`. To prevent this I do a full `cargo clean` before the `cargo build`. The re-build after that will take significantly longer, but since we don't use this release build script that often I think this is fully OK.

I also added a safety check that the correct stable compiler version is installed. I want the build script to be as strict as possible, too many things that are easy to forget when building a release and the tighter the automatic checks can be, the better. So we'll have to update the version variable approximately every six weeks when there is a new rustc, but I think that is much better than doing releases compiled on the wrong compiler.

Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/74)

### CODE REVIEW

**Comment by faern** [comment]
We should probably also check the yarn version etc. But I'll leave that for the future for now.

**Comment by mvd-ows** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/74)*

**Comment by pronebird** [comment]
Regarding `yarn` we can include the requirement in `packages.json`:

See https://github.com/yarnpkg/yarn/issues/522

Are you sure Cargo.toml does not have the compiler version requirement?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/74#-:-L6Lk7nd5wDOK6Xyjj85:byrr16j)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/74)*

**Comment by pronebird** [comment]
i.e it would be smart to have a minimum compiler version needed, for example due to features we may use that are only available on the newer compilers.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/74#-:-L6Lku2Q087gbR1_XiJa:b-yroamb)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[build.sh, line 8 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/74#-L6Ll3Mt2JVwAeEy18HL:-L6Ll3Mt2JVwAeEy18HM:b-hcc9sk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b85b75b9bfddb04f0a58785da494aee8c951b7b2/build.sh#L8)):*
> ```Shell
> set -eu
> 
> REQUIRED_RUSTC_VERSION="rustc 1.24.0 (4d90ac38c 2018-02-12)"
> ```

We'll have to maintain that string. 

Is there a reason why you want the project to be compiled on a specific version of compiler as opposed to based on available features we use in the language or a version range, for example `>= 1.24.0`?

I don't oppose, just wonder.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/74)*

**Comment by pronebird** [comment]
:thumbsup: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/74#-:-L6LlyyREAqwmbUg6riW:b4c9lyr)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[build.sh, line 8 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/74#-L6Ll3Mt2JVwAeEy18HL:-L6LncV-K-1ZgH11SQC5:b150kc6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b85b75b9bfddb04f0a58785da494aee8c951b7b2/build.sh#L8)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

We'll have to maintain that string. 

Is there a reason why you want the project to be compiled on a specific version of compiler as opposed to based on available features we use in the language or a version range, for example `>= 1.24.0`?

I don't oppose, just wonder.
</blockquote></details>

We indeed have to bump that approximately every six weeks yes. I thought I left a comment about that, but can't find it.

So, why I didn't do something like `>= 1.24.0`:
* It's much harder to do that check in bash, I would have to parse semver in some way, would be complicated.
* If it checks for a minimum version we could release `2018.2` with rustc `1.25` and then accidentally release `2018.3` with `1.24` if the minimum is untouched. This could of course work perfectly, but it could also introduce yet unknown problems. I thought if we strictly make sure it's built with an exact version and we only bump that version upwards we'll never accidentally go back and we'll know exactly which version each release was compiled with in case there is a hard to find bug later on.

Thoughts on this? It's a bit more maintenance. But lowering the number of variables one has to check prior to each release is also very desirable since there are too many parameters to get right when building a release today.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/74)*

**Comment by faern** [comment]
Cool. @pronebird Could you maybe push such a requirement in `packages.json` to this branch? If it's an easy fix I mean, better get it done asap. You probably know better than me how to do it and which version we should require.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/74#-:-L6Lon06r_hiRfR9bED6:b8c1kbh)*

**Comment by faern** [comment]
I merged this without waiting for that extra feature from @pronebird. Too many open threads and nothing happened, please add that check in a separate PR when given time.

**Comment by pronebird** [comment]
I haven't been here yesterday. I can add a version to package.json later.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/74#-:-L6WRUOm4QTht_3hi5QQ:b2es97t)*

**Pull request merged**
