### PR TITLE
Introduce new Routing framework for high level router and coordinator code

### PR DESCRIPTION
**Pull request by rablador**
Introduces new Routing framework for better UI separation, making it easier to write tests for routers and coordinators. 

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)* status: all files reviewed, 4 unresolved discussions (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNuEKs06Zw9uw2MXCd:-NcNuEKs06Zw9uw2MXCe:bi1eu6m) (no related file):*
Couple of suggestions:

1. Mullvad VPN: move everything from `Coordinators/App` into `Coordinators`. No need for nesting when `Coordinators/` only contains one folder.
2. `Routing/Router/AppRoutes.swift` is a part of `Mullvad VPN` and not a part of general solution/framework. So maybe we should keep in the app then.
3. Project settings Mullvad VPN > Info - please select "Base" configuration for Routing framework in both Debug and Release.
4. Routing > Build settings > PRODUCT_BUNDLE_IDENTIFIER please set it to `$(APPLICATION_IDENTIFIER).Routing`
5. Routing > Build settings > Deployment target IPHONE_OS_DEPLOYMENT_TARGET() - select and hit delete. The text should lose bold style but remain sayingg "iOS 14", which means it inherits deployment target  from project-wide settings.

Otherwise :lgtm: 

___
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 4626 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNynAOBV2JqQoPWE-v:-NcNynAOBV2JqQoPWE-w:b82sm1u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/MullvadVPN.xcodeproj/project.pbxproj#L4626)):*
> ```
> 				PRODUCT_NAME = "$(TARGET_NAME)";
> 				SWIFT_VERSION = 5.0;
> 				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/MullvadVPN.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/MullvadVPN";
> ```

Please reset test host under `MullvadVPNTests` to _None_ as we don't want to bootstrap our entire app to run isolated unit tests.
___
*[`ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNwToQ10XPbyf8Twuf:-NcNwToQ10XPbyf8Twug:b10u7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme#L56)):*
> ```
>             </BuildableReference>
>          </TestableReference>
>          <TestableReference
> ```

For some reason Routing tests were added under PacketTunnel schema. I don't think they need to be there.
___
*[`ios/Routing/Router/ApplicationRouter.swift` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNxF4LAB1ZDXllni8P:-NcNxF4M-Wf59hwg9ba5:bwn23qr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/Routing/Router/ApplicationRouter.swift#L139)):*
> ```Swift
>          */
>         if let lastRouteGroup = modalStack.last, route.routeGroup.isModal,
>            ((lastRouteGroup > route.routeGroup) || (route.isExclusive && lastRouteGroup == route.routeGroup)) {
> ```

FYI I took time to evaluate this in my head and think that's the better version of what I had. But in general, I think we should be re-modelling that `isExclusive`/`isModal` relationship and merging both groups and routes into a tree of routes. Just not now.
___
*[`ios/Routing/Router/AppRoutes.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNy21f8_-qjFGsGwTk:-NcNy21gB9CMPDvifjtc:bweluh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/Routing/Router/AppRoutes.swift#L15)):*
> ```Swift
>  inside with exception where primary navigation is a part of root controller on iPhone.
>  */
> public enum AppRouteGroup: AppRouteGroupProtocol {
> ```

This should go back into Mullvad VPN. It's app specific and does not concern router as it works with abstractions instead.

**Review by buggmagnet — APPROVED** [review]
This is fantastic, looking forward to see Routing having more tests !

:lgtm:

> Reviewed 20 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-:-NcRHIBF-390HRj6THUA:b2fwzg6)* status: 13 of 35 files reviewed, 7 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/RoutingTests/RoutingTests.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcRCAri-3IT5xEGIWoN:-NcRCAri-3IT5xEGIWoO:b-hkcets) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L13)):*
> ```Swift
> 
> final class RoutingTests: XCTestCase {
>     override func setUpWithError() throws {}
> ```

We can remove those overrides if we don't intend to use them
___
*[`ios/RoutingTests/RoutingTests.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcQv8qx-eI56efAA05A:-NcQv8qx-eI56efAA05B:b-rwduit) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L26)):*
> ```Swift
> }
> 
> // MARK: Horisontal flow tests
> ```

Horizontal, here and everywhere in this file
___
*[`ios/RoutingTests/RoutingTests.swift` line 117 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcRCmlk7WvrlZlTvXVx:-NcRCmlk7WvrlZlTvXVy:b-nnx6dj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L117)):*
> ```Swift
>     }
> 
>     func testShouldDropSameLevelModalRouteIfPreceededByExclusve() throws {
> ```

FYI
I really like these kind of names, where you can see the "why" and the "how".

If I compare it to one of the other tests `testPresentModalRoutesOfDifferentLevels` for example, it tells me what it does, but not why.

Also there is a typo in the test name `Exclusve` :smile: 
___
*[`ios/RoutingTests/RoutingTests.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcRFYYr6lcfEI4DiZyD:-NcRFYYr6lcfEI4DiZyE:btiayr8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L160)):*
> ```Swift
> }
> 
> class RouterBlockDelegate<RouteType: AppRouteProtocol>: ApplicationRouterDelegate {
> ```

IMHO This is big enough to warrant being in its own file

**Review by pronebird — COMMENTED** [review]
> Reviewed 17 of 19 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 4626 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNynAOBV2JqQoPWE-v:-NcR7D53AT8qpqrreBRv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/MullvadVPN.xcodeproj/project.pbxproj#L4626)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please reset test host under `MullvadVPNTests` to _None_ as we don't want to bootstrap our entire app to run isolated unit tests.
</blockquote></details>

Done.
___
*[`ios/RoutingTests/RoutingTests.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcRCAri-3IT5xEGIWoN:-NcSkC2j0VP0Aaq1iOKA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can remove those overrides if we don't intend to use them
</blockquote></details>

Done.
___
*[`ios/RoutingTests/RoutingTests.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcQv8qx-eI56efAA05A:-NcSkVeq3BH5bXxrTvMG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L26)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Horizontal, here and everywhere in this file
</blockquote></details>

Done.
___
*[`ios/RoutingTests/RoutingTests.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcRFYYr6lcfEI4DiZyD:-NcSl-mT6E3vWhGTtJVM:bwhgldf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/RoutingTests/RoutingTests.swift#L160)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

IMHO This is big enough to warrant being in its own file
</blockquote></details>

Moved!
___
*[`ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNwToQ10XPbyf8Twuf:-NcR6Vv0BMisyd13RTeb:b-d2wyu3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme#L56)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

For some reason Routing tests were added under PacketTunnel schema. I don't think they need to be there.
</blockquote></details>

No idea how they ended up here, but will remove.
___
*[`ios/Routing/Router/AppRoutes.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcNy21f8_-qjFGsGwTk:-NcR6jN7B_UNfS1yHI3m:bnf6nsh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689ad1c0b68a7975592198809f20135d37512a51/ios/Routing/Router/AppRoutes.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This should go back into Mullvad VPN. It's app specific and does not concern router as it works with abstractions instead.
</blockquote></details>

Indeed, will move it back.

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 6 of 35 files at r1, 17 of 19 files at r2, 2 of 5 files at r3, 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)* status: 33 of 36 files reviewed, 2 unresolved discussions (waiting on @pronebird and @rablador)

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)* status: 22 of 38 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/RoutingTests/RoutingTests.swift` line 114 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-NcXiyQS38h4gRXjDkJj:-NcXiyQS38h4gRXjDkJk:bq2bx78) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5654bb9fb05eba85acc7a68d9282632baddd6b4f/ios/RoutingTests/RoutingTests.swift#L114)):*
> ```Swift
>     }
> 
>     func testShouldDropSameLevelModalRouteIfPreceededByExclusive() throws {
> ```

the function name should be  `testShouldDropSameLevelModalRouteIfProceededByExclusive`

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031#-:-NcXkznZ25r2GfQhVzE8:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5031)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

**Pull request merged**
