### PR TITLE
Use optional modifier for scalars in protobuf

### PR DESCRIPTION
**Pull request by dlon**
Instead of mapping default values of strings and integers to 0/"", we can just set them to optional. `optional` was reintroduced in protobuf 3.15.

Closes DES-367.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5191)

### CODE REVIEW

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

Soo good! Looking forward to the day we can nuke `option_from_proto_string` :rocket: 

> Reviewed 5 of 9 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5191#-:-NgXm-6X5ysS3i75_EyP:b-br6fbw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5191)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:raised_hands: 

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5191#-:-Ngbrde50M6XL-R9qleW:b-j1we20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5191)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
