### PR TITLE
Update translations for 2024.9

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7313)

### CODE REVIEW

**Comment by hulthe** [comment]
@Rawa would appreciate it if you could sanity-check the android stuff :)

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 76 of 76 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7313#-:-OEZd6BnBLlW9nxhx7GL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7313#-:-OEo_iX43m0qQ0n2OxA1:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7313)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
