### PR TITLE
fix some linting violations

### PR DESCRIPTION
**Pull request by mojganii**
This PR addresses several SwiftLint violations.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-NcwSudHEBMp_h6Np87P:b-c21bii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
> ```Swift
>             tableName: "Account",
>             value: """
>             This is the name assigned to the device. Each device logged in on a Mullvad account gets a unique name \
> ```

Back slash?
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwX4Zh6-HT4eEAOZdP:-NcwX4Zh6-HT4eEAOZdQ:b-er40vv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L123)):*
> ```Swift
> 
>         addConstrainedSubviews([contentStackView, buttonStackView]) {
>             contentStackView.topAnchor.constraint(equalTo: layoutMarginsGuide.topAnchor)
> ```

I we adopt the `addConstrainedSubviews` function we might as well adopt the builder functions as well, eg. `pinEdges` etc.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/Shared/ApplicationTarget.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-Ncwg9P42rgPa6CtSpfS:-Ncwg9P42rgPa6CtSpfT:b-cs42ru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/Shared/ApplicationTarget.swift#L18)):*
> ```Swift
>         let key = "MainApplicationIdentifier"
>         guard let mainBundleIdentifier = Bundle.main.object(forInfoDictionaryKey: key) as? String else {
>             assertionFailure("Unexpected value for : \(key)")
> ```

There is nothing to assert, it must crash if it cannot extract that value. There is no recovery from that. Returning empty string is meaningless and would likely break something somewhere else.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-Ncwh2sA2EZqB5K2XY9t:-Ncwh2sA2EZqB5K2XY9u:brhumzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/Shared/ApplicationConfiguration.swift#L16)):*
> ```Swift
>     static var securityGroupIdentifier: String {
>         let key = "ApplicationSecurityGroupIdentifier"
>         guard let value = Bundle.main.object(forInfoDictionaryKey: key) as? String else {
> ```

Same here.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-Nd-LHMv-RM0_Mm8PWB9:bkk3g83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Back slash?
</blockquote></details>

It seems that in multiline literal a line break is a line break, so Mojgan had to use backslash to keep things on the same line.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: 15 of 22 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-Nd-OVLYCOQWVaTP0KBi:bb7s9mg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It seems that in multiline literal a line break is a line break, so Mojgan had to use backslash to keep things on the same line.
</blockquote></details>

yeah
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwX4Zh6-HT4eEAOZdP:-Nd-WntSCWzmPfhgb4Q6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L123)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I we adopt the `addConstrainedSubviews` function we might as well adopt the builder functions as well, eg. `pinEdges` etc.
</blockquote></details>

Done.
___
*[`ios/Shared/ApplicationConfiguration.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-Ncwh2sA2EZqB5K2XY9t:-Nd-PP4XCtfo_3hizTrB:bs7wub4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/Shared/ApplicationConfiguration.swift#L16)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done!
___
*[`ios/Shared/ApplicationTarget.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-Ncwg9P42rgPa6CtSpfS:-Nd-OmEv7cwqrvAa8WmY:bmfxfve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/Shared/ApplicationTarget.swift#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

There is nothing to assert, it must crash if it cannot extract that value. There is no recovery from that. Returning empty string is meaningless and would likely break something somewhere else.
</blockquote></details>

Done!

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-Nd-z2pqEE-LYv1DPEUb:byge6xc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

yeah
</blockquote></details>

Thought it looked weird, so I tried it myself and I can get everthing on one line with no slashes 🤷‍♂️

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-Nd02qdJAFPE5JCk8MIc:b-czt8b8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Thought it looked weird, so I tried it myself and I can get everthing on one line with no slashes 🤷‍♂️
</blockquote></details>

it breaks the line length linting rule.do you have a better solution to break hardcoded string into several lines without newlines and without exceeding line columns ?

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-Nd04HOW-Su9Iwg83GLp:bwq37st) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it breaks the line length linting rule.do you have a better solution to break hardcoded string into several lines without newlines and without exceeding line columns ?
</blockquote></details>

when we use """ """, it keeps the format we aim to have in UI in paragraph and so on

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/AccountCoordinator.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-NcwSudHEBMp_h6Np87O:-Nd083J5-Z6LCw0kSQyF:b-7vrk3j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c3a2105e137965d3df36a4c7c41c64014336e80f/ios/MullvadVPN/Coordinators/AccountCoordinator.swift#L160)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

when we use """ """, it keeps the format we aim to have in UI in paragraph and so on
</blockquote></details>

Hmm, I tried again, simply breaking with no slashes, but this time it didn't work as intended. 🫠 Let's keep your impl, it looks fine. :)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/Shared/ApplicationTarget.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-Nd0HB_xAYrhNHve3Lep:-Nd0HB_xAYrhNHve3Leq:b-6876lq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c75c9ae771bed1f1f4f757dde5a787d9f4ecf97f/ios/Shared/ApplicationTarget.swift#L16)):*
> ```Swift
>     /// Returns target bundle identifier.
>     var bundleIdentifier: String {
>         let key = "MainApplicationIdentifier"
> ```

Can you please put the constant back the way it was without intermediate variable.

**Review by pronebird — COMMENTED** [review]
> Dismissed @rablador from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: 20 of 22 files reviewed, all discussions resolved (waiting on @rablador)

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 22 files at r1, 1 of 7 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/Account/AccountExpiryRow.swift` line 85 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5056#-Nd0VNAW5lmkNRa-Kc9Y:-Nd0VNAW5lmkNRa-Kc9Z:bz6uzyp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe27d80236374922f050d3b3b71e616aa3195924/ios/MullvadVPN/View%20controllers/Account/AccountExpiryRow.swift#L85)):*
> ```Swift
>                 greaterThanOrEqualTo: activityIndicator.leadingAnchor,
>                 constant: -UIMetrics.padding8
>             )
> ```

Would this work instead?
`textLabel.trailingAnchor.constraint(equalToSystemSpacingAfter: activityIndicator.leadingAnchor, multiplier: -1)`
Or perhaps we should just swap the anhors.

**Pull request merged**
