### PR TITLE
Make bottomsheets into destinations

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476)* status: 0 of 19 files reviewed, 1 unresolved discussion

___
*[`android/app/build.gradle.kts` line 386 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O23w0GD9bJkSFg5iU8c:-O23w0GD9bJkSFg5iU8d:b2tkck8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/build.gradle.kts#L386)):*
> ```Kotlin
> configurations.all {
>     resolutionStrategy {
>         force("androidx.navigation:navigation-compose:2.8.0-beta05")
> ```

Should be removed before any merge

**Review by Pururun — COMMENTED** [review]
Removing and adding locations to the list does not seems to trigger a toast with an undo. As far as I can tell the required code for that is missing?

Otherwise nice work :+1: 

> Reviewed 13 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-:-O24E7mkELIw3gx2UOxM:b-n1aa4)* status: 13 of 19 files reviewed, 9 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MullvadModalBottomSheet.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24Cpqj1Sa-5r0SYzC_:-O24CpqkAx1islY1ZG_D:btmqrsd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MullvadModalBottomSheet.kt#L43)):*
> ```Kotlin
> @OptIn(ExperimentalMaterial3Api::class)
> @Composable
> fun MullvadModalBottomSheet(sheetContent: @Composable ColumnScope.() -> Unit) {
> ```

Since this is not a bottom sheet anymore, this should called `MullbadBottomSheetContent` or something
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24Dfx_7Eilsd4kn3_D:-O24Dfx_7Eilsd4kn3_E:b72k8y5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt#L19)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.viewmodel.CustomListEntrySheetSideEffect.GenericError
> 
> data class CustomListEntrySheetUiState(
> ```

Not sure if it is universal but ui states are usually in it's own file?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DbXDELeIqFsGHZJr:-O24DbXDELeIqFsGHZJs:b-v61bjd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt#L23)):*
> ```Kotlin
> )
> 
> sealed interface CustomListEntrySheetSideEffect {
> ```

Side effects are usually at the bottom?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DmIO7JVRLK7mfAaz:-O24DmIO7JVRLK7mfAb-:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt#L13)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.CustomListName
> 
> data class CustomListSheetUiState(
> ```

See above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24Dn5Q9R_cetOkc8cg:-O24Dn5Q9R_cetOkc8ch:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt#L18)):*
> ```Kotlin
> )
> 
> sealed interface CustomListSheetSideEffect {
> ```

See above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ImportOverridesViewModel.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DpoD5bjv7JiLiG-A:-O24DpoD5bjv7JiLiG-B:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ImportOverridesViewModel.kt#L10)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.repository.RelayOverridesRepository
> 
> data class ImportOverridesSheetUiState(val overridesActive: Boolean)
> ```

See above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DruO96I7JBdKd5Dd:-O24DruO96I7JBdKd5De:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt#L24)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.usecase.customlists.CustomListsRelayItemUseCase
> 
> sealed interface LocationUiState {
> ```

See above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DtDK1quuaNT27mbj:-O24DtDK1quuaNT27mbk:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt#L37)):*
> ```Kotlin
> data class CustomListEntry(val customList: RelayItem.CustomList, val canAdd: Boolean)
> 
> sealed interface LocationSideEffect {
> ```

See above

**Review by Rawa — COMMENTED** [review]
Ah, this was a small mistake on my end, I've fixed it now :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-:-O28yXXyAJZDMV0dACud:brb32w)* status: 8 of 23 files reviewed, 9 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24Dfx_7Eilsd4kn3_D:-O28uB0J144br1oYwRQM:b2mr1p6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt#L19)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Not sure if it is universal but ui states are usually in it's own file?
</blockquote></details>

Yeah it should. Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DbXDELeIqFsGHZJr:-O28uV_v07NwTBdZkO_7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListEntrySheetViewModel.kt#L23)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Side effects are usually at the bottom?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DmIO7JVRLK7mfAaz:-O28vLfC7vbwSVUIhhf9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt#L13)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24Dn5Q9R_cetOkc8cg:-O28vLvU52ctKugP-gW1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListSheetViewModel.kt#L18)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DruO96I7JBdKd5Dd:-O28vfz084TkZUu87IMl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt#L24)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DtDK1quuaNT27mbj:-O28vgQ-0r-75MadU-FR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LocationSheetViewModel.kt#L37)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MullvadModalBottomSheet.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24Cpqj1Sa-5r0SYzC_:-O28u84rBBbDiLLutJvZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MullvadModalBottomSheet.kt#L43)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Since this is not a bottom sheet anymore, this should called `MullbadBottomSheetContent` or something
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ImportOverridesViewModel.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-O24DpoD5bjv7JiLiG-A:-O28vRdE3HUzC4gq_n_8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3461670d7c14885cf308b14756647e7970bbb608/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ImportOverridesViewModel.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-:-O29N7b0EOgJO6C2pwp4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6476#-:-O2PBblD-IC_h2zLCC70:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request closed without merging**
