### PR TITLE
Implement daemon support for split tunneling for Android

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR implements daemon support for split tunneling on Android.

The list of excluded apps is now handled by the daemon. The list of excluded apps is provided to the Android client via `TunConfig`, which has been updated slightly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 18 of 18 files at r2, 18 of 18 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-:-NwKPFk30DDXx8s2fZzr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-:-NwKTa9357p9cp5TYEuV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-types/src/settings/mod.rs` line 128 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwKRecW0mVBOqttL5Bb:-NwKRecW0mVBOqttL5Bc:bt6dfej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab17b2a8c55efb3e293b545095f2b12adebbc14b/mullvad-types/src/settings/mod.rs#L128)):*
> ```XML
>     /// # Note
>     /// This function is fallible due to the Window's dito being fallible, and it is convenient to have the same API across all platforms.
>     #[cfg(target_os = "android")]
> ```

Nit: Should we use two impl blocks since there's no overlap?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @dlon and @Pururun)

___
*[`mullvad-types/src/settings/mod.rs` line 128 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwKRecW0mVBOqttL5Bb:-NwKXOuPDYiQQGhXGbX-:bk9petg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab17b2a8c55efb3e293b545095f2b12adebbc14b/mullvad-types/src/settings/mod.rs#L128)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Should we use two impl blocks since there's no overlap?
</blockquote></details>

Yes, that's a lot nicer! Thanks :smile:

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-:-Nwd8TIK1v5ECVMbNeg6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/migrations/mod.rs` line 205 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdSUQ58xumbHsc002o:-NwdSUQ58xumbHsc002p:bi7fw20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/mod.rs#L205)):*
> ```XML
>         settings,
>         #[cfg(target_os = "android")]
>         directories.map(|directories| v9::Directories {
> ```

Feels a bit excessive to define `v9::Directories` instead of just passing in `Option<Directories>` (or `Option<&Path>`).
___
*[`mullvad-daemon/src/migrations/v9.rs` line 34 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdV40DC7zhPPI3iBI8:-NwdV40DC7zhPPI3iBI9:bi3w77q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L34)):*
> ```XML
> // ======================================================
> 
> /// This is an open migration
> ```

This isn't the case at the moment (but maybe it should be).
___
*[`mullvad-daemon/src/migrations/v9.rs` line 67 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdRCcJAedGTWWZ7Nq0:-NwdRCcK1RhNJ0_Xq1aI:b441bx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L67)):*
> ```XML
>     }
> 
>     json_blob["settings_version"] = serde_json::json!(SettingsVersion::V10);
> ```

I suspect that we do not need to bump the version yet. Could we not just migrate the old settings whenever the new settings don't exist (and the old files do) and leave this as an "open" migration?
___
*[`mullvad-daemon/src/migrations/v9.rs` line 97 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdRNet5Im8AdNAcVp6:-NwdRNeu1TzEgsTjPHtt:b99wa5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L97)):*
> ```XML
> /// Read the existing split-tunneling settings which the Android client has kept track off and
> /// write them to the settings object.
> #[cfg(target_os = "android")]
> ```

Would it be cleaner to move these into `mod android { ... }`?
___
*[`mullvad-daemon/src/migrations/v9.rs` line 129 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdTiKYC1h55mKVmRxi:-NwdTiKYC1h55mKVmRxj:b4mazqb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L129)):*
> ```XML
>     ensure_split_tunnel_subkey(settings);
>     // Store the read split tunnel state in the daemon's settings
>     settings["split_tunnel"] = json!({ "enable_exclusions": enabled, "apps": apps });
> ```

You can probably get rid of `ensure_split_tunnel_subkey` by replacing this with something like

```
settings.insert("split_tunnel".to_string(), serde_json::Value::Object(json!( ... )));
```

or

```
settings.insert("split_tunnel".to_string(), json!( ... ).into());
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/migrations/mod.rs` line 205 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdSUQ58xumbHsc002o:-NwdWEbT88MzIAcITsMe:b-8zzitz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/mod.rs#L205)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Feels a bit excessive to define `v9::Directories` instead of just passing in `Option<Directories>` (or `Option<&Path>`).
</blockquote></details>

We can't pass in `Directories`, as that would imply a cyclical dependency between `v9.rs` and `mod.rs`. Also, we should be able to modify `Directories` without potentially breaking the migration defined in `v9.rs` :blush:

I don't have a strong opinion on whether to pass down `settings_dir: Option<&Path>` or `directories: Option<Directories>`, but the latter is a bit more explicit at the call site imho. The best thing would probably be to accept `impl Into<V9::Directories>`, but I didn't care enough to implement `From<Directories> for <V9::Directories>` :blush:
___
*[`mullvad-daemon/src/migrations/v9.rs` line 34 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdV40DC7zhPPI3iBI8:-Nwdfn5j05zPvpGUiCQx:b-fkkgff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L34)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This isn't the case at the moment (but maybe it should be).
</blockquote></details>

As stated in another comment: It is probably nice to keep this migration open for now - updated the code to allow us to support that properly :blush:
___
*[`mullvad-daemon/src/migrations/v9.rs` line 67 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdRCcJAedGTWWZ7Nq0:-Nwd_7Uq4RxpycSG8YJm:blbt55s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L67)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I suspect that we do not need to bump the version yet. Could we not just migrate the old settings whenever the new settings don't exist (and the old files do) and leave this as an "open" migration?
</blockquote></details>

Sure, I'm open to keep this migration open :wink:
___
*[`mullvad-daemon/src/migrations/v9.rs` line 97 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdRNet5Im8AdNAcVp6:-Nwdb9L0EhMjwsLNo4x1:b-3lyy78) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L97)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Would it be cleaner to move these into `mod android { ... }`?
</blockquote></details>

Maybe, lot's of `#[cfg(..)]`action going on atm :sweat_smile:

I went ahead and did it :blush:
___
*[`mullvad-daemon/src/migrations/v9.rs` line 129 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdTiKYC1h55mKVmRxi:-Nwdfguf5jt2sOT6Ujkt:bgocdpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L129)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You can probably get rid of `ensure_split_tunnel_subkey` by replacing this with something like

```
settings.insert("split_tunnel".to_string(), serde_json::Value::Object(json!( ... )));
```

or

```
settings.insert("split_tunnel".to_string(), json!( ... ).into());
```
</blockquote></details>

Got rid of `ensure_split_tunnel_key` and simply used `settings.insert` :blush:

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/migrations/mod.rs` line 205 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdSUQ58xumbHsc002o:-NwdlVHm8q-XU3KAwiV9:byo5k4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/mod.rs#L205)):*
> we should be able to modify `Directories` without potentially breaking the migration defined in `v9.rs` 😊

Fair enough!

> the latter is a bit more explicit at the call site imho

Is the parameter name not explicit enough, though? Anyway, this isn't important, so merge away.
___
*[`mullvad-daemon/src/migrations/v9.rs` line 67 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6182#-NwdRCcJAedGTWWZ7Nq0:-NwdkvrN4t8SKaOU8LRb:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b81debf3e91c01b95ac94d59220eea7615da7d/mullvad-daemon/src/migrations/v9.rs#L67)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Sure, I'm open to keep this migration open :wink:
</blockquote></details>

Nice!

**Comment by MarkusPettersson98** [comment]
Closing this PR - the has been cherry-picked into the base branch! :shipit:

**Pull request closed without merging**
