### PR TITLE
Fix problem reports not being kept correctly

### PR DESCRIPTION
**Pull request by Pururun**
Also restore secure view behaviour for Send report problem success screen.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457)

### CODE REVIEW

**Review by sabercodic — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457)* status: 6 of 7 files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457#-:-NjSJKJC2768UU4WkoRq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457#-NjSJSefERnL85UgwbAg:-NjSY4Hd4ikVHsLPRr8U:b-3nxquw) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps we should clear the input on logout? I'm not sure how it worked before :thinking:
</blockquote></details>

As mentioned offline, I suggest we keep the behavior we had before the regression was introduced.

___

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457#-NjSJSefERnL85UgwbAg:-NjSfP7oDKByXtBMZk_w:b-2avcky) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As mentioned offline, I suggest we keep the behavior we had before the regression was introduced.
</blockquote></details>

Test on current production and email and message was not deleted if the user logged out, so we have the same behaviour as before.

___

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457#-:-NjShSMd88CzQPZrwQFN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457#-:-NjSknv27uFmUi6YvTVo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
