### PR TITLE
Work around non-existent 'ComponentId' registry value

### PR DESCRIPTION
**Pull request by dlon**
When creating a Wintun device, a couple of registry values belonging to the device are not initialized on some machines. Most importantly `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\<DEVICE>\ComponentId`. This is presumably due to a bug in either Windows or Wintun.

While `wireguard-go` ignores this registry value, OpenVPN uses it to determine whether a particular network device is a tunnel device. As a result, connecting using OpenVPN fails. Beyond that, though, it doesn't appear to be crucial. This patch simply creates the registry value if it does not exist.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)

### CODE REVIEW

**Review by mvd-ows — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 734 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338#-MO2xZGK5Arvs_50YLpp:-MO2xZGK5Arvs_50YLpq:bio6ydi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6f15da118dd8f438745dbc3b8a52c67d2caa29f/talpid-core/src/tunnel/openvpn/mod.rs#L734)):*
> ```Rust
>         #[cfg(windows)]
>         {
>             // cmd.tunnel_alias(Some(OsString::from(*ADAPTER_GUID_STR)));
> ```

Is this commented statement needed?
___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 262 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338#-MO2xvq1DgWt3dayaP78:-MO2xvq1DgWt3dayaP79:byf7ymv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6f15da118dd8f438745dbc3b8a52c67d2caa29f/talpid-core/src/tunnel/openvpn/windows.rs#L262)):*
> ```Rust
> pub fn find_adapter_registry_key(find_guid: &str, permissions: REGSAM) -> io::Result<RegKey> {
>     let net_devs = RegKey::predef(HKEY_LOCAL_MACHINE).open_subkey_with_flags(
>         r"SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}",
> ```

What is this GUID? Recall that the hack that forces a specific GUID for the virtual adapter doesn't work on Win7.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 734 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338#-MO2xZGK5Arvs_50YLpp:-MO5zW9b4Cu2XvlSYJ5C:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6f15da118dd8f438745dbc3b8a52c67d2caa29f/talpid-core/src/tunnel/openvpn/mod.rs#L734)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Is this commented statement needed?
</blockquote></details>

Removed.
___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 262 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338#-MO2xvq1DgWt3dayaP78:-MO5zYgv-N4fylSByPZZ:b2gxmbm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6f15da118dd8f438745dbc3b8a52c67d2caa29f/talpid-core/src/tunnel/openvpn/windows.rs#L262)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What is this GUID? Recall that the hack that forces a specific GUID for the virtual adapter doesn't work on Win7.
</blockquote></details>

If you're referring to the hardcoded GUID, it belongs to the device class (i.e., network adapters).

Good reminder about Windows 7. It doesn't seem like the problem  occurs when the GUID hack is not used, which is why it didn't happen before the switch to a fixed GUID. Or perhaps it occurs but only randomly.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 257 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338#-MO60dEd8bMgYhdlduEq:-MO60dEd8bMgYhdlduEr:b-y4tpee) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba4608f5bbfe9ec06f8e52d339bff277640cc5fb/talpid-core/src/tunnel/openvpn/windows.rs#L257)):*
> ```Rust
>     let length = unsafe { StringFromGUID2(guid, &mut buffer[0] as *mut _, buffer.len() as i32 - 1) }
>         as usize;
>     let length = std::cmp::max(0, length - 1);
> ```

I'm not sure what `usize(0) - 1` results in.

But regardless, the logic could specifically handle the single failure case separately (length == 0).

Then if it's not a failure, you can unconditionally subtract 1.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 257 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338#-MO60dEd8bMgYhdlduEq:-MO67HwBEXMfeuBp7b-R:b-9itbj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba4608f5bbfe9ec06f8e52d339bff277640cc5fb/talpid-core/src/tunnel/openvpn/windows.rs#L257)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I'm not sure what `usize(0) - 1` results in.

But regardless, the logic could specifically handle the single failure case separately (length == 0).

Then if it's not a failure, you can unconditionally subtract 1.
</blockquote></details>

Good point. Fixed, although this should never fail.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
