### PR TITLE
Add more tests to FDA check

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR touches up the FDA check code just a little bit more to ensure that no obvious bugs are still present.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 616 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338#-OE-qF2u9Kc7GMI3pd4X:-OE-qF2u9Kc7GMI3pd4Y:b7bdc8o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f82adab82d2d7355e48a84fd8a71069a30ef2e/talpid-core/src/split_tunnel/macos/process.rs#L616)):*
> ```XML
>     #[tokio::test]
>     async fn test_parse_logger_status_timeout() {
>         let need_fda = parse_logger_status(
> ```

This test doesn't seem to test any time out now (since it immediately prints to stdout/stderr). It is identical to `test_parse_logger_status_immediate_exit`.

Would something like make more sense?

```
        let stdout = output("This will never be printed\n", Duration::MAX);
        let stderr = output(
            "ES_NEW_CLIENT_RESULT_ERR_NOT_PERMITTED\n",
            EARLY_FAIL_TIMEOUT + Duration::from_secs(1),
        );
```

Though I'm not sure if it's particularly valuable given that it's just a special case of `test_parse_logger_status_hogged`. Removing it might be fine?
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 657 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338#-OE-smPA22Z-wDGyaqzT:-OE-smPA22Z-wDGyaqzU:by44dfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f82adab82d2d7355e48a84fd8a71069a30ef2e/talpid-core/src/split_tunnel/macos/process.rs#L657)):*
> ```XML
>             EARLY_FAIL_TIMEOUT / 2,
>         );
>         tokio::time::resume();
> ```

Are `start` and `resume` necessary here? I think it should just work if you only set the `start_paused` attribute: `#[tokio::test(start_paused = true)]`

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 616 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338#-OE-qF2u9Kc7GMI3pd4X:-OE07TLnEjbEluRoXVaO:buk169z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f82adab82d2d7355e48a84fd8a71069a30ef2e/talpid-core/src/split_tunnel/macos/process.rs#L616)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This test doesn't seem to test any time out now (since it immediately prints to stdout/stderr). It is identical to `test_parse_logger_status_immediate_exit`.

Would something like make more sense?

```
        let stdout = output("This will never be printed\n", Duration::MAX);
        let stderr = output(
            "ES_NEW_CLIENT_RESULT_ERR_NOT_PERMITTED\n",
            EARLY_FAIL_TIMEOUT + Duration::from_secs(1),
        );
```

Though I'm not sure if it's particularly valuable given that it's just a special case of `test_parse_logger_status_hogged`. Removing it might be fine?
</blockquote></details>

It is a special case of `test_parse_logger_status_hogged`, so I think we can simply remove this one. Renaming it to `test_parse_logger_status_timeout` though :blush:
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 657 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338#-OE-smPA22Z-wDGyaqzT:-OE0827T6eenrrvFOHNw:b-wbzlxf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f82adab82d2d7355e48a84fd8a71069a30ef2e/talpid-core/src/split_tunnel/macos/process.rs#L657)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are `start` and `resume` necessary here? I think it should just work if you only set the `start_paused` attribute: `#[tokio::test(start_paused = true)]`
</blockquote></details>

We can get rid of `start` in favor of `#[tokio::test(start_paused = true)]`, but `resume` seems relevant to me because time should not be frozen during the subsequent call to `parse_logger_status`. Maybe I understand the `tokio::time` test utils wrong tho

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 657 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338#-OE-smPA22Z-wDGyaqzT:-OEDnvZO3Gb_OyExZP4b:bq51n7v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f82adab82d2d7355e48a84fd8a71069a30ef2e/talpid-core/src/split_tunnel/macos/process.rs#L657)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

We can get rid of `start` in favor of `#[tokio::test(start_paused = true)]`, but `resume` seems relevant to me because time should not be frozen during the subsequent call to `parse_logger_status`. Maybe I understand the `tokio::time` test utils wrong tho
</blockquote></details>

It automatically advances timers when there's no other work to do. Maybe that's less correct here?

**Pull request merged**
