### PR TITLE
Create gui-settings file on launch if it doesn't already exist

### PR DESCRIPTION
**Pull request by raksooo**
This PR makes the `GuiSettings.load()` call check whether or not the settings file exist before loading it, and if it doesn't it creates the file with the default settings.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/gui-settings.ts, line 87 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400#-MRUszCQBot9DYWiKwwJ:-MRUszCRB3idd3NTgqsv:b9d67uo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9935293a3702f76a353cc474e79e8810968676a2/gui/src/main/gui-settings.ts#L87)):*
> ```XML
> 
>     // Read settings if the file exists, otherwise write the default settings to it.
>     if (fileExistsSync(settingsFile)) {
> ```

It would be simpler to catch the error and check if the error.code == 'ENOENT' or 'EPERM' depending if we think the file is not accessible by the process. That would eliminate the need for addition check for existence of file.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/gui-settings.ts, line 87 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400#-MRUszCQBot9DYWiKwwJ:-MRUttSn-Ah83d6QmiwF:b-oeeumj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9935293a3702f76a353cc474e79e8810968676a2/gui/src/main/gui-settings.ts#L87)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It would be simpler to catch the error and check if the error.code == 'ENOENT' or 'EPERM' depending if we think the file is not accessible by the process. That would eliminate the need for addition check for existence of file.
</blockquote></details>

Just give a little more context: `fs.readFileSync` should throw an error if it can't read the file.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/gui-settings.ts, line 87 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400#-MRUszCQBot9DYWiKwwJ:-MRUykyq9Wrh2nTNFJNb:bitax77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9935293a3702f76a353cc474e79e8810968676a2/gui/src/main/gui-settings.ts#L87)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Just give a little more context: `fs.readFileSync` should throw an error if it can't read the file.
</blockquote></details>

Yes that works. Fixed.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
