### PR TITLE
Add functions to and update the route manager in winnet

### PR DESCRIPTION
**Pull request by dlon**
These new functions and route manager updates will be used to inform the split tunneling driver of what interface provides Internet access.

### Changes

* Export a function to obtain the best default route.
* Add a function to obtain the IP address given an interface and address family.
* Update the route monitor to identify the default route correctly when using OpenVPN. (As the daemon stands, this is not a bug because the route manager is not being used in this case yet.)
* Minor fix to the offline monitor for the TAP adapter: It wasn't properly identified as a virtual adapter. This was apparently caught by the other checks, though.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115)

### CODE REVIEW

**Review by mvd-ows — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/winnet.rs, line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFnljv7TzuQ1jd9Qiu:-MHFnljv7TzuQ1jd9Qiv:b-vexpow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/winnet.rs#L179)):*
> ```Rust
> pub struct WinNetDefaultRoute {
>     pub interface_luid: u64,
>     pub gateway: WinNetIp,
> ```

This is preferred to using `Option<WinNetIp>`, right? Because with `Option<>` you could have an instance which is all zeroes...
___
*[talpid-core/src/winnet.rs, line 460 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFpTMM1d3jJTq6xAFN:-MHFpTMM1d3jJTq6xAFO:by78lge) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/winnet.rs#L460)):*
> ```Rust
>     #[allow(dead_code)]
>     #[repr(u32)]
>     pub enum FailableOptionalStatus {
> ```

It's `Fallible`.

What does `Optional` signify?
___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 194 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFpqke-ZofgT3qYJVt:-MHFpqke-ZofgT3qYJVu:b-776hnh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L194)):*
> ```Rust
> 
>         wgRebindTunnelSocket(
>             default_route.gateway.addr_family.to_windows_proto_enum(),
> ```

This seems wrong. Is gateway sourced from "next hop"?

If so, the code is wrong because you can't bind the socket to an IP on another machine.

If not, gateway is not the correct term?
___
*[windows/winnet/src/winnet/converters.cpp, line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFqNnV7qAmDfNWsVFG:-MHFqNnV7qAmDfNWsVFH:btmp0gs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/converters.cpp#L48)):*
> ```cpp
> 		case AF_INET:
> 		{
> 			memcpy(to.bytes, &from.Ipv4.sin_addr.s_addr, sizeof(from.Ipv4.sin_addr.s_addr));
> ```

It would be more prudent to either assign the 32-bit value directly, or `memcpy` from/to a 4-byte array.
___
*[windows/winnet/src/winnet/offlinemonitor.cpp, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFrttuEjL7Mxf1QxXp:-MHFrttuEjL7Mxf1QxXq:b-mmx23p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/offlinemonitor.cpp#L19)):*
> ```cpp
> 		case IF_TYPE_SOFTWARE_LOOPBACK:
> 		case IF_TYPE_TUNNEL:
> 		case IF_TYPE_PROP_VIRTUAL:
> ```

This is a massive can of worms. It's plausible that a virtual network interface could communicate with another non-network device to provide Internet connectivity.

E.g. tethering via Bluetooth comes to mind.

If the updated code depends on this change, I suggest it's tested with a few Bluetooth devices and WLAN USB devices.
___
*[windows/winnet/src/winnet/winnet.h, line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFt7JVDb8KRox0GMa3:-MHFt7JVDb8KRox0GMa4:byahnuj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L183)):*
> ```objc
> );
> 
> typedef struct tag_WINNET_DEFAULT_ROUTE
> ```

Is this the best route over-all or the best non-tunnel route? A comment or name change could be used to clarify.
___
*[windows/winnet/src/winnet/winnet.h, line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFsxo-BQTRvRR84PzS:-MHFsxo-BQTRvRR84PzT:b-ui72lh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L190)):*
> ```objc
> WINNET_DEFAULT_ROUTE;
> 
> enum WINNET_GBDR_STATUS
> ```

IIRC, we consolidated these duplicated types into a general enumeration?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115)* status: 4 of 10 files reviewed, 6 unresolved discussions (waiting on @mvd-ows)

___
*[talpid-core/src/winnet.rs, line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFnljv7TzuQ1jd9Qiu:-MHGmAZv9ERvWC7d9wc2:b3jg69t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/winnet.rs#L179)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is preferred to using `Option<WinNetIp>`, right? Because with `Option<>` you could have an instance which is all zeroes...
</blockquote></details>

All zeroes is the same as there being no gateway. This is directly used in C, so I'm not sure using `Option<T>` would be correct, and I think this is better than returning a pointer.
___
*[talpid-core/src/winnet.rs, line 460 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFpTMM1d3jJTq6xAFN:-MHFz7QiDKytqcGs5cKI:balg9wx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/winnet.rs#L460)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

It's `Fallible`.

What does `Optional` signify?
</blockquote></details>

Optional signifies that the function doesn't necessarily return a value (i.e., `NotFound`). I've renamed this.
___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 194 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFpqke-ZofgT3qYJVt:-MHFz_2m3lX25s297XDN:b2gf3vd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L194)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This seems wrong. Is gateway sourced from "next hop"?

If so, the code is wrong because you can't bind the socket to an IP on another machine.

If not, gateway is not the correct term?
</blockquote></details>

It only used this to determine the address family, because they are necessarily the same (correct me if I'm wrong). `iface_idx` was the interface that was used. Confusingly, I set the family for the gateway even if the gateway itself was not set, so I've updated it anyway.
___
*[windows/winnet/src/winnet/offlinemonitor.cpp, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFrttuEjL7Mxf1QxXp:-MHFyuwF1Id-L2UN_KUd:bfqpmzf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/offlinemonitor.cpp#L19)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is a massive can of worms. It's plausible that a virtual network interface could communicate with another non-network device to provide Internet connectivity.

E.g. tethering via Bluetooth comes to mind.

If the updated code depends on this change, I suggest it's tested with a few Bluetooth devices and WLAN USB devices.
</blockquote></details>

For now, I'm leaving this unchanged due to the various caveats. If the check I've added to the route manager is broken, it will likely only break for OpenVPN, and operate in the same way as before when using WireGuard (because the route has no gateway). At some point, this function could be shared with the `GetBestDefaultRoute`.
___
*[windows/winnet/src/winnet/winnet.h, line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFt7JVDb8KRox0GMa3:-MHFyjncDQR0VoK6fDrQ:btg8tr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L183)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Is this the best route over-all or the best non-tunnel route? A comment or name change could be used to clarify.
</blockquote></details>

Non-tunnel route, but you're not wrong. We use the term like this elsewhere in the app--e.g., the route manager (on Linux and Windows) is supposed to ignore tunnel routes, but "default route" implicitly refers to "non-tunnel route"--so I've not renamed it for the time being.
___
*[windows/winnet/src/winnet/winnet.h, line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFsxo-BQTRvRR84PzS:-MHFzD9EDfsrIPKeXv36:b-v2nsgo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L190)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

IIRC, we consolidated these duplicated types into a general enumeration?
</blockquote></details>

Those types were new, but I've consolidated them into `WINNET_STATUS`. This may be slightly confusing given that most functions return `bool`. Thoughts?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115)* status: 4 of 10 files reviewed, 6 unresolved discussions (waiting on @mvd-ows)

___
*[windows/winnet/src/winnet/winnet.h, line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFt7JVDb8KRox0GMa3:-MHGvvod16UxMLnkf_Gf:b-xl5vm1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L183)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Non-tunnel route, but you're not wrong. We use the term like this elsewhere in the app--e.g., the route manager (on Linux and Windows) is supposed to ignore tunnel routes, but "default route" implicitly refers to "non-tunnel route"--so I've not renamed it for the time being.
</blockquote></details>

Correction: "non-tunnel **default** route"

**Review by mvd-ows — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 194 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFpqke-ZofgT3qYJVt:-MHGx1dE3xkg9iZgJznn:bovf2nd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L194)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It only used this to determine the address family, because they are necessarily the same (correct me if I'm wrong). `iface_idx` was the interface that was used. Confusingly, I set the family for the gateway even if the gateway itself was not set, so I've updated it anyway.
</blockquote></details>

Ah, sloppy reading on my part. Everything makes sense now.
___
*[windows/winnet/src/winnet/offlinemonitor.cpp, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFrttuEjL7Mxf1QxXp:-MHGxaVQAslQvrx-JD8O:brxp9sq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/offlinemonitor.cpp#L19)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

For now, I'm leaving this unchanged due to the various caveats. If the check I've added to the route manager is broken, it will likely only break for OpenVPN, and operate in the same way as before when using WireGuard (because the route has no gateway). At some point, this function could be shared with the `GetBestDefaultRoute`.
</blockquote></details>

Sounds good.
___
*[windows/winnet/src/winnet/winnet.h, line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFt7JVDb8KRox0GMa3:-MHGxrdvDfwIoVw_90o2:b-nfkzvu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L183)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Correction: "non-tunnel **default** route"
</blockquote></details>

OK, great.
___
*[windows/winnet/src/winnet/winnet.h, line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHFsxo-BQTRvRR84PzS:-MHGyD9i7I8un6qpb9ZP:b-bfwc4e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8f08ac121a16c0e16de9d4518023d962d80190b/windows/winnet/src/winnet/winnet.h#L190)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Those types were new, but I've consolidated them into `WINNET_STATUS`. This may be slightly confusing given that most functions return `bool`. Thoughts?
</blockquote></details>

I must have been thinking of some other module. Sounds good to me.
___
*[windows/winnet/src/winnet/routing/helpers.cpp, line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHGyozVBoDHo3QQsnRY:-MHGyozWByxM51Wyo56z:bivva3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0bbd7ae73dd8b0ba39c3ecbf52d1b24cc5274e4/windows/winnet/src/winnet/routing/helpers.cpp#L18)):*
> ```cpp
> };
> 
> bool IsPhysicalInterface(const MIB_IPFORWARD_ROW2 &route)
> ```

`IsRouteOnPhysicalInterface` would be more descriptive but maybe a little too long? `IsRouteThroughPhysicalInterface` is even longer though :-)
___
*[windows/winnet/src/winnet/routing/helpers.cpp, line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHGzoYH63CAkvv6wtOo:-MHGzoYH63CAkvv6wtOp:b-6zoobj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0bbd7ae73dd8b0ba39c3ecbf52d1b24cc5274e4/windows/winnet/src/winnet/routing/helpers.cpp#L41)):*
> ```cpp
> 	}
> 
> 	for (size_t i = 0; i < sizeof(TUNNEL_INTERFACE_DESCS) / sizeof(TUNNEL_INTERFACE_DESCS[0]); i++)
> ```

`ARRAY_SIZE`?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[windows/winnet/src/winnet/routing/helpers.cpp, line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHGyozVBoDHo3QQsnRY:-MHH4HTh0n_MjsaT22AI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0bbd7ae73dd8b0ba39c3ecbf52d1b24cc5274e4/windows/winnet/src/winnet/routing/helpers.cpp#L18)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`IsRouteOnPhysicalInterface` would be more descriptive but maybe a little too long? `IsRouteThroughPhysicalInterface` is even longer though :-)
</blockquote></details>

Done.
___
*[windows/winnet/src/winnet/routing/helpers.cpp, line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-MHGzoYH63CAkvv6wtOo:-MHH4LMl6jHSGAEKGuvg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0bbd7ae73dd8b0ba39c3ecbf52d1b24cc5274e4/windows/winnet/src/winnet/routing/helpers.cpp#L41)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`ARRAY_SIZE`?
</blockquote></details>

Done.

**Review by mvd-ows — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2115#-:-MHH8kobDJGsjrYu61yg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
