### PR TITLE
Add separate tidy config for /values

### PR DESCRIPTION
**Pull request by Pururun**
Change it so that the tidy script is run two times, one for files under `/values` and one for the other files. This is so that we can have a separate configuration for the files in `/values`.

Applied this new tidy configuration to the files in `/values`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Looks good in general! I just have feedback on a minor thing with `CDATA`

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612#-:-NTrBQKw76v1VMfdLGVt:bdt69n8)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/res/values/strings.xml` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612#-NTrBDQyBZyscu69EAHA:-NTrBDQyBZyscu69EAHB:bgvllvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cd18b6c4f3b5c98173bd8a53901fec1d6d46784/android/app/src/main/res/values/strings.xml#L155)):*
> ```XML
>     <string name="always_on_vpn_error_notification_title">Always-on VPN assigned to other app</string>
>     <string name="always_on_vpn_error_notification_content">
>         <![CDATA[Unable to start tunnel connection. Please disable Always-on VPN for <b>%s</b> before
> ```

This can be a single line, right? :thinking: 



_Code quote:_
```XML
        <![CDATA[Unable to start tunnel connection. Please disable Always-on VPN for <b>%s</b> before
            using Mullvad VPN.]]>
```

**Review by Pururun — COMMENTED** [review]
Oh, forgot about needing to manually change that line. Fixed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612#-:-NTrKhbh9q01kpoNEkqT:b-nl2ixp)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612#-:-NTrNzzD4y-tzHjiIfN1:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/scripts/tidy.sh` line 50 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612#-NTrOmnN2M54FihlSfyT:-NTrSf3W1C9ACzFhcOr9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e083cecc8a72e792f07b4d4d0d366455c3439a7/android/scripts/tidy.sh#L50)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please cleanup these spaces also :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
