### PR TITLE
Enable r8 minify and shrinking

### PR DESCRIPTION
**Pull request by albin-mullvad**
Enabling r8 minify and shrinking to reduce apk size (`31M` -> `26M`) and to apply code optimization. This seem to also improve the performance when using Jetpack Compose.

More info about minify and shrinking is available here: https://developer.android.com/studio/build/shrink-code

TODO:
- [x] ~~Upload generated `mapping.txt` to enable deobfuscation.~~
- [x] ~~Set proper name for uploaded `mapping.txt` to avoid confusion with other platforms.~~
- [x] Doducment reason (FFI) for excluding `net.mullvad.*` from minification.
- [ ] ~~Test run on build server.~~

Upload of `mapping.txt` will be done in a separate PR as it relies on some other build script changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4364)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4364)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4364)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4364)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4364)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
