### PR TITLE
Update changelog for Android 2024.4

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718#-O5qh7QY-mQRXBS1wWYf:-O5qh7QY-mQRXBS1wWYg:bfor08w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c93eb54ab15c8464f3e5bc27b470bc29f252e28/android/src/main/play/release-notes/en-US/default.txt#L1)):*
> ```help
> - Add splash screen animation on app start up.
> ```

I think we missed it last time as well, but we should mention api access methods in the relase notes

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718#-O5qh7QY-mQRXBS1wWYf:-O5r-XGJEcJL1QPIjmCm:b-5i5i4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c93eb54ab15c8464f3e5bc27b470bc29f252e28/android/src/main/play/release-notes/en-US/default.txt#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think we missed it last time as well, but we should mention api access methods in the relase notes
</blockquote></details>

Good catch! Added a line

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718#-:-O5r26EeAC_C-9xNWb4m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by Pururun — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718#-:-O5r6FJe9htJQNU67-hP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/CHANGELOG.md` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718#-O5rwK4f2ZrznCn8t1RD:-O5rwK4f2ZrznCn8t1RE:bt5x2pc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a872891a42fdf661620a060140a5284afb216a3d/android/CHANGELOG.md#L27)):*
> ```Markdown
> 
> 
> ## [android/2024.4] - 2024-09-02
> ```

Update to `03`



_Code quote:_
```Markdown
02
```

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
