### PR TITLE
Implement `From<RelaySettingsUpdate>` for gRPC equivalent

### PR DESCRIPTION
**Pull request by dlon**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4178)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
What is this for?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4178#-:-NI6yFE178USvguD_uV8:bzbe37d)* status: 0 of 1 files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
It's used by the system/integration tests.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4178#-:-NI6zgYJ6v8uWjjehwgb:b33jueq)* status: 0 of 1 files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4178)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4178)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
