### PR TITLE
MTU detection integration test on Linux and Windows

### PR DESCRIPTION
**Pull request by Serock3**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: all files reviewed, 8 unresolved discussions (waiting on @Serock3)

___
*[`.github/workflows/desktop-e2e.yml` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDaQwm0V7v0NEmX9rH:-NsDaQwm0V7v0NEmX9rI:bvby9bf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/.github/workflows/desktop-e2e.yml#L16)):*
> ```YAML
>     inputs:
>       oses:
>         description: "Comma-separated list of targets to run tests on, e.g. `debian11 debian12`. \
> ```

Is this not space-delimited?
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 141 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDbCRk1jySkmWadkY3:-NsDbCRk1jySkmWadkY4:b-uvb0yy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L141)):*
> ```XML
>         .await
>         .expect("Ping should return when disconnected");
>     log::info!("Connecting");
> ```

Already logged in `connect_and_wait`.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 150 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDbtxx9rV7aCxeZo8o:-NsDbtxx9rV7aCxeZo8p:b-gvtvbi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L150)):*
> ```XML
>         .await
>         .expect("failed to find tunnel interface");
>     let mtu = rpc.get_interface_mtu(tunnel_iface).await?;
> ```

Won't this just return the default MTU, unless the MTU detection happens to complete first? I think you'll have to wait for the MTU detection to finish, somehow.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 152 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDjcZ02kio-jS3UViU:-NsDjcZ02kio-jS3UViV:b98ayvq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L152)):*
> ```XML
>     let mtu = rpc.get_interface_mtu(tunnel_iface).await?;
>     log::info!("Tunnel MTU: {mtu}");
>     assert!(mtu > 1000);
> ```

Using a constant would be nicer. Would `large_ping_size` (+ something) be correct here?
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDc_-NBUA7fWY1chRD:-NsDc_-NBUA7fWY1chRE:b-uvb0yy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L168)):*
> ```XML
>         .await
>         .expect_err("Ping larger than nftables filter should time out");
>     log::info!("Connecting");
> ```

Already logged in `connect_and_wait`.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 169 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDfIn87Zgkcvvhn8Gz:-NsDfIn87Zgkcvvhn8H-:b-a3ljfq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L169)):*
> ```XML
>         .expect_err("Ping larger than nftables filter should time out");
>     log::info!("Connecting");
>     connect_and_wait(&mut mullvad_client).await.unwrap();
> ```

Arguably, we could replace all of the steps above with only the following:
1. Fail unless we can send packets larger than `max_packet_size` outside the tunnel. Or connect and fail if the *detected* MTU is smaller than `max_packet_size`.
2. Add the nftables rule and reconnect. Assert that the detected MTU is smaller than `max_packet_size`.
___
*[`test/test-runner/src/net.rs` line 156 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDi5UL0m0ciH4CfCTV:-NsDi5UL0m0ciH4CfCTW:b5ar97r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-runner/src/net.rs#L156)):*
> ```XML
>     };
>     let config = if let Some(iface_name) = interface {
>         config.interface(iface_name)
> ```

This doesn't seem to do anything on Windows. Previously, we set the source address, which we probably still want to do in the leak tests.
___
*[`test/test-runner/src/net.rs` line 165 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDiyHqCxDEgWb9Fc5t:-NsDiyHqCxDEgWb9Fc5u:b54wmd8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e993df31f96080b1cf51eef216092befec6c306/test/test-runner/src/net.rs#L165)):*
> ```XML
> 
>     #[cfg(target_os = "windows")]
>     cmd.args(["-n", "1"]);
> ```

Do we still only send a single ping here?

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: 10 of 15 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`.github/workflows/desktop-e2e.yml` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDaQwm0V7v0NEmX9rH:-NsDrf2J9UtObJElxyy0:be5ifu8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/.github/workflows/desktop-e2e.yml#L16)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this not space-delimited?
</blockquote></details>

Yup, :facepalm:. Wrote the example space delimited but messed up the text.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 141 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDbCRk1jySkmWadkY3:-NsEAlsh5D9T4Ulh7jyp:bxyo87r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L141)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Already logged in `connect_and_wait`.
</blockquote></details>

Note sure what you are refering to, does this function log in?
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 150 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDbtxx9rV7aCxeZo8o:-NsDsOZb9y2eTiCFkAKR:by9x6n4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L150)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Won't this just return the default MTU, unless the MTU detection happens to complete first? I think you'll have to wait for the MTU detection to finish, somehow.
</blockquote></details>

Oh, you're right. Reworked the tests to remove this part.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 152 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDjcZ02kio-jS3UViU:-NsEBMG64Z_SU0PwBXAL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L152)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Using a constant would be nicer. Would `large_ping_size` (+ something) be correct here?
</blockquote></details>

Done.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDc_-NBUA7fWY1chRD:-NsEBOls0hcvEGyd4HSr:b7u323k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L168)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Already logged in `connect_and_wait`.
</blockquote></details>

Again note sure what you mean
___
*[`test/test-runner/src/net.rs` line 156 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDi5UL0m0ciH4CfCTV:-NsEBUNzEQVLkyJlmFEl:b-cpqav5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-runner/src/net.rs#L156)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This doesn't seem to do anything on Windows. Previously, we set the source address, which we probably still want to do in the leak tests.
</blockquote></details>

Fixed. Made it bind to the interface ip, both for Windows and Linux. Slightly different behavior so we should check that it doesn't mess up any existing tests.
___
*[`test/test-runner/src/net.rs` line 165 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDiyHqCxDEgWb9Fc5t:-NsEBRmP0JTOI54dz4PY:b2nhswy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e993df31f96080b1cf51eef216092befec6c306/test/test-runner/src/net.rs#L165)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we still only send a single ping here?
</blockquote></details>

Yes

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon and @Serock3)

___
*[`test/test-manager/src/tests/tunnel_state.rs` line 119 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI3zfHANLa73jvC_6f:-NsI3zfI04-q8h28_mZt:b-jod6pe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-manager/src/tests/tunnel_state.rs#L119)):*
> ```XML
>     let _nft_guard = setup_nftables_drop_pings_rule(MAX_PACKET_SIZE).await;
>     #[cfg(target_os = "macos")]
>     let _pf_guard = setup_packetfilter_drop_pings_rule(max_packet_size).await;
> ```

What's up with the lowercase variable here? Should it be `MAX_PACKET_SIZE`? :blush:



_Code quote:_
```XML
max_packet_size
```
___
*[`test/test-runner/src/net.rs` line 283 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI4rm0CkeZb_pdp5vA:-NsI4rm0CkeZb_pdp5vB:bl6auh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-runner/src/net.rs#L283)):*
> ```XML
>     Ok(unsafe { ifr.ifr_ifru.ifru_mtu }
>         .try_into()
>         .expect("MTU should fit in u16"))
> ```

Should we add some comments on the safety here, or are we fine leaving those out? :blush: 



_Code quote:_
```XML
    unsafe {
        std::ptr::copy_nonoverlapping(
            interface_name.as_ptr() as *const libc::c_char,
            &mut ifr.ifr_name as *mut _,
            interface_name.len(),
        )
    };

    // TODO: define SIOCGIFMTU for macos
    if unsafe { libc::ioctl(sock.as_raw_fd(), libc::SIOCGIFMTU, &mut ifr) } < 0 {
        let e = std::io::Error::last_os_error();

        log::error!("{}", e);
        return Err(test_rpc::Error::Syscall); // TODO: look over error type
    }
    Ok(unsafe { ifr.ifr_ifru.ifru_mtu }
        .try_into()
        .expect("MTU should fit in u16"))
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: 14 of 15 files reviewed, 8 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`test/test-manager/src/tests/tunnel_state.rs` line 119 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI3zfHANLa73jvC_6f:-NsIs59k5BQqZZx6wksX:b-vt63tn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-manager/src/tests/tunnel_state.rs#L119)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

What's up with the lowercase variable here? Should it be `MAX_PACKET_SIZE`? :blush:
</blockquote></details>

Whoops. Fixed.
___
*[`test/test-runner/src/net.rs` line 283 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI4rm0CkeZb_pdp5vA:-NsIQk6NEDEhLg9-TSVo:b-ckf2fb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-runner/src/net.rs#L283)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should we add some comments on the safety here, or are we fine leaving those out? :blush:
</blockquote></details>

@dlon What do you think? We already check that dest > src for `copy_nonoverlapping`, not sure if there are any safety concerns about `ioctl.

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: all files reviewed, 6 unresolved discussions (waiting on @MarkusPettersson98 and @Serock3)

___
*[`test/test-manager/src/tests/tunnel_state.rs` line 141 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDbCRk1jySkmWadkY3:-NsJ8MqN4Fiqu-Sfd2dK:b3c7rpt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L141)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Note sure what you are refering to, does this function log in?
</blockquote></details>

This comment was originally on some completely different line.
___
*[`test/test-manager/src/tests/tunnel_state.rs` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDc_-NBUA7fWY1chRD:-NsJ8_eZ5YeLj1nzxKbF:bk7hszj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L168)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Again note sure what you mean
</blockquote></details>

I mean that "connecting" is already logged inside `connect_and_wait` when the latter is called. :)
___
*[`test/test-rpc/src/lib.rs` line 22 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsJ8pbV2wrZivgVgXLu:-NsJ8pbV2wrZivgVgXLv:bxn3s21) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e95466dae824e37b973f2fbf7992875357640817/test/test-rpc/src/lib.rs#L22)):*
> ```XML
>     #[error("Syscall failed")]
>     Syscall,
>     #[error("Internal IO error occurred")]
> ```

Do we want to print the string here? I.e.

```
Internal IO error occurred: {0}
```

I think this applies to some other variants too.
___
*[`test/test-runner/src/net.rs` line 283 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI4rm0CkeZb_pdp5vA:-NsJKPOJ9CyfzBE5-ZTD:b3ov1ap) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-runner/src/net.rs#L283)):*
Doesn't hurt, even if you keep it brief. Some suggestions:

> // SAFETY:  `interface_name` is shorter than `ifr.ifr_name`

> // SAFETY: `SIOCGIFMTU` expects an `ifreq`, and the socket is valid

> // SAFETY: `ifru_mtu` is set since `SIOGCIFMTU` succeeded

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`test/test-runner/src/net.rs` line 283 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI4rm0CkeZb_pdp5vA:-NsMsjyZ2S8xWnPmUXLB:btq93c6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-runner/src/net.rs#L283)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Doesn't hurt, even if you keep it brief. Some suggestions:

> // SAFETY:  `interface_name` is shorter than `ifr.ifr_name`

> // SAFETY: `SIOCGIFMTU` expects an `ifreq`, and the socket is valid

> // SAFETY: `ifru_mtu` is set since `SIOGCIFMTU` succeeded
</blockquote></details>

Nice, thanks! :blush: :crab:

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/tests/tunnel_state.rs` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsDc_-NBUA7fWY1chRD:-NsJYJ0S7sxr8yE2eGMN:b7jlat7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c48e0e9e990ffe5669a07756c18834ff7594395/test/test-manager/src/tests/tunnel_state.rs#L168)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I mean that "connecting" is already logged inside `connect_and_wait` when the latter is called. :)
</blockquote></details>

Ah, I see. Fixed!
___
*[`test/test-rpc/src/lib.rs` line 22 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsJ8pbV2wrZivgVgXLu:-NsN7O1K9UXHGfTiVfm5:b-utu5ev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e95466dae824e37b973f2fbf7992875357640817/test/test-rpc/src/lib.rs#L22)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we want to print the string here? I.e.

```
Internal IO error occurred: {0}
```

I think this applies to some other variants too.
</blockquote></details>

Oh, I thought `thiserror` did that by default, similar to `anyhow`. But yes, I will add that.
___
*[`test/test-runner/src/net.rs` line 283 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI4rm0CkeZb_pdp5vA:-NsNuBmB3ZWJuBQyHB9r:bjomedr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-runner/src/net.rs#L283)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nice, thanks! :blush: :crab:
</blockquote></details>

Right. I though you were referring to a doc-string with instructions on how not to cause safety issues. I added the comments you suggest David, I can't think of anything else off the top of my head.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`test/test-runner/src/net.rs` line 283 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsI4rm0CkeZb_pdp5vA:-NsSWV2l8XIl_UGoqJ3_:bg7igkv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a360b7b1ed3cecaf1ed400149af6974efc07f13/test/test-runner/src/net.rs#L283)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Right. I though you were referring to a doc-string with instructions on how not to cause safety issues. I added the comments you suggest David, I can't think of anything else off the top of my head.
</blockquote></details>

:lgtm: 
___
*[`test/test-runner/src/net.rs` line 284 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891#-NsSWP1F9NEDhjdk-OyE:-NsSWP1F9NEDhjdk-OyF:b-fz18pq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053ee03783c2594a8ac1a88503c8be104a3fb0ba/test/test-runner/src/net.rs#L284)):*
> ```XML
>     }
> 
>     // SAFETY: ifru_mtu is set since SIOGCIFMTU succeeded
> ```

I snuck in a typo here.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rkwjdgus9880 — COMMENTED** [review]
나

**Pull request merged**
