### PR TITLE
Update readme with more backend instructions

### PR DESCRIPTION
**Pull request by faern**
Ok, so we have opened the repo to the public, but the readme is not very helpful for someone external. Let's put a few minutes into improving that.

I'm not sure if these instructions will work directly. Some of it was a bit of guesswork at the moment. I hope you can fill in on the frontend parts.

I separated the backend and frontend now. Since building and running them requires completely different tools/toolchains and commands, so it felt a bit messy to mix them. The packaging section on the other hand handles both since it's for packaging the entirety.

- [x] Is the "Repository structure" still correct, regarding the frontend? I added a few entries for the backend.
- [x] Is the frontend diagram still correct?
- [x] Does the "View layout" section still need to be here? What purpose does it serve?
- [x] Is the "Build dependencies" section still correct? Are these packages needed? Anything else that is needed, it looks a bit short maybe?

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/15)

### CODE REVIEW

**Comment by eriklarko** [comment]
Just some very small changes to the repo structure, very good! 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 114 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L210cEGAP_4aXyHYghF:-L210cEGAP_4aXyHYghG:b-49a7nq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L114)):*
> ```Markdown
>   - **lib/** - shared classes and utilities
>   - **assets/** - graphical assets and stylesheets
>   - **config.js** - static configuration file
> ```

This is a json file and not a js file

---

*[README.md, line 118 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L210sFgJeO_YWIZQrMi:-L210sFgJeO_YWIZQrMj:brurvbc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L118)):*
> ```Markdown
>   - **main.js** - entry file for background process
>   - **routes.js** - routes configurator
>   - **store.js** - redux store configurator
> ```

This has been moved into `redux` and can thus be removed from this list

---

*[README.md, line 119 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L210xyUFhkuFhOFEke4:-L210xyUFhkuFhOFEke5:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L119)):*
> ```Markdown
>   - **routes.js** - routes configurator
>   - **store.js** - redux store configurator
>   - **enums.js** - common enums used across components
> ```

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-:-L2113q-ouKAi1tinNQn:b-vsfzb8)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 114 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L210cEGAP_4aXyHYghF:-L2180blzaaCSca_XPDp:bdkz1lz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L114)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

This is a json file and not a js file
</blockquote></details>

What is it a config for? I would argue that saying that something named `config` is a configuration file does not provide very much value. Either we explain in more detail what it's for or we don't list it at all IMO. This argument holds for a few more entries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by eriklarko** [comment]
*[README.md, line 114 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L210cEGAP_4aXyHYghF:-L218yS_wO46K-FCKcXr:bsz1bf5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L114)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What is it a config for? I would argue that saying that something named `config` is a configuration file does not provide very much value. Either we explain in more detail what it's for or we don't list it at all IMO. This argument holds for a few more entries.
</blockquote></details>

Right now it holds the urls for the guides and such as well as the mapbox config. But the mapbox config will be removed so it will only contain links to our external resources.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 126 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L24Cz25Iqafo0zCjbdQ:-L24Cz25Iqafo0zCjbdR:b-1tlneo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37e95bf1af78cee079082165335754dab76f51a5/README.md#L126)):*
> ```Markdown
> - **mullvad-daemon/** - Main crate building the backend daemon binary
> - **scripts/** - support scripts for development
> - **test/** - tests
> ```

Frontend tests maybe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 139 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Av3IKKutHZ9xTZ_J:-L25Av3JMXAOLUarsWdv:bt6k9jb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L139)):*
> ```Markdown
> 
> Most of application layouts consist of header bar area and main content area. Three of components
> from `components/Layout` help to assemble each view, i.e:
> ```

I'm not sure what this information is for, who needs it and when. I guess it's relevant to someone who want to read or write code for the frontend?

I'm thinking we should move such instructions out to other files. Either a generic `CONTRIBUTING.md`, or a file specific to the frontend with instructions how to get used to the code. Thoughts on that? It's quite random to end up in the main readme which will be the file presented on first view of the repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L25Crka9l-9KERHDd9b:b-8g3tkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
> ```Markdown
> 
> ```bash
> sudo apt install icnsutils graphicsmagick
> ```

I didn't get any response on if this was still needed. So I moved it to the packaging section. Tell me if this is the wrong place or if they are required for something other than packaging. No dependencies when building on macOS?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L29M5vUEJsR8uNRyn6T:b-lswbn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I didn't get any response on if this was still needed. So I moved it to the packaging section. Tell me if this is the wrong place or if they are required for something other than packaging. No dependencies when building on macOS?
</blockquote></details>

I'd move `yarn install` before `yarn run pack` because it's somewhat a necessary step.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L29MqzyBcBsLJyGe4G-:bs9mb49) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I'd move `yarn install` before `yarn run pack` because it's somewhat a necessary step.
</blockquote></details>

Just like you do `apt-get install ...`, there is no difference except you install javascript deps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 139 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Av3IKKutHZ9xTZ_J:-L29N5x467rJSEb0-JdS:b-swj16j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L139)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure what this information is for, who needs it and when. I guess it's relevant to someone who want to read or write code for the frontend?

I'm thinking we should move such instructions out to other files. Either a generic `CONTRIBUTING.md`, or a file specific to the frontend with instructions how to get used to the code. Thoughts on that? It's quite random to end up in the main readme which will be the file presented on first view of the repo.
</blockquote></details>

I'd remove it  since we have enough codebase proving that's how we build most of the views. That was more of a hint for devs how to add more views.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L29OCCqUNYKFwhAKtwK:bn1sb50) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Just like you do `apt-get install ...`, there is no difference except you install javascript deps.
</blockquote></details>

(Reviewable broke so I commented on something else in a wrong place)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L29O_OkKGiB4znJ2889:b3g682q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

(Reviewable broke so I commented on something else in a wrong place)
</blockquote></details>

The deps mentioned above are still needed. This is documented by electron-builder project:

https://www.electron.build/multi-platform-build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L29Oq8gm0hF4Vp4OGF1:b-mzduov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

The deps mentioned above are still needed. This is documented by electron-builder project:

https://www.electron.build/multi-platform-build
</blockquote></details>

on macOS all required dependencies are downloaded automatically by electron-builder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 119 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29PgujCmEvoJXT1IRB:-L29Pguka9kiCMC7Rgs9:b34uopr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L119)):*
> ```Markdown
>   - **routes.js** - routes configurator
>   - **store.js** - redux store configurator
>   - **enums.js** - common enums used across components
> ```

This has been removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 119 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29PyHqJ90GexW5iTMk:-L29PyHqJ90GexW5iTMl:blyzjes) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L119)):*
> ```Markdown
>   - **routes.js** - routes configurator
>   - **store.js** - redux store configurator
>   - **enums.js** - common enums used across components
> ```

We've added:

```
- **types.js** - common Flow types used across the app
- **transitions.js** - transition rules between views
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 134 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29RenRCF8CsHjOw8No:-L29RenRCF8CsHjOw8Np:b-ew4j1k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L134)):*
> ```Markdown
> ## Diagram of frontend architecture
> 
> App diagram
> ```

Most of the diagram shows how the React works. This is a little bit unnecessary but we can leave it if it helps somebody.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L2KldMLZo8a0gJHiQgT:b12s5qz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

on macOS all required dependencies are downloaded automatically by electron-builder.
</blockquote></details>

Ah. I thought `yarn install` in the `Building and running the frontend (electron app)` section was enough. To package you also need to actually install `yarn` etc. So I'll add a note to the packaging section saying that one must first go through the two `Building and running ...` sections before packaging.

---

*[README.md, line 119 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29PgujCmEvoJXT1IRB:-L2KyyuuUDiIOgbSK69s:bvr767y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L119)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This has been removed.
</blockquote></details>

The file still exists in the latest master. Is it removed in some feature branch? Or do you mean it's unused but still left in the repo?

---

*[README.md, line 134 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29RenRCF8CsHjOw8No:-L2KzUjWtUEko9jEv3uB:b9r3oky) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L134)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Most of the diagram shows how the React works. This is a little bit unnecessary but we can leave it if it helps somebody.
</blockquote></details>

It takes a lot of space. Unless it's actually up to date, easy to understand and is likely to help someone I'd rather remove it. Having a cleaner and easier to read README might also be helpful to some. What do you think?

---

*[README.md, line 139 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Av3IKKutHZ9xTZ_J:-L2Kzwy3kJOlC2AT6Xuk:b-h3981r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L139)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I'd remove it  since we have enough codebase proving that's how we build most of the views. That was more of a hint for devs how to add more views.
</blockquote></details>

Cool. Removed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 119 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29PyHqJ90GexW5iTMk:-L2L-91Tu1c26B9nmZgL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L119)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

We've added:

```
- **types.js** - common Flow types used across the app
- **transitions.js** - transition rules between views
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 134 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29RenRCF8CsHjOw8No:-L2L6kY4BrvTKZLCFIf8:bq0smt5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L134)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It takes a lot of space. Unless it's actually up to date, easy to understand and is likely to help someone I'd rather remove it. Having a cleaner and easier to read README might also be helpful to some. What do you think?
</blockquote></details>

I'd remove it entirely with `README Images`. This was relevant in the beginning of development but now it's better to ask me or anyone on the team.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L2L7JcJULw4xCe7tEg-:b3ops9e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah. I thought `yarn install` in the `Building and running the frontend (electron app)` section was enough. To package you also need to actually install `yarn` etc. So I'll add a note to the packaging section saying that one must first go through the two `Building and running ...` sections before packaging.
</blockquote></details>

Well, you need compiled backend and frontend to package the app. 

We can mention that for packaging please make sure to compile FE and BE. Then there is no need to run `yarn install` once again. Sorry for confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 119 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29PgujCmEvoJXT1IRB:-L2L8FDrCg6KudomlInV:bz4oyqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L119)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The file still exists in the latest master. Is it removed in some feature branch? Or do you mean it's unused but still left in the repo?
</blockquote></details>

That was a comment for `enum.js`. Reviewable had a bad day or I used the wrong revision. Ignore this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by faern** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 134 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L29RenRCF8CsHjOw8No:-L2LDFMhpolRS2ihUWVr:b4aqa7t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L134)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I'd remove it entirely with `README Images`. This was relevant in the beginning of development but now it's better to ask me or anyone on the team.
</blockquote></details>

I'm not sure I think "ask someone on the team" is a sustainable way of documenting things really :P
But I'll remove the image anyway since I got the impression that it's at least a bit outdated, and having invalid documentation is bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by faern** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 92 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-L25Crka9l-9KERHDd9a:-L2LDqHjm4dTl2CzmUxK:ba7qnq5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb05e5bed5e903e85165cbf869b6c69b521633a/README.md#L92)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Well, you need compiled backend and frontend to package the app. 

We can mention that for packaging please make sure to compile FE and BE. Then there is no need to run `yarn install` once again. Sorry for confusion.
</blockquote></details>

I added step to follow initial toolchain, and then added `yarn install` before the pack step. Looks good?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-:-L2OkHI1an1zzxXNjv_h:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/15#-:-L2PJWx7fRUl6cCaZC81:bnfp4nl)*

**Pull request merged**
