### PR TITLE
Windows: Update installer/uninstaller for split tunneling

### PR DESCRIPTION
**Pull request by mvd-ows**
As above.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[windows/driverlogic/src/service.cpp, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFkLup9Ckd-xAIt2Bf:-MYFkLup9Ckd-xAIt2Bg:b-ailmtw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/service.cpp#L32)):*
> ```cpp
> 		}
> 
> 		if (GetTickCount() > endTime)
> ```

This is unlikely, but if `GetTickCount() + maxWaitMs` overflows, then this may fail before `maxWaitMs` milliseconds have elapsed.
___
*[windows/driverlogic/src/util.cpp, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFcD22-OUyZ51CW7S9:-MYFcD236_6sC7wT3o7H:bomwipg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L8)):*
> ```cpp
> 
> std::filesystem::path
> GetProcessModulePath
> ```

Arguably, this could be moved to `libcommon`.
___
*[windows/driverlogic/src/util.cpp, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFeO8K5yIBgvdQRAA5:-MYFeO8K5yIBgvdQRAA6:b-y9y5uk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L9)):*
> ```cpp
> std::filesystem::path
> GetProcessModulePath
> (
> ```

Using `_get_wpgmptr` would have been more concise. Although it does assume that the entry point is `wmain`.
___
*[windows/driverlogic/src/util.cpp, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFj0YmAhnPIWInjtET:-MYFj0YmAhnPIWInjtEU:b2cxm1i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L27)):*
> ```cpp
> 		if (writtenChars != pathBuffer.size())
> 		{
> 			return std::filesystem::path(pathBuffer.begin(), std::next(pathBuffer.begin(), writtenChars));
> ```

Why not simply `path(pathBuffer.begin(), pathBuffer.begin() + writtenChars)`?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[windows/driverlogic/src/service.cpp, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFkLup9Ckd-xAIt2Bf:-MYGCcup1qTwjvVN181M:b-uo5fka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/service.cpp#L32)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is unlikely, but if `GetTickCount() + maxWaitMs` overflows, then this may fail before `maxWaitMs` milliseconds have elapsed.
</blockquote></details>

Yep, this is quite sloppy. Would be better to wrap both the setup and comparison in a class. I'll see about it.

Or maybe change it to use `GetTickCount64()`, so it almost never fails :-)
___
*[windows/driverlogic/src/util.cpp, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFcD22-OUyZ51CW7S9:-MYGF23GEHAyLUgfriQg:b-dai7my) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L8)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Arguably, this could be moved to `libcommon`.
</blockquote></details>

Sure, but that can be said about a lot of code. I'd prefer to make it a separate project to move things into libcommon and add tests.
___
*[windows/driverlogic/src/util.cpp, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFeO8K5yIBgvdQRAA5:-MYGGaK59EG0OFG1eKoT:b390w57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L9)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Using `_get_wpgmptr` would have been more concise. Although it does assume that the entry point is `wmain`.
</blockquote></details>

There are two versions of that function, maybe one of them could be used here. That's interesting about the `wmain` limitation, I guess that's a good reason to not use those functions in a more general context. Assuming we're eventually moving this code to libcommon.
___
*[windows/driverlogic/src/util.cpp, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFj0YmAhnPIWInjtET:-MYGHDQR8a0Bn0cAGFaE:b3bt4qe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why not simply `path(pathBuffer.begin(), pathBuffer.begin() + writtenChars)`?
</blockquote></details>

I don't believe `std::filesystem` is in scope here.

The reason I chose to apply `std::next` alludes me at the moment. I'll look into it.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[windows/driverlogic/src/util.cpp, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFj0YmAhnPIWInjtET:-MYGm8czD19714gs0Cz_:bng9z0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L27)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I don't believe `std::filesystem` is in scope here.

The reason I chose to apply `std::next` alludes me at the moment. I'll look into it.
</blockquote></details>

Right, since the iterator type is known, there's certainly no need to use `std::next` here.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[windows/driverlogic/src/util.cpp, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFcD22-OUyZ51CW7S9:-MYJeZ7M78LW_NKKCuuZ:btd51a6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L8)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Sure, but that can be said about a lot of code. I'd prefer to make it a separate project to move things into libcommon and add tests.
</blockquote></details>

I agree.
___
*[windows/driverlogic/src/util.cpp, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYFeO8K5yIBgvdQRAA5:-MYJexE37ycLro5sJZhz:b7ti3qz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e94d71509aa3b77ba6544003b568de637f5ef09/windows/driverlogic/src/util.cpp#L9)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There are two versions of that function, maybe one of them could be used here. That's interesting about the `wmain` limitation, I guess that's a good reason to not use those functions in a more general context. Assuming we're eventually moving this code to libcommon.
</blockquote></details>

Yep. Let's leave it as it is.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[windows/driverlogic/src/driverlogic.cpp, line 349 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYJjkbhB3O7OD7eQOaK:-MYJjkbhB3O7OD7eQOaL:b-xcodb6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6a8a55a85108ee020cec8682aa48fb0ab6400c85/windows/driverlogic/src/driverlogic.cpp#L349)):*
> ```cpp
> 		{
> 			Log(common::string::ToWide(e.what()));
> 			return e.errorCode();
> ```

Something I just realized: Is there not a chance that these codes will collide with our own? IIRC, that's why they were negative before.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[windows/driverlogic/src/driverlogic.cpp, line 349 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666#-MYJjkbhB3O7OD7eQOaK:-MYJnLmWAkSvGdKQo5bD:b20u9qb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6a8a55a85108ee020cec8682aa48fb0ab6400c85/windows/driverlogic/src/driverlogic.cpp#L349)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Something I just realized: Is there not a chance that these codes will collide with our own? IIRC, that's why they were negative before.
</blockquote></details>

There's certainly a chance of that happening. Ideally, the return code would be { success, failure, windowsException }, and in the latter case the actual error code could be acquired from somewhere else.

**Pull request merged**
