### PR TITLE
Add `status listen` sub-command to Mullvad CLI

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pronebird, @faern, and @jvff)

---

*[mullvad-cli/src/cmds/status.rs, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247#-LG-Ntnj3RYDWSK0rTFQ:-LG-Ntnj3RYDWSK0rTFR:bp4m4qx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb96dc99c3a7659e6611e3b85288c7ab2b5964e3/mullvad-cli/src/cmds/status.rs#L45)):*
> ```Rust
> 
>                 if new_state == CONNECTED || new_state == DISCONNECTED {
>                     print_location(&mut rpc)?;
> ```

If I recall it correctly, I encountered the cases when user location was not updated on time by the time the state changed. This may have been fixed already though. Not sure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247)*

**Comment by pronebird** [comment]
:+1: 

---

Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pronebird, @faern, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247#-:-LG-OdnZ48ugVG2Z2cI8:b-8fx2u7)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247)*

**Comment by faern** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[mullvad-cli/src/cmds/status.rs, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247#-LG-Ntnj3RYDWSK0rTFQ:-LG-V6m_92gi7saddgSC:b-5x1iy0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb96dc99c3a7659e6611e3b85288c7ab2b5964e3/mullvad-cli/src/cmds/status.rs#L45)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

If I recall it correctly, I encountered the cases when user location was not updated on time by the time the state changed. This may have been fixed already though. Not sure.
</blockquote></details>

If I remember correctly this bug was because the daemon regarded the `Exiting` state (when OpenVPN is shutting down but did not yet die) as `DISCONNECTED`. This was fixed, so it is now regarded as `CONNECTED` until the `Exiting` state is done. So hopefully this should not be a problem here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[mullvad-cli/src/cmds/status.rs, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247#-LG-Ntnj3RYDWSK0rTFQ:-LG-VmVtD7pTMwiQlcKQ:b9rufn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb96dc99c3a7659e6611e3b85288c7ab2b5964e3/mullvad-cli/src/cmds/status.rs#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If I remember correctly this bug was because the daemon regarded the `Exiting` state (when OpenVPN is shutting down but did not yet die) as `DISCONNECTED`. This was fixed, so it is now regarded as `CONNECTED` until the `Exiting` state is done. So hopefully this should not be a problem here.
</blockquote></details>

Great thanks @faern for confirming this :+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247)*

**Pull request merged**
