### PR TITLE
Migrate LocationDataSource from traditional to diffable

### PR DESCRIPTION
**Pull request by rablador**
Since we dropped iOS 12, we can move on and use modern classes to handle and animate changes in collections.

This PR is about migration from traditional UITableViewDataSource to modern UITableViewDiffableDataSource and NSDiffableDataSourceSnapshot.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/LocationDataSource.swift` line 222 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQztUOI1y4rNmLsSs6e:-NQztUOI1y4rNmLsSs6f:b8z2sfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L222)):*
> ```Swift
> 
>         updateCellFactory(with: nodeByLocation)
>         updateDataSnapshot(with: locationList, animated: true) { [weak self] in
> ```

`animated` flag should be passed in place of `true` for `animated` arg.
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 231 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzt7BYCZF50RuWdGKi:-NQzt7BZ7ZVq1Ljd67he:bagwlv1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L231)):*
> ```Swift
>                 self?.tableView.scrollToRow(
>                     at: lastInsertedIndexPath,
>                     at: .bottom,
> ```

How does it work when you expand USA for example? Previously we used to scroll to the top item when there are way too many items within the expanded sub-list.
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzvSvF5AyGfK9CfvbI:-NQzvSvF5AyGfK9CfvbJ:bsdkat0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L239)):*
> ```Swift
> 
>     private func item(for indexPath: IndexPath) -> LocationDataSourceItemProtocol? {
>         return nodeByLocation[snapshot().itemIdentifiers[indexPath.row]]
> ```

wouldn't be cheaper to use `itemIdentifier(for:)`?

https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3255154-itemidentifier
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 243 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzvrhnA0ucycYgUs3R:-NQzvrhnA0ucycYgUs3S:bwtktgf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L243)):*
> ```Swift
> 
>     override func indexPath(for location: RelayLocation) -> IndexPath? {
>         return snapshot().itemIdentifiers.firstIndex(where: { $0 == location }).flatMap { index in
> ```

`indexPath(for: location)` should work right?

https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3255151-indexpath
___
*[`ios/MullvadVPN/SelectLocationViewController.swift` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzuTps0atyWLyuT4WI:-NQzuTps0atyWLyuT4WJ:b-lr32tc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/SelectLocationViewController.swift#L22)):*
> ```Swift
> 
> class SelectLocationViewController: UIViewController, UITableViewDelegate {
>     static let cellReuseIdentifier = LocationDataSource.CellReuseIdentifiers.locationCell.rawValue
> ```

You should probably this static constant. Do we need it for something?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462)* status: all files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/LocationDataSource.swift` line 164 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzwS4-7l9ZKyyJeRbP:-NQzwS409CRi7WQSKeyy:bypwpp9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L164)):*
> ```Swift
> 
>     func indexPathForSelectedRelay() -> IndexPath? {
>         if let location = selectedRelayLocation {
> ```

Nit: could simplify that as:

```swift
return selectedRelayLocation.flatMap { indexPath(for: $0) }
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/LocationDataSource.swift` line 164 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzwS4-7l9ZKyyJeRbP:-NR3-zh07CvwwLnszcA0:bysng9f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L164)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: could simplify that as:

```swift
return selectedRelayLocation.flatMap { indexPath(for: $0) }
```
</blockquote></details>

Agreed 👍
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 222 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQztUOI1y4rNmLsSs6e:-NR2xjD8-Ty75uD6Xa-Q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L222)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`animated` flag should be passed in place of `true` for `animated` arg.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 231 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzt7BYCZF50RuWdGKi:-NR3KcBR-eM3UFoaS9O2:b-agvhwh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L231)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

How does it work when you expand USA for example? Previously we used to scroll to the top item when there are way too many items within the expanded sub-list.
</blockquote></details>

Was kind of expecting the same behavior regardless of list length, but now that I've compared it to the previous behavior I agree with you. Fix added for long lists.
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzvSvF5AyGfK9CfvbI:-NR32zEaA4r1MwmTN-fv:bceuwb4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L239)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

wouldn't be cheaper to use `itemIdentifier(for:)`?

https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3255154-itemidentifier
</blockquote></details>

For sure!
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 243 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzvrhnA0ucycYgUs3R:-NR353-3AOMIcRlhpx6-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/LocationDataSource.swift#L243)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`indexPath(for: location)` should work right?

https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource/3255151-indexpath
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SelectLocationViewController.swift` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-NQzuTps0atyWLyuT4WI:-NR3LFAEBsRrTWHKXhGK:b-hudqc2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c017c8da6f2c7152b10035851b318baff8425f5/ios/MullvadVPN/SelectLocationViewController.swift#L22)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You should probably this static constant. Do we need it for something?
</blockquote></details>

Removed, along with some other obsolete code.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462#-:-NR7nVCWBgTWyQapqmDU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
