### PR TITLE
Make use of material icons

### PR DESCRIPTION
**Pull request by Rawa**
Move to usage of Material Icons

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
Needs to do a minified build and check for apk size

> Reviewed 81 of 81 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884#-:-O825dcE2bDpEvRnamZ5:bp90bj3)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/gradle/libs.versions.toml` line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884#-O825OXFBlYJOf-rZYWM:-O825OXGEJztQtJBMjNh:b-3r6g2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b229d0ceaef2eec7a2a6c7744138cc3d152c01cb/android/gradle/libs.versions.toml#L158)):*
> ```TOML
> # Compose
> compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
> ```

Newline added by mistake?

**Review by Rawa — COMMENTED** [review]
Test build can be found here, it is the same size as before:
https://releases.mullvad.net/android/builds/2024.4-dev-4d5a2e%2Bandroid-material-icons/

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884#-:-O85xVBj4ZfiXt7suhId:b-jwzcau)* status: 79 of 82 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/gradle/libs.versions.toml` line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884#-O825OXFBlYJOf-rZYWM:-O85mYfkDMr5ULZPiaX3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b229d0ceaef2eec7a2a6c7744138cc3d152c01cb/android/gradle/libs.versions.toml#L158)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Newline added by mistake?
</blockquote></details>

Done.

**Review by Pururun — DISMISSED** [review]
Great

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884#-:-O869hDY6GXg33tjlOCy:b-87hbi0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6884#-:-O86Clys7ieiW7gslK8y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
