### PR TITLE
Update elliptic, @eslint/plugin-kit and cross-spawn to non-vulnerable versions

### PR DESCRIPTION
**Pull request by raksooo**
This PR updates these dependencies due to them having known vulnerabilities. All changes to `package-lock.json` were generated by `npm audit fix`. The osv-scanner ignore for `elliptic` has also been removed. None of these vulnerabilities affected the app or users.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7191)

### CODE REVIEW

**Comment by raksooo** [comment]
Turns out the update of `@eslint/plugin-kit` is incompatible with the current version of `typescript-eslint`: https://github.com/typescript-eslint/typescript-eslint/issues/10338

According to the comments a fix will be out in a few days.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7191#-:-OC2MvVt6GAei5mKRIPD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by olmoh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7191#-:-OC2Q6wVCt4FiK7DZwH8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7191)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
