### PR TITLE
Add malware dns blocking

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds malware block setting to both the Daemon, CLI and GUI.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 8 files at r2, 5 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245)* status: 10 of 20 files reviewed, 1 unresolved discussion (waiting on @dlon and @raksooo)

___
*[mullvad-daemon/src/lib.rs, line 845 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245#-Mt3j0EfASEBvZgV9Elj:-Mt3j0EfASEBvZgV9Elk:bdbmbka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a6627163c0ff9e264ed5a46a7553724265b6f34/mullvad-daemon/src/lib.rs#L845)):*
> ```XML
>                 }
> 
>                 if use_blocking_ip {
> ```

Maybe this should just check if `last_byte != 0`.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245)* status: 9 of 20 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 845 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245#-Mt3j0EfASEBvZgV9Elj:-Mt7oiFS9uIfBMo-fSMe:b8f1lm9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a6627163c0ff9e264ed5a46a7553724265b6f34/mullvad-daemon/src/lib.rs#L845)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe this should just check if `last_byte != 0`.
</blockquote></details>

I did that at first.. But that relies on all `DNS_*_IP_BIT`s to be non-zero for it to work. So I avoided doing that.. But I realize now that it would basically be a bug to have any of those constants be zero anyway, it would be bad for other reasons. So I adapted your proposal.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 15 files at r3, 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 16 files at r6, 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
