### PR TITLE
Only store a single account number in the history

### PR DESCRIPTION
**Pull request by dlon**
Overview of changes:
* The account history only contains the last used account. It is only used to remember the most recently used account when logged out. `AccountHistory` doesn't do any key management.
* The WireGuard key and addresses are stored in the settings.
* The file permissions of `settings.json` are set to `600` due to the change mentioned in the previous point.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 1235 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKFwUtDQm-3WdDdFLx:-McKFwUtDQm-3WdDdFLy:b2zn50l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L1235)):*
> ```XML
>                             .notify_key_event(KeygenEvent::NewKey(public_key));
>                         if is_first_key {
>                             self.ensure_key_rotation().await;
> ```

What's the risk for always ensuring that the key is rotated?
___
*[mullvad-daemon/src/lib.rs, line 1573 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKGyvcCYcY065nYYzg:-McKGyvd1KwZGkkqh4J1:b-cqircq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L1573)):*
> ```XML
>             self.account_history
>                 .get()
>                 .map(|token| vec![token])
> ```

Should this RPC not be changed to only return the last account that was used?

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 1573 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKGyvcCYcY065nYYzg:-McKNkbI1jyd8RZV3Bw-:b-70ppir) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L1573)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this RPC not be changed to only return the last account that was used?
</blockquote></details>

More precisely, it should be changed to return a single account rather than a list of accounts.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 583 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKOCcFDMTUCYNdglQb:-McKOCcFDMTUCYNdglQc:b3p7nkb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L583)):*
> ```XML
>         );
>         tokio::spawn(version_updater.run());
>         let mut account_history = account_history::AccountHistory::new(&cache_dir, &settings_dir)
> ```

The creation of account history and migration could be put into an async function that takes the directories and the settings struct as parameters.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 583 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKOCcFDMTUCYNdglQb:-McNvsGZ9XiE8Sh-FVAQ:b-x6bf19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L583)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The creation of account history and migration could be put into an async function that takes the directories and the settings struct as parameters. 
</blockquote></details>

Do you think this belongs in `AccountHistory` or this file?
___
*[mullvad-daemon/src/lib.rs, line 1235 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKFwUtDQm-3WdDdFLx:-McNucwB9N9Wk32Wci-I:be25nj2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L1235)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What's the risk for always ensuring that the key is rotated?
</blockquote></details>

No real risk, I think. It just resets the rotation task unnecessarily.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 583 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKOCcFDMTUCYNdglQb:-McOt7Hz9rLVD1jtLxeJ:b-n2yuom) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L583)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do you think this belongs in `AccountHistory` or this file?
</blockquote></details>

I think `AccountHistory` is as good a place as any.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 10 of 31 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 583 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKOCcFDMTUCYNdglQb:-McP2D6E6FsqDrO2R34J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L583)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think `AccountHistory` is as good a place as any.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/lib.rs, line 1573 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McKGyvcCYcY065nYYzg:-McP2Dk30YpTGCxP0x89:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7111937254c71bc0015419fbacae10bdb43775b2/mullvad-daemon/src/lib.rs#L1573)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

More precisely, it should be changed to return a single account rather than a list of accounts.
</blockquote></details>

Done.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 14 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 24 of 31 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[gui/src/renderer/components/Login.tsx, line 328 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McP8QXQ2iq50dpmqMa_:-McP8QXR0qwl5RJ60r79:b-1mfu01) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11cccfc4b480148c16a8f6cd8e4ab8758e6e395b/gui/src/renderer/components/Login.tsx#L328)):*
> ```XML
>   const label = formatAccountToken(token);
>   return (
>     <>
> ```

@raksooo Is the surrounding  `<>` element really required here?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 26 of 31 files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 6 of 21 files at r2, 7 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 23 of 34 files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[gui/src/main/index.ts, line 1166 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPVyXG2nJ9zf_QnJrg:-McPVyXG2nJ9zf_QnJrh:bsb5otb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11cccfc4b480148c16a8f6cd8e4ab8758e6e395b/gui/src/main/index.ts#L1166)):*
> ```XML
>       const args = ['collect', '--output', reportPath];
>       if (toRedact) {
>         args.push('--redact', toRedact!);
> ```

`!` isn't needed since the if-statement makes sure that `toRedact` has a value.
___
*[gui/src/renderer/components/Login.tsx, line 328 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McP8QXQ2iq50dpmqMa_:-McPZh2WDzMXy7iG-XEt:bozusd5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11cccfc4b480148c16a8f6cd8e4ab8758e6e395b/gui/src/renderer/components/Login.tsx#L328)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

@raksooo Is the surrounding  `<>` element really required here?
</blockquote></details>

@pinkisemils That's correct. IIRC it was there before to make the typechecker happy, although it wasn't really needed. Since the contents isn't an array anymore this should work fine without `<>`. 
___
*[gui/src/renderer/components/Login.tsx, line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPXt4J3PQIhs81TCuc:-McPXt4J3PQIhs81TCud:b-859qha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L211)):*
> ```XML
> 
>   private shouldShowAccountHistory() {
>     return this.allowInteraction() && this.state.isActive && !!this.props.accountHistory;
> ```

I'm not a big fan of converting truthy/falsy values to a bool when there are multiple possible falsy values. In this situation it isn't very intuitive that this corresponds to `this.props.accountHistory !== undefined && this.props.accountHistory !== ""`. I can imagine that if someone refactors/rewrites this in some other way in the future they could miss the empty string case. Although I've probably done this many times myself and it results in less code so I'll let you decide.
___
*[gui/src/renderer/components/Login.tsx, line 291 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPaODs6pUJt-RtXhl-:-McPaODs6pUJt-RtXhl0:b3knkm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L291)):*
> ```XML
>             <StyledAccountDropdownContainer>
>               <AccountDropdown
>                 item={this.props.accountHistory!}
> ```

I try to avoid the non-null assertion operator. Instead of making this assumption here I think it would make more sense to set the default value of `accountHistory` to the empty string in the redux reducer instead.

If you would replace the empty string with an optional/undefined, then the simplest way to handle this would probably be to just return `null` in `AccountDropdown` if `accountHistory === undefined`.
___
*[gui/src/renderer/components/Login.tsx, line 330 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McP_n4T0qLWgqj_TPqx:-McP_n4T0qLWgqj_TPqy:bwqia3d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L330)):*
> ```XML
>     <>
>       <AccountDropdownItem
>         key={token}
> ```

`key` isn't needed anymore either since it was used to help react keep track of which array element is which before.
___
*[gui/src/renderer/containers/SupportPage.tsx, line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPcc9j5QYNC2ES4AIg:-McPcc9j5QYNC2ES4AIh:b-j6181f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/containers/SupportPage.tsx#L13)):*
> ```XML
>   defaultEmail: state.support.email,
>   defaultMessage: state.support.message,
>   account: state.account.accountToken,
> ```

Why not use `accountHistory` here? This would only work while logged in.
___
*[mullvad-management-interface/proto/management_interface.proto, line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPUaUH9BMYj48aBxtC:-McPUaUI3P_HdizWZCPU:b-z9ml2g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11cccfc4b480148c16a8f6cd8e4ab8758e6e395b/mullvad-management-interface/proto/management_interface.proto#L49)):*
> ```protobuf
> 	rpc SetAccount(google.protobuf.StringValue) returns (google.protobuf.Empty) {}
> 	rpc GetAccountData(google.protobuf.StringValue) returns (AccountData) {}
> 	rpc GetAccountHistory(google.protobuf.Empty) returns (google.protobuf.StringValue) {}
> ```

I tried it out and noticed that if there is no history then this returns an empty string. Wouldn't it be better to make this optional?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 14 of 34 files reviewed, 4 unresolved discussions (waiting on @pinkisemils and @raksooo)

___
*[gui/src/main/index.ts, line 1166 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPVyXG2nJ9zf_QnJrg:-McTFXuA7qkTm_kj84pZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11cccfc4b480148c16a8f6cd8e4ab8758e6e395b/gui/src/main/index.ts#L1166)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

`!` isn't needed since the if-statement makes sure that `toRedact` has a value.
</blockquote></details>

Done.
___
*[gui/src/renderer/components/Login.tsx, line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPXt4J3PQIhs81TCuc:-McTEtPt9WMHES3l-QeX:bctpdcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L211)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I'm not a big fan of converting truthy/falsy values to a bool when there are multiple possible falsy values. In this situation it isn't very intuitive that this corresponds to `this.props.accountHistory !== undefined && this.props.accountHistory !== ""`. I can imagine that if someone refactors/rewrites this in some other way in the future they could miss the empty string case. Although I've probably done this many times myself and it results in less code so I'll let you decide.
</blockquote></details>

Makes sense. Done.
___
*[gui/src/renderer/components/Login.tsx, line 291 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPaODs6pUJt-RtXhl-:-McTF2twC8LWa-W2kR8H:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L291)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I try to avoid the non-null assertion operator. Instead of making this assumption here I think it would make more sense to set the default value of `accountHistory` to the empty string in the redux reducer instead.

If you would replace the empty string with an optional/undefined, then the simplest way to handle this would probably be to just return `null` in `AccountDropdown` if `accountHistory === undefined`.
</blockquote></details>

Done.
___
*[mullvad-management-interface/proto/management_interface.proto, line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPUaUH9BMYj48aBxtC:-McTFCDJ8DVDUj_9uYnD:bn570qa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11cccfc4b480148c16a8f6cd8e4ab8758e6e395b/mullvad-management-interface/proto/management_interface.proto#L49)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I tried it out and noticed that if there is no history then this returns an empty string. Wouldn't it be better to make this optional?
</blockquote></details>

Yes. Fixed, though I made it return 404 instead.
___
*[gui/src/renderer/containers/SupportPage.tsx, line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPcc9j5QYNC2ES4AIg:-McTF_1006XkHp6wbvBe:bye9n9u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/containers/SupportPage.tsx#L13)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Why not use `accountHistory` here? This would only work while logged in.
</blockquote></details>

Fixed! I didn't think about the fact that you can send problem reports when logged out. The reason was that the history was potentially empty. It was only updated when switching between accounts or logging out, but I've changed that.

**Review by raksooo — COMMENTED** [review]
> Reviewed 6 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 20 of 34 files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @raksooo)

___
*[gui/src/renderer/components/Login.tsx, line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPXt4J3PQIhs81TCuc:-McTHubAAGpji-8CAxLu:b-1ah3mt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L211)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Makes sense. Done.
</blockquote></details>

Since you changed the daemon response to 404 and made `daemon-rpc.ts` return `undefined` instead of `""` you shouldn't need the the empty string check anymore :slightly_smiling_face:

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 21 of 34 files reviewed, 2 unresolved discussions (waiting on @dlon, @pinkisemils, and @raksooo)

___
*[gui/src/renderer/containers/SupportPage.tsx, line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPcc9j5QYNC2ES4AIg:-McTJFQu8zFWoqVyp1aL:bwasv2h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/containers/SupportPage.tsx#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Fixed! I didn't think about the fact that you can send problem reports when logged out. The reason was that the history was potentially empty. It was only updated when switching between accounts or logging out, but I've changed that.
</blockquote></details>

Now when thinking about it. Shouldn't `mullvad-problem-report` redact everything that looks like an account number? If the user switches accounts the old account won't be redacted. This could of course have happened before this change as well, but might be more common now.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 21 of 34 files reviewed, 1 unresolved discussion (waiting on @pinkisemils and @raksooo)

___
*[gui/src/renderer/containers/SupportPage.tsx, line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPcc9j5QYNC2ES4AIg:-McTLMz0-M5-p6whX_JL:b-o34f9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/containers/SupportPage.tsx#L13)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Now when thinking about it. Shouldn't `mullvad-problem-report` redact everything that looks like an account number? If the user switches accounts the old account won't be redacted. This could of course have happened before this change as well, but might be more common now.
</blockquote></details>

Asked on Slack on was informed that all 16 digit numbers are redacted.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 8 of 18 files at r3, 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 30 of 34 files reviewed, 2 unresolved discussions (waiting on @dlon, @pinkisemils, and @raksooo)

___
*[mullvad-daemon/src/management_interface.rs, line 442 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McTOyF90-MeCmh7Gltv:-McTOyF90-MeCmh7Gltw:b-dtdvhl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0799c0cb3c1d0e37a233a0bf7bb3fcf9881c7b52/mullvad-daemon/src/management_interface.rs#L442)):*
> ```XML
>         match self.wait_for_result(rx).await? {
>             Some(history) => Ok(Response::new(history)),
>             None => Err(Status::not_found("history is empty")),
> ```

Does it have to be an error? Is an empty history invalid?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 29 of 34 files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @raksooo)

___
*[gui/src/renderer/components/Login.tsx, line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McPXt4J3PQIhs81TCuc:-McTQfLi4O_yA_Y5pESr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2de8584a4362ecb5b7981706ae0d7cca764d0a79/gui/src/renderer/components/Login.tsx#L211)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Since you changed the daemon response to 404 and made `daemon-rpc.ts` return `undefined` instead of `""` you shouldn't need the the empty string check anymore :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[mullvad-daemon/src/management_interface.rs, line 442 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McTOyF90-MeCmh7Gltv:-McTQiAb22Tu9r_6it_f:b-9jtqz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0799c0cb3c1d0e37a233a0bf7bb3fcf9881c7b52/mullvad-daemon/src/management_interface.rs#L442)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Does it have to be an error? Is an empty history invalid?
</blockquote></details>

It doesn't have to be, but I found it simpler than creating another message just to wrap a `StringValue`.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-:-McTSS8NCGrXIoIFXoYc:bnfp4nl)* status: 30 of 34 files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @raksooo)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 28 of 34 files reviewed, 1 unresolved discussion (waiting on @pinkisemils and @raksooo)

___
*[mullvad-daemon/src/management_interface.rs, line 442 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-McTOyF90-MeCmh7Gltv:-McTXdY7Cw4EYSNBbkqb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0799c0cb3c1d0e37a233a0bf7bb3fcf9881c7b52/mullvad-daemon/src/management_interface.rs#L442)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It doesn't have to be, but I found it simpler than creating another message just to wrap a `StringValue`.
</blockquote></details>

Done.

**Review by raksooo — COMMENTED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801)* status: 30 of 34 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 2 of 18 files at r3, 3 of 10 files at r4, 1 of 1 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2801#-:-McTqESgCMn0SkEtLmZC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
