### PR TITLE
New tunnel manager

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Move periodic key rotation into `TunnelManager`.
2. `TunnelManager` automatically listens `UIApplication.didBecomeActiveNotification` and reloads the tunnel state once the app becomes active again.
3. `TunnelManager` passes tunnel related errors to observers.
4. Move account token and tunnel settings into `TunnelInfo` struct and expose it via `TunnelManager.tunnelInfo`
4. Avoid sending IPC requests to the tunnel process in `connecting` state. Fixes the bug where the tunnel process ends up in `connecting` state indefinitely.
4. Pick relay in the main process and pass it over via `options`  to the tunnel process. This eliminates the need for obtaining that information when the tunnel is `connecting`, and makes the relay we're connecting to, immediately available for display in UI.
5. Add `ActionAfterDisconnect` which makes it possible to gracefully transition between `disconnecting` and `connecting` states. There is a temporary `pendingReconnect` state that the tunnel state machine enters once its fully `disconnected`.
6. Show either `Cancel` or `Secure connection` button when `disconnecting` which toggles the `ActionAfterDisconnect` between `nothing` and `reconnect`. This makes the UI a little more responsive, since the `disconnecting` state may sometimes last for a couple of seconds.
7. Request background task for majority of tunnel management related tasks.
8. Update `Account` to use new `TunnelManager` interface. 
9. Scope `WireGuardKit` & `NetworkExtension` imports to avoid importing types that aren't meant to be used in the main executable.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: 0 of 27 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/ConsolidatedApplicationLog.swift, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-Mk7CsYV247zvsjO_L5E:-Mk7CsYV247zvsjO_L5F:bduspnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47884b3376553475767332ea8cc49a5a86c148db/ios/MullvadVPN/ConsolidatedApplicationLog.swift#L70)):*
> ```Swift
>     func addLogFiles(fileURLs: [URL], includeLogBackups: Bool) {
>         for fileURL in fileURLs {
>             addLogFile(fileURL: fileURL, includeLogBackup: includeLogBackups)
> ```

FYI was a typo in the method name.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: 0 of 27 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-Mk7DEUr4_F6DYSJmh5k:-Mk7DEUr4_F6DYSJmh5l:b-41ev5z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/AppDelegate.swift#L26)):*
> ```Swift
> 
>     #if DEBUG
>     private let packetTunnelLogForwarder = LogStreamer<UTF8>(fileURLs: [ApplicationConfiguration.packetTunnelLogFileURL!])
> ```

FYI we removed it a while ago but I forgot to commit that change.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: 0 of 27 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-Mk7DLAr7ZLQlLQy5wDP:-Mk7DLAr7ZLQlLQy5wDQ:bo1hiqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/AppDelegate.swift#L43)):*
> ```Swift
>     }
>     private var relayConstraints: RelayConstraints?
>     private let alertPresenter = AlertPresenter()
> ```

FYI tunnel errors will be displayed in the banner.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: 0 of 27 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/ConnectViewController.swift, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-Mk7Dga_7hSOclmyqDtC:-Mk7Dga_7hSOclmyqDtD:blemvzu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/ConnectViewController.swift#L23)):*
> ```Swift
> protocol ConnectViewControllerDelegate: AnyObject {
>     func connectViewControllerShouldShowSelectLocationPicker(_ controller: ConnectViewController)
>     func connectViewControllerShouldConnectTunnel(_ controller: ConnectViewController)
> ```

FYI controllers call `TunnelManager` directly. Easier this way really.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/DisplayChainedError.swift, line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkBTofB9t_p7y9w-WSN:-MkBTofB9t_p7y9w-WSO:b-jv32tw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/DisplayChainedError.swift#L239)):*
> ```Swift
>             return nil
> 
>         case .verifyWireguardKey(let restError):
> ```

Can't this case happen anymore or why is it removed?
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 382 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkbA7Cq37RYNQB5XfUo:-MkbA7Cq37RYNQB5XfUp:bbyws2l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47884b3376553475767332ea8cc49a5a86c148db/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L382)):*
> ```Swift
>                         }
> 
>                         self.tunnelInfo = nil
> ```

Does this mean that the selected location and other settings will be reset on log out?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[ios/MullvadVPN/DisplayChainedError.swift, line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkBTofB9t_p7y9w-WSN:-MkfiPoM-uYnn0mFLWzi:bpguewq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/DisplayChainedError.swift#L239)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Can't this case happen anymore or why is it removed?
</blockquote></details>

The controller calls REST directly. We used to do that via `TunnelManager` but it really makes little sense.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 382 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkbA7Cq37RYNQB5XfUo:-MkfimTvEGYlEvxWtLPm:b-ac9sb5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47884b3376553475767332ea8cc49a5a86c148db/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L382)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Does this mean that the selected location and other settings will be reset on log out?
</blockquote></details>

Yeah very much everything is wiped, account token, tunnel settings stored in Keychain including relay constraint.

**Review by raksooo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/DisplayChainedError.swift, line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkBTofB9t_p7y9w-WSN:-MkkHpHo4q64rwQlMtTo:bdbj7f1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/DisplayChainedError.swift#L239)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Sorry, I meant to say the WireGuard keys controller
</blockquote></details>

Okay. I also noticed that `VERIFY_WIREGUARD_KEY_ERROR` is still defined in `TunnelManager.strings` but it isn't referenced anywhere.
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 382 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkbA7Cq37RYNQB5XfUo:-MkkIBhm-Wn_SCiA9_Oa:b-60jpyn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47884b3376553475767332ea8cc49a5a86c148db/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L382)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Yeah very much everything is wiped, account token, tunnel settings stored in Keychain including relay constraint.
</blockquote></details>

Okay, is this how we want the app to work? In the desktop app we keep the settings when switching accounts. I understand that this behavior isn't new in this PR so I'll mark this discussion as done.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 382 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkbA7Cq37RYNQB5XfUo:-MkkrPB28nT4aNzXCDDJ:br8kb9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47884b3376553475767332ea8cc49a5a86c148db/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L382)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Okay, is this how we want the app to work? In the desktop app we keep the settings when switching accounts. I understand that this behavior isn't new in this PR so I'll mark this discussion as done.
</blockquote></details>

That's a good point and definitely a topic for discussion. At the moment the entire configuration is stored in Keychain and bound by account token.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/DisplayChainedError.swift, line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkBTofB9t_p7y9w-WSN:-MklD7wd7yKuRK8-yj6s:b7qnxp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9157094f12dbfecda2c2cec6ed0d31a1dff31675/ios/MullvadVPN/DisplayChainedError.swift#L239)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Okay. I also noticed that `VERIFY_WIREGUARD_KEY_ERROR` is still defined in `TunnelManager.strings` but it isn't referenced anywhere.
</blockquote></details>

Good spot. Updated translations.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-:-MklEHHQDN_d4NOpSjW_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 382 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2977#-MkbA7Cq37RYNQB5XfUo:-MklECeWD3JxE0vHwRMg:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47884b3376553475767332ea8cc49a5a86c148db/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L382)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

That's a good point and definitely a topic for discussion. At the moment the entire configuration is stored in Keychain and bound by account token.
</blockquote></details>

Okay :+1:

**Pull request merged**
