### PR TITLE
Add data-driven TunnelSettingsUpdate type and method for atomically applying them...

### PR DESCRIPTION
**Pull request by acb-mv**
modify Preferences{Interactor,ViewController} to use these.

This means that for each preferences change, the tunnel gets recreated only once. It also gives us a data-driven type for modelling changes to the preferences, factoring code out of TunnelManager into a self-contained type.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
Asides from the changes @rablador mentioned, this looks good. 

2 things that don't appear in this PR but could be fixed here 

- :warning: Line Length Violation: Line should be 120 characters or less; currently it has 154 characters (line_length) in`PreferencesViewController:166`
- :warning: Function Body Length Violation: Function body should span 50 lines or less excluding comments and whitespace: currently spans 54 lines (function_body_length) in `PreferencesViewController:115` 

For the later one, we can just issue a `// swiftlint:disable:next function_body_length` directive

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809#-:-Nqa_Gtt4pUtT-0tNZui:b-xx0o99)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesInteractor.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809#-NqZ8k47A2ocp5M72gUg:-NqaXJv9BXIy8pmi9qqR:blgq41a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/990977e1cb0eabc5ce090d685b3f7cbb57da9c22/ios/MullvadVPN/View%20controllers/Preferences/PreferencesInteractor.swift#L43)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we keep this one around?
</blockquote></details>

Agreed, it looks like we can get rid of it

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesInteractor.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809#-NqZ8k47A2ocp5M72gUg:-Nqawp8uBKiqfkjSpG4E:b-a1mmmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/990977e1cb0eabc5ce090d685b3f7cbb57da9c22/ios/MullvadVPN/View%20controllers/Preferences/PreferencesInteractor.swift#L43)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Agreed, it looks like we can get rid of it
</blockquote></details>

It is my plan to replace other `set`methods with `updateSettings`before the PR gets promoted from draft.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809#-Nqbap_oBS-4awOU1gVb:-Nqbap_pBPxKyhKrtD6o:b-bpvs88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b941ab90e0dcedffde09c9fbd6902fb950acd40/ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift#L15)):*
> ```Swift
> 
> final class TunnelSettingsUpdateTests: XCTestCase {
>     override func setUpWithError() throws {
> ```

nit
If we don't intend to use those, we can remove them

**Review by rablador — APPROVED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5809)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
