### PR TITLE
Migrate in app notification banner to compose

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 24 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 24 of 27 files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWaSDMBcq0jjjisy8a:-NcWaSDMBcq0jjjisy8b:b8x0a6w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60febf2228da1534c57ce1dfea5f0235ef8c74b1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt#L90)):*
> ```Kotlin
>                     Intent.ACTION_VIEW,
>                     Uri.parse(
>                         requireContext()
> ```

The `context` is accessed both here and further down, but in different ways. I suggest unifying it.



_Code quote:_
```Kotlin
requireContext()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWaLJcAUGfJCt1fny8:-NcWaLJcAUGfJCt1fny9:b4zmlrp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60febf2228da1534c57ce1dfea5f0235ef8c74b1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt#L100)):*
> ```Kotlin
> 
>     private fun openAccountUrl() {
>         // TODO Move this to the viewmodel
> ```

Will this be done in in this PR?



_Code quote:_
```Kotlin
// TODO Move this to the viewmodel
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 44 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWotgDBjmZVKF9SIwq:-NcWotgDBjmZVKF9SIwr:b-fkklk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L44)):*
> ```Kotlin
>     private val serviceConnectionManager: ServiceConnectionManager,
>     private val isVersionInfoNotificationEnabled: Boolean =
>         BuildConfig.ENABLE_IN_APP_VERSION_NOTIFICATIONS,
> ```

I believe we should try to avoid BuildConfig values outside of the koin setup if/where possible to make the code more readable. I also don't believe we need a default value here since the caller should always explicitly define whether version notifications should be shown.



_Code quote:_
```Kotlin
BuildConfig.ENABLE_IN_APP_VERSION_NOTIFICATIONS
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWoRzt6gu_2KefCVJX:-NcWoRzt6gu_2KefCVJY:b-41ewes) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L143)):*
> ```Kotlin
>         callbackFlowFromNotifier(this.onStateChange)
> 
>     private fun calculateNotificationState(
> ```

I suggest renaming to something like `evaluateNotificationState` since it's not a typical calculation.



_Code quote:_
```Kotlin
calculateNotificationState
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWo3-S1hu2Md3lq7y2:-NcWo3-S1hu2Md3lq7y3:b-7olw9p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L168)):*
> ```Kotlin
>         }
> 
>     private fun AccountExpiry.shouldShowNotification(): Boolean {
> ```

I suggest renaming to `isCloseToExpiring`



_Code quote:_
```Kotlin
shouldShowNotification
```

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 24 of 27 files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcXYN160O1BQaOYndey:-NcXYN160O1BQaOYndez:b219t7y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L31)):*
> ```Kotlin
> 
> @Composable
> fun ConnectionStatusText(state: TunnelState, modifier: Modifier = Modifier) {
> ```

Would it be possible to avoid passing along `Modifier` in so many places? Perhaps we can structure things differently to avoid that?



_Code quote:_
```Kotlin
modifier: Modifier = Modifier
```

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 21 of 29 files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcXYN160O1BQaOYndey:-Ncb-JJYCVtqQ19TETB_:b-gpr82i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would it be possible to avoid passing along `Modifier` in so many places? Perhaps we can structure things differently to avoid that?
</blockquote></details>

I'm asking since I'm concerned that we might be missing something in terms of to best structure things, but if this is the preferred compose way we should ofc keep it

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcXYN160O1BQaOYndey:-NcbtuIw-195hO4LGvsw:b-4pl03c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm asking since I'm concerned that we might be missing something in terms of to best structure things, but if this is the preferred compose way we should ofc keep it
</blockquote></details>

I could just remove it since it's no longer used.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWaSDMBcq0jjjisy8a:-NcbyEiN0fzv8mpY92NB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60febf2228da1534c57ce1dfea5f0235ef8c74b1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt#L90)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The `context` is accessed both here and further down, but in different ways. I suggest unifying it.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 44 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWotgDBjmZVKF9SIwq:-NcbyD26AISFHDWrjMBE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L44)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we should try to avoid BuildConfig values outside of the koin setup if/where possible to make the code more readable. I also don't believe we need a default value here since the caller should always explicitly define whether version notifications should be shown.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWoRzt6gu_2KefCVJX:-NcbyCNN78by7UVU3WaT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L143)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to something like `evaluateNotificationState` since it's not a typical calculation.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWo3-S1hu2Md3lq7y2:-NcbyAbsDMbfvKaaofiO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L168)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `isCloseToExpiring`
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 16 of 29 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcXYN160O1BQaOYndey:-Ncc6uKS6aOJZLmDzcz9:buqwym9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L31)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I could just remove it since it's no longer used.
</blockquote></details>

It was used for resize animations, but that was bugged so I disabled it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcWaLJcAUGfJCt1fny8:-Ncc7-ke7JGMMVn0tw4U:be9xmx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60febf2228da1534c57ce1dfea5f0235ef8c74b1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt#L100)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Will this be done in in this PR?
</blockquote></details>

Added a new commit for it.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r3, 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 28 of 29 files reviewed, 8 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt` line 818 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfnRQM6_vcF_l-KCM0:-NcfnRQM6_vcF_l-KCM1:b-3ahjbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt#L818)):*
> ```Kotlin
>         composeTestRule.apply {
>             onNodeWithText("UNSECURED CONNECTION").assertDoesNotExist()
>             onNodeWithText("Secure my connection").assertDoesNotExist()
> ```

Can we assert this in a more reliable way?



_Code quote:_
```Kotlin
            onNodeWithText("UNSECURED CONNECTION").assertDoesNotExist()
            onNodeWithText("Secure my connection").assertDoesNotExist()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcXYN160O1BQaOYndey:-NcfkhTm9qdwjnlQ1Ysp:boojpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L31)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It was used for resize animations, but that was bugged so I disabled it.
</blockquote></details>

Still seem to be there or perhaps I'm misunderstanding :thinking: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt` line 126 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-Ncfp6LKCQAAW0S9YJqO:-Ncfp6LKCQAAW0S9YJqP:b-ered77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt#L126)):*
> ```Kotlin
>             )
>         }
>         else -> {}
> ```

I suggest explicitly checking if it's the hide state here rather than having an `else` catch. I also suggest adding a comment to clarify why the block is empty.



_Code quote:_
```Kotlin
 else -> {}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt` line 170 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfpjCs-emDvN_C80tX:-NcfpjCs-emDvN_C80tY:b-y5mg4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt#L170)):*
> ```Kotlin
>                         bottom.linkTo(textTitle.bottom)
>                     }
>         ) {}
> ```

Why is this block empty?



_Code quote:_
```Kotlin
{}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 48 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfiG5D815gGCCtLSNa:-NcfiG5D815gGCCtLSNb:bqtbemh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L48)):*
> ```Kotlin
> class ConnectViewModel(
>     private val serviceConnectionManager: ServiceConnectionManager,
>     accountRepository: AccountRepository,
> ```

I suggest moving this to the bottom of the argument list for better readability



_Code quote:_
```Kotlin
accountRepository: AccountRepository,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 200 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcflAym7-r0ENlx4jFB:-NcflAym7-r0ENlx4jFC:b-y4iubr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L200)):*
> ```Kotlin
>     }
> 
>     fun onShowAccountClick() {
> ```

I suggest renaming to `onManageAccountClick`



_Code quote:_
```Kotlin
onShowAccountClick
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 211 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfiR2B-uyVk3v7I6VE:-NcfiR2B-uyVk3v7I6VF:b-2i5933) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L211)):*
> ```Kotlin
> 
>     sealed interface ViewAction {
>         data class OpenAccountView(val token: String) : ViewAction
> ```

I believe we should rename this to something like `OpenAccountManagementPageInBrowser` to clarify that it's not the "regular" in-app account view. It would also be nice to make sure the same is done for any other occurance (e.g. `AccountViewModel`).



_Code quote:_
```Kotlin
OpenAccountView
```
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 75 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfkWuZCXfq2bW0JTeL:-NcfkWuZCXfq2bW0JTeM:byp4v6y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L75)):*
> ```Kotlin
>         inversePrimary = MullvadGreen,
>         error = MullvadRed,
>         errorContainer = Color(0xFFFFD323),
> ```

Is there a reason for not defining this in the color file?



_Code quote:_
```Kotlin
Color(0xFFFFD323)
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 21 of 31 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt` line 818 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfnRQM6_vcF_l-KCM0:-Nd-eiq85mBhXICelN1-:bz2k672) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt#L818)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we assert this in a more reliable way?
</blockquote></details>

Replaced it with a tag on the whole screen.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcXYN160O1BQaOYndey:-Nd-Se1tBq1dEf9QZkgh:ba59h77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73d31f836ad3aa9c2fb7375b858fb93b508818f8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Still seem to be there or perhaps I'm misunderstanding :thinking:
</blockquote></details>

Sorry what I meant to say was that I added the Modifier to be able to call `Modifier.animateContentSize` from the screen. I removed that call since it caused weird behaviour when combined with animated visibility. Since we are no longer using the modifier from the screen we can just remove that from the public function and all internal functions.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt` line 126 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-Ncfp6LKCQAAW0S9YJqO:-Nd-XsTW7kcZ4S-7oBCa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt#L126)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest explicitly checking if it's the hide state here rather than having an `else` catch. I also suggest adding a comment to clarify why the block is empty.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt` line 170 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfpjCs-emDvN_C80tX:-Nd-XdHe5cnff85QiN_d:bbc9c17) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt#L170)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why is this block empty?
</blockquote></details>

Seems to have been added by mistake, I'll remove it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 48 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfiG5D815gGCCtLSNa:-Nd-Xu7q1d8vpgSy31mE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L48)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest moving this to the bottom of the argument list for better readability
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 200 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcflAym7-r0ENlx4jFB:-Nd-YqxOAYZoKXBqa1EN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L200)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `onManageAccountClick`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 211 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfiR2B-uyVk3v7I6VE:-Nd-YriI2ivGLkERtXiw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L211)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we should rename this to something like `OpenAccountManagementPageInBrowser` to clarify that it's not the "regular" in-app account view. It would also be nice to make sure the same is done for any other occurance (e.g. `AccountViewModel`).
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 20 of 33 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 75 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NcfkWuZCXfq2bW0JTeL:-Nd-yovf5lUAc3y7XFIc:bvxd35n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fa54c4b4d67489f26e59a60b7f9f4f98027b06/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L75)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a reason for not defining this in the color file?
</blockquote></details>

No seems to be an oversight. Fixed.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 7 of 10 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 30 of 33 files reviewed, 1 unresolved discussion

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 10 files at r8, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt` line 148 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NdZxVaUBdYaJLj8ZhPK:-NdZxVaUBdYaJLj8ZhPL:b-xbd3xh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/623ff4d57a370db46d350d53d77af801bbd51152/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt#L148)):*
> ```Kotlin
>             }
>         }
>     data?.let {
> ```

nit: I suggest renaming `data` to something like `notificationData`



_Code quote:_
```Kotlin
data
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903)* status: 31 of 33 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt` line 148 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4903#-NdZxVaUBdYaJLj8ZhPK:-Nd_cMV-3etaYfxcOeMs:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/623ff4d57a370db46d350d53d77af801bbd51152/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt#L148)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest renaming `data` to something like `notificationData`
</blockquote></details>

Done

**Pull request merged**
