### PR TITLE
Refactor REST client

### PR DESCRIPTION
**Pull request by dlon**
This PR refactors parts of `mullvad-rpc`:
* Generalize `TcpStream` into `AbortableStream`.
* Encapsulate socket closure code in `HttpsConnectorWithSni`.
* Move TLS config to new `TlsStream` type which can be used with any stream.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 0 of 7 files reviewed, 1 unresolved discussion

___
*[mullvad-rpc/src/abortable_stream.rs, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuAdxX46yZ-YoFDVdRD:-MuAdxX46yZ-YoFDVdRE:b-jkovq8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d9af0effd6000a63d367ef3b14764e5b534ec897/mullvad-rpc/src/abortable_stream.rs#L52)):*
> ```XML
>                 let inner = { inner_lock.lock().unwrap().take() };
>                 if let Some(mut inner) = inner {
>                     if let Err(error) = inner.stream.shutdown().await {
> ```

I think that this only calls `shutdown(., SHUT_WR)`, but presumably dropping the stream itself closes the socket.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 3 of 7 files reviewed, 1 unresolved discussion

___
*[mullvad-rpc/src/abortable_stream.rs, line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBZWdf62uhPnwOAdLZ:-MuBZWdf62uhPnwOAdL_:bfoai6i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L26)):*
> ```XML
> }
> 
> pub struct AbortableStream<S: AsyncRead + AsyncWrite + Connection + Unpin> {
> ```

This struct could do with some tests to properly test it's behavior.
___
*[mullvad-rpc/src/abortable_stream.rs, line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBZP7w5wHUDYJfbIPt:-MuBZP7w5wHUDYJfbIPu:bgcpdxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L109)):*
> ```XML
>         self.do_stream(
>             |stream| Pin::new(stream).poll_flush(cx),
>             Poll::Ready(Ok(())),
> ```

Should a flush not error out if the socket is already closed?

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-rpc/src/tls_stream.rs, line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBi4zp1ANfqV1GDVgr:-MuBi4zq-5dYivJ_uGVB:bo3jh8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/tls_stream.rs#L37)):*
> ```XML
>                     .with_root_certificates(read_cert_store())
>                     .with_no_client_auth();
>                 //config.alpn_protocols = vec![b"h2".to_vec()];
> ```

This line probably doesn't belong here.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuBsF9gEgM9dDxKXkD2:b-9e6pt6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
> ```XML
> 
> pub struct AbortableStream<S: AsyncRead + AsyncWrite + Connection + Unpin> {
>     inner: Arc<Mutex<Option<StreamInner<S>>>>,
> ```

Instead of putting the stream into an Option, could the Abortable stream not just do the equivalent of a `select!` between a oneshot channel and the socket in all the `AsyncRead` and `AsyncWrite` implementations. Then you can elide the mutex and arc. Then, you'd have a `AbortableStream{ inner: S, shutdown_rx: Option<oneshot::Receiver<()>> }`. 

I'm not sure if this is something we definitely need to do though, might be more complicated. But it kind of seems like you're doing half of this anyway.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuBuFcS7b-2znqKqjRh:b3prg8o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Instead of putting the stream into an Option, could the Abortable stream not just do the equivalent of a `select!` between a oneshot channel and the socket in all the `AsyncRead` and `AsyncWrite` implementations. Then you can elide the mutex and arc. Then, you'd have a `AbortableStream{ inner: S, shutdown_rx: Option<oneshot::Receiver<()>> }`. 

I'm not sure if this is something we definitely need to do though, might be more complicated. But it kind of seems like you're doing half of this anyway.
</blockquote></details>

In fact, the inner stream can be optional too, to allow for closing the inner socket before the AbortableStream is dropped.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuCH0yz9o__vZjsaCVk:b6wciij) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

In fact, the inner stream can be optional too, to allow for closing the inner socket before the AbortableStream is dropped.
</blockquote></details>

Good suggestions! It's far simpler now. I got rid of the explicit shutdown as well, as the sockets are gone according to `lsof`.
___
*[mullvad-rpc/src/abortable_stream.rs, line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBZP7w5wHUDYJfbIPt:-MuCHYwg0BP-0lp3Y_sr:b-byjxso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L109)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should a flush not error out if the socket is already closed?
</blockquote></details>

Done. I don't think it can hurt to do so.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuCJYuUEYakuhKiZDbS:b-vvtdby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Good suggestions! It's far simpler now. I got rid of the explicit shutdown as well, as the sockets are gone according to `lsof`.
</blockquote></details>

...Though, that might be because the `AbortableStream` itself is dropped. So this is probably kind of wrong without your suggestion to make the inner socket optional.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-rpc/src/tls_stream.rs, line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBi4zp1ANfqV1GDVgr:-MuCMCmO0O6aScUHKF5u:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/tls_stream.rs#L37)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This line probably doesn't belong here.
</blockquote></details>

Done.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuDL8WdCN7og2gTYl4i:bpz8ixl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

...Though, that might be because the `AbortableStream` itself is dropped. So this is probably kind of wrong without your suggestion to make the inner socket optional.
</blockquote></details>

Does `shutdown_tx` need to be stored inside `AbortableStream` at all?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuFOlaJ65EFhU600t7k:bem8ky6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Does `shutdown_tx` need to be stored inside `AbortableStream` at all? 
</blockquote></details>

I think so. We need it to remove the abort handle from the map in `HttpsConnectorWithSniHandle`. `TcpStream` did the same thing, really. It has nothing to do with `shutdown_rx`, though, so the name might be bad.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuFyEvHCzqLb7RonEBe:bxtzppo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think so. We need it to remove the abort handle from the map in `HttpsConnectorWithSniHandle`. `TcpStream` did the same thing, really. It has nothing to do with `shutdown_rx`, though, so the name might be bad.
</blockquote></details>

The name could be better, but, and I'm sure you know this feeling, I struggle to come up with a better name. I think just documenting the field would be very helpful.
___
*[mullvad-rpc/src/https_client_with_sni.rs, line 181 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuFyz9fE5p8W3EGMKW0:-MuFyz9fE5p8W3EGMKW1:bwaxj8e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/https_client_with_sni.rs#L181)):*
> ```XML
> 
>     fn poll_ready(&mut self, _: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
>         Poll::Ready(Ok(()))
> ```

I wonder if more locks could be elided by instead doing the blocking.  But the shutdown channel should probably register with the waker before the connection is returned.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[mullvad-rpc/src/abortable_stream.rs, line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuBsF9gEgM9dDxKXkD1:-MuGHSoX19G8YmMeyxLd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7007757f5835e8737c35fe906e6141c418b2df4f/mullvad-rpc/src/abortable_stream.rs#L27)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The name could be better, but, and I'm sure you know this feeling, I struggle to come up with a better name. I think just documenting the field would be very helpful.
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[mullvad-rpc/src/abortable_stream.rs, line 26 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuGKPdT0BhhoA0E77WI:-MuGKPdT0BhhoA0E77WJ:b90e3y3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52e5a44c0f8b2cd3685fc077bb110afda1d29f8e/mullvad-rpc/src/abortable_stream.rs#L26)):*
> ```XML
>             let _ = tx.send(());
>         }
>         if let Some(tx) = self.notify_tx.lock().unwrap().take() {
> ```

Without this, the `AbortableStream` must be polled before the sending happens. But maybe that is fine/correct? I only noticed this when writing unit tests.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[mullvad-rpc/src/https_client_with_sni.rs, line 45 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285#-MuGR0BKEKcngzC06RL4:-MuGR0BKEKcngzC06RL5:bghphs8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52e5a44c0f8b2cd3685fc077bb110afda1d29f8e/mullvad-rpc/src/https_client_with_sni.rs#L45)):*
> ```XML
> impl HttpsConnectorWithSniHandle {
>     /// Stop all streams produced by this connector
>     pub fn reset(&self) {
> ```

Maybe this should be added to the connector itself instead, since it is supposed to be a cloneable handle anyway.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3285)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
