### PR TITLE
Add coordinators and app router

### PR DESCRIPTION
**Pull request by pronebird**
1. Re-structure Xcode project, categorizes code into different subfolders.
2. Introduce coordinator pattern. All objects coordinating VC presentation should subclass from `Coordinator`. 

    Coordinators capable of presenting other child coordinators modally should conform to `Presenting` protocol and all coordinators capable of being presented modally should conform to `Presentable`. 
     
     Interactive dismissal is handled properly and children are removed automatically from their parent when that happens. 
3. Introduce `ApplicationRouter` capable of doing conditional navigation. This is essential given that device state may change at any time and so sometimes we need to ignore navigation or postpone it. It understands interactive dismissal when coordinators it presents conform to `Presentable`.
4. Add custom formsheet presentation, so that we could customize modal presentation with settings cog without using nasty hacks. So full control over the presentation at the expense of having to implement formsheet ourselves.

Worth to note:

- Settings cog is not blocked when logging in. I just didn't get to it. It doesn't break anything but maybe we should fix that
- Reworked login controller a bit and used custom Promise there. Perhaps we could improve that part.
- Haven't tested out of time part all that much. Navigation works fine when revoking device.
 

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460)* status: 0 of 201 files reviewed, 10 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/SceneDelegate.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR2UzV42J62MVb2isln:-NR2UzV42J62MVb2islo:b-2whswn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/SceneDelegate.swift#L179)):*
> ```Swift
>                 "ALERT_TITLE",
>                 tableName: "SettingsMigrationUI",
>                 value: "Settings migration erfror",
> ```

"erfror"
___
*[`ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR2YA8r2kg2V42gGzIE:-NR2YA8r2kg2V42gGzIF:b-lix7op) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Containers/Navigation/UINavigationBar%2BAppearance.swift#L31)):*
> ```Swift
> 
>     func configureCustomAppeareance() {
>         var margins = layoutMargins
> ```

`layoutMargins` is mutable and can be modified directly. Since iOS11, however, we should use `directionalLayoutMargins` instead.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 291 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7uCNV7wTiODmgJhGJ:-NR7uCNV7wTiODmgJhGK:b-ep3q3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L291)):*
> ```Swift
>         router.dismissAll(.primary, animated: false)
> 
>         continueFlow(animated: true)
> ```

If we call `continueFlow` without animations we can get a logout flow that's similar to the current logout flow. See comment in `ApplicationCoordinator.presentSettings` below.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 417 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR3Z5Hs4hJWSkKtpAiF:-NR3Z5Hs4hJWSkKtpAiG:b4ui3v4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L417)):*
> ```Swift
>             guard let self = self else { return }
> 
>             self.logoutRevokedDevice()
> ```

Seeing as we only do one thing here, `self?.logoutRevokedDevice()` seems cleaner.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 537 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7t1mdBnqjsomw7RnD:-NR7t1mdBnqjsomw7RnE:b-f5yf5p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L537)):*
> ```Swift
> 
>         coordinator.didFinish = { [weak self] coordinator, reason in
>             self?.router.dismissAll(.settings, animated: true)
> ```

Calling `didLogout` (and subsequently calling `continueFlow` without animations) before dismissing the settings group will give us a similar behavior to the current flow. Ie you land directly on the login screen when the modal has been dismissed rather than first on an empty map and then navigate to login.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 265 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR3kjzR6X4L9QuQSKT0:-NR3kjzR6X4L9QuQSKT1:b-c2z5h1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L265)):*
> ```Swift
> protocol ApplicationRouterDelegate: AnyObject {
>     /**
>      Delegate should present the route pass corresponding `Coordinator` upon completion.
> ```

"and pass"
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 390 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR3s5NJCfMLFxmhp-Lo:-NR3s5NJCfMLFxmhp-Lp:bt63bpn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L390)):*
> ```Swift
>          */
>         if route.supportsSubNavigation, modalStack.contains(route.routeGroup) {
>             var presentedRoute = presentedRoutes[route.routeGroup]!.first!
> ```

Is this safe? presentedRoutes seem to generally be handled with more care elsewhere in the code.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 661 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7cUoD2nq44ujFgxbg:-NR7cUoD2nq44ujFgxbh:b-zc7x4a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L661)):*
> ```Swift
>                 modalStack.append(group)
>             } else {
>                 modalStack.insert(group, at: 0)
> ```

Why is added it to the modal stack if it isn't modal?
___
*[`ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7oqqJ6KDajCBIfemP:-NR7oqqJ6KDajCBIfemQ:b1dr0a3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift#L67)):*
> ```Swift
>         )
> 
>         navigationController.setViewControllers([controller], animated: false)
> ```

Could perhaps be to .pushViewController(makeViewController) instead, making it consistent with how the other coordinators look.
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7zE1x8kqGZP1Q9rs-:-NR7zE1x8kqGZP1Q9rs0:b7gxznu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L54)):*
> ```Swift
>         let preferredContentSize = presentedViewController.preferredContentSize
> 
>         assert(preferredContentSize.width > 0 && preferredContentSize.height > 0)
> ```

This can be substituted with call to function `targetFrame` below.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460)* status: 0 of 201 files reviewed, 10 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 661 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7cUoD2nq44ujFgxbg:-NR8D3bn6s-bJWLya935:b-wl1zxo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L661)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why is added it to the modal stack if it isn't modal?
</blockquote></details>

It's modal on iPad but not on iPhone. That's simpler this way.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460)* status: 0 of 201 files reviewed, 10 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/SceneDelegate.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR2UzV42J62MVb2isln:-NR8JceI5djwzZHothPw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/SceneDelegate.swift#L179)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"erfror"
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR2YA8r2kg2V42gGzIE:-NR8HeNA5i2ZY9VhP1DM:b-yj9j2g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Containers/Navigation/UINavigationBar%2BAppearance.swift#L31)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`layoutMargins` is mutable and can be modified directly. Since iOS11, however, we should use `directionalLayoutMargins` instead.
</blockquote></details>

`layoutMargins` is a value type (`UIEdgeInsets`). Do you reckon that mutating each individual field in a value type won't trigger a series of `layoutMarginsDidChange` when mutating it?

To answer the second part of your comment. We'd have to switch from `UIEdgeInsets` to `NSDirectionalEdgeInsets` in UIMetrics. As trivial as it is, I would really rather not do that as a part of this PR as it would affect nearly every VC in the app.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 291 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7uCNV7wTiODmgJhGJ:-NR8MurQDhHGSwBlmlf7:b-wdl8h7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L291)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

If we call `continueFlow` without animations we can get a logout flow that's similar to the current logout flow. See comment in `ApplicationCoordinator.presentSettings` below.
</blockquote></details>

Not on iPad.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 417 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR3Z5Hs4hJWSkKtpAiF:-NR8Hd7TE7BcVjr5stkn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L417)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Seeing as we only do one thing here, `self?.logoutRevokedDevice()` seems cleaner.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 537 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7t1mdBnqjsomw7RnD:-NR8KGOfD8DALORwa5TQ:b-qbbxx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L537)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Calling `didLogout` (and subsequently calling `continueFlow` without animations) before dismissing the settings group will give us a similar behavior to the current flow. Ie you land directly on the login screen when the modal has been dismissed rather than first on an empty map and then navigate to login.
</blockquote></details>

Not on iPad in regular environment, where Login appears modally after settings are dismissed. However I think the best would be to simply disable controls from disappearing on iPhone and iPad in compact width to avoid a blank map issue.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 265 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR3kjzR6X4L9QuQSKT0:-NR8JSCf7NSEB5N8lcB2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L265)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"and pass"
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 390 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR3s5NJCfMLFxmhp-Lo:-NR8JX-l7waHgoJZqRY8:b-o9sy6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L390)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is this safe? presentedRoutes seem to generally be handled with more care elsewhere in the code.
</blockquote></details>

Despite how ugly it looks, `presentedRoutes` should have at least one route in it when `modalStack` indicates that it has a certain coordination group presented.  I have moved that `var` into `if` statement.
___
*[`ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7oqqJ6KDajCBIfemP:-NR8DNbu8ReFJOv4YzGj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift#L67)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Could perhaps be to .pushViewController(makeViewController) instead, making it consistent with how the other coordinators look.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7zE1x8kqGZP1Q9rs-:-NR8Gn9D3Dhk-8vxt-RM:b-ibav9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L54)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This can be substituted with call to function `targetFrame` below.
</blockquote></details>

`targetFrame` is not used any longer. Removed the function.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460)* status: 0 of 202 files reviewed, 10 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 537 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7t1mdBnqjsomw7RnD:-NR8PycOAoe32RDSMuyW:b-sgc1ro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L537)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not on iPad in regular environment, where Login appears modally after settings are dismissed. However I think the best would be to simply disable controls from disappearing on iPhone and iPad in compact width to avoid a blank map issue.
</blockquote></details>

Let's resolve that in a separate PR. No big deal that it looks blank in compact environment.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460)* status: 0 of 202 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR2YA8r2kg2V42gGzIE:-NR8ZcywDVIf-9LGJljR:b29pwpa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Containers/Navigation/UINavigationBar%2BAppearance.swift#L31)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`layoutMargins` is a value type (`UIEdgeInsets`). Do you reckon that mutating each individual field in a value type won't trigger a series of `layoutMarginsDidChange` when mutating it?

To answer the second part of your comment. We'd have to switch from `UIEdgeInsets` to `NSDirectionalEdgeInsets` in UIMetrics. As trivial as it is, I would really rather not do that as a part of this PR as it would affect nearly every VC in the app.
</blockquote></details>

1. Hmm, I don't know, but you might very well be right. Let's keep it as it is.
2. Sure!
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 537 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4460#-NR7t1mdBnqjsomw7RnD:-NR8_5tx6HGMDvC3imDK:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffb4f5ad02d246d7b1dfe00a81b5fc023bb984aa/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L537)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Let's resolve that in a separate PR. No big deal that it looks blank in compact environment.
</blockquote></details>

👍

**Pull request merged**
