### PR TITLE
Sort device list by age

### PR DESCRIPTION
**Pull request by dlon**
Changes:
* Sort devices chronologically (oldest first) in the "Too many devices" view
* Sort devices chronologically when calling `mullvad list-devices`.
* Show device creation in CLI device list.
* Add `hijack_dns` and `created` fields to `device.json`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-:-N2uE2W14X4DyQp7MrfF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`CHANGELOG.md` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uC3-X4KCatMlmgm2s:-N2uC3-X4KCatMlmgm2t:b-hsmiqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/CHANGELOG.md#L28)):*
Can we be slightly more clear please? Currently it's not clear from this entry alone what the timestamp is about.

> Add device creation timestamp to the CLI's device list

?
___
*[`CHANGELOG.md` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uB56A98c1WubC5sUW:-N2uB56B3nKqx3c2siMW:b-pwkduo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/CHANGELOG.md#L31)):*
I'd argue that "age, descending order" is somewhat ambiguous. Is an old age a big or a small value? The age is large, but the creation timestamp is smaller. I don't think we have used the word "age" anywhere else? How about something like:

> List devices on an account by creation date, oldest to newest, instead of alphabetically

?
___
*[`mullvad-daemon/src/device/mod.rs` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uDXMt36kf2C6E-m9W:-N2uDXMt36kf2C6E-m9X:b-nvil8z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/mullvad-daemon/src/device/mod.rs#L162)):*
> ```XML
>     #[serde(default)]
>     pub hijack_dns: bool,
>     #[serde(default = "Utc::now")]
> ```

I think we should add comments to both these serde-default lines explaining that they are semi-temporary to avoid migration code. That the default values does not really make much sense, but having the values be wrong is not critical, so it's better than needing migration code.
___
*[`mullvad-daemon/src/device/service.rs` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uRGHsE2CWH3KN3mmv:-N2uRGHsE2CWH3KN3mmw:bq51chv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27c633a45e4968c1da0b342d251624aa37bbc59/mullvad-daemon/src/device/service.rs#L112)):*
> ```XML
>         account_token: AccountToken,
>         device_id: DeviceId,
>     ) -> Result<(Device, Vec<Device>), Error> {
> ```

As discussed AFK: Let's simplify this return type to `Result<Vec<Device>>`. None of the frontends actually use the returned removed `Device`, and it makes the code messier by having to come up with a fake device.

Later we probably want to simplify this further. Instead of broadcasting a new list of remaining devices to frontends on delete we probably just want to broadcast the removed device ID. If the frontends want state they can hold it themselves, and if they want an updated list they can ask the daemon for the new list on this event. This remove event should not need to execute a list devices RPC call.

**Review by faern — COMMENTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: 8 of 16 files reviewed, 4 unresolved discussions (waiting on @faern and @pronebird)

___
*[`CHANGELOG.md` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uC3-X4KCatMlmgm2s:-N2uXI9W3YEq-UxmT-KE:b-77hqbi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/CHANGELOG.md#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we be slightly more clear please? Currently it's not clear from this entry alone what the timestamp is about.

> Add device creation timestamp to the CLI's device list

?
</blockquote></details>

Is this better? It's added for the current device as well, not just lists, so I didn't use your exact description.
___
*[`CHANGELOG.md` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uB56A98c1WubC5sUW:-N2uXdOG3UnVjHyFEVNK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/CHANGELOG.md#L31)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'd argue that "age, descending order" is somewhat ambiguous. Is an old age a big or a small value? The age is large, but the creation timestamp is smaller. I don't think we have used the word "age" anywhere else? How about something like:

> List devices on an account by creation date, oldest to newest, instead of alphabetically

?
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/device/mod.rs` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uDXMt36kf2C6E-m9W:-N2uXgAY-Xrjc6W4zmja:bx1ma98) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/mullvad-daemon/src/device/mod.rs#L162)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should add comments to both these serde-default lines explaining that they are semi-temporary to avoid migration code. That the default values does not really make much sense, but having the values be wrong is not critical, so it's better than needing migration code.
</blockquote></details>

Setting `hijack_dns` to `false` is correct, as it is always disabled at the moment. Does it still need a comment in your opinion?
___
*[`mullvad-daemon/src/device/service.rs` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uRGHsE2CWH3KN3mmv:-N2uY3xv0MJor0zGAW7E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27c633a45e4968c1da0b342d251624aa37bbc59/mullvad-daemon/src/device/service.rs#L112)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As discussed AFK: Let's simplify this return type to `Result<Vec<Device>>`. None of the frontends actually use the returned removed `Device`, and it makes the code messier by having to come up with a fake device.

Later we probably want to simplify this further. Instead of broadcasting a new list of remaining devices to frontends on delete we probably just want to broadcast the removed device ID. If the frontends want state they can hold it themselves, and if they want an updated list they can ask the daemon for the new list on this event. This remove event should not need to execute a list devices RPC call.
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1, 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @pronebird)

___
*[`CHANGELOG.md` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uC3-X4KCatMlmgm2s:-N2uYgod1qTLIkek6U3m:brxp9sd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/CHANGELOG.md#L28)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this better? It's added for the current device as well, not just lists, so I didn't use your exact description.
</blockquote></details>

Sounds good!
___
*[`mullvad-daemon/src/device/mod.rs` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uDXMt36kf2C6E-m9W:-N2uYx5Q9OQxeUw1Hel5:bf9kgoq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/mullvad-daemon/src/device/mod.rs#L162)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Setting `hijack_dns` to `false` is correct, as it is always disabled at the moment. Does it still need a comment in your opinion?
</blockquote></details>

Yes, because it's still a hack due to the fact that everyone upgrading from `2022.2-beta1` will be missing the field, but everyone else is expected to have it. So I don't think we should keep these serde-default modifiers forever. They can probably be removed in a few versions when almost no one is using the current beta still. So I think these should be `FIXME` comments so they are easier to find. And should probably explicitly say to be removed when not very many use `2022.2-beta1` on desktop.
___
*[`mullvad-daemon/src/device/service.rs` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uRGHsE2CWH3KN3mmv:-N2uZYy1ASwRp-6jIuUG:b-i5yu6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27c633a45e4968c1da0b342d251624aa37bbc59/mullvad-daemon/src/device/service.rs#L112)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

SO NICE!

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @pronebird)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @faern and @pronebird)

___
*[`mullvad-daemon/src/device/mod.rs` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611#-N2uDXMt36kf2C6E-m9W:-N2ub3kE0dLpSCtnzlJs:bfybtlx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795346a642dc8d8e271d6700578bfd505749645b/mullvad-daemon/src/device/mod.rs#L162)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes, because it's still a hack due to the fact that everyone upgrading from `2022.2-beta1` will be missing the field, but everyone else is expected to have it. So I don't think we should keep these serde-default modifiers forever. They can probably be removed in a few versions when almost no one is using the current beta still. So I think these should be `FIXME` comments so they are easier to find. And should probably explicitly say to be removed when not very many use `2022.2-beta1` on desktop.
</blockquote></details>

Done. Unfortunately, this is very verbose.

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 3 of 8 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
