### PR TITLE
Refactor port dialog to use a view model

### PR DESCRIPTION
**Pull request by kl**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R42dfC-6pk0Vyo4NK:-O6R42dfC-6pk0Vyo4NL:b-1rp68b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt#L42)):*
> ```Kotlin
>     @SuppressLint("ComposableNaming")
>     @Composable
>     private fun testWireguardCustomPortDialog(
> ```

Would look clearer for me if it is called `createtWireguardCustomPortDialog` instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R5UA50SUoPbWCrt9a:-O6R5UA50SUoPbWCrt9b:bmybjt9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt#L21)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.util.inAnyOf
> 
> class WireguardCustomPortDialogViewModel(
> ```

Since we have added a ViewModel, maybe we should also make the calls to settings here as well?

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)* status: all files reviewed, 4 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R42dfC-6pk0Vyo4NK:-O6R6WA9ALsf3ykuF_YL:bovqrvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt#L42)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Would look clearer for me if it is called `createtWireguardCustomPortDialog` instead.
</blockquote></details>

`createt`, you mean `set`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R03Ma6M_t6oSTuB8F:-O6R03Ma6M_t6oSTuB8G:b-6w3ntf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt#L57)):*
> ```Kotlin
>     fun onSaveClick(portValue: String) =
>         viewModelScope.launch(dispatcher) {
>             val port = Port.fromString(portValue).getOrNull() ?: return@launch
> ```

We should validate the port here, this would fail otherwise. Right now if the user enters a invalid port, presses submit on keyboard, and this function will be called and we will Complete with an invalid port, thus resulting in an invalid port being set.

I think it would be nice to validate the input in one function:

```
fun validatePort(input: String): Either<PortValidationError, Port> = either {
    val port = Port.fromString(input).mapLeft { ... }.bind()
    ensure(port.inAnyOf(allowedPortRanges)) { ... }.bind()
}
```

However, right now we don't display any errors in this dialog so maybe a simpler function can be used instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R60q87IF2OhvByhl6:-O6R60q87IF2OhvByhl7:bcjw8ib) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt#L69)):*
> ```Kotlin
> 
> sealed interface WireguardCustomPortDialogSideEffect {
>     data class Complete(val port: Port?) : WireguardCustomPortDialogSideEffect
> ```

To me `Complete` can be the result of either success or fail, maybe `Success` is more accurate?

**Review by Rawa — COMMENTED** [review]
In general very nice! Good job! :muscle: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-:-O6R6htv1-adTMKNTn-N:bczdrsw)* status: all files reviewed, 4 unresolved discussions (waiting on @kl and @Pururun)

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)* status: all files reviewed, 4 unresolved discussions (waiting on @kl and @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R42dfC-6pk0Vyo4NK:-O6R76fm1hjuZF2q5GcC:b-n3ehzf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt#L42)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`createt`, you mean `set`?
</blockquote></details>

I meant `create` but `set` works for me as well.

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R42dfC-6pk0Vyo4NK:-O6RF91T46c37-NZtGEE:bwf3gf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt#L42)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I meant `create` but `set` works for me as well.
</blockquote></details>

We also have for example `fun testMtuDialog` so to be consistent should we change that as well?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R5UA50SUoPbWCrt9a:-O6REN9P6S14HZU42DQh:b-3irecd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt#L21)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Since we have added a ViewModel, maybe we should also make the calls to settings here as well?
</blockquote></details>

Because we already have the Repository save logic in the VpnSettingsViewModel it is better to keep the save logic in one place.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R03Ma6M_t6oSTuB8F:-O6RGGN426-vs-7PuNHj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should validate the port here, this would fail otherwise. Right now if the user enters a invalid port, presses submit on keyboard, and this function will be called and we will Complete with an invalid port, thus resulting in an invalid port being set.

I think it would be nice to validate the input in one function:

```
fun validatePort(input: String): Either<PortValidationError, Port> = either {
    val port = Port.fromString(input).mapLeft { ... }.bind()
    ensure(port.inAnyOf(allowedPortRanges)) { ... }.bind()
}
```

However, right now we don't display any errors in this dialog so maybe a simpler function can be used instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R60q87IF2OhvByhl6:-O6RGDwV2xTU_7mlZe_6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt#L69)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

To me `Complete` can be the result of either success or fail, maybe `Success` is more accurate?
</blockquote></details>

Done.

**Review by Pururun — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-:-O6SX7ePDSzAyRGpgxeC:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-O6R42dfC-6pk0Vyo4NK:-O6SX0qU4iKNyKsi_NuJ:bqdiwke) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a971ff7bdcaf97c6c24cb9f4a8c9a71ea8e3a10/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt#L42)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

We also have for example `fun testMtuDialog` so to be consistent should we change that as well?
</blockquote></details>

Hmm yes that is true. I guess we can keep it as it is now.

**Review by Rawa — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-:-O6u-LGj7SUEY88LaEfe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-:-O6uQAPa4Y_GzL0JLnp0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
Seems like a merge commit is included by mistake?

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779#-:-O6z8E825MY2qB_S_FUB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
