### PR TITLE
Correctly handle removal & disabling of access method

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR aims to fix a few holes in the logic of enabling/disabling/removing access methods in different edge cases.

* If the access method currently in-use is disabled → Switch to the next available access method
* If the last enabled access method is removed → Enable the direct access method and switch to it
* If the last enabled access method is currently in-use and removed → Enable the direct access method and switch to it

This logic can somewhat be simplified by restructuring the access methods part of the settings datastructure to always include the predefined `Direct` and `Mullvad Bridges` access methods. Piggybacking on the settings migration started by the [custom OpenVPN SOCKS5 bridge PR](https://github.com/mullvad/mullvadvpn-app/pull/5587), this PR alters the layout of the serialized access method settings accordingly.

This PR also fixes DES-547

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 4 files at r2, 1 of 2 files at r3, 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/access_method.rs` line 181 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NovjyCg5zQ5S1W_uTBZ:-NovjyCh7TWLCCBAgR6t:b-kd3xwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/853db69743250840cd2ce8955f0c3c18b96acd11/mullvad-daemon/src/access_method.rs#L181)):*
> ```XML
>                 *access_method = access_method_update.clone();
>             }
>             ensure_direct_is_enabled(settings);
> ```

Although this is fine, I think it would be nicer if it it were impossible for the collection itself to end up in an "invalid" state (e.g. no enabled methods) instead of expecting the client to make sure that this is the case (discussed offline).
___
*[`mullvad-management-interface/src/types/conversions/access_method.rs` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NovpuAX5TYp357fOaBK:-NovpuAY0UczBj8oY9c7:b-hp3bdr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/853db69743250840cd2ce8955f0c3c18b96acd11/mullvad-management-interface/src/types/conversions/access_method.rs#L14)):*
> ```XML
>                 mullvad_bridges: Some(settings.mullvad_bridges.into()),
>                 access_method_settings: settings
>                     .user_defined
> ```

Nit: Would be slightly nicer to stick to *either* "custom" or "user-defined" (but only use one of them).

**Comment by MarkusPettersson98** [comment]
@raksooo Please have a look at the modifications made in `gui/` :blush:

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 11 of 18 files reviewed, 3 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`gui/src/shared/daemon-rpc-types.ts` line 532 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NpLKJgk8HhzY0d2-4nF:-NpLKJgk8HhzY0d2-4nG:b-4rhwvk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bef60443f7f1aae405eddba9b7b4fc9a11362e40/gui/src/shared/daemon-rpc-types.ts#L532)):*
> ```XML
> export type ApiAccessMethodSettings = {
>   direct: AccessMethodSetting;
>   mullvad_bridges: AccessMethodSetting;
> ```

I thought the linter would complain about this, I'll have to look into it. We use camelCase for variables and object properties.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @dlon and @raksooo)

___
*[`mullvad-daemon/src/access_method.rs` line 181 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NovjyCg5zQ5S1W_uTBZ:-NpOWGxVEdt7UBh2CAdw:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/853db69743250840cd2ce8955f0c3c18b96acd11/mullvad-daemon/src/access_method.rs#L181)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Although this is fine, I think it would be nicer if it it were impossible for the collection itself to end up in an "invalid" state (e.g. no enabled methods) instead of expecting the client to make sure that this is the case (discussed offline).
</blockquote></details>

Done
___
*[`mullvad-management-interface/src/types/conversions/access_method.rs` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NovpuAX5TYp357fOaBK:-NpOWI7_At9vq8Cpumqs:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/853db69743250840cd2ce8955f0c3c18b96acd11/mullvad-management-interface/src/types/conversions/access_method.rs#L14)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Would be slightly nicer to stick to *either* "custom" or "user-defined" (but only use one of them).
</blockquote></details>

Done

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 5 of 21 files reviewed, 1 unresolved discussion (waiting on @dlon and @raksooo)

___
*[`gui/src/shared/daemon-rpc-types.ts` line 532 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NpLKJgk8HhzY0d2-4nF:-NpO_iBR3dgUKGIjW39K:br1vzj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bef60443f7f1aae405eddba9b7b4fc9a11362e40/gui/src/shared/daemon-rpc-types.ts#L532)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I thought the linter would complain about this, I'll have to look into it. We use camelCase for variables and object properties.
</blockquote></details>

Done

Added a rule to cover this to the ESLint config

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 6 files at r5, 7 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 12 of 21 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98 and @raksooo)

___
*[`mullvad-daemon/src/access_method.rs` line 181 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NovjyCg5zQ5S1W_uTBZ:-NpOjg0A-7TqG2u5AWpc:b903kkx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/853db69743250840cd2ce8955f0c3c18b96acd11/mullvad-daemon/src/access_method.rs#L181)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Awesome :)
___
*[`mullvad-types/src/access_method.rs` line 35 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NpOj9ud49bh7paKVGXZ:-NpOj9ud49bh7paKVGX_:bf99hqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e2b3d559810e3260b5e72b9d974f26c9cfeaef2/mullvad-types/src/access_method.rs#L35)):*
> ```XML
>     /// This function will return an error if a built-in API access is about to
>     /// be removed.
>     pub fn remove(&mut self, api_access_method: &Id) -> Result<(), Error> {
> ```

Do we need to check if the enabled collection is empty here as well? In case the only active (non-builtin) method is deleted.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 11 of 21 files reviewed, 2 unresolved discussions (waiting on @dlon and @raksooo)

___
*[`mullvad-types/src/access_method.rs` line 35 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NpOj9ud49bh7paKVGXZ:-NpOlFod-Dkttdj51LTT:bx0z48f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e2b3d559810e3260b5e72b9d974f26c9cfeaef2/mullvad-types/src/access_method.rs#L35)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we need to check if the enabled collection is empty here as well? In case the only active (non-builtin) method is deleted.
</blockquote></details>

Hmm, your are right. We used to have this check when a custom access was deleted. Re-added!

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 13 files at r8, 8 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`gui/src/shared/daemon-rpc-types.ts` line 532 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NpLKJgk8HhzY0d2-4nF:-NpOmfElAEXIhkMBSgdx:b-a9ohj3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bef60443f7f1aae405eddba9b7b4fc9a11362e40/gui/src/shared/daemon-rpc-types.ts#L532)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Done

Added a rule to cover this to the ESLint config
</blockquote></details>

Great! :+1:

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[`mullvad-daemon/src/api.rs` line 433 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695#-NpQ5ILV7CPNJ_4jhM2-:-NpTdBBxAkdmH4cJr5Q6:bqh79qd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808d2807826e10f4ef56d1b7a5e7b023e495ac48/mullvad-daemon/src/api.rs#L433)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This might be unnecessary given that we always use modulo before using the index?
</blockquote></details>

It _might_ be unnecessary, given that we rotate the access method when removing access methods which is the case I'm guarding for here. Removing this piece of code since I don't think it accomplishes anything :blush:

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @raksooo)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 5 files at r11, 1 of 1 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5695)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
