### PR TITLE
Update text and indentation for DNS content blockers

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 125 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWBfh4o0LHmZbusPMVk:-NWDIrBq66ZC5wThYGRI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff07d2fa92a57bc199a61c0394328f6e0e964ff6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L125)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Afaik, it's usually a good practice to hoist logic like this in compose. For example, could it make sense to create multiple specialized versions of `SwitchComposeCell` that all use a (private version of) `SwitchComposeCell` with different arguments? In that case a `HeaderSwitchComposeCell` could for example set the `titleStyle` of the `SwitchComposeCell` etc. It would probably also reduce the amount of duplicate arguments when used in some places.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWBn61n6y_g2dElhMlI:-NWDIt5j0_GF0AiM4lY_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff07d2fa92a57bc199a61c0394328f6e0e964ff6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is probably not going to be content blocker specific, so I believe changing the name to something more generic would be a good idea
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWBhA8893vZbf7_UcoQ:-NWDIu3G337sAVTPzNMB:b-47mc66) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff07d2fa92a57bc199a61c0394328f6e0e964ff6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this only used for the hostname?
</blockquote></details>

It was from `dimensions.xml` but I changed it to a more generic one instead.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 40 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbOqGa-nFSPTqq5Kpc:-NWbOqGa-nFSPTqq5Kpd:bbapt82) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L40)):*
> ```Kotlin
>                     BaseCellTitle(
>                         title = "Header title",
>                         style = MaterialTheme.typography.titleMedium
> ```

Is it correct that the "Header" is bigger than the "Normal"
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbO1qY5xR04NnHqRG5:-NWbO1qY5xR04NnHqRG6:baora0q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L13)):*
> ```Kotlin
> fun SelectableCell(
>     title: String,
>     selected: Boolean,
> ```

I suggest `isSelected` to improve readability.



_Code quote:_
```Kotlin
selected
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbNwBQ9t02roSOhznt:-NWbNwBQ9t02roSOhznu:bqoob57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L17)):*
> ```Kotlin
>     startPadding: Dp = Dimens.indentedCellStartPadding,
>     selectedColor: Color = MaterialTheme.colorScheme.surface,
>     background: Color = MaterialTheme.colorScheme.secondaryContainer,
> ```

I suggest `backgroundColor` to keep it consistent with the `selectedColor`



_Code quote:_
```Kotlin
background
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 124 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbWByZB8rZlqpICLfz:-NWbWByZB8rZlqpICLg-:bjhiz6t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L124)):*
> ```Kotlin
> @ExperimentalMaterialApi
> @Composable
> fun VpnSettingsScreen(
> ```

The amount of arguments are extreme even for being compose :smile: The naming of the arguments are also quite inconsistent. I suggest sticking with the `Click` suffix for new click handlers. Would perhaps also be nice to switch for existing functions, but not necessarily a requirement for this PR.



_Code quote:_
```Kotlin
VpnSettingsScreen
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 40 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbOqGa-nFSPTqq5Kpc:-NWdKY6mDjnNuq8PYl0a:b-a8ala4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L40)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is it correct that the "Header" is bigger than the "Normal"
</blockquote></details>

Not sure what we want to call it, but yes it working as intended.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbO1qY5xR04NnHqRG5:-NWdKgbx3hNmLOwQfmog:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest `isSelected` to improve readability.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbNwBQ9t02roSOhznt:-NWdKhF5BoezB8Xj0d93:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest `backgroundColor` to keep it consistent with the `selectedColor`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 124 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727#-NWbWByZB8rZlqpICLfz:-NWdMWJQ0_5yc6SQs2AN:bb5x7sk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f01eea1f955ea64b67842ff0793c128cd6f8916/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L124)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The amount of arguments are extreme even for being compose :smile: The naming of the arguments are also quite inconsistent. I suggest sticking with the `Click` suffix for new click handlers. Would perhaps also be nice to switch for existing functions, but not necessarily a requirement for this PR.
</blockquote></details>

Changed to click

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)* status: all files reviewed, 1 unresolved discussion

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
