### PR TITLE
Add a new container view to wrap the whole location selection

### PR DESCRIPTION
**Pull request by rablador**
The wrapper should have a segmented control. The child will be updated through the wrapper, keeping most of the previous implementation intact.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-NwclG5C2zpMGA9EcHQA:-NwclG5D960xZmVLmceJ:b-30piqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7caa3455767fe65a8aa836eb8091ba78ce1813a8/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L66)):*
> ```Swift
>         navigationItem.largeTitleDisplayMode = .never
> 
>         navigationItem.title = NSLocalizedString(
> ```

We will probably want to have accessibility on those items if we don't want to break already existing UI Tests here.
Please Make sure you run the Custom Lists UI tests when you rebase from main.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-NwckP7S6eQBw4W1VFqe:-NwckP7S6eQBw4W1VFqf:b-1luvlj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7caa3455767fe65a8aa836eb8091ba78ce1813a8/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L102)):*
> ```Swift
> 
>         segmentedControl.insertSegment(withTitle: NSLocalizedString(
>             "SEGMENTED_CONTROL_ENTRY",
> ```

nit
Typically the `key` parameter of a localised string is used by translators to figure out the context.
Here, "segmented control" doesn't mean anything to a non engineer. 
Also it doesn't really matter that it's a segmented control, it could be anything. 
A more fitting name would probably be `"MULTIHOP_LABEL_ENTRY"` or something similar, that is more descriptive as to which element the localization pertains.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-NwclG5C2zpMGA9EcHQA:-NxCi2ob7NJCmCKGK2Uk:bwy6vi3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7caa3455767fe65a8aa836eb8091ba78ce1813a8/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L66)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We will probably want to have accessibility on those items if we don't want to break already existing UI Tests here.
Please Make sure you run the Custom Lists UI tests when you rebase from main.
</blockquote></details>

ID was added in main and custom list ui tests pass now.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift` line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-NwckP7S6eQBw4W1VFqe:-NxCjmbj7CwWmn8HHCq1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7caa3455767fe65a8aa836eb8091ba78ce1813a8/ios/MullvadVPN/View%20controllers/SelectLocation/LocationViewControllerWrapper.swift#L102)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Typically the `key` parameter of a localised string is used by translators to figure out the context.
Here, "segmented control" doesn't mean anything to a non engineer. 
Also it doesn't really matter that it's a segmented control, it could be anything. 
A more fitting name would probably be `"MULTIHOP_LABEL_ENTRY"` or something similar, that is more descriptive as to which element the localization pertains.
</blockquote></details>

Done.

**Review by acb-mv — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-:-NxY-cl-6Qwc2LYMLr-6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by mojganii — CHANGES_REQUESTED** [review]
while these changes aim to be merged into main, then we should show [select location view] with the previous design instead of the changes are coming with multi-hop like segment.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-:-NxY0Cp05DhLu7C4YxYU:bnlyo7m)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-:-NxkiWUq1HYtSxh9H3oQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
@mojganii If you run in mock release the segmented control will be hidden.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-:-Nxkp96x8cgVCFztljXH:beobna9)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @acb-mv and @buggmagnet)

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181#-:-NxkxrGXDE-erVdLpeEp:bnfp4nl)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @acb-mv and @buggmagnet)

**Pull request merged**
