### PR TITLE
Replace moment js

### PR DESCRIPTION
**Pull request by raksooo**
This PR removes moment.js due to it being considered to be a legacy project and since it caused us some issues with translations. The changes are:
* Upgrade TypeScript to 4.2.3, changelog: https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/
* Implemented helpers to add/subtract minutes/hours/days to JavaScript `Date` objects
* Switched to comparison operators when checking if a date is before or after another date, e.g. `expiry < new Date()`
* Implemented formatting of difference between two dates, e.g. `two days left` or `5 minutes ago`. This mostly reuses the translations from the Android app but also adds a few new ones.

I suggest starting the review with `date-helpers.ts` and `account-expiry.ts`.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 11 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/date-helper.ts, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXq5rfP55Tj3VpsW3tm:-MXq5rfP55Tj3VpsW3tn:b-7c1l0k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/date-helper.ts#L8)):*
Does it support overflows? MDN docs state:

> minutesValue
> An integer between 0 and 59, representing the minutes.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes
___
*[gui/src/shared/date-helper.ts, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXq8L9H1p6Ty4bkKf0K:-MXq8L9H1p6Ty4bkKf0L:buguwkn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/date-helper.ts#L18)):*
> ```XML
> }
> 
> export function modifyDays(date: DateType, days: number): Date {
> ```

You could refactor all three into one and avoid some code duplication, i.e:

```
enum DateComponent {
  day, hour, minute
}

function addComponent(date: DateType, component: DateComponent, value: number) {
    const modifiedDate = new Date(date)
    switch (component) {
         case DateComponent.day:
             modifiedDate.setDate(modifiedDate.getDate() + value)
         // and so forth...
    }
}
```

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging.ts, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXqAYb3AzRFL0-C4E6c:-MXqAYb3AzRFL0-C4E6d:b-qdk4jv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/logging.ts#L15)):*
> ```XML
> 
>   public log(level: LogLevel, ...data: unknown[]) {
>     const time = new Date().toISOString();
> ```

Would be great to maintain the same format we use across all of our apps, which was the one before. You could probably keep using `toISOString()`, just strip out the trailing `Z`

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @raksooo)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging.ts, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXqAYb3AzRFL0-C4E6c:-MXqBddCE6Ts5fJi9aY2:bocembz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/logging.ts#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Would be great to maintain the same format we use across all of our apps, which was the one before. You could probably keep using `toISOString()`, just strip out the trailing `Z`
</blockquote></details>

Also worth to note, and I am not sure, but I believe I use local time on iOS. `toISOString()` prints UTC. Not sure if relevant.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging.ts, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXqAYb3AzRFL0-C4E6c:-MXqE9hQAB4T9etIRbQU:b-esyg13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/logging.ts#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Also worth to note, and I am not sure, but I believe I use local time on iOS. `toISOString()` prints UTC. Not sure if relevant.
</blockquote></details>

Confirmed that we use local time on desktop too.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[gui/src/shared/date-helper.ts, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXq5rfP55Tj3VpsW3tm:-MXqOi9RDL-lwhfrQ13z:b-2jgqy5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/date-helper.ts#L8)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does it support overflows? MDN docs state:

> minutesValue
> An integer between 0 and 59, representing the minutes.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes

</blockquote></details>

Yes, and it's really handy when changing the date since we don't have to consider the number of days in a month.
___
*[gui/src/shared/date-helper.ts, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXq8L9H1p6Ty4bkKf0K:-MXqOyAU54vjcj9guntc:brgq1k0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/date-helper.ts#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could refactor all three into one and avoid some code duplication, i.e:

```
enum DateComponent {
  day, hour, minute
}

function addComponent(date: DateType, component: DateComponent, value: number) {
    const modifiedDate = new Date(date)
    switch (component) {
         case DateComponent.day:
             modifiedDate.setDate(modifiedDate.getDate() + value)
         // and so forth...
    }
}
```
</blockquote></details>

Sure. Done.
___
*[gui/src/shared/logging.ts, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXqAYb3AzRFL0-C4E6c:-MXqP0TA5cR4yik6ex5I:bbvzh2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92c9eaa781136afbfbd8a9e76204146c7e8269e4/gui/src/shared/logging.ts#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Confirmed that we use local time on desktop too.
</blockquote></details>

I've changed the implementation. It's more code but it's the correct format and in local time.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/shared/date-helper.ts, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXr_s2u8H34xvjVWXi_:-MXr_s2u8H34xvjVWXia:b-e80g8u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc799dd6fda997599caed50ceecd18e75580260c/gui/src/shared/date-helper.ts#L12)):*
> ```XML
> }
> 
> export function modifyDate(date: DateType, component: DateComponent, value: number) {
> ```

FYI I will leave it up to you but I think this method deserves to be called `dateByAddingComponent` (similar to how these kinds of things are named on iOS though)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/shared/logging.ts, line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXrbAOs-uSnWC8bSRau:-MXrbAOs-uSnWC8bSRav:b3p4d56) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc799dd6fda997599caed50ceecd18e75580260c/gui/src/shared/logging.ts#L45)):*
`String.padStart` may come handy as it does exactly that, i.e:

```
> "1".padStart(5, "0")
< "00001"
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/shared/date-helper.ts, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXr_s2u8H34xvjVWXi_:-MY6RW1X55Kqxd81NzXZ:burdvpa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc799dd6fda997599caed50ceecd18e75580260c/gui/src/shared/date-helper.ts#L12)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I will leave it up to you but I think this method deserves to be called `dateByAddingComponent` (similar to how these kinds of things are named on iOS though)
</blockquote></details>

I'm fine with both so I've changed.
___
*[gui/src/shared/logging.ts, line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-MXrbAOs-uSnWC8bSRau:-MY6RaB32BQgkPUuObif:bohb4be) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc799dd6fda997599caed50ceecd18e75580260c/gui/src/shared/logging.ts#L45)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`String.padStart` may come handy as it does exactly that, i.e:

```
> "1".padStart(5, "0")
< "00001"
```
</blockquote></details>

Didn't know about that one, thanks! Done.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2645#-:-MYF8pHJEPwH3JWeiCHT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
