### PR TITLE
Replace `lazy_static` with `once_cell` and `std` alternatives

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR refactors the use of `lazy_static` to use `OnceLock`/`OnceCell`/`LazyLock` instead.

The rationale is that the standard library is moving towards the abstractions provided by `once_cell`, and `lazy_static` is proposed to be deprecated by its maintainers. `OnceLock` and `OnceCell` have been stabilized in the standard library since `1.70.0`, and `LazyLock` is in `nightly`.

Until `LazyLock` is stabilized, we still need to rely on `once_cell`, but dropping this dependency down the line will be rather easy if this PR is accepted.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
:lgtm:

I guess this is blocked on #4812, though?

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-:-NYrAJaa0im2602ATHfJ:b-3swuls)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — COMMENTED** [review]
Yes, that is correct. I've marked this PR as a draft until #4812 is merged :blush: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-:-NYrM2OB1HI6tvn7w4oV:byoq7ca)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: 20 of 41 files reviewed, 1 unresolved discussion (waiting on @dlon and @MarkusPettersson98)

___
*[`mullvad-daemon/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-NazP12Z23xlMDovnUEe:-NazP12Z23xlMDovnUEf:brku4hh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4b5a77d18c524f1a518ab6551d3b3f608970b48d/mullvad-daemon/Cargo.toml#L20)):*
> ```TOML
> fern = { version = "0.6", features = ["colored"] }
> futures = "0.3"
> ipnetwork = "0.16"
> ```

I don't think this belongs here? Seems unrelated to this PR.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: 20 of 41 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`mullvad-daemon/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-NazP12Z23xlMDovnUEe:-NazRav8-BXTIqC2zrnO:b-8nop0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4b5a77d18c524f1a518ab6551d3b3f608970b48d/mullvad-daemon/Cargo.toml#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think this belongs here? Seems unrelated to this PR.
</blockquote></details>

It does indeed not belong here, mistake from rebase I presume. :)

Fixed!

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 7 of 21 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: 29 of 41 files reviewed, 1 unresolved discussion (waiting on @dlon and @MarkusPettersson98)

___
*[`mullvad-jni/Cargo.toml` line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-NazTEJjBW36TyZ6GEdm:-NazTEJjBW36TyZ6GEdn:bq7xr2o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4b5a77d18c524f1a518ab6551d3b3f608970b48d/mullvad-jni/Cargo.toml#L23)):*
> ```TOML
> ipnetwork = "0.16"
> jnix = { version = "0.5", features = ["derive"] }
> once_cell = "1.13"
> ```

This crate does not seem to contain any usage of `once_cell`?

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 41 files at r1, 11 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: 40 of 42 files reviewed, 2 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`mullvad-relay-selector/src/lib.rs` line 931 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-NazWPJNBh5kRhtzWt8Y:-NazWPJNBh5kRhtzWt8Z:b986kck) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/856f5834269683ba1e3f8684f43bddd7157b273c/mullvad-relay-selector/src/lib.rs#L931)):*
> ```XML
>     }
> 
>     pub fn get_obfuscator(
> ```

Why was this method moved out of the test module? Is that related to the `Lazy`-changes or an unrelated refactor?

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: 41 of 42 files reviewed, 1 unresolved discussion (waiting on @dlon and @MarkusPettersson98)

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: 41 of 42 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`mullvad-relay-selector/src/lib.rs` line 931 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-NazWPJNBh5kRhtzWt8Y:-NazWxWtAU1QNJlNITiN:b3ei03w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/856f5834269683ba1e3f8684f43bddd7157b273c/mullvad-relay-selector/src/lib.rs#L931)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why was this method moved out of the test module? Is that related to the `Lazy`-changes or an unrelated refactor?
</blockquote></details>

Not related to `Lazy`-changes or unrelated refactor, older version was erroneously selected during rebase onto `main` (and subsequently https://github.com/mullvad/mullvadvpn-app/commit/3a2a04422f532a26b46bc65a5f6e27dc629907ae). Well spotted!

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4826#-:-NazZL8q-JhV1ioIrHD0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
