### PR TITLE
More idiomatic bash in build_windows_modules.sh

### PR DESCRIPTION
**Pull request by faern**
Some changes to adapt a bit towards the [coding guidelines](https://github.com/mullvad/coding-guidelines/blob/master/bash.md). This script was largely written before those existed.

* Add a shebang at the start
* Change indentation to four spaces
* Compress `case` branches in some places where I felt they were more verbose than needed. This is not part of the written style guideline.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[build_windows_modules.sh, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119#-MoiKqLH4ru6gf4O0TVF:-MoiKqLH4ru6gf4O0TVG:b-kx9i8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97d299095c4c2de2283481fdcdb0ad311d5f01cd/build_windows_modules.sh#L23)):*
> ```Shell
>     if [[ -z ${DEV_BUILD+x} ]]; then
>         # Clean all intermediate and output files
>         rm -r $path/bin/* || true
> ```

Could be `${path:?}`? It doesn't make sense to call this if `$path` is empty.
___
*[build_windows_modules.sh, line 153 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119#-MoiIwxkAbTaskVFAAI-:-MoiIwxkAbTaskVFAAI0:b-p4mppa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97d299095c4c2de2283481fdcdb0ad311d5f01cd/build_windows_modules.sh#L153)):*
> ```Shell
>     build_solution "$winnet_root_path" "winnet.sln"
> 
>     copy_outputs $winfw_root_path "winfw.dll"
> ```

Should `$winfw_root_path` be quoted in case it contains whitespace?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[build_windows_modules.sh, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119#-MoiKqLH4ru6gf4O0TVF:-MoiMZES1jquMKEsC8rR:b-hzepku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97d299095c4c2de2283481fdcdb0ad311d5f01cd/build_windows_modules.sh#L23)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could be `${path:?}`? It doesn't make sense to call this if `$path` is empty.
</blockquote></details>

Ah yes. I forgot that this script triggers a million small stuff with shellcheck. I should also run shellcheck and push more commits. So far I just did minor style reformat stuff, not refactor the script. Hold on

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon)

___
*[build_windows_modules.sh, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119#-MoiKqLH4ru6gf4O0TVF:-MoiUSol4QildihVUWTI:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97d299095c4c2de2283481fdcdb0ad311d5f01cd/build_windows_modules.sh#L23)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah yes. I forgot that this script triggers a million small stuff with shellcheck. I should also run shellcheck and push more commits. So far I just did minor style reformat stuff, not refactor the script. Hold on
</blockquote></details>

Fixed!

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mvd-ows — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
