### PR TITLE
Use wireguard-nt by default

### PR DESCRIPTION
**Pull request by dlon**
As above.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115)

### CODE REVIEW

**Review by mvd-ows — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[CHANGELOG.md, line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115#-MocISCD-n1nd8O7wYHd:-MocISCF92LsrbLzm2Ah:bx3qy45) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58b7a22e5646992fc867e8e40e0b4bf5a9be6ac9/CHANGELOG.md#L31)):*
> ```Markdown
> 
> #### Windows
> - Make wireguard-nt the default driver for WireGuard.
> ```

This implies that only the driver implementation has changed. It could be more clear that `wireguard-go` is not being used in this configuration.
___
*[talpid-types/src/net/wireguard.rs, line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115#-MocJjywB1FgdxI9zrUf:-MocJjywB1FgdxI9zrUg:b-o867ct) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58b7a22e5646992fc867e8e40e0b4bf5a9be6ac9/talpid-types/src/net/wireguard.rs#L102)):*
> ```XML
> 
> impl Default for TunnelOptions {
>     fn default() -> Self {
> ```

When would this be getting called? Only in cases where no tunnel settings have been configured or serialized previously?

If so, for all app upgrades that are made, the active setting will still be `false`?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[CHANGELOG.md, line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115#-MocISCD-n1nd8O7wYHd:-MocaHpT8Gwwdjy2Yf6F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58b7a22e5646992fc867e8e40e0b4bf5a9be6ac9/CHANGELOG.md#L31)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This implies that only the driver implementation has changed. It could be more clear that `wireguard-go` is not being used in this configuration.
</blockquote></details>

Done.
___
*[talpid-types/src/net/wireguard.rs, line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115#-MocJjywB1FgdxI9zrUf:-MocLiSf-oghLr1ocqgF:b-ptur6a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58b7a22e5646992fc867e8e40e0b4bf5a9be6ac9/talpid-types/src/net/wireguard.rs#L102)):*
> When would this be getting called? Only in cases where no tunnel settings have been configured or serialized previously?

Yep.

> If so, for all app upgrades that are made, the active setting will still be `false`?

The field was renamed to prevent this from happening. It will always default to true no matter what the previous value was.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
