### PR TITLE
Create openvpn log backup

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/84)

### CODE REVIEW

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mullvad-daemon/src/main.rs, line 659 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84#-L6q1ln2oC5y6JyRLqN-:-L6q1ln2oC5y6JyRLqN0:b-5xgiwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9208a2c31c00191ad721d9d44250a9847fc8988/mullvad-daemon/src/main.rs#L659)):*
> ```Rust
>         backup.set_extension("old.log");
> 
>         if backup.exists() {
> ```

It may be more reliable to actually attempt to remove file and ignore std::io::ErrorKind::NotFound

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84)*

**Comment by faern** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 19 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-L6qYN141CrSo75a8MUy:-L6qYN141CrSo75a8MUz:b-gc8auy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5185f7fc8dfd6fe1da3de01242cd71d83e10b70f/CHANGELOG.md#L19)):*
> ```Markdown
> ### Added
> - Add `--disable-rpc-auth` flag to daemon to make it accept unauthorized control.
> - Create a backup of the existing tunnel log instead of overwriting it.
> ```

The changelog is user facing and should only contain changes that affect usage of the app. And yes, this does have the impact that the last two logs are included in the problem report, which is user facing. But then it should probably be formulated in a way describing how it affects users instead of how it was solved.

I think it would be more clear to write "Include the last two OpenVPN logs in problem reports instead of just the last."

---

*[mullvad-daemon/src/main.rs, line 659 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-L6q1ln2oC5y6JyRLqN-:-L6qYgHR9Yo_vfrsEeko:b-uk4jj4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9208a2c31c00191ad721d9d44250a9847fc8988/mullvad-daemon/src/main.rs#L659)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It may be more reliable to actually attempt to remove file and ignore std::io::ErrorKind::NotFound
</blockquote></details>

Yes, I also usually prefer the try-and-see-what-happens approach to file system operations. Since checking for existence and then moving is not one single atomic operation this is not fool proof. So just using `fs::rename` directly is probably enough? The rename can probably be inlined in the above method and both `exists()` checks removed? Then also `let _ = fs::remove_file(...)` can go from the above method since we know it will be gone after the rename anyway.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84)*

**Comment by jvff** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 19 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84#-L6qYN141CrSo75a8MUy:-L6r6gHAT1Zlt2Re0E4c:bqough) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5185f7fc8dfd6fe1da3de01242cd71d83e10b70f/CHANGELOG.md#L19)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The changelog is user facing and should only contain changes that affect usage of the app. And yes, this does have the impact that the last two logs are included in the problem report, which is user facing. But then it should probably be formulated in a way describing how it affects users instead of how it was solved.

I think it would be more clear to write "Include the last two OpenVPN logs in problem reports instead of just the last."
</blockquote></details>

Done. Should an explanation also be included? (e.g.: "because most recent log file might not have error to be reported")

---

*[mullvad-daemon/src/main.rs, line 659 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84#-L6q1ln2oC5y6JyRLqN-:-L6r6yQ8AeukAPayqtRl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9208a2c31c00191ad721d9d44250a9847fc8988/mullvad-daemon/src/main.rs#L659)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes, I also usually prefer the try-and-see-what-happens approach to file system operations. Since checking for existence and then moving is not one single atomic operation this is not fool proof. So just using `fs::rename` directly is probably enough? The rename can probably be inlined in the above method and both `exists()` checks removed? Then also `let _ = fs::remove_file(...)` can go from the above method since we know it will be gone after the rename anyway.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mullvad-daemon/src/main.rs, line 658 at r4](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84#-L6r8g7cBqm1GXbLKRFG:-L6rABvRVTENRtT1jt-j:b-70lqen) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00e19f2404cf2025e01344793868137d1ca1cb0d/mullvad-daemon/src/main.rs#L658)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Very good that you kept the `.log` extension, that way the frontend will pick it up and send it in the problem report :thumbsup: 
</blockquote></details>

It was suggested by @faern, so credit is his :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/84)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 19 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-L6qYN141CrSo75a8MUy:-L6rstdT4YBW2iFZ0QDp:bfn8gzz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5185f7fc8dfd6fe1da3de01242cd71d83e10b70f/CHANGELOG.md#L19)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

I think it is fine now. An explanation would of course be very nice, but I don't feel it's entirely necessary. 
</blockquote></details>

In general we don't really describe the *why* part of a change so much. Just what the change was. I think this version is fine!

---

*[mullvad-daemon/src/main.rs, line 659 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-L6q1ln2oC5y6JyRLqN-:-L6rtf8f6n7sAK7i82vC:b-138d54) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9208a2c31c00191ad721d9d44250a9847fc8988/mullvad-daemon/src/main.rs#L659)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice. I like it!

---

*[mullvad-daemon/src/main.rs, line 658 at r4](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-L6r8g7cBqm1GXbLKRFG:-L6rtBdq1N7A4EZo-E79:b-dq64cv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00e19f2404cf2025e01344793868137d1ca1cb0d/mullvad-daemon/src/main.rs#L658)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

It was suggested by @faern, so credit is his :)
</blockquote></details>

Did not know there was a `set_extension` method. Awesome way to solve this :ok_hand: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-:-L6rtnSO8E411xGxs2jY:bnfp4nl)*

**Comment by pronebird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84#-:-L6vVQr3BqFe7f0WXoGC:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/84)*

**Pull request merged**
