### PR TITLE
Refactor PacketTunnelActor to use a Reducer

### PR DESCRIPTION
**Pull request by acb-mv**
This is a refactoring of the PacketTunnelActor state machine, which splits the state processing logic into two stages: a stateless function (a Reducer) which takes incoming events (Events) and existing state and produces updated state and zero or more Effect values, and stateful code within the actor that executes the Effect values, producing effects. This is an instance of the Reducer architecture, and has the effect of making the state transition logic purely stateless and allowing it to be tested and reasoned about without concern for side effects.

As part of this, the `Command` type has been renamed to `Effect`, for accuracy: a value of this type can represent not only a user command (such as `.start`, `.stop` or `.reconnect`) but non-user events such as key rotations and network condition changes. (Additionally, renaming it to Event keeps it consistent with common nomenclature in the Reducer pattern.)

There is also a suite of unit tests to validate state transitions in the Actor through its Reducer.

(There was an earlier, unnumbered, PR,  but it fell by the wayside of extensive rebasing activity.)

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 341 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nyt8G5Y71UoznMHIZim:-Nyt8G5Y71UoznMHIZin:b-cc5fpf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05823c879b7bc137c3801c6bba92662169168d7/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L341)):*
> ```Swift
>      - Returns: New connection state or `nil` if current state is at or past `.disconnecting` phase.
>      */
>     internal func makeConnectionState(
> ```

Swiftlint body length warning.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nyt8oHl5Mbh_jkO47MR:-Nyt8oHl5Mbh_jkO47MS:b-kwy2p2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05823c879b7bc137c3801c6bba92662169168d7/ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift#L55)):*
> ```Swift
>     }
> 
>     static func reducer(_ state: inout State, _ event: Event) -> [Effect] {
> ```

Perhaps this function could be broken down to smaller pieces to make it easier to follow.

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nyt8oHl5Mbh_jkO47MR:-NytIDsy9evDVT3nzSPq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05823c879b7bc137c3801c6bba92662169168d7/ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift#L55)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Perhaps this function could be broken down to smaller pieces to make it easier to follow.
</blockquote></details>

Done.

**Comment by acb-mv** [comment]
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 341 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nyt8G5Y71UoznMHIZim:-NytIQkqBsR6DfOryBrg:b4zlrax) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05823c879b7bc137c3801c6bba92662169168d7/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L341)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Swiftlint body length warning.
</blockquote></details>

That's not one of the functions touched in this PR

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nz29GQ5AE0wymlV4H-r:-Nz29GQ5AE0wymlV4H-s:b46dvon) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d119ec0570d376f4079b782bd845aabc232e84de/ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift#L12)):*
> ```Swift
> import WireGuardKitTypes
> 
> extension WireGuardKey where Self: Equatable {}
> ```

That shouldn't be needed, `WireGuardKey` types already implement `Equatable` 
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nz2Bc54Dvrfvm0thK0f:-Nz2Bc54Dvrfvm0thK0g:berws6e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d119ec0570d376f4079b782bd845aabc232e84de/ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift#L55)):*
> ```Swift
>     }
> 
>     static func reducer(_ state: inout State, _ event: Event) -> [Effect] {
> ```

Any specific reason why it's all static methods ? 
Unless I'm mistaken, a struct should be able to do the same job and we can avoid having to depend on `PacketTunnelActor` inside the tests equally well. 

I'm assuming this was done so we don't need to instantiate it for tests, and just use the static functions instead, but it will just make it harder to actually write logic tests for `PacketTunnelActor` now because with this, we can't avoid dealing with reduced states.

IMHO this shouldn't be an extension of the PacketTunnel at all, it should just consume it, and depend on it.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 10 of 13 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-:-Nz36RRP9KuAvJVcVqvy:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6280#-Nz2Bc54Dvrfvm0thK0f:-Nz2zNDr-7yF3MuICQYA:bpld2nf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d119ec0570d376f4079b782bd845aabc232e84de/ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift#L55)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Any specific reason why it's all static methods ? 
Unless I'm mistaken, a struct should be able to do the same job and we can avoid having to depend on `PacketTunnelActor` inside the tests equally well. 

I'm assuming this was done so we don't need to instantiate it for tests, and just use the static functions instead, but it will just make it harder to actually write logic tests for `PacketTunnelActor` now because with this, we can't avoid dealing with reduced states.

IMHO this shouldn't be an extension of the PacketTunnel at all, it should just consume it, and depend on it.
</blockquote></details>

This was discussed offline, we decided to take an approach with both the benefits of having a struct, and use static functions to infer that there shouldn't be any statefulness in there.

**Pull request merged**
