### PR TITLE
Add setting for udp2tcp port

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 34 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTI_Th5YmlWHjTXT33:-NzTI_Th5YmlWHjTXT34:bii3d9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L212)):*
> ```Kotlin
> 
>     @Test
>     fun testShowTcpOverUdpPortOptions() =
> ```

Maybe we should have some tests so that you can not set the port when udp over tcp is not available?
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 456 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTIkL7CN4QIJTg1_Bc:-NzTIkL7CN4QIJTg1_Bd:b-2hzb9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L456)):*
> ```Kotlin
> 
>             // Assert
>             verify(exactly = 1) { mockedNavigateToObfuscationInfo() }
> ```

Just a side not, but could be nice with a `verifyExactlyOnce` function, or maybe that is too verbose?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 594 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTJjF01K3nBdefkgCS:-NzTJjF01K3nBdefkgCT:bfc2o4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L594)):*
> ```Kotlin
> 
>             itemWithDivider {
>                 ExpandableComposeCell(
> ```

Should show disabled somehow and should not be able to change port if udp over tcp is disabled

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310)* status: all files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 389 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTOIU21WTl2lbW2qHc:-NzTOIU21WTl2lbW2qHd:b-ddwx9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L389)):*
> ```Kotlin
>             .mapEmpty()
> 
>     suspend fun setObfuscationPort(
> ```

This function looks quite complicated, can we not wrap the whole this in an either catch?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310)* status: 28 of 36 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTI_Th5YmlWHjTXT33:-NzTUQuM-eglemFC9JIG:b-s0ro35) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L212)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe we should have some tests so that you can not set the port when udp over tcp is not available?
</blockquote></details>

Added a test for this.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 456 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTIkL7CN4QIJTg1_Bc:-NzTUV336MYnlhc-cpYM:b-z2i0bc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L456)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Just a side not, but could be nice with a `verifyExactlyOnce` function, or maybe that is too verbose?
</blockquote></details>

Too verbose I think, lets just use the simple standard way.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 594 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTJjF01K3nBdefkgCS:-NzTUZSC-hwErJ0Ywfqg:b-x32923) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L594)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should show disabled somehow and should not be able to change port if udp over tcp is disabled
</blockquote></details>

Yes it totally should! Fixed!
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 389 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-NzTOIU21WTl2lbW2qHc:-NzTUGPW7-qoRlQnnbg-:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d04230edcec4055b3c29174faa9bdc06554d18/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L389)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This function looks quite complicated, can we not wrap the whole this in an either catch?
</blockquote></details>

Fixed!

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6310#-:-NzT_Bh5-QZU20-BN3lf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
