### PR TITLE
Simplify jitter test

### PR DESCRIPTION
**Pull request by dlon**
Gets rid of the unnecessary PRNGs (#2455) by just taking a `u64` as input.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/future_retry.rs, line 195 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466#-MTKvTTPCK9w6WGti9fL:-MTKvTTPCK9w6WGti9fM:byh66nv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5401a1c6c3e43bb09e849333317b07dfe48f42e6/talpid-core/src/future_retry.rs#L195)):*
> ```XML
>         let unjittered_duration = Duration::from_millis(millis);
>         let jittered_duration = apply_jitter(unjittered_duration, jitter);
>         assert!(jittered_duration <= unjittered_duration);
> ```

Would this allow for getting back the assertion we lost in the last change?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/future_retry.rs, line 195 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466#-MTKvTTPCK9w6WGti9fL:-MTLBXPeBDjm8W2qQCg7:b-wzaueb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5401a1c6c3e43bb09e849333317b07dfe48f42e6/talpid-core/src/future_retry.rs#L195)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would this allow for getting back the assertion we lost in the last change?
</blockquote></details>

The other calculation produces a somewhat different result than `apply_jitter`, so that assertion fails.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
