### PR TITLE
Update supported platform and available features table in README

### PR DESCRIPTION
**Pull request by faern**
Updating the tables in the main README outlining what we support and where. Please review what I have added and if you know any more cool feature we have, suggest it!

I took inspiration from, but did not mimic 1:1: https://mullvad.net/en/why-mullvad-vpn/

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`README.md` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411#-NPbnIyE2KZK7Xpdua9x:-NPbnIyE2KZK7Xpdua9y:b43y8ul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/455ed77faa2e8f403c1d1b13a6afc1c9c6641ad7/README.md#L66)):*
> ```Markdown
> | Content blockers (Ads etc)    |    ✓    |   ✓   |   ✓   |         |  ✓  |
> | Optional local network access |    ✓    |   ✓   |   ✓   |    ✓    |  ✓\* |
> | [Externally audited](./audits)|    ✓    |   ✓   |   ✓   |    ✓    |  ✓ |
> ```

This is a great addition to this list!

**Pull request merged**
