### PR TITLE
Add guide for auto connect and lockdown mode

### PR DESCRIPTION
**Pull request by Pururun**
This is a continuation of: https://github.com/mullvad/mullvadvpn-app/pull/5592

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 18 of 18 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Pururun** [comment]
This is on hold waiting for design review.

**Comment by Pururun** [comment]
This is now on hold waiting for input from @Rawa

**Comment by Pururun** [comment]
This has been approved by design and @Rawa so it is now open for review again.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 72 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643#-Nq76Pk131k-w1_7OW5O:-Nq76Pk131k-w1_7OW5P:bp93cpk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70136bb8693fad2377a2a505f8c7fc01b9c0327/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L72)):*
> ```Kotlin
> @OptIn(ExperimentalFoundationApi::class)
> @Composable
> fun AutoConnectCarousel() {
> ```

This function is a bit long, possibly worth considering breaking it apart to:
- PageContent (Insides of the horizontal pager)
- PageIndicator (Last Row in this function
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 297 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643#-Nq77Qvn-i-YZJWvVi8S:-Nq77Qvn-i-YZJWvVi8T:b7pmkdj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70136bb8693fad2377a2a505f8c7fc01b9c0327/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L297)):*
> ```Kotlin
>         snackbarHostState = snackbarHostState
>     ) { modifier, lazyListState ->
>         val context = LocalContext.current
> ```

I think we should avoid using `LocalContext.current` as much as possible, also if VPN settings are available is something that should be described into the view state. Maybe creating a UseCase that injects the `applicationContext` to find this information out is a better alternative?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: 20 of 29 files reviewed, 2 unresolved discussions (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 297 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643#-Nq77Qvn-i-YZJWvVi8S:-Nq80s1sEmCb3QHxvTmS:b-2h092m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70136bb8693fad2377a2a505f8c7fc01b9c0327/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L297)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think we should avoid using `LocalContext.current` as much as possible, also if VPN settings are available is something that should be described into the view state. Maybe creating a UseCase that injects the `applicationContext` to find this information out is a better alternative?
</blockquote></details>

Added UseCase
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 72 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643#-Nq76Pk131k-w1_7OW5O:-Nq80vCBAO3qFHAyXTwt:bpwa5s4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70136bb8693fad2377a2a505f8c7fc01b9c0327/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L72)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This function is a bit long, possibly worth considering breaking it apart to:
- PageContent (Insides of the horizontal pager)
- PageIndicator (Last Row in this function
</blockquote></details>

I made the screen more to how we made our other screens.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 297 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643#-Nq77Qvn-i-YZJWvVi8S:-Nqb7Dup-rNifzLQ4MRO:bb66cmv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70136bb8693fad2377a2a505f8c7fc01b9c0327/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L297)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added UseCase
</blockquote></details>

Nice! :clap: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 72 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643#-Nq76Pk131k-w1_7OW5O:-Nqb7RM-8XLcXiasN_Cb:b-kmi9x6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70136bb8693fad2377a2a505f8c7fc01b9c0327/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L72)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I made the screen more to how we made our other screens.
</blockquote></details>

:lgtm: Good job! :1st_place_medal:

**Review by Rawa — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5643)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
