### PR TITLE
Refactor translations converter

### PR DESCRIPTION
**Pull request by jvff**
This PR tries to improve the Android translation converter helper tool so that the code is clearer and easier to navigate. The main changes are the creation of sub modules to better organize the code, the creation of a new `normalize` module and refactoring the creation of wrapped strings to make it clearer when escaping is performed.

The goal when creating the `normalize` module was to keep the code to convert to a common format close together. This makes it easier to spot differences when converting from Android string values or gettext msgstrs. It should also help with future changes to the "normalized" format, since now everything that would need to be changed is in a single module file.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal tool refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 4 of 10 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 7 of 10 files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/translations-converter/src/android/string_value.rs, line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-M_eRlZQ2M3hkKHX-aeH:-M_eRlZQ2M3hkKHX-aeI:b5y80v8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dd51ff7d0e48ccacec9cebc0983d1fa506acf45/android/translations-converter/src/android/string_value.rs#L31)):*
> ```XML
>     }
> 
>     fn ensure_parameters_are_indexed(original: String) -> String {
> ```

These kinds of functions would benefit greatly from having some argument examples.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/translations-converter/src/android/string_value.rs, line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-M_eRlZQ2M3hkKHX-aeH:-M_f0xN96Q224z-EsxNJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dd51ff7d0e48ccacec9cebc0983d1fa506acf45/android/translations-converter/src/android/string_value.rs#L31)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

These kinds of functions would benefit greatly from having some argument examples.
</blockquote></details>

Done.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/translations-converter/src/gettext/msg_string.rs, line 64 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-M_vXuq4Cnv0xhgFafb1:-M_vXuq58ye9_Rz-PfOC:b-wkjykk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ec5bff1a68aaaf7d758a0455505aba937d20e66/android/translations-converter/src/gettext/msg_string.rs#L64)):*
> ```XML
> 
>         assert_eq!(input.to_string(), expected);
>     }
> ```

FYI: I realized that the current code isn't handling escaping a backslash, so I went to dig into what escape sequences were supported by gettext. In summary: it's C string syntax. I'll open a separate PR to add support for all of the escape sequences, maybe there's a crate to help with this.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
I'm a big fan of all the tests :thumbsup: 

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-:-M_z1ewe6ebiwV5AjXGy:b-e8fpp8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[android/translations-converter/src/android/string_value.rs, line 150 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-M_zyOKS9KkohTkZzMv_:-M_zyOKS9KkohTkZzMva:b-azy4sr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/418f14832bdd77daef1ca13cffd0ad69414ef58e/android/translations-converter/src/android/string_value.rs#L150)):*
> ```XML
> 
>         assert_eq!(input.to_string(), expected);
>     }
> ```

FYI: I considered adding a deserialization test here, but since the type itself is just a string, I thought it could use `serde_json` so that it's `serde_json::from_str(r#""A string""#)?` or something. But since the `StringResources` deserialization test already covers this indirectly without needing `serde_json`, I left it out.

Do you think it's a good idea to add a deserialization test here?

Pro: keep test closer to implementation
Con: adding a test-only dependency, and possibly being redundant

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/translations-converter/src/android/string_value.rs, line 150 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-M_zyOKS9KkohTkZzMv_:-Ma3cD9j905l-589yTK3:bxe4er0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa652abef4174801701986145cdef6825f35d28/android/translations-converter/src/android/string_value.rs#L150)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

FYI: I considered adding a deserialization test here, but since the type itself is just a string, I thought it could use `serde_json` so that it's `serde_json::from_str(r#""A string""#)?` or something. But since the `StringResources` deserialization test already covers this indirectly without needing `serde_json`, I left it out.

Do you think it's a good idea to add a deserialization test here?

Pro: keep test closer to implementation
Con: adding a test-only dependency, and possibly being redundant
</blockquote></details>

I'm not worried about adding a development dependency here, so go ahead and add it.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[android/translations-converter/src/android/string_value.rs, line 150 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-M_zyOKS9KkohTkZzMv_:-Ma3kI_BEJWfVhsLGUs4:b1ygq91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa652abef4174801701986145cdef6825f35d28/android/translations-converter/src/android/string_value.rs#L150)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'm not worried about adding a development dependency here, so go ahead and add it.
</blockquote></details>

Done. I tried with `serde_json` first, but that led to some issues regarding quoting. More specifically, backslashes are used for escaping in JSON, but not in XML, so there could be some surprises when reading the test due to extra backslashes that aren't necessary in XML.

To keep things a bit simpler, I just used `serde_xml_rs` again and added a wrapper `struct` to allow the serialization to be tested.

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2742#-:-Ma413Fo-I5yrVddJw5K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
