### PR TITLE
Make `mullvad status` print if lockdown mode is enabled while disconnected

### PR DESCRIPTION
**Pull request by Serock3**
Fixes DES-535

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-core/src/tunnel_state_machine/disconnected_state.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-NnioCmq9gPeBKrtJ-e0:-NnioCmq9gPeBKrtJ-e1:b-v2nrbf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b638f95474249c0b639138b7050cd9889b975d8/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L171)):*
> ```XML
>                     shared_values.block_when_disconnected = block_when_disconnected;
> 
>                     // TODO: Investigate if we can simply return
> ```

TODO

Is this meant to be left in the code for some future PR, or are you intending to investigate this in this PR?:)



_Code quote:_
```XML
TODO
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/tunnel_state_machine/disconnected_state.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-NnioCmq9gPeBKrtJ-e0:-NnmRa9RA6KNHmL3O0qd:b-s25ld) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b638f95474249c0b639138b7050cd9889b975d8/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L171)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

TODO

Is this meant to be left in the code for some future PR, or are you intending to investigate this in this PR?:)
</blockquote></details>

I intended this to be left for a future PR. Initially I just used`Self::enter` and hoped for the best, but David convinced me to go for the safer alternative and leave a comment to the next person working on this part of the codebase.

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-core/src/tunnel_state_machine/disconnected_state.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-NnioCmq9gPeBKrtJ-e0:-NnmbD4Z8njkQRTstYA6:bdk5ylx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b638f95474249c0b639138b7050cd9889b975d8/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L171)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I intended this to be left for a future PR. Initially I just used`Self::enter` and hoped for the best, but David convinced me to go for the safer alternative and leave a comment to the next person working on this part of the codebase.
</blockquote></details>

Okay, good! :blush: 
___
*[`talpid-core/src/tunnel_state_machine/disconnected_state.rs` line 170 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-NnnXIwd7O1Kkwdwmv8L:-NnnXIwd7O1Kkwdwmv8M:b-8w6d7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cb98e94d49d0fb5b9c867da51409391a5c2da62/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L170)):*
> ```XML
>             }
>             Some(TunnelCommand::BlockWhenDisconnected(block_when_disconnected, complete_tx)) => {
>                 if dbg!(shared_values.block_when_disconnected != block_when_disconnected) {
> ```

Left-over `dbg!` :smile: 



_Code quote:_
```XML
dbg!
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)* status: 2 of 13 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/tunnel_state_machine/disconnected_state.rs` line 170 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-NnnXIwd7O1Kkwdwmv8L:-NoCoxwb3bwBOu0EDhLM:bt2vr0b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cb98e94d49d0fb5b9c867da51409391a5c2da62/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L170)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Left-over `dbg!` :smile:
</blockquote></details>

Fixed

**Review by MarkusPettersson98 — APPROVED** [review]
The code looks good! Now we have to fix the issues with the Android CI :blush: 

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-:-NoG0xMb8VH5kzKVXQhM:b-ee1gl2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656#-:-NoS-3BpEjh-it3lGlDR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
