### PR TITLE
Document "raison d'être" of some NAT rules in macOS firewall module

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Context is in the comment.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/firewall/macos.rs` line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084#-OAHSOqC2_6oCrFJQt2s:-OAHSOqC2_6oCrFJQt2t:bu1p6js) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0507ab55cdb0d8dd3034ab1fe6823646ac096b68/talpid-core/src/firewall/macos.rs#L238)):*
> ```XML
>     /// Some programs have been shown to bind their sockets directly to the physical network
>     /// interface. To stop their network traffic from leaking outside the tunnel, we add a
>     /// whole slew of redirect rules which redirect these packets to the tunnel again.
> ```

Nit: These rules do not actually redirect packets through the tunnel interface. That's handled by a `route-to` rule. But we do need these rules as well just to fix the source IP address.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/firewall/macos.rs` line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084#-OAHSOqC2_6oCrFJQt2s:-OAHcWnQ9IE7y-o2hmfr:bdaeuid) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0507ab55cdb0d8dd3034ab1fe6823646ac096b68/talpid-core/src/firewall/macos.rs#L238)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: These rules do not actually redirect packets through the tunnel interface. That's handled by a `route-to` rule. But we do need these rules as well just to fix the source IP address.
</blockquote></details>

You're right. Is this better?

**Review by hulthe — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon and @MarkusPettersson98)

___
*[`talpid-core/src/firewall/macos.rs` line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084#-OAHSOqC2_6oCrFJQt2s:-OAHeH_BEPxVsPlJkp-W:b-q8l2ii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0507ab55cdb0d8dd3034ab1fe6823646ac096b68/talpid-core/src/firewall/macos.rs#L238)):*
> To stop their network traffic from leaking

Technically not true :monocle_face: . The traffic will be blocked by our other fw-rules and the service just won't work.

**Review by hulthe — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/firewall/macos.rs` line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084#-OAHSOqC2_6oCrFJQt2s:-OAHkhoC73HuaYj3vTPE:bb7k0qh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0507ab55cdb0d8dd3034ab1fe6823646ac096b68/talpid-core/src/firewall/macos.rs#L238)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I tried to clarify this part, wdyt?
</blockquote></details>

lgtm

**Review by hulthe — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
