### PR TITLE
Migrate connect fragment, expect notification bar, to compose

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 4 of 29 files at r1, 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875)* status: 31 of 32 files reviewed, 7 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Button.kt` line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DQfqq1BXO05NwpGIw:-N_DQfqq1BXO05NwpGIx:b-8a1d9p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87a93b6b16329aafa737b3a2e5bb1fc9a6186040/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Button.kt#L80)):*
> ```Kotlin
> 
> @Composable
> fun SwitchLocationButton(
> ```

It might be a good idea with a new package `package net.mullvad.mullvadvpn.compose.button` where we can put various buttons in separate files to avoid too large kotlin files.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionButton.kt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DRggQCFtDO5kFt5Qg:-N_DRggQCFtDO5kFt5Qh:bl6xhrs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87a93b6b16329aafa737b3a2e5bb1fc9a6186040/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionButton.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.compose.component
> ```

See other comment regarding a separate button package.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DW7VHBpNCZdWIpBah:-N_DW7VHBpNCZdWIpBai:b-6clzzd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87a93b6b16329aafa737b3a2e5bb1fc9a6186040/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt#L47)):*
> ```Kotlin
> 
> @Composable
> private fun Disconnected() {
> ```

I suggest renaming these and other composable text functions in this file to reflect that it renders text, for example `DisconnectText`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DS-aC05QE9gpnDd7k:-N_DS-aC05QE9gpnDd7l:b-4dxglq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87a93b6b16329aafa737b3a2e5bb1fc9a6186040/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt#L48)):*
> ```Kotlin
>     onToggleTunnelInfo: () -> Unit,
>     visible: Boolean,
>     expanded: Boolean,
> ```

I suggest to prefix these with `is`



_Code quote:_
```Kotlin
    visible: Boolean,
    expanded: Boolean,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DSERG9PvnPLs6dlS4:-N_DSERG9PvnPLs6dlS5:bw1whg3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87a93b6b16329aafa737b3a2e5bb1fc9a6186040/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt#L126)):*
> ```Kotlin
>             } else {
>                 ""
>             }
> ```

I believe it might be better to place this in the VM in order to keep the view as simple as possible and just expose the addresses. Any thoughts?



_Code quote:_
```Kotlin
        // In address
        val inAddress =
            if (expanded && tunnelEndpoint != null) {
                val relayEndpoint = tunnelEndpoint.obfuscation?.endpoint ?: tunnelEndpoint.endpoint
                val host = relayEndpoint.address.address.hostAddress ?: ""
                val port = relayEndpoint.address.port
                val protocol =
                    when (relayEndpoint.protocol) {
                        TransportProtocol.Tcp -> stringResource(id = R.string.tcp)
                        TransportProtocol.Udp -> stringResource(id = R.string.udp)
                    }
                "${stringResource(id = R.string.in_address)} $host:$port $protocol"
            } else {
                ""
            }
        Text(text = inAddress, color = colorExpanded, style = MaterialTheme.typography.labelMedium)
        // Out address
        val outAddress =
            if (expanded && location != null && (location.ipv4 != null || location.ipv6 != null)) {
                val ipv4 = location.ipv4
                val ipv6 = location.ipv6

                if (ipv6 == null) {
                    "${stringResource(id = R.string.out_address)} ${ipv4?.hostAddress ?: ""}"
                } else if (ipv4 == null) {
                    "${stringResource(id = R.string.out_address)} ${ipv6.hostAddress ?: ""}"
                } else {
                    "${stringResource(id = R.string.out_address)} ${ipv4.hostAddress} / ${ipv6.hostAddress}"
                }
            } else {
                ""
            }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DXWEt-KOX7yYopyAg:-N_DXWEt-KOX7yYopyAh:bs5e4ie) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87a93b6b16329aafa737b3a2e5bb1fc9a6186040/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L55)):*
> ```Kotlin
>     onToggleTunnelInfo: () -> Unit = {}
> ) {
>     LazyColumn(
> ```

Can you elaborate on the choice of `LazyColumn` here? Seems a bit unnecessary since it's not a typical scrollable view etc. My initial thought would have been to use something like `ConstraintLayout` to have easy and full control of placement.



_Code quote:_
```Kotlin
LazyColumn
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/constant/ContentType.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DROwg9k32w8ym93sJ:-N_DROwg9k32w8ym93sK:b-su80jv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cdd09a3b5f854219dfe4bfa20e5d83a5154ae02/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/constant/ContentType.kt#L13)):*
> ```Kotlin
>     const val DISCONNECT_BUTTON = 7
>     const val CONNECT_BUTTON = 8
>     const val SWITCH_LOCATION_BUTTON = 9
> ```

I noticed you removed these. Are they not needed?



_Code quote:_
```Kotlin
    const val DISCONNECT_BUTTON = 7
    const val CONNECT_BUTTON = 8
    const val SWITCH_LOCATION_BUTTON = 9
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_DxiYM6sHavtYpJH2o:-N_DxiYM6sHavtYpJH2p:bd7luy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76242d0a6c8a3a94336b66dd094d043936e89475/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L123)):*
> ```Kotlin
>                 is TunnelState.Connected -> false
>                 is TunnelState.Error -> true
>             }
> ```

This might also be nice to do in the VM instead :thinking: 



_Code quote:_
```Kotlin
        val showLocation =
            when (uiState.tunnelUiState) {
                is TunnelState.Disconnected -> true
                is TunnelState.Disconnecting -> {
                    when (uiState.tunnelUiState.actionAfterDisconnect) {
                        ActionAfterDisconnect.Nothing -> true
                        ActionAfterDisconnect.Block -> true
                        ActionAfterDisconnect.Reconnect -> false
                    }
                }
                is TunnelState.Connecting -> false
                is TunnelState.Connected -> false
                is TunnelState.Error -> true
            }
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt` line 5 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_EOY3z9WGPbMBBnehG:-N_EOY3z9WGPbMBBnehH:b-hytffe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97f89f2950a26920c9cda6b3efba55b17009690f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt#L5)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.model.GeoIpLocation
> 
> fun GeoIpLocation?.toOutAddress(): String =
> ```

I suggest skipping this case and handling at the call site. That should also mean that this function can be simplified.



_Code quote:_
```Kotlin
?
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_EOrNhA9YSKccBCrXm:-N_EOrNhA9YSKccBCrXn:birvlik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97f89f2950a26920c9cda6b3efba55b17009690f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt#L8)):*
> ```Kotlin
>     if (this != null && (this.ipv4 != null || this.ipv6 != null)) {
>         val ipv4 = this.ipv4
>         val ipv6 = this.ipv6
> ```

Are these necessary? Especially if making the `GeoIpLocation` non-nullable



_Code quote:_
```Kotlin
        val ipv4 = this.ipv4
        val ipv6 = this.ipv6
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875)* status: 37 of 40 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt` line 5 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_EOY3z9WGPbMBBnehG:-N_I85Hr0p1bIR4MN-OB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97f89f2950a26920c9cda6b3efba55b17009690f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt#L5)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest skipping this case and handling at the call site. That should also mean that this function can be simplified.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875#-N_EOrNhA9YSKccBCrXm:-N_I85gf87hfOVJ1jkxt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97f89f2950a26920c9cda6b3efba55b17009690f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/GeoIpLocationExtensions.kt#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are these necessary? Especially if making the `GeoIpLocation` non-nullable
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4875)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
