### PR TITLE
Anchor the quit button to the bottom of the settings page

### PR DESCRIPTION
**Pull request by eriklarko**
Makes sure the quit button is anchored to the bottom om the settings screen. The render method is simply split up into parts and then some flex magic pushes the quit button to the bottom.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/12)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/CustomScrollbars.css, line 5 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L2-slO2vk0ee2TB4NEj:-L20O_3adHEBn9iqco5j:b-x6e3b0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/CustomScrollbars.css#L5)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

The parent has `height: 100%` already in this case and the `custom-scrollbars` div does not fill the parent. If I add `flex-grow: 1` it does fill the parent, but the `custom-scrollbars__scrollable` does not
</blockquote></details>

`.custom-scrollbars__scrollable` has the height of `100%` so it should stretch naturally.

If there is no bug in `CustomScrollbars` then I suggest you sort the Settings layout issue in Settings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L20VFrP-_vhJw5LM7TS:bcb2zgj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does textAlign work on non-text node? I assumed that text styles and view styles are two separate things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by eriklarko** [comment]
*[app/components/CustomScrollbars.css, line 5 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L2-slO2vk0ee2TB4NEj:-L20V6AbW7e4klHt42s6:b-ur5h0k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/CustomScrollbars.css#L5)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

`.custom-scrollbars__scrollable` has the height of `100%` so it should stretch naturally.

If there is no bug in `CustomScrollbars` then I suggest you sort the Settings layout issue in Settings.
</blockquote></details>

But it doesn't :) I would put the changes there if it was just a settings layout issue, but the div in the scroll thing has `height: 100%` and the parent of the scroll this has `height: 100%` but the height of the scroll this does not fill the parent so it doesn't matter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/CustomScrollbars.css, line 5 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L2-slO2vk0ee2TB4NEj:-L20VVuUQiVOMWOVvOrq:bar1cpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/CustomScrollbars.css#L5)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

But it doesn't :) I would put the changes there if it was just a settings layout issue, but the div in the scroll thing has `height: 100%` and the parent of the scroll this has `height: 100%` but the height of the scroll this does not fill the parent so it doesn't matter
</blockquote></details>

But that change will affect all `CustomScrollbars` around the app which undesired side effect. It could be the problem is in something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by eriklarko** [comment]
*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L20Vv5-xwJ4rtr518NJ:b-tvtht6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Does textAlign work on non-text node? I assumed that text styles and view styles are two separate things.
</blockquote></details>

These are the text styles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L20WB1tHJD-4bndUoNt:by1q66b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

These are the text styles.
</blockquote></details>

But container is a View. This won't work on mobile to my understanding.

```
<View style={styles.settings__account_paid_until_label_container}>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/CustomScrollbars.css, line 5 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L2-slO2vk0ee2TB4NEj:-L20aZEPv69gkUn9cgKb:b6ieirw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/CustomScrollbars.css#L5)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

But that change will affect all `CustomScrollbars` around the app which undesired side effect. It could be the problem is in something else?
</blockquote></details>

I just removed the `padding-bottom: 48px` from the button and it moved offscreen. Something fishy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 87 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20cQk41EXpML_UxtEw:-L20cQk41EXpML_UxtEx:bwx9g3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L87)):*
> ```JavaScript
>   },
>   settings__footer:{
>     width: '100%',
> ```

There is no need for `width: 100%` for vertically placed elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 93 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20cXvwiXXza1uEwVC6:-L20cXvwiXXza1uEwVC7:b-3li87z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L93)):*
> ```JavaScript
>     paddingLeft: 24,
>     paddingRight: 24,
>     paddingBottom: 24 * 2, // Not entirely sure why I need to double the padding here :/
> ```

It shouldn't be double I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 93 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20cXvwiXXza1uEwVC6:-L20ccT28pR2hhiKxi-O:b3z6iwg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L93)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It shouldn't be double I think
</blockquote></details>

Yes! According to Zeplin it's 24px too. So use the same padding for bottom too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 88 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20cqdN8mvDTvg10pQo:-L20cqdN8mvDTvg10pQp:b93mvh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L88)):*
> ```JavaScript
>   settings__footer:{
>     width: '100%',
>     justifyContent: 'center',
> ```

There is only one button padded from all sides, no need to center it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 84 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20dGty0XKVFC5w0vp3:-L20dGty0XKVFC5w0vp4:bljqw1v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L84)):*
> ```JavaScript
>     justifyContent: 'center',
>     alignItems: 'center',
>     width: '100%',
> ```

If you remove `center` for align/justifyContent props from the parent then you don't need this `width: 100%` either since the default strategy is to stretch.

---

*[app/components/SettingsStyles.js, line 89 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20cy1BgMZSy_Wt6Dn0:-L20cy1BgMZSy_Wt6Dn1:brhumzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L89)):*
> ```JavaScript
>     width: '100%',
>     justifyContent: 'center',
>     alignItems: 'center',
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[app/components/SettingsStyles.js, line 38 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20g5wg0xP5J_U5RIDm:-L20g5wg0xP5J_U5RIDn:b9gebkt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L38)):*
> ```JavaScript
>     flex: 0,
>     opacity: 0.6,
>     marginRight: 8,
> ```

Unnecessary margin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Erik I pushed one commit that fixes layout and updated CustomScrollbars a little to be able to pass `styles` along. Please review the changes and feel free to reverse the commit if you don't like it :)

---

Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-:-L20qVLSTRCySxW5LhMm:b-re0hgs)*

**Comment by eriklarko** [comment]
Looks good!

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-:-L2KksGNRHzDhITR7QHX:b-vs1prh)*

**Comment by eriklarko** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 38 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20g5wg0xP5J_U5RIDm:-L2Km6tMwC8SB9BBGir3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L38)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Unnecessary margin
</blockquote></details>

Done.

---

*[app/components/SettingsStyles.js, line 84 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20dGty0XKVFC5w0vp3:-L2KmLUVeXT79EIO6gri:b-pv7tfr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L84)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

If you remove `center` for align/justifyContent props from the parent then you don't need this `width: 100%` either since the default strategy is to stretch.
</blockquote></details>

The `alignItems` control the position of the text so I'll keep that but remove the `justify`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Kq-q5rh4Iuc0AkAMM:b-1ajfi2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

But container is a View. This won't work on mobile to my understanding.

```
<View style={styles.settings__account_paid_until_label_container}>
```
</blockquote></details>

I am confused about text and view styles in RX so I'll mark this as satisfied for now and we'll fix any issues later when we know/run this project on mobile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 84 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L20dGty0XKVFC5w0vp3:-L2KqOn8wODNR1uc3BDK:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9aa9e73685b5188f8e21daebfd37dc5fd174481/app/components/SettingsStyles.js#L84)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

The `alignItems` control the position of the text so I'll keep that but remove the `justify`
</blockquote></details>

👍

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Haven't ran this but from the other day of testing I'd say fixing this should look good in practice.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-:-L2Kq_9Qr65mG5jkcMPg:bttoddn)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PGQgFmmxZr8v9YbJd:bpb6x4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I am confused about text and view styles in RX so I'll mark this as satisfied for now and we'll fix any issues later when we know/run this project on mobile.
</blockquote></details>

@anderklander can you shed the light if `textAlign` style can be used in `View` styles?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
@eriklarko would be great to merge this PR since the upcoming PR by @anderklander is based on it so it will be easier to review if this PR goes into master. :+1: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-:-L2PGbAec94Vlf3d3xVc:b-tmk92g)*

**Comment by anderklander** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PNtbiwtk5ohh9WGUt:b8b3if0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

@anderklander can you shed the light if `textAlign` style can be used in `View` styles?
</blockquote></details>

Didn't see any difference when i tested, but throws a warning about failed prop type on android. Seems like we basically just should change <View> to <Text>?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by anderklander** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PQLks0ZVKrYz-rFc6:b-7js7d9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

Didn't see any difference when i tested, but throws a warning about failed prop type on android. Seems like we basically just should change <View> to <Text>?
</blockquote></details>

Change View to Text ... I could add it to my PR if its easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PYMpiyKLnM8wbCS2W:bw6l21s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

Change View to Text ... I could add it to my PR if its easier.
</blockquote></details>

OK, so we can't use any text related styles on Views.

@anderklander could you please check if moving `textAlign` style to `settings__account_paid_until_label` solves the problem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PYm41S2H8Dd3F-Eo8:buqvcbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

OK, so we can't use any text related styles on Views.

@anderklander could you please check if moving `textAlign` style to `settings__account_paid_until_label` solves the problem?
</blockquote></details>

PS: Yes it seems that on the web it's legal to use those props and they work as expected, but textAlign won't work when applied to `View` on mobile since Views do not render text and have no clue what to do with text alignment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PZ8q0odqzW4NNo-Tf:b37y113) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

PS: Yes it seems that on the web it's legal to use those props and they work as expected, but textAlign won't work when applied to `View` on mobile since Views do not render text and have no clue what to do with text alignment.
</blockquote></details>

The other option is `alignSelf: end` on label?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by anderklander** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Paa9377aTkM5J1_Vp:bx5escv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

The other option is `alignSelf: end` on label?
</blockquote></details>

"Unlike other ReactXP components, some of the style attributes for an Text cascade to its children. "

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PkI2dQE9o7ewExrdg:bnw0udz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

"Unlike other ReactXP components, some of the style attributes for an Text cascade to its children. "
</blockquote></details>

All we need to do is to remove the container and move container styles to label.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by anderklander** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PoJnNfTkbx9-uwc9B:b84llun) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

All we need to do is to remove the container and move container styles to label.
</blockquote></details>

Or change View -> Text …

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2PpWffb0LtmWyAevtT:b-mrhucw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

Or change View -> Text …
</blockquote></details>

Sure but it's unnecessary to have more complex view hierarchy when a single Text node can achieve the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by eriklarko** [comment]
*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Q2dXc0blViWAb1EnG:b-9ab6ef) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Sure but it's unnecessary to have more complex view hierarchy when a single Text node can achieve the same.
</blockquote></details>

I guess I should wait with the merge? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Q2oxL0kD_XWBLxbX-:bau827o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

I guess I should wait with the merge? :)
</blockquote></details>

I can fix that if you wish but I have to install the computer on my bike first :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by anderklander** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Q3yY6RurG8_R915VF:bh2drqz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I can fix that if you wish but I have to install the computer on my bike first :)
</blockquote></details>

I have committed a fix in my branch, sice this works in electron i suggest merge and we take the react-native fix in my PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by eriklarko** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Q4dIsvDZVFU5GSQTE:b-6fqukc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

I have committed a fix in my branch, sice this works in electron i suggest merge and we take the react-native fix in my PR.
</blockquote></details>

Cool, I'll start merging this then. Gonna need to rebase and wait for travis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SettingsStyles.js, line 122 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-L1wdGAWcnLeKJU_LDIN:-L2Q4uMew33Wp8fDc_QS:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86f18214c8bee4622845b3af3cd595da51c4cadd/app/components/SettingsStyles.js#L122)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Cool, I'll start merging this then. Gonna need to rebase and wait for travis
</blockquote></details>

👍

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12)*

**Comment by pronebird** [comment]
Please mark threads as resolved.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/12#-:-L2Q51Sef-OTdlPjOee1:b-muafr3)*

**Pull request merged**
