### PR TITLE
Add initial android e2e tests

### PR DESCRIPTION
**Pull request by albin-mullvad**
Adds initial Android end-to-end tests in a separate module. The purpose of this test module is to be able to trigger end-to-end tests separately from the main app module, mainly due to the flaky nature of end-to-end tests. These tests will NOT be automatically executed in this first iteration.

Git checklist:

~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 29 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: 29 of 33 files reviewed, all discussions resolved

___
*[android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413#-My75ThH4iyXdRoUTUUX:-My75ThH4iyXdRoUTUUY:bnyqmzg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecc59fcc6bff2fdd0e8b75a71ba7031c661de8e7/android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt#L20)):*
> ```Kotlin
>         }
>         intent.component = ComponentName.unflattenFromString(
>             "com.android.settings/.Settings\$VpnSettingsActivity"
> ```

Is this component supposed to be launchable on all Android versions? Because it'd be really cool to be able to guide the user to the system VPN settings to toggle _always-on_ and _block without VPN_, but when I tried to do this some time ago, I couldn't find a universal way of doing this.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/misc/SimpleMullvadHttpClient.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413#-My76HJe2e5mszOICbhO:-My76HJe2e5mszOICbhP:b822fuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecc59fcc6bff2fdd0e8b75a71ba7031c661de8e7/android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/misc/SimpleMullvadHttpClient.kt#L17)):*
> ```Kotlin
> import org.json.JSONObject
> 
> class SimpleMullvadHttpClient(context: Context) {
> ```

I guess involving the rust side of this code might be a bit much, but we could also expose the same functionality through the JNI and then we'd get rid of this duplication.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413#-My75ThH4iyXdRoUTUUX:-My9A_bBB3d9xfWstbM9:byso4o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecc59fcc6bff2fdd0e8b75a71ba7031c661de8e7/android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt#L20)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this component supposed to be launchable on all Android versions? Because it'd be really cool to be able to guide the user to the system VPN settings to toggle _always-on_ and _block without VPN_, but when I tried to do this some time ago, I couldn't find a universal way of doing this.
</blockquote></details>

It seem to be available on most (all?) phone devices, however it's unfortunantely not available on some devices, for example TVs.
___
*[android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/misc/SimpleMullvadHttpClient.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413#-My76HJe2e5mszOICbhO:-My9CcqQ02wlb6x0yUV0:bskvstq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecc59fcc6bff2fdd0e8b75a71ba7031c661de8e7/android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/misc/SimpleMullvadHttpClient.kt#L17)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I guess involving the rust side of this code might be a bit much, but we could also expose the same functionality through the JNI and then we'd get rid of this duplication. 
</blockquote></details>

Might be an option in the future, however this part of the end-to-test setup will probably look quite different once there is a dedicated environment available.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413#-My75ThH4iyXdRoUTUUX:-My9KmBN6FqFxZjvPGJZ:b3th94m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecc59fcc6bff2fdd0e8b75a71ba7031c661de8e7/android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt#L20)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It seem to be available on most (all?) phone devices, however it's unfortunantely not available on some devices, for example TVs.
</blockquote></details>

If we can test to see if the such an activity exists, we could add an optional button that's only displayed when the activity is available and it would let users get to the appropriate activity a lot quicker. I sure find it tedious to get to those settings myself.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413#-My75ThH4iyXdRoUTUUX:-MyBelro7pZcWVCrneCe:b3th4px) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecc59fcc6bff2fdd0e8b75a71ba7031c661de8e7/android/e2e/src/main/java/net/mullvad/mullvadvpn/e2e/interactor/SystemSettingsInteractor.kt#L20)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If we can test to see if the such an activity exists, we could add an optional button that's only displayed when the activity is available and it would let users get to the appropriate activity a lot quicker. I sure find it tedious to get to those settings myself.
</blockquote></details>

Yes, I agree, it's really tedious to find those settings. The original plan was to add a button to open the VpnSettingsActivity, however it definitively sounds like a good idea to try and check whether it's available and conditionally change/hide the information presented to the user.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3413)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
