### PR TITLE
Add iOS buildscripts for building the app on new buildservers

### PR DESCRIPTION
**Pull request by pinkisemils**
These are the new scripts the new build system uses. The script for automatically building the app will need to be adjusted slightly, but I'd rather see these scripts reviewed and committed to our repo sooner than later.

Generally, the `build.sh` no longer uploads the app to AppStore Connect, that's done by `fastlane pilot`. The build step is executed within one VM and the result is copied into another VM that does the uploading.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-:-NYXUXVk02NFGYzKgBVO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ci/ios/upload-vm/Gemfile` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NYXTAHtCKluqYRj15An:-NYXTAHtCKluqYRj15Ao:b-5s0azv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f24982ffae126ea8ecfc6084a6f46e54f76fefd/ci/ios/upload-vm/Gemfile#L1)):*
> ```Ruby
> source "https://rubygems.org"
> ```

Nit: Gemfile is already available under `iOS/` that includes fastlane, so perhaps `bundle` can inherit it from there? Again not strictly necessary to do and perhaps scopes build VM to certain set of deps as opposed to whatever we may have in `iOS/`

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ci/ios/upload-vm/Gemfile` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NYXTAHtCKluqYRj15An:-NYsCKHB4NLT4Z3BPC4j:b-2euhix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f24982ffae126ea8ecfc6084a6f46e54f76fefd/ci/ios/upload-vm/Gemfile#L1)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: Gemfile is already available under `iOS/` that includes fastlane, so perhaps `bundle` can inherit it from there? Again not strictly necessary to do and perhaps scopes build VM to certain set of deps as opposed to whatever we may have in `iOS/`
</blockquote></details>

It's a different gemfile. I'm more lenient towards changing it, so that we don't slow development. This particular one should be added to the list of files that should only be changeable with a signed commit.
___
*[`ios/build.sh` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NYXU_GM-Z98A5OkJWq4:-NYsCDmoBKfizNACN-RV:b-u4ozko) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f24982ffae126ea8ecfc6084a6f46e54f76fefd/ios/build.sh#L92)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: we could leverage building the app using fastlane over time. We do rely on xcconfigs quite a bit and fastlane offers to feed a lot of the same info via ruby script, so perhaps a bit exploration is necessary.
</blockquote></details>

As discussed elsewhere, Fastlane does all of it's magic by using our AppStore connect credentials.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Since there are a few new scripts in this PR, I believe it would be great with a `ci/ios` top-level readme that briefly describe how these are related. For example, the relationship between the following is not obvious unless digging into to all of the scripts:

```
buildserver-build-ios.sh
run-build.sh
run-in-vm-sh
../../ios/build.sh
```

> Reviewed 3 of 6 files at r1, 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-:-N_hP2O6DuYkHd8FsGDO:b-sabitn)* status: 4 of 7 files reviewed, 10 unresolved discussions (waiting on @pinkisemils and @pronebird)

___
*[`ci/ios/run-build.sh` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hUWAo-iU36Re4VlhI:-N_hUWAo-iU36Re4VlhJ:bnhgpxr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-build.sh#L1)):*
> ```Shell
> #!/usr/bin/env/ bash
> ```

I suggest renaming this script to reflect that it's also responsible for uploading.
___
*[`ci/ios/run-build.sh` line 24 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hTw7Y8Gp_KrzLsdnS:-N_hTw7Y8Gp_KrzLsdnT:b78nh4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-build.sh#L24)):*
> ```Shell
> MULLVAD_CHECKOUT_DIR="${MULLVAD_CHECKOUT_DIR:-mullvadvpn-app}"
> 
> BUILD_SCRIPT="
> ```

Is it possible to move this build/cleanup logic to any of the other scripts in order to reduce the amount of levels of logic?

As far as I understand we currently have the following levels:
1. `buildserver-build-ios.sh`
2. `run-build.sh`
3. `run-in-vm-sh`
4. `$BUILD_SCRIPT` (sent along to `run-in-vm-sh`) 
5. `../../ios/build.sh`
___
*[`ci/ios/run-in-vm.sh` line 4 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hQxLc3UZBN4TgbOsG:-N_hQxLc3UZBN4TgbOsH:b-gwu1py) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-in-vm.sh#L4)):*
> ```Shell
> # 1. tart VM name
> # 2. Script to execute in the VM
> # 3. Passthrough directory paths, formatted like "$guest_mount_name:$host_dir_path"
> ```

Does this support multiple paths or only a single one?



_Code quote:_
```Shell
Passthrough directory paths
```
___
*[`ci/ios/run-in-vm.sh` line 16 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hQmyD0gi9q8HTISu_:-N_hQmyD0gi9q8HTISua:b-s0ccwy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-in-vm.sh#L16)):*
nit: clarify that it's a directory rather than some other passthrough

>No passthrough directory provided

or 

>No passthrough directories provided



_Code quote:_
```Shell
No passthrough provided
```
___
*[`ci/ios/run-in-vm.sh` line 16 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hRZu6DgoMJKDcsc_y:-N_hRZu6DgoMJKDcsc_z:biuuu5c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-in-vm.sh#L16)):*
> ```Shell
> VM_NAME=${1:?"No VM name provided"}
> SCRIPT=${2:?"No script provided"}
> SHARED_DIR=${3:?"No passthrough provided"}
> ```

nit: to keep it consistent in the script, I suggest sticking with either "shared" or "passthrough" in vars, comments and help text.



_Code quote:_
```Shell
SHARED
```
___
*[`ci/ios/upload-vm/README.md` line 3 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hO0LA5wJ9-NTRonra:-N_hO0LA5wJ9-NTRonrb:b-d894l3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/upload-vm/README.md#L3)):*
> ```Markdown
> ## Gemfiles for uploading to Appstore Connect.
> These gemfiles specify the `fastlane` dependencies needed to run our script
> that uploads our iOS app to the AppStore.
> ```

It would be great to clarify the usage a bit further. For example, is this a single time configuration setup of the VM (and perhaps some occasional updates)?



_Code quote:_
```Markdown
These gemfiles specify the `fastlane` dependencies needed to run our script
that uploads our iOS app to the AppStore.
```
___
*[`ci/ios/upload-vm/README.md` line 5 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hGJBK5eU3Gbd_9KaK:-N_hGJBK5eU3Gbd_9KaL:b-w2t39l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/upload-vm/README.md#L5)):*
> ```Markdown
> that uploads our iOS app to the AppStore.
> 
> To set up fastlane, you should invoke `bundle` like so
> ```

nit: I suggest ending the line with a colon
___
*[`ios/build.sh` line 92 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hJ7XP3ALkdbONlHlt:-N_hJ7XP3ALkdbONlHlu:b-fh5zeo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ios/build.sh#L92)):*
> ```Shell
> 
> release_build() {
>   PATH=/usr/local/go/bin:$PATH xcodebuild \
> ```

I think it might be worth consider moving this out of the build script and to some automated or manual machine configuration steps.



_Code quote:_
```Shell
PATH=/usr/local/go/bin:$PATH 
```
___
*[`ci/ios/buildserver-build-ios.sh` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hH1eQ7rs9GaLCyQhy:-N_hH1eQ7rs9GaLCyQhz:b-g5dwou) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/buildserver-build-ios.sh#L11)):*
> ```Shell
> mkdir -p "$LAST_BUILT_DIR"
> 
> # Convince git to work on our checkout of the app repository, regardless of PWD.
> ```

Is there a specific reason we need this? I think it would be nice to skip if possible since it (1) makes the script a bit harder to follow imo and (2) isn't consistent with our other build scripts.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 2 of 11 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @pronebird)

___
*[`ci/ios/run-in-vm.sh` line 4 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hQxLc3UZBN4TgbOsG:-N_i5m5t6AG8mCtLU6A7:bos73vd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-in-vm.sh#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does this support multiple paths or only a single one?
</blockquote></details>

Just a single one, I'll elaborate.
___
*[`ci/ios/upload-vm/README.md` line 3 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hO0LA5wJ9-NTRonra:-N_i9byb0HpNUme5QVTp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/upload-vm/README.md#L3)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It would be great to clarify the usage a bit further. For example, is this a single time configuration setup of the VM (and perhaps some occasional updates)?
</blockquote></details>

Done.
___
*[`ios/build.sh` line 92 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hJ7XP3ALkdbONlHlt:-N_i8ldz7_q1YzXCkbGG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ios/build.sh#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I think it might be worth consider moving this out of the build script and to some automated or manual machine configuration steps.
</blockquote></details>

Done.
___
*[`ci/ios/run-build.sh` line 24 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hTw7Y8Gp_KrzLsdnS:-N_i5f10CPO6-31nHhDe:bih91ok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/run-build.sh#L24)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is it possible to move this build/cleanup logic to any of the other scripts in order to reduce the amount of levels of logic?

As far as I understand we currently have the following levels:
1. `buildserver-build-ios.sh`
2. `run-build.sh`
3. `run-in-vm-sh`
4. `$BUILD_SCRIPT` (sent along to `run-in-vm-sh`) 
5. `../../ios/build.sh`

</blockquote></details>

I'll move `$BUILD_SCRIPT`s out to separate files. 
___
*[`ci/ios/buildserver-build-ios.sh` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_hH1eQ7rs9GaLCyQhy:-N_i5Qjr4uach6fua9KB:b-z64ntx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95c251990eb0ca47e392f5c243843d92c7d74a17/ci/ios/buildserver-build-ios.sh#L11)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a specific reason we need this? I think it would be nice to skip if possible since it (1) makes the script a bit harder to follow imo and (2) isn't consistent with our other build scripts.
</blockquote></details>

It's easier to have this script run from a level below as all of the scripts this one invokes must reside outside the repository.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: all files reviewed, 5 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/ios/build-app.sh` line 1 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_rhaAA7XOHw-8ixLDt:-N_rhaAA7XOHw-8ixLDu:bvz1k3i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b58b25e5f892abf03e423e9ec5c38dffc08f2e6/ci/ios/build-app.sh#L1)):*
> ```Shell
> #!/usr/bin/env zsh
> ```

The result of this command would differ depending on where the script is called from. See comment in `upload-app.sh` for more info. 
___
*[`ci/ios/run-build-and-upload.sh` line 9 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_rhGBh6bxFwZfPMznL:-N_rhGBh6bxFwZfPMznM:b-kdytf2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b58b25e5f892abf03e423e9ec5c38dffc08f2e6/ci/ios/run-build-and-upload.sh#L9)):*
> ```Shell
> # reachable via SSH without a password via the SSH key located in
> # ~/.ssh/ios-vm-key.
> ```

nit: remove newline
___
*[`ci/ios/run-build-and-upload.sh` line 27 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_rhIto1qWzOZywwN5J:-N_rhIto1qWzOZywwN5K:b-kdytf2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b58b25e5f892abf03e423e9ec5c38dffc08f2e6/ci/ios/run-build-and-upload.sh#L27)):*
> ```Shell
> cp "${MULLVAD_CHECKOUT_DIR}/ios/Build/MullvadVPN.ipa" build-output/MullvadVPN.ipa
> ```

nit: remove newline
___
*[`ci/ios/upload-app.sh` line 6 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_reDeM1B8fmSkHmqoq:-N_reDeN8HMIZrkbCvDp:b-op9m8j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b58b25e5f892abf03e423e9ec5c38dffc08f2e6/ci/ios/upload-app.sh#L6)):*
> ```Shell
> VM_UPLOAD_IPA_PATH="/Volumes/My\ Shared\ Files/build-output/MullvadVPN.ipa"
> API_KEY_PATH="~/ci/app-store-connect-key.json"
> cd ci/
> ```

The result of this command would differ depending on where the script is called from. Even though this script is a bit different from many of our other scripts in the sense that it runs in a VM (and runs using `zsh`), I believe it might be a good idea to somehow ensure that the script behaves as expected regardless where it's called from. 


Example from some of our other scripts:
```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"
```

This comment also applies to `build-app.sh` and perhaps other scripts as well.



_Code quote:_
```Shell
cd ci/
```

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad)

___
*[`ci/ios/upload-app.sh` line 6 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_reDeM1B8fmSkHmqoq:-N_t4YA53qVpXFq-Eudc:b1ch69a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b58b25e5f892abf03e423e9ec5c38dffc08f2e6/ci/ios/upload-app.sh#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The result of this command would differ depending on where the script is called from. Even though this script is a bit different from many of our other scripts in the sense that it runs in a VM (and runs using `zsh`), I believe it might be a good idea to somehow ensure that the script behaves as expected regardless where it's called from. 


Example from some of our other scripts:
```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"
```

This comment also applies to `build-app.sh` and perhaps other scripts as well.
</blockquote></details>

The `SCRIPT_DIR` would end up being `/dev/stdin` because it's piped in. I'll just document the assumption that it's expected to be ran from the ~ of it's designated VM.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @pinkisemils)

___
*[`ci/ios/build-app.sh` line 1 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NavgFMhB_46ukra4N1g:-NavgFMi6spcZjGGza8T:bsr0kwg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a9b807eff45b8df9f793bb916d89a4185681874/ci/ios/build-app.sh#L1)):*
> ```Shell
> #!/usr/bin/env zsh
> ```

Which part of this is not able to run in bash? I see it later invokes bash. If it's incompatible with bash we can of course keep zsh. But if it's not strictly needed I'd rather see we keep using the same scripting language as everywhere else.
___
*[`ci/ios/upload-app.sh` line 8 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NavfGd-DYnd1_qmyf7z:-NavfGd-DYnd1_qmyf8-:bhzh3sa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a9b807eff45b8df9f793bb916d89a4185681874/ci/ios/upload-app.sh#L8)):*
> ```Shell
> cd ci/
> source ~/.zshrc
> source ~/.zprofile
> ```

Why doesn't zsh load these by default? Seems strange that we would need to explicitly do such fundamental stuff.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 6 of 11 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`ci/ios/build-app.sh` line 1 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NavgFMhB_46ukra4N1g:-Nd0Jv702FvM2x43lzra:b-scfpxr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a9b807eff45b8df9f793bb916d89a4185681874/ci/ios/build-app.sh#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Which part of this is not able to run in bash? I see it later invokes bash. If it's incompatible with bash we can of course keep zsh. But if it's not strictly needed I'd rather see we keep using the same scripting language as everywhere else.
</blockquote></details>

It's been bashified now.
___
*[`ci/ios/upload-app.sh` line 8 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-NavfGd-DYnd1_qmyf7z:-Ncfv2eI1_1ufgVuK3U_:b-7f62jo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a9b807eff45b8df9f793bb916d89a4185681874/ci/ios/upload-app.sh#L8)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why doesn't zsh load these by default? Seems strange that we would need to explicitly do such fundamental stuff.
</blockquote></details>

These were not being sourced when the script was being invoked over SSH, possibly due to zsh not being ran interactively. The bash version does the same now.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 5 of 11 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`ci/ios/build-app.sh` line 8 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-Nd0KPPhA2PoN0eqgdYK:-Nd53pwI6I7XqLZRwQgA:bvvbijt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3dac4fcc8a943b00cb8a28d1458bc09e1fc51b73/ci/ios/build-app.sh#L8)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

> # This single path ...

Does that comment relate to `set -eu`? Currently it looks like it and it makes me confused.
</blockquote></details>

It's meant to explain `VM_BUILD_DIR`.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`ci/ios/upload-app.sh` line 6 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-N_reDeM1B8fmSkHmqoq:-Nd5IoumCmSozfEDp3zH:b-zcmp87) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b58b25e5f892abf03e423e9ec5c38dffc08f2e6/ci/ios/upload-app.sh#L6)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The `SCRIPT_DIR` would end up being `/dev/stdin` because it's piped in. I'll just document the assumption that it's expected to be ran from the ~ of it's designated VM. 
</blockquote></details>

Alright, sounds good! Didn't think of that even though I was aware of the use case :facepalm:

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 3 of 5 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/ios/build-app.sh` line 26 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-Nd5SaAH4FcjtkBOS7rL:-Nd5SaAIDPEszV1Qc-Mf:b-k0464q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/286790a613e249493286838c774cba14573a601d/ci/ios/build-app.sh#L26)):*
> ```Shell
>     bash build.sh
> 
> cp "$HOME/build/ios/Build/MullvadVPN.ipa" "/Volumes/My Shared Files/build/ios/Build/"
> ```

Please use `$VM_BUILD_DIR` instead of hard coding the path a second time.
___
*[`ci/ios/build-app.sh` line 26 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-Nd5SgmK6a-P9jiYgxAY:-Nd5SgmK6a-P9jiYgxAZ:b-trz6u4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/286790a613e249493286838c774cba14573a601d/ci/ios/build-app.sh#L26)):*
> ```Shell
>     bash build.sh
> 
> cp "$HOME/build/ios/Build/MullvadVPN.ipa" "/Volumes/My Shared Files/build/ios/Build/"
> ```

Inconsistent use of `~` vs `$HOME`

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`ci/ios/build-app.sh` line 26 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-Nd5SgmK6a-P9jiYgxAY:-Nd5ZjvW-r7pz58EZkmz:b7iu8n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/286790a613e249493286838c774cba14573a601d/ci/ios/build-app.sh#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Inconsistent use of `~` vs `$HOME`
</blockquote></details>

`$HOME` works here but `~` doesn't. We don't use `$HOME` anywhere else, this is due to how the string is escaped here.
___
*[`ci/ios/build-app.sh` line 26 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-Nd5SaAH4FcjtkBOS7rL:-Nd5Zs5bDSByqzgm3lnd:bbhl1ws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/286790a613e249493286838c774cba14573a601d/ci/ios/build-app.sh#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please use `$VM_BUILD_DIR` instead of hard coding the path a second time.
</blockquote></details>

Let's see if this works. I'd prefer to change these files as little as possible given how they've been edited for 3 months and testing each change is painfully slow. And the jankiness of the whole thing doesn't help.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/ios/build-app.sh` line 26 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816#-Nd5SgmK6a-P9jiYgxAY:-Nd5dB2UCxwLNJ6rNCtY:bu1jcsu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/286790a613e249493286838c774cba14573a601d/ci/ios/build-app.sh#L26)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`$HOME` works here but `~` doesn't. We don't use `$HOME` anywhere else, this is due to how the string is escaped here.
</blockquote></details>

But you reference `~/build/` (with either `~` or `$HOME` four times in this script. Would it not then make sense to define it as a variable at the top and use that? That would also make it consistent.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by faern — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4816)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
