### PR TITLE
Add multi-hop toggle to settings view

### PR DESCRIPTION
**Pull request by mojganii**
This PR allows users to change the multi-hop state in the settings view.

<table style="width:50%">
  <tr>
    <th>Before</th>
    <th>After</th> 
  </tr>
  <tr>
    <td></td>
    <td>

</td>
  </tr>
</table>

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
The cell stays selected if I tap on it, we should disable selection for this specific cell.
[MultiSelect.mov](https://files.reviewableusercontent.io/images/reviewable/129761703/JY_UBdw-mxt6MdrIAzTU5QQr/MultiSelect.mov)

> Reviewed 9 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-:-O-1vldKCw8k8pOIcCTo:bo2bott)* status: 9 of 24 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-1wePDCPWxKFYqMM8k:-O-1wePDCPWxKFYqMM8l:bx9oiq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47c8e1d83c280823fbde372ef90a43a4cf3e92c2/ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift#L56)):*
nit:
> if the multihop **settings** have changed 
___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-5cfgX7n3jSDGGjzNE:-O-5cfgX7n3jSDGGjzNF:bjyy5ei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47c8e1d83c280823fbde372ef90a43a4cf3e92c2/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSDataSource.swift#L123)):*
> ```Swift
>     private weak var tableView: UITableView?
> 
>     weak var delegate: DnsSettingsDataSourceDelegate?
> ```

nit
It should be `DNSSettingsDataSourceDelegate?` 
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-5dQBd-LJju5Fhd3Z7:-O-5dQBd-LJju5Fhd3Z8:b-pv4wrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47c8e1d83c280823fbde372ef90a43a4cf3e92c2/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift#L23)):*
> ```Swift
>     func showIPOverrides()
>     func didSelectWireGuardPort(_ port: UInt16?)
>     func showMultihopConfirmation(_ onSave: @escaping () -> Void, _ onDiscard: @escaping () -> Void)
> ```

We should leave the name arguments here, otherwise, it's really hard to tell which closure will do what on the call site.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335)* status: 9 of 24 files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 245 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-FnAfa-a3E9anRSKIE:-O-FnAfa-a3E9anRSKIF:b-c9jfpb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3bcde84a520e5306f2fe8a07ebf135f960e5100d/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L245)):*
> ```Swift
>             for await newState in stateStream {
>                 // Pass relay constraints retrieved during the last read from setting into transport provider.
>                 if let relayConstraints = newState.relayConstraints {
> ```

Why was this line removed ?

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335)* status: 9 of 24 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-1wePDCPWxKFYqMM8k:-O-FqCcOE3QtUs4dmt9S:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47c8e1d83c280823fbde372ef90a43a4cf3e92c2/ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift#L56)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit:
> if the multihop **settings** have changed
</blockquote></details>

done
___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-5cfgX7n3jSDGGjzNE:-O-FpuPe2g5EkjkevgEy:b-2stbqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47c8e1d83c280823fbde372ef90a43a4cf3e92c2/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSDataSource.swift#L123)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
It should be `DNSSettingsDataSourceDelegate?`
</blockquote></details>

Right, it's acronym.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-5dQBd-LJju5Fhd3Z7:-O-FqG08DlkOh95YaIW6:b-3cslex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47c8e1d83c280823fbde372ef90a43a4cf3e92c2/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift#L23)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should leave the name arguments here, otherwise, it's really hard to tell which closure will do what on the call site.
</blockquote></details>

indeed!
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 245 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-O-FnAfa-a3E9anRSKIE:-O-Fp4Eo64VaDmUW4kTL:b-ilsydv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3bcde84a520e5306f2fe8a07ebf135f960e5100d/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L245)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why was this line removed ?
</blockquote></details>

we are tracking the value or relay constraints above. we don't need fetch that from connection state.

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 3 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335)* status: 9 of 24 files reviewed, 2 unresolved discussions

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335#-:-O-GUESM8iu8vWh6JVp1:bnfp4nl)* status: 9 of 24 files reviewed, 1 unresolved discussion

**Pull request merged**
