### PR TITLE
Add detekt

### PR DESCRIPTION
**Pull request by Rawa**
This PR adds detekt as a linting to ensure we have nice code quality in our project. We've done some evaluation and have opted not to use it for formatting. There we will keep using ktfmt until we see a clear benefit to switch to something else.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Please add a description to the PR where you clarify how we intend to use detekt as of this PR.

> Reviewed 20 of 22 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-:-NousxYq4Df8hcv5jcEl:biuo8j)* status: 20 of 24 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/build.gradle.kts` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-Nousj9o2qsyanHprYV_:-Nousj9o2qsyanHprYVa:b62ito6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5f04e43501599554978bc236371407a1a5c899c/android/build.gradle.kts#L32)):*
> ```Kotlin
> allprojects {
>     apply(plugin = Dependencies.Plugin.dependencyCheckId)
>     apply(plugin = Dependencies.Plugin.ktfmtId)
> ```

Are we completely removing ktfmt? Wasn't the plan to use it in combination with detekt? :thinking: 
___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NousKJJ2GPpucA53_WK:-NousKJJ2GPpucA53_WL:b-teshe4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d711288da29a51f0ad8ff19a2eb0ecf2b89a0379/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L144)):*
> ```Kotlin
>             is Inet4Address -> 32
>             is Inet6Address -> 128
>             else -> throw IllegalArgumentException("Invalid IP address (not IPv4 nor IPv6)")
> ```

Just to double check; was this one incorrect before?



_Code quote:_
```Kotlin
IllegalArgumentException
```
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NourNlh95zq--coIov-:-NourNlh95zq--coIov0:b7cc5y4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5f04e43501599554978bc236371407a1a5c899c/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L11)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.ipc.Event
> import net.mullvad.mullvadvpn.lib.ipc.Request
> import net.mullvad.mullvadvpn.model.*
> ```

Is there a risk that expanding the imports might affect ktfmt or the android studio formatting?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: 20 of 24 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NousKJJ2GPpucA53_WK:-NouuPe0CkDyE6oVOYzX:bwf82ty) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d711288da29a51f0ad8ff19a2eb0ecf2b89a0379/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L144)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just to double check; was this one incorrect before?
</blockquote></details>

We got a warning for using a too generic exception. Thus I updated throw an `IlleagalArgumentException`  
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NourNlh95zq--coIov-:-Novwd0Z6qQTgPXbOwL-:b-vschko) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5f04e43501599554978bc236371407a1a5c899c/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L11)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a risk that expanding the imports might affect ktfmt or the android studio formatting?
</blockquote></details>

I tried Android Studio Reformat Code and ktfmtFormat, none complained about expanding them. I believe the default in android studio should also not use wildcard.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: 17 of 24 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/build.gradle.kts` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-Nousj9o2qsyanHprYV_:-NovyoTZAdEl2OKfsMvu:b-ag40ua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5f04e43501599554978bc236371407a1a5c899c/android/build.gradle.kts#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are we completely removing ktfmt? Wasn't the plan to use it in combination with detekt? :thinking:
</blockquote></details>

Issue with Android Studio not showing diffs correctly. Restored now.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: 23 of 24 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`-- commits` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxB4htBydz3pnaJHSq):*
Reminder to clean up the commit history a bit before merging.
___
*[`android/build.gradle.kts` line 57 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxAlVL5FRmrZemLb8b:-NoxAlVL5FRmrZemLb8c:b-fxonoi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/build.gradle.kts#L57)):*
> ```Kotlin
> 
> // Kotlin DSL
> tasks.withType<Detekt>().configureEach { jvmTarget = "1.8" }
> ```

Is there a reason for not using `Versions.jvmTarget`? It's set to `"17"` btw. Same applies below.



_Code quote:_
```Kotlin
jvmTarget = "1.8"
```
___
*[`android/config/detekt.yml` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBs3i27YfGrjV5Hc2:-NoxBs3i27YfGrjV5Hc3:b-bdj3xc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L1)):*
> ```YAML
> build:
> ```

Is this file based on some default suggestions? It might be nice to add some info or documentation regarding that to the file as a header. Also, if any deviations are made from the default suggestion, it would be nice clarify using comments.
___
*[`android/config/detekt.yml` line 94 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBIOR4_tb4kcM_2kR:-NoxBIOR4_tb4kcM_2kS:bxcewmk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L94)):*
> ```YAML
>       - '**/androidInstrumentedTest/**'
>       - '**/jsTest/**'
>       - '**/iosTest/**'
> ```

Are these needed? :thinking: 

This also applies to some more parts of this file.



_Code quote:_
```YAML
      - '**/jsTest/**'
      - '**/iosTest/**'
```
___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NousKJJ2GPpucA53_WK:-NoxABHfCocL9lsJQ8jI:brpdree) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d711288da29a51f0ad8ff19a2eb0ecf2b89a0379/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L144)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We got a warning for using a too generic exception. Thus I updated throw an `IlleagalArgumentException`
</blockquote></details>

Aha, so `RuntimeException` is counted as too generic?
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NourNlh95zq--coIov-:-NoxA7EyCEf1hlbArpOp:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5f04e43501599554978bc236371407a1a5c899c/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L11)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I tried Android Studio Reformat Code and ktfmtFormat, none complained about expanding them. I believe the default in android studio should also not use wildcard.
</blockquote></details>

Alright :thumbsup:

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 21 files at r7, 1 of 19 files at r8, 19 of 19 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: all files reviewed, 5 unresolved discussions (waiting on @Rawa)

___
*[`android/build.gradle.kts` line 32 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NpJnn-WCG1MJnmOjqc9:-NpJnn-X9od5ffEhBlCk:basmxjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0c5a8fd0e07e77481f61388a0c4df6ccca76ce3/android/build.gradle.kts#L32)):*
> ```Kotlin
> allprojects {
>     apply(plugin = Dependencies.Plugin.dependencyCheckId)
>     apply(plugin = Dependencies.Plugin.ktfmtId)
> ```

Will this mean that we no longer will have formatting done by ktfmt
___
*[`android/build.gradle.kts` line 44 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NpJnswG8uNvqNfUJVGu:-NpJnswG8uNvqNfUJVGv:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0c5a8fd0e07e77481f61388a0c4df6ccca76ce3/android/build.gradle.kts#L44)):*
> ```Kotlin
>     }
> 
>     configure<com.ncorti.ktfmt.gradle.KtfmtExtension> {
> ```

See above

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: 3 of 24 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/build.gradle.kts` line 57 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxAlVL5FRmrZemLb8b:-NpOWSDT9n0LrjCaENhx:b-6vvh43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/build.gradle.kts#L57)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a reason for not using `Versions.jvmTarget`? It's set to `"17"` btw. Same applies below.
</blockquote></details>

Thanks, legacy, cleaned up :)
___
*[`android/build.gradle.kts` line 32 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NpJnn-WCG1MJnmOjqc9:-NpOWX4s0GPJmv2dUcuJ:bp47e8c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0c5a8fd0e07e77481f61388a0c4df6ccca76ce3/android/build.gradle.kts#L32)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Will this mean that we no longer will have formatting done by ktfmt
</blockquote></details>

Reviewable shows these lines really weird for me, didn't show any change. Now it shows it as an addition. I've tried to restore them now.
___
*[`android/build.gradle.kts` line 44 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NpJnswG8uNvqNfUJVGu:-NpOWeYU1KhHXMOFXyQu:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0c5a8fd0e07e77481f61388a0c4df6ccca76ce3/android/build.gradle.kts#L44)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

See above
___
*[`android/config/detekt.yml` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBs3i27YfGrjV5Hc2:-NpOPo5N5Ykbe98NSNLb:b-izqipx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this file based on some default suggestions? It might be nice to add some info or documentation regarding that to the file as a header. Also, if any deviations are made from the default suggestion, it would be nice clarify using comments.
</blockquote></details>

Yes, one can generate a basic config from `./gradlew detektGenerateConfig` then I've done some corrections to make it play nice with compose etc.
___
*[`android/config/detekt.yml` line 94 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBIOR4_tb4kcM_2kR:-NpOPfFC8j432b_e8T_A:b-cmft1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L94)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are these needed? :thinking: 

This also applies to some more parts of this file.
</blockquote></details>

Not really, but part of the standard generated config. I was thinking less change makes us less prone to have unexpected behavior. Do you think we should remove it?
___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NousKJJ2GPpucA53_WK:-NpOPW9e5gpnH8uHsQaD:b-sq193a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d711288da29a51f0ad8ff19a2eb0ecf2b89a0379/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L144)):*
Yes, not sure exact logic for that rule but it warned it to be too generic in this case.

```
> Task :detekt FAILED
/Users/rawa/Code/mullvadvpn-app/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt:144:21: RuntimeException is a too generic Exception. Prefer throwing specific exceptions that indicate a specific error case. [TooGenericExceptionThrown]```
```

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 21 files at r10, 1 of 1 files at r11, 19 of 19 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-:-NpTR0tbCx2cpx5uXdDt:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
@Rawa did you see my comment above? :arrow_up: 

> Reviewed 1 of 21 files at r10, 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-:-Np_CUgK3logf-YnELlK:b9hnvrh)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/config/detekt.yml` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBs3i27YfGrjV5Hc2:-Np_DWbL7oIuFR5cKzO3:b-gb8vrj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L1)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yes, one can generate a basic config from `./gradlew detektGenerateConfig` then I've done some corrections to make it play nice with compose etc.
</blockquote></details>

Can we add the generated config as a separate commit to clarify that it's genereated as well as easily see what we've changed from the default?
___
*[`android/config/detekt.yml` line 94 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBIOR4_tb4kcM_2kR:-Np_Cb-Y7CzW_3Ondkg6:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L94)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not really, but part of the standard generated config. I was thinking less change makes us less prone to have unexpected behavior. Do you think we should remove it?
</blockquote></details>

Alright :thumbsup:

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 1 files at r11, 18 of 19 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
@albin-mullvad Fixed!

> Reviewed 1 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-:-NpeRVUg4nPe_2pAhdQM:b26a3l4)* status: 19 of 24 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`android/config/detekt.yml` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-NoxBs3i27YfGrjV5Hc2:-NpeR_NM4u9WAJN8UlTk:b-dqsts6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77c8d94dea22dfacf83497b3056345ac930e548c/android/config/detekt.yml#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we add the generated config as a separate commit to clarify that it's genereated as well as easily see what we've changed from the default?
</blockquote></details>

I've now split them out to 2 separate commits

**Review by Rawa — COMMENTED** [review]
> Reviewed 4 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: 19 of 24 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by Rawa — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: 19 of 24 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539#-:-NpsqJHT7XQn8fcBQtzP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5539)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
