### PR TITLE
Use custom flavor endpoints

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to use custom flavor endpoints for development and testing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/di/ApiEndpointModule.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294#-NgrQkggEWlYj_YbXrTp:-Ngre8wWED6IlSlSmRiC:bsfc4ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c002b6e76d5c764721cc52a45f697e2f4b23aa7e/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/di/ApiEndpointModule.kt#L13)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Just to make sure since this is a bit of a magic number:
Should we switch this number to either a build config or a defined constant? I guess this might be useful in the future.
</blockquote></details>

Add a constant!

**Comment by albin-mullvad** [comment]
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294)_ status: 5 of 7 files reviewed, all discussions resolved (waiting on @Pururun)
> 
> _[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/di/ApiEndpointModule.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294#-NgrQkggEWlYj_YbXrTp:-Ngre8wWED6IlSlSmRiC:bsfc4ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c002b6e76d5c764721cc52a45f697e2f4b23aa7e/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/di/ApiEndpointModule.kt#L13)):_
> Previously, Pururun (Jonatan Rhodin) wrote…
> 
> Add a constant!

added* :laughing:

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294#-:-NgrhkVv6i-vHtXS_c5g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
