### PR TITLE
Add device management

### PR DESCRIPTION
**Pull request by pronebird**
- Add device management controller that enables users to delete existing devices before being able to log-in.
- Handle `MAX_DEVICES_REACHED` error during login and show device management controller.
- Change `DevicesProxy.getDevice()` to return `REST.Error` (`.deviceNotFound`) instead of `nil` when device no longer exists.
- Detect if device was revoked by analysing key rotation error.
- Drop `RevokedDeviceError` as it's more or less superficial error. Use `REST.Error.compareErrorCode(.deviceNotFound)` instead to determine device revocation.
- Bridge `DataSnapshotDifference` with `UIStackView` to apply changes with folding animation.
- Few minor changes related to formatting and logger names. Some unused `logger`s were also removed.
- Remove `Equatable` from `ServerRelay`. It was introduced by mistake.
- Relax horizontal constraint priority in `SelectLocationCell`. Fixes layout related warnings on iPad.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805)

### CODE REVIEW

**Review by AndreasShortcut — APPROVED** [review]
> Reviewed 20 of 20 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805)* status: all files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/DataSourceSnapshot.swift` line 486 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8P2o-t6nCLZb8nraFL:-N8P2o-u1NHDwZosiQMO:b-byr7k5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DataSourceSnapshot.swift#L486)):*
> ```Swift
> 
>         // Layout inserted subviews before running animations to achieve a folding effect.
>         if animateDifferences {
> ```

Perhaps `shouldAnimateDifferences`?
___
*[`ios/MullvadVPN/DataSourceSnapshot.swift` line 504 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8P39vA01U15Te007kA:-N8P39vA01U15Te007kB:b-fj8vq0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DataSourceSnapshot.swift#L504)):*
> ```Swift
>         }
> 
>         let removeViewsAfterAnimationFinished = {
> ```

The `AfterAnimationFinished` part seems unnecessary
___
*[`ios/MullvadVPN/DeviceManagementContentView.swift` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8SXf9i7mxjPGP__zZC:-N8SXf9i7mxjPGP__zZD:bpbeni0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DeviceManagementContentView.swift#L105)):*
> ```Swift
> 
>         let applyConfiguration = StackViewApplyDataSnapshotConfiguration { indexPath in
>             let view = DeviceRowView()
> ```

Maybe it's nicer to initialize by passing the view model into the view?
___
*[`ios/MullvadVPN/DeviceManagementViewController.swift` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8SUsHX1Bha0y-uJjza:-N8SUsHY4j_h_MY6OmW7:bd6ah98) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DeviceManagementViewController.swift#L183)):*
> ```Swift
>     }
> 
>     private func showDeleteConfirmation(deviceName: String, _ completion: @escaping (Bool) -> Void)
> ```

I would suggest keeping the argument label on the completion block for clarity
___
*[`ios/MullvadVPN/DeviceRowView.swift` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8Sa0pY7d5mriRUn1W9:-N8Sa0pY7d5mriRUn1WA:b-5k2r7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DeviceRowView.swift#L72)):*
> ```Swift
> 
>         for subview in [textLabel, removeButton, activityIndicator] {
>             addSubview(subview)
> ```

Perhaps we should make an extension to add an array of subviews? E.g.
```
extension UIView {
    func addSubviews(_ subviews: [UIView]) {
        subviews.forEach { addSubview($0) }
    }
}
```

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805)* status: all files reviewed, 2 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/DataSourceSnapshot.swift` line 486 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8P2o-t6nCLZb8nraFL:-N8Sq4xa6CiUT43ljhqX:b-ocegkg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DataSourceSnapshot.swift#L486)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Perhaps `shouldAnimateDifferences`?
</blockquote></details>

Do booleans have to have `should` prefix?
___
*[`ios/MullvadVPN/DataSourceSnapshot.swift` line 504 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8P39vA01U15Te007kA:-N8Sr5p-6yWMUpaiInpR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DataSourceSnapshot.swift#L504)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

The `AfterAnimationFinished` part seems unnecessary
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/DeviceManagementContentView.swift` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8SXf9i7mxjPGP__zZC:-N8Ss0Hd3B9I_kKvNUBO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DeviceManagementContentView.swift#L105)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Maybe it's nicer to initialize by passing the view model into the view?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/DeviceManagementViewController.swift` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8SUsHX1Bha0y-uJjza:-N8SqaaKBJPpB-YojPq6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DeviceManagementViewController.swift#L183)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

I would suggest keeping the argument label on the completion block for clarity
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/DeviceRowView.swift` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8Sa0pY7d5mriRUn1W9:-N8SqjTv6O8hEZ-QukzJ:b-uu8sum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DeviceRowView.swift#L72)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Perhaps we should make an extension to add an array of subviews? E.g.
```
extension UIView {
    func addSubviews(_ subviews: [UIView]) {
        subviews.forEach { addSubview($0) }
    }
}
```
</blockquote></details>

Note that this code can also be rewritten using `forEach()`:

 ```
[ /*subviews*/ ].forEach(addSubview)
```

Perhaps a matter of personal choice.

Let's keep it simple for now. Less extensions = less dependencies. Introduction of such extension would have a significant impact/footprint on the codebase and this PR is large enough.

**Review by AndreasShortcut — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/DataSourceSnapshot.swift` line 486 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805#-N8P2o-t6nCLZb8nraFL:-N8TEpQn9z83Ig3RbbgX:beknob9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e002a103389a2a1cbce991c8b47834b291105770/ios/MullvadVPN/DataSourceSnapshot.swift#L486)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Do booleans have to have `should` prefix?
</blockquote></details>

Of course not, but is/should is pretty common. Makes the sentence read more like natural language. Also, it's just a suggestion, feel free to ignore it if you don't agree.

**Review by AndreasShortcut — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3805)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
