### PR TITLE
Ignore API IP rotations when the machine is offline

### PR DESCRIPTION
**Pull request by dlon**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864#-MfXEi-8AoFpb3I0ykGA:-MfXEi-A3UBCogUiRYh1:b-yrptc6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9aa39115946f4d00b1b03c0d5e7801b1272e58f/talpid-core/src/tunnel_state_machine/connected_state.rs#L200)):*
> ```XML
>             }
>             Some(TunnelCommand::AllowEndpoint(endpoint, tx)) => {
>                 if shared_values.is_offline {
> ```

I think that when the machine is offline, the TSM should never even receive the _allow endpoint_ command - the address cache shouldn't be rotating the address anyway. Otherwise, if the endpoint is rotated but a hole in the firewall isn't punched, requests will fail regardless.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864#-MfXEi-8AoFpb3I0ykGA:-MgegNjL3Eef8PqSHEfF:bq1fwhx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9aa39115946f4d00b1b03c0d5e7801b1272e58f/talpid-core/src/tunnel_state_machine/connected_state.rs#L200)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think that when the machine is offline, the TSM should never even receive the _allow endpoint_ command - the address cache shouldn't be rotating the address anyway. Otherwise, if the endpoint is rotated but a hole in the firewall isn't punched, requests will fail regardless.
</blockquote></details>

If the TSM rejects it, then the rotation doesn't actually occur. But I agree that this is more of a band-aid fix than a good one.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2864#-MfXEi-8AoFpb3I0ykGA:-MgexnmZCND5l09sk5vV:b-wsx8ov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9aa39115946f4d00b1b03c0d5e7801b1272e58f/talpid-core/src/tunnel_state_machine/connected_state.rs#L200)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If the TSM rejects it, then the rotation doesn't actually occur. But I agree that this is more of a band-aid fix than a good one.
</blockquote></details>

I'd rework this to have the address cache check if it's online or offline. Maybe we need to multicast the offline state to both the TSM and the address cache? Maybe there should be another channel that allows the TSM to send messages to the daemon - this could be useful for the custom resolver to be able to report errors when it fails to bind to port 53 without stopping the whole TSM during startup.

**Comment by dlon** [comment]
Superseded: #2937.

**Pull request closed without merging**
