### PR TITLE
Support custom DNS on macOS

### PR DESCRIPTION
**Pull request by dlon**
Support custom DNS on macOS. The details are essentially the same as in https://github.com/mullvad/mullvadvpn-app/pull/2210.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/firewall/macos.rs, line 167 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKfHOhN1Iv8d23mqEOp:-MKfHOhN1Iv8d23mqEOq:bdx56al) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/313275939c99722758242d455e18abc5d647f622/talpid-core/src/firewall/macos.rs#L167)):*
> ```Rust
>         if is_local {
>             // Block requests on the tunnel interface
>             let block_tunnel_tcp = self
> ```

Is the block necessary? Sure, we don't want the DNS requests to seep into the tunnel, but if it's already routed through the tunnel interface, there's no way it'll reach the destination. And since the user has specified a local resolver, they probably need to ensure that it'll be routed outside the tunnel anyway. On macOS and Linux this could be tested before going into the connected state.
___
*[talpid-core/src/firewall/macos.rs, line 199 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKfJpbI8DVJuRbCxT8A:-MKfJpbJ6hcsGsoG4GgV:b-z1iw4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/313275939c99722758242d455e18abc5d647f622/talpid-core/src/firewall/macos.rs#L199)):*
> ```Rust
>             let allow_nontunnel_udp = self
>                 .create_rule_builder(FilterRuleAction::Pass)
>                 .direction(pfctl::Direction::Out)
> ```

You shouldn't have to specify 2 rules each to allow traffic to flow both ways, you should be able to just not specify the direction, and make the rule keep state.
___
*[talpid-core/src/firewall/macos.rs, line 551 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKfGjhW8kGtdMDTzNtq:-MKfGjhW8kGtdMDTzNtr:bbaeq2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/313275939c99722758242d455e18abc5d647f622/talpid-core/src/firewall/macos.rs#L551)):*
> ```Rust
>     for net in (&*super::ALLOWED_LAN_NETS)
>         .iter()
>         .chain(&*super::LOOPBACK_NETS)
> ```

I think this can be simplified to `(&*super::ALLOWED_LAN_NETS).iter().chain(&*super::LOOPBACK_NETS).any(|net| net.contains(*address))`. And I think something like this is implemented elswhere in `talpid-core`, maybe even in a firewall module for another platform. It'd be better not to repeat this code.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/firewall/macos.rs, line 167 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKfHOhN1Iv8d23mqEOp:-MKio3ZtCI-oGF2WQLPN:bn9kbk5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/313275939c99722758242d455e18abc5d647f622/talpid-core/src/firewall/macos.rs#L167)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is the block necessary? Sure, we don't want the DNS requests to seep into the tunnel, but if it's already routed through the tunnel interface, there's no way it'll reach the destination. And since the user has specified a local resolver, they probably need to ensure that it'll be routed outside the tunnel anyway. On macOS and Linux this could be tested before going into the connected state.
</blockquote></details>

It's probably necessary to enforce that random LAN addresses don't leak into the tunnel and eventually get out to the internet.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214)* status: 11 of 16 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 199 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKfJpbI8DVJuRbCxT8A:-MKiuCf91SOFsGbpL0dt:bh7nx2c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/313275939c99722758242d455e18abc5d647f622/talpid-core/src/firewall/macos.rs#L199)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

You shouldn't have to specify 2 rules each to allow traffic to flow both ways, you should be able to just not specify the direction, and make the rule keep state.
</blockquote></details>

Done. Although it may still specify the direction.
___
*[talpid-core/src/firewall/macos.rs, line 551 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKfGjhW8kGtdMDTzNtq:-MKiuQoYDx8sk0aptpQK:b-nliye9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/313275939c99722758242d455e18abc5d647f622/talpid-core/src/firewall/macos.rs#L551)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think this can be simplified to `(&*super::ALLOWED_LAN_NETS).iter().chain(&*super::LOOPBACK_NETS).any(|net| net.contains(*address))`. And I think something like this is implemented elswhere in `talpid-core`, maybe even in a firewall module for another platform. It'd be better not to repeat this code.
</blockquote></details>

Done. I used the same code for nftables.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/routing/linux.rs, line 821 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-MKiw2Kd2EqhIAlDHGK5:-MKiw2Kd2EqhIAlDHGK6:b-mkvvkh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a60b383a64c9538c08b5d2f5f7d3dff79c3a78f3/talpid-core/src/routing/linux.rs#L821)):*
> ```Rust
> 
>     async fn delete_route_if_exists(&self, route: &Route) -> Result<()> {
>         if let Err(error) = self.delete_route(route).await {
> ```

Technically this could be improved to have less indentation by using a match statement with arms for`Err(Error::NetlinkError(rnetlink::Error::NetlinkError(msg))) if msg.code == -lib::ESRCH`, `Ok()` returning `Ok(())` and an arm for passing through the real error.

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214#-:-MKj12bwDViEUeN-pQcT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
