### PR TITLE
Allow users to disable split tunneling when FDA is off

### PR DESCRIPTION
**Pull request by olmoh**
Fixes DES-1521

This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)

### CODE REVIEW

**Comment by olmoh** [comment]
Fixes DES-1521

**Review by hulthe — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321#-OEDygZaCnGUScR_D8cT:-OEDygZaCnGUScR_D8cU:b729l2h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d82b56afced040788f26a8b7b1322e30d03123ff/desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx#L67)):*
> ```XML
>   const disableSplitTunneling = useCallback(async () => {
>     setIsModalOpen(false);
>     await setSplitTunnelingState(false);
> ```

Maybe we want to tell the daemon to reconnect here. As a workaround untill DES-1567 is fixed

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321#-OEE7M6UCd9iRk4Pu3lq:-OEE7M6UCd9iRk4Pu3lr:bd8svbl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d82b56afced040788f26a8b7b1322e30d03123ff/desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx#L173)):*
> ```XML
>         case 'troubleshoot-dialog':
>           setTroubleshootInfo(action.troubleshoot);
>           setIsModalOpen(true);
> ```

Hmm. Since you've decoupled `ModalAlert.isOpen` from the contents of the `ModalMessage`, the type system won't guard against us trying to show an empty modal anymore. I personally prefer having stricted guarantees, that way there's less chance that we break something in the future

**Review by hulthe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321#-OEE7M6UCd9iRk4Pu3lq:-OEE8VUb1btfUDLUP-Af:b-2kqqtc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d82b56afced040788f26a8b7b1322e30d03123ff/desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx#L173)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Hmm. Since you've decoupled `ModalAlert.isOpen` from the contents of the `ModalMessage`, the type system won't guard against us trying to show an empty modal anymore. I personally prefer having stricted guarantees, that way there's less chance that we break something in the future
</blockquote></details>

Ah. Seems there's actually bug here. If you click "Send problem report", troubleshootInfo will become undefined and the Modal will glitch out.

**Review by olmoh — COMMENTED** [review]
Both of these issues should be solved in this PR. :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321#-:-OEEazExAsorzEOd_jm1:b-gpjqg5)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @hulthe)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321#-OEE7M6UCd9iRk4Pu3lq:-OEENGAMBcAHv6SLq16q:b-jpdwv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d82b56afced040788f26a8b7b1322e30d03123ff/desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx#L173)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Ah. Seems there's actually bug here. If you click "Send problem report", troubleshootInfo will become undefined and the Modal will glitch out.
</blockquote></details>

Nice catch, I will fix the bug. I also made some changes so that the function returns earlier if it is one of the notification variants without a modal.

If we want to make sure that we get an error if we don't pass any content to the modal I think it is a cleaner solution to solve that in the actual modal component, for by requiring the children prop. I have not looked into how much changes we would need since the component is used in a few places, should not be too many however but I don't think that is in scope for this PR.

**Review by hulthe — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321#-OEE7M6UCd9iRk4Pu3lq:-OEF0L1N5fYX2Yz0GcwO:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d82b56afced040788f26a8b7b1322e30d03123ff/desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx#L173)):*
<details><summary><i>Previously, olmoh (Oliver Mohlin) wrote…</i></summary><blockquote>

Nice catch, I will fix the bug. I also made some changes so that the function returns earlier if it is one of the notification variants without a modal.

If we want to make sure that we get an error if we don't pass any content to the modal I think it is a cleaner solution to solve that in the actual modal component, for by requiring the children prop. I have not looked into how much changes we would need since the component is used in a few places, should not be too many however but I don't think that is in scope for this PR.
</blockquote></details>

:+1:

**Review by hulthe — DISMISSED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
