### PR TITLE
Make SelectLocationPage use hooks

### PR DESCRIPTION
**Pull request by hankolsen**
This PR makes SelectLocationPage use hooks

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)* status: all files reviewed, 2 unresolved discussions (waiting on @hankolsen)

___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NEX8_q70Bff89RYx2cz:-NEX8_q70Bff89RYx2d-:b-1r4kch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/953c84a765ea5f99dde5781bcbb3ad2b7b2d3b0c/gui/src/renderer/containers/SelectLocationPage.tsx#L35)):*
> ```XML
>   const { relaySettings, bridgeSettings, bridgeState } = settings;
> 
>   const [multihopEnabled, setMultihopEnabled] = useState(false);
> ```

I don't think anything in this component needs a state. `multihopEnabled`, `selectedExitLocation`, `selectedEntryLocation` and `selectedBridgeLocation` should probably just be wrapped in `useMemo` along with the logic to figure them out.
___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NEXATECAbtukIaaorCO:-NEXATECAbtukIaaorCP:b-ne2wyu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/953c84a765ea5f99dde5781bcbb3ad2b7b2d3b0c/gui/src/renderer/containers/SelectLocationPage.tsx#L140)):*
> ```XML
>   }, [updateRelaySettings]);
> 
>   useEffect(() => {
> ```

Thise logic could be part of `useMemo` calls for the states mentioned above.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NEXATECAbtukIaaorCO:-NEZd6XoE1SLMBZ6HbnK:b-bjc3tn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/953c84a765ea5f99dde5781bcbb3ad2b7b2d3b0c/gui/src/renderer/containers/SelectLocationPage.tsx#L140)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Thise logic could be part of `useMemo` calls for the states mentioned above.
</blockquote></details>

Can this expression be simplified..?



_Code snippet:_
```XML
if (
      !(tunnelProtocol === 'openvpn' && 'normal' in bridgeSettings) &&
      'normal' in relaySettings
    ) 
```

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NEX8_q70Bff89RYx2cz:-NEZdqrbAY5NaMlV8TEB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/953c84a765ea5f99dde5781bcbb3ad2b7b2d3b0c/gui/src/renderer/containers/SelectLocationPage.tsx#L35)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't think anything in this component needs a state. `multihopEnabled`, `selectedExitLocation`, `selectedEntryLocation` and `selectedBridgeLocation` should probably just be wrapped in `useMemo` along with the logic to figure them out.
</blockquote></details>

Done.

**Review by raksooo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hankolsen)

___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NE_g3na8wrUu15IEbr4:-NE_g3nb8xv4SEW9_i_l:b-peak3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5c7091b65c92125a6d83b76ce49f39f9781bac/gui/src/renderer/containers/SelectLocationPage.tsx#L58)):*
> ```XML
>     if (
>       !(tunnelProtocol === 'openvpn' && 'normal' in bridgeSettings) &&
>       'normal' in relaySettings
> ```

Reviewable placed the other very weird for me so I'll respond in a new one. Yes it should be possible to simplify this! I beleive this would be correct:
```
return tunnelProtocol !== 'openvpn' && 'normal' in relaySettings && relaySettings.normal.wireguard.useMultihop;
```
We don't really care about the bridge settings, which are OpenVPN specific, when it's not set to OpenVPN.
___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NE_gmrw-t2VjJH9fUz9:-NE_gmrw-t2VjJH9fUzA:brr0rdp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5c7091b65c92125a6d83b76ce49f39f9781bac/gui/src/renderer/containers/SelectLocationPage.tsx#L65)):*
> ```XML
>   }, [tunnelProtocol, relaySettings]);
> 
>   const selectedEntryLocation = useMemo<RelayLocation | undefined>(() => {
> ```

The same goes for this one. And it could be made even simpler now that we have `multihopEnabled` set.
```
if (multihopEnabled && 'normal' in relaySettings) {
    const entryLocation = relaySettings.normal.wireguard.entryLocation;
    if (entryLocation !== 'any') {
      return entryLocation;
    }
}
return undefined;
```

I don't think TypeScript would be smart enough but it should be correct to skip the `'normal' in relaySettings` as well since that's already a condition for `useMultihop`.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NE_g3na8wrUu15IEbr4:-NE_n2NSAvJwDJfxMZHc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5c7091b65c92125a6d83b76ce49f39f9781bac/gui/src/renderer/containers/SelectLocationPage.tsx#L58)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Reviewable placed the other very weird for me so I'll respond in a new one. Yes it should be possible to simplify this! I beleive this would be correct:
```
return tunnelProtocol !== 'openvpn' && 'normal' in relaySettings && relaySettings.normal.wireguard.useMultihop;
```
We don't really care about the bridge settings, which are OpenVPN specific, when it's not set to OpenVPN.
</blockquote></details>

Done.
___
*[`gui/src/renderer/containers/SelectLocationPage.tsx` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-NE_gmrw-t2VjJH9fUz9:-NE_n1zS0S1EEKw0Ul0a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5c7091b65c92125a6d83b76ce49f39f9781bac/gui/src/renderer/containers/SelectLocationPage.tsx#L65)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The same goes for this one. And it could be made even simpler now that we have `multihopEnabled` set.
```
if (multihopEnabled && 'normal' in relaySettings) {
    const entryLocation = relaySettings.normal.wireguard.entryLocation;
    if (entryLocation !== 'any') {
      return entryLocation;
    }
}
return undefined;
```

I don't think TypeScript would be smart enough but it should be correct to skip the `'normal' in relaySettings` as well since that's already a condition for `useMultihop`.
</blockquote></details>

Done.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040#-:-NEeiFcB8E76DoR1nz0p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
