### PR TITLE
Improve-ephemeral-peer-error-logs

### PR DESCRIPTION
**Pull request by Serock3**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)

### CODE REVIEW

**Review by dlon — DISMISSED** [review]
:shipit: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-:-OEZk_eR7FPGZXktptXn:bizlbj6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 978 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZmzCpAO-DRwgw96l_:-OEZmzCpAO-DRwgw96la:b-t7gn1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-wireguard/src/lib.rs#L978)):*
> ```XML
> async fn log_tunnel_data_usage(config: &Config, tunnel: &Arc<AsyncMutex<Option<Box<dyn Tunnel>>>>) {
>     let tunnel = tunnel.lock().await;
>     let Ok(tunnel_stats) = tunnel.as_ref().unwrap().get_tunnel_stats() else {
> ```

nit: maybe prefer to just return if the tunnel is `None` instead of unwrapping, even if it currently will always be `Some`

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon and @Serock3)

___
*[`talpid-wireguard/src/lib.rs` line 978 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZmzCpAO-DRwgw96l_:-OEZnJS32qKS7n6wZt4W:bcjigsv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-wireguard/src/lib.rs#L978)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

nit: maybe prefer to just return if the tunnel is `None` instead of unwrapping, even if it currently will always be `Some`
</blockquote></details>

i.e.
```rust
    let Some(tunnel) = &*tunnel else { return }
```

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon and @Serock3)

___
*[`talpid-tunnel-config-client/src/lib.rs` line 361 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZo67Z6_PIycvt4MZr:-OEZo67Z6_PIycvt4MZs:b-sscb8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-tunnel-config-client/src/lib.rs#L361)):*
> ```XML
>     ) -> std::task::Poll<std::io::Result<()>> {
>         std::pin::Pin::new(&mut self.s).poll_shutdown(cx)
>     }
> ```

nit : There's a lot of fully qualified type paths here, a bit too much noise imo. Maybe consider removing some of them? Also, isn't `Unpin` in the prelude??

**Review by hulthe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dlon and @Serock3)

___
*[`talpid-tunnel-config-client/src/lib.rs` line 330 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZpN7cA3ImXduTVfjR:-OEZpN7cA3ImXduTVfjS:b-v98war) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-tunnel-config-client/src/lib.rs#L330)):*
> ```XML
>         let bytes = std::task::ready!(std::pin::Pin::new(&mut self.s).poll_read(cx, buf));
>         if bytes.is_ok() {
>             self.rx_bytes += buf.filled().len();
> ```

Nothing's stopping the caller from providing a partially filled ReadBuf here, in which case this addition would be wrong.

**Review by hulthe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @dlon and @Serock3)

___
*[`talpid-tunnel-config-client/src/lib.rs` line 344 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZpeIJ-n5Ey6fqBcOr:-OEZpeIJ-n5Ey6fqBcOs:b-i0zsg6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-tunnel-config-client/src/lib.rs#L344)):*
> ```XML
>         let bytes = std::task::ready!(std::pin::Pin::new(&mut self.s).poll_write(cx, buf));
>         if bytes.is_ok() {
>             self.tx_bytes += buf.len();
> ```

The inner writer is not guaranteed to write all of `buf`. You need to inspect `bytes` (which is a `Result<usize>`) to see how many bytes were written.

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon and @hulthe)

___
*[`talpid-tunnel-config-client/src/lib.rs` line 330 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZpN7cA3ImXduTVfjR:-OEZtRQ47q0Ss202bNPC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-tunnel-config-client/src/lib.rs#L330)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Nothing's stopping the caller from providing a partially filled ReadBuf here, in which case this addition would be wrong.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/lib.rs` line 344 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396#-OEZpeIJ-n5Ey6fqBcOr:-OEZtRcO9aQxBz3GSA9y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed10ac2b48314b663046c9e64c7406269c0b182d/talpid-tunnel-config-client/src/lib.rs#L344)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

The inner writer is not guaranteed to write all of `buf`. You need to inspect `bytes` (which is a `Result<usize>`) to see how many bytes were written.
</blockquote></details>

Done.

**Review by hulthe — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
