### PR TITLE
Refactor PacketTunnelActor State, decoupling state from ancilliary data

### PR DESCRIPTION
**Pull request by acb-mv**
This involves:
* defining a protocol, `StateAssociatedData`, which encompasses common fields of the connection data for connected states and blockage data for error states
* implementing a method, `mutateAssociatedData`, which applies a mutating function to the data, if present, and replacing a lot of case statements with this
* renaming `ConnectionState` and `BlockedState` to `State.ConnectionData` and `State.BlockingData`, for clarity and namespace hygiene
* making `State` `Èquatable` (within reason), and using equality testing in lieu of keeping track of whether a change was made

The result: a lot of business logic that acts on/modifies connection/blockage data is now considerably shorter, as it no longer needs to know about what the state is or which states may exist.

This was made in the course of the post-quantum functionality, and merged into that feature branch. This pull request is a backport of this to `main`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042)

### CODE REVIEW

**Review by rablador — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042#-NuUAXcC7ZgEWgLQvAAk:-NuUAXcC7ZgEWgLQvAAl:bdny5zh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/306880cc02ff53658211cddcebb5ba13f240382a/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BKeyPolicy.swift#L26)):*
> ```Swift
>      */
>     func cacheActiveKey(lastKeyRotation: Date?) {
>         // There should be a way to rationalise these two identical functions into one.
> ```

Is this comment still valid?

**Comment by acb-mv** [comment]
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042#-NuUAXcC7ZgEWgLQvAAk:-NuUBTB7EEXDloM3WVBf:b23tzlh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/306880cc02ff53658211cddcebb5ba13f240382a/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BKeyPolicy.swift#L26)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this comment still valid?
</blockquote></details>

Good catch. It's not.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6042#-:-NuZMqs19_-_GgAoPVcz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
