### PR TITLE
Fix android DAITA strings and translations

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to align and fix some of DAITA related strings and translations.

TODO:
- [x] Double check whether it should be `Go to %s settings` (like the desktop app) or `Open %s settings`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
I get a lot of `java.util.MissingFormatArgumentException: Format specifier '%s'` for several strings with arguments. I am not sure why.

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-:-ODrGWBd-UJfuOeE-2LN:b-30xqyj)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 378 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODrCBxo1aYqtGCwN-7q:-ODrCBxo1aYqtGCwN-7r:b-zfzlwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30be491aefad3aefb82bba041ddffc323d2a8432/android/lib/resource/src/main/res/values/strings.xml#L378)):*
> ```XML
>     <string name="feature_server_ip_override">Server IP override</string>
>     <string name="feature_custom_mtu">MTU</string>
>     <string name="feature_daita">DAITA</string>
> ```

This needs to be changed in `FeatureIndicatorsPanel`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt` line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODrGS915tx_vKtEsLGV:-ODrGS915tx_vKtEsLGW:b-6l9p5d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00f0593ac6f3a0067b1eccbb706c109ae88dfbde/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt#L217)):*
> ```Kotlin
>                 stringResource(
>                     R.string.daita_description_slide_1_third_paragraph,
>                     stringResource(id = R.string.daita),
> ```

This does not require argument

**Review by Rawa — COMMENTED** [review]
> Reviewed 21 of 25 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODugba41_g8exFCpw4V:-ODugba41_g8exFCpw4W:b-tmuyzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L112)):*
> ```Kotlin
>         Text(
>             text =
>                 stringResource(
> ```

:see_no_evil: 
___
*[`android/lib/resource/lint-baseline.xml` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODufSfn4QJeo2jSqcEy:-ODufSfn4QJeo2jSqcEz:b5w46v9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/lib/resource/lint-baseline.xml#L8)):*
> ```XML
>         message="Inconsistent number of arguments in formatting string `daita_description_slide_2_second_paragraph`; found both 1 here and 2 in values/strings.xml"
>         errorLine1="    &lt;string name=&quot;daita_description_slide_2_second_paragraph&quot;>Daher verwenden wir automatisch Multihop, um %1$s mit jedem Server zu aktivieren.&lt;/string>"
>         errorLine2="    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~">
> ```

Have we tried that this works fine? Some languages only using 2 arguments while others are using 1.

**Review by Pururun — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 5 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt` line 235 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODuiQ6K1esq9nMj29-M:-ODuiQ6L-VZWuTbPCDIw:b-y9a9my) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt#L235)):*
> ```Kotlin
>                     R.string.daita_description_slide_2_second_paragraph,
>                     stringResource(id = R.string.daita),
>                     stringResource(id = R.string.daita)
> ```

Probably nicer to have `%1$s` in the string, but maybe that won't work with the translation script?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: 21 of 30 files reviewed, 5 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt` line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODrGS915tx_vKtEsLGV:-ODv8prd3xwcgrPtJVzD:b-obpntn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00f0593ac6f3a0067b1eccbb706c109ae88dfbde/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt#L217)):*
You sure? :thinking: This is the string:

> If an observer monitors these data packets, %s makes it significantly harder for them to identify which websites you are visiting or with whom you are communicating.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt` line 235 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODuiQ6K1esq9nMj29-M:-ODv8eB3CQf8fBV3k7VI:b-1q0jgw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt#L235)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Probably nicer to have `%1$s` in the string, but maybe that won't work with the translation script?
</blockquote></details>

I can try that :thumbsup: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODugba41_g8exFCpw4V:-ODv8w1_4ME9bJgeIO1U:b4zv41w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L112)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

:see_no_evil:
</blockquote></details>

Indeed...
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 378 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODrCBxo1aYqtGCwN-7q:-ODv8RphDj_WOmzE2wbB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30be491aefad3aefb82bba041ddffc323d2a8432/android/lib/resource/src/main/res/values/strings.xml#L378)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This needs to be changed in `FeatureIndicatorsPanel`
</blockquote></details>

Done.
___
*[`android/lib/resource/lint-baseline.xml` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODufSfn4QJeo2jSqcEy:-ODv8zfdECUMwPFncbtr:b-w60ikb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/lib/resource/lint-baseline.xml#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Have we tried that this works fine? Some languages only using 2 arguments while others are using 1.
</blockquote></details>

The lint warning seemed to suggest that it's fine, but will double check by running the app

**Review by Pururun — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt` line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODrGS915tx_vKtEsLGV:-ODvA7PAECnfJiN4JtME:b-ndrhwy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00f0593ac6f3a0067b1eccbb706c109ae88dfbde/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt#L217)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

You sure? :thinking: This is the string:

> If an observer monitors these data packets, %s makes it significantly harder for them to identify which websites you are visiting or with whom you are communicating.
</blockquote></details>

Weird, it seems my comment got in the wrong place, it should referer to
``` 
stringResource(  
    R.string.daita\_description\_slide\_1\_second\_paragraph,  
    stringResource(id = R.string.daita),  
)
```

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/lib/resource/lint-baseline.xml` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODufSfn4QJeo2jSqcEy:-ODvB_hZ3cND7Zpz07ix:b3ogu9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/lib/resource/lint-baseline.xml#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The lint warning seemed to suggest that it's fine, but will double check by running the app
</blockquote></details>

:+1: @Pururun tested, and it didn't crash the app. But yeah we should address this in the near future.

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`.github/workflows/android-app.yml` line 243 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODvC6s629hgYmU3QCzY:-ODvC6s629hgYmU3QCzZ:b-t7pe19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad6a2365310c44af03a9b5a1916a5e9d02eeb26f/.github/workflows/android-app.yml#L243)):*
> ```YAML
>           - gradle-task: :test:arch:test --rerun-tasks
>           - gradle-task: detekt
>           - gradle-task: :app:lint
> ```

Should this change? or mistake?

**Review by Rawa — COMMENTED** [review]
> Reviewed 4 of 6 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

**Review by Pururun — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: 29 of 30 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/resource/lint-baseline.xml` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODufSfn4QJeo2jSqcEy:-ODvX02U-JgqS-x_oAEN:b-1iuskk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/lib/resource/lint-baseline.xml#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@Pururun did it look correct as well (apart from not crashing)?
</blockquote></details>

Yes looked fine, with quotation marks and everything.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: 28 of 30 files reviewed, 2 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt` line 235 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODuiQ6K1esq9nMj29-M:-ODvdMEDE1Z29wYmzebp:b3vdamb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DaitaScreen.kt#L235)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I can try that :thumbsup:
</blockquote></details>

Seems to work well, I've added indices to all related strings 
___
*[`android/lib/resource/lint-baseline.xml` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-ODufSfn4QJeo2jSqcEy:-ODvdGGu2ySfM0pV-yv6:b-w91i3e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a36dbc7e1016f87dced4a74fbe6ffe2108f1fd/android/lib/resource/lint-baseline.xml#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes looked fine, with quotation marks and everything.
</blockquote></details>

Perfect, thanks! :tada:

**Comment by albin-mullvad** [comment]
This PR has now been rebased on top of #7337 in order to clarify the single baseline addition that this PR itself introduces.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329#-:-ODwxNO3C7OVVVtOulf7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> Reviewed 8 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by Pururun — APPROVED** [review]
> Reviewed 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
