### PR TITLE
Add support for app languages

### PR DESCRIPTION
**Pull request by Rawa**
This PR adds the support for app languages. It uses the automatic way of adding languages:
https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig

If we want more finer control, we can add a custom list of languages but that would also require us to maintain that list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389#-:-NicwjwSBl_kAxUXNCTu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`CHANGELOG.md` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389#-NiiGDRk0Js5ZSPSkXfT:-NiiGDRk0Js5ZSPSkXfU:b-e9bsr8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ade7dfed6792be610fd8aeb7e197247c7fa5772e/CHANGELOG.md#L49)):*
> ```Markdown
> - Migrate voucher dialog to compose.
> - Add "New Device" in app notification & rework notification system
> - Add support for App Languages
> ```

Can this be clarified a bit? Perhaps something like:

```
 - Add support for setting per-app language in system settings.
```



_Code quote:_
```Markdown
 Add support for App Languages
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`CHANGELOG.md` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389#-NiiGDRk0Js5ZSPSkXfT:-NisIESY640MVxTDtKXe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ade7dfed6792be610fd8aeb7e197247c7fa5772e/CHANGELOG.md#L49)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be clarified a bit? Perhaps something like:

```
 - Add support for setting per-app language in system settings.
```
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389#-:-NislTMKCnRNfQqNEaED:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
