### PR TITLE
Add build container setup scripts and instructions

### PR DESCRIPTION
**Pull request by faern**
Adding a script and instructions for how to build, sign and publish the build containers we are going to use for Linux desktop and Android builds.

Actual sigstore content and published images will come in a separate PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)

### CODE REVIEW

**Comment by albin-mullvad** [comment]
I know this is a WIP/draft and you might already be aware of this, but I wanted to mention that I think something like the below way of scoping the sigstore/registry/policy config to `ghcr.io/mullvad` would be nice. Btw I'm not fully sure about the difference between `sigstore` and `lookaside` and haven't digged into it, but the structure of these files still applies.

`~/.config/containers/registries.d/mullvad.yaml`
```
docker:
    ghcr.io/mullvad:
        lookaside: file://${repo}/build-containers/sigstore
```
https://github.com/containers/image/blob/main/docs/containers-registries.d.5.md

`~/.config/containers/policy.json`
```
{
  "default": [{ "type": "insecureAcceptAnything" }],
  "transports": {
    "docker": {
      "ghcr.io/mullvad": [
        {
          "type": "signedBy",
          "keyType": "GPGKeys",
          "keyPath": "/${repo}/ci/keys/1.mullvad_signing.pub"
        }
      ]
    }
  }
}

```
(NOTE: Should there be an initial `/` in the `keyPath`?)
https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md

**Comment by albin-mullvad** [comment]
Regarding the `build/` directory, it's quite common to use it for build artifacts and therefore it's also common to put as a repository wide directory to ignore in the `.gitignore`. So I don't believe it's a good idea to use for checked in stuff, but I'm all for improving the structure for files and directories related to the build process etc.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Good job, looks really good! I have a few minor comments and will also try to verify all of this on my machine.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-:-NI6M_RXAjzXY1R-iufR:bchpqd4)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`build-containers/build-and-publish.sh` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6JOmP8Y3i0whZDQQk:-NI6JOmP8Y3i0whZDQQl:bko9ml0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/504b31520b8a7289fe99285cf20056cea6f682b9/build-containers/build-and-publish.sh#L19)):*
> ```Shell
>     desktop)
>         container_name="ghcr.io/mullvad/mullvadvpn-app-build:$tag"
>         containerfile_dir="."
> ```

`Context` is usually used to describe the directory of the Dockerfile, so I suggest something like `container_context_dir`.

`podman build`
```
Builds an image using instructions from one or more Containerfiles or Dockerfiles and a specified build context directory.
```

https://docs.podman.io/en/latest/markdown/podman-build.1.html
___
*[`build-containers/build-and-publish.sh` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6J7e_4Q_HdFCaNQIX:-NI6J7e_4Q_HdFCaNQIY:b-7kdd5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/504b31520b8a7289fe99285cf20056cea6f682b9/build-containers/build-and-publish.sh#L33)):*
> ```Shell
> 
> log_header "Building container $container_name"
> podman build "$containerfile_dir" -t "$container_name"
> ```

We might also want to tag as latest.



_Code quote:_
```Shell
-t "$container_name"
```
___
*[`build-containers/build-and-publish.sh` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6IpbK7vEDEw4X_P1K:-NI6IpbK7vEDEw4X_P1L:b-2kmqf6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/504b31520b8a7289fe99285cf20056cea6f682b9/build-containers/build-and-publish.sh#L36)):*
> ```Shell
> 
> log_header "Pushing container $container_name"
> podman push --sign-by 1E551687D67F5FD820BEF2C4D7C17F87A0D3D215 "$container_name"
> ```

I suggest defining a variable for this one.



_Code quote:_
```Shell
1E551687D67F5FD820BEF2C4D7C17F87A0D3D215
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`build-containers/build-and-publish.sh` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6JOmP8Y3i0whZDQQk:-NI6SjF49DdhMDF7rBBd:b-8ojuv3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/504b31520b8a7289fe99285cf20056cea6f682b9/build-containers/build-and-publish.sh#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

`Context` is usually used to describe the directory of the Dockerfile, so I suggest something like `container_context_dir`.

`podman build`
```
Builds an image using instructions from one or more Containerfiles or Dockerfiles and a specified build context directory.
```

https://docs.podman.io/en/latest/markdown/podman-build.1.html
</blockquote></details>

Good input! Done.
___
*[`build-containers/build-and-publish.sh` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6IpbK7vEDEw4X_P1K:-NI6TJ064rbpmN0QJcxA:b6f6naq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/504b31520b8a7289fe99285cf20056cea6f682b9/build-containers/build-and-publish.sh#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest defining a variable for this one.
</blockquote></details>

Yeah, that is a nice little improvement indeed. Done

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: 3 of 15 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`build-containers/build-and-publish.sh` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6J7e_4Q_HdFCaNQIX:-NI6qwz3EIrb1Bxb6hvs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/504b31520b8a7289fe99285cf20056cea6f682b9/build-containers/build-and-publish.sh#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We might also want to tag as latest.
</blockquote></details>

Done.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: 3 of 15 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`build-containers/build-and-publish.sh` line 79 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6o_mI2Ppf8yHG_3gG:-NI6o_mI2Ppf8yHG_3gH:b97glnx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/194ee64cf6aec9cd62e2bec8a63bc5d82b965ce6/build-containers/build-and-publish.sh#L79)):*
> ```Shell
> 
> log_info "Storing container tag to $container_image_tag_path"
> echo "$tag" > "$container_image_tag_path"
> ```

I'll just mention this even though it doesn't have to be considered for this PR specifically. Could there perhaps be a scenario where we want to build a new image but not use it immediately? We might for example want to evaluate it for some time before before we consider it stable. The same comment might apply for the `latest` tag as well.



_Code quote:_
```Shell
echo "$tag" > "$container_image_tag_path"
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: 3 of 15 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`build-containers/build-and-publish.sh` line 79 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6o_mI2Ppf8yHG_3gG:-NI6sxItC3Es2-idejgn:bpgydn7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/194ee64cf6aec9cd62e2bec8a63bc5d82b965ce6/build-containers/build-and-publish.sh#L79)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'll just mention this even though it doesn't have to be considered for this PR specifically. Could there perhaps be a scenario where we want to build a new image but not use it immediately? We might for example want to evaluate it for some time before before we consider it stable. The same comment might apply for the `latest` tag as well.
</blockquote></details>

Yes. As discussed AFK: We want to do this at a later stage. Allowing the script to initially only:
* Build a new image, tagged with the git commit hash
* Push the new image with the git commit hash tag only (not latest)
* Commit the new image signature to the sigstore

This allows other developers to get the new image and test/use it. But the `latest` tag does not move, nor does the `dist-assets/*-image-tag.txt` files, so it does not impact anyone who is not ready to use the new image yet.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 7 files at r3, 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: all files reviewed, 1 unresolved discussion

**Review by faern — COMMENTED** [review]
Thank you! Remaining work once the script/readme and everything is approved is:

* Rebase and re-sign the commits with my developer key (rather than the build server key, like now)
* Delete all existing sigstore entries and start from scratch, build and publish a new image
* Update the Android docker file to point to the new desktop image and build a new Android image as well that we publish along with the sigstore entry for it.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-:-NI6u-b34U_8SGNl8baJ:bhfzrmg)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`build-containers/build-and-publish.sh` line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6uJ_d9qfCRh53MDcl:-NI6uJ_eEIwdRT2BcJhm:box6k6j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32cb87450095a9788cc15bcc2e4ae66c44c83609/build-containers/build-and-publish.sh#L50)):*
> ```Shell
> trap 'delete_tmp_signature_dir' EXIT
> 
> log_header "Pushing $container_name:latest'"
> ```

Is this a typo or should it be here?



_Code quote:_
```Shell
'
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`build-containers/build-and-publish.sh` line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-NI6uJ_d9qfCRh53MDcl:-NI6vXcx2buJilVa_-Ex:brxsfpf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32cb87450095a9788cc15bcc2e4ae66c44c83609/build-containers/build-and-publish.sh#L50)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this a typo or should it be here?
</blockquote></details>

Oops! Definitely typo! Good catch. Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

I'll try to build using the published image once it has been published. Would be nice to do it before merging just to double check.

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117#-:-NI6xGBhEyZBa7NxyEn1:bfwrbkx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r7, 3 of 4 files at r8, 8 of 9 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4117)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
