### PR TITLE
Extract actor functions to separate class

### PR DESCRIPTION
**Pull request by axti**
In this PR extract actor logic to separate abstract class to avoid code duplications.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)

### CODE REVIEW

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt, line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz2l_V-RRj9Rg0-Bsz:-MYz2l_V-RRj9Rg0-Bt-:b38fv0a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt#L141)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>                 if (Build.VERSION.SDK_INT >= 24) {
>                     service.stopForeground(Service.STOP_FOREGROUND_DETACH)
>                 } else {
>                     service.stopForeground(false)
>                 }
> ```
</details>

This is redundant since our minSDK is 24

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)* status: 1 of 16 files reviewed, 4 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5FOm3JNh6N2FqIsd:-MYz5FOn0eS7riLg2Eb2:bf0ti0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L108)):*
> ```Kotlin
> }
> 
> typealias RequestDispatcher = MessageDispatcher<Request>
> ```

I'd also move this change with the `requestDispatcher` property into a separate PR. They're not related to the actor refactor.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt, line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz2l_V-RRj9Rg0-Bsz:-MYz56jADb5cGMpV5OiU:b-w9jz8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt#L141)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>                 if (Build.VERSION.SDK_INT >= 24) {
>                     service.stopForeground(Service.STOP_FOREGROUND_DETACH)
>                 } else {
>                     service.stopForeground(false)
>                 }
> ```
This is redundant since our minSDK is 24
</blockquote></details>

But shouldn't this be in a separate PR?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5PkJB8Ignj1EnbYG:-MYz5PkJB8Ignj1EnbYH:bnyoich) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L11)):*
> ```Kotlin
> import kotlinx.coroutines.channels.sendBlocking
> 
> abstract class Actor<T : Any>(dispatcher: CoroutineDispatcher = Dispatchers.Default) {
> ```

Maybe it's a good idea to add `capacity: Int = Channel.UNLIMITED` parameter as well? That way the `LocationInfoCache` can also use this as a super class.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5pUD0idGLJBgd3m5:-MYz5pUD0idGLJBgd3m6:b-ufib3k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L18)):*
> ```Kotlin
>             }
>         } catch (exception: ClosedReceiveChannelException) {
>         }
> ```

I think it's a good idea to keep a comment inside the block to explain why it's empty.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz4a5R3NAsZyzK8eN4:-MYz4a5R3NAsZyzK8eN5:b-mov6aw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L23)):*
> ```Kotlin
>     protected fun sendBlocking(command: T) = commandChannel.sendBlocking(command)
>     protected suspend fun send(command: T) = commandChannel.send(command)
>     protected fun closeActor() = commandChannel.close()
> ```

Nit: Would it make sense to replace `closeActor()` with a `open fun onDestroy() = commandChannel.close()`?

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 6 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)* status: 7 of 16 files reviewed, 9 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHKVwDzBaWj5N-FLM:-MYzHKVwDzBaWj5N-FLN:bq85wkp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L50)):*
> ```Kotlin
>     val relayListListener = RelayListListener(this)
>     val splitTunneling = SplitTunneling(SplitTunnelingPersistence(context), this)
>     val voucherRedeemer = VoucherRedeemer(this)
> ```

Why is this being removed?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt, line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHcBR4bkjtN-gr68d:-MYzHcBR4bkjtN-gr68e:be8t8sh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L93)):*
> ```Kotlin
>             listeners.add(listener)
> 
>             sequenceOf(
> ```

I see no point in this change. It's harder to read.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHrrzEoZhoLtyY6ya:-MYzHrrzEoZhoLtyY6yb:b-janky6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L19)):*
> ```Kotlin
>     }
> 
>     private val intermittentDaemon = endpoint.intermittentDaemon
> ```

Why change the name?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzI3n770ZoQ2SmL4nS:-MYzI3n770ZoQ2SmL4nT:bgapkya) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L68)):*
> ```Kotlin
>     fun subscribe(id: Any, listener: (Settings) -> Unit) =
>         settingsNotifier.subscribe(id) { maybeSettings ->
>             maybeSettings?.run { listener(this) }
> ```

I'd rather this is either left as it was, or become simply `if (settings != null)`. Using `this` makes it harder to read.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzIJgg6BGWVJI-U9yE:-MYzIJgg6BGWVJI-U9yF:b9mgly3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L89)):*
> ```Kotlin
> 
>     private fun fetchInitialSettings(daemon: MullvadDaemon) {
>         synchronized(this) {
> ```

Why was the synchronized block removed?

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt, line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz2l_V-RRj9Rg0-Bsz:-MYzQmCB1KlLsRn_4qhY:b-a8k3rw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt#L141)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

But shouldn't this be in a separate PR?
</blockquote></details>

Next PR.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5PkJB8Ignj1EnbYG:-MYzQpHSDOlppDIjqjtF:bv60sfa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L11)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe it's a good idea to add `capacity: Int = Channel.UNLIMITED` parameter as well? That way the `LocationInfoCache` can also use this as a super class.
</blockquote></details>

I can't see the usage for now. Maybe we can improve it on next PR.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5pUD0idGLJBgd3m5:-MYzQv3N3xeFSTWop0uC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L18)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think it's a good idea to keep a comment inside the block to explain why it's empty.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz4a5R3NAsZyzK8eN4:-MYzQvudDxkvYg2PE6Ik:bfh6s7a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L23)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Would it make sense to replace `closeActor()` with a `open fun onDestroy() = commandChannel.close()`?
</blockquote></details>

Previously when I create like you said you ask me to change to separate functions instead of override and call super.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHKVwDzBaWj5N-FLM:-MYzREFi6ZI88hEqsV_3:bh1ztzl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L50)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Why is this being removed?
</blockquote></details>

Merge conflict happened. Thanks.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHrrzEoZhoLtyY6ya:-MYzRPPp0-KN4MA6Y6mC:b-9f8qst) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L19)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Why change the name?
</blockquote></details>

Because I think it is more related that just simple `daemon`. When I read some functions I was confused with name shadows .
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzI3n770ZoQ2SmL4nS:-MYzReEf3QxG5u_TY9Y3:bq8oc7p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L68)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'd rather this is either left as it was, or become simply `if (settings != null)`. Using `this` makes it harder to read.
</blockquote></details>

So if we want to simplify we should have dedicated callback and not to many lambdas.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzIJgg6BGWVJI-U9yE:-MYzRxB52Wb8po0Flrky:b9oo0sf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L89)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Why was the synchronized block removed?
</blockquote></details>

We already have `synchronised` block inside `handleNewSettings` looks like overhead to have it in this place.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt, line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHcBR4bkjtN-gr68d:-MYzSS5dDwF3D7junN3w:b-yts9dz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L93)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I see no point in this change. It's harder to read.
</blockquote></details>

Kotlin is designed to chain operation for sequence, which part is hard, can you point please?

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 2 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)* status: 3 of 16 files reviewed, 7 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, line 192 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MZ-G5-c8GoKuRdrZDOH:-MZ-G5-c8GoKuRdrZDOI:b-lah6hp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cad39f3eccb2247b94695a03fcbdd106db987e1/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L192)):*
> ```Kotlin
> 
>     private suspend fun doLogout() {
>         accountNumber?.run { daemon.await().setAccount(null) }
> ```

I think using `if (accountNumber != null)` is clearer.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz4a5R3NAsZyzK8eN4:-MZ-GHE1AiXX_WHU4DX_:b-9w1ipb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L23)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Previously when I create like you said you ask me to change to separate functions instead of override and call super.
</blockquote></details>

Yes, but that was a different situation. In that case, every sub-class would have to override the method and call the `super` class. In this case, sub-classes that only need to call `closeActor` wouldn't have to override the super class.

The common thing between both cases is that in both of them I'm trying to allow the sub-class to not have to write an extra method if it's not necessary. I.e., the idea is to remove:

```
override fun onDestroy() {
    super.onDestroy()
}
```

in the previous case and

```
fun onDestroy() {
    closeActor()
}
```

in this case.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt, line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHcBR4bkjtN-gr68d:-MZ-HW4hB2uwzIUOB4jQ:bgq46w2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L93)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Kotlin is designed to chain operation for sequence, which part is hard, can you point please? 
</blockquote></details>

The sequence part. It's a lot easier to read

1. Here is a list of initial events
2. If VPN permission is waiting for a response, add a VPN permission request to that list
3. Send each initial event to the listener

than

1. Given a sequence of events
2. Let a new sequence be either that plus another or just that one, depending on whether the VPN permission is waiting for a response
3. Send each event

Just because a language offers an extra tool, it doesn't mean we should try to use it everywhere we can. We should always think if there are any advantages in order to use those tools. This PR contains way too many "style" changes. That makes the review longer and harder, and I think not all of them are great. Like replacing `apply` with `run`, `if (x != null)` with `x?.let`, removing function body braces, etc. All of those changes seem subjective, are not part of the main scope of the PR (refactoring to use an `Actor` super class), and while in some cases they are great and make the code a lot better, in other cases not so much, and should probably be discussed individually.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzHrrzEoZhoLtyY6ya:-MZ-KkOv8tPYSo7ab5hA:bpw34e8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L19)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Because I think it is more related that just simple `daemon`. When I read some functions I was confused with name shadows .
</blockquote></details>

This could be a separate PR on its own. 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzI3n770ZoQ2SmL4nS:-MZ-L0WWBHpjwxaGPpHr:bxf0egx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L68)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

So if we want to simplify we should have dedicated callback and not to many lambdas.
</blockquote></details>

The number of lambas is the exact same, you just saved one line, by at the same time making it harder to read. This didn't have to change, but if you want to change it, IMO it should be something like:

```
settingsNotifier.subscribe(id) { settings ->
    if (settings != null) {
        listener(settings)
    }
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYzIJgg6BGWVJI-U9yE:-MZ-LR6J-D_RPib7QoIh:b-gvb89k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/112b98f92ceb4fb5c0bb6d1e2b88853c62f48d23/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L89)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

We already have `synchronised` block inside `handleNewSettings` looks like overhead to have it in this place.
</blockquote></details>

That's not the reason this one is here. The reason this one is here is because it must do the `daemon.getSettings()` and the `handleNewSettings` as one atomic operation.

**Review by jvff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)* status: 3 of 16 files reviewed, 7 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5PkJB8Ignj1EnbYG:-MZ-Lcdc5I8NMEprzfZr:b-x5woja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L11)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

I can't see the usage for now. Maybe we can improve it on next PR.
</blockquote></details>

There's a lot of things that I feel that shouldn't be in this PR. This is not one of them.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699)* status: 3 of 16 files reviewed, 6 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2699#-MYz5PkJB8Ignj1EnbYG:-MZ-VybW9N_qpvUixiZh:b-4tvbpw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ed234415a600060619582878096fcd3c1e8cd4c/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/Actor.kt#L11)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

There's a lot of things that I feel that shouldn't be in this PR. This is not one of them.
</blockquote></details>

I looked again at the code, and unfortunately the `LocationInfoCache` was already refactored to use `flow`, which makes it not fit the `Actor` class very well. You're right, this will take more work than expected, let's decide if it's worth it later :+1:

**Comment by axti** [comment]
Abandoned

**Pull request closed without merging**
