### PR TITLE
Add Playwright e2e testing

### PR DESCRIPTION
**Pull request by hankolsen**
- Add IntelliJ folder to .gitignore
- Make eslint ignore all javascript files, until we have it configured correctly
- Add missing typescript files to tsconfig.json
- Add Playwright
- Add two simple e2e tests
- Fix eslint error message for gui ts files
- Add an e2e flag to build.sh to keep the resulting .app file

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
Not very important but just a thought. What do you think about structuring the test directories like this?
```
gui/
  test/
    unit/
      account-data-cache.spec.ts
      auth-failure.spec.ts
      ...
    e2e/
      main.spec.ts
      settings.spec.ts
      ...
```

> Reviewed 4 of 11 files at r1, 2 of 5 files at r2, 5 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-:-NC-DHGC4kL8ghyLak6N:bashimr)* status: 11 of 35 files reviewed, 7 unresolved discussions (waiting on @hankolsen)

___
*[`.github/workflows/frontend.yml` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NBwUeA39LnRu_fapWU3:-NBwUeA39LnRu_fapWU4:b-px1c6q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/.github/workflows/frontend.yml#L56)):*
> ```YAML
>                   run: npm test
> 
>             - name: Run Playwright tests
> ```

I couldn't find this in the GitHub actions job when looking at it. What am I missing? :laughing: 
___
*[`gui/e2e/utils.ts` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-AAsd9WCSDv7whlxZ:-NC-AAsd9WCSDv7whlx_:blk4hy9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/e2e/utils.ts#L12)):*
> ```XML
> 
> const startApp = async (): Promise<StartAppResponse> => {
>   process.env.CI = 'e2e';
> ```

I've seen projects use `process.env.NODE_ENV = 'test'` a bunch of times. Are there any reasons to not use it here?
___
*[`gui/e2e/utils.ts` line 36 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-KEJ8-lWJa61nQEWR:-NC-KEJ8-lWJa61nQEWS:b2qv2gn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/e2e/utils.ts#L36)):*
> ```XML
> };
> 
> const mockIpcHandle = async <T>({ channel, response }: MockIpcHandleProps<T>) => {
> ```

This looks nice! :slightly_smiling_face: 
___
*[`gui/e2e/utils.ts` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-J69UC5s3b0LIRQ_Q:-NC-J69UC5s3b0LIRQ_R:bvblaqk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/e2e/utils.ts#L65)):*
> ```XML
> };
> 
> const _getStyleProperty = async (locator: Locator, property: string) => {
> ```

What does the `_` mean? Is it that it isn't exported? If that's the case, would it be a better idea to prefix all `const` declarations with `export`, instead of exporting them at the bottom, to communicate this?

We currently use the `_` prefix for variables which aren't used. https://github.com/mullvad/mullvadvpn-app/blob/master/gui/.eslintrc.js#L86
___
*[`gui/src/renderer/.eslintignore` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-9jMI4iVmQuTyCpPf:-NC-9jMI4iVmQuTyCpPg:b-v0rnrb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/.eslintignore#L1)):*
> ```ignore
> .eslintrc.js
> ```

Shouldn't it work to add `renderer/.eslintrc.js` to the other `.eslintignore`? Or does it require an ignore-file for each directory with an rc-file?
___
*[`gui/src/renderer/preload.ts` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BJk0EZk406EanzMG:-NC-BJk0EZk406EanzMH:bquqzl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/preload.ts#L8)):*
> ```XML
> 
> contextBridge.exposeInMainWorld('env', {
>   e2e: process.env.CI,
> ```

If we decide to go with `NODE_ENV='test'`, then I think we should use `test` for the key here as well to be consistent :slightly_smiling_face: 
___
*[`gui/src/renderer/components/NotificationBanner.tsx` line 105 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-EGBuBlXlr3NMAwZU:-NC-EGBuBlXlr3NMAwZV:b-swkkqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/components/NotificationBanner.tsx#L105)):*
> ```XML
> }
> 
> const TRANSITION_DURATION = window.env.e2e ? 1 : 350;
> ```

What do you say about doing something like this in `app.tsx`?
```
if (window.env.e2e) {
  createGlobalStyle({
    '*': {
      transitionDuration: '1ms !important',
    },
  });
}
```

This would be really nice since it would affect all transitions, map, notification banner, navigation, setttings toggles etc.
___
*[`gui/src/renderer/redux/store.ts` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BthT0ukc83a7u_bx:-NC-BthT0ukc83a7u_by:b-nhutdc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/redux/store.ts#L65)):*
> ```XML
>   return window.env.development
>     ? // eslint-disable-next-line @typescript-eslint/no-explicit-any
>       (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__?.({ actionCreators })() ?? compose()
> ```

I know I suggested this change but I think it would be possible to make it more readable. What do you think about something like this:
```
if (window.env.development) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const devtoolsCompose = (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__?.({ actionCreators });
  return devtoolsCompose ? devtoolsCompose() : compose();
} else {
  return compose();
}
```

Is it more readable? What do you think?

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 11 of 35 files reviewed, 7 unresolved discussions (waiting on @hankolsen and @raksooo)

___
*[`.github/workflows/frontend.yml` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NBwUeA39LnRu_fapWU3:-NC-LS9p7maWm3WS8R5B:b2kheo9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/.github/workflows/frontend.yml#L56)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I couldn't find this in the GitHub actions job when looking at it. What am I missing? :laughing: 
</blockquote></details>

It's there :) 
https://github.com/mullvad/mullvadvpn-app/actions/runs/3051531939/jobs/4919874837


___
*[`gui/e2e/utils.ts` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-AAsd9WCSDv7whlxZ:-NC-LdvBCaVyuRdfhK1Z:b127xfe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/e2e/utils.ts#L12)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I've seen projects use `process.env.NODE_ENV = 'test'` a bunch of times. Are there any reasons to not use it here?
</blockquote></details>

This was a copy/paste from the example repo for [electron-playwright-helpers](https://github.com/spaceagetv/electron-playwright-helpers) package

https://github.com/spaceagetv/electron-playwright-example/blob/master/e2e-tests/main.spec.ts
___
*[`gui/e2e/utils.ts` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-J69UC5s3b0LIRQ_Q:-NC-MVNCBrbZCaOKG46G:b3zxlvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/e2e/utils.ts#L65)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

What does the `_` mean? Is it that it isn't exported? If that's the case, would it be a better idea to prefix all `const` declarations with `export`, instead of exporting them at the bottom, to communicate this?

We currently use the `_` prefix for variables which aren't used. https://github.com/mullvad/mullvadvpn-app/blob/master/gui/.eslintrc.js#L86
</blockquote></details>

An old habit of prefixing "private" stuff with _. 
But I guess it is enough that it is not exported.
___
*[`gui/src/renderer/.eslintignore` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-9jMI4iVmQuTyCpPf:-NC-NZ_u9x2espyjVBAK:ba6ra2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/.eslintignore#L1)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Shouldn't it work to add `renderer/.eslintrc.js` to the other `.eslintignore`? Or does it require an ignore-file for each directory with an rc-file?
</blockquote></details>

Unfortunately not, I found out the hard way.
___
*[`gui/src/renderer/preload.ts` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BJk0EZk406EanzMG:-NC-Ngv87y1ntWXuJ_Pj:b-8ayu6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/preload.ts#L8)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

If we decide to go with `NODE_ENV='test'`, then I think we should use `test` for the key here as well to be consistent :slightly_smiling_face: 
</blockquote></details>

Agree
___
*[`gui/src/renderer/redux/store.ts` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BthT0ukc83a7u_bx:-NC-Or3k3PAfo6_6mb_T:bvl18lg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/redux/store.ts#L65)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I know I suggested this change but I think it would be possible to make it more readable. What do you think about something like this:
```
if (window.env.development) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const devtoolsCompose = (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__?.({ actionCreators });
  return devtoolsCompose ? devtoolsCompose() : compose();
} else {
  return compose();
}
```

Is it more readable? What do you think?
</blockquote></details>

Looks good, however I get a typescript error when trying to implement it:

TS2322: Type ' (a: R) => R' is not assignable to type '{ ():  (a: R) => R;  (f: F): F; (f1: (b: A) => R, f2: Func0): Func0 ; (f1: (b: A) => R, f2: Func1 ): Func1...>; (f1: (b: A) => R, f2: Func2...>): Func2...>; (f1: (b: A) => R, f2: Func3...>): Func3...>; (f1: (b: B) => R, f2:...'.



_Code snippet:_
```XML
if (window.env.development) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const devtoolsCompose = (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__?.({
      actionCreators,
    });
    return devtoolsCompose ? devtoolsCompose() : compose();
  }

  return compose();
```

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 11 of 36 files reviewed, 7 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/components/NotificationBanner.tsx` line 105 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-EGBuBlXlr3NMAwZU:-NC-UqDGC7gJW9PwPRcv:b-8b11j9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/components/NotificationBanner.tsx#L105)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

What do you say about doing something like this in `app.tsx`?
```
if (window.env.e2e) {
  createGlobalStyle({
    '*': {
      transitionDuration: '1ms !important',
    },
  });
}
```

This would be really nice since it would affect all transitions, map, notification banner, navigation, setttings toggles etc.
</blockquote></details>

Added

**Review by hankolsen — COMMENTED** [review]
Fixed

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-:-NC-a7GX614HQ63RC51d:b-886gsx)* status: 4 of 48 files reviewed, 7 unresolved discussions (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 3 of 3 files at r5, 1 of 36 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 9 of 48 files reviewed, 1 unresolved discussion (waiting on @hankolsen and @raksooo)

___
*[`.github/workflows/frontend.yml` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NBwUeA39LnRu_fapWU3:-NC-XzC7Agc1_gE-gSvf:bgibzcg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/.github/workflows/frontend.yml#L56)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

It's there :) 
https://github.com/mullvad/mullvadvpn-app/actions/runs/3051531939/jobs/4919874837



</blockquote></details>

That's strange! That's exactly where I looked for it but it wasn't there :laughing: Maybe I had to reload the page and checked the GitHub action jobs from before you added it or something. I can see it now :+1:
___
*[`gui/src/renderer/.eslintignore` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-9jMI4iVmQuTyCpPf:-NC-XfFp4MWYMchELxPF:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/.eslintignore#L1)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Unfortunately not, I found out the hard way.
</blockquote></details>

Okay :+1:
___
*[`gui/src/renderer/preload.ts` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BJk0EZk406EanzMG:-NC-aXU3E33dX2SmOKHQ:b-74rdlh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/preload.ts#L8)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Agree
</blockquote></details>

As mentioned above, let's keep it like this.
___
*[`gui/src/renderer/redux/store.ts` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BthT0ukc83a7u_bx:-NC-YjTD7jq6sGe3b5xf:b-44yh1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/redux/store.ts#L65)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Looks good, however I get a typescript error when trying to implement it:

TS2322: Type ' (a: R) => R' is not assignable to type '{ ():  (a: R) => R;  (f: F): F; (f1: (b: A) => R, f2: Func0): Func0 ; (f1: (b: A) => R, f2: Func1 ): Func1...>; (f1: (b: A) => R, f2: Func2...>): Func2...>; (f1: (b: A) => R, f2: Func3...>): Func3...>; (f1: (b: B) => R, f2:...'.
</blockquote></details>

Sorry for not trying it out before suggesting. I think the reason it works currently is since the returned value probably has the type `any` due to the devtools stuff.

After looking into it a bit it looks like the return type of `composeEnhancers()` should be `StoreEnhancer` which can be imported from `'redux'`. It's always nice to catch such errors when doing something completely unrelated :smile:
___
*[`gui/e2e/utils.ts` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-AAsd9WCSDv7whlxZ:-NC-a9ROBE0JonTbqHDA:big1i0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/e2e/utils.ts#L12)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

This was a copy/paste from the example repo for [electron-playwright-helpers](https://github.com/spaceagetv/electron-playwright-helpers) package

https://github.com/spaceagetv/electron-playwright-example/blob/master/e2e-tests/main.spec.ts
</blockquote></details>

I had a look at playwrights documentation and in a few places the use `process.env.CI` as well so this is probably the convention. Let's keep it like this then :+1:

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 9 of 48 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/redux/store.ts` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC-BthT0ukc83a7u_bx:-NC-c1miCo4F4pSrbqUP:b-kl9v05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95ee189e59f336cc9cb4e30b9d3c5c7e954a6b25/gui/src/renderer/redux/store.ts#L65)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Sorry for not trying it out before suggesting. I think the reason it works currently is since the returned value probably has the type `any` due to the devtools stuff.

After looking into it a bit it looks like the return type of `composeEnhancers()` should be `StoreEnhancer` which can be imported from `'redux'`. It's always nice to catch such errors when doing something completely unrelated :smile:
</blockquote></details>

Nice!
I've update the code

**Review by raksooo — CHANGES_REQUESTED** [review]
Great! I'm still not sure about whether or not it's best to store the screenshots in the repo. I'll do some reading! :)

> Reviewed 3 of 27 files at r3, 19 of 36 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-:-NC0g2XG7_6wkF5Aaqe9:b-dnijq)* status: 32 of 48 files reviewed, 2 unresolved discussions (waiting on @hankolsen and @raksooo)

___
*[`.github/workflows/frontend.yml` line 61 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC05TP448WpbF12RwpC:-NC05TP448WpbF12RwpD:b-vu0wy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/.github/workflows/frontend.yml#L61)):*
> ```YAML
> 
>             - name: Upload failed screenshots
>               uses: actions/upload-artifact@v3
> ```

How does this work? Where is it uploaded to?
___
*[`gui/package.json` line 69 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC06eYH7CcCdW06CzK7:-NC06eYH7CcCdW06CzK8:b-7fu98y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/gui/package.json#L69)):*
> ```JSON
>     "electron-mocha": "^11.0.2",
>     "electron-notarize": "^0.1.1",
>     "electron-playwright-helpers": "^1.2.0",
> ```

I can't find any imports of this. Is it used somewhere or can it be removed?

**Review by raksooo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 32 of 48 files reviewed, 3 unresolved discussions (waiting on @hankolsen and @raksooo)

___
*[`gui/package.json` line 81 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC4Hupw5b3KxnzxYkLv:-NC4Hupw5b3KxnzxYkLw:bk8t451) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/gui/package.json#L81)):*
> ```JSON
>     "gulp-typescript": "^5.0.1",
>     "playwright": "^1.25.1",
>     "playwright-core": "^1.25.1",
> ```

I don't think we need to import `playwright-core` ourselves. `playwright` depends on `playwright-core` and re-exports it.
https://github.com/microsoft/playwright/blob/main/packages/playwright/package.json
https://github.com/microsoft/playwright/blob/main/packages/playwright/index.d.ts

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 32 of 48 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`.github/workflows/frontend.yml` line 61 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC05TP448WpbF12RwpC:-NC4ORw2CdhX9g-sPtBF:b8hsqyf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/.github/workflows/frontend.yml#L61)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

How does this work? Where is it uploaded to?
</blockquote></details>

It ends up under the "Artifacts" section here: https://github.com/mullvad/mullvadvpn-app/actions/runs/3060908066

However, it seems that [Playwright lacks support for Electron](https://github.com/microsoft/playwright/issues/8208) at the moment, so the best we can do at the moment is to upload a html page with the test report. So I'm not sure that this is of an help.
___
*[`gui/package.json` line 69 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC06eYH7CcCdW06CzK7:-NC4PAW88jgBKOcJe_Gt:b-obkwos) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/gui/package.json#L69)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I can't find any imports of this. Is it used somewhere or can it be removed?
</blockquote></details>

Hmm, I started out using it, but after some refactoring back and forth it seems it was no longer needed. I'll remove it.
___
*[`gui/package.json` line 81 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC4Hupw5b3KxnzxYkLv:-NC4PiTz0IgPH9zmvWx_:b-mdty1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/gui/package.json#L81)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't think we need to import `playwright-core` ourselves. `playwright` depends on `playwright-core` and re-exports it.
https://github.com/microsoft/playwright/blob/main/packages/playwright/package.json
https://github.com/microsoft/playwright/blob/main/packages/playwright/index.d.ts
</blockquote></details>

Probably due to a copy/paste from an too old tutorial... I'll remove it.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 33 of 48 files reviewed, 1 unresolved discussion (waiting on @hankolsen and @raksooo)

___
*[`-- commits` line 66 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NCL8tAG4BAyCHQ5emnE):*
Very minor: This commit message should start with a capital letter.
___
*[`gui/package.json` line 69 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC06eYH7CcCdW06CzK7:-NCKvUtoBsrCKUbiuKPe:bccpe83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/gui/package.json#L69)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Hmm, I started out using it, but after some refactoring back and forth it seems it was no longer needed. I'll remove it.
</blockquote></details>

Awesome!
___
*[`gui/package.json` line 81 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NC4Hupw5b3KxnzxYkLv:-NCKvY100AZd9sd-mIqm:bhzvliq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d62403bd237aa115e4a6b53c68b4ea361b2229fe/gui/package.json#L81)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Probably due to a copy/paste from an too old tutorial... I'll remove it.
</blockquote></details>

Great :+1:

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 31 of 48 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`-- commits` line 66 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NCL8tAG4BAyCHQ5emnE):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Very minor: This commit message should start with a capital letter.
</blockquote></details>

Fixed

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 45 files at r14, 1 of 5 files at r15, 44 of 62 files at r16, 16 of 16 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867)* status: 65 of 66 files reviewed, 1 unresolved discussion (waiting on @hankolsen and @raksooo)

___
*[`gui/tasks/distribution.js` line 53 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-NCOuVG2EnKtx5_pmqKN:-NCOuVG2EnKtx5_pmqKO:bz0oodo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a591ef0afe213c869f58dc9a6f3df6b4a62b8f6a/gui/tasks/distribution.js#L53)):*
> ```JavaScript
>     'build/src/renderer/preloadBundle.js',
>     '!**/*.tsbuildinfo',
>     '!test/e2e/',
> ```

This one should probably include all tests :)

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 62 files at r16, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3867#-:-NCOwcxCApL_8J3gFJqt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
