### PR TITLE
Add SSL pinning

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR mainly adds SSL pinning to Mullvad RPC using Security framework by Apple to verify the server trust.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746)

### CODE REVIEW

**Review by jvff — COMMENTED** [review]
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746)* status: 6 of 8 files reviewed, all discussions resolved

___
*[ios/BuildInstructions.md, line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_uw7ay0yEtcrvgFGew:-M_uw7ay0yEtcrvgFGex:b-v431m8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/BuildInstructions.md#L184)):*
> ```Markdown
> openssl x509 -in ../mullvad-rpc/new_le_root_cert.pem -outform der -out Assets/new_le_root_cert.cer
> openssl x509 -in ../mullvad-rpc/old_le_root_cert.pem -outform der -out Assets/old_le_root_cert.cer
> ```
> ```

FYI: I think the end of file newline was removed here.
___
*[ios/update-relays.sh, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_uwIOo-RfufKZSukOs:-M_uwIOo-RfufKZSukOt:b-2y14yk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/update-relays.sh#L15)):*
> ```Shell
>     rm "$RELAYS_FILE"
>   else
>   	echo "Relays file does not exist"
> ```

FYI: tab here instead of spaces.

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/SSLPinningURLSessionDelegate.swift, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_vMQ-L079EeqYEvQcw:-M_vMQ-M1Q60WfxeDjpO:bqx939p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/MullvadVPN/SSLPinningURLSessionDelegate.swift#L33)):*
> ```Swift
>             }
>         } else {
>             evaluation = (.performDefaultHandling, nil)
> ```

I'm not sure I understand everything, but is this `else` clause evaluated when the connection doesn't use authentication? Should it then reject the connection?
___
*[ios/MullvadVPN/SSLPinningURLSessionDelegate.swift, line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_vMuTSBqh8kw80BIxG:-M_vMuTSBqh8kw80BIxH:b-7eljub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/MullvadVPN/SSLPinningURLSessionDelegate.swift#L44)):*
> ```Swift
>     private func verifyServerTrust(_ serverTrust: SecTrust) -> Bool {
>         // Set trusted root certificates
>         var secResult = SecTrustSetAnchorCertificates(serverTrust, trustedRootCertificates as CFArray)
> ```

Just to be sure, this sets `trustedRootCertificates` as the only root certificates, right? I.e., it clears any previous certificates?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/BuildInstructions.md, line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_uw7ay0yEtcrvgFGew:-M_yaLuRDyiX1e7MxiNC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/BuildInstructions.md#L184)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

FYI: I think the end of file newline was removed here.
</blockquote></details>

Done.
___
*[ios/update-relays.sh, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_uwIOo-RfufKZSukOs:-M_yaKqj-KNkTaFWsG_t:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/update-relays.sh#L15)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

FYI: tab here instead of spaces.
</blockquote></details>

Done.
___
*[ios/MullvadVPN/SSLPinningURLSessionDelegate.swift, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_vMQ-L079EeqYEvQcw:-M_yVrYQBV5iJqsknCU1:b-5stibb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/MullvadVPN/SSLPinningURLSessionDelegate.swift#L33)):*
During testing I found that this `URLSession` delegate method is called with different authentication methods, one is server trust which we use to validate SSL/TLS chain and the other is client certificate which we don't support, so I tell the system to do whatever it does by default with it. 

However you raise a good point and we should probably return `.rejectProtectionSpace` in that case to tell the system that we don't care for other authentication methods except server trust. Although documentation states that most apps should delegate authentication that they can't handle back to the system to perform the default action, I suppose that since we fully control the interaction with the API, we should then reject authentication challenge and move on with the next one in queue.

Quote:

> The URLSession.AuthChallengeDisposition.rejectProtectionSpace disposition is only appropriate in fairly unusual situations. 
>
> For example, a Windows server might use both NSURLAuthenticationMethodNegotiate and NSURLAuthenticationMethodNTLM. If your app can only handle NTLM, you would want to reject the Negotiate challenge, in order to then receive the queued NTLM challenge.
>
>However, most apps won't face this scenario, and if you cannot provide a credential for a certain authentication method, you should usually fall back to the URLSession.AuthChallengeDisposition.performDefaultHandling disposition instead.

Reference:
https://developer.apple.com/documentation/foundation/urlsession/authchallengedisposition/rejectprotectionspace
___
*[ios/MullvadVPN/SSLPinningURLSessionDelegate.swift, line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_vMuTSBqh8kw80BIxG:-M_yZukt0qw6hKegWJpi:b5eivgd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/MullvadVPN/SSLPinningURLSessionDelegate.swift#L44)):*
Yes and the call below `SecTrustSetAnchorCertificatesOnly` ensures that. https://developer.apple.com/documentation/security/1399071-sectrustsetanchorcertificatesonl


```
SecTrustSetAnchorCertificatesOnly(serverTrust, true)
```

The documentation for the boolean flag (second argument):

> anchorCertificatesOnly
>
>If true, disables trusting any anchors other than the ones passed in with the SecTrustSetAnchorCertificates(_:_:) function.  If false, the built-in anchor certificates are also trusted. If SecTrustSetAnchorCertificates(_:_:) is called and SecTrustSetAnchorCertificatesOnly(_:_:) is not called, only the anchors explicitly passed in are trusted.

I have tried changing the API address to `https://google.com/` and got the following error:
> SecTrustEvaluateWithError failure: “GlobalSign” certificate is not trusted

Which makes me think that this works as expected.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/SSLPinningURLSessionDelegate.swift, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-M_vMQ-L079EeqYEvQcw:-M_ycc4S3lB9oZOFFQcV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dacdabdb83a318a316d25159df395d90b245e84/ios/MullvadVPN/SSLPinningURLSessionDelegate.swift#L33)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

During testing I found that this `URLSession` delegate method is called with different authentication methods, one is server trust which we use to validate SSL/TLS chain and the other is client certificate which we don't support, so I tell the system to do whatever it does by default with it. 

However you raise a good point and we should probably return `.rejectProtectionSpace` in that case to tell the system that we don't care for other authentication methods except server trust. Although documentation states that most apps should delegate authentication that they can't handle back to the system to perform the default action, I suppose that since we fully control the interaction with the API, we should then reject authentication challenge and move on with the next one in queue.

Quote:

> The URLSession.AuthChallengeDisposition.rejectProtectionSpace disposition is only appropriate in fairly unusual situations. 
>
> For example, a Windows server might use both NSURLAuthenticationMethodNegotiate and NSURLAuthenticationMethodNTLM. If your app can only handle NTLM, you would want to reject the Negotiate challenge, in order to then receive the queued NTLM challenge.
>
>However, most apps won't face this scenario, and if you cannot provide a credential for a certain authentication method, you should usually fall back to the URLSession.AuthChallengeDisposition.performDefaultHandling disposition instead.

Reference:
https://developer.apple.com/documentation/foundation/urlsession/authchallengedisposition/rejectprotectionspace
</blockquote></details>

Done.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-:-M_yrgzJ2nXfaQt8xCj7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2746#-:-M_zOhNaADYDeq0lZzrg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
