### PR TITLE
Filter invalid relay endpoints

### PR DESCRIPTION
**Pull request by pinkisemils**
Currently, the relay selector may operate on relays containing nonsensical endpoint data - data containing no port ranges or other such invalid values.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3djFK2Gssoi_An3bJ:-Mv3djFK2Gssoi_An3bK:bj1bm2a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L113)):*
> ```XML
>                     let openvpn_endpoints = &mut relay_with_location.tunnels.openvpn;
> 
>                     openvpn_endpoints.retain(|data| data.port != 0);
> ```

We are very good at having long functions doing more than one thing. Without documentation/comments. Can we please extract `filter_invalid_endpoints` to a separate function? It's very hard to know what this blob of code is doing and why it's part of `from_relay_list`.
___
*[mullvad-daemon/src/relays/mod.rs, line 115 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3e9zG6gkERfLnngEx:-Mv3e9zG6gkERfLnngEy:b-xo4wo5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L115)):*
> ```XML
>                     openvpn_endpoints.retain(|data| data.port != 0);
>                     filtered_openvpn_endpoints +=
>                         relay.tunnels.openvpn.len() - openvpn_endpoints.len();
> ```

Instead of just counting them and printing the count. If you extract the code that finds and removes invalid endpoints it can instead log more accurately. Instead of one global "X endpoints are invalid" it can log "relay Y have X invalid endpoints" which would be great in debugging the issue.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3eQDI-OSYhzJpXdhg:-Mv3eQDI-OSYhzJpXdhh:b-7pl9qs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L118)):*
> ```XML
> 
>                     wireguard_endpoints.retain(|data| {
>                         !data.port_ranges.is_empty()
> ```

Could this be done in `filter_matching_endpoints`? Or is it done here because this is considered invalid input?
___
*[mullvad-daemon/src/relays/mod.rs, line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3f5p64gaf5I90sU5y:-Mv3f5p64gaf5I90sU5z:b-i5zyyw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L124)):*
> ```XML
>                         relay.tunnels.wireguard.len() - wireguard_endpoints.len();
> 
>                     *wireguard_endpoints = wireguard_endpoints
> ```

I realize this isn't new, but we might want to comment this hack that adds TCP endpoints or extract it to its own function as well.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3f5p64gaf5I90sU5y:-Mv3wZpz5YYYxRRcmqzS:b-4bt500) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L124)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I realize this isn't new, but we might want to comment this hack that adds TCP endpoints or extract it to its own function as well.
</blockquote></details>

More functions: :all-the-functions: :tada:

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-daemon/src/relays/mod.rs, line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3djFK2Gssoi_An3bJ:-Mv4A2W14HjP8MwKR2bQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L113)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We are very good at having long functions doing more than one thing. Without documentation/comments. Can we please extract `filter_invalid_endpoints` to a separate function? It's very hard to know what this blob of code is doing and why it's part of `from_relay_list`.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays/mod.rs, line 115 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3e9zG6gkERfLnngEx:-Mv49zhP-tQvaXDVlBuz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L115)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Instead of just counting them and printing the count. If you extract the code that finds and removes invalid endpoints it can instead log more accurately. Instead of one global "X endpoints are invalid" it can log "relay Y have X invalid endpoints" which would be great in debugging the issue.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays/mod.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3eQDI-OSYhzJpXdhg:-Mv49cCD6zx34n86QYfT:b1v9b6j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L118)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could this be done in `filter_matching_endpoints`? Or is it done here because this is considered invalid input?
</blockquote></details>

I prefer to do data validation once when the invalid data is ingested. This allows the daemon to log about the bad data once rather than twice every time a relay is selected.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[mullvad-daemon/src/relays/mod.rs, line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3djFK2Gssoi_An3bJ:-Mv4LpjL-O9YIeQ32XFQ:b-tm9zlh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L113)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not a blocker, obviously, but this would be marginally cleaner IMO:
```
let (valid_openvpn_endpoints, invalid_openvpn_endpoints): (Vec<_>, Vec<_>) = openvpn_endpoints
    .iter()
    .cloned()
    .partition(|data| data.port != 0);
if !invalid_openvpn_endpoints.is_empty() {
    // ...
}
```
___
*[mullvad-daemon/src/relays/mod.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3eQDI-OSYhzJpXdhg:-Mv4KTuGDQ3axPSxLqmA:bxxx4gf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L118)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I prefer to do data validation once when the invalid data is ingested. This allows the daemon to log about the bad data once rather than twice every time a relay is selected.
</blockquote></details>

That makes sense.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3djFK2Gssoi_An3bJ:-Mv4N5KjCempeiFTotIL:b-3wt9l8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L113)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not a blocker, obviously, but this would be marginally cleaner IMO:
```
let (valid_openvpn_endpoints, invalid_openvpn_endpoints): (Vec<_>, Vec<_>) = openvpn_endpoints
    .iter()
    .cloned()
    .partition(|data| data.port != 0);
if !invalid_openvpn_endpoints.is_empty() {
    // ...
}
```
</blockquote></details>

We don't need the invalid endpoints for anything. So a partition feels overkill/unjustified IMO.

Do we really need to iter->clone->filter->collect. Why not just `Vec::retain`? If we really want to have logging we can store the length of the vector to a local integer before the `retain` and then get a number to compare with in that way.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 167 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv4Qk7B-WO_JiHum1jv:-Mv4Qk7B-WO_JiHum1jw:b-xz4jg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0f745fd7ff2af31b89c93b804c4031fd63fd0b5/mullvad-daemon/src/relays/mod.rs#L167)):*
> ```XML
>             .iter()
>             .cloned()
>             .map(|udp_endpoint| {
> ```

The fact that `endpoints` is a vector is very strange. Each relay will by definition (the API format) only have one of these endpoints. So here we iterate over the definitely-just-one-endpointdata and make it into two endpoint datas. I hope we can simplify the modeling of this once we rip TCP out. This is collecting technical debt and is hard to understand IMO.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[mullvad-daemon/src/relays/mod.rs, line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv3djFK2Gssoi_An3bJ:-Mv4Ty0pEuLNdLvFFUrQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/977aa3c73ad205d02eb9b8ff6bdd7bc9ca9d6ef2/mullvad-daemon/src/relays/mod.rs#L113)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We don't need the invalid endpoints for anything. So a partition feels overkill/unjustified IMO.

Do we really need to iter->clone->filter->collect. Why not just `Vec::retain`? If we really want to have logging we can store the length of the vector to a local integer before the `retain` and then get a number to compare with in that way.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays/mod.rs, line 167 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-Mv4Qk7B-WO_JiHum1jv:-Mv4SHkG2XwOE3bu5ES1:b-fa9097) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0f745fd7ff2af31b89c93b804c4031fd63fd0b5/mullvad-daemon/src/relays/mod.rs#L167)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The fact that `endpoints` is a vector is very strange. Each relay will by definition (the API format) only have one of these endpoints. So here we iterate over the definitely-just-one-endpointdata and make it into two endpoint datas. I hope we can simplify the modeling of this once we rip TCP out. This is collecting technical debt and is hard to understand IMO.
</blockquote></details>

It's the similarity with OpenVPN endpoint data that makes this so.  I agree, it's not pretty, and once we get rid of TCP WireGuard relays, this will no longer be an issue - a relay will be able to have a single WireGuard endpointassociated with it. But that will also necessitate a change in the API schema.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 125 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-MvOFb71AuPFTNuVkOAs:-MvOFb727v5K_50RijOG:b26nz4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/222c4b6a51b69ab0ed6bbeacd96b04e050bdc50e/mullvad-daemon/src/relays/mod.rs#L125)):*
> ```XML
>     fn filter_invalid_relays(relay: &mut Relay) {
>         let total_openvpn_endpoints = relay.tunnels.openvpn.len();
>         let filtered_openvpn_endpoints = &mut relay.tunnels.openvpn;
> ```

`filtered_openvpn_endpoints` and `&mut relay.tunnels.openvpn` have the exact same number of characters. I'm not sure why you go through assigning it to a variable here. Not that the number of characters is a very good metric, but I also don't see much added code clarity. It's instead rather tricky since `filtered_openvpn_endpoints` is not a different set, it's just a reference. So in practice `relay.tunnels.openvpn` is also the filtered set after the retain operation. So this kind of gives a false sense of there being a separate filtered set available.

```rust
relay.tunnels.openvpn.retain(|data| data.port != 0);
if relay.tunnels.openvpn.len() < total_openvpn_endpoints {...}
```

Seems not worse, but simpler to me. Same goes for WireGuard below.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319#-:-MvOKPC_EiujQLP4GhMG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
