### PR TITLE
Add --json flag to `mullvad status`

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569)

### CODE REVIEW

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[`mullvad-cli/src/cmds/status.rs` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569#-O3YGWDB44knitZ8voYq:-O3YGWDB44knitZ8voYr:bb8vbrp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85137f9bc31d14eb5fb5d80b938850def9113433/mullvad-cli/src/cmds/status.rs#L24)):*
> ```XML
> 
>     /// Enable debug output
>     #[arg(long, short = 'd', conflicts_with_all = ["verbose", "json"])]
> ```

Not sure that making --debug be incompatible with --verbose is good, but it seems to me that's how it should have been to begin with, since --verbose doesn't do anything if --debug is specified

**Review by Serock3 — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569#-:-O3c-u328K5U10Hug-g4:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`mullvad-cli/src/cmds/status.rs` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569#-O3YGWDB44knitZ8voYq:-O3byxnJDe4JIDS5PNBP:b2jcxsz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85137f9bc31d14eb5fb5d80b938850def9113433/mullvad-cli/src/cmds/status.rs#L24)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Not sure that making --debug be incompatible with --verbose is good, but it seems to me that's how it should have been to begin with, since --verbose doesn't do anything if --debug is specified
</blockquote></details>

I wasn't aware that that clap supported specifying incompatible arguments, nice addition
___
*[`mullvad-types/src/device.rs` line 89 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569#-O3bzSYH08WLklPwjXZo:-O3bzSYH08WLklPwjXZp:baa7873) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4b46a1a90d20ac59f4442c46e2cdd415b2d362/mullvad-types/src/device.rs#L89)):*
> ```XML
> 
> /// Reason why a [DeviceEvent] was emitted.
> #[derive(Clone, Debug, Serialize, Deserialize)]
> ```

I guess we don't really need `Deserialize`, do we?

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`mullvad-types/src/device.rs` line 89 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569#-O3bzSYH08WLklPwjXZo:-O3c1C2GCxXgwV9Xa_Hv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4b46a1a90d20ac59f4442c46e2cdd415b2d362/mullvad-types/src/device.rs#L89)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I guess we don't really need `Deserialize`, do we?
</blockquote></details>

Done.

**Review by Serock3 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
