### PR TITLE
Upgrade clap to 3.0

### LINKED ISSUE #3305: Subcommands are not correctly suggested in zsh
## Issue report

Operating system: macOS 10.15.7
App version: 2021.6
Shell: zsh 5.7.1 (x86_64-apple-darwin19.0)
 
### Issue description
If you type mullvad relay set tunnel and press Tab, the subcommand will be suggested as follows.
`help       -- Prints this message or the help of the given subcommand(s)`
`openvpn    -- Set OpenVPN-specific constraints`
`wireguard  -- Set WireGuard-specific constraints`
However, the subcommand `help` does not actually exist. The correct one is `--help`.

### PR DESCRIPTION
**Pull request by dlon**
The changes are fairly minimal. All breaking API changes and deprecated functionality are fixed. Unfortunately, clap 2.34 is still a dependency due to `udp-over-tcp`.

Closes #3305.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 8 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353)* status: 8 of 27 files reviewed, all discussions resolved

___
*[mullvad-cli/src/cmds/auto_connect.rs, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353#-MvsALJ0DrBuavTojc-D:-MvsALJ0DrBuavTojc-E:bp96iz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7e5a50f018da70ba0a7a8703f0c72c9602394fb/mullvad-cli/src/cmds/auto_connect.rs#L29)):*
> ```XML
>     async fn run(&self, matches: &clap::ArgMatches) -> Result<()> {
>         if let Some(set_matches) = matches.subcommand_matches("set") {
>             let auto_connect = set_matches.value_of("policy").expect("missing policy");
> ```

Technically, one could use `value_of_t_or_exit::<String>("policy")` here and elsewhere.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 19 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dlon** [comment]
> > Reviewed 8 of 27 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353)_ status: 8 of 27 files reviewed, all discussions resolved
> 
> _[mullvad-cli/src/cmds/auto_connect.rs, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353#-MvsALJ0DrBuavTojc-D:-MvsALJ0DrBuavTojc-E:bp96iz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7e5a50f018da70ba0a7a8703f0c72c9602394fb/mullvad-cli/src/cmds/auto_connect.rs#L29)):_
> 
> > ```
> >     async fn run(&self, matches: &clap::ArgMatches) -> Result<()> {
> >         if let Some(set_matches) = matches.subcommand_matches("set") {
> >             let auto_connect = set_matches.value_of("policy").expect("missing policy");
> > ```
> 
> Technically, one could use `value_of_t_or_exit::<String>("policy")` here and elsewhere.

I did not do this because `value_of` returns a `&str` already. So it should never fail anyway.

**Pull request merged**
