### PR TITLE
Login: add submit button

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR adds the submit button next login text field.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/AccountInputGroupView.swift, line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-McTTnBk90r6EVId2I_W:-McTTnBl2EPbKAQDQis5:bw2eu1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29ae5dc5ca496186cb8e52dbca02799340e9a671/ios/MullvadVPN/AccountInputGroupView.swift#L35)):*
> ```Swift
>     }
> 
>     var minimunAccountTokenLength = 10 {
> ```

Typo: Should be "minimu**m**AccountTokenLength"
___
*[ios/MullvadVPN/AccountInputGroupView.swift, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-McTXgbQ4ywMuMCqzQeR:-McTXgbR0wf923kZ8b5b:b-xj0qw8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29ae5dc5ca496186cb8e52dbca02799340e9a671/ios/MullvadVPN/AccountInputGroupView.swift#L36)):*
> ```Swift
> 
>     var minimunAccountTokenLength = 10 {
>         didSet {
> ```

Is this `didSet` needed? The same functions are called in `init` and the property is never changed as far as I can tell.
___
*[ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-McT5gEq8GqLPDzn4Wrf:-McT5gEq8GqLPDzn4Wrg:bmu2dcm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29ae5dc5ca496186cb8e52dbca02799340e9a671/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L14)):*
> ```
>       },
>       {
>         "package": "wireguard-apple",
> ```

What does this change do?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-McT5gEq8GqLPDzn4Wrf:-MchgEJW7KavCSw40BCT:b-b39yfz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29ae5dc5ca496186cb8e52dbca02799340e9a671/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L14)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

What does this change do?
</blockquote></details>

`Package.resolved` is similar to `package-lock.json` in Node.js. So I think that change is automatic, seems like new Xcode prefers to use the last component from the repository URL vs. the name of the package.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-:-MchiLgO80et-OpcawOI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-McT5gEq8GqLPDzn4Wrf:-MchiI2q0ANM-XTDB5tb:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29ae5dc5ca496186cb8e52dbca02799340e9a671/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`Package.resolved` is similar to `package-lock.json` in Node.js. So I think that change is automatic, seems like new Xcode prefers to use the last component from the repository URL vs. the name of the package.
</blockquote></details>

Okay :+1:

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[ios/CHANGELOG.md, line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805#-MchrO6b6Qn4ip4qyarF:-MchrO6b6Qn4ip4qyarG:b-tx7pa1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12034abba345982714354379e725e89e8de08f6e/ios/CHANGELOG.md#L31)):*
> ```Markdown
> 
> ### Fixed
> - Update WireGuardKit to the latest. Fixes the iOS 15 support.
> ```

FYI I realised that I haven't update the entry to indicate the iOS 15 fix.

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
