### PR TITLE
Block in-tunnel traffic for `mullvad-exclude`

### PR DESCRIPTION
**Pull request by dlon**
This updates the firewall to disallow any traffic going inside the tunnel when using `mullvad-exclude`, excepting non-custom DNS. DNS traffic is also blocked in the tunnel if custom DNS servers are configured.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/firewall/linux.rs, line 349 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274#-MMLfwSUEZyg3gOd2v2r:-MMLfwSUEZyg3gOd2v2s:b-q2vzvz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4274ac76bdb176da9649bb0c4cb0432038cd3ae2/talpid-core/src/firewall/linux.rs#L349)):*
> ```Rust
>         for chain in &nat_chains {
>             // Block remaining marked outgoing in-tunnel traffic
>             if let FirewallPolicy::Connected { tunnel, .. } = policy {
> ```

There may be a slight chance that the `0.0.0.0/1` route is created just prior to entering the connected state. Maybe there is an opportunity for leaks at that short interval if the routes are not correctly set up.
___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274#-MMLhp2374BDDHtqOZuA:-MMLhp2374BDDHtqOZuB:bdvx9cf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4274ac76bdb176da9649bb0c4cb0432038cd3ae2/talpid-core/src/tunnel_state_machine/connected_state.rs#L135)):*
> ```Rust
>             shared_values
>                 .route_manager
>                 .route_exclusions_dns(&self.metadata.interface, &dns_routes)
> ```

This is temporary. It should be possible to just set this up in the tunnel monitor or route manager, given that the destination is always the gateway IP.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/firewall/linux.rs, line 349 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274#-MMLfwSUEZyg3gOd2v2r:-MMM3b-aCNYOa-5e2EXi:b-df24pw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4274ac76bdb176da9649bb0c4cb0432038cd3ae2/talpid-core/src/firewall/linux.rs#L349)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There may be a slight chance that the `0.0.0.0/1` route is created just prior to entering the connected state. Maybe there is an opportunity for leaks at that short interval if the routes are not correctly set up.
</blockquote></details>

Routing in general shouldn't be used to enforce security guarantees. I'll respond with a more coherent thought after reviewing the code closer.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/firewall/linux.rs, line 349 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274#-MMLfwSUEZyg3gOd2v2r:-MMMHv0M13Yc-mk7WOAz:b-cbqjvi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4274ac76bdb176da9649bb0c4cb0432038cd3ae2/talpid-core/src/firewall/linux.rs#L349)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Routing in general shouldn't be used to enforce security guarantees. I'll respond with a more coherent thought after reviewing the code closer.
</blockquote></details>

The only reason the routes are set up before the tunnel is that it enabled the daemon to send ICMP to the gateway. So one way to block leaks during this time would be to apply the final routes after the firewall rules have been applied for the connected state. But this sounds somewhat hacky.
If the tunnel devices were kept around for the lifetime of the daemon, the connected state could also start blocking the split traffic from the tunnel quicker, even before the routes are applied. Lots of things might be simpler if one could just assume that the tunnel devices are there to stay.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Pull request merged**
