### PR TITLE
Detect macos scrollbar visibility

### PR DESCRIPTION
**Pull request by raksooo**
This PR reads the macOS scrollbar visibility setting and detects the visibility if the setting is set to `Automatic`. This is to behave the same as the OS.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/CustomScrollbars.tsx, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952#-MjDmYlk57HZpiPVEfs1:-MjDmYlk57HZpiPVEfs2:b-5zxe5u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8a9f08756fd927f13b3c947c978aba8b4fd2f54/gui/src/renderer/components/CustomScrollbars.tsx#L18)):*
> ```XML
> interface IProps {
>   autoHide?: boolean;
>   trackPadding?: { x: number; y: number };
> ```

Track padding has default prop, any reason it has to be nullable?

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952#-:-MjDnjxDEPrrW0fKg7vo:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/CustomScrollbars.tsx, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952#-MjDmYlk57HZpiPVEfs1:-MjDnDYF0534ALIGLFYe:b-pfpsx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8a9f08756fd927f13b3c947c978aba8b4fd2f54/gui/src/renderer/components/CustomScrollbars.tsx#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Track padding has default prop, any reason it has to be nullable?
</blockquote></details>

I had to add a container element to access `macOsScrollbarsVisible` in Redux. The container element messes up the detection of `defaultProps` and results in `trackPadding` being required in all usages of `CustomScrollbars`. There might be a better solution to this though, I didn't spend a lot of time on it. I'll do some thinking and see if I come up with something.

We could of course have two different interfaces for the container and component.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)* status: 12 of 13 files reviewed, all discussions resolved

___
*[gui/src/renderer/components/CustomScrollbars.tsx, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952#-MjDmYlk57HZpiPVEfs1:-MjDvo1F0Qn4vYPjVlE8:bli4h2u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8a9f08756fd927f13b3c947c978aba8b4fd2f54/gui/src/renderer/components/CustomScrollbars.tsx#L18)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I had to add a container element to access `macOsScrollbarsVisible` in Redux. The container element messes up the detection of `defaultProps` and results in `trackPadding` being required in all usages of `CustomScrollbars`. There might be a better solution to this though, I didn't spend a lot of time on it. I'll do some thinking and see if I come up with something.

We could of course have two different interfaces for the container and component.
</blockquote></details>

No need I suppose.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
