### PR TITLE
Rewrite screenshot tests to use new syntax

### PR DESCRIPTION
**Pull request by rablador**
We should update our screenshot tests to use the new syntax we use for UI tests.

This PR also adds replaces the location selection screenshot with a custom list selection screenshot, and includes https://linear.app/mullvad/issue/IOS-684/update-screenshots-to-use-pq-tunnels.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)

### CODE REVIEW

**Review by niklasberglund — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPNUITests/Pages/EditCustomListLocationsPage.swift` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzCzxpF4Um4HZ1NxOJK:-NzCzxpF4Um4HZ1NxOJL:b-azr98b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/MullvadVPNUITests/Pages/EditCustomListLocationsPage.swift#L61)):*
> ```Swift
>         }
> 
>         app.navigationBars[navigationBarName].buttons.firstMatch.tap()
> ```

This class `EditCustomListLocationsPage` is now for both add and edit, so the `action` context is required. Maybe it should be broken out into two page classes? There are a few differences between the edit and add views even though they also have much in common.
___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzDACxK9Vn9skgv1nWv:-NzDACxK9Vn9skgv1nWw:b2cnnw8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L37)):*
> ```Swift
>     }
> 
>     func testTakeScreenshotOfSecuredConnection() throws {
> ```

Should this screenshot still be captured? My interpretation of https://linear.app/mullvad/issue/IOS-684/update-screenshots-to-use-pq-tunnels is that this screenshot should be replaced by the screenshot with a quantum secured connection. It's nice to still have this around, but the drawback is that it opens up for possible mistakes if all screenshots should be used except this one.
___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzD-tsA7PCYPGVKh388:-NzD-tsA7PCYPGVKh389:b-2u8uof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L112)):*
> ```Swift
> 
>         CustomListPage(app)
>             .renameCustomList(name: "Low latency locations")
> ```

nit: would be nice as a constant since it is reused
___
*[`ios/TestPlans/MullvadVPNScreenshots.xctestplan` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzD0iKw9OmLIGw8tjA-:-NzD0iKw9OmLIGw8tjA0:b-6q4hed) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/TestPlans/MullvadVPNScreenshots.xctestplan#L31)):*
> ```
>         "SettingsMigrationTests",
>         "SettingsTests"
>       ],
> ```

Make sure to also uncheck "Automatically include new tests" for the `ScreenshotTests` test plan, otherwise new tests will be included in the plan.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Pages/EditCustomListLocationsPage.swift` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzCzxpF4Um4HZ1NxOJK:-NzS17yR7pfhWSXkrRK2:b-p6b5d5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/MullvadVPNUITests/Pages/EditCustomListLocationsPage.swift#L61)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

This class `EditCustomListLocationsPage` is now for both add and edit, so the `action` context is required. Maybe it should be broken out into two page classes? There are a few differences between the edit and add views even though they also have much in common.
</blockquote></details>

Right now the difference is basically the navigation title. We don't use inheritance much in the app, but I think a new `AddCustomListLocationsPage` could simply inherit `EditCustomListLocationsPage` and override the back tap function.
___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzDACxK9Vn9skgv1nWv:-NzRoEg3CSJca-zoHG0S:b-ogxztu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L37)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Should this screenshot still be captured? My interpretation of https://linear.app/mullvad/issue/IOS-684/update-screenshots-to-use-pq-tunnels is that this screenshot should be replaced by the screenshot with a quantum secured connection. It's nice to still have this around, but the drawback is that it opens up for possible mistakes if all screenshots should be used except this one.
</blockquote></details>

Yeah, you're probably right. I'll remove this test.
___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzD-tsA7PCYPGVKh388:-NzRpscnDpABsMJFC5dM:b2nhswv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L112)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

nit: would be nice as a constant since it is reused
</blockquote></details>

Yep
___
*[`ios/TestPlans/MullvadVPNScreenshots.xctestplan` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzD0iKw9OmLIGw8tjA-:-NzRqHfP6GJjeuohCUze:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/880b1f3759ad8690bdb550add430d773e52e79c9/ios/TestPlans/MullvadVPNScreenshots.xctestplan#L31)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Make sure to also uncheck "Automatically include new tests" for the `ScreenshotTests` test plan, otherwise new tests will be included in the plan.


</blockquote></details>

Done.

**Review by niklasberglund — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-:-NzS56tX21awotxWAU8J:bnfp4nl)* status: 0 of 18 files reviewed, 3 unresolved discussions

**Review by niklasberglund — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzS78HSBgRnccoUUKeh:-NzS78HSBgRnccoUUKei:b-y4b7q1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc8d80b04f0580ee8fef0eac86fcc8f623ec179a/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L33)):*
> ```Swift
>         if TunnelControlPage(app).connectionIsSecured {
>             TunnelControlPage(app)
>                 .tapDisconnectButton()
> ```

I think it would be easier to follow the code if this reset is done in `testTakeScreenshotOfQuantumSecuredConnection` teardown.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzS78HSBgRnccoUUKeh:-NzSPEKC9PCwkjHLUR1j:b61x4ld) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc8d80b04f0580ee8fef0eac86fcc8f623ec179a/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L33)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

I think it would be easier to follow the code if this reset is done in `testTakeScreenshotOfQuantumSecuredConnection` teardown.
</blockquote></details>

I agree, but that also requires each test to go back to the home screen when they're done. On startup that's where we begin each time. The real "problem" here is that the tests aren't completely stand-alone, but it felt unnecessarily thorough/slow to uninstall the app between each of them.

**Review by niklasberglund — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzS78HSBgRnccoUUKeh:-NzSiRLA7kNnlpFS7o9b:b-vq6jj5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc8d80b04f0580ee8fef0eac86fcc8f623ec179a/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L33)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I agree, but that also requires each test to go back to the home screen when they're done. On startup that's where we begin each time. The real "problem" here is that the tests aren't completely stand-alone, but it felt unnecessarily thorough/slow to uninstall the app between each of them.
</blockquote></details>

It looks like `testTakeScreenshotOfQuantumSecuredConnection` is the only test case connecting to a relay, so this code will only run after `testTakeScreenshotOfQuantumSecuredConnection`, so it's kind of its teardown but instead it is in the next test cases' setup.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzS78HSBgRnccoUUKeh:-NzSlCRqDfj8DdfpaXXZ:b-4keebn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc8d80b04f0580ee8fef0eac86fcc8f623ec179a/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L33)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It looks like `testTakeScreenshotOfQuantumSecuredConnection` is the only test case connecting to a relay, so this code will only run after `testTakeScreenshotOfQuantumSecuredConnection`, so it's kind of its teardown but instead it is in the next test cases' setup.
</blockquote></details>

Discussed offline. Will inherit from `LoggedInWithTimeUITestCase` to make tests independent of each other (results in a logout if logged in before each test).

**Review by niklasberglund — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-:-NzSrhW2ALqmkJgpZJPn:bnfp4nl)* status: 0 of 18 files reviewed, 4 unresolved discussions

**Review by buggmagnet — APPROVED** [review]
> Reviewed 12 of 17 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @niklasberglund and @rablador)

___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzTNL406ZNDiPc8WO1w:-NzTNL406ZNDiPc8WO1x:bncwln6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f1985021e29dd7c56e9ef21766e5662c2b43dba/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L25)):*
> ```Swift
> 
>     func testTakeScreenshotOfQuantumSecuredConnection() throws {
>         // We can't close banners in the screenshot tests due to how the NotificationController view
> ```

Is it because the notification is not accessible ?
Can we make it accessible in that case ? That seems like a silly limitation to have.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-NzTNL406ZNDiPc8WO1w:-NzTTx0-5r6TzM7Kp7ep:b-un4d77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f1985021e29dd7c56e9ef21766e5662c2b43dba/ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Is it because the notification is not accessible ?
Can we make it accessible in that case ? That seems like a silly limitation to have.
</blockquote></details>

It's indeed silly. There's a PR for it here: https://linear.app/mullvad/issue/IOS-704/make-notifications-accessible

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6300#-:-NzX0FGn9ylNXy5oMhgG:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @niklasberglund)

**Pull request merged**
