### PR TITLE
Add support for adaptive icons.

### PR DESCRIPTION
**Pull request by axti**
This PR contains adaptive icon for Android.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
We need to update the documentation about graphics/icons to reflect this I think? Please see `graphics/README.md` and see what adjustments need to be made/added. Would be nice to describe there that Android supports adaptive icons and include the path to the vector image that defines the actual icon.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-:-MXksbrt09JT2pne-U0G:b-b4962m)* status: 0 of 4 files reviewed, all discussions resolved

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-MXlPlQ1CDIgS9FQPkj1:-MXlPlQ37qID1L3-G6pA:bdvkktq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/095dc3c37a431f399f7d6b94972230e7d6d4ef9a/android/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L5)):*
> ```XML
>     <background android:drawable="@color/ic_launcher_background"/>
>     <foreground android:drawable="@drawable/ic_launcher_foreground"/>
> </adaptive-icon>
> ```

Missing new line at the end of the file.

**Review by axti — COMMENTED** [review]
@faern No adjustment needed, as source we use another icon. I add the source icon and update readme in graphics.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-:-MXpMvqx1HHMRfUf92u7:b-jltb8z)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-MXlPlQ1CDIgS9FQPkj1:-MXpNJrn8fwyxbRsWKX6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/095dc3c37a431f399f7d6b94972230e7d6d4ef9a/android/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L5)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Missing new line at the end of the file.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
:clap: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-:-MXpqURa1K4Hg2qhWMF2:bc0irgz)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[CHANGELOG.md, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-MXppxGt8v_kSJU3aklp:-MXppxGt8v_kSJU3aklq:b-n0je9a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af14a4513a17bfa7cca5b77c9b6f94c29f5f9f5b/CHANGELOG.md#L33)):*
> ```Markdown
> 
> #### Android
> - Added support of adaptive icons (available only from Android 8).
> ```

Nitpick. Should be `Add` not `Added` for imperative form.

**Review by jvff — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @jvff)

___
*[CHANGELOG.md, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-MXppxGt8v_kSJU3aklp:-MY9xOyn-zQ9SbZfz7F0:b-ucfkn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af14a4513a17bfa7cca5b77c9b6f94c29f5f9f5b/CHANGELOG.md#L33)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpick. Should be `Add` not `Added` for imperative form.
</blockquote></details>

Thanks.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2643#-:-MYBDxQDArj338IogA1f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
