### PR TITLE
Add device revoked view

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR adds the revoked device view/flow to the Android app using jetpack compose.

Git checklist:

~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (partial feature)
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 5 of 22 files at r2, 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: 6 of 27 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 5 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: 11 of 27 files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 165 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627#-N3y84Gi6wJoy4czRzsa:-N3y84Gi6wJoy4czRzsb:b-dcwx7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5597fe428e1db8a2c179b7c206a679e20e64ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L165)):*
> ```Kotlin
>                         is DeviceState.Revoked -> openRevokedView()
>                         is DeviceState.LoggedOut -> openLoginView()
>                         else -> Unit
> ```

Would it not make more sense to cover all the cases in a stricter fashion? Currently, the `else` accounts only fort the initial state.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: 11 of 27 files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 165 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627#-N3y84Gi6wJoy4czRzsa:-N3yH78TB8u7ess3dNlf:bse7yx7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5597fe428e1db8a2c179b7c206a679e20e64ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L165)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would it not make more sense to cover all the cases in a stricter fashion? Currently, the `else` accounts only fort the initial state.
</blockquote></details>

Good point! I was thinking about improving this so I'll have another look.

EDIT: I've updated the PR to better handle device states.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 10 of 22 files at r2, 1 of 3 files at r3, 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt` line 94 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627#-N3yQe549WXdMgr7ZVti:-N3yQe549WXdMgr7ZVtj:bz6xjdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5597fe428e1db8a2c179b7c206a679e20e64ce/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt#L94)):*
> ```Kotlin
>             assertEquals(DeviceRevokedUiState(false), awaitItem())
>             serviceConnectionState.value = ServiceConnectionState.ConnectedReady(mockedContainer)
>             assertEquals(DeviceRevokedUiState(true), awaitItem())
> ```

I'm not disagreeing with the necessity for such a test, but I am struggling to come up with a practical scenario where the user would see the revoked screen go from an unsecured to a secured state.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: 0 of 34 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt` line 94 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627#-N3yQe549WXdMgr7ZVti:-N4VtqXu3gkZRAMF0kM7:b-oo3g4r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c5597fe428e1db8a2c179b7c206a679e20e64ce/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt#L94)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'm not disagreeing with the necessity for such a test, but I am struggling to come up with a practical scenario where the user would see the revoked screen go from an unsecured to a secured state.
</blockquote></details>

Changed DeviceRevokedUiState into an enum to reflect whether the state is SECURED, UNSECURED or UNKNWON (e.g. while service is re-connecting). This test includes the UNKNOWN state as it's the default value until the service has started and been bound.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: 30 of 35 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 180 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627#-N4XEbOkElL-EJsM0XZp:-N4aM9hUDXl18N2slKoa:b-pmabss) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9320f878089cd6f9c1eaf42aebed08e2db0c6818/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L180)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This reduces all device state events so that the flow would never produce two of the same event in series?
</blockquote></details>

Removed this in favor of adding proper equality checking for the `DeviceState.LoggedIn`, which means that the regular comparison `currentState != newState` will cover this case. As the `Unknown` state is debounced, e.g. during app resume, there might be two of the same events in series.

Here's an example of the transitions:
1. App startup: `Initial` -> `Unknown` (until connected to service) -> `LoggedIn`
2. App put to background: (no event)
3. App put to foreground: `Unknown` (debounced due to reconnecting to service) -> `LoggedIn` (note that last event was also `LoggedIn` due to the debounce)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3627)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
