### PR TITLE
Refactor the tunnel state machine to get rid of futures 0.1

### PR DESCRIPTION
**Pull request by dlon**
This implements everything using new-style futures and gets rid of `futures 0.1`. `TunnelStateMachine` is no longer implemented as a `Stream` but instead provides a `run` method to handle tunnel commands and state changes.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MId2mLv9xJ_5RVwSmOZ:-MId2mME5XvAZnYgu5SB:bsi1dtn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/connected_state.rs#L289)):*
> ```Rust
>             }
>         };
>         fut
> ```

`EventConsequence` is not a future, is it? I think the return type here is `EventConsequence`?. So the name of this variable seems off :thinking: Feels like binding to a variable is not needed? The entire `futures::select!` block can just be the return expression?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdIkKfCEOQlw4W4g3s:-MIdIkKg75pEMf6xuRXE:b-a42azc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L132)):*
> ```Rust
> 
>         // TODO: Spawn this on a tokio runtime, and share it with RouteManager, etc.
>         futures::executor::block_on(state_machine.run(state_change_listener));
> ```

Just marking this TODO as a thread. Should likely be fixed before merge. I don't think we should start mixing in two runtimes here.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 246 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdJ9Go9OEIdzdMugjb:-MIdJ9Go9OEIdzdMugjc:b-7qutml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L246)):*
> ```Rust
>                 }
>                 Finished => {
>                     log::debug!("Finished");
> ```

These debug statements should probably be either more explanatory or removed before merge.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdJHeqBdKfjFsE9ZDh:-MIdJHeqBdKfjFsE9ZDi:b9x442c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L287)):*
> ```Rust
> }
> 
> unsafe impl std::marker::Send for SharedTunnelStateValues {}
> ```

Are we sure this is safe?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MId2mLv9xJ_5RVwSmOZ:-MIdSiPO6lOVkZiWzMn5:b-8kripy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/connected_state.rs#L289)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`EventConsequence` is not a future, is it? I think the return type here is `EventConsequence`?. So the name of this variable seems off :thinking: Feels like binding to a variable is not needed? The entire `futures::select!` block can just be the return expression?
</blockquote></details>

Fixed. It has to have an explicit return statement, though.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 246 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdJ9Go9OEIdzdMugjb:-MIderfT9ryiJrGswrPf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L246)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These debug statements should probably be either more explanatory or removed before merge.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdJHeqBdKfjFsE9ZDh:-MIdesEhD1aCQMKsFIOA:bvnpod9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L287)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Are we sure this is safe?
</blockquote></details>

I nearly forgot about this. It might not be safe. Based on [this](https://docs.rs/dbus/0.9.0/dbus/blocking/struct.Connection.html) and [this](https://github.com/diwic/dbus-rs/blob/master/dbus/changes-in-0.7.md), it seems to be avoidable by refactoring our code to not use the old connection type.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MId2mLv9xJ_5RVwSmOZ:-MIdnWPC9mvFH-y0eJho:bvlktin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/connected_state.rs#L289)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Fixed. It has to have an explicit return statement, though.
</blockquote></details>

Not very idiomatic to use `return` when it's the last expression in the method. You can just get rid of `return` and the ending `;`

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[talpid-core/src/tunnel_state_machine/disconnecting_state.rs, line 90 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdlhsf9BGvpYXF5acp:-MIdlhsg5qh_zOLxvoSv:blsyn6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75041285f4fc961daa19ea9814c538d5f1770805/talpid-core/src/tunnel_state_machine/disconnecting_state.rs#L90)):*
> ```Rust
>                 Some(TunnelCommand::Disconnect) => AfterDisconnect::Nothing,
>                 Some(TunnelCommand::Block(reason)) => AfterDisconnect::Block(reason),
>                 None => AfterDisconnect::Nothing,
> ```

Nit, but this arm can be combined with the `TunnelCommand:Disconnect` arm.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdIkKfCEOQlw4W4g3s:-MIdmtlM2WvM0K1VKoZW:b-1swrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L132)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Just marking this TODO as a thread. Should likely be fixed before merge. I don't think we should start mixing in two runtimes here.
</blockquote></details>

Given that the fix would be trivial - get a tokio handle from the parent thread and move it into the closure - I completely agree.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 163 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdnNnD-_igWe-E_Auz:-MIdnNnD-_igWe-E_Av-:bq9v820) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75041285f4fc961daa19ea9814c538d5f1770805/talpid-core/src/tunnel_state_machine/mod.rs#L163)):*
> ```Rust
> }
> 
> type TunnelCommandReceiver = Pin<Box<dyn FusedStream<Item = TunnelCommand> + Send>>;
> ```

This can be simplified to `Box<dyn FusedStream<Item = TunnelCommand> + Send + Unpin>`.
Or it could be simplified further to `stream::Fuse<mpsc::UnbounderdReceiver<TunnelCommand>>`, to elide the extra boxing.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MId2mLv9xJ_5RVwSmOZ:-MIdqbVP7rYrnYUV4mWT:b-96lu5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/connected_state.rs#L289)):*
> Fixed. It has to have an explicit return statement, though.

For some reason I missed that you wrote this :o Sorry!
How come it must be an explicit return statement? That sounds very strange.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/disconnecting_state.rs, line 90 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdlhsf9BGvpYXF5acp:-MIdv1IP53JFpZXJ_Ud_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75041285f4fc961daa19ea9814c538d5f1770805/talpid-core/src/tunnel_state_machine/disconnecting_state.rs#L90)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Nit, but this arm can be combined with the `TunnelCommand:Disconnect` arm.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdIkKfCEOQlw4W4g3s:-MIdv2i79qjvVeEFGw80:b-obldg6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L132)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Given that the fix would be trivial - get a tokio handle from the parent thread and move it into the closure - I completely agree.
</blockquote></details>

It's not entirely that trivial. Simply calling `handle.block_on(state_machine.run())` here causes a panic when `block_on` is later called within the route manager.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 163 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdnNnD-_igWe-E_Auz:-MIdvQkQ4y0hagGf8q8S:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75041285f4fc961daa19ea9814c538d5f1770805/talpid-core/src/tunnel_state_machine/mod.rs#L163)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This can be simplified to `Box<dyn FusedStream<Item = TunnelCommand> + Send + Unpin>`.
Or it could be simplified further to `stream::Fuse<mpsc::UnbounderdReceiver<TunnelCommand>>`, to elide the extra boxing.
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 289 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MId2mLv9xJ_5RVwSmOZ:-MIdvh2f1DELUuN80yAE:b-oxg7gx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/connected_state.rs#L289)):*
I didn't look into what was going on in the macro, but the exact error was this:
> can't capture dynamic environment in a fn item
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdIkKfCEOQlw4W4g3s:-MIsA_046Acnn7DkFv16:bilremg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L132)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's not entirely that trivial. Simply calling `handle.block_on(state_machine.run())` here causes a panic when `block_on` is later called within the route manager.
</blockquote></details>

Done.

`handle_event` takes a runtime handle now, and is only used to resolve the futures, preventing these panics (and preventing this PR from becoming too large). This was also done to avoid the `unsafe impl Send`.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdJHeqBdKfjFsE9ZDh:-MIsB5rm3jhDScNGZwWG:b-fetgo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L287)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I nearly forgot about this. It might not be safe. Based on [this](https://docs.rs/dbus/0.9.0/dbus/blocking/struct.Connection.html) and [this](https://github.com/diwic/dbus-rs/blob/master/dbus/changes-in-0.7.md), it seems to be avoidable by refactoring our code to not use the old connection type.
</blockquote></details>

This could be removed. See the comment above.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 2 files at r3, 3 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[talpid-core/src/routing/linux.rs, line 964 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIsEpN0-cD-EAWr-TQA:-MIsEpN0-cD-EAWr-TQB:bhdhmi8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c59753ebaceece13091c0961003dd37863a5075f/talpid-core/src/routing/linux.rs#L964)):*
> ```Rust
> impl Drop for RouteManagerImpl {
>     fn drop(&mut self) {
>         futures::executor::block_on(self.destructor());
> ```

What guarantees that the routes will always be cleaned up in case that the TSM crashes?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/routing/linux.rs, line 964 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIsEpN0-cD-EAWr-TQA:-MIsHUWX-3GjiZvnW9tl:b-1h75a4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c59753ebaceece13091c0961003dd37863a5075f/talpid-core/src/routing/linux.rs#L964)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What guarantees that the routes will always be cleaned up in case that the TSM crashes?
</blockquote></details>

Doesn't `RouteManager::drop` already do this?

**Review by pinkisemils — APPROVED** [review]
> Reviewed 6 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[talpid-core/src/routing/linux.rs, line 964 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIsEpN0-cD-EAWr-TQA:-MIsIEg54LkDTppcRXWe:b-n9k8nw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c59753ebaceece13091c0961003dd37863a5075f/talpid-core/src/routing/linux.rs#L964)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Doesn't `RouteManager::drop` already do this?
</blockquote></details>

Ah, you are correct!

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: all files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159#-MIdIkKfCEOQlw4W4g3s:-MIsPOK--C_pGxQiyNso:b-97yj3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bf44c64a9944527b6d43831abdcd4b5c0436d08/talpid-core/src/tunnel_state_machine/mod.rs#L132)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.

`handle_event` takes a runtime handle now, and is only used to resolve the futures, preventing these panics (and preventing this PR from becoming too large). This was also done to avoid the `unsafe impl Send`.
</blockquote></details>

I'm a bit confused. We are currently in an `async fn`. `spawn` is `async fn`. Having it create a new runtime, spawn an OS thread and make the OS thread drive the new runtime seems very strange. Can't we just replace the entire `std::thread::spawn` with `tokio::spawn` and thus drive the state machine in a new task in the current runtime?

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2159)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
