### PR TITLE
Fix reliability and time consumption of testInitialConnectionTimings test

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 406 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecaqhV-Fz9ibrmOU-v:-NecaqhV-Fz9ibrmOU-w:b-jiyt9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/MullvadVPN.xcodeproj/project.pbxproj#L406)):*
> ```
> 		7A42DEC92A05164100B209BE /* SettingsInputCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A42DEC82A05164100B209BE /* SettingsInputCell.swift */; };
> 		7A42DECD2A09064C00B209BE /* SelectableSettingsCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A42DECC2A09064C00B209BE /* SelectableSettingsCell.swift */; };
> 		7A6B4F592AB8412E00123853 /* TunnelMonitorTimings.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A6B4F582AB8412E00123853 /* TunnelMonitorTimings.swift */; };
> ```

Please move the file after `TunnelMonitorProtocol.swift`
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NeccNoxCvdDmj6RJeJH:-NeccNoxCvdDmj6RJeJI:bnf869m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L62)):*
nit
I would say that the documentation bit is redundant here, we already established the timeouts when creating the `timings` variable. 

The part that says
> default first connection attempt starts at 4 second timeout, then doubles with each subsequent attempt, while being capped at 15s max.

Is probably more relevant in the `TunnelMonitor` file, or maybe the `TunnelMonitorTimings` file itself. 

But it's not a big deal either.
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecdgdREGH0leJ7xDdp:-NecdgdSDCPwKlWT5rwG:bg69hgf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L73)):*
> ```Swift
> 
>         // Calculate the amount of time necessary to perform the test adding some leeway.
>         let timeout = expectedTimings.reduce(1000, +)
> ```

On my machine, this runs roughly in 900ms, so that leeway could work. But it can easily run slower in a VM / on the CI environment. 

Just today I had a test where it ran in 43.017 seconds instead of the original 42 seconds. 

So it would also fail here for the wrong reasons. 

I suggest being conserative and tripling that value for now, so 3 seconds expected at most. 
This should be low enough that we never wait too long, and high enough that if there is a deadlock, it doesn't make the test runner stall for too long before moving on.
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecfPEN2bU-ARUmX-pP:-NecfPEN2bU-ARUmX-pQ:b-36uwj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L98)):*
Currently it's printing 
> [1/3] connectionLost, time elapsed: 100s

You can use the following trick to avoid computing time manually
`let measuredTimeElapsed = Measurement(value: Double(timeElapsed), unit: UnitDuration.milliseconds)`

Then if you want to convert you can simply do `measuredTimeElapsed.converted(to: UnitDuration.seconds)` 
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NeciJTz8ShJcl7yAxk_:-NeciJTz8ShJcl7yAxka:b544t80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L148)):*
> ```Swift
> 
>     private func roundToHundreds(_ value: Int) -> Int {
>         return (value / 100 * 100) + ((value % 100) / 50 * 100)
> ```

Couple of things come to mind here 

- This could probably be an extension on `Int` instead
- The first expression `(value / 100 * 100)` is redundant... Unless we're dealing with `Double` 

Which we are, because we're doing maths on `TimeInterval` 
Also I think the whole computation is unnecessary. 
Instead of rounding our values, we should just use the `accuracy` option of `XCTestEqual` 

If I do the following instead 
`let elapsed = Int(Date().timeIntervalSince(startDate) * 1000)
Then I can simply do 
`XCTAssertEqual(elapsed, expectedDuration, accuracy: 10, "Some fancy error message here")`


Without doing any complicated maths.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 406 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecaqhV-Fz9ibrmOU-v:-NegSLNVDS3p7-zUKWbD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/MullvadVPN.xcodeproj/project.pbxproj#L406)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please move the file after `TunnelMonitorProtocol.swift`
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NeccNoxCvdDmj6RJeJH:-NegS0zJ3xD1xl7bY0ej:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L62)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I would say that the documentation bit is redundant here, we already established the timeouts when creating the `timings` variable. 

The part that says
> default first connection attempt starts at 4 second timeout, then doubles with each subsequent attempt, while being capped at 15s max.

Is probably more relevant in the `TunnelMonitor` file, or maybe the `TunnelMonitorTimings` file itself. 

But it's not a big deal either.
</blockquote></details>

Removed.
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecdgdREGH0leJ7xDdp:-NegQL5T0tOrIJlUdPXy:bkctd81) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L73)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

On my machine, this runs roughly in 900ms, so that leeway could work. But it can easily run slower in a VM / on the CI environment. 

Just today I had a test where it ran in 43.017 seconds instead of the original 42 seconds. 

So it would also fail here for the wrong reasons. 

I suggest being conserative and tripling that value for now, so 3 seconds expected at most. 
This should be low enough that we never wait too long, and high enough that if there is a deadlock, it doesn't make the test runner stall for too long before moving on.
</blockquote></details>

Not that much, though? Perhaps upping to 1500? 
If each individual measure is about 100-300 millis, adding 3000 as leeway is a little overkill (not that it really matters). What I mean is that if we're going with your proposal below to use "accuracy" when asserting the time elapsed, I think 50ms would be good for that. Everything outside that will fail. So if all four asserts fail there's going to be 200ms added in total. Ie, if the tests takes more that 1100 millis it should fail anyway.
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecfPEN2bU-ARUmX-pP:-NegPMj4EaAMzlAdeTAZ:b3ymb4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L98)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Currently it's printing 
> [1/3] connectionLost, time elapsed: 100s

You can use the following trick to avoid computing time manually
`let measuredTimeElapsed = Measurement(value: Double(timeElapsed), unit: UnitDuration.milliseconds)`

Then if you want to convert you can simply do `measuredTimeElapsed.converted(to: UnitDuration.seconds)`
</blockquote></details>

Oh, simply forgot to add an "m". I like your suggestion, but perhaps a little overkill?
___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NeciJTz8ShJcl7yAxk_:-NegJ20l342tBytIEoeT:b-qn5eat) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85b08ef2713a781dd78628eee2becec7a3b85476/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L148)):*
> The first expression `(value / 100 * 100)` is redundant...

Since we're dealing with integers there's some rounding going on here. Eg. 123 / 100 * 100 = 100.

The reason for normalising the values is that we - apart from the assertion - also print out what happens. So in `Expected to report connection loss after \(expectedDuration)s, instead reported it after \(timeElapsed)s` we probably want numbers that match.

I do agree that accuracy in XCTAssertEqual is generally a better choice (didn't know about it until now), but I'm not sure what to do about those logs. Maybe `Expected to report connection loss after *roughly* \(expectedDuration)s [...]` or something?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCoreTests/TunnelMonitorTests.swift` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-NecfPEN2bU-ARUmX-pP:-Neh9Mvg33wp7sp0vLCr:b-tqkdqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8de84cee7c8329733d47ed36adc831586838cdc/ios/PacketTunnelCoreTests/TunnelMonitorTests.swift#L98)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Oh, simply forgot to add an "m". I like your suggestion, but perhaps a little overkill?
</blockquote></details>

Discussed offline and the decision was to leave it as-is

**Review by buggmagnet — APPROVED** [review]
nice job ! 

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160#-:-NehAXUhAmrvX8VH3xkv:b-v5yun4)* status: 4 of 5 files reviewed, all discussions resolved

**Pull request merged**
