### PR TITLE
Improve the android build instructions for mac os

### PR DESCRIPTION
**Pull request by Pururun**
Added macOS variants whenever needed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NWbpuk93nSd1tuZjxtX):*
nit: I suggest macos or macOS



_Code quote:_
```
mac os
```
___
*[`android/BuildInstructions.md` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NWbpZjI0ajpbEfPyL0Q:-NWbpZjJBvOVh7-kw_3O:b-jwiz02) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d4974e57a01ce6b9371a835b4616d04e3e76551/android/BuildInstructions.md#L175)):*
> ```Markdown
>   ```
>   [target.aarch64-linux-android]
>   ar = "/opt/android/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
> ```

Can we use `${NDK_TOOLCHAIN_DIR}` in this config file instead of the full paths? This applies to all `ar` and `linker` fields



_Code quote:_
```Markdown
/opt/android/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin
```

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`android/BuildInstructions.md` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NWdQqQeA1nnS5K1lxg3:-NWdQqQeA1nnS5K1lxg4:b9tfvqf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d4974e57a01ce6b9371a835b4616d04e3e76551/android/BuildInstructions.md#L137)):*
> ```Markdown
> environment variables:
> 
> ##### Linux
> ```

This is not rendered correctly because the indentation is off.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @Pururun)

**Review by dlon — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @dlon)

___
*[`android/BuildInstructions.md` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NWbpZjI0ajpbEfPyL0Q:-NXUGW1mBLMGKCKZCbsl:brgvbvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d4974e57a01ce6b9371a835b4616d04e3e76551/android/BuildInstructions.md#L175)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we use `${NDK_TOOLCHAIN_DIR}` in this config file instead of the full paths? This applies to all `ar` and `linker` fields
</blockquote></details>

Changed it so that we use environment variables instead, since those are the same on linux and macOS.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @dlon)

___
*[`android/BuildInstructions.md` line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NXUJUqs4bqoSxjVTZHY:-NXikuPM3f9zUhXgr_eK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e65dbed4b94a06b1b7808d5a7dace0ddc9d2ad07/android/BuildInstructions.md#L146)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps we should clarify that this and other env vars should be put in something like `.bashrc`/`.zshrc`/`.zshenv`? 
</blockquote></details>

Done.
___
*[`android/BuildInstructions.md` line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NXUIbb15Hl2HBi5d_CZ:-NXikwGWDwODF4mhT5du:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e65dbed4b94a06b1b7808d5a7dace0ddc9d2ad07/android/BuildInstructions.md#L172)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest moving these up to the other environment variables, which would mean that cross-compilation, the linker and  the archiver is configured in a single step.
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-:-NXioa694QKMB-ez5T1F:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/BuildInstructions.md` line 137 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NXipdXrB5qDmSZGYtJs:-NXipdXrB5qDmSZGYtJt:bw5ewfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d58967dac11d502a77a01d92e1765638f45376de/android/BuildInstructions.md#L137)):*
> ```Markdown
> environment variables:
> 
> ##### Linux
> ```

It still looks a bit weird rendered because the Linux header is not indented, I think. Could we maybe remove the header and change the point below to

```
- (Linux) Add to `~/.bashrc` or equivalent:
```

?

And do the same thing for macOS.

This is only a suggestion, though. You can merge this anyway, if you want.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/BuildInstructions.md` line 140 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740#-NXjU1fh3hQYLv2O-fYJ:-NXjX8685k3wZVYhLeLc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e2d5559f92c70acf7515b4be749bd564c155280f/android/BuildInstructions.md#L140)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There seem to be two spaces here on this otherwise empty line
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
