### PR TITLE
Change account expiry text to display 'less than a day'

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-:-NiETu9s7N11Drua2rOY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by pinkisemils** [comment]
Would you mind adding a screenshot of how it looks now?  :slightly_smiling_face:

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-:-NiKodizDVaA14lCMuB4:bimkvn9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @pronebird)

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-Ni_OKIEB08DNa8bPHqq:-Ni_OKIEB08DNa8bPHqr:brto9za) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396cee88df154c1be5fb4a92ee87c6121cf84b0/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L41)):*
> ```Swift
> 
>     var notificationDescriptor: InAppNotificationDescriptor? {
>         guard
> ```


This is what I get when I log with an account that doesn't have time. It looks like the condition that was there previously was necessary.

Let's add tests to :
- Make sure we don't repeat that mistake again next time we modify this
- Make sure the behaviour is well defined

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NidNuLl9ieOP8X67kAj:-NidNuLm8LazmH8RoRjp:bj9kzoe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396cee88df154c1be5fb4a92ee87c6121cf84b0/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L32)):*
> ```Swift
>         guard dateComponents.day != nil else {
>             return NSLocalizedString(
>                 "ACCOUNT_EXPIRY_INAPP_NOTIFICATION_LESS_THAN_ONE_DAY",
> ```

Maybe the text identifier should better reflect where it comes from?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NidNuLl9ieOP8X67kAj:-NieCGzs6XV0F8CHaBUR:buketii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396cee88df154c1be5fb4a92ee87c6121cf84b0/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L32)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe the text identifier should better reflect where it comes from?
</blockquote></details>

Indeed
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-Ni_OKIEB08DNa8bPHqq:-NieCIdjEyvxMkMvs52l:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396cee88df154c1be5fb4a92ee87c6121cf84b0/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>


This is what I get when I log with an account that doesn't have time. It looks like the condition that was there previously was necessary.

Let's add tests to :
- Make sure we don't repeat that mistake again next time we modify this
- Make sure the behaviour is well defined
</blockquote></details>

Done.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NieHUCc23PDfilcYItP:-NieHUCc23PDfilcYItQ:b-5ts1bw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70f72cdd73d61b0315c5eaf62817c105fce6f68c/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L47)):*
> ```Swift
>     }
> 
>     private static func isLessThanADayLeft(dateComponents: DateComponents) -> Bool {
> ```

nit: I would suggest of renaming that to `isLessThanOneDay`



_Code snippet:_
```Swift
fileprivate extension DateComponents {
    var isLessThanOneDayLeft : Bool {
        let year = self.year ?? 0
        let day = self.day ?? 0

        return (year == 0) && (day == 0)
    }
}
```
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 33 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NieKMNm36plGSHBhtzi:-NieKMNm36plGSHBhtzj:bxmnl4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df9a89c62366f863d4c92eecab5677526f229341/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L33)):*
> ```Swift
>             let triggerDate,
>             let duration = CustomDateComponentsFormatting.localizedString(
>                 from: Date(),
> ```

it's better to consider the now constant you've defined above

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

**Review by buggmagnet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NieHUCc23PDfilcYItP:-NiiCPXvEgWSqE6326Xt:b-zcncoa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70f72cdd73d61b0315c5eaf62817c105fce6f68c/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L47)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: I would suggest of renaming that to `isLessThanOneDay`
</blockquote></details>

The current name is fine
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NiiBLpDBfaXRoOdr300:-NiiBLpE0YjRIqn6IwId:bn2q4mq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df9a89c62366f863d4c92eecab5677526f229341/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L13)):*
> ```Swift
> import MullvadTypes
> 
> struct AccountExpiry {
> ```

Let's put this in a separate file
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 19 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NiiCmcT9wuBqddqO1eG:-NiiCmcT9wuBqddqO1eH:bmm4wjl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df9a89c62366f863d4c92eecab5677526f229341/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L19)):*
> ```Swift
>         guard let expiryDate else { return nil }
> 
>         return Calendar.current.date(
> ```

It's better to use `autoupdatingCurrent` to track user made time changes.
...
Although considering we use `current` everywhere else, I will create a janitor task instead to change all references to `autoupdatingCurrent`

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NieHUCc23PDfilcYItP:-NiiwdsiCF5ny5WjF4tO:bpkfufs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70f72cdd73d61b0315c5eaf62817c105fce6f68c/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L47)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The current name is fine
</blockquote></details>

I'll change the name, but keep the function in CustomDateComponentsFormatting since it's probably only relevant in this context.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NiiBLpDBfaXRoOdr300:-NiixN8D2-og819tWDpr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df9a89c62366f863d4c92eecab5677526f229341/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's put this in a separate file
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 19 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NiiCmcT9wuBqddqO1eG:-Niiwvsj3PZKpYtYjsIz:byv3f8f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df9a89c62366f863d4c92eecab5677526f229341/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L19)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It's better to use `autoupdatingCurrent` to track user made time changes.
...
Although considering we use `current` everywhere else, I will create a janitor task instead to change all references to `autoupdatingCurrent`
</blockquote></details>

I'll keep it as-is then.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift` line 33 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NieKMNm36plGSHBhtzi:-NiixO5kAxlJXox1LpL1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df9a89c62366f863d4c92eecab5677526f229341/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiryInAppNotificationProvider.swift#L33)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's better to consider the now constant you've defined above
</blockquote></details>

Done.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 440 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NinJkDvCZZyQYxhFrpq:-NinJkDvCZZyQYxhFrpr:b-hupqn0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d5ed047ac9d726579f43a9443112a47e0241877/ios/MullvadVPN.xcodeproj/project.pbxproj#L440)):*
> ```
> 		7A6B4F592AB8412E00123853 /* TunnelMonitorTimings.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A6B4F582AB8412E00123853 /* TunnelMonitorTimings.swift */; };
> 		7A6F2FA52AFA3CB2006D0856 /* AccountExpiryTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A6F2FA42AFA3CB2006D0856 /* AccountExpiryTests.swift */; };
> 		7A6F2FA72AFBB9AE006D0856 /* AccountExpiry.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A6F2FA62AFBB9AE006D0856 /* AccountExpiry.swift */; };
> ```

You forgot to make `AccountExpiry` part of the `MullvadVPNTests` target, the tests don't compile anymore

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-:-NiofEpF7N2BidPTzHnU:bnfp4nl)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @pronebird and @rablador)

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 440 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391#-NinJkDvCZZyQYxhFrpq:-Nit7v3f5x66kKc0s6vU:buydf68) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d5ed047ac9d726579f43a9443112a47e0241877/ios/MullvadVPN.xcodeproj/project.pbxproj#L440)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You forgot to make `AccountExpiry` part of the `MullvadVPNTests` target, the tests don't compile anymore
</blockquote></details>

Went and fixed it after talking with @rablador since it was the only thing blocking this PR.

**Pull request merged**
