### PR TITLE
Add promise

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR adds Promise implementation with the following features:

1. Promises can be chained to transform the value using `Promise.then`.
2. The state of `Promise` can be observed with `Promise.observe`. The first call to that method also starts the `Promise`'s execution.
2. Promises can either be resolved with value or cancelled. The value can be `Result` itself, so the `Error` is basically not a part of `Promise` but rather a part of `Value` it holds.
3. Promises can be cancelled. Cancelling the downstream promise does not cancel the upstream ones. This is intentional.
4. Promises do not have to be explicitly retained as `PromiseResolver` passed to the promise's body retains the Promise itself.
5. Promise will assert its state upon deallocation to keep track of programmer errors.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932)* status: 0 of 10 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/Promise/Promise.swift, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiLlQ_k-EjHG4pdbQYH:-MiLlQ_k-EjHG4pdbQYI:b-btwfyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/Promise.swift#L12)):*
> ```Swift
> 
> private enum PromiseState<Value> {
>     case pending((PromiseResolver<Value>) -> Void, DispatchQueue?)
> ```

FYI optional `DispatchQueue` on which to execute the given Promise's body.
___
*[ios/MullvadVPN/Promise/Promise.swift, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiLlYJ44fH7anxpvhhS:-MiLlYJ44fH7anxpvhhT:b-fkpkj0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/Promise.swift#L14)):*
> ```Swift
>     case pending((PromiseResolver<Value>) -> Void, DispatchQueue?)
>     case executing
>     case resolved(Value, DispatchQueue?)
> ```

FYI optional `DispatchQueue` on which to deliver the resolved `Value`.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932)* status: 0 of 10 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/Promise/AnyResult.swift, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiLq2-E0wPi-6OOjFu3:-MiLq2-E0wPi-6OOjFu4:b-tc9alx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/AnyResult.swift#L12)):*
> ```Swift
> 
> /// Protocol uniting all Result types.
> protocol AnyResult {
> ```

FYI used exclusively to be able to match the Result type in where clause in extension for `Promise`, see `Promise+Result.swift`

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932)* status: 0 of 10 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/Promise/AnyOptional.swift, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiLqUCw4tCUuYZZzk0t:-MiLqUCw4tCUuYZZzk0u:b1cftz1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/AnyOptional.swift#L12)):*
> ```Swift
> 
> /// Protocol uniting all Optional types.
> protocol AnyOptional {
> ```

FYI used exclusively to be able to match the Optional<T> type in where clause in extension for `Promise`, see `Promise+Optional.swift`

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/Promise/Promise+Optional.swift, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiQ7S3_0l5mmBvnNKZG:-MiQ7S3_0l5mmBvnNKZH:b-fjvw8s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/Promise+Optional.swift#L21)):*
> ```Swift
>     func map<NewValue>(defaultValue: NewValue, transform: @escaping (Value.Wrapped) -> NewValue) -> Promise<NewValue> {
>         return then { value -> NewValue in
>             switch value.asConcreteType() {
> ```

Doesn't there already exist a `map` function on `Optional`. Would something like this work?
```
return value.asConcreteType().map(transform) ?? defaultValue
```
___
*[ios/MullvadVPN/Promise/PromiseCompletion.swift, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiQ4pNmBPNUwamPXD8I:-MiQ4pNn30X6jOuZLJNc:bq720tq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/PromiseCompletion.swift#L45)):*
> ```Swift
>         case (.finished(let lhsValue), .finished(let rhsValue)):
>             return lhsValue == rhsValue
>         case (.cancelled, .cancelled):
> ```

Does this comparison ever make sense to do? I would suggest that this returns `false` to make `==` useful without having to check for cancelled as well. I can't see a situation where you would use `==` to check if their both cancelled.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[ios/MullvadVPN/Promise/Promise+Optional.swift, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiQ7S3_0l5mmBvnNKZG:-MiQWx5r0NEDcPpMhsZu:bkacmhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/Promise+Optional.swift#L21)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Doesn't there already exist a `map` function on `Optional`. Would something like this work?
```
return value.asConcreteType().map(transform) ?? defaultValue
```
</blockquote></details>

Good one! Updated the PR for both `map` and `mapThen`
___
*[ios/MullvadVPN/Promise/PromiseCompletion.swift, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2932#-MiQ4pNmBPNUwamPXD8I:-MiQNDE-DdHNRtAR1SGd:bb8rrdy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7269bbe92979aef29a43f2a4d961ce720b5d8e49/ios/MullvadVPN/Promise/PromiseCompletion.swift#L45)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Does this comparison ever make sense to do? I would suggest that this returns `false` to make `==` useful without having to check for cancelled as well. I can't see a situation where you would use `==` to check if their both cancelled.
</blockquote></details>

It makes sense in tests where we want to make sure that the Promise has finished with a certain result.

```
let a: PromiseCompletion<Int> = myPromise.await()
let b: PromiseCompletion<Int> = .cancelled

XCTAssertEqual(a, b)
```

**Pull request merged**
