### PR TITLE
Fix dialogs padding and spacing

### PR DESCRIPTION
**Pull request by Rawa**
Fixes inconsistencies between different dialogs and aligns it closer to the current design.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 45 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-Ndnn67F6tqM5aHjdExQ:-Ndnn67G0xeZ69d5rbYR:bxkqimb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/854f0c25dcea9d8b2aeb9b7a88b3ede4455e688a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L45)):*
> ```Kotlin
>                 modifier = Modifier.fillMaxWidth(),
>                 verticalArrangement =
>                     Arrangement.spacedBy(dimensionResource(id = R.dimen.small_padding))
> ```

Should use `Dimens.smallPadding` instead.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 152 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-Ndnig9RC__gG8m9m5GQ:-NdowcFK6NfJwgK0J0or:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/827a84c9287705e30487f2f53b360e05dc418f54/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L152)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

If there is just one usage for this just use it directly instead of define variable
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt` line 45 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-Ndnn67F6tqM5aHjdExQ:-NdowadyE11V9kLCw39w:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/854f0c25dcea9d8b2aeb9b7a88b3ede4455e688a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt#L45)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should use `Dimens.smallPadding` instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/QuantumResistanceInfoDialog.kt` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-Ndnjdqg-xSLTbWlg9qw:-NdoweHk3CzUBqbPa7Dy:b-oemhsm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/854f0c25dcea9d8b2aeb9b7a88b3ede4455e688a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/QuantumResistanceInfoDialog.kt#L10)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

make previews scope private. it applies for all previews
</blockquote></details>

Good catch! :+1:

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-:-NdoxnYa2j8EyK0Wnyle:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 2 of 4 files at r3, 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-:-Ndp3dg32_XF2WWYXZgL:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

**Review by sabercodic — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129)* status: all files reviewed, 2 unresolved discussions

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129#-:-Ne2Q4jE5OtHLka1QbU7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Review by Pururun — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
