### PR TITLE
Add DeviceName to Welcome Screen

### PR DESCRIPTION
**Pull request by Rawa**
This commit adds device name to the welcome screen and a InfoDialog to clarify it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt` line 204 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173#-NerbKsq0_qT4j40rCg_:-NerbKsq0_qT4j40rCga:b-qafbi8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/332faa4b86143053c28778d246a330c74d07ff8f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt#L204)):*
> ```Kotlin
>                     )
>                 }
>                 if (showDeviceNameDialog) {
> ```

So this is more future-proofing, but we will add other types of dialoges in this view in the future connected to billing.
How do you envision that would work so that they do not conflict?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt` line 204 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173#-NerbKsq0_qT4j40rCg_:-New9UlC4-gnzeiPYE5O:b5l519o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/332faa4b86143053c28778d246a330c74d07ff8f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt#L204)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So this is more future-proofing, but we will add other types of dialoges in this view in the future connected to billing.
How do you envision that would work so that they do not conflict?
</blockquote></details>

I think later on when we introduce navigation in compose we should have them as navigational paths. Much like you navigate to a screen (or fragment in our case) we should navigate to a dialog.

**Review by Pururun — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt` line 204 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173#-NerbKsq0_qT4j40rCg_:-NewA-EFBAi4yyyjx9PI:brxp9sd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/332faa4b86143053c28778d246a330c74d07ff8f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt#L204)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think later on when we introduce navigation in compose we should have them as navigational paths. Much like you navigate to a screen (or fragment in our case) we should navigate to a dialog.
</blockquote></details>

Sounds good!

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173#-:-NfKXFxCCrXA8-GgtQDQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
