### PR TITLE
Fix all baselined lint issues

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 5 of 19 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

**Review by Pururun — COMMENTED** [review]
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/AndroidManifest.xml` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8aaCbA39DlPK9vV-KG:-O8aaCbA39DlPK9vV-KH:bkvoxw7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/app/src/main/AndroidManifest.xml#L30)):*
> ```XML
>                  android:banner="@mipmap/ic_banner"
>                  android:allowBackup="false"
>                  android:fullBackupContent="@xml/full_back_content"
> ```

Have we made sure we haven't accidentally changed the backup behaviour? We could potentially backup and send sensitive data.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/AndroidManifest.xml` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8aaCbA39DlPK9vV-KG:-O8abnSk0_3v51QFvne7:b-a8ajlr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/app/src/main/AndroidManifest.xml#L30)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Have we made sure we haven't accidentally changed the backup behaviour? We could potentially backup and send sensitive data.
</blockquote></details>

According to the android documentation this should not cause any data transfers. I've explicitly excluded all domains that exists as options to backup.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8HxBzN5f1xS4vatq_R:-O8ac3RW44D05GStIqG6:bf3ndul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/417b001b7ea4d1cf951cae6c564b3016b6abf536/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please add a comment regarding this suppression
</blockquote></details>

Reworked this to get rid of the magic number. Looked at the desktop implementation where the similar code exists but they in actuality never use the months. Also they only show years if it is more than 2, so I fixed that as well.
___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8HxcVl3-5Npz-BXnLh:-O8_d8Na9oLI350xQ_5K:bl6u1u3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/417b001b7ea4d1cf951cae6c564b3016b6abf536/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L77)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please add a comment regarding this suppression
</blockquote></details>

Added comment and referenced a ticket.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Mostly looks good, just a few minor comments to address

> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-:-O8bZug0Awk1Il1w2pYp:b20ky7x)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/res/xml/data_extraction_rules.xml` line 21 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8bYyZW5NQrGdoIPD5h:-O8bYyZW5NQrGdoIPD5i:btrue2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/app/src/main/res/xml/data_extraction_rules.xml#L21)):*
> ```XML
>         <exclude domain="external" />
>     </device-transfer>
> </data-extraction-rules>
> ```

bad eof
___
*[`android/app/src/main/res/xml/full_back_content.xml` line 16 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8bZ0Og6TKSMS14kbXG:-O8bZ0Og6TKSMS14kbXH:btrue2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/app/src/main/res/xml/full_back_content.xml#L16)):*
> ```XML
>     <exclude domain="device_sharedpref" />
>     <exclude domain="device_root" />
> </full-backup-content>
> ```

bad eof
___
*[`android/lib/resource/build.gradle.kts` line 24 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8bZC8TEvracKZnFizG:-O8bZC8TEvracKZnFizH:b-ymqqya) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/lib/resource/build.gradle.kts#L24)):*
> ```Kotlin
>     }
> 
>     lint {
> ```

Is this lint config needed when we use `checkDependencies`?
___
*[`android/lib/resource/src/main/res/values/ic_banner_background.xml` line 4 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8bZS0w6GnqToXcYeWv:-O8bZS0w6GnqToXcYeWw:btrue2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/lib/resource/src/main/res/values/ic_banner_background.xml#L4)):*
> ```XML
> <resources>
>     <color name="ic_banner_background">#192E45</color>
> </resources>
> ```

bad eof
___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt` line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8bZYfm-rVlFM0J94hJ:-O8bZYfm-rVlFM0J94hK:b-w83c6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L78)):*
> ```Kotlin
> 
>     // DROID-1407
>     // Function is to be cleaned up and lint warning to be removed.
> ```

Should it be `lint suppression`?



_Code quote:_
```Kotlin
lint warning 
```

**Review by Pururun — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921)* status: 37 of 57 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/AndroidManifest.xml` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8aaCbA39DlPK9vV-KG:-O8fHMiD4hhZ4d6SSzCQ:b-albw1q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/app/src/main/AndroidManifest.xml#L30)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

According to the android documentation this should not cause any data transfers. I've explicitly excluded all domains that exists as options to backup.
</blockquote></details>

Tested on Android 14 and nothing is backed up :star:

**Review by Pururun — APPROVED** [review]
> Reviewed 20 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921)* status: all files reviewed, 5 unresolved discussions (waiting on @Rawa)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 27 of 27 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-:-O8gRj_KCNRvF7Y4Puzd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/resource/build.gradle.kts` line 24 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6921#-O8bZC8TEvracKZnFizG:-O8gRVgs3jpe4QDliRAA:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc9799ebddfc5d550ec457dffb7b43f2637e479d/android/lib/resource/build.gradle.kts#L24)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

As discussed, we leave them kept, since they are needed.
</blockquote></details>

:thumbsup:

**Pull request merged**
