### PR TITLE
Migrate split tunneling fragment to compose

### PR DESCRIPTION
**Pull request by Pururun**
- Create SplitTunnelingScreen
- Improve SplitTunnelingViewModel
- Improve List compose component

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 11 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 5 of 18 files reviewed, 9 unresolved discussions (waiting on @Pururun)

___
*[`CHANGELOG.md` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVU_d9L7vdK-H45vpiY:-NVU_d9L7vdK-H45vpiZ:b-fdccuo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/CHANGELOG.md#L49)):*
> ```Markdown
> - Change and add text in Content blockers informational dialog.
> - Update advanced settings scrollbar appearance.
> - Migrate split tunneling view to compose
> ```

nit: add dot
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYdKWeDDPksXPHZF56:-NVYdKWeDDPksXPHZF57:bcvc9kl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt#L38)):*
> ```Kotlin
>     onCellClicked: () -> Unit
> ) {
>     Box(
> ```

Are there any reason we don't want to use the `BaseCell`? Can it be be tweaked to support something that it doesn't already?



_Code quote:_
```Kotlin
Box
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYe6Tg2me7GtRbu5Pd:-NVYe6Tg2me7GtRbu5Pe:bi55i1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L193)):*
> ```Kotlin
> const val TYPE_TITLE = 2
> const val TYPE_SWITCH_CELL = 3
> const val TYPE_APPLICATION = 4
> ```

Can you elaborate a bit on why we need these types?



_Code quote:_
```Kotlin
const val TYPE_DESCRIPTION = 1
const val TYPE_TITLE = 2
const val TYPE_SWITCH_CELL = 3
const val TYPE_APPLICATION = 4
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVUaNLL-ki5GbGfGAqy:-NVUaNLL-ki5GbGfGAqz:b-inph9n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt#L7)):*
> ```Kotlin
> sealed interface SplitTunnelingUiState {
>     object Loading : SplitTunnelingUiState
>     data class Data(
> ```

Can this name be clarified a bit?



_Code quote:_
```Kotlin
Data
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYaeoO2zSR6N-npPt3:-NVYaeoO2zSR6N-npPt4:b-55hxxz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L16)):*
> ```Kotlin
>     val cellLeftPadding: Dp = 22.dp,
>     val cellRightPadding: Dp = 16.dp,
>     val iconSize: Dp = 24.dp,
> ```

Can this name be a bit more specific?



_Code quote:_
```Kotlin
iconSize
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYa_qTCCc9CTIALuzQ:-NVYa_qTCCc9CTIALuzR:b-w2ltw1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L17)):*
> ```Kotlin
>     val cellRightPadding: Dp = 16.dp,
>     val iconSize: Dp = 24.dp,
>     val progressSize: Dp = 60.dp
> ```

I suggest: `progressIndicatorSize`



_Code quote:_
```Kotlin
progressSize
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYasKpAKApQXco9diq:-NVYasKpAKApQXco9dir:b-l5r7ug) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt#L27)):*
> ```Kotlin
>                 appsScope.linkTo(serviceConnectionScope)
>             }
>         }
> ```

Can this be removed or migrated to somewhere else? Or would it be better in a separate PR?



_Code quote:_
```Kotlin
    private val scope: Scope =
        getKoin().getOrCreateScope(APPS_SCOPE, named(APPS_SCOPE)).also { appsScope ->
            getKoin().getScopeOrNull(SERVICE_CONNECTION_SCOPE)?.let { serviceConnectionScope ->
                appsScope.linkTo(serviceConnectionScope)
            }
        }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYb9ItCAEfw4xLJmJf:-NVYb9ItCAEfw4xLJmJg:bmsbxho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt#L44)):*
> ```Kotlin
>                         onShowSystemAppsClicked = viewModel::setShowSystemApps,
>                         addToExcluded = viewModel::addToExcluded,
>                         removeFromExcluded = viewModel::removeFromExcluded,
> ```

By looking at how big the constructor argument list of the `AdvancedSettingsScreen` is, I believe it would be better to just provide the VM as an argument to the screen (like we did for some other screens). Any thoughts about doing that?



_Code quote:_
```Kotlin
                        onShowSystemAppsClicked = viewModel::setShowSystemApps,


                        addToExcluded = viewModel::addToExcluded,
                        removeFromExcluded = viewModel::removeFromExcluded,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYiNfyCtUdF4oGBLdq:-NVYiNfz2O_DRiKbiCwl:b-3ddzom) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt#L23)):*
> ```Kotlin
> import org.koin.core.scope.inject
> 
> class ApplicationImageView
> ```

Do we need a custom view? It seems like this view might be doing a bit too much.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 5 of 18 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYdKWeDDPksXPHZF56:-NVYv7CxB8zCW1UYbBoK:b97mu58) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt#L38)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are there any reason we don't want to use the `BaseCell`? Can it be be tweaked to support something that it doesn't already?
</blockquote></details>

It's mostly so what we can use ApplicationImageView.
Will see if I can find a workaround.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYe6Tg2me7GtRbu5Pd:-NVYsZWl9ZggWSPFxBDR:b6hjeln) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L193)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can you elaborate a bit on why we need these types?
</blockquote></details>

It's mostly for performance, it is useful for the lazy column to know if they can reuse components.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVUaNLL-ki5GbGfGAqy:-NVYvlH_BGPZ6fcI3Il_:bgukda5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt#L7)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this name be clarified a bit?
</blockquote></details>

Changed it to `ShowAppList`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYaeoO2zSR6N-npPt3:-NVYtRaiBFDdkMhnQwE4:bc0m1hb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this name be a bit more specific?
</blockquote></details>

Will change it to `listIconSize`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYa_qTCCc9CTIALuzQ:-NVYtIda-PG3rHN7tYIJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest: `progressIndicatorSize`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYasKpAKApQXco9diq:-NVYti4BCDZOrzlwZy5p:b-yn3bpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be removed or migrated to somewhere else? Or would it be better in a separate PR?
</blockquote></details>

I can just revert it to the normal view model injection
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYb9ItCAEfw4xLJmJf:-NVYsiXa-_TOwg5yHcKw:b3qbpnu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt#L44)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

By looking at how big the constructor argument list of the `AdvancedSettingsScreen` is, I believe it would be better to just provide the VM as an argument to the screen (like we did for some other screens). Any thoughts about doing that?
</blockquote></details>

The primary reason for not doing that would be that it kinda makes previews impossible.
I guess you can work around that by providing an interface or something.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYiNfyCtUdF4oGBLdq:-NVYutJIA0bI183E7HVB:b-sep7ws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need a custom view? It seems like this view might be doing a bit too much.
</blockquote></details>

I will see if I can find a better way.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 3 of 7 files at r2, 1 of 1 files at r3, 12 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 17 of 24 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYb9ItCAEfw4xLJmJf:-NVdxPSb81BgCUz1JuDf:baz24fz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SplitTunnelingFragment.kt#L44)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

The primary reason for not doing that would be that it kinda makes previews impossible.
I guess you can work around that by providing an interface or something.
</blockquote></details>

Good point, let's do it like this for now :thumbsup:

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 18 files at r4, 4 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 21 of 28 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYe6Tg2me7GtRbu5Pd:-NVmqa1I3Ra-0H51bQ_t:b-ug1hml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L193)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It's mostly for performance, it is useful for the lazy column to know if they can reuse components.
</blockquote></details>

Alright :thumbsup: Is there any compose best practice in terms of where to place these and what visibility they should have? I usually prefer constants at the top of the file, but I guess this order might make more sense in compose :thinking: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVmsjKo9SHgmJopLGTD:-NVmsjKp06i_m86g8-ae:b-nh9vne) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69930bf5e3f12d6d406ae5cf9f53e9fc2e7e3113/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L77)):*
> ```Kotlin
>     addToExcluded: (packageName: String) -> Unit = {},
>     removeFromExcluded: (packageName: String) -> Unit = {},
>     onBackClick: () -> Unit = {},
> ```

I suggest using the following function names to improve readability and consistency. This applies to the screen and its components as well as the VM.

```
onShowSystemAppsClick
onExcludeAppClick
onIncludeAppClick
onBackClick
```



_Code quote:_
```Kotlin
    onShowSystemAppsClicked: (show: Boolean) -> Unit = {},
    addToExcluded: (packageName: String) -> Unit = {},
    removeFromExcluded: (packageName: String) -> Unit = {},
    onBackClick: () -> Unit = {},
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYiNfyCtUdF4oGBLdq:-NVmrb4y4Eq6_V8_TFCp:b-645od0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt#L23)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I will see if I can find a better way.
</blockquote></details>

Sounds good, otherwise we'll keep this since it's not new (which Reviewable seems to believe...).

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 19 of 28 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVmsjKo9SHgmJopLGTD:-NW1EMpH4ptNTXCaEKqK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69930bf5e3f12d6d406ae5cf9f53e9fc2e7e3113/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L77)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using the following function names to improve readability and consistency. This applies to the screen and its components as well as the VM.

```
onShowSystemAppsClick
onExcludeAppClick
onIncludeAppClick
onBackClick
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYiNfyCtUdF4oGBLdq:-NW1DowsARAx6mUDlvMM:b7lvwfx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Sounds good, otherwise we'll keep this since it's not new (which Reviewable seems to believe...).
</blockquote></details>

I think I found a way, but that would require updating and adding libraries so I think we should just postpone it until later.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 19 of 30 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYe6Tg2me7GtRbu5Pd:-NW6XwipD5OK4QA6mnx4:b-792zfw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L193)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Alright :thumbsup: Is there any compose best practice in terms of where to place these and what visibility they should have? I usually prefer constants at the top of the file, but I guess this order might make more sense in compose :thinking: 
</blockquote></details>

Could not find any official code that even uses content type so I just made my own solution where I moved the types to a separate file. Tell me what you think. :)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, 1 of 18 files at r4, 3 of 4 files at r6, 6 of 6 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt` line 63 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NW6XEnbBlrIxhYT0wLW:-NW6XEnc5q4INOCCTMDo:b2zenmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94da5adad61e13d472e7bb2ed88089763ec6b180/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt#L63)):*
> ```Kotlin
>                 applicationImageView.packageName = packageName ?: ""
>             },
>             onReset = {},
> ```

Should this be empty?



_Code quote:_
```Kotlin
{}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVmsjKo9SHgmJopLGTD:-NW6X-Rw5DwVSzqJYUNr:bjtu3yb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69930bf5e3f12d6d406ae5cf9f53e9fc2e7e3113/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L77)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: would be nice to change the suffix `onShowSystemAppsClicked` -> `onShowSystemAppsClick` to keep it consistent.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 48 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NW6XwUh477MPDbDwyN9:-NW6XwUh477MPDbDwyNA:brkjlqs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94da5adad61e13d472e7bb2ed88089763ec6b180/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L48)):*
> ```Kotlin
>                         listOf(
>                             AppData(
>                                 packageName = "Package C",
> ```

nit: (very minor) would be nice to keep in the same format as packages are expected to have, for example: `my.package.c`



_Code quote:_
```Kotlin
Package C
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NVYiNfyCtUdF4oGBLdq:-NW6WvIy9ZOzPexjqi0F:b-ux0ur8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f13003cab01bdcabbe8e2a69480fd270a09a7af/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/ApplicationImageView.kt#L23)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think I found a way, but that would require updating and adding libraries so I think we should just postpone it until later.
</blockquote></details>

Sounds good :thumbsup: 
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt` line 114 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NW6mkG50cjBWxYAu1Tq:-NW6mkG50cjBWxYAu1Tr:b-t6pp7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bcfb31f6be98a1bd35521ec7813699eec17c824/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L114)):*
> ```Kotlin
> 
>     @Test
>     fun test_remove_app_from_excluded() =
> ```

I suggest renaming to something like: `test_include_app`



_Code quote:_
```Kotlin
test_remove_app_from_excluded
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680)* status: 26 of 32 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt` line 63 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NW6XEnbBlrIxhYT0wLW:-NW711TE4LqcSZeMQ-3R:b-x7736a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94da5adad61e13d472e7bb2ed88089763ec6b180/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt#L63)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should this be empty?
</blockquote></details>

I though that was required, but it was not.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt` line 114 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-NW6mkG50cjBWxYAu1Tq:-NW71CWy3JaZa0LVsf1a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4bcfb31f6be98a1bd35521ec7813699eec17c824/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L114)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to something like: `test_include_app`
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4680#-:-NW7v-6_BRP73kj_3rWS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
