### PR TITLE
Replace third party top bar library

### PR DESCRIPTION
**Pull request by Rawa**
Material 3 has a collapsable toolbar, this PR aim to replace our third party dependency and use the native one.

Before any merge we should also update `verification-metadata.xml` to remove the old dependency.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 5 of 11 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231#-:-Nfyp6XJ6jQGgONvF66S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Rawa** [comment]
This PR also fixes our issue with overlapping header text. I've confirmed with marketing that it is ok for us to show the logo in this way, however they are doing a double check with stakeholder.

Screenshot 2023-10-05 at 10 36 49
Screenshot 2023-10-05 at 10 47 58

**Comment by Rawa** [comment]
All approved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 3 of 10 files at r2, 1 of 2 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 88 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231#-NfzzypM5A4LbAvrLoGL:-NfzzypM5A4LbAvrLoGM:b-xc0twe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a8b4bbf10ddd69a1fccc81ca0f0a6082c0f06320/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L88)):*
> ```Kotlin
> }
> 
> @OptIn(ExperimentalMaterial3Api::class)
> ```

Can this be removed when using `@file:OptIn(ExperimentalMaterial3Api::class)`?



_Code quote:_
```Kotlin
@OptIn(ExperimentalMaterial3Api::class)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 192 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231#-Nfzzn8J6PR1C2Kuzjfo:-Nfzzn8J6PR1C2Kuzjfp:b-xc0twe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a8b4bbf10ddd69a1fccc81ca0f0a6082c0f06320/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L192)):*
> ```Kotlin
> }
> 
> @OptIn(ExperimentalMaterial3Api::class)
> ```

Can this be removed when using `@file:OptIn(ExperimentalMaterial3Api::class)`?



_Code quote:_
```Kotlin
@OptIn(ExperimentalMaterial3Api::class)
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 88 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231#-NfzzypM5A4LbAvrLoGL:-Ng2odHa5nko7XCCVHQP:b-sxkoxv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a8b4bbf10ddd69a1fccc81ca0f0a6082c0f06320/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L88)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be removed when using `@file:OptIn(ExperimentalMaterial3Api::class)`?
</blockquote></details>

Yeah, good catch!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 192 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231#-Nfzzn8J6PR1C2Kuzjfo:-Ng2okY-8Au2dqH3kjAj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a8b4bbf10ddd69a1fccc81ca0f0a6082c0f06320/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L192)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be removed when using `@file:OptIn(ExperimentalMaterial3Api::class)`?
</blockquote></details>

Done.

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

**Review by Rawa — COMMENTED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 1 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5231)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
