### PR TITLE
Clean up dependencies in `talpid-openvpn`

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Some cleanups to dependencies in `talpid-openvpn`. The major one is replacing [duct](https://docs.rs/duct/latest/duct/) with [tokio::process::Command](https://docs.rs/tokio/latest/tokio/process/struct.Command.html) for spawning an OpenVPN process. The minor cleanups make `once_cell` a proper workspace-dependency and replacing the [is_terminal crate](https://docs.rs/is-terminal/latest/is_terminal/) with [std::io::IsTerminal](https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 13 of 17 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-openvpn/src/lib.rs` line 814 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgKpjmG4ay1SFUHyzEO:-NgKpjmG4ay1SFUHyzEP:b-on3mon) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e66cd2e67e19841c5d7cc36a35294b28db419d09/talpid-openvpn/src/lib.rs#L814)):*
> ```XML
> impl ProcessHandle for OpenVpnProcHandle {
>     fn wait(&self) -> io::Result<ExitStatus> {
>         let handle = tokio::runtime::Handle::current();
> ```

Was it not possible to replace this with an async method? Having this many sync-async boundaries is making things messier.
___
*[`talpid-openvpn/src/process/openvpn.rs` line 415 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgKmNw4-cvRclSYfTQ4:-NgKmNw4-cvRclSYfTQ5:bkxqz13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e66cd2e67e19841c5d7cc36a35294b28db419d09/talpid-openvpn/src/process/openvpn.rs#L415)):*
> ```XML
>     fn kill(&self) -> io::Result<()> {
>         log::warn!("Killing OpenVPN process");
>         let rt = tokio::runtime::Builder::new_current_thread()
> ```

Was it not possible to replace this with an async method? Having this many sync-async boundaries is making things messier.

I'm not sure we even need the `StoppableProcess` trait. We're only implementing it on `OpenVpnProcHandle`, so we might as well just add async methods to replace these.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`talpid-openvpn/src/lib.rs` line 814 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgKpjmG4ay1SFUHyzEO:-NgOE7TX8-RWjhc27oBi:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e66cd2e67e19841c5d7cc36a35294b28db419d09/talpid-openvpn/src/lib.rs#L814)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Was it not possible to replace this with an async method? Having this many sync-async boundaries is making things messier.
</blockquote></details>

done
___
*[`talpid-openvpn/src/process/openvpn.rs` line 415 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgKmNw4-cvRclSYfTQ4:-NgOEIA3AGuLcTBXRtvM:bdh1uwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e66cd2e67e19841c5d7cc36a35294b28db419d09/talpid-openvpn/src/process/openvpn.rs#L415)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Was it not possible to replace this with an async method? Having this many sync-async boundaries is making things messier.

I'm not sure we even need the `StoppableProcess` trait. We're only implementing it on `OpenVpnProcHandle`, so we might as well just add async methods to replace these.
</blockquote></details>

done

I didn't touch `StoppableProcess` this time, but I did have to convert it to an `async` trait.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-openvpn/src/process/stoppable_process.rs` line 51 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOO6DMCyXKTU50gA7B:-NgOPQPyAn_PnNiBDu6X:b2v31wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/362f020a12cebc910a1c4f17162ac13328e17681/talpid-openvpn/src/process/stoppable_process.rs#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Use `tokio::time::sleep`. This blocks the runtime.
</blockquote></details>

I'm tunnel visioning a bit here. Can't we use `tokio::time::timeout()` on `Child::wait()` instead of polling?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-openvpn/src/lib.rs` line 489 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOOaEXCKU_VsS26lcb:-NgOPmDF77j8gsjnaI8u:bjl4tc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/362f020a12cebc910a1c4f17162ac13328e17681/talpid-openvpn/src/lib.rs#L489)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'm sure we could make this whole `wait` function async. But I'll not increase the scope of this PR. It's already a big improvement. :)
</blockquote></details>

It would be nice, the `wait` function is overly complicated due to it not being `async`. Maybe due for next cleanup :broom:
___
*[`talpid-openvpn/src/process/openvpn.rs` line 441 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgONYG5C1mxn2qU-TN8:-NgOQ1cYDQuByE5SnWDs:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/362f020a12cebc910a1c4f17162ac13328e17681/talpid-openvpn/src/process/openvpn.rs#L441)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: `Ok(exit_status?.is_some())`
</blockquote></details>

done
___
*[`talpid-openvpn/src/process/stoppable_process.rs` line 51 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOO6DMCyXKTU50gA7B:-NgOY5s18a1AyRcgQxcQ:bi70gyc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/362f020a12cebc910a1c4f17162ac13328e17681/talpid-openvpn/src/process/stoppable_process.rs#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'm tunnel visioning a bit here. Can't we use `tokio::time::timeout()` on `Child::wait()` instead of polling?
</blockquote></details>

`tokio::time::timeout` did the trick :ok_hand:

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-openvpn/src/process/stoppable_process.rs` line 51 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOO6DMCyXKTU50gA7B:-NgOhGxs2F9sB_PAK3-B:b4j1vuv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/362f020a12cebc910a1c4f17162ac13328e17681/talpid-openvpn/src/process/stoppable_process.rs#L51)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

`tokio::time::timeout` did the trick :ok_hand:
</blockquote></details>

I think this won't work. `has_stopped` will return immediately. It won't actually wait for the child process to stop. We need to use `timeout` on `wait`, if possible.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-openvpn/src/process/stoppable_process.rs` line 51 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOO6DMCyXKTU50gA7B:-NgOprYC0IJFKBLHCg55:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/362f020a12cebc910a1c4f17162ac13328e17681/talpid-openvpn/src/process/stoppable_process.rs#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think this won't work. `has_stopped` will return immediately. It won't actually wait for the child process to stop. We need to use `timeout` on `wait`, if possible.
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-openvpn/src/lib.rs` line 812 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOyB7xCK0nYuq66RIq:-NgOyB7xCK0nYuq66RIr:bex1cdz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15f255f74d390b4d18c1b4bf8a81ccbcd77de141/talpid-openvpn/src/lib.rs#L812)):*
> ```XML
> impl ProcessHandle for OpenVpnProcHandle {
>     async fn wait(&self) -> io::Result<ExitStatus> {
>         crate::process::stoppable_process::StoppableProcess::wait(self).await
> ```

How about just adding a `wait()` method on `OpenVpnProcHandle` directly and calling that?

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: 16 of 20 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`talpid-openvpn/src/lib.rs` line 812 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245#-NgOyB7xCK0nYuq66RIq:-NgTPe9H7ZL1QJWfeDD0:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15f255f74d390b4d18c1b4bf8a81ccbcd77de141/talpid-openvpn/src/lib.rs#L812)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

How about just adding a `wait()` method on `OpenVpnProcHandle` directly and calling that?
</blockquote></details>

done

**Review by dlon — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5245)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by MarkusPettersson98** [comment]
Ready to be merged, since e201d1a7682e73bf852787d4068b7bca5e9386be and f88689df68501a28f75101cdf8582fe3dfac3e5a was merged to main

**Pull request merged**
