### PR TITLE
Block OpenVPN relays from being selected on android

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574#-Nl8wI0I2wTzQqpqw8hV:-Nl8wI0I2wTzQqpqw8hW:b-zbj9pf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e820fa592071dd6b8eba49d038adf14ef4d86a52/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L67)):*
> ```Kotlin
>         // Fix tunnel protocol being set to any
>         getSettings()?.relaySettings?.let { relaySettings ->
>             if (relaySettings is RelaySettings.Normal) {
> ```

We should scope it as limited as possible I feel like::
`relaySettings is RelaySettings.Normal && relaySettings.tunnelType != Constraint.Only(TunnelType.Wireguard)`

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574#-Nl8wI0I2wTzQqpqw8hV:-Nl8wni89tVmTixdN9zH:belq9pw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e820fa592071dd6b8eba49d038adf14ef4d86a52/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L67)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should scope it as limited as possible I feel like::
`relaySettings is RelaySettings.Normal && relaySettings.tunnelType != Constraint.Only(TunnelType.Wireguard)`
</blockquote></details>

Also if this is approved we should reference some issue that has a due date to remove this.

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574#-:-NlO0k1q34DMiD814_It:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574#-:-NlOB8U4DT0_FmTphy18:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
