### PR TITLE
Update our dependencies

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR bumps the versions of `NSEventMonitor` and `windows-security` packages to the latest. Both packages received security updates last week.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/191)

### CODE REVIEW

**Comment by pinkisemils** [comment]
Looks OK, but I've not tested these changes just yet!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/191#-:-LDb-eqz5yJKfrbZVr4U:b-q56gm4)*

**Comment by pronebird** [comment]
OK. Visually there are no changes except that we use newer node-pre-gyp internally in nseventmonitor and windows-security. So it should successfully pull the prebuilt binaries as usual.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/191#-:-LDbZ_TI48KllmQYQ4j8:bvw1nl9)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/191)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/191)*

**Pull request merged**
