### PR TITLE
Update icons and logos

### PR DESCRIPTION
**Pull request by faern**
I took the new SVGs from our source of truth logo collection and added them to git and ran the scripts for generating various assets. Some of this was very messy. So I (together with Matilda, Albin and Oskar) cleaned up a bit, renamed some icons and improved documentation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)

### CODE REVIEW

**Comment by albin-mullvad** [comment]
As you say, we'll have to investigate why some sizes are different and why some monochrome icons are inverted :thinking: 

Also, keep in mind that the `generate-pngs.sh` script was moved in #4293

**Comment by raksooo** [comment]
I've now updated the macOS icons in `/graphics/macOS/` and ran `gui/scripts/build-logo-icons.sh`.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 16 of 28 files at r1, 11 of 32 files at r3, 12 of 18 files at r4, 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: 40 of 52 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMhNQVEDiO8Iox-Bcub):*
Moved to `./android/scripts/generate-pngs.sh`



_Code quote:_
```
./android/generate-pngs.sh
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 32 files at r3, 6 of 18 files at r4, 4 of 5 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`ios/README.md` line 110 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMi5EUG9oX-GIGZ5l2d:-NMi5EUG9oX-GIGZ5l2e:bbu2qpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/392e6962843e150a6230745758ee9bf4cd1fb66d/ios/README.md#L110)):*
> ```Markdown
> ## Icons and assets
> 
> For a general overview of icons and graphics read [the graphics readme](../graphics/README.md).
> ```

Might be a good idea to add a similar section to `android/README.md`



_Code quote:_
```Markdown
## Icons and assets

For a general overview of icons and graphics read [the graphics readme](../graphics/README.md).
```
___
*[`ios/README.md` line 117 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMi6PEkEx-ODZzVXk2M:-NMi6PEkEx-ODZzVXk2N:b-rgrx97) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/392e6962843e150a6230745758ee9bf4cd1fb66d/ios/README.md#L117)):*
>No newline at end of file



_Code quote:_
```Markdown
```
```


<!-- Sent from Reviewable.io -->

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMhNQVEDiO8Iox-Bcub):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Moved to `./android/scripts/generate-pngs.sh`
</blockquote></details>

Done.
___
*[`ios/README.md` line 110 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMi5EUG9oX-GIGZ5l2d:-NMiA7ahEn4S4dyOOBUx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/392e6962843e150a6230745758ee9bf4cd1fb66d/ios/README.md#L110)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Might be a good idea to add a similar section to `android/README.md`
</blockquote></details>

Done.
___
*[`ios/README.md` line 117 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMi6PEkEx-ODZzVXk2M:-NMiI1PR28agex3fJKrC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/392e6962843e150a6230745758ee9bf4cd1fb66d/ios/README.md#L117)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

>No newline at end of file
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 26 files at r7, 16 of 16 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-:-NMiMZoT6ShDurX96xOC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-:-NMmD7nCBD2U71qpzO3p:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`graphics/README.md` line 55 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMmE7bN8W0tV6oTCJB-:-NMmE7bN8W0tV6oTCJB0:bz5vqd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/359ce59fb99ec422eadbfff4a1d7990fb99edf16/graphics/README.md#L55)):*
> ```Markdown
> ```
> 
> ### `icon-android.svg` & `icon-android-mono.svg`
> ```

FYI That feels like it should be under Android section.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`graphics/README.md` line 64 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMmEET29unzKYihdmNO:-NMmEET29unzKYihdmNP:b-uil5rq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/359ce59fb99ec422eadbfff4a1d7990fb99edf16/graphics/README.md#L64)):*
> ```Markdown
> `icon-android-mono.svg` is the monochromatic version. It's used as "themed icons" on Android.
> 
> ### `icon-shaved.svg`
> ```

FYI now that's a good mention. We may need this on iOS down the road in system menus etc.. where icons are pretty small.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`graphics/README.md` line 55 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMmE7bN8W0tV6oTCJB-:-NMn5hdjE-8kJOUN3H-f:bkjsrf8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/359ce59fb99ec422eadbfff4a1d7990fb99edf16/graphics/README.md#L55)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI That feels like it should be under Android section.
</blockquote></details>

I believe the formatting is correct atm :thinking:  The idea is for the icon names to be higher level headings (fewer `#`) than the platform headings.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`graphics/README.md` line 64 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4292#-NMmEET29unzKYihdmNO:-NMn6wC-DvXScWmXxYff:bkwmtnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/359ce59fb99ec422eadbfff4a1d7990fb99edf16/graphics/README.md#L64)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI now that's a good mention. We may need this on iOS down the road in system menus etc.. where icons are pretty small.
</blockquote></details>

We'll add it when we use it then.

**Pull request merged**
