### PR TITLE
Update connection details on main view to indicate that DAITA is used

### PR DESCRIPTION
**Pull request by rablador**
When DAITA is being used, the main view should indicate as much. 

The main view should be updated to follow desktop and add extra text to the relay line to indicate if DAITA is being used. For now, multihop and singlehop cases shouldn't be differentiated.

Whether DAITA is used or not should be inferred from the communication between the client and the packet tunnel.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)

### CODE REVIEW

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)* status: 0 of 56 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719#-O5qqNUw-ARxebliJsj3:-O5qqNUw-ARxebliJsj4:b-rurijo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e31698e289aa505b2451666041e40e5f4107490e/ios/MullvadVPN/View%20controllers/Tunnel/TunnelControlView.swift#L239)):*
> ```Swift
> 
>             if observedState.connectionState?.isDaitaEnabled == true {
>                 connectedRelayName += " using DAITA"
> ```

Should we use localised strings here ?
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719#-O5qq9ph4a73oVJDK91B:-O5qq9ph4a73oVJDK91C:b-ukwdaf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e31698e289aa505b2451666041e40e5f4107490e/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L18)):*
> ```
>       "location" : "https://github.com/mullvad/wireguard-apple.git",
>       "state" : {
>         "revision" : "fb9a34f15e47b167866af3257a8dcc9901d9e7c1"
> ```

Please remove this change

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)* status: 0 of 56 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719#-O5qqNUw-ARxebliJsj3:-O5qqVzr0Je02dX0RZ2c:b5r252w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e31698e289aa505b2451666041e40e5f4107490e/ios/MullvadVPN/View%20controllers/Tunnel/TunnelControlView.swift#L239)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Should we use localised strings here ?
</blockquote></details>

Or rather, I think this should be the localised string instead of setting it below, since those work with lookup tables, we'd need a different localised string for every possible "relay name +  using daita" combination, if you see what I mean

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)* status: 0 of 56 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719#-O5qqNUw-ARxebliJsj3:-O5rPcjX3NZYxhvh2kqd:bjto2lq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e31698e289aa505b2451666041e40e5f4107490e/ios/MullvadVPN/View%20controllers/Tunnel/TunnelControlView.swift#L239)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Or rather, I think this should be the localised string instead of setting it below, since those work with lookup tables, we'd need a different localised string for every possible "relay name +  using daita" combination, if you see what I mean
</blockquote></details>

I see indeed, however, we should come up with something more clever than simply adding the strings as they are. On desktop, the Swedish translation is grammatically wrong since it's directly translated. 😕

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)* status: 0 of 56 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719#-O5qq9ph4a73oVJDK91B:-O61Tln482KdN8xWNlxN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e31698e289aa505b2451666041e40e5f4107490e/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please remove this change
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 56 of 56 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
