### PR TITLE
Platform specific newlines in log file

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)

### CODE REVIEW

**Comment by mvd-ows** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[mullvad-daemon/src/logging.rs, line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBUmmLI0KxFIj-qE5ye:-LBUmmLI0KxFIj-qE5yf:b-tooabj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a869b8e61cb52500bd1f6bd46c059c1573907d12/mullvad-daemon/src/logging.rs#L80)):*
> ```Rust
>         let file_dispatcher = fern::Dispatch::new()
>             .format(move |out, message, record| file_formatter.output_msg(out, message, record))
>             .chain(Output::file(f, LINE_SEPARATOR));
> ```

What if `f` has embedded new lines? Is that likely to occur?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mullvad-daemon/src/logging.rs, line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBUmmLI0KxFIj-qE5ye:-LBVCmZd0DbTyw9hIJ42:b-1rsd29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a869b8e61cb52500bd1f6bd46c059c1573907d12/mullvad-daemon/src/logging.rs#L80)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What if `f` has embedded new lines? Is that likely to occur?
</blockquote></details>

I assume you meant if `message` has embedded newlines?

It's possible, because someone can do `debug!("First line\nSecond line")`. It's not a complex fix, but it seems like a rare event, and the fix leads to an extra run-time cost: traversing the message and allocating a new message. So I'm not sure if this should be included :/

Any opinions on this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mullvad-daemon/src/logging.rs, line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBUmmLI0KxFIj-qE5ye:-LBVtQ9B5kUzTfSbofk1:b-poee6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a869b8e61cb52500bd1f6bd46c059c1573907d12/mullvad-daemon/src/logging.rs#L80)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I would much prefer if we can keep the code you have suggested here. It's just that I recall @faern saying something about deliberatly using embedded `\n` to avoid breaking up multiline log events.
</blockquote></details>

We have many log entries with newlines in the message itself, yes. So we need to process the messages like this. But would be nicer if it was done more at compile time, and reduce the amount of code directly in this closure. Something like

```rust
.format(move |out, message, record| {
    let message = escape_newline(message);
    ...
}

#[cfg(not(windows))]
fn escape_newline(message: String) -> String {
    message
}

#[cfg(windows)]
fn escape_newline(message: String) -> String {
    message.replace("\n", LINE_SEPARATOR)
}
```

---

*[mullvad-daemon/src/bin/problem-report.rs, line 274 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBVw7Vg0ajmscbcEnwf:-LBVw7Vg0ajmscbcEnwg:boffqvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a869b8e61cb52500bd1f6bd46c059c1573907d12/mullvad-daemon/src/bin/problem-report.rs#L274)):*
> ```Rust
> impl fmt::Display for ProblemReport {
>     fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
>         write_line!(fmt, "System information:")?;
> ```

I don't think the line endings should affect the `Display` implementation of any type. Would be very messy if some Rust types have one line ending and some others another. The line ending conversion should be done as close as possible to the writing to the file IMO.

We should also make sure to convert all line endings to `\n` before we send the report to our RPC endpoint as well. So that all problem reports end up with the same format on the server.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Comment by jvff** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-daemon/src/logging.rs, line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBUmmLI0KxFIj-qE5ye:-LBbRmjcCL1OuQAgJ0Ps:b-e3czp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a869b8e61cb52500bd1f6bd46c059c1573907d12/mullvad-daemon/src/logging.rs#L80)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We have many log entries with newlines in the message itself, yes. So we need to process the messages like this. But would be nicer if it was done more at compile time, and reduce the amount of code directly in this closure. Something like

```rust
.format(move |out, message, record| {
    let message = escape_newline(message);
    ...
}

#[cfg(not(windows))]
fn escape_newline(message: String) -> String {
    message
}

#[cfg(windows)]
fn escape_newline(message: String) -> String {
    message.replace("\n", LINE_SEPARATOR)
}
```
</blockquote></details>

Done, but I realized I pushed an early attempt at replacing newlines inside log messages. The attempt didn't actually work. Sorry about that :/

This version works, but there's a runtime cost to it (and an extra allocation).

---

*[mullvad-daemon/src/bin/problem-report.rs, line 274 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBVw7Vg0ajmscbcEnwf:-LBbScVwADTVf4H8_B4r:brl0to9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a869b8e61cb52500bd1f6bd46c059c1573907d12/mullvad-daemon/src/bin/problem-report.rs#L274)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think the line endings should affect the `Display` implementation of any type. Would be very messy if some Rust types have one line ending and some others another. The line ending conversion should be done as close as possible to the writing to the file IMO.

We should also make sure to convert all line endings to `\n` before we send the report to our RPC endpoint as well. So that all problem reports end up with the same format on the server.
</blockquote></details>

Done, but probably not the way you expected. I removed the `Display` implementation because it prints the file contents as is, and with this PR it means that it will probably pick-up inconsistent newlines from the log files. I opted to create a new method that at least doesn't give the impression that it has consistent behavior with other types. What do you think?

---

*[mullvad-daemon/src/bin/problem-report.rs, line 404 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148#-LBcqmbq7F0BkRr3SvW9:-LBcqmbq7F0BkRr3SvWA:b-e0ep16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f4183da245455009b2cb6ee0bd4d75b481116252/mullvad-daemon/src/bin/problem-report.rs#L404)):*
> ```Rust
> 
> #[cfg(not(windows))]
> fn normalize_newlines(text: String) -> String {
> ```

I'm not sure if this function should be platform specific. We'll probably rarely (if ever) get `CRLF` in other platforms, but maybe we should normalize them just in case?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Comment by pinkisemils** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)*

**Pull request merged**
