### PR TITLE
Apply multi-hop settings into tunnel

### PR DESCRIPTION
**Pull request by mojganii**
This PR enables multi-hop tunneling support in Swift.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/Relay/RelaySelectorWrapper.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kjcHYEWFZUJTY4p20:-O-kjcHYEWFZUJTY4p21:ba9kkjt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadREST/Relay/RelaySelectorWrapper.swift#L56)):*
> ```Swift
>     private func addObserver() {
>         self.observer = MultihopObserverBlock(didUpdateMultihop: { [weak self] _, multihopState in
>             // Discard applying multi-hop settings until it's under development
> ```

We already have a debug check for the settings switch, right? Should be enough.
___
*[`ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kjh9x3QKq-kUTfsNx:-O-kjh9y715CaF_1CyC-:ba9kkjt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift#L56)):*
> ```Swift
>         // The multihop state gets updated a lot when observing the tunnel, clear the cache if the multihop settings have changed.
>         self.observer = MultihopObserverBlock(didUpdateMultihop: { [weak self] _, newMultihopState in
>             // Discard applying multi-hop settings until it's under development
> ```

We already have a debug check for the settings switch, right? Should be enough.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 187 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kkfvv5ZZ0hJK9ykeg:-O-kkfvv5ZZ0hJK9ykeh:b-sy8a8z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ba31ffd89c0abace0f5390e336ad31d3bc72b2d/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L187)):*
> ```Swift
>                         "TUNNEL_STATE_PQ_CONNECTED_ACCESSIBILITY_LABEL",
>                         tableName: "Main",
>                         value: "Quantum secure connection. Connected to %@, %@",
> ```

Aren't we changing these too?
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kl8_ODPf4mLJWr3vQ:-O-kl8_ODPf4mLJWr3vR:b-witi0q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift#L37)):*
> ```Swift
>             multihopUpdater: multihopUpdater
>         )
>         multihopStateListener.onNewMultihop?(.off)
> ```

Duplicate
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-klTFJ3yAzB5vNJrPk:-O-klTFJ3yAzB5vNJrPl:b6fm3ri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L89)):*
> ```Swift
>             newSettings: updatedSettings
>         ))
>     }
> ```

Perhaps we should add a test case where there should be no reconnect as well.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: 0 of 278 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 187 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kkfvv5ZZ0hJK9ykeg:-O0F1XK0CgQFUw927qzF:b-8itstk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ba31ffd89c0abace0f5390e336ad31d3bc72b2d/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L187)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Aren't we changing these too?
</blockquote></details>

As I've seen in desktop app, this always shows exit country and city.
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kl8_ODPf4mLJWr3vQ:-O0F1qczBR7HwjtwP4lP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift#L37)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Duplicate
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-klTFJ3yAzB5vNJrPk:-O0F3NHE1kyAuy20AKD_:b-h8ghsh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L89)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Perhaps we should add a test case where there should be no reconnect as well.
</blockquote></details>

The test covers the scenario where any changes in settings occur. Based on the `TunnelSettingsStrategy`, it decides whether to reconnect to new relays or not. For example, if the change is related to `relayConstraints` or `multihop`, it triggers a reconnect to the new relays. However, if the change happens  to `obfuscater`, it retains the current relays. The test covers all properties.
___
*[`ios/MullvadREST/Relay/RelaySelectorWrapper.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kjcHYEWFZUJTY4p20:-O0F29ic0OXfpFHcpWlm:b5u7kl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadREST/Relay/RelaySelectorWrapper.swift#L56)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We already have a debug check for the settings switch, right? Should be enough.
</blockquote></details>

now we are importing the commit which contains `go` side.I remove that to make the test easier.
___
*[`ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-kjh9x3QKq-kUTfsNx:-O0F2Rky3I7BPITpc9tL:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift#L56)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We already have a debug check for the settings switch, right? Should be enough.
</blockquote></details>

Removed

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 33 of 53 files at r3, 245 of 245 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

___
*[`ios/build-wireguard-go.sh` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_BtED3-r9hj0_4ZT:-O0I_BtED3-r9hj0_4ZU:b8qf2mi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/build-wireguard-go.sh#L15)):*
> ```Shell
> ACTION=$1
> 
> export PATH="/opt/homebrew/opt/go@1.20/bin:$PATH"
> ```

This should not be added in this PR I think.
___
*[`ios/MullvadVPN/TunnelManager/Tunnel+Settings.swift` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_eJ59VP-QrgyOKG8:-O0I_eJ59VP-QrgyOKG9:b-okydff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN/TunnelManager/Tunnel%2BSettings.swift#L26)):*
> ```Swift
>         switch (oldSettings, newSettings) {
>         case let (old, new) where old.relayConstraints != new.relayConstraints:
>             logger?.debug("Relay address changed from \(old.relayConstraints) to \(new.relayConstraints)")
> ```

Do we need these logs? They're good when developing to see that it works, but we also have tests for this.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 489 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0Im0v72PTFFjsYtJKO:-O0Im0v72PTFFjsYtJKP:bi06f3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN.xcodeproj/project.pbxproj#L489)):*
> ```
> 		7A3353972AAA0F8600F0A71C /* OperationBlockObserverSupport.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A3353962AAA0F8600F0A71C /* OperationBlockObserverSupport.swift */; };
> 		7A3AD5012C1068A800E9AD90 /* RelayPicking.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A3AD5002C1068A800E9AD90 /* RelayPicking.swift */; };
> 		7A3EFAAB2BDFDAE800318736 /* (null) in Sources */ = {isa = PBXBuildFile; };
> ```

These nulls seem weird.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 5936 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0Im7R2EymRqApxZDre:-O0Im7R2EymRqApxZDrf:bb7lkwc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN.xcodeproj/project.pbxproj#L5936)):*
> ```
> 				58B26E242943520C00D5980C /* NotificationProviderProtocol.swift in Sources */,
> 				5877F94E2A0A59AA0052D9E9 /* NotificationResponse.swift in Sources */,
> 				7AE2414A2C20682B0076CE33 /* (null) in Sources */,
> ```

null
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 2 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0Im9ID-RXCTforQhlR:-O0Im9ID-RXCTforQhlS:b3qn4i3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L2)):*
> ```
> {
>   "originHash" : "c15149b2d59d9e9c72375f65339c04f41a19943e1117e682df27fc9f943fdc56",
> ```

This file should not change.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-klTFJ3yAzB5vNJrPk:-O0ImMF0Af8dwrhBF5zq:b93zaz8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L89)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

The test covers the scenario where any changes in settings occur. Based on the `TunnelSettingsStrategy`, it decides whether to reconnect to new relays or not. For example, if the change is related to `relayConstraints` or `multihop`, it triggers a reconnect to the new relays. However, if the change happens  to `obfuscater`, it retains the current relays. The test covers all properties.
</blockquote></details>

Yes, I was only thinking that an inverted test could be good as well. To make sure that the strategy does not trigger a reconnect if nothing changes.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: all files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/build-wireguard-go.sh` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_BtED3-r9hj0_4ZT:-O0Ir0vi33iyZmAytjQo:b8gr4r1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/build-wireguard-go.sh#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This should not be added in this PR I think.
</blockquote></details>

the app doesn't get built without this line.
___
*[`ios/MullvadVPN/TunnelManager/Tunnel+Settings.swift` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_eJ59VP-QrgyOKG8:-O0IscYI6JddX2vP3eJN:b-t0mg44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN/TunnelManager/Tunnel%2BSettings.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Do we need these logs? They're good when developing to see that it works, but we also have tests for this.
</blockquote></details>

I doubt wether it's needed or not.but it gives information to us when reconnecting is using the new relays or not.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 489 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0Im0v72PTFFjsYtJKO:-O0It8WI49jwccGyVqnu:b6l0bws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN.xcodeproj/project.pbxproj#L489)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

These nulls seem weird.
</blockquote></details>

I've not seen that! Xcode made it. good catch!
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 5936 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0Im7R2EymRqApxZDre:-O0Iu6Ci4g3cAzQxL-1M:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN.xcodeproj/project.pbxproj#L5936)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

null
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 2 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0Im9ID-RXCTforQhlR:-O0Iu9uICeDTtvwFuBS7:brg4qpj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L2)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This file should not change.
</blockquote></details>

It shouldn't have been updated.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-klTFJ3yAzB5vNJrPk:-O0IuMnq3v_w31fIsjA4:b535m4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L89)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Yes, I was only thinking that an inverted test could be good as well. To make sure that the strategy does not trigger a reconnect if nothing changes.
</blockquote></details>

When settings changes occur, reconnection happens regardless of whether `oldSettings` and `newSettings` are the same. If we decide to reconnect only when the old and new settings are different, then we need to cover the test case you mentioned. However, the current behavior of the app is to reconnect whenever settings are updated, even if the values are repetitive.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: 276 of 278 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/build-wireguard-go.sh` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_BtED3-r9hj0_4ZT:-O0J1uSeDfi3TXuMZjme:b-k8wg14) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/build-wireguard-go.sh#L15)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the app doesn't get built without this line.
</blockquote></details>

let's remove that when `main` was updated.

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/build-wireguard-go.sh` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_BtED3-r9hj0_4ZT:-O0J4YZOAfT3NDV1al5U:bu9g9t4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/build-wireguard-go.sh#L15)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's remove that when `main` was updated.
</blockquote></details>

Are you sure? Main doesn't need go 1.20 now. I had problems on main earlier today, but that was because I had caches from when we tried to get the new wireguardkit updates to work. Cleaning derived data fixed it.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-klTFJ3yAzB5vNJrPk:-O0J3cZbEXCTP1SIWpT4:b9ll6b2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L89)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

When settings changes occur, reconnection happens regardless of whether `oldSettings` and `newSettings` are the same. If we decide to reconnect only when the old and new settings are different, then we need to cover the test case you mentioned. However, the current behavior of the app is to reconnect whenever settings are updated, even if the values are repetitive.
</blockquote></details>

The reconnection happens, but not selecting a new relay, every time, right? Isn't that what the tunnel strategy tries to determine? Let's say there's something wrong in the code in `shouldReconnectToNewRelay`, then we could end up with selecting a new relay every time even though neither multihop nor relay constraints have changed.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: 274 of 278 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O-klTFJ3yAzB5vNJrPk:-O0JF2zH1gCQn3rBsqnv:b32w1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29819dce0925aaf29ebf36b4bb080aa3eb3c7369/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L89)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The reconnection happens, but not selecting a new relay, every time, right? Isn't that what the tunnel strategy tries to determine? Let's say there's something wrong in the code in `shouldReconnectToNewRelay`, then we could end up with selecting a new relay every time even though neither multihop nor relay constraints have changed.
</blockquote></details>

Ok
___
*[`ios/build-wireguard-go.sh` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378#-O0I_BtED3-r9hj0_4ZT:-O0JJoJm04OxgHLYN_x_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56389e45d7e0a0be4b6181a2ad2919f164680b2c/ios/build-wireguard-go.sh#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Are you sure? Main doesn't need go 1.20 now. I had problems on main earlier today, but that was because I had caches from when we tried to get the new wireguardkit updates to work. Cleaning derived data fixed it.
</blockquote></details>

Done.

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
