### PR TITLE
Expose mullvad-api to iOS UI tests

### PR DESCRIPTION
**Pull request by pinkisemils**
This is a small change to `mullvad-api` to expose an FFI that can be consumed by Rust. As such, I expect the reviewers to review their respective half of the changes - @dlon  and @MarkusPettersson98 can review the Rust changes, and @buggmagnet and @niklasberglund should be reviewing the Swift changes.

 I expect that this will not be ideal Swift code and it'll be somewhat clunky FFI code for Rust, do not be gentle.  

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 9 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 10 of 15 files reviewed, 11 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-api/build.rs` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4GQhQAyuC5_YboLs5:-Nq4GQhQAyuC5_YboLs6:b-tl0ny9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/build.rs#L10)):*
> ```XML
>         .generate()
>         .expect("failed to generate bindings")
>         .write_to_file("include/mullvad-api.h");
> ```

For consistency with how we do this elsewhere, I think the generated header should be committed/versioned.
___
*[`mullvad-api/build.rs` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq2epNe-s7LQPtMzu-c:-Nq2epNe-s7LQPtMzu-d:bj6v3d5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/build.rs#L13)):*
> ```XML
> }
> 
> #[cfg(not(any(target_os = "macos", target_os = "ios")))]
> ```

Maybe we do not need to generate the header when the target is macOS, since we do not need this on desktop? Or could this perhaps be guarded by some `ffi` feature instead?
___
*[`mullvad-api/build.rs` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq452wZ6BoPQaI-_hIi:-Nq452wZ6BoPQaI-_hIj:b37k7cp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/build.rs#L13)):*
> ```XML
> }
> 
> #[cfg(not(any(target_os = "macos", target_os = "ios")))]
> ```

I guess it would be fine for `ios-ffi` to live in `mullvad_api::ffi`? It's just a C API for `mullvad-api`. Nothing iOS-specific about it.
___
*[`mullvad-api/Cargo.toml` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq2fFf_34XPiitf9Cxk:-Nq2fFfa1wRcaC9PbJbb:b-3wgtn2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/Cargo.toml#L42)):*
> ```TOML
> 
> [target.'cfg(target_os = "macos")'.build-dependencies]
> cbindgen = { version = "0.24.3", default-features = false }
> ```

Should this not be a dependency for (and only for) `ios`?
___
*[`mullvad-api/src/ios_ffi/device.rs` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq40Xc1-htg-IkrbuYb:-Nq40Xc1-htg-IkrbuYc:bcq5vrp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/device.rs#L48)):*
> ```XML
>     fn from(dev: Device) -> Self {
>         let name_bytes = dev.name.clone().into_bytes().into_boxed_slice();
>         let name_len = name_bytes.len();
> ```

How do you feel about just appending a nul terminator to `name_bytes` and getting rid of the length? Would make it *slightly* more convenient to construct the string in Swift: https://developer.apple.com/documentation/swift/string/init(cstring:)-2p84k
___
*[`mullvad-api/src/ios_ffi/device.rs` line 50 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4-2PiCSCtg8gzBh8i:-Nq4-2PiCSCtg8gzBh8j:bk4qgya) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/device.rs#L50)):*
> ```XML
>         let name_len = name_bytes.len();
>         let name_ptr = name_bytes.as_ptr();
>         let name_backing_ptr = Box::into_raw(name_bytes) as *mut _;
> ```

How about calling `Box::into_raw`/`Box::from_raw` directly on `name_ptr` and removing the "backing" pointer? These pointers are identical.
___
*[`mullvad-api/src/ios_ffi/error.rs` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4CE2P3QnOGfMtYDeU:-Nq4CE2P3QnOGfMtYDeV:bdfwndq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/error.rs#L16)):*
> ```XML
> 
> /// MullvadApiErrorKind contains a description and an error kind. If the error kind is
> /// `MullvadApiErrorKind` is NoError, the pointer will be nil.
> ```

This seems wrong. `description` is not a null pointer in the `NoError` case, but rather a pointer to an empty string?
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq43cASD9kKMebVt2ZE:-Nq43cASD9kKMebVt2ZF:bxzi05v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L12)):*
> a thread-safe to

Missing a word or two.
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4HbUY8G2-Zk2-y_vq:-Nq4HbUY8G2-Zk2-y_vr:b-d5sm1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L27)):*
> ```XML
>     }
> 
>     unsafe fn from_raw(self) -> Arc<IosApiClientContext> {
> ```

Couldn't all of the functions (except the init function) just take in a `*const IosApiClientContext` and convert it to `&IosApiClientContext` instead of doing this dance? Also, instead of using `Arc`, just have the freeing function call `Box::from_raw` on it.

Using `Box::from_raw` instead of `Arc` should be possible either way.
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 69 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4LgEi90m5AIteMP2W:-Nq4LgEi90m5AIteMP2X:b9oaew8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L69)):*
> ```XML
> /// `api_address_len`: size of the API address string
> #[no_mangle]
> pub extern "C" fn mullvad_api_initialize_api_runtime(
> ```

Should all of the `mullvad_api_*` functions be labeled `unsafe`?
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq49XQF303TfErgDMWo:-Nq49XQF303TfErgDMWp:b-i9cg5m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L77)):*
> ```XML
> ) -> MullvadApiError {
>     let Some(addr_str) = (unsafe { string_from_raw_ptr(api_address_ptr, api_address_len) }) else {
>         return MullvadApiError::with_str(
> ```

It might be more ergonomic (and result in fewer `let-else` and `match` expressions) to write inner functions that return `Result`s, and have the results converted back into `MullvadApiError`s in the public C functions that wrap them.
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 351 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4LWow5lDbXwLjn_-9:-Nq4B3WH7TkDc3iM__2X:bleerkn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L351)):*
> ```XML
> 
> #[no_mangle]
> pub extern "C" fn mullvad_api_error_drop(error: MullvadApiError) {
> ```

Forcing the caller to deallocate errors feels wrong. Since all of the strings are constants, could you not just define static variables and use `CStr`/`&[u8]`? Or even `b"Failed to parse account number\0".as_ptr()`.

**Review by buggmagnet — APPROVED** [review]
In general the API looks fine, but I think there's too much Rust<->Swift  data conversion that could be simplified, by introducing a String type in rust that has a C buffer and a size, which we could then convert in Swift

> Reviewed 1 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-:-Nq7Hygn9sYH3FkMpfQd:bqzvq3f)* status: 10 of 15 files reviewed, 15 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1191 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq302px7jeLvG_y0j2b:-Nq302px7jeLvG_y0j2c:b35vyqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPN.xcodeproj/project.pbxproj#L1191)):*
> ```
> /* Begin PBXFileReference section */
> 		01EF6F292B6A473900125696 /* MullvadApi.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = MullvadApi.swift; sourceTree = "<group>"; };
> 		01EF6F2D2B6A51B100125696 /* mullvad-api.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; name = "mullvad-api.h"; path = "../mullvad-api/include/mullvad-api.h"; sourceTree = "<group>"; };
> ```

This file should be moved to the `MullvadVPNUITests` folder
___
*[`ios/MullvadVPNUITests/MullvadApi.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq30hIK8L6EzRSOtvMu:-Nq30hIK8L6EzRSOtvMv:b-bbeg9a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPNUITests/MullvadApi.swift#L11)):*
> ```Swift
> import Foundation
> 
> class ApiError: Error {
> ```

This probably could be a struct
___
*[`ios/MullvadVPNUITests/MullvadApi.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq30eCGCHdW7j-R18RW:-Nq30eCGCHdW7j-R18RX:b-x4s4fe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPNUITests/MullvadApi.swift#L27)):*
> ```Swift
> }
> 
> class InitMutableBufferError: Error {
> ```

This should be a struct or an enum
___
*[`ios/MullvadVPNUITests/MullvadApi.swift` line 114 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq34CLe8TRWDawBXFj2:-Nq34CLe8TRWDawBXFj3:b-3lusb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPNUITests/MullvadApi.swift#L114)):*
> ```Swift
>     }
> 
>     class Device {
> ```

This can also be a struct

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 10 of 15 files reviewed, 16 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-api/src/ios_ffi/device.rs` line 87 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq6uEPTBQ8Un5_gp-fL:-Nq6uEPTBQ8Un5_gp-fM:b-73sc7s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/device.rs#L87)):*
> ```XML
> pub extern "C" fn mullvad_api_device_iter_next(
>     mut iter: MullvadApiDeviceIterator,
>     device_ptr: *mut MullvadApiDevice,
> ```

Could we not just return `*mut MullvadApiDevice` or null (when done) here?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 10 of 15 files reviewed, 16 unresolved discussions (waiting on @buggmagnet and @dlon)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1191 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq302px7jeLvG_y0j2b:-Nq7MqSU8wY6F-GjvS1x:bb76mu4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPN.xcodeproj/project.pbxproj#L1191)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This file should be moved to the `MullvadVPNUITests` folder
</blockquote></details>

Why?
___
*[`mullvad-api/build.rs` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq2epNe-s7LQPtMzu-c:-Nq7Mx39AqWsuMyJuvNE:b-7iqhk4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/build.rs#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe we do not need to generate the header when the target is macOS, since we do not need this on desktop? Or could this perhaps be guarded by some `ffi` feature instead?
</blockquote></details>

The buildscript is wrong - it should only ever be ran when on macOS, since you need can only compile for iOS from macOS. 
___
*[`mullvad-api/build.rs` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq452wZ6BoPQaI-_hIi:-Nq7N4MQ-7JZlKxTTQzN:b-jcgjbr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/build.rs#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I guess it would be fine for `ios-ffi` to live in `mullvad_api::ffi`? It's just a C API for `mullvad-api`. Nothing iOS-specific about it.
</blockquote></details>

Fair, I'll change it to be `mullvad-api::ffi`. 
___
*[`mullvad-api/Cargo.toml` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq2fFf_34XPiitf9Cxk:-Nq84JTp70Hu23CdvfvO:b-4zr8k0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/Cargo.toml#L42)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this not be a dependency for (and only for) `ios`?
</blockquote></details>

Discussed offline, it's finnicky. I'll add this as a build dependency for all platforms.
___
*[`mullvad-api/src/ios_ffi/device.rs` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq40Xc1-htg-IkrbuYb:-Nq7cakA4BltOR_pz2mH:bptl0p4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/device.rs#L48)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

How do you feel about just appending a nul terminator to `name_bytes` and getting rid of the length? Would make it *slightly* more convenient to construct the string in Swift: https://developer.apple.com/documentation/swift/string/init(cstring:)-2p84k
</blockquote></details>

Let's do that - it works a lot better and we are already receiving nul-terminated strings.
___
*[`mullvad-api/src/ios_ffi/device.rs` line 50 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4-2PiCSCtg8gzBh8i:-Nq84-t9BG9_FOoknPuf:b-2byl43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/device.rs#L50)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

How about calling `Box::into_raw`/`Box::from_raw` directly on `name_ptr` and removing the "backing" pointer? These pointers are identical.
</blockquote></details>

`name_bytes` is not pointing to the first element of the array - instead it's pointing to the length of the array.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 10 of 15 files reviewed, 16 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1191 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq302px7jeLvG_y0j2b:-Nq8SSvZDhklK7frhcg0:b-bg1vlp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPN.xcodeproj/project.pbxproj#L1191)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Mostly because it's not meant to be used outside of the UITests, so it should be confined in the UITests folder instead of being at the root of the project structure

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 10 of 15 files reviewed, 16 unresolved discussions (waiting on @buggmagnet and @dlon)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1191 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq302px7jeLvG_y0j2b:-NqBwAhc17-bo4AtOmH0:b-b31p67) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPN.xcodeproj/project.pbxproj#L1191)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Mostly because it's not meant to be used outside of the UITests, so it should be confined in the UITests folder instead of being at the root of the project structure
</blockquote></details>

It is not at the root, it's at the crate where it is generated. Currently, all rust crates that the iOS code depends on generate their headers at the root of the crate, `$crate/include/$crate.h`. 
___
*[`mullvad-api/src/ios_ffi/device.rs` line 50 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4-2PiCSCtg8gzBh8i:-Nq8kor8BzyrDBOAlkxE:b418i4u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/device.rs#L50)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`name_bytes` is not pointing to the first element of the array - instead it's pointing to the length of the array.
</blockquote></details>

We both looked into this and it seems `Box::into_raw` is pure magic and it's also good enough.
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4HbUY8G2-Zk2-y_vq:-Nq8l04y1HZyMv8mZPhL:bq9qbu5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Couldn't all of the functions (except the init function) just take in a `*const IosApiClientContext` and convert it to `&IosApiClientContext` instead of doing this dance? Also, instead of using `Arc`, just have the freeing function call `Box::from_raw` on it.

Using `Box::from_raw` instead of `Arc` should be possible either way.
</blockquote></details>

I think `Arc` isn't required here, you're right. I'll remove it and use `Box`. 
___
*[`mullvad-api/src/ios_ffi/mod.rs` line 351 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4LWow5lDbXwLjn_-9:-NqBw3XV7GqJzF6-n8mY:b-wn4bcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/src/ios_ffi/mod.rs#L351)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Forcing the caller to deallocate errors feels wrong. Since all of the strings are constants, could you not just define static variables and use `CStr`/`&[u8]`? Or even `b"Failed to parse account number\0".as_ptr()`.
</blockquote></details>

For some errors, the description is generated dynamically.

**Review by niklasberglund — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 10 of 15 files reviewed, 17 unresolved discussions (waiting on @buggmagnet, @dlon, and @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 4315 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-NqC-Lw7CV5e189D3nMG:-NqC-Lw7CV5e189D3nMH:b-ui399o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPN.xcodeproj/project.pbxproj#L4315)):*
> ```
> 			runOnlyForDeploymentPostprocessing = 0;
> 			shellPath = /bin/sh;
> 			shellScript = "# Type a script or drag a script file from your workspace to insert its path.\nCARGO_TARGET_DIR=${PROJECT_DIR}/../target bash ${PROJECT_DIR}/build-rust-library.sh mullvad-api\n";
> ```

Unless Xcode is doing something smart I'm thinking `${PROJECT_DIR}/build-rust-library.sh` will fail if there's space in `PROJECT_DIR` and need quotes around it to handle spaces in the path?

**Review by dlon — COMMENTED** [review]
> Reviewed 9 of 12 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 13 of 16 files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 14 files at r2, 5 of 12 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1191 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq302px7jeLvG_y0j2b:-NqRscSB1gc5789WgLCu:bcjl38u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPN.xcodeproj/project.pbxproj#L1191)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It is not at the root, it's at the crate where it is generated. Currently, all rust crates that the iOS code depends on generate their headers at the root of the crate, `$crate/include/$crate.h`.
</blockquote></details>

This was discussed offline
___
*[`ios/MullvadVPNUITests/MullvadApi.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq30hIK8L6EzRSOtvMu:-NqRsi9m4VAn6PusTuE7:b-dh4swi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPNUITests/MullvadApi.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This probably could be a struct
</blockquote></details>

This looks solved
___
*[`ios/MullvadVPNUITests/MullvadApi.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq30eCGCHdW7j-R18RW:-NqRskFX6k0ExDih-7rm:bm5cpax) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPNUITests/MullvadApi.swift#L27)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be a struct or an enum
</blockquote></details>

This was solved
___
*[`ios/MullvadVPNUITests/MullvadApi.swift` line 114 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq34CLe8TRWDawBXFj2:-NqRsmiTEF593PsrCEGS:bm5cpax) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/ios/MullvadVPNUITests/MullvadApi.swift#L114)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This can also be a struct
</blockquote></details>

This was solved
___
*[`mullvad-api/build.rs` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780#-Nq4GQhQAyuC5_YboLs5:-NqRtXqm8jN-PawRDWpu:bowkaqt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/471ebbccd6ed0e0d1800d8a6bab20587fbba42b6/mullvad-api/build.rs#L10)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

For consistency with how we do this elsewhere, I think the generated header should be committed/versioned.
</blockquote></details>

I agree, we did the same thing for the other auto-generated header files we added to iOS.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 14 files at r2, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: all files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

**Review by buggmagnet — APPROVED** [review]
> Reviewed 4 of 12 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

**Pull request merged**
