### PR TITLE
Migrate select location fragment to compose

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: 8 of 24 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 44 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NWq7hUH4ZGBMNDan0qQ:-NX9MHGzC2lVO4ZwLRfY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6132e7a9b16cc8873efc138e3f22afb93a61cc9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L44)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it's better to expose `_close` separately from the ui state. This applies in general to oneshot actions that the view should handle. Another similar example is how we use a `SharedFlow` to trigger toasts in `VpnSettingsViewModel`.  
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: 9 of 24 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/BuildInstructions.md` line 85 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NX9cyM0-7aZI1zwO1By:-NX9cyM0-7aZI1zwO1Bz:bvfgmhg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/749f507fce21b7795db1cdacaad9901638ff8026/android/BuildInstructions.md#L85)):*
> ```Markdown
> 
> - Install the JDK
> ```

This should be part of the macOS documentation PR, right? :thinking:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: 9 of 24 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/BuildInstructions.md` line 85 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NX9cyM0-7aZI1zwO1By:-NX9ucLe5FLzmwKRRyD5:bpodnn6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/749f507fce21b7795db1cdacaad9901638ff8026/android/BuildInstructions.md#L85)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should be part of the macOS documentation PR, right? :thinking: 
</blockquote></details>

Yeah no idea how it ended up here.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: 16 of 26 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 85 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA33yP7HBXZhzHx-a4:-NXB5Xn89gyqs0TVMfu-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L85)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can some material color be used here? In cases where's it's not possible atm it might be a good idea to add some comment to elaborate on why it's not possible. That way, it's easier to review and come back to later.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 30 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA0aPw2dPsM7x0N3TQ:-NXB5ZQH65zhD9N_oxlN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L30)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Unless this is used in multiple places, this can probably be included when setting up the `_vmState`.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 60 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA0y7xC4rDp-E0jAph:-NXB5_Mg34h3QunkvtwY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Add newline between these flows
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 61 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA-ZEJ88H-9MDdzn9R:-NXB5a2z0fZJp5lY7C5M:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L61)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

In order to improve readability I think it might be a good idea to call this `uiCloseAction`. Another alternative could be to name it `uiAction` and supply it with some object representing the "close" action.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelState.kt` line 9 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA2GMZ07JVB17r1MRy:-NXB5bKjEn7Lxmi8jfSo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelState.kt#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can you elaborate on the naming of these properties? As they currently seem to represent the current VM state I don't fully understand the `new` prefix.

Also, in this case it seems like we might be able to skip this class as it doesn't seem to add much value (compared to some of the other VMs/views).
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/RelayLocation.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA1OJa7ha0Sq1mo4tL:-NXB43IRCYSqCvjGk7-H:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/RelayLocation.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Make private
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/RelayLocation.kt` line 179 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA4sm059iysaaKZqHf:-NXB4MLTBgAnatNTz9Pc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/RelayLocation.kt#L179)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can these use material colors?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/RelayLocation.kt` line 181 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA4VRh8jRwJqZRsrtU:-NXB4Mll419i2jUK2Wrt:bk3kwex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/RelayLocation.kt#L181)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There are some various magic values in terms of dimens, alpha values and rotation angles throughout this file that would be nice to define as constants.
</blockquote></details>

My bad. I added the magic values when a couple of other PRs had not been merged and my intention was to replace those with values derived from dimensions and theme, but I forgot about it.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelState.kt` line 9 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXA2GMZ07JVB17r1MRy:-NXU4cU97OUcR1cFQaJF:b-hx0s1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/466ff791d293b2035226f31f9a938924db26c8ff/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelState.kt#L9)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seems to look the same? :thinking:

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r10, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt` line 46 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXjnTRS352y9B_0Y1mq:-NXjnTRT8Tx6YU1RwcpC:bjg2ylg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86fc949b684381e33e193b220a40c4007745c49/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt#L46)):*
> ```Kotlin
>             onNodeWithText("Relay City 1").assertDoesNotExist()
>             onNodeWithText("Relay 1").assertDoesNotExist()
>             onNodeWithText("Relay Country 2").assertDoesNotExist()
> ```

Why do we need to assert that these are not visible in the Loading state?



_Code quote:_
```Kotlin
            onNodeWithText("Relay Country 1").assertDoesNotExist()
            onNodeWithText("Relay City 1").assertDoesNotExist()
            onNodeWithText("Relay 1").assertDoesNotExist()
            onNodeWithText("Relay Country 2").assertDoesNotExist()
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt` line 91 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXk3hFu9y4jN-FKrUn8:-NXk3hFu9y4jN-FKrUn9:b-mbkni9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86fc949b684381e33e193b220a40c4007745c49/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt#L91)):*
> ```Kotlin
>                 assertEquals(expectedState.selectedRelay, actualState.selectedRelay)
>             } else {
>                 throw Throwable("State is not ShowRelayList")
> ```

I believe it would be better to fail using assertions rather than a `Throwable` if possible. Would something like that be possible?



_Code quote:_
```Kotlin
throw Throwable("State is not ShowRelayList")
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt` line 92 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXk1tZ23uWFRUD046Mt:-NXk1tZ23uWFRUD046Mu:b-crzcz7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86fc949b684381e33e193b220a40c4007745c49/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt#L92)):*
> ```Kotlin
>             } else {
>                 throw Throwable("State is not ShowRelayList")
>             }
> ```

Would be great if we would improve the readability a bit, for example by:
* Adding comments for each test section, for example `// Arrange` as seen in the linked test class.
* Assert all states in the end of the test if possible. This would also the reduce the `viewModel.uiState.test` scope.

Here's another VM test class where I believe it's a bit easier to follow some of the tests:
https://github.com/mullvad/mullvadvpn-app/blob/main/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt#L79



_Code quote:_
```Kotlin
            val mockCountries = listOf<RelayCountry>(mockk(), mockk())
            val selectedRelay: RelayItem = mockk()
            val mockRelayList: RelayList = mockk()
            val expectedState = SelectLocationUiState.ShowData(mockCountries, selectedRelay)
            assertEquals(SelectLocationUiState.Loading, awaitItem())
            every { mockRelayList.countries } returns mockCountries
            serviceConnectionState.value =
                ServiceConnectionState.ConnectedReady(mockServiceConnectionContainer)
            relaySlot.captured.invoke(mockRelayList, selectedRelay)
            val actualState = awaitItem()
            if (actualState is SelectLocationUiState.ShowData) {
                assertLists(expectedState.countries, actualState.countries)
                assertEquals(expectedState.selectedRelay, actualState.selectedRelay)
            } else {
                throw Throwable("State is not ShowRelayList")
            }
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723)* status: 22 of 27 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt` line 46 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXjnTRS352y9B_0Y1mq:-NXoAJt64963hxlzwV1L:bhlx3d3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86fc949b684381e33e193b220a40c4007745c49/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt#L46)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why do we need to assert that these are not visible in the Loading state?
</blockquote></details>

Yeah I guess it's a weird thing to assert. Changed it so that we assert that loading spinner is showing instead.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt` line 91 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXk3hFu9y4jN-FKrUn8:-NXoApiy0-nbmgR2oSK2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86fc949b684381e33e193b220a40c4007745c49/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt#L91)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it would be better to fail using assertions rather than a `Throwable` if possible. Would something like that be possible?
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt` line 92 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-NXk1tZ23uWFRUD046Mt:-NXoAqsS8zmuQ0I2-5_7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86fc949b684381e33e193b220a40c4007745c49/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be great if we would improve the readability a bit, for example by:
* Adding comments for each test section, for example `// Arrange` as seen in the linked test class.
* Assert all states in the end of the test if possible. This would also the reduce the `viewModel.uiState.test` scope.

Here's another VM test class where I believe it's a bit easier to follow some of the tests:
https://github.com/mullvad/mullvadvpn-app/blob/main/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt#L79
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Looks like it's not possible to expand items using DPAD navigation atm which is a regression compared to the previous implementation. Please have a look at that.

> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-:-NXoRT350cEYdq97xxDs:besk8ws)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
Great! :lgtm: 

> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4723#-:-NXpHk1c6qmsktTej_8A:b-twwq5v)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
