### PR TITLE
Store unit test report

### PR DESCRIPTION
**Pull request by niklasberglund**
Store Xcode test report as artefact for unit tests in `ios.yml`. Can be tested by running the "iOS app" workflow with this branch https://github.com/mullvad/mullvadvpn-app/actions/workflows/ios.yml

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`.github/workflows/ios.yml` line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966#-O8v401X7sbJ2mkVXAuy:-O8v401Y2Fx97VPaJRZD:b-h5k9tw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d9671b31254e2ba7199564925209d21942dad1ca/.github/workflows/ios.yml#L126)):*
> ```YAML
> 
>       - name: Archive test report
>         if: always()
> ```

Isn't the default behavior to always run unless otherwise specified?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`.github/workflows/ios.yml` line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966#-O8v401X7sbJ2mkVXAuy:-O98xFuF69XLwVofC5A5:bocis11) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d9671b31254e2ba7199564925209d21942dad1ca/.github/workflows/ios.yml#L126)):*
The default value is `success()` so by default steps will only run if all previous steps were successful

> You can use the following status check functions as expressions in `if` conditionals. A default status check of `success()` is applied unless you include one of these functions.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966#-:-O9i0TjXB4LClB7zAYDI:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @rablador)

**Review by niklasberglund — COMMENTED** [review]
All artefacts are also listed in the summary page for a run - https://github.com/mullvad/mullvadvpn-app/actions/runs/11434648753/
But they are a little hidden because the list of warnings above is quite long.

> Are we certain this will not leak any secrets?
I'm fairly certain, but would be great if others also have a look at the test results and check if you can see a way we might leak secrets through it.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966#-:-O9i2-RM7JZQyCUW2R46:bonldqc)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @rablador)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
