### PR TITLE
Add piping for google play payment API requests

### PR DESCRIPTION
**Pull request by Jontified**
This commit adds all of the basic piping in order to let Android use the JNI interface in order to make requests to our API pertaining to google play payment initialization and status.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 4 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-api/src/lib.rs` line 504 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NfzXOis22ndzJgwa_oq:-NfzXOis22ndzJgwa_or:b-d98wjm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-api/src/lib.rs#L504)):*
> ```XML
>         }
> 
>         let submission = PlayPurchaseSubmission {
> ```

Nit: Could we not just derive `Serialize` on `PlayPurchase`?
___
*[`mullvad-jni/src/lib.rs` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NfzDy7_An3fMdlc499-:-NfzDy7_An3fMdlc4990:bpx6ax5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L196)):*
> ```XML
> #[derive(IntoJava)]
> #[jnix(package = "net.mullvad.mullvadvpn.model")]
> pub enum PlayPurchaseInitResult {
> ```

Should we create the actual type in Kotlin for this?
___
*[`mullvad-jni/src/lib.rs` line 202 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NfzE4xMA0BZ1AN8OwPm:-NfzE4xNC-a20366IdQl:bpx6ax5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L202)):*
> ```XML
> 
> #[derive(IntoJava)]
> #[jnix(package = "net.mullvad.mullvadvpn.model")]
> ```

Should we create the actual type in Kotlin for this?
___
*[`mullvad-types/src/account.rs` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-Nfz96_CBzGOcQPIjV4D:-Nfz96_D4nS66dTnEUqT:bpojv0i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-types/src/account.rs#L15)):*
> ```XML
> /// The payment token returned by initiating a google play purchase.
> /// In the API this is called the `obfuscated_id`.
> pub type PlayPurchaseInitResult = String;
> ```

Could we maybe rename this to `PlayPurchasePaymentToken` or something else less generic?

**Review by Pururun — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`mullvad-jni/src/lib.rs` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NfzDy7_An3fMdlc499-:-Nfze1NH1aJv3u-LeMH_:b7jhp6s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L196)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we create the actual type in Kotlin for this?
</blockquote></details>

They are added in a separate PR
___
*[`mullvad-jni/src/lib.rs` line 202 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NfzE4xMA0BZ1AN8OwPm:-Nfze3XQC36Fo8nvUq6z:b-j88iio) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L202)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we create the actual type in Kotlin for this?
</blockquote></details>

They are added in a seperate PR

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 3 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-jni/src/lib.rs` line 204 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-Nfzkf777CQGj-GD3v4d:-Nfzkf777CQGj-GD3v4e:bsxlhj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L204)):*
> ```XML
> #[jnix(package = "net.mullvad.mullvadvpn.model")]
> pub enum PlayPurchaseInitError {
>     OtherError,
> ```

Is this generic error good enough? We might want to differentiate between timeouts, the service being unavailable, etc.

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-api/src/lib.rs` line 504 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NfzXOis22ndzJgwa_oq:-Ng-3fCl96fQz6dKLol7:b-8r0wh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-api/src/lib.rs#L504)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Could we not just derive `Serialize` on `PlayPurchase`?
</blockquote></details>

Yeah, why not
___
*[`mullvad-types/src/account.rs` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-Nfz96_CBzGOcQPIjV4D:-Ng-4I6X5FIr9o2n1Hnb:b-jhzqjf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-types/src/account.rs#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we maybe rename this to `PlayPurchasePaymentToken` or something else less generic?
</blockquote></details>

Yes we can!

**Review by dlon — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, 2 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @Jontified)

**Review by Pururun — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-jni/src/lib.rs` line 204 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-Nfzkf777CQGj-GD3v4d:-NgSeWIh2af_EC6vxCmV:buebflz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L204)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this generic erro enough? We might want to differentiate between timeouts, the service being unavailable, etc.
</blockquote></details>

Yeah it would be nice to differentiate between generic errors and the mullvad service being unavailable for some reason.

**Review by Pururun — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 7 of 8 files at r5, 7 of 7 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 4 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-api/src/rest.rs` line 404 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NgsjbaD29BPvX28O0R8:-NgsjbaD29BPvX28O0R9:bqr726v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea4e9a4b773a6b26545c5a6be0cb18dbced5edc/mullvad-api/src/rest.rs#L404)):*
> ```XML
> const DEFAULT_ERROR_TYPE: &str = "about:blank";
> #[derive(serde::Deserialize)]
> pub struct NewErrorResponse {
> ```

Can we make this struct and `OldErrorResponse` private?
___
*[`mullvad-api/src/rest.rs` line 407 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NgslXbs-L-lmYy0g20M:-NgslXbs-L-lmYy0g20N:b-2be6p7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea4e9a4b773a6b26545c5a6be0cb18dbced5edc/mullvad-api/src/rest.rs#L407)):*
> ```XML
>     pub status: i32, 
>     pub title: String,
>     pub r#type: Option<String>,
> ```

Could we out the fields we don't actually use? That is, everything except `r#type`.
___
*[`mullvad-daemon/src/device/mod.rs` line 908 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NgsoAb68kZ6k_hqOUzl:-NgsoAb68kZ6k_hqOUzm:b6b9cit) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea4e9a4b773a6b26545c5a6be0cb18dbced5edc/mullvad-daemon/src/device/mod.rs#L908)):*
> ```XML
>         match &response {
>             Ok(_) => (),
>             Err(Error::InvalidAccount) => {
> ```

Do we still get the old style error codes from the API when this occurs? If not, they'll probably not have been parsed correctly here.
___
*[`mullvad-types/src/account.rs` line 54 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-Ngsp9A81Y27FdD0zjvR:-NgshZoG4oOhJX-CiS3t:b3pe0gr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea4e9a4b773a6b26545c5a6be0cb18dbced5edc/mullvad-types/src/account.rs#L54)):*
> ```XML
> pub struct PlayPurchase {
>     pub product_id: String,
>     pub purchase_token: String,
> ```

Nit: Shouldn't this be a `PlayPurchasePaymentToken`?

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: all files reviewed, 3 unresolved discussions (waiting on @Jontified)

**Review by Jontified — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: 14 of 16 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`mullvad-daemon/src/device/mod.rs` line 908 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-NgsoAb68kZ6k_hqOUzl:-Ngt3M2DA8ijg3evPt9u:bqvvi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea4e9a4b773a6b26545c5a6be0cb18dbced5edc/mullvad-daemon/src/device/mod.rs#L908)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we still get the old style error codes from the API when this occurs? If not, they'll probably not have been parsed correctly here.
</blockquote></details>

Old codes will (likely) be sent for this.
___
*[`mullvad-jni/src/lib.rs` line 204 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230#-Nfzkf777CQGj-GD3v4d:-NgsvKZl7MYkiKfjC5w7:b4xaprc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02b91ed5caeccf6e192808d9736b326a33bcba57/mullvad-jni/src/lib.rs#L204)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yeah it would be nice to differentiate between generic errors and the mullvad service being unavailable for some reason.
</blockquote></details>

Update: we've agreed to do this in a separate PR when we've worked out how exactly we want to do errors.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5230)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
