### PR TITLE
Remove the use of intent provider for request vpn permission

### PR DESCRIPTION
**Pull request by Pururun**
Continuation from: https://github.com/mullvad/mullvadvpn-app/pull/6592

Also removes intent holder (but still uses intents) for api overrides that comes for intents.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC82c7y4ta110FrnmAf:-OC82c7y4ta110FrnmAg:bxjuvsg):*
I'm a bit on the fence about this, feels like we are going the wrong way about this solution. 

If I understand correctly this is the case where a user click on a notification because they lack the permission of VPN? Wouldn't it be more natural to utilize deeplinks for this? Show a page saying helping the user to setup a VPN profile. Then I believe we should be able to avoid doing any dance with passing intents from the activity to the view.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC82Qj89DGmY6IGTPcF:-OC82Qj89DGmY6IGTPcG:b-l1egjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9330f9c12c4f75c6628f79d216c8f14f1cdde607/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt#L52)):*
> ```Kotlin
>             mullvadAppViewModel.connect()
>         }
>     val activity = LocalContext.current.getActivity() as ComponentActivity
> ```

Feels a bit weird that we have to grab the activity, and cast it. Would be nice if we can avoid this.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC8-_aA-sD7R1faHBYC:-OC8-_aA-sD7R1faHBYD:bf7mye5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9330f9c12c4f75c6628f79d216c8f14f1cdde607/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt#L53)):*
> ```Kotlin
>         }
>     val activity = LocalContext.current.getActivity() as ComponentActivity
>     LaunchedEffect(navHostController) {
> ```

What is the reasoning behind using `navHostController` as key for the launch effect?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC82c7y4ta110FrnmAf:-OC894co0MqnWBGRbDiz:bqy54ho):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm a bit on the fence about this, feels like we are going the wrong way about this solution. 

If I understand correctly this is the case where a user click on a notification because they lack the permission of VPN? Wouldn't it be more natural to utilize deeplinks for this? Show a page saying helping the user to setup a VPN profile. Then I believe we should be able to avoid doing any dance with passing intents from the activity to the view.
</blockquote></details>

I avoided using a deep link because it was not clear where it would deep link to. I guess you could deep link to a dummy screen that then navigates to the correct screen or I guess a dedicated set up vpn permission screen.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC82Qj89DGmY6IGTPcF:-OC8AkAlBHh601eFXrQ8:b-2bbyih) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9330f9c12c4f75c6628f79d216c8f14f1cdde607/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt#L52)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Feels a bit weird that we have to grab the activity, and cast it. Would be nice if we can avoid this.
</blockquote></details>

You think we should move the cast somewhere else?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC8-_aA-sD7R1faHBYC:-OC8ApXt4h6HBvschEIn:b-2lvnhb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9330f9c12c4f75c6628f79d216c8f14f1cdde607/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt#L53)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

What is the reasoning behind using `navHostController` as key for the launch effect?
</blockquote></details>

Probably a remnant from a previous solution, will remove.

**Comment by Pururun** [comment]
Setting this as on hold since we have other vpn permission work ongoing.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC82c7y4ta110FrnmAf:-ODm_X7q4-BF58AkNI0K:bbn0n1j):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I avoided using a deep link because it was not clear where it would deep link to. I guess you could deep link to a dummy screen that then navigates to the correct screen or I guess a dedicated set up vpn permission screen.
</blockquote></details>

Updated code based on our discussion.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-OC82Qj89DGmY6IGTPcF:-ODm_c__Aw8I5IUI51Si:b-cxchxo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9330f9c12c4f75c6628f79d216c8f14f1cdde607/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt#L52)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

You think we should move the cast somewhere else?
</blockquote></details>

No longer relevant.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 13 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 134 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-ODpcd6q31cXc9U-sLXx:-ODpcd6q31cXc9U-sLXy:b-lyhnx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2678bf87383d1eced5ba091ee761c2176a28951e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L134)):*
> ```Kotlin
>     private fun setUpIntentListener() {
>         lifecycleScope.launch {
>             intents().collect {
> ```

Small remark regarding clarity.

I think we should do it in the following way:

```
onCreate() {
    ...
    lifecycleScope.launch{
        intents().collect(::handleIntent)
    }
    ...
}

private fun handleIntent(intent: Intent) {
    when(val action = intent.action) {
        KEY_REQUEST_VPN_PROFILE -> requestVpnProfile()
        KEY_SET_API_OVERRIDE -> apiEndpointOverrideHolder.set(intent.data.parse()) // or something like this
        else -> Log.w("Unhandled intent action: $action")
    }
}
```
___
*[`android/lib/endpoint/src/debug/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpointFromIntentHolder.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-ODpeBr17bqAilcAytMb:-ODpeBr2Bf5S1RxVuFEZ:b-8o9j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2678bf87383d1eced5ba091ee761c2176a28951e/android/lib/endpoint/src/debug/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpointFromIntentHolder.kt#L10)):*
> ```Kotlin
> 
>     fun handleIntent(intent: Intent) {
>         apiEndpointOverride = intent.getApiEndpointConfigurationExtras()
> ```

Would be nice if this one isn't aware of intent.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: 11 of 16 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 134 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-ODpcd6q31cXc9U-sLXx:-ODr6fPW28RujvnQrBLl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2678bf87383d1eced5ba091ee761c2176a28951e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L134)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Small remark regarding clarity.

I think we should do it in the following way:

```
onCreate() {
    ...
    lifecycleScope.launch{
        intents().collect(::handleIntent)
    }
    ...
}

private fun handleIntent(intent: Intent) {
    when(val action = intent.action) {
        KEY_REQUEST_VPN_PROFILE -> requestVpnProfile()
        KEY_SET_API_OVERRIDE -> apiEndpointOverrideHolder.set(intent.data.parse()) // or something like this
        else -> Log.w("Unhandled intent action: $action")
    }
}
```
</blockquote></details>

Done.
___
*[`android/lib/endpoint/src/debug/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpointFromIntentHolder.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-ODpeBr17bqAilcAytMb:-ODr6fmy4-ykQOlLwm7S:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2678bf87383d1eced5ba091ee761c2176a28951e/android/lib/endpoint/src/debug/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpointFromIntentHolder.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would be nice if this one isn't aware of intent.
</blockquote></details>

Done.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 134 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-ODu6V_Q-YOxpv4cSV8t:-ODu6V_Q-YOxpv4cSV8u:b-1867qq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f35e848ee075b8770735a87758c9fa2631dd071d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L134)):*
> ```Kotlin
> 
>     private fun handleIntent(intent: Intent) {
>         if (intent.action == KEY_REQUEST_VPN_PROFILE) {
> ```

Don't forget when statement, with warning logging if unsupported action.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 134 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198#-ODu6V_Q-YOxpv4cSV8t:-ODuI6vkC5Jn4tG6CGxE:bbe02mq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f35e848ee075b8770735a87758c9fa2631dd071d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L134)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

```    
when(val action = intent.action) {
        KEY_REQUEST_VPN_PROFILE -> requestVpnProfile()
        KEY_SET_API_OVERRIDE -> apiEndpointOverrideHolder.set(intent.data.parse()) // or something like this
        else -> Log.w("Unhandled intent action: $action")
    }```
```

</blockquote></details>

Ah sorry missed that part. Done

**Review by Rawa — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7198)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
