### PR TITLE
Add auto connect and lockdown mode screen

### PR DESCRIPTION
**Pull request by MaryamShaghaghi**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592)

### CODE REVIEW

**Review by MaryamShaghaghi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592)* status: 24 of 25 files reviewed, 11 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcI8eI6AAvs4BLsKnD:-NlcnExd4wy7YIBHog_K:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L48)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should define this as a constant, such as `const val CAROUSEL_PAGE_SIZE = 3`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcIba0-JKJ0RdOOQMz:-NlcnJAkA2bKDS79jQsY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L62)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Use annotated string instead of HtmlText
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcIVl_E6g7HSibsgae:-NlgfJ1MD9-Wsx7ED0r2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L78)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Try to use a style instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcIhU38QLlQSKvCLup:-NlgmeeEDTT5s7JwSNaf:bh4t0ju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L98)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magic number
</blockquote></details>

do we need to create another icon for back arrow instead of rotating it, or we should have another const val?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 121 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcIvAK1NfnjLTip4eE:-Nlgbvv01x8XFez4kD0T:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L121)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is better to write as `page < CAROUSEL_PAGE_SIZE`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcJ4Sh2lkd1HwW0hA0:-Nlgc-gZBBd9vAw2mgrO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L142)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Same as above user AnnotatedString
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcJ87E8N1LhDXkmugx:-NlglEVk0Q9tWbSardHZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L158)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Use style instead (which you can do if you use annotated string)
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcJD2B9aJV1-oCssN_:-Nlgdh4BEV7SLw8-S4hn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L175)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Use theme colors instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 277 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcJmpmB2JIJznPdGZu:-NlgduMD6mLThbWS29jf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L277)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Can we wrap this in `requireActivity(Intent("android.settings.VPN_SETTINGS"))` ?
</blockquote></details>

Done.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcKEqw4-t5655LRe3n:-Nlgev2vD5mjHMByDk7a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/lib/resource/src/main/res/values/strings.xml#L80)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is it possible to make this a bit more expressive? Like `auto_connect_carousel_first_slide_top_text` or something? The same is applicable to all of these.
</blockquote></details>

Done.
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcKUHn0ugBjXlQHtIC:-Nlgf-3O-dG3amzi3azO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L11)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Preferable use something divided by 2 or even better 4.
</blockquote></details>

Done.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592)* status: all files reviewed, 2 unresolved discussions (waiting on @MaryamShaghaghi)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-NlcIhU38QLlQSKvCLup:-NlgrNQo51wTFR-rXVh2:b-quv78r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63972f0ecc452efb80522e0dded9179d2d84c12b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L98)):*
<details><summary><i>Previously, MaryamShaghaghi (Maryam Shaghaghi) wrote…</i></summary><blockquote>

do we need to create another icon for back arrow instead of rotating it, or we should have another const val?
</blockquote></details>

I will retract this since we have used hardcoded numbers elsewhere in the app.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt` line 193 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592#-Nlgr7Yb3oztyB2eCqN-:-Nlgr7Yb3oztyB2eCqN0:by9bn3z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e085e55966b18146315feafd5aadb3442225e3e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AutoConnectCarousel.kt#L193)):*
> ```Kotlin
>                     .constrainAs(pageIndicatorRef) {
>                         top.linkTo(lowerTextRef.bottom)
> ```

Remove this line

**Comment by Pururun** [comment]
This will be continued here: https://github.com/mullvad/mullvadvpn-app/pull/5643

**Review by sabercodic — COMMENTED** [review]
> Reviewed 5 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5592)* status: all files reviewed, 2 unresolved discussions (waiting on @MaryamShaghaghi and @Pururun)

**Pull request closed without merging**
