### PR TITLE
Refactor location data type and dependencies

### PR DESCRIPTION
**Pull request by rablador**
We need to split the location view into two sections, one for custom lists and one for all locations. Due to the current data structure being pretty much locked into a certain hierarchy we decided to create a new flexible data type and refactor the main data source and its dependencies.

Includes:

- [IOS-494](https://linear.app/mullvad/issue/IOS-494/allow-selecting-a-single-location-from-a-custom-list)
- [IOS-493](https://linear.app/mullvad/issue/IOS-493/adjust-search-bar-to-filter-custom-lists-by-name-but-not-by-contents)

To test, add the following snippet somewhere before the call to show locations:

```
try? CustomListRepository().create("Netflix", locations: [
    .hostname("al", "tia", "ca-tor-wg-001"),
    .country("se"),
    .city("ca", "tor"),
])

try? CustomListRepository().create("Youtube", locations: [
    .hostname("ca", "tor", "ca-tor-wg-101"),
    .city("de", "ber"),
])
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: 0 of 21 files reviewed, 2 unresolved discussions

___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NritqG094g9hFbmxNqT:-NritqG094g9hFbmxNqU:b1p015y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f73eadb1dbc4e637269e0c1db5503ce186219c2a/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift#L1)):*
> ```Swift
> //
> ```

Something happened during rebase, likely because this PR was originally based on another non-main PR. In any case, this file was only moved and doesn't need to be reviewed (again).
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorContentView.swift` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NriuQke3PQ2j8Kzldse:-NriuQke3PQ2j8Kzldsf:b1p015y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f73eadb1dbc4e637269e0c1db5503ce186219c2a/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorContentView.swift#L1)):*
> ```Swift
> //
> ```

Something happened during rebase, likely because this PR was originally based on another non-main PR. In any case, this file was only moved and doesn't need to be reviewed (again).

**Review by acb-mv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 21 files at r1, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: 20 of 22 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 103 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NroKA7iE7i8P3YDDdMh:-NroKA7iE7i8P3YDDdMi:b-tg00hw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L103)):*
> ```Swift
>     }
> 
>     static func == (lhs: LocationNode, rhs: LocationNode) -> Bool {
> ```

A minor nit, but shouldn't this be under an `Equatable` conformance rather than `Hashable`?

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: 20 of 22 files reviewed, 10 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIColor+Palette.swift` line 120 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrlQqvB3TpcV4U1O6NS:-NrlQqvCBmmGYTTCaSf3:b-7hr6r0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/UI%20appearance/UIColor%2BPalette.swift#L120)):*
> ```Swift
>     }
> 
>     enum SubSubSubCell {
> ```

I would suggest you to refactor node background color in this way :



_Code snippet:_
```Swift
  enum LocationNodeLevelCell {
        enum BackgroundColor {
            static let zero = UIColor(red: 0.15, green: 0.23, blue: 0.33, alpha: 1.0)
            static let one = UIColor(red: 0.15, green: 0.23, blue: 0.33, alpha: 1.0)
            static let two = UIColor(red: 0.13, green: 0.20, blue: 0.30, alpha: 1.0)
            static let three = UIColor(red: 0.11, green: 0.17, blue: 0.27, alpha: 1.0)
        }
    }
    
    or 
    
     enum LocationCell {
        enum NodeLevel {
            enum BackgroundColor {
                static let zero = UIColor(red: 0.15, green: 0.23, blue: 0.33, alpha: 1.0)
                static let one = UIColor(red: 0.15, green: 0.23, blue: 0.33, alpha: 1.0)
                static let two = UIColor(red: 0.13, green: 0.20, blue: 0.30, alpha: 1.0)
                static let three = UIColor(red: 0.11, green: 0.17, blue: 0.27, alpha: 1.0)
            }
        }
    }
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Nro_2VeEwkvd3QdtpMO:-Nro_2VeEwkvd3QdtpMP:b-ywm2of) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L13)):*
> ```Swift
> 
> class LocationNode {
>     let nodeName: String
> ```

the class name contains `node`,having them in the properties are redundant 



_Code snippet:_
```Swift
class LocationNode {
    let name: String
    var code: String
    ...
     init(
        name: String,
        code: String,
        locations: [RelayLocation] = [],
        indentationLevel: Int = 0,
        parent: LocationNode? = nil,
        children: [LocationNode] = [],
        showsChildren: Bool = false
    ) {
        self.name = nodeName
        self.code = nodeCode
        self.locations = locations
        self.indentationLevel = indentationLevel
        self.parent = parent
        self.children = children
        self.showsChildren = showsChildren
    }
}
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 41 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrobgDS87mRphaa4IAE:-NrobgDS87mRphaa4IAF:b-barwb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L41)):*
> ```Swift
> 
> extension LocationNode {
>     var topmostAncestor: LocationNode {
> ```

if I were you,I would rename that to `root`
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 45 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Nro_nKA-tz8cTMoyHx7:-Nro_nKA-tz8cTMoyHx8:b-pqq681) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L45)):*
> ```Swift
>     }
> 
>     func countryFor(countryCode: String) -> LocationNode? {
> ```

countryFor(countryCode: String)



_Code snippet:_
```Swift
func country(for Code: String)
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 58 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrobHYW34CCDkVk0_Nb:-NrobHYW34CCDkVk0_Nc:b-vdla1o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L58)):*
> ```Swift
> 
>     func childNodeFor(nodeCode: String) -> LocationNode? {
>         self.nodeCode == nodeCode ? self : children.compactMap { $0.childNodeFor(nodeCode: nodeCode) }.first
> ```

cannot we aggregate 3 functions in 1? 



_Code snippet:_
```Swift
   func find(by code : String) -> LocationNode? {
        nodeCode == code ? self : children.first(where: { $0.nodeCode == code })
    }
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrocaAm0D1Kby7OIgTs:-NrocaAm0D1Kby7OIgTt:bu66lhu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L77)):*
> ```Swift
> 
> extension LocationNode {
>     func copy(withParent parent: LocationNode? = nil) -> LocationNode {
> ```

`LocationNode` is a reference type.cannot we change just the properties we want instead of making another object?



_Code snippet:_
```Swift
func deepCopy(with parent: LocationNode? = nil) -> LocationNode {
        self.parent = parent

        self.children = recursivelyCopyChildren(withParent: self)

        return self
    }
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 103 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NroKA7iE7i8P3YDDdMh:-Nrofgqq0eu2hzSyj1N6:b4s38s7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L103)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

A minor nit, but shouldn't this be under an `Equatable` conformance rather than `Hashable`?
</blockquote></details>

`Hashable` conforms `Equatable`. `LocationNode` should be `Hashable` for the essence of `UITableViewDiffableDataSource`
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 121 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrogfqO-CZPbfDHAyiU:-NrogfqO-CZPbfDHAyiV:b-6c0m7f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L121)):*
> ```Swift
> }
> 
> class ListLocationNode: LocationNode {
> ```

should it be `CustomListLocationNode`?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: 20 of 22 files reviewed, 10 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 45 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Nro_nKA-tz8cTMoyHx7:-NrolCUb9W6ZuPSpjD_S:bvu4c1d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L45)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

countryFor(countryCode: String)
</blockquote></details>

Stylistically I agree, but from call site `country(for: String)` doesn't give any clue as to what `for` should be.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 58 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrobHYW34CCDkVk0_Nb:-Nrol2Vx0NurABRZfxLc:blrsowh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L58)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

cannot we aggregate 3 functions in 1?
</blockquote></details>

Yeah, perhaps we should. The reason I've kept them apart is that this operation is a lot more expensive that the others, since it recursively travels through the whole tree if needed.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrocaAm0D1Kby7OIgTs:-NrokVxY9Zvb7Zz_8rm5:b-7nccdt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L77)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

`LocationNode` is a reference type.cannot we change just the properties we want instead of making another object?
</blockquote></details>

That won't work, since the copy typically comes from the nodes in the other data source. If you change eg. `showsChildren` you'll end up expanding the referenced node as well. I'm not in love with the idea of copying like this, but we really do need separate objects here. An alternative could be to let `CustomListDataSource` construct its own complete list of nodes from the relay response, just like `AllLocationsDataSource`, but the operations is a little expensive and unnecessary to duplicate.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 103 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NroKA7iE7i8P3YDDdMh:-NrolT80AYotpIEPaudd:b7u03hh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L103)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

`Hashable` conforms `Equatable`. `LocationNode` should be `Hashable` for the essence of `UITableViewDiffableDataSource`
</blockquote></details>

Correct

**Review by rablador — COMMENTED** [review]
I've just realized that the search functionality isn't working as intended. Please disregard those parts from the PR until fixed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-:-NrouQTHDqe1hy5FYt2O:b5ynrrp)* status: 20 of 22 files reviewed, 10 unresolved discussions (waiting on @acb-mv and @mojganii)

**Review by rablador — COMMENTED** [review]
There, updated.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-:-NrpU8B98a9VjiInPTWs:b-khb02i)* status: 13 of 25 files reviewed, 10 unresolved discussions (waiting on @acb-mv and @mojganii)

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 12 of 21 files at r1, 1 of 8 files at r3, 2 of 7 files at r4, 2 of 5 files at r5, 7 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: 24 of 26 files reviewed, 15 unresolved discussions (waiting on @acb-mv, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIColor+Palette.swift` line 120 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrlQqvB3TpcV4U1O6NS:-NrtFV1G6cgKjYLz9s_1:b-3tmmrw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/UI%20appearance/UIColor%2BPalette.swift#L120)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I would suggest you to refactor node background color in this way :
</blockquote></details>

Wouldn't it be easier to just switch things around instead ?
```swift

    enum SubCell {
        static func backgroundColorForIdentationLevel(level: Int) -> UIColor {
            switch level {
            case 1:
                return UIColor(red: 0.15, green: 0.23, blue: 0.33, alpha: 1.0)
            case 2:
                return UIColor(red: 0.13, green: 0.20, blue: 0.30, alpha: 1.0)
            case 3:
                return UIColor(red: 0.11, green: 0.17, blue: 0.27, alpha: 1.0)
            default:
                return UIColor.Cell.backgroundColor

            }
        }
    }
```

and on the call site
```swift
    private func backgroundColorForIdentationLevel() -> UIColor {
        UIColor.SubCell.backgroundColorForIdentationLevel(level: indentationLevel)
    }

```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 20 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtHTseBOt5vdTOxAEM:-NrtHTseBOt5vdTOxAEN:bqr97xu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L20)):*
> ```Swift
>     }
> 
>     func reload(_ response: REST.ServerRelaysResponse, relays: [REST.ServerRelay]) {
> ```

Could you add a brief comment of what the function does in broad terms ?
It doesn't have to be super deep, but just to help future readers get the general idea, for example why are cities special cased in this 
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 56 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtI2-N7r6HD9GMTM9B:-NrtI2-N7r6HD9GMTM9C:b-cvvzcn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L56)):*
> ```Swift
>             return switch locations.first {
>             case let .country(countryCode):
>                 customListNode.childNodeFor(nodeCode: "\(customListNode.nodeCode)-\(countryCode)")
> ```

IMHO we shouldn't pass a custom format here, it's very easy to get wrong. 
What do you feel about passing an array of strings instead, which the `childNodeFor` function will know how to format properly ?

i.e. something along those lines 

```swift
    func childNodeFor(nodes: [String]) -> LocationNode? {
        let nodeCode = nodes.joined(separator: "-")
        return childNodeFor(nodeCode: nodeCode)
    }
```

The callsite becomes `customListNode.childNodeFor(nodes: [customListNode.nodeCode, countryCode])` which cannot have the wrong format now.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtLIy18Ls-qntA-Tht:-NrtLIy18Ls-qntA-Thu:b-eb1s6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCellViewModel.swift#L23)):*
> ```Swift
>     static func == (lhs: Self, rhs: Self) -> Bool {
>         lhs.node == rhs.node &&
>             lhs.section == rhs.section
> ```

nit
Do we want to check the indentation level here as well ?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 93 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtYTja3rK-_KpTf648:-NrtYTja3rK-_KpTf649:b-k3bn38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L93)):*
> ```Swift
> 
>         updateDataSnapshot(with: list, reloadExisting: !searchString.isEmpty) {
>             DispatchQueue.main.async {
> ```

Not sure why is this dispatch to main here, from what I can see, this `filterRelays` is always called on the main thread.
What problem did you have that required this workaround ?
___
*[`ios/MullvadVPNTests/Location/AllLocationsDataSourceTests.swift` line 42 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Nrteafv7DCkebPXBVIp:-Nrteafv7DCkebPXBVIq:b-f9iohk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPNTests/Location/AllLocationsDataSourceTests.swift#L42)):*
> ```Swift
>         XCTAssertEqual(nodes, dataSource.nodes)
>     }
> ```

For completion's sake, can we have 2 extra tests ? 
- One test that calls `node(by .country(...)` 
- One test that calls `node(by: .city(...))`

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: 24 of 26 files reviewed, 15 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/UI appearance/UIColor+Palette.swift` line 120 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrlQqvB3TpcV4U1O6NS:-Nrta3-O4kfOt1PkQDuN:bp34n6k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/UI%20appearance/UIColor%2BPalette.swift#L120)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Wouldn't it be easier to just switch things around instead ?
```swift

    enum SubCell {
        static func backgroundColorForIdentationLevel(level: Int) -> UIColor {
            switch level {
            case 1:
                return UIColor(red: 0.15, green: 0.23, blue: 0.33, alpha: 1.0)
            case 2:
                return UIColor(red: 0.13, green: 0.20, blue: 0.30, alpha: 1.0)
            case 3:
                return UIColor(red: 0.11, green: 0.17, blue: 0.27, alpha: 1.0)
            default:
                return UIColor.Cell.backgroundColor

            }
        }
    }
```

and on the call site
```swift
    private func backgroundColorForIdentationLevel() -> UIColor {
        UIColor.SubCell.backgroundColorForIdentationLevel(level: indentationLevel)
    }

```
</blockquote></details>

I made changes to the `Cell` enum already present there.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 20 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtHTseBOt5vdTOxAEM:-Nrtte0CE3zuTZjGPwPM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Could you add a brief comment of what the function does in broad terms ?
It doesn't have to be super deep, but just to help future readers get the general idea, for example why are cities special cased in this
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 56 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtI2-N7r6HD9GMTM9B:-Nru0R_WDL_WagqABZV4:belm58l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L56)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

IMHO we shouldn't pass a custom format here, it's very easy to get wrong. 
What do you feel about passing an array of strings instead, which the `childNodeFor` function will know how to format properly ?

i.e. something along those lines 

```swift
    func childNodeFor(nodes: [String]) -> LocationNode? {
        let nodeCode = nodes.joined(separator: "-")
        return childNodeFor(nodeCode: nodeCode)
    }
```

The callsite becomes `customListNode.childNodeFor(nodes: [customListNode.nodeCode, countryCode])` which cannot have the wrong format now.
</blockquote></details>

It's not a custom format, and I can see how it easily could be interpreted as such. `customListNode.nodeCode` as a prefix is a necessary evil to differentiate nodes and scope them under a list. Without this the diffable data source will complain about identical item identifiers. We could add something like a custom list id to `LocationNode` and include it in the hash. That would remove the need for this jank, but at the same time add further bloat to each node.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtLIy18Ls-qntA-Tht:-Nru31PR9eKuHD_nGT3G:b-aqwsaj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCellViewModel.swift#L23)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Do we want to check the indentation level here as well ?
</blockquote></details>

Originally no, since selecting an item while searching could yeild a different indentation level than when all nodes are visible (custom list top node is removed from search results, meaning one less level of indentation). This would make comparisons of `selectedItem` with any other item unreliable. However, I could change the one place where we compare this way (in `tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPat)`) to compare nodes instead. This works, but we may have future side effects this way.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 93 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtYTja3rK-_KpTf648:-Nru51WW3Alo32vsyFql:b-fdswnj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L93)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Not sure why is this dispatch to main here, from what I can see, this `filterRelays` is always called on the main thread.
What problem did you have that required this workaround ?
</blockquote></details>

If `updateDataSnapshot` is called while the snapshot is being applied the tableView will throw:

`Deadlock detected: calling this method on the main queue with outstanding async updates is not permitted and will deadlock. Please always submit updates either always on the main queue or always off the main queue`

The call from `LocationViewController.setUpDataSource` is what's causing this.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Nro_2VeEwkvd3QdtpMO:-NrtcrvaDVTs9RWJh80r:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the class name contains `node`,having them in the properties are redundant
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 41 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrobgDS87mRphaa4IAE:-NrtV0AvEu50GhMqyMaM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L41)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

if I were you,I would rename that to `root`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift` line 121 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrogfqO-CZPbfDHAyiU:-NrtV1ZaCcJ87rFRBf2D:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72b58a4754f6a6cbcf6e3392baa28c06e98e4d48/ios/MullvadVPN/View%20controllers/SelectLocation/LocationNode.swift#L121)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

should it be `CustomListLocationNode`?
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/Location/AllLocationsDataSourceTests.swift` line 42 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Nrteafv7DCkebPXBVIp:-NrtftyV-W1pQjPnv4o0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPNTests/Location/AllLocationsDataSourceTests.swift#L42)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

For completion's sake, can we have 2 extra tests ? 
- One test that calls `node(by .country(...)` 
- One test that calls `node(by: .city(...))`
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, 1 of 8 files at r6, 17 of 18 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-:-Ns8NoRvERdHBpF320FR:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 56 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-NrtI2-N7r6HD9GMTM9B:-Ns8-c8LDm9pRlVPhcEp:b-nkve8n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b1fbc55cd342f49ea0c066b0f06bf2a0b27cabd/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L56)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's not a custom format, and I can see how it easily could be interpreted as such. `customListNode.nodeCode` as a prefix is a necessary evil to differentiate nodes and scope them under a list. Without this the diffable data source will complain about identical item identifiers. We could add something like a custom list id to `LocationNode` and include it in the hash. That would remove the need for this jank, but at the same time add further bloat to each node.
</blockquote></details>

nit
I think we misunderstood each other, but it's not a big deal. Marking this as resolved

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-:-Ns8wezgE2QrTnipNvpF:bnfp4nl)* status: 29 of 32 files reviewed, 8 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift` line 16 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Ns8vU0t1TBIvPVlcQFF:-Ns8yhAx0nWcZhugPI59:b93igq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7150986d64887dbc99788fe31479ea0006c88a2/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCellViewModel.swift#L16)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do we need to implement hasher?
</blockquote></details>

Nope, will remove.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 22 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872#-Ns8ve2W6NyHe7nKrKrI:-Ns8zxN40t9URkM-eYGH:b6px6cw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7150986d64887dbc99788fe31479ea0006c88a2/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L22)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

cannot we use `RelayLocations` model instead of tuple value?
</blockquote></details>

Yeah, that's better!

**Review by buggmagnet — APPROVED** [review]
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5872)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

**Pull request merged**
