### PR TITLE
Device info should only be displayed once user dismissed "device created" notification

### PR DESCRIPTION
**Pull request by mojganii**
when user buys more credit, the account data will be changed with more expiry time. it means it's look like to these states :
`logged out` -> `logged in` -> `logged in` with new data. in this case we shouldn't dismiss the banner view until user taps close button.
solution :
- When user buys more credit, the previous and current device state are `logged in` with different account data.we check if user dismissed the registered device in app banner then we show device info with new data otherwise we stay until user dismisses the banner
- Hide device info when user goes from `logged out` to `logged in` till user dismisses the in app banner
- Hide device info when user is in `revoked` or `logged out` state

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 740 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704#-NW2VmW85B3eWi42Spfm:-NW2VmW9DGIWMw5ewktn:b-snblzx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d75018e88c9eee1eb47587a23ec4bf63a3a55655/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L740)):*
> ```Swift
>     }
> 
>     private func shouldShowDeviceInfo(_ deviceState: DeviceState, previousDeviceState: DeviceState) -> Bool {
> ```

I wanted to see all the possible outcomes, so I wrote the following program :


```

enum DeviceState: Codable, Equatable {
    case loggedIn
    case loggedOut
    case revoked
}

func shouldShowDeviceInfo(_ deviceState: DeviceState, previousDeviceState: DeviceState) -> Bool { ... }

let state1: DeviceState = .loggedIn
let state2: DeviceState = .loggedOut
let state3: DeviceState = .revoked

let pairs: [(DeviceState, DeviceState)] = [
    (state1, state1),
    (state1, state2),
    (state1, state3),
    
    (state2, state2),
    (state2, state1),
    (state2, state3),
    
    (state3, state3),
    (state3, state2),
    (state3, state1),
]

pairs.forEach { pair in
    print("from \(pair.0) to \(pair.1) -> should show device info: \(shouldShowDeviceInfo(pair.1, previousDeviceState: pair.0))")
}
```

It gave me the following output 

```
from loggedIn to loggedIn -> should show device info: true
from loggedIn to loggedOut -> should show device info: false
from loggedIn to revoked -> should show device info: false
from loggedOut to loggedOut -> should show device info: true
from loggedOut to loggedIn -> should show device info: false
from loggedOut to revoked -> should show device info: true
from revoked to revoked -> should show device info: true
from revoked to loggedOut -> should show device info: true
from revoked to loggedIn -> should show device info: true
```

It looks like if we transition from `revoked` to `logged` we show the device info, despite the PR description saying otherwise.

I'm a huge fan of [making illegal states unrepresentable](https://oleb.net/blog/2018/03/making-illegal-states-unrepresentable/)

I don't know if some of these combinations make sense, but in any case, I'd like to request that we make sure of the following

* We cannot have an illegal transition, so the app should either crash (not great) or not compile (great, but hard to do) if we have one
* If we cannot do the above, have the guarantee that this function can only be called for valid transitions 
* Write tests for this so we cover what's a valid state and what's not

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 740 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704#-NW2VmW85B3eWi42Spfm:-NW2ba4T3pIfAXXyPOFc:bpslvpa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d75018e88c9eee1eb47587a23ec4bf63a3a55655/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L740)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I wanted to see all the possible outcomes, so I wrote the following program :


```

enum DeviceState: Codable, Equatable {
    case loggedIn
    case loggedOut
    case revoked
}

func shouldShowDeviceInfo(_ deviceState: DeviceState, previousDeviceState: DeviceState) -> Bool { ... }

let state1: DeviceState = .loggedIn
let state2: DeviceState = .loggedOut
let state3: DeviceState = .revoked

let pairs: [(DeviceState, DeviceState)] = [
    (state1, state1),
    (state1, state2),
    (state1, state3),
    
    (state2, state2),
    (state2, state1),
    (state2, state3),
    
    (state3, state3),
    (state3, state2),
    (state3, state1),
]

pairs.forEach { pair in
    print("from \(pair.0) to \(pair.1) -> should show device info: \(shouldShowDeviceInfo(pair.1, previousDeviceState: pair.0))")
}
```

It gave me the following output 

```
from loggedIn to loggedIn -> should show device info: true
from loggedIn to loggedOut -> should show device info: false
from loggedIn to revoked -> should show device info: false
from loggedOut to loggedOut -> should show device info: true
from loggedOut to loggedIn -> should show device info: false
from loggedOut to revoked -> should show device info: true
from revoked to revoked -> should show device info: true
from revoked to loggedOut -> should show device info: true
from revoked to loggedIn -> should show device info: true
```

It looks like if we transition from `revoked` to `logged` we show the device info, despite the PR description saying otherwise.

I'm a huge fan of [making illegal states unrepresentable](https://oleb.net/blog/2018/03/making-illegal-states-unrepresentable/)

I don't know if some of these combinations make sense, but in any case, I'd like to request that we make sure of the following

* We cannot have an illegal transition, so the app should either crash (not great) or not compile (great, but hard to do) if we have one
* If we cannot do the above, have the guarantee that this function can only be called for valid transitions 
* Write tests for this so we cover what's a valid state and what's not
</blockquote></details>

it's state. we transition between them based on a logic. so I don't think some states never happen.

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 740 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704#-NW2VmW85B3eWi42Spfm:-NW6aXBm8bawHZsHZfQn:b-3qpqoc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d75018e88c9eee1eb47587a23ec4bf63a3a55655/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L740)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's state. we transition between them based on a logic. so I don't think some states never happen.
</blockquote></details>

I'm not confident enough to comment on the state transitions, but I think this function needs a little tidying up. Eg. there's different spacing between and before lines.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704#-:-NW7F0hU9islf2L8EZhq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by rablador — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704#-:-NWBjVuK9052b7NDbTWW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4704#-:-NWCAcVZ1BFkHUZ5rkGq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
