### PR TITLE
The build script now updates the server list and builds the dmg

### PR DESCRIPTION
**Pull request by eriklarko**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/48)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build-release-artifacts.sh, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WiiAKRgOo8kqWl6q:-L45WiiAKRgOo8kqWl6r:b46smp4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L15)):*
> ```Shell
> 
> # Update the server list
> target/debug/list-relays > dist-assets/relays.json
> ```

`target/release/list-relays` since you've built a release above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by eriklarko** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build-release-artifacts.sh, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WiiAKRgOo8kqWl6q:-L45XIjh5vtcF38q0EQj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L15)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

`target/release/list-relays` since you've built a release above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[build-release-artifacts.sh, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WiiAKRgOo8kqWl6q:-L45X9DVbQ6UKqn2udNG:berxe2y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L15)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

`target/release/list-relays` since you've built a release above.
</blockquote></details>

Does this mean we want to stop commiting it to git? Otherwise we are in some gray zone here. Where we build the dmg in a dirty working directory if we update `relays.json` and then builds the dmg without commiting the changed file.

---

*[build-release-artifacts.sh, line 18 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WpV7JTd0uEIgbLyt:-L45WpV7JTd0uEIgbLyu:b761nba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L18)):*
> ```Shell
> 
> # Build the dmg
> yarn pack:mac
> ```

This part makes it mac-specific now, which it was not before. Would be nice if there was a `yarn pack:my-platform` or similar. But this is fine for now. We'll have to re-work this when cross building for Android etc anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build-release-artifacts.sh, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WiiAKRgOo8kqWl6q:-L45X_ALws2q95WRoSm1:b407nx9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this mean we want to stop commiting it to git? Otherwise we are in some gray zone here. Where we build the dmg in a dirty working directory if we update `relays.json` and then builds the dmg without commiting the changed file.
</blockquote></details>

makes sense

```
git rm dist-assets/relays.json
echo 'dist-assets/relays.json' >> .gitignore 
```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[build-release-artifacts.sh, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45YAQuHeK7SQlHXCGh:-L45YAQuHeK7SQlHXCGi:b-i4ys5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L5)):*
> ```Shell
> set -e
> 
> export MACOSX_DEPLOYMENT_TARGET="10.7"
> ```

this makes it mac specific too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[build-release-artifacts.sh, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45YAQuHeK7SQlHXCGh:-L45YENFf5razGXhKhcH:brjpbhb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L5)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

this makes it mac specific too?
</blockquote></details>

cc @faern 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build-release-artifacts.sh, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45YAQuHeK7SQlHXCGh:-L45_DownftwErS9e2-B:b-lj0bxu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L5)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

cc @faern 
</blockquote></details>

Yes and no. It only *helps* on a mac. But it does not *break* anything form building on Linux.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build-release-artifacts.sh, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WiiAKRgOo8kqWl6q:-L45_L-kSLsQElWL5Pab:b-qu1wx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L15)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

makes sense

```
git rm dist-assets/relays.json
echo 'dist-assets/relays.json' >> .gitignore 
```

?
</blockquote></details>

I would say one or the other. If we have it checked in but automatically update it then we will end up with a super old file in git after a while that does no good. On the other hand, not having it in git will require us to add to the setup instructions how to get the initial version, as people checking out the repo will not automatically get it.

I agree it's good to remove it from git, since it's almost always out of date anyway. But then add a step in the README how to get it from the beginning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build-release-artifacts.sh, line 5 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45YAQuHeK7SQlHXCGh:-L45_sRiUrqgQ1YAwAlK:b-hxoe0n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes and no. It only *helps* on a mac. But it does not *break* anything form building on Linux.
</blockquote></details>

Sorry not the PR I am assigned to. Went here by mistake (because I get emails for the repos that I watch on Github)

I have nothing against having it here for the time being.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build-release-artifacts.sh, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48#-L45WiiAKRgOo8kqWl6q:-L45aAEnstOCq_1fahPZ:bberwgv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cebb6fef0f23725ea419529bc3aa0a9c79798f05/build-release-artifacts.sh#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I would say one or the other. If we have it checked in but automatically update it then we will end up with a super old file in git after a while that does no good. On the other hand, not having it in git will require us to add to the setup instructions how to get the initial version, as people checking out the repo will not automatically get it.

I agree it's good to remove it from git, since it's almost always out of date anyway. But then add a step in the README how to get it from the beginning.
</blockquote></details>

One of cons of having it there is basically if you're on a secret mission to Afghanistan and the spy balloon intercepts all of the communication but you have a cloned repository of Mullvad VPN on your computer, you can easily build it offline, get online safely and do a secret communication with the mother base. Just saying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/48)*

**Pull request closed without merging**
