### PR TITLE
Update changelog for `android/2014.10-beta2`

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395#-OEZNsXt4WS9v1HWmyjw:-OEZNsXt4WS9v1HWmyjx:be8gz1a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcf40d4446e2de55a09ada64606644988a3b0c0f/android/src/main/play/release-notes/en-US/default.txt#L1)):*
> ```help
> - Fixed a crash that would occur because a Provider would be listed twice in the filter screen.
> ```

nit: I suggest a slight rephrasing:

`Fixed a crash in the filter screen that could happen depending on available Providers.`



_Code quote:_
```help
- Fixed a crash that would occur because a Provider would be listed twice in the filter screen.
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395#-OEZNsXt4WS9v1HWmyjw:-OEZRIMDD4-74Y_uP-BK:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcf40d4446e2de55a09ada64606644988a3b0c0f/android/src/main/play/release-notes/en-US/default.txt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest a slight rephrasing:

`Fixed a crash in the filter screen that could happen depending on available Providers.`
</blockquote></details>

Done

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395#-OEZNsXt4WS9v1HWmyjw:-OEZUAGt6h3BiHIn3MQr:bx9a24f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcf40d4446e2de55a09ada64606644988a3b0c0f/android/src/main/play/release-notes/en-US/default.txt#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Crowdin complains about a missing newline

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395#-OEZNsXt4WS9v1HWmyjw:-OEZUeghE9X-v5Wj5Z1n:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcf40d4446e2de55a09ada64606644988a3b0c0f/android/src/main/play/release-notes/en-US/default.txt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Crowdin complains about a missing newline
</blockquote></details>

Fixed

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395#-:-OEZUxBN0w4OKjeVHJPu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
