### PR TITLE
Master by ip

### PR DESCRIPTION
**Pull request by jvff**
**If this PR is merged, PR #97 must be closed.**

This is an initial attempt at using an IP address to connect to the master API server. It stores the IP in a cache and re-uses it when possible. If the cache is empty, the IP is resolved and stored in the cache.

This version attempts to minimize the changed code. I also wrote a different version that's more complex, but I felt that could be a better option. I pushed both as PRs so everyone can take a look and see which option is better. It might be better to choose one first then do a more fine-grained review of the code to avoid duplicated effort (sorry about that). After an option is chosen, the other PR must be closed.

Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/96)

### CODE REVIEW

**Comment by pronebird** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by pronebird** [comment]
I know there are some issues with

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 219 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yXYeD-k0PBnXzofuF:-L7yXYeD-k0PBnXzofuG:bmokeh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-daemon/src/main.rs#L219)):*
> ```Rust
>         );
> 
>         let api_address_cache_dir = resource_dir.clone();
> ```

Maybe we shouldn't save the cache to resources folder. I always thought of it as a read-only assets folder. The same way `relays.json` shipped with the app is not overwritten but instead used as a baseline and later updated and saved into a separate location on disk, i.e. we have caches directory or something like that.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-:-L7yVePW5XlB6Ys-Jh93:bw552dd)*

**Comment by pronebird** [comment]
LOL I accidentally left a comment two days ago ignore it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-rpc/src/lib.rs, line 31 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yad-e22bvTl_fIWU7:-L7yad-e22bvTl_fIWU8:bq9p8ar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/lib.rs#L31)):*
> ```Rust
> use chrono::DateTime;
> use chrono::offset::Utc;
> use hyper::header::Host;
> ```

If I get it right, hyper is used internally by jsonrpc_client_http. Following the practice of re-exporting dependent symbols something tel

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-:-L7yZiyE2Nd780mDtAwH:bvofxce)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 219 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yXYeD-k0PBnXzofuF:-L7yiZ_KLKmwIYJkCoQo:bplw33) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-daemon/src/main.rs#L219)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Maybe we shouldn't save the cache to resources folder. I always thought of it as a read-only assets folder. The same way `relays.json` shipped with the app is not overwritten but instead used as a baseline and later updated and saved into a separate location on disk, i.e. we have caches directory or something like that.
</blockquote></details>

Yes. The `resource_dir` is read only. On Windows it's going to be `C:\Program Files\MullvadVPN\` or similar and on macOS it will be `/Applications/MullvadVPN.app/Contents/Resources/`.

Look at how we cache the `relays.json` for example code. We do read `relays.json` from `resource_dir` as a fallback if the cached one does not exist. This will result in the one shipped with the installer of the app, but that is read only.

---

*[mullvad-rpc/src/api_address.rs, line 14 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yjJA4MSYhshelBl-b:-L7yjJA4MSYhshelBl-c:bfzu1ac) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L14)):*
> ```Rust
> #[derive(Clone, Debug, Deserialize, Serialize)]
> struct CachedAddress {
>     ip: String,
> ```

Why not use an `IpAddr` or even `Ipv4Addr`?

---

*[mullvad-rpc/src/lib.rs, line 31 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yad-e22bvTl_fIWU7:-L7yk0eUvWOp1yKF7ffs:b-z2jnm5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/lib.rs#L31)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

If I get it right, hyper is used internally by jsonrpc_client_http. Following the practice of re-exporting dependent symbols something tel
</blockquote></details>

Indeed. With the addition of setting custom headers we do expose hyper types in the public API of `jsonrpc_client_http`, thus should we re-export those types as well. The type we expose is just the `Header` trait. But since that trait is kind of useless on its own (one need the implementing types) we should likely export all of the headers module or all of `hyper` with `pub extern crate hyper;`. See https://github.com/mullvad/jsonrpc-client-rs/pull/34

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 219 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yXYeD-k0PBnXzofuF:-L7yoo0uSaUp7F-OFVRz:b-5vo6rx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-daemon/src/main.rs#L219)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes. The `resource_dir` is read only. On Windows it's going to be `C:\Program Files\MullvadVPN\` or similar and on macOS it will be `/Applications/MullvadVPN.app/Contents/Resources/`.

Look at how we cache the `relays.json` for example code. We do read `relays.json` from `resource_dir` as a fallback if the cached one does not exist. This will result in the one shipped with the installer of the app, but that is read only.
</blockquote></details>

But we should ship the app with an IP in a file in the installation directory. To be able to give the IP to those who will fail the DNS resolution on first try. So it should likely work more or less exactly as the relays feature. One cached IP and one IP in the resource dir. And if the cached one is too old then try to update it. If anything fails we can always fallback to the one in the resource dir, which must be there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/Cargo.toml, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yq1jpsG42tbUXs78t:-L7yq1jpsG42tbUXs78u:b-vywrw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/Cargo.toml#L15)):*
> ```TOML
> jsonrpc-client-http = { git = "https://github.com/mullvad/jsonrpc-client-rs" }
> serde = "1.0"
> serde_derive = "1.0"
> ```

You can avoid depending directly on `serde_derive`. There is a trick around that. You can add `features = ["derive"]` to your `serde` dependency and import it with `#[macro_use]` and it will pull in the macros for you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L7yucWDtd9cxWFIIe1K:b4nm2bx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
> ```Rust
>     fn caches_resolved_address() {
>         let temp_dir = TempDir::new("address-cache-test").unwrap();
>         let address = api_address(Some(temp_dir.path()));
> ```

This test performs an actual DNS lookup, right? I'm generally of the viewpoint that a unit test should test the thing it's testing without relying on any external components, not even other components of the same codebase, even less on disk or network. That is the responsibility of a more full blown system test. On the other hand it can be hard to design code to allow for this. An awful lot of mocks are usually required :( But on the other hand it can be hard to test if they rely on internet etc.

---

*[mullvad-rpc/src/lib.rs, line 48 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yrajeffcEgtNrIsaw:-L7yrajeffcEgtNrIsax:bgc94g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/lib.rs#L48)):*
> ```Rust
> 
> mod api_address;
> use api_address::*;
> ```

I usually try to avoid wildcard imports. They make it harder to track down what types are in use. The exception I sometimes make is if I publicly want to re-export some module or if the module I'm importing is very close and obvious what it contains, like this:

```rust
pub mod ip {
    /// nice to put IPv4 stuff in separate module (usually separate file) for easy browsing and clarity...
    mod ipv4 { ... }
    /// But should still be part of public API of `ip` module.
    pub use ipv4::*;
}
```
or
```rust
mod errors {
    pub struct Error {...}
    pub enum ErrorKind {...}
}
use errors::*;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by jvff** [comment]
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[mullvad-rpc/Cargo.toml, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yq1jpsG42tbUXs78t:-L7zcmjBOJBklbaaeeM6:b-orag1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/Cargo.toml#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You can avoid depending directly on `serde_derive`. There is a trick around that. You can add `features = ["derive"]` to your `serde` dependency and import it with `#[macro_use]` and it will pull in the macros for you.
</blockquote></details>

Done, that's pretty neat!

---

*[mullvad-rpc/src/api_address.rs, line 14 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yjJA4MSYhshelBl-b:-L7zdQiSYVkINREKZpZU:b76jbm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why not use an `IpAddr` or even `Ipv4Addr`?
</blockquote></details>

I considered using `SocketAddr` instead, but I assumed that it didn't implement `Serialize` and `Deserialize`. I only checked that assumption after Odd asked the same question. I found out that it does implement those traits, so I can use them directly.

I updated it to use `SocketAddr`. Are there any reasons to ignore the port?

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L7zgBqDICxERRUKYBKI:b-6bymyy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This test performs an actual DNS lookup, right? I'm generally of the viewpoint that a unit test should test the thing it's testing without relying on any external components, not even other components of the same codebase, even less on disk or network. That is the responsibility of a more full blown system test. On the other hand it can be hard to design code to allow for this. An awful lot of mocks are usually required :( But on the other hand it can be hard to test if they rely on internet etc.
</blockquote></details>

I prefer minimal test cases, but I'd rather not complicate too much the code to make the tests simpler.

Any ideas on how to simplify this? Or should I move the tests to be in the `tests` directory?

---

*[mullvad-rpc/src/lib.rs, line 48 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yrajeffcEgtNrIsaw:-L7zhyESWbIUk3VFI5JP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/lib.rs#L48)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I usually try to avoid wildcard imports. They make it harder to track down what types are in use. The exception I sometimes make is if I publicly want to re-export some module or if the module I'm importing is very close and obvious what it contains, like this:

```rust
pub mod ip {
    /// nice to put IPv4 stuff in separate module (usually separate file) for easy browsing and clarity...
    mod ipv4 { ... }
    /// But should still be part of public API of `ip` module.
    pub use ipv4::*;
}
```
or
```rust
mod errors {
    pub struct Error {...}
    pub enum ErrorKind {...}
}
use errors::*;
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by faern** [comment]
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/Cargo.toml, line 15 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yq1jpsG42tbUXs78t:-L81rVCO5b_0yNmGB8Wz:bik6uv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/Cargo.toml#L15)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done, that's pretty neat!
</blockquote></details>

Not pushed yet? Or is reviewable acting up again maybe.

---

*[mullvad-rpc/src/api_address.rs, line 14 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yjJA4MSYhshelBl-b:-L81rbTN1N_jchIz0mn4:b-d3812g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L14)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I considered using `SocketAddr` instead, but I assumed that it didn't implement `Serialize` and `Deserialize`. I only checked that assumption after Odd asked the same question. I found out that it does implement those traits, so I can use them directly.

I updated it to use `SocketAddr`. Are there any reasons to ignore the port?
</blockquote></details>

Do we need the port at all, where do you get it from? Don't we just connect to `https://193.138.219.46/rpc` anyway? The port is given by the protocol and automatically figured out by hyper. We basically want to act as our own DNS cache, and DNS does not include the port.

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L81s6hbAPk4vU_VdDrk:bvkcnr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I prefer minimal test cases, but I'd rather not complicate too much the code to make the tests simpler.

Any ideas on how to simplify this? Or should I move the tests to be in the `tests` directory?
</blockquote></details>

Yeah, if the test uses the network and filesystem I think it should be considered an integration test. So please move it to the `tests` directory.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L81oEDU8AGfhVL-8Vcj:bnnmoq9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yeah, if the test uses the network and filesystem I think it should be considered an integration test. So please move it to the `tests` directory.
</blockquote></details>

We can add a mocking DNS resolver. Can be a function passed to `api_address` as a second argument.

If it's not too annoying to keep the object around, I'd go for a design that would allow to pass the resolver during initialization. This will likely improve the performance too so we don't read/write to disk on each request. (I realize though that we want a minimal design - less code). Hard choices.

```
trait MyDnsResolver {
  pub fn resolve(domain: String) -> Result<Ip>;
}

struct MyCachingDnsResolver<T: MyDnsResolver> {
  resolver: T;
};

impl<T> MyCachingDnsResolver<T> {
  pub new(dnsResolver: T) {
    self.resolver = dnsResolver;
  }
  
  // etc..
}
```

Then mocking resolver and the real one can be implemented separately and used during initialization of the IP cache object.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by pronebird** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/Cargo.toml, line 15 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yq1jpsG42tbUXs78t:-L81tnvx0e3E_4J2mmbV:b-6pvwsb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/Cargo.toml#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not pushed yet? Or is reviewable acting up again maybe.
</blockquote></details>

I don't see the change yet either..

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/src/api_address.rs, line 14 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yjJA4MSYhshelBl-b:-L81ttgc-ndXGeIvA6PU:b-vqzbh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do we need the port at all, where do you get it from? Don't we just connect to `https://193.138.219.46/rpc` anyway? The port is given by the protocol and automatically figured out by hyper. We basically want to act as our own DNS cache, and DNS does not include the port.
</blockquote></details>

Yep, the DNS resolution does not depend on HTTP port in the address so we can easily drop it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/src/api_address.rs, line 14 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yjJA4MSYhshelBl-b:-L81tpJ480j_lKnQP3Ev:bwjuusx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L14)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Yep, the DNS resolution does not depend on HTTP port in the address so we can easily drop it.
</blockquote></details>

Ah... I see, because you use `SocketAddr` to do the domain name resolution for you. Yeah this is sadly the only way to do DNS resolution in stable Rust. But you can just have any hardcoded dummy port and then throw it away and store the IP.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L81uXfi2SjJl-NS-z5n:b-h32whu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

We can add a mocking DNS resolver. Can be a function passed to `api_address` as a second argument.

If it's not too annoying to keep the object around, I'd go for a design that would allow to pass the resolver during initialization. This will likely improve the performance too so we don't read/write to disk on each request. (I realize though that we want a minimal design - less code). Hard choices.

```
trait MyDnsResolver {
  pub fn resolve(domain: String) -> Result<Ip>;
}

struct MyCachingDnsResolver<T: MyDnsResolver> {
  resolver: T;
};

impl<T> MyCachingDnsResolver<T> {
  pub new(dnsResolver: T) {
    self.resolver = dnsResolver;
  }
  
  // etc..
}
```

Then mocking resolver and the real one can be implemented separately and used during initialization of the IP cache object.

</blockquote></details>

I have a love-hate relationship with mocking. It allows much better and deterministic testing. But it's often quite verbose and requires a lot of code. The good thing with having a mock DNS resolver here is that we can verify that the correct IP is written to the cache file. If we use a real DNS we don't know what IP it does resolve to and can thus not verify the content of the file. Right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by jvff** [comment]
*[mullvad-rpc/Cargo.toml, line 15 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yq1jpsG42tbUXs78t:-L81uBoXl0uR_YN35tLQ:b-fcu5i3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/Cargo.toml#L15)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I don't see the change yet either..
</blockquote></details>

Sorry, I implemented the change in commit 7d93878 using the `serde` feature, but I forgot to actually remove the `serde_derive` dependency. Then, in commit 6c04634, I don't actually needed the `derive` feature, so I removed it. But `serde_derive` dependency is still left over there, which is why the revision appears like nothing changed. I'll fix it and push it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by jvff** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[mullvad-rpc/src/api_address.rs, line 14 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yjJA4MSYhshelBl-b:-L822YvD3XXFxjWBRaKb:b-vfr2g5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah... I see, because you use `SocketAddr` to do the domain name resolution for you. Yeah this is sadly the only way to do DNS resolution in stable Rust. But you can just have any hardcoded dummy port and then throw it away and store the IP.
</blockquote></details>

Done, replaced `SocketAddr` with `IpAddr`.

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L822fvNzUDeVVkMUmD3:bbgeryd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I have a love-hate relationship with mocking. It allows much better and deterministic testing. But it's often quite verbose and requires a lot of code. The good thing with having a mock DNS resolver here is that we can verify that the correct IP is written to the cache file. If we use a real DNS we don't know what IP it does resolve to and can thus not verify the content of the file. Right?
</blockquote></details>

I share the sentiment. I love mocks, but I try to avoid them when they introduce more code to be tested.

I had an idea for this case though. I think I can just use the `ToSocketAddrs` trait. I'll use a generic type that has the constraint `T: Into<String> + ToSocketAddrs` and use `String` as the default type parameter. Then I can just leave the default type for normal operation and change the type parameter in the tests to a mock type. I'm not sure if it's going to work, but I'll post an update when I get some results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by jvff** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[mullvad-rpc/src/api_address.rs, line 118 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yucWC_tyhQBOxCvrZ:-L82F0yhBnsM3R8S_yvW:b-6virwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-rpc/src/api_address.rs#L118)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I share the sentiment. I love mocks, but I try to avoid them when they introduce more code to be tested.

I had an idea for this case though. I think I can just use the `ToSocketAddrs` trait. I'll use a generic type that has the constraint `T: Into<String> + ToSocketAddrs` and use `String` as the default type parameter. Then I can just leave the default type for normal operation and change the type parameter in the tests to a mock type. I'm not sure if it's going to work, but I'll post an update when I get some results.
</blockquote></details>

Ok, pushed the attempt so everyone can see. IMHO it's not looking very good. I think I'm leaning towards implementing @pronebird's suggestion of a `DnsResolver` trait.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by pinkisemils** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Comment by jvff** [comment]
Review status: 1 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[mullvad-daemon/src/main.rs, line 219 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96#-L7yXYeD-k0PBnXzofuF:-L83znEsnrhVPMO2HbBt:b-5lwq62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a875ffaf92e6041125903957db1e42868df366ed/mullvad-daemon/src/main.rs#L219)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

But we should ship the app with an IP in a file in the installation directory. To be able to give the IP to those who will fail the DNS resolution on first try. So it should likely work more or less exactly as the relays feature. One cached IP and one IP in the resource dir. And if the cached one is too old then try to update it. If anything fails we can always fallback to the one in the resource dir, which must be there.
</blockquote></details>

Done. Behaviour should now be correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/96)*

**Comment by mvd-ows** [comment]
Reviewed 1 of 7 files at r1, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/96)*

**Pull request closed without merging**
