### PR TITLE
Fix Swiftlint warnings in PacketTunnelProvider

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
Refactoring to fix lint error `function_body_length` and/or `cyclomatic_complexity`.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107#-:-NdZw1lx37HrucF93PYa:b-nmg2wc)* status: 0 of 1 files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107#-Ne8OZkH6APRNZLJSMmU:-Ne8OZkH6APRNZLJSMmV:b-aq6chs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/PacketTunnel/PacketTunnelProvider.swift#L128)):*
> ```Swift
> 
>     override init() {
>         var loggerBuilder = LoggerBuilder()
> ```

This has to execute first because If you initialize `Logger(name: "<name>")` before configuring the logging pipeline then you'd end up with logger that only `print()` to console.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107#-Ne8OZkH6APRNZLJSMmU:-Ne8Q24h5Wz43sIYmZNU:b-89xse9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/PacketTunnel/PacketTunnelProvider.swift#L128)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This has to execute first because If you initialize `Logger(name: "<name>")` before configuring the logging pipeline then you'd end up with logger that only `print()` to console.
</blockquote></details>

Aha, will look into it.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107#-Ne8OZkH6APRNZLJSMmU:-NeD2WPg4p-gKuHkF3Mz:bevjgfg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/PacketTunnel/PacketTunnelProvider.swift#L128)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Aha, will look into it.
</blockquote></details>

Just to clarify, even a call to eg. `REST.AddressCache` below (which in turns relies on `Logger`) will trigger the global bootstrapping function to connect to an unconfigured logging pipeline? (as described on Slack)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107#-Ne8OZkH6APRNZLJSMmU:-NeHrU97B6AdOQgLI-Ii:bikpnaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/PacketTunnel/PacketTunnelProvider.swift#L128)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Just to clarify, even a call to eg. `REST.AddressCache` below (which in turns relies on `Logger`) will trigger the global bootstrapping function to connect to an unconfigured logging pipeline? (as described on Slack)
</blockquote></details>

Yes. You can create a static function, i.e `class func configureLogger()` and call `Self.configureLogger()` first thing in `init()` then you can create individual `Logger`s safely within initializer.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107#-Ne8OZkH6APRNZLJSMmU:-NecZjrpBGy5DGFQ2non:btoa9w5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7444ac28c93fbdc6cfbbae648fa19eec70e57077/ios/PacketTunnel/PacketTunnelProvider.swift#L128)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Yes. You can create a static function, i.e `class func configureLogger()` and call `Self.configureLogger()` first thing in `init()` then you can create individual `Logger`s safely within initializer.
</blockquote></details>

I did some other refactoring before I saw this. Unless they're undesirable the warning has been dealt with.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
