### PR TITLE
Log when certain functions are called an excessive number of times

### PR DESCRIPTION
**Pull request by dlon**
Fix DES-683.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-types/src/error.rs` line 79 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsMvg7IDJge6M0cVXDG:-NsMvg7IDJge6M0cVXDH:bwsj6oj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc6bccc65cc5cf8363edb87d89a930143a52183d/talpid-types/src/error.rs#L79)):*
> ```XML
> 
>     #[macro_export]
>     macro_rules! detect_flood {
> ```

I think a doc-comment would be very nice to have, so that if I see `detect_flood!` being used somewhere I can quickly bring up the documentation at the call site instead of having to go to this source to figure out its purpose :blush:



_Code quote:_
```XML
    #[macro_export]
    macro_rules! detect_flood {
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-types/src/error.rs` line 79 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsMvg7IDJge6M0cVXDG:-NsNL2JqDdU62QURbpCw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc6bccc65cc5cf8363edb87d89a930143a52183d/talpid-types/src/error.rs#L79)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think a doc-comment would be very nice to have, so that if I see `detect_flood!` being used somewhere I can quickly bring up the documentation at the call site instead of having to go to this source to figure out its purpose :blush:
</blockquote></details>

Done.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-:-NsOageH5aAEdyi-WqqX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`talpid-types/src/error.rs` line 72 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTdLxl2JFUboVSGZVF:-NsTdLxl2JFUboVSGZVG:bzb9cop) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L72)):*
> ```XML
> }
> 
> pub mod flood {
> ```

I'm not a fan of more code ending up in this crate. But not going to block it this time since I don't have a concrete better suggestion right now.
___
*[`talpid-types/src/error.rs` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsT_a6z7t2BH7rRs4XJ:-NsT_a6z7t2BH7rRs4XK:b-dgfqm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L81)):*
> ```XML
>     /// period of `CALLS_INTERVAL`.
>     ///
>     /// The caller of this macro must have `once_cell` and `log` as dependencies.
> ```

Instead of declaring that the caller crate must have `once_cel` and `log` I think it would be cleaner if the crate defining the macro re-exports these crates and uses `$crate::once_cell::...` etc instead.

Implicitly the macro also relies on special versions of these crates. If `log 0.5` is released one day, this macro might not be compatible.

The reexports can be tagged with `#[doc(hidden)]` since they are not supposed to be part of the "public" API of this crate.
___
*[`talpid-types/src/error.rs` line 86 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTb-w94X8k24_lbOYC:-NsTb-w94X8k24_lbOYD:b-hucn88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L86)):*
> ```XML
>         () => {{
>             static FLOOD: ::once_cell::sync::Lazy<
>                 ::std::sync::Mutex<talpid_types::flood::DetectFlood>,
> ```

This is fragile against the calling crate importing `talpid_types` under a different name. Can we use `$crate` here also instead?
___
*[`talpid-types/src/error.rs` line 91 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTczO68u4NphcTLoQF:-NsTczO68u4NphcTLoQG:b99vh93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L91)):*
> ```XML
>             });
>             if FLOOD.lock().unwrap().bump() {
>                 ::log::debug!("Flood: {}, line {}, col {}", file!(), line!(), column!());
> ```

Good log message! But should we maybe consider bumping this to at least a warning? I know we add it to debug something, but if this log line is ever executed it means the process is in a pretty bad state, so it's really a warning.
___
*[`talpid-types/src/error.rs` line 120 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTcOCc5Zb3ogHabz--:-NsTcOCc5Zb3ogHabz-0:bnjtc0d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L120)):*
> ```XML
>                 let was_less = self.counter < CALLS_THRESHOLD;
>                 self.counter = self.counter.saturating_add(1);
>                 return was_less && self.counter >= CALLS_THRESHOLD;
> ```

A comment here would be justified IMHO. It took me a few iterations of thinking before I realized why we check the counter against the threshold twice.. Because we only want to return `true` *once*, right?

Can't this be simplified to just `self.counter == CALLS_THRESHOLD` to only return `true` exactly when we hit the threshold?
___
*[`talpid-types/src/error.rs` line 122 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTcC0m82Ylc64hJCcc:-NsTcC0m82Ylc64hJCcd:b5aqdq5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L122)):*
> ```XML
>                 return was_less && self.counter >= CALLS_THRESHOLD;
>             }
>             false
> ```

IMHO it would be slightly more straight forward if this was moved into the if branch. That removes the early return. The `false` is only ever hit when we hit the if branch anyway.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @faern and @MarkusPettersson98)

___
*[`talpid-types/src/error.rs` line 72 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTdLxl2JFUboVSGZVF:-NsTt8DEERi9VkMkHBwQ:b-jnc2yh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L72)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not a fan of more code ending up in this crate. But not going to block it this time since I don't have a concrete better suggestion right now.
</blockquote></details>

Same. If we don't mind crate inflation, I could create `talpid-log` or `talpid-debug`.
___
*[`talpid-types/src/error.rs` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsT_a6z7t2BH7rRs4XJ:-NsTtPMXDnbKKgKA5813:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Instead of declaring that the caller crate must have `once_cel` and `log` I think it would be cleaner if the crate defining the macro re-exports these crates and uses `$crate::once_cell::...` etc instead.

Implicitly the macro also relies on special versions of these crates. If `log 0.5` is released one day, this macro might not be compatible.

The reexports can be tagged with `#[doc(hidden)]` since they are not supposed to be part of the "public" API of this crate.
</blockquote></details>

Done.
___
*[`talpid-types/src/error.rs` line 86 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTb-w94X8k24_lbOYC:-NsTuZAGABqlVMfzeEa5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L86)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is fragile against the calling crate importing `talpid_types` under a different name. Can we use `$crate` here also instead?
</blockquote></details>

Done.
___
*[`talpid-types/src/error.rs` line 120 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTcOCc5Zb3ogHabz--:-NsTunJxA_i7FjUpHgPH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L120)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

A comment here would be justified IMHO. It took me a few iterations of thinking before I realized why we check the counter against the threshold twice.. Because we only want to return `true` *once*, right?

Can't this be simplified to just `self.counter == CALLS_THRESHOLD` to only return `true` exactly when we hit the threshold?
</blockquote></details>

Done.
___
*[`talpid-types/src/error.rs` line 122 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsTcC0m82Ylc64hJCcc:-NsTvDYw3mjW7X-5liV4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L122)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

IMHO it would be slightly more straight forward if this was moved into the if branch. That removes the early return. The `false` is only ever hit when we hit the if branch anyway.
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`talpid-types/Cargo.toml` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmUm0O4qRoZTaG38YC:-NsmUm0O4qRoZTaG38YD:bt3q2b2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/Cargo.toml#L20)):*
> ```TOML
> thiserror = { workspace = true }
> zeroize = "1.5.7"
> log = "0.4"
> ```

`log` is also available as a workspace dependency.
___
*[`talpid-types/src/error.rs` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsT_a6z7t2BH7rRs4XJ:-NsmUyub3eEGBF6yXxCd:b6y7bo7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L81)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Macro documentation not updated yet.
___
*[`talpid-types/src/error.rs` line 92 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmWHqH6TEeRwONZy8r:-NsmWHqH6TEeRwONZy8s:b-tjouos) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/src/error.rs#L92)):*
> ```XML
>                 ::std::sync::Mutex<talpid_types::flood::DetectFlood>,
>             > = $crate::flood::once_cell::sync::Lazy::new(|| {
>                 ::std::sync::Mutex::new($crate::flood::DetectFlood::default())
> ```

`Mutex::new` is a `const fn`. If we change `last_clear: Instant` to `last_clear: Option<Instant>` we can have a `const fn `DetectFlood::new` and not need to deal with all the lazy stuff at all. It could just be a regular static. Would that not be simpler? At least it would get rid of needing `once_cell`. It would slightly complicate `bump`, but I think it can be done without much trouble.

What do you think? I think that would be somewhat simpler.
___
*[`talpid-types/src/error.rs` line 129 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmVMsOAx_SH1UwKfXT:-NsmVMsOAx_SH1UwKfXU:b-jjsm1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/src/error.rs#L129)):*
> ```XML
>             } else {
>                 self.counter = self.counter.saturating_add(1);
>                 self.counter == CALLS_THRESHOLD
> ```

If we move the `log::warn!` call into here, we do not need to re-export `log` to make it available to the caller, since it would then not be part of the macro.

Then the `DetectFlood` would be coupled to the logging, but that's what it will only ever be used for, so does it matter? :thinking:

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`talpid-types/src/error.rs` line 129 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmVMsOAx_SH1UwKfXT:-NsmeDiKCUgOrlnxZcdB:b8ebpen) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/src/error.rs#L129)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If we move the `log::warn!` call into here, we do not need to re-export `log` to make it available to the caller, since it would then not be part of the macro.

Then the `DetectFlood` would be coupled to the logging, but that's what it will only ever be used for, so does it matter? :thinking:
</blockquote></details>

Aah, wait. I realize we depend on `file!`, `line!` etc to be inserted in the call position. Darn. They could theoretically be sent in as arguments, but it makes the solution dirtier. Let's ignore this, keeping the logging in the macro is fine!

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @faern and @MarkusPettersson98)

___
*[`talpid-types/Cargo.toml` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmUm0O4qRoZTaG38YC:-NssHpBL2mHdCHZ7jUGm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/Cargo.toml#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`log` is also available as a workspace dependency.
</blockquote></details>

Done.
___
*[`talpid-types/src/error.rs` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsT_a6z7t2BH7rRs4XJ:-NssHqHFDjvFNJHqP8lM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb994bc96dff8517c6dc6c7ddfe83306b49f9d27/talpid-types/src/error.rs#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Macro documentation not updated yet.
</blockquote></details>

Done.
___
*[`talpid-types/src/error.rs` line 92 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmWHqH6TEeRwONZy8r:-NssJPGWETWSFStelYDk:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/src/error.rs#L92)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`Mutex::new` is a `const fn`. If we change `last_clear: Instant` to `last_clear: Option<Instant>` we can have a `const fn `DetectFlood::new` and not need to deal with all the lazy stuff at all. It could just be a regular static. Would that not be simpler? At least it would get rid of needing `once_cell`. It would slightly complicate `bump`, but I think it can be done without much trouble.

What do you think? I think that would be somewhat simpler.
</blockquote></details>

Done!

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-:-NssM-MDDcv2oYjxpPDJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-types/src/error.rs` line 92 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903#-NsmWHqH6TEeRwONZy8r:-NssLmLC-eirv2HiEA7D:b8wvvf0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57298ae14621aab283853278cfca7c0577517d41/talpid-types/src/error.rs#L92)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

NICE! The `get_or_insert` there really made in sparkling :heart:

**Pull request merged**
