### PR TITLE
Add offline monitor docs

### PR DESCRIPTION
**Pull request by pinkisemils**
I've added a small paragraph about offline detection for each of the platforms we support in the architecture docs. I don't expect all of the reviewers to read all of the changes, only the bits you'd feel most comfortable reviewing.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)

### CODE REVIEW

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-:-MWzviQOCpQsJSY457bV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[docs/architecture.md, line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1TFFW4spNPqUdoR0J:-MX1TFFXCTV4DTCILeWn:b-w0czm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L148)):*
> ```Markdown
> ### Detecting device offline
> The tunnel state machine has an offline monitor that tries to detect when a device will certainly
> not be able to connect to a tunnel or reach the API without sending any traffic. In general, this
> ```

What does "without sending any traffic" mean? If the device is offline sending traffic is not even possible.... Oh wait, I think this is a misplaced modifier? I think you should separate how it's implemented (without sending any traffic) and what the purpose is (certainly not able to establish tunnels or talk to the API.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[docs/architecture.md, line 147 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1Vu9rDpie1V2-mdSw:-MX1Vu9s1JcMvvJ8P3Qu:b-m6ojid) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L147)):*
> ```Markdown
> 
> ### Detecting device offline
> The tunnel state machine has an offline monitor that tries to detect when a device will certainly
> ```

Nit. But try to leave one empty line after the headlines before the paragraphs starts. That's how the rest of the document is laid out, and it makes seeing the headlines way easier IMO.
___
*[docs/architecture.md, line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1X9kZ5eXnuuozJNtp:-MX1X9kZ5eXnuuozJNtq:bkonomh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L154)):*
> ```Markdown
> #### Windows
> On Windows, connectivity is inferred if there exists an enabled interface with either an IPv4 or an
> IPv6 address and the machine is not suspended.
> ```

My understanding is that the only reason why we listen for suspend events is that the virtual adapter is not really ready just when the computer wakes up from sleep. So we use the suspend/wakeup events to stay in the offline mode from just before suspend until a few seconds after wakeup.

I think it's important to describe the actual reason here: virtual adapter (TAP) breaking/going nuts if we try to use it too fast after wakeup. Because being offline when suspended is kind of given, the computer is not even running. So the current text is a bit confusing, since I as a reader have no idea why we need to care about the suspend.
___
*[docs/architecture.md, line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1WCY-Bv9eJq6zav3A:-MX1WCY-Bv9eJq6zav3B:b-v41hsh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L165)):*
It's not technically random. Or well. It's random as in https://xkcd.com/221/.. But..

I think it would be better formulated as something along these lines:

> ... checking if a public IP on the internet is routable. Currently the Mullvad API IP is used, but the actual IP does not matter as long as it's not a local one.
___
*[docs/architecture.md, line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1Y9n39HLoBqLkbhmq:-MX1Y9n39HLoBqLkbhmr:b6t94ip) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L171)):*
> ```Markdown
> #### macOS
> On macOS,  the offline monitor uses [`SCNetworkReachability`] callbacks to
> detect change in connectivity and then enumerates network interfaces via [`SCDynamicStore`] and
> ```

change**s**?
___
*[docs/architecture.md, line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1YRyw9yag1eySi-z4:-MX1YRyw9yag1eySi-z5:bffdlah) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L175)):*
> ```Markdown
> 
> #### Issues
> After coming back from boot, the network reachability callback won't be invoked until macOS has done
> ```

s/boot/sleep? Maybe boot works here, but I have never used it in that way.

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[docs/architecture.md, line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1TFFW4spNPqUdoR0J:-MX1orZn49DXTKTHYyKP:b-3rpnjo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L148)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What does "without sending any traffic" mean? If the device is offline sending traffic is not even possible.... Oh wait, I think this is a misplaced modifier? I think you should separate how it's implemented (without sending any traffic) and what the purpose is (certainly not able to establish tunnels or talk to the API.
</blockquote></details>

I was under the impression that from the outset, not sending any traffic was a requirement.
___
*[docs/architecture.md, line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1X9kZ5eXnuuozJNtp:-MX24kESBXi8wLe2bHDv:b4n8288) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L154)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

My understanding is that the only reason why we listen for suspend events is that the virtual adapter is not really ready just when the computer wakes up from sleep. So we use the suspend/wakeup events to stay in the offline mode from just before suspend until a few seconds after wakeup.

I think it's important to describe the actual reason here: virtual adapter (TAP) breaking/going nuts if we try to use it too fast after wakeup. Because being offline when suspended is kind of given, the computer is not even running. So the current text is a bit confusing, since I as a reader have no idea why we need to care about the suspend.
</blockquote></details>

I hope I've added enough detail about the tunnel adapters now.
___
*[docs/architecture.md, line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX1WCY-Bv9eJq6zav3A:-MX24jIyBv6aFhQELToJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/015c6e2a526cefe7635016abd4c2d99d9e5f6f5e/docs/architecture.md#L165)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's not technically random. Or well. It's random as in https://xkcd.com/221/.. But..

I think it would be better formulated as something along these lines:

> ... checking if a public IP on the internet is routable. Currently the Mullvad API IP is used, but the actual IP does not matter as long as it's not a local one.


</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[docs/architecture.md, line 170 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629#-MX2dAq1DvimxdkOCgB7:-MX2dAq1DvimxdkOCgB8:b1xh9bf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79a1c09de90e7eccc8995b269772735cc7e67772/docs/architecture.md#L170)):*
> ```Markdown
> 
> On Linux, connectivity is inferred by checking if there exists a route to a public IP address
> exists. Currently the Mullvad API IP is used, but the actual IP does not matter as long as it's not
> ```

The word exists is duplicated here.

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
