### PR TITLE
Wrap maybenot in a cdylib with a C FFI layer

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165)

### CODE REVIEW

**Review by Serock3 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165)* status: 5 of 13 files reviewed, 6 unresolved discussions (waiting on @hulthe)

___
*[`libmaybenot/libmaybenot.h` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6RyO0Bun0KJuF4J-j:-Nw6RyO0Bun0KJuF4J-k:brgdfbr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/libmaybenot.h#L3)):*
> ```objc
> /* Generated with cbindgen:0.26.0 */
> 
> /* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */
> ```

i guess we leave these lines in even though we aren't adding `cbindgen` as a dep, right?
___
*[`libmaybenot/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6UtWn5P_7lQ3QbGzp:-Nw6UtWoDddxLZ4lrnyv:b-io4ybm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L21)):*
> ```XML
>     // we aren't allowed to look into MachineId, so we need our own id type to use with FFI
>     /// A map from `hash(MachineId)` to `MachineId`
>     machine_id_hashes: HashMap<u64, MachineId>,
> ```

Why do we need to look into it? Does it have something to do with `cbindgen`? Can we not place `MachineId` directly in `MaybenotEvent`?
___
*[`libmaybenot/src/lib.rs` line 124 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6YOjj62z5R80SHedG:-Nw6YOjj62z5R80SHedH:b-33ergj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L124)):*
> ```XML
>             Instant::now(),
>         )
>         .map_err(|e| anyhow!("Failed to initialize framework: {e}"))?;
> ```

It really bugs me that we can't use `.context()` here, but oh well...
___
*[`libmaybenot/src/lib.rs` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6VMTF4vlyZzxV6CBq:-Nw6VMTG0YaegDcRDlzV:b-yeb265) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L138)):*
> ```XML
>         actions: &mut [MaybeUninit<MaybenotAction>],
>         event: MaybenotEvent,
>     ) -> anyhow::Result<u64> {
> ```

Do we want `anyhow` in our public API? Considering Linus discussion on the topic, maybe we should return a bespoke error type, or a dynamic one?
___
*[`libmaybenot/src/lib.rs` line 149 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6Yt184yfsyJk-SsUA:-Nw6Yt184yfsyJk-SsUB:b6kpvxg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L149)):*
> ```XML
>             .map(|action| convert_action(action, &mut self.machine_id_hashes))
>             // write the actions to the out buffer
>             .zip(actions.iter_mut())
> ```

Are we sure that no events are missed here? Actions seems to be allocated with `this.framework.num_machines()` elements, but the description of `trigger_events` fn says "Trigger zero or more `TriggerEvent` for all machines running in the framework". Could it trigger more than one per machine, i.e. more in total than the number of machines?
___
*[`talpid-wireguard/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6_LubErug8iZ1x3nH:-Nw6_LubErug8iZ1x3nI:bvwfiu7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/talpid-wireguard/Cargo.toml#L34)):*
> ```TOML
> surge-ping = "0.8.0"
> maybenot = "1.1"
> libmaybenot = { path = "../libmaybenot" }
> ```

Should this still be present when we make `libmaybenot` a dep of `wireguard-go`?

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165)* status: 5 of 13 files reviewed, 6 unresolved discussions (waiting on @Serock3)

___
*[`libmaybenot/libmaybenot.h` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6RyO0Bun0KJuF4J-j:-Nw92a0P9tgKZnj9kyEQ:b-6n8pcj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/libmaybenot.h#L3)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

i guess we leave these lines in even though we aren't adding `cbindgen` as a dep, right?
</blockquote></details>

I think we should. Those lines are meant to encourage using cbindgen if we want to change the interface at some point. Using cbindgen is safer and imo easier that trying to write bindings by hand.
___
*[`libmaybenot/src/lib.rs` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6UtWn5P_7lQ3QbGzp:-Nw95ZFBD9EIgA_ZnMh6:b-1wj6ma) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L21)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Why do we need to look into it? Does it have something to do with `cbindgen`? Can we not place `MachineId` directly in `MaybenotEvent`?
</blockquote></details>

The problem is that we need to be able to pass the machine id to Go, which means we need a C type for it. If we try to expose MachineId in the FFI, cbindgen won't know what type it is. We could write our own C type for it, I suppose.. but there's no guarantee that the representation of MachineId won't change.

Hmm... We could return a MachneId pointer maybe...
___
*[`libmaybenot/src/lib.rs` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6VMTF4vlyZzxV6CBq:-Nw95G8-3aPtZ5Ib3L7F:b-4s5v9p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L138)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Do we want `anyhow` in our public API? Considering Linus discussion on the topic, maybe we should return a bespoke error type, or a dynamic one?
</blockquote></details>

Good thought. The error handling in libmaybenot needs a lot more polish, I haven't put much thought into it tbh.
___
*[`libmaybenot/src/lib.rs` line 149 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6Yt184yfsyJk-SsUA:-Nw93Ey_8PQE81EeRM6d:b9clmdw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L149)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Are we sure that no events are missed here? Actions seems to be allocated with `this.framework.num_machines()` elements, but the description of `trigger_events` fn says "Trigger zero or more `TriggerEvent` for all machines running in the framework". Could it trigger more than one per machine, i.e. more in total than the number of machines?
</blockquote></details>

I looked into maybenots source-code and it wont return more than 1 action per machine, but it *is* true that neither the docs nor the function signature promises that. This isn't ideal, but I'm not sure how to fix it without making the FFI significantly worse/uglier/less performant.
___
*[`talpid-wireguard/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6_LubErug8iZ1x3nH:-Nw94y82BPNVDhDNjV8y:b-4zty1n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/talpid-wireguard/Cargo.toml#L34)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Should this still be present when we make `libmaybenot` a dep of `wireguard-go`?
</blockquote></details>

Nope, if we somehow make wireguard-go depend directly on libmaybenot, then we wont need this.

**Review by Serock3 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, 5 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @hulthe)

___
*[`libmaybenot/src/lib.rs` line 149 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-Nw6Yt184yfsyJk-SsUA:-NwE56JL0wrt84Bep1mZ:bndkeeb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc9ff8759e8b37cb743178df085e4686fcf8f7f7/libmaybenot/src/lib.rs#L149)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I looked into maybenots source-code and it wont return more than 1 action per machine, but it *is* true that neither the docs nor the function signature promises that. This isn't ideal, but I'm not sure how to fix it without making the FFI significantly worse/uglier/less performant.
</blockquote></details>

Fair enough. We should probably document that decision in the code though.
___
*[`mullvad-api/src/device.rs` line 53 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6165#-NwE5NJI4ISo9drwD0Q3:-NwE5NJI4ISo9drwD0Q4:b-eqvub3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e33a1cd9ca2c6f0809fdcdb10fc210fccb6b691/mullvad-api/src/device.rs#L53)):*
> ```XML
> 
>             // TODO: same_ip on stagemole.eu is bork. remove this before merging to main.
>             same_ip: false,
> ```

Leaving this blocking comment as a reminder to remove this

**Comment by Serock3** [comment]
Outdated in favor of  https://github.com/maybenot-io/maybenot/pull/21

**Pull request closed without merging**
