### PR TITLE
Add experimental support for Windows ARM64

### PR DESCRIPTION
**Pull request by dpaoliello**
Adds experimental support for Windows ARM64:

* Add instructions on how to cross-compile for Windows ARM64.
* Add sections to config.toml.
* Update to version of `maybenot` that uses newer version of `ring` that supports Windows ARM64.
* Ran `cargo update`.
* Updated build scripts to support Windows ARM64 or be architecture agnostic.
* Modified exception logging to support ARM64 context.
* Added ARM64 configs to C++ projects.

NOTE: WireGuard is working, but OpenVPN is not.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)

### CODE REVIEW

**Comment by dlon** [comment]
Thank you so much for these changes! We will try to review and test everything soon.

**Review by dlon — COMMENTED** [review]
> Reviewed 17 of 21 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)* status: 18 of 21 files reviewed, 1 unresolved discussion (waiting on @dpaoliello)

___
*[`gui/tasks/distribution.js` line 405 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315#-O2jPY248LSGmzefFe4j:-O2jPY248LSGmzefFe4k:b-5q6jmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05a68630e2cc066e57a81d15d00beabd97055562/gui/tasks/distribution.js#L405)):*
> ```JavaScript
>   }
>   // Use host architecture.
>   return 'x64';
> ```

Assuming that the host is `x64` won't work on arm. This might deserve a comment at the very least.

**Review by dlon — APPROVED** [review]

**Comment by dpaoliello** [comment]
@dlon this PR is not yet ready for review: first we need the prebuilt `aarch64-pc-windows-msvc` binaries added to the `dist-assets/binaries` submodule. I'm assuming that's something that you or someone else from Mullvad needs to do so that the binaries are built in a trusted way (and, at the very least, the driver needs to be signed).

**Comment by dlon** [comment]
@dpaoliello The binaries are available on the `arm64` branch of `mullvadvpn-app-binaries` (but not yet merged). So feel free to make sure that this PR is ready for review.

**Comment by dpaoliello** [comment]
Working for me locally:
image

**Comment by dlon** [comment]
@dpaoliello It works great using Wireguard! We can get OpenVPN to work as well by building `talpid_openvpn_plugin.dll` for x64 instead of arm. I've added the arm build of wintun.dll to the branch in the binaries submodule.

**Comment by dpaoliello** [comment]
> @dpaoliello It works great using Wireguard! We can get OpenVPN to work as well by building `talpid_openvpn_plugin.dll` for x64 instead of arm. I've added the arm build of wintun.dll to the branch in the binaries submodule.

Yep, using x64 `talpid_openvpn_plugin.dll` worked.

The alternative is to get an ARM64 openvpn.exe - it looks like the last successful build of Mullvad's openvpn repo did include ARM64 Windows, but the artifacts are not expired: https://github.com/mullvad/openvpn/actions/runs/7058997763

**Comment by dlon** [comment]
We don't think it makes sense to block this PR on an ARM64 openvpn build. Let's include an x64 build of `talpid_openvpn_plugin.dll` and we'll take of it later.

We currently cross-compile openvpn using mingw on Linux, which can't target arm, and our branch doesn't even compile with MSVC. We'll likely switch soon, though.

**Comment by dpaoliello** [comment]
> Let's include an x64 build of `talpid_openvpn_plugin.dll` and we'll take of it later.

Done

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 21 files at r1, 8 of 12 files at r4, 4 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @dpaoliello)

___
*[`test/ci-runtests.sh` line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315#-O4ETenLBjEHMqyCy9c3:-O4ETenLBjEHMqyCy9c4:bwwc4a5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81f5a922ce42adae73637562968b4a1494774ac7/test/ci-runtests.sh#L102)):*
> ```Shell
>             ;;
>         windows*)
>             echo "MullvadVPN-${version}_x64.exe"
> ```

The `_x64` suffix is missing now from the function in `test/scripts/test-utils.sh`.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @dpaoliello)

___
*[`ci/buildserver-build.sh` line 228 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315#-O4EVk_o6aeRG7R6p2Jr:-O4EVk_o6aeRG7R6p2Js:bhjp1ok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07838a3580f9b5e73c7f88abe2428cc72d290cce/ci/buildserver-build.sh#L228)):*
> ```Shell
>         pushd "$artifact_dir"
>         for original_file in MullvadVPN-*-dev-*{.deb,.rpm,.exe,.pkg}; do
>             new_file=$(echo "$original_file" | sed -nE "s/^(MullvadVPN-.*-dev-.*)(_amd64\.deb|_x86_64\.rpm|_arm64\.deb|_aarch64\.rpm|\.exe|\.pkg)$/\1$version_suffix\2/p")
> ```

I believe `$version_suffix` should come before `_x64 | _arm64`.

**Comment by dlon** [comment]
Fixed the issues above and also added `apisocks5.exe`.

**Review by raksooo — COMMENTED** [review]
> Reviewed 11 of 21 files at r1, 2 of 12 files at r4, 1 of 6 files at r5, 5 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)* status: 26 of 27 files reviewed, all discussions resolved (waiting on @dlon)

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
