### PR TITLE
Move the title 'Server IP Override' up

### PR DESCRIPTION
**Pull request by rablador**
In the Server IP Override section, the title should be at the same level as other top level titles in pages such as API Access or VPN Settings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)* status: 0 of 10 files reviewed, 2 unresolved discussions

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-NtPrmuy0h2kl3r8x2Wl:-NtPrmuy0h2kl3r8x2Wm:b-mtfoji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift#L76)):*
> ```Swift
>     }
> 
>     private func about() {
> ```

Unrelated changes, but decided to fix anyway.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 380 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-NtPriAu6KucYs4oa1A-:-NtPriAu6KucYs4oa1A0:b-jz1hk1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L380)):*
> ```Swift
>         let sectionIdentifier = snapshot().sectionIdentifiers[section]
> 
>         return switch sectionIdentifier {
> ```

Unrelated, but decided to fix anyway.

**Review by acb-mv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4E-Ek3NnBw1fqexSv:-Nu4E-Ek3NnBw1fqexSw:b-vgcoyf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L58)):*
> ```Swift
>         view.directionalLayoutMargins = UIMetrics.contentHeadingLayoutMargins
> 
>         confgiureNavigation()
> ```

Misspelling of "configure"

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)* status: all files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4Gn1i7N4vAbeB4UOi:-Nu4Gn1i7N4vAbeB4UOj:bmpmfzb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift#L11)):*
> ```Swift
> import UIKit
> 
> /// Header view pinned at the top of ``AccessMethodListViewController``.
> ```

This comment and the next one refers to a different feature
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4GeDQEfpRXsAwoi9T:-Nu4GeDQEfpRXsAwoi9U:bqvhqwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift#L55)):*
> ```Swift
>         let body = NSLocalizedString(
>             "ACCESS_METHOD_HEADER_BODY",
>             tableName: "APIAccess",
> ```

This is the wrong table name, same below
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 380 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-NtPriAu6KucYs4oa1A-:-Nu4GxJ-3sGyu1o5Yl2N:bb7lbs2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L380)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Unrelated, but decided to fix anyway.
</blockquote></details>

nice
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1740 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4H3Cz2iDh-3hZuTem:-Nu4H3Cz2iDh-3hZuTen:b-36vkb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN.xcodeproj/project.pbxproj#L1740)):*
> ```
> 		7A21DACE2A30AA3700A787A9 /* UITextField+Appearance.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = "UITextField+Appearance.swift"; sourceTree = "<group>"; };
> 		7A2882692BA8336600FD9F20 /* VPNSettingsCoordinator.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = VPNSettingsCoordinator.swift; sourceTree = "<group>"; };
> 		7A28826C2BAAC9DE00FD9F20 /* IPOverrideHeaderView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = IPOverrideHeaderView.swift; sourceTree = "<group>"; };
> ```

"Sort by name"

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4Gn1i7N4vAbeB4UOi:-NucEWx3-l9Mo1o4knlH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This comment and the next one refers to a different feature
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4GeDQEfpRXsAwoi9T:-NucFbUAD7vp-LbmpNG4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift#L55)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is the wrong table name, same below
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4E-Ek3NnBw1fqexSv:-NucFnJL0R6lk2MgEAFQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L58)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Misspelling of "configure"
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1740 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-Nu4H3Cz2iDh-3hZuTem:-NucKH8XAe5MTWCrhX4q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bac1805448e3a5b9946221ded0e91d1223cd2a6f/ios/MullvadVPN.xcodeproj/project.pbxproj#L1740)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

"Sort by name"
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-:-NuhEJWx9fl-Wcq0t_vd:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983#-:-NvBjcpq72xo-OqotE1D:bnfp4nl)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by acb-mv — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
