### PR TITLE
Add daemon restart button to split tunneling settings on MacOS

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)

### CODE REVIEW

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 563 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OC3vQBG38nPgVvEihKg:-OC3vQBG38nPgVvEihKh:b-vvdu2a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L563)):*
> ```XML
>             )}
>           </StyledMiniTitle>
>           <Spacing height="8px" />
> ```

I'm not crazy about adding the `Spacing` component. Having the spacing expressed as a marginTop in the individual components didn't feel right either though.

**Review by raksooo — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 563 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OC3vQBG38nPgVvEihKg:-OCE0s5PBBf8G6cXdgWB:b-jfhul4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L563)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I'm not crazy about adding the `Spacing` component. Having the spacing expressed as a marginTop in the individual components didn't feel right either though.
</blockquote></details>

I prefer the marginTop :) Maybe ask Oliver for input? @olmoh.

If all elements should have the same spacing then something like flex gap would be useful but I'm not sure tihs is the case here.

**Review by olmoh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: all files reviewed, 3 unresolved discussions (waiting on @hulthe and @raksooo)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 563 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OC3vQBG38nPgVvEihKg:-OCIKK8-5Ke4KH8HmNgZ:bx9ub2x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L563)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I prefer the marginTop :) Maybe ask Oliver for input? @olmoh.

If all elements should have the same spacing then something like flex gap would be useful but I'm not sure tihs is the case here.
</blockquote></details>

I have nothing against a `<Spacing>` component, but in that case I think we should have a general one in `Layout.tsx` that makes use of the spacing tokens and can be reused.
I think in general though what tends to result in the  is to not let individual elements handle their spacing, but instead let that be handled by their parents. So I would probably default to using wrapper elements with flex-gap here.
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 560 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OCIK-sYB1y2hAP0Bm5Z:-OCIK-sZCmhUmMF5ydtp:b-4gtffy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L560)):*
> ```XML
>             {messages.pgettext(
>               'split-tunneling-view',
>               'Enabled "Fill disk access" and still having issues?',
> ```

Should probably be "Full disk access"
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 565 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OCIMAin0dzxGOl67DWW:-OCIMAin0dzxGOl67DWX:b-38vs51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L565)):*
> ```XML
>           <Spacing height="8px" />
>           <StyledSystemSettingsButton onClick={restartDaemon}>
>             Restart Mullvad Service
> ```

Should this be localized as well?

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @olmoh and @raksooo)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 560 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OCIK-sYB1y2hAP0Bm5Z:-OCIP7xp6fldXB100HXs:bjnc9y4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L560)):*
<details><summary><i>Previously, olmoh (Oliver Mohlin) wrote…</i></summary><blockquote>

Should probably be "Full disk access"
</blockquote></details>

Oops. Nice catch.
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 563 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OC3vQBG38nPgVvEihKg:-OCIPAhC0HwUJt_SxBaC:brlbmol) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L563)):*
<details><summary><i>Previously, olmoh (Oliver Mohlin) wrote…</i></summary><blockquote>

I have nothing against a `<Spacing>` component, but in that case I think we should have a general one in `Layout.tsx` that makes use of the spacing tokens and can be reused.
I think in general though what tends to result in the  is to not let individual elements handle their spacing, but instead let that be handled by their parents. So I would probably default to using wrapper elements with flex-gap here.
</blockquote></details>

Can we use flex-gap here? Given all the spacing is different for each child?
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 565 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OCIMAin0dzxGOl67DWW:-OCIjv4q1XnqRsf41tec:blqnbr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L565)):*
<details><summary><i>Previously, olmoh (Oliver Mohlin) wrote…</i></summary><blockquote>

Should this be localized as well?
</blockquote></details>

Oh yeah I guess it should. "Open System Settings" isn't localized either though. @raksooo?

**Review by olmoh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @hulthe and @raksooo)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 563 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OC3vQBG38nPgVvEihKg:-OCJ3MN08OFiifco8Ypv:b-l8ofeg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L563)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Can we use flex-gap here? Given all the spacing is different for each child?
</blockquote></details>

You would need to use different wrappers with different gaps on them :)

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @hulthe and @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 565 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OCIMAin0dzxGOl67DWW:-OCYzQrY31sBQSl2paTt:b-f9cn0p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L565)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Oh yeah I guess it should. "Open System Settings" isn't localized either though. @raksooo?
</blockquote></details>

Both should be :) We should probably rename `StyledSystemSettingsButton` to something that describes both.

**Review by olmoh — COMMENTED** [review]
> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @hulthe and @raksooo)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx` line 563 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-OC3vQBG38nPgVvEihKg:-OCcjRxl40Yjm6Nl43iD:b-40i0dw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b034f015906e44879825e7a4dd21603d6e2ef99/desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx#L563)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I moved Spacing to Layout.tsx, but if using a wrapper with flex-gap is more ideomatic, i can do that instead
</blockquote></details>

I think both approaches are generally fine, we are doing some work with spacings parallel with this and flex-gap is more in line with what we are doing there. But I think this is fine for now.

**Review by olmoh — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201#-:-OChv_TE8m93kdcBugoW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Serock3 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
