### PR TITLE
Replace "smart routing" with "direct only"

### PR DESCRIPTION
**Pull request by Serock3**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)

### CODE REVIEW

**Review by hulthe — COMMENTED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r3, 17 of 23 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: 18 of 27 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`mullvad-types/src/wireguard.rs` line 101 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935#-O8an3Gt2cUHJazPd30Y:-O8an3Gt2cUHJazPd30Z:bqyigkd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6eb71472445095eb61fc1ef16c1b44dc8bdef1f2/mullvad-types/src/wireguard.rs#L101)):*
Proposal: 

```
#[cfr_attr(target_os = "android", serde(skip))]
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: 18 of 27 files reviewed, all discussions resolved (waiting on @hulthe)

___
*[`mullvad-types/src/wireguard.rs` line 101 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935#-O8an3Gt2cUHJazPd30Y:-O8anmSdEDtlwzh_08rB:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6eb71472445095eb61fc1ef16c1b44dc8bdef1f2/mullvad-types/src/wireguard.rs#L101)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Proposal: 

```
#[cfr_attr(target_os = "android", serde(skip))]
```
</blockquote></details>

Done

**Review by raksooo — APPROVED** [review]
> Reviewed 10 of 21 files at r2, 11 of 23 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: 25 of 27 files reviewed, all discussions resolved (waiting on @hulthe)

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 3 of 10 files at r1, 21 of 23 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: 25 of 27 files reviewed, 1 unresolved discussion (waiting on @hulthe and @Serock3)

___
*[`mullvad-daemon/src/management_interface.rs` line 359 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935#-O8aotySDRhucofYUmVm:-O8aotySDRhucofYUmVn:b6qb37m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c79508b397fb1c2077537ffc0d8661e64dc00f43/mullvad-daemon/src/management_interface.rs#L359)):*
> ```XML
>         log::debug!("set_daita_direct_only({value})");
>         let (tx, rx) = oneshot::channel();
>         self.send_command_to_daemon(DaemonCommand::SetDaitaUseMultihopIfNecessary(tx, !value))?;
> ```

Nit: `value` is a bit vague. I would prefer if the variable name carried a hint on what the value represents, e.g. `use_direct_only`.



_Code quote:_
```XML
        let value = request.into_inner();
        log::debug!("set_daita_direct_only({value})");
        let (tx, rx) = oneshot::channel();
        self.send_command_to_daemon(DaemonCommand::SetDaitaUseMultihopIfNecessary(tx, !value))?;
```

**Review by hulthe — COMMENTED** [review]
daemon :lgtm: 

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935#-:-O8ar2MI5h3-742Ngu0v:b9afbnh)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Review by Pururun — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935#-:-O8avA716ZncL9tbnP5k:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: 26 of 27 files reviewed, all discussions resolved (waiting on @raksooo)

**Review by hulthe — APPROVED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 2 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
