### PR TITLE
Sandbox Electron renderer process

### PR DESCRIPTION
**Pull request by raksooo**
This PR changes these options on `BrowserWindow`:
```
webPreferences: {
  nodeIntegration: false,
  nodeIntegrationInWorker: false,
  nodeIntegrationInSubFrames: false,
  enableRemoteModule: false,
  sandbox: true,
  contextIsolation: true,
}
```

The purpose of enabling these settings is to increase the security in the renderer by sandboxing third party dependencies. To make this possible quite a lot of thing had to be adjusted:
* Logging over IPC (merged in https://github.com/mullvad/mullvadvpn-app/pull/2390)
* Replace node APIs, e.g. `path`, `process`. `process.env.NODE_ENV` and `process.platform` are now passed over IPC instead.
* Pass loaded translations over IPC since loading those require file system access.
* Split renderer and main parts of IPC initialization to different files to avoid importing `ipcMain` in renderer.
* Add preload script to initialize IPC.
* Bundle preload scripts into one JavaScript file.
* Bundle renderer scripts into one JavaScript file.

This PR still has the sandbox disabled on Linux which I will look into and might change in a future PR.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/package.json, line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRUvR_-46DsMDymyqn7:-MRUvR_-46DsMDymyqn8:b-a3r4nk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/package.json#L107)):*
> ```JSON
>     "lint": "eslint --ext tsx,ts .",
>     "format": "prettier \"**/*.{js,css,ts,tsx}\" --write",
>     "develop": "gulp develop --development",
> ```

Does this switch affect something internally?

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 3 of 36 files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 3 of 36 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/package.json, line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRUvR_-46DsMDymyqn7:-MRUvdXHAOceZkQztLGg:b-fl6tir) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/package.json#L107)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does this switch affect something internally?
</blockquote></details>

Yes, it's used to decide if `debug: true` should be passed to `browserify` in `scripts.js`. Maybe there's a better way to accomplish this though.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 6 of 36 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/tasks/scripts.js, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRV8eQi7Nj642A5IgVf:-MRV8eQi7Nj642A5IgVg:bx2eifp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/tasks/scripts.js#L18)):*
> ```JavaScript
>   const compileScripts = function () {
>     const watch = new TscWatchClient();
>     watch.on('success', () =>
> ```

You can use `first_success` event instead.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 6 of 36 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/tasks/scripts.js, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRV8eQi7Nj642A5IgVf:-MRV9M2m9x41xrdzEm3G:b-vuo8ve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/tasks/scripts.js#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You can use `first_success` event instead.
</blockquote></details>

No, unfortunately not. `browserifyRenderer` and `browserifyPreload` needs to be executed on each success. `onFirstSuccess` should be called after those have completed the first time.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 7 of 36 files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 6 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 13 of 36 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/shared/ipc-helpers.ts, line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRVAVVY7NHeX4CGBOJT:-MRVAVVY7NHeX4CGBOJU:b-b3gmhx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/src/shared/ipc-helpers.ts#L81)):*
> ```XML
> export function createIpcRenderer<S extends Schema>(
>   schema: S,
>   ipcRenderer: EIpcRenderer,
> ```

`EIpcRenderer`? Is it a typo or that leading `E` has some meaning?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 13 of 36 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/shared/ipc-helpers.ts, line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRVAVVY7NHeX4CGBOJT:-MRVAk-E2gh8rA9dvlMY:baxb2gw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/src/shared/ipc-helpers.ts#L81)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`EIpcRenderer`? Is it a typo or that leading `E` has some meaning?
</blockquote></details>

Oh I see. Looks like an alias.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 14 of 36 files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 15 of 36 files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 17 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 32 of 36 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/ImageView.tsx, line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRZRMFxDZVMmaiGEMAb:-MRZRMFxDZVMmaiGEMAc:b-15n66s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/src/renderer/components/ImageView.tsx#L42)):*
> ```XML
> 
> export default function ImageView(props: IImageViewProps) {
>   const url = props.source.startsWith('/')
> ```

This won't work on windows as paths on Windows start with `drive:/`

**Review by pronebird — COMMENTED** [review]
> Reviewed 4 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/tasks/scripts.js, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRZTc1CC-k-8XgPeMxQ:-MRZTc1CC-k-8XgPeMxR:b4l42nu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/tasks/scripts.js#L11)):*
> ```JavaScript
> const source = require('vinyl-source-stream');
> 
> const isDevelopment = process.argv.includes('--development');
> ```

Why not making a generator that makes the gulp task, i.e:

```
function makeBrowserifyTask(debug: boolean) {
  return parallel(makeBrowserifyRenderer(debug), makeBrowserifyPreload(debug))
}

func makeBrowserifyRenderer(debug: boolean) {
 return () => {
    // browserify code
  }
}

func makeBrowserifyPreload(debug: boolean) {
 return () => {
    // browserify code
  }
}
```

Then you don't need `argv` and you can pass the flag from `develop` task.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399)* status: 33 of 37 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/renderer/components/ImageView.tsx, line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRZRMFxDZVMmaiGEMAb:-MR_w6cI1GId70vgEBdf:bdkf18u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/src/renderer/components/ImageView.tsx#L42)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This won't work on windows as paths on Windows start with `drive:/`
</blockquote></details>

When thinking about it I realize that absolute paths won't work at all since it's sandboxed. I've now replaced the absolute paths for icons in the list of split tunneling applications with data-urls instead.
___
*[gui/tasks/scripts.js, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-MRZTc1CC-k-8XgPeMxQ:-MR_wJKPEqZaczuiiHz8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a66d567c494967f9a3a921e6562987bb1a355a98/gui/tasks/scripts.js#L11)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why not making a generator that makes the gulp task, i.e:

```
function makeBrowserifyTask(debug: boolean) {
  return parallel(makeBrowserifyRenderer(debug), makeBrowserifyPreload(debug))
}

func makeBrowserifyRenderer(debug: boolean) {
 return () => {
    // browserify code
  }
}

func makeBrowserifyPreload(debug: boolean) {
 return () => {
    // browserify code
  }
}
```

Then you don't need `argv` and you can pass the flag from `develop` task.
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
Looks great! :lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2399#-:-MRdl4021qhwvcFp2lua:bgq9xs7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
