### PR TITLE
Move build and release instructions to separate documents

### PR DESCRIPTION
**Pull request by dlon**
This PR moves the build and release instructions out of `README.md` and into separate documents, and also separates the build instructions for Android from the desktop instructions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)

### CODE REVIEW

**Comment by faern** [comment]
I think this is better reviewed primarily by an Android developer. But I can give it a quick glance and come with some feedback.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`BuildInstructions.md` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtDAnoBytPrIcMMBPe:-NCtDAnoBytPrIcMMBPf:bxqv2bc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/BuildInstructions.md#L2)):*
> ```Markdown
> These are instructions on how to build the app on desktop platforms. For instructions on how to
> build the Android app, see [here](./android/README.md).
> ```

Please also include the link to the corresponding iOS instructions. Does not hurt to make that more discoverable. 

But also please see my other comment about trying to avoid `[here]` as link text.
___
*[`BuildInstructions.md` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtDwYq1GiyzhasP4HZ:-NCtDwYq1GiyzhasP4H_:bl1nvoe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/BuildInstructions.md#L18)):*
> ```Markdown
>   your platform for details.
> 
> - Install Go (ideally version `1.18`) by following the [official
> ```

Can we avoid specifying the version here in order to reduce the risk of this getting out of date? Like with node above, is there any good source of truth available in some code file we can reference? :thinking: Causing 
___
*[`android/README.md` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtCezx9S_4TwTOPePM:-NCtCezx9S_4TwTOPePN:b-kc3und) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/android/README.md#L7)):*
> ```Markdown
> ## Building the app
> 
> See [this](BuildInstructions.md) for instructions on how to build the app.
> ```

Nitpick. But I think [this] links is a tiny bit of markdown smell. It looks nicer to integrate the link text more naturally in the sentence. Something like `See [build instructions](BuildInstructions.md) for help compiling the app`

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`BuildInstructions.md` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtDAnoBytPrIcMMBPe:-NCu0Tm8DXC2VvHs95of:b-mlpmt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/BuildInstructions.md#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please also include the link to the corresponding iOS instructions. Does not hurt to make that more discoverable. 

But also please see my other comment about trying to avoid `[here]` as link text.
</blockquote></details>

What do you think of just linking to the build section of the readme?
___
*[`BuildInstructions.md` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtDwYq1GiyzhasP4HZ:-NCtw-lZ7wcrgZOUxrKT:bbu3dmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/BuildInstructions.md#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we avoid specifying the version here in order to reduce the risk of this getting out of date? Like with node above, is there any good source of truth available in some code file we can reference? :thinking: Causing 
</blockquote></details>

The closest thing might be the `go.mod` file for libwg. But it's only a minimum version and doesn't include a patch version.

I think we should define an exact `GOLANG_VERSION` version in `.env` or something and use that in all scripts and GitHub Actions workflows.
___
*[`android/README.md` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtCezx9S_4TwTOPePM:-NCu3Msb6LKuHCtJwLlR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/android/README.md#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpick. But I think [this] links is a tiny bit of markdown smell. It looks nicer to integrate the link text more naturally in the sentence. Something like `See [build instructions](BuildInstructions.md) for help compiling the app`
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`BuildInstructions.md` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtDAnoBytPrIcMMBPe:-ND8ZARiD1afFQrsIawp:bfjyf0v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/BuildInstructions.md#L2)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

What do you think of just linking to the build section of the readme?
</blockquote></details>

This makes sense! Less duplication of links :+1: Smart
___
*[`BuildInstructions.md` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NCtDwYq1GiyzhasP4HZ:-ND8ZVAoAZ-Qzel-Nu0P:b-nnxbrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ec906de02238560fdce07a02cc49df8ca3c251f/BuildInstructions.md#L18)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The closest thing might be the `go.mod` file for libwg. But it's only a minimum version and doesn't include a patch version.

I think we should define an exact `GOLANG_VERSION` version in `.env` or something and use that in all scripts and GitHub Actions workflows.
</blockquote></details>

Ok. Makes sense, but that's for a different PR. Maybe when we define the build Dockerfiles.
___
*[`BuildInstructions.md` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8_4ew1cvKwTHE3jHt:-ND8_4ex1u19RemK8FJZ:b-4mxlof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2560d0d5fda040e80ed0f8fcfaafcb7758f9fd21/BuildInstructions.md#L16)):*
> ```Markdown
>   versions that we target are specified in `package.json` in the `volta` section. Those versions
>   will be used automatically if volta is installed and setup. See the instructions specific to
>   your platform for details.
> ```

I currently feel like it's a lot of jumping around to follow these docs. You read this "all platforms" list which specifies the node version, but then it says "do whatever the platform docs says". And then down in those docs we basically repeat the same thing over and over about installing volta. I think we can condense this and make it less jumpy by including everything right here.

```
- You need Node.js and npm. You can find the exact versions in the `volta` section of `gui/package.json`. The toolchain is managed by volta.
  ## Linux & macOS
  
  `cargo install --git https://github.com/volta-cli/volta && volta setup`
  
  ## Windows
  
  Install the `msi` hosted here: https://github.com/volta-cli/volta
```

I think we should stop listing alternatives, such as (get volta **or** install it manually). And instead focus on clean and straightforward instructions for the single recommended way.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`BuildInstructions.md` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8_4ew1cvKwTHE3jHt:-ND8m9dV-vwtfcpMXIf1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2560d0d5fda040e80ed0f8fcfaafcb7758f9fd21/BuildInstructions.md#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I currently feel like it's a lot of jumping around to follow these docs. You read this "all platforms" list which specifies the node version, but then it says "do whatever the platform docs says". And then down in those docs we basically repeat the same thing over and over about installing volta. I think we can condense this and make it less jumpy by including everything right here.

```
- You need Node.js and npm. You can find the exact versions in the `volta` section of `gui/package.json`. The toolchain is managed by volta.
  ## Linux & macOS
  
  `cargo install --git https://github.com/volta-cli/volta && volta setup`
  
  ## Windows
  
  Install the `msi` hosted here: https://github.com/volta-cli/volta
```

I think we should stop listing alternatives, such as (get volta **or** install it manually). And instead focus on clean and straightforward instructions for the single recommended way.
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Nice work with separating instructions! I have some feedback for the Android build instructions:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-:-ND9-DljEiT8ayieEWcS:bgtg1tj)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @dlon and @faern)

___
*[`android/BuildInstructions.md` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8wG_y0FSH1s73cGS_:-ND8wG_y0FSH1s73cGSa:b-epii51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L3)):*
> ```Markdown
> These instructions are for building the app for Android **under Linux**.
> 
> # Install toolchains and dependencies
> ```


I suggest some slight restructuring here:

```
# Setup build environment
## Android toolchain
- JDK
- SDK
- NDK
## Rust toolchain for building the daemon
- Rustup
- Android targets
- Cargo linker
```
___
*[`android/BuildInstructions.md` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8z1fsDsdkAd6Fd1hC:-ND8z1fsDsdkAd6Fd1hD:bq7mh0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L10)):*
> ```Markdown
> - Get the latest **stable** Rust toolchain via [rustup.rs](https://rustup.rs/).
> 
> - Install Go (ideally version `1.18`) by following the [official
> ```

Is go needed? I believe we build wireguard-go in docker, at least when building using the `build-apk.sh` script.
https://github.com/mullvad/mullvadvpn-app/blob/master/wireguard/build-wireguard-go.sh#L121
___
*[`android/BuildInstructions.md` line 101 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8u_XK-ayEvzcsPkTC:-ND8u_XL2i_zB7zYTPfd:bdhrg15) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L101)):*
> ```Markdown
> ```
> 
> # Signing key for release APKs (optional)
> ```

Would be nice to change the structure here a bit as most readers probably only will build debug builds. I suggest something like this:
```
...

# Building a debug build
...

# Buliding a release build
## Configure signing key
...
## Buliding and packaging
...
```
___
*[`android/BuildInstructions.md` line 133 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8zYVH5yTLdCgDf0QW:-ND8zYVH5yTLdCgDf0QX:b-xym433) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L133)):*
> ```Markdown
> automatically generated debug keys:
> ```bash
> ./build-apk.sh --dev-build
> ```

The paths to the `build-apk.sh` should probably adjusted as it resides in the root of the project.
___
*[`android/BuildInstructions.md` line 139 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8znty7W_dqR__QcvV:-ND8znty7W_dqR__QcvW:b-mn3sub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L139)):*
> ```Markdown
> ```bash
> echo "org.gradle.jvmargs=-Xmx4608M" >> ~/.gradle/gradle.properties
> ./android/gradlew --stop
> ```

Can probably be adjusted to `./gradlew` now that the instructions exist in the `android` directory.



_Code quote:_
```Markdown
./android/gradlew
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @dlon and @faern)

___
*[`android/BuildInstructions.md` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8z1fsDsdkAd6Fd1hC:-ND91GWb2nbxSkMcYbdW:bs6f8hd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is go needed? I believe we build wireguard-go in docker, at least when building using the `build-apk.sh` script.
https://github.com/mullvad/mullvadvpn-app/blob/master/wireguard/build-wireguard-go.sh#L121
</blockquote></details>

My mistake, we seem to support both building with and without docker (via the `--no-docker` flag). As this is the case, I suggest adding a separate GO section to the above suggestion, resulting in:

```
# Setup build environment
## Android toolchain
- JDK
- SDK
- NDK
## GO
### With docker
...
### Without docker
...
## Rust toolchain for building the daemon
- Rustup
- Android targets
- Cargo linker
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`android/BuildInstructions.md` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8wG_y0FSH1s73cGS_:-NDCN_CoCMSEJwe48Vcr:bo1lvas) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L3)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>


I suggest some slight restructuring here:

```
# Setup build environment
## Android toolchain
- JDK
- SDK
- NDK
## Rust toolchain for building the daemon
- Rustup
- Android targets
- Cargo linker
```
</blockquote></details>

Done. Docker doesn't really fit into either section, though.
___
*[`android/BuildInstructions.md` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8z1fsDsdkAd6Fd1hC:-ND91zdq-ZQ_g2GW5CVa:b5rydsk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

My mistake, we seem to support both building with and without docker (via the `--no-docker` flag). As this is the case, I suggest adding a separate GO section to the above suggestion, resulting in:

```
# Setup build environment
## Android toolchain
- JDK
- SDK
- NDK
## GO
### With docker
...
### Without docker
...
## Rust toolchain for building the daemon
- Rustup
- Android targets
- Cargo linker
```
</blockquote></details>

I've added information about `--no-docker` near the end, as discussed.
___
*[`android/BuildInstructions.md` line 101 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8u_XK-ayEvzcsPkTC:-NDCNVR24mQyIRiX31hr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L101)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to change the structure here a bit as most readers probably only will build debug builds. I suggest something like this:
```
...

# Building a debug build
...

# Buliding a release build
## Configure signing key
...
## Buliding and packaging
...
```
</blockquote></details>

Done.
___
*[`android/BuildInstructions.md` line 133 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8zYVH5yTLdCgDf0QW:-ND92FCc-40rF1QKR0QQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L133)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The paths to the `build-apk.sh` should probably adjusted as it resides in the root of the project.
</blockquote></details>

Done.
___
*[`android/BuildInstructions.md` line 139 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-ND8znty7W_dqR__QcvV:-ND92F1F8W7FvSIKphDz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/android/BuildInstructions.md#L139)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can probably be adjusted to `./gradlew` now that the instructions exist in the `android` directory.
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @dlon, and @faern)

___
*[`android/BuildInstructions.md` line 151 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCQmBxEye2d6Z1uMDO:-NDCQmBxEye2d6Z1uMDP:b-gu2e4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a34ac96843253a592ceac8bdf1f4f24b709083fa/android/BuildInstructions.md#L151)):*
> ```Markdown
> 
> It is possible to build the app without Docker, but normally a container is used.
> The image is needed as it includes a patch to the go runtime for using a clock that
> ```

Which image? Is to referring to the docker image (that isn't used in this case)? This sentence is a bit unclear to me. I've only built `wireguard-go` using the docker container so that might be the reason I'm a bit confused.



_Code quote:_
```Markdown
The image is needed
```

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @dlon, and @faern)

___
*[`BuildInstructions.md` line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCMK5H3pKdFd4jo5RB:-NDCMK5H3pKdFd4jo5RC:b-x5qgow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/BuildInstructions.md#L31)):*
> ```Markdown
> 
> - Install a protobuf compiler (version 3.15.6 and up), it can be installed on most major Linux
>   distros via the package name `protobuf-compiler`, `protobuf` on macOS via Homebrew, and on Windows
> ```

This needs rebasing/syncing. Emils merged fixes to these docs on `master`.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @dlon, and @faern)

___
*[`android/BuildInstructions.md` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCX26h-h-A6xxzxKlZ:-NDCX26h-h-A6xxzxKl_:b-2easaj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a34ac96843253a592ceac8bdf1f4f24b709083fa/android/BuildInstructions.md#L11)):*
> ```Markdown
> 
> - Docker is required to build `wireguard-go`. Follow the
>   [instructions](https://docs.docker.com/engine/install/debian/) for your distribution.
> ```

I'd personally much rather recommend podman. Or maybe the the docs can be container engine agnostic? I don't think this documentation has to include how to install a container engine at least.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`BuildInstructions.md` line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCMK5H3pKdFd4jo5RB:-NDCWz2H4vMy1bcZD-J2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1ada1ae4ead4243ab3cd35c35835038918bcf46/BuildInstructions.md#L31)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This needs rebasing/syncing. Emils merged fixes to these docs on `master`.
</blockquote></details>

Done.
___
*[`android/BuildInstructions.md` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCX26h-h-A6xxzxKlZ:-NDCZlJQAwIqPvqvmKr2:b-s1f4p4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a34ac96843253a592ceac8bdf1f4f24b709083fa/android/BuildInstructions.md#L11)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'd personally much rather recommend podman. Or maybe the the docs can be container engine agnostic? I don't think this documentation has to include how to install a container engine at least.
</blockquote></details>

We use `docker` in a couple of scripts. So Docker seems to be a requirement, unfortunately.
___
*[`android/BuildInstructions.md` line 151 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCQmBxEye2d6Z1uMDO:-NDCZyTl7b_bAuCEYdrl:bnm9vdy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a34ac96843253a592ceac8bdf1f4f24b709083fa/android/BuildInstructions.md#L151)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Which image? Is to referring to the docker image (that isn't used in this case)? This sentence is a bit unclear to me. I've only built `wireguard-go` using the docker container so that might be the reason I'm a bit confused.
</blockquote></details>

I've removed the section.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`android/BuildInstructions.md` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDCX26h-h-A6xxzxKlZ:-NDCcSRU15nPn627mpgF:b-2ur95o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a34ac96843253a592ceac8bdf1f4f24b709083fa/android/BuildInstructions.md#L11)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We use `docker` in a couple of scripts. So Docker seems to be a requirement, unfortunately.
</blockquote></details>

Yeah, I take this back. Long term we should lift that requirement by building *the entire Android app* in a container. Then said container can be ran in any container engine.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`Release.md` line 13 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDClVpv-c0bXPNfDr7B:-NDClVpv-c0bXPNfDr7C:b-66d68t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0478c728317696b6c4debc91847fef6aa0b800b3/Release.md#L13)):*
> ```Markdown
>    header at the top. Push this, get it reviewed and merged.
> 
> 1. Run `./prepare_release.sh <VERSION>`. This will do the following for you:
> ```

This is outdated... And I think this entire file has a large risk of being incredibly outdated. We have the build instructions on Confluence and I have not updated nor even read these instructions in years :see_no_evil:

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-:-NDDah88EnSjrdIV7XN1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Release.md` line 13 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDClVpv-c0bXPNfDr7B:-NDDaTSk7pv7WpPuKGsp:bzc4fo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0478c728317696b6c4debc91847fef6aa0b800b3/Release.md#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest that we keep these instructions in a single place, rather than in two or more places. My personal preference would be keep it in the git repository, but if that's not feasible I instead suggest we move all of it over to confluence.
</blockquote></details>

We have things in confluence that it would not make sense to add to git. Such as guidelines for when to blog about something etc etc. So an app release instruction in confluence is unavoidable. It could refer to here for how to build the actual app. But then it will be more jumping around when actually doing a release.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`Release.md` line 13 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957#-NDClVpv-c0bXPNfDr7B:-NDDdX057JIAeVxRIwcF:b-kaftw2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0478c728317696b6c4debc91847fef6aa0b800b3/Release.md#L13)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We have things in confluence that it would not make sense to add to git. Such as guidelines for when to blog about something etc etc. So an app release instruction in confluence is unavoidable. It could refer to here for how to build the actual app. But then it will be more jumping around when actually doing a release.
</blockquote></details>

We already refer to here from the Confluence document, so as you mentioned a nice split would be to keep build instructions here and the guidelines and other internal information in Confluence. Otherwise, it's just a matter of time before it's out-of-sync again.

**Pull request merged**
