### PR TITLE
Allow relay selector to select an entry peer

### PR DESCRIPTION
**Pull request by rablador**
The relay selector should be able to select a WireGuard relay for an entry peer. It should make precautions to not select the same relay for both entry and exit peers.

When either the entry constraints or the exit constraints are changed and the app is connected, the tunnel should reconnect and both entry and exit locations should be re-evaluated.

When selecting entry and exit relays, and either of the location constraints match only a single relay, which ever position has just a single matching relay gets to pick that one, and the single matching relay is excluded from the other position's possible set of relays. If both entry and exit positions match the same single relay, the relay selector should return an error and the app should go into the blocked state.

If both positions have multiple candidate relays, first an exit relay is picked and the selected exit relay is removed from the candidate set for the entry position.

When selecting a bridge for API communication, the relay selector should honor if multi hop is enabled or not - if it is, the entry constraints should be used to pick a bridge for API access, otherwise the exit constraints should be used to pick a bridge for API access.

When passing the relay selector result to the packet tunnel actor, the packet tunnel actor may ignore the entry relay for now.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
This PR goes the whole distance in terms of relay selector, but there's still work to do with integrating wireguardkit and the coming updates to it. As such there are some todos left and places where exit/entry endpoints and the like might not be completely correct yet.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-:-O0JVEGLBDGWrsG8uChA:bug4kv0)* status: 0 of 52 files reviewed, all discussions resolved

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 35 of 50 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift` line 180 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0N_djV61q_WXNk_wA3:-O0N_djV61q_WXNk_wA4:b-17u39z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9fd8093b9697fd47bedf4535014b14a2cd996ea/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift#L180)):*
> ```Swift
>                     connectionAttemptCount: 0,
>                     transportLayer: .udp,
>                     remotePort: selectedRelays.exit.endpoint.ipv4Relay.port, // TODO: Multihop
> ```

Do we want to fix this for an upcoming PR ?
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2848 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0NxmVW-CYTf1z7EIE2:-O0NxmVW-CYTf1z7EIE3:bhqhdjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9fd8093b9697fd47bedf4535014b14a2cd996ea/ios/MullvadVPN.xcodeproj/project.pbxproj#L2848)):*
> ```
> 			isa = PBXGroup;
> 			children = (
> 				F01DAE322C2B032A00521E46 /* RelaySelection.swift */,
> ```

Order by name

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift` line 180 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0N_djV61q_WXNk_wA3:-O0OlMZi66SeCnuzLy5q:b2nhswv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9fd8093b9697fd47bedf4535014b14a2cd996ea/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift#L180)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Do we want to fix this for an upcoming PR ?
</blockquote></details>

Yep

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/RelayPicking.swift` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0OsPtzEt5rHd09Babt:-O0OsPtzEt5rHd09Babu:bbj2sj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9fd8093b9697fd47bedf4535014b14a2cd996ea/ios/MullvadREST/Relay/RelayPicking.swift#L75)):*
> ```Swift
>         )
> 
>         let decisionFlow = OneToOne(
> ```

nit
It could be useful to have a comment here explaining why we do first 1 to 1, then 1 to many and finally many to many.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: 27 of 55 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/Relay/RelayPicking.swift` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0OsPtzEt5rHd09Babt:-O0hErdW4gWlKn1PL4EV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9fd8093b9697fd47bedf4535014b14a2cd996ea/ios/MullvadREST/Relay/RelayPicking.swift#L75)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
It could be useful to have a comment here explaining why we do first 1 to 1, then 1 to many and finally many to many.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2848 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0NxmVW-CYTf1z7EIE2:-O0hF-xh0NdxM32XWdzK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9fd8093b9697fd47bedf4535014b14a2cd996ea/ios/MullvadVPN.xcodeproj/project.pbxproj#L2848)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Order by name
</blockquote></details>

Done.

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 18 of 20 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: 54 of 55 files reviewed, 1 unresolved discussion

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-:-O0rx3ZMCGQ-Re0S1u6z:bnfp4nl)* status: 54 of 55 files reviewed, 1 unresolved discussion

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: 59 of 63 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 105 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0wazY10cjRmHhDuDmw:-O0wazY10cjRmHhDuDmx:bvyx9gc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/217bd4b1f446dd55b5f580fdf442bce3f1f62c2e/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L105)):*
> ```Swift
>             )
> 
>             if hostCode == "al-tia-wg-001" {
> ```

Did you forget to remove debug code ?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 116 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0wb1Lv0uecdOvnCXRl:-O0wb1Lv0uecdOvnCXRm:b-cectgr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/217bd4b1f446dd55b5f580fdf442bce3f1f62c2e/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L116)):*
> ```Swift
>                 cityNode.children.sort()
> 
> //                hostNode.isExcluded = selectedRelays.excluded?.locations.contains { excludedLocation in
> ```

Please delete those comments 
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListLocationNodeBuilder.swift` line 52 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-O0wb4S283xk-keeADFT:-O0wb4S283xk-keeADFU:b-l5z3w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/217bd4b1f446dd55b5f580fdf442bce3f1f62c2e/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListLocationNodeBuilder.swift#L52)):*
> ```Swift
> 
>         listNode.isActive = !listNode.children.isEmpty
> //        listNode.isExcluded = listNode.children.filter { !$0.isExcluded }.isEmpty
> ```

Please delete

**Review by rablador — COMMENTED** [review]
> Dismissed @buggmagnet from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413)* status: 55 of 63 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6413#-:-O1X8ujgBTZUH3dyXc8x:bnfp4nl)* status: 52 of 63 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Pull request merged**
