### PR TITLE
Refactor URLSession out of outgoing connection proxy tests

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjMm_6F72eK95em_mhy:-NjMm_6F72eK95em_mhz:b-2r3y31) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04c6609948a770aed30491c66c4c6d779bc71c92/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L30)):*
> ```Swift
>     }
> 
>     func testNoInternetConnection() async throws {
> ```

Ok to remove this test? It relies on the previoud MockURLProtocol to work and isn't really compatible with the refactor.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNd0Pp6dK90HyMD_0J:-NjNd0Pp6dK90HyMD_0K:b57dt16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L72)):*
> ```Swift
>             throw REST.Error.network(URLError(.badURL))
>         }
>         let request = URLRequest(
> ```

This is not used anymore since we are using `func data(from url: URL) async throws -> (Data, URLResponse)` instead.

If that was intentional, please delete this variable.
If it wasn't, please adjust the protocol accordingly.
___
*[`ios/MullvadVPNTests/MockURLSession.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNd_2l7a7feRkmlGhI:-NjNd_2mD4LfRc6tnM_q:bmn7gy2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPNTests/MockURLSession.swift#L11)):*
> ```Swift
> import Foundation
> 
> class MockURLSession: URLSessionProtocol {
> ```

[Let's rename this `URLSessionStub`](https://martinfowler.com/articles/mocksArentStubs.html#TheDifferenceBetweenMocksAndStubs)
(I never get tired of posting this article :cowboy_hat_face:)
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjMm_6F72eK95em_mhy:-NjNeprT-wYLh7pqvGdE:b-m8hssx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04c6609948a770aed30491c66c4c6d779bc71c92/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L30)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Ok to remove this test? It relies on the previoud MockURLProtocol to work and isn't really compatible with the refactor.
</blockquote></details>

I think that's okay. 
On the other hand, it would be nice if we could have a test that validates the retry logic of `OutgoingConnectionProxy`
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNfI7w5kFBSeqNGQ9N:-NjNfI7w5kFBSeqNGQ9O:b-b1ux32) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L85)):*
> ```Swift
> 
> extension OutgoingConnectionProxyTests {
>     private enum IPVersion: String {
> ```

If `ExitIPVersion` wasn't declared as a private enum to `OutgoingConnectionProxy`
we could reuse it here instead of declaring a similar type

I think it's worth making `ExitIPVersion` internal, for that purpose, and declare it outside of `OutgoingConnectionProxy`

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNd0Pp6dK90HyMD_0J:-NjRPwvL9IMw1q0dzZpP:by2v4uq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L72)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is not used anymore since we are using `func data(from url: URL) async throws -> (Data, URLResponse)` instead.

If that was intentional, please delete this variable.
If it wasn't, please adjust the protocol accordingly.
</blockquote></details>

Forgot to remove, but on second thought I think should just keep it and adjust the protocol. I don't believe the custom timeout matters much here, but is is more consistent.
___
*[`ios/MullvadVPNTests/MockURLSession.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNd_2l7a7feRkmlGhI:-NjRQU8wBolZaLuhi1Ho:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPNTests/MockURLSession.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

[Let's rename this `URLSessionStub`](https://martinfowler.com/articles/mocksArentStubs.html#TheDifferenceBetweenMocksAndStubs)
(I never get tired of posting this article :cowboy_hat_face:)
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNfI7w5kFBSeqNGQ9N:-NjRQeJz6luwyrj7gOjr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L85)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If `ExitIPVersion` wasn't declared as a private enum to `OutgoingConnectionProxy`
we could reuse it here instead of declaring a similar type

I think it's worth making `ExitIPVersion` internal, for that purpose, and declare it outside of `OutgoingConnectionProxy`
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
Nice job ! 

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-:-Njfu5c19MNHLHH-TlhS:b-3kymyo)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5446#-NjNd0Pp6dK90HyMD_0J:-NjfsNKm0f0BuZPlMM58:b84gg41) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/110dddd1847f9f3812cf0ce0a7cf29cb48714867/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L72)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Forgot to remove, but on second thought I think should just keep it and adjust the protocol. I don't believe the custom timeout matters much here, but is is more consistent.
</blockquote></details>

IIRC the default timeout for `URLRequest` is 60 seconds, so slightly different.
But I agree with you on the consistent values :thumbsup:

**Pull request merged**
