### PR TITLE
Reduce master RPC timeout

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/138)

### CODE REVIEW

**Comment by jvff** [comment]
Should this be in the change log?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/138#-:-LAUPn1gCVUnh7PWHQBG:b-wcjl18)*

**Comment by pinkisemils** [comment]
I think you can add a line to the changelog. However, I'm not sure whether this is a change or an addition. Other than that, it :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/138#-:-LAXTl3JA_2EswmnlPnP:bsbo3wj)*

**Comment by faern** [comment]
I agree about adding to the changelog. But I think it should either go under changed or fixed. The connection had a timeout before this as well, just that we didn't control it. We added to more or less fix a bug, which is why I think the fixed category suits.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/138#-:-LAlQe0xCwXVhouwiS8L:b-vdvfup)*

**Comment by jvff** [comment]
Done.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/138#-:-LAlslEq2PRUQNDbaBAH:b-896fix)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/138#-:-LAm5Rjs9_2WWAuhESfv:bnfp4nl)*

**Pull request merged**
