### PR TITLE
Fix endless loop on gboard on TV for custom text fields

### PR DESCRIPTION
**Pull request by Pururun**
Fixed by copying the internal implementation of `BasicTextField` but with a slight adjustment so that we get the expected cursor behavior.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953#-NssLFeNEcmBTHxXdJjo:-NssLFeNEcmBTHxXdJjp:bvxjd7i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c50d49e94e8565757be7cb3851833a14e70d8117/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L47)):*
> ```Kotlin
> 
>     // This is the same implementation as in BasicTextField.kt but with initial selection set at the
>     // end of the text rather than in the beginning.
> ```

Are there any upstream or internal issues we can refer to?



_Code quote:_
```Kotlin
    // This is the same implementation as in BasicTextField.kt but with initial selection set at the
    // end of the text rather than in the beginning.
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953#-NssLFeNEcmBTHxXdJjo:-NssRQKa3CZTCfjoRihw:bhnt6u5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c50d49e94e8565757be7cb3851833a14e70d8117/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L47)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are there any upstream or internal issues we can refer to?
</blockquote></details>

Yeah would be nice to find out, maybe we can remove all this logic all together if it has been fixed? As I remember it the cursor ended up in the wrong position, like ahead of all the text. Not sure if there was any special usecase when this happened though.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953#-NssLFeNEcmBTHxXdJjo:-NsvxXA11hGmMYfLPUWU:bywlsku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c50d49e94e8565757be7cb3851833a14e70d8117/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L47)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yeah would be nice to find out, maybe we can remove all this logic all together if it has been fixed? As I remember it the cursor ended up in the wrong position, like ahead of all the text. Not sure if there was any special usecase when this happened though.
</blockquote></details>

The cursor ends up at the start of the text if you move the focus to the `TextField` rather than doing a touch selection. This is quite consistent as long as there is text that is set from code. I could not find a way to work around this.

This is the bug reported to Google:
https://issuetracker.google.com/issues/272693535

This is a gist made by the guy that reported the bug, which is quite similar to my solution for obvious reasons:
https://issuetracker.google.com/issues/272693535

This is the issue where the first workaround was introduced it does not mention this specific issue though.
https://linear.app/mullvad/issue/DROID-401/investigate-and-fix-the-dpad-navigation-bug-on-alert-dialog

I guess a solution could be to link to the bug report?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953#-NssLFeNEcmBTHxXdJjo:-NswGcXz2BQOPIKAZ-Cc:b9san7x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c50d49e94e8565757be7cb3851833a14e70d8117/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L47)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

The cursor ends up at the start of the text if you move the focus to the `TextField` rather than doing a touch selection. This is quite consistent as long as there is text that is set from code. I could not find a way to work around this.

This is the bug reported to Google:
https://issuetracker.google.com/issues/272693535

This is a gist made by the guy that reported the bug, which is quite similar to my solution for obvious reasons:
https://issuetracker.google.com/issues/272693535

This is the issue where the first workaround was introduced it does not mention this specific issue though.
https://linear.app/mullvad/issue/DROID-401/investigate-and-fix-the-dpad-navigation-bug-on-alert-dialog

I guess a solution could be to link to the bug report?
</blockquote></details>

Yeah, I think it would be nice to link to that one as well. I'm not fond of our solution for this, but I don't have a better suggestion right now.

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953#-:-NswH5J68altsblsEd0X:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953#-NssLFeNEcmBTHxXdJjo:-NswLCxa2wpE_56jJuco:bjwo3lh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c50d49e94e8565757be7cb3851833a14e70d8117/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L47)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yeah, I think it would be nice to link to that one as well. I'm not fond of our solution for this, but I don't have a better suggestion right now.
</blockquote></details>

Yeah, agreed, let's add a link to the bug report :thumbsup:

**Pull request merged**
