### PR TITLE
Fix zero weight handling (iOS)

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

- Change `ServerRelay.weight` type to `UInt64`.
- Pick random relay when all relays within the list have zero weight.
- Fix roulette algorithm to skip relays with zero weight.

Similar PR for desktop: https://github.com/mullvad/mullvadvpn-app/pull/3262

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/RelaySelector.swift, line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331#-MvJF-GW6oGw-LuV4gcI:-MvJF-GW6oGw-LuV4gcJ:b-sc3hjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94004cdf630f6e849b8350b453d8bc87ba891027/ios/MullvadVPN/RelaySelector.swift#L110)):*
> ```Swift
>             i = isOverflow ? 0 : result
> 
>             return i == 0
> ```

Wouldn't it be simpler to just do it like this?
```
i = result
return isOverflow
```

The current implementation was a bit more difficult to follow.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/RelaySelector.swift, line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331#-MvJF-GW6oGw-LuV4gcI:-MvJNJ_qCKy_BwfTsHQF:b2jogvi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94004cdf630f6e849b8350b453d8bc87ba891027/ios/MullvadVPN/RelaySelector.swift#L110)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Wouldn't it be simpler to just do it like this?
```
i = result
return isOverflow
```

The current implementation was a bit more difficult to follow.
</blockquote></details>

When overflow happens, the `result` is a truncated value, and not zero. For example:

```
let (partialValue, isOverflow) = UInt64(1).subtractingReportingOverflow(2)

print("partialValue = \(partialValue); isOverflow = \(isOverflow)")
```

Output:

```
partialValue = 18446744073709551615; isOverflow = true
```

Sadly there are no other functions I am aware of that can  clamp the value at 0 in that case such as [saturating_sub](https://doc.rust-lang.org/std/primitive.u64.html#method.saturating_sub) in Rust. Just don't know alternative here sadly. But it's simple enough to check if overflow happened.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/RelaySelector.swift, line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331#-MvJF-GW6oGw-LuV4gcI:-MvJUQEp24ao0QruZRxU:b-kjuygx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94004cdf630f6e849b8350b453d8bc87ba891027/ios/MullvadVPN/RelaySelector.swift#L110)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

When overflow happens, the `result` is a truncated value, and not zero. For example:

```
let (partialValue, isOverflow) = UInt64(1).subtractingReportingOverflow(2)

print("partialValue = \(partialValue); isOverflow = \(isOverflow)")
```

Output:

```
partialValue = 18446744073709551615; isOverflow = true
```

Sadly there are no other functions I am aware of that can  clamp the value at 0 in that case such as [saturating_sub](https://doc.rust-lang.org/std/primitive.u64.html#method.saturating_sub) in Rust. Just don't know alternative here sadly. But it's simple enough to check if overflow happened.
</blockquote></details>

Also note that you suggest to return `isOverflow` although the original condition to stop the roulette algorithm is when `i == 0`.

When subtracting for instance `1 - 1` we get `0` result and no overflow. Overflow happens when the type cannot hold the resulting value, i.e unsigned integer cannot be negative, etc..

**Review by raksooo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331#-:-MvNdVFF7Zg-GTI3C7T2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/RelaySelector.swift, line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331#-MvJF-GW6oGw-LuV4gcI:-MvNdP_K6ZYEXKfVH4_h:b-3pa4xa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94004cdf630f6e849b8350b453d8bc87ba891027/ios/MullvadVPN/RelaySelector.swift#L110)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Also note that you suggest to return `isOverflow` although the original condition to stop the roulette algorithm is when `i == 0`.

When subtracting for instance `1 - 1` we get `0` result and no overflow. Overflow happens when the type cannot hold the resulting value, i.e unsigned integer cannot be negative, etc..
</blockquote></details>

Ah okay :+1:

**Pull request merged**
