### PR TITLE
Add android and linux build container wrapper script

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to add a container wrapper script which simplifies building a specific commit with the image (incl. tag). It aims to support both Android and Linux builds using the same script by providing the target as an argument.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/build-container-wrapper.sh` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8C9Nd9YYy35G4-y9y:-NI8C9Nd9YYy35G4-y9z:bq013mh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

The way I read the name is "construct the container wrapper" :thinking: If the sole purpose of the script is to invoke `build-apk.sh` but in our signed container, how about we call it `container-build-apk.sh` or `build-apk-container.sh` - so the relationship is clear?
___
*[`android/build-container-wrapper.sh` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8D9mP27mhgirWns1Y:-NI8D9mP27mhgirWns1Z:b-10ysmb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L13)):*
> ```Shell
> cd "$SCRIPT_DIR"
> 
> CONTAINER_COMMAND=${CONTAINER_COMMAND:-"podman"}
> ```

Nit. "container command" can be interpreted as the command that will be executed *inside* the container. How about naming it `CONTAINER_RUNNER`?
___
*[`android/build-container-wrapper.sh` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8CmaV-RHFuFbceSEt:-NI8CmaV-RHFuFbceSEu:bd8ng4e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L16)):*
> ```Shell
> 
> image_tag=$(cat "$REPO_DIR"/building/android-container-image-tag.txt)
> build_command="./build-apk.sh --no-docker $*"
> ```

Will `$*` work fine with multiple arguments here? Maybe my info is outdated, but I have sometime learned that `$@` is preferred in most cases. https://stackoverflow.com/questions/3008695/what-is-the-difference-between-and-in-bash
___
*[`android/build-container-wrapper.sh` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8Dn0E0zybxevk00TP:-NI8Dn0E0zybxevk00TQ:b-k492ao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L18)):*
> ```Shell
> build_command="./build-apk.sh --no-docker $*"
> 
> printf "Building in podman using command: %s\n\n" "$build_command"
> ```

Maybe a nitpick. But we are not using `printf` in any other bash script we have. Would `echo -e` suffice here or is `printf` needed?
___
*[`android/build-container-wrapper.sh` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8EOBT5VPVITBqtaY6:-NI8EOBT5VPVITBqtaY7:b-iwqpow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L16)):*
> ```Shell
> 
> image_tag=$(cat "$REPO_DIR"/building/android-container-image-tag.txt)
> build_command="/build/build-apk.sh --no-docker $*"
> ```

Can we somehow get rid of the `/build` part? I know I have been able to not specify it when building for desktop. It's unfortunate if this little detail about how the container mounts up the project needs to be hardcoded here.
___
*[`android/build-container-wrapper.sh` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8EkEhDKNiR8yOqF-0:-NI8EkEhDKNiR8yOqF-1:bhc6nsf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L19)):*
> ```Shell
> 
> printf "Building in $CONTAINER_COMMAND using command: %s\n\n" "$build_command"
> $CONTAINER_COMMAND run --rm -v "$REPO_DIR":/build ghcr.io/mullvad/mullvadvpn-app-build-android:"$image_tag" /bin/bash -c "$build_command"
> ```

Can we incoporate the Rust registry and target cache here to save time? Or should we save that for a later revision of the script you think?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @faern)

___
*[`android/build-container-wrapper.sh` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8C9Nd9YYy35G4-y9y:-NI8GD2AA7LL5_pjWzwR:b-326kao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The way I read the name is "construct the container wrapper" :thinking: If the sole purpose of the script is to invoke `build-apk.sh` but in our signed container, how about we call it `container-build-apk.sh` or `build-apk-container.sh` - so the relationship is clear?
</blockquote></details>

As discussed AFK, we'll use the same script for android and linux. I've moved and changed the name of the script to `containerized-build.sh`. Any other suggestions? A shorter name would be nice as long as it's obvious what the script does.
___
*[`android/build-container-wrapper.sh` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8CmaV-RHFuFbceSEt:-NI8FTi81mkAOTZNJggQ:b-mzym11) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Will `$*` work fine with multiple arguments here? Maybe my info is outdated, but I have sometime learned that `$@` is preferred in most cases. https://stackoverflow.com/questions/3008695/what-is-the-difference-between-and-in-bash
</blockquote></details>

ShellCheck recommends `$*` for concatenating the elements into a string as far as I understand.
https://www.shellcheck.net/wiki/SC2124
___
*[`android/build-container-wrapper.sh` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8Dn0E0zybxevk00TP:-NIBN_Ey7GOQrW_aToFd:b-i0v389) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe a nitpick. But we are not using `printf` in any other bash script we have. Would `echo -e` suffice here or is `printf` needed?
</blockquote></details>

Sure, I've change from `printf` to `echo`. I also added some more prints (=echo) while modifying the script to support linux. Let's discuss AFK if we want to keep any of the prints.
___
*[`android/build-container-wrapper.sh` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8EOBT5VPVITBqtaY6:-NIBMI5k0jEmfs5Mj186:brn5b4f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

For me I need to explicitly say `./` first. So `./build.sh` when I build for desktop
</blockquote></details>

As discussed AFK, I believe might that the `./` might confuse users of the script that the it refers to either:
* The same directory as the `SCRIPT_DIR`.
* The terminal session on the host (outside the container).

As we also plan to move the build scripts, I believe a full path (within the cotnainer) is most clear. As discussed, I've added a var called to `REPO_MOUNT_TARGET` to improve readability etc.
___
*[`android/build-container-wrapper.sh` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8EkEhDKNiR8yOqF-0:-NI8IMrEApX1v_r4CFeY:bd7lv6q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L19)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we incoporate the Rust registry and target cache here to save time? Or should we save that for a later revision of the script you think?
</blockquote></details>

Added named volumes for the caches :thumbsup: 
___
*[`android/build-container-wrapper.sh` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8FW0oBlGR2-PA7t_N:-NI8Iee1Eq8P3IA5Y8FI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L19)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we please add `:Z` to all volume mounts? That way it will work with SELinux enabled machines (which the build server is)
</blockquote></details>

Done.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @faern)

___
*[`android/build-container-wrapper.sh` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8C9Nd9YYy35G4-y9y:-NIBTcMP1-vXbjolM9ea:bmnmvt7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As discussed AFK, we'll use the same script for android and linux. I've moved and changed the name of the script to `containerized-build.sh`. Any other suggestions? A shorter name would be nice as long as it's obvious what the script does.
</blockquote></details>

Perhaps `containerized.sh` could be sufficient given the path. That would result in the following command if standing in the repo root: `building/containerized.sh android`

**Review by faern — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`building/containerized-build.sh` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC-itt7EMfbiGFbCzy:-NIC-itu-6qhQciphDom:bedyeoa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> # Helper script to build the Android app in a container.
> ```

Outdated now when it supports Linux.
___
*[`building/containerized-build.sh` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC-oWgCiC2X6aiPb0P:-NIC-oWgCiC2X6aiPb0Q:b-bnvix8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L3)):*
Maybe instead of saying "a container" (vague) saying something that makes it clear that it's *the* recommended container. Something like:

> Builds the app in the current build container, as designated by the `*-container-image-tag.txt` files
___
*[`building/containerized-build.sh` line 43 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC0bGb2BmaB-JDlDED:-NIC0bGb2BmaB-JDlDEE:b-o04mrv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L43)):*
> ```Shell
> esac
> 
> full_container_name_with_tag="$REGISTRY_HOST/$REGISTRY_ORG/$container_name:$(cat "$container_tag_path")"
> ```

I got an idea. Instead of repeating all the logic and constants needed to compute the full container name in multiple scripts. Should we maybe make the `*-container-image-tag.txt` files contain the full thing? The file can contain:
```
ghcr.io/mullvad/mullvadvpn-app-build:62371bb6c
```
And be more generally named `linux-container-image.txt` etc.?

This would remove the need for `REGISTRY_HOST`, `REGISTRY_ORG` and a bunch more stuff in this script.
___
*[`building/containerized-build.sh` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC1R058is_pfacY0rD:-NIC1R058is_pfacY0rE:b-u6484u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L56)):*
> ```Shell
>     -v "$CARGO_TARGET_VOLUME_NAME":/root/.cargo/target:Z \
>     -v "$CARGO_REGISTRY_VOLUME_NAME":/root/.cargo/registry:Z \
>     -v "$GRADLE_CACHE_VOLUME_NAME":/root/.gradle:Z \
> ```

I guess it does not hurt to have this mounted for Linux builds also? Otherwise we could make this optional, but maybe that's not worth it?
___
*[`android/build-container-wrapper.sh` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8C9Nd9YYy35G4-y9y:-NIBzykM8Bv9txurU3Fz:b-o81sbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps `containerized.sh` could be sufficient given the path. That would result in the following command if standing in the repo root: `building/containerized.sh android`
</blockquote></details>

I like the current name! If we remove `build` from the name it could be a bit vague. Let's try the current name you have here (`containerized-build.sh`) and see if it's too cumbersome to type or not.
___
*[`android/build-container-wrapper.sh` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8CmaV-RHFuFbceSEt:-NIC1m8N3lQ2eCS2S5t0:bi921q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/465fe2b38a650de1a62980afb8c233d03c0fb1e7/android/build-container-wrapper.sh#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

ShellCheck recommends `$*` for concatenating the elements into a string as far as I understand.
https://www.shellcheck.net/wiki/SC2124
</blockquote></details>

Ok! I did not know. I guess I have to read that page. but I see you replaced it with array expansion now anyway.
___
*[`android/build-container-wrapper.sh` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8EOBT5VPVITBqtaY6:-NIC-bH_BI2AYCP6gI4m:bb6mt9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As discussed AFK, I believe might that the `./` might confuse users of the script that the it refers to either:
* The same directory as the `SCRIPT_DIR`.
* The terminal session on the host (outside the container).

As we also plan to move the build scripts, I believe a full path (within the cotnainer) is most clear. As discussed, I've added a var called to `REPO_MOUNT_TARGET` to improve readability etc.
</blockquote></details>

:+1:
___
*[`android/build-container-wrapper.sh` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NI8EkEhDKNiR8yOqF-0:-NIC-eaKEJ-T33n3dFpv:bccpe83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a56156610f2550219cf987b95c348c1ff62c4a4d/android/build-container-wrapper.sh#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Added named volumes for the caches :thumbsup: 
</blockquote></details>

Awesome!

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`building/containerized-build.sh` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC93oC3h423Gk3Wx-J:-NIC93oC3h423Gk3Wx-K:bu01rb6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/451a7856175f4ecc80ea50dd833ec03ce7ca9497/building/containerized-build.sh#L50)):*
> ```Shell
> echo "Container   : $full_container_name_with_tag"
> echo "Build script: $build_script"
> echo "Build args  : $build_script_args"
> ```

I like this output section in general! Makes it clearer what you are running. But I would maybe consider squashing these last two lines into one echo. Like you had it in the previous revision:
```
Command   : /build/build.sh --optimize --sign
```
I think that's easier to read when you see the arguments next to the script it's sent to, and a little bit less verbose.

**Review by faern — COMMENTED** [review]
> Reviewed 6 of 7 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`.github/workflows/android-app.yml` line 48 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NICUzcx5RDRyrh8rU9m:-NICUzcx5RDRyrh8rU9n:b37qkjb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/895a7ec77b041cfbbfe0b5d0ac74bc0cbfb49417/.github/workflows/android-app.yml#L48)):*
> ```YAML
>           if: "${{ github.event.inputs.override_container_image == '' }}"
>           run: |
>             echo "inner_container_image=$(cat ./building/android-container-image.txt)" >> $GITHUB_ENV
> ```

Soo nice to not have to repeat the full image registry host and path in so many places. feels more flexible :sparkles: 
___
*[`building/containerized-build.sh` line 43 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC0bGb2BmaB-JDlDED:-NICTmis20CcDioS2rD1:bnr3olz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I got an idea. Instead of repeating all the logic and constants needed to compute the full container name in multiple scripts. Should we maybe make the `*-container-image-tag.txt` files contain the full thing? The file can contain:
```
ghcr.io/mullvad/mullvadvpn-app-build:62371bb6c
```
And be more generally named `linux-container-image.txt` etc.?

This would remove the need for `REGISTRY_HOST`, `REGISTRY_ORG` and a bunch more stuff in this script.
</blockquote></details>

Wow, so much nicer! :sparkles: Great work!

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @faern)

___
*[`building/containerized-build.sh` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC-itt7EMfbiGFbCzy:-NIC599e4nmmqoWbqwSP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L3)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Outdated now when it supports Linux.
</blockquote></details>

Done.
___
*[`building/containerized-build.sh` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC-oWgCiC2X6aiPb0P:-NICOx7b8VyMrD97WbQM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L3)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe instead of saying "a container" (vague) saying something that makes it clear that it's *the* recommended container. Something like:

> Builds the app in the current build container, as designated by the `*-container-image-tag.txt` files
</blockquote></details>

Done.
___
*[`building/containerized-build.sh` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIC1R058is_pfacY0rD:-NICPbwx8qrJeRthg_eF:b-ucqg1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4a76fa148688494a234775609d7a3507b523cd/building/containerized-build.sh#L56)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I guess it does not hurt to have this mounted for Linux builds also? Otherwise we could make this optional, but maybe that's not worth it?
</blockquote></details>

Good point! Tried another approach of building the full command by using concat. This makes it easier to handle the optional volume and seem to better pass along arguments to the build scripts.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-:-NICdWopAQyzEnpglfnv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`building/README.md` line 50 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-NIDC5VY1rp990Us2IJZ:-NIDC5VY1rp990Us2IJ_:bl8fz83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35d4eb153c6d2067c4bdddee145d32de98df215d/building/README.md#L50)):*
> ```Markdown
> docker:
>   ghcr.io/$testorg:
>     sigstore-staging: file://${testorg}/building/sigstore
> ```

Should this still not be `${repo}`? If `${testorg}` is `faern` for me, then `file://faern/building/sigstore` is not the correct path.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4184#-:-NIDCW5RCB2L_-OD59uD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
