### PR TITLE
Remove `DaemonExecutionState`

### PR DESCRIPTION
**Pull request by Serock3**
Refactor away this small state machine and simplify shutdown logic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`wireguard-go-rs/libwg/wireguard-go` line 0 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386#-O-okwE22oUUV15RxEiS:-O-okwE22oUUV15RxEiT:bgeuwcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d5890a5700d94633ea3275f3add3c781cbb8b5e/wireguard-go-rs/libwg/wireguard-go#L0)):*
This should not be included

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`wireguard-go-rs/libwg/wireguard-go` line  at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386#-O-okwE22oUUV15RxEiS:-O-oocNU6nOIf5qCPCW0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9d5890a5700d94633ea3275f3add3c781cbb8b5e/wireguard-go-rs/libwg/wireguard-go#L)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should not be included
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386#-:-O-p_qoO1XpdxSC4TtPL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
