### PR TITLE
Update changelog for android/2024.1-beta1

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to update the changelog for the upcoming `android/2024.1-beta1`

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`CHANGELOG.md` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972#-NtGqdArAm0-ith6yAKa:-NtGqdArAm0-ith6yAKb:b-z4dzz6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b65049e40dcd15020c53cf3a89e427bd64bed837/CHANGELOG.md#L32)):*
> ```Markdown
> ### Changed
> - Change default obfuscation setting to `auto`.
> - Migrate obfuscation settings for existing users from `off` to `auto`.
> ```

This and item above is included in our current build.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`CHANGELOG.md` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972#-NtGqvTSAsr4_Uy3n0yt:-NtGqvTSAsr4_Uy3n0yu:bx17bjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b65049e40dcd15020c53cf3a89e427bd64bed837/CHANGELOG.md#L37)):*
> ```Markdown
> - Continual excessive attempts to update the API IP were made after testing access methods.
> - Fix pointless API access method rotations for concurrent requests.
> - Fix daemon rotating logs on startup even if another daemon is already running.
> ```

Double check with desktop if anything needs to be added to our changelog

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`CHANGELOG.md` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972#-NtGqdArAm0-ith6yAKa:-NtGyBfhBpCoQ3u3f6NN:bves97t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b65049e40dcd15020c53cf3a89e427bd64bed837/CHANGELOG.md#L32)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This and item above is included in our current build.
</blockquote></details>

Good catch! Fixed!
___
*[`CHANGELOG.md` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972#-NtGqvTSAsr4_Uy3n0yt:-NtGyIgk9PZnnNGxvvTW:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b65049e40dcd15020c53cf3a89e427bd64bed837/CHANGELOG.md#L37)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Double check with desktop if anything needs to be added to our changelog
</blockquote></details>

Done!

**Pull request merged**
