### PR TITLE
Add forceConsistentCasingInFileNames tsconfig flag

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds the `forceConsistentCasingInFileNames` to `tsconfig.json` to ensure that all TS files are cased correctly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3845)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3845#-:-N9f6QGAEulYFCQi3QC3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by MrChocolatine** [comment]
Awesome, it feels great being listened and that suggestions (even the smallest ones) actually make it.
Keep it up!

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3845)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by raksooo** [comment]
@MrChocolatine Thanks for the suggestion!

**Pull request merged**
