### PR TITLE
Round textfield unless showing dropdown

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5353)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
When I tested it on my phone, the bottom left and right corner always loses its corner radius when the text field is selected, regardless if the dropdown is showing or not.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5353#-:-Nhb0FjT59LPfAcFgfrj:bmslbz3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
Can you verify that it works now? I believe i fixed. Also updated unfocused label colors as well. 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5353#-:-NhbFmpGCIXTT_Sv9g1r:b-ey8ie)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
Yeah look fine now.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5353#-:-Nhf8vvz3mysP9j7ppjR:bdhobet)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5353)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
