### PR TITLE
Modernize app

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

1. This PR refactors `main.js` and incorporates a fare share of it into `WindowController`.
2. Renames `TrayIconManager` to `TrayIconController` because `manager` is a bad bad name.
3. Changes verbosity of Websocket IPC which used to log every packet with debug level, I changed that to `silly` (AKA `trace` in other logging systems)
4. Upgrades reactxp to 1.3.0 RC which addresses some of the issues I had upgrading from 1.1 RC to 1.2.0 that introduced some of regressions
5. Moves problem-report execution from renderer to main process.
6. Removes timeout for problem-report collection.
7. Stops passing `--enable-logging` to Electron when developing. `electron-log` funnels renderer logs to main automatically and vise-versa so there is no point to dupe the same messages.

No user facing changes.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/main.js, line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEj7oxzExiKQ0XGjPCL:-LEjGefB87vZWnr5b09u:bbh8u4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/873d56ad13a85fb5715eef84ac883bd3fdb0ac9c/app/main.js#L43)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Will `app.quit()` ensure that a currently running tunnel is disconnected?
</blockquote></details>

You were the last who worked on that piece ;)

https://github.com/mullvad/mullvadvpn-app/blob/0b30e5e5f4d118a05507f0303870f83d1ecda7a7/app/main.js.

I think it calls `before-quit`when that happens. I'll move the `before-quit` higher next to other app event handlers.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/main.js, line 452 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEj9xqo9OrWCBQwH-CW:-LEjHH374NTNuyMlTI3E:bea47qo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/873d56ad13a85fb5715eef84ac883bd3fdb0ac9c/app/main.js#L452)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could this function be named `_appHasTrayIcon()`?
</blockquote></details>

The result of this function is used to determine whether the window should be hidden once it goes out of focus (like popup menus / popovers)

The tray icon itself is always created if Electron is able to do so.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/main.js, line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEj7oxzExiKQ0XGjPCL:-LEjKGGV0_04b6t8iXWL:b-8ciruj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7119c56cfcebe66793e91120a78ad313ec3f98d/app/main.js#L43)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

You were the last who worked on that piece ;)

https://github.com/mullvad/mullvadvpn-app/blob/0b30e5e5f4d118a05507f0303870f83d1ecda7a7/app/main.js.

I think it calls `before-quit`when that happens. I'll move the `before-quit` higher next to other app event handlers.
</blockquote></details>

Hmm actually it makes sense to attach `before-quit` handler only after `ready`received.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jvff and @pinkisemils)

---

*[app/main.js, line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEj7oxzExiKQ0XGjPCL:-LEjMY_MEnAl7a5lCJma:bhh7nle) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7119c56cfcebe66793e91120a78ad313ec3f98d/app/main.js#L43)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Hmm actually it makes sense to attach `before-quit` handler only after `ready`received.
</blockquote></details>

It works as expected. So `app.quit` causes `before-quit` event, which we cancel with `preventDefault` and notify the renderer process that the app should quit, renderer process kills the tunnel and then sends `daemon-shutdown` back to main process.

1. `app.quit()`
2. `before-quit`. Checks if ready to quit, sends `app-shutdown` to renderer
3. `app-shutdown` - kills the tunnel and sends `daemon-shutdown` to main
4. main raises `readyToQuit` and calls `app.quit()` once again.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r3.
Review status: 0 of 11 files reviewed, all discussions resolved (waiting on @jvff and @pinkisemils)

---

*[app/main.js, line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEj7oxzExiKQ0XGjPCL:-LEjNhAuBLnlgMdsxReI:bm0w3hx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7119c56cfcebe66793e91120a78ad313ec3f98d/app/main.js#L43)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It works as expected. So `app.quit` causes `before-quit` event, which we cancel with `preventDefault` and notify the renderer process that the app should quit, renderer process kills the tunnel and then sends `daemon-shutdown` back to main process.

1. `app.quit()`
2. `before-quit`. Checks if ready to quit, sends `app-shutdown` to renderer
3. `app-shutdown` - kills the tunnel and sends `daemon-shutdown` to main
4. main raises `readyToQuit` and calls `app.quit()` once again.
</blockquote></details>

I guess I'm asking because I remember I was confused at the time I was working on it :)
I know that this isn't the most understandable code, but I guess you've not looked too much into making it easier to follow? No need to do so in this PR anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: 0 of 11 files reviewed, all discussions resolved (waiting on @jvff and @pinkisemils)

---

*[app/main.js, line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEj7oxzExiKQ0XGjPCL:-LEjOo8S63IYpL7k5jSs:b-6wqtmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7119c56cfcebe66793e91120a78ad313ec3f98d/app/main.js#L43)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I guess I'm asking because I remember I was confused at the time I was working on it :)
I know that this isn't the most understandable code, but I guess you've not looked too much into making it easier to follow? No need to do so in this PR anyway.
</blockquote></details>

Trying to keep the PRs small. Maybe we should have a class called `ShutdownHandler` that would keep the `ready` flag and handle a communication with renderer?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by jvff** [comment]
Reviewed 8 of 11 files at r1, 1 of 1 files at r2.
Review status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/app.js, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkBb9w8SYA0DQ75UrQ:-LEkBb9y2jIgRO7CidoW:b-k2ene8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/app.js#L60)):*
> ```JavaScript
>   log.info('Been told by the renderer process that the app is shutting down');
> 
>   // The shutdown behaviour may have to be different on mobile platforms
> ```

Would adding a `TODO` in the comment make sense?

---

*[app/lib/jsonrpc-ws-ipc.js, line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkETN-A2pWA6wkqadb:-LEkETN-A2pWA6wkqadc:bc4pv6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/lib/jsonrpc-ws-ipc.js#L109)):*
> ```JavaScript
>       }
>     } catch (e) {
>       log.error(`Failed adding listener to ${event}: e.message`);
> ```

Doesn't `e.message` need to be in `${}`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r3.
Review status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/main.js, line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEl8uIa5pgH2Bu93evy:-LEl8uIa5pgH2Bu93evz:b-c6tvta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/main.js#L196)):*
> ```JavaScript
>           });
>         } else {
>           log.debug(`Problem report is written to ${reportPath}`);
> ```

Minor suggestion: `Problem report was written to...`

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by jvff** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

---

*[app/app.js, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkBb9w8SYA0DQ75UrQ:-LEnCwjBAO11xiYEZMPY:b-qyrh8t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/app.js#L60)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Would adding a `TODO` in the comment make sense?
</blockquote></details>

I think we should remove that comment at once because this is a desktop app.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @jvff and @pronebird)

---

*[app/main.js, line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEl8uIa5pgH2Bu93evy:-LEnjxoB9DTArDCmFLd4:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/main.js#L196)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Minor suggestion: `Problem report was written to...`
</blockquote></details>

Done

---

*[app/lib/jsonrpc-ws-ipc.js, line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkETN-A2pWA6wkqadb:-LEnEmexAGujRFxEZ8lX:bwjqy6k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/lib/jsonrpc-ws-ipc.js#L109)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Doesn't `e.message` need to be in `${}`?
</blockquote></details>

Good spot. Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff and @pinkisemils)

---

*[app/lib/jsonrpc-ws-ipc.js, line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkETN-A2pWA6wkqadb:-LEnkBfz1sNFFCNKUL0q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/lib/jsonrpc-ws-ipc.js#L109)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Good spot. Fixed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pronebird** [comment]
Review status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff and @pinkisemils)

---

*[app/app.js, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkBb9w8SYA0DQ75UrQ:-LEnkEYO1bu4-5Kr8i0j:boo8m1a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/app.js#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I think we should remove that comment at once because this is a desktop app.
</blockquote></details>

This comment will be removed in the follow up PR that untangles the event system and adds `ShutdownCoordinator`. Can we leave it as is for now?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r4.
Review status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jvff and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[app/app.js, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206#-LEkBb9w8SYA0DQ75UrQ:-LEnyNDwCiqqdNpm4xOa:bb6mt9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c4a865f74ea6f3901889838f489423c3d030bc2/app/app.js#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This comment will be removed in the follow up PR that untangles the event system and adds `ShutdownCoordinator`. Can we leave it as is for now?
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/206)*

**Pull request merged**
