### PR TITLE
Check the authorization status of the launch daemon on macOS

### PR DESCRIPTION
**Pull request by dlon**
This PR adds a flag to `mullvad-daemon`, `--query-service`, which returns the authorization status of the launch daemon. If it is disallowed (`SMAppServiceStatusRequiresApproval`), then the GUI displays a message and a button that opens the login items panel, where the user can allow it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`gui/src/main/index.ts` line 896 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN2czqV3sOaJoM1i1PS:-NN2czqV3sOaJoM1i1PT:b-irviq6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/main/index.ts#L896)):*
> ```XML
>             this.daemonAllowed = false;
>             resolve();
>             return;
> ```

Nitpick: I would skip this return and add an else-statement, and also replace all the `resolve()` with one outside the if-statements since all branches resolve.
___
*[`gui/src/main/user-interface.ts` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5vyDr8X0l-NHaWIOv:-NN5vyDr8X0l-NHaWIOw:bw51kit) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/main/user-interface.ts#L76)):*
> ```XML
>     IpcMainEventChannel.app.handleShowLaunchDaemonSettings(async () => {
>       return new Promise((resolve, _reject) => {
>         exec('open -W x-apple.systempreferences:com.apple.LoginItems-Settings.extension');
> ```

This call is asynchronous and won't be finished when `resolve` is called on the line below. You will need to add a callback argument to `exec` the same way you did for `execFile` in `index.ts`, and then resolve in the callback.
___
*[`gui/src/renderer/components/ErrorView.tsx` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5zFDFCqtItmFgXZp2:-NN5zFDFCqtItmFgXZp3:b-s9r47g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/renderer/components/ErrorView.tsx#L24)):*
> ```XML
>   backgroundColor: colors.blue,
>   padding: '12px',
>   position: 'absolute',
> ```

We should use a flex-layout here to make sure that the reset of the component adjusts correctly if the text is a lot longer in other languages. I can do it if you don't want to spend the time :)
___
*[`gui/src/renderer/components/ErrorView.tsx` line 90 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5ytirAPe9Hn4N00FS:-NN5ytirAPe9Hn4N00FT:b-xzeg5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/renderer/components/ErrorView.tsx#L90)):*
> ```XML
> }
> 
> function SettingsFooter(props: ISettingsFooterProps) {
> ```

This component (along with the styled components further up) is pretty specific to the launch-view and I think it should be placed in there. We could pass it as an argument to `ErrorView` like `<ErrorView footer={SettingsFooter}>`.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/macos.rs` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN63UVICxgA3VZIyzd6:-NN63UVICxgA3VZIyzd7:b-p8vmpp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/mullvad-daemon/src/macos.rs#L95)):*
> ```XML
> type Id = libc::intptr_t;
> 
> const DAEMON_PLIST_PATH: &[u8] = b"/Library/LaunchDaemons/net.mullvad.daemon.plist\0";
> ```

I would prefer if all this new code in a separate module. And documentation please. I know the PR is WIP, but want to leave that feedback. We can have `mullvad-daemon/macos/...` be a module directory with multiple submodules. I don't think it makes sense to mix and match Plist handling with exclusion groups above.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 8 of 14 files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/main/index.ts` line 896 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN2czqV3sOaJoM1i1PS:-NN6DMMZE2dgCZMEDa-F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/main/index.ts#L896)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Nitpick: I would skip this return and add an else-statement, and also replace all the `resolve()` with one outside the if-statements since all branches resolve.
</blockquote></details>

Done.
___
*[`gui/src/main/user-interface.ts` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5vyDr8X0l-NHaWIOv:-NN6DU9lAz_vQE_OMrh3:b-brflc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/main/user-interface.ts#L76)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This call is asynchronous and won't be finished when `resolve` is called on the line below. You will need to add a callback argument to `exec` the same way you did for `execFile` in `index.ts`, and then resolve in the callback.
</blockquote></details>

Done. I used `promisify` instead. I hope this works.
___
*[`gui/src/renderer/components/ErrorView.tsx` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5zFDFCqtItmFgXZp2:-NN6DobL2W6zE6SxdjVC:b-8mg6tx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/renderer/components/ErrorView.tsx#L24)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We should use a flex-layout here to make sure that the reset of the component adjusts correctly if the text is a lot longer in other languages. I can do it if you don't want to spend the time :)
</blockquote></details>

Feel free to push commits to this PR.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 7 of 15 files reviewed, 4 unresolved discussions (waiting on @faern and @raksooo)

___
*[`mullvad-daemon/src/macos.rs` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN63UVICxgA3VZIyzd6:-NN6PPLRC4m3ttipplMK:bok0ker) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/mullvad-daemon/src/macos.rs#L95)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I would prefer if all this new code in a separate module. And documentation please. I know the PR is WIP, but want to leave that feedback. We can have `mullvad-daemon/macos/...` be a module directory with multiple submodules. I don't think it makes sense to mix and match Plist handling with exclusion groups above.
</blockquote></details>

Done. I just moved it to a new separate module, since we only ever use it in `main`. Does this make sense?

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 8 of 16 files reviewed, 5 unresolved discussions (waiting on @dlon and @raksooo)

___
*[`mullvad-daemon/src/cli.rs` line 122 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN7JfOU3UBJN__xpjL3:-NN7JfOU3UBJN__xpjL4:b-jmh11z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45e8a077c8166969aad548372a24f6f8c2a29494/mullvad-daemon/src/cli.rs#L122)):*
> ```XML
>             Arg::new("query_service")
>                 .long("query-service")
>                 .help("Checks the status of the launch daemon"),
> ```

Would be nice to explain in the CLI help text that the exit code represents the launch daemon status. Since it does not print anything to stdout/err it's a bit cryptic at the moment.
___
*[`mullvad-daemon/src/macos.rs` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN63UVICxgA3VZIyzd6:-NN7IkR7E6bBuC55sXYt:by7sn93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/mullvad-daemon/src/macos.rs#L95)):*
`mullvad-daemon/src/launch_daemon.rs`:
> //! Provides functions to handle or query the status of the Mullvad launch
> //! daemon/system service.

As it stands currently nothing about this module tells me it's about macOS specifically. Unless I happen to know launch daemons is a macOS specific thing. This is information I don't think a reader should need. Why keep it in the root? The layout of this crate is already very flat. I think it could benefit greatly from some deeper structure. `mullvad_daemon::macos::launch_daemon` would IMO be a better path for this.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 7 of 16 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`gui/src/main/user-interface.ts` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5vyDr8X0l-NHaWIOv:-NN8fU2V7cga-ZTZTihx:bkx1gtf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/main/user-interface.ts#L76)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. I used `promisify` instead. I hope this works.
</blockquote></details>

Works great! :+1:
___
*[`gui/src/renderer/components/ErrorView.tsx` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN5zFDFCqtItmFgXZp2:-NN8faDr3wrhJYqBbuk2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/gui/src/renderer/components/ErrorView.tsx#L24)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Feel free to push commits to this PR.
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 6 of 17 files reviewed, 2 unresolved discussions (waiting on @faern and @raksooo)

___
*[`mullvad-daemon/src/cli.rs` line 122 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN7JfOU3UBJN__xpjL3:-NNBHFiy0kTdkuZe7b6Z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45e8a077c8166969aad548372a24f6f8c2a29494/mullvad-daemon/src/cli.rs#L122)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Would be nice to explain in the CLI help text that the exit code represents the launch daemon status. Since it does not print anything to stdout/err it's a bit cryptic at the moment.
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/macos.rs` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NN63UVICxgA3VZIyzd6:-NNBHJsS9q4fYlFr6OyR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f40f70b713343f0de5e500f22b77bc7ac4826d53/mullvad-daemon/src/macos.rs#L95)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`mullvad-daemon/src/launch_daemon.rs`:
> //! Provides functions to handle or query the status of the Mullvad launch
> //! daemon/system service.

As it stands currently nothing about this module tells me it's about macOS specifically. Unless I happen to know launch daemons is a macOS specific thing. This is information I don't think a reader should need. Why keep it in the root? The layout of this crate is already very flat. I think it could benefit greatly from some deeper structure. `mullvad_daemon::macos::launch_daemon` would IMO be a better path for this.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 7 of 17 files reviewed, all discussions resolved (waiting on @raksooo)

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5, 1 of 4 files at r7, 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @dlon and @raksooo)

___
*[`mullvad-daemon/src/cli.rs` line 120 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNBXkln-K5cAlxEJiL8:-NNBXkln-K5cAlxEJiL9:bkx4k6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6831bd741961f0ea2fa965140759b1db369c4829/mullvad-daemon/src/cli.rs#L120)):*
> ```XML
>     if cfg!(target_os = "macos") {
>         app = app.arg(Arg::new("query_service").long("query-service").help(
>             "Checks the status of the launch daemon. The exit code represents the current status",
> ```

Is the flag naming "query-service" user friendly enough? I see in the low level API Apple refers to them as services, but we always talk about them as launch daemons. And "query" is very generic. Query it about what? This is sort of a nitpick, but I might opt for calling the flag `--launch-daemon-status`.
___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 35 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNBXLy83LxRKgN9pI1G:-NNBXLy83LxRKgN9pI1H:bfqmzo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6831bd741961f0ea2fa965140759b1db369c4829/mullvad-daemon/src/macos_launch_daemon.rs#L35)):*
> ```XML
> /// Return whether the daemon is running, not found, or is not authorized.
> /// NOTE: On macos < 13, this function always returns `LaunchDaemonStatus::Ok`.
> pub fn get_status() -> LaunchDaemonStatus {
> ```

Nit: For readability and code cleanliness I would personally have split this into multiple functions. Maybe one for probing macOS version and one for probing daemon status. Maybe one for NSUrl initialization etc.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @dlon and @raksooo)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @faern and @raksooo)

___
*[`mullvad-daemon/src/cli.rs` line 120 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNBXkln-K5cAlxEJiL8:-NNB_yW1-58JfiwGMbDG:bwbq2uh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6831bd741961f0ea2fa965140759b1db369c4829/mullvad-daemon/src/cli.rs#L120)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is the flag naming "query-service" user friendly enough? I see in the low level API Apple refers to them as services, but we always talk about them as launch daemons. And "query" is very generic. Query it about what? This is sort of a nitpick, but I might opt for calling the flag `--launch-daemon-status`.
</blockquote></details>

I'll change it, but maybe it should also be hidden. I don't think there's any reason for it to be visible to users.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 7 of 17 files reviewed, 1 unresolved discussion (waiting on @faern and @raksooo)

___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 35 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNBXLy83LxRKgN9pI1G:-NNC-oTk1UhVhUkWJOOX:bgy85ho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6831bd741961f0ea2fa965140759b1db369c4829/mullvad-daemon/src/macos_launch_daemon.rs#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit: For readability and code cleanliness I would personally have split this into multiple functions. Maybe one for probing macOS version and one for probing daemon status. Maybe one for NSUrl initialization etc.
</blockquote></details>

Done. Hopefully this is an improvement.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 9 of 17 files reviewed, 3 unresolved discussions (waiting on @dlon and @raksooo)

___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 24 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNC4Orc6rYfBXaNt1Hb:-NNC4Orc6rYfBXaNt1Hc:b-vx9vw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81442cb7bce2191a01d71fde7131096da3076a99/mullvad-daemon/src/macos_launch_daemon.rs#L24)):*
> ```XML
> /// Errors that can happen when using the OpenVPN tunnel.
> #[derive(err_derive::Error, Debug)]
> pub enum Error {
> ```

How is this error type related to OpenVPN?

It does not need to be public. This error is never exposed from the module. Feels overkill in general to define an entire error type for a single error that we also never handle, but rather just unwrap. Can't we make `nsurl_from_str` infallible and have it define the hardcoded URL inside itself? That way it becomes self contained.
___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 91 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNC3vae3ekllA3uYyYH:-NNC3vaf-3ANvKTqu9qA:b-d0uptt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81442cb7bce2191a01d71fde7131096da3076a99/mullvad-daemon/src/macos_launch_daemon.rs#L91)):*
> ```XML
>     let _: libc::c_void = unsafe { msg_send![nsstr_inst, release] };
> 
>     if nsurl_inst == std::ptr::null_mut() {
> ```

nit: `.is_null()` is more idiomatic.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 9 of 17 files reviewed, 3 unresolved discussions (waiting on @dlon and @raksooo)

___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 35 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNBXLy83LxRKgN9pI1G:-NNC4w5n2ObOn4oqbovF:b-irprs2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6831bd741961f0ea2fa965140759b1db369c4829/mullvad-daemon/src/macos_launch_daemon.rs#L35)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. Hopefully this is an improvement.
</blockquote></details>

Yes! Much better in general. But I think we can simplify the error handling, as pointed out in a different thread.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 8 of 17 files reviewed, 2 unresolved discussions (waiting on @faern and @raksooo)

___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 24 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNC4Orc6rYfBXaNt1Hb:-NNC731i7ttClg2sD-EI:bciquru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81442cb7bce2191a01d71fde7131096da3076a99/mullvad-daemon/src/macos_launch_daemon.rs#L24)):*
It's related in that I copied the enum from elsewhere and forgot to update the comment.

> Can't we make nsurl_from_str infallible and have it define the hardcoded URL inside itself? That way it becomes self contained

Done. Renamed since it's no longer general.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r18, 1 of 7 files at r19, 2 of 4 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 11 of 17 files reviewed, 2 unresolved discussions (waiting on @dlon and @raksooo)

___
*[`mullvad-daemon/src/cli.rs` line 120 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNBXkln-K5cAlxEJiL8:-NNCGSfxCAGyiLxdeUcO:bxpbove) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6831bd741961f0ea2fa965140759b1db369c4829/mullvad-daemon/src/cli.rs#L120)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'll change it, but maybe it should also be hidden. I don't think there's any reason for it to be visible to users.
</blockquote></details>

Making it hidden is an option. But given that no user is really supposed to manually run `mullvad-daemon` ever anyway it does not matter if it's there. It would be different if the `mullvad` binary had not-user-facing options, those should be hidden to allow the CLI to be clean.
___
*[`mullvad-daemon/src/cli.rs` line 10 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNCHhfa8bI4DOz1BXV0:-NNCHhfa8bI4DOz1BXV1:byn2jh4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b920d603fd707d64213efa8c7b262b5b0f97d422/mullvad-daemon/src/cli.rs#L10)):*
> ```XML
>     pub run_as_service: bool,
>     pub register_service: bool,
>     pub launch_daemon_status: bool,
> ```

I think this field should be conditionally compiled, just as `initialize_firewall_and_exit`. That way it becomes more self documenting where it's used.
___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 24 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNC4Orc6rYfBXaNt1Hb:-NNCH6Kt-GUYgrz0NHge:b-qp4cum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81442cb7bce2191a01d71fde7131096da3076a99/mullvad-daemon/src/macos_launch_daemon.rs#L24)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's related in that I copied the enum from elsewhere and forgot to update the comment.

> Can't we make nsurl_from_str infallible and have it define the hardcoded URL inside itself? That way it becomes self contained

Done. Renamed since it's no longer general.
</blockquote></details>

Oooh, this is cleeeen now :sparkles: 
___
*[`mullvad-daemon/src/macos_launch_daemon.rs` line 71 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319#-NNCHHsJBeilILc0N4vz:-NNCHHsJBeilILc0N4w-:bc4icas) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b920d603fd707d64213efa8c7b262b5b0f97d422/mullvad-daemon/src/macos_launch_daemon.rs#L71)):*
This will most certainly be forgotten to be updated if we ever move the plist. Would it maybe help to add a comment both here and in `dist-assets/pkg-scripts/postinstall` next to the same path over there saying:

> This must be kept in sync with {other place}.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 4 files at r5, 4 of 6 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 13 of 18 files reviewed, all discussions resolved (waiting on @raksooo)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 6 files at r24.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 14 of 18 files reviewed, all discussions resolved (waiting on @raksooo)

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 1 of 6 files at r24.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)* status: 16 of 18 files reviewed, all discussions resolved

**Pull request merged**
