### PR TITLE
Add support for bullets in changes file

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389#-O-oWvaICzuzA3SxNLVt:-O-oWvaJ-Yni3pCw78Na:buczv0p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/745e53b3f1c46ae626ed7d4a939e4677c6a4f8d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L16)):*
> ```Kotlin
>     Html.fromHtml(this, HtmlCompat.FROM_HTML_MODE_LEGACY).toString()
> 
> fun List<String>.trim() = map { it.trim() }
> ```

I suggest renaming to `trimAll`



_Code quote:_
```Kotlin
trim
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389#-O-oWvaICzuzA3SxNLVt:-O-o_L0wDvRnp3m53lGe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/745e53b3f1c46ae626ed7d4a939e4677c6a4f8d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `trimAll`
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389#-:-O-onBgY5nK7ifmdKTAr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepository.kt` line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389#-O08CeVX-SUXqzpO5CRr:-O08CeVX-SUXqzpO5CRs:bplsjha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb8dfd748136ad26aecf35e91ef6a01ec722a70d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepository.kt#L29)):*
> ```Kotlin
>             .getChangelog()
>             .split(BULLET_POINT_CHAR)
>             .map { it.split(NEWLINE_CHAR).trimAll().fastJoinToString(SPACE_STRING).trim() }
> ```

Not sure what we feel about `fastJoinToString` it comes from the `compose.ui.util` package, do we see a good purpose to have it? Or should we just use the normal joinToString?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepository.kt` line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389#-O08CeVX-SUXqzpO5CRr:-O08MOhd6No_wf47uk1a:bxyzng8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb8dfd748136ad26aecf35e91ef6a01ec722a70d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepository.kt#L29)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure what we feel about `fastJoinToString` it comes from the `compose.ui.util` package, do we see a good purpose to have it? Or should we just use the normal joinToString?
</blockquote></details>

No it was just me that was confused and though it was part of some kotlin library instead of compose. Changed it to `joinToString`

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
