### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/build.gradle.kts` line 343 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUPmybD_K_EOt4RsXz:-NkUPmybD_K_EOt4RsY-:b-o4hyt0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c8d672a199185fbe7ae7aebc98d7464d4a590dc/android/app/build.gradle.kts#L343)):*
> ```Kotlin
>     implementation(Dependencies.Koin.core)
>     implementation(Dependencies.Koin.android)
>     implementation(Dependencies.Koin.compose)
> ```

I believe this one should be kept, it is used by the new navigation PR.
___
*[`android/service/build.gradle.kts` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUXrrFC7xL0yKM5iuq:-NkUXrrFC7xL0yKM5iur:biparj1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c8d672a199185fbe7ae7aebc98d7464d4a590dc/android/service/build.gradle.kts#L54)):*
> ```Kotlin
>     implementation(project(Dependencies.Mullvad.ipcLib))
>     implementation(project(Dependencies.Mullvad.modelLib))
>     implementation(project(Dependencies.Mullvad.resourceLib))
> ```

Since it handles the notifications shouldn't it also need the `resourceLib` to get its' strings?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/buildSrc/src/main/kotlin/Dependencies.kt` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUZZUZBw_tSNS9fwqg:-NkUZZUZBw_tSNS9fwqh:b-9rsn19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ed049dc926c8b3c073b0edad8b51ced5ce93593/android/buildSrc/src/main/kotlin/Dependencies.kt#L0)):*
We have some weird additions in this file even though we made just removals from the dependencies, @albin-mullvad  can you double check to see if the file would be the same for you?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/service/build.gradle.kts` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUXrrFC7xL0yKM5iuq:-NkU_K0o6iDRK66oidt5:b-t8ukau) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c8d672a199185fbe7ae7aebc98d7464d4a590dc/android/service/build.gradle.kts#L54)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Since it handles the notifications shouldn't it also need the `resourceLib` to get its' strings?
</blockquote></details>

Seems like this gets retrieved through commonLib. Should we keep it for clarify or not?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/build.gradle.kts` line 343 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUPmybD_K_EOt4RsXz:-NkZxIqh9IV_Ky0vjoFm:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c8d672a199185fbe7ae7aebc98d7464d4a590dc/android/app/build.gradle.kts#L343)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe this one should be kept, it is used by the new navigation PR.
</blockquote></details>

Done

**Review by Rawa — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-:-NkzlXRw12_vTKfRMxbW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/buildSrc/src/main/kotlin/Dependencies.kt` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUZZUZBw_tSNS9fwqg:-Nm0awZEEur699HiDkul:b-4vmzro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ed049dc926c8b3c073b0edad8b51ced5ce93593/android/buildSrc/src/main/kotlin/Dependencies.kt#L)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We have some weird additions in this file even though we made just removals from the dependencies, @albin-mullvad  can you double check to see if the file would be the same for you?
</blockquote></details>

I managed to run the update lock file script in docker. @albin-mullvad can you verify that the output is correct?

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-:-Nn8aKho9WxVO_LtwtwI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/buildSrc/src/main/kotlin/Dependencies.kt` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUZZUZBw_tSNS9fwqg:-Nn8aMzt75kkmXwTcJ2R:b-2oshw5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ed049dc926c8b3c073b0edad8b51ced5ce93593/android/buildSrc/src/main/kotlin/Dependencies.kt#L)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I managed to run the update lock file script in docker. @albin-mullvad can you verify that the output is correct?
</blockquote></details>

I've verified that it looks correct by re-generating the lockfile locally.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/service/build.gradle.kts` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5523#-NkUXrrFC7xL0yKM5iuq:-Nn96mL60HiYaZT4LcRP:brey3ps) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c8d672a199185fbe7ae7aebc98d7464d4a590dc/android/service/build.gradle.kts#L54)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think we can keep `resourceLib` for clarity, what do you think @albin-mullvad ?
</blockquote></details>

After discussion with @albin-mullvad we decided to remove it as it would make it easier to use such tools in the future.

**Pull request merged**
