### PR TITLE
Add apparmor profile on Ubuntu 24.04 or later

### LINKED ISSUE #6128: Impossible to launch Mullvad GUI | The SUID sandbox helper binary was found, but is not configured correctly.
It works using `--no-sandbox`.

### PR DESCRIPTION
**Pull request by dlon**
Disable restrictions for unprivileged user namespaces. See [this](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890) for details.

Fix #6128.
Fix DES-924.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6196)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6196)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`dist-assets/linux/after-install.sh` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6196#-NwhrgR8-UwXBMumeLUT:-NwhrgR8-UwXBMumeLUU:b18ru4n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c9b38e937dbaa3390e69753b0f667a1bb049b6/dist-assets/linux/after-install.sh#L33)):*
> ```Shell
>   include if exists <local/mullvad>
> }
> EOF
> ```

Are you opposed to shipping this AppArmor profile in a separate file (in `dist-assets/linux/`) instead? We already do this with our systemd services, and I feel like it will be slightly easier to see what we actually bundle with the app :blush:



_Code quote:_
```Shell
    cat <<EOF > /etc/apparmor.d/mullvad
abi <abi/4.0>,
include <tunables/global>

profile mullvad /opt/Mullvad\ VPN/mullvad-gui flags=(unconfined) {
  userns,
  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/mullvad>
}
EOF
```

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6196)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`dist-assets/linux/after-install.sh` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6196#-NwhrgR8-UwXBMumeLUT:-Nwi24Z8B7oj3sZb7y-Y:bcv502w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c9b38e937dbaa3390e69753b0f667a1bb049b6/dist-assets/linux/after-install.sh#L33)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Are you opposed to shipping this AppArmor profile in a separate file (in `dist-assets/linux/`) instead? We already do this with our systemd services, and I feel like it will be slightly easier to see what we actually bundle with the app :blush:
</blockquote></details>

Nice :+1:

**Comment by greengem70** [comment]
Installed 24.02 hoping fixed but still fails.     GUI does not launch from Applications

From terminal:
/opt/Mullvad\ VPN/mullvad-gui 

gives.
[314073:0506/195002.808568:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Mullvad VPN/chrome-sandbox is owned by root and has mode 4755.

Workaround still functions.

**Comment by dlon** [comment]
@greengem70 This was included in the 2024.3-beta1 release. Did you try that one?

**Comment by gamer191** [comment]
If this script only runs when installing Mullvad on 24.04, doesn't that mean that Mullvad VPN will need to be re-installed when upgrading to 24.04?

**Comment by MarkusPettersson98** [comment]
Yes, that is an unfortunate consequence.

**Comment by gamer191** [comment]
@MarkusPettersson98 would it make more sense to  always copy the profile if the OS is Ubuntu?

**Comment by MarkusPettersson98** [comment]
I don't think it makes too much sense _any more_. The number of people upgrading from an earlier version of Ubuntu to 24.04 is decreasing all the time, and deploying the suggested fix would already run our apparmor deployment since people would be upgrading their app version. If we would have been quicker to pick up this fix on our side, then I would be all for it.

Thanks for making us aware about this potential issue, such efforts are always appreciated :yellow_heart:

**Comment by gamer191** [comment]
@MarkusPettersson98 According to https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890

>Users of 22.04 LTS however will be offered the automatic upgrade when 24.04.1 LTS is released, which is scheduled for the 15th of August.

As such, I suspect there will be a large increase in the number of users experiencing this issue in about 2 days (sorry, I just noticed that now)

**Comment by MarkusPettersson98** [comment]
Thanks for making us aware of those release notes, we'll see what we can do to prepare for this event.

**Pull request merged**
