### PR TITLE
REST: handle HTTP 200 and 201 in /v1/create-apple-payment

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR fixes the regression in REST API handling where `/v1/create-apple-payment` was not properly handling both `200` and `201` responses.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/MullvadRest.swift, line 792 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757#-MaE49UC9OUKDqieGA63:-MaE49UD7CLbvEYNQBuR:bq5zud7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db384bb79fc232819a26dfc7888ec423907fa51b/ios/MullvadVPN/MullvadRest.swift#L792)):*
> ```Swift
>         formatter.allowedUnits = [.day, .hour]
>         formatter.unitsStyle = .full
>         
> ```

Leftover whitespace here.

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/MullvadVPN/MullvadRest.swift, line 792 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757#-MaE49UC9OUKDqieGA63:-MaEAaXk-LsOsj_h6exw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db384bb79fc232819a26dfc7888ec423907fa51b/ios/MullvadVPN/MullvadRest.swift#L792)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Leftover whitespace here.
</blockquote></details>

Done.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757#-:-MaEMvFr7JMrgxwgLzbB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
