### PR TITLE
Fix `test-runner` bootstrap failing if `apt` lock is already held

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Seems to be working: https://github.com/mullvad/mullvadvpn-app/actions/runs/10616373857

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test/scripts/ssh-setup.sh` line 132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712#-O5YgAcW2lJ0kG_epGSv:-O5YjOlC1Vn-aUb_wBRC:b-gsl22j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fde7907e45c4c7720fbf3edc99e4cc71ba85c44/test/scripts/ssh-setup.sh#L132)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We should probably also wait for the lock when installing the app (in `test-runner`).
</blockquote></details>

That's probably a good idea. Working on it

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/test-runner/src/package.rs` line 155 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712#-O5lcO054svyKSAEqHjZ:-O5lcO054svyKSAEqHj_:b33tggt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e98d9fbce0f9c8e9052cf09ad38a2bbf6085a53/test/test-runner/src/package.rs#L155)):*
> ```XML
>     if purge {
>         action = "apt --purge";
>         cmd.args(["--purge", name]);
> ```

I think this should be `purge` now, not `--purge`.

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-runner/src/package.rs` line 152 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712#-O5ldAVo9fAHLBC4CygK:-O5ldAVpAcihljfSDgux:b-x0a94t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e98d9fbce0f9c8e9052cf09ad38a2bbf6085a53/test/test-runner/src/package.rs#L152)):*
> ```XML
> async fn uninstall_apt(name: &str, env: HashMap<String, String>, purge: bool) -> Result<()> {
>     let action;
>     let mut cmd = Command::new("/usr/bin/apt");
> ```

Can `DPkg::Lock::Timeout` be set here too?

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712#-:-O5lh1jxCgC4FWa9cc-L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
