### PR TITLE
Fix e2e and mockapi tests failing

### PR DESCRIPTION
**Pull request by niklasberglund**
This PR contains fixes for making e2e and mockapi tests run.

 - Added dependencies to mockapi and e2e's gradle files. We found that adding these dependencies fixes a crash when running tests because dependency versions are bumped.
 - Fix for Firebase e2e tests running against production instead of stagemole.
 - Fix for Firebase e2e tests hitting rate limits due to setup running for disabled tests and tests possibly running twice.
 - Running tests highly affected by rate limiting nightly only. Introduced `enable_highly_rate_limited_tests` for specifying whether these tests should run or not.
 - Removed `testCreateAccountAndLogout`.
 - Re-enabled `testLoginWithInvalidCredentials` to see if it is stable now.

The changes in this PR can be tested by running the Android - Build and test workflow with e2e tests and firebase tests enabled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/mockapi/build.gradle.kts` line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4B4lo1E8N2k8TUkAG2:-O4B4lo1E8N2k8TUkAG3:b-4by25c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68c8d64341853364223cb1c7f0396f86bb10dcee/android/test/mockapi/build.gradle.kts#L93)):*
> ```Kotlin
> 
>     implementation(Dependencies.junit5AndroidTestCompose)
>     implementation(libs.compose.material3)
> ```

I suggest trying to include `implementation(libs.compose.ui)` as well to see if that helps gradle use newer versions of various dependencies 
___
*[`android/test/mockapi/build.gradle.kts` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4B51QfCeG0UFhugaQ7:-O4B51QfCeG0UFhugaQ8:b-9t6rpm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68c8d64341853364223cb1c7f0396f86bb10dcee/android/test/mockapi/build.gradle.kts#L94)):*
> ```Kotlin
>     implementation(Dependencies.junit5AndroidTestCompose)
>     implementation(libs.compose.material3)
> }
> ```

We should make similar adjustments to `android/test/e2e/build.gradle.kts` and also make sure we're able to run those tests.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-:-O4JepV43LpIZtNxswki:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: all files reviewed, 4 unresolved discussions (waiting on @niklasberglund)

___
*[`.github/workflows/android-app.yml` line 472 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4LWa0DAjIbAEWGkWTi:-O4LWa0DAjIbAEWGkWTj:bewwr7l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/780149d43839decafb7c9749add8d3efb5153b96/.github/workflows/android-app.yml#L472)):*
> ```YAML
>   instrumented-e2e-tests:
>     name: Run instrumented e2e tests
>     runs-on: [self-hosted, android-device, android-runner-v1] # Temporary until we can add secrets
> ```

I suggest clarifying that this refers specifically to `android-runner-v1`. Would also be nice to move the comment to the line above since the suggestion would result in a quite long line



_Code quote:_
```YAML
# Temporary until we can add secrets
```
___
*[`.github/workflows/android-app.yml` line 504 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4LX-m_5y_-cQ_hgCxd:-O4LX-ma7TnZzQNdBFjk:betrhst) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/780149d43839decafb7c9749add8d3efb5153b96/.github/workflows/android-app.yml#L504)):*
> ```YAML
>         run: |
>           if [ ${{github.event_name}} == 'schedule' ]; then
>             echo "ignore_highly_rate_limited_tests=false" >> $GITHUB_ENV
> ```

I believe it would be a good idea to invert this variable to avoid a double-false which can easily be misunderstood. So e.g. use the following here: `enable_highly_rate_limited_tests=true` 



_Code quote:_
```YAML
ignore_highly_rate_limited_tests=false
```
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/annotations/HighlyRateLimited.kt` line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4LY4Lk4TQT5XFFIweX:-O4LY4Lk4TQT5XFFIweY:bkgly8m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/780149d43839decafb7c9749add8d3efb5153b96/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/annotations/HighlyRateLimited.kt#L23)):*
Can this be shortened a bit? The following should be sufficient and also matches the `enabled` case:

> Skipping test test highly affected by rate limiting.



_Code quote:_
```Kotlin
Skipping test because this run is configured to skip tests that are highly affected by rate limiting
```
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/annotations/HighlyRateLimited.kt` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4LYtZC9aVkHfu_sOZk:-O4LYtZDB3M8TC0JYctG:bl402lr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/780149d43839decafb7c9749add8d3efb5153b96/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/annotations/HighlyRateLimited.kt#L25)):*
> ```Kotlin
>                 return ConditionEvaluationResult.disabled("Skipping test because this run is configured to skip tests that are highly affected by rate limiting")
>             } else {
>                 return ConditionEvaluationResult.enabled("Running test highly affected by rate limiting")
> ```

nit: please add a dot



_Code quote:_
```Kotlin
limiting")
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @niklasberglund)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @niklasberglund)

___
*[`-- commits` line 22 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4PBMaP3lKpQ3_fToSq):*
Too long and a bit difficult to parse, please try to clarify. E.g. is it running or ignoring the mentioned tests? 



_Code quote:_
```
Both firebase and self hosted e2e runs ignoring rate limited tests
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 4 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @niklasberglund and @Pururun)

**Review by Pururun — COMMENTED** [review]
> Reviewed 3 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: all files reviewed, 3 unresolved discussions (waiting on @niklasberglund)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 8 files at r6, 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/scripts/run-instrumented-tests.sh` line 134 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4dnZKE7pP1iDQY5ow5:-O4dnZKE7pP1iDQY5ow6:bfhi58a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dad6611d77ee3d6984af5697896b027b977994ca/android/scripts/run-instrumented-tests.sh#L134)):*
> ```Shell
>         exit 1
>     fi
>     if [[ "${ENABLE_HIGHLY_RATE_LIMITED_TESTS}" == "false" ]]; then
> ```

Should we not set the test argument for both `true` and `false`? :thinking: 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 38 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4dnjKP5sbhhs3757FL:-O4dnjKP5sbhhs3757FM:b-knu4sb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dad6611d77ee3d6984af5697896b027b977994ca/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L38)):*
> ```Kotlin
> 
>     @Test
>     @Disabled
> ```

Just to double check since I don't remember. Did we decide to disable this test for now?



_Code quote:_
```Kotlin
@Disabled
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 3 of 8 files at r2, 1 of 8 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/scripts/run-instrumented-tests.sh` line 134 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4dnZKE7pP1iDQY5ow5:-O4dvFda13rPJXmdRzi2:bpduh3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dad6611d77ee3d6984af5697896b027b977994ca/android/scripts/run-instrumented-tests.sh#L134)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should we not set the test argument for both `true` and `false`? :thinking:
</blockquote></details>

True, now setting for both and also made `enable_highly_rate_limited_tests` optional with default value `false`.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 38 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610#-O4dnjKP5sbhhs3757FL:-O4drdKq9hC5qrpFcUlu:b-s531wk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dad6611d77ee3d6984af5697896b027b977994ca/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L38)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just to double check since I don't remember. Did we decide to disable this test for now?
</blockquote></details>

Yes we said it can be re-introduced later. Created an issue for it https://linear.app/mullvad/issue/DROID-1262/fix-failing-test-testconnectandverifywithconnectioncheck

The useful description to go with `@Disabled` has been removed though, I have now added it again.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by niklasberglund — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: 15 of 16 files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6610)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
