### PR TITLE
Replace retry with exponential backoff with arrow schedule

### PR DESCRIPTION
**Pull request by Pururun**
Also clean up the code related to play purchase verification

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_w5o92ImSajPizMDK:-O-_w5o92ImSajPizMDL:b-vuspj4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4432dbe92a4d670b82b430bf6da42c62eb9c9352/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L61)):*
> ```Kotlin
>     }
> 
>     override suspend fun verifyPurchases() =
> ```

It's a bit difficult to interpret what this boolean means in respect to `verifyPurchases`. `true` could for example potentially mean that "everything has already been verified".

Also, I'm a bit curious to hear your thoughts on whether or not we could expose the result as an `either` :thinking: 



_Code quote:_
```Kotlin
verifyPurchases
```
___
*[`android/lib/payment/build.gradle.kts` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_uHjcAkN3gTzzOLfg:-O-_uHjcAkN3gTzzOLfh:byoilph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4432dbe92a4d670b82b430bf6da42c62eb9c9352/android/lib/payment/build.gradle.kts#L44)):*
> ```Kotlin
>     implementation(Dependencies.Kotlin.stdlib)
>     implementation(Dependencies.KotlinX.coroutinesAndroid)
>     implementation(Dependencies.Arrow.core)
> ```

nit: move to the top of the dependency list



_Code quote:_
```Kotlin
implementation(Dependencies.Arrow.core)
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 5 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_w5o92ImSajPizMDK:-O-eYFjU7Puui1w1ERGo:b-p74ufm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3373677adb44f7053c27c3bffac65df94f9699a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L61)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess it depends if you want to add `getOrNull() == VerificationResult.Success` to all viewmodels or not.
Updated.
</blockquote></details>

Yeah, I think it's best to prioritze keeping the main API clear even though it might require the rest of the code to be a bit more verbose.

Maybe there's some arrow/either API that can be used to make the VMs prettier? Otherwise we can always consider using some extension function such as:

```
fun Either<VerificationError, VerificationResult>.isSuccess() =
        this.getOrNull() == VerificationResult.Success
```

Which would let the VMs use:
```
paymentUseCase.verifyPurchases().isSuccess()
```
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-e_lKt8EuI5VcxHXeb:-O-e_lKt8EuI5VcxHXec:b-t7cjwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a5bc6221a1eb898cfb86fb3441bb3581d62f26c/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L136)):*
> ```Kotlin
>     }
> 
>     override suspend fun verifyPurchases(): Either<VerificationError, VerificationResult> = either {
> ```

How will the lack of emitting `FetchingUnfinishedPurchases` and `VerificationStarted` here impact the code and app behavior? :thinking:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_w5o92ImSajPizMDK:-O-fBGaxEQ2SOrnTT_iK:b8pirb7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3373677adb44f7053c27c3bffac65df94f9699a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L61)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yeah, I think it's best to prioritze keeping the main API clear even though it might require the rest of the code to be a bit more verbose.

Maybe there's some arrow/either API that can be used to make the VMs prettier? Otherwise we can always consider using some extension function such as:

```
fun Either<VerificationError, VerificationResult>.isSuccess() =
        this.getOrNull() == VerificationResult.Success
```

Which would let the VMs use:
```
paymentUseCase.verifyPurchases().isSuccess()
```
</blockquote></details>

Yes that would look better.
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-e_lKt8EuI5VcxHXeb:-O-fBM201rj9r81Eyo8J:b-r2l22j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a5bc6221a1eb898cfb86fb3441bb3581d62f26c/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L136)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

How will the lack of emitting `FetchingUnfinishedPurchases` and `VerificationStarted` here impact the code and app behavior? :thinking:
</blockquote></details>

No impact at all. The fact that it was a flow that emitted states before was kind of redundant since we only checked for success state and error states.

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_w5o92ImSajPizMDK:-O-fDnRd4RQvFXMKOKrv:bjd2ox2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3373677adb44f7053c27c3bffac65df94f9699a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L61)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes that would look better.
</blockquote></details>

So that means you'll update the PR? I'm fine with either keeping as-is or updating :slightly_smiling_face: 
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 136 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-e_lKt8EuI5VcxHXeb:-O-fDgi10ns1SUQGPWPD:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a5bc6221a1eb898cfb86fb3441bb3581d62f26c/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L136)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

No impact at all. The fact that it was a flow that emitted states before was kind of redundant since we only checked for success state and error states.
</blockquote></details>

Alright :thumbsup:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_w5o92ImSajPizMDK:-O-fYnaYE4MXl2CRSDBW:b-sjmgk7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3373677adb44f7053c27c3bffac65df94f9699a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L61)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

So that means you'll update the PR? I'm fine with either keeping as-is or updating :slightly_smiling_face:
</blockquote></details>

Yes sorry, will add it.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: 10 of 16 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-O-_w5o92ImSajPizMDK:-O-f__O41cF1Auh9AHkN:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3373677adb44f7053c27c3bffac65df94f9699a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L61)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes sorry, will add it.
</blockquote></details>

Done

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-:-O-foO1B20sZ66oDyFO8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6362#-:-O-k9JwI1eD2VcCgctkp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
