### PR TITLE
Do not fail installation in containers without systemd init

### PR DESCRIPTION
**Pull request by pavinjosdev**
Do not fail installation in containers without systemd init.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5431)

### CODE REVIEW

**Comment by faern** [comment]
We are going to discuss if we want to relax the scripts like this or not. In general we don't support non-systemd systems and we are not going to spend time on supporting them. But this is slightly different. We just need to figure out if this PR could have any negative impact on our regular non-container users or not.

Can you maybe describe a bit more in detail why you want this PR merged? What's your setup where you want to run the app in a container?

**Comment by faern** [comment]
Sorry, specifically containers without systemd. I can install our app fine in a regular fedora container. Why do you need your container to be systemd-less? I doubt we will support such an edge case.

**Comment by pavinjosdev** [comment]
I'm using [distrobox](https://github.com/89luca89/distrobox) with podman. Its init/systemd flag is unfortunately not working as expected, for example if I have mullvad running, then firefox would get segfaults.
Fedora's [toolbox](https://github.com/containers/toolbox) which comes pre-installed with their immutable distros like Silverblue / Kinote does not support any init system.

Could you share how you're running the app inside container with systemd? Thanks.

**Comment by faern** [comment]
I'm confused why this is needed to make it work. My Fedora containers also don't have systemd but it works fine. What errors do you get?

I run this:
```
$ podman run --rm -it fedora:latest
# dnf install -y https://releases.mullvad.net/desktop/releases/2023.5/MullvadVPN-2023.5_x86_64.rpm
....
  Running scriptlet: mullvad-vpn-2023.5-1.x86_64                                                                                                                   13/13
/var/tmp/rpm-tmp.IQM4S3: line 17: pkill: command not found

  Installing       : mullvad-vpn-2023.5-1.x86_64                                                                                                                   13/13
  Running scriptlet: mullvad-vpn-2023.5-1.x86_64                                                                                                                   13/13
/var/tmp/rpm-tmp.Lt3YmJ: line 6: systemctl: command not found
warning: %post(mullvad-vpn-2023.5-1.x86_64) scriptlet failed, exit status 127

Error in POSTIN scriptlet in rpm package mullvad-vpn
/var/tmp/rpm-tmp.XD4IWQ: line 9: systemctl: command not found
/var/tmp/rpm-tmp.XD4IWQ: line 10: systemctl: command not found
/var/tmp/rpm-tmp.XD4IWQ: line 11: systemctl: command not found
/var/tmp/rpm-tmp.XD4IWQ: line 12: systemctl: command not found
```
BUT it still installs. The package scripts obviously get a lot of errors. And no system service starts automatically, of course. And the daemon can't be started afterwards. But I don't see how the code in this PR would change that issue.

**Comment by pavinjosdev** [comment]
I confirm dnf on fedora handles this much more gracefully. But apt does not. After failing the installation, it keeps trying to fix it by reconfiguring the mullvad-vpn package every time an upgrade or install of other packages are performed.

Following is the log from a debian 12 distrobox/container without systemd/init running on podman:

```
pavin@deb:~/Downloads$ sudo apt install ./MullvadVPN-2023.5_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'mullvad-vpn' instead of './MullvadVPN-2023.5_amd64.deb'
The following additional packages will be installed:
  libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-indicator3-7 libdbusmenu-glib4 libdbusmenu-gtk3-4
The following NEW packages will be installed:
  libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-indicator3-7 libdbusmenu-glib4 libdbusmenu-gtk3-4 mullvad-vpn
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 186 kB/82.3 MB of archives.
After this operation, 329 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://deb.debian.org/debian bookworm/main amd64 libayatana-ido3-0.4-0 amd64 0.9.3-1 [57.6 kB]
Get:2 /var/home/pavin/Downloads/MullvadVPN-2023.5_amd64.deb mullvad-vpn amd64 2023.5 [82.1 MB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 libayatana-indicator3-7 amd64 0.9.3-1 [32.8 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 libdbusmenu-glib4 amd64 18.10.20180917~bzr492+repack1-3 [42.1 kB]
Get:5 http://deb.debian.org/debian bookworm/main amd64 libdbusmenu-gtk3-4 amd64 18.10.20180917~bzr492+repack1-3 [29.0 kB]
Get:6 http://deb.debian.org/debian bookworm/main amd64 libayatana-appindicator3-1 amd64 0.5.92-1 [24.5 kB]
Fetched 186 kB in 1s (300 kB/s)                        
Selecting previously unselected package libayatana-ido3-0.4-0:amd64.
(Reading database ... 26454 files and directories currently installed.)
Preparing to unpack .../0-libayatana-ido3-0.4-0_0.9.3-1_amd64.deb ...
Unpacking libayatana-ido3-0.4-0:amd64 (0.9.3-1) ...
Selecting previously unselected package libayatana-indicator3-7:amd64.
Preparing to unpack .../1-libayatana-indicator3-7_0.9.3-1_amd64.deb ...
Unpacking libayatana-indicator3-7:amd64 (0.9.3-1) ...
Selecting previously unselected package libdbusmenu-glib4:amd64.
Preparing to unpack .../2-libdbusmenu-glib4_18.10.20180917~bzr492+repack1-3_amd64.deb ...
Unpacking libdbusmenu-glib4:amd64 (18.10.20180917~bzr492+repack1-3) ...
Selecting previously unselected package libdbusmenu-gtk3-4:amd64.
Preparing to unpack .../3-libdbusmenu-gtk3-4_18.10.20180917~bzr492+repack1-3_amd64.deb ...
Unpacking libdbusmenu-gtk3-4:amd64 (18.10.20180917~bzr492+repack1-3) ...
Selecting previously unselected package libayatana-appindicator3-1.
Preparing to unpack .../4-libayatana-appindicator3-1_0.5.92-1_amd64.deb ...
Unpacking libayatana-appindicator3-1 (0.5.92-1) ...
Selecting previously unselected package mullvad-vpn.
Preparing to unpack .../5-MullvadVPN-2023.5_amd64.deb ...
Unpacking mullvad-vpn (2023.5) ...
Setting up libdbusmenu-glib4:amd64 (18.10.20180917~bzr492+repack1-3) ...
Setting up libayatana-ido3-0.4-0:amd64 (0.9.3-1) ...
Setting up mullvad-vpn (2023.5) ...
Created symlink /etc/systemd/system/multi-user.target.wants/mullvad-daemon.service → /usr/lib/systemd/system/mullvad-daemon.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package mullvad-vpn (--configure):
 installed mullvad-vpn package post-installation script subprocess returned error exit status 1
Setting up libayatana-indicator3-7:amd64 (0.9.3-1) ...
Setting up libdbusmenu-gtk3-4:amd64 (18.10.20180917~bzr492+repack1-3) ...
Setting up libayatana-appindicator3-1 (0.5.92-1) ...
Processing triggers for libc-bin (2.36-9+deb12u3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 mullvad-vpn
N: Download is performed unsandboxed as root as file '/var/home/pavin/Downloads/MullvadVPN-2023.5_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ sudo apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up mullvad-vpn (2023.5) ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package mullvad-vpn (--configure):
 installed mullvad-vpn package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 mullvad-vpn
E: Sub-process /usr/bin/dpkg returned an error code (1)
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ 
pavin@deb:~/Downloads$ sudo apt install htop
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libnl-3-200 libnl-genl-3-200
Suggested packages:
  lm-sensors strace
The following NEW packages will be installed:
  htop libnl-3-200 libnl-genl-3-200
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 237 kB of archives.
After this operation, 633 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://deb.debian.org/debian bookworm/main amd64 libnl-3-200 amd64 3.7.0-0.2+b1 [63.1 kB]
Get:2 http://deb.debian.org/debian bookworm/main amd64 libnl-genl-3-200 amd64 3.7.0-0.2+b1 [21.6 kB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 htop amd64 3.2.2-2 [152 kB]
Fetched 237 kB in 1s (359 kB/s)
Selecting previously unselected package libnl-3-200:amd64.
(Reading database ... 26596 files and directories currently installed.)
Preparing to unpack .../libnl-3-200_3.7.0-0.2+b1_amd64.deb ...
Unpacking libnl-3-200:amd64 (3.7.0-0.2+b1) ...
Selecting previously unselected package libnl-genl-3-200:amd64.
Preparing to unpack .../libnl-genl-3-200_3.7.0-0.2+b1_amd64.deb ...
Unpacking libnl-genl-3-200:amd64 (3.7.0-0.2+b1) ...
Selecting previously unselected package htop.
Preparing to unpack .../htop_3.2.2-2_amd64.deb ...
Unpacking htop (3.2.2-2) ...
Setting up mullvad-vpn (2023.5) ...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package mullvad-vpn (--configure):
 installed mullvad-vpn package post-installation script subprocess returned error exit status 1
Setting up libnl-3-200:amd64 (3.7.0-0.2+b1) ...
Setting up libnl-genl-3-200:amd64 (3.7.0-0.2+b1) ...
Setting up htop (3.2.2-2) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.36-9+deb12u3) ...
Errors were encountered while processing:
 mullvad-vpn
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

With the proposed PR, the installation would not fail on apt based systems and continue to be a problem.
There are no other side effects to normal systems with systemd.

**Comment by faern** [comment]
A potential danger is the failing silently aspect of this. On a systemd distro the system service can fail to start and the install/upgrade would proceed without an error. Given how we block firewall rules during upgrades etc this could leave the user without any internet or similar bad states without much to help them. On the other hand, the current errors for this are pretty bad for debugging also.

**Comment by pavinjosdev** [comment]
I agree, failing silently would be bad but currently it would produce *at least* the following error for the user when not being able to start the `mullvad-daemon` service: `Failed to start mullvad-daemon.service`

Of course I can improve the error message to be an ASCII banner or something if you prefer. Something like this:

```
██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗         ███████╗ █████╗ ██╗██╗     ███████╗██████╗ 
██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║         ██╔════╝██╔══██╗██║██║     ██╔════╝██╔══██╗
██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║         █████╗  ███████║██║██║     █████╗  ██║  ██║
██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║         ██╔══╝  ██╔══██║██║██║     ██╔══╝  ██║  ██║
██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗    ██║     ██║  ██║██║███████╗███████╗██████╔╝
╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═════╝ 
                                                                                                     
```

**Comment by faern** [comment]
I don't think the size of the error message makes much difference. We have decided to go ahead and merge this if it works. I'm testing it right now.

**Comment by faern** [comment]
Thank you for the contribution. Hoping it will help you and similar setups :blush:

**Pull request merged**
