### PR TITLE
Perform a clippy --fix

### PR DESCRIPTION
**Pull request by Jontified**
This is a giant commit which performs only a clippy --fix.

Auditing can happen in two ways, either by reading every line or by
running a `cargo clippy --fix` on the previous commit and make sure that
the result is the same.

This initial PR only commits the auto-fixed changes since we would like to get those out of the way first.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
None of the changes affect behavior, so they look good to me, but I left a few comments.

> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-:-N4CR5p585Tt1vptE0My:bi7yvg)* status: all files reviewed, 4 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-api/src/rest.rs` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-N4CK7gE7XVyAUwMw-gk:-N4CK7gE7XVyAUwMw-gl:b359cd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2db1289ddeb83bc2031663af6202525e2ec5eb5a/mullvad-api/src/rest.rs#L155)):*
> ```XML
> 
>         if let Some(config) = proxy_config_provider.next().await {
>             connector_handle.set_connection_mode(config)
> ```

This should end with a semi-colon, IMO.
___
*[`mullvad-cli/src/state.rs` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-N4CKaq62x35yHE97rK6:-N4CKaq62x35yHE97rK7:b-1qsde9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2db1289ddeb83bc2031663af6202525e2ec5eb5a/mullvad-cli/src/state.rs#L29)):*
> ```XML
>                     };
> 
>                     if (sender.send(forward).await).is_err() {
> ```

I could be wrong, but I don't think the parenthesis around `sender.send(forward).await` is needed.
___
*[`mullvad-types/src/location.rs` line 201 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-N4CPckt1GV37YC-9Iu9:-N4CPckt1GV37YC-9IuA:bp2ujn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2db1289ddeb83bc2031663af6202525e2ec5eb5a/mullvad-types/src/location.rs#L201)):*
> ```XML
>         assert_eq!(
>             haversine_dist_deg(36.12, -86.67, 33.94, -118.4),
>             2_887.259_950_607_111
> ```

A digit was lost here.
___
*[`mullvad-types/src/relay_constraints.rs` line 216 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-N4CQYCM5Zo_3FsaRU0L:-N4CQYCM5Zo_3FsaRU0M:ba5tjjz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2db1289ddeb83bc2031663af6202525e2ec5eb5a/mullvad-types/src/relay_constraints.rs#L216)):*
> ```XML
>             location: update.location.unwrap_or_else(|| self.location.clone()),
>             providers: update.providers.unwrap_or_else(|| self.providers.clone()),
>             ownership: update.ownership.unwrap_or_else(|| self.ownership.clone()),
> ```

It would make sense to implement `Copy` on `Ownership` as well, given that it's just an enum.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 11 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647)* status: all files reviewed, 4 unresolved discussions (waiting on @Jontified)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`mullvad-cli/src/state.rs` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-N4CKaq62x35yHE97rK6:-N4Cms7d2iJjckd8MTmc:byc1771) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2db1289ddeb83bc2031663af6202525e2ec5eb5a/mullvad-cli/src/state.rs#L29)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I could be wrong, but I don't think the parenthesis around `sender.send(forward).await` is needed.
</blockquote></details>

It isn't.

**Comment by Jontified** [comment]
> 
> _[`mullvad-types/src/location.rs` line 201 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647#-N4CPckt1GV37YC-9Iu9:-N4CPckt1GV37YC-9IuA:bp2ujn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2db1289ddeb83bc2031663af6202525e2ec5eb5a/mullvad-types/src/location.rs#L201)):_
> 
> > ```
> >         assert_eq!(
> >             haversine_dist_deg(36.12, -86.67, 33.94, -118.4),
> >             2_887.259_950_607_111
> > ```
> 
> A digit was lost here.
> 

Clippy [thinks](https://rust-lang.github.io/rust-clippy/master/index.html#excessive_precision) this is too high precision. Is there any point in keeping this even if this is true?

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3647)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
