### PR TITLE
Windows: Override and enforce DNS settings

### PR DESCRIPTION
**Pull request by mvd-ows**
This is work in progress.

However, it would be great to get some feedback on the overall structure of the code, and the approach used.

Some of the things that need to be fixed:
* All the TODOs
* Pass errorSink to monitoring thread
* Move generic WMI code into libcommon
* Serialize settings to be restored and send to `windns` client
** This will be done continuously from the monitoring thread
* Implement shelling out to `netsh` for updating settings on adapters that are offline
* Extend `Reset` function to accept serialized settings to be restored

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 4 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 6 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 7 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 13 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 15 of 46 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 21 of 46 files reviewed at latest revision, all discussions resolved.

---

*[windows/windns/src/windns/itracesink.h, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDban41-kelKQQ4zVB3:-LDban41-kelKQQ4zVB4:bt2xbcb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/itracesink.h#L7)):*
> ```objc
> struct ITraceSink
> {
> 	virtual ~ITraceSink() = 0
> ```

Is it a pure virtual function or it has a default body? Is it possible to have both at the same time?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 26 of 46 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 26 of 46 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/windns/src/windns/netconfighelpers.cpp, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbbcuF077FKC_f8k7H:-LDbbcuF077FKC_f8k7I:b-6gh7dh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/netconfighelpers.cpp#L46)):*
> ```cpp
> 	}
> 
> 	auto status = methodCall.invoke(connection, instance, L"SetDNSServerSearchOrder");
> ```

Is it possible that this call fails? If so, would be great to throw an error or something.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 27 of 46 files reviewed at latest revision, 2 unresolved discussions.

---

*[windows/windns/src/windns/stdafx.cpp, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbbpqR5Wqqyn6iwqzC:-LDbbpqR5Wqqyn6iwqzD:b-1binpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/stdafx.cpp#L1)):*
> ```cpp
> ��// stdafx.cpp : source file that includes just the standard includes
> ```

is it UTF-8 BOM? :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 29 of 46 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 30 of 46 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 34 of 46 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 35 of 46 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 36 of 46 files reviewed at latest revision, 3 unresolved discussions.

---

*[windows/windns/src/windns/wmi/resultset.cpp, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbceZt-WmB4FUYBoCF:-LDbceZt-WmB4FUYBoCG:b-ux03w9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/resultset.cpp#L17)):*
> ```cpp
> 	if (nullptr != m_result)
> 	{
> 		m_result.Release();
> ```

Do you have to do the same in destructor `~ResultSet()`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 37 of 46 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 38 of 46 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 39 of 46 files reviewed at latest revision, 4 unresolved discussions.

---

*[windows/windns/src/windns/wmi/methodcall.cpp, line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbeKoN3m7p33ZOhAAb:-LDbeKoN3m7p33ZOhAAc:bdlsmb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/methodcall.cpp#L56)):*
> ```cpp
> 
> //
> // the following code is almost what is needed for static method calls
> ```

Is this something we may need in future?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 40 of 46 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 41 of 46 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
This code seriously lacks some comments to tell which classes do what. It's not easy to understand the relationships between classes since I am not very familiar with WMI objects and how to interact with it from C++.

---

Review status: 41 of 46 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-:-LDbedd04owSsmu4rVkR:bwkb0ve)*

**Comment by pronebird** [comment]
Review status: 42 of 46 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 43 of 46 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 44 of 46 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 44 of 46 files reviewed at latest revision, 5 unresolved discussions.

---

*[windows/windns/src/windns/wmi/notification.cpp, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbf8Cj8e6G2BBYgsID:-LDbf8Cj8e6G2BBYgsIE:b-3gfgd1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/notification.cpp#L66)):*
> ```cpp
> 	// Using a Sleep() here is preferable to introducing a critical section in the callback.
> 	//
> 	while (m_eventSink->processing())
> ```

Probably this can be moved to `EventSink` implementation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by mvd-ows** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[windows/windns/src/windns/itracesink.h, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDban41-kelKQQ4zVB3:-LDehU3KClFNSooHnu7c:bgwilfi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/itracesink.h#L7)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Is it a pure virtual function or it has a default body? Is it possible to have both at the same time?
</blockquote></details>

The dtor is a special case in C++: Even when defined as pure virtual it must have an implementation.

---

*[windows/windns/src/windns/netconfighelpers.cpp, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbbcuF077FKC_f8k7H:-LDeiB4Z3wc11qj2pm8-:b-j9hu1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/netconfighelpers.cpp#L46)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Is it possible that this call fails? If so, would be great to throw an error or something.
</blockquote></details>

Certainly, see the next line :-D

This is actually a critical part of the code and must be handled appropriately, with a throw. Will fix.

---

*[windows/windns/src/windns/stdafx.cpp, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbbpqR5Wqqyn6iwqzC:-LDeiRuv1_Jfp5dOVMSS:b-oyaty9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/stdafx.cpp#L1)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

is it UTF-8 BOM? :)
</blockquote></details>

Probably, VS is weird. You can't set the default encoding and it decides which encoding to use whenever you save a file. So it adds a BOM randomly :-(

I will look into fixing this file.

---

*[windows/windns/src/windns/wmi/methodcall.cpp, line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbeKoN3m7p33ZOhAAb:-LDeihQT4sxQoyB0wXfN:b-3nu22p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/methodcall.cpp#L56)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Is this something we may need in future?
</blockquote></details>

Possibly. I'd like to clean it up and include it even though we're not currently using it. Unless it turns out to be too much work.

---

*[windows/windns/src/windns/wmi/notification.cpp, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbf8Cj8e6G2BBYgsID:-LDekpWCEB77i1UZZQti:bu9yqmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/notification.cpp#L66)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Probably this can be moved to `EventSink` implementation?
</blockquote></details>

Makes sense. I kept moving the code back and forth when first writing this. I will add another method to `EventSink` that can contain the `Sleep`.

---

*[windows/windns/src/windns/wmi/resultset.cpp, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbceZt-WmB4FUYBoCF:-LDfD-VWDtvSALKuIo45:b-b8zvbg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/resultset.cpp#L17)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Do you have to do the same in destructor `~ResultSet()`?
</blockquote></details>

Funnily enough, no. It's an automatic pointer so will be released once destructed. The reason I have to release it here is because the `Next` method will fail otherwise. I think `&m_result` may behave differently depending on whether the pointer has a valid instance. This is how others do it as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[windows/windns/src/windns/itracesink.h, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDban41-kelKQQ4zVB3:-LDfSW_l1NzuO2MgIsQl:bavu2lx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/itracesink.h#L7)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The dtor is a special case in C++: Even when defined as pure virtual it must have an implementation.
</blockquote></details>

Right, I just thought that 

```
virtual ~ITraceSink() {}
```

would be enough.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[windows/windns/src/windns/stdafx.cpp, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbbpqR5Wqqyn6iwqzC:-LDfSmZ-2Hl0UHRUGn0K:bygewoq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/stdafx.cpp#L1)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Probably, VS is weird. You can't set the default encoding and it decides which encoding to use whenever you save a file. So it adds a BOM randomly :-(

I will look into fixing this file.
</blockquote></details>

Cool, thanks. This doesn't block the the VS from compiling the code but it looks weird everywhere since UTF-8 BOM does not seem to be very well handled elsewhere. :) So Reviewable shows some chinese character first :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[windows/windns/src/windns/wmi/resultset.cpp, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbceZt-WmB4FUYBoCF:-LDfTJ-p4cpdsrF-Gkih:bpmbh6f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/resultset.cpp#L17)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Funnily enough, no. It's an automatic pointer so will be released once destructed. The reason I have to release it here is because the `Next` method will fail otherwise. I think `&m_result` may behave differently depending on whether the pointer has a valid instance. This is how others do it as well.
</blockquote></details>

Ah I think they may be reusing the same pointer, but then they can't `Reset` the contained value until it is `Release`d.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by mvd-ows** [comment]
*[windows/windns/src/windns/itracesink.h, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDban41-kelKQQ4zVB3:-LDfjoOsEXBo42lAyaX0:b-3khnh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/itracesink.h#L7)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Right, I just thought that 

```
virtual ~ITraceSink() {}
```

would be enough.
</blockquote></details>

It needs to be pure virtual to ensure the struct is abstract. Otherwise someone could instantiate this type, which doesn't make sense, because it's supposed to be used as an interface only.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by mvd-ows** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[windows/windns/src/windns/wmi/notification.cpp, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbf8Cj8e6G2BBYgsID:-LDghfHz1fGsz__adEzW:bxwc4xu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/notification.cpp#L66)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Makes sense. I kept moving the code back and forth when first writing this. I will add another method to `EventSink` that can contain the `Sleep`.
</blockquote></details>

I just realized why the `Sleep` was not placed inside `EventSink`. It's because the `EventSink` class has no way of knowing when the query it is linked to has been unregistered, and therefore cannot authoritatively answer whether all processing is completed. It only has the knowledge to answer whether or not it's currently processing an event.

I can either leave the code as is, or move the cancelling and waiting into a utility function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by mvd-ows** [comment]
*[windows/windns/src/windns/stdafx.cpp, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbbpqR5Wqqyn6iwqzC:-LDgiy2y1Hkbor3xU07V:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/stdafx.cpp#L1)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Cool, thanks. This doesn't block the the VS from compiling the code but it looks weird everywhere since UTF-8 BOM does not seem to be very well handled elsewhere. :) So Reviewable shows some chinese character first :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 33 of 46 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[windows/windns/src/windns/itracesink.h, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDban41-kelKQQ4zVB3:-LDkRgjB6xsdaWZEB-sZ:b-zdna4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/itracesink.h#L7)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

It needs to be pure virtual to ensure the struct is abstract. Otherwise someone could instantiate this type, which doesn't make sense, because it's supposed to be used as an interface only.
</blockquote></details>

Right, that's what I read but wasn't sure that's the case. Thanks for explaining.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 34 of 46 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[windows/windns/src/windns/wmi/notification.cpp, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbf8Cj8e6G2BBYgsID:-LDkS-vW87hQVdjsWqQo:b-11w1wk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/notification.cpp#L66)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I just realized why the `Sleep` was not placed inside `EventSink`. It's because the `EventSink` class has no way of knowing when the query it is linked to has been unregistered, and therefore cannot authoritatively answer whether all processing is completed. It only has the knowledge to answer whether or not it's currently processing an event.

I can either leave the code as is, or move the cancelling and waiting into a utility function.
</blockquote></details>

If it's the only such occurrence then maybe leaving it is fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: 42 of 46 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by faern** [comment]
From my understanding the plan is to shell out to `netsh` since it can handle any adapter, online or offline. My interpretation of the comments above is that the plan is to still use WMI to set the DNS for online adapters?

If the above is true, then I wonder if the WMI approach has a noticeable benefit over using `netsh`. I mean, shelling out is a kind of ugly hack. But since we know we will have to do it anyway in some cases, can't we do only that to modify DNS? To not have to maintain two separate solutions with a fallback from one to the other.

I guess some part of the WMI is still needed to continuously monitor all adapters for a change in DNS though, so we can instantly set it back to our IP? And to get a list of all the adapters we need to configure DNS for?

---

Review status: 26 of 48 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-:-LDul9Rh1AaX8uADA5CI:b-af65ap)*

**Comment by pronebird** [comment]
Review status: 18 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/windns/src/windns/wmi/methodcall.cpp, line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbeKoN3m7p33ZOhAAb:-LEUDXSbCOvjkp8i82hI:b6icvt0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/methodcall.cpp#L56)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Possibly. I'd like to clean it up and include it even though we're not currently using it. Unless it turns out to be too much work.
</blockquote></details>

Seems like this file was removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 1 of 35 files at r4.
Review status: 19 of 37 files reviewed at latest revision, all discussions resolved.

---

*[windows/windns/src/extras/loader/loader.cpp, line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LEUE_ppDMyDMKQVmPAM:-LEUE_ppDMyDMKQVmPAN:b-5lfw0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ccd700a73934dcefc8ad2cb9db189914b5b70f5/windows/windns/src/extras/loader/loader.cpp#L17)):*
> ```cpp
> 	std::wcout << L"Updated config was delivered to WINDNS client code" << std::endl;
> 
> 	auto f = CreateFileW(L"windns_recovery", GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, 0, nullptr);
> ```

Not sure if this runs as a separate CLI, but if not, the recovery info can either be stored in memory. If it really has to be stored in a file, then we should store in a reasonable location.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pinkisemils** [comment]
Reviewed 6 of 47 files at r1, 10 of 13 files at r2, 2 of 25 files at r3, 19 of 35 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/windns/src/windns/wmi/methodcall.cpp, line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbeKoN3m7p33ZOhAAb:-LEUFToNCjQT9oB4vyMa:b-dhmfc2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/methodcall.cpp#L56)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Seems like this file was removed.
</blockquote></details>

It was moved to `libcommon`. https://github.com/mullvad/windows-libraries/pull/1

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 2 of 35 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/windns/src/extras/loader/loader.cpp, line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LEUE_ppDMyDMKQVmPAM:-LEUFi1p4U_5CIYpnF23:b4vrsde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ccd700a73934dcefc8ad2cb9db189914b5b70f5/windows/windns/src/extras/loader/loader.cpp#L17)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Not sure if this runs as a separate CLI, but if not, the recovery info can either be stored in memory. If it really has to be stored in a file, then we should store in a reasonable location.
</blockquote></details>

The rust FFI code exposes a callback that would take care of saving the file. I'm not entirely certain what is going on here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 1 of 35 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 1 of 35 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 2 of 35 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by mvd-ows** [comment]
Review status: 25 of 37 files reviewed, 1 unresolved discussion (waiting on @pronebird and @pinkisemils)

---

*[windows/windns/src/extras/loader/loader.cpp, line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LEUE_ppDMyDMKQVmPAM:-LEmn94H6-AXVkvc_MGY:b-gto23s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ccd700a73934dcefc8ad2cb9db189914b5b70f5/windows/windns/src/extras/loader/loader.cpp#L17)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The rust FFI code exposes a callback that would take care of saving the file. I'm not entirely certain what is going on here.
</blockquote></details>

This CLI is only used for manual testing. So it doesn't matter much.

---

*[windows/windns/src/windns/wmi/methodcall.cpp, line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbeKoN3m7p33ZOhAAb:-LEmnZSoBXz1V70nLCJJ:b-4m2vyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/methodcall.cpp#L56)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It was moved to `libcommon`. https://github.com/mullvad/windows-libraries/pull/1
</blockquote></details>

Well there was a piece at the end that could be cleaned up and used for calling static WMI methods. But I did not feel it was worth the effort since we currently don't need that functionality. So the file was moved and the extra code at the end was removed.

---

*[windows/windns/src/windns/wmi/notification.cpp, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190#-LDbf8Cj8e6G2BBYgsID:-LEmnsaSDRPc0skMKmeD:bd2ij93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/080aebcc455f53a5b758211b900c587083b0141f/windows/windns/src/windns/wmi/notification.cpp#L66)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

If it's the only such occurrence then maybe leaving it is fine.
</blockquote></details>

Yep, I left it like it was.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pinkisemils** [comment]
Reviewed 14 of 19 files at r5.
Review status: 15 of 33 files reviewed, 1 unresolved discussion (waiting on @pronebird and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 1 of 19 files at r5.
Review status: 29 of 33 files reviewed, all discussions resolved (waiting on @pinkisemils and @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pronebird** [comment]
Reviewed 1 of 19 files at r5.
Review status: 30 of 33 files reviewed, all discussions resolved (waiting on @pinkisemils and @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 3 files at r6.
Review status: 32 of 33 files reviewed, all discussions resolved (waiting on @pinkisemils and @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 3 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/190)*

**Pull request merged**
