### PR TITLE
Add feature indicators to changelog

### PR DESCRIPTION
**Pull request by raksooo**
I forgot to add a changelog entry for the main view redesign and feature indicators. This PR adds that to the changelog.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6726)

### CODE REVIEW

**Review by Serock3 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6726)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Serock3** [comment]
After approving I was a potential error, "Add feature indicators in the main view" should be " Add feature indicators to the main view".

**Review by raksooo — COMMENTED** [review]
Nice! Done :+1:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6726#-:-O5xWIOBD9wQBgaBt6S1:bg5s6s7)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Serock3)

**Review by Serock3 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6726)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
