### PR TITLE
Prevent duplicate navigate up

### PR DESCRIPTION
**Pull request by Rawa**
Makes use of newly added dropUnlessResumed to prevent user from clicking navigate up while we already are navigating up.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @Rawa)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-GRA6sAlRVsNzffrWQ:-O-GRA6sAlRVsNzffrWR:b-f41rog) (no related file):*
Is there any way we can ensure we don't miss adding `dropUnlessResumed`?

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/WireguardCustomPortDialog.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-GR0tbE3_V0oCsMK6j:-O-GR0tbE3_V0oCsMK6k:b-5lnsrb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca19e63ccc993eccf28c215411ab333f148a71e2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/WireguardCustomPortDialog.kt#L19)):*
> ```Kotlin
> import androidx.compose.ui.res.stringResource
> import androidx.compose.ui.tooling.preview.Preview
> import androidx.lifecycle.compose.dropUnlessResumed
> ```

Used in this class? Maybe reviewable acting up



_Code quote:_
```Kotlin
dropUnlessResumed
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 156 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-GQtfB5Eaiouefe0dp:-O-GQtfB5Eaiouefe0dq:b-kh67x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca19e63ccc993eccf28c215411ab333f148a71e2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L156)):*
> ```Kotlin
>     LaunchedEffectCollect(vm.uiSideEffect) {
>         when (it) {
>             SelectLocationSideEffect.CloseScreen -> navigateBack()
> ```

Why was this specific call broken broken out? :thinking: 



_Code quote:_
```Kotlin
navigateBack()
```

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 35 of 35 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: all files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListsScreen.kt` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-Gf3NuCDT6OCrZwsT3:-O-Gf3NuCDT6OCrZwsT4:b-9hf5ns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aec7d8c50615d686f014dde689ca44542005399c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListsScreen.kt#L105)):*
> ```Kotlin
>             navigator.navigate(
>                 EditCustomListDestination(customListId = customList.id),
>                 onlyIfResumed = true
> ```

This uses both `launchSingleTop` and `onlyIfResumed` which in this case mostly do the same?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt` line 68 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-GfNDtAq1ogpnGvFod:-O-GfNDtAq1ogpnGvFoe:bp93s00) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aec7d8c50615d686f014dde689ca44542005399c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt#L68)):*
> ```Kotlin
>         state = state,
>         onSettingsClicked =
>             dropUnlessResumed {
> ```

Same as above, both `dropUnlessResumed` and `launchSingleTop`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 39 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-Gr_qe1q3R-r_dWDvB:-O-Gr_qe1q3R-r_dWDvC:b-lhcitw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aec7d8c50615d686f014dde689ca44542005399c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L39)):*
> ```Kotlin
> import com.ramcosta.composedestinations.result.ResultRecipient
> import kotlinx.coroutines.launch
> import mullvad_daemon.management_interface.portRange
> ```

This should probably not be here?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: 9 of 44 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListsScreen.kt` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-Gf3NuCDT6OCrZwsT3:-O-KJZhU7BHkZU1kvpr-:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aec7d8c50615d686f014dde689ca44542005399c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListsScreen.kt#L105)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This uses both `launchSingleTop` and `onlyIfResumed` which in this case mostly do the same?
</blockquote></details>

Fixed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt` line 68 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-GfNDtAq1ogpnGvFod:-O-KJjTMAUPPQWyx54EN:bzij3nc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aec7d8c50615d686f014dde689ca44542005399c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt#L68)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Same as above, both `dropUnlessResumed` and `launchSingleTop`
</blockquote></details>

Thanks, fixed :+1: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 39 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-Gr_qe1q3R-r_dWDvB:-O-KK70M5HLow6ujvHBX:b-3efd2l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aec7d8c50615d686f014dde689ca44542005399c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L39)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should probably not be here?
</blockquote></details>

Correct, mistake, fixed.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 35 of 35 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-:-O-Kbh-r107uHlaUOP7N:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 35 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-GRA6sAlRVsNzffrWQ:-O-KuPnw6jHhP8ubcBhn:b-d36tsq) (no related file):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not straight of that I can think of I'm afraid :( It is also a bit of case by case where we need to apply it.

So things to worth noting in this PR:
- `dropUnlessResumed` needs to be called in a composable context (thus we can't call it from within side-effects. unless we create the lambda outside)
- `dropUnlessResumed` returns a lambda with return type `() -> Unit` does we can apply it do places where we pass an argument.

My approach for applying it:
- We apply it everywhere it makes sense (especially crucial is the navigate up I feel)
- For side effect we expect it do collect in a sane manner (e.g only if Resumed) or make us of `onlyIfResume` argument for `navigate`
- I've removed `launchSingleTop`in a lot of places since it feels a bit duplicated, open for discussion to add this back if we feel like it adds something.
</blockquote></details>

Alright! Let's go with this approach for now :thumbsup:

But I really think that we long term should come up with a plan for making sure this is done correctly, either by using `konsist` or other types of test automation. 

___

**Review by Pururun — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 211 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-_MISlEc000l7nLIe5:-O-_MISlEc000l7nLIe6:b8j9a58) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad908ff042a137d86601282cebc11b1224805251/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L211)):*
> ```Kotlin
>                 onlyIfResumed = true
>             ) {
>                 launchSingleTop = true
> ```

Not needed to have both `onlyIfResumed` and `launchSingleTop`

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347)* status: 43 of 44 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 211 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-O-_MISlEc000l7nLIe5:-O-_Q_-h8198RBDJmFH0:b-gm3kg8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad908ff042a137d86601282cebc11b1224805251/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L211)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Not needed to have both `onlyIfResumed` and `launchSingleTop`
</blockquote></details>

Nice find, fixed!

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6347#-:-O-_R9iJBJRvlBxSRUAC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
