### PR TITLE
Update settings migration workflow

### PR DESCRIPTION
**Pull request by mojganii**
This PR optimizes the testing workflow by reusing the `ios-end-to-end-tests` for generating `xcresult`. it's a great step towards enhancing efficiency and consistency in iOS test reporting.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9hsYtY3BbDppWRyAIV:-O9hsYtY3BbDppWRyAIW:b-7nvq7h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L16)):*
> ```YAML
> env:
>   TEST_DEVICE_UDID: 00008130-0019181022F3803A
>   OLD_APP_COMMIT_HASH: 895b7d98825e678f5d7023d5ea3c9b7beee89280
> ```

This commit doesn't seem to exist anymore 
Do you have a link to a successful run of this flow that runs the tests correctly ?
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9ht4fNDvQbHB1m94lq:-O9ht4fNDvQbHB1m94lr:b-fuyvl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L62)):*
> ```YAML
>       - uninstall_app
>     uses: mullvad/mullvadvpn-app/.github/workflows/ios-end-to-end-tests.yml@main
>     with:
> ```

I think we can remove the `mullvad/mullvadvpn-app` prefix here

**Review by rablador — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9hsYtY3BbDppWRyAIV:-O9iBfAH-iMdp6_N2Lwo:bk1qjex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This commit doesn't seem to exist anymore 
Do you have a link to a successful run of this flow that runs the tests correctly ?
</blockquote></details>

I checked out this commit to address the issue reported at [IOS\-866](https://linear.app/mullvad/issue/IOS-866/fix-settings-migration-tests). Additionally, you can view the successful execution of the flow [here](https://github.com/mullvad/mullvadvpn-app/actions/runs/11386707017).
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9ht4fNDvQbHB1m94lq:-O9iBFFy-1XXcldIM7hD:b-escmux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L62)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think we can remove the `mullvad/mullvadvpn-app` prefix here
</blockquote></details>

we can't indeed. it is part of syntax.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9ht4fNDvQbHB1m94lq:-O9irjeYDb3qTZ1W5JN_:b5l0xec) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L62)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can't indeed. it is part of syntax.
</blockquote></details>

I'm not sure I follow, the previous version had this line
`uses: ./.github/actions/ios-end-to-end-tests`

Are you saying that wasn't working ?

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9ht4fNDvQbHB1m94lq:-O9jITwq6t7BzXC8cKy6:b9rsta6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L62)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure I follow, the previous version had this line
`uses: ./.github/actions/ios-end-to-end-tests`

Are you saying that wasn't working ?
</blockquote></details>

they aren't equal. the  previous one is `./.github/actions/ios-end-to-end-tests` which is using the workflow in the checked out repo but mine is using workflow from main branch which `mullvad/mullvadvpn-app/.github/workflows/ios-end-to-end-tests.yml@main`

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9ht4fNDvQbHB1m94lq:-O9jJE1E45SF-afFB838:b-usrszn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L62)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

they aren't equal. the  previous one is `./.github/actions/ios-end-to-end-tests` which is using the workflow in the checked out repo but mine is using workflow from main branch which `mullvad/mullvadvpn-app/.github/workflows/ios-end-to-end-tests.yml@main`
</blockquote></details>

You can find more info [here](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow).

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-:-O9n1mht9A4T0Gc3v9OG:bnfp4nl)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9hsYtY3BbDppWRyAIV:-O9n-yC1DQ27rz7QsDbt:b-gg7iri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L16)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I checked out this commit to address the issue reported at [IOS\-866](https://linear.app/mullvad/issue/IOS-866/fix-settings-migration-tests). Additionally, you can view the successful execution of the flow [here](https://github.com/mullvad/mullvadvpn-app/actions/runs/11386707017).
</blockquote></details>

My bad, it looks like I didn't have the commit in my git history. 
___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9ht4fNDvQbHB1m94lq:-O9n0CQF9RgQ-dJ6R6Cu:bvpmlgl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6a8ba5f4ea3d23b43708825bc5132a1cbfb1786/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L62)):*
Ah right, reusable workflows
The docs does specify the following 
> -   `./.github/workflows/{filename}` for reusable workflows in the same repository.

Both are in our repo, but I think it's fine to leave it like this. After looking at it again, I think I prefer the explicit version. rather than the implicit one.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9nTasi4YPyQytd8clL:-O9nTasi4YPyQytd8clM:bewty3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/081f9abeb1ed22e15d8e56e2ccbc30b12bf0172a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L13)):*
> ```YAML
>     # At midnight every day.
>     # Notifications for scheduled workflows are sent to the user who last modified the cron
>     # syntax in the workflow file. If you update this you must have notifications for
> ```

As discussed offline, let's reinstate this comment

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests-settings-migration.yml` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9nTasi4YPyQytd8clL:-O9obiYA1eSnw1eN4k5S:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/081f9abeb1ed22e15d8e56e2ccbc30b12bf0172a/.github/workflows/ios-end-to-end-tests-settings-migration.yml#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

As discussed offline, let's reinstate this comment
</blockquote></details>

Done.

**Review by rablador — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by rablador — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 38 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7012#-O9xBP5DDgak8xMZ8jfm:-O9xBP5DDgak8xMZ8jfn:b2u1624) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ec8c9d6c4dc799fb0c6479cdc9dad438bf37129/.github/workflows/ios-end-to-end-tests.yml#L38)):*
> ```YAML
>         shell: bash
> 
>   # Define the set of tests to run based on the event type and input
> ```

What's the reason to delete this and similar comments below?

**Comment by mojganii** [comment]
It has been agreed that due to the high maintenance required for the workflow, it is better to execute it locally rather than in CI.

**Pull request closed without merging**
