### PR TITLE
Add smart routing to daita settings data

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
```
2024-09-30 10:26:45.003185+0200 MullvadVPN[1536:467494] [LoadTunnelConfigurationOperation] Cannot read settings.
Caused by: Key "daitaState" not found at "data.daita". (domain = NSCocoaErrorDomain, code = 4865)
```

If I upgrade from an existing AppStore Build, I cannot connect anymore.
Please make sure to:
- Test upgrading from a public version 
- Add unit tests (ideally automated one but that's up to your discretion) that test this.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O811doT1xGAUWTG3Qai:b3vpkak)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
Ah, my bad, I forgot about migration!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O81N1AHAYXPnmvGdnSt:b-d1ol95)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
Should we either:

1. Keep `state` (rather than renaming to `daitaState`) and add `smartRouting` prop?
2. Deprecate `state` and introduce `daitaState`and `smartRoutingState` (like current code)?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O81Qhe59lJsyySaT6Py:bxdhg9p)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
Ex of second option:

```
@available(*, deprecated, renamed: "daitaState")
public let state: DAITAState = .off

[...]

public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    daitaState = try container.decodeIfPresent(DAITAState.self, forKey: .daitaState)
        ?? container.decodeIfPresent(DAITAState.self, forKey: .state)
        ?? .off

    smartRoutingState = try container.decode(SmartRoutingState.self, forKey: .smartRoutingState)
}
```

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O81RhoPDMk8XzSh7aYk:b-65ukcm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — COMMENTED** [review]
Option 1 is better IMHO, daitaState is redundant since we're already talking about a `DaitaSettings` object.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O8B6PHX2DJCVZAYYjGg:b-8ezlto)* status: 12 of 13 files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
What would the name of the smart routing state? We could call it simply `smartRouting`, but then we'd end up with `state` and `smartRouting` where both are states.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O8BiIhMEISt40qxc1x5:b9i8xjs)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
Ok I see what you mean, then let's go with your original proposition. We rename `state` to `daitaState` and introduce the smart routing var as well.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870#-:-O8BsX1W63ANkHbSecaA:bw6x4mc)* status: 12 of 13 files reviewed, all discussions resolved

**Pull request merged**
