### PR TITLE
Add device name and time left to main view

### PR DESCRIPTION
**Pull request by Rawa**
Adds the device name and time left to the main view.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 57 of 57 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256)* status: 57 of 61 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 293 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-NgSdvizBRAf71v6iq4F:-NgSdvizBRAf71v6iq4G:b-jyle2q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f568abcfce51660038c976faa4e51d49e4f3afa9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L293)):*
> ```Kotlin
>             horizontalArrangement = Arrangement.spacedBy(Dimens.mediumPadding)
>         ) {
>             Text(
> ```

So if the device name is either null or empty this will show as "Device name:". So I wonder if it would be better to just not show device name at all in that case or if that would break?
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/AccountExpiry.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-NgOq59q6FeumqQjeoVU:-NgOq59q6FeumqQjeoVV:b4hrvoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/31970dd843b1e02598dfc25d35e21165c3b17ba2/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/AccountExpiry.kt#L12)):*
> ```Kotlin
>     @Parcelize
>     data class Available(val expiryDateTime: DateTime) : AccountExpiry() {
>         override fun daysLeft(): Int =
> ```

This perhaps could be a more generic extension function for DateTime?

**Review by Pururun — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256)* status: 36 of 63 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 293 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-NgSdvizBRAf71v6iq4F:-NgT0Xkj5uR4JVd1Jn5N:b-wo8uo2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f568abcfce51660038c976faa4e51d49e4f3afa9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L293)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So if the device name is either null or empty this will show as "Device name:". So I wonder if it would be better to just not show device name at all in that case or if that would break?
</blockquote></details>

It would certainly work, I'd like us to use maybe something like "placeholder" in this case:
https://google.github.io/accompanist/placeholder/ . I think shimmer is a pretty easily applied affect to hind that the data is loading.

 But that should then be aligned with the rest of the team and design before we apply something like that.

I've removed "Device name:" until the text have been loaded now, reason for still rendering the `Text` it self it to prevent "Time Left" to take it's place.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/AccountExpiry.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-NgOq59q6FeumqQjeoVU:-NgT3Jcr833ZdZPIlvQ6:bvs1n4n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/31970dd843b1e02598dfc25d35e21165c3b17ba2/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/AccountExpiry.kt#L12)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This perhaps could be a more generic extension function for DateTime?
</blockquote></details>

:+1: Agree. Fixed.

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 26 of 26 files at r4, 19 of 19 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 293 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-NgSdvizBRAf71v6iq4F:-NgXnGNfBqezBw9mUzt3:bppw1cp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f568abcfce51660038c976faa4e51d49e4f3afa9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L293)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It would certainly work, I'd like us to use maybe something like "placeholder" in this case:
https://google.github.io/accompanist/placeholder/ . I think shimmer is a pretty easily applied affect to hind that the data is loading.

 But that should then be aligned with the rest of the team and design before we apply something like that.

I've removed "Device name:" until the text have been loaded now, reason for still rendering the `Text` it self it to prevent "Time Left" to take it's place.
</blockquote></details>

I think it is at least something we should raise since it is something that is happening some times in the current implementation.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-:-NgXxcW96YLS1MfJLfiT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256#-:-NgcDRTb0OwSUxCYMaha:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Pururun — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5256)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
