### PR TITLE
More Tokio and futures migration

### PR DESCRIPTION
**Pull request by dlon**
Some of the changes:
* Use 0.3 futures (i.e., new mpsc types) for the channel between the daemon and management interface.
* Get rid of the `BoxFuture` type.
* Use `async`/`await` syntax in `Daemon` instead of passing a tokio runtime handle around.
* Use `async`/`await` and 0.3 futures in the offline monitor.
* Remove tokio 0.1 runtime and the entire dependency.
* Share tokio runtime between the management interface, `mullvad-rpc`, and `mullvad-daemon`.

Some remaining issues:
* The tunnel state machine still implements the old stream type (i.e., from `futures 0.1`). The tunnel state machine should probably be redesigned to avoid directly calling `poll()` etc., since this requires passing on a context in futures 0.3.
   As a result, `async` functions cannot be `await`ed in the TSM, and there is no shared runtime.
* The route manager on Linux and the OpenVPN tunnel monitor have their own runtimes as a result of the above.
* `mullvad-rpc` is relatively untouched.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 4 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: 4 of 34 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/account_history.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFfcOy8BgtOwNTQiKyS:-MFfcOy8BgtOwNTQiKyT:bzngap) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/account_history.rs#L213)):*
> ```Rust
> 
>         let _ = self.accounts.pop_front();
>         self.save_to_disk()
> ```

Will `save_to_disk` not block whilst waiting on the filesystem? On a bloated SSD, this can take a surprisingly long time.
___
*[mullvad-daemon/src/lib.rs, line 970 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFfdic38H9hit8ODN-0:-MFfdic38H9hit8ODN-1:bqs76i9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/lib.rs#L970)):*
> ```Rust
>     }
> 
>     async fn schedule_reconnect(&mut self, delay: Duration) {
> ```

This doesn't have to be asynchronous.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 8 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: 12 of 34 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 1428 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjUxmMDOnr4W40xyIw:-MFjUxmMDOnr4W40xyIx:bt9tm97) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/lib.rs#L1428)):*
> ```Rust
> 
> 
>         if let Err(e) = self.settings.reset() {
> ```

Technically `settings.reset()` does blocking I/O, but I'm not sure if it matters here.
___
*[mullvad-daemon/src/lib.rs, line 1748 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjV9sDCD691DFAqpA5:-MFjV9sDCD691DFAqpA6:b-sneu2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/lib.rs#L1748)):*
> ```Rust
>     }
> 
>     async fn on_generate_wireguard_key_internal(&mut self) -> Result<KeygenEvent, String> {
> ```

Normally these kinds of fucntions are _inner_, not _internal_.
___
*[mullvad-daemon/src/main.rs, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjVUou8QAH_6lGImGZ:-MFjVUou8QAH_6lGImG_:bvzam5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/main.rs#L28)):*
> ```Rust
> 
>     let mut runtime = tokio::runtime::Builder::new()
>         .threaded_scheduler()
> ```

I suggest we specify a number of threads - otherwise by default tokio will spawn a thread for each core. I don't think there's any benefit to running more than 4 threads.
___
*[mullvad-daemon/src/management_interface.rs, line 1494 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjWi3y-CNvqinv7KwZ:-MFjWi3y-CNvqinv7Kw_:b-i9inmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/management_interface.rs#L1494)):*
> ```Rust
> 
>     /// Consumes the server and waits for it to finish. Returns an error if the server exited
>     /// due to an error.
> ```

These comments have not been valid for a while, it seems.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 22 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[mullvad-jni/src/daemon_interface.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjXROj32bA2lua1UWx:-MFjXROj32bA2lua1UWy:b-la2x3f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-jni/src/daemon_interface.rs#L70)):*
> ```Rust
>         block_on(rx)
>             .map_err(|_| Error::NoResponse)?
>             .map_err(|_| Error::SetTargetState)
> ```

Why are these errors special?
___
*[mullvad-problem-report/src/lib.rs, line 270 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjXzLPAGZvQeE3Nepy:-MFjXzLPAGZvQeE3Nepz:b-7qavcp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-problem-report/src/lib.rs#L270)):*
> ```Rust
> 
>     let runtime = tokio::runtime::Builder::new()
>         .threaded_scheduler()
> ```

This certainly doesn't have to be a threaded scheduler.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjb8YqBeA0626g22pI:-MFjb8YqBeA0626g22pJ:bjqtsmn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/talpid-core/src/tunnel_state_machine/mod.rs#L108)):*
> ```Rust
> 
>     // Hide internal 0.1 futures from the client
>     let (command_adapter_tx, command_adapter_rx) = old_mpsc::unbounded();
> ```

I've been told that spooky action at a distance is inevitable if old and new channels are mixed, if they are not oneshot channels. Have you experienced any weirdness at all?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: 20 of 35 files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/account_history.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFfcOy8BgtOwNTQiKyS:-MG3BRnS1bNv2dij2W99:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/account_history.rs#L213)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Will `save_to_disk` not block whilst waiting on the filesystem? On a bloated SSD, this can take a surprisingly long time.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/lib.rs, line 1748 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjV9sDCD691DFAqpA5:-MG3BWAV8Af1fMKu9JJi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/lib.rs#L1748)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Normally these kinds of fucntions are _inner_, not _internal_.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/main.rs, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjVUou8QAH_6lGImGZ:-MG3BZUW1yjSrMQsqkB9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/main.rs#L28)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I suggest we specify a number of threads - otherwise by default tokio will spawn a thread for each core. I don't think there's any benefit to running more than 4 threads.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/management_interface.rs, line 1494 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjWi3y-CNvqinv7KwZ:-MG3BaxYEfFWqZkI_5l0:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/management_interface.rs#L1494)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

These comments have not been valid for a while, it seems.
</blockquote></details>

Fixed.
___
*[mullvad-jni/src/daemon_interface.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjXROj32bA2lua1UWx:-MG3BfHa2yu_vLpn__Gd:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-jni/src/daemon_interface.rs#L70)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Why are these errors special?
</blockquote></details>

Fixed.
___
*[mullvad-problem-report/src/lib.rs, line 270 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjXzLPAGZvQeE3Nepy:-MG3Bj7S1HbQoQ7eXVx7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-problem-report/src/lib.rs#L270)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This certainly doesn't have to be a threaded scheduler.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjb8YqBeA0626g22pI:-MG3BnIi8do94IaY9jL_:b-2be3pg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/talpid-core/src/tunnel_state_machine/mod.rs#L108)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I've been told that spooky action at a distance is inevitable if old and new channels are mixed, if they are not oneshot channels. Have you experienced any weirdness at all?
</blockquote></details>

I haven't experienced any weirdness so far.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: 20 of 35 files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/account_history.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFfcOy8BgtOwNTQiKyS:-MG3C9IGD_wC7ofD-jAX:bx8a9f7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/account_history.rs#L213)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The reason for not using `tokio::fs` is that there is no Windows-specific `OpenOptions`.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 15 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/account_history.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFfcOy8BgtOwNTQiKyS:-MG50zEk6FdakiD5j5p4:b-bw3768) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/account_history.rs#L213)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The reason for not using `tokio::fs` is that there is no Windows-specific `OpenOptions`.
</blockquote></details>

Technically, would it not be possible to open the file via the standard library, set the async flags and convert it to a tokio `File` via `File::from_std`? Regardless, I think the current solution is fine and can be left as is.
___
*[mullvad-problem-report/src/lib.rs, line 270 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFjXzLPAGZvQeE3Nepy:-MG54758C22UaY_7ppoz:b-h2xfg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-problem-report/src/lib.rs#L270)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I wonder if we scale back the features we use here, the problem report binary might become significantly smaller. But that could be a card in and of itself.
___
*[talpid-core/src/tunnel/openvpn.rs, line 245 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MG55XbQ9halUZ8GKC1m:-MG553Z46_Zllz6kjGMo:bilqy9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2f098239c794fd7120831bf732fa7f6444a94032/talpid-core/src/tunnel/openvpn.rs#L245)):*
> ```Rust
>             .threaded_scheduler()
>             .core_threads(1)
>             .max_threads(1)
> ```

I wonder what'd be the benefit of using a basic scheudler here? Given that the cost would be slightly less clean code.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/account_history.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MFfcOy8BgtOwNTQiKyS:-MG7hRL87agREpkzadG9:b921vx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f067ef0bf454aae011533462872732fbea009f29/mullvad-daemon/src/account_history.rs#L213)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Technically, would it not be possible to open the file via the standard library, set the async flags and convert it to a tokio `File` via `File::from_std`? Regardless, I think the current solution is fine and can be left as is.
</blockquote></details>

That would indeed be cleaner.
___
*[talpid-core/src/tunnel/openvpn.rs, line 245 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029#-MG55XbQ9halUZ8GKC1m:-MG7s3S4-UQa3PkC9omz:b-c419u9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2f098239c794fd7120831bf732fa7f6444a94032/talpid-core/src/tunnel/openvpn.rs#L245)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I wonder what'd be the benefit of using a basic scheudler here? Given that the cost would be slightly less clean code.
</blockquote></details>

None as far as I can tell, as it should not run on the current thread.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2029)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
