### PR TITLE
Add support for building universal macOS app

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds support for cross compiling the app for the M1 macs on x86 macs as well as support for making universal builds.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[README.md, line 301 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL5ny_8HbxvViVDw8L:-MYL5ny_8HbxvViVDw8M:bvfeecc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/README.md#L301)):*
> ```Markdown
> #### macOS
> 
> By default a universal app is build on macOS. To build specifically for x86_64 or ARM64 add
> ```

s/build/built
___
*[gui/tasks/distribution.js, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL3EE4BACTH3Rkaxsa:-MYL3EE594n5C0TrChcy:bv9n8wd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/gui/tasks/distribution.js#L1)):*
> ```JavaScript
> const cp = require('child_process');
> ```

Is `cp` not very strongly associated with copying?
___
*[gui/tasks/distribution.js, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL65r40aC5nFsPdxYH:-MYL65r40aC5nFsPdxYI:b-19sagw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/gui/tasks/distribution.js#L284)):*
> ```JavaScript
> function getMacThirdPartyBinaryPath(relativePath) {
>   if (universal) {
>     return getMacBinaryPath(relativePath);
> ```

Why are the third party binaries under `dist-assets/$arch` when universal but under `dist-assets/binaries/$target_triple` when not universal? Should we not always get the third party binaries from the binaries submodule?
___
*[gui/tasks/distribution.js, line 286 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL59Zl72b61HFkr5FD:-MYL59Zm1n82PURZStbM:bwxusjq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/gui/tasks/distribution.js#L286)):*
> ```JavaScript
>     return getMacBinaryPath(relativePath);
>   } else {
>     const arch = process.arch === 'arm64' || arm64 ? 'aarch64' : 'x86_64';
> ```

Here we compute a local `arch`. But the function above seems to use a global `${arch}`. I find that confusing, but that's maybe just because I'm not that used to this file. Especially since they seem to have different types of values. The other one is one of `x64` or `arm64`.

Also, why do we need to check both the `arm64` variable *and* `process.arch`?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[gui/tasks/distribution.js, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL3EE4BACTH3Rkaxsa:-MYPFmkL2Nb-An37JZSo:b-p07wyv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/gui/tasks/distribution.js#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is `cp` not very strongly associated with copying?
</blockquote></details>

It's commonly used as an abbreviation in JavaScript/TypeScript and is even used in the official documentation. But it turned out to be unused here so I've removed it.
___
*[gui/tasks/distribution.js, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL65r40aC5nFsPdxYH:-MYPHaK_5t6KLRG_wB3t:b-vg3jkg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/gui/tasks/distribution.js#L284)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why are the third party binaries under `dist-assets/$arch` when universal but under `dist-assets/binaries/$target_triple` when not universal? Should we not always get the third party binaries from the binaries submodule?
</blockquote></details>

Described more thoroughly further down. In short it was due to the `${arch}` macro having the values `x64` and `arm64` which didn't match the target-triples.
___
*[gui/tasks/distribution.js, line 286 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYL59Zl72b61HFkr5FD:-MYPGDs5CkF-bjoQputy:be0hoz0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eddfff2e2e2ccf7091d9ea9ec98892d10e643854/gui/tasks/distribution.js#L286)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Here we compute a local `arch`. But the function above seems to use a global `${arch}`. I find that confusing, but that's maybe just because I'm not that used to this file. Especially since they seem to have different types of values. The other one is one of `x64` or `arm64`.

Also, why do we need to check both the `arm64` variable *and* `process.arch`?
</blockquote></details>

This is/was a mess and is indeed confusing. To instruct electron bulider to find the correct binaries for each platform we have to use the file macros which are very limited. The `"${arch}"` macro is either `arm64` or `x64` which doesn't match our target-triples and I therefore had to move all binaries to a directories with those names. When making a non-universal build we can refer to the correct directory without using a file-macro since the arch is the same for everything.

The reason to why we needed both `arm64` and `process.arch` was that `arm64` initially wasn't set when building on the M1 macs.

I've now worked around this by setting an environment variable, containing the target triple, before packaging the binaries for each arch. This is still a bit hacky but a bit cleaner and hopefully much easier to understand.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @faern and @raksooo)

___
*[gui/tasks/distribution.js, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYQAgYp9HpfefRY1_nP:-MYQAgYq096iA9yc1p-Z:b-q7pnmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60103523917e1f6e098ffa305709d263500db67f/gui/tasks/distribution.js#L289)):*
> ```JavaScript
>     return ['arm64'];
>   } else {
>     return undefined;
> ```

When is it undefined? When not building universal on an Intel mac is my interpretation? Can we document this function a bit better to explain this to the user?

Also, the return value seems to be a list (but always a single entry). Can the documentation then also describe why it's a list please.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[gui/tasks/distribution.js, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYQAgYp9HpfefRY1_nP:-MYdAr_U86AYk5N1OEQ0:b-3zcwgc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60103523917e1f6e098ffa305709d263500db67f/gui/tasks/distribution.js#L289)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

When is it undefined? When not building universal on an Intel mac is my interpretation? Can we document this function a bit better to explain this to the user?

Also, the return value seems to be a list (but always a single entry). Can the documentation then also describe why it's a list please.
</blockquote></details>

Done. It works with a string if there's only one value :+1:

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[build.sh, line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYjhGG681Pt4tWReBk_:-MYjhGG681Pt4tWReBka:bj829h7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a70d87df033da319f260849b1c789bc0b25404/build.sh#L172)):*
> ```Shell
> function build() {
>     local current_target=${1:-""}
>     local forTargetString=""
> ```

Inconsistent variable naming style. Please use snake_case.
___
*[build.sh, line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYjehp33q7d0SPVmlqa:-MYjehp4-wnmFRH4QnAu:b-uddvx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a70d87df033da319f260849b1c789bc0b25404/build.sh#L251)):*
> ```Shell
> 
> if [[ "$(uname -s)" == "Darwin" || "$(uname -s)" == "Linux" ]]; then
>     mkdir -p "$SCRIPT_DIR/dist-assets/shell-completions"
> ```

Nitpick. Since we `cd` into the `$SCRIPT_DIR` at the very start of the script I think you can use only relative paths. For some places you need absolute paths maybe, but for running this command it should be fine I think. On the other hand it makes sense to be consistent with the cargo invocation below. Does that one need absolute path?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[build.sh, line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYjhGG681Pt4tWReBk_:-MYnMbJw2xUoeszftPIo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a70d87df033da319f260849b1c789bc0b25404/build.sh#L172)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Inconsistent variable naming style. Please use snake_case.
</blockquote></details>

Done.
___
*[build.sh, line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-MYjehp33q7d0SPVmlqa:-MYnMooH8kadWNrs8waZ:b-x5dmbl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a70d87df033da319f260849b1c789bc0b25404/build.sh#L251)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpick. Since we `cd` into the `$SCRIPT_DIR` at the very start of the script I think you can use only relative paths. For some places you need absolute paths maybe, but for running this command it should be fine I think. On the other hand it makes sense to be consistent with the cargo invocation below. Does that one need absolute path?
</blockquote></details>

Some of the `$SCRIPT_DIR` were here before I started working on this, but everything seems to work as expected without the `$SCRIPT_DIR`.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673#-:-MYngfKG4JuhQpL4ZS9P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
