### PR TITLE
Block Accept Privacy until service is ready

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoHiRcq-c6DmsGLBk5a):*
Please clarify this commit message subject



_Code quote:_
```
block until service is ready
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoHtOb0CxpdF2xJtOQW:-NoHtOb0CxpdF2xJtOQX:b-vtuq7h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a51feec3abb481cad1eda321426b2507a9179adb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L84)):*
> ```Kotlin
>                 PrivacyDisclaimerUiSideEffect.StartService -> {
>                     scope.launch {
>                         (context as MainActivity).startServiceSuspend()
> ```

What do you think about adding some type of timeout behavior here? Basically to show the splash/connecting screen if it takes more than a few seconds to start? :thinking:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoHtOb0CxpdF2xJtOQW:-NoLXZKZ0qpU5zhQ8PGW:b-n2mf33) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a51feec3abb481cad1eda321426b2507a9179adb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L84)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What do you think about adding some type of timeout behavior here? Basically to show the splash/connecting screen if it takes more than a few seconds to start? :thinking:
</blockquote></details>

I can test and see how that would work.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoHiRcq-c6DmsGLBk5a):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please clarify this commit message subject
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoHtOb0CxpdF2xJtOQW:-NoMHCqG59T--6377iEU:b-218bia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a51feec3abb481cad1eda321426b2507a9179adb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt#L84)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I can test and see how that would work.
</blockquote></details>

Seems to work fine.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoMQ3xp3b7eTFu_XdXz:-NoMQ3xp3b7eTFu_XdY-:b-pqvrqg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/935f4569d7b04138671fc4081a75c7a1176664d8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L77)):*
> ```Kotlin
>     }
> 
>     suspend fun startServiceSuspend(timeOutMs: Long = Long.MAX_VALUE) : Boolean {
> ```

nit: should be `timeout` since it's one word. That's also how it's written in the rest of the code base.



_Code quote:_
```Kotlin
timeOut
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoMPqL41OvHcocwQwXs:-NoMPqL41OvHcocwQwXt:bpd31iv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/935f4569d7b04138671fc4081a75c7a1176664d8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L80)):*
> ```Kotlin
>         return try {
>             checkForNotificationPermission()
>             withTimeout(timeOutMs) {
> ```

I believe it's easier to follow the code if we let the caller wrap the `startServiceSuspend` call with `withTimeout`



_Code quote:_
```Kotlin
withTimeout(timeOutMs) {
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoMQ3xp3b7eTFu_XdXz:-NoMelEfCWyvtcuMnoG9:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/935f4569d7b04138671fc4081a75c7a1176664d8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L77)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: should be `timeout` since it's one word. That's also how it's written in the rest of the code base.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672#-NoMPqL41OvHcocwQwXs:-NoMeoz682Y4zl1lzCxR:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/935f4569d7b04138671fc4081a75c7a1176664d8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L80)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it's easier to follow the code if we let the caller wrap the `startServiceSuspend` call with `withTimeout`
</blockquote></details>

Done

**Pull request merged**
