### PR TITLE
Add custom port option for WireGuard

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds the ability to add custom options to the `Selector` component and uses it for the WireGuard port selector.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)

### CODE REVIEW

**Review by hankolsen — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/cell/Selector.tsx` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950#-NCdrst_0yByguegyb-F:-NCdrstaAj0I1P47E2kh:b-rkalyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/057d516264093fc873eef2ab29ed9990ae455e3f/gui/src/renderer/components/cell/Selector.tsx#L175)):*
> ```XML
> 
> const StyledCustomContainer = styled(Cell.Container)((props: StyledCustomContainerProps) => ({
>   minHeight: '44px',
> ```

Maybe out-of-scope for this PR, but there are a lot of '44px' floating around in the code, could this be improved with a variable somewhere?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: all files reviewed, 1 unresolved discussion (waiting on @hankolsen)

___
*[`gui/src/renderer/components/cell/Selector.tsx` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950#-NCdrst_0yByguegyb-F:-NCy-BjSAD1_lki8yW7K:by3ie49) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/057d516264093fc873eef2ab29ed9990ae455e3f/gui/src/renderer/components/cell/Selector.tsx#L175)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Maybe out-of-scope for this PR, but there are a lot of '44px' floating around in the code, could this be improved with a variable somewhere?
</blockquote></details>

Great idea! I'll start work on this, along with margins and button height in a separate branch.

**Review by hankolsen — APPROVED** [review]
> Reviewed 17 of 17 files at r2, 6 of 6 files at r3, 8 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @hankolsen and @raksooo)

___
*[`gui/src/renderer/components/WireguardSettings.tsx` line 184 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950#-NCyARGc1F3WqbyD0R1F:-NCyARGc1F3WqbyD0R1G:b-2bv88m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb2d6875d59340bd7a40b332ad32baca5a797e3/gui/src/renderer/components/WireguardSettings.tsx#L184)):*
> ```XML
>     <AriaInputGroup>
>       <StyledSelectorContainer>
>         <SelectorWithCustom
> ```

A bit of an odd name..? Custom what?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @hankolsen)

___
*[`gui/src/renderer/components/WireguardSettings.tsx` line 184 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950#-NCyARGc1F3WqbyD0R1F:-NCyAp2GAV0TtGlug__o:b-vco6ln) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb2d6875d59340bd7a40b332ad32baca5a797e3/gui/src/renderer/components/WireguardSettings.tsx#L184)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

A bit of an odd name..? Custom what?
</blockquote></details>

Good point! Do you have any suggestions? The best I can think of is `SelectorWithCustomOption` but it feels like there could be better alternatives.

**Review by hankolsen — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/WireguardSettings.tsx` line 184 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950#-NCyARGc1F3WqbyD0R1F:-NCyBFJNDILJ_7s3Rc4h:b-oitvnu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb2d6875d59340bd7a40b332ad32baca5a797e3/gui/src/renderer/components/WireguardSettings.tsx#L184)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Good point! Do you have any suggestions? The best I can think of is `SelectorWithCustomOption` but it feels like there could be better alternatives.
</blockquote></details>

SelectorWithCustomItem or SelectorWithCustomOption

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @hankolsen)

___
*[`gui/src/renderer/components/WireguardSettings.tsx` line 184 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950#-NCyARGc1F3WqbyD0R1F:-NCyFTMk20OtpXy66F9H:b-df95cm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb2d6875d59340bd7a40b332ad32baca5a797e3/gui/src/renderer/components/WireguardSettings.tsx#L184)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

SelectorWithCustomItem or SelectorWithCustomOption
</blockquote></details>

I've now updated it to `SelectorWithCustomItem`.

**Review by hankolsen — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
