### PR TITLE
Improve accessibility on iOS

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Hide the map from voice over and other accessibility tools
2. Add accessibility label for the "reconnect" button
3. Add accessibility label for the settings cog button in header bar
4. Set appropriate accessibility traits for disabled cells (unavailable relays) in "Select Location" controller
5. Add custom accessibility actions to streamline the operation of collapsing or expanding the tree levels in "Select Location" controller (as described in https://developer.apple.com/videos/play/wwdc2019/250/?time=78)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783)

### CODE REVIEW

**Review by raksooo — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/SelectLocationCell.swift, line 150 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-MbL7BJI4xCWm9UpNU4n:-MbL7BJJ0K9Exi6YhUjF:b-4881wk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5045a0a65446f7192d4da0e0dd9ef1f6671f66b0/ios/MullvadVPN/SelectLocationCell.swift#L150)):*
> ```Swift
>         } else {
>             accessibilityTraits.remove(.notEnabled)
>         }
> ```

Nitpick: The function name doesn't correspond to the contents anymore. Would it be a better idea that move this to a separate method that is called from `isDisabled`'s `didSet` and in `setupCell`, but not in `indentationLevel`'s `didSet`?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/SelectLocationCell.swift, line 150 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-MbL7BJI4xCWm9UpNU4n:-MbLAtL6A3sDCtGalWxV:b-jn6edq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5045a0a65446f7192d4da0e0dd9ef1f6671f66b0/ios/MullvadVPN/SelectLocationCell.swift#L150)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Nitpick: The function name doesn't correspond to the contents anymore. Would it be a better idea that move this to a separate method that is called from `isDisabled`'s `didSet` and in `setupCell`, but not in `indentationLevel`'s `didSet`?
</blockquote></details>

Good idea. What about moving it to `updateDisabled()` (defined just above)?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/SelectLocationCell.swift, line 150 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-MbL7BJI4xCWm9UpNU4n:-MbLCD7z7PlvgxZ5HeXZ:b4yklt0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5045a0a65446f7192d4da0e0dd9ef1f6671f66b0/ios/MullvadVPN/SelectLocationCell.swift#L150)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Good idea. What about moving it to `updateDisabled()` (defined just above)?
</blockquote></details>

Sounds perfect :+1:

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[ios/MullvadVPN/SelectLocationCell.swift, line 150 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-MbL7BJI4xCWm9UpNU4n:-MbLWKuV6m_5tdHd_r2c:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5045a0a65446f7192d4da0e0dd9ef1f6671f66b0/ios/MullvadVPN/SelectLocationCell.swift#L150)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Sounds perfect :+1:
</blockquote></details>

Done.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[ios/MullvadVPN/HeaderBarView.swift, line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-MbLWc8c-nUwNwncCKe7:-MbLWc8c-nUwNwncCKe8:b-d6w7qj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/71c0ba85517a936e39b852b7768d8ad557694060/ios/MullvadVPN/HeaderBarView.swift#L25)):*
> ```Swift
>         titleLabel.font = UIFont.boldSystemFont(ofSize: 24)
>         titleLabel.textColor = UIColor.white.withAlphaComponent(0.8)
>         titleLabel.accessibilityTraits.insert(.header)
> ```

FYI it turned out that adding the `.header` trait is more appropriate on the header label itself. Verified with the standard navigation bar. Works like a charm and VO says "heading"  after announcing the label.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-:-MbLZRxJD0RxusgUTLj5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/HeaderBarView.swift, line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2783#-MbLWc8c-nUwNwncCKe7:-MbLZCi9AA4t1MrOmoK8:b-e4e7xg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/71c0ba85517a936e39b852b7768d8ad557694060/ios/MullvadVPN/HeaderBarView.swift#L25)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI it turned out that adding the `.header` trait is more appropriate on the header label itself. Verified with the standard navigation bar. Works like a charm and VO says "heading"  after announcing the label.
</blockquote></details>

Awesome :+1:

**Pull request merged**
