### PR TITLE
Fix `install.log` reporting wrong Windows version

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
Get Windows version using `talpid-platform-metadata`, which is the way that `mullvad-problem-report` reports the correct build number.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-nsis/src/lib.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787#-Nq3wLQVBvlbef6ubYj6:-Nq3wLQVBvlbef6ubYj7:b27mavh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2407e6680be6c7fd3452e380445c487d4b7ea5b/mullvad-nsis/src/lib.rs#L97)):*
> ```XML
> /// the final null terminator.
> #[no_mangle]
> pub unsafe extern "C" fn get_system_version(buffer: *mut u16, buffer_size: *mut usize) -> Status {
> ```

As suggested offline, we could probably just return `talpid_platform_metadata::version()` and remove the "patch" code from the plugin.
___
*[`mullvad-nsis/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787#-Nq3x5Za9vgPKX79Zdbx:-Nq3x5ZbDEzEn6YHXfgd:bwkd1ft) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2407e6680be6c7fd3452e380445c487d4b7ea5b/mullvad-nsis/src/lib.rs#L111)):*
> ```XML
>         let result: Vec<u16> = build_number.encode_wide().chain(iter::once(0u16)).collect();
> 
>         ptr::copy_nonoverlapping(result.as_ptr(), buffer, result.len());
> ```

`buffer_size` is not being checked and updated. The function should probably use the same contract as `get_system_local_appdata`.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`mullvad-nsis/src/lib.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787#-Nq3wLQVBvlbef6ubYj6:-Nq84LXw55-6gd7EYaqC:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2407e6680be6c7fd3452e380445c487d4b7ea5b/mullvad-nsis/src/lib.rs#L97)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

As suggested offline, we could probably just return `talpid_platform_metadata::version()` and remove the "patch" code from the plugin.
</blockquote></details>

Done
___
*[`mullvad-nsis/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787#-Nq3x5Za9vgPKX79Zdbx:-Nq84MSm-HTrpPu7yjZl:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2407e6680be6c7fd3452e380445c487d4b7ea5b/mullvad-nsis/src/lib.rs#L111)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`buffer_size` is not being checked and updated. The function should probably use the same contract as `get_system_local_appdata`.
</blockquote></details>

Done

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
