### PR TITLE
Implement "smart routing" daita setting

### PR DESCRIPTION
**Pull request by hulthe**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)

### CODE REVIEW

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 0 of 26 files reviewed, 1 unresolved discussion

___
*[`mullvad-cli/src/cmds/tunnel.rs` line 201 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KBVmf1QLX5amFmvDu:-O4KBVmf1QLX5amFmvDv:bo38afi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-cli/src/cmds/tunnel.rs#L201)):*
> ```XML
>             rpc.set_daita_settings(DaitaSettings {
>                 enabled: *daita,
>                 use_anywhere: true, /* TODO */
> ```

What do we think is the best way of fixing this?

Maybe adding a `use-anywhere` mode of some kind to `mullvad tunnel set wireguard --daita`?
Or adding RPC calls that specifically set  `daita.enabled` and `daita.use_anywhere`?
Or something else?

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 8 of 11 files at r1, 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @hulthe)

___
*[`gui/src/renderer/components/WireguardSettings.tsx` line 616 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4FG7DW1KMBWVjDguZe:-O4FG7DW1KMBWVjDguZf:b4putsz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/gui/src/renderer/components/WireguardSettings.tsx#L616)):*
> ```XML
>         <Cell.Container>
>           <AriaLabel>
>             <Cell.InputLabel>The "Just make it work" Button</Cell.InputLabel>
> ```

:ok_hand: 



_Code quote:_
```XML
 <Cell.InputLabel>The "Just make it work" Button</Cell.InputLabel>
```
___
*[`mullvad-relay-selector/src/relay_selector/mod.rs` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4K6Nh41E1yVKLFQvnn:-O4K6Nh41E1yVKLFQvno:bjz0hhb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-relay-selector/src/relay_selector/mod.rs#L126)):*
> ```XML
>     pub daita: bool,
> 
>     pub daita_use_anywhere: bool,
> ```

Nit Please add a small comment similar to the one for the `daita` property :blush:



_Code quote:_
```XML
    pub daita_use_anywhere: bool,
```
___
*[`mullvad-relay-selector/src/relay_selector/mod.rs` line 753 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KCIMlBlopxXn-4nQm:-O4KCIMlBlopxXn-4nQn:b-i7e4tx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-relay-selector/src/relay_selector/mod.rs#L753)):*
> ```XML
>     /// * `Ok(WireguardInner::Multihop)` otherwise
>     fn get_wireguard_auto_multihop_config(
>         // TODO: document or change assumption that `query` is constrained to daita only
> ```

Do we even need to make this assumption in this function? It seems general enough that you can simply remove this TODO note IMHO. Maybe we should abstract this function over the entry relay predicate (i.e. the closure passed to `take_while` below), but even that seems overkill for now.



_Code quote:_
```XML
       // TODO: document or change assumption that `query` is constrained to daita only
```
___
*[`mullvad-relay-selector/src/relay_selector/query.rs` line 244 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KExLXCL3jhs-UNasx:-O4KExLXCL3jhs-UNasy:b-kcwfcv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-relay-selector/src/relay_selector/query.rs#L244)):*
> ```XML
> //        }
> //    }
> //}
> ```

Please remove :smile:



_Code quote:_
```XML
//impl From<WireguardRelayQuery> for AdditionalWireguardConstraints {
//    /// The mapping from [`WireguardRelayQuery`] to [`AdditionalWireguardConstraints`].
//    fn from(value: WireguardRelayQuery) -> Self {
//        AdditionalWireguardConstraints {
//            daita: value
//                .daita
//                .unwrap_or(AdditionalWireguardConstraints::default().daita),
//        }
//    }
//}
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 24 of 26 files reviewed, 5 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-cli/src/cmds/tunnel.rs` line 201 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KBVmf1QLX5amFmvDu:-O4KLi5Q5SR_-lndt_7U:b-3opz1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-cli/src/cmds/tunnel.rs#L201)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

What do we think is the best way of fixing this?

Maybe adding a `use-anywhere` mode of some kind to `mullvad tunnel set wireguard --daita`?
Or adding RPC calls that specifically set  `daita.enabled` and `daita.use_anywhere`?
Or something else?
</blockquote></details>

Either add RPC calls for setting `daita.enabled` and `daita.use_anywhere` separately, or have the existing `set_daita_settings` RPC accept a type which can represent updating these values together or separately. Something like
```rust
enum DaitaSettingsUpdate {
    SetEnabled(bool),
    SetUseAnywhere(bool),
    SetSettings(DaitaSettings),
}
```

The latter seems more sound to me, but it is a bit more noisy. Also, it breaks the current protobuf interface, forcing all clients to be updated. But maybe that's fine :shrug:
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 198 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KL4lu67NqegIUq4gO:-O4KL4lu67NqegIUq4gP:bsijegl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c80f55b7a146d21dab361e12997ddf86266b5c53/mullvad-cli/src/cmds/tunnel.rs#L198)):*
> ```XML
> 
>         #[cfg(daita)]
>         if let Some(daita) = daita {
> ```

Nit: Since all desktop platforms ship DAITA, we should be able to remove the `#[cfg(daita)]` gates :tada:



_Code quote:_
```XML
        #[cfg(daita)]
        if let Some(daita) = daita {
```

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 21 of 26 files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-relay-selector/src/relay_selector/mod.rs` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4K6Nh41E1yVKLFQvnn:-O4LMdax4Ny0ZYtJbqhY:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-relay-selector/src/relay_selector/mod.rs#L126)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Please add a small comment similar to the one for the `daita` property :blush:
</blockquote></details>

Done
___
*[`mullvad-relay-selector/src/relay_selector/mod.rs` line 753 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KCIMlBlopxXn-4nQm:-O4LMfag8IMRKLYfmGX2:b-ukrnzg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-relay-selector/src/relay_selector/mod.rs#L753)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Do we even need to make this assumption in this function? It seems general enough that you can simply remove this TODO note IMHO. Maybe we should abstract this function over the entry relay predicate (i.e. the closure passed to `take_while` below), but even that seems overkill for now.
</blockquote></details>

I had another look, and I agree. I've removed the comment.
___
*[`mullvad-relay-selector/src/relay_selector/query.rs` line 244 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KExLXCL3jhs-UNasx:-O4LN2Gu369mnl2651Hw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-relay-selector/src/relay_selector/query.rs#L244)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Please remove :smile:
</blockquote></details>

Done.

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 25 of 26 files reviewed, 2 unresolved discussions (waiting on @hulthe)

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 15 of 15 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: all files reviewed, 3 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-api/src/relay_list.rs` line 277 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4dueRn4zNM7Wk-lwrH:-O4dueRn4zNM7Wk-lwrI:bjn01yb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f46767e69a9b54584b4331aab5844c37300d961d/mullvad-api/src/relay_list.rs#L277)):*
> ```XML
> fn inclusive_range_from_pair<T>(pair: (T, T)) -> RangeInclusive<T> {
>     RangeInclusive::new(pair.0, pair.1)
> }
> ```

Nit: Could be make `const` :blush:



_Code quote:_
```XML
fn inclusive_range_from_pair<T>(pair: (T, T)) -> RangeInclusive<T> {
    RangeInclusive::new(pair.0, pair.1)
}
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: all files reviewed, 4 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-cli/src/cmds/tunnel.rs` line 48 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4egfa-6VsiQeSYd9an:-O4egfa-6VsiQeSYd9ao:b-v3uc7o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f31112ec47c4184b4c0bab8c11099a654d99dd17/mullvad-cli/src/cmds/tunnel.rs#L48)):*
> ```XML
>         #[cfg(daita)]
>         #[arg(long)]
>         daita_use_anywhere: Option<BooleanOption>,
> ```

We can safely ditch the `#[cfg(daita)]` gates, right? Since we ship DAITA on all platforms with the CLI now :blush:



_Code quote:_
```XML
        /// Configure whether to enable DAITA
        #[cfg(daita)]
        #[arg(long)]
        daita: Option<BooleanOption>,
        /// Configure whether to enable DAITA "use anywhere"
        #[cfg(daita)]
        #[arg(long)]
        daita_use_anywhere: Option<BooleanOption>,
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 4 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 31 of 32 files reviewed, 3 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-api/src/relay_list.rs` line 277 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4dueRn4zNM7Wk-lwrH:-O4fbQoSEYaYzt3QQ_de:bpsr437) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f46767e69a9b54584b4331aab5844c37300d961d/mullvad-api/src/relay_list.rs#L277)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

how did you even find this when reviewing haha
</blockquote></details>

:face_with_peeking_eye: 
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 201 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KBVmf1QLX5amFmvDu:-O4fbEG10KRLhlbYwqeI:bk6xccu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2be4a4661051aa418e9f14a8f25ae2f072b06ca/mullvad-cli/src/cmds/tunnel.rs#L201)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I opted for multiple RPC-calls instead. Didn't want to risk over-engineering anything (and also, adding new proto types is annoying heh). lmk if you disagree with this
</blockquote></details>

I think that's absolutely fine!
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 198 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4KL4lu67NqegIUq4gO:-O4fbA5Y1YzVIhzg4CJK:bnjzbbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c80f55b7a146d21dab361e12997ddf86266b5c53/mullvad-cli/src/cmds/tunnel.rs#L198)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

:+1: :+1:
</blockquote></details>

:tada:
___
*[`mullvad-cli/src/cmds/tunnel.rs` line 48 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4egfa-6VsiQeSYd9an:-O4fb7JL4Iel3KrshwAM:bnjzbbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f31112ec47c4184b4c0bab8c11099a654d99dd17/mullvad-cli/src/cmds/tunnel.rs#L48)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

:tada:
___
*[`mullvad-daemon/src/lib.rs` line 3011 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4ftbRK-C2MH_IZ5MqP:-O4ftbRK-C2MH_IZ5MqQ:bz452sj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/315e9809c790937e16b10d38c7e9134d423f1657/mullvad-daemon/src/lib.rs#L3011)):*
> ```XML
>                     } else {
>                         false
>                     };
> ```

This feels so suboptimal :joy: I get that there is nothing to do about it without a major refactoring, 



_Code quote:_
```XML
                #[cfg(daita)]
                let daita_use_anywhere =
                    if let RelaySettings::Normal(constraints) = settings.relay_settings {
                        // Detect whether we're using "use_anywhere" by checking if multihop is
                        // in use but not explicitly enabled.
                        daita && multihop && !constraints.wireguard_constraints.use_multihop
                    } else {
                        false
                    };
```

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r7, 1 of 2 files at r9, 4 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 30 of 34 files reviewed, 3 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-relay-selector/src/relay_selector/query.rs` line 503 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4naBv62nXRHAB6_bNl:-O4naBv62nXRHAB6_bNm:bk09f7s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea6b55bcd4aa10968588bbea0778457ca543ab4/mullvad-relay-selector/src/relay_selector/query.rs#L503)):*
> ```XML
>             self
>         }
>     }
> ```

:raised_hands:



_Code quote:_
```XML
    // impl-block for after DAITA is set
    impl<Multihop, Obfuscation> RelayQueryBuilder<Wireguard<Multihop, Obfuscation, bool>> {
        /// Enable DAITA use_anywhere.
        pub fn daita_use_anywhere(mut self, constraint: impl Into<Constraint<bool>>) -> Self {
            self.query.wireguard_constraints.daita_use_anywhere = constraint.into();
            self
        }
    }
```
___
*[`mullvad-relay-selector/tests/relay_selector.rs` line 1436 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4ndXJG3jJGjwREFXCy:-O4ndXJG3jJGjwREFXCz:b5l1bg1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea6b55bcd4aa10968588bbea0778457ca543ab4/mullvad-relay-selector/tests/relay_selector.rs#L1436)):*
> ```XML
>         .wireguard()
>         .daita()
>         .daita_use_anywhere(Constraint::Any)
> ```

Isn't `Constraint::Any` the default value of `use_anywhere` in a `WireguardRelayQuery`? I.e., this statement doesn't actually do anything :sweat_smile: 

If the intention is to test the relay selector with `use_anywhere` enabled, wouldn't it make sense to set the option to explicitly `true`? :blush:

```rust
.daita_use_anywhere(true)
```



_Code quote:_
```XML
        .daita_use_anywhere(Constraint::Any)
```

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 29 of 34 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-relay-selector/tests/relay_selector.rs` line 1436 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4ndXJG3jJGjwREFXCy:-O4o0iGg3p1vUkMyA1f-:b9xkasg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea6b55bcd4aa10968588bbea0778457ca543ab4/mullvad-relay-selector/tests/relay_selector.rs#L1436)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Isn't `Constraint::Any` the default value of `use_anywhere` in a `WireguardRelayQuery`? I.e., this statement doesn't actually do anything :sweat_smile: 

If the intention is to test the relay selector with `use_anywhere` enabled, wouldn't it make sense to set the option to explicitly `true`? :blush:

```rust
.daita_use_anywhere(true)
```
</blockquote></details>

Yes, the intention is to test with `use_anywhere` enabled. Setting it to Constraint::Any just made sense in my head, but clearly it doesn't make sense as a reader x)

I changed it

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 30 of 34 files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`mullvad-relay-selector/tests/relay_selector.rs` line 1436 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O4ndXJG3jJGjwREFXCy:-O4o4c7B1NaXaENCMUp5:b-p9p5o2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea6b55bcd4aa10968588bbea0778457ca543ab4/mullvad-relay-selector/tests/relay_selector.rs#L1436)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Yes, the intention is to test with `use_anywhere` enabled. Setting it to Constraint::Any just made sense in my head, but clearly it doesn't make sense as a reader x)

I changed it
</blockquote></details>

I mean, it did work right? :wink:
But thanks, I think it is more explicit this way :blush:

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 30 of 34 files reviewed, 1 unresolved discussion (waiting on @hulthe)

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 30 of 34 files reviewed, 1 unresolved discussion (waiting on @hulthe)

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r14, 1 of 3 files at r17, 16 of 29 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 27 of 40 files reviewed, 4 unresolved discussions (waiting on @hulthe)

___
*[`test/test-manager/src/tests/daita.rs` line 33 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O6uWahj5QBFFMDUbf1O:-O6uWahj5QBFFMDUbf1P:bopm8mq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5336918667c559a2c3e268d79ea92201246cb154/test/test-manager/src/tests/daita.rs#L33)):*
> ```XML
>         .iter()
>         .flat_map(|countries| &countries.cities)
>         .flat_map(|cities| &cities.relays)
> ```

Nit You could simplify this a bit by using the `relays` method on `RelayList`.
```rust
-        .countries
-        .iter()
-        .flat_map(|countries| &countries.cities)
-        .flat_map(|cities| &cities.relays)
+        .relays()
```



_Code quote:_
```XML
        .countries
        .iter()
        .flat_map(|countries| &countries.cities)
        .flat_map(|cities| &cities.relays)
```
___
*[`test/test-manager/src/tests/daita.rs` line 87 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O6uY6nx7V7CS0pBmm25:-O6uY6nx7V7CS0pBmm26:bj06x2d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5336918667c559a2c3e268d79ea92201246cb154/test/test-manager/src/tests/daita.rs#L87)):*
> ```XML
> 
>         log::info!("Failed to connect, this is expected!");
>     }
> ```

Should we also assert that we run into the expected error cause?

```rust
ensure!(matches!(state.cause(), ErrorStateCause::StartTunnelError));
```



_Code quote:_
```XML
    log::info!("Enabling DAITA and trying to connect without smart_routing");
    {
        mullvad_client.set_enable_daita(true).await?;
        mullvad_client.set_daita_smart_routing(false).await?;
        helpers::set_relay_settings(&mut mullvad_client, non_daita_location_query).await?;

        let result = helpers::connect_and_wait(&mut mullvad_client).await;
        let Err(Error::UnexpectedErrorState(state)) = result else {
            bail!("Connection failed unsuccessfully, reason: {:?}", result);
        };
        let ErrorStateCause::TunnelParameterError(_) = state.cause() else {
            bail!("Connection failed unsuccessfully, cause: {}", state.cause());
        };

        log::info!("Failed to connect, this is expected!");
    }
```
___
*[`test/test-manager/src/tests/daita.rs` line 150 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O6uYiB66wg6j5lCAECU:-O6uYiB66wg6j5lCAECV:b-n5pm0f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5336918667c559a2c3e268d79ea92201246cb154/test/test-manager/src/tests/daita.rs#L150)):*
> ```XML
> 
>         log::info!("Failed to connect, this is expected!");
>     }
> ```

Same dilemma here: should we also assert that the error cause matches the expected error cause?



_Code quote:_
```XML
    log::info!("Connecting to non_daita relay with multihop");
    {
        helpers::set_relay_settings(&mut mullvad_client, non_daita_multihop_query).await?;
        let result = helpers::connect_and_wait(&mut mullvad_client).await;
        let Err(Error::UnexpectedErrorState(state)) = result else {
            bail!("Connection failed unsuccessfully, reason: {:?}", result);
        };
        let ErrorStateCause::TunnelParameterError(_) = state.cause() else {
            bail!("Connection failed unsuccessfully, cause: {}", state.cause());
        };

        log::info!("Failed to connect, this is expected!");
    }
```

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 11 files at r6, 1 of 7 files at r10, 1 of 13 files at r14, 1 of 1 files at r15, 11 of 29 files at r18, 2 of 7 files at r19.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 36 of 41 files reviewed, 4 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 36 of 41 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/daita.rs` line 33 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O6uWahj5QBFFMDUbf1O:-O6v8Xk-DbDnVl9I3A9z:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5336918667c559a2c3e268d79ea92201246cb154/test/test-manager/src/tests/daita.rs#L33)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit You could simplify this a bit by using the `relays` method on `RelayList`.
```rust
-        .countries
-        .iter()
-        .flat_map(|countries| &countries.cities)
-        .flat_map(|cities| &cities.relays)
+        .relays()
```
</blockquote></details>

Done
___
*[`test/test-manager/src/tests/daita.rs` line 87 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O6uY6nx7V7CS0pBmm25:-O6v8iyk7rK7G-I1qiIi:bwqbmpp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5336918667c559a2c3e268d79ea92201246cb154/test/test-manager/src/tests/daita.rs#L87)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should we also assert that we run into the expected error cause?

```rust
ensure!(matches!(state.cause(), ErrorStateCause::StartTunnelError));
```
</blockquote></details>

what do you mean? TunnelParameterError is the expected `state.cause`

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r19, 1 of 7 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-:-O6vJ5FvC751uWvz-LE6:bnfp4nl)* status: 33 of 42 files reviewed, 3 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 3 of 7 files at r19, 5 of 7 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604)* status: 41 of 42 files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`test/test-manager/src/tests/daita.rs` line 87 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-O6uY6nx7V7CS0pBmm25:-O6ya3Rm95fqd9P0KEqz:b-9vnc3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5336918667c559a2c3e268d79ea92201246cb154/test/test-manager/src/tests/daita.rs#L87)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

what do you mean? TunnelParameterError is the expected `state.cause`
</blockquote></details>

Nvm, I was stupid

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6604#-:-O6yagpo7GI_5tc0abXa:bnfp4nl)* status: 41 of 42 files reviewed, all discussions resolved

**Pull request merged**
