### PR TITLE
Add copy icon feedback on click

### PR DESCRIPTION
**Pull request by sabercodic**
Fixes: DROID-171

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-Nafxv848aL0qNkTK5rB:-Nafxv854EDVeDTxWpi1:b9i93nt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L20)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.R
> 
> private const val PRESS_EFFECT_TIME_SPAN: Long = 1000
> ```

This should be an argument instead.



_Code quote:_
```Kotlin
private const val PRESS_EFFECT_TIME_SPAN: Long = 1000
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-NafygIj0SCDkQ_w8dH4:-NafygIj0SCDkQ_w8dH5:b-bkm4nr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L24)):*
> ```Kotlin
> @OptIn(ExperimentalAnimationApi::class)
> @Composable
> fun AnimatedContentButton(
> ```

What is "Content" in `AnimatedContentButton` referring to? Isn't this more like a `AnimatedIconButton` or something?



_Code quote:_
```Kotlin
AnimatedContentButton
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-NafyUdU3UFsi_sA7nIV:-NafyUdU3UFsi_sA7nIW:bxlza65) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L48)):*
> ```Kotlin
>                 )
>             }
>             ButtonState.TOGGLED -> {
> ```

Is this used somewhere or why did you add it?



_Code quote:_
```Kotlin
ButtonState.TOGGLED
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-NafzW_fA0DGmT2fz-hJ:-NafzW_fA0DGmT2fz-hK:b-gmjlev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L80)):*
> ```Kotlin
>     TOGGLED,
>     PRESSED
> }
> ```

Since we don't support "toggled" (?) I suggest just using a boolean value to represent idle or pressed.



_Code quote:_
```Kotlin
enum class ButtonState {
    IDLE,
    TOGGLED,
    PRESSED
}
```

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-NafyUdU3UFsi_sA7nIV:-Nag-h5z-MA9Ax6NEGzQ:bdigpue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L48)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this used somewhere or why did you add it?
</blockquote></details>

Nvm, misunderstood this one
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 80 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-NafzW_fA0DGmT2fz-hJ:-Nag-oJM-BUto1hkgPtV:bdigpue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L80)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Since we don't support "toggled" (?) I suggest just using a boolean value to represent idle or pressed.
</blockquote></details>

Nvm, misunderstood this one

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-Nafxv848aL0qNkTK5rB:-Nak1xSB5fLTZXOFaffu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L20)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should be an argument instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934#-NafygIj0SCDkQ_w8dH4:-Nak2oo52x8qS6NKBZOw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2915b1d69b883a40d44162076b295186df0573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedContentButton.kt#L24)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What is "Content" in `AnimatedContentButton` referring to? Isn't this more like a `AnimatedIconButton` or something?
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
