### PR TITLE
Problem report to crate

### PR DESCRIPTION
**Pull request by faern**
Moving out the problem-report to its own crate. Basically it was never closely tied to the daemon anyway. Plus, this will allow easier adding special binary metadata on Windows for example.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @mvd-ows and @pronebird)

---

*[mullvad-problem-report/src/main.rs, line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGQPwubEBj1JdzpKoLO:-LGQPwubEBj1JdzpKoLP:b-m455mm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfab544af495f4518b8328f9a1c150bd962dd109/mullvad-problem-report/src/main.rs#L34)):*
> ```Rust
> 
> /// Maximum number of bytes to read from each log file
> const LOG_MAX_READ_BYTES: usize = 512 * 1024;
> ```

Decreased to `512` kiB to not make the report huge when we have more logs. Is this OK @richard-mullvad ?

---

*[mullvad-problem-report/src/main.rs, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGQPR8xByQUrDO8T5yR:-LGQPR8xByQUrDO8T5yS:bqo55o8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfab544af495f4518b8328f9a1c150bd962dd109/mullvad-problem-report/src/main.rs#L37)):*
> ```Rust
> const EXTRA_BYTES: usize = 32 * 1024;
> /// Fit four logs plus some system information in the report.
> const REPORT_MAX_SIZE: usize = 4 * LOG_MAX_READ_BYTES + EXTRA_BYTES;
> ```

FYI we previously only had two logs. The OpenVPN logs and the daemon logs. Now we rotate both and keep one old copy. So we have a maximum of four logs ending up in the report... Wait, we have the GUI log as well. Did we not account for that earlier? I probably want to bump this to `5` now?

Anyway, the updated `EXTRA_BYTES` is because on macOS we have some short installation logs as well. Plus with the extra logs the delimiters between all the logs now take a little bit more space as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)*

**Comment by mvd-ows** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @pronebird, @mvd-ows, and @faern)

---

*[mullvad-cli/Cargo.toml, line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGTfPxh9NrgM6bgnrNX:-LGTfPxh9NrgM6bgnrNY:bift0ne) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36cde95c19b0f669b9c612a03917031d2aeddc62/mullvad-cli/Cargo.toml#L5)):*
> ```TOML
> version = "2018.1.0"
> authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
> description = "Manage the Mullvad VPN daemon via a convenient CLI"
> ```

Great description :+1: 

---

*[mullvad-problem-report/src/main.rs, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGQPR8xByQUrDO8T5yR:-LGTgAJR2iukWMb7Ks_0:b-driomf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfab544af495f4518b8328f9a1c150bd962dd109/mullvad-problem-report/src/main.rs#L37)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

FYI we previously only had two logs. The OpenVPN logs and the daemon logs. Now we rotate both and keep one old copy. So we have a maximum of four logs ending up in the report... Wait, we have the GUI log as well. Did we not account for that earlier? I probably want to bump this to `5` now?

Anyway, the updated `EXTRA_BYTES` is because on macOS we have some short installation logs as well. Plus with the extra logs the delimiters between all the logs now take a little bit more space as well.
</blockquote></details>

This expression depends on operator precedence. Doesn't hurt to include parentheses.

---

*[mullvad-problem-report/src/main.rs, line 447 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGTiRWDDR6-6mXn2cw6:-LGTiRWDDR6-6mXn2cw7:bvueu7a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36cde95c19b0f669b9c612a03917031d2aeddc62/mullvad-problem-report/src/main.rs#L447)):*
> ```Rust
>     let mut metadata = HashMap::new();
>     metadata.insert(
>         String::from("mullvad-daemon-version"),
> ```

This string reference needs to be updated?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)*

**Comment by faern** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @pronebird, and @faern)

---

*[mullvad-cli/Cargo.toml, line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGTfPxh9NrgM6bgnrNX:-LGUSuHq9U_aRIst-gry:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36cde95c19b0f669b9c612a03917031d2aeddc62/mullvad-cli/Cargo.toml#L5)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Great description :+1: 
</blockquote></details>

Done.

---

*[mullvad-problem-report/src/main.rs, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGQPR8xByQUrDO8T5yR:-LGUTcbx0xiOLOUP0LIn:b-hj3ub9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfab544af495f4518b8328f9a1c150bd962dd109/mullvad-problem-report/src/main.rs#L37)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This expression depends on operator precedence. Doesn't hurt to include parentheses.
</blockquote></details>

I'll add that.

---

*[mullvad-problem-report/src/main.rs, line 447 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGTiRWDDR6-6mXn2cw6:-LGUTQ32CETa8oinXA4f:b6hkkpc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36cde95c19b0f669b9c612a03917031d2aeddc62/mullvad-problem-report/src/main.rs#L447)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This string reference needs to be updated?
</blockquote></details>

I was thinking about that. The problem is that these key-values are parsed by the server to get metadata about the problem report. But I spoke to Simon and he is OK with making it look for `mullvad-product-version`. So I'll update it to that if that sounds better?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)*

**Comment by mvd-ows** [comment]
Reviewed 5 of 5 files at r3.
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @mvd-ows, @pronebird, and @faern)

---

*[Cargo.lock, line 768 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGUURBaD62KQkLLbpWg:-LGUURBaD62KQkLLbpWh:bjtx2w1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e4a50269e468a2b9739fc11544f8b2a6753ea9f1/Cargo.lock#L768)):*
> ```TOML
> [[package]]
> name = "mullvad-cli"
> version = "2018.2.0-beta1"
> ```

Perhaps this should be in a separate PR to not accidentally hide it? I don't mind either way.

---

*[mullvad-problem-report/src/main.rs, line 447 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266#-LGTiRWDDR6-6mXn2cw6:-LGUUo3d393lNtB5itsS:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36cde95c19b0f669b9c612a03917031d2aeddc62/mullvad-problem-report/src/main.rs#L447)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I was thinking about that. The problem is that these key-values are parsed by the server to get metadata about the problem report. But I spoke to Simon and he is OK with making it look for `mullvad-product-version`. So I'll update it to that if that sounds better?
</blockquote></details>

Nice!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)*

**Comment by mvd-ows** [comment]
Reviewed 2 of 2 files at r4.
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @pronebird, @mvd-ows, and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)*

**Comment by pronebird** [comment]
Reviewed 2 of 8 files at r1, 3 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @mvd-ows)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/266)*

**Pull request merged**
