### PR TITLE
Add tests for version checker

### PR DESCRIPTION
**Pull request by dlon**
Fix DES-870.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/version_check.rs` line 622 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-NvpWLC-E7xeQDhZCzdO:-NvpWLC0-SQQP9CA8TOE:b-gv74b6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9c0478e60a6138375ad0dd8cccd128aaf9880d8/mullvad-daemon/src/version_check.rs#L622)):*
> ```XML
>     /// Test whether check immediately fetches version info if it's non-existent
>     #[tokio::test(start_paused = true)]
>     async fn test_version_check_run_immediate() {
> ```

If I run `cargo test` in the `mullvad-daemon` crate, I get the following error
```
$ cargo test
   Compiling mullvad-daemon v0.0.0 (/home/markus/projects/mullvad/app/mullvad-daemon)
error[E0599]: no method named `start_paused` found for struct `tokio::runtime::Builder` in the current scope
   --> mullvad-daemon/src/version_check.rs:620:5
    |
620 |     #[tokio::test(start_paused = true)]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field, not a method
    |
    = note: this error originates in the attribute macro `tokio::test` (in Nightly builds, run with -Z macro-backtrace for more info)
```

It can be fixed by enabling the `test-util` feature for `tokio`
```toml
# mullvad-daemon/Cargo.toml
[dev-dependencies]
talpid-time = { path = "../talpid-time", features = ["test"] }
tokio = { workspace = true, features =  ["test-util"] }
```



_Code quote:_
```XML
    #[tokio::test(start_paused = true)]
    async fn test_version_check_run_immediate() {
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/version_check.rs` line 622 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-NvpWLC-E7xeQDhZCzdO:-NvpvzuXCR9D7Jj-8Eq-:bka5xw7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9c0478e60a6138375ad0dd8cccd128aaf9880d8/mullvad-daemon/src/version_check.rs#L622)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

If I run `cargo test` in the `mullvad-daemon` crate, I get the following error
```
$ cargo test
   Compiling mullvad-daemon v0.0.0 (/home/markus/projects/mullvad/app/mullvad-daemon)
error[E0599]: no method named `start_paused` found for struct `tokio::runtime::Builder` in the current scope
   --> mullvad-daemon/src/version_check.rs:620:5
    |
620 |     #[tokio::test(start_paused = true)]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field, not a method
    |
    = note: this error originates in the attribute macro `tokio::test` (in Nightly builds, run with -Z macro-backtrace for more info)
```

It can be fixed by enabling the `test-util` feature for `tokio`
```toml
# mullvad-daemon/Cargo.toml
[dev-dependencies]
talpid-time = { path = "../talpid-time", features = ["test"] }
tokio = { workspace = true, features =  ["test-util"] }
```
</blockquote></details>

Fixed! Thanks.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`mullvad-daemon/src/version_check.rs` line 221 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw4XmKfCnV04v2w2A_j:-Nw4XmKfCnV04v2w2A_k:b-uq8vuq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L221)):*
> ```XML
>     /// Also, if we are currently have a pending [GetVersionInfo][rvc] command, respond to it.
>     ///
>     /// [rvc]: VersionUpdaterCommand::GetVersionInfo
> ```

This docstr looks outdated
___
*[`mullvad-daemon/src/version_check.rs` line 401 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw4WLe6BamM33nfwOUj:-Nw4WLe6BamM33nfwOUk:bcm5edk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L401)):*
> ```XML
> impl UpdateContext {
>     /// Write [Self::last_app_version_info], if any, to the cache file ([VERSION_INFO_FILENAME]).
>     /// Also notify listener
> ```

Broken doc link
___
*[`mullvad-daemon/src/version_check.rs` line 418 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw4X0rn6J0o_W-XPxEy:-Nw4X0rn6J0o_W-XPxEz:b-uw9sk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L418)):*
> ```XML
>             let _ = tokio::io::copy(&mut read_buf, &mut file)
>                 .await
>                 .map_err(Error::WriteVersionCache)?;
> ```

Nit: Would tokio::fs::write look nicer?
___
*[`mullvad-daemon/src/version_check.rs` line 739 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw5DRGa5hOd860YHdK3:-Nw5DRGb7HJqzDdsnSQh:b-ni55ov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L739)):*
> ```XML
>             latest_beta: "2024.1-beta1".to_owned(),
>         }
>     }
> ```

Very cool test setup. Didn't know tokio had these features.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

___
*[`mullvad-daemon/src/version_check.rs` line 221 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw4XmKfCnV04v2w2A_j:-Nw9I-sIE415kFDHDNnc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L221)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

This docstr looks outdated
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/version_check.rs` line 401 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw4WLe6BamM33nfwOUj:-Nw9I-MNA6o1SWdjBWVK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L401)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Broken doc link
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/version_check.rs` line 418 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153#-Nw4X0rn6J0o_W-XPxEy:-Nw9DyCZCh1Zl_nAv6db:b809414) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd4f53f162292b76978279eefedf3cec503a9576/mullvad-daemon/src/version_check.rs#L418)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Nit: Would tokio::fs::write look nicer?
</blockquote></details>

It would! Done.

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 3 of 3 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
