### PR TITLE
Negotiate with both peers when using multihop and pq ios 746

### PR DESCRIPTION
**Pull request by mojganii**
In the current implementation, the Post-Quantum key is negotiated only with the exit peer. To enhance security, we proposed an implementaion  to be sure that no traffic is leaked until PQ key exchanges have been completed with both the entry and exit peers.this PR support PQ key exchanging for both peers when multihop is enabled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 24 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509)* status: 24 of 26 files reviewed, 11 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 4102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iOnBd5ufSIs4MuHpS:-O2iOnBd5ufSIs4MuHpT:b-dg6u9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/MullvadVPN.xcodeproj/project.pbxproj#L4102)):*
> ```
> 				F05919782C45402E00C301F3 /* SingleHopPostQuantumKeyExchanging.swift */,
> 			);
> 			path = PostQuantom;
> ```

This folder should be renamed `PostQuantum` 
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2i8X7uDE2IE44NGCom:-O2i8X7uDE2IE44NGCon:b-6wobvk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L106)):*
> ```Swift
>                 iteratorProvider: { REST.RetryStrategy.postQuantumKeyExchange.makeDelayIterator() }
>             ),
>             onUpdateConfiguration: { [weak self] configuration in
> ```

Since the packet tunnel provider is guaranteed to always be a valid instance, we can simplify this using `unowned` here
```swift
            onUpdateConfiguration: { [unowned self] configuration in
                actor.replaceKeyWithPQ(configuration: configuration)
            }, onFinish: { [unowned self] in
                actor.notifyPostQuantumKeyExchanged()
            }
```

Or if you want to keep weak references, you don't need to strongify them just after for the same reason.
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 279 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2i96qLAxmPRpbCfsKk:-O2i96qLAxmPRpbCfsKl:bxmjfp4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L279)):*
> ```Swift
>                     lastConnectionAttempt = connectionAttempt
> 
>                 case let .negotiatingPostQuantumKey(connState, privateKey):
> ```

I think we should rename this `observedConnectionState` to remind ourselves of what it is, since we don't have type information available without clicking around.
___
*[`ios/PacketTunnel/PostQuantom/MultiHopPostQuantumKeyExchanging.swift` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iIfPSC2ZeVKxj90vZ:-O2iIfPSC2ZeVKxj90v_:b-gwyy4a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnel/PostQuantom/MultiHopPostQuantumKeyExchanging.swift#L27)):*
> ```Swift
>     private var exitPostQuantumKey: PostQuantumKey!
> 
>     private let defaultGatewayAddressRange = [IPAddressRange(from: "10.64.0.1/32")!]
> ```

We are starting to repeat those 2 addresses (`10.64.0.1` and `0.0.0.0`) quite a lot in the codebase.
How about we add a `VPNConstants` enum in `MullvadTypes` where we can have this, and the IP subnet masks perhaps ?
___
*[`ios/PacketTunnel/PostQuantom/MultiHopPostQuantumKeyExchanging.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iKhkT5tmSeQDbXDQM:-O2iKhkT5tmSeQDbXDQN:b-6xapjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnel/PostQuantom/MultiHopPostQuantumKeyExchanging.swift#L37)):*
> ```Swift
>         case negotiatingBetweenEntryAndExit
>         case makeConnection
>         case connected
> ```

We are not using the `connected` state it seems, let's remove it 
___
*[`ios/PacketTunnel/PostQuantom/MultiHopPostQuantumKeyExchanging.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iMse565w_55EmsEba:-O2iMse565w_55EmsEbb:bwsp0n9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnel/PostQuantom/MultiHopPostQuantumKeyExchanging.swift#L56)):*
> ```Swift
>     }
> 
>     func start() {
> ```

I like that the flow is self explanatory, but I think we can still document how the whole PQ KEX process happens overall,
as it's a pretty intricate process, and it will make it easier for our future selves (or new additions to the team) to understand what's going on.

I can help writing that part if you want. 
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iV8IYDdgPtBi9iFOU:-O2iV8IYDdgPtBi9iFOV:bhg401l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPostQuantum.swift#L59)):*
> ```Swift
>          */
>         let settings: Settings = try settingsReader.read()
>         let connectionData = try obfuscateConnection(
> ```

`obfuscateConnection` might return `nil` if the `state` is either `disconnecting` or `disconnected`, which will crash down the line with the forced unwraps we do.

It's okay to return early instead and print an error.

```swift
        guard let connectionData = try obfuscateConnection(
            nextRelays: .current,
            settings: settings,
            reason: .userInitiated
        ) else {
            logger.error("Tried to replace post quantum configuration in invalid state: \(state.name)")
            return
        }
```
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Public.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iWSwX8hvsfGAnyROU:-O2iWSwX8hvsfGAnyROV:b-i2edn8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPublic.swift#L67)):*
> ```Swift
>      */
> 
>     nonisolated public func replaceKeyWithPQ(configuration: PostQuantumNegotiationState) {
> ```

We should rename this `updatePostQuantumNegotiationState(configuration: PostQuantumNegotiationState)`
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iWElp79Q_1_qCDPBO:-O2iWElp79Q_1_qCDPBP:b-8ubbn8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift#L40)):*
> ```Swift
> 
>         /// Update the device private key, as per post-quantum protocols
>         case replaceDevicePrivateKey(PostQuantumNegotiationState)
> ```

We should probably rename this `postQuantumNegotiationStateChanged` 
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iXD4YCeQd52Cj8tFS:-O2iXD4YCeQd52Cj8tFT:bn9sfzv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift#L23)):*
> ```Swift
>         case restartConnection(NextRelays, ActorReconnectReason)
>         case reconfigureForPostQuantum(PostQuantumNegotiationState)
>         // trigger a reconnect, which becomes several effects depending on the state
> ```

Shouldn't we handle the `reconfigureForPostQuantum` effect here too ?
___
*[`ios/PacketTunnelCoreTests/MultiHopPostQuantumKeyExchangingTests.swift` line 115 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-O2iYNt2ABPGtzmCh2-F:-O2iYNt2ABPGtzmCh2-G:b7vnhbt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cbaaaa62d1b508a7a553bf8f635b6d082111ec9f/ios/PacketTunnelCoreTests/MultiHopPostQuantumKeyExchangingTests.swift#L115)):*
> ```Swift
>             keyExchanger: keyExchangeActor
>         ) { _ in
>             reconfigurationExpectation.fulfill()
> ```

We should check that the correct pre shared key and ephemeral keys are sent here, and in the other places where we update the configuration with new keys.

Also that the configuration sent is the correct one.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 26 files at r1, 13 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509#-:-O2iw9DP8rrCQxrFc3Jz:bnfp4nl)* status: 27 of 28 files reviewed, 11 unresolved discussions (waiting on @mojganii)

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509)* status: 27 of 28 files reviewed, 11 unresolved discussions (waiting on @mojganii)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 14 of 26 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509)* status: all files reviewed, 11 unresolved discussions (waiting on @mojganii)

**Pull request merged**
