### PR TITLE
Add container based android build server script

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to create a new Android specific build server script that builds the Android app in a container.

This PR relies on: #4184

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)

### CODE REVIEW

**Review by faern — APPROVED** [review]
Looks good to me! Some minor stuff, but basically mergable. Great work! :lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-:-NICmBt72Nh_LtSYitXI:b-4j0q10)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`ci/buildserver-build-android.sh` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NICjoHx2kPzLDaEnsqw:-NICjoHx2kPzLDaEnsqx:bagacla) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7b9b60ca61d1a7027f9554f6faab8053f8deba9e/ci/buildserver-build-android.sh#L15)):*
> ```Shell
> BUILD_DIR="$SCRIPT_DIR/mullvadvpn-app"
> LAST_BUILT_DIR="$SCRIPT_DIR/last-built"
> UPLOAD_DIR="/home/upload/upload"
> ```

This was a separate users since the old build server received artifacts from the macOS and Windows machines over sftp. On this machine we won't need that. At least not for now, and maybe not even later. So maybe modify this to use just `$SCRIPT_DIR/upload` for simplicity?
___
*[`ci/buildserver-build-android.sh` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NICkfre-07RVSZjiKsk:-NICkfrfEcdqlxVTqWdl:bfgthxj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7b9b60ca61d1a7027f9554f6faab8053f8deba9e/ci/buildserver-build-android.sh#L23)):*
> ```Shell
>   for f in MullvadVPN-*.{apk,aab}; do
>     sha256sum "$f" > "$f.sha256"
>       # Linux is both the build and upload server. Just move directly to target dir
> ```

Something is wrong with the indentation of the comment here.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: 1 of 9 files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`ci/buildserver-build-android.sh` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIGiGd8DlXKosArMtsu:-NIGiGd8DlXKosArMtsv:b-3dm6fm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22397f8b546de00fb3d356db07ea357b83ecd4b2/ci/buildserver-build-android.sh#L15)):*
> ```Shell
> BUILD_DIR="$SCRIPT_DIR/mullvadvpn-app"
> LAST_BUILT_DIR="$SCRIPT_DIR/last-built"
> UPLOAD_DIR="/home/upload/upload"
> ```

Why was this reverted?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`ci/buildserver-build-android.sh` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIGiGd8DlXKosArMtsu:-NIH-gi55xDAzMWXn-1k:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22397f8b546de00fb3d356db07ea357b83ecd4b2/ci/buildserver-build-android.sh#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why was this reverted?
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`ci/buildserver-build-android.sh` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIffKA253GF60wde2Q3:-NIffKA253GF60wde2Q4:b-b8wenl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/260df9cfac58e9eef825222e2ad69b62f732a972/ci/buildserver-build-android.sh#L62)):*
> ```Shell
> 
>   echo "Building Android app"
>   ANDROID_CREDENTIALS_DIR=$SCRIPT_DIR/credentials-android \
> ```

Any reason not to move this up to where the other local paths are defined, such as `UPLOAD_DIR`? I would prefer that for consistency and it being more self-documenting.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`ci/buildserver-build-android.sh` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIffKA253GF60wde2Q3:-NIgBFoy6vu7Dq8_lITB:bvrizh1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/260df9cfac58e9eef825222e2ad69b62f732a972/ci/buildserver-build-android.sh#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Any reason not to move this up to where the other local paths are defined, such as `UPLOAD_DIR`? I would prefer that for consistency and it being more self-documenting.
</blockquote></details>

The difference is that `UPLOAD_DIR` is used by _this_ script whereas `ANDROID_CREDENTIALS_DIR` is used only by `./building/containerized-build.sh`. I can move it to the top or to a separate line, but that would also mean setting it to `export`.

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`ci/buildserver-build-android.sh` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIffKA253GF60wde2Q3:-NIhHu956YwblYzKwNvp:b-sp7a3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/260df9cfac58e9eef825222e2ad69b62f732a972/ci/buildserver-build-android.sh#L62)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The difference is that `UPLOAD_DIR` is used by _this_ script whereas `ANDROID_CREDENTIALS_DIR` is used only by `./building/containerized-build.sh`. I can move it to the top or to a separate line, but that would also mean setting it to `export`.
</blockquote></details>

You can move the definition up and update this line to

```bash
ANDROID_CREDENTIALS_DIR=$ANDROID_CREDENTIALS_DIR ./building/containerized-build.sh android --app-bundle || return 0
```

That's probably what I would prefer.

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`ci/buildserver-build-android.sh` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIffKA253GF60wde2Q3:-NIhIBbP7ml9GI-BMH1c:bb8ggyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/260df9cfac58e9eef825222e2ad69b62f732a972/ci/buildserver-build-android.sh#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You can move the definition up and update this line to

```bash
ANDROID_CREDENTIALS_DIR=$ANDROID_CREDENTIALS_DIR ./building/containerized-build.sh android --app-bundle || return 0
```

That's probably what I would prefer.
</blockquote></details>

Since the value it contains is of importance when understanding what this script does. How it later passes on the value to potential sub-scripts is an implementation detail.

We have examples of this style already being used by us here: https://github.com/mullvad/mullvadvpn-app/blob/ba01f52daba959da8cc34f99a5205ff35b97ac09/build.sh#L282

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @faern and @sabercodic)

___
*[`ci/buildserver-build-android.sh` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186#-NIffKA253GF60wde2Q3:-NIhOeI90UoT-8KF0cnz:b-h43rl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/260df9cfac58e9eef825222e2ad69b62f732a972/ci/buildserver-build-android.sh#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since the value it contains is of importance when understanding what this script does. How it later passes on the value to potential sub-scripts is an implementation detail.

We have examples of this style already being used by us here: https://github.com/mullvad/mullvadvpn-app/blob/ba01f52daba959da8cc34f99a5205ff35b97ac09/build.sh#L282
</blockquote></details>

Sounds good, done!

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
