### PR TITLE
Graceful shutdown on Windows (and all other platforms).

### PR DESCRIPTION
**Pull request by pinkisemils**
I've changed the way OpenVPN subprocess is stopped to allow it to be stopped gracefully on windows.
The changes here are intended to work with the changes outlined here https://github.com/mullvad/openvpn/pull/5

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[talpid-core/src/process/openvpn.rs, line 221 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYV2WJA8rQa4YQts0b:-LCYV2WJA8rQa4YQts0c:b-7uhfwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/openvpn.rs#L221)):*
> ```Rust
>     pub fn new(openvpn_command: duct::Expression) -> io::Result<Self> {
>         let (reader, writer) = pipe()?;
>         let mut cmd = openvpn_command;
> ```

Can't you mark the argument as `mut` directly instead of reassigning it?

---

*[talpid-core/src/process/openvpn.rs, line 231 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYVK1m1p0-nG-0dwIs:-LCYVK1m1p0-nG-0dwIt:b-d7jtri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/openvpn.rs#L231)):*
> ```Rust
>         }
> 
>         let proc_handle = cmd.stdin_handle(reader).start()?;
> ```

Very picky. But I would have moved down `let (reader, writer) = pipe()?;` to just before this line. Since this is where it's first used.

---

*[talpid-core/src/process/openvpn.rs, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYVxQk9NdUH1djl_OI:-LCYVxQk9NdUH1djl_OJ:b202kua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/openvpn.rs#L244)):*
> ```Rust
>         use std::io::Write;
>         let mut writer = self.stdin.lock().unwrap();
>         writer.write(&[Self::KILL_BYTE])?;
> ```

I think this risks returning after writing zero bytes. If it's changed to the `write_all` method we will know that the `KILL_BYTE` has been written.

---

*[talpid-core/src/process/openvpn.rs, line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYWJyc5JvjJX89UnEI:-LCYWJyc5JvjJX89UnEJ:btgy5cs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/openvpn.rs#L249)):*
> ```Rust
> 
>     /// Brutally kills the underlinyg process
>     pub fn kill_process(&self) -> io::Result<()> {
> ```

Feels like both `kill_process` and `try_stop` could be removed and the code be put just in the implementation for `StoppableProcess`? Since I don't think this type is never used directly? It's just used as a `StoppableProcess`.

---

*[talpid-core/src/process/stoppable_process.rs, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYUA4s3M0mBrhEjNea:-LCYUA4s3M0mBrhEjNeb:bwb5a11) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/stoppable_process.rs#L10)):*
> ```Rust
> use std::time::{Duration, Instant};
> 
> static POLL_INTERVAL_MS: u64 = 50;
> ```

Fairly minor thing. But `Duration::from_millis` has been made a `const fn` now, so we could encode the type better in the constant:
```rust
const POLL_INTERVAL: Duration = Duration::from_millis(50);
```

---

*[talpid-core/src/process/stoppable_process.rs, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYSMZV11t2gVkSi1GB:-LCYSMZV11t2gVkSi1GC:bon7p6i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/stoppable_process.rs#L20)):*
> ```Rust
>     /// Gracefully stops a process.
>     fn stop(&self) -> io::Result<()>;
>     /// Kills a process unconditionally. Implementations should strive to never fail.
> ```

Could we maybe have a newline between a method and the documentation for the coming method? Now all these methods are very smooshed together.

---

*[talpid-core/src/process/stoppable_process.rs, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYSeQu7QoLvR0c2VZu:-LCYSeQu7QoLvR0c2VZv:b27jret) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/stoppable_process.rs#L28)):*
> ```Rust
>     /// process.
>     fn nice_kill(&self, timeout: Duration) -> io::Result<()> {
>         trace!("Trying to stop openvpn gracefully");
> ```

This trait is written as if it was not at all related to OpenVPN. So then it should probably not mention OpenVPN in its logging. Or it could be moved to the `openvpn` module and be made completely OpenVPN specific.

I also think we should stick to capitalizing it as OpenVPN for any display version of the name.

---

*[talpid-core/src/process/stoppable_process.rs, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYTP0XBHLXISQrMjGc:-LCYTP0XBHLXISQrMjGd:b-d27ifx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/stoppable_process.rs#L41)):*
> ```Rust
>             Ok(())
>         } else {
>             warn!("Child process did not exit from SIGTERM, sending SIGKILL");
> ```

The terms `SIGTERM` and `SIGKILL` are not technically correct at this platform agnostic level of the abstraction. Maybe replace "sending SIGKILL" with "forcing process termination" and "exit from SIGTERM" with "terminate gracefully within timeout"?

---

*[talpid-core/src/process/stoppable_process.rs, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYUN1y4zEA0ArWdxcl:-LCYUN1y4zEA0ArWdxcm:bl2kub4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/stoppable_process.rs#L47)):*
> ```Rust
> }
> 
> impl StoppableProcess for OpenVpnProcHandle {
> ```

I feel this implementation should be next to `OpenVpnProcHandle` rather than next to the trait.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Review status: 4 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[talpid-core/src/process/openvpn.rs, line 276 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCZTmpW6P26K3dIfiRL:-LCZU6S05RG8xPySoit1:bextb46) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99939b19c603d97571271b37ba424c73e084f884/talpid-core/src/process/openvpn.rs#L276)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I can't find any explicit `Drop` implementation in the code for `os_pipe`. But the documentation and some comments in the code seems to suggest that a dropped pipe automatically closes it. Have you tried this?
</blockquote></details>

Ah. The handles hold `File`s which Rust should close for us when they are dropped. That is probably how it works.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Reviewed 1 of 5 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/process/openvpn.rs, line 276 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCZTmpW6P26K3dIfiRL:-LC_JL4cCTwj7cfhct7T:b-9zb35x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99939b19c603d97571271b37ba424c73e084f884/talpid-core/src/process/openvpn.rs#L276)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah. The handles hold `File`s which Rust should close for us when they are dropped. That is probably how it works.
</blockquote></details>

I wanted to avoid taking `self` by value as to not break all the interfaces that already existed for this code, and I don't think that relying on `Drop` makes it obvious what this code does.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/process/openvpn.rs, line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCYWJyc5JvjJX89UnEI:-LC_KUhl70PFH_IZE3z0:b-4ww888) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ea9bd60dc213edaa9bf5156d5bff8a716f4cbef/talpid-core/src/process/openvpn.rs#L249)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Feels like both `kill_process` and `try_stop` could be removed and the code be put just in the implementation for `StoppableProcess`? Since I don't think this type is never used directly? It's just used as a `StoppableProcess`.
</blockquote></details>

Yep, moved these functions to the trait implementation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 2 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/process/openvpn.rs, line 276 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCZTmpW6P26K3dIfiRL:-LCbkEQt-htnpNEaGNki:b-c29q71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99939b19c603d97571271b37ba424c73e084f884/talpid-core/src/process/openvpn.rs#L276)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I wanted to avoid taking `self` by value as to not break all the interfaces that already existed for this code, and I don't think that relying on `Drop` makes it obvious what this code does.
</blockquote></details>

I think bringing in two low level ways of closing a raw handle is much more confusing. Using the drop it could be simplified to a single
```rust
fn stop(&mut self) {
    // Drop our stdin handle to close it. Will cause our fork of OpenVPN to quit gracefully.
    let _ = self.stdin.take();
}
```

This code above would of course also require us to put `stdin` in an `Option` and to change `stop` to take `&mut self` and not return a `Result`. I feel it's fully reasonable to make the trait take `&mut self`. If your type represents a process, the action to stop that process very much feels like a mutation action.

I feel the added comment much simpler expresses the intent than the many lines of low level code present to close handles differently on different platforms.

One possible downside is that we won't know if the close failed or not. I don't know in what situations the different platforms can possibly fail to close a handle that we are the unique owners to, I guess that should not happen? And the worst thing that happens if we don't know the result of `stop` is that we'll wait the timeout when we didn't need to, nothing critical.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[talpid-core/src/process/openvpn.rs, line 261 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCcZ5QF23IUuBJWe9wE:-LCcZ5QF23IUuBJWe9wF:br8sn7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ad3a2c3e53c27d762ce226651e94695e3bac3c4/talpid-core/src/process/openvpn.rs#L261)):*
> ```Rust
>         // gracefully stop our openvpn child process.
>         let _ = stdin.take();
>         Ok(())
> ```

Is there any reason this has to still return a `Result` at all? Isn't this the only implementer to begin with, and it deterministically succeeds. Might simplify the `nice_kill` implementation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[talpid-core/src/process/openvpn.rs, line 261 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCcZ5QF23IUuBJWe9wE:-LCcf9dRDxNE_RtOxVV2:bw63w0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ad3a2c3e53c27d762ce226651e94695e3bac3c4/talpid-core/src/process/openvpn.rs#L261)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is there any reason this has to still return a `Result` at all? Isn't this the only implementer to begin with, and it deterministically succeeds. Might simplify the `nice_kill` implementation.
</blockquote></details>

Fair point.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[talpid-core/src/process/openvpn.rs, line 236 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCmZTCQ6WRpF8i8XBPx:-LCmZTCQ6WRpF8i8XBPy:b-d2hnp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3749055e11e7fefb4a31ed9ec9046a856a921207/talpid-core/src/process/openvpn.rs#L236)):*
> ```Rust
>     /// Constructor for a new openvpn proc handle
>     pub fn new(mut cmd: duct::Expression) -> io::Result<Self> {
>         if atty::is(atty::Stream::Stdout) || cfg!(windows) {
> ```

What is the reason Windows should always send output to `NUL`? The OpenVPN output won't be displayed in the console anyway?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[talpid-core/src/process/openvpn.rs, line 236 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCmZTCQ6WRpF8i8XBPx:-LCmd1Uo4rhIiQEcOYyN:bynmc53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3749055e11e7fefb4a31ed9ec9046a856a921207/talpid-core/src/process/openvpn.rs#L236)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What is the reason Windows should always send output to `NUL`? The OpenVPN output won't be displayed in the console anyway?
</blockquote></details>

This was an arcane bug that I came across when running the daemon as a service on windows - since the parent process has no handles for STDIN/STDERR/STDOUT, the child process can't inherit any. It would work if the standard input handle is not set, but it would fail if it was. And _obviously_,  in this case in order to add one of those handles, you have to add all three. Otherwise, the process would fail to start with errors about how the standard IO handles are not available (which makes sense, since the subprocess will try to inherit them from the parent). I think from now on, all manual testing on Windows will have to be done when the daemon is running as a service. But yes, I could redirect standard error out to a file where we store all the logs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[talpid-core/src/process/openvpn.rs, line 236 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCmZTCQ6WRpF8i8XBPx:-LCmhWP563JMkI78C2JP:besc3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3749055e11e7fefb4a31ed9ec9046a856a921207/talpid-core/src/process/openvpn.rs#L236)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This was an arcane bug that I came across when running the daemon as a service on windows - since the parent process has no handles for STDIN/STDERR/STDOUT, the child process can't inherit any. It would work if the standard input handle is not set, but it would fail if it was. And _obviously_,  in this case in order to add one of those handles, you have to add all three. Otherwise, the process would fail to start with errors about how the standard IO handles are not available (which makes sense, since the subprocess will try to inherit them from the parent). I think from now on, all manual testing on Windows will have to be done when the daemon is running as a service. But yes, I could redirect standard error out to a file where we store all the logs.
</blockquote></details>

Do you think it'd be beneficial to detect if the daemon is running as a windows service and only then null out the handles?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[talpid-core/src/process/openvpn.rs, line 236 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LCmZTCQ6WRpF8i8XBPx:-LCn44rGBAaGx8Wym7SU:b-4uilid) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3749055e11e7fefb4a31ed9ec9046a856a921207/talpid-core/src/process/openvpn.rs#L236)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Do you think it'd be beneficial to detect if the daemon is running as a windows service and only then null out the handles?
</blockquote></details>

I see. For me it's fine to always null them out. I don't feel like we need to redirect them to files. As we noticed today, errors are usually GUI dialogs anyway so it would probably not capture a lot. I don't know if it help development to be able to manually run `mullvad-daemon.exe` and see the output? I personally think it's annoying that they are mixed and prefer `tail -f`ing the logfile anyway, but maybe Odd or someone has other opinions.

Since this solves the problem for now let's go with nulling them out. If it hinders development we can do something smarter at a later point.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Reviewed 2 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[talpid-core/src/process/openvpn.rs, line 5 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LD149tuEUXG34UWBjZQ:-LD149tuEUXG34UWBjZR:bu5pa8l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d3452ec2be39fe1bb4b4df4beadce06f08db914d/talpid-core/src/process/openvpn.rs#L5)):*
> ```Rust
> extern crate os_pipe;
> #[cfg(windows)]
> extern crate winapi;
> ```

I don't think you are using this any longer and can remove it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[talpid-core/src/process/openvpn.rs, line 5 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LD149tuEUXG34UWBjZQ:-LD1EXN32hOizOU1A0Eu:b-o1cujt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d3452ec2be39fe1bb4b4df4beadce06f08db914d/talpid-core/src/process/openvpn.rs#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think you are using this any longer and can remove it?
</blockquote></details>

You are correct, removed it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Cargo.lock, line 1385 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LD1PZrM28GkzCDlwdm5:-LD1PZrM28GkzCDlwdm6:b-mjl1ha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a38d763bba1e57816766d8d509261d82ec08ef34/Cargo.lock#L1385)):*
> ```TOML
>  "uuid 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)",
>  "widestring 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)",
>  "winapi 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)",
> ```

You need to perform at least a `cargo build` in order for this to go away.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Cargo.lock, line 1385 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-LD1PZrM28GkzCDlwdm5:-LD61T9-E9Moo6FCslRm:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a38d763bba1e57816766d8d509261d82ec08ef34/Cargo.lock#L1385)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You need to perform at least a `cargo build` in order for this to go away.
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169#-:-LD62cTz25s1OCE2UHRM:bnfp4nl)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/169)*

**Pull request merged**
