### PR TITLE
Add packet capturing to iOS test router service

### PR DESCRIPTION
**Pull request by dlon**
Close IOS-443.

This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877)

### CODE REVIEW

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877#-:-NromH8y7_VeRcg_63Nq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`ci/ios/test-router/raas/src/capture/mod.rs` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877#-NrozPCh6SpanSRQMs1D:-NrozPCh6SpanSRQMs1E:b-u2bqp8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcdbe8ceb372029a0e147ee7cd0375eb3ca901f1/ci/ios/test-router/raas/src/capture/mod.rs#L77)):*
> ```XML
>             .map_err(Error::EnableNonblock)?;
> 
>         // TODO: limit snaplen?
> ```

Should be removed?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @niklasberglund)

___
*[`ci/ios/test-router/raas/src/capture/mod.rs` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877#-NrozPCh6SpanSRQMs1D:-NrpbNhvCF0cpXQQql0L:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcdbe8ceb372029a0e147ee7cd0375eb3ca901f1/ci/ios/test-router/raas/src/capture/mod.rs#L77)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Should be removed?
</blockquote></details>

Done.

**Review by niklasberglund — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877#-:-NrpcrIv7Ze1AZyaLJBm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
