### PR TITLE
Add iOS buildscript for CI

### PR DESCRIPTION
**Pull request by pinkisemils**
Adding an iOS buildscript. It keeps track of 2 build artifacts - the commit and the version of a build.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/buildserver-build-ios.sh` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSKKXb2CGdCWHXg0om:-NPSKKXb2CGdCWHXg0on:bpiaabj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L54)):*
> ```Shell
>     fi
> 
>     bash "$BUILD_DIR"/build.sh --deploy
> ```

We usually don't prefix with `bash` when invoking other helper-scripts in our build scripts.
___
*[`ci/buildserver-build-ios.sh` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJ7o0EH2s3XjwNOeO:-NPSJ7o0EH2s3XjwNOeP:bja9y6m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L67)):*
> ```Shell
> 
> build_loop() {
>     cd "$BUILD_DIR"
> ```

Is there a technical reason you need to do this in the loop? In the other scripts (which I think we should be as consistent as possible with) we don't do this corresponding `cd` in the loop.
___
*[`ci/buildserver-build-ios.sh` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJJKL07XcJSevVFvw:-NPSJJKL07XcJSevVFvx:bpteai9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L69)):*
> ```Shell
>     cd "$BUILD_DIR"
>     while true; do
>       # Delete all tags. So when fetching we only get the ones existing on the remote
> ```

Indentation. I just fixed all existing build scripts to finally be consistent 4 space indented just a few days ago. Let's not break that again please :sweat_smile: 
___
*[`ci/buildserver-build-ios.sh` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSK2npDncPmZhlzRUl:-NPSK2npDncPmZhlzRUm:b-oqo0ns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L76)):*
> ```Shell
> 
>       for tag in "${tags[@]}"; do
>         build_ref "refs/tags/$tag" "$tag"
> ```

You pass two arguments, but `build_ref` never references `$2`
___
*[`ci/buildserver-build-ios.sh` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJUEq2VKPXsQ_aujF:-NPSJUErCGCCqD_8VnCA:b1eonnt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L83)):*
> ```Shell
> }
> 
> build_loop
> ```

Not going to block the PR on this, it's a bit nitpicky. But I don't see why this needs to be a function when it's not in the other build scripts. Just "costs" an extra indent level IMO.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/buildserver-build-ios.sh` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSM4Z_DuXt7mUYzlQB:-NPSM4Z_DuXt7mUYzlQC:b2cfkp3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L15)):*
> ```Shell
>     local ref=$1;
>     local current_hash="";
>     if ! current_hash=$(git rev-parse "$ref"); then
> ```

Consider adding `^{commit}` like we do in all other invocations to `rev-parse`. Otherwise git is not guaranteed to return a commit hash. It can under some circumstances return something else. I can't fully remember when or what.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/buildserver-build-ios.sh` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSNjeF4ftq-KkuBBGr:-NPSNjeF4ftq-KkuBBGs:b-arc2xh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L60)):*
> ```Shell
> read_app_version() {
>     project_version=$(sed -n "s/CURRENT_PROJECT_VERSION = \([[:digit:]]\)/\1/p" ios/Configurations/Version.xcconfig)
>     marketing_version=$(sed -n "s/MARKETING_VERSION = \([[:digit:]]\)/\1/p" ios/Configurations/Version.xcconfig)
> ```

Should the paths here really start with `ios/`? We do `cd $BUILD_DIR` so I think this code will be executed inside the `ios` dir already?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/buildserver-build-ios.sh` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSOrJH9fa4qbI1Ujnv:-NPSOrJH9fa4qbI1Ujnw:b-he3dyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L46)):*
> ```Shell
>     echo "[#] $ref: $app_build_version $current_hash, building new packages."
> 
>     if ! git verify-tag "$ref"; then
> ```

Since `$ref` must be a tag, I think it would be clearer to name it `tag`

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/buildserver-build-ios.sh` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSP1sm4SEOkHeLviUM:-NPSP1sm4SEOkHeLviUN:bnbb7lw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L39)):*
> ```Shell
>         echo "[#] App version already built in commit $(cat "${LAST_BUILT_DIR}/build-${app_build_version}")"
>         echo "[#] The build version in ios/Configuration/Version.xcconfig should be bumped."
>         echo "!!!"
> ```

This check is smart! But similar to the GPG verification below I think this would benefit from a `sleep 60` or similar. Since the message is intended for a build server sysadmin. And with no delay they might easily miss this. And to avoid a too tight build loop if it ever happens.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`ci/buildserver-build-ios.sh` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSM4Z_DuXt7mUYzlQB:-NPSOxBKAYlhoo5qFlXs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Consider adding `^{commit}` like we do in all other invocations to `rev-parse`. Otherwise git is not guaranteed to return a commit hash. It can under some circumstances return something else. I can't fully remember when or what.
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSP1sm4SEOkHeLviUM:-NPSeBWhEdtvtg1yomAZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L39)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This check is smart! But similar to the GPG verification below I think this would benefit from a `sleep 60` or similar. Since the message is intended for a build server sysadmin. And with no delay they might easily miss this. And to avoid a too tight build loop if it ever happens.
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSOrJH9fa4qbI1Ujnv:-NPSPNTQAngEj1iu1VIT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since `$ref` must be a tag, I think it would be clearer to name it `tag`
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSKKXb2CGdCWHXg0om:-NPSPMIuBV-DhRHYGxFy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L54)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We usually don't prefix with `bash` when invoking other helper-scripts in our build scripts.
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSNjeF4ftq-KkuBBGr:-NPSPLmNEJWxQq-Gypkv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Should the paths here really start with `ios/`? We do `cd $BUILD_DIR` so I think this code will be executed inside the `ios` dir already?
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJ7o0EH2s3XjwNOeO:-NPSPrGsDHHIlOq-ToAn:b-xc1kc9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L67)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is there a technical reason you need to do this in the loop? In the other scripts (which I think we should be as consistent as possible with) we don't do this corresponding `cd` in the loop.
</blockquote></details>

The `cd` takes place outside of the loop.
___
*[`ci/buildserver-build-ios.sh` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJJKL07XcJSevVFvw:-NPSPmzCAuwO7mAkHF1U:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L69)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Indentation. I just fixed all existing build scripts to finally be consistent 4 space indented just a few days ago. Let's not break that again please :sweat_smile: 
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSK2npDncPmZhlzRUl:-NPSPma2CjhzFXimvnFT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L76)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You pass two arguments, but `build_ref` never references `$2`
</blockquote></details>

Done.
___
*[`ci/buildserver-build-ios.sh` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJUEq2VKPXsQ_aujF:-NPSPS4BDdbvh0ds_-y1:btufw2q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L83)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not going to block the PR on this, it's a bit nitpicky. But I don't see why this needs to be a function when it's not in the other build scripts. Just "costs" an extra indent level IMO.
</blockquote></details>

It's easier to comment out a single line and test out parts of the script during development. I can change it later.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ci/buildserver-build-ios.sh` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402#-NPSJ7o0EH2s3XjwNOeO:-NPY0xjuBRoUIN7A2Pfc:bwo9ing) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecea7083759be4abeb6e92648876495bb7199557/ci/buildserver-build-ios.sh#L67)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Oh yeah. Why is it in a function named loop then :joy: :shrug: 
</blockquote></details>

Because it's running the build loop. Maybe it should be `run_build_loop`.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4402)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
