### PR TITLE
Add account observer

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR swaps the notification mechanism to observer mechanism we use elsewhere in the codebase and adds two more events to tell when user logs in and out.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654)* status: 0 of 4 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppStorePaymentManager.swift, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654#-MY4qaC2CKvjxagTZSCC:-MY4qaC2CKvjxagTZSCD:bwoo81r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/840674e3585e87e1d1c37d1c9eaf98e511f06bb1/ios/MullvadVPN/AppStorePaymentManager.swift#L52)):*
> ```Swift
> 
> /// A type-erasing weak container for `AppStorePaymentObserver`
> private class AnyAppStorePaymentObserver: AppStorePaymentObserver, WeakObserverBox, Equatable {
> ```

FYI just adds a formal conformance to the protocol that `AnyAppStorePaymentObserver` implements.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654#-:-MYBSJJw3LT4KED5BY4f:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/SettingsViewController.swift, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654#-MYBRbXiEEdu99W41KPJ:-MYBRbXj0HRtg7uwuCgA:b-rwdmrf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff8b8231615f5c39ec38fbd34000c11a0ba6a3c5/ios/MullvadVPN/SettingsViewController.swift#L79)):*
> ```Swift
> 
>     func accountDidLogout(_ account: Account) {
>         // no-op
> ```

Will you handle how logging in and logging out affects the settings screen later? For example, on Android when there is no account logged in we don't show the Account, Preferences or Advanced items.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/MullvadVPN/SettingsViewController.swift, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654#-MYBRbXiEEdu99W41KPJ:-MYJOM8q5vn9j3c0LeZC:bkki6qc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff8b8231615f5c39ec38fbd34000c11a0ba6a3c5/ios/MullvadVPN/SettingsViewController.swift#L79)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Will you handle how logging in and logging out affects the settings screen later? For example, on Android when there is no account logged in we don't show the Account, Preferences or Advanced items.
</blockquote></details>

This is already handled. The UI is configured in `viewDidLoad` and the log out procedure is very much blocking the entire UI after which the Settings controller is dismissed.

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
