### PR TITLE
Add copy icon button account created screen

### PR DESCRIPTION
**Pull request by Rawa**
Add the copy icon to make it clean that the user can copy the account number.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141#-Ne2SCufDLYbdT9fvFhS:-Ne2SCufDLYbdT9fvFhT:b-p7s43e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2574713e6f3a14d11e33a639556ccdb34c0e995/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt#L61)):*
> ```Kotlin
        val copy = {
            context.copyToClipboard(
                content = content,
                clipboardLabel = context.getString(R.string.mullvad_account_number)
            )
            SdkUtils.showCopyToastIfNeeded(
                context,
                context.getString(R.string.copied_mullvad_account_number)
            )
        }
> ```

This lambda should be replaced with the compose style of doing it long-term (`LocalClipboardManager` & `SnackbarHostState` for toast). However, I avoided doing this due to the third-party library used for Collapsible App Bar does not support `Snackbar`.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141#-Neb_aBUDnTT7L_-SFm2:-Neb_aBV7oYdMbuna9F7:bn63jkf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7041c12563ad0c6ca7d30f2123a38ad084ba774/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt#L32)):*
> ```Kotlin
> @Composable
> fun CopyableObfuscationView(content: String) {
>     var shouldObfuscated by remember { mutableStateOf(true) }
> ```

I'm aware that this `var` named was already used before this PR, but would be nice to improve/clarfiy it



_Code quote:_
```Kotlin
shouldObfuscated
```

**Review by Pururun — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
