### PR TITLE
Use Shadowsocks library instead of launching a subprocess

### PR DESCRIPTION
**Pull request by dlon**
This updates the Shadowsocks proxy monitor to use the crates instead of launching a subprocess, and removes all related binaries and references to them. It also contains some refactoring of the OpenVPN monitor.

Related PR: https://github.com/mullvad/mullvadvpn-app-binaries/pull/93

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 10 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: 10 of 14 files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 318 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474#-MzZzaKE-o_cTvWYYcPc:-MzZzaKE-o_cTvWYYcPd:b-a3xyi7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9313e9de5c4be2360cad84c2fbe668ada7f4bdab/talpid-core/src/tunnel/openvpn/mod.rs#L318)):*
> ```XML
> 
>         let handle = runtime.handle().clone();
>         handle.block_on(Self::new_internal_with_runtime(
> ```

This seems sketchy in retrospect: `runtime_handle.block_on(f(runtime))`. This task itself will still exist when the runtime is dropped. It works, but it could be cleaner.

I think we should have a `TunnelMonitor` trait with async start and wait methods. But I don't want to make a bunch of unrelated changes here.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/tunnel/mod.rs, line 160 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474#-Mza5x3c7fHIyWhvrlgK:-Mza5x3c7fHIyWhvrlgL:bbo3c4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/099c3648413646e5bdc9717b40c60197b4171ae9/talpid-core/src/tunnel/mod.rs#L160)):*
> ```XML
>                     match proxy {
>                         openvpn_types::ProxySettings::Shadowsocks(..) => {
>                             return std::env::current_exe().unwrap()
> ```

Is this necessary on anything besides Windows? It's still good to have this interface, but if I understand this correctly, the only reason the path for the path to exist is to let the firewall exclude the traffic, right?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/mod.rs, line 160 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474#-Mza5x3c7fHIyWhvrlgK:-MzndcSw5nV30bBBOf1w:b3b04ez) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/099c3648413646e5bdc9717b40c60197b4171ae9/talpid-core/src/tunnel/mod.rs#L160)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this necessary on anything besides Windows? It's still good to have this interface, but if I understand this correctly, the only reason the path for the path to exist is to let the firewall exclude the traffic, right?
</blockquote></details>

What changes are you proposing? This is still needed to decide whether `openvpn.exe` or `mullvad-daemon.exe` should be allowed to talk to the first hop.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/mod.rs, line 160 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474#-Mza5x3c7fHIyWhvrlgK:-Mznrtj8AeyeUeThCum9:b-xtqox1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/099c3648413646e5bdc9717b40c60197b4171ae9/talpid-core/src/tunnel/mod.rs#L160)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

What changes are you proposing? This is still needed to decide whether `openvpn.exe` or `mullvad-daemon.exe` should be allowed to talk to the first hop.
</blockquote></details>

Since it's still useful, then I propose that the current code is plenty good enough.
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 318 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474#-MzZzaKE-o_cTvWYYcPc:-MzokDtiEHCEzyqJ9giZ:bzfc83v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9313e9de5c4be2360cad84c2fbe668ada7f4bdab/talpid-core/src/tunnel/openvpn/mod.rs#L318)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This seems sketchy in retrospect: `runtime_handle.block_on(f(runtime))`. This task itself will still exist when the runtime is dropped. It works, but it could be cleaner.

I think we should have a `TunnelMonitor` trait with async start and wait methods. But I don't want to make a bunch of unrelated changes here.
</blockquote></details>

Making it async would be better.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474#-:-MztDN9E7p-RQQC-gbo3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
