### PR TITLE
Do not warn users about multihop extra latency, add info button instead

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR changes the UI behaviour to remove the alert when enabling multihop, for a less disruptive experience.
Instead, an info button is added next to the setting name that indicates what the option does.

This PR also orders by name the `Pages` UITest subfolder.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535)

### CODE REVIEW

**Review by acb-mv — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535#-O2yvy3Z0C5gL8BsnowZ:-O2yvy3Z0C5gL8Bsnow_:bwemgow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0b744dcbe34d07aaaf414db185ee2175eb79c87/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L183)):*
> ```Swift
>                 "MULTIHOP_INFORMATION_TEXT",
>                 tableName: "Multihop",
>                 value: "This setting increases latency. Use only if needed.",
> ```

Is this the final copy?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535#-O2yvy3Z0C5gL8BsnowZ:-O3-3y5q7P0-v_Q9ERoI:b-wc0bhk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0b744dcbe34d07aaaf414db185ee2175eb79c87/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L183)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Is this the final copy?
</blockquote></details>

It is for now. We can improve it, but we currently don't need to change it, because it's the exact same text we're already showing.

**Review by acb-mv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535)* status: 7 of 8 files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
