### PR TITLE
Use netlink for connectivity checking

### PR DESCRIPTION
**Pull request by dlon**
One of the connectivity checker implementations uses D-Bus to check whether any traffic has been sent or received on the tunnel interface. This is preferentially used when setting up the kernel implementation of the WG tunnel.

At least one user has found that these D-Bus requests may time out and cause disconnects (apparently randomly). It isn't clear why this occurs, but it is possible that the time out is simply too ruthless on some slow systems. There should be no harm in giving the request more time to obtain the information. That is what this PR does.

```
[talpid_core::tunnel::wireguard::network_manager][ERROR] Failed to read tunnel stats from NM: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
[talpid_core::tunnel::wireguard][ERROR] Error: Connectivity monitor failed
```

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/tunnel/wireguard/network_manager.rs, line 369 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238#-MLIDjBI3bq7uqV87Kjy:-MLIDjBI3bq7uqV87Kjz:b-a3hovr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4fca1b397e745d7829b7c9fa55bac6bed777733/talpid-core/src/tunnel/wireguard/network_manager.rs#L369)):*
> ```Rust
>     }
> 
>     fn get_tunnel_stats(&self) -> std::result::Result<Stats, TunnelError> {
> ```

This should be updated to rely on netlink instead.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)* status: 0 of 4 files reviewed, all discussions resolved

___
*[talpid-core/src/tunnel/wireguard/network_manager.rs, line 369 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238#-MLIDjBI3bq7uqV87Kjy:-MLJ5hdy4uIkU2u4-OxT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4fca1b397e745d7829b7c9fa55bac6bed777733/talpid-core/src/tunnel/wireguard/network_manager.rs#L369)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should be updated to rely on netlink instead.
</blockquote></details>

Done.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/nm_tunnel.rs, line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238#-MLMteRs7zuJlYKLCHJy:-MLMteRs7zuJlYKLCHJz:b-43w0iv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cd89daff04d7e017435b6b61069cd21d54a27694/talpid-core/src/tunnel/wireguard/wireguard_kernel/nm_tunnel.rs#L2)):*
> ```Rust
> use super::{
>     super::stats::Stats, wg_message::DeviceNla, Config, Error, Handle, Tunnel, TunnelError,
> ```

The `Error` import could be renamed

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/nm_tunnel.rs, line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238#-MLMteRs7zuJlYKLCHJy:-MLN4PyKC8AhHrcjYQSy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cd89daff04d7e017435b6b61069cd21d54a27694/talpid-core/src/tunnel/wireguard/wireguard_kernel/nm_tunnel.rs#L2)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The `Error` import could be renamed 
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2238)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
