### PR TITLE
Upload instrumentation report regardless if tests failed

### PR DESCRIPTION
**Pull request by niklasberglund**
Upload instrumentation test report no matter whether tests failed or ran successfully. Before it not uploaded if tests fail because by default a step's `if` have a `successful()` condition steps following a failing test not to run.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`.github/workflows/android-app.yml` line 480 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071#-OAH8qfA3uOkNYM5vzRV:-OAH8qfA3uOkNYM5vzRW:b-wt23hs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c888ec711a43c1275db8f39cf7aa7a1601960278/.github/workflows/android-app.yml#L480)):*
> ```YAML
>       - name: Upload instrumentation report (${{ matrix.test-type }})
>         uses: actions/upload-artifact@v4
>         if: always() && matrix.test-repeat != 0
> ```

What is `always()`, just `true`? I don't follow how this change aligns with the name of the PR.

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`.github/workflows/android-app.yml` line 480 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071#-OAH8qfA3uOkNYM5vzRV:-OBz3K8h7qonDo1UEmlo:bmtibyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c888ec711a43c1275db8f39cf7aa7a1601960278/.github/workflows/android-app.yml#L480)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

What is `always()`, just `true`? I don't follow how this change aligns with the name of the PR.
</blockquote></details>

GitHub Actions does some magic with status checks in `if` conditions. If no status check is specified it will default to `success()` and the the step will only run if previous steps are successful. With `always()` this step will run even if previous steps failed. 

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/android-app.yml` line 480 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071#-OAH8qfA3uOkNYM5vzRV:-OC83cix35EqDJOoZaSg:b44u3f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c888ec711a43c1275db8f39cf7aa7a1601960278/.github/workflows/android-app.yml#L480)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

GitHub Actions does some magic with status checks in `if` conditions. If no status check is specified it will default to `success()` and the the step will only run if previous steps are successful. With `always()` this step will run even if previous steps failed. 

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions
</blockquote></details>

😳

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
