### PR TITLE
Add extra metadata to problem reports on Linux

### PR DESCRIPTION
**Pull request by pinkisemils**
To better aid us with understanding what goes wrong on Linux, we should add more metadata to our problem reports about which specific version of NetworkManager, WireGuard, and the Linux kernel is being used on a given machine. I've also added SystemD's version given that the daemon relies on systemd-resolved for managing DNS. Since NetworkManager's version is acquired via DBus, some slight refactoring had to be done to move out the DBus code into it's own module so that `mullvad-problem-report` doesn't end up depending on `talpid-core`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-dbus/Cargo.toml, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQWIFDT81zShSDboKUk:-MQWIFDT81zShSDboKUl:b-oe8kgo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a8d38c766922ee30fe65e3ec9b59ea93aa670f/talpid-dbus/Cargo.toml#L5)):*
> ```TOML
> version = "0.1.0"
> authors = ["Emīls <emils@mullvad.net>"]
> edition = "2018"
> ```

Fix the metadata to be consistent with the other crates. Disallowing publishing, setting the authors etc.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: 11 of 18 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-dbus/src/network_manager.rs, line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQXa60B57y9-BstNUc_:-MQXa60C8cVZvZ8ijT7K:bchsa1p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d9e1d346fe66e3f35adcfe2fc985d4edcc7dcee/talpid-dbus/src/network_manager.rs#L2)):*
> ```Rust
> //! NetworkManager is the one-stop-shop of network configuration on Linux.
> pub use dbus::arg::{RefArg, Variant};
> ```

There is already a `pub use dbus` in `lib.rs`. Does it make consuming this much easier by having both these somewhat redundant re-exports? Settling for one might make the public API more approachable?

**Review by faern — COMMENTED** [review]
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: 13 of 18 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: 12 of 18 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[talpid-dbus/Cargo.toml, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQWIFDT81zShSDboKUk:-MQXobBY663derPGP144:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2a8d38c766922ee30fe65e3ec9b59ea93aa670f/talpid-dbus/Cargo.toml#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Fix the metadata to be consistent with the other crates. Disallowing publishing, setting the authors etc.
</blockquote></details>

Done.
___
*[talpid-dbus/src/network_manager.rs, line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQXa60B57y9-BstNUc_:-MQXnw7d6XH3JTUjLM0i:b1wvyro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d9e1d346fe66e3f35adcfe2fc985d4edcc7dcee/talpid-dbus/src/network_manager.rs#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

There is already a `pub use dbus` in `lib.rs`. Does it make consuming this much easier by having both these somewhat redundant re-exports? Settling for one might make the public API more approachable?
</blockquote></details>

It does, given that `RefArg` and `Variant` are the only types that are required to use the NetworkManager bit of this crate, whereas the other export just exposes the whole `dbus` crate so that only a single crate needs to depend on `dbus` . I don't think having 2 re-exports, one being specific to  `NetworkManager` makes this really terrible.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: 15 of 18 files reviewed, 5 unresolved discussions (waiting on @pinkisemils)

___
*[env.sh, line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlwaURB9HyPEntU-RG:-MQlwaUS7JKDj5Q7uN0t:b2nb1ij) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L5)):*
> ```Shell
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> 
> export RUST_BUILD_PACKAGES=(
> ```

I think we should use `CRATES` instead of `PACKAGES`. A bit nitpicky, but I think it can help understanding.
___
*[env.sh, line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlwrCUCZoBo3Hg_jxn:-MQlwrCVDKS2WiaIAWNu:bqofqbt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L5)):*
> ```Shell
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> 
> export RUST_BUILD_PACKAGES=(
> ```

This constant is only used in one place. Can we `local` it inside `rust_build_package_args` to better show what it's for/where it's used?
___
*[env.sh, line 18 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQm1A8s9W_71gUnBHHA:-MQm1A8s9W_71gUnBHHB:b-f5257d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L18)):*
> ```Shell
> 
> 
> function rust_build_package_args {
> ```

`rust_package_args` vs `rust_build_package_args` don't immediately tell me very clearly which one does what. Maybe name the former `crates_to_cargo_args`?
___
*[env.sh, line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlxmBeCsV_B092um1a:-MQlxmBeCsV_B092um1b:b-r8iemu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L23)):*
> ```Shell
> 
> function rust_testable_packages {
>     local ALL_RUST_PACKAGES=$( cd $SCRIPT_DIR; (for manifest in $(ls */Cargo.toml android/*/Cargo.toml); do basename $(dirname $manifest); done) )
> ```

The intention of this is to avoid having to specify a manual list of crates to test. In order to have less manual stuff to maintain, and forget updating. The problem is that this automation will miss any crate not placed in these two locations specified. So the automated solution still has a hardcoded list that might have to be updated. So it will work automatically *sometimes*. I think this risks causing problems easier than the other solution.

Another benefit of a plain manual list is that it's very easy to read and understand, and to grep for in code searches.

I'm not sure which is best. Since the automated solution has flaws I think I'm leaning towards the simplest and clearest solution :thinking: 
___
*[ci/ci-rust-script.sh, line 40 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlx2sl221OpH7eUUeY:-MQlx2sl221OpH7eUUeZ:b-k16374) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/ci/ci-rust-script.sh#L40)):*
> ```Shell
> 
> time cargo build --locked --verbose $(rust_build_package_args)
> time cargo test --locked --verbose $(rust_package_args $(rust_testable_packages))
> ```

It's quite asymmetrical that for testable packages you have to build the argument list yourself but for the build packages you get that done for you with a function. If we go with the testable-style solution we can get rid of `rust_build_packade_args` completely and have one function less.

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: all files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-dbus/src/network_manager.rs, line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQmEe474YpD-QmBtLi5:-MQmEe480AsWg-Tlr9n2:b5kddgn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/talpid-dbus/src/network_manager.rs#L196)):*
> ```Rust
>         let minor_version: u32 = parts.next().ok_or_else(|| version_too_old())??;
> 
>         if major_version < MINIMUM_SUPPORTED_MAJOR_VERSION
> ```

This considers the version to be too old if `major > MINIMUM_SUPPORTED_MAJOR_VERSION` and `minor < MINIMUM_SUPPORTED_MINOR_VERSION`.

**Review by faern — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[env.sh, line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlwrCUCZoBo3Hg_jxn:-MQmEbHG0TIVDzKFPP57:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This constant is only used in one place. Can we `local` it inside `rust_build_package_args` to better show what it's for/where it's used?
</blockquote></details>

Done.
___
*[env.sh, line 18 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQm1A8s9W_71gUnBHHA:-MQmADt7A29_3xDqB7Zy:bpqpg3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`rust_package_args` vs `rust_build_package_args` don't immediately tell me very clearly which one does what. Maybe name the former `crates_to_cargo_args`?
</blockquote></details>

The reason _package_ permeate all the variable names is because the `-p` in `cargo build -p` is short for `--package`.   
___
*[env.sh, line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlxmBeCsV_B092um1a:-MQmEBSyBA5db_0YUWNo:bzh45uc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L23)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

To help with updating it would not hurt with a comment in the top `Cargo.toml` saying that if any crate is added to the workspace, one should make sure to update `RUST_BUILD_CRATES` and `RUST_TEST_CRATES` accordingly
</blockquote></details>

It's not just `RUST_TEST_CRATES`, it'd be a base list of creates that is filtered for different platforms, and exclusions for different platforms. Or two separate lists, one for Linux, and one for others.

For now, I've just made the code compile on all platforms and removed all the bash/CI changes for simplicity's sake. I think the hard mistake that I committed (and committed to it too) is expecting a collection of bash scripts would be the ideal platform for implementing a build system - because that's what I ended up doing anyway. The final version of this used `find` instead of `ls`, and filtered out definitely wrong crates (for now just dist-assets), and that might work automagickally, but I wholeheartedly agree that it isn't readable.
___
*[talpid-dbus/src/network_manager.rs, line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQmEe474YpD-QmBtLi5:-MQo0NTuAFiSdeJSYyUP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/talpid-dbus/src/network_manager.rs#L196)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This considers the version to be too old if `major > MINIMUM_SUPPORTED_MAJOR_VERSION` and `minor < MINIMUM_SUPPORTED_MINOR_VERSION`.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[env.sh, line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2380#-MQlxmBeCsV_B092um1a:-MQqDeDA16mOJnTT7H7H:b-cyej6p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639dbab3be9cfedd9e91d02549d08b33c7c1c7be/env.sh#L23)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It's not just `RUST_TEST_CRATES`, it'd be a base list of creates that is filtered for different platforms, and exclusions for different platforms. Or two separate lists, one for Linux, and one for others.

For now, I've just made the code compile on all platforms and removed all the bash/CI changes for simplicity's sake. I think the hard mistake that I committed (and committed to it too) is expecting a collection of bash scripts would be the ideal platform for implementing a build system - because that's what I ended up doing anyway. The final version of this used `find` instead of `ls`, and filtered out definitely wrong crates (for now just dist-assets), and that might work automagickally, but I wholeheartedly agree that it isn't readable.
</blockquote></details>

Yes it would be a `case` statement with one `RUST_TEST_CRATES` per platform. But still just a plain list of lists and no logic.

**Pull request merged**
