### PR TITLE
Integrate WireGuardKit

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR migrates iOS app to WireGuardKit:

1. Replace `WireguardPrivateKey`, `WireguardPublicKey` with `PrivateKey` and `PublicKey` from WireGuardKit
2. Remove `IPAddressRange` in favour of the implementation from WireGuardKit
3. Remove wireguard-go from our repo

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448)

### CODE REVIEW

**Comment by jvff** [comment]
___
*[ios/MullvadVPN/AutomaticKeyRotationManager.swift, line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448#-MT6V1Pb0u06gSgMOge-:-MT6V1Pb0u06gSgMOge0:b-3co37s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af3bbc59f4ffa61c89a4b313bb8949ea01c26cee/ios/MullvadVPN/AutomaticKeyRotationManager.swift#L22)):*
> ```Swift
> struct KeyRotationResult {
>     var isNew: Bool
>     var publicKeyWithMetadata: PublicKeyWithMetadata
> ```

Nit: Would it make sense to call this just `publicKey`?

**Review by jvff — APPROVED** [review]
> Reviewed 34 of 34 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/MullvadVPN/AutomaticKeyRotationManager.swift, line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448#-MT6V1Pb0u06gSgMOge-:-MTAGesp63u3Ox3fVQHb:b-ykakgv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af3bbc59f4ffa61c89a4b313bb8949ea01c26cee/ios/MullvadVPN/AutomaticKeyRotationManager.swift#L22)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Would it make sense to call this just `publicKey`?
</blockquote></details>

I know it's verbose but it does reflect the pair or pubkey + metadata vs. just pubkey or metadata.

**Review by jvff — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448#-:-MTBADbp5941OLj0oCuv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2448)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
