### PR TITLE
Create separate crate for Mullvad RPC client

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Internal refactor, not user visible.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[mullvad-ipc-client/Cargo.toml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB50aW2AxCB-g4rNd91:-LB50aW2AxCB-g4rNd92:b-nbr90d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/Cargo.toml#L4)):*
> ```TOML
> name = "mullvad-ipc-client"
> version = "0.1.0"
> authors = ["Janito Vaqueiro Ferreira Filho <janito@mullvad.net>"]
> ```

Please always have `"Mullvad VPN <admin@mullvad.net>"` as the first author, like in the other crates.

Also add `license = "GPL-3.0"` so we have the correct license metadata for the entire product.

---

*[mullvad-ipc-client/src/lib.rs, line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB54qgp8Y3Kcs4HxS6H:-LB54qgp8Y3Kcs4HxS6I:b-jh33jc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L99)):*
> ```Rust
>             .next()
>             .ok_or_else(|| ErrorKind::EmptyRpcFile(file_path.display().to_string()))?
>             .chain_err(|| ErrorKind::ReadRpcFileError(file_path.display().to_string()))
> ```

Really nice that you put work into error handling. I would however argue that having fewer error types would also be fine and simpler. Since we have the chain of errors, the cause of the error will tell us more in detail what happened. Would we thus lose anything from combining for example the open and read error types? Failing to open the file is a failure to read it IMO and the cause will tell us which one it is.

---

*[mullvad-ipc-client/src/lib.rs, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB56T-GBCJNTXmortAF:-LB56T-I9Qk4g9X5002T:bclgh71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L103)):*
> ```Rust
> 
>     pub fn connect(&self) -> Result<()> {
>         self.call("connect", &NO_ARGS)
> ```

Really nice to finally get these calls as Rust methods that hide the ugly RPC call :P :+1:

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by jvff** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[mullvad-ipc-client/Cargo.toml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB50aW2AxCB-g4rNd91:-LB5XR-y5hOLcDX4uK4E:b-vicsok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/Cargo.toml#L4)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please always have `"Mullvad VPN <admin@mullvad.net>"` as the first author, like in the other crates.

Also add `license = "GPL-3.0"` so we have the correct license metadata for the entire product.
</blockquote></details>

Done. Sorry, I just used the metadata generated by `cargo init` :/

I also added a short description now.

---

*[mullvad-ipc-client/src/lib.rs, line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB54qgp8Y3Kcs4HxS6H:-LB5XmNa0Ht_qDjHmwSk:b-h38zyn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L99)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Really nice that you put work into error handling. I would however argue that having fewer error types would also be fine and simpler. Since we have the chain of errors, the cause of the error will tell us more in detail what happened. Would we thus lose anything from combining for example the open and read error types? Failing to open the file is a failure to read it IMO and the cause will tell us which one it is.
</blockquote></details>

Done.

I also did a small refactor, creating a closure to reduce the repeated code to get the file path string. Let me know if you think this makes the code easier to read, otherwise I'll return it to how it was.

---

*[mullvad-ipc-client/src/lib.rs, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB56T-GBCJNTXmortAF:-LB5Y_j9BYNeafv-8l5b:b-1ezawn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L103)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Really nice to finally get these calls as Rust methods that hide the ugly RPC call :P :+1:
</blockquote></details>

I also wrote a macro to generate the boilerplate code in these cases, but I'm not sure it lead to an improvement. I didn't include it in this PR, but I left it as a separate PR so that it can be reviewed separately.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by pinkisemils** [comment]
Reviewed 6 of 7 files at r1, 1 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB5j_CWAW7Ywy3raoog:b-lwew7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
> ```Rust
>     use super::*;
> 
>     pub fn rpc_file_path() -> Result<PathBuf> {
> ```

This might be more work to extract common stuff but I'd rather see this kind of code shared between the daemon and the client.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by jvff** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB5mMQo4iF3YsjIRZzv:bvqv9xx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This might be more work to extract common stuff but I'd rather see this kind of code shared between the daemon and the client.
</blockquote></details>

Good idea. I'm not sure what would be the best approach, though. Since another PR will make `mullvad-daemon` use the `DaemonRpcClient` from this new crate to try to connect to another running instance of the daemon, I think it's probably better to have the `rpc_file_path` function here, and use it in `mullvad-daemon`? If that's the case, then the integration will be in the other PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB5pVoC7UgIK5NrR1ei:bq791u5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Good idea. I'm not sure what would be the best approach, though. Since another PR will make `mullvad-daemon` use the `DaemonRpcClient` from this new crate to try to connect to another running instance of the daemon, I think it's probably better to have the `rpc_file_path` function here, and use it in `mullvad-daemon`? If that's the case, then the integration will be in the other PR.
</blockquote></details>

Hence it'd be more work - it'd have to be a separate crate. Thinking of it as a dependency graph, I definitely don't think that the daemon _should_ depend on the CLI, but that would be exactly what'd happen if it were importing this function. In actuality, I don't think it's that critical for now, but this is just something to be aware of going forward. So maybe this can stay the way it is and in the future it could be consolidated in a separate module/crate. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by jvff** [comment]
*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB5qlAx22_FCxuIkrKH:b-8gm94o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Hence it'd be more work - it'd have to be a separate crate. Thinking of it as a dependency graph, I definitely don't think that the daemon _should_ depend on the CLI, but that would be exactly what'd happen if it were importing this function. In actuality, I don't think it's that critical for now, but this is just something to be aware of going forward. So maybe this can stay the way it is and in the future it could be consolidated in a separate module/crate. 
</blockquote></details>

I'm not sure I understand. Maybe we're using the same terms for different things, but this is the separate crate with client-RPC-stuff. `mullvad-cli` hasn't been touched yet, but it will also use this new crate. And `mullvad-daemon` will also use this new crate, so I think it can also import the function defined here.

Or did you mean moving the function somewhere else?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB5sNFr8Nxn_IsF02Ql:b-glxink) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm not sure I understand. Maybe we're using the same terms for different things, but this is the separate crate with client-RPC-stuff. `mullvad-cli` hasn't been touched yet, but it will also use this new crate. And `mullvad-daemon` will also use this new crate, so I think it can also import the function defined here.

Or did you mean moving the function somewhere else?
</blockquote></details>

Nope, I had it wrong. Having a separate client-rpc crate would be ideal, yes. I guess when that is introduced, you can remove the function from here. Sorry for the confusion :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by faern** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[mullvad-ipc-client/Cargo.toml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB50aW2AxCB-g4rNd91:-LB5znxo4ZP0TFiPYS5b:b-e4e7xg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/Cargo.toml#L4)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. Sorry, I just used the metadata generated by `cargo init` :/

I also added a short description now.
</blockquote></details>

Awesome :+1:

---

*[mullvad-ipc-client/src/lib.rs, line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB54qgp8Y3Kcs4HxS6H:-LB60EPX3bAgOnDiCBm0:bge04uk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L99)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.

I also did a small refactor, creating a closure to reduce the repeated code to get the file path string. Let me know if you think this makes the code easier to read, otherwise I'll return it to how it was.
</blockquote></details>

This is fine I think :+1: Having the closure is maybe a tiny bit harder to understand, but it's a very isolated place as well so completely fine :)

---

*[mullvad-ipc-client/src/lib.rs, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB56T-GBCJNTXmortAF:-LB6-KO38E96_aR_-evO:b-ln84qp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L103)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I also wrote a macro to generate the boilerplate code in these cases, but I'm not sure it lead to an improvement. I didn't include it in this PR, but I left it as a separate PR so that it can be reviewed separately.
</blockquote></details>

Ok. Spontaneously this looks simple enough. But I have not seen the macro code so can't comment, just thinking that macros can at times make it more complex to read as well.

---

*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB6-uXD8NhwXpA9j_2E:b-jzrgwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Nope, I had it wrong. Having a separate client-rpc crate would be ideal, yes. I guess when that is introduced, you can remove the function from here. Sorry for the confusion :)
</blockquote></details>

Isn't this crate that separate crate you are talking about? I felt the entire purpose of this crate was to let everyone reach one implementation of `rpc_file_path` as well as checking the permissions on that file.

Plus the RPC client itself as well, but that is used by a bit fewer parts later.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by jvff** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[mullvad-ipc-client/src/lib.rs, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB56T-GBCJNTXmortAF:-LB6LJdPEihP5SmoBUS_:b-6nr27e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L103)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ok. Spontaneously this looks simple enough. But I have not seen the macro code so can't comment, just thinking that macros can at times make it more complex to read as well.
</blockquote></details>

Yeah, I agree. I think it became more complex and didn't offer much improvement. We'll see when I open the separate PR.

---

*[mullvad-ipc-client/src/lib.rs, line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146#-LB5j_CWAW7Ywy3raoof:-LB6LAGwEnSiBHdq2Nmo:btih660) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11534b1ded1b149fa375dfdb7f527b462cd2cfe1/mullvad-ipc-client/src/lib.rs#L211)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Isn't this crate that separate crate you are talking about? I felt the entire purpose of this crate was to let everyone reach one implementation of `rpc_file_path` as well as checking the permissions on that file.

Plus the RPC client itself as well, but that is used by a bit fewer parts later.
</blockquote></details>

Yes, exactly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)*

**Pull request merged**
