### PR TITLE
Improve device and key management (Add device concept to daemon + CLI)

### PR DESCRIPTION
**Pull request by dlon**
This PR makes all changes required for handling devices in the daemon and CLI. Some of these changes include:

* Fixing the "too many keys" error. Invalid WireGuard keys are automatically rotated.
* Detecting when a device/key has been revoked or logged out by another device or on the site.
* Adding CLI commands for listing and revoking devices as well as for login and logout.
* Android: Rust-side changes for JNI code and the daemon interface.

Related PR for GUI changes: #3364

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 6 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 6 of 34 files reviewed, all discussions resolved

___
*[mullvad-cli/src/main.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwR5neA7-IHLVS-SupU:-MwR5neA7-IHLVS-SupV:bd8q6co) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-cli/src/main.rs#L54)):*
> ```XML
> 
>     #[error(display = "{}", _0)]
>     Other(&'static str),
> ```

Could this not be a more specific error type? Maybe it doesn't matter since these errors aren't actually returned to any caller.
___
*[mullvad-cli/src/cmds/account.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwR7Izy0GOO3l9BoisQ:-MwR7Izy0GOO3l9BoisR:b-edz9qx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-cli/src/cmds/account.rs#L213)):*
> ```XML
>             .map_err(map_device_error)?
>             .into_inner();
>         let mut device_id = None;
> ```

This could be 
```
let device_id = device_list.devices.find(|dev| dev.name.eq_ignore_ascii_case(&device_to_revoke) || dev.id.eq_ignore_ascii_case(&device_to_revoke)
    .map(|device| device.id)
     .ok_or_else(|| Error::Other(DEVICE_NOT_FOUND_ERROR))?`;
```

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 6 of 34 files reviewed, all discussions resolved

___
*[mullvad-cli/src/cmds/account.rs, line 306 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwR7yMX0I3K1FRqYjrO:-MwR7yMX0I3K1FRqYjrP:b-sy04uf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-cli/src/cmds/account.rs#L306)):*
> ```XML
> }
> 
> fn map_device_error(error: Status) -> Error {
> ```

Maybe there needs to be an account or  device error type? Again, probably a nit pick since these types aren't returned to anyone.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 6 of 34 files reviewed, all discussions resolved

___
*[mullvad-daemon/src/device.rs, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwRF7jf0eWfh920p0TF:-MwRF7jf0eWfh920p0TG:bytsft7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L66)):*
> "Oneshot was unexpectedly cancelled"
This is somewhat non-descript. If I was to read this line in the logs, it wouldn't explain what went wrong.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 7 of 34 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/device.rs, line 801 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwTFq4A0ETJZljp8P4r:-MwTFq4A0ETJZljp8P4s:b-yfvdum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L801)):*
> ```XML
> 
> impl Account {
>     pub fn new(
> ```

This should be a method for `AccountService` and the `Account` type should be removed.  But I think this function deserves to be a standalone function.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 7 of 34 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/device.rs, line 299 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwTJU9b7yZUI887J2_p:-MwTJU9b7yZUI887J2_q:b4ffq70) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L299)):*
> ```XML
>     }
> 
>     pub fn get(&self) -> Option<DeviceData> {
> ```

This function could be called `data` or `device_data`. 
___
*[mullvad-daemon/src/device.rs, line 303 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwTIw9Y89yrmI5j73ut:-MwTIw9Z2KJlrGkhGclh:b-7c0a3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L303)):*
> ```XML
>     }
> 
>     pub fn is_some(&self) -> bool {
> ```

Could be named `has_data` or something clearer.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 7 of 34 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwWAXYaDPyWByF9hpjl:-MwWAXYaDPyWByF9hpjm:b93p4s6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/lib.rs#L226)):*
> ```XML
>     CreateNewAccount(ResponseTx<String, Error>),
>     /// Request the metadata for an account.
>     /// TODO: Remove this? GetDevice?
> ```

If `GetAccountData` and the associated RPC is no longer used, we should remove them.
___
*[mullvad-daemon/src/lib.rs, line 658 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwWAuno1SjmmHB2LhpT:-MwWAuno1SjmmHB2LhpU:b-iva3o9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/lib.rs#L658)):*
> ```XML
>         .await
>         .map_err(Error::LoadAccountManager)?;
>         if let Some(rotation_interval) = settings.tunnel_options.wireguard.rotation_interval {
> ```

Was the plan not to remove the rotation interval setting?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 7 of 34 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-cli/src/cmds/account.rs, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwR7Izy0GOO3l9BoisQ:-MwWyfVL-KXjGD2LuRPu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-cli/src/cmds/account.rs#L213)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This could be 
```
let device_id = device_list.devices.find(|dev| dev.name.eq_ignore_ascii_case(&device_to_revoke) || dev.id.eq_ignore_ascii_case(&device_to_revoke)
    .map(|device| device.id)
     .ok_or_else(|| Error::Other(DEVICE_NOT_FOUND_ERROR))?`;
```

</blockquote></details>

Done.
___
*[mullvad-daemon/src/device.rs, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwRF7jf0eWfh920p0TF:-MwWyjI24O-Pk5QqOzQp:bzhf3eq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L66)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

> "Oneshot was unexpectedly cancelled"
This is somewhat non-descript. If I was to read this line in the logs, it wouldn't explain what went wrong. 
</blockquote></details>

This is supposed to never happen. But I tried to make it more specific.
___
*[mullvad-daemon/src/device.rs, line 299 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwTJU9b7yZUI887J2_p:-MwWyuL91Di8bI3pYLZC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L299)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This function could be called `data` or `device_data`. 
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device.rs, line 303 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwTIw9Y89yrmI5j73ut:-MwWyt3wC1X7aUAJ-vw1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L303)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could be named `has_data` or something clearer.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/lib.rs, line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwWAXYaDPyWByF9hpjl:-MwWYirO-qX9j8qQDNCr:bgqs3a7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/lib.rs#L226)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If `GetAccountData` and the associated RPC is no longer used, we should remove them.
</blockquote></details>

I've removed the comment. Later, if the expiry becomes part of the cache, this RPC could be removed.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 7 of 34 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/device.rs, line 801 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwTFq4A0ETJZljp8P4r:-MwX-lmL3GzRzLJzK6JN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/device.rs#L801)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This should be a method for `AccountService` and the `Account` type should be removed.  But I think this function deserves to be a standalone function.
</blockquote></details>

Done.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 5 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 11 of 34 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 1193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwWB87U1QCKKJDYc-0K:-MwWB87U1QCKKJDYc-0L:b-lbgm9t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/lib.rs#L1193)):*
> ```XML
>                 if self.wg_check_validity && self.wg_retry_attempt % WG_DEVICE_CHECK_THRESHOLD == 0
>                 {
>                     match self.account_manager.validate_device().await {
> ```

Will this ever execute successfully on Linux whilst in the `Connecting` state?

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 11 of 34 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 1193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwWB87U1QCKKJDYc-0K:-Mwa9jAFCukKYz5j_hpu:b39w1yv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/lib.rs#L1193)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Will this ever execute successfully on Linux whilst in the `Connecting` state?
</blockquote></details>

This should be reworked so that it doesn't block the tunnel parameter generation.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 12 of 34 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/migrations/v5.rs, line 324 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwaL_uR9QqDU1cKWgG4:-MwaL_uR9QqDU1cKWgG5:bi5ex2e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-daemon/src/migrations/v5.rs#L324)):*
> ```XML
>     #[test]
>     fn test_v5_v1_migration() {
>         let runtime = tokio::runtime::Runtime::new().expect("Failed to initialize runtime");
> ```

Whilst it's a single threaded runtime, `tokio` does provide the `tokio::test` proc macro for writing async tests. It's pretty useful and could simplify a lot of things.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 15 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 27 of 34 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/lib.rs, line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbIYYfBMbcvtK8HwHC:-MwbIYYfBMbcvtK8HwHD:bp8wwf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-rpc/src/lib.rs#L301)):*
> ```XML
>         let service = self.handle.service.clone();
>         let factory = self.handle.factory.clone();
>         let access_proxy = self.handle.token_store.clone();
> ```

Seems like handling the access token could be something that is abstracted away either in the factory or elsewhere IMO.
___
*[mullvad-rpc/src/lib.rs, line 401 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbJ8Gu1Be0mZH-gLiq:-MwbJ8Gu1Be0mZH-gLir:b-umcvsw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-rpc/src/lib.rs#L401)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct DevicesProxy {
> ```

The device stuff might deserve a module of it's own.
___
*[mullvad-setup/src/main.rs, line 188 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbKFPg96UMmTYlt-e0:-MwbKFPg96UMmTYlt-e1:b-2f61mr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-setup/src/main.rs#L188)):*
> ```XML
>         .map_err(Error::RemoveDeviceError)?;
> 
>         cacher
> ```

Can the file just not be removed? Is there a reason to write nothing into it?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 28 of 34 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 27 of 35 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/device.rs, line 763 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mwl1gILA-WQ71Atva_H:-Mwl1gILA-WQ71Atva_I:b-bijtss) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d5d6d89f37e477c52029407c896f59520fcef8e/mullvad-daemon/src/device.rs#L763)):*
> ```XML
>             path
>         };
>         tokio::fs::remove_file(path).await?;
> ```

This should probably ensure that the handle is actually closed. By at least flushing before dropping the handle.
___
*[mullvad-daemon/src/lib.rs, line 1193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwWB87U1QCKKJDYc-0K:-MwkWpBiAysaGL4wvLCk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e9c2608a37fc45e279bf29aef1c5a7ff988ec165/mullvad-daemon/src/lib.rs#L1193)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This should be reworked so that it doesn't block the tunnel parameter generation.
</blockquote></details>

Done.
___
*[mullvad-rpc/src/lib.rs, line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbIYYfBMbcvtK8HwHC:-Mwku4Hg7vph2wsv8F-N:bspyn4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-rpc/src/lib.rs#L301)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Seems like handling the access token could be something that is abstracted away either in the factory or elsewhere IMO.
</blockquote></details>

The most natural solution is to pass in `access_proxy` to `send_*_request`. Since it depends on the service, it doesn't really fit in `factory`. And it doesn't belong in `RequestService` (as currently designed) because it needs to check the parsed responses of all requests. But is that enough of an improvement?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 24 of 35 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/lib.rs, line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbIYYfBMbcvtK8HwHC:-Mwl9Xub4Yatod-Mdixx:b-pndqe8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-rpc/src/lib.rs#L301)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The most natural solution is to pass in `access_proxy` to `send_*_request`. Since it depends on the service, it doesn't really fit in `factory`. And it doesn't belong in `RequestService` (as currently designed) because it needs to check the parsed responses of all requests. But is that enough of an improvement?
</blockquote></details>

I've done this, but I do think the request service could own the "token store" instead.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 23 of 36 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/migrations/v5.rs, line 324 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwaL_uR9QqDU1cKWgG4:-MwzzSF86nJqWxSMD5Sb:b-tcko3t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-daemon/src/migrations/v5.rs#L324)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Whilst it's a single threaded runtime, `tokio` does provide the `tokio::test` proc macro for writing async tests. It's pretty useful and could simplify a lot of things.
</blockquote></details>

Cool. Done. You can actually specify that it should use a multithreaded runtime, when needed.
___
*[mullvad-rpc/src/lib.rs, line 401 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbJ8Gu1Be0mZH-gLiq:-MwzzgtcDlkLQGhfHbXA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-rpc/src/lib.rs#L401)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The device stuff might deserve a module of it's own.
</blockquote></details>

Done.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 34 files at r1, 1 of 3 files at r2, 3 of 4 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 1027 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mx4nIcT2RCi0GiOZB-9:-Mx4nIcT2RCi0GiOZB-A:bb6wcie) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa1af7e9f27ef8cf6a644422202e4d90852afd87/mullvad-daemon/src/lib.rs#L1027)):*
> ```XML
> 
>         // Check device validity last so that the broadcast is not delayed.
>         self.maybe_validate_device(&tunnel_state).await;
> ```

I'm 
___
*[mullvad-rpc/src/lib.rs, line 301 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-MwbIYYfBMbcvtK8HwHC:-Mx4oawa66a2T1nA8SJg:bsnm6h0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00fca7f1ea71491633d14c64a54a3aa5d35ad42f/mullvad-rpc/src/lib.rs#L301)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I've done this, but I do think the request service could own the "token store" instead.
</blockquote></details>

You are right, it's a bit messy. Feels like there should be a concept of a _session_ that keeps track of state like this.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 27 of 37 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device.rs, line 235 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdj_Ao25RLnL-hOnsA:-Mxdj_Ao25RLnL-hOnsB:b5k88q3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L235)):*
> ```XML
>         &self,
>         cmd: AccountManagerCommand,
>         rx: oneshot::Receiver<Result<T, Error>>,
> ```

This could take a closure that receives the `oneshot::Sender<Result<T, Error>>`,  so all the callers could remove the `let (tx, rx) = oneshot::channel();` and simplifcy stuff a bit.

Feels like there could be a macro written for these kinds of handles - I'm sure I've written code like this a dozen times already.
___
*[mullvad-daemon/src/device.rs, line 287 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdo2dM0tv5pQbgyO7R:-Mxdo2dM0tv5pQbgyO7S:b19rk8n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L287)):*
> ```XML
>     }
> 
>     async fn into_future(mut self, mut cmd_rx: mpsc::UnboundedReceiver<AccountManagerCommand>) {
> ```

I'm sure I've flip-flopped on this before, but I think functions like these should be called `run` or something similar.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 10 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 35 of 37 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device.rs, line 235 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdj_Ao25RLnL-hOnsA:-MxiKpK096RFCb62h92l:bvjtx2s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L235)):*
Done.

> Feels like there could be a macro written for these kinds of handles - I'm sure I've written code like this a dozen times already.

Yep. That would be nice, unless it sacrifices too much readability.
___
*[mullvad-daemon/src/device.rs, line 287 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdo2dM0tv5pQbgyO7R:-MxiKoI-B2dLxpm2R9VN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L287)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'm sure I've flip-flopped on this before, but I think functions like these should be called `run` or something similar.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device.rs, line 377 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdr1-r-2ebcCRFETfd:-MxiRZIED9W-JJLhs7Bt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L377)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This function can just inline `set_inner` now.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device.rs, line 409 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdr8NL9xYhmCSbNCVe:-MxiLMZJ1kPQ-lSW_xaI:b-bjaqu6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L409)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is something we should discuss, but I think that using the same timer for account data and rotating the device would make sense.
</blockquote></details>

If by account data you mean expiry, I think they should be separate things. But since we fetch the device anyway, it would make sense to update ports, etc., here. It's not critical that the ports are up to date for now, though.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 35 of 37 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device.rs, line 377 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdr1-r-2ebcCRFETfd:-MxiTsNW7ye_k5sfHAMS:b-hk78w6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L377)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't know if you meant literally use the inline attribute, but I think it makes sense to keep the method itself.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: 36 of 37 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/device.rs, line 377 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375#-Mxdr1-r-2ebcCRFETfd:-My72yX10mKj6PAPvS8r:bjcos1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03fb6ea0d1c7b0cde52ca1495a949fc5f388eba7/mullvad-daemon/src/device.rs#L377)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't know if you meant literally use the inline attribute, but I think it makes sense to keep the method itself.
</blockquote></details>

What I meant was to just remove `set_inner` and move it's implementation to `set`.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> Dismissed @pinkisemils from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3375)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
