### PR TITLE
Xp transistions

### PR DESCRIPTION
**Pull request by anderklander**
New transistion component!

Need some help with the Flow issues, ping @pronebird 

No impact for end user so no update to changelog.

Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/64)

### CODE REVIEW

**Comment by eriklarko** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by anderklander** [comment]
It should be noted that there is some issues with reactxp 51.1 and animations, so reactxp must be updated to something like 51.7 (their version history has room for improvements ...)

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-:-L5jESy7zl-7nVM591vX:bk7lx76)*

**Comment by pronebird** [comment]
yeah there and we should use the latest RX

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L5myhTF7u8uOJl0ZQM_:b-s2xv81)*

**Comment by pronebird** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[app/transitions.js, line 80 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5mz1G1CqyW-36AarLi:-L5mz1G1CqyW-36AarLj:b-an5xvl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/transitions.js#L80)):*
> ```JavaScript
> 
> /**
>  * Integrate TransitionDescriptor into CSSTransitionGroupProps
> ```

The description is not correct

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/transitions.js, line 100 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5mzAtjBQ5Waemjnnw2:-L5mzAtjBQ5Waemjnnw3:b-jds1rk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/transitions.js#L100)):*
> ansitionEnter

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
This looks like a good work but unfortunately none of this works on my laptop. There are no animations whatsoever.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L5n9-V8EhDCbqwaFoO4:b-rzw2ww)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[app/transitions.js, line 100 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5mzAtjBQ5Waemjnnw2:-L5n9AWPBZ3eOLZAaObD:b-f9f9hy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/transitions.js#L100)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

> ansitionEnter
</blockquote></details>

Ugh sorry for that, reviewable glitched. None of `transitionEnter` nor `transitionLeave` seem to be used. If you don't use something then maybe you should delete it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[app/transitions.js, line 100 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5mzAtjBQ5Waemjnnw2:-L5n9PHq9_Snt_nFyfpq:bsxuk9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/transitions.js#L100)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Ugh sorry for that, reviewable glitched. None of `transitionEnter` nor `transitionLeave` seem to be used. If you don't use something then maybe you should delete it.
</blockquote></details>

Sorry,`transitionEnter` is actually used, but not `transitionLeave`. I'd just replace it with `animated: boolean` so we can control which animations run animated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Actually this code didn't work on 0.51.3 either. So I've upgraded to the latest and it seems to work. If that's the requirement you should include the updated `yarn.lock` and `package.json` in this PR.

```
yarn upgrade reactxp --latest
```

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L5nCsrFAx_bGcdni8Tl:b1f3rlj)*

**Comment by pronebird** [comment]
Also, please remove `transitions.css` if it's not used anymore.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L5nGAlh67UO-4Bu_7ol:bp7oj5w)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 163 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5nI6CB0VUyfGq1FldY:-L5nI6CB0VUyfGq1FldZ:bvbpc2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L163)):*
> ```JavaScript
>           {previousChildren}
>         </Animated.View>
>         <Animated.View style={[this.animationStyles.style, childrenAnimation]}>
> ```

You probably noticed when transitioning from the Map to Settings, the Map component flickers. This is due to re-mounting of the components.

We could give React a hint using the `key` that we'd like to maintain the same containers for already placed views. React then will simply reorder the views and update the style. The best option would be to simply use `children.key` for `Animated.View`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 108 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5nLTsc9x3T5jlD36A6:-L5nLTsc9x3T5jlD36A7:bkcymrr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L108)):*
> ```JavaScript
>         });
>         break;
>       case 'push-transition':
> ```

The push and pop transitions do not not match the ones that we have.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
You can rebase since Flow should now be updated to the latest and `React.Node` annotations should work properly.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-:-L5rttF6iaLGLiijXFb8:b-37urq7)*

**Comment by pronebird** [comment]
Reviewed 1 of 5 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 11 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5sNvBrdaXLjZuefHlW:-L5sNvBrdaXLjZuefHlX:bs3ed0c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L11)):*
> ```JavaScript
> }
> 
> export default class TransitionContainer extends Component {
> ```

So now with Flow 0.66 we can do the following:

```
type State = {
    previousChildren: React.Node,
    childrenAnimation: Types.AnimatedViewStyleRuleSet,
    previousChildrenAnimation: Types.AnimatedViewStyleRuleSet,
    currentTranslationValue: Animated.Value,
    previousTranslationValue: Animated.Value,
    toValue: number,
    dimensions: Types.Dimensions,
};
```

Then the component is defined as:

```
class TransitionContainer extends Component<TransitionContrainerProps, State>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/components/TransitionContainer.js, line 11 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5sNvBrdaXLjZuefHlW:-L5sOTh6x1FtL5VH6RON:b-gtyce) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L11)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

So now with Flow 0.66 we can do the following:

```
type State = {
    previousChildren: React.Node,
    childrenAnimation: Types.AnimatedViewStyleRuleSet,
    previousChildrenAnimation: Types.AnimatedViewStyleRuleSet,
    currentTranslationValue: Animated.Value,
    previousTranslationValue: Animated.Value,
    toValue: number,
    dimensions: Types.Dimensions,
};
```

Then the component is defined as:

```
class TransitionContainer extends Component<TransitionContrainerProps, State>
```

</blockquote></details>

Actually keep in mind that previousChildren can be `null` in the beginning, so should be `previousChildren: ?React.Node` I guess. Same goes for other props that can be null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/components/TransitionContainer.js, line 111 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5sOqBgdItw6ACX8noh:-L5sOqBgdItw6ACX8noi:b-6o514t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L111)):*
> ```JavaScript
>           }),
>         }, ()=>{
>           let compositeAnimation = Animated.parallel([
> ```

Use `const` if you don't plan to re-assign the variable. This will ensure that you don't mistakenly overwrite something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 1 of 5 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 2 of 5 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 11 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5sNvBrdaXLjZuefHlW:-L5sPiAEjzDnpE55ERO4:b7v9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L11)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Actually keep in mind that previousChildren can be `null` in the beginning, so should be `previousChildren: ?React.Node` I guess. Same goes for other props that can be null.
</blockquote></details>

or either you can assign `previousChildren` to `[]` then it will never be null :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 108 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5nLTsc9x3T5jlD36A6:-L5sQ-SeR5x02_yIUo8s:b78boi6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L108)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

The push and pop transitions do not not match the ones that we have.
</blockquote></details>

to elaborate on that: 

the previous view should move left when the next view is pushed. So instead of drawer effect we have somewhat "parallax" movement.

I used different travel distances for views to achieve the effect when it feels like the previous view goes slower than the one that's being pushed and covers the former. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 132 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5sQoPEZRksxKbjgg9A:-L5sQoPEZRksxKbjgg9B:b-86nt2x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L132)):*
> ```JavaScript
>         break;
>       case 'pop':
>         this.state.currentTranslationValue.setValue(-50);
> ```

if that's -50% of the window width then that's correct, otherwise could you please try with `measureWindow().width * 0.5 * -1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 1 of 5 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Since we don't need react-transition-group anymore, we can drop it and remove flow annotations as well:

```
yarn remove react-transition-group
yarn rimraf flow-typed/npm/react-transition-group_vx.x.x.js
yarn install # to update lock file
```

---

Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-:-L5sRR4dkSQa-Zawm4vG:bmso3ou)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 163 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5nI6CB0VUyfGq1FldY:-L5sTB8u0LBhuIN155LI:b-6badpl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L163)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

Got a fix where the map is ok, but i also found that SelectLocation animates like shit. Will try to make a quick rewrite of SelectLocation to xp and see if the issue goes away.
</blockquote></details>

The issue seems to originate from the use of `scrollIntoViewIfNeeded` in `componentDidMount`. There is no need to rewrite `SelectLocation` right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 163 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5nI6CB0VUyfGq1FldY:-L5sTMqRTcva_FVauuD3:b-t9dqt6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L163)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

The issue seems to originate from the use of `scrollIntoViewIfNeeded` in `componentDidMount`. There is no need to rewrite `SelectLocation` right now.
</blockquote></details>

Try commenting `componentDidMount` in `SelectLocation` to see if that solves the problem for you too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 163 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L5nI6CB0VUyfGq1FldY:-L5sXZReA2GypyygaRmx:b-vlkm6m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L163)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Try commenting `componentDidMount` in `SelectLocation` to see if that solves the problem for you too.
</blockquote></details>

I prepared a PR that fixes this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by anderklander** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 163 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5nI6CB0VUyfGq1FldY:-L5sa3hh2w-EY9rsLKvx:b-5fqpf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79fd8ab87490cab3aa0b78731e0a7ec47440a92a/app/components/TransitionContainer.js#L163)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I prepared a PR that fixes this.
</blockquote></details>

Great! Thanks!

---

*[app/components/TransitionContainer.js, line 111 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5sOqBgdItw6ACX8noh:-L5sa7t202LZfDPHZsmW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L111)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Use `const` if you don't plan to re-assign the variable. This will ensure that you don't mistakenly overwrite something.
</blockquote></details>

Done.

---

*[app/components/TransitionContainer.js, line 132 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L5sQoPEZRksxKbjgg9A:-L5sa6Kr4KuNXL3teEKt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/267242e0d83db863ef9adc69309102574cbe2b20/app/components/TransitionContainer.js#L132)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

if that's -50% of the window width then that's correct, otherwise could you please try with `measureWindow().width * 0.5 * -1`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 2 of 4 files at r4.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 2 of 4 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Push animation does not seem to work on Support page.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-:-L5x9boHcucgYzlGmZLY:b-8ii1zu)*

**Comment by anderklander** [comment]
Removing `autoFocus={ true }` makes it work. If we can manage without i could just remove it, otherwise i guess that we could use `React.cloneElement` and update a prop in the children when the animation is done and implement a focus-function after that. Also guessing that auto-focus on mobiles will feel strange, so a different approach might be good. 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L6D9fii5Xya0UdRVKpp:b-6axhg4)*

**Comment by pronebird** [comment]
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 18 at r5](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L6Gjv7L8aJmQrGKWBwi:-L6Gjv7L8aJmQrGKWBwj:baesfg7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c98ca2b2fbbad83a8c36762205f08a198c8c538/app/components/TransitionContainer.js#L18)):*
> ```JavaScript
>     currentTranslationValue: Animated.Value,
>     previousTranslationValue: Animated.Value,
>     toValue: number,
> ```

This seem to be unused

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 16 at r5](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L6Gjye28W2qBz9OW5cU:-L6Gjye28W2qBz9OW5cV:b-2ji4tl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c98ca2b2fbbad83a8c36762205f08a198c8c538/app/components/TransitionContainer.js#L16)):*
> ```JavaScript
>     previousChildrenAnimation: Types.AnimatedViewStyleRuleSet,
>     animationStyles: Types.AnimatedViewStyleRuleSet,
>     currentTranslationValue: Animated.Value,
> ```

It seems like a very tiny optimization to store `currentTranslationValue` and `previousTranslationValue`. Removing those and spinning of new `Animated.Value` on demand should be fine and will trim down the current state.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[app/components/TransitionContainer.js, line 45 at r5](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L6Gktje4t-hznIpYrFm:-L6Gktje4t-hznIpYrFn:bgu9do1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c98ca2b2fbbad83a8c36762205f08a198c8c538/app/components/TransitionContainer.js#L45)):*
> ```JavaScript
> 
>   componentWillReceiveProps(nextProps: TransitionContainerProps) {
>     switch (nextProps.name){
> ```

Last thing, can we extract the cases from that switch and move them to separate methods? In this current form it's hardly readable and is a very long switch case.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[app/components/Support.js, line 166 at r5](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-L6GlHue0CRc8vEI1TnY:-L6GlHue0CRc8vEI1TnZ:bs453bi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de0e4d9353c9e1fadd219fc794cf8809a0ce1904/app/components/Support.js#L166)):*
> ```JavaScript
>             onChangeText={ this.onChangeEmail }
>             keyboardType="email-address"
>             autoFocus={ true } />
> ```

That may work as a temporary solution however Login screen heavily dependent on autoFocus. It doesn't usually animate and will only glitch on log out which is not very often event.

I don't want to over engineer anything here. I believe autofocus should work without us adding some hooks and additional complexity. I raised this issue with RX team. I played around with code and I don't think it's related to what we do.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
I don't like regressions in our code but please code you refactor few things (see comments below) and I agree we should merge with autoFocus disabled in support page. I'll add a regression task to backlog and someday I'll get to the bottom of it :+1: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L6Gm9KaDeaQBpAhot8H:b56njvx)*

**Comment by pronebird** [comment]
/code you refactor/ = could you refactor

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/64#-:-L6Gmssd4sk1-_RHilyh:b8qxjxe)*

**Comment by anderklander** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[app/components/TransitionContainer.js, line 16 at r5](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L6Gjye28W2qBz9OW5cU:-L6Gzhs71EElzTFWWvmY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c98ca2b2fbbad83a8c36762205f08a198c8c538/app/components/TransitionContainer.js#L16)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It seems like a very tiny optimization to store `currentTranslationValue` and `previousTranslationValue`. Removing those and spinning of new `Animated.Value` on demand should be fine and will trim down the current state.
</blockquote></details>

Done.

---

*[app/components/TransitionContainer.js, line 18 at r5](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L6Gjv7L8aJmQrGKWBwi:-L6GzhceY0WCRVArt4NT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c98ca2b2fbbad83a8c36762205f08a198c8c538/app/components/TransitionContainer.js#L18)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This seem to be unused
</blockquote></details>

Done.

---

*[app/components/TransitionContainer.js, line 45 at r5](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-L6Gktje4t-hznIpYrFm:-L6GzjIdXHgS9MuVTIXR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c98ca2b2fbbad83a8c36762205f08a198c8c538/app/components/TransitionContainer.js#L45)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Last thing, can we extract the cases from that switch and move them to separate methods? In this current form it's hardly readable and is a very long switch case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/64#-:-L6H-WVDm1gWbJ5tHB82:bnfp4nl)*

**Pull request merged**
