### PR TITLE
Move settings on unix

### PR DESCRIPTION
**Pull request by faern**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LCZfcq27R3zIszTLL9J:-LCZfcq27R3zIszTLL9K:b-ociof4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/package.json#L77)):*
> ```JSON
>     "flow": "flow",
>     "pack": "run-s pack:mac pack:win pack:linux",
>     "pack:mac": "./pre-mac-sign.sh && cross-env BABEL_ENV=electron run-s private:clean private:compile private:build:mac && rm -r ./dist/mac",
> ```

This is added because of the strange behavior of the pkg installer. If the pkg installer can find `Mullvad VPN.app` *anywhere on disk* it will try to upgrade that one instead of installing fresh. And after the build the full app resides in `dist/mac/Mullvad VPN.app`. Unless I remember to remove it any install will try to upgrade that version. This is very annoying during testing. This extra step ensures there is no upgradable version of the app laying around.

---

*[dist-assets/pkg-scripts/preinstall, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LCZfz4l5UoRad8vh0Z6:-LCZfz4l5UoRad8vh0Z7:bllaxaq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L18)):*
> ```
>     pkill MullvadVPN || true
>     pkill mullvad-daemon || true
>     sleep 0.5
> ```

The daemon can take up to 500 ms to shut down sometimes. I add this so we are sure to wait until it exits before removing the app.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Comment by jvff** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[dist-assets/pkg-scripts/preinstall, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_cxdc1Z5gqAtGtPKL:-LC_cxdc1Z5gqAtGtPKM:bs5yv8k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L28)):*
> ```
>     echo "Found old setting dir $OLD_SETTINGS_DIR. Moving to $NEW_SETTINGS_DIR"
>     mkdir -p "$NEW_SETTINGS_DIR"
>     mv "$OLD_SETTINGS_DIR/settings.json" "$NEW_SETTINGS_DIR/settings.json" || true
> ```

Is it dangerous to just do a `mv "$OLD_SETTINGS_DIR" "$NEW_SETTINGS_DIR"`?

---

*[dist-assets/pkg-scripts/preinstall, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_dPyiDnWlHP-yPjvL:-LC_dPyiDnWlHP-yPjvM:b-t65t68) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L45)):*
> ```
>     echo "Found old cache dir at $OLD_CACHE_DIR, moving to $NEW_CACHE_DIR"
>     mkdir -p "$NEW_CACHE_DIR"
>     mv "$OLD_CACHE_DIR/*" "$NEW_CACHE_DIR/" || true
> ```

Doesn't the `*` have to be outside the double-quotes for shell expansion to work?

Also, maybe this could also be simplified to `mv "$OLD_CACHE_DIR" "$NEW_CACHE_DIR"`, which would allow removing the `mkdir` and the `rm`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dist-assets/pkg-scripts/preinstall, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_cxdc1Z5gqAtGtPKL:-LCb_8dgCh36TNSXX0gZ:b-y5yc2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is it dangerous to just do a `mv "$OLD_SETTINGS_DIR" "$NEW_SETTINGS_DIR"`?
</blockquote></details>

I think you'll have to elaborate. What part of it do you think might be dangerous? The fact that we might overwrite settings? Well the `[ -d "$OLD_SETTINGS_DIR" ]` condition should only hold the first time you run one of these installers. You could of course re-install the old `2018.1` and in that way create new settings in the old location. But if you bother downgrading, starting the old client and actually log in to it so a settings file is created then I feel it's justified to do the migration again if you ever install a newer client again.

These upgrade scripts can't really be perfect, they'll have to fit most users and screw up as little as possible for the rest. But I'm open for suggestions on improvements.

---

*[dist-assets/pkg-scripts/preinstall, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_dPyiDnWlHP-yPjvL:-LCb_lYi0FC-8rysAjad:blushgi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L45)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Doesn't the `*` have to be outside the double-quotes for shell expansion to work?

Also, maybe this could also be simplified to `mv "$OLD_CACHE_DIR" "$NEW_CACHE_DIR"`, which would allow removing the `mkdir` and the `rm`.
</blockquote></details>

TIL! I did not know that, but yeah, seems like it. I was certain I had tested this to work, but now when I test again it does not. I'll move the `/*` part out of the quote. Good catch.

If I use `mv <old> <new>` and `<new>` already exists mv will default to move *into* the destination and we will end up with `<new>/<old>`. Is there any flag to avoid this? Also the `mkdir` is for safety in case any parent folder to the cache folder is absent as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dist-assets/pkg-scripts/preinstall, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_dPyiDnWlHP-yPjvL:-LCbcgjN-CtV-bdoNPxL:b-j3ucus) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

TIL! I did not know that, but yeah, seems like it. I was certain I had tested this to work, but now when I test again it does not. I'll move the `/*` part out of the quote. Good catch.

If I use `mv <old> <new>` and `<new>` already exists mv will default to move *into* the destination and we will end up with `<new>/<old>`. Is there any flag to avoid this? Also the `mkdir` is for safety in case any parent folder to the cache folder is absent as well.
</blockquote></details>

And the reason for the `|| true` is to make the script not crash in case the old directory exists but it has no files in it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Comment by pinkisemils** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dist-assets/pkg-scripts/preinstall, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_cxdc1Z5gqAtGtPKL:-LCcI-NUCKcWfLcNO6Tr:b-ujut18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think you'll have to elaborate. What part of it do you think might be dangerous? The fact that we might overwrite settings? Well the `[ -d "$OLD_SETTINGS_DIR" ]` condition should only hold the first time you run one of these installers. You could of course re-install the old `2018.1` and in that way create new settings in the old location. But if you bother downgrading, starting the old client and actually log in to it so a settings file is created then I feel it's justified to do the migration again if you ever install a newer client again.

These upgrade scripts can't really be perfect, they'll have to fit most users and screw up as little as possible for the rest. But I'm open for suggestions on improvements.
</blockquote></details>

I asked if it was dangerous because I was wondering why only the `settings.json` file was being copied, instead of `*` for example. Is there some additional files in the old settings dir that shouldn't be copied?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[dist-assets/pkg-scripts/preinstall, line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171#-LC_cxdc1Z5gqAtGtPKL:-LCcXWqn6H0xWH7bmO3E:bhv31ij) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab587cf19382c1a34c7f4eb3261158ee2a17dbae/dist-assets/pkg-scripts/preinstall#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I asked if it was dangerous because I was wondering why only the `settings.json` file was being copied, instead of `*` for example. Is there some additional files in the old settings dir that shouldn't be copied?
</blockquote></details>

No, we only have one settings file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)*

**Pull request merged**
