### PR TITLE
Android split tunnel UI updates

### PR DESCRIPTION
**Pull request by axti**
Filter application on the split tunnel list by internet permission

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2381)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2381)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2381#-MQX61v43hCLo8EX6_3E:-MQX61v43hCLo8EX6_3F:b6mk2md) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aad86eac3f9c6b3cae0e6c801392ac539e8059f7/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt#L23)):*
> ```Kotlin
>     private val packageManager = context.packageManager
>     private val thisPackageName = context.packageName
>     private val applicationFilterPredicate: (ApplicationInfo) -> Boolean = { appInfo ->
> ```

Nit: I would personally add an empty line before this property, so it's easier to find when glancing (but that's very subjective, and we can try to converge on style with time :D )
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2381#-MQX5uhoD7mcj8kv-yLn:-MQX5uhp2FsY-dWT_SPP:b13gq2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aad86eac3f9c6b3cae0e6c801392ac539e8059f7/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt#L82)):*
> ```Kotlin
>     private fun hasInternetPermission(packageName: String): Boolean {
>         return PackageManager.PERMISSION_GRANTED ==
>                 packageManager.checkPermission(Manifest.permission.INTERNET, packageName)
> ```

CI is complaining that this line has an extra indentation level :/

**Comment by axti** [comment]
@jvff I fix your comments.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2381#-:-MQXS6lB5Oj6pmL6oVut:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by faern** [comment]
Closed by manual merge in 1a2c45d89

**Pull request closed without merging**
