### PR TITLE
Add `wireguard-go` and golang upgrade instructions

### PR DESCRIPTION
**Pull request by Serock3**
Fixes DES-830

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391)

### CODE REVIEW

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`wireguard-go-rs/README.md` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O-prvlc-rLYPOivAPgj:-O-q-lZc6xHlQU18Ms2d:b24hw02) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b30de08fcd751bc35d8e9267697e2bb185700002/wireguard-go-rs/README.md#L8)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Is this still true? :eyes:
</blockquote></details>

You're right, it's not. I removed that entire section.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-:-O081g8zD-3PhWSzxeC3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`android/fdroid-build/init.sh` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08C0C79_6YioZfacxS:-O08C0C79_6YioZfacxT:bcdrc15) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aae55e328caee7e6c16b545cd1fec26436b12828/android/fdroid-build/init.sh#L30)):*
> ```Shell
> echo "$GOLANG_HASH go.tgz" | sha256sum -c
> tar -xzvf go.tgz
> patch -p1 -f -N -r- -d "$HOME/go" < "$REPO_DIR/wireguard/libwg/goruntime-boottime-over-monotonic.diff"
> ```

This was a good finding we did last week! It looks like the file at the previous path was removed on `main`, but luckly enough we are currently releasing from a long-living release branch which branched out before the file was removed.
___
*[`wireguard-go-rs/README.md` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08F5uSD9al_FfjAPtb:-O08F5uSD9al_FfjAPtc:bo0gv8l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf8dfd53759fdcd0328a3462fc9b87843b18e450/wireguard-go-rs/README.md#L1)):*
> ```Markdown
> # `wireguard-go-rs`
> ```

Looks like this file is missing some newlines :thinking: 
___
*[`wireguard-go-rs/README.md` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08Ckmo9ztPrxju-jXq:-O08Ckmo9ztPrxju-jXr:b-i0oj1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf8dfd53759fdcd0328a3462fc9b87843b18e450/wireguard-go-rs/README.md#L8)):*
> ```Markdown
> Upgrading `wireguard-go` involves updating the git submodule found in `libwg/wireguard-go`, which points to [Mullvad VPN's fork of wireguard-go](https://github.com/mullvad/wireguard-go). To update the fork, find the desired release of `wireguard-go` at <https://github.com/WireGuard/wireguard-go/tags> and rebase the fork on the corresponding commit. Change directory to `libwg` and run `go mod tidy` to update indirect dependencies.
> 
> To upgrade the version of `Go` run `go mod edit -go=XX`. You will also need to update the `ARG GOLANG_VERSION` version in `building/Dockerfile` and build and distribute new development container images, see the corresponding [instructions](../building/README.md).
> ```

This is a bit misleading since the image is used by the build server as well, so I suggest just removing it.



_Code quote:_
```Markdown
 development
```
___
*[`wireguard-go-rs/README.md` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08EH7B4yGWXTXZZ4aS:-O08EH7B4yGWXTXZZ4aT:b-n7w57d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf8dfd53759fdcd0328a3462fc9b87843b18e450/wireguard-go-rs/README.md#L10)):*
> ```Markdown
> To upgrade the version of `Go` run `go mod edit -go=XX`. You will also need to update the `ARG GOLANG_VERSION` version in `building/Dockerfile` and build and distribute new development container images, see the corresponding [instructions](../building/README.md).
> 
> Before upgrading the version of `Go` or `wireguard-go`, be aware that we depend on a patch for the internal clocks of the go runtime on android, see <https://git.zx2c4.com/wireguard-android/tree/tunnel/tools/libwg-go>. Upgrading the versions of `wireguard-go` or `Go` beyond what the patch is built for should be done with caution. Note, however, that the patch states that "In Linux 4.17, the kernel will actually make MONOTONIC act like BOOTTIME anyway, so this switch will additionally unify the timer behavior across kernels." According to <https://source.android.com/docs/core/architecture/kernel/android-common>, Android version 11 and newer seem to use sufficiently new versions of the linux kernel to not need this patch. When we no longer support older versions of android, we may be able to drop this compatibility requirement.
> ```

I believe it would be good to add some sort of title to this section. That would also make it possible to link to this section from other places.
___
*[`wireguard-go-rs/README.md` line 11 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08Dl6REv0uXN7f49fM:-O08Dl6REv0uXN7f49fN:bltk2oz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf8dfd53759fdcd0328a3462fc9b87843b18e450/wireguard-go-rs/README.md#L11)):*
> ```Markdown
> 
> Before upgrading the version of `Go` or `wireguard-go`, be aware that we depend on a patch for the internal clocks of the go runtime on android, see <https://git.zx2c4.com/wireguard-android/tree/tunnel/tools/libwg-go>. Upgrading the versions of `wireguard-go` or `Go` beyond what the patch is built for should be done with caution. Note, however, that the patch states that "In Linux 4.17, the kernel will actually make MONOTONIC act like BOOTTIME anyway, so this switch will additionally unify the timer behavior across kernels." According to <https://source.android.com/docs/core/architecture/kernel/android-common>, Android version 11 and newer seem to use sufficiently new versions of the linux kernel to not need this patch. When we no longer support older versions of android, we may be able to drop this compatibility requirement.
> ```

Looks like a bad EOF according to reviewable

**Review by Pururun — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`wireguard-go-rs/README.md` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08EH7B4yGWXTXZZ4aS:-O09QDWC3je5YEU5B28l:b6f8vdh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf8dfd53759fdcd0328a3462fc9b87843b18e450/wireguard-go-rs/README.md#L10)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Done WDYT?
</blockquote></details>

I like the icon, but the anchor unfortunantely becomes quite ugly: `#%EF%B8%8F-caution-go-runtime-patch`

For that reason I would prefer skipping the icon unless it's possible to define a custom anchor etc

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`wireguard-go-rs/README.md` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6391#-O08EH7B4yGWXTXZZ4aS:-O09kh3HCmI-bsXk9w9g:bte8bte) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bf8dfd53759fdcd0328a3462fc9b87843b18e450/wireguard-go-rs/README.md#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I like the icon, but the anchor unfortunantely becomes quite ugly: `#%EF%B8%8F-caution-go-runtime-patch`

For that reason I would prefer skipping the icon unless it's possible to define a custom anchor etc
</blockquote></details>

Fair enough :joy: Removed it :cry:

**Pull request merged**
