### PR TITLE
Improve wireguard obfuscation settings

### PR DESCRIPTION
**Pull request by Pururun**
- Improve selectable cell to add support for checkmark
- Add preview to selectable cell
- Changed title to WireGuard obfuscation
- Replaced some hardcoded values in BaseCell with values from theme and dimensions

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh01FH0PyGY4imFshx:-NWh01FH0PyGY4imFshy:bt36byn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L70)):*
> ```Kotlin
>     val cellHeight = Dimens.cellHeight
>     val cellVerticalSpacing = Dimens.cellLabelVerticalPadding
>     val subtitleVerticalSpacing = Dimens.cellFooterTopPadding
> ```

I suggest skipping defining `val`s for these 



_Code quote:_
```Kotlin
    val cellHeight = Dimens.cellHeight
    val cellVerticalSpacing = Dimens.cellLabelVerticalPadding
    val subtitleVerticalSpacing = Dimens.cellFooterTopPadding
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh3EjM61DYd64w1DsT:-NWh3EjM61DYd64w1DsU:b-qudig6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L29)):*
> ```Kotlin
>         Column(Modifier.background(MaterialTheme.colorScheme.background)) {
>             SelectableCell(title = "Selected", isSelected = true)
>             Spacer(modifier = Modifier.height(1.dp))
> ```

Maybe not for this PR, but would be really nice to add some default spacer like this to avoid specifying the modifier over and over



_Code quote:_
```Kotlin
Spacer(modifier = Modifier.height(1.dp))
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh4c5-ABCR5rsKFQSE:-NWh4c5-ABCR5rsKFQSF:b-7g7c94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L51)):*
> ```Kotlin
>                             1f
>                         } else {
>                             0f
> ```

Perhaps we can skip rendering the icon instead? That should probably result in better performance than setting the alpha to zero.



_Code quote:_
```Kotlin
0f
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh1Sgo0JAde-sfOKBS:-NWh1Sgo0JAde-sfOKBT:bk1b647) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L23)):*
> ```Kotlin
>     val cellLabelVerticalPadding: Dp = 14.dp,
>     val cellFooterTopPadding: Dp = 6.dp,
>     val selectableCellTextMargin: Dp = 12.dp
> ```

Would be nice to come up with how we should organize all these dimensions since it's starting to get a bit messy. I guess the easiest way is to just do it alphabetically. Any thoughts?



_Code quote:_
```Kotlin
    val cellHeight: Dp = 52.dp,
    val cellLabelVerticalPadding: Dp = 14.dp,
    val cellFooterTopPadding: Dp = 6.dp,
    val selectableCellTextMargin: Dp = 12.dp
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750)* status: 21 of 26 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh01FH0PyGY4imFshx:-NWkmS_xBKYh7Zn_V_24:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L70)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest skipping defining `val`s for these 
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh3EjM61DYd64w1DsT:-NWkmUFA5hJUZoDEp-KW:b-y1wjr1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Maybe not for this PR, but would be really nice to add some default spacer like this to avoid specifying the modifier over and over
</blockquote></details>

I added a spaced column instead which serves the same purpose.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh4c5-ABCR5rsKFQSE:-NWkmc8G2LTe1gNKZwne:bq6wzf7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps we can skip rendering the icon instead? That should probably result in better performance than setting the alpha to zero.
</blockquote></details>

So the reason I did this was to simulate the View.INVISIBLE behaviour. The main reason for this is to keep the indentation regardless if the checkmark is there or not. We can discuss if there's another way to do this.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh1Sgo0JAde-sfOKBS:-NWkmwpP2xz6YVaiURLU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to come up with how we should organize all these dimensions since it's starting to get a bit messy. I guess the easiest way is to just do it alphabetically. Any thoughts?
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-NWh4c5-ABCR5rsKFQSE:-NWpxNb10WOHSRBpPvYn:b-7b85wl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c82a4238bcfddee3598f1b18c9ed72405c2ce7a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L51)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So the reason I did this was to simulate the View.INVISIBLE behaviour. The main reason for this is to keep the indentation regardless if the checkmark is there or not. We can discuss if there's another way to do this.
</blockquote></details>

I looked at some other ways to handle the indentation in a non-hardcoded way, but it's probably better to stick with using the alpha as long as we don't see any overall performance issues in the view.

We have some alpha values defined in `Color.kt` so I suggest doing the same for these values if we go with this route. It might also be nice to skip the curly braces to improve formatting if the alpha stuff fits on a single line.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750#-:-NWqPnIlExp7RoPK7t-G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
