### PR TITLE
Make `test-manager` easier to run on any app version

### PR DESCRIPTION
**Pull request by Serock3**
* The first three commits fixes a couple if issues preventing the `test-manager` from finding release build packages.
* The last commit restructures the convenience scripts. `ci-runtests.sh` should now only be used by the GitHub actions, the new `test-by-version.sh` script can be used to manually test any pre-built app version 
* The remaining commits cleans up the CLI, polishes the logs and error messages and fixes a flaky test.

Fixes DES-1092

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 12 of 12 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568)* status: 21 of 23 files reviewed, 4 unresolved discussions (waiting on @Serock3)

___
*[`test/test-by-version.sh` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3amw2wDh6krJqBQ5l-:-O3amw2wDh6krJqBQ5l0:b-3oqki2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-by-version.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> set -eu
> ```

Would be nice with a small introductory comment which explains the intended use of this script, preferably explaining the script's arguments :blush:



_Code quote:_
```Shell
#!/usr/bin/env bash

set -eu
```
___
*[`test/test-manager/src/main.rs` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3aTJncEEhL22EH2TGN:-O3aTJncEEhL22EH2TGO:b-omogq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8f622947480fca198d8e0ba52fc58dddb27a4f1/test/test-manager/src/main.rs#L31)):*
> ```XML
>     /// Create or edit a VM config
>     Set {
>         /// Name of the config
> ```

Nit: Maybe change to something like "Name of the test runner config (vm)" ? :blush:

Otherwise, just "Name of the VM config" to be consistent with the other commands `Remove/List/RunVM`



_Code quote:_
```XML
/// Name of the config
```
___
*[`test/test-manager/src/network_monitor.rs` line 101 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3atUzcAyTul6QX7YYO:-O3atUzcAyTul6QX7YYP:b-5dzz51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L101)):*
> ```XML
>             }
>             IpHeaderProtocols::Icmp => {}
>             proto => log::warn!("ignoring v4 packet, transport/protocol type {proto}"),
> ```

Now when I think about it, maybe this log should be `debug` instead. Might be spammy with `warn`?



_Code quote:_
```XML
            proto => log::warn!("ignoring v4 packet, transport/protocol type {proto}"),
```
___
*[`test/test-manager/src/network_monitor.rs` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3at_8c6pydw-ta0rW5:-O3at_8c6pydw-ta0rW6:b-5dzz51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L143)):*
> ```XML
>             }
>             IpHeaderProtocols::Icmpv6 => {}
>             proto => log::warn!("ignoring v6 packet, transport/protocol type {proto}"),
> ```

Now when I think about it, maybe this log should be `debug` instead. Might be spammy with `warn`?



_Code quote:_
```XML
            proto => log::warn!("ignoring v6 packet, transport/protocol type {proto}"),
```
___
*[`test/test-manager/src/package.rs` line 183 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3avJfj6z6KtVtMvEZb:-O3avJfj6z6KtVtMvEZc:be9we6h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/package.rs#L183)):*
> ```XML
>         assert_eq!(capture, "2024.3");
>     }
> }
> ```

:heart:



_Code quote:_
```XML
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version_regex() {
        let path = Path::new("../some/path/MullvadVPN-2024.4-beta1-dev-f7df8e_amd64.deb");
        let capture = get_version_from_path(path).unwrap();
        assert_eq!(capture, "2024.4-beta1-dev-f7df8e");

        let path = Path::new("../some/path/MullvadVPN-2024.4-beta1-f7df8e_amd64.deb");
        let capture = get_version_from_path(path).unwrap();
        assert_eq!(capture, "2024.4-beta1-f7df8e");

        let path = Path::new("../some/path/MullvadVPN-2024.4-dev-f7df8e_amd64.deb");
        let capture = get_version_from_path(path).unwrap();
        assert_eq!(capture, "2024.4-dev-f7df8e");

        let path = Path::new("../some/path/MullvadVPN-2024.3_amd64.deb");
        let capture = get_version_from_path(path).unwrap();
        assert_eq!(capture, "2024.3");
    }
}
```

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568)* status: 21 of 24 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-by-version.sh` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3amw2wDh6krJqBQ5l-:-O3bLiQX2Tb6bhCkLtdi:b2997qs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-by-version.sh#L3)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice with a small introductory comment which explains the intended use of this script, preferably explaining the script's arguments :blush:
</blockquote></details>

Yup, Magnus also commented on that. Added a `usage` function. What do you think?
___
*[`test/test-manager/src/main.rs` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3aTJncEEhL22EH2TGN:-O3bLtkR2bwwInvopaWe:b-9nxvhh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8f622947480fca198d8e0ba52fc58dddb27a4f1/test/test-manager/src/main.rs#L31)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: Maybe change to something like "Name of the test runner config (vm)" ? :blush:

Otherwise, just "Name of the VM config" to be consistent with the other commands `Remove/List/RunVM`
</blockquote></details>

Good catch. I wrote `VM config` in all other places but missed it here. I also added `run 'test-manager list' to see available configs` to the explanation for `vm`
___
*[`test/test-manager/src/network_monitor.rs` line 101 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3atUzcAyTul6QX7YYO:-O3bPKoIBo7YE0RGwUBe:b-4ymsh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L101)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Now when I think about it, maybe this log should be `debug` instead. Might be spammy with `warn`?
</blockquote></details>

Looking at then logs from the CI, this string doesn't appear at all. Have you seen it a lot?
___
*[`test/test-manager/src/network_monitor.rs` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3at_8c6pydw-ta0rW5:-O3c8ziKBGFuuuHWZoOk:byr4ffv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L143)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Now when I think about it, maybe this log should be `debug` instead. Might be spammy with `warn`?
</blockquote></details>

see above

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`test/test-by-version.sh` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3amw2wDh6krJqBQ5l-:-O3fRKcH0VUu9xEcyUN8:bszm2f7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-by-version.sh#L3)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Yup, Magnus also commented on that. Added a `usage` function. What do you think?
</blockquote></details>

Much better!
___
*[`test/test-manager/src/main.rs` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3aTJncEEhL22EH2TGN:-O3fRf7j-RVGiDE2-e4F:b-ejix1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8f622947480fca198d8e0ba52fc58dddb27a4f1/test/test-manager/src/main.rs#L31)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Good catch. I wrote `VM config` in all other places but missed it here. I also added `run 'test-manager list' to see available configs` to the explanation for `vm`
</blockquote></details>

Ah, nice! Did you update the comment which I quoted yet? :blush:
___
*[`test/test-manager/src/network_monitor.rs` line 101 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3atUzcAyTul6QX7YYO:-O3fQrvK7T5mrguHSnT0:bf11ylf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L101)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Looking at then logs from the CI, this string doesn't appear at all. Have you seen it a lot?
</blockquote></details>

I've seen it, not much though. I don't think the event is that interesting though, which is probably why it was `debug` to begin with :sweat_smile:

**Review by Serock3 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-:-O3frVMm1Iptn0iuG5lA:bnfp4nl)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/main.rs` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3aTJncEEhL22EH2TGN:-O3ftMXx3lQpxUmeeECX:b-x30wqq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8f622947480fca198d8e0ba52fc58dddb27a4f1/test/test-manager/src/main.rs#L31)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Ah, nice! Did you update the comment which I quoted yet? :blush:
</blockquote></details>

Whoops :facepalm:, fixed now
___
*[`test/test-manager/src/network_monitor.rs` line 101 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3atUzcAyTul6QX7YYO:-O3ftipUC8VJRSM7f_7h:b-r5zqt9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L101)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I've seen it, not much though. I don't think the event is that interesting though, which is probably why it was `debug` to begin with :sweat_smile:
</blockquote></details>

Alright, lowered it to debug
___
*[`test/test-manager/src/network_monitor.rs` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3at_8c6pydw-ta0rW5:-O3ftkkyCKR_jLm_DOYm:b-72rnvx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f45fb6017fc264138ed0dca71ae929839fa868ee/test/test-manager/src/network_monitor.rs#L143)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Lowered to debug

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-:-O3fyHPNB4FUlIf52RMD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-:-O3gf_TX6n6RYsPRjLOi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 247 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3kbiESAZSPy5e3vy0u:-O3kbiESAZSPy5e3vy0v:b-fbi0gr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90b81e3dfde1b17962f335f78a133a7803e614c9/test/scripts/test-utils.sh#L247)):*
> ```Shell
> 
>     if [[ -z "${TEST_REPORT+x}" ]]; then
>         echo "'TEST_REPORT' env not set, not saving test report"
> ```

Is it explained anywhere what `TEST_REPORT` is expected to be? A directory? A path to a file? etc :blush:



_Code quote:_
```Shell
        echo "'TEST_REPORT' env not set, not saving test report"
```

**Review by Serock3 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-:-O3l8bTo7YQeVwZlvp7d:bnfp4nl)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`test/scripts/test-utils.sh` line 247 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-O3kbiESAZSPy5e3vy0u:-O3l8Qhq6HXkPY1czAu2:b-xnclyx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90b81e3dfde1b17962f335f78a133a7803e614c9/test/scripts/test-utils.sh#L247)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Is it explained anywhere what `TEST_REPORT` is expected to be? A directory? A path to a file? etc :blush:
</blockquote></details>

I added it to the `usage` function in`test-by-version.sh` and improved the CLI help text

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-:-O3l9cJ11Og_ho1E85qP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6568#-:-O3mDTGD1A-DGG_kYABw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
