### PR TITLE
Prevent logging when running tests

### PR DESCRIPTION
**Pull request by raksooo**
This PR prevents our logging implementation from outputting to the console when encountering errors while running tests.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)

### CODE REVIEW

**Comment by axti** [comment]
We don't want to use logs from tests or they are redundant?

**Comment by raksooo** [comment]
The logs that I have disabled when running tests are the logs to the console that are output due to failure in accessing the file system. This is expected in some of the tests and pollutes the test result with log messages. I don't think there is any need for logging in tests.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTep8K5Aq75OBRckMi-:-MTep8K5Aq75OBRckMi0:b-yk7kp8) (no related file):*
It sounds like what you really want is to avoid setting up logging in the first place when running in the test environment.

---

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/logging.ts, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTepjuT8mpsn2PKT0Q4:-MTepjuT8mpsn2PKT0Q5:byzboyb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aeeca0e38f2e7c0b24349e61ef17420bf6c55474/gui/src/main/logging.ts#L18)):*
> ```XML
>   private fileDescriptor?: number;
> 
>   constructor(public level: LogLevel, private filePath: string) {
> ```

BTW it would be better to delegate the error handling to the caller. Instead what happens now is that we get a defunct `FileOutput`.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTep8K5Aq75OBRckMi-:-MTfN7jd8WrILxZ5LULT:bcpz8hg) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It sounds like what you really want is to avoid setting up logging in the first place when running in the test environment.
</blockquote></details>

I've updated the PR with the changes discussed on Slack.

---
___
*[gui/src/main/logging.ts, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTepjuT8mpsn2PKT0Q4:-MTfN5ZQ72GE6GpRTRRU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aeeca0e38f2e7c0b24349e61ef17420bf6c55474/gui/src/main/logging.ts#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

BTW it would be better to delegate the error handling to the caller. Instead what happens now is that we get a defunct `FileOutput`.
</blockquote></details>

Done.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/main/index.ts, line 363 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTfV76Y9j_CnI0cyhel:-MTfV76Y9j_CnI0cyhem:b-ffxmux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74d40eb1266a03535e04a2ab33681aad99b2cd4e/gui/src/main/index.ts#L363)):*
> ```XML
>     this.daemonRpc.disconnect();
> 
>     try {
> ```

Maybe wrap it in a loop, i.e:

```
for logger in [log, this.rendererLog] {
    try { logger.dispose() } catch { .. }
}
```

This way you'd attempt at disposing each of objects before bailing.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging.ts, line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTfWP8m2ml_OeDnhJ2l:-MTfWP8m2ml_OeDnhJ2m:bof2f65) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74d40eb1266a03535e04a2ab33681aad99b2cd4e/gui/src/shared/logging.ts#L37)):*
> ```XML
>       .forEach(async (output) => {
>         try {
>           await output.write(level, message);
> ```

Don't you have to handle `void` return value?

```
let maybePromise = output.write(level, message);

if maybePromise {
  try {
    await maybePromise;
  } catch {
    // log error
  }
}
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 363 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTfV76Y9j_CnI0cyhel:-MTfzo4Y9GUScmMppsjt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74d40eb1266a03535e04a2ab33681aad99b2cd4e/gui/src/main/index.ts#L363)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe wrap it in a loop, i.e:

```
for logger in [log, this.rendererLog] {
    try { logger.dispose() } catch { .. }
}
```

This way you'd attempt at disposing each of objects before bailing.
</blockquote></details>

Done.
___
*[gui/src/shared/logging.ts, line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-MTfWP8m2ml_OeDnhJ2l:-MTfzpBXCV1UYbkmpPCb:b1vzos9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74d40eb1266a03535e04a2ab33681aad99b2cd4e/gui/src/shared/logging.ts#L37)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Don't you have to handle `void` return value?

```
let maybePromise = output.write(level, message);

if maybePromise {
  try {
    await maybePromise;
  } catch {
    // log error
  }
}
```
</blockquote></details>

It's possible to `await` any value but will have to convert the value to a `Promise`. Even though it works to await the value this is nicer. Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474#-:-MTjFhVIE_ZpzLyce9Hn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
