### PR TITLE
Update changelog for beta 9

### PR DESCRIPTION
**Pull request by eriklarko**
Not sure why I did this change, you guys are the ones who really care about it. So feel free to push any changes you want on this branch

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/47)

### CODE REVIEW

**Comment by pronebird** [comment]
You've reflected my change in the CHANGELOG. :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-:-L45X91Utmddl7G52QGk:b-iqpngs)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[CHANGELOG.md, line 16 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45XwkVDrafE5Z6L86r:-L45XwkWYTf6hO13l8Tn:bosjqx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L16)):*
> ```Markdown
> 
> 
> ## [Unreleased]
> ```

Maybe bump the header as well unless you want to have a separate release PR where this is done.

---

*[CHANGELOG.md, line 27 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45YppyMbgJtY2HePJL:-L45YppzEs8A9x84npDf:b-355vv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L27)):*
> ```Markdown
> - Fixed a bug where the problem report tool would redact some things in the logs which were not
>   IPv6 addresses, but looked like ones.
> - Show a better error message when api.mullvad.net is unreachable.
> ```

Maybe add `- Fix bug getting daemon state on frontend start instead of assuming it.` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 27 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45YppyMbgJtY2HePJL:-L45_X_A9L6HdDER934C:b8pirtn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L27)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe add `- Fix bug getting daemon state on frontend start instead of assuming it.` ?
</blockquote></details>

Was it fixed??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 27 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45YppyMbgJtY2HePJL:-L45_rRZwqBKJrd7DSlQ:b-7uqobd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L27)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Was it fixed??
</blockquote></details>

I see a commit for it (2707a29) so I guess so?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 27 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45YppyMbgJtY2HePJL:-L45bKW9DDXroX8jUbe-:bbdwqd9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L27)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I see a commit for it (2707a29) so I guess so?
</blockquote></details>

Oh yeah right. It's 22 days old. Didn't we release anything in over 3 weeks? :open_mouth: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47)*

**Comment by eriklarko** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 16 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45XwkVDrafE5Z6L86r:-L45elXzWkyTWlifu0oc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe bump the header as well unless you want to have a separate release PR where this is done.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 27 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47#-L45YppyMbgJtY2HePJL:-L45eksFV4FxJ5jK4Kn2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76ef413f2ef1bc1a9c5bcb76a7144946153c1228/CHANGELOG.md#L27)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Oh yeah right. It's 22 days old. Didn't we release anything in over 3 weeks? :open_mouth: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/47)*

**Pull request merged**
