### PR TITLE
Adding section header view for select location sections ios 549

### PR DESCRIPTION
**Pull request by mojganii**
adding section header view in select location

- each section should have its own distinct header view.
- custom list section has an action that should take user to add/edit custom list.it will be coming during upcoming changes.
- refactoring location cell
- removing LocationCellFactory

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, 8 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Supporting Files/Assets.xcassets/Kebab.imageset/Contents.json` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh0fgg5RhWwMYLnoI4:-Nsh0fgg5RhWwMYLnoI5:bn7gtny) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/Supporting%20Files/Assets.xcassets/Kebab.imageset/Contents.json#L4)):*
> ```JSON
>   "images" : [
>     {
>       "filename" : "Kebab.pdf",
> ```

I love me some kebab too but... what is this file doing here ?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh6Wi59egF-4SVTndi:-Nsh6Wi66hPQlrF7bgXo:b-yqhpmu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L223)):*
> ```Swift
>     override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
>         // swiftlint:disable:next force_cast
>         let cell = super.tableView(tableView, cellForRowAt: indexPath) as! LocationCell
> ```

Don't forget to reenable `force_cast` if we can't avoid casting here
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh2MaRAbCPao_-k5Uk:-Nsh2MaRAbCPao_-k5Ul:b-3uh237) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationSectionHeaderView.swift#L36)):*
The "Kebab" menu is an Android idiom, we shouldn't be using this on iOS. 
Instead, we should use the `ellipsis` icon here.
```swift
button.setImage(UIImage(systemName: "ellipsis"), for: .normal)
```

From the [HIG](https://developer.apple.com/design/human-interface-guidelines/menus)
> **Append an ellipsis to a menu item’s label when people need to provide additional information before the action can complete.** The ellipsis character (…) signals that another view will open in which people can input information or make choices.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSourceProtocol.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh0CXRDvSAkOp-d3CU:-Nsh0CXRDvSAkOp-d3CV:b-uzd62i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSourceProtocol.swift#L15)):*
> ```Swift
> 
> protocol LocationDataSourceProtocol {
>     var viewForHeader: UIView? { get }
> ```

This, and its various implementations don't need to be `Optional`

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Supporting Files/Assets.xcassets/Kebab.imageset/Contents.json` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh0fgg5RhWwMYLnoI4:-Nsh9RI-70f48Yvg2f_Z:b-plm407) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/Supporting%20Files/Assets.xcassets/Kebab.imageset/Contents.json#L4)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I love me some kebab too but... what is this file doing here ?
</blockquote></details>

it's the icon we are using in custom list section header view.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh6Wi59egF-4SVTndi:-Nsh9aMh12MPkKN14K2D:b-7rl0kd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L223)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Don't forget to reenable `force_cast` if we can't avoid casting here
</blockquote></details>

done
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh2MaRAbCPao_-k5Uk:-NshAcAICm49UTjQn0fB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationSectionHeaderView.swift#L36)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The "Kebab" menu is an Android idiom, we shouldn't be using this on iOS. 
Instead, we should use the `ellipsis` icon here.
```swift
button.setImage(UIImage(systemName: "ellipsis"), for: .normal)
```

From the [HIG](https://developer.apple.com/design/human-interface-guidelines/menus)
> **Append an ellipsis to a menu item’s label when people need to provide additional information before the action can complete.** The ellipsis character (…) signals that another view will open in which people can input information or make choices.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSourceProtocol.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh0CXRDvSAkOp-d3CU:-NshAefaCnYXOhYrpk9A:bc7cya1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSourceProtocol.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This, and its various implementations don't need to be `Optional`
</blockquote></details>

while we are going to use  `AllLocationDataSource` for `AddLocations` into a custom list and it doesn't have any header view it would be meaningless to keep them into datasources  then I took them into`LocationDataSource`

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1, 9 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshDdpo4tnIdZaIMOTU:-NshDdpo4tnIdZaIMOTV:b-56rkf4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L12)):*
> ```Swift
> import MullvadREST
> import MullvadTypes
> import UIKit
> ```

Unless other changes were made to the code, this import shouldn't be needed.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshDnEwE_0DIc9S3GUD:-NshDnEwE_0DIc9S3GUE:b-56rkf4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L13)):*
> ```Swift
> import MullvadSettings
> import MullvadTypes
> import UIKit
> ```

Unless other changes were made to the code, this import shouldn't be needed.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshEWZW22iymaZpkilo:-NshEWZW22iymaZpkilp:b-f2ddjp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L30)):*
> ```Swift
>     private let statusIndicator: UIView = {
>         let view = UIView()
>         view.layer.cornerRadius = 16 * 0.5
> ```

Nit: Just put 8 here.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh6Wi59egF-4SVTndi:-NshFsZXA9YOt43OLFJ6:ba5atlc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L223)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

done
</blockquote></details>

Why do we handle cell creation here if it's already handled in init?

Also, swiftlint:disable:next doesn't need to be enabled again, since it's a one-off.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshFSQZ3kt0YkI5PJOE:-NshFSQZ3kt0YkI5PJOF:b-7pfh58) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L38)):*
> ```Swift
>         super.init(tableView: tableView) { _, indexPath, itemIdentifier in
>             let reuseIdentifier = LocationSection.Cell.locationCell.reuseIdentifier
>             // swiftlint:disable force_cast
> ```

// swiftlint:disable:next handles one-off cases.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 258 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshGoWa06UrAaX2KYRH:-NshGoWa06UrAaX2KYRI:b-b7xful) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L258)):*
> ```Swift
>             return .zero
>         case .customLists:
>             return 24.0
> ```

Nit: Decicmal doesn't add anything but unnecessary verbosity.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshHoQUB8L8sY_aEB6y:-NshHoQUB8L8sY_aEB6z:b-3c5z5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationSectionHeaderView.swift#L67)):*
> ```Swift
> 
>     private func apply(configuration: Configuration) {
>         let isActionHidden = (configuration.primaryAction == nil)
> ```

Nit: We usually don't have parenthesis for cases like this elsewhere in the code.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 15 files at r1, 1 of 9 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-:-NshTXB1CjorfOPrVqlg:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh6Wi59egF-4SVTndi:-NshT3vUB1jH47riIsEh:b3g8yxf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L223)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we handle cell creation here if it's already handled in init?

Also, swiftlint:disable:next doesn't need to be enabled again, since it's a one-off.
</blockquote></details>

My bad, I had misread this, indeed `disable:next` is a one off and doesn't need reenabling.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: 10 of 15 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshEWZW22iymaZpkilo:-Nshe5Fo2DNM-OurgQS-:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L30)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Just put 8 here.
</blockquote></details>

done
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsh6Wi59egF-4SVTndi:-NsheO592dOo9JeS5uzS:b-flnj3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60268d2665a1a4aaf4f9169efb4bfa4dd49e1e8c/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L223)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

My bad, I had misread this, indeed `disable:next` is a one off and doesn't need reenabling.
</blockquote></details>

reverted, I was not paying attention which is `next` rule
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshHoQUB8L8sY_aEB6y:-NshgeB-2un-mJtsaX1t:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationSectionHeaderView.swift#L67)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: We usually don't have parenthesis for cases like this elsewhere in the code.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshDdpo4tnIdZaIMOTU:-NshcnB24X8wLfQ6OA1x:b3dfa4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L12)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Unless other changes were made to the code, this import shouldn't be needed.
</blockquote></details>

I forgot to remove that, done!
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshDnEwE_0DIc9S3GUD:-NshdzgR5VIqWWrJBCDi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L13)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Unless other changes were made to the code, this import shouldn't be needed.
</blockquote></details>

Done.

**Review by rablador — COMMENTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshFSQZ3kt0YkI5PJOE:-NshqW3s5EayTu-EBHDL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

// swiftlint:disable:next handles one-off cases.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 258 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-NshGoWa06UrAaX2KYRH:-NshqTGh8ZKVSEVOHMfE:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f516098eb9884ffc3d3b44371cf99b30fefeda85/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L258)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Decicmal doesn't add anything but unnecessary verbosity.
</blockquote></details>

Done

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/InMemoryCustomListRepository.swift` line 20 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsi-AOP5BG47cksqGOu:-Nsi-AOP5BG47cksqGOv:bk8u02z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b0d2b95acd62dba96b6c408250f2f3a9542a080/ios/MullvadVPN/View%20controllers/SelectLocation/InMemoryCustomListRepository.swift#L20)):*
> ```Swift
> 
>     private var customRelayLists: [CustomList] = [
>         CustomList(id: UUID(), name: "Netflix", locations: [.city("al", "tia")]),
> ```

These ID:s need to be fixed. The problem is that the custom list id is added to the relay constraint when you select a location in a custom list, but if these ID:s change every time the location list is loaded, they don't match with the stored custom list id anymore. Meaning that the wrong item will be pre-selected.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-:-Nsi-dwV3Ws_fE8r8ZF3:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

**Review by buggmagnet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/InMemoryCustomListRepository.swift` line 20 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-Nsi-AOP5BG47cksqGOu:-Nsi0oJX4bIGOfg7YJmV:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b0d2b95acd62dba96b6c408250f2f3a9542a080/ios/MullvadVPN/View%20controllers/SelectLocation/InMemoryCustomListRepository.swift#L20)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

These ID:s need to be fixed. The problem is that the custom list id is added to the relay constraint when you select a location in a custom list, but if these ID:s change every time the location list is loaded, they don't match with the stored custom list id anymore. Meaning that the wrong item will be pre-selected.
</blockquote></details>

done

**Review by rablador — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5930#-:-NsiDeG_3f9UC6QQZPiD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
