### PR TITLE
Add javascript code formatter

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR adds a Javascript formatter to the project. The rationale behind is the same as for `rustfmt`. Unlike `rustfmt` which is nightly, `prettier` suggests pinning the exact version of it to avoid exact issues we have with `rustfmt`. 

`eslint-config-prettier` overrides `ESLint` formatting related rules, so there should be no more complaints from `ESLint` regarding formatting since `prettier` is now in charge of that.

The code can be formatted with `yarn format` and travis script has been updated to run `yarn check-format` which exits with non-zero code if source code is not formatted, just like we have it for `rustfmt`.

This PR *does not include* the re-formatted source code.

No user facing changes.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)

### CODE REVIEW

**Comment by pinkisemils** [comment]
I'd recommend not merging this until we've reformatted all of the code, otherwise build failures won't tell us much :(

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LDqSaPs6VUiZ7eEc3DG:b-i7cy7a)*

**Comment by pronebird** [comment]
I will include the formatted code either in this or subsequent one, if this PR gets approval. 

Also, that's a good time to showcase how Travis fails if there are some formatting issues. Also, I've sent a request to `prettier` to include `diff` if possible for the files that aren't properly formatted, just like `cargo fmt` does for Rust.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LDqnQF_2wbGgWrmnFZs:byz0qsm)*

**Comment by faern** [comment]
I agree with @pinkisemils. If we merge this without doing the reformat we essentially merge a PR that has failing CI. Making all subsequent stuff also fail until it is fixed.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[.eslintrc, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-LDrNHpp21rtp_SRGjpS:-LDrNHpp21rtp_SRGjpT:b4fr9f2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82bb03afc60d809c5e35a3ed6293e67699bc3825/.eslintrc#L18)):*
> ```
>     "quotes": [ "error", "single" ],
>     "linebreak-style": [ "error", "unix" ],
>     "semi": [ 2, "always" ],
> ```

prettier already does all of this?

---

*[.prettierrc.yml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-LDrNS2G0um6SgFBj3Fx:-LDrNS2G0um6SgFBj3Fy:bxrfc49) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/606b6b2c2fc145f3e3060bd74340ce1aeaaaddb1/.prettierrc.yml#L4)):*
> ```YAML
> # see: https://prettier.io/docs/en/options.html
> printWidth: 100
> tabWidth: 2
> ```

I can't comment very much on the formatter options in general. Since I'm not aware of any community de-facto standards or similar most commonly used formatting in the JS-world.

But I in general prefer 4 spaces for tabs :man_shrugging:. Mostly because it seems to be the most commonly used from the code I have read. IMO two spaces makes it too hard to vertically see which indent matches which level if there are too many lines in between.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LDrMzCZ3ssDu_Oz6GzF:b7o3it9)*

**Comment by faern** [comment]
But really awesome to finally get deterministic formatting for the JS code as well! :ok_hand: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LDrP_aQBeDN4Jt-STxg:b-hh1z3s)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.eslintrc, line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-LDrNHpp21rtp_SRGjpS:-LDrPqNU9QOB0G_rFZNR:bsek9or) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82bb03afc60d809c5e35a3ed6293e67699bc3825/.eslintrc#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

prettier already does all of this?
</blockquote></details>

ESlint only enforced these settings. So previously it would throw an error if we had, let's say, missing semicolon or invalid indentation.

With `prettier` it automatically formats the source code just like `rustfmt`, so there is no need to enforce the style anymore with `eslint`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.prettierrc.yml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-LDrNS2G0um6SgFBj3Fx:-LDrQQ8z-Aw09fGYTqZf:b5zw8bf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/606b6b2c2fc145f3e3060bd74340ce1aeaaaddb1/.prettierrc.yml#L4)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I can't comment very much on the formatter options in general. Since I'm not aware of any community de-facto standards or similar most commonly used formatting in the JS-world.

But I in general prefer 4 spaces for tabs :man_shrugging:. Mostly because it seems to be the most commonly used from the code I have read. IMO two spaces makes it too hard to vertically see which indent matches which level if there are too many lines in between.
</blockquote></details>

2 space indentation is quite popular in JS, so I decided to keep it. Historically the project used 2-space indentation. I find it appealing but if anyone objects we can change it to 4-space indentation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.prettierrc.yml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-LDrNS2G0um6SgFBj3Fx:-LDrR5cC02M4WfSBDeLq:buo5ns9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/606b6b2c2fc145f3e3060bd74340ce1aeaaaddb1/.prettierrc.yml#L4)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

2 space indentation is quite popular in JS, so I decided to keep it. Historically the project used 2-space indentation. I find it appealing but if anyone objects we can change it to 4-space indentation.
</blockquote></details>

We'll let @jvff and @pinkisemils have a say what they think. They will likely be working in that codebase more than me and should thus have more saying on the matter. I mostly thought it was good to bring the discussion up before we create the huge diff that will come out of automatic formatting.

For almost all formatting debates I vote on what is the most standard and goes towards consistency. So if you by "quite popular" mean that >80% of the JS code out there uses 2 spaces, then I think we should also stick to 2 spaces. But if 2 space JS in the wild is more like <60% then I don't think the JS community itself has a strong enough consensus and we should lean towards what the dev community as a whole is used to. Which in my experience is 4 spaces, but that is only my perception, and might not fully reflect reality. It would also be consistent with the Rust code (which I don't think we should change, for the same reason as above), and also with OpenVPN.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by pinkisemils** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.prettierrc.yml, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-LDrNS2G0um6SgFBj3Fx:-LDuq548D5okLB2iqBlZ:b-ob32g7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/606b6b2c2fc145f3e3060bd74340ce1aeaaaddb1/.prettierrc.yml#L4)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We'll let @jvff and @pinkisemils have a say what they think. They will likely be working in that codebase more than me and should thus have more saying on the matter. I mostly thought it was good to bring the discussion up before we create the huge diff that will come out of automatic formatting.

For almost all formatting debates I vote on what is the most standard and goes towards consistency. So if you by "quite popular" mean that >80% of the JS code out there uses 2 spaces, then I think we should also stick to 2 spaces. But if 2 space JS in the wild is more like <60% then I don't think the JS community itself has a strong enough consensus and we should lean towards what the dev community as a whole is used to. Which in my experience is 4 spaces, but that is only my perception, and might not fully reflect reality. It would also be consistent with the Rust code (which I don't think we should change, for the same reason as above), and also with OpenVPN.
</blockquote></details>

I'd prefer not to change the current 2-space indentation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by jvff** [comment]
Review status: 3 of 106 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by jvff** [comment]
Review status: 3 of 106 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by faern** [comment]
Review status: 16 of 106 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197)*

**Comment by faern** [comment]
I checked out the commit before the reformatting and tried `yarn format` myself. To verify I ended up with the same result. I did, so it seems correct and all :+1:

If all of you are happy with the formatter settings themselves I say :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LDxL18e4tCTSk8N2zjS:becobd9)*

**Comment by pronebird** [comment]
I'll wait for Janito to vote on this.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LE9x5ev3BWMjyiK4tRI:b-paed2q)*

**Comment by jvff** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/197#-:-LEELWSjCbOTkvA1X1j8:bnfp4nl)*

**Pull request merged**
