### PR TITLE
Add tests for custom bridge GUI

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds tests for the custom bridge GUI. When implementing the tests I also noticed that the bridge type wasn't set to normal when "Automatic was selected". This has also been fixed in this PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136)

### CODE REVIEW

**Comment by raksooo** [comment]
Test results: https://github.com/mullvad/mullvadvpn-app/actions/runs/8701557921

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts` line 86 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkBA8yCcuavSnX1ZQG:-NvkBA8yCcuavSnX1ZQH:b4z4e5q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f90b2025529209183933f09591eb466fae0e9bad/gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts#L86)):*
> ```XML
> 
>   await inputs.nth(1).fill('443');
>   await expect(addButton).toBeEnabled();
> ```

Is there a particular reason why `'443'` is hardcoded here? Can we use `SHADOWSOCKS_SERVER_PORT` instead? :blush:



_Code quote:_
```XML
  await inputs.nth(1).fill('443');
  await expect(addButton).toBeEnabled();
```
___
*[`test/test-manager/src/tests/helpers.rs` line 256 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkBmXd5X6NRKc8iaMX:-NvkBmXd5X6NRKc8iaMY:b-9lxpfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59b9af1e67e0dec8163be763170c878e3899b1c2/test/test-manager/src/tests/helpers.rs#L256)):*
> ```XML
> /// This will first check whether we are logged in. If not, it will also try to login
> /// on your behalf. If this function returns with any errors, it means that we are logged in
> /// to.
> ```

Reading my own comment here is painful, I must have been so tired :joy:

Anyway, I think this comment is misleading. It should say "If this function returns *without* any errors, we are logged in to a valid account" or something along those lines :blush:



_Code quote:_
```XML
/// This will first check whether we are logged in. If not, it will also try to login
/// on your behalf. If this function returns with any errors, it means that we are logged in
/// to.
```
___
*[`test/test-manager/src/tests/ui.rs` line 209 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkD8_x57wG7l7oYKvH:-NvkD8_x57wG7l7oYKvI:b-bba4e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5fd2ae7df999f8de9b05374c0523e7b2c6221f5/test/test-manager/src/tests/ui.rs#L209)):*
> ```XML
>     )
>     .await
>     .map_err(|_| Error::DaemonNotRunning)??;
> ```

Tip Cleaning up modified environment variables should no longer be necessary as of [this commit](https://github.com/mullvad/mullvadvpn-app/commit/9531b3085b3831108fee3e4d7a8563ac79dc4225).

If you have seen issues related to this lately, please file a bug report about it :blush:



_Code quote:_
```XML
    // Reset the `api-override` feature.
    tokio::time::timeout(
        std::time::Duration::from_secs(60),
        rpc.set_daemon_environment(helpers::get_app_env()),
    )
    .await
    .map_err(|_| Error::DaemonNotRunning)??;
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts` line 86 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkBA8yCcuavSnX1ZQG:-NvlZ6Oo3_Sh12Rl3HjR:b-sdrj02) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f90b2025529209183933f09591eb466fae0e9bad/gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts#L86)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Is there a particular reason why `'443'` is hardcoded here? Can we use `SHADOWSOCKS_SERVER_PORT` instead? :blush:
</blockquote></details>

I used `443` since in a later test we edit the method and I wanted something to change in the edit :laughing: We never actually connect so we could use bogus values as well.
___
*[`test/test-manager/src/tests/helpers.rs` line 256 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkBmXd5X6NRKc8iaMX:-Nvl_fUiANLtlojkPd4Y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59b9af1e67e0dec8163be763170c878e3899b1c2/test/test-manager/src/tests/helpers.rs#L256)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Reading my own comment here is painful, I must have been so tired :joy:

Anyway, I think this comment is misleading. It should say "If this function returns *without* any errors, we are logged in to a valid account" or something along those lines :blush:
</blockquote></details>

Done.
___
*[`test/test-manager/src/tests/ui.rs` line 209 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkD8_x57wG7l7oYKvH:-Nvl_gqR0oinW_F-o91S:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5fd2ae7df999f8de9b05374c0523e7b2c6221f5/test/test-manager/src/tests/ui.rs#L209)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Tip Cleaning up modified environment variables should no longer be necessary as of [this commit](https://github.com/mullvad/mullvadvpn-app/commit/9531b3085b3831108fee3e4d7a8563ac79dc4225).

If you have seen issues related to this lately, please file a bug report about it :blush:
</blockquote></details>

Done.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 8 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts` line 86 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136#-NvkBA8yCcuavSnX1ZQG:-NvpAQDk1r0spx9Rvxba:b-11hobv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f90b2025529209183933f09591eb466fae0e9bad/gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts#L86)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I used `443` since in a later test we edit the method and I wanted something to change in the edit :laughing: We never actually connect so we could use bogus values as well.
</blockquote></details>

Alright!

**Pull request merged**
