### PR TITLE
Use gRPC (tonic) for the management interface

### PR DESCRIPTION
**Pull request by dlon**
This gets rid of JSON-RPC from the project. The crates used weren't being maintained and caused multiple issues. It also aids in migrating completely from tokio 0.1 to tokio 0.2.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 6 files at r23, 4 of 6 files at r27, 1 of 5 files at r29.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 50 of 57 files reviewed, 9 unresolved discussions (waiting on @dlon, @faern, @pinkisemils, and @raksooo)

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r31, 1 of 5 files at r33.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 48 of 57 files reviewed, 5 unresolved discussions (waiting on @dlon, @faern, @pinkisemils, and @raksooo)

___
*[gui/src/main/daemon-rpc.ts, line 136 at r33](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946#-MF4OxD5BY3Y8HGv_lzx:-MF4OxD62H4BWp9lKjZU:b-7rwbsc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a8e497c4f1e82db200195d5c2077e4f5acc3a50a/gui/src/main/daemon-rpc.ts#L136)):*
> ```XML
>   private nextSubscriptionId = 0;
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
>   private subscriptions: Map<number, grpc.ClientReadableStream<any>> = new Map();
> ```

It should be possible to replace this `any` with `grpcTypes.DaemonEvent` right?

**Review by raksooo — COMMENTED** [review]
> Reviewed 2 of 5 files at r33.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 50 of 57 files reviewed, 5 unresolved discussions (waiting on @dlon, @faern, @pinkisemils, and @raksooo)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 47 of 56 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, @pinkisemils, and @raksooo)

___
*[mullvad-daemon/src/management_interface.rs, line 1257 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946#-MCuiBe3D9b8FDvrcZDa:-MEcv_6aEFu2JPmVkbPE:bpsoplp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/31c9b04cb3489481d576e1b25e1f056c96d56569/mullvad-daemon/src/management_interface.rs#L1257)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Doing this kind of computation here feels a bit misplaced. :thinking: 

It has long been problematic IMO how this setting is exposed to frontends. The frontends can't see what the default is. So whenever the default is set it can only print "default" but no word on what that value is. And the fact that `None` means default but `Some(0)` means disabled is also quite confusing IMO.

Regardless of this computation here I think we need to improve so frontends can always get the current value *and* know what the default is. It would be better if the request for this setting returned the current value and the default value.
</blockquote></details>

The computation is gone.

As for the other suggestions, the current state of this is the same as before, so I think this is fine for now. But on `None` vs. `Some(0)`: Distinguishing between the actual default and `None` is useful, e.g. so that we can change the default value and not have it overridden by the settings. If a user explicitly sets 7 days as the interval, it *should* override any changes to the default, but not if the interval is `None`.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r36.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 48 of 56 files reviewed, 6 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[gui/src/main/daemon-rpc.ts, line 240 at r36](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946#-MF5VXikBZc2RENcVgJL:-MF5VXikBZc2RENcVgJM:bq6cvge) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13bca1ffa8514ffc469cff961d12bab4dddd8b88/gui/src/main/daemon-rpc.ts#L240)):*
> ```XML
>           }),
>         );
>         this.setChannelCallback(currentState);
> ```

`setChannelCallback` is called in both `connect` and here, won't the number of listeners double on each disconnect?
___
*[gui/src/main/daemon-rpc.ts, line 241 at r36](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946#-MF5UzzB0tQKcf8zOFLE:-MF5UzzB0tQKcf8zOFLF:brrkffq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13bca1ffa8514ffc469cff961d12bab4dddd8b88/gui/src/main/daemon-rpc.ts#L241)):*
> ```XML
>         );
>         this.setChannelCallback(currentState);
>       } else if (!wasConnected && currentState == grpc.connectivityState.READY) {
> ```

Nitpick: Replace all usages of `==` with `===`.
___
*[gui/src/main/daemon-rpc.ts, line 550 at r36](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946#-MF5Vw2V-zQaR08O2b3C:-MF5Vw2V-zQaR08O2b3D:b-768ec1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13bca1ffa8514ffc469cff961d12bab4dddd8b88/gui/src/main/daemon-rpc.ts#L550)):*
> ```XML
>     });
> 
>     const removeSubscription = () => {
> ```

Nitpick: Code duplication between `removeSubscription` and `unsubscribeDaemonEventListener`

**Review by dlon — COMMENTED** [review]
> Reviewed 7 of 43 files at r1, 3 of 19 files at r2, 1 of 5 files at r5, 6 of 33 files at r7, 4 of 8 files at r8, 16 of 22 files at r9, 2 of 5 files at r17, 3 of 10 files at r19, 1 of 7 files at r22, 6 of 6 files at r38, 2 of 5 files at r40, 1 of 4 files at r42, 6 of 6 files at r43.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 41 of 57 files reviewed, 4 unresolved discussions (waiting on @dlon)

**Review by raksooo — COMMENTED** [review]
> Reviewed 2 of 6 files at r38, 2 of 5 files at r40, 1 of 6 files at r43.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 46 of 57 files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r44.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 46 of 57 files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 46 of 57 files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 1 files at r44.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 47 of 57 files reviewed, all discussions resolved (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> Reviewed 6 of 6 files at r46, 2 of 5 files at r48, 1 of 4 files at r50, 6 of 6 files at r51.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1946)* status: 41 of 57 files reviewed, all discussions resolved (waiting on @dlon)

**Review by pinkisemils — APPROVED** [review]

**Pull request merged**
