### PR TITLE
Update go to version 1.21.3 and wireguard go to 20230223181233

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)

### CODE REVIEW

**Comment by faern** [comment]
Make sure to either sync fully with the iOS team and/or make sure you don't touch what version of this they use.

**Comment by Pururun** [comment]
> Make sure to either sync fully with the iOS team and/or make sure you don't touch what version of this they use.

@pinkisemils says that it should be fine.

**Review by dlon — COMMENTED** [review]
:lgtm: except for the outdated Linux container.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-:-NlSESsBAI5cDzSiaBpU:b-rjq0p9)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`wireguard/libwg/go.sum` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NlSFwQ_9vocgCBKmbFX:-NlSFwQ_9vocgCBKmbFY:bs29dvn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/def90ab95c1ce509541de13ad1ae53ff81caa9b2/wireguard/libwg/go.sum#L6)):*
> ```
> golang.org/x/net v0.0.0-20220809184613-07c6da5e1ced/go.mod h1:YDH+HFinaLZZlnHAfSS6ZXJJ9M9t4Dl22yv3iI2vPwk=
> golang.org/x/sys v0.0.0-20220808155132-1c4a2a72c664 h1:v1W7bwXHsnLLloWYTVEdvGvA7BHMeBYsPcF0GLDxIRs=
> golang.org/x/sys v0.0.0-20220808155132-1c4a2a72c664/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
> ```

Can these old entries be pruned?

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/docker/goruntime-boottime-over-monotonic.diff` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NlSMvhg7CwpI2WCq0um:-NlSMvhg7CwpI2WCq0un:b-ifkogg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/def90ab95c1ce509541de13ad1ae53ff81caa9b2/android/docker/goruntime-boottime-over-monotonic.diff#L1)):*
> ```Diff
> From 61f3ae8298d1c503cbc31539e0f3a73446c7db9d Mon Sep 17 00:00:00 2001
> ```

Can you either make sure we only have a single copy of the patch file or create a new issue for that? :pray:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @dlon)

___
*[`android/docker/goruntime-boottime-over-monotonic.diff` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NlSMvhg7CwpI2WCq0um:-NlSNt58C6XbQ0jtGwIg:b-lspxwa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/def90ab95c1ce509541de13ad1ae53ff81caa9b2/android/docker/goruntime-boottime-over-monotonic.diff#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can you either make sure we only have a single copy of the patch file or create a new issue for that? :pray:
</blockquote></details>

I could probably look into that.
___
*[`wireguard/libwg/go.sum` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NlSFwQ_9vocgCBKmbFX:-NlSNqvjB4AzQwRRwHw8:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/def90ab95c1ce509541de13ad1ae53ff81caa9b2/wireguard/libwg/go.sum#L6)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can these old entries be pruned?
</blockquote></details>

Done

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/docker/goruntime-boottime-over-monotonic.diff` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NlSMvhg7CwpI2WCq0um:-Nn9WCqs1oA_j0P5zdoU:b-sgguxi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/def90ab95c1ce509541de13ad1ae53ff81caa9b2/android/docker/goruntime-boottime-over-monotonic.diff#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I could probably look into that.
</blockquote></details>

Added issue here:
https://linear.app/mullvad/issue/DROID-611/use-only-one-goruntime-boottime-over-monotonicdiff-file

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NnF4qMz05MN2jnugYoB):*
Can this commit be a bit clarified and/or split since we have many commits related to bumping these version?



_Code quote:_
```
Update go to version 1.21.3 and wireguard go to 20230223181233
```
___
*[`building/android-container-image.txt` line 1 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NnF3cc88ItXbuQFhzuZ:-NnF3cc88ItXbuQFhzu_:b-p6pnnr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a3221282dff77c013fb7e1969f2fc36aed52ff27/building/android-container-image.txt#L1)):*
> ```help
> ghcr.io/mullvad/mullvadvpn-app-build-android:169361256
> ```

Can this be moved to a separate commit with a subject similar to the linux container bump?



_Code quote:_
```help
169361256
```

**Review by albin-mullvad — COMMENTED** [review]
Except for cleaning up the commits a bit this looks good! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-:-NnF6QA99OIqkhh5wvvT:ba87rwm)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @dlon, and @pinkisemils)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NnF4qMz05MN2jnugYoB):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this commit be a bit clarified and/or split since we have many commits related to bumping these version?
</blockquote></details>

Split into 4 different commits
___
*[`building/android-container-image.txt` line 1 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NnF3cc88ItXbuQFhzuZ:-NnGR7TL-WxhMPPYE-x4:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a3221282dff77c013fb7e1969f2fc36aed52ff27/building/android-container-image.txt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be moved to a separate commit with a subject similar to the linux container bump?
</blockquote></details>

Done

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-:-NnIWZpzEqLWGLbo33KS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-NnF4qMz05MN2jnugYoB):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Split into 4 different commits
</blockquote></details>

Nice! :thumbsup:

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559#-:-NnIfpzO8SphuFqRArZ-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
