### PR TITLE
Disconnect provider and ownership

### PR DESCRIPTION
**Pull request by Rawa**
This PR changes the one-to-one relationship to one-to-many between provider and ownership.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
:star: 

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-:-OEVBPydBx2qJFEVUMAV:bjpn40d)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVACLW30z3_75a5L99:-OEVACLW30z3_75a5L9A:behmm2h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L60)):*
> ```Kotlin
>                             Ownership.entries
>                         } else {
>                             Ownership.entries.filter { ownership ->
> ```

I think this could be simplified and be more like this:
```
allProviders.filter { it.providerId in selectedProviders }
                     .flatMap { it.ownership }
                     .distinct()
```
Could probably improve on the flatmap as well.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVAoGcAfwsS5J4NzQq:-OEVAoGcAfwsS5J4NzQr:bpnufdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L107)):*
> ```Kotlin
>     fun onApplyButtonClicked() {
>         val newSelectedOwnership = selectedOwnership.value.toOwnershipConstraint()
>         // TODO should be all providers?!
> ```

Could do something like
`availableProvidersUseCase.invoke().first()`
maybe?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: 5 of 16 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVACLW30z3_75a5L99:-OEW8SMe1CWDk-LMvvyc:br0meyy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L60)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think this could be simplified and be more like this:
```
allProviders.filter { it.providerId in selectedProviders }
                     .flatMap { it.ownership }
                     .distinct()
```
Could probably improve on the flatmap as well.
</blockquote></details>

Fixed by reworking data.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: 5 of 16 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVAoGcAfwsS5J4NzQq:-OEW8_D4BwWDN5h040WI:b-uu4gs2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L107)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Could do something like
`availableProvidersUseCase.invoke().first()`
maybe?
</blockquote></details>

Simplified in new version.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVAoGcAfwsS5J4NzQq:-OEYA5Xg1snoIKO54cV2:b-jvhgns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L107)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Simplified in new version.
</blockquote></details>

Do we actually need allProviders in the ui state?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVAoGcAfwsS5J4NzQq:-OEYAn9E-JMZBbgVEZ4O:b-yr4zh3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L107)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Do we actually need allProviders in the ui state?
</blockquote></details>

We need it to see if all providers are selected.
```
    val isAllProvidersChecked = allProviders.size == selectedProviders.size
```

We could use the `providersToOwnershipUseCase` here to get the full list of providers, but we would still need it in the UI state.

**Review by Pururun — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-:-OEYDvYz21LgezIeQ0n1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEVAoGcAfwsS5J4NzQq:-OEYDtFyChvn-H5eRkWx:ba3cnpp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0419765090dd4c45f96b7646b67191b744a8e41/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt#L107)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We need it to see if all providers are selected.
```
    val isAllProvidersChecked = allProviders.size == selectedProviders.size
```

We could use the `providersToOwnershipUseCase` here to get the full list of providers, but we would still need it in the UI state.
</blockquote></details>

Right, then all good!

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r1, 3 of 11 files at r2, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCaseTest.kt` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYUaBn8SxFr6Zdx-A7:-OEYUaBn8SxFr6Zdx-A8:b-9hsf3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04d9fb784d8ec0e3434101b0270686e39aad68f5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCaseTest.kt#L25)):*
> ```Kotlin
> 
>     private val mockRelayListFilterRepository: RelayListFilterRepository = mockk()
>     private val mockProvidersOwnershipUseCase: ProviderToOwnershipsUseCase = mockk()
> ```

nit: `mockProviderToOwnershipsUseCase`



_Code quote:_
```Kotlin
ProvidersOwnership
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYWDFl9AVln-PkYLAs:-OEYWDFl9AVln-PkYLAt:bkw0tok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04d9fb784d8ec0e3434101b0270686e39aad68f5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt#L65)):*
> ```Kotlin
>                                 true
>                             } else {
>                                 providerOwnershipRelationship[providerId]!!.contains(
> ```

Is this safe? E.g. what if a provider is used as a constraint is later removed from the relay list? 



_Code quote:_
```Kotlin
!!
```

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYXjvr3y6FcuJuPmXH:-OEYXjvr3y6FcuJuPmXI:b-22mno) (no related file):*
Don't forget to update the changelog!

**Review by Pururun — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: 24 of 25 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYWDFl9AVln-PkYLAs:-OEYfqmFAzh8MMVxxTEg:btlmztp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04d9fb784d8ec0e3434101b0270686e39aad68f5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this safe? E.g. what if a provider is used as a constraint is later removed from the relay list?
</blockquote></details>

Addressed. Was not safe.

**Review by Pururun — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYWDFl9AVln-PkYLAs:-OEYi9j099JPjyeBoCzB:b2jpy2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04d9fb784d8ec0e3434101b0270686e39aad68f5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt#L65)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Addressed. Was not safe.
</blockquote></details>

Nice! :thumbsup: 

Can we add some unit test to somehow cover this case as well? Basically something like:

* Set a provider in the provider filter
* Change the underlying relay list
* Ensure that the provider is part of the removed relays

Might even be easier ways to achieve this :thinking: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt` line 69 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYi8nt9QZxTSoa75XN:-OEYi8nt9QZxTSoa75XO:b2ni8l0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39388cfdd5349023bdeed7d31fcb837886271751/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt#L69)):*
> ```Kotlin
>                                 // so it is visible for the user. Because we won't know what
>                                 // ownerships it
>                                 // had
> ```

nit



_Code quote:_
```Kotlin
                                // ownerships it
                                // had
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYWDFl9AVln-PkYLAs:-OEZ8Eek0iiXGLRMQ5_L:b-vgu0e8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/04d9fb784d8ec0e3434101b0270686e39aad68f5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nice! :thumbsup: 

Can we add some unit test to somehow cover this case as well? Basically something like:

* Set a provider in the provider filter
* Change the underlying relay list
* Ensure that the provider is part of the removed relays

Might even be easier ways to achieve this :thinking:
</blockquote></details>

I believe @Pururun fixed tests
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt` line 69 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-OEYi8nt9QZxTSoa75XN:-OEZ8J1nBoylVzkPp4Th:bx3iq6m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39388cfdd5349023bdeed7d31fcb837886271751/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt#L69)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit
</blockquote></details>

Addressed

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386#-:-OEZ8WjY2oZNp26l5MD7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
