### PR TITLE
Increase ripple contrast

### PR DESCRIPTION
**Pull request by Rawa**
Fixes: DROID-720

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

Looks much more clear when using DPAD/focus navigation, so I suggest we go ahead with this improvement!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911#-:-Nsgy_8VEcJ56Rx3bJYy:b-sh9t3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
@Rawa please update the changelog as well

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911#-:-NshViu30Cnv4--UhoRE:b-ri30cs)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
@albin-mullvad Updated! :+1: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911#-:-NsiBZonEdD5vah3B1Y0:b-ef153t)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`CHANGELOG.md` line 43 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911#-NsiBfcGENOZKUYI-kJV:-NsiBfcH5Axx0Y2q5LM3:b4dth67) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b7486b619d7f2f86e2c5b194a65a689a0fb43f2/CHANGELOG.md#L43)):*
> ```Markdown
> #### Android
> - Migrate to Compose Navigation which also improves screen transition animations.
> - Increase focus highlight opacity
> ```

nit: end with a dot

**Pull request merged**
