### PR TITLE
Make sure all settings are cleared in between E2E tests.

### PR DESCRIPTION
**Pull request by hulthe**
I noticed the `cleanup_after_test` seemed to omit a few settings, namely:
- `api_access_methods`
- `relay_overrides`
- `custom_lists`

So I added those to the cleanup function.

I also noticed that `clear_split_tunnel_processes` and `clear_split_tunnel_apps` were gated behind `#[cfg(target_os)]`, which doesn't seem right since that only checks the host machine, not the test runner. So I removed the cfg gate, hopefully that doesn't break anything.

Lastly, I added a GRPC call to clear all the custom API access methods, mostly to support the cleanup function. This may be overkill.

Update: Added a GRPC call to clear custom lists as well

## TODO
- [x] Test the new GRPC calls
  - [ ] <del>(maybe add a new e2e test? woah, meta.)</del>
- [x] Test all the tests
- [x] Test all the tests on a Mac host
- [x] Make sure I haven't broken Android
- [ ] <del>Maybe add cli command to reset access methods?</del>
- [ ] <del>Maybe add cli command to clear custom lists?</del>

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6099)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
I think it makes perfect sense.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6099#-:-Nv39hDg-asmbQL3vPOB:bdb11sp)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`mullvad-types/src/access_method.rs` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6099#-Nv39yPT1aI78zBunJy2:-Nv39yPT1aI78zBunJy3:b-949eqn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8af8f03366e74b21d117438987efc837f53420fb/mullvad-types/src/access_method.rs#L79)):*
> ```XML
>     /// Clear all custom access methods.
>     pub fn clear_custom(&mut self) {
>         self.custom.clear();
> ```

This needs to be followed by `self.ensure_consistent_state()`.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

I think we can wait with hooking up the new clear-{access methods, custom lists} functions to the CLI :blush:

> Reviewed 1 of 7 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6099#-:-NvByMEA6rmkFFJHsbFN:b51c9vf)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

**Comment by hulthe** [comment]
@MarkusPettersson98 I've cleaned up the commits and rebased on main. Ready for merge.

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6099)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

**Pull request merged**
