### PR TITLE
Propagate network status when there is no tunnel

### PR DESCRIPTION
**Pull request by rablador**
Network status should be propagated to tunnel status even when there is no tunnel. Without this are occassions where the app will not tell the user that the network is down.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658#-:-NUawRQy5bAgoH344RzC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658#-NUaxe1HE4jzk0ECv2Bu:-NUaxe1HE4jzk0ECv2Bv:b-x64hvh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29d6e4793b199191932f4ccf731c8bb579ada9cc/ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift#L113)):*
> ```Swift
>                 interactor.updateTunnelStatus { tunnelStatus in
>                     tunnelStatus = TunnelStatus()
>                     tunnelStatus.state = .disconnecting(.nothing)
> ```

FYI: I thought this could be changed to account for smoother transition to disconnected state when the tunnel is up but we're in airplane mode:

```
tunnelStatus.state = pathStatus == .unsatisfied
                        ? .waitingForConnectivity(.noNetwork)
                        : .disconnecting(.nothing)
```

but the problem is, path monitor usually reports `requiresConnection` at that point as the tunnel hasn't shutdown entirely at this point yet.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658#-NUaxe1HE4jzk0ECv2Bu:-NUb0AQMCoGtj9I4huUt:b-c8r6xp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d9383a58c5997b6cfa9f1d9645062f877e9926f4/ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift#L113)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI: I thought this could be changed to account for smoother transition to disconnected state when the tunnel is up but we're in airplane mode:

```
tunnelStatus.state = pathStatus == .unsatisfied
                        ? .waitingForConnectivity(.noNetwork)
                        : .disconnecting(.nothing)
```

but the problem is, path monitor usually reports `requiresConnection` at that point as the tunnel hasn't shutdown entirely at this point yet.
</blockquote></details>

Maybe we could packet tunnel's connectivity status here though!

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658#-NUaxe1HE4jzk0ECv2Bu:-NUcHvZS7nIQKM4F8iYo:b-iuhqv2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d9383a58c5997b6cfa9f1d9645062f877e9926f4/ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift#L113)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we could packet tunnel's connectivity status here though!
</blockquote></details>

Yep, works well!

**Pull request merged**
