### PR TITLE
Port download link removal to main

### PR DESCRIPTION
**Pull request by sabercodic**
Fixes: DROID-209

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 129 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-N_h9Nkf6HUvkXl7gXG-:-N_h9NkgCyRqZcLypDxt:b-egkwch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4e8a9e311acb240f5e32e59005aa2a3cd5b3c7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L129)):*
> ```Kotlin
>                             )
>                         }
>                     },
> ```

I believe it makes sense to skip making it clickable/focusable.



_Code quote:_
```Kotlin
                    onClick = {
                        if (BuildConfig.BUILD_TYPE != BuildTypes.RELEASE) {
                            context.openLink(
                                Uri.parse(
                                    context.resources
                                        .getString(R.string.download_url)
                                        .appendHideNavOnReleaseBuild()
                                )
                            )
                        }
                    },
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-N_h99UX2dKHLxwliEbM:-N_h99UX2dKHLxwliEbN:ba3hwyx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4e8a9e311acb240f5e32e59005aa2a3cd5b3c7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt#L44)):*
> ```Kotlin
> 
>             shouldShow = true
>             if (BuildTypes.RELEASE == BuildConfig.BUILD_TYPE) {
> ```

Invert order



_Code quote:_
```Kotlin
BuildTypes.RELEASE == BuildConfig.BUILD_TYPE
```

**Review by sabercodic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-:-N_hOhtv8e4-zhT2sg1G:bnfp4nl)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-N_hZnTj12C5cxgztD15:-N_hZnTj12C5cxgztD16:b-hgy5d4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90d2d76b58e6f02f103a11c48e3cd59c28f66a12/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt#L92)):*
> ```Kotlin
>         text = title,
>         style = MaterialTheme.typography.titleMedium,
>         modifier = modifier,
> ```

Why was this necessary to add? Also, was there a reason to placing it between the `style` and `color` argument? I'm asking since the order can sometimes be significant



_Code quote:_
```Kotlin
modifier = modifier,
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-N_hZnTj12C5cxgztD15:-N_i1ltE4gBLO31prM4_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90d2d76b58e6f02f103a11c48e3cd59c28f66a12/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why was this necessary to add? Also, was there a reason to placing it between the `style` and `color` argument? I'm asking since the order can sometimes be significant
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-:-N_i2vsQ1FMiCrVzuDDK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 139 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-N_iLP078VfyAyFGP7HH:-N_iLP078VfyAyFGP7HI:b-ey4rc5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5eca9846d7e81bfbbf85425b9e83f89dbdccd10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L139)):*
> ```Kotlin
>                             } else {
>                                 Text(
>                                     text = uiState.appVersion.uppercase(),
> ```

The version should not be uppercase.



_Code quote:_
```Kotlin
uppercase()
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 139 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908#-N_iLP078VfyAyFGP7HH:-N_iQfn-8Em58KweXsdt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5eca9846d7e81bfbbf85425b9e83f89dbdccd10/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L139)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The version should not be uppercase.
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4908)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
