### PR TITLE
Add known issues documentation

### PR DESCRIPTION
**Pull request by faern**
This PR adds a dedicated known security and privacy issues document. This takes the known issues we had in the `security.md` document along with issues spread out in various other places and aims to consolidate them in one publicly accessible document.

The aim of doing this is to:
* Be more transparent to our users about known problems affecting our app and service. We usually blog about these things. But blogs are more ephemeral. All known privacy and security issues should be kept in this document for as long as they still affect the app and its users.
* Consolidate a bunch of spread out sources into one easier to digest list of issuses.
* Gather all known information on an issue in a single place. Such as links to blog posts about it and upstream bug reports.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: 0 of 2 files reviewed, 2 unresolved discussions

___
*[`docs/known-issues.md` line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9KgMdT9AvFxXmzfJHl:-O9KgMdU5w3Jjz1BDlnV:bchovec) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b7f2e600fbb0a9dbd390ad55e4c9d6a41d5c9d5/docs/known-issues.md#L163)):*
> ```Markdown
> * October ????, 2024 - We observe this behavior by accident after a macOS upgrade
> * October 15(????), 2024 - We report the issue upstream to Apple.
>   No public issue tracker is available.
> ```

@raksooo Please help me with the details here :)
___
*[`docs/security.md` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9KgSzp5NgSziSQuQyT:-O9KgSzp5NgSziSQuQyU:b-91hp3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b7f2e600fbb0a9dbd390ad55e4c9d6a41d5c9d5/docs/security.md#L65)):*
> ```Markdown
> 
> - [Incorrect VPN lockdown documentation](https://issuetracker.google.com/issues/249990229)
> - [Add option to disable connectivity checks when VPN lockdown is enabled](https://issuetracker.google.com/issues/250529027)
> ```

@albin-mullvad I suggest we move all of these "leaks" or known special cases where traffic goes outside the tunnel to the known issues document as well. Do you agree or do you have a better idea?

If we see the security document as "threat model and roughly how the app upholds these guarantees" and the known issues document as "list of temporary or semi-permanent exceptions to the security document", then I think they belong better in the known issues document.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: 0 of 2 files reviewed, 2 unresolved discussions

___
*[`docs/security.md` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9Kgy2QB8IU89aH4RzT:-O9Kgy2QB8IU89aH4RzU:bahgvte) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a06592ba05a2e7cc56261532fdfda2688fef204/docs/security.md#L77)):*
> ```Markdown
> that all traffic should flow through the tunnel, the same way it works on Android.
> 
> The iOS app currently does not support blocking in the app's blocked state.
> ```

FYI: Unrelated to the known issues move, but outdated information

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`docs/known-issues.md` line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9KgMdT9AvFxXmzfJHl:-O9On9EE9ZeGtCLKpNjn:b-nw5t6l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b7f2e600fbb0a9dbd390ad55e4c9d6a41d5c9d5/docs/known-issues.md#L163)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

@raksooo Please help me with the details here :)
</blockquote></details>

I'm a bit unsure about when we first observed it. I'll ask the team.
I reported it to apple on October 16 as well.
___
*[`docs/security.md` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9Olp138i3cWNgJDTn6:-O9Olp138i3cWNgJDTn7:b8z1rc0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7cf48d0c3f614784f22cbcbfe4f615f84cdd256/docs/security.md#L11)):*
> ```Markdown
> integration is implemented.
> 
> For known security and privacy issues issues, that might cause the app to not uphold the
> ```

Duplicate "issues"



_Code quote:_
```Markdown
issues issues
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`docs/security.md` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9Olp138i3cWNgJDTn6:-O9PPg3cALmOQLgyTpxs:b-i11clo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7cf48d0c3f614784f22cbcbfe4f615f84cdd256/docs/security.md#L11)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Duplicate "issues"
</blockquote></details>

Thanks. Fixed

**Review by raksooo — APPROVED** [review]
Great work! This is really nice to have and is well structured!

> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-:-O9TgoCzBePNMKG8ZyGh:b-iwf5o2)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`docs/known-issues.md` line 109 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9Tf8TZ6lwjUSL3ko45:-O9Tf8TZ6lwjUSL3ko46:bbbq3gu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/93e68e8bcf9ceb5b434539d01fbb89b35d99815c/docs/known-issues.md#L109)):*
> ```Markdown
> DNS lookups performed directly with the C function `getaddrinfo` can leak for a short period
> of time while an android VPN app is being re-configured (reconnecting, force-stopped etc).
> These leaks happens even when when the system setting "Block connections without VPN" is
> ```

Duplicate "when".



_Code quote:_
```Markdown
when when
```

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: all files reviewed, 1 unresolved discussion

___
*[`docs/known-issues.md` line 120 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9UhAFo1-wGXp4sGTqD:-O9UkQuC6RSHKZTCvlN7:b-y94rg2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4abf9d78bcd2433c9dd51d48b43fda63a2332fc1/docs/known-issues.md#L120)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: looks like different form is used for this and other timelines, e.g. "We became", "We report", "Someone reports". I'm however no grammar expert and it's not super important to address, just an observation.
</blockquote></details>

Fixed! I went with the "Mullvad ..." form on everything. Thanks for pointing it out.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @pinkisemils)

___
*[`docs/security.md` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9KgSzp5NgSziSQuQyT:-O9Ula52BoCm4aewDiuf:b-ixteod) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b7f2e600fbb0a9dbd390ad55e4c9d6a41d5c9d5/docs/security.md#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Sounds good! :thumbsup:
</blockquote></details>

Good! But I'll save that for a separate PR. Since I want this document merged for the audit. And moving those things over is not critical.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-:-O9UnKe911E_Vc-LAESy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`docs/known-issues.md` line 120 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9UhAFo1-wGXp4sGTqD:-O9Un1BO9lhIit9XJpgp:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4abf9d78bcd2433c9dd51d48b43fda63a2332fc1/docs/known-issues.md#L120)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Fixed! I went with the "Mullvad ..." form on everything. Thanks for pointing it out.
</blockquote></details>

:thumbsup: 
___
*[`docs/security.md` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6994#-O9KgSzp5NgSziSQuQyT:-O9Un6u9698g0iBoZbZQ:bht10at) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b7f2e600fbb0a9dbd390ad55e4c9d6a41d5c9d5/docs/security.md#L65)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Good! But I'll save that for a separate PR. Since I want this document merged for the audit. And moving those things over is not critical.
</blockquote></details>

Sounds good! :thumbsup:

**Pull request merged**
