### PR TITLE
Implement initial View App Logs screen

### PR DESCRIPTION
**Pull request by jvff**
On Android, there is no easy way to share the collected logs included in the problem report. On desktop, the "View App Logs" button opens a text editor to view the collected logs. On Android, files can't be shared between apps easily, and require the implementation of a File Provider. Therefore, the Android app has been without the ability to view the collected logs until now.

Recently, debugging an issue turned out problematic because the issue caused problem reports to fail to send. Therefore, the process was more complicated than it needed to be, and a way for the reported to view the logs would have saved some time. Therefore, this PR implements a simple screen to load the collected logs and show them to the user. The text is selectable, so the user can copy it all (or parts of it) to send manually if sending a problem report through the app fails.

The screen in this initial version is pretty raw, and it could be improved to have an animation while it's loading, a button to share the text (or the file using a File Provider), etc.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317#-:-MNSrMTT0JvimHEVGU-n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @jvff and @pinkisemils)

___
*[gui/src/main/index.ts, line 1442 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317#-MNU6xS9ER4IE4m7tVB5:-MNU6xSA2VEomKZ2d_wx:bfw1wxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e0b5182bbdbe1d20d69439d7851921c60980227/gui/src/main/index.ts#L1442)):*
> ```XML
>           appWindow.setVisibleOnAllWorkspaces(true);
>           app.dock.hide();
>         }
> ```

What's this change?

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[gui/src/main/index.ts, line 1442 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317#-MNU6xS9ER4IE4m7tVB5:-MNUDiWK-2n8j4xYhS0a:b-hivmy1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e0b5182bbdbe1d20d69439d7851921c60980227/gui/src/main/index.ts#L1442)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What's this change?
</blockquote></details>

I think Reviewable became confused when I forced pushed to master by accident :(

This is part of a change Oskar did (and was the tip of master at the time).

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2317)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
