### PR TITLE
allow user to switch between accounts when the account number is ente…

### PR DESCRIPTION
**Pull request by mojganii**
This PR introduces a user-friendly dialogue box designed to assist users who mistakenly input their account number instead of a voucher code during the redeeming voucher  within the account flow. This feature empowers users to seamlessly log out from their current account and effortlessly transition to an alternative account.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ndj6xu74qOi7GgnERQR:-Ndj6xu74qOi7GgnERQS:b85pvgb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift#L20)):*
> ```Swift
>     private var accountNumber: String?
>     private lazy var accountNumberInputErrorView = {
>         VerifiedAccountView {
> ```

It feels a little weird to me to provide views from coordinator to viewcontroller this way. I understand that it has been set up this way to let us reuse and patch existing `RedeemVoucherViewController` with account verification functionality, but I wonder if we could do it some other way. Maybe @buggmagnet or @pronebird has suggestions?
___
*[`ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift` line 167 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ndeya0dEHHA6lLX5dPt:-Ndeya0dEHHA6lLX5dPu:b-5oi5us) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift#L167)):*
> ```Swift
>         coordinator.didLogout = { [weak self] voucherCoordinator in
>             voucherCoordinator.removeFromParent()
>             guard let self else { return }
> ```

Nit: Move the guard to top of closure?
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VerifiedAccountView.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-NdizqsW8VJN7TO6GyaH:-NdizqsW8VJN7TO6GyaI:b-p4eug4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/View%20controllers/RedeemVoucher/VerifiedAccountView.swift#L31)):*
> ```Swift
>             tableName: "CreateAccountRedeemingVoucher",
>             value: """
>             It looks like you have entered a Mullvad account number instead of a voucher code.\
> ```

Space needed before the backslash.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VerifiedAccountView.swift` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-NdixVd02MJ4sTMuyb2O:-NdixVd02MJ4sTMuyb2P:b-4yw897) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/View%20controllers/RedeemVoucher/VerifiedAccountView.swift#L73)):*
> ```Swift
>     }
> 
>     private func configureUI() {
> ```

We could use stackviews here to handle detailed constraints. Also, simply adding the containerview without dynamic constraints gives us a smooth fade-in animation.



_Code snippet (i):_
```Swift
private func configureUI() {
    let contentStack = UIStackView(arrangedSubviews: [messageLabel, logoutButton])
    contentStack.axis = .vertical
    contentStack.spacing = UIMetrics.padding16
    contentStack.isLayoutMarginsRelativeArrangement = true
    contentStack.layoutMargins = containerView.layoutMargins

    containerView.addConstrainedSubviews([contentStack]) {
        contentStack.pinEdgesToSuperview(.all())
    }

    addConstrainedSubviews([containerView]) {
        containerView.pinEdgesToSuperview(.all())
    }

    fadeOut()
}
```



_Code snippet (ii):_
```Swift
func fadeIn() {
    animateWith(animations: {
        self.containerView.alpha = 1.0
    }, duration: 0.3, delay: 0.2)
}

func fadeOut() {
    animateWith(animations: {
        self.containerView.alpha = 0.0
    }, duration: 0.0, delay: 0.0)
}
```
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VerifiedAccountView.swift` line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-NdijUPK9mNMRb-MPUZL:-NdijUPK9mNMRb-MPUZM:b-xr0s3h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/View%20controllers/RedeemVoucher/VerifiedAccountView.swift#L124)):*
> ```Swift
>     }
> 
>     private func animateWith(
> ```

Perhaps this could be turned into an extension on UIView for use elsewhere too?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ndj6xu74qOi7GgnERQR:-Ndnx5-4DmBrTavP26BH:b-cjwzn2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift#L20)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It feels a little weird to me to provide views from coordinator to viewcontroller this way. I understand that it has been set up this way to let us reuse and patch existing `RedeemVoucherViewController` with account verification functionality, but I wonder if we could do it some other way. Maybe @buggmagnet or @pronebird has suggestions?
</blockquote></details>

I concur. I think view controller should be managing the views, coordinator should mostly be responsible for bigger picture. 

Personally I'd either configure the view controller directly or via delegate to change its behavior in regards of when voucher should be matched against account number _or_ tweak interactor and make it configurable, i.e:


```swift
struct CreateAccountVoucherInteractor {

    enum RedeemResult {
        case invalidVoucher
        case voucherIsAccountNumber
        case redeemed
    }

    var shouldMatchVoucherWithAccountNumber = false

    @MainActor
    func redeemVoucher(_ voucher: String) throws async -> RedeemResult  {
        do {
            try await submitVoucher(voucher)

            return .redeemed
        } catch let error as? REST.Error where error.compareErrorCode(.invalidVoucher) {
            guard shouldMatchVoucherWithAccountNumber else { throw error }

            do {
                _ = try await getAccountData(voucher)

                return .voucherIsAccountNumber
            }  catch let error as? REST.Error where error.compareErrorCode(.invalidAccount) {
                return .invalidVoucher
            }
        }
    }

}
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: 2 of 19 files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ndj6xu74qOi7GgnERQR:-Ne3AJAh-PU72t7kHROf:bmfxqef) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift#L20)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I concur. I think view controller should be managing the views, coordinator should mostly be responsible for bigger picture. 

Personally I'd either configure the view controller directly or via delegate to change its behavior in regards of when voucher should be matched against account number _or_ tweak interactor and make it configurable, i.e:


```swift
struct CreateAccountVoucherInteractor {

    enum RedeemResult {
        case invalidVoucher
        case voucherIsAccountNumber
        case redeemed
    }

    var shouldMatchVoucherWithAccountNumber = false

    @MainActor
    func redeemVoucher(_ voucher: String) throws async -> RedeemResult  {
        do {
            try await submitVoucher(voucher)

            return .redeemed
        } catch let error as? REST.Error where error.compareErrorCode(.invalidVoucher) {
            guard shouldMatchVoucherWithAccountNumber else { throw error }

            do {
                _ = try await getAccountData(voucher)

                return .voucherIsAccountNumber
            }  catch let error as? REST.Error where error.compareErrorCode(.invalidAccount) {
                return .invalidVoucher
            }
        }
    }

}
```
</blockquote></details>

Done...
___
*[`ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift` line 167 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ndeya0dEHHA6lLX5dPt:-Ne3AwU4EtwmWkAfu19z:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift#L167)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Move the guard to top of closure?
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VerifiedAccountView.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-NdizqsW8VJN7TO6GyaH:-Ne3B1xj9GVgCdxCbImT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/View%20controllers/RedeemVoucher/VerifiedAccountView.swift#L31)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Space needed before the backslash.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VerifiedAccountView.swift` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-NdixVd02MJ4sTMuyb2O:-Ne3BBJP2Mjs-FQjkeFa:b-b49bl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/View%20controllers/RedeemVoucher/VerifiedAccountView.swift#L73)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We could use stackviews here to handle detailed constraints. Also, simply adding the containerview without dynamic constraints gives us a smooth fade-in animation.
</blockquote></details>

It brokes constraints when the view is faded in and out.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VerifiedAccountView.swift` line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-NdijUPK9mNMRb-MPUZL:-Ne3BSJx-S8axxuMJdVZ:b-c7iz5j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad4608601a00b52fa68b9135c4520163eb75bb70/ios/MullvadVPN/View%20controllers/RedeemVoucher/VerifiedAccountView.swift#L124)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Perhaps this could be turned into an extension on UIView for use elsewhere too?
</blockquote></details>

The animation depends on layout constraints, and if these constraints are integrated into an extension, there's a strong likelihood of redundancy that ends in breaking UI

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, 4 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: 6 of 19 files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/Login/LoginContentView.swift` line 177 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3QVyiCd-JaGyDsVrz:-Ne3QVyiCd-JaGyDsVs-:b4fhp46) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/Login/LoginContentView.swift#L177)):*
> ```Swift
>     }
> 
>     private func addObservers() {
> ```

A view should not be registering to notifications to get its model data, this breaks encapsulation.
Instead, the view controller that holds this view (`LoginContentView` in this case) should be made aware via the `LoginInteractor` that there should be a "preferred account number" to fill.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3VFxZEU3gQXio-09V:-Ne3VFxZEU3gQXio-09W:b-xh7x91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L68)):*
> ```Swift
>     private func verifyVoucherAsAccount(code: String) {
>         let executer = accountsProxy.getAccountData(accountNumber: code)
>         tasks.append(executer.execute(retryStrategy: .noRetry) { [weak self] result in
> ```

You can replace this with `tasks.append(executer.execute { [weak self] result in` 
The default `execute` method already specifies `.noRetry` 



_Code quote:_
```Swift
tasks.append(executer.execute(retryStrategy: .noRetry) { [weak self] result in
```
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3VUvjC7K36mfd9LHk:-Ne3VUvjC7K36mfd9LHl:b-orqxlv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L81)):*
> ```Swift
>      Name of notification posted when current account number changes.
>      */
>     static let didChangePreferredAccountNumber = Notification
> ```

This shouldn't be broadcasting notifications about the "preferred account" being changed, instead it should bubble back this information to the Welcome `Interactor/Coordinator` (whichever has the view model that will be applied to the login view)

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: 6 of 19 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Login/LoginContentView.swift` line 177 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3QVyiCd-JaGyDsVrz:-Ne4slip-_XEE_38-NGL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/Login/LoginContentView.swift#L177)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

A view should not be registering to notifications to get its model data, this breaks encapsulation.
Instead, the view controller that holds this view (`LoginContentView` in this case) should be made aware via the `LoginInteractor` that there should be a "preferred account number" to fill.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3VFxZEU3gQXio-09V:-Ne4sr8A0ugn5DJ3fQdk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L68)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You can replace this with `tasks.append(executer.execute { [weak self] result in` 
The default `execute` method already specifies `.noRetry`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3VUvjC7K36mfd9LHk:-Ne4t1tY3EDfZowx-8lc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L81)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This shouldn't be broadcasting notifications about the "preferred account" being changed, instead it should bubble back this information to the Welcome `Interactor/Coordinator` (whichever has the view model that will be applied to the login view)
</blockquote></details>

Done.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne3iYoC1MsKfkEhQKpg:-Ne7emR84GreJx0loe4d:bb74ce2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8a5bcf22b8b1d177da83d1177ad4823b4f8b3b12/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L83)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Could this be renamed to something more consise? Perhaps "accountVerificationView" or "logoutView"?
</blockquote></details>

Sure

**Review by rablador — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r2, 8 of 8 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 48 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8AQtb4hzpM9UDXocz:-Ne8AQtb4hzpM9UDXod-:btdw9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L48)):*
> ```Swift
> 
>     /// Posts `preferredAccountNumber` notification when user inputs the account number instead of voucher code
>     private let preferredAccountNumberSubject = PassthroughSubject<String?, Never>()
> ```

The `String` type doesn't need to be optional here
___
*[`ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8DMw4E7XDzf0X_X_w:-Ne8DMw4E7XDzf0X_X_x:bib01gr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift#L25)):*
> ```Swift
> 
>     var didFinish: ((WelcomeCoordinator) -> Void)?
>     var didLogout: ((WelcomeCoordinator, String) -> Void)?
> ```

We never use the first parameter passed here in those callbacks, we should remove them. 
___
*[`ios/MullvadVPN/View controllers/Login/LoginInteractor.swift` line 17 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8BcGJ-m7VoV5yH8gq:-Ne8BcGJ-m7VoV5yH8gr:b1xkvbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN/View%20controllers/Login/LoginInteractor.swift#L17)):*
> ```Swift
>     private var tunnelObserver: TunnelObserver?
>     var didCreateAccount: (() -> Void)?
>     var doSuggestPreferredAccountNumber: ((String) -> Void)?
> ```

We can rename this `suggestPreferredAccountNumber` 
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1390 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8E0Y40YylaDwhRiM9:-Ne8E0Y40YylaDwhRiMA:bp7wr85) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN.xcodeproj/project.pbxproj#L1390)):*
> ```
> 		F07BF2612A26279100042943 /* RedeemVoucherOperation.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = RedeemVoucherOperation.swift; sourceTree = "<group>"; };
> 		F07CFF1F29F2720E008C0343 /* RegisteredDeviceInAppNotificationProvider.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = RegisteredDeviceInAppNotificationProvider.swift; sourceTree = "<group>"; };
> 		F09A29782A9F8A9B00EA3B6F /* LogoutDialogueView.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = LogoutDialogueView.swift; sourceTree = "<group>"; };
> ```

Please move `LogoutDialogueView` above the `RedeemVoucher*.swift` files

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 48 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8AQtb4hzpM9UDXocz:-Ne8PkXB0R5fslxXyNzJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L48)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The `String` type doesn't need to be optional here
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8DMw4E7XDzf0X_X_w:-Ne8Q_nQ8m752ZaW_AKY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We never use the first parameter passed here in those callbacks, we should remove them.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Login/LoginInteractor.swift` line 17 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8BcGJ-m7VoV5yH8gq:-Ne8QkYN9LvJrBGvpwtE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN/View%20controllers/Login/LoginInteractor.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can rename this `suggestPreferredAccountNumber`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1390 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-Ne8E0Y40YylaDwhRiM9:-Ne8QvX336_XeZvLc-3i:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f1d4ae3dcff71ff124398cf3ada71f9d76923f7/ios/MullvadVPN.xcodeproj/project.pbxproj#L1390)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please move `LogoutDialogueView` above the `RedeemVoucher*.swift` files
</blockquote></details>

Done.

**Review by buggmagnet — COMMENTED** [review]
very well done ! :lgtm_strong: 

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-:-Ne8myHADw-u_s4oqvOP:b-buypcy)* status: all files reviewed, 2 unresolved discussions

**Review by buggmagnet — APPROVED** [review]
I said approve, not request changes 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5119#-:-Ne8pB_m53DlHU4gvqZ5:b-kylbhb)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
