### PR TITLE
Add UI for adding and editing a custom list

### PR DESCRIPTION
**Pull request by rablador**
The user should be able to create and edit a new custom list from the UI.

To test, simply add either `AddCustomListCoordinator` or `EditCustomListCoordinator` to some button action the UI somewhere, eg.

```
let coordinator = AddCustomListCoordinator(
    navigationController: CustomNavigationController(),
    customListInteractor: CustomListInteractor(repository: CustomListRepository())
)
coordinator.start()

coordinator.didFinish = {
    coordinator.dismiss(animated: true)
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)

### CODE REVIEW

**Review by buggmagnet — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by acb-mv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0gwz18Q4pNxk11xfd:-Nr0gwz18Q4pNxk11xfe:bje2hae) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift#L98)):*
> ```Swift
>         tableView.deselectRow(at: indexPath, animated: false)
> 
>         dataSource.itemIdentifier(for: indexPath).flatMap { item in
> ```

`flatMap` (a functional operation that returns a value) used purely for side-effects can look unclear (a bit like `map` used in place of `for _ in _`). A more idiomatic alternative would be:

```swift
if let item = dataSource.itemIdentifier(for: indexPath) {
  didSelectItem?(item)
}
```
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0iGBeDVEtGNh6uhlo:-Nr0iGBeDVEtGNh6uhlp:b-re82jn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift#L26)):*
> ```Swift
> extension SettingsValidationErrorConfiguration: Equatable {
>     static func == (lhs: SettingsValidationErrorConfiguration, rhs: SettingsValidationErrorConfiguration) -> Bool {
>         lhs.errors.map { $0.errorDescription } == rhs.errors.map { $0.errorDescription }
> ```

Would it be possible to make `SettingsValidationErrorProtocol` conform to `Equatable`? Otherwise we have classes which have their own equality tests for types they contain, which could introduce bugs in the future.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0gwz18Q4pNxk11xfd:-Nr0z8ltCchv4j5JQCqS:bxt5z9i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift#L98)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

`flatMap` (a functional operation that returns a value) used purely for side-effects can look unclear (a bit like `map` used in place of `for _ in _`). A more idiomatic alternative would be:

```swift
if let item = dataSource.itemIdentifier(for: indexPath) {
  didSelectItem?(item)
}
```
</blockquote></details>

Waiting to resolve a discussion about the same thing in another PR.
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0iGBeDVEtGNh6uhlo:-Nr0zdJK-0_PmAKpVm5w:b-ku087s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift#L26)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Would it be possible to make `SettingsValidationErrorProtocol` conform to `Equatable`? Otherwise we have classes which have their own equality tests for types they contain, which could introduce bugs in the future.
</blockquote></details>

I tried, but I can't get `SettingsValidationErrorConfiguration` to conform to equatable without custom equality tests anyway.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4f5sb567BYII7YiIP:-Nr4f5sb567BYII7YiIQ:b-5piwxv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift#L54)):*
> ```Swift
>         var snapshot = dataSource.snapshot()
> 
>         validationErrors.forEach { error in
> ```

nit
Right now there's only 1 case for `CustomListFieldValidationError` which is `.name`

So we could simplify this (at some cost for readability I admit)  to
`snapshot.reloadSections(validationErrors.map { _ in .name })`

I think what begs the question is : if there's only one case for the error, does it make sense to store it as an enum ?
Here it makes the code more indirect (need to swich over cases)

This discussion is probably moot if we plan to have more than one case in the errors, but otherwise, maybe I want to ask if we couldn't turn `CustomListFieldValidationError` into a struct instead ?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListItemIdentifier.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4gfTo2a0bH6GLZgvF:-Nr4gfTo2a0bH6GLZgvG:b-lx46p2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListItemIdentifier.swift#L54)):*
> ```Swift
> 
>     static func fromFieldValidationErrors(_ errors: Set<CustomListFieldValidationError>) -> [CustomListItemIdentifier] {
>         errors.compactMap { error in
> ```

nit
Same discussion as above, we could simplify this to `errors.compactMap { _ in .name }` ?
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0iGBeDVEtGNh6uhlo:-Nr4h0bc5XnhiIqvLYYn:bygaodr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift#L26)):*
> Would it be possible to make `SettingsValidationErrorProtocol` conform to `Equatable`?

Long story short : We shouldn't, it's usually not a good idea. [This article](https://khawerkhaliq.com/blog/swift-protocols-equatable-part-one/) goes into great lengths to explain why.

It looks like to me that `SettingsValidationErrorProtocol` is not needed. The `Error` protocol already does all the required things.

Having `CustomListFieldValidationError` implement both `SettingsValidationErrorProtocol` and  `LocalizedError` is redundant. 

If you get rid of `CustomListFieldValidationError` and declare errors as such `var errors: [CustomListFieldValidationError] = []` 
You get `Equatable` on `SettingsValidationErrorConfiguration` for free 
___
*[`ios/MullvadVPNTests/CustomListRepositoryTests.swift` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4jjQJ151_URxZovSe:-Nr4jjQJ151_URxZovSf:boc0epp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPNTests/CustomListRepositoryTests.swift#L74)):*
> ```Swift
>         repository.update(streaming)
> 
>         let gaming = try XCTUnwrap(repository.create("PS5", locations: [
> ```

:warning:  `Initialization of immutable value 'gaming' was never used; consider replacing with assignment to '_' or removing it`


What are the calls to `update` meant to do ? 
If I remove them, the test still passes.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4f5sb567BYII7YiIP:-Nr4qUPI-hE33fm1iqKL:b-qakzts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift#L54)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Right now there's only 1 case for `CustomListFieldValidationError` which is `.name`

So we could simplify this (at some cost for readability I admit)  to
`snapshot.reloadSections(validationErrors.map { _ in .name })`

I think what begs the question is : if there's only one case for the error, does it make sense to store it as an enum ?
Here it makes the code more indirect (need to swich over cases)

This discussion is probably moot if we plan to have more than one case in the errors, but otherwise, maybe I want to ask if we couldn't turn `CustomListFieldValidationError` into a struct instead ?
</blockquote></details>

I've been going back and forth on this. First I thought we should just simplify things and basically "hard code" the error handling and only care about name input. But that felt a little inelegant. Now we at least have a general error handling and can add things if we want (the final designs aren't set, so who knows). Either way, we can do what you propose, since that's on the consumer side. `snapshot.reloadSections([.name])` would be even simpler.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0gwz18Q4pNxk11xfd:-Nr4ut0aBYjx1h5xHsFs:b499q7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift#L98)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Waiting to resolve a discussion about the same thing in another PR.
</blockquote></details>

Changed
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListItemIdentifier.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4gfTo2a0bH6GLZgvF:-Nr4v--gANC_cglMovNl:b-oo9t1a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListItemIdentifier.swift#L54)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Same discussion as above, we could simplify this to `errors.compactMap { _ in .name }` ?
</blockquote></details>

If we want a general error handling I think we shouldn't make changes like this on the "producer" side.
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr0iGBeDVEtGNh6uhlo:-Nr4y0Eo43-_wQeUqa3K:b-w4dm0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift#L26)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> Would it be possible to make `SettingsValidationErrorProtocol` conform to `Equatable`?

Long story short : We shouldn't, it's usually not a good idea. [This article](https://khawerkhaliq.com/blog/swift-protocols-equatable-part-one/) goes into great lengths to explain why.

It looks like to me that `SettingsValidationErrorProtocol` is not needed. The `Error` protocol already does all the required things.

Having `CustomListFieldValidationError` implement both `SettingsValidationErrorProtocol` and  `LocalizedError` is redundant. 

If you get rid of `CustomListFieldValidationError` and declare errors as such `var errors: [CustomListFieldValidationError] = []` 
You get `Equatable` on `SettingsValidationErrorConfiguration` for free
</blockquote></details>

Removed the protocol in favor of the concrete type.
___
*[`ios/MullvadVPNTests/CustomListRepositoryTests.swift` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4jjQJ151_URxZovSe:-Nr4yPRK3CWrsdSylgMK:bcj83jx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPNTests/CustomListRepositoryTests.swift#L74)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

:warning:  `Initialization of immutable value 'gaming' was never used; consider replacing with assignment to '_' or removing it`


What are the calls to `update` meant to do ? 
If I remove them, the test still passes.
</blockquote></details>

Lost in translation when I updated the tests. Removed them.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListItemIdentifier.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr4gfTo2a0bH6GLZgvF:-Nr57VUH3RrUzFjMyZld:b-21f79o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a334e00f690a4b4475ffd9a372a7898850d7de1b/ios/MullvadVPN/Coordinators/CustomLists/CustomListItemIdentifier.swift#L54)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Up to you, it ultimately depends on whether we intend to expand `CustomListFieldValidationError` but I also want to say
"YAGNI, until you do, then you can make the change"
</blockquote></details>

As discussed f2f, we'll leave it like this until we have the final designs.
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818#-Nr5356x6oz-QmDz1JF5:-Nr57UO_6vSEbUxNnnRf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed9f13c6642dd11630869bae935e96c2985c6b38/ios/MullvadVPN/Coordinators/Settings/SettingsValidationErrorConfiguration.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You can also remove the entire extension, it's not needed to implement `Equatable`.

If the`Element`  type of an array is `Equatable` the array itself is too, and since all the types in `SettingsValidationErrorConfiguration` are `Equatable` it -- itself -- is too.
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 4 unresolved discussions (waiting on @acb-mv)

**Review by buggmagnet — APPROVED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv)

**Review by acb-mv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5818)* status: all files reviewed, 3 unresolved discussions

**Pull request merged**
