### PR TITLE
Add stagemole flavor

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to add a `stagemole` flavor in the infrastructure dimension.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258#-:-NgOAFEs9qbPdD22G-80:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258#-:-NgOVxNi6AVIQvuvkC6X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258#-:-NgO_yAn8pwm8Ok-rgK0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
