### PR TITLE
Fix dns e2e tests on linux

### PR DESCRIPTION
**Pull request by hulthe**
The DNS e2e tests all seem to [fail](https://github.com/mullvad/mullvadvpn-app/actions/runs/9865964454). Seems like it fails to negotiate an ephemeral peer, which makes sense since we are connecting to a local wg relay without that functionality for those tests.

At some point, the local wg relay should be updated with the same functionality as the regular relays (to ensure a realistic testing environment). That would be a bigger task though.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6457)

### CODE REVIEW

**Comment by hulthe** [comment]
Started a full E2E test run to test if this fixes the problem
https://github.com/mullvad/mullvadvpn-app/actions/runs/9873431698

**Comment by hulthe** [comment]
Note to self, fix clippy warning on maocs

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by hulthe** [comment]
@faern, This should be good to merge now. I went ahead and rebased on main

**Pull request merged**
