### PR TITLE
Enable custom Shadowsocks port selection on entry servers in multihop

### PR DESCRIPTION
**Pull request by rablador**
**Steps to reproduce**

- Select a relay that has shadowsocks_extra_addr_in enabled
- Connect to it in single hop mode
- Select a custom shadowsocks obfuscation port to validate that it supports any ports in the 1-65535 range
- Disconnect
- Turn on multihop
- Select the aforementioned server as an entry point for multihop
- Select any other server as an exit hop
- Tap on "Secure Connection"

**Expected Result**

The app should just connect using Shadowsocks obfuscation on the entry server.

**Actual result**

The app enters the blocked state, thinking that the relay constraints are not valid.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7263)

### CODE REVIEW

**Review by buggmagnet — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mojganii — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7263#-:-OD73gWE0M_Ga5rFfB7e:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7263#-:-ODAhxZQ0B2NcnXcohF6:bnfp4nl)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7263#-:-ODAjKkaCu6JjxZIErNl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
