### PR TITLE
Replace custom GeoJSON parser with MKGeoJSONDecoder

### PR DESCRIPTION
**Pull request by rablador**
We use our own GEO JSON deserializer (GeoJSON.swift). However MapKit supports MKGeoJSONDecoder since iOS 13 and onwards.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/MapViewController.swift` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501#-NRgsmL509lWnxIamsiB:-NRgsmL62tV0NztU7crj:b-az76lb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4b84f4efe531aa9b5a812d7771577a4b09fda110/ios/MullvadVPN/View%20controllers/Tunnel/MapViewController.swift#L190)):*
> ```Swift
>             for feature in features {
>                 for geometry in feature.geometry {
>                     if let polygon = geometry as? MKPolygon {
> ```

MapKit seems to be having issues to render polygons with interior polygons and multi polygons in general, so try extracting both and see if it helps, i.e:

```swift
for feature in features {
    for geometry in feature.geometry {
        if let polygon = geometry as? MKPolygon {
            if let interiorPolygons = polygon.interiorPolygons, !interiorPolygons.isEmpty {
                overlays.append(MKPolygon(points: polygon.points(), count: polygon.pointCount))
                overlays.append(contentsOf: interiorPolygons)
            } else {
                overlays.append(polygon)
            }
        }

        if let multiPolygon = geometry as? MKMultiPolygon {
            overlays.append(contentsOf: multiPolygon.polygons)
        }
    }
}
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/Tunnel/MapViewController.swift` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501#-NRgsmL509lWnxIamsiB:-NRlouiy1s3I6TAoC8Jp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4b84f4efe531aa9b5a812d7771577a4b09fda110/ios/MullvadVPN/View%20controllers/Tunnel/MapViewController.swift#L190)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

MapKit seems to be having issues to render polygons with interior polygons and multi polygons in general, so try extracting both and see if it helps, i.e:

```swift
for feature in features {
    for geometry in feature.geometry {
        if let polygon = geometry as? MKPolygon {
            if let interiorPolygons = polygon.interiorPolygons, !interiorPolygons.isEmpty {
                overlays.append(MKPolygon(points: polygon.points(), count: polygon.pointCount))
                overlays.append(contentsOf: interiorPolygons)
            } else {
                overlays.append(polygon)
            }
        }

        if let multiPolygon = geometry as? MKMultiPolygon {
            overlays.append(contentsOf: multiPolygon.polygons)
        }
    }
}
```
</blockquote></details>

Done.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/MapViewController.swift` line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501#-NRmHabBCZHsiVtjvxVN:-NRmHabC9SqqNFJfZwqP:brely62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/71f2773839f90b099f45cf5ad08d76eee096713b/ios/MullvadVPN/View%20controllers/Tunnel/MapViewController.swift#L111)):*
> ```Swift
>         }
> 
>         if let multiPolygon = overlay as? MKMultiPolygon {
> ```

Since we don't use multi polygons, then perhaps no need for that configuration?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/Tunnel/MapViewController.swift` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501#-NRgsmL509lWnxIamsiB:-NRrhpiR4W-e-Jybg_ug:bhkrlas) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4b84f4efe531aa9b5a812d7771577a4b09fda110/ios/MullvadVPN/View%20controllers/Tunnel/MapViewController.swift#L190)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not sure what "done" means in this context. Did you test it? How's that look as you zoom in and zoom out, or move around the map? does it work on iPad too?
</blockquote></details>

I simply used the done button in Reviewable. 😅 I've tested it by trying out different locations, and it seems to work well. Just confirmed on iPad too.
___
*[`ios/MullvadVPN/View controllers/Tunnel/MapViewController.swift` line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501#-NRmHabBCZHsiVtjvxVN:-NRri4Da-eSQRqrir9cS:bss4a1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/71f2773839f90b099f45cf5ad08d76eee096713b/ios/MullvadVPN/View%20controllers/Tunnel/MapViewController.swift#L111)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Since we don't use multi polygons, then perhaps no need for that configuration?
</blockquote></details>

Removed!

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4501#-:-NRsTekhCYtg5z7-dNqk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
