### PR TITLE
Add gambling adult content blocking

### PR DESCRIPTION
**Pull request by AndreasShortcut**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

- Add blocking option for gambling and adult content.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/PreferencesDataSource.swift` line 381 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634#-N3cU30K46EJUgh4qbba:-N3cU30K46EJUgh4qbbb:bwhdb0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15cf9deea1386fe00c16cffabb19aa1a20d592c7/ios/MullvadVPN/PreferencesDataSource.swift#L381)):*
> ```Swift
> 
>             return cell
>             
> ```

Xcode is not very tidy when it comes to cleaning leading/trailing whitespaces etc.. This will be solved with formatter and we have a branch for automatic code formatting but I haven't been satisfied with it so we're not there yet. Until then I usually use a simple shell script to strip out whitespace:

```
find . -name '*.swift' -exec sed -i '' -E 's/[[:space:]]+$//g' {} +
```

(run in `ios` directory)

This can also be added as a pre-commit hook, although I usually just run it manually.

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)* status: all files reviewed, 1 unresolved discussion (waiting on @AndreasShortcut)

**Comment by AndreasShortcut** [comment]
> > Reviewed 2 of 4 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)_ status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @AndreasShortcut)
> 
> _[`ios/MullvadVPN/PreferencesDataSource.swift` line 381 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634#-N3cU30K46EJUgh4qbba:-N3cU30K46EJUgh4qbbb:bwhdb0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15cf9deea1386fe00c16cffabb19aa1a20d592c7/ios/MullvadVPN/PreferencesDataSource.swift#L381)):_
> 
> > ```swift
> >             return cell
> >             
> > ```
> 
> Xcode is not very tidy when it comes to cleaning leading/trailing whitespaces etc.. This will be solved with formatter and we have a branch for automatic code formatting but I haven't been satisfied with it so we're not there yet. Until then I usually use a simple shell script to strip out whitespace:
> 
> ```
> find . -name '*.swift' -exec sed -i '' -E 's/[[:space:]]+$//g' {} +
> ```
> 
> (run in `ios` directory)
> 
> This can also be added as a pre-commit hook, although I usually just run it manually.

Thanks! Fixed in [b31af7d](https://github.com/mullvad/mullvadvpn-app/pull/3634/commits/b31af7de75d02f7da6a48fc53a86cb3f83fce0dc)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/PreferencesViewModel.swift` line 63 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634#-N3cjvOfBIXhZdWdXQHJ:-N3cjvOfBIXhZdWdXQHK:b5x88rt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b31af7de75d02f7da6a48fc53a86cb3f83fce0dc/ios/MullvadVPN/PreferencesViewModel.swift#L63)):*
> ```Swift
>                     "CUSTOM_DNS_DISABLE_ADTRACKER_BLOCKING_FOOTNOTE",
>                     tableName: "Preferences",
>                     value: "Disable **Block ads**, **Block trackers** and **Block malware** to activate this setting.",
> ```

Mhm this list if updated will get even longer.. Perhaps some sort of group name should be used to reference the blocking options.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/PreferencesViewModel.swift` line 63 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634#-N3cjvOfBIXhZdWdXQHJ:-N3cw-kf5-Tc1a5MMoIS:b-blkvx7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b31af7de75d02f7da6a48fc53a86cb3f83fce0dc/ios/MullvadVPN/PreferencesViewModel.swift#L63)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Could you please change that `Disable all content blockers (under Preferences) to activate this setting.`
</blockquote></details>

Oh and if we don't need markdown parsing here then perhaps initialize the attributed string with `NSAttributedString(string: ...)`

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634#-:-N3d1WVW7JF_ctlBHPlR:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @pronebird)

**Pull request merged**
