### PR TITLE
Convert ProblemReport to functional component

### PR DESCRIPTION
**Pull request by hankolsen**
This PR makes ProblemReport a functional component

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: all files reviewed, 4 unresolved discussions (waiting on @hankolsen)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 147 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELIZ1l7TehM_v6y50H:-NELIZ1l7TehM_v6y50I:b-v8bri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L147)):*
> ```XML
>     ) {
>       try {
>         setSendState(SendState.sending);
> ```

Why not call `sendReport()` here instead of triggering it in a `useEffect`?
___
*[`gui/src/renderer/components/ProblemReport.tsx` line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELIs-f9SVeTn49Q80b:-NELIs-f9SVeTn49Q80c:bpeadrn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L154)):*
> ```XML
>   }, [email]);
> 
>   const renderContent = () => {
> ```

It would be nice to move this out to a separate component.
___
*[`gui/src/renderer/components/ProblemReport.tsx` line 357 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELfmXNDRQEZ_Y9lzHv:-NELfmXNDRQEZ_Y9lzHw:byy55sk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L357)):*
> ```XML
> };
> 
> function Failed({ setSendState, onSend }: FailedProps) {
> ```

It's really nice to have these as individual components instead of just methods.
___
*[`gui/src/renderer/components/ProblemReport.tsx` line 440 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELgYmqCOvEfVAuDFoS:-NELgYmqCOvEfVAuDFoT:bybehlm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L440)):*
> ```XML
>   const openDownloadLink = useCallback(async () => {
>     await openUrl(suggestedIsBeta ? links.betaDownload : links.download);
>   }, []);
> ```

The dependency array here should probably include `suggestedIsBeta`. The version info is updated once a day and although highly unlikely, this value could change while the dialog is open.
___
*[`gui/src/renderer/components/ProblemReport.tsx` line 447 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELgrUp3f0GUzSB2FZV:-NELgrUp3f0GUzSB2FZW:b-4dtylw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L447)):*
> ```XML
>     acknowledgeOutdatedVersion();
>     onClose();
>   }, []);
> ```

We need to include `onClose` here since it could change if `history.pop` changes.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: all files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 440 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELgYmqCOvEfVAuDFoS:-NELkm_gES2ldOf7yj5O:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L440)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The dependency array here should probably include `suggestedIsBeta`. The version info is updated once a day and although highly unlikely, this value could change while the dialog is open.
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/ProblemReport.tsx` line 447 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELgrUp3f0GUzSB2FZV:-NELkmrHCWH963tjJ0lN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L447)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We need to include `onClose` here since it could change if `history.pop` changes.
</blockquote></details>

Done.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 147 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELIZ1l7TehM_v6y50H:-NELlZeM0Xq3lPB607Ng:b-uajoo2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L147)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Why not call `sendReport()` here instead of triggering it in a `useEffect`?
</blockquote></details>

Previously this, and also the collectAndViewLog logic, was implemented in callbacks in setState. 
So I tried to mimic that behavior. Which makes it all a bit complicated, and I wouldn't mind to update it if there is nothing depending on the state being actually update first.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: all files reviewed, 2 unresolved discussions (waiting on @hankolsen)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 147 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELIZ1l7TehM_v6y50H:-NELmzTkEN2BT94T5id5:bj7zzix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L147)):*
<details><summary><i>Previously, hankolsen wrote…</i></summary><blockquote>

Previously this, and also the collectAndViewLog logic, was implemented in callbacks in setState. 
So I tried to mimic that behavior. Which makes it all a bit complicated, and I wouldn't mind to update it if there is nothing depending on the state being actually update first.
</blockquote></details>

You probably know this better than me now :laughing: Please go ahead and try it out if you think it would work.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 147 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELIZ1l7TehM_v6y50H:-NE_O4VX842o-Y3epxGI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L147)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

You probably know this better than me now :laughing: Please go ahead and try it out if you think it would work.
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/ProblemReport.tsx` line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NELIs-f9SVeTn49Q80b:-NE_ODVp2r0FHNTHdWAm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21aef08c23cd0ae6ad0872f64fde12dd219bdca7/gui/src/renderer/components/ProblemReport.tsx#L154)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

It would be nice to move this out to a separate component.
</blockquote></details>

Done.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hankolsen)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 393 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NEp_bn09R87mjZ64j5D:-NEp_bn09R87mjZ64j5E:b6h1ezx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b7cf8fe086959e43e70666372f94259b45e3004c/gui/src/renderer/components/ProblemReport.tsx#L393)):*
> ```XML
>       try {
>         const reportId = await collectPromise;
>         return new Promise((resolve) => {
> ```

I don't think we need to return a promise here. You should be able to just return the `reportId` here.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/ProblemReport.tsx` line 393 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-NEp_bn09R87mjZ64j5D:-NEpcqX50rXELjbv-mFs:b-8fx2ut) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b7cf8fe086959e43e70666372f94259b45e3004c/gui/src/renderer/components/ProblemReport.tsx#L393)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't think we need to return a promise here. You should be able to just return the `reportId` here.
</blockquote></details>

:+1:

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4042#-:-NEplsEe1QQalHABXEsn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
