### PR TITLE
Fix text overflow and max lines on connection screen

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351#-O-KcLcJ22UXepNcyQnw):*
Should probably mention that this is in the connect screen.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351#-O-KcLcJ22UXepNcyQnw):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should probably mention that this is in the connect screen.
</blockquote></details>

Fixed

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351#-:-O-KiHz59vwhOv52NAS2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
