### PR TITLE
Api access methods desktop GUI

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds the API access method GUI (https://app.zeplin.io/project/5f928a32fdc9962af9018d70/flow/61f14327d6d7cda2828d3f0c), along with a few new components for handling the new form layout and input types:
* Settings row
* Form wrapper
* Text input for the new settings row
* Select input
* Radio buttons

Fixes DES-341, DES-555

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/components/ContextMenu.tsx` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np0-WMc-hTzPiGBOwEs:-Np0-WMc-hTzPiGBOwEt:b-h6ywgl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/ContextMenu.tsx#L162)):*
> ```XML
>         window.innerHeight
>         ? 'down'
>         : 'up';
> ```

nit this computation looks a bit hairy due to it being split up across multiple lines, but I get if you don't want to introduce intermediate variables / extract into a function either. If you feel like it's readable as is, simply ignore this nit



_Code quote:_
```XML
      return bounds.y +
        bounds.height +
        props.items.length * ITEM_HEIGHT +
        2 * (BORDER_WIDTH + PADDING_VERTICAL) <
        window.innerHeight
        ? 'down'
        : 'up';
```
___
*[`gui/src/renderer/components/Modal.tsx` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np-jWNqET0hoUNIxW5j:-Np-jWNqET0hoUNIxW5k:b-84jrck) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/Modal.tsx#L106)):*
> ```XML
>   warning,
> 
>   working,
> ```

May I suggest something like `loading`/`progressing`/`inProgress`? `working` can be mistaken for a final state, in which case it could be confused with the `success` variant of this enum :blush: 



_Code quote:_
```XML
 working
```
___
*[`gui/src/renderer/components/SmallButton.tsx` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np-uZVO3Kodsfobv3TN:-Np-uZVO3Kodsfobv3TO:btg9gxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/SmallButton.tsx#L20)):*
> ```XML
>       };
>     case SmallButtonColor.blue:
>     default:
> ```

nit: Not necessary to switch on `SmallButtonColor.blue` since it just falls through to `default`, but I see how it can be nice for explicitness :blush:



_Code quote:_
```XML
    case SmallButtonColor.blue:
    default:
```
___
*[`gui/src/renderer/components/cell/SettingsRadioGroup.tsx` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Novfl6j8to1QAjd9NC-:-Novfl6j8to1QAjd9NC0:buf7wqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/cell/SettingsRadioGroup.tsx#L16)):*
> ```XML
> function getGroupKey() {
>   return ++groupCounter;
> }
> ```

Could the `useId` hook be used here as well? :blush: 



_Code quote:_
```XML
let groupCounter = 0;
function getGroupKey() {
  return ++groupCounter;
}
```

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714)* status: all files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[`gui/src/renderer/lib/api-access-methods.ts` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-NovimnJAQAALbAJ-jar:-NovimnJAQAALbAJ-jas:buf7wqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/lib/api-access-methods.ts#L12)):*
> ```XML
> function getTestId() {
>   return ++testId;
> }
> ```

Could the `useId` hook be used here as well? :blush: 



_Code quote:_
```XML
// Each test needs to have an id to be cancelable.
let testId = 0;
function getTestId() {
  return ++testId;
}
```

**Review by raksooo — COMMENTED** [review]
I've fixed your comments and also added a line to the changelog.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-:-Np0J1O-9C1f7SuXokkN:bm92i0o)* status: 30 of 37 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`gui/src/renderer/components/ContextMenu.tsx` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np0-WMc-hTzPiGBOwEs:-Np0J6pT43kAVTvyRv7X:b-gz92sj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/ContextMenu.tsx#L162)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

nit this computation looks a bit hairy due to it being split up across multiple lines, but I get if you don't want to introduce intermediate variables / extract into a function either. If you feel like it's readable as is, simply ignore this nit
</blockquote></details>

That was horrible :laughing: How did I not notice this beast myself when writing it :see_no_evil: Fixed!
___
*[`gui/src/renderer/components/Modal.tsx` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np-jWNqET0hoUNIxW5j:-Np0JIzwDhbrImJePjJ5:b7gmbp2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/Modal.tsx#L106)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

May I suggest something like `loading`/`progressing`/`inProgress`? `working` can be mistaken for a final state, in which case it could be confused with the `success` variant of this enum :blush:
</blockquote></details>

Loading sounds great to me! Done.
___
*[`gui/src/renderer/components/SmallButton.tsx` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np-uZVO3Kodsfobv3TN:-Np0JOCv7brOb7Z_cU6C:b-oqd0gd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/SmallButton.tsx#L20)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

nit: Not necessary to switch on `SmallButtonColor.blue` since it just falls through to `default`, but I see how it can be nice for explicitness :blush:
</blockquote></details>

When I wrote it I opted for explicitness but when thinking about it now I realize `default` is explicit enough. Fixed!
___
*[`gui/src/renderer/components/cell/SettingsRadioGroup.tsx` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Novfl6j8to1QAjd9NC-:-Np0JXLdE2Ld09saWMgF:b60r4zt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/cell/SettingsRadioGroup.tsx#L16)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Could the `useId` hook be used here as well? :blush:
</blockquote></details>

Yes, done!
___
*[`gui/src/renderer/lib/api-access-methods.ts` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-NovimnJAQAALbAJ-jar:-Np0JaAkBqXN1umtZJeG:bnk60nd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/lib/api-access-methods.ts#L12)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Could the `useId` hook be used here as well? :blush:
</blockquote></details>

Unfortunately not. Hooks can only be used at the top level in components/custom hooks and this is used in a callback. Although when taking a look at it I realized we could use the actual promise to compare if it's the most recent test or not.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-:-Np5LXX0-43-GT6HF0AF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`gui/src/renderer/components/ContextMenu.tsx` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-Np0-WMc-hTzPiGBOwEs:-Np5F2I-7_OFV1NwVTsi:bh7r4d0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/components/ContextMenu.tsx#L162)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

That was horrible :laughing: How did I not notice this beast myself when writing it :see_no_evil: Fixed!
</blockquote></details>

nice :tada:
___
*[`gui/src/renderer/lib/api-access-methods.ts` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5714#-NovimnJAQAALbAJ-jar:-Np5KrB5EtTH2p8k1JLd:baqdwhn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd3236fb3ca3cc14be52e258ba6b2438735f1ee/gui/src/renderer/lib/api-access-methods.ts#L12)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Unfortunately not. Hooks can only be used at the top level in components/custom hooks and this is used in a callback. Although when taking a look at it I realized we could use the actual promise to compare if it's the most recent test or not.
</blockquote></details>

I see, but your new solution seems fins to me! :blush:

**Pull request merged**
