### PR TITLE
Update ru locales

### PR DESCRIPTION
**Pull request by Erghel**
- Added Russian translation of the new settings in the Mullvad client

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3782)

### CODE REVIEW

**Comment by faern** [comment]
Hi. Thank you for wanting to contribute. But we sadly can't accept this right now. First of all we never translate the GUI between releases. We just trigger a larger translation at release time. Otherwise we create a lot of extra work by doing many small translation rounds, which is inefficient. Secondly we don't currently take in third party translations. I have had to close a number of localization PRs in the past because of this. Please see #3709 for an explanation.

However, things are about to improve here. We are working on a way to let users submit translation suggestions directly to our translation company. If that plays out well, maybe we can take in third party translations eventually. But those will likely just be change suggestions to existing strings, not brand new translation.

**Comment by Erghel** [comment]
Got it! Thanks so much for the answer and explanations. I'll be glad to help when the situation changes.

**Comment by faern** [comment]
We can now accept third party translation suggestions! There is a google docs spreadsheet where users can suggest improvements. Please see our new section in the contribution guidelines! https://github.com/mullvad/mullvadvpn-app/blob/master/CONTRIBUTING.md

**Comment by Erghel** [comment]
I sent the translation to this document.

**Comment by faern** [comment]
Thanks for the help. However, these are *new* translations. Not *improvements to existing ones*. We can only accept the latter. The strings you submitted have not even gone through our translation company yet. I guess you are building and trying the `master` branch of this app? We can only accept corrections to existing translations in released stable apps.

We run a round of translations with our translation company just before each release. So the `master` branch will always contain a bunch of untranslated strings. This is because we need to continuously improve the UI in `master`, but we can't ping our translation company continuously, they have to be translating in batches. So we queue up everything until we perform a release.

**Comment by Erghel** [comment]
I really apologize for misleading the translation company. I will know how to do it right. 

I apologize again.

**Comment by faern** [comment]
No worries! I could have been more clear! As this entire PR was about new translations, I should have mentioned that explicitly.

Out of curiosity: are you using our app directly from the master branch? Or did you see these strings were not yet translated anyway?

**Comment by Erghel** [comment]
I saw that the lines hadn't been translated yet, so I thought I could help, since I didn't know how you go about the translation process (do you have a company or is it all done by the community). Now I know how things are, so next time hopefully there will be less mistakes on my part.

**Pull request closed without merging**
