### PR TITLE
Add Encrypted DNS proxy as an access method

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR tracks the progress of adding Encrypted DNS as an access method in the daemon.

## TODO
- [x] Rebase on top of https://github.com/mullvad/mullvadvpn-app/pull/7008
- [x] Rebase on top of https://github.com/mullvad/mullvadvpn-app/pull/7025

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)

### CODE REVIEW

**Review by Serock3 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-api/src/proxy.rs` line 110 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010#-O9i9kxI-spGfu3LvaiN:-O9i9kxI-spGfu3LvaiO:b8ralvh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b74695bf76fd7270f399c9c7d4d2f660bd405b29/mullvad-api/src/proxy.rs#L110)):*
> ```XML
>             }
>             ProxyConfig::EncryptedDnsProxy(proxy) => {
>                 write!(f, "ApiSusan {}", proxy.addr)
> ```

Haha I almost want you to leave this in, but you probably shouldn't. This display impl is only used for a single log statement though, maybe we should remove it entirely and use debug formatting, i.e.

`mullvad-daemon/src/api.rs`: 

```rust
fn set_current(){
...
  tokio::spawn(async move {
      if new_connection_mode.save(&cache_dir).await.is_err() {
          log::warn!("Failed to save {new_connection_mode:?} to cache")
      }
  });
...
}
```
___
*[`mullvad-daemon/src/api.rs` line 278 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010#-O9iHUUT6YpCAVDBheS4:-O9iHUUT6YpCAVDBheS5:b-eacco3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b74695bf76fd7270f399c9c7d4d2f660bd405b29/mullvad-daemon/src/api.rs#L278)):*
> ```XML
>             let mut cache = EncryptedDnsProxyState::default();
>             // Hydrate the cache by fetching new proxy configs.
>             if let Err(_error) = cache.fetch_configs().await {
> ```

Not handling this error case is especially problematic as we do not currently fulfill this acceptance criteria:

"A new DoH request to get the latest proxy configs must be sent out every time this access method is engaged."

I'll leave this comment and a reminder to implement that criteria.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`mullvad-api/src/proxy.rs` line 110 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010#-O9i9kxI-spGfu3LvaiN:-O9imbU8BaLOERbDh-2W:b-4vbus4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b74695bf76fd7270f399c9c7d4d2f660bd405b29/mullvad-api/src/proxy.rs#L110)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Haha I almost want you to leave this in, but you probably shouldn't. This display impl is only used for a single log statement though, maybe we should remove it entirely and use debug formatting, i.e.

`mullvad-daemon/src/api.rs`: 

```rust
fn set_current(){
...
  tokio::spawn(async move {
      if new_connection_mode.save(&cache_dir).await.is_err() {
          log::warn!("Failed to save {new_connection_mode:?} to cache")
      }
  });
...
}
```
</blockquote></details>

Alright, I'll remove it :wink:

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`mullvad-daemon/src/api.rs` line 278 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010#-O9iHUUT6YpCAVDBheS4:-O9oM4qmEGaZ03fR9mOs:b-3jv1q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b74695bf76fd7270f399c9c7d4d2f660bd405b29/mullvad-daemon/src/api.rs#L278)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Not handling this error case is especially problematic as we do not currently fulfill this acceptance criteria:

"A new DoH request to get the latest proxy configs must be sent out every time this access method is engaged."

I'll leave this comment and a reminder to implement that criteria.
</blockquote></details>

Done We now fetch new configs every time this access method is engaged.

**Review by Serock3 — APPROVED** [review]
> Reviewed 11 of 11 files at r8, 4 of 4 files at r9, 9 of 9 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, 4 of 4 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 3 of 3 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Serock3 — APPROVED** [review]
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
