### PR TITLE
Fix button highlight and refactor screen

### PR DESCRIPTION
**Pull request by Rawa**
- Fix button highlight
- Fix spacing
- Refactor screen to make it easier to comprehend.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt` line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387#-NiZYjRW81dAWfoCq5Oj:-NisBaH7DpoA5ZHPZkvN:b-wztq43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76c822eaa23574d710bc08f96de92dab3a194fda/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt#L247)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should this be hardcoded? I think we can use `R.string.remove_button` instead.
</blockquote></details>

It got carried over from the old button when refactoring, I've changed to use the content description of the remove button now which has a matching string.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt` line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387#-NiZYjRW81dAWfoCq5Oj:-NisBlRlCrHPhT5tKHjW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76c822eaa23574d710bc08f96de92dab3a194fda/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt#L247)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It got carried over from the old button when refactoring, I've changed to use the content description of the remove button now which has a matching string.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387#-:-NitR3nf2vrykcyNHs82:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387#-:-NjSuztXEIXjyAgf1BSk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5387)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
