### PR TITLE
Show loading states in purchasing flow an extra minimum amount of time

### PR DESCRIPTION
**Pull request by Pururun**
This is to reduce the flickering in the ui.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6084)

### CODE REVIEW

**Comment by Pururun** [comment]
@Rawa Updated the PR to be more like we discussed yesterday.

**Comment by albin-mullvad** [comment]
@Rawa please review!

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6084)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6084#-:-NvVniBtAKNlKxTCMoDt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
