### PR TITLE
Auth failed event

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/113)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 91 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9Aof0pCTjdRKwJ1sZx:-L9Aof0pCTjdRKwJ1sZy:bpp7xcj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/mullvad-daemon/src/main.rs#L91)):*
> ```Rust
>         AuthFailed(reason: String) {
>             description("Authentication failed")
>             display("Authentication failed{}", reason)
> ```

+ space?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by faern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 173 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9F8Al_ECEhKPWpVN3V:-L9F8Al_ECEhKPWpVN3W:bqiubjt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/mullvad-daemon/src/main.rs#L173)):*
> ```Rust
>     Connecting,
>     /// The tunnel connection was cancelled before it was successfully established.
>     ConnectionCancelled,
> ```

What does this state represent? I'm very careful when it comes to this state machine in general. Who cancels the connection and what is the next state? Do we get stuck in this state? Should the firewall rules be active or allow all traffic in this state?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by faern** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 91 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9Aof0pCTjdRKwJ1sZx:-L9K6Z9a3iwfBqf70h4f:b-9xi1m2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/mullvad-daemon/src/main.rs#L91)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

+ space?
</blockquote></details>

Ah.. I see now, the `: ` is part of the `reason`. I feel that is a bit misplaced, the `: ` is not conceptually part of the reason, it's part of the formatting of the error output.

---

*[talpid-core/src/tunnel/mod.rs, line 83 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9K6yxBA5kbDX8m6Gjf:-L9K6yxBA5kbDX8m6Gjg:baj33jf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/talpid-core/src/tunnel/mod.rs#L83)):*
> ```Rust
>         match *event {
>             OpenVpnPluginEvent::AuthFailed => {
>                 let reason = env.get("auth_failed_reason").map(String::to_owned);
> ```

Is the `auth_failed_reason` not guaranteed to always exist with your current implementation in OpenVPN? Or is it optional there as well? If it's expected to always exist I think we can just run `.expect("No auth failure reason")` like we do with `env.get("dev")` for example. Would simplify things.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by faern** [comment]
Reviewed 2 of 13 files at r1.
Review status: 2 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/tunnel/mod.rs, line 83 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9K6yxBA5kbDX8m6Gjf:-L9KSQkq823Sh9vPcU-9:b-i55tba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/talpid-core/src/tunnel/mod.rs#L83)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

It's optional. If no reason is received, the environment variable isn't added.
</blockquote></details>

I see. Yeah, then it should be like this :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: 2 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 517 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PLarQ-VOnnhDMgc3G:-L9PLarQ-VOnnhDMgc3H:bxaoy3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/lib/backend.js#L517)):*
> ```JavaScript
>   _dispatchError(errorChain: Array<string>) {
>     var authFailed = 'Authentication failed';
>     if(errorChain[0].startsWith(authFailed)) {
> ```

Potential out of bounds index access.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: 2 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 521 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PNLW8BRkVyue5tTP_:-L9PNLW8BRkVyue5tTPa:b-kmie8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/lib/backend.js#L521)):*
> ```JavaScript
>       var cause = new BackendError('UNKNOWN_ERROR');
>       switch(errorCause) {
>       case ': no credit':
> ```

That doesn't look like your base switch-case. Is there any way we can refine that?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: 2 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/lib/backend.js, line 521 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PNLW8BRkVyue5tTP_:-L9PNePr3a7NKzQIhXN2:bp8b6kc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/lib/backend.js#L521)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

That doesn't look like your base switch-case. Is there any way we can refine that?
</blockquote></details>

/base/best/s

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: 2 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/lib/backend.js, line 521 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PNLW8BRkVyue5tTP_:-L9PO6EK8Bn54FJb_uJz:br1f4wu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/lib/backend.js#L521)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

/base/best/s
</blockquote></details>

Maybe we should look into providing a meaningful structured errors back to the app. Error code would be easier to work with.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: 2 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/components/Connect.js, line 346 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PPB2m-JfSmTOCJMEg:-L9PPB2m-JfSmTOCJMEh:b-qhuw7p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/components/Connect.js#L346)):*
> ```JavaScript
> 
>   displayError(): ?BackendError {
>     if(this.props.connection.status === 'connected') {
> ```

I am entirely confused about what `displayError()` became. I can't make any sense of what it is doing...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: 2 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[mullvad-daemon/src/main.rs, line 173 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9F8Al_ECEhKPWpVN3V:-L9PPz5H2EYAqkGIUlD2:bwjjo7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/mullvad-daemon/src/main.rs#L173)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm not sure if it's the same thing. I guess they are equivalent states on the state machine, but I'm not sure if they have the same purpose. I only created the state because otherwise when I cancel the connection the GUI get's notified that it is killing a secure connection, giving the false impression that the connection was secure for a few seconds.

If you'd like to, I'd suggest looking at the individual [commit](https://github.com/mullvad/mullvadvpn-app/commit/01651f49ceb131d4981d9871ea450ca87e662f73). Might be easier to focus on this separately.

Maybe we should discuss more about this state and the blocking state on slack?
</blockquote></details>

@faern online/offline status is not only about the availability of primary interface, because for example Wi-Fi interface on my MacBook is available, but I may not have internet working. 

MacOS has reachability APIs that can be configured to periodically ping certain domain or IP to find out if internet connection is up and of course check if interfaces are up.

Although of course we should be careful about leaking any traffic even to make a tiny ping.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/lib/backend.js, line 516 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PS6z07IF9gRjeUI87:-L9PS6z07IF9gRjeUI88:b-x9mtdj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/lib/backend.js#L516)):*
> ```JavaScript
> 
>   _dispatchError(errorChain: Array<string>) {
>     var authFailed = 'Authentication failed';
> ```

`var` is used to define global variables. You should use `const` for variables that do not mutate and `let` for any local variables.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/lib/backend.js, line 521 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9PNLW8BRkVyue5tTP_:-L9P_Lb9DDHfznxNzneh:b-67skmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599d009d1facc743b536e9b8564ba5b44c2ce391/app/lib/backend.js#L521)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Maybe we should look into providing a meaningful structured errors back to the app. Error code would be easier to work with.
</blockquote></details>

Why the `: ` part? I think we should have better structured strings for this maybe?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[mullvad-daemon/src/main.rs, line 173 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9F8Al_ECEhKPWpVN3V:-L9Pa-OVCiQBWg1x0g7l:b-y1xzbi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/mullvad-daemon/src/main.rs#L173)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

@faern online/offline status is not only about the availability of primary interface, because for example Wi-Fi interface on my MacBook is available, but I may not have internet working. 

MacOS has reachability APIs that can be configured to periodically ping certain domain or IP to find out if internet connection is up and of course check if interfaces are up.

Although of course we should be careful about leaking any traffic even to make a tiny ping.
</blockquote></details>

I never said having a primary interface is a guarantee for having internet. But I think we can regard having *no* primary interface as a guarantee for not having internet? Thus we can stop trying to establish a connection while there is no primary interface. I don't think we should make it too complicated with the reachability API. My point was just that we could make the backend a bit more efficient at times.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[mullvad-daemon/src/main.rs, line 173 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113#-L9F8Al_ECEhKPWpVN3V:-LASDqbu92mjtt4mHmHd:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22536b922df5ec3063ed7d4eed9fc95ea9a335d4/mullvad-daemon/src/main.rs#L173)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I never said having a primary interface is a guarantee for having internet. But I think we can regard having *no* primary interface as a guarantee for not having internet? Thus we can stop trying to establish a connection while there is no primary interface. I don't think we should make it too complicated with the reachability API. My point was just that we could make the backend a bit more efficient at times.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by pinkisemils** [comment]
Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/113)*

**Comment by jvff** [comment]
I'm closing this because it will be rewritten to take advantage of the new `blocked` state.

**Pull request closed without merging**
