### PR TITLE
Simplify login flow IOS-189

### PR DESCRIPTION
**Pull request by pronebird**
1. This PR simplifies logout and login flow by moving from operation heavy code towards rather more traditional approach with callbacks which I believe we'll improve further with async/await in the future, but we're not there yet but that's the first step towards that anyway.
2. Drop `TransformOperation` and `InputOperation` as I believe that operations should be lighter as they are heavy in general and less friendly to many developers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)

### CODE REVIEW

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 365 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWw6qCQ0RIzzLMDfEbP:-NWw6qCR9WfpJqK2DStV:b-d6cqih) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/AppDelegate.swift#L365)):*
> ```Swift
>     }
> 
>     private func setupNotificationHandler() {
> ```

nit: I think the name of function isn't well-defined.maybe setup notification would be a better replacment 
___
*[`ios/MullvadVPN/AppDelegate.swift` line 393 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWw7a8TCfH5K6R7fLC0:-NWw7a8TCfH5K6R7fLC1:b-ajedka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/AppDelegate.swift#L393)):*
> ```Swift
>             SettingsManager.migrateStore(with: proxyFactory) { [self] migrationResult in
>                 // Tell the tunnel to re-read tunnel configuration after migration.
>                 if case .success = migrationResult {
> ```

couldn't do this in the switch case?

```
                   let migrateSettingsOperation = AsyncBlockOperation(dispatchQueue: .main) { [self] finish in
            SettingsManager.migrateStore(with: proxyFactory) { [self] result in
                switch result {
                case .failure(let error):
                    guard let settingsMigrationUIHandler = application.connectedScenes.first   as? SettingsMigrationUIHandler else {
                        finish(error)
                        break
                    }
                    settingsMigrationUIHandler.showMigrationError(error) {
                        finish(error)
                    }
                    
                case .success:
                    logger.debug("Reconnect the tunnel after settings migration.")
                    tunnelManager.reconnectTunnel(selectNewRelay: true)
                    fallthrough
                case .nothing:
                    finish(nil)
                }
            }
        }
```
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWwC61Q4g72yoP7lpV4:-NWwC61Q4g72yoP7lpV5:b-2u63ek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L48)):*
> ```Swift
> }
> 
> class SetAccountOperation: ResultOperation<StoredAccountData?> {
> ```

is it related to account flow and scopes?
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 166 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWwDkYq1rcR4yeVm27V:-NWwDkYq1rcR4yeVm27W:b-m0fe43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L166)):*
> ```Swift
>                 storeSettings(accountData: accountData, newDevice: newDevice)
>             }
>             completion(result.map { _ in accountData })
> ```

can we replace this part with this?
```
completion(.success(accountData))
```

**Review by rablador — COMMENTED** [review]
> Reviewed 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWwC61Q4g72yoP7lpV4:-NXFzMe1B2_6r7MHJ1_S:bwh10vx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L48)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

is it related to account flow and scopes?
</blockquote></details>

This is account log-in/log-out flow. Not sure about scopes, can you elaborate?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 365 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWw6qCQ0RIzzLMDfEbP:-NXFzlt77hq-IS08VUhz:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/AppDelegate.swift#L365)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: I think the name of function isn't well-defined.maybe setup notification would be a better replacment 
</blockquote></details>

Done

**Review by rablador — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 393 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWw7a8TCfH5K6R7fLC0:-NXKVqKWBXaF7GbOjyHM:burpatt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/AppDelegate.swift#L393)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Done. Not sure folks like `fallthrough` but I went with it.
</blockquote></details>

It's in compliance with Google's styleguide as long as the fallthrough is not the only statement of a case, so it should be fine.

**Review by mojganii — CHANGES_REQUESTED** [review]
Just for suggestion and maybe future improvement, I think maybe it's not a bad idea to separate login flow from create account flow and have interaction for each of them.I know they have a  lot  in common but maybe we can come to solution for this part.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-:-NXLOLbgEH9RkBxMfvLa:b8vjv5b)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWwC61Q4g72yoP7lpV4:-NXLIVcNCO6PLR9CuUKB:bwg3pa2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L48)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is account log-in/log-out flow. Not sure about scopes, can you elaborate?
</blockquote></details>

after discussion on Friday I figgured it out.
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NXLIwi2-GUg4gOsvO7v:-NXLIwi2-GUg4gOsvO7w:b-xn1hpd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fdd051450e4bab7fdccd53cf7336fc06438b468a/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L38)):*
> ```Swift
>     }
> 
>     fileprivate var accountNumber: String? {
> ```

nit : I think it's not good idea to make a computed variable for getting  an associated   value, especially in this case we have the account number when the case is `exsisting`.
moreover, the spelling of the name isn't correct
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 177 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NXLNMOv3VyPhtBGnbfq:-NXLNMOv3VyPhtBGnbfr:b4ncr1k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fdd051450e4bab7fdccd53cf7336fc06438b468a/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L177)):*
> ```Swift
> 
>         do {
>             try SettingsManager.setLastUsedAccount(accountNumber)
> ```

do we persist more than one account? if not, the key name is not descriptive

**Review by pronebird — COMMENTED** [review]
Acknowledged.

> Dismissed @mojganii from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-:-NXLhJu22Yz4MAEF1Y3Q:b-54snbz)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 393 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NWw7a8TCfH5K6R7fLC0:-NXLhX560i2DQL7GGRyw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a3d1303d14851629465bacd0f222bb034d2d100/ios/MullvadVPN/AppDelegate.swift#L393)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's in compliance with Google's styleguide as long as the fallthrough is not the only statement of a case, so it should be fine.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NXLIwi2-GUg4gOsvO7v:-NXLim_b3jsZCU3bpjs-:b1n4jbb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fdd051450e4bab7fdccd53cf7336fc06438b468a/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L38)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : I think it's not good idea to make a computed variable for getting  an associated   value, especially in this case we have the account number when the case is `exsisting`.
moreover, the spelling of the name isn't correct
</blockquote></details>

The spelling seems correct to me. (`existing`)

Having accessor saves some repetition inside of `main()` and I believe this will eventually go away once we start using async-await.
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 177 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NXLNMOv3VyPhtBGnbfq:-NXLhjvkDAAHZvVcC5lm:b-kxiwk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fdd051450e4bab7fdccd53cf7336fc06438b468a/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L177)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do we persist more than one account? if not, the key name is not descriptive 
</blockquote></details>

Only the last account user logged in with, and we use it to display that account in the dropdown on login in case when user logs out by accident so that they could log back in as many people lose their account numbers or don't have them handy somehow. 

This is beyond the scope of this PR as I am only refactoring this specific part of the project by merely reshuffling the code and not adding anything new.

If you'd like to have a deeper discussion on that, please open a thread on Slack.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753#-NXLIwi2-GUg4gOsvO7v:-NXPw9Qr5F_lJnfjgNgR:b-r1i4b8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fdd051450e4bab7fdccd53cf7336fc06438b468a/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L38)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The spelling seems correct to me. (`existing`)

Having accessor saves some repetition inside of `main()` and I believe this will eventually go away once we start using async-await.
</blockquote></details>

Fixed as per your request.

**Review by rablador — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4753)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Pull request merged**
