### PR TITLE
Ensure android app is reinstalled in gh actions

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to make the instrumentation more robust as it avoids any potential signature mismatch (which is acceptable in a ci environment). It also makes sure that no app data/cache is left from previous runs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110)

### CODE REVIEW

**Comment by sabercodic** [comment]
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragmentTest.kt` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110#-NFnCie84lXZ6C8MqQqX:-NFnCie84lXZ6C8MqQqY:b-fyjqlw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f4665048b6321ae40d762ad00d24568771ff1ef9/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragmentTest.kt#L155)):*
> ```Kotlin
>             .check(matches(withText("Test App Name")))
> 
>         onView(withRecyclerView(R.id.recyclerView).atPositionOnView(0)).perform(click())
> ```

Is it ok to skip targetViewId ?

**Review by sabercodic — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragmentTest.kt` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110#-NFnCie84lXZ6C8MqQqX:-NFnEOFeEPbl8fTAyl9k:b-bzhenz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f4665048b6321ae40d762ad00d24568771ff1ef9/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragmentTest.kt#L155)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Is it ok to skip targetViewId ?
</blockquote></details>

There might be better ways to write this test, but I believe unifying it to use `atPositionOnView`, as it does in other places, is good enough for now. This PR is more about how the app (+test) package is installed and uninstalled. Fixing a failing test was just a bonus.

**Review by sabercodic — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
