### PR TITLE
Add info dialog to Encrypted DNS proxy access method

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/EncryptedDnsProxyInfoDialog.kt` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087#-OAMPwZj8LrfrDNfLpUp:-OAMPwZj8LrfrDNfLpUq:b-s5edby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d0ce635b4ef48cdb8126ef22d4e9b0683ae1569a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/EncryptedDnsProxyInfoDialog.kt#L24)):*
> ```Kotlin
> fun EncryptedDnsProxyInfo(navigator: DestinationsNavigator) {
>     InfoDialog(
>         message =
> ```

Info dialogs needs some cleanup, but I think you can achieve the same effect by just setting `message` and `additionalInfo` and then you don't need `appendLine`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 263 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087#-OAMQVJ8COKzLxeVVrkv:-OAMQVJ8COKzLxeVVrkw:buoxfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d0ce635b4ef48cdb8126ef22d4e9b0683ae1569a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L263)):*
> ```Kotlin
>                 is ApiAccessMethod.CustomProxy.Socks5Remote -> null
>                 ApiAccessMethod.Direct -> null
>                 ApiAccessMethod.EncryptedDns -> onNavigateToEncryptedDnsInfoDialog
> ```

Should be able to collapse all the null cases to one

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/EncryptedDnsProxyInfoDialog.kt` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087#-OAMPwZj8LrfrDNfLpUp:-OAMnRu0C5EjU7s5XmAZ:b-jn5s6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d0ce635b4ef48cdb8126ef22d4e9b0683ae1569a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/EncryptedDnsProxyInfoDialog.kt#L24)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Info dialogs needs some cleanup, but I think you can achieve the same effect by just setting `message` and `additionalInfo` and then you don't need `appendLine`
</blockquote></details>

Discussed offline.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 263 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087#-OAMQVJ8COKzLxeVVrkv:-OAMnUbFDWL_fYXYw2F1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d0ce635b4ef48cdb8126ef22d4e9b0683ae1569a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L263)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should be able to collapse all the null cases to one
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087#-:-OAMoUDW7Rdondi4QIBp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087#-:-OAN90B-65TlPSzpXlhu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
