### PR TITLE
Improve alpha values in advanced settings

### PR DESCRIPTION
**Pull request by albin-mullvad**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543)

### CODE REVIEW

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543#-NSokAvTARYO4vcsOSx2:-NSokAvTARYO4vcsOSx3:b-agi3rm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/354c75471672bdff2cd811c5d838b7d83f44f12f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L65)):*
> ```Kotlin
>         isRowEnabled = isEnabled,
>         bodyView = {
>             SwitchCellView(
> ```

Do we change alpha of switch view anywhere?

**Review by sabercodic — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543#-NSokAvTARYO4vcsOSx2:-NSokyHE333YU5OCDhDf:b-v86a2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/354c75471672bdff2cd811c5d838b7d83f44f12f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L65)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Do we change alpha of switch view anywhere?
</blockquote></details>

It's passed along to the `CellSwitch` which relies on it to set alpha and handle/skip tap events

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543#-:-NSor_444Uos-7UsdGE3:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Pull request merged**
