### PR TITLE
Beta10

### PR DESCRIPTION
**Pull request by eriklarko**
I forked off the beta 9 tag and added the following merge commits

* c5499bf Merge branch 'email-confirmation'
* 3f5593b Merge branch 'line-height'
* 32ba7bc Merge branch 'app-version'
* 51e2cf9 Merge branch 'advanced-xp'
* a8467c4 Merge branch 'update-crl'

Then I updated the package.json version and the changelog and signed that commit.

Checklist for a PR:

* [ x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/61)

### CODE REVIEW

**Comment by faern** [comment]
Niceee. I like that you were able to keep the merges, so the features stay in discrete off-branches with a merge commit!

I have verified that the cherry-picked features, `advanced-xp` and `update-crl` are identical to those in the `master` branch :+1:

The last commit, 46ce508, is not signed. We have not done this type of offshoot release before, but I think we should regard this branch the same as `master` and thus sign all commits on the `beta10` branch, since it will end up in a release.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 25 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-L5G1cDmFosrory5oH54:-L5G1cDnSY2eG3MvwiLr:b8fsbmx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46ce508822e5662510634d29b472b2e8600076ca/CHANGELOG.md#L25)):*
> ```Markdown
> ### Changed
> - Require confirmation when sending problem reports without an email address.
> - Rewrote the advanced settings to ReactXP
> ```

We usually don't describe changes that don't effect, or don't intend to effect, the user. This is purely a refactoring. I don't see the need to tell the users that. If they want to see the actual code changes they have access to git.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-:-L5G1Wq_Owso0wdbl2et:b-krm30k)*

**Comment by pronebird** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 25 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-L5G1cDmFosrory5oH54:-L5G715mcxOCidkEIMLb:b-4qr4e7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46ce508822e5662510634d29b472b2e8600076ca/CHANGELOG.md#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We usually don't describe changes that don't effect, or don't intend to effect, the user. This is purely a refactoring. I don't see the need to tell the users that. If they want to see the actual code changes they have access to git.
</blockquote></details>

Agree. End users have no idea what react xp is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61)*

**Comment by faern** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 25 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-L5G1cDmFosrory5oH54:-L5G9SWedLpk3t6QFugV:bydwhs0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46ce508822e5662510634d29b472b2e8600076ca/CHANGELOG.md#L25)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Agree. End users have no idea what react xp is
</blockquote></details>

The changelog is some kind of middleground IMO. Here we should state all changes that affect the usage of the app, even the more technical ones ordinary users might not understand. The changelog is a technical document, but it should only document feature changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61)*

**Comment by eriklarko** [comment]
Ah, true. It is signed now

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 25 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-L5G1cDmFosrory5oH54:-L5HeRma5jXSFCJzMBo0:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46ce508822e5662510634d29b472b2e8600076ca/CHANGELOG.md#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The changelog is some kind of middleground IMO. Here we should state all changes that affect the usage of the app, even the more technical ones ordinary users might not understand. The changelog is a technical document, but it should only document feature changes.
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-:-L5HeZ_pAb7bcejmp52G:bvc61f7)*

**Comment by faern** [comment]
Sweeet! :lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-:-L5IKFz6XEGqT2znhDbf:b-7iwoar)*

**Comment by pronebird** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-:-L5Ie84_-7tO5VhFFsfp:bnfp4nl)*

**Comment by eriklarko** [comment]
I'll close this PR, cherry-pick the changelog and package.json changes onto master and PR that 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/61#-:-L5KsbNGN9zrfUdcDfUJ:by4k8uf)*

**Comment by eriklarko** [comment]
Closed in favor of https://github.com/mullvad/mullvadvpn-app/pull/62

**Pull request closed without merging**
