### PR TITLE
Convert accordion to ReactXP

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

1. This PR converts Accordion to ReactXP

2. Adjusts the animation duration based on the travel distance, i.e if animation is reversed half way through it will only take half time to animate back to original value.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/108)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/Accordion.js, line 90 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/108#-L8cOC5lHroi50kzVdL0:-L8cOC5lHroi50kzVdL1:b9ptw18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a90515f8cf6308bb0d6c1b1bec12fa334d1c278/app/components/Accordion.js#L90)):*
> ```JavaScript
>     // calculate the animation duration based on travel distance
>     // note: _getValue() is private.
>     const primitiveFromValue = parseInt(fromValue._getValue());
> ```

Sadly there is no public interface to get the animation value and `onLayout` does not provide up to date values on the web :(

I raised an issue here: https://github.com/Microsoft/reactxp/issues/578

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/108)*

**Comment by pronebird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/Accordion.js, line 90 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/108#-L8cOC5lHroi50kzVdL0:-L8cP3CAcGBUwqcScXO-:b-yw2zxt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a90515f8cf6308bb0d6c1b1bec12fa334d1c278/app/components/Accordion.js#L90)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Sadly there is no public interface to get the animation value and `onLayout` does not provide up to date values on the web :(

I raised an issue here: https://github.com/Microsoft/reactxp/issues/578
</blockquote></details>

We probably need to get rid of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/108)*

**Comment by anderklander** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/108#-:-L8cUakx0E9sHeYgJ9hs:bnfp4nl)*

**Comment by pronebird** [comment]
Travis fails for unrelated reasons. I am merging this.

**Comment by anderklander** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/108)*

**Pull request merged**
