### PR TITLE
Add 2022 app audit report and document about it

### PR DESCRIPTION
**Pull request by faern**
Adding the full audit report from this years' security audit by Atredis Partners. Also adding a markdown document explaining the audit and our responses to all identified issues.

Here is the rendered version of the markdown file: https://github.com/mullvad/mullvadvpn-app/blob/2022-audit-report/audits/2022-10-14-atredis.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`audits/2022-10-14-atredis.md` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEopIGJ0M2xYbPpoKet:-NEopIGJ0M2xYbPpoKeu:bagtzmq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fb60b56cbf3e09e24ab5de97f84eda4ffe2ddfa/audits/2022-10-14-atredis.md#L54)):*
> ```Markdown
> found could easily or substantially compromise the security or privacy of the app users.
> 
> Mullvad implemented fixes for two of the findings. Two findings resulted in updated security
> ```

We also updated the security documentation for one of these (`MUL22-02`), as we mention further down. Perhaps that's enough?



_Code quote:_
```Markdown
Mullvad implemented fixes for two of the findings
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`audits/2022-10-14-atredis.md` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEopIGJ0M2xYbPpoKet:-NEoyrtGAadQnHve8hdu:b-i7akrg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fb60b56cbf3e09e24ab5de97f84eda4ffe2ddfa/audits/2022-10-14-atredis.md#L54)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We also updated the security documentation for one of these (`MUL22-02`), as we mention further down. Perhaps that's enough?
</blockquote></details>

True! But I'd argue that the documentation fix for `MUL22-02` was about the part of it that we found ourselves (bootup). So that fix was slightly outside the scope of the audit. And also, because expressing it that way sounds complicated. But I'm open for concrete suggestions.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`audits/2022-10-14-atredis.md` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEopIGJ0M2xYbPpoKet:-NEozb0p8Zt4UtfrRHRL:bhg2om6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fb60b56cbf3e09e24ab5de97f84eda4ffe2ddfa/audits/2022-10-14-atredis.md#L54)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

True! But I'd argue that the documentation fix for `MUL22-02` was about the part of it that we found ourselves (bootup). So that fix was slightly outside the scope of the audit. And also, because expressing it that way sounds complicated. But I'm open for concrete suggestions.
</blockquote></details>

Just wanted to highlight it in case it was skipped by mistake, no change needed.
___
*[`audits/2022-10-14-atredis.md` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEp-d8kCKuFC4zpSsTJ:-NEp-d8kCKuFC4zpSsTK:b-vdzmlk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fb60b56cbf3e09e24ab5de97f84eda4ffe2ddfa/audits/2022-10-14-atredis.md#L74)):*
This sentence sounds a bit strange. I suggest changing to something like below. Slashes are used to represent two variants of the suggested sentence:

> Regardless of the low severity, the issue/bug has been resolved/fixed in the kernel driver.



_Code quote:_
```Markdown
The bug was still fixed of course.
```
___
*[`audits/2022-10-14-atredis.md` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEp6t5g7I49mjPyw-Ws:-NEp6t5g7I49mjPyw-Wt:b9ori5o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fb60b56cbf3e09e24ab5de97f84eda4ffe2ddfa/audits/2022-10-14-atredis.md#L111)):*
Suggested change:

> We've done the following in response to this finding:



_Code quote:_
```Markdown
What we have done in response to this finding is
```
___
*[`audits/2022-10-14-atredis.md` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEp7lv4-4hYwO3EbRcw:-NEp7lv4-4hYwO3EbRcx:b-p85rwa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fb60b56cbf3e09e24ab5de97f84eda4ffe2ddfa/audits/2022-10-14-atredis.md#L142)):*
> ```Markdown
> 
> We wish to thank Atredis Partners for the smooth collaboration, good communication and great
> security assessment work!
> ```

Reviewable seem to complain about a missing newline?



_Code quote:_
```Markdown
work!
```

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`audits/2022-10-14-atredis.md` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEpGMXh3OGYXm-ZrK12:-NEpGMXh3OGYXm-ZrK13:b-zckc4z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5de4af586e1d54ddc57a07e0bcb64fe3f5ee7f3/audits/2022-10-14-atredis.md#L58)):*
I think it would be bit easier to read if this was replaced with:
> All fixes were merged and released before the final...

It was already clarified that not everything was/could be fixed.
___
*[`audits/2022-10-14-atredis.md` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEpFGHD0lwkQyIr_494:-NEpFGHD0lwkQyIr_495:bs4eeop) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5de4af586e1d54ddc57a07e0bcb64fe3f5ee7f3/audits/2022-10-14-atredis.md#L60)):*
"has all found vulnerabilities fixed" makes it sound like we've fixed all the reported issues, which as described above is incorrect. Maybe replace it with something like:
> Version `2022.5-beta1` (and newer) of the desktop app includes all fixes.
___
*[`audits/2022-10-14-atredis.md` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEpGrvZCoz_IlZcjv3v:-NEpGrvZCoz_IlZcjv3w:bh4bi4l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5de4af586e1d54ddc57a07e0bcb64fe3f5ee7f3/audits/2022-10-14-atredis.md#L60)):*
> ```Markdown
> All issues that we implemented fixes for had their fixes merged and released before the final
> report was done and sent over to Mullvad. Version `2022.5-beta1` (and newer) of the desktop
> app has all found vulnerabilies fixed.
> ```

It's also the only use of "vulnerabilities", which I think we should replace with "issues".

(Not relevant if my suggestion is applied but "vulnerabilities" isn't correctly spelled here, it's missing the "ti" towards the end)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`audits/2022-10-14-atredis.md` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEpGMXh3OGYXm-ZrK12:-NEpIbRk6gFqPOXmRJlX:b-nmwf4u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5de4af586e1d54ddc57a07e0bcb64fe3f5ee7f3/audits/2022-10-14-atredis.md#L58)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I think it would be bit easier to read if this was replaced with:
> All fixes were merged and released before the final...

It was already clarified that not everything was/could be fixed.
</blockquote></details>

I see what you mean, and agree. Fixed.
___
*[`audits/2022-10-14-atredis.md` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEpFGHD0lwkQyIr_494:-NEpIv-W5brApU6e-fkz:b-pcc7jh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5de4af586e1d54ddc57a07e0bcb64fe3f5ee7f3/audits/2022-10-14-atredis.md#L60)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

"has all found vulnerabilities fixed" makes it sound like we've fixed all the reported issues, which as described above is incorrect. Maybe replace it with something like:
> Version `2022.5-beta1` (and newer) of the desktop app includes all fixes.
</blockquote></details>

Yeah, makes sense. Fixed.
___
*[`audits/2022-10-14-atredis.md` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-NEpGrvZCoz_IlZcjv3v:-NEpJ4kvDgjV4eNsTdIL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5de4af586e1d54ddc57a07e0bcb64fe3f5ee7f3/audits/2022-10-14-atredis.md#L60)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

It's also the only use of "vulnerabilities", which I think we should replace with "issues".

(Not relevant if my suggestion is applied but "vulnerabilities" isn't correctly spelled here, it's missing the "ti" towards the end)
</blockquote></details>

Done.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4071#-:-NEpJeQKAcqK_ZznrB24:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
