### PR TITLE
Get position and IP from am.i.mullvad.net

### PR DESCRIPTION
**Pull request by faern**
On the frontend it's a bit broken at the moment. Trying to fix it, but could use some help.

On the backend I have removed the `get_public_ip` RPC call, since the IP is now baked into the new `GeoIpLocation` struct returned from `get_current_location`, so the IP can be obtained there instead.

Now the mocked Narnia location is removed in favor of asking am.i.mullvad.net for the current location.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/25)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/lib/backend.js, line 379 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2dQ8IsfRMHkAMh6KQs:-L2dQ8IsfRMHkAMh6KQt:b-2vh8z6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb02d9f51d7357684e3ecfa0bb47b674cea96a1c/app/lib/backend.js#L379)):*
> ```JavaScript
>       latitude: location.latitude,
>       longitude: location.longitude,
>       mullvadExitIp: location.mullvad_exit_ip,
> ```

Yesterday when I did this the new `locationUpdate` was identical to `location`. So I was wondering if I actually needed to do this verbose copy over to a new struct. But now it has one field name different I see, so might have to be kept I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by eriklarko** [comment]
*[mullvad-types/src/location.rs, line 28 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2dUHeWZ9ujJWLP5Qio:-L2dUHeWZ9ujJWLP5Qip:b-7l1ddl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb02d9f51d7357684e3ecfa0bb47b674cea96a1c/mullvad-types/src/location.rs#L28)):*
> ```Rust
>     // pub fn ip(&self) -> Option<IpAddr> {
>     //     IpAddr::from_str(&self.ip).ok()
>     // }
> ```

plong

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by eriklarko** [comment]
Reviewed 13 of 18 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Review status: 18 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 379 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2dQ8IsfRMHkAMh6KQs:-L2e7J6dG7K_X7iEKi6F:bse6gx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fcbf70faa2471f55b6bf7aca8cc90038b11e3dfd/app/lib/backend.js#L379)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yesterday when I did this the new `locationUpdate` was identical to `location`. So I was wondering if I actually needed to do this verbose copy over to a new struct. But now it has one field name different I see, so might have to be kept I guess.
</blockquote></details>

We use camelCase in Javascript so that's why all structures are converted this way. I know it may look silly.

Also, current IPC response validation mechanisms use "exact" object types so the validator throws an error if extra field occurs in the response. That's why I opted in for passing `mullvadExitIp` along even though we don't use it in the UI yet. It can be easily fixed if we used `partialObject({ ... })` instead of `object({ ... })` in response schema but I didn't want to change the way things work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Review status: 18 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-types/src/location.rs, line 28 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2dUHeWZ9ujJWLP5Qio:-L2e8ZTgydeCxjKebZWp:bmp3lmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fcbf70faa2471f55b6bf7aca8cc90038b11e3dfd/mullvad-types/src/location.rs#L28)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

plong
</blockquote></details>

What does it mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Review status: 18 of 23 files reviewed at latest revision, 3 unresolved discussions.

---

*[mullvad-types/src/location.rs, line 20 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2e8zpHgqR5q3yYiKm9:-L2e8zpHgqR5q3yYiKmA:bzbo7d4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca343c2c4421cb4c6ebff3afabc5cbcd9cef9c10/mullvad-types/src/location.rs#L20)):*
> ```Rust
>     pub ip: IpAddr,
>     pub country: String,
>     pub city: Option<String>,
> ```

I just realized it's optional. I'll update the corresponding JS schema.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Review status: 13 of 26 files reviewed at latest revision, 3 unresolved discussions.

---

*[mullvad-types/src/location.rs, line 20 at r3](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2e8zpHgqR5q3yYiKm9:-L2eUQMYHQvD0K9GoA9a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca343c2c4421cb4c6ebff3afabc5cbcd9cef9c10/mullvad-types/src/location.rs#L20)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I just realized it's optional. I'll update the corresponding JS schema.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by faern** [comment]
Review status: 13 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[mullvad-types/src/location.rs, line 28 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2dUHeWZ9ujJWLP5Qio:-L2eV1TfbPBXksZG8Zbp:b4fdsnf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fcbf70faa2471f55b6bf7aca8cc90038b11e3dfd/mullvad-types/src/location.rs#L28)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

What does it mean?
</blockquote></details>

It was pointing at different code before. I forgotten commented out method. It's gone now. This is fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Reviewed 11 of 18 files at r1, 2 of 7 files at r2, 5 of 5 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Review status: 25 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/Connect.js, line 190 at r5](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2euZZUAPLY1Ar7rbVW:-L2euZZUAPLY1Ar7rbVX:b9wi3v0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eff4eb86a3523d135160cd706dc204db528ee797/app/components/Connect.js#L190)):*
> ```JavaScript
> 
>             { /* location when connecting or connected */ }
>             <If condition={ isConnecting || isConnected }>
> ```

This needs to be coordinated with Matt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by faern** [comment]
Review status: 22 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/Connect.js, line 190 at r5](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-L2euZZUAPLY1Ar7rbVW:-L2f2VNW5RbR_3tsXM68:b-skxdra) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eff4eb86a3523d135160cd706dc204db528ee797/app/components/Connect.js#L190)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This needs to be coordinated with Matt.
</blockquote></details>

This has been reverted again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Reviewed 3 of 3 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/25#-:-L2yIZnlLyOz9P1GlnOy:bnfp4nl)*

**Pull request merged**
