### PR TITLE
Upgrade jsonrpc and other dependencies

### PR DESCRIPTION
**Pull request by faern**
Main reason for this was to get rid of the HUGE Json response when downloading the list of relays from master. This because `jsonrpc-client-core` logged it to debug level (which is our default level). And it did not feel right to have at debug level to begin with. So I upgraded `jsonrpc-client-core` (and `-http`) to new versions that log to the trace level instead.

While doing this I also managed to upgrade our jsonrpc server crates to the newest version as well. Not strictly needed, but good to follow along with upgrades.

Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/88)

### CODE REVIEW

**Comment by pronebird** [comment]
Yes please merge because it spams terminal with that JSON.

---

Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88#-:-L6v-8J871s8GUCHFYv7:b-1afmmk)*

**Comment by pronebird** [comment]
Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88)*

**Comment by jvff** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/88)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88)*

**Comment by faern** [comment]
I usually do one round of `cargo update` after each release in order to keep our product as up to date with the ecosystem as possible. This has not happened for quite some time and I felt it was about time.

Since this PR was already purely upgrading of dependencies I felt I could push more of the same thing to it instead of creating another similar PR directly after.

So this PR now does two things:
* Manually upgrade a couple of crates that had major/breaking new releases and would thus not get automatically pulled in by a `cargo update`
* A simple `cargo update` to get the latest non-breaking releases of all our dependencies.

---

Review status: 2 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88#-:-L6xXnzDGHbua5oAJTgG:bxl5otu)*

**Comment by jvff** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88)*

**Comment by pronebird** [comment]
Reviewed 7 of 7 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/88)*

**Pull request merged**
