### PR TITLE
Write e2e tests for split tunneling

### PR DESCRIPTION
**Pull request by hulthe**
Basic E2E tests of split tunneling for Windows and Linux. Also includes some changes to the testing framework that fixes some problems I encountered while implementing and testing this.

The split tunnel test is implemented by spawning a seperate process (`connecton-checker`) that tries to contact https://am.i.mullvad.net, and send TCP, UDP, and ICMP packets to 1.1.1.1.

This test does not run on MacOS ATM. But if split tunnel handling on MacOS isn't notably different from Linux or Windows, then it could be enabled fairly easily.

This PR also:
- Replaces `panics` in `test_function` macro with syn errors, to get nicer compiler errors.
- Enables anyhow errors in e2e tests.
- Makes paths to OVMF vars configurable (the default paths were different on my system).
- Tries to tidy up any code I found hard to read.

^ I could spend some time to split some of these into seperate PRs if you, dear reviewer, thinks its worth it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)

### CODE REVIEW

**Comment by hulthe** [comment]
*[`mullvad-management-interface/src/client.rs` line 594 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtHD-rH3PhIl4QouKEf:-NtHD-rH3PhIl4QouKEg:b-9bjid2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5881da9a259cb2fa0a62e639ddbaaaca7b4afec0/mullvad-management-interface/src/client.rs#L594)):*
> ```XML
>     }
> 
>     #[cfg(target_os = "linux")]
> ```

This one is interesting. It's needed because we run the MullvadProxyClient on a different host from the daemon. Do you see any problems with exposing these methods on other platforms?

**Review by dlon — COMMENTED** [review]
> Reviewed 16 of 23 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)* status: all files reviewed, 11 unresolved discussions (waiting on @hulthe)

___
*[`mullvad-management-interface/src/client.rs` line 594 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtHD-rH3PhIl4QouKEf:-NtLkpv3Co6OlfTt22Fx:b-ioamhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5881da9a259cb2fa0a62e639ddbaaaca7b4afec0/mullvad-management-interface/src/client.rs#L594)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

This one is interesting. It's needed because we run the MullvadProxyClient on a different host from the daemon. Do you see any problems with exposing these methods on other platforms?
</blockquote></details>

It's nice that we cannot accidentally use these methods when they're unavailable. But since we need them, I think it's fine.
___
*[`test/scripts/build-runner-image.sh` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLnpZ57EE2n9P_a8Ka:-NtLnpZ57EE2n9P_a8Kb:bh2yw4g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/scripts/build-runner-image.sh#L36)):*
> ```Shell
>             -i "${TEST_RUNNER_IMAGE_PATH}" \
>             "${SCRIPT_DIR}/../target/$TARGET/release/test-runner.exe" \
>             "${SCRIPT_DIR}/../target/$TARGET/release/connection-checker.exe" \
> ```

`ssh-setup.sh` should also be updated to copy this file from the temp dir.
___
*[`test/test-manager/src/tests/mod.rs` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLoVDr3Wd-JZQoQkzQ:-NtLoVDsEZzGePIplRlJ:b7ym6p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/mod.rs#L39)):*
> ```XML
> 
> #[derive(thiserror::Error, Debug)]
> pub enum Error {
> ```

We could probably get rid of this `Error`. Not very unrelated to the PR, though.
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLwGIf8ZtIO8ird6d-:-NtLwGIf8ZtIO8ird6d0:b-4ttlwa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L18)):*
> ```XML
> use super::{config::TEST_CONFIG, helpers, TestContext};
> 
> const CHECKER_PATH_WINDOWS: &str = "E:\\connection-checker.exe";
> ```

The path should be relative to `TEST_CONFIG.artifacts_dir`.
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtM063f0d85NUr-Z55g:-NtM063f0d85NUr-Z55h:b65lxx0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L27)):*
> ```XML
> /// - Splitting/unsplitting should work regardless if process is running.
> #[test_function]
> pub async fn test_split_tunnel(
> ```

We need to prevent the test from running on macOS.
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLxD6HBT7R4JZlzu4G:-NtLxD6HBT7R4JZlzu4H:b-1qn7z6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L32)):*
> ```XML
>     mut mullvad_client: MullvadProxyClient,
> ) -> anyhow::Result<()> {
>     helpers::disconnect_and_wait(&mut mullvad_client).await?;
> ```

This can be removed.
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtM-xDg5cUvGC2fX0aO:-NtM-xDg5cUvGC2fX0aP:bp83s5v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L85)):*
> ```XML
>     (handle.assert_secure().await)
>         .with_context(|| "Test connected and being unsplit while running")?;
>     drop(handle);
> ```

Nit: This can be removed.
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 110 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtM00vmAH7DK6q5AeFR:-NtM00vmAH7DK6q5AeFS:bylwjn3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L110)):*
> ```XML
> }
> 
> struct ConnectonStatus {
> ```

Nit: Connecton
___
*[`test/test-rpc/src/transport.rs` line 259 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLrBOABWumFYq8GFKa:-NtLrBOABWumFYq8GFKb:bl4a07o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-rpc/src/transport.rs#L259)):*
> ```XML
> 
>     loop {
>         futures::select! {
> ```

Nice. A lot more readable. :sweat_smile: 
___
*[`test/test-runner/src/main.rs` line 449 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLs5uw3PUGf92mMB9W:-NtLs5ux9DmWoCAkYvat:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-runner/src/main.rs#L449)):*
> ```XML
>             .spawned_procs
>             .get_mut(&pid)
>             .expect("TODO: unknown pid error");
> ```

TODO
___
*[`test/test-runner/src/main.rs` line 484 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLrzmP7mJ6eC9eTsuk:-NtLrzmP7mJ6eC9eTsul:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-runner/src/main.rs#L484)):*
> ```XML
>             .spawned_procs
>             .get_mut(&pid)
>             .expect("TODO: unknown pid error");
> ```

TODO
___
*[`test/test-runner/src/main.rs` line 504 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLs9ze8CnRc4n-HOfQ:-NtLs9ze8CnRc4n-HOfR:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-runner/src/main.rs#L504)):*
> ```XML
>             .spawned_procs
>             .get_mut(&pid)
>             .expect("TODO: unknown pid error");
> ```

TODO
___
*[`test/test-runner/src/util.rs` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLtVMr7TUBGbLchpfS:-NtLtVMr7TUBGbLchpfT:b79mkmy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-runner/src/util.rs#L2)):*
> ```XML
> /// Drop guard that executes the provided callback function when dropped.
> pub struct OnDrop<F = Box<dyn FnOnce() + Send>>
> ```

I think we could probably replace `AbortOnDrop` with this as well.

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)* status: 24 of 26 files reviewed, 9 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/tests/split_tunnel.rs` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLwGIf8ZtIO8ird6d-:-NtMJ_nw4TbL4PSqPYoc:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L18)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The path should be relative to `TEST_CONFIG.artifacts_dir`.
</blockquote></details>

Fixed!
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLxD6HBT7R4JZlzu4G:-NtMJrMn0XWv2jt1eiCd:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L32)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This can be removed.
</blockquote></details>

:+1: 
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtM-xDg5cUvGC2fX0aO:-NtMJpQHBXIw0lDElvO5:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L85)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: This can be removed.
</blockquote></details>

:+1: 
___
*[`test/test-rpc/src/transport.rs` line 259 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLrBOABWumFYq8GFKa:-NtMK2zcCshK6sQcxVv-:b-f4pn18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-rpc/src/transport.rs#L259)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nice. A lot more readable. :sweat_smile:
</blockquote></details>

happy you agree :D

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)* status: 24 of 26 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`test/scripts/build-runner-image.sh` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLnpZ57EE2n9P_a8Ka:-NtMKGQc6em-Rl3IH02G:b-7ql1td) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/scripts/build-runner-image.sh#L36)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`ssh-setup.sh` should also be updated to copy this file from the temp dir.
</blockquote></details>

fixed
___
*[`test/test-manager/src/tests/split_tunnel.rs` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLwGIf8ZtIO8ird6d-:-NtMKF2t2A5wjgAvYVDE:b-7ql1td) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/split_tunnel.rs#L18)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Fixed!
</blockquote></details>

fixed

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)* status: all files reviewed, 3 unresolved discussions (waiting on @hulthe)

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)* status: 24 of 27 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/tests/mod.rs` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLoVDr3Wd-JZQoQkzQ:-NtRXANlA_gravAf2miP:b9ycj0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-manager/src/tests/mod.rs#L39)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We could probably get rid of this `Error`. Not very unrelated to the PR, though.
</blockquote></details>

I could look into doing this in a seperate PR
___
*[`test/test-runner/src/util.rs` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtLtVMr7TUBGbLchpfS:-NtRWyNREdTOjOhwDgjC:b-3lgi9v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17e30b579565aa7153a26eb7fa2862633f4deb16/test/test-runner/src/util.rs#L2)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think we could probably replace `AbortOnDrop` with this as well.
</blockquote></details>

Agreed, but they're in different crates so we'd need to move it to a shared one.

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906)* status: all files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`test/test-manager/src/tests/test_metadata.rs` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5906#-NtRXIk961ZPpWcfqoeK:-NtRXIk961ZPpWcfqoeL:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52b56e5a2661c85405d2729b6b1e52ebf503096c/test/test-manager/src/tests/test_metadata.rs#L8)):*
> ```XML
>     pub name: &'static str,
>     pub command: &'static str,
>     pub targets: &'static [Os],
> ```

Nice!

**Pull request merged**
