### PR TITLE
Reuse WebSocket connection in `WsIpcClient`

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Internal refactor; not user visible.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[talpid-ipc/src/client.rs, line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBeQoruD7dtI-Y6dD71:-LBeQoruD7dtI-Y6dD72:b-ymt21z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L162)):*
> ```Rust
>     url: url::Url,
>     next_id: i64,
>     active_request: Arc<Mutex<Option<(i64, mpsc::Sender<Result<JsonValue>>)>>>,
> ```

What is the textual description of this field? The type itself is a bit hard to interpret IMO.

---

*[talpid-ipc/src/client.rs, line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBePCKH2iqX7JeO4SVU:-LBePCKH2iqX7JeO4SVV:b-jdvrxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L163)):*
> ```Rust
>     next_id: i64,
>     active_request: Arc<Mutex<Option<(i64, mpsc::Sender<Result<JsonValue>>)>>>,
>     sender: Option<Mutex<ws::Sender>>,
> ```

I only see `sender` used inside the `WsIpcClient`, and only in a `&mut self` context. So why must it be residing inside a `Mutex` instead of directly in the `Option`?

---

*[talpid-ipc/src/client.rs, line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBeQHFgB3QGzoheZ-Y3:-LBeQHFgB3QGzoheZ-Y4:bfbn9ew) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L179)):*
> ```Rust
>     }
> 
>     pub fn connect(&mut self) -> Result<()> {
> ```

Would it maybe make sense to bake `connect` into `new`? That would eliminate the state of having a `WsIpcClient` that is not connected. That would make it possible to remove the `Option` from the `sender` field and it would remove the theoretical panic in `send_request` that accesses `sender`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153)*

**Comment by jvff** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[talpid-ipc/src/client.rs, line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBeQoruD7dtI-Y6dD71:-LBefwIN2WDXTP4tRpYz:balibgl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L162)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What is the textual description of this field? The type itself is a bit hard to interpret IMO.
</blockquote></details>

Done. This field is a shared mutable reference to the ID and response channel of the current active request. Initially I implemented a `HashMap<i64, mpsc::Sender<JsonValue>>` to support multiple requests, but thought that it was simpler to have only one active request. So the tuple was created as a "one-entry `HashMap`". But I agree the type became complex.

I tried to make the field less dense and clearer by having an explicit `ActiveRequest` type. I think this made it clearer, at the cost of extra verbosity. My only fear is if there are too many types used together in the same module, but this is arguably a simple type.

---

*[talpid-ipc/src/client.rs, line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBePCKH2iqX7JeO4SVU:-LBehcz71zsuRPPG4Yw1:b-j1kupl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L163)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I only see `sender` used inside the `WsIpcClient`, and only in a `&mut self` context. So why must it be residing inside a `Mutex` instead of directly in the `Option`?
</blockquote></details>

Done. I had added a `Mutex` to it so that the type implements `panic::RefUnwindSafe` (required by `openvpn-plugin`). Now that you mentioned it, I think a saner solution is to have the `Mutex` in `talpid_openvpn_plugin::processing::EventProcessor` instead of in `WsIpcClient`.

---

*[talpid-ipc/src/client.rs, line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBeQHFgB3QGzoheZ-Y3:-LBf61I7EW3PYDbOV69g:bczaalm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L179)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Would it maybe make sense to bake `connect` into `new`? That would eliminate the state of having a `WsIpcClient` that is not connected. That would make it possible to remove the `Option` from the `sender` field and it would remove the theoretical panic in `send_request` that accesses `sender`.
</blockquote></details>

Done. I think it also makes it clearer that it represents an open connection. Thanks!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153)*

**Comment by faern** [comment]
I salute you for understanding `ws` well enough to solve this :)

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-ipc-client/src/lib.rs, line 172 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBf8EAc0aI5STHuxwEP:-LBf8EAe8mh60KSfwUPm:b-rossrj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/553286a2d899d11ea98d6d2f1151d7adb4f772e5/mullvad-ipc-client/src/lib.rs#L172)):*
> ```Rust
>     {
>         let mut rpc_client = WsIpcClient::connect(self.address.clone())
>             .chain_err(|| ErrorKind::StartRpcClient(self.address.clone()))?;
> ```

Don't you want/need to store a single `WsIpcClient` in the `DaemonRpcClient` in order to use the persisted connection, and thus solve the auth issue? Or maybe that is planned for a separate PR?

---

*[talpid-ipc/src/client.rs, line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBeQoruD7dtI-Y6dD71:-LBfBQd7ARcyGBSRiTwd:b-9755fa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bffe2ed0320a0435693faf15a1a257cdf3212da1/talpid-ipc/src/client.rs#L162)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. This field is a shared mutable reference to the ID and response channel of the current active request. Initially I implemented a `HashMap<i64, mpsc::Sender<JsonValue>>` to support multiple requests, but thought that it was simpler to have only one active request. So the tuple was created as a "one-entry `HashMap`". But I agree the type became complex.

I tried to make the field less dense and clearer by having an explicit `ActiveRequest` type. I think this made it clearer, at the cost of extra verbosity. My only fear is if there are too many types used together in the same module, but this is arguably a simple type.
</blockquote></details>

Thank you.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-:-LBfBTzD77HfgfP70RrY:b-xz2ch7)*

**Comment by jvff** [comment]
Thanks :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[mullvad-ipc-client/src/lib.rs, line 172 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-LBf8EAc0aI5STHuxwEP:-LBfHS-1C3PqGIWusihy:bqdesqu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/553286a2d899d11ea98d6d2f1151d7adb4f772e5/mullvad-ipc-client/src/lib.rs#L172)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Don't you want/need to store a single `WsIpcClient` in the `DaemonRpcClient` in order to use the persisted connection, and thus solve the auth issue? Or maybe that is planned for a separate PR?
</blockquote></details>

Yes, this is on a separate PR :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153#-:-LBfHMFi02CeBUwdxNkv:bvtk9y9)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r1, 2 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153)*

**Comment by pinkisemils** [comment]
Reviewed 3 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153)*

**Pull request merged**
