### PR TITLE
Fix screenshots test

### PR DESCRIPTION
**Pull request by rablador**
Fixes the broken screenshots test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
To run the tests locally you can either run them in Xcode or through fastlane. The latter takes actual screenshots and require some additional setup: https://github.com/mullvad/mullvadvpn-app/tree/main/ios#screenshots-for-appstore

Running the tests in Xcode require only this configuration step of above: https://github.com/mullvad/mullvadvpn-app/tree/main/ios#configuration

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-:-Nl4Dqai9WI6rYODuyco:b-n4o9h8)* status: 0 of 5 files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
Are the screenshot tests ran as part of the regular test suite? If not, we should change the regular `ios.yml` workflow to execute those tests too. 

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-:-Nl4KlBsAOacgeVfgwam:b-ecfroo)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`.github/workflows/ios-screenshots.yml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4KFmbDrEvmXGGOVkQ:-Nl4KFmbDrEvmXGGOVkR:b-o4y4gf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L9)):*
> ```YAML
>       - ios/.swiftformat
>       - ios/**/*.swift
>       - ios/**/*.xctestplan
> ```

When I tag releases, I often change just a single XCConfig and the `Assets/changes.txt` files, and since the all the `push` condiitons need to be satisfied, screenshots would never be ran. 
___
*[`.github/workflows/ios-screenshots.yml` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4If_vDhy35aFh_Zk5:-Nl4If_vDhy35aFh_Zk6:bjzvbeb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L16)):*
> ```YAML
>   check-formatting:
>     name: Check formatting
>     runs-on: macos-13-xlarge
> ```

I don't believe we need to run this job for screenshots.
___
*[`.github/workflows/ios-screenshots.yml` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4IjG48hLOB9EYC56J:-Nl4IjG48hLOB9EYC56K:b8oi7ma) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L33)):*
> ```YAML
> 
>   swiftlint:
>     name: Run swiftlint
> ```

Nor should we run swiftlint here too.
___
*[`.github/workflows/ios-screenshots.yml` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4JTEuCH3Bj7JLTPfI:-Nl4JTEuCH3Bj7JLTPfJ:bo34yzu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L48)):*
> ```YAML
>   test:
>     name: Take screenshots
>     runs-on: macos-13-xlarge
> ```

We should try out different instance sizes and see if a smaller instance would work just as well - this job won't ever be blocking a merge, so it isn't critical that these tests must finish _fast_. 
___
*[`.github/workflows/ios-screenshots.yml` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4Iz3o9n9AHX9sGIeW:-Nl4Iz3o9n9AHX9sGIeX:b-xe6f0j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L99)):*
> ```YAML
>           brew install xcbeautify
> 
>       - name: Run screenshot tests
> ```

A more apt name would be _Create screenshots_, I think.
___
*[`ios/Snapfile` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4J6_s9LaKZB9rfSj8:-Nl4J6_s9LaKZB9rfSj9:b-q7ohe8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4003ba7ae029e8c8937eea5893e5c025000f5406/ios/Snapfile#L6)):*
> ```Ruby
>   "iPhone 11 Pro Max", # 6.5"
>   "iPhone 14 Pro Max", # 6.7"
>   "iPad Pro (12.9-inch) (2nd generation)",
> ```

I'll double check this tomorrow, but we might want the older iPad too.

**Review by pinkisemils — COMMENTED** [review]
However, if running the screenshot test itself would take far too long, then we can run it on a slower instance once a day instead of doing it for every commit :shrug: .

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-:-Nl4MSAA3KrxS45jLSdT:b-4etqxv)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @rablador)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/Snapfile` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4J6_s9LaKZB9rfSj8:-Nl8-tfqCJW8dD5pyK-R:bmsl5re) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4003ba7ae029e8c8937eea5893e5c025000f5406/ios/Snapfile#L6)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'll double check this tomorrow, but we might want the older iPad too.
</blockquote></details>

Yep, we need both the 6th gen and 2nd gen 12.9" iPad Pros.

**Review by rablador — COMMENTED** [review]
After discussing with @pinkisemils IRL we decided to run the screenshot tests in the same github action. They add about a minute to the action overall.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-:-Nl8Rehw9xkxwLQZ8Co9:bv9qp6h)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`.github/workflows/ios-screenshots.yml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4KFmbDrEvmXGGOVkQ:-Nl8RsjV-TQy554LPgZv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L9)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

When I tag releases, I often change just a single XCConfig and the `Assets/changes.txt` files, and since the all the `push` condiitons need to be satisfied, screenshots would never be ran.
</blockquote></details>

Done.
___
*[`.github/workflows/ios-screenshots.yml` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4If_vDhy35aFh_Zk5:-Nl8RtQy-u7n613na3NZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L16)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I don't believe we need to run this job for screenshots.
</blockquote></details>

Done.
___
*[`.github/workflows/ios-screenshots.yml` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4IjG48hLOB9EYC56J:-Nl8RuVLE6Ay6EX3N3PV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L33)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Nor should we run swiftlint here too.
</blockquote></details>

Done.
___
*[`.github/workflows/ios-screenshots.yml` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4Iz3o9n9AHX9sGIeW:-Nl8S0MJ5nu3G5cOFhbT:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L99)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

A more apt name would be _Create screenshots_, I think.
</blockquote></details>

Done
___
*[`ios/Snapfile` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4J6_s9LaKZB9rfSj8:-Nl8EZrd4XmzMPe6WVmI:b90n57w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4003ba7ae029e8c8937eea5893e5c025000f5406/ios/Snapfile#L6)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yep, we need both the 6th gen and 2nd gen 12.9" iPad Pros.
</blockquote></details>

There are the ones we can get from github:

iPad Air (5th generation)  
iPad (10th generation)  
iPad mini (6th generation)  
iPad Pro (11-inch) (4th generation)  
iPad Pro (12.9-inch) (6th generation)

After IRL discussion we settled on adding iPad Pro (11-inch) (4th generation) as well.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/ios-screenshots.yml` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-Nl4JTEuCH3Bj7JLTPfI:-Nl8fV2H913m3WuCLbZd:bbdaiha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4a4552f323519cc093e162fae40bab6724c1cef7/.github/workflows/ios-screenshots.yml#L48)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We should try out different instance sizes and see if a smaller instance would work just as well - this job won't ever be blocking a merge, so it isn't critical that these tests must finish _fast_.
</blockquote></details>

I tried running the regular tests on the slower intel mac, and it's slower than it is cheap, so it'd cost about the same.

**Review by pinkisemils — APPROVED** [review]
Let's merge this :) 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558#-:-Nl8fg1j9NADI2fMJQpf:bu155zp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
