### PR TITLE
Version check platform header

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds the `M-Platform-Version` header to the version check API call. To accomplish this the `os` module in `mullvad-problem-report` has been moved to `mullvad-rpc` to make it accessible from both packages.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[CHANGELOG.md, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk98f4-O_BHRTjYZbd:-MOk98f4-O_BHRTjYZbe:b-807afv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/CHANGELOG.md#L27)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - Add header containing OS version to version-check API call to enable OS specific compatiblitiy and
> ```

Typo.
___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MOk9aB21y1SkxvQPeKF:b-6a5jrg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
> ```Rust
> 
> #[cfg(target_os = "linux")]
> pub mod os {
> ```

I think these functions should be in `mullvad_rpc::os`, not `mullvad_rpc::os::os`.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @raksooo)

___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MOlIbEv-uripVkG5MmB:b1mmvgw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think these functions should be in `mullvad_rpc::os`, not `mullvad_rpc::os::os`.
</blockquote></details>

I agree, check the DNS and firewall modules to see how we've done this elsewhere.
___
*[mullvad-rpc/src/rest.rs, line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOlIrfiDGvxKam_BDZR:-MOlIrfiDGvxKam_BDZS:b-3hy37c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/rest.rs#L416)):*
> ```Rust
>         path: &str,
>         method: Method,
>         headers: Option<HashMap<&str, String>>,
> ```

I'd rather have this be a builder method on the `Request` type rather than an argument in this helper function. It should be possible to mutate the already built request via [`mut_headers()`](https://docs.rs/hyper/0.13.9/hyper/struct.Request.html#method.headers_mut).

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[CHANGELOG.md, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk98f4-O_BHRTjYZbd:-MOosfj75htiZwHdFWsv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/CHANGELOG.md#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Typo.
</blockquote></details>

Done.
___
*[mullvad-rpc/src/rest.rs, line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOlIrfiDGvxKam_BDZR:-MOotBr8DWORSGoAXD7R:bbmnrgv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/rest.rs#L416)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'd rather have this be a builder method on the `Request` type rather than an argument in this helper function. It should be possible to mutate the already built request via [`mut_headers()`](https://docs.rs/hyper/0.13.9/hyper/struct.Request.html#method.headers_mut). 
</blockquote></details>

Good idea! Something like this then?
___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MOosjaw22fdXNOYFRGI:bivy0uf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I agree, check the DNS and firewall modules to see how we've done this elsewhere.
</blockquote></details>

I put the `os` module in `lib.rs` in the new `platform-metadata` since it's currently the only content in that crate. Would you prefer it to be in a separate file?

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @dlon and @raksooo)

___
*[mullvad-rpc/src/lib.rs, line 327 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOpS7w342Bj1OISDkbw:-MOpS7w342Bj1OISDkbx:b-gfysy6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cd87bf203d4f55f4b4e985c0aab59e707d6a0f44/mullvad-rpc/src/lib.rs#L327)):*
> ```Rust
> 
>         let mut headers = HashMap::new();
>         headers.insert("M-Platform-Version", os::version());
> ```

`os::version` is blocking but this function shouldn't block, so it should be passed as a parameter here, IMO.
___
*[mullvad-rpc/src/lib.rs, line 329 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOpQzbpCB0JrVji2mhT:-MOpQzbpCB0JrVji2mhU:b2x2xis) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cd87bf203d4f55f4b4e985c0aab59e707d6a0f44/mullvad-rpc/src/lib.rs#L329)):*
> ```Rust
>         headers.insert("M-Platform-Version", os::version());
> 
>         let request = rest::send_request(
> ```

Instead of changing `send_request` to accept headers, I'd prefer to create the `Request` type and send it via 
```rust
let request = self.handle.factory.get(format!("/v1/releases/{}/{}", platform, version));
request.add_header("M-Platform_Version", os_version);

let response = service.request(request). parse_rest_response(response, expected_status).await
```
___
*[mullvad-rpc/src/rest.rs, line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOlIrfiDGvxKam_BDZR:-MOpQUg49jAUrmfADwmA:b3i2gy0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/rest.rs#L416)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Good idea! Something like this then?
</blockquote></details>

Yeah, but there's still a lot of `None`'s  for the `send_request` helper call sites. I'd like those to be changed too.
___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MOpO0Df83wA4zs_IpIX:b-ob7efo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I put the `os` module in `lib.rs` in the new `platform-metadata` since it's currently the only content in that crate. Would you prefer it to be in a separate file?
</blockquote></details>

It'd be better to have all the implementations be in `imp` modules like this:
```rust
#[cfg(target_os="linux")]
#[path = "linux.rs"]
mod imp;

#[cfg(target_os="macos")]
#[path = "macos.rs"]
mod imp;
...

pub use imp::{version, extra_metadata};
```

Or at the very least, make these modules not public, and just expose the functions directly - `pub use os::*;`.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/version_check.rs, line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MP3SHQ92F8q_hZ9KzUY:-MP3SHQ92F8q_hZ9KzUZ:bw7ii22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9b841dc49d3f5db38db8163a59abde521e38331/mullvad-daemon/src/version_check.rs#L146)):*
> ```Rust
>                 PRODUCT_VERSION.to_owned(),
>                 PLATFORM,
>                 platform_version.clone(),
> ```

Is there any better alternative than doing the double `clone` of the `platform_version`?
___
*[mullvad-rpc/src/lib.rs, line 327 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOpS7w342Bj1OISDkbw:-MP3SRIJDKnYWRwBS-a5:b4d60sp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cd87bf203d4f55f4b4e985c0aab59e707d6a0f44/mullvad-rpc/src/lib.rs#L327)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`os::version` is blocking but this function shouldn't block, so it should be passed as a parameter here, IMO.
</blockquote></details>

I've put it `start` in `mullvad-daemon` instead.
___
*[mullvad-rpc/src/lib.rs, line 329 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOpQzbpCB0JrVji2mhT:-MP3SjWd8q9vOcXKOPu0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cd87bf203d4f55f4b4e985c0aab59e707d6a0f44/mullvad-rpc/src/lib.rs#L329)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Instead of changing `send_request` to accept headers, I'd prefer to create the `Request` type and send it via 
```rust
let request = self.handle.factory.get(format!("/v1/releases/{}/{}", platform, version));
request.add_header("M-Platform_Version", os_version);

let response = service.request(request). parse_rest_response(response, expected_status).await
```
</blockquote></details>

Done.
___
*[mullvad-rpc/src/rest.rs, line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOlIrfiDGvxKam_BDZR:-MP3Spee03eSALDhsWya:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/rest.rs#L416)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yeah, but there's still a lot of `None`'s  for the `send_request` helper call sites. I'd like those to be changed too.
</blockquote></details>

Done.
___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MP3SOlw9ZnzDHpfHiYH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It'd be better to have all the implementations be in `imp` modules like this:
```rust
#[cfg(target_os="linux")]
#[path = "linux.rs"]
mod imp;

#[cfg(target_os="macos")]
#[path = "macos.rs"]
mod imp;
...

pub use imp::{version, extra_metadata};
```

Or at the very least, make these modules not public, and just expose the functions directly - `pub use os::*;`.
</blockquote></details>

Done.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 11 files at r2, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @dlon and @raksooo)

___
*[mullvad-daemon/src/lib.rs, line 523 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MP3uskIEjOD_2BcwI5u:-MP3uskIEjOD_2BcwI5v:b-fnyljx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9b841dc49d3f5db38db8163a59abde521e38331/mullvad-daemon/src/lib.rs#L523)):*
> ```Rust
> 
>         let app_version_info = version_check::load_cache(&cache_dir);
>         let platform_version = mullvad_platform_metadata::version();
> ```

Since this isn't used anywhere else in the daemon, it could be better to call this from within `VersionUpdater::new`. 
___
*[mullvad-daemon/src/version_check.rs, line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MP3SHQ92F8q_hZ9KzUY:-MP3dmbbA-wtIXyD4eJ-:b-qqpmoi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9b841dc49d3f5db38db8163a59abde521e38331/mullvad-daemon/src/version_check.rs#L146)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Is there any better alternative than doing the double `clone` of the `platform_version`?
</blockquote></details>

No, and it kind of makes sense - you move the version first into the closure, and the closure has to return futures which own the version too. You could change it to an `Arc<_>`, but I don't think the clone is too heavy in this case.
___
*[mullvad-platform-metadata/src/lib.rs, line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MP3kB8bBfph7srGk82M:-MP3kB8bBfph7srGk82N:ba54g81) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9b841dc49d3f5db38db8163a59abde521e38331/mullvad-platform-metadata/src/lib.rs#L31)):*
> ```Rust
>             let gathered_info = format!(
>                 "{} {}",
>                 os_name.unwrap_or_else(|| "[unknown distribution]".to_owned()),
> ```

The `unwrap_or_else` is used here to not have to  allocate unless `os_name` is None, right? This can be _somewhat_ simplified to completely forego the allocation - `os_name.deref().unwrap_or("[unknown distribution]")`.  The same applies to `os_version` and the android implementation below.
___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MP3gCV57o6HGQS1QH_V:byvvkd3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Preferably, the modules should be put into files rather than inlined modules, but this can be left as is.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 523 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MP3uskIEjOD_2BcwI5u:-MP48Zvr9EaN5ishwWIN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9b841dc49d3f5db38db8163a59abde521e38331/mullvad-daemon/src/lib.rs#L523)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Since this isn't used anywhere else in the daemon, it could be better to call this from within `VersionUpdater::new`. 
</blockquote></details>

Done.
___
*[mullvad-platform-metadata/src/lib.rs, line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MP3kB8bBfph7srGk82M:-MP48mgJ4Ce1ZyIgXfYh:b5iej8j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9b841dc49d3f5db38db8163a59abde521e38331/mullvad-platform-metadata/src/lib.rs#L31)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The `unwrap_or_else` is used here to not have to  allocate unless `os_name` is None, right? This can be _somewhat_ simplified to completely forego the allocation - `os_name.deref().unwrap_or("[unknown distribution]")`.  The same applies to `os_version` and the android implementation below.
</blockquote></details>

These modules are just copied from `mullvad-problem-report::os` and hasn't changed in this PR so I'll leave them as is.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/os.rs, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MOk9aB21y1SkxvQPeKE:-MP4Ay4V1A-ddwGQKoMV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae3130196f7cebd30952ece3cd02a464c3894d5/mullvad-rpc/src/os.rs#L4)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Preferably, the modules should be put into files rather than inlined modules, but this can be left as is.
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r3, 3 of 5 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-:-MP4btmc2NiSs6Y6Rvmf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Comment by raksooo** [comment]
I've updated the PR with a new function called `short_version` which is the same for all platforms except for Windows where stuff like build number is redacted. On macOS the string already is short and on Linux I'm not sure if there is a reliable way to redact it.

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mullvad-platform-metadata/src/lib.rs, line 107 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MQCExWVAg4KQYpfCSSp:-MQCExWVAg4KQYpfCSSq:b-hdyu3z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/981a1fb8d6eed4f40a8d6588fe5e07370938e412/mullvad-platform-metadata/src/lib.rs#L107)):*
> ```Rust
>             let mut split = line.split(":");
>             if let (Some(key), Some(value)) = (split.next(), split.next()) {
>                 Some((key.to_owned(), value.to_owned()))
> ```

Why not use a `HashMap` here? Iterating over the key-value pairs in `parse_version` and `parse_full_version` would be unnecessary.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 8 of 16 files reviewed, all discussions resolved (waiting on @dlon)

___
*[mullvad-platform-metadata/src/lib.rs, line 107 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MQCExWVAg4KQYpfCSSp:-MQD2acX1PtqdkIqgXBn:bt7r50y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/981a1fb8d6eed4f40a8d6588fe5e07370938e412/mullvad-platform-metadata/src/lib.rs#L107)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why not use a `HashMap` here? Iterating over the key-value pairs in `parse_version` and `parse_full_version` would be unnecessary.
</blockquote></details>

I agree. Fixed. I've moved the each module to it's own file as well and this code can now be found in `windows.rs`

**Review by dlon — APPROVED** [review]
> Reviewed 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[mullvad-platform-metadata/src/lib.rs, line 17 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MQD6ZRIBSyN80BpwwUo:-MQD6ZRJ8E60w3i4fudO:b-3g65zb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c94ffa59da0a5134260e3dcf13956c006d8989d7/mullvad-platform-metadata/src/lib.rs#L17)):*
> ```Rust
> mod imp;
> 
> pub use self::imp::imp::{extra_metadata, short_version, version};
> ```

You can remove one `::imp` if you move all functions out of the `imp` module in all OS-specific files.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: 11 of 16 files reviewed, all discussions resolved (waiting on @dlon)

___
*[mullvad-platform-metadata/src/lib.rs, line 17 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362#-MQD6ZRIBSyN80BpwwUo:-MQDECBG2NtddQE2Tde5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c94ffa59da0a5134260e3dcf13956c006d8989d7/mullvad-platform-metadata/src/lib.rs#L17)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You can remove one `::imp` if you move all functions out of the `imp` module in all OS-specific files.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2362)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
