### PR TITLE
Migrate from sinon to chai-spies

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

Not a user facing change.

This PR refines tests and migrates them from `sinon` to `chai-spies`. Since we already use `chai` it makes sense to use `spies` plugin for it than bringing the whole other framework.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[test/.eslintrc, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNCIK_9MDFd87qrfox:-LFNCIK_9MDFd87qrfoy:b-oste5a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L1)):*
> ```
> {
> ```

.eslintrc cascade so this is only a subset of rules for test environment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @jvff)

---

*[test/.eslintrc, line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNCPaO1RdcjgIZ8QXA:-LFNCPaO1RdcjgIZ8QXB:b-yiblub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L3)):*
> ```
> {
>   "rules": {
>     "no-unused-expressions" : "off",
> ```

It's common to have unused expressions in chai, i.e:

```
// will throw an error, if function is not called once
expect(func).should.have.been.called.once;
```

There is not much we can do about it, and `once()` is not a function but is likely a getter.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 5 unresolved discussions (waiting on @jvff)

---

*[test/.eslintrc, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNDX4G2CAL_xyrTTtg:-LFNDX4G2CAL_xyrTTth:b-vowzyc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L10)):*
> ```
>   },
>   "globals": {
>     "expect": true,
> ```

The reason why I exported `expect` and `spy` is because we use them quite often across many tests so it felt redundant. On the other side, this is also as a part of Flow plumbing because `chai-spies` extends `chai` with `spy` (`chai.spy`) dynamically and Flow does not support such tricks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 5 unresolved discussions (waiting on @jvff)

---

*[test/.eslintrc, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNDX4G2CAL_xyrTTtg:-LFNDtgN7Y7Ron8Lx83O:b7jahe3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L10)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

The reason why I exported `expect` and `spy` is because we use them quite often across many tests so it felt redundant. On the other side, this is also as a part of Flow plumbing because `chai-spies` extends `chai` with `spy` (`chai.spy`) dynamically and Flow does not support such tricks.
</blockquote></details>

ps: it felt redundant to `import` expect and spy in every test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 6 unresolved discussions (waiting on @jvff)

---

*[.eslintrc, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNE0K61nJ9MFUs6GfX:-LFNE0K61nJ9MFUs6GfY:b-p9qe2m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/.eslintrc#L30)):*
> ```
>       "varsIgnorePattern": "_.*"
>     }],
>     "block-scoped-var": "error",
> ```

This enables errors like:

```
if (true) {
  var x = 10;
}

// ERROR: x is defined in different scope
console.log('x is ' + x);
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by jvff** [comment]
*[test/.eslintrc, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNDOVI7uElNruX2whP:-LFNMupd5a1MZAmdXDSo:b3cj2pp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L7)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Tests run with mocha automatically exported, i.e functions like `it` and `describe` are globally available without explicit `import`.
</blockquote></details>

This is enabled here? Or is this just telling the linter?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 8 unresolved discussions (waiting on @jvff and @pronebird)

---

*[test/.eslintrc, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNDOVI7uElNruX2whP:-LFNOKZB5AuJxZvTlrLx:b-eddb1h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This is enabled here? Or is this just telling the linter?
</blockquote></details>

It just tells the linter that it should complain about missing `it` and `describe` and assume that they exist, but the actual implicit import happens when we run `electron-mocha`, which basically warms up the testing environment for us and then includes our tests javascript.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 8 unresolved discussions (waiting on @jvff and @pronebird)

---

*[test/.eslintrc, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNDOVI7uElNruX2whP:-LFNObTm8WqBZg6x6FNp:b-2t2swl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/044513dfff51a0ef318cba1fcd2cdb7cad991955/test/.eslintrc#L7)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It just tells the linter that it should complain about missing `it` and `describe` and assume that they exist, but the actual implicit import happens when we run `electron-mocha`, which basically warms up the testing environment for us and then includes our tests javascript.
</blockquote></details>

/it should complain/it should *NOT* complain/

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 9 unresolved discussions (waiting on @jvff)

---

*[test/setup/renderer.js, line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNOzQwAOO_K8fQMnc-:-LFNOzQwAOO_K8fQMnc0:b-vo6828) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63c40163dba4d00f4d20eab7d3e48daacf85a378/test/setup/renderer.js#L6)):*
> ```JavaScript
> const spies = require('chai-spies');
> 
> chai.use(spies);
> ```

That adds `chai.spy` extension.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 0 of 30 files reviewed, 10 unresolved discussions (waiting on @jvff)

---

*[test/setup/renderer.js, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNP3Ol20QDck546H4r:-LFNP3Ol20QDck546H4s:b-tq8100) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63c40163dba4d00f4d20eab7d3e48daacf85a378/test/setup/renderer.js#L12)):*
> ```JavaScript
> });
> 
> global.expect = chai.expect;
> ```

Here we export `expect` and `spy` globally for all tests so we don't have to import it in each test, i.e

```
import { expect } from 'chai';
```

But one of main reasons for re-rexporting two of  this is because Flow does not follow when `chai` is being extended with `spy`. So it always thinks that `chai.spy` does not exist. Well, not anymore :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by pronebird** [comment]
Review status: 27 of 30 files reviewed, 11 unresolved discussions (waiting on @jvff and @pronebird)

---

*[.eslintrc, line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224#-LFNx4os1ayy6qaImOms:-LFNx4ot27szDItipVPc:b-p5dhlv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d33c5639936d0c85e0cfb531fa075e7c1030b99/.eslintrc#L37)):*
> ```
>     "react": {
>       "pragma": "React",
>       "version": "16.2",
> ```

Based on the version of React we use, `eslint-plugin-react` turns on some of deprecation notices etc..

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Comment by jvff** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed, 1 unresolved discussion

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/224)*

**Pull request merged**
