### PR TITLE
Add enable/disable button to Split Tunnelling

### PR DESCRIPTION
**Pull request by Pururun**
Preview:
Screenshot_20240208_000006
Screenshot_20240207_235958

To align with desktop.

This is continued from: https://github.com/mullvad/mullvadvpn-app/pull/5554

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnE7GqB4KQzvJsC6mie:-NnE7GqB4KQzvJsC6mif:b-aysv7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L163)):*
> ```Kotlin
>     content: @Composable (modifier: Modifier, lazyListState: LazyListState) -> Unit
> ) {
> ```

nit: remove this empty newline
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 168 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnE7K6s1UyT-ZUGryYQ:-NnE7K6s1UyT-ZUGryYR:bff98r8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L168)):*
> ```Kotlin
>     val scrollBehavior =
>         TopAppBarDefaults.exitUntilCollapsedScrollBehavior(appBarState, canScroll = { canScroll })
>     Scaffold(
> ```

nit: add empty line before `Scaffold` call to improve readability
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnDPwdQ1F9q8rnKDEMZ:-NnDPwdQ1F9q8rnKDEM_:balp258) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt#L6)):*
> ```Kotlin
> 
> data class SplitTunnelingUiState(
>     val checked: Boolean = false,
> ```

Can the name of this property be clarified a bit?



_Code quote:_
```Kotlin
checked
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnE7pwi4cG9mNnCbuGo:-NnE7pwj7F8GZjPJT12n:bagfwba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L85)):*
> ```Kotlin
>     }
> 
>     fun enableSplitTunneling(show: Boolean) {
> ```

There's a mix of words used to represent the setting/toggle state, such as `enable`, `show`, `checked` etc. Can that be clarified throughout this PR?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnE7GqB4KQzvJsC6mie:-NnEJ2uNCrsR_BHoOlko:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L163)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: remove this empty newline
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 168 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnE7K6s1UyT-ZUGryYQ:-NnEJ3gg8tMmmzQwArcm:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L168)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: add empty line before `Scaffold` call to improve readability
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnDPwdQ1F9q8rnKDEMZ:-NnEJ4n83i27sDdAqbyU:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can the name of this property be clarified a bit?
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NnE7pwi4cG9mNnCbuGo:-NnEJ5Th1AGJbNIniKOc:bzbpmrw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3276bc2a6b25d1187bd3874506ebec8e1cae2c0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L85)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There's a mix of words used to represent the setting/toggle state, such as `enable`, `show`, `checked` etc. Can that be clarified throughout this PR?
</blockquote></details>

Changed to use `enable` everywhere.

**Comment by Pururun** [comment]
This is on hold waiting for design review.

**Comment by Pururun** [comment]
This is now on hold waiting for a stable release of the new compose version.

**Comment by Pururun** [comment]
Since we updated the compose material 3 library this is now open for review again 🎉

**Comment by Pururun** [comment]
Put on hold again since the design is getting an update.

**Comment by Pururun** [comment]
Design update is done, this is open for review again.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 2 of 6 files at r3, 7 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)* status: all files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 158 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-Nq74N4w1LMARJgEW-QT:-Nq74N4w1LMARJgEW-QU:b-a34hue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef9a1e3433694e37ccd4aaf796c4498ffca3416d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L158)):*
> ```Kotlin
>     navigationIcon: @Composable () -> Unit = {},
>     actions: @Composable RowScope.() -> Unit = {},
>     switch: @Composable RowScope.() -> Unit = {},
> ```

Is this still needed when we moved out the switch? Can we remove?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt` line 242 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-Nq74cEqEa5wQvIbNJO6:-Nq74cEqEa5wQvIbNJO7:bf4e5vq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef9a1e3433694e37ccd4aaf796c4498ffca3416d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt#L242)):*
> ```Kotlin
> @OptIn(ExperimentalMaterial3Api::class)
> @Composable
> fun MullvadMediumTopBarWithSwitch(
> ```

Same here, is this still needed or can it be removed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 151 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-Nq74qYZ6VbjmGFqmKuc:-Nq74qYZ6VbjmGFqmKud:b-u4i9ai) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef9a1e3433694e37ccd4aaf796c4498ffca3416d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L151)):*
> ```Kotlin
> }
> 
> private fun LazyListScope.enabledToggle(enabled: Boolean, onShowSplitTunneling: (Boolean) -> Unit) {
> ```

`onShowSplitTunneling` -> `onEnableSplitTunneling`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt` line 180 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-Nq75BflBiWp99U899B5:-Nq75BflBiWp99U899B6:bq6c14r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef9a1e3433694e37ccd4aaf796c4498ffca3416d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt#L180)):*
> ```Kotlin
> }
> 
> private fun LazyListScope.appList(
> ```

Nice work splitting this up, much more clear now :clap:

**Review by Rawa — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-:-NqbL26M4OYaoXqOCTqm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 2 of 8 files at r4, 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 14 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NqhgYlR2njpZvN0_BES):*
nit: I suggest simplifying this message a bit to just `Update translations` which we usually use



_Code quote:_
```
Update messages.pot with disable split tunneling
```
___
*[`CHANGELOG.md` line 38 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NqhfZZV6R8m-sEt1hpR:-NqhfZZV6R8m-sEt1hpS:bputagn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6de5838123bf2f9fa057c9d42e5d20e94de60886/CHANGELOG.md#L38)):*
> ```Markdown
> #### Android
> - Add support for all screen orientations.
> - Add enable split tunneling toggle.
> ```

nit: since it's not just for "enabling" I suggest changing to something like: `Add toggle for enabling or disabling split tunneling.`

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)* status: 12 of 14 files reviewed, all discussions resolved (waiting on @albin-mullvad and @Rawa)

___
*[`-- commits` line 14 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NqhgYlR2njpZvN0_BES):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest simplifying this message a bit to just `Update translations` which we usually use
</blockquote></details>

Done
___
*[`CHANGELOG.md` line 38 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641#-NqhfZZV6R8m-sEt1hpR:-Nqit9buCAPnxjfYFdaA:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6de5838123bf2f9fa057c9d42e5d20e94de60886/CHANGELOG.md#L38)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: since it's not just for "enabling" I suggest changing to something like: `Add toggle for enabling or disabling split tunneling.`
</blockquote></details>

Done

**Pull request merged**
