### PR TITLE
Use `resolv-conf` version in crates.io

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Not user visible.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205)

### CODE REVIEW

**Comment by pinkisemils** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205#-:-LEihdtA7EoXkCSyd5Ni:bnfp4nl)*

**Comment by faern** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[talpid-core/Cargo.toml, line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205#-LEixv0C1Xkt6HcZWtNN:-LEixv0C1Xkt6HcZWtNO:b2g6v0b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/181ae9a065dbfc7409c3a8e2778c04b90e5ac5cf/talpid-core/Cargo.toml#L26)):*
> ```TOML
> [target.'cfg(target_os = "linux")'.dependencies]
> notify = "4.0"
> resolv-conf = "0.6"
> ```

The feature we need, was it introduced in `0.6.0` or `0.6.1`? If the latter, we should write `0.6.1` here to make it impossible to compile this towards `0.6.0`

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205)*

**Comment by faern** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[talpid-core/Cargo.toml, line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205#-LEixv0C1Xkt6HcZWtNN:-LEiy5vI7j0pXQi767rK:b972lkv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/181ae9a065dbfc7409c3a8e2778c04b90e5ac5cf/talpid-core/Cargo.toml#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The feature we need, was it introduced in `0.6.0` or `0.6.1`? If the latter, we should write `0.6.1` here to make it impossible to compile this towards `0.6.0`
</blockquote></details>

Pretty sure it should be `0.6.1`. Since your change was commited on April 10, and `0.6.0` was released in February :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205)*

**Comment by faern** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205#-:-LEj5ZKV6l-PvKTleGAJ:bnfp4nl)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 1 of 2 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205)*

**Pull request merged**
