### PR TITLE
Clarify lockdown limitations in guide

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to clarify the lockdown information in the in-app guide.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)* status: 0 of 24 files reviewed, 4 unresolved discussions

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 264 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3ORI90e9VWGQI56Bh:-Nz3ORI90e9VWGQI56Bi:bb1if58) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L264)):*
> ```Kotlin
> }
> 
> private enum class PAGES(
> ```

This `PAGES` structure doesn't feel optimal, but don't want to make too big changes at this point
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 328 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3OKfz5E0H9NbI5aXk:-Nz3OKg-B-GlScLo3ayT:br7qylx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L328)):*
> ```Kotlin
>                     }
>                     append(" ")
>                     pushUrlAnnotation(UrlAnnotation(stringResource(id = R.string.lockdown_url)))
> ```

Will be replaced by https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/AnnotatedString.kt;l=1168
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Ntda7ArxWc01WKuM:-Nz3Ntda7ArxWc01WKuN:bmxfw9g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/lib/resource/src/main/res/values/strings.xml#L92)):*
> ```XML
>         <![CDATA[The Lockdown mode is called <b>Block connections without VPN</b> in the Android system settings. It helps minimize leaks, however it has some known limitations which you can read more about it]]>
>     </string>
>     <string name="auto_connect_carousel_third_slide_top_text_website_link">here.</string>
> ```

Should we include the dot or not? Is there a better way to build this string?



_Code quote:_
```XML
here.
```
___
*[`android/lib/resource/src/main/res/values/strings_non_translatable.xml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3NjYZCVIM4xMhr-F7:-Nz3NjYZCVIM4xMhr-F8:bmgsiaq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/lib/resource/src/main/res/values/strings_non_translatable.xml#L9)):*
> ```XML
>     <string name="faqs_and_guides_url" translatable="false">https://mullvad.net/help/tag/mullvad-app/</string>
>     <string name="privacy_policy_url" translatable="false">https://mullvad.net/help/privacy-policy/</string>
>     <string name="lockdown_url" translatable="false">https://mullvad.net/app-links/android-vpn-settings</string>
> ```

This URL needs to be aligned before we merge

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)* status: all files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 271 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Px_w7BVJSqEXpIkU:-Nz3Px_w7BVJSqEXpIkV:b-7wo0y9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L271)):*
> ```Kotlin
>     FIRST(
>         annotatedTopText =
>             @Composable {
> ```

Feels like we should contemplate refactoring these `buildAnnotatedString` out,  the depth of them is a ton, and gets even worse with the enum class. Maybe also some of the internal functions can be broken out for readability as well.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 343 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Qu2U7gNpjC34gZ05:-Nz3Qu2U7gNpjC34gZ06:b77pg10) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L343)):*
> ```Kotlin
>                         )
>                     }
>                     pop()
> ```

What is it we pop here? pushUrlAnnotation? can we do something similar as `withStyle` where it automatically resets?
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Ntda7ArxWc01WKuM:-Nz3P_PoDbns3xhFq4Gi:b-hiniyz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/lib/resource/src/main/res/values/strings.xml#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should we include the dot or not? Is there a better way to build this string?
</blockquote></details>

Generally I don't think the dot should be included, but yeah it would be a bit of pain to just have a new string, unless we insert it in the other string as argument?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 271 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Px_w7BVJSqEXpIkU:-O-GOIrt9P0EqaMCKTZS:b-xf041p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L271)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Since we probably want to replace this enum thing with separate composables I don't think we need to make this prettier at this point. We also want to ship this asap.
</blockquote></details>

Made it a bit prettier without too much work. Didn't change the enum class though since we can attack that later. Please have another look!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 343 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Qu2U7gNpjC34gZ05:-O-GOauJ40FlW1xx3MxX:bvrf8i2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L343)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yes, the pop for `pushUrlAnnotation`. Will not be needed in compose ui `1.7.0`. I linked to the upstream change in my other comment: https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3OKfz5E0H9NbI5aXk
</blockquote></details>

Added a temporary `withLink` function. Please have a look!
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Ntda7ArxWc01WKuM:-NzSHUsn0WhjvWfeFvM-:b-1eb74v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/lib/resource/src/main/res/values/strings.xml#L92)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'll see if I can find a better way, but I think we're a bit limited due to how we build the annotated string :thinking:
</blockquote></details>

Moved the dot out of this string and instead append it. Eventually it would be nice to do something like: https://github.com/Aghajari/AnnotatedText?tab=readme-ov-file#url-onclick

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/resource/src/main/res/values/strings_non_translatable.xml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3NjYZCVIM4xMhr-F7:-O-GQ1OSCKjuh2B3Icw6:b4ahgq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/lib/resource/src/main/res/values/strings_non_translatable.xml#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This URL needs to be aligned before we merge
</blockquote></details>

Using https://mullvad.net/help/using-mullvad-vpn-on-android until we've settled on which URL to use due to problems with `hide_nav` in the shortened URL.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, 24 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-:-O-GX97T3Wl6vOshpKv_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)* status: all files reviewed, 1 unresolved discussion

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt` line 343 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3Qu2U7gNpjC34gZ05:-O-H45JJ1dCBvTyI1r2R:bcv502w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt#L343)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Added a temporary `withLink` function. Please have a look!
</blockquote></details>

Nice :+1:

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/resource/src/main/res/values/strings_non_translatable.xml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293#-Nz3NjYZCVIM4xMhr-F7:-O-H4fha7ls6ZhrXCADZ:bv9nu28) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12eca2d437d91e00ec78fcb93797e2e224a24a29/android/lib/resource/src/main/res/values/strings_non_translatable.xml#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Using https://mullvad.net/help/using-mullvad-vpn-on-android until we've settled on which URL to use due to problems with `hide_nav` in the shortened URL.
</blockquote></details>

Will merge this as-is. URL will be updated in: https://linear.app/mullvad/issue/DROID-1060

**Pull request merged**
