### PR TITLE
Update account view

### PR DESCRIPTION
**Pull request by AndreasShortcut**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

Updated account view:
- Added device name
- Added buttons to show/hide and copy account number
- Added accessibility custom actions

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/AccountContentView.swift` line 222 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5Ag5f3CRbzlSMAPpFL:-N5Anhda8ZT-yNjHOKSA:b-gg058p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L222)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why not `let copyIcon = UIImage(named: "IconTick")!`? We do expect all assets to be available within the bundle.
</blockquote></details>

Worst case it can be `UIImage?`, many controls accept `UIImage?` so it's fine, although we do expect assets to be in the bundle.

**Review by AndreasShortcut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)* status: 10 of 14 files reviewed, 6 unresolved discussions (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AeY4O1FKP7OSWTyby:-N5FEsFI3sprUgfZtHmQ:b-886gsx) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Could you please update `convert-assets.rb` to include the appropriate graphical assets from the desktop app?
</blockquote></details>

Fixed

___
___
*[`ios/CHANGELOG.md` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5Anz9P7D_vwXOV5HJM:-N5F8H991Kw1r6XEodgx:bt2vr0b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/CHANGELOG.md#L29)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

These are minor UI adjustments and most of it we already had there before, so I think it's fine to sum it up as "Display device name under account view" or similar.
</blockquote></details>

Fixed
___
*[`ios/MullvadVPN/AccountContentView.swift` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5Ap86C8qYVowTZO9gj:-N5AxFVk2GAo4GLnlKB7:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L106)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It's fine to have it `String?` which does not require the initial state either as `nil` is implied.
</blockquote></details>

Fixed
___
*[`ios/MullvadVPN/AccountContentView.swift` line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AgWQj34UzAWEjhTVa:-N5EiopZ10xlOHDVPVSL:bgfowdz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L165)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Can be simplified to:

```
StringFormatter.formatAccountNumber(accountNumber ?? "").map { ch in
    return ch == " " ? ch : "<REPLACEMENT CHARACTER>"
}
```
</blockquote></details>

Good point, I'll remove the concealedAccountNumber(from:) method
___
*[`ios/MullvadVPN/AccountContentView.swift` line 170 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AiMto94KGsR2Z2oGE:-N5B2cAk1u_EtICdtK9l:b-hpz4kq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L170)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Do you have to store it? You can compute the value on-go:

```
func updateView() {
  let formatted = StringFormatter.formatAccountNumber(accountNumber ?? "")
  if isConcealed {
      label.text = formatted.map { ch in 
          return ch == " " ? ch : "<REPLACEMENT CHARACTER>"
      }
  } else {
      label.text = formatted
  }
}
```
</blockquote></details>

Hm, I thought it made more sense to store it, since we will only need to do it once
___
*[`ios/MullvadVPN/AccountContentView.swift` line 198 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5As-g6Am3Qk-UdIvS7:-N5AxZEuBuZSM0D9HqLa:bfcq7zi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L198)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably better to omit `textAlignment`. Since `.natural` is the default alignment, it will automatically turn into `left` in left-to-right languages and into `.right` in right-to-left languages. 
</blockquote></details>

Good point, fixed
___
*[`ios/MullvadVPN/AccountContentView.swift` line 222 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5Ag5f3CRbzlSMAPpFL:-N5AuurU9yU1Se8etqGo:b-po800l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L222)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Worst case it can be `UIImage?`, many controls accept `UIImage?` so it's fine, although we do expect assets to be in the bundle.
</blockquote></details>

I never really force unwrap anything if I can avoid it. Sure, the asset _should_ be there, but it could be that we rename it or remove it at some point, or that we change the non type-safe String, intentionally or by accident. If that happens, it seems much better to just not load an image than to crash the app, don't you agree?
___
*[`ios/MullvadVPN/AccountContentView.swift` line 262 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AfERnCKb9JNKuZWwV:-N5B-GJ74CdoUK_PCN8D:bnd3qwi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L262)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

"Show or hide" is not good description for blind person, should reflect that the action will unobscure the account or not. I'd move all that into `updateView()` function and assign values based on current state of the view, either concealed or not.. 
</blockquote></details>

Very good point. I went for reveal/obscure, what do you think? I tried "unobscure account number", but it sounded like "an obscure account number" 
___
*[`ios/MullvadVPN/AccountViewController.swift` line 87 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AjTBd6kCltWcyFpg9:-N5B4-5ADcGlFkjT2GKw:bhgzqmi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountViewController.swift#L87)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You can perhaps let the view do the visual formatting.
</blockquote></details>

I agree, that makes sense. Fixed.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)* status: 10 of 14 files reviewed, 6 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AccountContentView.swift` line 274 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5FEhy8EcEUbzdKOXqb:-N5FEhy95VMvUbrxpUVS:b-xnlcy2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcc4954d69da4ed1073a2316a203b6ed29b28589/ios/MullvadVPN/AccountContentView.swift#L274)):*
> ```Swift
>                                                                 tableName: "Account",
>                                                                 value: (isAccountNumberObscured
>                                                                         ? "Reveal account number"
> ```

Btw: don't do this because the source code parser for `NSLocalizedString` will extract one identifier for translation `ACCOUNT_ACCESSIBILITY_SHOW_OR_HIDE_ACCOUNT`. So ideally you want two separate identifiers, i.e:

```swift
let revealString = NSLocalizedString(
  "<MY_IDENTIFIER_A>",
   tableName: "Account",
   value: "Reveal",
   comment: ""
)
let hideString = NSLocalizedString(
  "<MY_IDENTIFIER_B>",
   tableName: "Account",
   value: "Hide",
   comment: ""
)

let actionName = shouldReveal ? revealString : hideString
``` 


Also `NSLocalizedString` is very long and verbose call so perhaps better be extracted into a variable to improve readability:

```swift
let revealActionName = NSLocalizedString(
  "<MY_IDENTIFIER>",
   tableName: "Account",
   value: "<VALUE>",
   comment: ""
)

accessibilityCustomActions = [
    UIAccessibilityCustomAction(name: revealActionName, ...)
]
```

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)* status: 10 of 14 files reviewed, 7 unresolved discussions (waiting on @AndreasShortcut and @pronebird)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)* status: all files reviewed, 4 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/AccountContentView.swift` line 170 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AiMto94KGsR2Z2oGE:-N5FGnpZEZxiPW4hWy3u:bxxgvp8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L170)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Hm, I thought it made more sense to store it, since we will only need to do it once
</blockquote></details>

It's not used too often and operation is fairly simple, so less state to maintain is probably better.
___
*[`ios/MullvadVPN/AccountContentView.swift` line 222 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5Ag5f3CRbzlSMAPpFL:-N5FGAj-1wwjc8SX7zxw:b6b9rfm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L222)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

I never really force unwrap anything if I can avoid it. Sure, the asset _should_ be there, but it could be that we rename it or remove it at some point, or that we change the non type-safe String, intentionally or by accident. If that happens, it seems much better to just not load an image than to crash the app, don't you agree?
</blockquote></details>

Sure, however what's wrong with simply returning `UIImage?`? What's the need for allocating an empty `UIImage`?
___
*[`ios/MullvadVPN/AccountContentView.swift` line 262 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685#-N5AfERnCKb9JNKuZWwV:-N5FFu-w7poxcJ_gBPMv:bwte29m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67501003892fe616fdc1454e2bd7237fd00f33ec/ios/MullvadVPN/AccountContentView.swift#L262)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Very good point. I went for reveal/obscure, what do you think? I tried "unobscure account number", but it sounded like "an obscure account number" 
</blockquote></details>

I think "Reveal" and "Hide" are good terms. We don't have it communicated in the desktop app, but I think it's fine if we do it that way for users & we can discuss that in UI/UX channel on Slack down the road. I just don't have much time right now to start a discussion.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 2 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3685)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @pronebird)

**Pull request merged**
