### PR TITLE
Consolidate retry attempts in a single location

### PR DESCRIPTION
**Pull request by mojganii**
The relay selector is now smart enough to choose relays for `entry` and `exit` peers. It is time to apply multihop on the tunnel. This PR introduces the ability to establish multihop connections without PQ. Implementing multihop with PQ will be addressed in another PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)

### CODE REVIEW

**Comment by pinkisemils** [comment]
I think you should rebase this on `main`, and drop the commit that updates `wireguard-apple`, then maybe the unit tests fill pass.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)* status: 0 of 28 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 447 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O24rykK8HGGeUhKdGG-:-O24rykK8HGGeUhKdGG0:b-q2jr1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e64d571a84d66e40840ba3a732e5d4f3d5de0c58/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L447)):*
> ```Swift
>             connectionState.connectedEndpoint,
>             settings: settings,
>             retryAttempts: connectionState.selectedRelays.retryAttempt
> ```

Should the `retryAttempt` field not be better suited to stay in `connectionState`?

**Review by acb-mv — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Review by mojganii — COMMENTED** [review]
I dropped the last commit as we discussed before.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-:-O2ABmNr5ax3jiNHse4w:busu5m)* status: 26 of 28 files reviewed, 1 unresolved discussion (waiting on @acb-mv and @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 447 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O24rykK8HGGeUhKdGG-:-O2AC17a7cdQ23ZEavw-:boxdv7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e64d571a84d66e40840ba3a732e5d4f3d5de0c58/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L447)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should the `retryAttempt` field not be better suited to stay in `connectionState`?
</blockquote></details>

it's using in relay selector. it's a common filed between them.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 25 of 28 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/TunnelManager/Tunnel+Settings.swift` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O2OlI643AjLY5Jq4nsn:-O2OlI643AjLY5Jq4nso:b-56342u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3138d943c26cc4ea7d977a21730c2139b406c00/ios/MullvadVPN/TunnelManager/Tunnel%2BSettings.swift#L20)):*
> ```Swift
> 
>     init(logger: Logger? = nil) {
>         self.logger = logger
> ```

This is confusing, what was the problem being solved by dependency injecting a logger object here ?
Loggers should not be shared around, they are bound to a specific object and it will just make the logs more confusing if they are starting to log for the wrong instance. 
___
*[`ios/MullvadVPN/TunnelManager/Tunnel+Settings.swift` line 23 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O2OnkrCApTT5VjGMBEw:-O2OnkrCApTT5VjGMBEx:b48lnek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3138d943c26cc4ea7d977a21730c2139b406c00/ios/MullvadVPN/TunnelManager/Tunnel%2BSettings.swift#L23)):*
> ```Swift
>     }
> 
>     func shouldReconnectToNewRelay(oldSettings: LatestTunnelSettings, newSettings: LatestTunnelSettings) -> Bool {
> ```

nit
I'm wondering right now where are the places in the code base that trigger a reconnection to the VPN without going through this logic.
Ideally, it should be done in one place only, and this seems like a good candidate. 
It might be worth discussing this as a team.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O2Oovdq6c60MEZC-8BI:-O2Oovdq6c60MEZC-8BJ:b-s2v5ed) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3138d943c26cc4ea7d977a21730c2139b406c00/ios/MullvadVPN/TunnelManager/TunnelState.swift#L81)):*
> ```Swift
> 
>     var description: String {
>         return switch self {
> ```

nit
We can omit `return` here 
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O2P1C2B1MFaYtjs5uPh:-O2P1C2B1MFaYtjs5uPi:beg7bf5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3138d943c26cc4ea7d977a21730c2139b406c00/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift#L13)):*
> ```Swift
> 
> final class TunnelSettingsStrategyTests: XCTestCase {
>     func connectToNewRelayOnMultihopChangesTest() {
> ```

None of those tests are running because the function name does not start with `test`.
Please prefix all those with `test`
___
*[`ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-O2P4azNBYri5Nbko7ce:-O2P4azNBYri5Nbko7cf:bfljdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3138d943c26cc4ea7d977a21730c2139b406c00/ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift#L61)):*
> ```Swift
>         }
> 
>         do {
> ```

If we are not making use of the `async` wrapper we wrote for this, might as well go all non async way and do the following instead

```swift
        adapter.stop { _ in
            adapter.startMultihop(exitConfiguration: exitConfiguration, entryConfiguration: entryConfiguration) {
                logger.error("\($0?.localizedDescription ?? "Error starting the adapter")")
            }
        }
```

Otherwise, let's add an async wrapper to this API in `WireGuardAdapter+Async.swift`

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474#-:-O2e38pM-_MRkipD5Q6R:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

**Review by pinkisemils — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii)

**Pull request merged**
