### PR TITLE
Add test for audit ticket MUL-02-002

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR adds an integration test to check for regressions to audit ticket [MUL-02-002 - Firewall allows deanonymization by eavesdropper](https://github.com/mullvad/mullvadvpn-app/blob/main/audits/2020-06-12-cure53.md#identified-vulnerabilities). The fix for this issue has been included in the app since version 2020.5.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979)

### CODE REVIEW

**Review by hulthe — CHANGES_REQUESTED** [review]
Very readable test. Nice.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-:-NuUMLXY2HGlFnKxz2C9:b-p0wcn2)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/tunnel.rs` line 828 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuUKvWNEZfkyuDevaw2:-NuUKvWNEZfkyuDevaw3:bpgex3x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L828)):*
> ```XML
> ) -> Result<(), anyhow::Error> {
>     // Step 0 - Disconnect from any active tunnel connection
>     helpers::disconnect_and_wait(&mut mullvad_client).await?;
> ```

IIRC the runtime makes sure we're disconnected when we start a test
___
*[`test/test-manager/src/tests/tunnel.rs` line 853 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuULEfKDHYeN9_qxaCD:-NuULEfKDHYeN9_qxaCE:b-a62hg7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L853)):*
> ```XML
>     // identifiable payload
>     // FIXME: This needs to be kept in sync with the magic payload string defined in `connection_cheker::net`.
>     // An easy fix would be to make the payload for `ConnCheck` configurable.
> ```


___
*[`test/test-manager/src/tests/tunnel.rs` line 869 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuULiBu95CnfSRtnVwS:-NuULiBu95CnfSRtnVwT:bv0f0rb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L869)):*
> ```XML
>     // Before proceeding, assert that the method of detecting identifiable packets work.
>     conn_artist.check_connection().await?;
>     let monitor_result = rogue_packet_monitor.into_result().await.unwrap();
> ```

unwrap?

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979)* status: all files reviewed, 4 unresolved discussions (waiting on @hulthe and @MarkusPettersson98)

___
*[`test/test-manager/src/tests/tunnel.rs` line 828 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuUKvWNEZfkyuDevaw2:-NuXQ79B18PIhujftjmV:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L828)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

IIRC the runtime makes sure we're disconnected when we start a test
</blockquote></details>

+1
___
*[`test/test-manager/src/tests/tunnel.rs` line 848 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuXRjLO0Rn06jD3K86m:-NuXRjLO0Rn06jD3K86n:b-ee9455) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L848)):*
> ```XML
>     };
>     helpers::disconnect_and_wait(&mut mullvad_client).await?;
>     let gateway = endpoint.endpoint.address;
> ```

`gateway` seems wrong. Also, it's not guaranteed to select the same endpoint when reconnecting (step 4).
___
*[`test/test-manager/src/tests/tunnel.rs` line 853 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuULEfKDHYeN9_qxaCD:-NuXQBl39jbJ2iYEyuW6:bxldzri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L853)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>


</blockquote></details>

+1. Or just define it as a constant somewhere.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @dlon and @hulthe)

___
*[`test/test-manager/src/tests/tunnel.rs` line 828 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuUKvWNEZfkyuDevaw2:-NuY_Rag8-CUuG0f7yEi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L828)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`test/test-manager/src/tests/tunnel.rs` line 848 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuXRjLO0Rn06jD3K86m:-NuhS8ho7dN-PHiHGjAg:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L848)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`gateway` seems wrong. Also, it's not guaranteed to select the same endpoint when reconnecting (step 4).
</blockquote></details>

Done
___
*[`test/test-manager/src/tests/tunnel.rs` line 853 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuULEfKDHYeN9_qxaCD:-NuhcZ055o01sLAGxJdJ:b-896fjb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L853)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

+1. Or just define it as a constant somewhere.
</blockquote></details>

Done 
___
*[`test/test-manager/src/tests/tunnel.rs` line 869 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuULiBu95CnfSRtnVwS:-NuhSA2n02W6KsHc6i1C:b-8l7sg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a2ca13f530c6cd5a1e199f0661dc71331c380f8/test/test-manager/src/tests/tunnel.rs#L869)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

unwrap?
</blockquote></details>

:scream_cat: 
Fixed! :sponge:

**Review by hulthe — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-:-Nuxofqr2Q6SaaEFQtWT:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`test/connection-checker/src/cli.rs` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-NuxeBxuEnxkXvbh9OXS:-NuxeBxuEnxkXvbh9OXT:b9sadbo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0256eeec9253328c2cec8dae2ef03f0096c6aa8d/test/connection-checker/src/cli.rs#L39)):*
> ```XML
>     /// Junk data for each UDP and TCP packet
>     #[clap(long, requires = "leak")]
>     pub payload: Option<String>,
> ```

Nit: I would use #[clap(default_value = "Hello there!")] instead of making this an option

**Review by hulthe — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-:-Nv1Y10iDzbE3wfa5vrG:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

**Review by hulthe — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by hulthe — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5979#-:-Nv1vlrJ09d--w3D9n_m:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
