### PR TITLE
Rework history and transitions

### PR DESCRIPTION
**Pull request by raksooo**
This PR reworks the history/transition implementations as discussed between me and @pronebird. The changes are mainly that instead of having transition rules that specify the transitions between paths, we now have methods in `History` that both describes navigation and transition, e.g. `push()`, `pop()`, `dismiss()`. I've also created a hook `useHistory` which returns our implementation and a HOC `withHistory` which adds our history object to props.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: 1 of 24 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/lib/history.ts, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQrAxJ1LKZuXpSGp32:-MdQrAxJ1LKZuXpSGp33:blxxaqe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0adf87449f0ee913fef0111c5d30efc37ac2eeef/gui/src/renderer/lib/history.ts#L32)):*
> ```XML
>     duration: 450,
>   },
>   none: {
> ```

FYI technically "no transition" can be expressed as `null` or `undefined`, i.e `TransitionSpecification?`.
___
*[gui/src/renderer/lib/history.ts, line 115 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQol4d6EP8Gh2WJlGn:-MdQol4d6EP8Gh2WJlGo:bec0eha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0adf87449f0ee913fef0111c5d30efc37ac2eeef/gui/src/renderer/lib/history.ts#L115)):*
> ```XML
>   }
> 
>   public block(): () => never {
> ```

Why all of the stub methods for history interface return closures of type `() => never`?

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: 2 of 24 files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 8 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: 12 of 24 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 629 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQu12r8fVLD6HezZ9F:-MdQu12r8fVLD6HezZ9G:bp5q0nu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b7fac4d26dc9d3b0031c7af8393d296e21293090/gui/src/renderer/app.tsx#L629)):*
> ```XML
>       if (this.settings.accountToken) {
>         const transition =
>           pathname === '/login' || pathname === '/' ? transitions.push : transitions.dismiss;
> ```

FYI I like the full control over transitions.
___
*[gui/src/renderer/app.tsx, line 632 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQt76sCaSgrav5ZY2Q:-MdQt76sCaSgrav5ZY2R:b-7qw5l7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b7fac4d26dc9d3b0031c7af8393d296e21293090/gui/src/renderer/app.tsx#L632)):*
> ```XML
>         this.history.reset('/main', transition);
>       } else {
>         const transition =
> ```

FYI yuck that ternary expression, wish the formatter indented each level.
___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 47 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQub_d2lbIBAGNGlGQ:-MdQub_d2lbIBAGNGlGR:blrd8u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L47)):*
> ```XML
> 
>   return {
>     onClose: () => props.history.pop(),
> ```

Select location should probably use dismiss right?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: 12 of 24 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 53 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQueMSCC_VfhQV0g8l:-MdQueMSCC_VfhQV0g8m:bvl34rp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L53)):*
> ```XML
>     onSelectExitLocation: async (relayLocation: RelayLocation) => {
>       // dismiss the view first
>       props.history.pop();
> ```

Same here. I think we should use dismiss to return to the main view.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: 13 of 24 files reviewed, 5 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 66 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQuitF2k5p35Y2IBxz:-MdQuitF2k5p35Y2IBy-:buo9nmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L66)):*
> ```XML
>     onSelectBridgeLocation: async (bridgeLocation: RelayLocation) => {
>       // dismiss the view first
>       props.history.pop();
> ```

Same here
___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQuk3sEDbswWqqe3xH:-MdQuk3sEDbswWqqe3xI:b-1kzc9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L78)):*
> ```XML
>     onSelectClosestToExit: async () => {
>       // dismiss the view first
>       props.history.pop();
> ```

And here.

**Review by pronebird — COMMENTED** [review]
> Reviewed 7 of 16 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: all files reviewed, 5 unresolved discussions (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: 1 of 24 files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[gui/src/renderer/app.tsx, line 632 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQt76sCaSgrav5ZY2Q:-MdWPeMi5Y2f7PhbKp5Q:b-gzd5qb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b7fac4d26dc9d3b0031c7af8393d296e21293090/gui/src/renderer/app.tsx#L632)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI yuck that ternary expression, wish the formatter indented each level.
</blockquote></details>

I first implemented it with a switch-case statement instead but that became huge. Yeah I would prefer one more level of indentation for the second ternary expression.
___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 47 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQub_d2lbIBAGNGlGQ:-MdWRL4EEMcDAqcrrwip:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L47)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Select location should probably use dismiss right?
</blockquote></details>

Done.
___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 53 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQueMSCC_VfhQV0g8l:-MdWRM2EBq0op52SA0tu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L53)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here. I think we should use dismiss to return to the main view.
</blockquote></details>

Done.
___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 66 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQuitF2k5p35Y2IBxz:-MdWRMcUBOl-Ing3-xwU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L66)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[gui/src/renderer/containers/SelectLocationPage.tsx, line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQuk3sEDbswWqqe3xH:-MdWRMyK8nl8ossNLlu_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d87aafdf792e9f16e55219f297042041287bf02/gui/src/renderer/containers/SelectLocationPage.tsx#L78)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

And here.
</blockquote></details>

Done.
___
*[gui/src/renderer/lib/history.ts, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQrAxJ1LKZuXpSGp32:-MdWROUY-RNB8quEkEeb:beiv83u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0adf87449f0ee913fef0111c5d30efc37ac2eeef/gui/src/renderer/lib/history.ts#L32)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI technically "no transition" can be expressed as `null` or `undefined`, i.e `TransitionSpecification?`.
</blockquote></details>

That was my first idea as well but then I noticed that this was how it was solved with the previous implementation and that it wouldn't require any changes to `TransitionContainer` to make it like this. I don't prefer this over the other, I'm fine with both so if you prefer `undefined` over this I'll change.

https://github.com/mullvad/mullvadvpn-app/blob/master/gui/src/renderer/transitions.ts#L104
___
*[gui/src/renderer/lib/history.ts, line 115 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQol4d6EP8Gh2WJlGn:-MdWRtNe6Mev95-Pbudh:b-e45mw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0adf87449f0ee913fef0111c5d30efc37ac2eeef/gui/src/renderer/lib/history.ts#L115)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why all of the stub methods for history interface return closures of type `() => never`?
</blockquote></details>

They should just return `never`. Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/renderer/lib/history.ts, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-MdQrAxJ1LKZuXpSGp32:-MdWTkxpC3bjXsg2wKPd:bos7opg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0adf87449f0ee913fef0111c5d30efc37ac2eeef/gui/src/renderer/lib/history.ts#L32)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

That was my first idea as well but then I noticed that this was how it was solved with the previous implementation and that it wouldn't require any changes to `TransitionContainer` to make it like this. I don't prefer this over the other, I'm fine with both so if you prefer `undefined` over this I'll change.

https://github.com/mullvad/mullvadvpn-app/blob/master/gui/src/renderer/transitions.ts#L104
</blockquote></details>

Up to you.

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2819#-:-MdWTt_-9a70np1DJkm4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
