### PR TITLE
Intercept and cancel web requests originating from renderer process

### PR DESCRIPTION
**Pull request by raksooo**
This PR is a step in the direction to secure the frontend further. It disables all network communication from the renderer process by intercepting and cancelling web requests. There are a few exception when running in development mode which are described in a comment in the code.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1375 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365#-MOknluV5m4xpjXmLX21:-MOknluW2N0zWNfflHT0:b-80ueuk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dc403113ed070b9c33f7bf1738dd3d3ba7070a0/gui/src/main/index.ts#L1375)):*
> ```XML
>   private blockRequests() {
>     session.defaultSession.webRequest.onBeforeRequest(
>       { urls: ['*://*/*'] },
> ```

Wouldn't just using * should do the trick?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1381 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365#-MOknusI2SgYVAOdtZN8:-MOknusI2SgYVAOdtZN9:bymws2y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dc403113ed070b9c33f7bf1738dd3d3ba7070a0/gui/src/main/index.ts#L1381)):*
> ```XML
>           (details.url.startsWith('http://localhost:8080/') ||
>             details.url.startsWith('http://localhost:35829/browser-sync/') ||
>             details.url.startsWith('https://clients2.google.com') ||
> ```

Would be great to document these URLs. I realise that these are used by extension installer, but still would like to see it documented.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 1375 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365#-MOknluV5m4xpjXmLX21:-MOkvWMRCP9GN9R0XsK-:bxa0g98) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dc403113ed070b9c33f7bf1738dd3d3ba7070a0/gui/src/main/index.ts#L1375)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Wouldn't just using * should do the trick?
</blockquote></details>

That's what I first tried but it needs to be specified like that. They have a few examples in the documentation which all conform to that format. https://www.electronjs.org/docs/api/web-request#webrequestonbeforerequestfilter-listener
___
*[gui/src/main/index.ts, line 1381 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365#-MOknusI2SgYVAOdtZN8:-MOkvi-V-799rVzytW1K:b-xnmmu0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dc403113ed070b9c33f7bf1738dd3d3ba7070a0/gui/src/main/index.ts#L1381)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Would be great to document these URLs. I realise that these are used by extension installer, but still would like to see it documented.
</blockquote></details>

I've replaced the bullet list in the comment above the function with comments above each line describing what it's used for. Is this better?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

___
*[gui/src/main/index.ts, line 1381 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365#-MOknusI2SgYVAOdtZN8:-MOpCN3j1g0BTjE4j40D:bocwr5b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7dc403113ed070b9c33f7bf1738dd3d3ba7070a0/gui/src/main/index.ts#L1381)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I've replaced the bullet list in the comment above the function with comments above each line describing what it's used for. Is this better?
</blockquote></details>

Much better thanks! In my mind I had something like this:

```
const allowedDevelopmentURLs = [
    // static assets ...
    'https://localhost:8080/',

   // dev tools extensions ...
    'https://google.com/',

   // etc...
]

const containsAllowedURL = allowedDevelopmentURLs.some((s) => details.url.startsWith(s))

if (process.env.NODE_ENV === 'development' || containsAllowedURL) {
   // permit request
} else {
   // reject request
}
```

Although that's more of a stylistic difference as I'd avoid repetition in favour of a loop or functional approach with `some()`.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365#-:-MOpEF-C4lplcRF6djxs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
