### PR TITLE
Add React exhaustive-deps and compiler ESLint rules

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds the React hooks `exhaustive-deps` rule and the React compiler rule to ESLint. I've also prohibited `@ts-ignore` comments and replaced the existing ones with `@ts-expect-error`, and done some general clean up.

There is no good way to implement `WillExit` and `useWillExit` that conforms with these rules (and Reacts design principles) so I removed those as they won't be needed in the upcoming PR where we move to the JavaScript ViewTransition API.

I really suggest going through this PR commit-by-commit.

Fixes DES-1314.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 47 of 64 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972)* status: 21 of 83 files reviewed, all discussions resolved

___
*[`gui/src/renderer/components/NotificationBanner.tsx` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-O9KeH2iBDtqk5wx3FYC:-O9KeH2iBDtqk5wx3FYD:bxrfsik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a2886e79eaca5a9c2065e170ed976637fedae9c/gui/src/renderer/components/NotificationBanner.tsx#L168)):*
> ```XML
>   }, [props.children]);
> 
>   // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

A motivation why the lint rule is disabled would be nice:)



_Code quote:_
```XML
  // eslint-disable-next-line react-hooks/exhaustive-deps
```

**Review by MarkusPettersson98 — DISMISSED** [review]
> Reviewed 17 of 64 files at r2, 3 of 3 files at r3, 12 of 12 files at r4, 5 of 5 files at r5, 52 of 52 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`gui/test/unit/notification-evaluation.spec.ts` line 31 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-O9Pu7qA8lR_pdhQjatY:-O9Pu7qA8lR_pdhQjatZ:bb7pae3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef9997c1160c3b82f4c2925ea647f0a51427c1d6/gui/test/unit/notification-evaluation.spec.ts#L31)):*
> ```XML
>   before(() => {
>     sandbox = sinon.createSandbox();
>     // @ts-expect-error Way to many methods to mock.
> ```

too*



_Code quote:_
```XML
to
```

**Review by raksooo — COMMENTED** [review]
I've now made all the updates we talked about yesterday.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-:-O9TKsBZ2BqthYdhOx_o:brmcagp)* status: 0 of 84 files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`gui/src/renderer/components/NotificationBanner.tsx` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-O9KeH2iBDtqk5wx3FYC:-O9TKhSx7PsCHRu1uMe5:b-if9vtv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a2886e79eaca5a9c2065e170ed976637fedae9c/gui/src/renderer/components/NotificationBanner.tsx#L168)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

A motivation why the lint rule is disabled would be nice:)
</blockquote></details>

This was removed in a later commit.
___
*[`gui/test/unit/notification-evaluation.spec.ts` line 31 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-O9Pu7qA8lR_pdhQjatY:-O9TKqqxDhtuImP0Ajtf:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef9997c1160c3b82f4c2925ea647f0a51427c1d6/gui/test/unit/notification-evaluation.spec.ts#L31)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

too*
</blockquote></details>

Done!

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm: :tada:

> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-:-O9TPGZ_7pduikT6Cac2:bck4n45)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/EditApiAccessMethod.tsx` line 73 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-O9o61P93_5TjJgwWdHc:-O9o61P93_5TjJgwWdHd:b-4295bp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/217f4dc7678b1fb24afeb4419955ad7cc77fc9e8/gui/src/renderer/components/EditApiAccessMethod.tsx#L73)):*
> ```XML
>       const enabled = id === undefined ? true : (method?.enabled ?? true);
>       const updatedMethod = { ...newMethod, enabled };
>       console.log(JSON.stringify(updatedMethod));
> ```

Should this `console.log` be left in? :blush:



_Code quote:_
```XML
console.log(JSON.stringify(updatedMethod));
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972)* status: 81 of 83 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`gui/src/renderer/components/EditApiAccessMethod.tsx` line 73 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-O9o61P93_5TjJgwWdHc:-O9oFWu_3GA1I8WJ5tYs:b84ucb2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/217f4dc7678b1fb24afeb4419955ad7cc77fc9e8/gui/src/renderer/components/EditApiAccessMethod.tsx#L73)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should this `console.log` be left in? :blush:
</blockquote></details>

Thanks for spotting that! Removed!

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6972#-:-O9oGxJt7mBIUGsN7SM3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
