### PR TITLE
Stop filtering null locations to avoid bugs with connection errors

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5101)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5101#-:-NdZwxIrBk3bboIY8FB1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Can you add a test for this case as well?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5101#-:-NdZx1l1E7CLKDU0BNjz:b-h52tzy)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — COMMENTED** [review]
Added two tests.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5101#-:-Nd_rkVOBJsS_4qcA8jV:b-7jnol6)* status: 1 of 2 files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5101#-:-Nd_rzZB-Uiag72e5Iuz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
