### PR TITLE
Switch to npm workspaces structure

### PR DESCRIPTION
**Pull request by raksooo**
This PR introduces workspaces for the Electron app. The `gui/`-directory has been moved to `desktop-electron-app/packages/mullvad-vpn`. Along with the added structure and project move, I've also moved generic node, npm, typescript and linting dependencies and config to the root package (`desktop-electron-app/`).

I really recommend reviewing this PR commit-by-commit. The first commit only moves files without any changes.

Fixes DES-1408.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> Reviewed 5 of 616 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: 5 of 616 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 616 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: 6 of 616 files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 8 of 616 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: 12 of 616 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-OB-WlDc3KgMHohRXZlY):*
nit: the package name `mullvad-vpn` sound a bit generic since all/most things in our repo is "mullvad-vpn" stuff. I suggest something like `mullvad-gui`, `mullvad-app`, `gui` or `app`. For Android we for example have `android/app`.



_Code quote:_
```
desktop-electron-app/packages/mullvad-vpn
```
___
*[`android/README.md` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-OB-ZiSKD7IRyDsYOiOf:-OB-ZiSL264QbUKImE7c:bdpduet) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da3a754b26b53b9bade5e12381c8b5febfd57025/android/README.md#L74)):*
> ```Markdown
> the tool used to sync translations between the Android and Desktop apps.
> 
> [desktop-locales-readme]: ../desktop-electron-app/packages/mullvad-vpn/locales/README.md
> ```

Not sure what the roadmap here is, but wouldn't it make sense to keep the `locales` directory outside of the `desktop-electron-app` directory as part of improving this structure? I believe we shouldn't have any dependencies from `android` on things under `desktop-electron-app`

**Comment by MrChocolatine** [comment]
`desktop-electron-app`, what if one day you migrate to Tauri #4063 ? Or similar?

**Review by raksooo — COMMENTED** [review]
We're open to change the naming again in the future if we switch to another technology. But we also decided to name the directory just `desktop` :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-:-OBAbRe21OAJuEb7XZeM:b-vaus8k)* status: 0 of 616 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @faern, and @pinkisemils)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-OB-WlDc3KgMHohRXZlY:-OBAbksu0bhMboKH1Zbz:b-e0nkix):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: the package name `mullvad-vpn` sound a bit generic since all/most things in our repo is "mullvad-vpn" stuff. I suggest something like `mullvad-gui`, `mullvad-app`, `gui` or `app`. For Android we for example have `android/app`.
</blockquote></details>

As talked about IRL, we've decided to keep the name "mullvad-vpn" but replace the top-level name with just "desktop".

**Review by faern — COMMENTED** [review]
> Reviewed 2 of 616 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: 2 of 616 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @pinkisemils)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: 2 of 616 files reviewed, all discussions resolved (waiting on @albin-mullvad, @faern, and @pinkisemils)

___
*[`android/README.md` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-OB-ZiSKD7IRyDsYOiOf:-OBAnDsD5HFWEBMWY-pi:b-awgr9x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da3a754b26b53b9bade5e12381c8b5febfd57025/android/README.md#L74)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Not sure what the roadmap here is, but wouldn't it make sense to keep the `locales` directory outside of the `desktop-electron-app` directory as part of improving this structure? I believe we shouldn't have any dependencies from `android` on things under `desktop-electron-app`
</blockquote></details>

As discussed IRL this would be really nice but I consider it out-of-scope in this PR. Would be really nice to do though!

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 611 of 616 files at r1, 2 of 2 files at r2, 613 of 616 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-:-OBAoIgiCaK2kvZ8Nv0O:bnfp4nl)* status: 613 of 616 files reviewed, all discussions resolved (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 7 of 616 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: 7 of 616 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-OB-WlDc3KgMHohRXZlY:-OBB2hJxAPtN9JYtyo6D:b-n55f24):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

As talked about IRL, we've decided to keep the name "mullvad-vpn" but replace the top-level name with just "desktop".
</blockquote></details>

Alright :thumbsup: 
___
*[`android/README.md` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130#-OB-ZiSKD7IRyDsYOiOf:-OBB2mn48UO6VMUkuvwR:blx4dtm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da3a754b26b53b9bade5e12381c8b5febfd57025/android/README.md#L74)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

As discussed IRL this would be really nice but I consider it out-of-scope in this PR. Would be really nice to do though!
</blockquote></details>

Sounds good! I created DROID-1518 to address it

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 611 of 616 files at r1, 2 of 2 files at r2, 613 of 616 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]

**Review by albin-mullvad — APPROVED** [review]

**Review by albin-mullvad — APPROVED** [review]

**Pull request merged**
