### PR TITLE
Linux firewall integration

### PR DESCRIPTION
**Pull request by faern**
Here comes the Linux firewall integration.

Beware, I have not tested it very extensively yet. There might even be an entire class of rules missing or misbehaving. I just feel like I have been massaging this for long enough without any insight into what I'm doing. So I don't think I can make it much better without having a round of feedback first. I have probably become blind to my own errors by now.

Sorry for it being a bit of a large PR. You can follow some changes commit for commit at first, but then the entire firewall implementation comes in one commit sadly.

Our netfilter library is very low level, and as such creating the rules here becomes very low level. Ask about anything you don't understand and I'll try to answer as best as I can :)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jvff, @pronebird, and @pinkisemils)

---

*[talpid-core/src/firewall/linux/mod.rs, line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7iRo43gDiNo5jJZ__:-LG7iRo55aFRn0q2-IvV:bwdksbd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/187b1b7eb6ae85713a57f5be6ded54fc8cf05e6b/talpid-core/src/firewall/linux/mod.rs#L73)):*
> ```Rust
> pub struct Netfilter {
>     dns_settings: DnsSettings,
>     table: Table,
> ```

FYI Having this table exist for the entire lifetime of the struct is not important in any sense really. It's really just so I don't have to repeat the line that creates it. Other solutions to this would involve making it a `lazy_static` but not sure that would be nicer in any way. Yet another way is to have a global static for the `ProtoFamily` it uses and simply create a new table instance in the two (lol) places it's used.

---

*[talpid-core/src/firewall/linux/mod.rs, line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7jWGB42MIqE9lVr93:-LG7jWGC-HwuavIyD-mo:brew8zb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/187b1b7eb6ae85713a57f5be6ded54fc8cf05e6b/talpid-core/src/firewall/linux/mod.rs#L181)):*
> ```Rust
> }
> 
> struct PolicyBatch<'a> {
> ```

The purpose of this helper struct is really just to be able to collect the batch + chain instances under one object. Makes it much easier and less verbose to create the rules down below. Makes me not have to pass around the batch and chains as arguments everywhere.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by faern** [comment]
Review status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jvff, @pronebird, and @pinkisemils)

---

*[talpid-core/src/firewall/linux/mod.rs, line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7iRo43gDiNo5jJZ__:-LG7lIMz3rJJf0EyKLmW:b7vny3x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/187b1b7eb6ae85713a57f5be6ded54fc8cf05e6b/talpid-core/src/firewall/linux/mod.rs#L73)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

FYI Having this table exist for the entire lifetime of the struct is not important in any sense really. It's really just so I don't have to repeat the line that creates it. Other solutions to this would involve making it a `lazy_static` but not sure that would be nicer in any way. Yet another way is to have a global static for the `ProtoFamily` it uses and simply create a new table instance in the two (lol) places it's used.
</blockquote></details>

Disregard that. I take it back. It does have to live for the entire time because the `FinalizedBatch` returned from `Netfilter::policy_batch` has references into the table.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by jvff** [comment]
Reviewed 6 of 9 files at r1, 3 of 4 files at r2.
Review status: 0 of 10 files reviewed, 9 unresolved discussions (waiting on @pronebird, @pinkisemils, @jvff, and @faern)

---

*[talpid-core/Cargo.toml, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7wZy04FzOz0gROMbx:-LG7wZy04FzOz0gROMby:bpzo2u4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/Cargo.toml#L12)):*
> ```TOML
> duct = "0.10"
> error-chain = "0.12"
> ipnetwork = "0.13"
> ```

Can this be moved to `[target.'cfg(unix)'.dependencies]`?

---

*[talpid-core/Cargo.toml, line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xFEO9IiukfUGSYrs:-LG7wtHG-J8WqNBcwy0H:byqggtt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/Cargo.toml#L15)):*
> ```TOML
> jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
> jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
> lazy_static = "1.0"
> ```

Can this be moved to `[target.'cfg(target_os = "linux")'.dependencies]`?

---

*[talpid-core/src/lib.rs, line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7wgzj4MhAvKQ-G4mB:-LG7wgzj4MhAvKQ-G4mC:bq0o0nb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/lib.rs#L20)):*
> ```Rust
> #[macro_use]
> extern crate error_chain;
> extern crate ipnetwork;
> ```

Can this be `#[cfg(unix)]`?

---

*[talpid-core/src/lib.rs, line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xEIW1BDsMjUEuMrW:-LG7x25KDIkNAW7cKtE7:b-jtrare) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/lib.rs#L25)):*
> ```Rust
> extern crate jsonrpc_macros;
> #[macro_use]
> extern crate lazy_static;
> ```

Can this be `#[cfg(target_os = "linux")]`?

---

*[talpid-core/src/firewall/mod.rs, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xMLj5tAjEsElsg8I:-LG7xMLj5tAjEsElsg8J:bmgbpj2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/mod.rs#L9)):*
> ```Rust
> 
> #[cfg(unix)]
> lazy_static! {
> ```

Hopefully your PR for `rustc` from the Impl Days gets merged in time for Rust 2018 :)

---

*[talpid-core/src/firewall/linux/mod.rs, line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG8Mg6d6wFp2JQvOY6T:-LG8Mg6d6wFp2JQvOY6U:bbkjurw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/linux/mod.rs#L91)):*
> ```Rust
>         }
> 
>         // First try to set the new policy with a batch starting with a command to delete the table
> ```

Would the same approach used in `reset_policy` work here? Adding a "dummy" table first with the same name then deleting it?

---

*[talpid-core/src/firewall/linux/mod.rs, line 155 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG8NuRf5WIBc2L8AaKF:-LG8NuRf5WIBc2L8AaKG:blr20hq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/linux/mod.rs#L155)):*
> ```Rust
>             .recv(&mut buf[..])
>             .chain_err(|| ErrorKind::NetlinkRecvError)?;
>         trace!("Read {} bytes from netlink", ret);
> ```

This might be a style issue, but I would try to move the 4 lines above into a separate function that returns the `&buf[..ret]` slice in an `Option`, so you could do something like `while let Some(bytes) = read_from_nl_socket(&mut socket, &mut buf)`. Not sure if there might be NLL requirements due to the borrows.

---

*[talpid-core/src/firewall/linux/mod.rs, line 157 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG8NHan7OR0PDDhfSwZ:-LG8NHan7OR0PDDhfSw_:bspz353) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/linux/mod.rs#L157)):*
> ```Rust
>         trace!("Read {} bytes from netlink", ret);
>         while ret > 0 {
>             match mnl::cb_run(&buf[..ret], 2, portid) {
> ```

Is it possible to add a `?` here? That would remove one of the match variants.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by faern** [comment]
I should maybe write some tips on how to use nftables to verify what the program does. You need to install the `nftables` package first. Then the command is `nft`. `nft list ruleset inet` will list all tables->chains->rules for inet (inet being IPv4 *and* IPv6). This program will add inet rules that can thus later hold rules to both IPv4 and IPv6 in the same chains, in order to not need two of everything.

So I usually have a separate terminal running `sudo watch -n 1 nft list ruleset inet` so I can watch the rules come and go live when I connect and disconnect.

---

Review status: 0 of 10 files reviewed, 9 unresolved discussions (waiting on @pronebird, @pinkisemils, @jvff, and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-:-LG9U-ak7_C-O6mC3_xT:bu9i8ts)*

**Comment by faern** [comment]
Review status: 0 of 10 files reviewed, 9 unresolved discussions (waiting on @pronebird, @pinkisemils, @jvff, and @faern)

---

*[talpid-core/Cargo.toml, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7wZy04FzOz0gROMbx:-LG9afk9-mAjcoQO0h5g:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/Cargo.toml#L12)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can this be moved to `[target.'cfg(unix)'.dependencies]`?
</blockquote></details>

Done.

---

*[talpid-core/Cargo.toml, line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xFEO9IiukfUGSYrs:-LG9afWKC3dmmxxPIasP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/Cargo.toml#L15)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can this be moved to `[target.'cfg(target_os = "linux")'.dependencies]`?
</blockquote></details>

Done.

---

*[talpid-core/src/lib.rs, line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7wgzj4MhAvKQ-G4mB:-LG9Uv4F4fpdbffRGptw:bsxv2o7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/lib.rs#L20)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can this be `#[cfg(unix)]`?
</blockquote></details>

Oh my god I'm looking forward to Rust 2018. All this bloat with `extern crates` is so messy.

---

*[talpid-core/src/lib.rs, line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xEIW1BDsMjUEuMrW:-LG9adW912gAzTsQhX7a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/lib.rs#L25)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can this be `#[cfg(target_os = "linux")]`?
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/mod.rs, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xMLj5tAjEsElsg8I:-LG9ah3iAC-RWj_cR-uj:b-vs89ad) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/mod.rs#L9)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Hopefully your PR for `rustc` from the Impl Days gets merged in time for Rust 2018 :)
</blockquote></details>

I would not have my hopes too high. So far I only got `u32::to_be` to be a `const fn` and it's not even accepted for stable. :)

---

*[talpid-core/src/firewall/linux/mod.rs, line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG8Mg6d6wFp2JQvOY6T:-LG9VJml97OaBlXnfvib:b-yaz1nh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/linux/mod.rs#L91)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Would the same approach used in `reset_policy` work here? Adding a "dummy" table first with the same name then deleting it?
</blockquote></details>

Hmm.. So you mean we make the batch always `add -> delete -> add` the table and then the rules.. That might actually work. It feels very hacky, but so is the other solution. Great thinking! I'll try :+1:

---

*[talpid-core/src/firewall/linux/mod.rs, line 155 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG8NuRf5WIBc2L8AaKF:-LG9aPg65BkN6bDXaJJN:b-vpb0bn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/linux/mod.rs#L155)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This might be a style issue, but I would try to move the 4 lines above into a separate function that returns the `&buf[..ret]` slice in an `Option`, so you could do something like `while let Some(bytes) = read_from_nl_socket(&mut socket, &mut buf)`. Not sure if there might be NLL requirements due to the borrows.
</blockquote></details>

It worked out kind of the way you described! Thanks, that's a lot better IMO.

---

*[talpid-core/src/firewall/linux/mod.rs, line 157 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG8NHan7OR0PDDhfSwZ:-LG9Z1GQ3WgT_NsKM3ET:byjsona) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/linux/mod.rs#L157)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is it possible to add a `?` here? That would remove one of the match variants.
</blockquote></details>

Hmm yeah that should be possible. Either I did something more with the error previously or I just missed this opportunity. Thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by pronebird** [comment]
Reviewed 4 of 9 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
Review status: 0 of 10 files reviewed, 10 unresolved discussions (waiting on @pinkisemils, @jvff, and @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by jvff** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 0 of 10 files reviewed, 5 unresolved discussions (waiting on @pinkisemils, @jvff, @pronebird, and @faern)

---

*[talpid-core/src/firewall/mod.rs, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG7xMLj5tAjEsElsg8I:-LGAFdarA5p8rlvs7KDI:bn7vhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/74311ef95a106535fc0cebc78c104b694fdbb149/talpid-core/src/firewall/mod.rs#L9)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I would not have my hopes too high. So far I only got `u32::to_be` to be a `const fn` and it's not even accepted for stable. :)
</blockquote></details>

Well, fingers crossed :)

---

*[talpid-core/src/firewall/linux/mod.rs, line 125 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG9cobnCUzQeP07hrj4:-LGAleeuAXl1iZk-PkCU:bclr1uj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88f5d1a87fe23b33192239ee225fd427049205b9/talpid-core/src/firewall/linux/mod.rs#L125)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`s/Its/It's/`
</blockquote></details>

The only suggestion I can give here is to maybe name it `sequence_num` or something for clarity :/ But I'm not sure if that would actually emphasize its importance in the context, which maybe should be minimized?

---

*[talpid-core/src/firewall/linux/mod.rs, line 222 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGALf7g5dKw8Xl8mg0h:-LGALf7g5dKw8Xl8mg0i:bessu5x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L222)):*
> ```Rust
>     fn add_policy_specific_rules(&mut self, policy: &SecurityPolicy) -> Result<()> {
>         match policy {
>             SecurityPolicy::Connecting {
> ```

Just an idea, not sure if it would work out well. Have the match only return `(relay_endpoint, allow_lan, Option<tunnel>)`, and handle them separately after the match.

Not sure if the order is important, but maybe you can even keep the `tunnel` handling in the match arm?

---

*[talpid-core/src/firewall/linux/mod.rs, line 254 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAMgJs8ttLpIb6kv-b:-LGAMgJs8ttLpIb6kv-c:bk1pewu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L254)):*
> ```Rust
>         in_rule.add_expr(nft_expr!(ct state))?;
>         let allowed_states = nftnl::expr::ct::States::ESTABLISHED.bits();
>         in_rule.add_expr(nft_expr!(bitwise mask allowed_states, xor 0u32))?;
> ```

Could this `0u32` become a constant with a name to describe it?

---

*[talpid-core/src/firewall/linux/mod.rs, line 345 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAiggJC8clYzSpZCzB:-LGAiggJC8clYzSpZCzC:bxbtd8f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L345)):*
> ```Rust
>         Direction::Out => {
>             check_port(&mut rule, PROTOCOL, End::Src, CLIENT_PORT)?;
>             check_port(&mut rule, PROTOCOL, End::Dst, SERVER_PORT)?;
> ```

Probably subjective, but I think these lines would be more readable if `PROTOCOL` was named `UDP`.

---

*[talpid-core/src/firewall/linux/mod.rs, line 379 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAk8FuEF3x2kyiNJuZ:-LGAk8Fw3-MYk4no54bp:b-8vxqgt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L379)):*
> ```Rust
> fn iface_index(name: &str) -> Result<libc::c_uint> {
>     let c_name = CString::new(name).chain_err(|| ErrorKind::InvalidInterfaceName(name.to_owned()))?;
>     let index = unsafe { libc::if_nametoindex(c_name.as_ptr()) };
> ```

Great that you found this!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by pinkisemils** [comment]
Reviewed 4 of 9 files at r1, 2 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @pronebird, @jvff, @pinkisemils, and @faern)

---

*[talpid-core/src/firewall/linux/mod.rs, line 345 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAiggJC8clYzSpZCzB:-LGAonbP8glbO9s1lb39:b-cqqy1z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L345)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Probably subjective, but I think these lines would be more readable if `PROTOCOL` was named `UDP`.
</blockquote></details>

I think leaving it as `TransportProtocol::Udp` would be the clearest option, if we're optimising for clarity.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by faern** [comment]
Review status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @pronebird, @jvff, @pinkisemils, and @faern)

---

*[talpid-core/src/firewall/linux/mod.rs, line 125 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG9cobnCUzQeP07hrj4:-LGAnZHQ8b1bo3ZLZJtL:bp93bxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88f5d1a87fe23b33192239ee225fd427049205b9/talpid-core/src/firewall/linux/mod.rs#L125)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

The only suggestion I can give here is to maybe name it `sequence_num` or something for clarity :/ But I'm not sure if that would actually emphasize its importance in the context, which maybe should be minimized?
</blockquote></details>

Yeah I usually try to make people name their magic constants as well. The difference here is that we don't even know what it's supposed to be really :P I'm fine with keeping it as is for now and then research more later what the appropriate value should be.

---

*[talpid-core/src/firewall/linux/mod.rs, line 222 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGALf7g5dKw8Xl8mg0h:-LGAohs13mpAQsKTex7W:b-5h0scr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L222)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Just an idea, not sure if it would work out well. Have the match only return `(relay_endpoint, allow_lan, Option<tunnel>)`, and handle them separately after the match.

Not sure if the order is important, but maybe you can even keep the `tunnel` handling in the match arm?
</blockquote></details>

This is a good improvement suggestion. Not sure how it would be possible to handle it inside the match arm, but I think this turned out nice anyway.

---

*[talpid-core/src/firewall/linux/mod.rs, line 254 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAMgJs8ttLpIb6kv-b:-LGAovGYARPRes2SoRDW:b-ld28xw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L254)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could this `0u32` become a constant with a name to describe it?
</blockquote></details>

I'm not sure how to describe it. The point is that it does *nothing*. We don't want to XOR the value at all, but one must supply a value so XOR with `0` changes nothing. Everything else here is so low level, so I don't see any immediate win in naming this, one would basically have to be familiar with bitmasking and xoring to read it anyway.

---

*[talpid-core/src/firewall/linux/mod.rs, line 345 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAiggJC8clYzSpZCzB:-LGApMAD8g2kodBY19vy:bnkve9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L345)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think leaving it as `TransportProtocol::Udp` would be the clearest option, if we're optimising for clarity.
</blockquote></details>

Udp is the value, protocol is the type. I don't see the rationale behind this. Would be equivalent to renaming `SERVER_PORT` into `PORT67` :wink:

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by faern** [comment]
Review status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @pronebird, @jvff, and @pinkisemils)

---

*[talpid-core/src/firewall/linux/mod.rs, line 345 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAiggJC8clYzSpZCzB:-LGAqg0lB4aWRQUYu37y:bbq8pdq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L345)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Udp is the value, protocol is the type. I don't see the rationale behind this. Would be equivalent to renaming `SERVER_PORT` into `PORT67` :wink:
</blockquote></details>

But I went with removing the constant and using the value directly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r6.
Review status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @pronebird, @jvff, and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by jvff** [comment]
Review status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @pronebird, @jvff, and @pinkisemils)

---

*[talpid-core/src/firewall/linux/mod.rs, line 125 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LG9cobnCUzQeP07hrj4:-LGArPp-5q1XcD_VzXWM:bv1upy7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88f5d1a87fe23b33192239ee225fd427049205b9/talpid-core/src/firewall/linux/mod.rs#L125)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yeah I usually try to make people name their magic constants as well. The difference here is that we don't even know what it's supposed to be really :P I'm fine with keeping it as is for now and then research more later what the appropriate value should be.
</blockquote></details>

Yeah, I agree. Better to name it later more appropriately.

---

*[talpid-core/src/firewall/linux/mod.rs, line 254 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAMgJs8ttLpIb6kv-b:-LGArm459uxIVqesFhtp:bxkd10) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L254)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure how to describe it. The point is that it does *nothing*. We don't want to XOR the value at all, but one must supply a value so XOR with `0` changes nothing. Everything else here is so low level, so I don't see any immediate win in naming this, one would basically have to be familiar with bitmasking and xoring to read it anyway.
</blockquote></details>

Ah, now I understand. Yeah, should be fine then :)

---

*[talpid-core/src/firewall/linux/mod.rs, line 345 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAiggJC8clYzSpZCzB:-LGArxoB0t-HaxfkCYNU:b-qzijo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L345)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

But I went with removing the constant and using the value directly.
</blockquote></details>

I understand your point. And I think my point is more subjective than anything else. It just felt that `protocol` was too ambiguous (did it mean the DHCP protocol, for instance? I know that's impossible, but naming wise it seemed weird), whereas `client port` and `server port` seemed to strike the right balance :/

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r6.
Review status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @pronebird, @jvff, @pinkisemils, and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by jvff** [comment]
Review status: 6 of 10 files reviewed, all discussions resolved (waiting on @pronebird, @jvff, and @pinkisemils)

---

*[talpid-core/src/firewall/linux/mod.rs, line 345 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260#-LGAiggJC8clYzSpZCzB:-LGAxsro7UmAzdSCZwux:b-7to165) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5186f15744d1e03d461374f39b097993c7d4700f/talpid-core/src/firewall/linux/mod.rs#L345)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah yeah, naming it `DHCP_PROTOCOL` would have made a lot of sense. You are correct! But you are fine the way it's implemented now, without a constant?
</blockquote></details>

Yes, looks good to me :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r7.
Review status: 5 of 10 files reviewed, all discussions resolved (waiting on @pronebird, @pinkisemils, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r7.
Review status: 5 of 10 files reviewed, all discussions resolved (waiting on @pronebird, @jvff, and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Comment by pronebird** [comment]
Reviewed 1 of 9 files at r1, 1 of 4 files at r2, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/260)*

**Pull request merged**
