### PR TITLE
Enable testing API access with a given configuration

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR implements the "Test" button for testing our API via a custom configuration.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: 4 of 16 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadREST/Transport/ConfiguredTransportProvider.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NoqIzRJAkszzkQR2mts:-Noujkn09n5jFpiuiXjF:b-9jzun3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58732119e01940bcc8a10fa05dfbf873478e617d/ios/MullvadREST/Transport/ConfiguredTransportProvider.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

shall it be a part of `MullvadREST` framework?   shouldn't it be better `ConfigurableTransportProvider` or `ProxyConfigurationTransportProvider`?
</blockquote></details>

I like `ProxyConfigurationTransportProvider`
___
*[`ios/MullvadREST/Transport/ConfiguredTransportProvider.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NoukxUf4pe-ukENwb69:-NoukxUf4pe-ukENwb6A:b5i79mz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58732119e01940bcc8a10fa05dfbf873478e617d/ios/MullvadREST/Transport/ConfiguredTransportProvider.swift#L55)):*
> ```Swift
>             return URLSessionSocks5Transport(
>                 urlSession: urlSession,
>                 configuration: Socks5Configuration(
> ```

Nit: This sort of circumvents the decision to keep `.noAuthentication` around instead of making user and pass optional. I think this looks and functions well, but in `TransportStrategy` we do check for both cases and create our config accordingly.
___
*[`ios/MullvadREST/Transport/ProxyConfiguredTransportProvider.swift` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NousS9V48145jEOk1QG:-NousS9V48145jEOk1QH:btr99x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39ac86c7536624ca38621c5a781734f34b889031/ios/MullvadREST/Transport/ProxyConfiguredTransportProvider.swift#L1)):*
> ```Swift
> //
> ```

This file is a duplicate of `ConfiguredTransportProvider.swift`.

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-Nouv1wZ1v4npgf_IJTq:-Nouv1wZ1v4npgf_IJTr:bxe5w0x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73541c00321c991220bd161c0e6bb21ddb3e8f35/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L30)):*
> ```Swift
>             let request = REST.HeadRequest(transport: transport)
>             headRequest = request
>             cancellable = request.makeRequest { error in
> ```

I know that we discussed the longevity of the request object before. Does the cancellable not keep the request alive then?

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadREST/Transport/ConfiguredTransportProvider.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NoqIzRJAkszzkQR2mts:-Nov04XZDTytnP4FoG0F:b-kqm6f0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58732119e01940bcc8a10fa05dfbf873478e617d/ios/MullvadREST/Transport/ConfiguredTransportProvider.swift#L14)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I like `ProxyConfigurationTransportProvider`
</blockquote></details>

Meh I'm not a big fan of it, but I'm not gonna die on that hill either, consider it done !
___
*[`ios/MullvadREST/Transport/ConfiguredTransportProvider.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NoukxUf4pe-ukENwb69:-Nov-fX42rttocGd6OJG:b-2zgocw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58732119e01940bcc8a10fa05dfbf873478e617d/ios/MullvadREST/Transport/ConfiguredTransportProvider.swift#L55)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: This sort of circumvents the decision to keep `.noAuthentication` around instead of making user and pass optional. I think this looks and functions well, but in `TransportStrategy` we do check for both cases and create our config accordingly.
</blockquote></details>

The code was written before we had that, and I forgot to update it. Will do now, good catch !
___
*[`ios/MullvadREST/Transport/ProxyConfiguredTransportProvider.swift` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NousS9V48145jEOk1QG:-NouzyeQ6SFps7VL04O_:bbs09s4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39ac86c7536624ca38621c5a781734f34b889031/ios/MullvadREST/Transport/ProxyConfiguredTransportProvider.swift#L1)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This file is a duplicate of `ConfiguredTransportProvider.swift`.
</blockquote></details>

Argh Xcode !!!!
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-Nouv1wZ1v4npgf_IJTq:-Nov0Qt_3Y9oSOg5W60l:bgqmdo0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73541c00321c991220bd161c0e6bb21ddb3e8f35/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L30)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I know that we discussed the longevity of the request object before. Does the cancellable not keep the request alive then?
</blockquote></details>

If no one holds the cancellable, it gets deallocated when it gets out of scope here. But also we need to keep it around to `cancel` it anyway. Unless I misunderstood what you were suggesting ?

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: 10 of 16 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadREST/ApiHandlers/HeadRequest.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NoqmnodBFGZeMSs-QD2:-NovcL8p2e9Xo8isInGo:bcar2ya) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58732119e01940bcc8a10fa05dfbf873478e617d/ios/MullvadREST/ApiHandlers/HeadRequest.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> this request is like a ping address

That is not correct.
What is usually called `ping` request is in most cases an [ICMP Ping](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol), which happens at the Internet layer of the OSI model.

This is a `HEAD` request, which implies it runs at the application layer (because it's HTTP).

> is `HeadRequest` well-defined name for that? the names seems to me every request with `head` method can go through with `HeadRequest`

I don't understand what you're suggesting.
</blockquote></details>

Certainly, considering your additional context, how about the name "ServerVisibilityChecker" or "ConnectionVerifier"? These names emphasise the functionality of the class in checking if the application can see our servers without explicitly mentioning the HTTP method in the name.

`HeadRequest` suggests that I can pass any 'HEAD' request through it but it's not correct.

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 30 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-Nouv1wZ1v4npgf_IJTq:-Novh-Ns8uahtvCJb7Us:b-8m2va) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73541c00321c991220bd161c0e6bb21ddb3e8f35/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L30)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If no one holds the cancellable, it gets deallocated when it gets out of scope here. But also we need to keep it around to `cancel` it anyway. Unless I misunderstood what you were suggesting ?
</blockquote></details>

I was thinking that the headRequest would not go out of scope so long as it's bound to the cancellable.

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: 12 of 16 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 19 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-Novp8Eq9KThn6Ty_wXX:-Novp8Er0-dyF2_dmHOz:bxw5cqq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6565de625d86e44c902ce484add9d6053022607/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L19)):*
> ```Swift
>     private var cancellable: MullvadTypes.Cancellable?
>     private let transportProvider: ProxyConfigurationTransportProvider
>     private var headRequest: REST.APIAvailabilityTestRequest?
> ```

shouldn't it be `apiAvailabilityTestRequest`?
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 31 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-Novpgg94JIdCsLmJoF0:-Novpgg94JIdCsLmJoF1:bh1xymf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6565de625d86e44c902ce484add9d6053022607/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L31)):*
> ```Swift
>             headRequest = request
>             cancellable = request.makeRequest { error in
>                 DispatchQueue.main.async {
> ```

it's better to do context switching in interactor. 
___
*[`ios/MullvadREST/ApiHandlers/APIAvailabilityTestRequest.swift` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NovoIN69EuSjK7zFbdq:-NovoIN69EuSjK7zFbdr:b88184m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6565de625d86e44c902ce484add9d6053022607/ios/MullvadREST/ApiHandlers/APIAvailabilityTestRequest.swift#L2)):*
> ```Swift
> //
> //  HeadRequest.swift
> ```

it should be renamed

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

**Review by mojganii — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 31 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-Novpgg94JIdCsLmJoF0:-NovukYY-aNcSHwMF4b1:b-nyzcw0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6565de625d86e44c902ce484add9d6053022607/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L31)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Then I'd have to do that in both the `AddAccessMethodInteractor` and `EditAccessMethodInteractor` which is suboptimal IMHO
</blockquote></details>

It's not a big deal.but If were I would do that at the layer is closer to the UI

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @rablador)

___
*[`ios/MullvadREST/ApiHandlers/APIAvailabilityTestRequest.swift` line 2 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713#-NovoIN69EuSjK7zFbdq:-NovxeoA1TkobbZSkJTZ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6565de625d86e44c902ce484add9d6053022607/ios/MullvadREST/ApiHandlers/APIAvailabilityTestRequest.swift#L2)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it should be renamed
</blockquote></details>

Done

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
