### PR TITLE
Add billing and infrastructure flavor dimensions

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR changes the build configuration from only relying on build types to also rely on two flavor dimensions.

Flavor dimensions:
* `billing` - used to build separate artifacts where (1) different policies are followed and (2) different dependencies are used. This dimension will initially have the following flavors: `oss`, `play`.
* `infrastructure` - used to enable development and testing against non-production environments. This dimension will initially have the following flavors: `prod`, `devmole`.

This is the full set of enabled variants: 
 
| Build variant      | Full distribution artifact name                      | Application id                    |
|--------------------|------------------------------------------------------|-----------------------------------|
| ossProdRelease     | MullvadVPN-\<version\>.apk                           | net.mullvad.mullvadvpn            |
| ossProdDebug       | MullvadVPN-\<version\>.debug.apk                     | net.mullvad.mullvadvpn            |
| ossProdFdroid      | MullvadVPN-\<version\>.fdroid.apk                    | net.mullvad.mullvadvpn            |
| ossProdLeakCanary  | MullvadVPN-\<version\>.leakCanary.apk                | net.mullvad.mullvadvpn.leakcanary |
| playProdRelease    | MullvadVPN-\<version\>.play.(apk\|aab)               | net.mullvad.mullvadvpn            |
| playProdDebug      | MullvadVPN-\<version\>.play.debug.(apk\|aab)         | net.mullvad.mullvadvpn            |
| playDevmoleRelease | MullvadVPN-\<version\>.play.devmole.(apk\|aab)       | net.mullvad.mullvadvpn.devmole    |
| playDevmoleDebug   | MullvadVPN-\<version\>.play.devmole.debug.(apk\|aab) | net.mullvad.mullvadvpn.devmole    |

> NOTE: The artifacts only listed as `*.apk` can also be explicitly built as bundles, but those will not be used since only `play*` variants will be uploaded to Google Play.

TODO:
* [ ] Verify/update the F-Droid build instructions in the F-Droid metadata repository.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-:-Ner01_N-g3Od_sGR4di:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/lib/build.gradle.kts` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-Ner-1tZ7DWZrSK1j431:-Ner-1tZ7DWZrSK1j432:b-1v8547) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5190bf7a7b168a1172bd077d9675070fecfd4287/android/lib/build.gradle.kts#L1)):*
> ```Kotlin
> 
> ```

I guess this was part of the formatting, but this looks a bit odd?
___
*[`android/test/build.gradle.kts` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-Ner-pEF3BTtj7v1SPut:-Ner-pEF3BTtj7v1SPuu:b-ya81ng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5190bf7a7b168a1172bd077d9675070fecfd4287/android/test/build.gradle.kts#L1)):*
> ```Kotlin
> 
> ```

Same as above

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/lib/build.gradle.kts` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-Ner-1tZ7DWZrSK1j431:-Ner0KM05ksAU4NGZUii:b-qyn1z8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5190bf7a7b168a1172bd077d9675070fecfd4287/android/lib/build.gradle.kts#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess this was part of the formatting, but this looks a bit odd?
</blockquote></details>

Yes, part of the formatting, but I agree
___
*[`android/test/build.gradle.kts` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-Ner-pEF3BTtj7v1SPut:-Ner0s6iChCqnJ-DmkvQ:b-qyn1z8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5190bf7a7b168a1172bd077d9675070fecfd4287/android/test/build.gradle.kts#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Yes, part of the formatting, but I agree

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-Ner7Cx247ZhZqFHJjDT:-Ner7Cx247ZhZqFHJjDU:b-x98kc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5190bf7a7b168a1172bd077d9675070fecfd4287/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L5)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.constant.IS_PLAY_BUILD
> 
> fun String.appendHideNavOnReleaseBuild(): String =
> ```

I saw that this was just moved and that the name hasn't changed but maybe we should rename this to `appendHideNavOnPlayBuild` or something along those lines?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684)* status: 29 of 33 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-Ner7Cx247ZhZqFHJjDT:-Ner7xHiElZxp299_usA:b-mavs24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5190bf7a7b168a1172bd077d9675070fecfd4287/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L5)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I saw that this was just moved and that the name hasn't changed but maybe we should rename this to `appendHideNavOnPlayBuild` or something along those lines?
</blockquote></details>

Good catch! Done :slightly_smiling_face:

**Review by Pururun — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — APPROVED** [review]
:lgtm:

> Reviewed 29 of 33 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-:-NerhgkA1L-0xJ5OOG12:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by sabercodic — APPROVED** [review]
> Reviewed 29 of 33 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4684#-:-NesPmmjA_ycosMAXXzq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Pull request merged**
