### PR TITLE
Handle legacy always-on vpn profiles

### PR DESCRIPTION
**Pull request by Rawa**
This PR reworks how we prepare the VpnService, expanding the to also handle the case of legacy always on. Changes include:
- Change of terminology inside our code base to be more aligned with API. (Prepared / NotPrepared)
- Rework the flow of requesting Vpn Profile
- Make cases more explicit so it is more clear what happens 
- Fix regression of `INVALID_DNS_SERVERS`, so we can show the more explicit error message again.
- Refactor the error messages for when no VPN profile is setup

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
Nice work, so much better!

> Reviewed 75 of 75 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-:-OCbwOl24nB5WjHGg0bE:biwgx5r)* status: all files reviewed, 7 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuVjI5zdcLEZDrzcU:-OCbuVjI5zdcLEZDrzcV:b-5mg94w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1cfddc46c17ca661bad974433f7c513b662832c/android/lib/resource/src/main/res/values/strings.xml#L109)):*
> ```XML
>     <string name="try_again">Try again</string>
>     <string name="blocked_connection">BLOCKED CONNECTION</string>
>     <string name="error_state">FAILED TO SECURE CONNECTION</string>
> ```

Has this been aligned with design?
___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/VpnProfileUseCase.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuzhV96YBBsRdE5hv:-OCbuzhWETWsK4TmwUTK:b-xk64c4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/VpnProfileUseCase.kt#L9)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.Prepared
> 
> class VpnProfileUseCase(private val applicationContext: Context) {
> ```

Not really important but almost all other uses cases are using `invoke()`operator and this does not. I understand why, since we want to wrap context, but maybe this should not be a use case?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbsehO7F-fplRs4EjU:-OCbsehO7F-fplRs4EjV:b8ux7nv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt#L109)):*
> ```Kotlin
>         message = error.message().formatWithHtml(),
>         statusLevel = StatusLevel.Error,
>         action = null,
> ```

If I am not mistaken, action is by default?
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbudfk780_fcuw1Tik:-OCbudfl2hWuWeLMsuaK:b-xhggle) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/resource/src/main/res/values/strings.xml#L172)):*
> ```XML
>         <![CDATA[Unable to start tunnel connection. Please disable Always-on VPN for <b>%s</b> before using Mullvad VPN.]]>
>     </string>
>     <string name="legacy_always_on_vpn_error_notification_title">Always-on VPN assigned to other app</string>
> ```

Should we mention app here? As far as I can tell it is a vpn profile. Could be confusing.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuOZvCEQOAf26Tqvn:-OCbuOZw2NSjaDhtZ_0Y:b-b3317a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt#L8)):*
> ```Kotlin
> 
> sealed interface PrepareError : PrepareResult {
>     // Result from VpnService.prepare() being invoked with legacy VPN app has always-on
> ```

Nit: Should probably not say legacy vpn app, but rather vpn profile
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuE7t2p21oIKxD69h:-OCbuE7t2p21oIKxD69i:b-uzjtth) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt#L11)):*
> ```Kotlin
>     data object OtherLegacyAlwaysOnVpn : PrepareError
> 
>     // Prepare gives intent but there is other always VPN app
> ```

Nit: Should at least be "always on VPN" but could maybe be improved further
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/CreateVpnProfile.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbt28r7B0kBJ9iJ7ly:-OCbt28r7B0kBJ9iJ7lz:buho2we) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/CreateVpnProfile.kt#L8)):*
> ```Kotlin
> import androidx.activity.result.contract.ActivityResultContract
> 
> class CreateVpnProfile : ActivityResultContract<Intent, Boolean>() {
> ```

I wonder if this could be done even more generic, since all we do is take any intent. So this could be `IntentActivityResultContract` instead or something.

**Review by Pururun — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: all files reviewed, 7 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbsehO7F-fplRs4EjU:-OCbw_CK3TTde22fLr5j:b-8nhkj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt#L109)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

If I am not mistaken, action is by default?
</blockquote></details>

*null

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 12 of 75 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: all files reviewed, 8 unresolved discussions (waiting on @Rawa)

___
*[`mullvad-daemon/src/lib.rs` line 1444 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCcKZhk77UeKvbasldD:-OCcKZhk77UeKvbasldE:b-7e8t5z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/mullvad-daemon/src/lib.rs#L1444)):*
> ```XML
>                 // Announce to all clients listening for updates of the
>                 // currently active access method. The announcement should be
>                 // made after the firewall policy has been updated, since the
> ```

Comment doesn't make sense on Android. `protect` is called by `mullvad-api`.
___
*[`talpid-core/src/tunnel_state_machine/connecting_state.rs` line 281 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCcK-7K4zv5qxUW0KOR:-OCcK-7K4zv5qxUW0KOS:b-t3rfka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/talpid-core/src/tunnel_state_machine/connecting_state.rs#L281)):*
> ```XML
> 
>                         #[cfg(target_os = "android")]
>                         tunnel::Error::WireguardTunnelMonitoringError(
> ```

We could probably clean up this match expression.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 73 of 75 files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbsehO7F-fplRs4EjU:-OCc2pSzA4Gmg0tNG5II:bfkocbp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt#L109)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

*null
</blockquote></details>

Correct! Good catch!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/CreateVpnProfile.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbt28r7B0kBJ9iJ7ly:-OCc2vet8QkkGaDbdQAN:bgiisam) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/CreateVpnProfile.kt#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I wonder if this could be done even more generic, since all we do is take any intent. So this could be `IntentActivityResultContract` instead or something.
</blockquote></details>

I believe the problem is that the parsing of result code might be different for different types of dialogs. For the VPN dialog it just returns a OK / FAIL. but this is not necessarily the case for others and then the contract generics would look different.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuOZvCEQOAf26Tqvn:-OCc3zxPD9J0A4mUYqTJ:b-5n7bjo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Nit: Should probably not say legacy vpn app, but rather vpn profile
</blockquote></details>

I've updated the text and clarified it a bit.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuE7t2p21oIKxD69h:-OCc42E88t-uxR9rHmV2:b-5n7bjo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt#L11)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Nit: Should at least be "always on VPN" but could maybe be improved further
</blockquote></details>

I've updated the text and clarified it a bit.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuVjI5zdcLEZDrzcU:-OCc46p01FnJ_tB7nB4K:b-701m85) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1cfddc46c17ca661bad974433f7c513b662832c/android/lib/resource/src/main/res/values/strings.xml#L109)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Has this been aligned with design?
</blockquote></details>

Yes, I've talked to Matilda.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbudfk780_fcuw1Tik:-OCcQ3p44CTWRHCJKV0N:b-i7arrv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/resource/src/main/res/values/strings.xml#L172)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should we mention app here? As far as I can tell it is a vpn profile. Could be confusing.
</blockquote></details>

Let's dicsuss offline

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 75 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 73 of 75 files reviewed, 6 unresolved discussions (waiting on @Pururun)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 73 of 75 files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/VpnProfileUseCase.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbuzhV96YBBsRdE5hv:-OCchM2v5-eJ30001rqi:b4vzfls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/VpnProfileUseCase.kt#L9)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Not really important but almost all other uses cases are using `invoke()`operator and this does not. I understand why, since we want to wrap context, but maybe this should not be a use case?
</blockquote></details>

No you are right, it is wrong. Because it is in the shared module our konsist rules didn't apply. I renamed the use case and fixed the function name :+1: Good catch!

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 73 of 76 files reviewed, 2 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`mullvad-daemon/src/lib.rs` line 1444 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCcKZhk77UeKvbasldD:-OCcnc7xEA5UqGLt3cVa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/mullvad-daemon/src/lib.rs#L1444)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Comment doesn't make sense on Android. `protect` is called by `mullvad-api`.
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/connecting_state.rs` line 281 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCcK-7K4zv5qxUW0KOR:-OCcmXyp5R8TgADDSOGS:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/talpid-core/src/tunnel_state_machine/connecting_state.rs#L281)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We could probably clean up this match expression.
</blockquote></details>

Fixed

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 50 of 76 files reviewed, 2 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239#-OCbudfk780_fcuw1Tik:-OCd5OdxBg29F8LYzitO:bvm7z8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a2c7a202e68cfe6e7db297860ccfc66a0ac4d0f/android/lib/resource/src/main/res/values/strings.xml#L172)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Let's dicsuss offline
</blockquote></details>

Resolved

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 14 of 75 files at r1, 1 of 1 files at r4, 2 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 54 of 76 files reviewed, 2 unresolved discussions (waiting on @dlon and @Pururun)

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 54 of 76 files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: 50 of 76 files reviewed, all discussions resolved (waiting on @MarkusPettersson98 and @Pururun)

**Review by Pururun — APPROVED** [review]
> Reviewed 26 of 26 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7239)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
