### PR TITLE
Device list resets after going to settings

### PR DESCRIPTION
**Pull request by Pururun**
This is because the device list is not updated unless specifically told so.

Added so that it always updates on successful device list events.

Also improved the compose view.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-Ne7er5m3LAn135bs9CK:-Ne7er5m3LAn135bs9CL:b99fvfd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d9b11568b12868ac548cc1a614fd1a5ca889461/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
> ```Kotlin
>             .map {
>                 if (it is DeviceListEvent.Available) {
>                     cachedDeviceList.value = DeviceList.Available(it.devices)
> ```

I believe this fix is fine for now but we should probably revisit/reimagine how the DeviceRepository works, it feels unnaturally complex with multiple streams containing deviceList, deviceState, deviceRemovalEvent etc.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-NebT-GrDXamxQwTesbn:-NebT-GrDXamxQwTesbo:b-n3qst0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d9b11568b12868ac548cc1a614fd1a5ca889461/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
> ```Kotlin
>             .map {
>                 if (it is DeviceListEvent.Available) {
>                     cachedDeviceList.value = DeviceList.Available(it.devices)
> ```

This is probably find, but did you test various cases to check whether this cache works as expected? For instance to make sure that the cache never is used in the wrong situation, e.g. if the user tries to log in to another account (and an updated device list fails to be fetched).



_Code quote:_
```Kotlin
cachedDeviceList.value = DeviceList.Available(it.devices)
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-NebT-GrDXamxQwTesbn:-Nebt4eyCz_oaBnXjFVw:b-zgght4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a5236ddef7422fde2c0d5179ed09abd07aee2df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is probably find, but did you test various cases to check whether this cache works as expected? For instance to make sure that the cache never is used in the wrong situation, e.g. if the user tries to log in to another account (and an updated device list fails to be fetched).
</blockquote></details>

probably fine*

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-Ne7er5m3LAn135bs9CK:-NecIgaTB1ouhJcicdBA:b-3dnl3h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a5236ddef7422fde2c0d5179ed09abd07aee2df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe this fix is fine for now but we should probably revisit/reimagine how the DeviceRepository works, it feels unnaturally complex with multiple streams containing deviceList, deviceState, deviceRemovalEvent etc.
</blockquote></details>

Yes agree, very unnecessarily complex.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-NebT-GrDXamxQwTesbn:-NecImCfA0L-9aIEpvhS:bdvi7lu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a5236ddef7422fde2c0d5179ed09abd07aee2df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

probably fine*
</blockquote></details>

I have tested logging in to a different account, but not where an updated list fails to fetch.

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-NebT-GrDXamxQwTesbn:-NfLOx6N9cS9toKf3wGp:b-bxuc24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a5236ddef7422fde2c0d5179ed09abd07aee2df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I have tested logging in to a different account, but not where an updated list fails to fetch.
</blockquote></details>

Can that scenario also be tested either manually or/and using automated tests? Otherwise this one looks ready to merge.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-NebT-GrDXamxQwTesbn:-Nfji9ViB-oJDuyPtuJk:b-2qtr88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a5236ddef7422fde2c0d5179ed09abd07aee2df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can that scenario also be tested either manually or/and using automated tests? Otherwise this one looks ready to merge.
</blockquote></details>

Tested it manually and it seems to work fine in that scenario. I think we can merge.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-NebT-GrDXamxQwTesbn:-NfkCErB9zr85EWTyUCW:bi7es19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a5236ddef7422fde2c0d5179ed09abd07aee2df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt#L60)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Tested it manually and it seems to work fine in that scenario. I think we can merge.
</blockquote></details>

Great! :rocket:

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5128#-:-NfkQbYVDuxbwOzim1Hn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
