### PR TITLE
Improve accessibility of connection panel

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

- Improve accessibility in `ConnectionPanelView`
- Remove protocol row (since we always use WireGuard and it's a part of the hostname)
- Move localizations from `Localizable.strings` to `ConnectionPanel.strings`

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[ios/MullvadVPN/ConnectionPanelView.swift, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-MeZzLau2AexBHl4RnMd:-MeZzLau2AexBHl4RnMe:by0fr6a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/ConnectionPanelView.swift#L40)):*
> ```Swift
>             )
>             collapseButton.accessibilityAttributedValue = NSAttributedString(
>                 string: connectedRelayName.replacingOccurrences(of: "-wireguard", with: " WireGuard"),
> ```

FYI makes voice over pronounce WireGuard in English. 
___
*[ios/MullvadVPN/ConnectionPanelView.swift, line 151 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-MeZzeodAvrzfvrF84kE:-MeZzeodAvrzfvrF84kF:b-96u54m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/ConnectionPanelView.swift#L151)):*
> ```Swift
>         collapseButton.style = showsConnectionInfo ? .up : .down
> 
>         if collapseButton.accessibilityElementIsFocused(), showsConnectionInfo {
> ```

If the button with the hostname is in focus, the code below moves focus to the "In address".
___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-KhoDupSrqFM2o4a:-Me_-KhoDupSrqFM2o4b:b-jlpatu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L8)):*
> ```
> 
> /* No comment provided by engineer. */
> "IN_ADDRESS_ACCESSIBILITY_LABEL" = "Input IP address";
> ```

FYI not entire sure that's the good way to announce the "in" address.
___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-PCh2AeaC-kJT7pf:-Me_-PCh2AeaC-kJT7pg:b-5colk4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L14)):*
> ```
> 
> /* No comment provided by engineer. */
> "OUT_ADDRESS_ACCESSIBILITY_LABEL" = "Output IP address";
> ```

Same here. Not sure. If "Out" is sufficient.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-:-Med8s0tC6142OCt9t1-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-KhoDupSrqFM2o4a:-Med5YiA1LeG1bDvkjzu:be0bfov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L8)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI not entire sure that's the good way to announce the "in" address.
</blockquote></details>

How about something like "Entry IP address"? Have you asked Kat?
___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-PCh2AeaC-kJT7pf:-Med5duKDd6tFdDHSeyA:bvy9lk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here. Not sure. If "Out" is sufficient.
</blockquote></details>

"Exit"?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-PCh2AeaC-kJT7pf:-MedUvAiDZL4TnMyFh77:b-xewft5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L14)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

"Exit"?
</blockquote></details>

As per conversation on Slack, decided to drop the alternative accessibility labels.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-KhoDupSrqFM2o4a:-MedVOXT7kXtE_K4mM3G:b-xewft5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L8)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

How about something like "Entry IP address"? Have you asked Kat?
</blockquote></details>

As per conversation on Slack, decided to drop the alternative accessibility labels.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-PCh2AeaC-kJT7pf:-MedWPns-dYCCOq9Khr_:b-jv3fbp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As per conversation on Slack, decided to drop the alternative accessibility labels.
</blockquote></details>

Then they should be removed from here as well right?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-PCh2AeaC-kJT7pf:-MedXvflC-jF_cY_QXGD:b-ggkhre) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L14)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Then they should be removed from here as well right?
</blockquote></details>

My bad. Removed.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-:-Med_iA28UWdHhKzzZVC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/en.lproj/ConnectionPanel.strings, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2854#-Me_-PCh2AeaC-kJT7pf:-Med_eQ8BMJv8ARKtEsN:bhzvliq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d55ea2539839660e9d9d9c8338615c1329a45c21/ios/MullvadVPN/en.lproj/ConnectionPanel.strings#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

My bad. Removed.
</blockquote></details>

Great :+1:

**Pull request merged**
