### PR TITLE
Remove dependency on relay selector from tunnel actor

### PR DESCRIPTION
**Pull request by pronebird**
Currently `RelaySelectorResult` (a part of RelaySelector module) is used across different parts of tunnel manager <-> tunnel actor.

`RelaySelectorResult` itself is produced by `RelaySelector` and passed as is from tunnel manager into actor via IPC to initiate connection, here is how the data layout looks like:

```swift
struct RelaySelectorResult {
    var endpoint: MullvadEndpoint // endpoints, gateways, pubkey
    var relay: REST.ServerRelay // Lotta info about relay returned from API
    var location: Location // Geo location
}
```

Then over time the tunnel manager receives a slice of that data via `PacketTunnelRelay` as it polls tunnel status:

```swift
struct PacketTunnelRelay { // PacketTunnelCore
    let ipv4Relay: IPv4Endpoint
    let ipv6Relay: IPv6Endpoint?
    let hostname: String
    let location: Location
}
```

In reality however, actor does not need the entire `RelaySelectorResult`, it would be enough to receive a type holding the following info instead:

```swift
struct SelectedRelay {
    var endpoint: MullvadEndpoint
    var hostname: String
    var location: Location
}
```

### Changes

- Replace `RelaySelectorResult` with `SelectedRelay` in IPC/Actor interaction and subsequently removes dependency on `RelaySelector` in the actor.
- Pass `NextRelay` type instead of `RelaySelectorResult?` via `reconnectTunnel()` IPC method.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261)

### CODE REVIEW

**Review by buggmagnet — APPROVED** [review]
> Reviewed 12 of 19 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2672 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261#-NgOvGL60RK8VqpjtHFx:-NgOvGL7CbHjf-KCOCJ6:b-hcm7ph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e259a2b8fa36071f00c4e383d1e1b90dbb15e64/ios/MullvadVPN.xcodeproj/project.pbxproj#L2672)):*
> ```
> 			isa = PBXGroup;
> 			children = (
> 				5819ABC22A8CF02C007B59A6 /* TunnelAdapterProtocol.swift */,
> ```

Nit
Can we reorder those files to be in alphabetical order ?
___
*[`ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261#-NgOwKtpA59gEYlDv3oD:-NgOwKtq2R3I7qr-x3Ua:b-quonrl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e259a2b8fa36071f00c4e383d1e1b90dbb15e64/ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift#L18)):*
> ```Swift
>         case selectedRelay = "selected-relay"
> 
>         /// Option key that holds the `NSNumber` value, which is when set to `1` indicates that
> ```

nit

```
        /// Option key that holds an `NSNumber` value, which, when set to `1` indicates that
        /// the tunnel was started by the system.
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261)* status: 17 of 20 files reviewed, all discussions resolved (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2672 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261#-NgOvGL60RK8VqpjtHFx:-NgSq5nQ-B_P8_RA9g7f:bboemzo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e259a2b8fa36071f00c4e383d1e1b90dbb15e64/ios/MullvadVPN.xcodeproj/project.pbxproj#L2672)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Nit
Can we reorder those files to be in alphabetical order ?
</blockquote></details>

Done but keep in mind that this change might lead likely to merge conflicts in outstanding PRs.
___
*[`ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261#-NgOwKtpA59gEYlDv3oD:-NgSqd3GCfy7NMx5esrt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e259a2b8fa36071f00c4e383d1e1b90dbb15e64/ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit

```
        /// Option key that holds an `NSNumber` value, which, when set to `1` indicates that
        /// the tunnel was started by the system.
```
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 19 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed 13 of 19 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5261)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
