### PR TITLE
Add ShutdownHandler

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR refactors the shutdown coordination between main and renderer processes into one class and one function.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)

### CODE REVIEW

**Comment by pinkisemils** [comment]
Reviewed 6 of 6 files at r1.
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/shutdown-handler.js, line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211#-LEnwnCh7huFtk3Pp0NL:-LEnwnCh7huFtk3Pp0NM:bdxsap7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5d6fb250fb291c48ed99a825aee29e99bfe5296/app/shutdown-handler.js#L75)):*
> ```JavaScript
>  * The closure may return a Promise to postpone the shutdown until the asynchronous task is finished.
>  */
> function setShutdownHandler(handler: () => ?Promise<void>) {
> ```

Do we have any case where the handler would return a null value? I think the code could be simpler if it took a function that would always return a promise.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Comment by pronebird** [comment]
Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jvff, @pinkisemils, and @pronebird)

---

*[app/shutdown-handler.js, line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211#-LEnwnCh7huFtk3Pp0NL:-LEo0J1i7gYmt_5mao19:b-xuhnoc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5d6fb250fb291c48ed99a825aee29e99bfe5296/app/shutdown-handler.js#L75)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Do we have any case where the handler would return a null value? I think the code could be simpler if it took a function that would always return a promise.
</blockquote></details>

No, just flexibility option, but it can be one if less for sure :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Comment by jvff** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Comment by pronebird** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[app/shutdown-handler.js, line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211#-LEnwnCh7huFtk3Pp0NL:-LEoLQddA8n3-Q-jvO1Q:b1b762e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5d6fb250fb291c48ed99a825aee29e99bfe5296/app/shutdown-handler.js#L75)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

No, just flexibility option, but it can be one if less for sure :)
</blockquote></details>

Fixed that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r2.
Review status: 5 of 6 files reviewed, all discussions resolved (waiting on @jvff and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 4 of 6 files reviewed, all discussions resolved (waiting on @pinkisemils and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)*

**Pull request merged**
