### PR TITLE
Splittuneling viewmodel

### PR DESCRIPTION
**Pull request by axti**
This ViewModel is lifecycle aware component that help to update the view and listen user interactions and transform them to split tunnelling actions. Will include filtering later on. Contains few tests for different use cases.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 22 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 21 of 33 files reviewed, 1 unresolved discussion (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX7TE8F548UzCpHh7PP:-MX7TE8GD_NsuwEqi7Gj:b-hpn8ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a12336b9b86f41e284c0cd3af106d2a7d57f19a/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L19)):*
> ```Kotlin
>     }
> 
>     fun getAppsListAsync(): Deferred<List<AppData>> = CompletableDeferred(
> ```

This looks weird. I think it's not actually async. The `CompletableDeferred` constructor is not a suspend method, so it will actually block until it is ready, making the whole thing synchronized. I think it would need to be something like:

```
fun getAppsList(): Deferred<List<AppData>> = someCoroutineScope.async {
    // ...
}
```

The `CompletableDeferred` type is normally used in situations like this:

```
val deferredValue = CompletableDeferred<Int>()

uiScope.launch {
    val value = deferredValue.await()
}

backgroundScope.launch {
    val value = longComputation

    deferredValue.complete(value) // This "wakes up" the other coroutine
}
```

Also, I think it's okay to omit the `Async` method suffix, unless there's also a sync version :thinking:

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 26 of 31 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX7TE8F548UzCpHh7PP:-MX7YqLF3xLk5DuKw6mp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a12336b9b86f41e284c0cd3af106d2a7d57f19a/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L19)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This looks weird. I think it's not actually async. The `CompletableDeferred` constructor is not a suspend method, so it will actually block until it is ready, making the whole thing synchronized. I think it would need to be something like:

```
fun getAppsList(): Deferred<List<AppData>> = someCoroutineScope.async {
    // ...
}
```

The `CompletableDeferred` type is normally used in situations like this:

```
val deferredValue = CompletableDeferred<Int>()

uiScope.launch {
    val value = deferredValue.await()
}

backgroundScope.launch {
    val value = longComputation

    deferredValue.complete(value) // This "wakes up" the other coroutine
}
```

Also, I think it's okay to omit the `Async` method suffix, unless there's also a sync version :thinking: 
</blockquote></details>

Done.
___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/TestUtils.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX7Wkcv8gFnvpB0R-i1:-MX7ZOdV9kWETBGANfXt:b-3cv2ox) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a12336b9b86f41e284c0cd3af106d2a7d57f19a/android/src/test/kotlin/net/mullvad/mullvadvpn/TestUtils.kt#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe this can be reworded to `List should have the expected size and items`?
</blockquote></details>

I'm check original messages from `Assertions` class and tried to have same construction.
For example:  "Expected value to be true."
"Expected value to be not null."
"Expected <$expected>, actual <$actual> is not same."

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 31 files at r1, 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 29 of 31 files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX7TE8F548UzCpHh7PP:-MX7c7yz8UmQapZQ3OIm:b-h4r5ib) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a12336b9b86f41e284c0cd3af106d2a7d57f19a/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L19)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think the issue is still there. Maybe just make it a normal method like it was before, without the `CompletableDeferred`?

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 27 of 30 files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/TestUtils.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX7Wkcv8gFnvpB0R-i1:-MX82ZOwE3bupveLwYNv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a12336b9b86f41e284c0cd3af106d2a7d57f19a/android/src/test/kotlin/net/mullvad/mullvadvpn/TestUtils.kt#L7)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

I'm check original messages from `Assertions` class and tried to have same construction.
For example:  "Expected value to be true."
"Expected value to be not null."
"Expected <$expected>, actual <$actual> is not same."
</blockquote></details>

Done.

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 27 of 30 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX7TE8F548UzCpHh7PP:-MX82d-g9cXxLIUCW0BH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a12336b9b86f41e284c0cd3af106d2a7d57f19a/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L19)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think the issue is still there. Maybe just make it a normal method like it was before, without the `CompletableDeferred`?
</blockquote></details>

Done.

**Review by jvff — COMMENTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 28 of 30 files reviewed, all discussions resolved

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: all files reviewed, 3 unresolved discussions (waiting on @axti)

**Review by axti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633)* status: 29 of 30 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt, line 59 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX8YSIE7VvjP7zsvuEK:-MXBEepj3xhnMJaGVVuO:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44376bce7cbd85a0615537f2dd9e6e99cc90cbf1/android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L59)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Very minor, but maybe each item should be in a separate line to make it easier to read?
</blockquote></details>

Done
___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt, line 102 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX8ZWNEEP2wGvxKYgTC:-MXBEh5K4WToonY7AHiQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44376bce7cbd85a0615537f2dd9e6e99cc90cbf1/android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L102)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm a bit confused here. Why is `excludedAppList` called twice?
</blockquote></details>

Done.
___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt, line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-MX8Zh5V55tMt16qQype:-MXBEhXiCXe9IL_YwuRk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44376bce7cbd85a0615537f2dd9e6e99cc90cbf1/android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L105)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Isn't this already done by the `tearDown` method?
</blockquote></details>

Done.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2633#-:-MXCBC050eEQdYfMO18i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
