### PR TITLE
Separate ICMP reads from writes 

### PR DESCRIPTION
**Pull request by pinkisemils**
`wireguard-apple` has been changed to disjoin sending and receiving ICMP echo's and their responses. These changes accomodate that behavior in the ping monitor.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6887)

### CODE REVIEW

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6887#-:-O824brV5UY24Ry33cpA:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by buggmagnet — CHANGES_REQUESTED** [review]
Please remove `Pinger.swift` and `PingerTests.swift` too 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6887#-:-O8B97o65vGFgGbiJR7I:br1g8s5)* status: 0 of 3 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
Removed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6887#-:-O8BJ9m03VP_8sykyOb3:bss4a2b)* status: 0 of 5 files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6887#-:-O8BM8J6E7TTdARkGCie:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
