### PR TITLE
Linux DNS

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [ ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/127)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[talpid-core/src/firewall/linux/dns.rs, line 42 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-L9y3kcF55cwZB2WlWy-:-L9y6uqk5uPOWJKOayrH:bqexpml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8eabf848cedc70ba478905ba1cfb132e007c476/talpid-core/src/firewall/linux/dns.rs#L42)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm thinking about this threaded approach. If it works, then it works and is fine. I was just thinking about the complexity and the need for having two separate threads. Maybe you thought about this already and it was deemed not feasible, I don't know.

Did you evaluate the approach taken by the macOS solution for DNS? Where instead of sending events to a common thread the state is shared in a mutex. So `DnsSettings::set_dns` would lock the mutex and do the needed operation instead of sending a message. Similar, the file notification watcher thread would lock the mutex and perform the needed backup operation.

The actual work to read and backup could be in helper functions so it's still in one place, just like now. I don't know if that would reduce the code, but I suspect it might.
</blockquote></details>

Sorry for coming with rather large design ideas so late in the process. But this is what I wanted to highlight on Slack, that we should try to discuss these things, at least two people, before they are implemented.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by jvff** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[talpid-core/Cargo.toml, line 25 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-L9xr_TBDoVxRfikl6t6:-LA-RxuJEwImUELeo_l9:bw0qlrj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8eabf848cedc70ba478905ba1cfb132e007c476/talpid-core/Cargo.toml#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do we need a change that is not published to crates.io yet?
</blockquote></details>

Yeah, the `Display` implementation for the `resolv-conf::Config` type which I upstreamed. Hopefully a new version is released before this is merged :)

---

*[talpid-core/src/firewall/linux/dns.rs, line 42 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-L9y3kcF55cwZB2WlWy-:-LA-Xz0J8XWrTLfxhXop:b-vpklm0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8eabf848cedc70ba478905ba1cfb132e007c476/talpid-core/src/firewall/linux/dns.rs#L42)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Sorry for coming with rather large design ideas so late in the process. But this is what I wanted to highlight on Slack, that we should try to discuss these things, at least two people, before they are implemented.
</blockquote></details>

Yeah, sorry, I was still biased with the DNS refactor architecture. I've simplified it now.

---

*[talpid-core/src/firewall/linux/dns.rs, line 94 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-L9y2J5c9RHhI019rCuP:-LA-Y7OV2x91d9iyxjDR:b-mq3ouw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8eabf848cedc70ba478905ba1cfb132e007c476/talpid-core/src/firewall/linux/dns.rs#L94)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Would this method maybe fit better on `DnsConfigurator` instead of as a static method here? Since it's working on a `DnsConfigurator` rather than being an operation tied to `DnsSettings`.
</blockquote></details>

Yes, good point. However this wasn't necessary because I managed to eliminate the `DnsConfigurator`.

---

*[talpid-core/src/firewall/linux/dns.rs, line 230 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-L9y32Kq6XAv2jq9OjSL:-LA-YF8e2uWnTpxHG1G2:b-eu2ps8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8eabf848cedc70ba478905ba1cfb132e007c476/talpid-core/src/firewall/linux/dns.rs#L230)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

In the approach with a backup state shared with a mutex this would of course not have a `notification_sink` but rather a `state: Arc<Mutex<State>` that the watcher thread would act upon in each event.
</blockquote></details>

I think it's better to treat this as two parts.

Part one: eliminating `DnsWatcher`. This is possible, but I'd rather not. If the watcher thread owns the `RecommendedWatcher`, I wouldn't be able to stop the thread because the `mpsc::Sender` endpoint is owned by a different thread (which, AFAICT is killed when the `RecommendedWatcher` is dropped). My approach was to have the "main" thread own the `DnsWatcher` just so that it indirectly owns a `RecommendedWatcher`, and when the "main" thread drops the `DnsSettings` object it would cascade to dropping the `mpsc::Sender` owned by the background notification thread, forcing the watcher thread to stop.

Part two: using an `Arc<Mutex<State>>`. Done, but I wrapped the `State` in an `Option` type because DNS settings might not be configured at some points (in the beginning or after a reset).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
Reviewed 2 of 3 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[talpid-core/Cargo.toml, line 25 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-L9xr_TBDoVxRfikl6t6:-LACkXV8ANALx8FBzTCf:b5ie2yp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8eabf848cedc70ba478905ba1cfb132e007c476/talpid-core/Cargo.toml#L25)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yeah, the `Display` implementation for the `resolv-conf::Config` type which I upstreamed. Hopefully a new version is released before this is merged :)
</blockquote></details>

I see. That crate has obviously only been used for parsing in files before then, never used to write such files :)

---

*[talpid-core/src/firewall/linux/dns.rs, line 114 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LAClOHMCpMLNyIf276N:-LAClOHMCpMLNyIf276O:b9knmce) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L114)):*
> ```Rust
>     fn start(state: Arc<Mutex<Option<State>>>) -> Result<Self> {
>         let (event_tx, event_rx) = mpsc::channel();
>         let mut watcher = notify::raw_watcher(event_tx).chain_err(|| ErrorKind::WatchResolvConf)?;
> ```

I have a concern about how we monitor the events and which events we trigger a backup on. At the moment we trigger a backup on all types of notify event, right? What if some other process does the equivalent of:
```bash
echo "new config" > /etc/resolv.conf.new
mv /etc/resolv.conf /etc/resolv.conf.backup
mv /etc/resolv.conf.new /etc/resolv.conf
```
We will trigger on both `mv` commands. But if we try to parse `/etc/resolv.conf` after the first one before the second one completed we would fail since the file would not exist. I think this would trigger the "Failed to update DNS ..." error logging, so it would not be critical in any way. Mostly thinking about if it would become a problem and if we should only trigger on certain type of filesystem events.

---

*[talpid-core/src/firewall/linux/dns.rs, line 120 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LACbu1z-cAWaB_u1mXz:-LACbu1z-cAWaB_u1mY-:b-a97ap4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L120)):*
> ```Rust
>             .chain_err(|| ErrorKind::WatchResolvConf)?;
> 
>         thread::spawn(move || Self::event_loop(event_rx, state));
> ```

I feel the design choice in `notify` is strange. To force the events to be sent over a channel. Because that forces any user of the library to have at least two threads. I assume `notify` spawn an internal thread(?). If they accepted a closure instead of a `Sender`, everything could be done in a single thread instead.

One could use the underlying `inotify` crate directly to mitigate that, we only need Linux support anyway. Not that we should do it now probably, having an extra thread is not that expensive. Just noting that it would be possible.

---

*[talpid-core/src/firewall/linux/dns.rs, line 134 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LACe822-YRwVofCA8ev:-LACe822-YRwVofCA8ew:b-4yzo7v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L134)):*
> ```Rust
>                 error!(
>                     "Failed to update DNS state after DNS settings have changed: {}",
>                     error.display_chain()
> ```

Printing error chains usually become nicer if one does:
```rust
let chained_err = error.chain_err(|| "Failed to update DNS state after DNS settings have changed");
error!("{}", chained_err.display_chain());
```
The reason for this is because of how `display_chain` formats the error. With the current code it would print as:
```
Failed to update DNS state after DNS settings have changed: Error: Unable to write to /etc/resolv.conf
Caused by: Permission denied
```
But by chaining the message first and then just printing the chain one get:
```
Error: Failed to update DNS state after DNS settings have changed
Caused by: Unable to write to /etc/resolv.conf
Caused by: Permission denied
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/src/firewall/linux/dns.rs, line 184 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADP1G55_jDAz5-aQr5:-LADP1G55_jDAz5-aQr6:b8vvyx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L184)):*
> ```Rust
> 
> fn write_config(config: &Config) -> Result<()> {
>     write_resolv_conf(&config.to_string()).chain_err(|| ErrorKind::WriteResolvConf)
> ```

When we restore settings we will restore the same settings as the user had (given that `Config` can parse them correctly), but we won't restore the exact order and any comments there was. Since this uses the default display formatting of `Config` and don't restore the original string content itself.

If the user has
```
# My router
nameserver 192.168.0.1
```
We will restore it as just
```
nameserver 192.168.0.1
```

We can go with this for now and and for the alpha and evaluate how this feels. Just wanted to note that this is a possible complaint from users who have manually crafted `/etc/resolv.conf`s.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[talpid-core/Cargo.toml, line 25 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADQ8ZT6kltUz4vQ4zg:-LADQ8ZT6kltUz4vQ4zh:bbkgo0t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/Cargo.toml#L25)):*
> ```TOML
> libc = "0.2.20"
> notify = "4.0"
> resolv-conf = { git = "https://github.com/tailhook/resolv-conf.git" }
> ```

Realized now that you probably want to move both dependencies to a new `[target.'cfg(target_os = "macos")'.dependencies]`. Since that is where they are used, and not all `unix`es.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by jvff** [comment]
There are three "maybe TODOs" in the discussions:

- use `inotify` instead of `notify`;
- keep extra syntax from parsed `resolv.conf` file;
- more specialized handling of notification events.

We should probably discuss if we should document them elsewhere so we don't forget about them.

---

Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[talpid-core/Cargo.toml, line 25 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADQ8ZT6kltUz4vQ4zg:-LADiTtU7Q9dlFsybMUm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/Cargo.toml#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Realized now that you probably want to move both dependencies to a new `[target.'cfg(target_os = "macos")'.dependencies]`. Since that is where they are used, and not all `unix`es.
</blockquote></details>

Done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 114 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LAClOHMCpMLNyIf276N:-LADic5A8iwh4L9l5Yyt:b-sjg24j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L114)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I have a concern about how we monitor the events and which events we trigger a backup on. At the moment we trigger a backup on all types of notify event, right? What if some other process does the equivalent of:
```bash
echo "new config" > /etc/resolv.conf.new
mv /etc/resolv.conf /etc/resolv.conf.backup
mv /etc/resolv.conf.new /etc/resolv.conf
```
We will trigger on both `mv` commands. But if we try to parse `/etc/resolv.conf` after the first one before the second one completed we would fail since the file would not exist. I think this would trigger the "Failed to update DNS ..." error logging, so it would not be critical in any way. Mostly thinking about if it would become a problem and if we should only trigger on certain type of filesystem events.


</blockquote></details>

I think that might make sense. But then again, it should work as is. We could delay handling specific events (e.g., file removed) to see what happens next, but maybe this is better left off for another PR in future that also does a more thorough analysis?

---

*[talpid-core/src/firewall/linux/dns.rs, line 120 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LACbu1z-cAWaB_u1mXz:-LAFe__C1LHF-bDvWpPm:b1xrz9n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L120)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I feel the design choice in `notify` is strange. To force the events to be sent over a channel. Because that forces any user of the library to have at least two threads. I assume `notify` spawn an internal thread(?). If they accepted a closure instead of a `Sender`, everything could be done in a single thread instead.

One could use the underlying `inotify` crate directly to mitigate that, we only need Linux support anyway. Not that we should do it now probably, having an extra thread is not that expensive. Just noting that it would be possible.
</blockquote></details>

I agree completely. Finding that it used an `mpsc` channel was an awkward moment. My guess is that different platforms have different thread usages, and the `mpsc` is the best isolation technique for a cross-platform implementation.

But I fully agree `inotify` should probably be revisited in the future.

---

*[talpid-core/src/firewall/linux/dns.rs, line 134 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LACe822-YRwVofCA8ev:-LAFev0_7Bm51r0TIgS-:b-90ux3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L134)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Printing error chains usually become nicer if one does:
```rust
let chained_err = error.chain_err(|| "Failed to update DNS state after DNS settings have changed");
error!("{}", chained_err.display_chain());
```
The reason for this is because of how `display_chain` formats the error. With the current code it would print as:
```
Failed to update DNS state after DNS settings have changed: Error: Unable to write to /etc/resolv.conf
Caused by: Permission denied
```
But by chaining the message first and then just printing the chain one get:
```
Error: Failed to update DNS state after DNS settings have changed
Caused by: Unable to write to /etc/resolv.conf
Caused by: Permission denied
```
</blockquote></details>

Done, thanks for the tip!

---

*[talpid-core/src/firewall/linux/dns.rs, line 184 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADP1G55_jDAz5-aQr5:-LAFfVIl-IJJRodd9Qez:ber130p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L184)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

When we restore settings we will restore the same settings as the user had (given that `Config` can parse them correctly), but we won't restore the exact order and any comments there was. Since this uses the default display formatting of `Config` and don't restore the original string content itself.

If the user has
```
# My router
nameserver 192.168.0.1
```
We will restore it as just
```
nameserver 192.168.0.1
```

We can go with this for now and and for the alpha and evaluate how this feels. Just wanted to note that this is a possible complaint from users who have manually crafted `/etc/resolv.conf`s.
</blockquote></details>

Yes, definitely. I thought about further extending the `resolv-conf` crate to have better support for this, but I'm afraid it will quickly expand beyond the original scope of the crate (as you said elsewhere, the original purpose was only parsing the file).

I thought about having a `ParsedConfig` type, that can be converted to a `Config`, but would by default be a "syntax" tree of the parsed file (i.e., contains which entries are present, comments, new-lines, etc.). Maybe this is something we can revisit in the future.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-:-LAFg3iA7HEDEgHk6E2n:b-uz5mug)*

**Comment by faern** [comment]
I'm not very much a fan of separate task lists or similar if we can avoid that. In my experience they usually end up forgotten or slowly become outdated. I think that if any of these hypothetical issues turn into actual issues we will find them again and fix them. If they don't turn into real issues they are just mental overhead to have in some list of things to maybe fix. And they will never be closed because there is usually no clear event that marks "now we have proved this will never be a real issue".

We have them documented in this PR, which is why I decided to post about them in the first place :)

---

Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[talpid-core/Cargo.toml, line 25 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADQ8ZT6kltUz4vQ4zg:-LAHRqHb4v_qcy_a5Nzj:b-orttzv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/Cargo.toml#L25)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I realize now that I invalidly wrote `target_os = "macos"` and not `"linux"`. But you figured that out :)

---

*[talpid-core/src/firewall/linux/dns.rs, line 114 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LAClOHMCpMLNyIf276N:-LAHSCp0Eq6zqCdAmuzO:bsgdiin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L114)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think that might make sense. But then again, it should work as is. We could delay handling specific events (e.g., file removed) to see what happens next, but maybe this is better left off for another PR in future that also does a more thorough analysis?
</blockquote></details>

Yes we can keep current functionality for at least the alpha and see how well it works when people get to test it :+1:

---

*[talpid-core/src/firewall/linux/dns.rs, line 184 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADP1G55_jDAz5-aQr5:-LAHSkr4EEAiiVbgsG1H:b-j505pt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L184)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yes, definitely. I thought about further extending the `resolv-conf` crate to have better support for this, but I'm afraid it will quickly expand beyond the original scope of the crate (as you said elsewhere, the original purpose was only parsing the file).

I thought about having a `ParsedConfig` type, that can be converted to a `Config`, but would by default be a "syntax" tree of the parsed file (i.e., contains which entries are present, comments, new-lines, etc.). Maybe this is something we can revisit in the future.
</blockquote></details>

Parsing is very hard. We have previously tried to avoid it in other scenarios. Doing parsing -> format again is very likely to never work 100% correctly. And I don't see any gain in trying to be so advanced. On could just back up the verbatim text version of the file and restore that directly? At least in most cases. It does not work where some other software merge settings with ours.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-:-LAHTY9M4eusUyLRda8k:brlehkl)*

**Comment by faern** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[talpid-core/Cargo.toml, line 23 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LAHxfkX-QjCAT0oC8bR:-LAHxfkX-QjCAT0oC8bS:b-r80wra) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/122e136f96e93df0e459aecb2aa14e53b0521fd1/talpid-core/Cargo.toml#L23)):*
> ```TOML
> 
> [target.'cfg(unix)'.dependencies]
> libc = "0.2.20"
> ```

I see that we depend on `libc` specifically for `unix` and then for `windows` separately. In other words, we depend on `libc` on all platforms. Could you simplify this by moving it to the generic `[dependencies]` section here? So we don't have to create a separate PR for just that :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by jvff** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[talpid-core/Cargo.toml, line 23 at r3](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LAHxfkX-QjCAT0oC8bR:-LAHzh1Q8io2ztK9NAHa:b-1eh3wi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/122e136f96e93df0e459aecb2aa14e53b0521fd1/talpid-core/Cargo.toml#L23)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I see that we depend on `libc` specifically for `unix` and then for `windows` separately. In other words, we depend on `libc` on all platforms. Could you simplify this by moving it to the generic `[dependencies]` section here? So we don't have to create a separate PR for just that :)
</blockquote></details>

Sure, done.

---

*[talpid-core/src/firewall/linux/dns.rs, line 184 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-LADP1G55_jDAz5-aQr5:-LAI-6O28RImePbwlRsF:b-8h1bof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbe7c45731b03885d127fa486e7d2839292a2565/talpid-core/src/firewall/linux/dns.rs#L184)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Parsing is very hard. We have previously tried to avoid it in other scenarios. Doing parsing -> format again is very likely to never work 100% correctly. And I don't see any gain in trying to be so advanced. On could just back up the verbatim text version of the file and restore that directly? At least in most cases. It does not work where some other software merge settings with ours.
</blockquote></details>

Saving the contents of the file in a `String` isn't too hard. The only problem is collecting file updates into the backup. Leave as is for now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Comment by faern** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127#-:-LAIAtsNEyHLm_eue1Ep:bnfp4nl)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/127)*

**Pull request merged**
