### PR TITLE
Rename tests to new format

### PR DESCRIPTION
**Pull request by Rawa**
This PR migrates all non-android tests to the [kotlin convention way of naming test methods](https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods)

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 12 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: 12 of 36 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA0mWB8JSFm0sUsiTc:-NrA0mWB8JSFm0sUsiTd:b9tw5n5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt#L17)):*
> ```Kotlin
> import org.junit.jupiter.api.Test
> 
> class PlayPaymentUseCaseTest {
> ```

There's a mix of test names starting with `given` and some starting with the the function name itself. Can that be unified? Also, in my experience "given" is usually used to reflect the starting state of the test rather than the action itself. If we don't see a need include a clear explanation of the starting state as part of the test name, I believe it's better to skip it and therefore changing names such as `given invocation of myFunction ...` to something like `myFunction invocation ...` or `myFunction call ...`. "call" might be preferred since it helps shorten the test name. 

For example, the following test:
`given invocation of queryPaymentAvailability paymentAvailability should emit updated paymentAvailability`

Can instead be written as:
`queryPaymentAvailability call should result in updated paymentAvailablity`
or
`queryPaymentAvailability invocation should result in updated paymentAvailablity`
or
`queryPaymentAvailability invocation should result in paymentAvailablity emitting updated paymentAvailability`
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA-ojS5CEdCEr3MCNR:-NrA-ojS5CEdCEr3MCNS:b-ual1e3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt#L59)):*
> ```Kotlin
> 
>     @Test
>     fun `purchaseProduct should invoke purchaseProduct on repository`() = runTest {
> ```

nit: I suggest clarifying in the test name that this is a function call rather than some type of data structure.

I suggest the following:
`purchaseProduct call should invoke purchaseProduct on repository`
or
`purchaseProduct invocation should invoke purchaseProduct on repository`

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 35 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: all files reviewed, 7 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA0Azf2AW1bO2vn3CX:-NrA0Azf2AW1bO2vn3CY:b-qdno92) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt#L58)):*
> ```Kotlin
> 
>     @Test
>     fun `comparator should be able to name of only handle numbers`() {
> ```

Maybe better with "comparator should be able to **handle** name of only ~handle~ numbers"
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA3_D20aykJj_wyWX5:-NrA3_D20aykJj_wyWX6:b-3g7tb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L96)):*
> ```Kotlin
> 
>     @Test
>     fun `given successful createAccount side effect of NavigateToWelcome`() = runTest {
> ```

Is probably more readable like this:
"given successful **.account creation ** should result in side effect of NavigateToWelcome"
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA4ZFOC-sgCBao15J1:-NrA4ZFOC-sgCBao15J2:b-1kx59) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L89)):*
> ```Kotlin
> 
>     @Test
>     fun `given includedApps and excludedApps returns sets uiState should include the lists`() =
> ```

Maybe change to "should include both"?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA4rxI9j7DBZltbpL3:-NrA4rxI9j7DBZltbpL4:bc22c7o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L118)):*
> ```Kotlin
> 
>     @Test
>     fun `given SettingsRepository emits Constraint Only 99 uiState should custom and selectedWireguardPort 99`() =
> ```

Should we have numbers in tests? Maybe be a bit more generic, such as "emits Port" and "selectedWireguardPort with the same value" ?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA5GOGBzbfTUJDavYj:-NrA5GOGBzbfTUJDavYk:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L142)):*
> ```Kotlin
> 
>     @Test
>     fun `onWireguardPortSelected with 99 should invoke updateSelectedWireguardConstraint with Constraint Only 99`() =
> ```

See above

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 5 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: all files reviewed, 8 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA0mWB8JSFm0sUsiTc:-NrA7h4ZE7-badYLb5aC:b-ypvw37) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There's a mix of test names starting with `given` and some starting with the the function name itself. Can that be unified? Also, in my experience "given" is usually used to reflect the starting state of the test rather than the action itself. If we don't see a need include a clear explanation of the starting state as part of the test name, I believe it's better to skip it and therefore changing names such as `given invocation of myFunction ...` to something like `myFunction invocation ...` or `myFunction call ...`. "call" might be preferred since it helps shorten the test name. 

For example, the following test:
`given invocation of queryPaymentAvailability paymentAvailability should emit updated paymentAvailability`

Can instead be written as:
`queryPaymentAvailability call should result in updated paymentAvailablity`
or
`queryPaymentAvailability invocation should result in updated paymentAvailablity`
or
`queryPaymentAvailability invocation should result in paymentAvailablity emitting updated paymentAvailability`
</blockquote></details>

To continue on this one, adding "call" or "invocation" is probably only necessary in cases where it's not clear that the initial "word"/"phrase" is a function name, so the above can probably be similified to: `queryPaymentAvailability should result in updated paymentAvailablity`
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/PaymentViewModelTest.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA5v_a0hVO5FeFVwLE:-NrA5v_a0hVO5FeFVwLF:b-bvllfc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/PaymentViewModelTest.kt#L60)):*
> ```Kotlin
> 
>     @Test
>     fun `given purchaseResult emits Success uiState should return success dialog data`() = runTest {
> ```

I believe this test can be clarified/simplified to something like: `purchaseResult emitting Success should result in success dialog state`

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: 18 of 39 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA0Azf2AW1bO2vn3CX:-NrAkRTLB_cZjO5GqI5h:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt#L58)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe better with "comparator should be able to **handle** name of only ~handle~ numbers"
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA0mWB8JSFm0sUsiTc:-NrZa2Va7mVaGd2oCKIF:b4ub2ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

To continue on this one, adding "call" or "invocation" is probably only necessary in cases where it's not clear that the initial "word"/"phrase" is a function name, so the above can probably be similified to: `queryPaymentAvailability should result in updated paymentAvailablity`
</blockquote></details>

We'd a internal discussion offline, I've now updated most of the test to include this simplification.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA-ojS5CEdCEr3MCNR:-NrZaMzO8zrg5MfH508S:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt#L59)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest clarifying in the test name that this is a function call rather than some type of data structure.

I suggest the following:
`purchaseProduct call should invoke purchaseProduct on repository`
or
`purchaseProduct invocation should invoke purchaseProduct on repository`
</blockquote></details>

Fixed
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA3_D20aykJj_wyWX5:-NrZaYEYALBPPe8LRt0r:b-cbgjh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L96)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is probably more readable like this:
"given successful **.account creation ** should result in side effect of NavigateToWelcome"
</blockquote></details>

Simplified it a bit, I believe it is more clear now :)
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/PaymentViewModelTest.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA5v_a0hVO5FeFVwLE:-NrZahmJ1R49jrQxhkfK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/PaymentViewModelTest.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe this test can be clarified/simplified to something like: `purchaseResult emitting Success should result in success dialog state`
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA4ZFOC-sgCBao15J1:-NrZailc4pFfqzDTdOZs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt#L89)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe change to "should include both"?
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA4rxI9j7DBZltbpL3:-NrZb6se-iJYGzyV1IZt:b632nav) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L118)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should we have numbers in tests? Maybe be a bit more generic, such as "emits Port" and "selectedWireguardPort with the same value" ?
</blockquote></details>

I think you are correct, I've removed it
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrA5GOGBzbfTUJDavYj:-NrZb9BLBGCxSS1AmlRs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59257eb328455fb6d7177a990e715fdd3c50c8d5/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt#L142)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZhDr83WDtlRtEhids:-NrZhDr83WDtlRtEhidt:bwhauqh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0470399cd63bbc48aebe3519a3d517034c322df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L15)):*
> ```Kotlin
> import androidx.compose.material3.Icon
> import androidx.compose.material3.IconButton
> import androidx.compose.material3.ListItem
> ```

Is this needed?
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/JUnitTest.kt` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZiBaBDFFR7gefi4nr:-NrZiBaBDFFR7gefi4ns:bg86mxs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0470399cd63bbc48aebe3519a3d517034c322df/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/JUnitTest.kt#L58)):*
> ```Kotlin
> 
>     companion object {
>         private val ignoredTestPackages =
> ```

Maybe there should be some kind of explanation why this is ignored?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: 37 of 39 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/JUnitTest.kt` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZiBaBDFFR7gefi4nr:-NrZjyti9k-eSxhtqVKk:b4wcbb8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0470399cd63bbc48aebe3519a3d517034c322df/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/JUnitTest.kt#L58)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe there should be some kind of explanation why this is ignored?
</blockquote></details>

Good idea, I've clarified it
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZhDr83WDtlRtEhids:-NrZjv6W3RVw7vL5E6RZ:bepcxva) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0470399cd63bbc48aebe3519a3d517034c322df/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L15)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Woops, fixed!

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 36 files at r1, 15 of 21 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: all files reviewed, 12 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt` line 79 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZtpTx-OY-vc7I0eCL:-NrZtpTx-OY-vc7I0eCM:b-db1rwc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/PlayPaymentUseCaseTest.kt#L79)):*
> ```Kotlin
> 
>     @Test
>     fun `on resetPurchaseResult call purchaseResult should emit null`() = runTest {
> ```

nit: is there a reason for this function to start with `on ...` whereas the other functions doensn't?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/TunnelStateNotificationUseCaseTest.kt` line 64 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZmw1t5LU9M-BpBk4a:-NrZmw1t5LU9M-BpBk4b:b7ohyz6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/TunnelStateNotificationUseCaseTest.kt#L64)):*
> ```Kotlin
> 
>     @Test
>     fun `given TunnelState is error use case should emit TunnelStateError notification`() =
> ```

`given` -> `when` ?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt` line 64 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZv-gw0v1cQHLBbjtf:-NrZv-gw0v1cQHLBbjtg:b2jq3lx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt#L64)):*
> ```Kotlin
> 
>     @Test
>     fun `uiState should return UNKNOWN when service connection state is Disconnected`() = runTest {
> ```

This naming is a bit different from many other vm tests. I'm not saying one is better than the other, but would be good to keep it consistent imo.

For example this one could be written as:
`when service connection state is Disconnected then uiState should emit UNKNOWN`
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt` line 64 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZvDKAEFqBmM_k_5b_:-NrZvDKAEFqBmM_k_5ba:b-k1cyef) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt#L64)):*
> ```Kotlin
> 
>     @Test
>     fun `uiState should return UNKNOWN when service connection state is Disconnected`() = runTest {
> ```

nit: `return` -> `emit`?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZwFMnDVAh6-GSF2_O:-NrZwFMnDVAh6-GSF2_P:b-2fmpv9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L69)):*
> ```Kotlin
> 
>     @Test
>     fun `login call should result in uiState with NoInternetConnection when no internet`() =
> ```

In this one the `when no internet` part is in the arrange section and a prerequisite for the test, so I believe it's a typical thing to include in the beginning of the test name as a "given" thing. 

For example theses test names would be more readable and better match the test imo:

`given no internet when login is attempted then uiState should emit NoInternetConnection`
or
`given no internet when login is called then uiState should emit NoInternetConnection`
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 113 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZy3nyEjKnov3Z5QJ4:-NrZy3nz3r6OslkuQtwE:bpya7cm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L113)):*
> ```Kotlin
> 
>     @Test
>     fun `given login call returns Ok uiSideEffect should emit NavigateToConnect`() = runTest {
> ```

Is this referring to the vm or repo? :thinking: Might be good to clarify that somehow. Same applies to other tests in this class.



_Code quote:_
```Kotlin
login call
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt` line 113 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZnNtb8KYr3EgQ9iZP:-NrZnNtb8KYr3EgQ9iZQ:b8v4zek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt#L113)):*
> ```Kotlin
> 
>     @Test
>     fun `on onSitePaymentClick call uiSideEffect should emit OpenAccountView`() = runTest {
> ```

nit: here the function names starts with `on onSitePaymentClick ...` whereas further down it's just `onDisconnectClick ...`. Would be nice to keep it consistent.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ReportProblemViewModelTest.kt` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZnynr9hHaPXWeKV8t:-NrZnynr9hHaPXWeKV8u:bmy5tjs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ReportProblemViewModelTest.kt#L48)):*
> ```Kotlin
> 
>     @Test
>     fun `when sendReport returns CollectLog error uiState should emit sendingState with CollectLog error`() =
> ```

Tbh I find it a bit hard to read something like below without something separating the sections of the statement (between `error` and `uiState`):

`... returns CollectLog error uiState should ...`


Two suggestions on how the readability can be a bit improved:

`... returns CollectLog error, uiState should ...`
or
`... returns CollectLog error then uiState should ...`


This comment also applies to more functions than this specific one.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZymqj-8uoFkbjLdWz:-NrZymqj-8uoFkbjLdX-:b-s2rcax) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt#L81)):*
> ```Kotlin
> 
>     @Test
>     fun `uiState should by default emit Loading state`() = runTest {
> ```

Other similar tests end with `... by default`. For example: `uiState should emit Loading state by default`



_Code quote:_
```Kotlin
uiState should by default emit Loading state
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 31 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZzVTp1k8zGinWCySX:-NrZzVTp1k8zGinWCySY:bvvftqu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L31)):*
> ```Kotlin
> 
> @ExtendWith(TestCoroutineRule::class)
> class VoucherDialogViewModelTest {
> ```

nit: the tests in this class are a bit inconsistent:
`onRedeem should`
`on onRedeem call with`
`on onRedeem with`

I've seen this in a some other places as well, so would be probably be a good idea to go through and make sure its consistent throughout this pr

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-:-Nr_5aamDAkt3dd0JZVf:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: 24 of 39 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZwFMnDVAh6-GSF2_O:-Nra151AA6CK2_vcXIn6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L69)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

In this one the `when no internet` part is in the arrange section and a prerequisite for the test, so I believe it's a typical thing to include in the beginning of the test name as a "given" thing. 

For example theses test names would be more readable and better match the test imo:

`given no internet when login is attempted then uiState should emit NoInternetConnection`
or
`given no internet when login is called then uiState should emit NoInternetConnection`
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 113 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZy3nyEjKnov3Z5QJ4:-Nra1yBz4B03hgKTLSO6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L113)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this referring to the vm or repo? :thinking: Might be good to clarify that somehow. Same applies to other tests in this class.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ReportProblemViewModelTest.kt` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZnynr9hHaPXWeKV8t:-Nra4N-y1tp6qUmdaEAA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ReportProblemViewModelTest.kt#L48)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Tbh I find it a bit hard to read something like below without something separating the sections of the statement (between `error` and `uiState`):

`... returns CollectLog error uiState should ...`


Two suggestions on how the readability can be a bit improved:

`... returns CollectLog error, uiState should ...`
or
`... returns CollectLog error then uiState should ...`


This comment also applies to more functions than this specific one.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-NrZymqj-8uoFkbjLdWz:-Nra4_Ew5C5MlutMc_0I:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ee8aadadeb013f85608c064a9b4b488240cf577/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt#L81)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Other similar tests end with `... by default`. For example: `uiState should emit Loading state by default`
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 21 files at r2, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838#-:-NrdfoDhEmkTDM0v6Pod:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
