### PR TITLE
Update windows build script

### PR DESCRIPTION
**Pull request by mvd-ows**
What the commits say, and also:

Fixes cleaning of binaries in the Windows build script. I noticed this had been broken for some time.
Fixes calling the Windows build script and forwarding the `--dev-build` flag. This broke the other day when `build.sh` was updated with `set -e`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @pinkisemils and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257)*

**Comment by faern** [comment]
Need to update script name in the AppVeyor config as well.

---

Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @pinkisemils and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257#-:-LG5sVWaBIuFYlUPC_gK:b-67e1rl)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257)*

**Comment by mvd-ows** [comment]
Good catch. Done.

---







*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257#-:-LG9YIS7DLUoo94clToD:boj1qgt)*

**Comment by faern** [comment]
Not me, AppVeyor catched it  :wink: 
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed, all discussions resolved (waiting on @pinkisemils and @faern)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257#-:-LG9qHDME6uf2yPf4oZd:b-bekqku)*

**Comment by pronebird** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: 2 of 3 files reviewed, all discussions resolved (waiting on @pinkisemils, @faern, and @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed, all discussions resolved (waiting on @pinkisemils, @faern, and @pronebird)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257#-:-LG9tSwS46ZQnddOj5A_:bnfp4nl)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/257)*

**Pull request merged**
