### PR TITLE
Introduce LocationDataSource

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Introduce a custom `LocationDataSource` to animate the relay list. Makes dependency on `TableViewDiffableDataSource` obsolete.
2. Make a sticky header view in "Select Location" controller and make it look similar to what we have on desktop
3. Make it possible to browse the sub-trees with all inactive relays.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/CustomNavigationBar.swift, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVw-UDN6HmcclFzsIQO:-MVw-UDN6HmcclFzsIQP:b-x4j0g3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/CustomNavigationBar.swift#L20)):*
> ```Swift
> 
>     // Returns the distance from the title label to the bottom of navigation bar
>     var titleLabelBottomInset: CGFloat {
> ```

Visually this looks as following, this code calculates the distance marked with the red line and then basically adjusts the title label margin so that the light green lines are of equal height.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/LocationDataSource.swift, line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVw0Zr43gHXrVuXypnT:-MVw0Zr43gHXrVuXypnU:b-7opi1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/LocationDataSource.swift#L184)):*
> ```Swift
>         }
> 
>         let numAffectedChildren = topNode.countChildrenRecursive { (node) -> Bool in
> ```

FYI Basically in order to understand how many rows to insert in order to expand the level, I have to count the number of children that will become visible after expansion. Then update data source and tell the table view to insert the certain number of rows at position. Same goes in reverse when collapsing the level.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/SelectLocationCell.swift, line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVw3xpx8q0c8qCbiGSE:-MVw3xpx8q0c8qCbiGSF:baitt21) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationCell.swift#L120)):*
> ```Swift
>             locationLabel.bottomAnchor.constraint(equalTo: contentView.layoutMarginsGuide.bottomAnchor),
> 
>             collapseButton.widthAnchor.constraint(equalToConstant: UIMetrics.contentLayoutMargins.left + UIMetrics.contentLayoutMargins.right + 24),
> ```

FYI Magic number 24 is the size of image.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/SelectLocationHeaderView.swift, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVzKuZvEcEifjOsi9V4:-MVzKuZvEcEifjOsi9V5:b-5hn479) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationHeaderView.swift#L41)):*
> ```Swift
> 
>         let trailingConstraint = textContentLabel.trailingAnchor.constraint(equalTo: contentView.layoutMarginsGuide.trailingAnchor)
>         trailingConstraint.priority = UILayoutPriority(800)
> ```

FYI I had to make these constraints breakable because sometimes when the view is created with zero frame, the `UILayoutPriority.required` (1000) level constraints cannot be satisfied, which cause the UIKit to dump errors in the console. 

`800` priority is used to take precedence about the intrinsic content size which has 775 priority and no constant defined in UIKit.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVzMOAi8MbnD0oV46E5:-MVzMOAi8MbnD0oV46E6:b-tctcal) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L12)):*
> ```Swift
> import Logging
> 
> class SelectLocationViewController: UIViewController, RelayCacheObserver, UITableViewDelegate {
> ```

FYI I switched to standard `UIViewController` vs. `UITableViewController` because the latter calls `reloadData` on `viewWillAppear` which caused quite a lot of issues with scrolling to selected relay from `viewWillAppear` and besides that we call `reloadData` in the `LocationDataSource`.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVzMfkH3pi6V3SubCSx:-MVzMfkH3pi6V3SubCSy:b43eg1o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L114)):*
> ```Swift
>         isViewAppeared = true
> 
>         tableView.flashScrollIndicators()
> ```

FYI based on docs, `UITableViewController` flashes scroll indicators on `viewDidAppear`, so we do the same here.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVzNCcf-ZdhWcGec4lO:-MVzNCcf-ZdhWcGec4lP:b-xj28mh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L112)):*
> ```Swift
>         super.viewDidAppear(animated)
> 
>         isViewAppeared = true
> ```

FYI `viewWillAppear` can be fired multiple times since user can drag the view controller down to dismiss it. The user can also change his intention and cancel the dismissal. So that' why I use the `isViewAppeared` flag.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 104 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVzOARqDisdGsznfQ0g:-MVzOARqDisdGsznfQ0h:bo0lpf2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L104)):*
> ```Swift
>         super.viewWillAppear(animated)
> 
>         if let indexPath = dataSource?.indexPathForSelectedRelay(), scrollToSelectedRelayOnViewWillAppear, !isViewAppeared {
> ```

`isViewAppeared` makes sure that we only scroll to the selected relay the first time the view is about to appear on screen.

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/CustomNavigationBar.swift, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWEq221Em9mHPJgaDl-:-MWEq2225lhatVoSEfOY:b-6eco6d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/CustomNavigationBar.swift#L53)):*
> ```Swift
> 
>         setOpaqueBackgroundAppearance(prefersOpaqueBackground)
>     }
> ```

Shouldn't `commonInit` still be called?
___
*[ios/MullvadVPN/SelectLocationCell.swift, line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVw3xpx8q0c8qCbiGSE:-MW615NB67NQKW2wT1rN:b-f6rj0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationCell.swift#L120)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI Magic number 24 is the size of image.
</blockquote></details>

Nit: Would it make sense to make it a constant or adding a comment? Or maybe creating a local variable where the name expresses the intent, like `chevronWidth` or something?
___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 231 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWF3TEI5jSXpqDfXqQJ:-MWF3TEJ4beMlzRobRXw:buzm64p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L231)):*
> ```Swift
>     // MARK: - Private
> 
>     private func showChildrenForRelayLocation(_ relayLocation: RelayLocation, animated: Bool, completion: (() -> Void)? = nil) {
> ```

I think I missed something here. Maybe I got confused with the name? When I read `showChildrenForRelayLocation`, I was expecting to see something like "country expands to show cities" and "city expands to show relays".

But from what I understood of the code this seems more like `showParentsForRelayLocation`? Or am I misunderstanding something?

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/LocationDataSource.swift, line 355 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWGIw3u5u_GjVRwkBk4:-MWGIw3x8f0OworMQtA7:baueptt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/LocationDataSource.swift#L355)):*
> ```Swift
>                     node.computeActiveChildrenRecursive()
>                     if node.isActive && !hasActiveChild {
>                         hasActiveChild = true
> ```

FYI: Not sure if this is a good suggestion, but you could do something like:

```
switch nodeType {
case .root, .country:
    for node in children {
        node.computeActiveChildrenRecursive()
    }
    fallthrough
case .city:
    isActive = children.first(where: { $0.isActive }) != nil
case .relay:
    break
}
```

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/CustomNavigationBar.swift, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWEq221Em9mHPJgaDl-:-MWNryEu0ld5amo8J_qi:buwio75) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/CustomNavigationBar.swift#L53)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Shouldn't `commonInit` still be called?
</blockquote></details>

Thanks. I have abandoned the `commonInit` and forgot to remove it. This is fixed now.
___
*[ios/MullvadVPN/LocationDataSource.swift, line 355 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWGIw3u5u_GjVRwkBk4:-MWNsYl703Iv3mEyOn8f:b-jzbjwr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/LocationDataSource.swift#L355)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

FYI: Not sure if this is a good suggestion, but you could do something like:

```
switch nodeType {
case .root, .country:
    for node in children {
        node.computeActiveChildrenRecursive()
    }
    fallthrough
case .city:
    isActive = children.first(where: { $0.isActive }) != nil
case .relay:
    break
}
```
</blockquote></details>

I think it's a good suggestion. Fixed.
___
*[ios/MullvadVPN/SelectLocationCell.swift, line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MVw3xpx8q0c8qCbiGSE:-MWNu_th5ZRsVNUelaYb:bis0m37) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationCell.swift#L120)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Would it make sense to make it a constant or adding a comment? Or maybe creating a local variable where the name expresses the intent, like `chevronWidth` or something?
</blockquote></details>

Agree. Done.
___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 231 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWF3TEI5jSXpqDfXqQJ:-MWNw1g-0Uvv4BDIvuBU:b-vlscyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L231)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think I missed something here. Maybe I got confused with the name? When I read `showChildrenForRelayLocation`, I was expecting to see something like "country expands to show cities" and "city expands to show relays".

But from what I understood of the code this seems more like `showParentsForRelayLocation`? Or am I misunderstanding something?
</blockquote></details>

You're right. This code actually expands the parent nodes instead of child nodes. I have fixed this in two ways:

1. Rename it to `showParents`
2. Move this code to `LocationDataSource` and add a flag `showHiddenParents` on the `setSelectedRelayLocation`.  It makes more sense this way because 
3. Rename `showChildrenHelper` to `toggleChildrenInternal` because it takes the flag argument that says `show` so if it's `false`, then it's more of a function to hide children, so I think `toggle` makes sense in that case. ps: I have used "Internal" before, instead of "Helper", so I figured it would be better for consistency.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/SelectLocationViewController.swift, line 231 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-MWF3TEI5jSXpqDfXqQJ:-MWO23jU0R9SNQeLMRHK:b7zeu54) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c2ea289af631c54484aa40fde325d86737abbea/ios/MullvadVPN/SelectLocationViewController.swift#L231)):*
> Move this code to LocationDataSource and add a flag showHiddenParents on the setSelectedRelayLocation.  It makes more sense this way because

... because `LocationData` already offers all functions to show and hide children, so adding the argument to show parents when selecting location looks logical.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582#-:-MWPGylm67zs0H5IBos6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
