### PR TITLE
Implement UI for custom DNS servers on Android

### PR DESCRIPTION
**Pull request by jvff**
This PR continues the work on custom DNS support on Android by adding the UI to configure custom DNS servers.

The Advanced screen is now a custom `RecyclerView`, where the previous screen contents are now part of the header item of the list, and the list items are provided by the `CustomDnsAdapter`. This allows the title collapse animation to continue working with the new layout.

The custom DNS items can be added by a row at the end of the list, and the address can be confirmed using the tick button. Pressing an already configured DNS server allows the user to change it, and it's possible to remove the DNS server by pressing the X icon.

All of these operations use standard list animations provided by Android, but require a "state cache" in the adapter to work, because a full refresh cancels all animations. Therefore, the changes are first done to the cache, and then applied to the daemon. The daemon then sends the updated actual configuration, and as long as it's the same as the cached one, the animation will run to the end as expected.

Invalid IP addresses aren't added, and the text becomes red to show that. Android considers some IP addresses as invalid (like loopback addresses), so they aren't allowed to be used (otherwise they crash the app when setting up the tunnel). A future PR will make sure that any invalid addresses that we don't know about are handled correctly.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 14 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)* status: 14 of 19 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt, line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331#-MNz5zLI7yX0PSB7WrlS:-MNz5zLJ7K3_iIoKJDsv:b-wmz8qg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/775be02809c36e6193099cb48ecc53231b9251ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt#L13)):*
> ```Kotlin
> 
>     var serverAddress by observable<InetAddress?>(null) { _, _, hostNameAndAddressText ->
>         val hostNameAndAddress = hostNameAndAddressText.toString().split('/', limit = 2)
> ```

What's with the slashes here? Wouldn't the hostnames be entered as is?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @jvff)

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt, line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331#-MNz5zLI7yX0PSB7WrlS:-MO1WnolAaLM6XEp_zql:bgifa11) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/775be02809c36e6193099cb48ecc53231b9251ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt#L13)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What's with the slashes here? Wouldn't the hostnames be entered as is?
</blockquote></details>

They're entered and stored as IP addresses, but Java's `InetAddress` type always prints itself when converting to a `String` as `hostname/IP address`, even though it's _just_ an IP address :roll_eyes:

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt, line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331#-MNz5zLI7yX0PSB7WrlS:-MO1zd8r9g6uZdfqLdxR:b-8obqsp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/775be02809c36e6193099cb48ecc53231b9251ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

They're entered and stored as IP addresses, but Java's `InetAddress` type always prints itself when converting to a `String` as `hostname/IP address`, even though it's _just_ an IP address :roll_eyes: 
</blockquote></details>

This seems to be done an awful lot, it'd be better to just have a specific function or maybe an extension of InetAddress to have it be a method. Reading this head-scratcher multiple times is not great. Aside from that, the code looks fine!

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)* status: 17 of 20 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt, line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331#-MNz5zLI7yX0PSB7WrlS:-MO87xlu-dVMpjwVmtSZ:b-2hz0hz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/775be02809c36e6193099cb48ecc53231b9251ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt#L13)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This seems to be done an awful lot, it'd be better to just have a specific function or maybe an extension of InetAddress to have it be a method. Reading this head-scratcher multiple times is not great. Aside from that, the code looks fine!
</blockquote></details>

Done. Wasn't sure about the name though. Should it be `toStringWithoutHostname`?

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331#-:-MO8kwEoBBBdsYQJVbuc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt, line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331#-MNz5zLI7yX0PSB7WrlS:-MO8kimZ4ZDoloGzE1Ie:b-hsy0b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/775be02809c36e6193099cb48ecc53231b9251ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsServerHolder.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. Wasn't sure about the name though. Should it be `toStringWithoutHostname`?
</blockquote></details>

I think the current one is good.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2331)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
