### PR TITLE
Consolidate iOS rust code into a single crate

### PR DESCRIPTION
**Pull request by pinkisemils**
To simplify (and speedup) the build process for the iOS app, the FFI for all of our rust code will now be accessed through a single crate and a single static library. This also enables the app to use a single tokio runtime per process.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458)

### CODE REVIEW

**Review by acb-mv — APPROVED** [review]
> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadRustRuntime/include/mullvad_rust_runtime.h` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1WrsdiB9NK0rWxS_NH:-O1WrsdiB9NK0rWxS_NI:b-mnkdkc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/ios/MullvadRustRuntime/include/mullvad_rust_runtime.h#L101)):*
> ```objc
>                                          const uint8_t *raw_preshared_key,
>                                          const uint8_t *raw_ephemeral_private_key);
> ```

A minor suggestion: maybe add a barrier comment saying that this is where shadowsocks begins, i.e., something like:



_Code snippet:_
```objc
//
// --- Shadowsocks
//
```

**Review by hulthe — COMMENTED** [review]
> Reviewed 5 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadRustRuntime/include/mullvad_rust_runtime.h` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1X-nKvEfJS9S8EMNA-:-O1X-nKvEfJS9S8EMNA0:bwkm3j3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/ios/MullvadRustRuntime/include/mullvad_rust_runtime.h#L1)):*
> ```objc
> #include <stdarg.h>
> ```

Is this file generated by `mullvad-ios/build.rs`? Could be worth adding a "[warning, autogenerated](https://docs.rs/cbindgen/latest/cbindgen/struct.Config.html#structfield.autogen_warning)" header here.

**Review by hulthe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1X4JqgEr-YLcuROWEt:-O1X4JqhB7aUPvemtQtm:bv9cn2l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L89)):*
> ```XML
> 
>     pub fn run(self) {
>         let runtime = mullvad_ios_runtime().expect("Could not get tokio runtime");
> ```

This is probably waaay out of scope but we might want to check so we don't panic unwind anywhere across the ffi.

**Review by hulthe — CHANGES_REQUESTED** [review]
> Reviewed 26 of 56 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458)* status: all files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-ios/src/shadowsocks_proxy/bin/run.rs` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1XRrTOCsi_Kq-HEafv:-O1XRrTOCsi_Kq-HEafw:b-afh4sq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/mullvad-ios/src/shadowsocks_proxy/bin/run.rs#L1)):*
> ```XML
> use std::{net::SocketAddr, str::FromStr};
> ```

I thought bins had to be placed in `/src/bin`?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458)* status: 45 of 56 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @hulthe)

___
*[`ios/MullvadRustRuntime/include/mullvad_rust_runtime.h` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1X-nKvEfJS9S8EMNA-:-O1q21Xk7JB_paQXbobT:b-8e2sgs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/ios/MullvadRustRuntime/include/mullvad_rust_runtime.h#L1)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Is this file generated by `mullvad-ios/build.rs`? Could be worth adding a "[warning, autogenerated](https://docs.rs/cbindgen/latest/cbindgen/struct.Config.html#structfield.autogen_warning)" header here.
</blockquote></details>

It is auto-generated, and thus it might be a pain to add that header since it's regenerated on every build. The only reason it is in git is because Xcode won't attempt to run the build if the header isn't even there.
___
*[`ios/MullvadRustRuntime/include/mullvad_rust_runtime.h` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1WrsdiB9NK0rWxS_NH:-O1q2Aol1iBeOaTZhE6F:b5ltpyx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/ios/MullvadRustRuntime/include/mullvad_rust_runtime.h#L101)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

A minor suggestion: maybe add a barrier comment saying that this is where shadowsocks begins, i.e., something like:
</blockquote></details>

Since it is autogenerated, the comments are lifted straight from the rust code.
___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1X4JqgEr-YLcuROWEt:-O1ved2fExa7LPkJZBPr:b-57wym3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L89)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

This is probably waaay out of scope but we might want to check so we don't panic unwind anywhere across the ffi.
</blockquote></details>

It really is not out of scope at all. I've changed it so that the FFI call returns an error early, and the handle to the runtime is passed down here.
___
*[`mullvad-ios/src/shadowsocks_proxy/bin/run.rs` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1XRrTOCsi_Kq-HEafv:-O1q2HJ85FHe2gbO11qC:bw6s5zf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/mullvad-ios/src/shadowsocks_proxy/bin/run.rs#L1)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

I thought bins had to be placed in `/src/bin`?
</blockquote></details>

This is a test binary, we probably don't want it here at all.

**Review by hulthe — APPROVED** [review]
:lgtm:

> Reviewed 7 of 56 files at r1, 11 of 11 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-:-O1vrk0W58C7So3AP8dX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6458#-O1X4JqgEr-YLcuROWEt:-O1vpqGF5pHNukPyU2Gc:b33hm8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f860ec050cd688cf0ad0cd2ccafb02b08f4be147/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L89)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It really is not out of scope at all. I've changed it so that the FFI call returns an error early, and the handle to the runtime is passed down here.
</blockquote></details>

Nice, elegant fix.

**Pull request merged**
