### PR TITLE
Update relay selector for shadowsocks obfuscation

### PR DESCRIPTION
**Pull request by rablador**
When shadowsocks should be used, the relay selector should only select relays that match the port settings for shadowsocks. 

When selecting candidates for a given selection, only candidates able to provide the ports should be considered. In the case that there is no port specified, this filtering will do nothing. 

- If a user selects a port within the port range defined in shadowsocks_port_range on the god object, all relays should be considered
- If a user selects a port outside of that port range, only the relays that provide an shadowsocks_extra_addr_in should be considered in the relay selection
- If the WireGuard over Shadowsocks obfuscation is automatic then we first select a relay, then we select a port based on whether the relay has a shadowsocks_extra_addr_in available (1-65000) or not (any port in the shadowsocks_port_range)

**Acceptance criteria**

- A new structure / object is created that will handle the port selection for obfuscation
- The logic held by ProtocolObfuscator for selecting the udpOverTcp port will move to that new object
- Based on Jon's prototype, a pre-filtering of relays will happen either in that new structure, or in the RelaySelectorWrapper 
- This avoid changing the logic of RelaySelector and its algorithmic selection of ports based on retry attempts
- The ProtocolObfuscator won't have any logic besides creating the appropriate obfuscator based on which settings it reads (either, udpOverTcp,  shadowsocks or default case of not obfuscating)
- For now, we decide to lie to the obfuscator by passing settings that are predetermined, we might revisit that later

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 6 of 15 files reviewed, 7 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/ObfuscationMethodSelector.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB03m0H-hrW0QBgOlN6:-OB03m0H-hrW0QBgOlN7:bgztmrc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscationMethodSelector.swift#L18)):*
> ```Swift
>         tunnelSettings: LatestTunnelSettings
>     ) -> WireGuardObfuscationState {
>         if tunnelSettings.wireGuardObfuscation.state == .automatic {
> ```

nit
I have to say, I really like how readable this is, that `UInt` extension is really doing a lot of heavy lifting, super cool ! :thumbsup: 
___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB0-9tM1yIkfYujfqib:-OB0-9tM1yIkfYujfqic:b-fbehh9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L50)):*
> ```Swift
>     }
> 
>     private func obfuscateShadowsocksRelays(tunnelSettings: LatestTunnelSettings) throws -> REST.ServerRelaysResponse {
> ```

This doesn't `try`, therefore we can remove the `throws` keyword
___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB00Yjc30Zlex1TQ4v6:-OB00Yjc30Zlex1TQ4v7:b-vskyxj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L96)):*
> ```Swift
>         switch tunnelSettings.wireGuardObfuscation.udpOverTcpPort {
>         case .automatic:
>             return (connectionAttemptCount % 2 == 0) ? .only(80) : .only(5001)
> ```

nit
I would have said that we can omit the `return` keywords here, but swiftlint then complains about the `void_function_in_ternary` rule 
___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB03-7g4t2sUHr8OIMT:-OB03-7g4t2sUHr8OIMU:b-apoep6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L128)):*
> ```Swift
>             port
>         default:
>             RelaySelector.pickRandomPort(rawPortRanges: portRanges)
> ```

nit
Should we add documentation here that specifies that the port filtering has already happened here? i.e. point out the assumptions to be made when this method is called so that we do not use it incorrectly in the future ?
___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 145 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB-z9s62b8-EwFkypSK:-OB-z9s62b8-EwFkypSL:b-pnc1x6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/RelaySelector.swift#L145)):*
> ```Swift
>         }
> 
>         assertionFailure("Port selection algorithm is broken!")
> ```

nit
We never hit that assert, but we should still improve it, right now it has no saliency.
It would be better to say "expected port in range <range> but got instead <value>" or something along those lines
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB-ssNsEO08RbQoWb2R:-OB-ssNsEO08RbQoWb2S:b-i859vg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift#L77)):*
> ```Swift
>         )
> 
>         try Array(0 ... 10).filter { $0.isMultiple(of: 2) }.forEach { attempt in
> ```

```swift
 27> (0...10).filter { $0.isMultiple(of: 2) } 
$R24: [ClosedRange<Int><>.Element] = 6 values {
  [0] = 0
  [1] = 2
  [2] = 4
  [3] = 6
  [4] = 8
  [5] = 10
}
```

We don't need to wrap it in `Array` for it to work
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB-qTOjA4c2R7AmFdZN:-OB-qTOk86cF67D3-yya:b-6jxhpt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift#L155)):*
> ```Swift
>         }
> 
>         let port = portsOutsideDefaultRange.randomElement() ?? 0
> ```

This will never fail, we can do the following instead
```swift
let port = try XCTUnwrap(portsOutsideDefaultRange.randomElement())
```

The same principle applies for all uses of `??` here

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 4 of 15 files reviewed, 7 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/Relay/ObfuscationMethodSelector.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB03m0H-hrW0QBgOlN6:-OB4cIxq2ia26CdxwH7M:b44u44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscationMethodSelector.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I have to say, I really like how readable this is, that `UInt` extension is really doing a lot of heavy lifting, super cool ! :thumbsup:
</blockquote></details>

🙌
___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB0-9tM1yIkfYujfqib:-OB4cEJN6B73XxIUOyp9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L50)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This doesn't `try`, therefore we can remove the `throws` keyword
</blockquote></details>

Done.
___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB00Yjc30Zlex1TQ4v6:-OB4XgEL4egX5ffL1OAa:b3kkrem) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L96)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I would have said that we can omit the `return` keywords here, but swiftlint then complains about the `void_function_in_ternary` rule
</blockquote></details>

Seems to work though :)
___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB03-7g4t2sUHr8OIMT:-OB4Ym_E17TqzTWldZHV:b7jadho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L128)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Should we add documentation here that specifies that the port filtering has already happened here? i.e. point out the assumptions to be made when this method is called so that we do not use it incorrectly in the future ?
</blockquote></details>

I moved it inside it's calling function instead. Slighlty messier but a lot clearer as to what's going on.
___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 145 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB-z9s62b8-EwFkypSK:-OB4ZKFG8FPK9KS1vHZq:b-72ljmr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadREST/Relay/RelaySelector.swift#L145)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
We never hit that assert, but we should still improve it, right now it has no saliency.
It would be better to say "expected port in range <range> but got instead <value>" or something along those lines
</blockquote></details>

We could just clean up this whole method with something like:



_Code snippet:_
```Swift
guard let port = parseRawPortRanges(rawPortRanges).randomElement()?.randomElement() {
    assertionFailure("Expected to find a port in ranges but found none")
}
return port
   
```
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB-ssNsEO08RbQoWb2R:-OB4bokg5Z_2x4kIN4eE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift#L77)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

```swift
 27> (0...10).filter { $0.isMultiple(of: 2) } 
$R24: [ClosedRange<Int><>.Element] = 6 values {
  [0] = 0
  [1] = 2
  [2] = 4
  [3] = 6
  [4] = 8
  [5] = 10
}
```

We don't need to wrap it in `Array` for it to work
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB-qTOjA4c2R7AmFdZN:-OB4bqdi04ybYTcxLl7_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c54c6059b149e798e8f37fc478dd76706a5c4dd/ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift#L155)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This will never fail, we can do the following instead
```swift
let port = try XCTUnwrap(portsOutsideDefaultRange.randomElement())
```

The same principle applies for all uses of `??` here
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 6 of 15 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-:-OB58duA9p4zbllqnerm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB5ZOf32nGbc-Wyfooe:-OB5ZOf32nGbc-Wyfoof:b-zfa8ki) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a98d184eb22f3962441cb69270c4efe4d6a853f4/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L52)):*
> ```Swift
>         }
> 
>         remotePort = endpoint.ipv4Relay.port
> ```

We need to move this line before the `guard obfuscationMethod != .off else {` 
the `ConnectionState` relies on the obfuscator returning the used port

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OB5ZOf32nGbc-Wyfooe:-OB9wgPvDgHNaeA6vBOR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a98d184eb22f3962441cb69270c4efe4d6a853f4/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L52)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We need to move this line before the `guard obfuscationMethod != .off else {` 
the `ConnectionState` relies on the obfuscator returning the used port
</blockquote></details>

Done.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 2 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OBOydStBjrxp9VHYOlX:-OBOydStBjrxp9VHYOlY:bq6d3mv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c0ef76cdcd2cfd15be2894495c5d96b420a2f0/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L2)):*
> ```
> {
>   "originHash" : "c15149b2d59d9e9c72375f65339c04f41a19943e1117e682df27fc9f943fdc56",
> ```

Please revert this change

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 2 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OBOydStBjrxp9VHYOlX:-OBPIQQB7nOco6zeNVMU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb65e7a22f208e857177e5444540d7c1d6ed384a/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L2)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please revert this change
</blockquote></details>

Done.

**Review by buggmagnet — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-:-OBQkEfg6dAd3SGozOIw:bnfp4nl)* status: 14 of 16 files reviewed, 2 unresolved discussions

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 96 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OBUt3IaAwpjM5wqPJVS:-OBUt3IaAwpjM5wqPJVT:b-edq2b4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c88916f60c2904e217a709feb0628d3545ca2780/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L96)):*
> ```Swift
>         switch tunnelSettings.wireGuardObfuscation.udpOverTcpPort {
>         case .automatic:
>             (connectionAttemptCount % 2 == 0) ? .only(80) : .only(5001)
> ```

there is SwiftLint warning here, use if instead or we can have something like this:

`[.only(80) ,.only(5001)][Int(connectionAttemptCount) % 2 ]`

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 96 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-OBUt3IaAwpjM5wqPJVS:-OBZmU_v5Hg2BEW6bVwp:b-4da0wu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c88916f60c2904e217a709feb0628d3545ca2780/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L96)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

there is SwiftLint warning here, use if instead or we can have something like this:

`[.only(80) ,.only(5001)][Int(connectionAttemptCount) % 2 ]`
</blockquote></details>

I did change this at some point, so I'm surprised that it looks like this. I have now reapplied my previous fix.

**Review by mojganii — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: 13 of 16 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by mojganii — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-:-OBZqkEW33EjGDppfemW:b-uwkowd)* status: 13 of 16 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131#-:-OBZvFSE1ovQqYxyRa34:bnfp4nl)* status: 15 of 16 files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7131)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
