### PR TITLE
Sanitize the us cities

### PR DESCRIPTION
**Pull request by pronebird**
This PR removes the US state from the city when displayed on main view. 

For example: 

```
New York, New York
```

becomes

```
New York
```

There are longer strings that don't fit into the interface and get truncated.

This PR is based off `get-position` PR by Linus so disregard all commits except the final "
Remove the US state from the city name"

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/27)

### CODE REVIEW

**Comment by pronebird** [comment]
That's been discussed on Slack with no follow up.

https://mullvad.slack.com/archives/C33N9MLQ7/p1513611419000509

The state looks fine in location picker but doesn't fit in the main view.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2fGf0MAHpTF0ZYZqkC:b9zm59h)*

**Comment by faern** [comment]
I'm not sure exactly how to solve it. I'm just saying it's conceptually wrong of the gui to know about data existing in the infrastructure. Because if it can't adapt without special cases like this then we end up in a situation where adding states (or any other special information) to other countries (just an example) also requires a code change. That is maybe not so desired.

It can't auto scale the text to always fit? That would be a much more general solution that would also solve other potential bugs. I mean, there is nothing stopping the infrastructure from suddenly having a city with such a long name that it does not fit.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2g5ds5jyjZbqigIhIl:bsuljbd)*

**Comment by pronebird** [comment]
We pretty much have MVC with React so there is nothing wrong with formatting the displayed data and I do my best working with the data I have at the moment. 

We receive the US state in the city field so we'd like to get rid of it on the main view, although it looks fine on the location picker screen. 

There are technical issues with scaling text on the web so we better avoid it for now.

From the practical standpoint this change is safe because it only targets the US and even if the state will suddenly disappear from the `city` field this change will be a no-op.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2jZz6zJj6JFaeUNXci:b-gkwb2f)*

**Comment by pronebird** [comment]
> Because if it can't adapt without special cases like this then we end up in a situation where adding states (or any other special information) to other countries (just an example) also requires a code change.

What special information would you like to add into the `city` field? Please do not repurpose the `city`. If you need to display some additional information let's talk and do it properly.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2jxIgsoW-ODEUD1fnr:beb5fl8)*

**Comment by faern** [comment]
> Please do not repurpose the city. If you need to display some additional information let's talk and do it properly.

Exactly! This is exactly what I try to communicate, I want to do it properly. I argue that *this PR* re-purpose `city` and make it into something more than it is. Because this PR brings in the special case that in US the `city` contains the state (and it also requires a special format that becomes hard to change if this is merged). Before this PR everything just treat `city` as an opaque string and does not try to know anything about the content of it.

If we want to do it properly we should talk with infrastructure and discuss if we should maybe add an optional `state` field that can propagate all the way from the infrastructure and down to the frontend, then the frontend can make a better judgment about how to treat the data (only show the state in some views). Then we can reclaim `city` to actually only contain a city and nothing else.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2k-S3vUBKH57qo3pYe:b-te6juq)*

**Comment by pronebird** [comment]
> Because this PR brings in the special case that in US the city contains the state (and it also requires a special format that becomes hard to change if this is merged). 

Do you mean you'd like to swap the State and City? i.e California, San Jose -> San Jose, California. Please don't do this because we already have a situation. If you wish to drop "California" from the output then this code will handle this properly by being effectively a no-op.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2k3HPKmHkxpCeJK3lE:bxxv3eh)*

**Comment by faern** [comment]
We'll take it on Mumble on Monday.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2k47s6jXuaIZhulyVG:bx8ixhq)*

**Comment by pronebird** [comment]
> If we want to do it properly we should talk with infrastructure and discuss if we should maybe add an optional state field that can propagate all the way from the infrastructure and down to the frontend, then the frontend can make a better judgment about how to treat the data (only show the state in some views). Then we can reclaim city to actually only contain a city and nothing else.

But we'll need to release an update that will render the "state" the same way everywhere except for the single label on the main view. So what's the gain? One way or another you'll break the API and then the old clients will show one thing and the new one another.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2k3oBXs87nIprwzPJG:b-3muwy9)*

**Comment by pronebird** [comment]
After speaking on slack we decided to merge this fix since it's future proof.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2tI27m6hdV7eH62aqW:b-ikfh4g)*

**Comment by pronebird** [comment]
Well there is a debate once again on Slack. I'll wait until get-position merged anyway since it's based off that branch.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/27#-:-L2tJQj_oTilB8x-iozD:b-k7a099)*

**Comment by pronebird** [comment]
Closing as agreed to abbreviate the states on API end.

**Pull request closed without merging**
