### PR TITLE
Fix re-subscribe crash

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
Looks good. Please add a changelog item as well :pray: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948#-:-O8kEcMVAmjtJsOdN2Kf:bb4srt5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
Added!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948#-:-O8kHGPMEbITpZCF4pAf:bqmjwcm)* status: 1 of 2 files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/CHANGELOG.md` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948#-O8kOKGe5dnrz4fbDtgC:-O8kOKGe5dnrz4fbDtgD:b-4zh7l4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/425fec3414615a9ccb32e4ffe5ec2ba8ee8e7d95/android/CHANGELOG.md#L41)):*
> ```Markdown
> - Fix VPN service being recreated multiple times when toggling certain options.
> - Fix unlabeled icon buttons for basic accessibility with screen readers.
> - Fix crash when edit custom list locations screen and changing app langauge.
> ```

typo? Should probably be "...when **in the** edit custom list locations screen..."



_Code quote:_
```Markdown
Fix crash when edit custom list locations screen and changing app langauge.
```

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948#-:-O8kSzEX9sFlKrsvI19W:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948#-:-O8laJ59-izcU_FTNlPH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
