### PR TITLE
Move and rename map gl data

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to move and rename the map OpenGL geographical data in order to satisfy the F-Droid build system.

Moving the map data from `gui/assets/geo` to `dist-assets/geo` fixes a build issue since we currently remove the `gui` directory as part of the F-Droid build configuration (https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.mullvad.mullvadvpn.yml#L473).

Renaming the map data from `*.bin` to `*.gl` makes the F-Droid scanner and its binary check happy. It also better represent the actual file content since it's not a typical binary, but rather a form of graphical asset.

Fixes: DROID-817, DROID-818, DES-740

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6059)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6059#-:-NuYIz59-azD-xxv1L6y:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by albin-mullvad** [comment]
This PR probably needs additional changes to work in the desktop app according to @raksooo, so putting **On hold** for now.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6059)* status: 6 of 10 files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6059)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6059)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6059#-:-Nui01igBiZSGVXYs1Y8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
