### PR TITLE
Correct product name

### PR DESCRIPTION
**Pull request by mvd-ows**
Moving this change (product name) into its own dedicated PR.

For more background: #115 

Checklist for a PR:

* [ X ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/117)

### CODE REVIEW

**Comment by faern** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 29 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117#-L9PkAWs0Ip8msRab9-d:-L9PkAWs0Ip8msRab9-e:b-ihsz4b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4069d8db960f3c2108dfc004ebfa18d5736a196/CHANGELOG.md#L29)):*
> ```Markdown
>   version is supported.
> - Add `version` subcommand in the CLI to show information about current versions.
> - Changed all occurrences of "MullvadVPN" into "Mullvad VPN", this affects paths and window captions etc.
> ```

You are not going to like me for this. But we try to keep imperative mood (change, not changed), and line wrap at 100 chars.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117#-:-L9PksN96kgr7zeBJJ9M:bnfp4nl)*

**Comment by faern** [comment]
:lgtm: :+1:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117#-:-L9PyPatElskFLChYNm-:bb67zex)*

**Comment by mvd-ows** [comment]
Tested these changes on two independent installations of Windows 10. Works perfectly.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117#-:-L9d0ORpClqKMFGYOVDQ:b-507u45)*

**Comment by mvd-ows** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[CHANGELOG.md, line 29 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117#-L9PkAWs0Ip8msRab9-d:-L9Pm1xV12xLGtvfTxim:b-pgtwhz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4069d8db960f3c2108dfc004ebfa18d5736a196/CHANGELOG.md#L29)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You are not going to like me for this. But we try to keep imperative mood (change, not changed), and line wrap at 100 chars.
</blockquote></details>

Really? It says in the guidelines above to use "Changed", that's where I got it from. But I can definitely see that now, looking at the other entries in this list.

I considered the line length but noticed lots of lines exceeding 80 chars to did not give it a second though.

Will update as advised.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[CHANGELOG.md, line 29 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117#-L9PkAWs0Ip8msRab9-d:-L9dPBl07sJaCIrgD82t:b-u9u7p0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4069d8db960f3c2108dfc004ebfa18d5736a196/CHANGELOG.md#L29)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Really? It says in the guidelines above to use "Changed", that's where I got it from. But I can definitely see that now, looking at the other entries in this list.

I considered the line length but noticed lots of lines exceeding 80 chars to did not give it a second though.

Will update as advised.
</blockquote></details>

You mean the title `### Changed`? Yes the title has that format, as per http://keepachangelog.com/en/1.0.0/

But each entry is imperative. I have not found the website to explicitly say so, but their entries follow that style from what I can see.

Also, I see now that this entry should be under `### Changed` and not added, it's a change not an addition. I'll fix that in my other changelog PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/117)*

**Pull request merged**
