### PR TITLE
Android materialize colors

### PR DESCRIPTION
**Pull request by Pururun**
Update all the colors in the app to be more in line with android design and materialize 3 colors.

Textfield colors are not included as they are not yet set in the design.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 22 of 90 files at r1, 18 of 37 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: 40 of 97 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g0_GEBiPTPOBNg-Rw:-O4g0_GEBiPTPOBNg-Rx:b-pyhj20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
> ```Kotlin
>             containerColor = MaterialTheme.colorScheme.error,
>             contentColor = MaterialTheme.colorScheme.onError,
>             disabledContentColor = MaterialTheme.colorScheme.onError.copy(alpha = Alpha20),
> ```

We eventually want to get rid of all alpha values, right? But I guess that's a future improvement?



_Code quote:_
```Kotlin
Alpha20
```
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g3V_-6PO7R-pIojdu:-O4g3V_-6PO7R-pIojdv:bwt9im7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.theme.color
> ```

Would perhaps be nice to split light and default/dark into separate files

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 24 of 90 files at r1, 5 of 37 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: 69 of 97 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g60MH3l5pR9B3e5Hl:-O4g60MH3l5pR9B3e5Hm:b-5frs2o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L64)):*
> ```Kotlin
>                 modifier = Modifier.fillMaxWidth(),
>                 onClick = dropUnlessResumed { resultBackNavigator.navigateBack(result = true) },
>                 text = stringResource(id = R.string.send_anyway)
> ```

Looks like a bug (mixup of send anyway <-> back)? :thinking:

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 13 of 90 files at r1, 13 of 37 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: 95 of 97 files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 234 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g7aGC0Y63nA7anI74:-O4g7aGD2UQ2BHAJReSa:b3jdqi5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L234)):*
> ```Kotlin
>             }
>     }
>     Color.Red
> ```

What happened here? :smile: 



_Code quote:_
```Kotlin
Color.Red
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 270 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g7orI70uvAQsAPwYb:-O4g7orI70uvAQsAPwYc:bm5h7yi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L270)):*
> ```Kotlin
>         )
>         if (overridesActive) {
>             HorizontalDivider(color = MaterialTheme.colorScheme.onSurface)
> ```

use locally declared `onBackgroundColor`



_Code quote:_
```Kotlin
MaterialTheme.colorScheme.onSurface
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 90 files at r1, 1 of 37 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: 95 of 99 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g0_GEBiPTPOBNg-Rw:-O4iccs49czcWSQX_FCt:btqgb90) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We eventually want to get rid of all alpha values, right? But I guess that's a future improvement?
</blockquote></details>

I guess, in this case it was either create a custom color or use alpha.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 234 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g7aGC0Y63nA7anI74:-O4id3ILEZ0sPl4o20Ot:b5x29f7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L234)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What happened here? :smile:
</blockquote></details>

No idea, removed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt` line 270 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g7orI70uvAQsAPwYb:-O4idCcD7dYBhboJjJWZ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt#L270)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

use locally declared `onBackgroundColor`
</blockquote></details>

Done
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g3V_-6PO7R-pIojdu:-O4ikX2N66GLhxqUvCI3:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would perhaps be nice to split light and default/dark into separate files
</blockquote></details>

Done

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: 95 of 99 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g60MH3l5pR9B3e5Hl:-O4ivM1B05YgX1CKjZY8:bxcd7rv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L64)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Looks like a bug (mixup of send anyway <-> back)? :thinking:
</blockquote></details>

We moved the order of the buttons to better match the dialog with other dialogs in the app. I checked the code and tested it in the app that it works as expected so I guess it might be reviewable that makes it look weird.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g0_GEBiPTPOBNg-Rw:-O4izLp15mp0mXd-L4kh:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt#L74)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess, in this case it was either create a custom color or use alpha.
</blockquote></details>

Alright :thumbsup: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4g60MH3l5pR9B3e5Hl:-O4iP7nJBOa-QJFySk08:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06cb9108c4e903ce5555e1787d9448589156203f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L64)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

We moved the order of the buttons to better match the dialog with other dialogs in the app. I checked the code and tested it in the app that it works as expected so I guess it might be reviewable that makes it look weird.
</blockquote></details>

Alright :thumbsup:

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`-- commits` line 3 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4kKHw2DA9oMwwKI6ah):*
nit: we should try to keep the subject line short where possible. I suggest changing to something like: `Align colors with material design` or `Align colors better with material design`



_Code quote:_
```
Update and change colors to be more in line with material design
```
___
*[`android/CHANGELOG.md` line 32 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4kK9sV5i-TJVQrskIx:-O4kK9sV5i-TJVQrskIy:bkeu5z2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c012e4f310a7d3be3804bcf4709f048faef31be2/android/CHANGELOG.md#L32)):*
> ```Markdown
> - Migrate underlaying communication wtih daemon to gRPC. This also implies major changes and
>   improvements throughout the app.
> - Updated colors in the app to be more in line with material design.  
> ```

Change to imperative form



_Code quote:_
```Markdown
Updated
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405)* status: 99 of 100 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 3 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4kKHw2DA9oMwwKI6ah):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: we should try to keep the subject line short where possible. I suggest changing to something like: `Align colors with material design` or `Align colors better with material design`
</blockquote></details>

Done
___
*[`android/CHANGELOG.md` line 32 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-O4kK9sV5i-TJVQrskIx:-O4no5T5EzGJuCEcoIj_:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c012e4f310a7d3be3804bcf4709f048faef31be2/android/CHANGELOG.md#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to imperative form
</blockquote></details>

Done

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6405#-:-O4nrSuKEGUb2_4ZUHGu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
