### PR TITLE
Add ability to override in-IPs to the CLI

### PR DESCRIPTION
**Pull request by dlon**
This adds a new subcommand `mullvad relay override` that can be used to override values in the relay list. The fields that can be overridden (as of this PR) are `ipv4_addr_in` and `ipv6_addr_in`.

Fix DES-421.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410)* status: all files reviewed, 9 unresolved discussions (waiting on @dlon)

___
*[`mullvad-cli/src/cmds/relay.rs` line 847 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisLYLZ2pfea7uQg-Zk:-NisLYLZ2pfea7uQg-Zl:b-f663yn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/relay.rs#L847)):*
> ```XML
>                         &hostname,
>                         |relay_override| {
>                             let _ = relay_override.ipv4_addr_in.take();
> ```

Since we're just discarding the return value of `ipv4_addr_in.take()`, you might as well just assign a`None` directly
```rust
Self::update_override(
    &hostname,
    |relay_override| relay_override.ipv4_addr_in = None,
    false,
)
.await?
```



_Code quote:_
```XML
let _ = relay_override.ipv4_addr_in.take();
```
___
*[`mullvad-cli/src/cmds/relay.rs` line 857 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisMHAP5lgtema_dYpV:-NisMHAP5lgtema_dYpW:bb7eybp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/relay.rs#L857)):*
> ```XML
>                         &hostname,
>                         |relay_override| {
>                             let _ = relay_override.ipv6_addr_in.take();
> ```

dito



_Code quote:_
```XML
let _ = relay_override.ipv6_addr_in.take();
```
___
*[`mullvad-cli/src/cmds/relay.rs` line 937 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisJD9T7GDio1adBqtx:-NisJD9T7GDio1adBqty:b-ctmesx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/relay.rs#L937)):*
> ```XML
> }
> 
> async fn get_filtered_relays_with_client(
> ```

May I suggest adding a small doc-comment explaining `get_filtered_relays(_with_client)` while you are here poking? :eyes: 



_Code quote:_
```XML
pub async fn get_filtered_relays() -> Result<Vec<RelayListCountry>> {
    let mut rpc = MullvadProxyClient::new().await?;
    get_filtered_relays_with_client(&mut rpc).await
}

async fn get_filtered_relays_with_client(
```
___
*[`mullvad-cli/src/cmds/reset.rs` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisKHSwEDHWz2_-OMGr:-NisKHSwEDHWz2_-OMGs:b-szuuxd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/reset.rs#L6)):*
> ```XML
> 
> pub async fn handle() -> Result<()> {
>     if !receive_confirmation("Are you sure you want to disconnect, log out, delete all settings, logs and cache files for the Mullvad VPN system service? [y/N]", false).await {
> ```

I suggest moving the `[y/N]` part of the prompt to `receive_confirmation`, since the confirmation-format is defined in that function :blush: 



_Code quote:_
```XML
[y/N]
```
___
*[`mullvad-relay-selector/src/lib.rs` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisT7Ju9iLTk26Rl7oc:-NisT7Ju9iLTk26Rl7od:b-nnwxf5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L120)):*
> ```XML
>                 let city_code = city.code.clone();
>                 let latitude = city.latitude;
>                 let longitude = city.longitude;
> ```

Most of these `let`-bindings could be inlined without hurting readability
```rust
fn relays_with_location(relay_list: &RelayList) -> Vec<Relay> {
    let mut relays = vec![];
    for country in &relay_list.countries {
        for city in &country.cities {
            for relay in &city.relays {
                let mut relay_with_location: Relay = relay.clone();
                relay_with_location.location = Some(Location {
                    country: country.name.clone(),
                    country_code: country.code.clone(),
                    city: city.name.clone(),
                    city_code: city.code.clone(),
                    latitude: city.latitude,
                    longitude: city.longitude,
                });
                relays.push(relay_with_location);
            }
        }
    }
    relays
}

```



_Code quote:_
```XML
            let country_name = country.name.clone();
            let country_code = country.code.clone();
            for city in &country.cities {
                let city_name = city.name.clone();
                let city_code = city.code.clone();
                let latitude = city.latitude;
                let longitude = city.longitude;
```
___
*[`mullvad-relay-selector/src/lib.rs` line 172 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisUIG33c_ZWb9oLcQk:-NisUIG33c_ZWb9oLcQl:b-mo2r3z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L172)):*
> ```XML
>     fn reset_overrides(&mut self) {
>         self.relays = Self::relays_with_location(&self.locations);
>     }
> ```

You would have to dig into the documentation of `RelayList` to know that setting `self.relays = Self::relays_with_location(&self.locations)` will cause `self.relays` to contain relays as returned by the Mullvad API. I wish that intention was more clear, either here or in `relays_with_location` :blush: 



_Code quote:_
```XML
    fn reset_overrides(&mut self) {
        self.relays = Self::relays_with_location(&self.locations);
    }
```
___
*[`mullvad-relay-selector/src/lib.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisV4TM8HDuYI8KnSbM:-NisV4TM8HDuYI8KnSbN:b9pm1m6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L175)):*
> ```XML
> 
>     fn append_overrides(&mut self, overrides: Vec<RelayOverride>) {
>         self.overrides.clear();
> ```

Why is `self.overrides` cleared here? Wouldn't it be safe to just `HashMap::insert` the new overrides and apply them over the applicable relays?



_Code quote:_
```XML
self.overrides.clear();
```
___
*[`mullvad-relay-selector/src/lib.rs` line 198 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-Nis_Jpq2F-ndf_aq1On:-Nis_Jpq2F-ndf_aq1Oo:bwfysh3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L198)):*
> ```XML
>                     );
>                     relay.ipv6_addr_in = Some(ipv6_addr_in.clone());
>                 }
> ```

Would it make sense to implement this override logic on the `RelayOverride` struct? :blush: 

```rust
impl RelayOverride {
    /// Apply a [`RelayOverride`] to a [`Relay`], replacing
    /// [`Relay::ipv4_addr_in`] and [`Relay::ipv6_addr_in`]
    /// for the matching relay.
    pub fn apply(&self, relay: &mut Relay) {
        ..
    }
}
```



_Code quote:_
```XML
                if let Some(ipv4_addr_in) = overrides.ipv4_addr_in {
                    log::debug!(
                        "Overriding ipv4_addr_in for {}: {ipv4_addr_in}",
                        relay.hostname
                    );
                    relay.ipv4_addr_in = ipv4_addr_in.clone();
                }
                if let Some(ipv6_addr_in) = overrides.ipv6_addr_in {
                    log::debug!(
                        "Overriding ipv6_addr_in for {}: {ipv6_addr_in}",
                        relay.hostname
                    );
                    relay.ipv6_addr_in = Some(ipv6_addr_in.clone());
                }
```
___
*[`mullvad-types/src/settings/mod.rs` line 200 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NiscE10ABtvjRUP6CGO:-NiscE10ABtvjRUP6CGP:b-iwillm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-types/src/settings/mod.rs#L200)):*
> ```XML
>             self.relay_overrides.push(relay_override);
>         }
>     }
> ```

This logic could probably be simplified using `enumerate`

```rust
pub fn set_relay_override(&mut self, relay_override: RelayOverride) {
    let existing_override = self
        .relay_overrides
        .iter_mut()
        .enumerate()
        .find(|(_, elem)| elem.hostname == relay_override.hostname);

    match existing_override {
        None => self.relay_overrides.push(relay_override),
        Some((index, elem)) => {
            if relay_override.is_empty() {
                self.relay_overrides.swap_remove(index);
            } else {
                // Update existing options
                *elem = relay_override;
            }
        }
    }
}
```



_Code quote:_
```XML
    pub fn set_relay_override(&mut self, relay_override: RelayOverride) {
        if relay_override.is_empty() {
            if let Some(index) = self
                .relay_overrides
                .iter()
                .position(|elem| elem.hostname == relay_override.hostname)
            {
                self.relay_overrides.swap_remove(index);
            }
            return;
        }
        if let Some(elem) = self
            .relay_overrides
            .iter_mut()
            .find(|elem| elem.hostname == relay_override.hostname)
        {
            // Update existing options
            *elem = relay_override;
        } else {
            self.relay_overrides.push(relay_override);
        }
    }
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410)* status: 8 of 15 files reviewed, 9 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-cli/src/cmds/relay.rs` line 847 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisLYLZ2pfea7uQg-Zk:-NitgZV31d000g1NPRzT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/relay.rs#L847)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Since we're just discarding the return value of `ipv4_addr_in.take()`, you might as well just assign a`None` directly
```rust
Self::update_override(
    &hostname,
    |relay_override| relay_override.ipv4_addr_in = None,
    false,
)
.await?
```
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 857 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisMHAP5lgtema_dYpV:-NitgZjv6RMX1jhl-HLq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/relay.rs#L857)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 937 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisJD9T7GDio1adBqtx:-NitgdKe1VedJmPmkrhq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/relay.rs#L937)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

May I suggest adding a small doc-comment explaining `get_filtered_relays(_with_client)` while you are here poking? :eyes:
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/reset.rs` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisKHSwEDHWz2_-OMGr:-NitgfoV0xhKlhSazeBU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-cli/src/cmds/reset.rs#L6)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I suggest moving the `[y/N]` part of the prompt to `receive_confirmation`, since the confirmation-format is defined in that function :blush:
</blockquote></details>

Done.
___
*[`mullvad-relay-selector/src/lib.rs` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisT7Ju9iLTk26Rl7oc:-Nitgjwf6pg03Pzr0djn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L120)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Most of these `let`-bindings could be inlined without hurting readability
```rust
fn relays_with_location(relay_list: &RelayList) -> Vec<Relay> {
    let mut relays = vec![];
    for country in &relay_list.countries {
        for city in &country.cities {
            for relay in &city.relays {
                let mut relay_with_location: Relay = relay.clone();
                relay_with_location.location = Some(Location {
                    country: country.name.clone(),
                    country_code: country.code.clone(),
                    city: city.name.clone(),
                    city_code: city.code.clone(),
                    latitude: city.latitude,
                    longitude: city.longitude,
                });
                relays.push(relay_with_location);
            }
        }
    }
    relays
}

```
</blockquote></details>

Done.
___
*[`mullvad-types/src/settings/mod.rs` line 200 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NiscE10ABtvjRUP6CGO:-NitiqrNEOM53ZFrJcR7:b-fflhqt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-types/src/settings/mod.rs#L200)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This logic could probably be simplified using `enumerate`

```rust
pub fn set_relay_override(&mut self, relay_override: RelayOverride) {
    let existing_override = self
        .relay_overrides
        .iter_mut()
        .enumerate()
        .find(|(_, elem)| elem.hostname == relay_override.hostname);

    match existing_override {
        None => self.relay_overrides.push(relay_override),
        Some((index, elem)) => {
            if relay_override.is_empty() {
                self.relay_overrides.swap_remove(index);
            } else {
                // Update existing options
                *elem = relay_override;
            }
        }
    }
}
```
</blockquote></details>

Great idea. Done.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410)* status: 8 of 15 files reviewed, 9 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-relay-selector/src/lib.rs` line 172 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisUIG33c_ZWb9oLcQk:-Nitgv81Aft9Ml17ctiq:b-719xbl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L172)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

You would have to dig into the documentation of `RelayList` to know that setting `self.relays = Self::relays_with_location(&self.locations)` will cause `self.relays` to contain relays as returned by the Mullvad API. I wish that intention was more clear, either here or in `relays_with_location` :blush:
</blockquote></details>

This should be more obvious now.
___
*[`mullvad-relay-selector/src/lib.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-NisV4TM8HDuYI8KnSbM:-NitjZqe7i0rTz0BWsyu:b-cxchxo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L175)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Why is `self.overrides` cleared here? Wouldn't it be safe to just `HashMap::insert` the new overrides and apply them over the applicable relays?
</blockquote></details>

No longer relevant.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410)* status: 7 of 16 files reviewed, 9 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-relay-selector/src/lib.rs` line 198 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-Nis_Jpq2F-ndf_aq1On:-Nj70OGC2KVftkHmnE9C:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82c7cd3ec1a02d9e67a274e900a53d5801285dde/mullvad-relay-selector/src/lib.rs#L198)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would it make sense to implement this override logic on the `RelayOverride` struct? :blush: 

```rust
impl RelayOverride {
    /// Apply a [`RelayOverride`] to a [`Relay`], replacing
    /// [`Relay::ipv4_addr_in`] and [`Relay::ipv6_addr_in`]
    /// for the matching relay.
    pub fn apply(&self, relay: &mut Relay) {
        ..
    }
}
```
</blockquote></details>

Done.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410#-:-Nj70enN24JzxoKnSEDj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
