### PR TITLE
Rework animation to look better with predictive back

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121)* status: all files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnTjO7GUj8R3OxNcx:-OAqnTjO7GUj8R3OxNcy:b-d5hmcv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt#L13)):*
> ```Kotlin
> import com.ramcosta.composedestinations.spec.DestinationStyle
> 
> object SelectLocationTransition : DestinationStyle.Animated() {
> ```

Not sure if there is a good way to solve this, but as far as I can see this is identical to `SettingTransition` ?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnPpx7NoqIfgERhNf:-OAqnPpx7NoqIfgERhNg:b-b6zc94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt#L17)):*
> ```Kotlin
>         AnimatedContentTransitionScope<NavBackStackEntry>.() -> EnterTransition =
>         {
>             fadeIn(spring()) + scaleIn(initialScale = 1.1f)
> ```

Magical number, should be clarified and possible be made into a constant
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SettingsTransition.kt` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnQM46_KmU3GTzeyb:-OAqnQM46_KmU3GTzeyc:b-b6zc94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SettingsTransition.kt#L18)):*
> ```Kotlin
>         AnimatedContentTransitionScope<NavBackStackEntry>.() -> EnterTransition =
>         {
>             fadeIn(spring()) + scaleIn(initialScale = 1.1f)
> ```

Magical number, should be clarified and possible be made into a constant
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/AccountTransition.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqmjgs7u8jErJXiAmi:-OAqmjgs7u8jErJXiAmj:b-b6zc94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/AccountTransition.kt#L17)):*
> ```Kotlin
>         AnimatedContentTransitionScope<NavBackStackEntry>.() -> EnterTransition =
>         {
>             fadeIn(spring()) + scaleIn(initialScale = 1.1f)
> ```

Magical number, should be clarified and possible be made into a constant

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnTjO7GUj8R3OxNcx:-OAvCXJID5eFo3EIGqaC:b-rm85sj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt#L13)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Not sure if there is a good way to solve this, but as far as I can see this is identical to `SettingTransition` ?
</blockquote></details>

I was thinking the same when looking through this PR. Since it simplifies some of the transitions, perhaps some of these transition objects can be combined?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121)* status: 7 of 14 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnTjO7GUj8R3OxNcx:-OAvJSRQBZQtLCnsExW4:bq2lm05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I was thinking the same when looking through this PR. Since it simplifies some of the transitions, perhaps some of these transition objects can be combined?
</blockquote></details>

Fixed, accounts is a bit special since it needs custom out animation, but addressed the other ones.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnPpx7NoqIfgERhNf:-OAvIOy27PtHBEcYCgjT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SelectLocationTransition.kt#L17)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number, should be clarified and possible be made into a constant
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/AccountTransition.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqmjgs7u8jErJXiAmi:-OAvI7Qp2wYDcxNgazbY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/AccountTransition.kt#L17)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number, should be clarified and possible be made into a constant
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SettingsTransition.kt` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-OAqnQM46_KmU3GTzeyb:-OAvIPoC3_dNBgioIxNl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bcdb6b6203962fd5760d3ee8356b7402b29a20d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SettingsTransition.kt#L18)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number, should be clarified and possible be made into a constant
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7121#-:-OAvNqil0Id_IabMYwlh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
