### PR TITLE
Add the ability to set a custom wireguard port

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 35 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`CHANGELOG.md` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_45R0p4fPhl9VB5Eie:-N_45R0p4fPhl9VB5Eif:b3veb4t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/CHANGELOG.md#L39)):*
> ```Markdown
>   is turned off.
> - Add quantum resistant tunneling.
> - Add the ability to set a specific wireguard port.
> ```

I suggest changing `specific` to `custom`



_Code quote:_
```Markdown
specific
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_94RhnESf9-WCN_gqZ:-N_94RhnESf9-WCN_gq_:b-oqv45a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt#L5)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.model.PortRange
> 
> fun List<PortRange>.portValid(port: Int) =
> ```

I suggest changing to something like `isPortValid` or `isPortInValidRange`



_Code quote:_
```Kotlin
portValid
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_94gKq37JpOXnk6-td:-N_94gKq37JpOXnk6-te:b-i4sfll) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt#L12)):*
> ```Kotlin
>         if (index != 0) {
>             append(",")
>             append(" ")
> ```

Any reason for not combining these?



_Code quote:_
```Kotlin
            append(",")
            append(" ")
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_968Dn83tgClnHc-eD:-N_968Dn83tgClnHc-eE:b-efhpnw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt#L47)):*
> ```Kotlin
> fun CustomPortDialog(
>     customPort: String,
>     allowedRange: List<PortRange>,
> ```

I suggest renaming to `allowedPortRanges` to clarify



_Code quote:_
```Kotlin
allowedRange
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: 13 of 39 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`CHANGELOG.md` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_45R0p4fPhl9VB5Eie:-N_9beqPAGuXuGfaoKhB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/CHANGELOG.md#L39)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing `specific` to `custom`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_968Dn83tgClnHc-eD:-N_9bgN5DOZpwMBEcilF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt#L47)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `allowedPortRanges` to clarify
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_94RhnESf9-WCN_gqZ:-N_9bhbyExgVIwWWBMQc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt#L5)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing to something like `isPortValid` or `isPortInValidRange`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_94gKq37JpOXnk6-td:-N_9biBV73ASuty1lm4D:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt#L12)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Any reason for not combining these?
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 728 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D55mNA60LOgg92W-F:-N_D55mNA60LOgg92W-G:bqi54fi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85cb909ab4ebe339f87eb3c1a7fa4ac9ab814d8f/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L728)):*
> ```Kotlin
>         composeTestRule
>             .onNodeWithTag(LAZY_LIST_TEST_TAG)
>             .performScrollToNode(hasTestTag(LAZY_LIST_WIREGUARD_CUSTOM_PORT_TEXT_TEST_TAG))
> ```

I suggest adding a `// Act` comment here since we interact with the UI, even though it's something in between Arrange and Act. Same applies to some of the other tests where we scroll.



_Code quote:_
```Kotlin
        composeTestRule
            .onNodeWithTag(LAZY_LIST_TEST_TAG)
            .performScrollToNode(hasTestTag(LAZY_LIST_WIREGUARD_CUSTOM_PORT_TEXT_TEST_TAG))
```
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 800 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D5RFJ-3RzpukZeltQ:-N_D5RFJ-3RzpukZeltR:b-6lq548) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85cb909ab4ebe339f87eb3c1a7fa4ac9ab814d8f/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L800)):*
> ```Kotlin
>         composeTestRule
>             .onNodeWithTag(testTag = LAZY_LIST_WIREGUARD_CUSTOM_PORT_TEXT_TEST_TAG)
>             .performClick()
> ```

Assert -> Act



_Code quote:_
```Kotlin
        composeTestRule
            .onNodeWithTag(testTag = LAZY_LIST_WIREGUARD_CUSTOM_PORT_TEXT_TEST_TAG)
            .performClick()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 182 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D4lN6BJ4VftymSw8h:-N_D4lN6BJ4VftymSw8i:b-fz8g8t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85cb909ab4ebe339f87eb3c1a7fa4ac9ab814d8f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L182)):*
> ```Kotlin
>     onShowCustomPortDialog: () -> Unit = {},
>     onCancelCustomPortDialogClick: () -> Unit = {},
>     onCustomPortDialogClose: () -> Unit = {}
> ```

I suggest changing to `onCloseCustomPortDialog`



_Code quote:_
```Kotlin
onCustomPortDialogClose
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D35abDM8MCrUlcV8B:-N_D35abDM8MCrUlcV8C:b-j8cwr3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85cb909ab4ebe339f87eb3c1a7fa4ac9ab814d8f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L185)):*
> ```Kotlin
> ) {
>     val cellVerticalSpacing = Dimens.cellLabelVerticalPadding
>     val cellHorizontalSpacing = Dimens.cellStartPadding
> ```

I believe it would be a good idea to remove these `val`s and instead just use the `Dimens` directly



_Code quote:_
```Kotlin
    val cellVerticalSpacing = Dimens.cellLabelVerticalPadding
    val cellHorizontalSpacing = Dimens.cellStartPadding
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 187 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D3WlX77xI9QqaqWTb:-N_D3WlX77xI9QqaqWTc:b-np3mz7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/85cb909ab4ebe339f87eb3c1a7fa4ac9ab814d8f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L187)):*
> ```Kotlin
>     val cellHorizontalSpacing = Dimens.cellStartPadding
> 
>     val savedCustomPort = rememberSaveable { mutableStateOf<Constraint<Port>>(Constraint.Any()) }
> ```

I'm a bit curious of how to best store intermediate values like this. I assume you prefer this way over keeping it in the VM (?). Do you believe we should change in other places as well (not in this PR ofc)? We can discuss this outside of the PR review if you prefer that :slightly_smiling_face: 



_Code quote:_
```Kotlin
savedCustomPort
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_94RhnESf9-WCN_gqZ:-N_D2cac7s0eJ-2sMZhP:by5jijy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17b39b4b133f8a8f11c9f5cd110e2775328dbf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortRangeExtensions.kt#L5)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I realize now that it should probably be `isPortInValidRanges` with a "s" in the end since we check within multiple ranges.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: 36 of 39 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 728 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D55mNA60LOgg92W-F:-N_DMryh1OjRoqIn1PLL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023d15cb4fdfd8e4e96e32654479cfe93b52d88b/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L728)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest adding a `// Act` comment here since we interact with the UI, even though it's something in between Arrange and Act. Same applies to some of the other tests where we scroll.
</blockquote></details>

Done.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt` line 800 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D5RFJ-3RzpukZeltQ:-N_DMsmp6-q7T6-DfRR_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023d15cb4fdfd8e4e96e32654479cfe93b52d88b/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt#L800)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Assert -> Act
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 182 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D4lN6BJ4VftymSw8h:-N_DMtpQCKYGFM0w-JsL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023d15cb4fdfd8e4e96e32654479cfe93b52d88b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L182)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing to `onCloseCustomPortDialog`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-N_D35abDM8MCrUlcV8B:-N_DMucCBMhaZyK7TVny:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023d15cb4fdfd8e4e96e32654479cfe93b52d88b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L185)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it would be a good idea to remove these `val`s and instead just use the `Dimens` directly
</blockquote></details>

Done.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883#-:-N_Du-V156tWFE2vNukV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4883)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
