### PR TITLE
Improve setupapi.dll patch detection

### PR DESCRIPTION
**Pull request by dlon**
Fixes an issue where the KB2921916 hotfix cannot be installed because of incompatibility with other updates. Instead of checking whether the specific hotfix is present, look for a signature directly in setupapi.dll.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481)

### CODE REVIEW

**Review by mvd-ows — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[dist-assets/windows/installer.nsh, line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTj4OPPC1KmIbK1tw7g:-MTj4OPPC1KmIbK1tw7h:b-9fsaag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/dist-assets/windows/installer.nsh#L97)):*
> ```NSIS
> 	log::Log "InstallWin7Hotfix()"
> 
> 	os::CheckWindows7Patch
> ```

This name is very unspecific, as is the name of the current function. Other parts of the code use "Sha2Fix" to make it more clear which specific patch/hotfix is being referred. Could this be done here as well?
___
*[windows/nsis-plugins/src/os/os.vcxproj, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjBnmY0QGPSp0cOS5s:-MTjBnmY0QGPSp0cOS5t:beguypc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/os.vcxproj#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

Maybe this module would be more aptly named `osinfo`?

Since changes to the operating environment is made through other modules (`tray`, `pathedit`, etc).
___
*[windows/nsis-plugins/src/os/update.cpp, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTj8m2xD-cgjXIQUaFU:-MTj8m2xD-cgjXIQUaFV:bwj125j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L14)):*
> ```cpp
> // Jason found this to be a reliable marker of the signature check fix:
> // https://git.zx2c4.com/wireguard-windows/tree/installer/customactions.c#n145
> const char PATCH_MARKER[] = "Signature Hash";
> ```

This is probably selected because it's at a low offset in the patched file, making a successful match very quick.

Using a longer string that includes "Sha2" might be more suitable.
___
*[windows/nsis-plugins/src/os/update.cpp, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTj9TYC58MZxMo-ah2i:-MTj9TYC58MZxMo-ah2j:b-nt7yo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L32)):*
> ```cpp
> 	{
> 		// Maybe sketchy to rely on GLE here
> 		THROW_WINDOWS_ERROR(GetLastError(), "Failed to open setupapi.dll");
> ```

GLE can't be used here.
___
*[windows/nsis-plugins/src/os/update.cpp, line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjAWq8035zVfd_oRn8:-MTjAWq8035zVfd_oRn9:bortimy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L35)):*
> ```cpp
> 	}
> 
> 	const auto marker_end = PATCH_MARKER + sizeof(PATCH_MARKER) - sizeof('\0');
> ```

Does the searched string end in a NULL-terminator? If not, you can define `PATCH_MARKER` as `{ 'S', 'i', 'g' ...` and there won't be a terminator appended at the end.
___
*[windows/nsis-plugins/src/os/update.cpp, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjACf-DcMF0n-Mi3ib:-MTjACf07GdT1qDWbWCp:b-yu5goa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L37)):*
> ```cpp
> 	const auto marker_end = PATCH_MARKER + sizeof(PATCH_MARKER) - sizeof('\0');
> 	const auto last = std::istreambuf_iterator<char>();
> 	return (last != std::search(std::istreambuf_iterator<char>(ifs), last, PATCH_MARKER, marker_end));
> ```

This is using too many abstractions. It's likely that every increment/deref of the iterator will apply bounds checking.

Can you do what Jason does instead, or something similar?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[windows/nsis-plugins/src/os/update.cpp, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTj8m2xD-cgjXIQUaFU:-MTjIfXN2ZPW1l8OlJEQ:bwmgi4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L14)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is probably selected because it's at a low offset in the patched file, making a successful match very quick.

Using a longer string that includes "Sha2" might be more suitable.
</blockquote></details>

I changed my mind. This marker is fine.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[windows/nsis-plugins/src/os/update.cpp, line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjAWq8035zVfd_oRn8:-MTjIzbZEwOKPJUdwtul:b-ejxnh3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L35)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Does the searched string end in a NULL-terminator? If not, you can define `PATCH_MARKER` as `{ 'S', 'i', 'g' ...` and there won't be a terminator appended at the end.
</blockquote></details>

There are two occurrences of this string in the updated binary. They sit right next to each other, one with a NULL terminator, and the other one without a terminator.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTj4OPPC1KmIbK1tw7g:-MTjkOmbBudtG59CEE53:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/dist-assets/windows/installer.nsh#L97)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This name is very unspecific, as is the name of the current function. Other parts of the code use "Sha2Fix" to make it more clear which specific patch/hotfix is being referred. Could this be done here as well?
</blockquote></details>

Done.
___
*[windows/nsis-plugins/src/os/update.cpp, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTj9TYC58MZxMo-ah2i:-MTjkQMp8BB9NLa4dzGL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L32)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

GLE can't be used here.
</blockquote></details>

Done.
___
*[windows/nsis-plugins/src/os/update.cpp, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjACf-DcMF0n-Mi3ib:-MTjkQr0A-va97Qy1zG0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/update.cpp#L37)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is using too many abstractions. It's likely that every increment/deref of the iterator will apply bounds checking.

Can you do what Jason does instead, or something similar?
</blockquote></details>

Done.
___
*[windows/nsis-plugins/src/os/os.vcxproj, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjBnmY0QGPSp0cOS5s:-MTjkW5mEdbhO0xKdWy0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c03efc1ff99608bf9229a2cdf42fe4308700e24/windows/nsis-plugins/src/os/os.vcxproj#L1)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Maybe this module would be more aptly named `osinfo`?

Since changes to the operating environment is made through other modules (`tray`, `pathedit`, etc).
</blockquote></details>

Done.

**Review by mvd-ows — APPROVED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[windows/nsis-plugins/src/osinfo/osinfo.vcxproj, line 62 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2481#-MTjj2B_0UZGDrJlr5DM:-MTjj2B_0UZGDrJlr5DN:bemqmmc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f64746255025e87b8e474cc15c3830824fb19cce/windows/nsis-plugins/src/osinfo/osinfo.vcxproj#L62)):*
> ```XML
>       <Optimization>Disabled</Optimization>
>       <SDLCheck>true</SDLCheck>
>       <PreprocessorDefinitions>WIN32;_DEBUG;_WINDOWS;_USRDLL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
> ```

This line is missing `osinfo_EXPORTS`, but we won't be using it, so optional to fix or discard.

**Pull request merged**
