### PR TITLE
Add color tokens and use some of them in our theme

### PR DESCRIPTION
**Pull request by Pururun**
Also switch to dark theme as base theme

This is part of the design system overhaul.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211#-:-Nfj80Rl-iFd9Xxg02gh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 7 of 26 files at r1, 11 of 20 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211)* status: 28 of 29 files reviewed, all discussions resolved (waiting on @Rawa)

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 20 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt` line 88 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211#-NgIPE8a-64UupKULPPP:-NgIPE8b3sl_CykExduF:b-d30bg3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9044a3eb3a1029651a4bfe476fb3214d71ab46d6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt#L88)):*
> ```Kotlin
>     val canScroll = lazyListState.canScrollForward || lazyListState.canScrollBackward
>     val scrollBehavior =
>         TopAppBarDefaults.exitUntilCollapsedScrollBehavior(appBarState, canScroll = { canScroll })
> ```

Weird that this got added to this commit? I guess because rebase is needed? :confused: 
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt` line 56 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211#-NgIPXJkDB2Hft_RgqUz:-NgIPXJkDB2Hft_RgqV-:bovdo56) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9044a3eb3a1029651a4bfe476fb3214d71ab46d6/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt#L56)):*
> ```Kotlin
> internal val md_theme_dark_onSurface = Color(0xFFFFFFFF) // MullvadWhite
> internal val md_theme_dark_surfaceVariant = Color(0xFFFFFFFF) // MullvadWhite
> internal val md_theme_dark_onSurfaceVariant = Color(0xFFA3ACB5) // Subtext
> ```

If SurfaceVariant is #FFFFFF then onSurfaceVariant #A3ACB5 seems to be too bright? Seems like we according to Zeplin use the PrimaryBlue or something like that? 
https://app.zeplin.io/project/5f928a32fdc9962af9018d70/screen/6037df6562fa815ad838d9f7

**Review by Rawa — APPROVED** [review]
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5211#-:-NgNQssB2IV6_daDfRPe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
