### PR TITLE
Cross platform problem reports

### PR DESCRIPTION
**Pull request by anderklander**
Moves collection/sending reports from SupportPage. Support component rewritten using reactxp (+tests). Fixes issue with collecting problem report on windows and prepares to handle problem reports on mobile.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/40)

### CODE REVIEW

**Comment by eriklarko** [comment]
*[app/components/Support.js, line 100 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-L3S6qESu1kOW8TTd-kJ:-L3S6qESu1kOW8TTd-kK:b-yydc07) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13273ed34e3a237c4d71d7dd4a3be2f9f5c196f4/app/components/Support.js#L100)):*
> ```JavaScript
>       <Text style={styles.support__title}>Report a problem</Text>
>       { this.state.sendState === 'INITIAL' && <Text style={styles.support__subtitle}>
>         { 'To help you more effectively, your app\'s log file will be attached to this message. Your data will remain secure and private, as it is encrypted & anonymised before sending.' }
> ```

I know this is not very nice of me, but we have discusses changing the wording of this text a bit to `To help you more effectively, your app's log file will be attached to this message. Your data will remain secure and private, as it is anonymised before being sent over an encrypted channel.` and it might make sense to do that now :D If you disagree you can ignore this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40)*

**Comment by anderklander** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/Support.js, line 100 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-L3S6qESu1kOW8TTd-kJ:-L3S7mo--MZbVivnXWjJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13273ed34e3a237c4d71d7dd4a3be2f9f5c196f4/app/components/Support.js#L100)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

I know this is not very nice of me, but we have discusses changing the wording of this text a bit to `To help you more effectively, your app's log file will be attached to this message. Your data will remain secure and private, as it is anonymised before being sent over an encrypted channel.` and it might make sense to do that now :D If you disagree you can ignore this comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40)*

**Comment by eriklarko** [comment]
Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/Support.js, line 214 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-L3S7IoBDpDfh1qhEdfA:-L3S7IoBDpDfh1qhEdfB:buglp10) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13273ed34e3a237c4d71d7dd4a3be2f9f5c196f4/app/components/Support.js#L214)):*
> ```JavaScript
>           <Text style={styles.support__subtitle}>
>             Thanks! We will look into this. If needed we will contact you on {'\u00A0'}
>             <Text style={styles.support__sent_email}>{ this.state.email }</Text>
> ```

There is also a bug here that I introduced where the `If needed we will contact you on X` text is visible even if the email is empty :) Not really expecting you to fix it now, but if you want to it'd be awesome.

---

*[app/lib/problem-report.android.js, line 1 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-L3S7iglzm5FegvaHKUN:-L3S7iglzm5FegvaHKUO:blky4cv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13273ed34e3a237c4d71d7dd4a3be2f9f5c196f4/app/lib/problem-report.android.js#L1)):*
> ```JavaScript
> // @flow
> ```

This is nice! Good job breaking it out into a separate module and doing the naming thing!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40)*

**Comment by anderklander** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/Support.js, line 214 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-L3S7IoBDpDfh1qhEdfA:-L3S9zECfk_kpJx0mr5h:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13273ed34e3a237c4d71d7dd4a3be2f9f5c196f4/app/components/Support.js#L214)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

There is also a bug here that I introduced where the `If needed we will contact you on X` text is visible even if the email is empty :) Not really expecting you to fix it now, but if you want to it'd be awesome.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40)*

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/Support.js, line 214 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-L3S7IoBDpDfh1qhEdfA:-L3SCVb-hAT3NIFIcsen:b9sq7y5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13273ed34e3a237c4d71d7dd4a3be2f9f5c196f4/app/components/Support.js#L214)):*
<details><summary><i>Previously, anderklander wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Niice, you're awesome

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-:-L3SDfcW1LNnXYX-liUA:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/40#-:-L3SlAiQZoxpDJwEUrWO:bnfp4nl)*

**Pull request merged**
