### PR TITLE
Update android build instructions for macOS

### PR DESCRIPTION
**Pull request by Rawa**
This PR splits out and updates the build instructions for macOS. 

The current instructions branch depending on if the user have Linux or macOS, which gets confusing for the user. It was also not able to run on a ARM based macbook for several reasons:

- Updated environmental variables caused AVD in Android Studio to crash
- Links to `ndk` would pull the Linux version of `ndk` for mac user that would not work.
- `./build-apk --dev-build` spits out error `optional_android_credentials_volume[@]: unbound variable` and the image wouldn't work on ARM-based macbook if it proceeded.

The new instructions are a bit more opinionated by requiring android studio, and not using stand-alone `sdkmanager`. Considering android-studio basically the only IDE android developer's I don't believe this is too controversial. Linux users/CI/CD can still use container builds to continue to build headless. 

The steps have been tested on a clean VM of macOS.

**Caveat**: The new instructions does not apply the patch for wireguard-go, noted here: https://github.com/mullvad/mullvadvpn-app/compare/update-build-instructions-for-macos?expand=1#diff-d99ff3a97afdf0546e736e895eb02af6d19cf941f4cfec80ffe42932c1ae2038R6 we should consider looking into how this build step can be added for a mac user as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-:-NdFrLodBXaQCDTUql35:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/docs/macos-build-instructions.md` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnVJGy2UqiN9fDwgJX:-NdnVJGy2UqiN9fDwgJY:b-gl0e1s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L0)):*
I suggest renaming to either `BuildInstructions.macos.md` or `BuildInstructions-macos.md` to keep the name more similar to the other document (`BuildInstructions.md`). It would also make sure they are listed together in terminals or GUIs when listing files (ordered by name).
___
*[`android/docs/macos-build-instructions.md` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnUdm20kwkeQZb86OS:-NdnUdm20kwkeQZb86OT:b-wlla5v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L45)):*
> ```Markdown
> 
> Export the following environmental variables, and possibly store them for example in your
> `~/.zprofile` or `~/zshrc` file:
> ```

typo: should probably be `~/.zshrc` (?)



_Code quote:_
```Markdown
~/zshrc
```

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/docs/macos-build-instructions.md` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnUdm20kwkeQZb86OS:-NdnacFt7hOfnj9ulbfm:b4954fb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

typo: should probably be `~/.zshrc` (?)
</blockquote></details>

Thanks! Fixed
___
*[`android/docs/macos-build-instructions.md` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnVJGy2UqiN9fDwgJX:-Ndnamr66cVtDUCtNBKW:b-j4ggse) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to either `BuildInstructions.macos.md` or `BuildInstructions-macos.md` to keep the name more similar to the other document (`BuildInstructions.md`). It would also make sure they are listed together in terminals or GUIs when listing files (ordered by name).
</blockquote></details>

@albin-mullvad With the intent of storing it directly under `android/`? I used similar pattern to https://github.com/mullvad/mullvadvpn-app/tree/main/docs for `macos-signing.md`, and since we want people to read the original BuildInstructions.md first it is hidden away under `android/docs/`

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/docs/macos-build-instructions.md` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnVJGy2UqiN9fDwgJX:-Ndnm75v-23P64TZpEL4:b5vxc8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L)):*
Yeah, right, forgot about this being under `docs`, but I still believe it would be best to keep it consistent with the other `BuildInstructions.md` and just add a suffix like suggested above. It's quite neat to easily find all instructions like this imo (including macos and windows examples):
```
> find . -name "BuildInstructions*"

./android/docs/BuildInstructions.macos.md
./android/docs/BuildInstructions.windows.md
./android/BuildInstructions.md
./ios/BuildInstructions.md
./BuildInstructions.md
```

It's always nice to compare with existing files, like `macos-signing.md`, but I don't believe that one specifically was named to set a pattern for other platform specific stuff in the project.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`android/docs/macos-build-instructions.md` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnVJGy2UqiN9fDwgJX:-Ne2N-Wg84z68QySQAZt:b-8fptmu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yeah, right, forgot about this being under `docs`, but I still believe it would be best to keep it consistent with the other `BuildInstructions.md` and just add a suffix like suggested above. It's quite neat to easily find all instructions like this imo (including macos and windows examples):
```
> find . -name "BuildInstructions*"

./android/docs/BuildInstructions.macos.md
./android/docs/BuildInstructions.windows.md
./android/BuildInstructions.md
./ios/BuildInstructions.md
./BuildInstructions.md
```

It's always nice to compare with existing files, like `macos-signing.md`, but I don't believe that one specifically was named to set a pattern for other platform specific stuff in the project.
</blockquote></details>

I agree that it is a clearer pattern of naming the documents, and have updated it. We should consider notifying the other teams so they are aware of the pattern.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-:-Ne31920DNbPU5i_y5tn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/docs/macos-build-instructions.md` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5085#-NdnVJGy2UqiN9fDwgJX:-Ne30zT1D_0aOx5q7N9J:bqxhpmp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ccfbcdb0f4350eb6b6f1f3d10ce4df3135648a1/android/docs/macos-build-instructions.md#L)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I agree that it is a clearer pattern of naming the documents, and have updated it. We should consider notifying the other teams so they are aware of the pattern.
</blockquote></details>

Sounds like a good idea :thumbsup:

**Pull request merged**
