### PR TITLE
Add more detailed snackbars when adding and removing a location in a custom list

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListSuccess.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O081zNbErc9JZZ5EAFH:-O081zNbErc9JZZ5EAFI:bb2beo6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a546af12961b4de543633673561dc221db3ec273/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListSuccess.kt#L36)):*
> ```Kotlin
>     val name: CustomListName,
>     val locationNamesAdded: List<String>? = null,
>     val locationNamesRemoved: List<String>? = null,
> ```

Doesn't make sense to have nullables. 

Also should we have `LocationsRemoved` & `LocationsAdded`? Or if we add the full new set of locations we could get the added/removed by doing set operations.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r3, 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListActionResultData.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32Ht-g0pNvzUmwu3st:-O32Ht-g0pNvzUmwu3su:b-czw0eh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListActionResultData.kt#L8)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.CustomListName
> 
> sealed interface CustomListActionResultData : Parcelable {
> ```

Introduce "Success" to split Error and Success in the result type.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 849 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32IH2r9WiZaJvuC0gR:-O32IH2r9WiZaJvuC0gS:b-uvyt4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L849)):*
> ```Kotlin
>             if (locationNames.size == 1) {
>                 context.getString(
>                     R.string.location_was_added_to_list,
> ```

Should we have a separate string? Now it will say the same thing as if you added a item to a list.
E.g
Added 'Stockholm' to 'my_list' doesn't really say list got created.
maybe should say along the lines of:
Created list 'my_list' with location 'Stockholm'
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt` line 95 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32JWB73sFhAxG_1iyq:-O32JWB73sFhAxG_1iyr:b-yeio0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt#L95)):*
> ```Kotlin
>                         { result ->
>                             val resultData =
>                                 if (navArgs.newList) {
> ```

Maybe break out this logic into another function and return the `CustomListActionResult`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt` line 108 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32Jn234MlGKMgA_osi:-O32JIBM7Ho-wzd5oIcP:b-s1jaky) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt#L108)):*
> ```Kotlin
>                                                 customListName = result.name,
>                                                 relayListRepository
>                                                     .find(result.removedLocations.first())!!
> ```

Could be worth looking into if we should use either effect here. Then we can propagate the GenericError thingy.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt` line 242 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32JwLnCRFI6wrIdmyM:-O32JwLnCRFI6wrIdmyN:bnrsgus) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt#L242)):*
> ```Kotlin
>         CustomListLocationsSideEffect
> 
>     data object Error : CustomListLocationsSideEffect
> ```

Not sure if we have other errors that occur or if it is enough with the generic error we already have for CustomListActionResultData.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 212 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32Kt8h-7Xy4Emckxbe:-O32Kt8h-7Xy4Emckxbf:bv8szaq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L212)):*
> ```Kotlin
>     // data class LocationAddedToCustomList(val result: LocationsChanged) : SelectLocationSideEffect
> 
>     // class LocationRemovedFromCustomList(val result: LocationsChanged) : SelectLocationSideEffect
> ```

We should remove these if they are not to be used.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)* status: 16 of 24 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListActionResultData.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32Ht-g0pNvzUmwu3st:-O36WQiJ4Ro6_7tqiCQO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListActionResultData.kt#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Introduce "Success" to split Error and Success in the result type.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 849 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32IH2r9WiZaJvuC0gR:-O36Wo2k2SlSL2YC4o1G:bs0wt9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L849)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should we have a separate string? Now it will say the same thing as if you added a item to a list.
E.g
Added 'Stockholm' to 'my_list' doesn't really say list got created.
maybe should say along the lines of:
Created list 'my_list' with location 'Stockholm'
</blockquote></details>

I agree, however I am not sure that I want to change existing copy with this PR. Maybe create a linear issue for this?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt` line 242 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32JwLnCRFI6wrIdmyM:-O36XPc52VPA_exEC9ye:b-likdjm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt#L242)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure if we have other errors that occur or if it is enough with the generic error we already have for CustomListActionResultData.
</blockquote></details>

The difference is that one navigate back to the SelectLocationScreen and the other one does not and only show a toast on this screen. But I don't think they need to be different though, so will remove this.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)* status: 7 of 24 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt` line 95 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32JWB73sFhAxG_1iyq:-O36_9DD99MDEv9_MtQ2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt#L95)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe break out this logic into another function and return the `CustomListActionResult`?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt` line 108 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32Jn234MlGKMgA_osi:-O36_AFs7aQD0NmWyb-k:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt#L108)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Could be worth looking into if we should use either effect here. Then we can propagate the GenericError thingy.
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)* status: 7 of 24 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 212 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32Kt8h-7Xy4Emckxbe:-O36_TlP-1cwH6nm0xwH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L212)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should remove these if they are not to be used.
</blockquote></details>

Done.

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 8 files at r6, 10 of 14 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 849 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-O32IH2r9WiZaJvuC0gR:-O36zBDu1RVxcFRiasiy:b-pkgs1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4dfb11ddf6bd958ee70f9d7cfb639d37fc17cc6a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L849)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I agree, however I am not sure that I want to change existing copy with this PR. Maybe create a linear issue for this?
</blockquote></details>

Sounds good to me

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380#-:-O37-blD50adAhediCzL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
