### PR TITLE
Add .nvmrc and use nvm install in buildserver build script

### PR DESCRIPTION
**Pull request by raksooo**
This PR specifies the required Node.js version in `.nvmrc` and calls `nvm install --latest-npm` in the build server wrapper script to ensure that all build server builds use the correct Node.js and NPM versions.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3002)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3002#-:-Mkve36MANNaXcemnPSC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3002)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3002)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3002)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by raksooo** [comment]
I forgot to push after rebasing and Github therefore doesn't understand that this is merged.

**Pull request closed without merging**
