### PR TITLE
Packet tunnel transport for http(s) requests

### PR DESCRIPTION
**Pull request by sajacl**
Created transport models,
Created cancel logic,
Created transport feature.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, 3 of 10 files at r3, 2 of 8 files at r5, 5 of 9 files at r6, 5 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 13 of 24 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, 1 of 8 files at r5, 7 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 16 of 25 files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r10, 10 of 50 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 10 of 50 files reviewed, 1 unresolved discussion (waiting on @sajacl)

___
*[`ios/MullvadVPN/REST/Transport/RESTTransportRegistry.swift` line 33 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NE62IFsCJOlZh58AuRZ:-NE62IFsCJOlZh58AuR_:b-7qrhgz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4acc39a7d812150d2f3de649b24585ececedd191/ios/MullvadVPN/REST/Transport/RESTTransportRegistry.swift#L33)):*
> ```Swift
>         defer { nslock.unlock() }
> 
>         guard let firstTransport = getTransport(),
> ```

`getTransport()` calls `nslock.lock()` internally. `NSLock` is not recursive, so this would deadlock. Since you already acquired a lock in here, access `transports` directly, i.e:

```
guard transports.first == transport else { return }
```

Same in `transportDidTimeout()`

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 10 of 50 files reviewed, 2 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift` line 234 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NE67G359YSnS8CkOLep:-NE67G359YSnS8CkOLeq:bkdagvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4218de43a0b1f0dcdeb0c83fc752295cbe6c7a3d/ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift#L234)):*
> ```Swift
> 
> /// Separating TransportMessageReply from Codable for future use. (Logs, separate strategies, etc)
> extension SendTunnelProviderMessageOperation where Output == TransportMessageReply {
> ```

This extension is basically a mirror of `extension SendTunnelProviderMessageOperation where Output: Codable`.

**Comment by sajacl** [comment]
> ```swift
> extension SendTunnelProviderMessageOperation where Output == TransportMessageReply {
> ```

I removed this extension in pervious commits once!
I'll remove it again.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r19.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 4 of 50 files reviewed, 5 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/REST/RESTError.swift` line 50 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NE9stDN6rCK_gP1pNGS:-NE9stDOEuOSW-cAoCao:b-yu2p3u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/REST/RESTError.swift#L50)):*
> ```Swift
>                 return "Failure to decode URL response data: \(error.localizedDescription)."
>             case let .transport(error):
>                 return "Transport error \(error.localizedDescription)."
> ```

Nit: can we add `:` after "Transport error" please, so that both sentences don't merge into one.
___
*[`ios/MullvadVPN/REST/RESTNetworkOperation.swift` line 192 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA-sX9AEAHyfETTwOI:-NEA-sX9AEAHyfETTwOJ:b-9uhaus) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/REST/RESTNetworkOperation.swift#L192)):*
> ```Swift
>         }
> 
>         private func didReceiveError(
> ```

Fix naming. `didReceiveSubject(_ subj: Subject, ...)`
___
*[`ios/MullvadVPN/REST/RESTNetworkOperation.swift` line 221 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA-_bZ5isgXz1ygKSR:-NEA-_bZ5isgXz1ygKSS:b-9uhaus) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/REST/RESTNetworkOperation.swift#L221)):*
> ```Swift
>         }
> 
>         private func didReceiveURLResponse(
> ```

Fix naming. `didReceiveSubject(_ subj: Subject, ...)`
___
*[`ios/MullvadVPN/REST/RESTProxy.swift` line 85 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA-zSJER-aC1e-63bK:-NEA-zSJER-aC1e-63bL:byfikcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/REST/RESTProxy.swift#L85)):*
> ```Swift
> 
>             super.init(
>                 transportRegistry: RESTTransportRegistry.shared,
> ```

Why `.shared` when you initialize a subclass of `ProxyConfiguration` with `ProxyConfiguration`?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 10 of 50 files reviewed, 7 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/REST/Transport/TransportMonitor.swift` line 13 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA42y0ELXjVap_4FVW:-NEA42y0ELXjVap_4FVX:b2f4ou0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/REST/Transport/TransportMonitor.swift#L13)):*
> ```Swift
> class TransportMonitor: TunnelObserver {
>     private let packetTunnelTransport = PacketTunnelTransport()
>     private let urlSessionTunnelTransport = URLSessionTransport(urlSession: REST.sharedURLSession)
> ```

Nit: variable name looks like copy and paste from above.



_Code quote:_
```Swift
urlSessionTunnelTransport
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 50 files at r14, 1 of 7 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 13 of 50 files reviewed, 8 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2009 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA5g_jCuDQ_uEG7zph:-NEA5g_kDs0La1qng5Rj:b-f2ssrl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN.xcodeproj/project.pbxproj#L2009)):*
> ```
> 				CODE_SIGN_ENTITLEMENTS = MullvadVPN/MullvadVPN.entitlements;
> 				CODE_SIGN_IDENTITY = "Apple Development";
> 				CODE_SIGN_STYLE = Manual;
> ```

FYI Thanks. Good spot. I realized that we had it set this way before we had XCConfig.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 13 of 50 files reviewed, 9 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/REST/Transport/PacketTunnelTransport.swift` line 13 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA5rXr69yewqy0mhl4:-NEA5rXr69yewqy0mhl5:b-5iff7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/REST/Transport/PacketTunnelTransport.swift#L13)):*
> ```Swift
> class PacketTunnelTransport: RESTTransport {
>     var name: String {
>         "packet-tunnel"
> ```

Nit: missing `return`

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 50 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 14 of 50 files reviewed, 9 unresolved discussions (waiting on @sajacl)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 50 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 16 of 50 files reviewed, 14 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift` line 20 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEAA1bi59XIR2oItXJM:-NEAA1bi59XIR2oItXJN:bvt6uxh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift#L20)):*
> ```Swift
>     case getTunnelStatus
> 
>     /// Request the tunnel to transport a http request.
> ```

Docs should say something along the lines of`Send HTTP request outside of VPN tunnel.`
___
*[`ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift` line 21 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEA9lbG78PqAPgzPrq2:-NEA9lbG78PqAPgzPrq3:ba0berl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift#L21)):*
> ```Swift
> 
>     /// Request the tunnel to transport a http request.
>     case transportHTTPRequest(TransportMessage)
> ```

Nit: maybe we should rename it to `sendURLRequest` to better match the `cancelURLRequest` counterpart.
___
*[`ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift` line 23 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEAAHmr4iXDFbq60FNi:-NEAAHmr4iXDFbq60FNj:b8i353p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift#L23)):*
> ```Swift
>     case transportHTTPRequest(TransportMessage)
> 
>     /// Request the tunnel to cancel transport for http request.
> ```

Similar here, should be along the lines of `Cancel HTTP request sent outside of VPN tunnel`

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 16 of 50 files reviewed, 15 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift` line 35 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEAAqI3ElwLPkFiPvAG:-NEAAqI3ElwLPkFiPvAH:b-nh9mbc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift#L35)):*
> ```Swift
>             return "transport-http-request"
>         case .cancelURLRequest:
>             return "cancel-transport-http-request"
> ```

Fix descriptions to match the case.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 50 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 16 of 50 files reviewed, 15 unresolved discussions (waiting on @sajacl)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 14 of 50 files reviewed, 19 unresolved discussions (waiting on @sajacl)

___
*[`ios/Shared/TransportMessage+Reply.swift` line 2 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEAB0jz7-pyEnu42csJ:-NEAB0jz7-pyEnu42csK:b-8lgtxx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7257c6de8ff3b8cf2799b7d9875631373b8b1c60/ios/Shared/TransportMessage%2BReply.swift#L2)):*
> ```Swift
> //
> //  RequestModel.swift
> ```

Nit: fix name. Also filename `TransportMessage+Reply` implies a `+Reply` extension  over `TransportMessage`. This the usual naming convention in Swift that `+` in filename implies extension. Anyways, I think it's ok if both classes leave under `TransportMessage.swift`.
___
*[`ios/Shared/TransportMessage+Reply.swift` line 21 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEACgT87gMcdQDcVBE6:-NEACgT87gMcdQDcVBE7:b-8y7vq6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d92f46be6084bc1d3c668c459edfe40b5748517f/ios/Shared/TransportMessage%2BReply.swift#L21)):*
> ```Swift
>     let httpHeaders: [String: String]?
> 
>     func encode() throws -> Data {
> ```

`encode()` is not used any longer, because `TunnelProviderMessage` implements it and this struct is Codable and included as a part of `TunnelProviderMessage`
___
*[`ios/Shared/TransportMessage+Reply.swift` line 26 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEACbBY4u1HzmjDKWGH:-NEACbBY4u1HzmjDKWGI:btmf03h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d92f46be6084bc1d3c668c459edfe40b5748517f/ios/Shared/TransportMessage%2BReply.swift#L26)):*
> ```Swift
> }
> 
> extension TransportMessage {
> ```

Please move `init()` into `struct` definition above and remove that extension.
___
*[`ios/Shared/TransportMessage+Reply.swift` line 46 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEACsrn0l_Ntuxe4O7U:-NEACsrn0l_Ntuxe4O7V:b-raz8i4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d92f46be6084bc1d3c668c459edfe40b5748517f/ios/Shared/TransportMessage%2BReply.swift#L46)):*
> ```Swift
>     let error: URLErrorWrapper?
> 
>     func decode(from data: Data) throws -> Self {
> ```

Both `decode()` and `encode()` are unused and should be removed. Decoding part is handled by `TunnelProviderReply`

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 14 of 50 files reviewed, 21 unresolved discussions (waiting on @sajacl)

___
*[`ios/Shared/TransportMessage+Reply.swift` line 14 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEAOQI1B3C0KCGbxNII:-NEAOQI2Dm9Oda6tUlO8:b-cuzyqj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d92f46be6084bc1d3c668c459edfe40b5748517f/ios/Shared/TransportMessage%2BReply.swift#L14)):*
> ```Swift
> /// Its a wrapper to send urlRequest to tunnel via Data,
> /// and recreate the original request inside the tunnel.
> struct TransportMessage: Codable {
> ```

Discussed in private, we should perhaps rename it to:

```
/// Struct describing serializable URLRequest data.
struct ProxyURLRequest: Codable {
```
___
*[`ios/Shared/TransportMessage+Reply.swift` line 41 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEAOMHc1mrYGbI_-veT:-NEAOMHdCqMcsRq3IsoW:b-1nm2sg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d92f46be6084bc1d3c668c459edfe40b5748517f/ios/Shared/TransportMessage%2BReply.swift#L41)):*
> ```Swift
> /// Its a wrapper for tunnel to respond back to app via Data.
> /// It will be decoded it inside the app to get the response from transported end point.
> struct TransportMessageReply: Codable {
> ```

Discussed in private. I think we should rename this to:

```
/// Struct describing serializable URLResponse data.
struct ProxyURLResponse: Codable {
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 2 files at r20, 13 of 13 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 19 of 50 files reviewed, 2 unresolved discussions (waiting on @sajacl)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 19 of 50 files reviewed, 3 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/REST/Transport/PacketTunnelTransport.swift` line 21 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEB1Q2E2fX9fEqLLwJ4:-NEB1Q2E2fX9fEqLLwJ5:bhcmkx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8477a6185238b208ed05fa90424b4b6daea5e1e2/ios/MullvadVPN/REST/Transport/PacketTunnelTransport.swift#L21)):*
> ```Swift
>     ) throws -> Cancellable {
>         let message = try ProxyURLRequest(
>             /// Create unique request UUID and store it along the URLSessionTask in a dictionary.
> ```

The comment relates to have packet tunnel is storing it internally, so perhaps not needed to be here.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 19 of 50 files reviewed, 3 unresolved discussions (waiting on @sajacl)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 243 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEB1teV6kbhi4XGnkn1:-NEB1teV6kbhi4XGnkn2:buxt7oq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8477a6185238b208ed05fa90424b4b6daea5e1e2/ios/PacketTunnel/PacketTunnelProvider.swift#L243)):*
> ```Swift
> 
>                 completionHandler?(response)
>             case let .sendURLRequest(message):
> ```

Nit: add blank line to separate cases.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 280 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEB1oxD0mwUKDYAAkwP:-NEB1oxD0mwUKDYAAkwQ:bwswcde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8477a6185238b208ed05fa90424b4b6daea5e1e2/ios/PacketTunnel/PacketTunnelProvider.swift#L280)):*
> ```Swift
> 
>                 task.resume()
>             case let .cancelURLRequest(messageId):
> ```

Nit: add blank line above to separate cases visually.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 19 of 50 files reviewed, 4 unresolved discussions (waiting on @sajacl)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 270 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-NEB2-_tD_JwfRdesD58:-NEB2-_tD_JwfRdesD59:b3z38tt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8477a6185238b208ed05fa90424b4b6daea5e1e2/ios/PacketTunnel/PacketTunnelProvider.swift#L270)):*
> ```Swift
>                             self.providerLogger.error(
>                                 error: error,
>                                 message: "Failed to encode tunnel status reply."
> ```

The message is a copy from somewhere else, should say `Failed to encode ProxyURLResponse.`

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 4 files at r23, 2 of 3 files at r24, 2 of 3 files at r25, 2 of 2 files at r26, 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 13 of 50 files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998#-:-NEC0wV68jsUusIAI-FF:bnfp4nl)* status: 13 of 50 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r28, 2 of 2 files at r29, 1 of 2 files at r30, 2 of 2 files at r32, 1 of 2 files at r33, 1 of 1 files at r35, 6 of 6 files at r38, 1 of 1 files at r39, 1 of 1 files at r40, 1 of 1 files at r41, 2 of 2 files at r42.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 18 of 50 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r43.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)* status: 19 of 50 files reviewed, all discussions resolved

**Pull request merged**
