### PR TITLE
Add ad blocking

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Add preferences controller with adblocking options under Settings > Preferences
2. Add custom `UISwitch` implementation for toggle control
3. Expose entire `TunnelSettings` from `TunnelManager` to avoid doing multiple asynchronous calls to fetch relay constraints, or ad blocking settings which makes the code more flat and easier to follow
4. Make majority of types stored in `TunnelSettings` conform to `Equatable` to be able to compare `TunnelSettings`

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 0 of 17 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/CustomSwitchContainer.swift, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaXw4NCARU4APShEP4H:-MaXw4NCARU4APShEP4I:b-7kxqmi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7e19a0b44966d4323758a889b62b0532767e1ae/ios/MullvadVPN/CustomSwitchContainer.swift#L11)):*
> ```Swift
> import UIKit
> 
> class CustomSwitchContainer: UIView {
> ```

FYI creates an outer frame around `CustomSwitch` control.
___
*[ios/MullvadVPN/CustomSwitchContainer.swift, line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaXwKUBDSfhBlN5i3xU:-MaXwKUBDSfhBlN5i3xV:b-goreu0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7e19a0b44966d4323758a889b62b0532767e1ae/ios/MullvadVPN/CustomSwitchContainer.swift#L60)):*
> ```Swift
> 
>     private func controlSize() -> CGSize {
>         var size = control.bounds.size
> ```

FYI on iOS a standard toggle control (`UISwitch`) has fixed dimensions.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 0 of 17 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/TunnelManager.swift, line 264 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaXw_mI1rToYNDkFxfC:-MaXw_mI1rToYNDkFxfD:b6of1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/966afc53057f1945600415db2c99b262749bf77a/ios/MullvadVPN/TunnelManager.swift#L264)):*
> ```Swift
> 
>     private var _tunnelState = TunnelState.disconnected
>     private var _publicKeyWithMetadata: PublicKeyWithMetadata?
> ```

FYII Since we query more data from settings, I figured we should just cache the entire `TunnelSettings` configuration

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 0 of 17 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/CustomSwitch.swift, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaXxNH26aDmV5TpRLbQ:-MaXxNH26aDmV5TpRLbR:b-5pf4tl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7e19a0b44966d4323758a889b62b0532767e1ae/ios/MullvadVPN/CustomSwitch.swift#L52)):*
> ```Swift
>         let actions = {
>             self.thumbTintColor = isOn ? UIColor.Switch.onThumbColor : UIColor.Switch.offThumbColor
>             self.backgroundView?.backgroundColor = .clear
> ```

FYI on iOS 13+ `UISwitch` ignores the `tintColor` setting and paints the semi transparent white background behind the toggle in off state. However it does respect the `onTintColor` unless it's not fully opaque, it ignores semi-transparent colors and falls back to semi transparent white. So the only way to fix it is to traverse the view hierarchy and find the background view.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 0 of 17 files reviewed, 1 unresolved discussion

___
*[ios/MullvadVPN/CustomSwitch.swift, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaXxNH26aDmV5TpRLbQ:-MaXz07K1JJb-N78-Jbj:bptkcgu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7e19a0b44966d4323758a889b62b0532767e1ae/ios/MullvadVPN/CustomSwitch.swift#L52)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI on iOS 13+ `UISwitch` ignores the `tintColor` setting and paints the semi transparent white background behind the toggle in off state. However it does respect the `onTintColor` unless it's not fully opaque, it ignores semi-transparent colors and falls back to semi transparent white. So the only way to fix it is to traverse the view hierarchy and find the background view.
</blockquote></details>

FYU on iOS 12 the `tintColor` and `onTintColor` settings are respected and `backgroundView` always returns `nil`

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/CHANGELOG.md, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaYeP4q1uf6ZIcNtWl9:-MaYeP4q1uf6ZIcNtWlA:bv9h5ov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb88e73b63d254e56d38502aeb525d7b3d0d39b9/ios/CHANGELOG.md#L33)):*
> ```Markdown
>   re-downloading the relay list if it hasn't changed.
> - Pin root SSL certificates.
> - Add ad blocking.
> ```

Maybe this could be a bit clearer? Maybe something like `Add option to use Mullvad's ad-blocking DNS servers.`?

**Review by raksooo — COMMENTED** [review]
> Reviewed 10 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 13 of 17 files reviewed, 2 unresolved discussions (waiting on @pronebird)

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 13 of 17 files reviewed, 2 unresolved discussions (waiting on @pronebird)

**Comment by CruiseMan** [comment]
What source of ad url's will be used in the app ?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @jvff and @raksooo)

___
*[ios/CHANGELOG.md, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MaYeP4q1uf6ZIcNtWl9:-MabscBJ1Rk14eRy_kbr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb88e73b63d254e56d38502aeb525d7b3d0d39b9/ios/CHANGELOG.md#L33)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe this could be a bit clearer? Maybe something like `Add option to use Mullvad's ad-blocking DNS servers.`?
</blockquote></details>

Done.

**Comment by jbjorkang** [comment]
> What source of ad url's will be used in the app ?

We are using these on the server side:

- **easylist-adblock**: https://justdomains.github.io/blocklists/lists/easylist-justdomains.txt
- **easylist-privacy**: https://justdomains.github.io/blocklists/lists/easyprivacy-justdomains.txt

**Review by raksooo — COMMENTED** [review]
> Reviewed 6 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @jvff, @pronebird, and @raksooo)

___
*[ios/MullvadVPN/CustomSwitch.swift, line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MacPJp30o7-R5ZxzAFn:-MacPJp30o7-R5ZxzAFo:bray8nb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb88e73b63d254e56d38502aeb525d7b3d0d39b9/ios/MullvadVPN/CustomSwitch.swift#L22)):*
> ```
> getRelayConstraints
> ```

Are there any other subviews with a background color? If so, is there any risk of the order changing and messing this up?

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff and @pronebird)

___
*[ios/MullvadVPN/CustomSwitch.swift, line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MacPJp30o7-R5ZxzAFn:-Mac__WmApGHcYaUJ0jX:b-k4f7tj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb88e73b63d254e56d38502aeb525d7b3d0d39b9/ios/MullvadVPN/CustomSwitch.swift#L22)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

> ```
> getRelayConstraints
> ```

Are there any other subviews with a background color? If so, is there any risk of the order changing and messing this up?
</blockquote></details>

I don't know how I got the "getRelayConstraint" in there, it's not supposed to be there.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff and @raksooo)

___
*[ios/MullvadVPN/CustomSwitch.swift, line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MacPJp30o7-R5ZxzAFn:-MacR4Gx7sjBTzko3Ai-:b-yxd39s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb88e73b63d254e56d38502aeb525d7b3d0d39b9/ios/MullvadVPN/CustomSwitch.swift#L22)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't know how I got the "getRelayConstraint" in there, it's not supposed to be there.
</blockquote></details>

There is a risk with the future releases if the private view hierarchy suddenly change.

**Review by raksooo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-:-MacskLABt6t4r-Hw6qD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/MullvadVPN/CustomSwitch.swift, line 22 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MacPJp30o7-R5ZxzAFn:-MacsVkYEGWznITU7Q1R:b-s0zq4e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb88e73b63d254e56d38502aeb525d7b3d0d39b9/ios/MullvadVPN/CustomSwitch.swift#L22)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

There is a risk with the future releases if the private view hierarchy suddenly change.
</blockquote></details>

Okay, hopefully it wont :crossed_fingers:

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/PreferencesViewController.swift, line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MadKlXjBRnLJ3c4eH5G:-MadKlXjBRnLJ3c4eH5H:b-mq0f4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0d1f62c1f2ecf768875a906e1cc2998548bfc136/ios/MullvadVPN/PreferencesViewController.swift#L38)):*
> ```Swift
>         tableView.rowHeight = UITableView.automaticDimension
>         tableView.estimatedRowHeight = 60
>         tableView.sectionHeaderHeight = 18
> ```

This is different from `PreferencesTableViewDataSource.tableView(heightForHeaderInSection)`. Just wanted to point it out in case it's not on purpose :D

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[ios/MullvadVPN/PreferencesViewController.swift, line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MadKlXjBRnLJ3c4eH5G:-MahDV3e9cp4NOL05nRI:b112rpd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0d1f62c1f2ecf768875a906e1cc2998548bfc136/ios/MullvadVPN/PreferencesViewController.swift#L38)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This is different from `PreferencesTableViewDataSource.tableView(heightForHeaderInSection)`. Just wanted to point it out in case it's not on purpose :D
</blockquote></details>

I think it's just a left over which has no effect since we implement a delegate...

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-:-MahVxZz8HckFotRTV53:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/PreferencesViewController.swift, line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762#-MadKlXjBRnLJ3c4eH5G:-MahJr157R-QRpvuR_tT:bz873w3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0d1f62c1f2ecf768875a906e1cc2998548bfc136/ios/MullvadVPN/PreferencesViewController.swift#L38)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think it's just a left over which has no effect since we implement a delegate...
</blockquote></details>

Ehm this is a hack. Basically by setting `sectionHeaderHeight > 0` makes table view query height from delegate, but then if you don't return any view for footer or header, then the table view simply adds an empty space instead.

I think what would be a little less confused is to return a transparent view for section header and then set the correct sectionHeaderHeight.

**Review by jvff — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2762)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
