### PR TITLE
Build test executable in buildserver-build.sh

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds a build script for building the GUI test executables for any platform. This script is called in `buildserver-build.sh` as well to build the executables automatically.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/test.pkg.json` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NOE5BTeAe59eMCjwomj:-NOE5BTeAe59eMCjwomk:bcnhm5j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0e090f79772052e038e42e7af333ab2ee01a246/gui/test.pkg.json#L1)):*
> ```JSON
> {
> ```

As discussed on slack. Maybe rename this file to `standalone-tests.pkg.json` to make it more clear.
___
*[`gui/scripts/build-test-executable.sh` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NODwU7M5to9GDIEeFGh:-NODwU7M5to9GDIEeFGi:bas6asp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0e090f79772052e038e42e7af333ab2ee01a246/gui/scripts/build-test-executable.sh#L7)):*
> ```Shell
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> cd "$SCRIPT_DIR"
> cd ..
> ```

I'd probably just combine this to `cd "$SCRIPT_DIR/..`.
___
*[`gui/scripts/build-test-executable.sh` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NODxy7E2pGFfkdeP3V0:-NODxy7E2pGFfkdeP3V1:b-qdkpsz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0e090f79772052e038e42e7af333ab2ee01a246/gui/scripts/build-test-executable.sh#L26)):*
> ```Shell
> if [[ -n ${TARGET:-""} ]]; then
>     case "$TARGET" in
>     "aarch64-unknown-linux-gnu"*)
> ```

Nit, but are the `*` really needed? Pretty sure the targets should match exactly.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`gui/scripts/build-test-executable.sh` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NODwU7M5to9GDIEeFGh:-NOFYgOe1zKufmIBJIN2:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0e090f79772052e038e42e7af333ab2ee01a246/gui/scripts/build-test-executable.sh#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'd probably just combine this to `cd "$SCRIPT_DIR/..`.
</blockquote></details>

Done
___
*[`gui/scripts/build-test-executable.sh` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NODxy7E2pGFfkdeP3V0:-NOFYhmg5ors_A5QDh2o:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0e090f79772052e038e42e7af333ab2ee01a246/gui/scripts/build-test-executable.sh#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit, but are the `*` really needed? Pretty sure the targets should match exactly.
</blockquote></details>

Done.
___
*[`gui/test.pkg.json` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NOE5BTeAe59eMCjwomj:-NOFYffB4HSO0eV7kTHx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0e090f79772052e038e42e7af333ab2ee01a246/gui/test.pkg.json#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As discussed on slack. Maybe rename this file to `standalone-tests.pkg.json` to make it more clear.
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/scripts/build-test-executable.sh` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NOF_M_v8wXvbTc-KLq9:-NOF_M_wEwEP8lEyyO38:bpy9iv3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/49df5eba2ef3a13f3f1370f61508155659332e53/gui/scripts/build-test-executable.sh#L8)):*
> ```Shell
> cd "$SCRIPT_DIR/.."
> 
> TARGET=${1:-$(rustc -vV | sed -n 's|host: ||p')}
> ```

Wow, great! This simplified stuff a lot!
___
*[`gui/scripts/build-test-executable.sh` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NOF_9KvBpOWSVgLIwiF:-NOF_9KvBpOWSVgLIwiG:b88i0qb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/49df5eba2ef3a13f3f1370f61508155659332e53/gui/scripts/build-test-executable.sh#L24)):*
> ```Shell
> 
> case "$TARGET" in
> "aarch64-unknown-linux-gnu")
> ```

These should be indented. Or is reviewable lying to me?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`gui/scripts/build-test-executable.sh` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-NOF_9KvBpOWSVgLIwiF:-NOF_xbT71wPLsKDCb0i:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/49df5eba2ef3a13f3f1370f61508155659332e53/gui/scripts/build-test-executable.sh#L24)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

These should be indented. Or is reviewable lying to me?
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-:-NOOYwvK-K0-zc23cOvT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
This is just a test "review". Reviewable.io seems broken?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4350#-:-NOTjUia7Ut2pnUeJtaP:bmxxblj)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
