### PR TITLE
Add API access method tests

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR add tests for custom API access methods to the integration test suite.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by dlon — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-future/src/lib.rs` line 4 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqU83Lk-WkMeKFFVg_H:-NqU83Lk-WkMeKFFVg_I:b4swlxw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b43a7fc0e2ac6babef6ae11092084b8f53f7bdb0/talpid-future/src/lib.rs#L4)):*
> ```XML
> #![deny(missing_docs)]
> 
> pub mod future_retry;
> ```

Nit: `future_` could probably be removed?

**Review by dlon — APPROVED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

**Review by dlon — COMMENTED** [review]
> Reviewed 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-api/src/lib.rs` line 256 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqbOjJe6dzjtySmsDAO:-NqbOjJe6dzjtySmsDAP:b17av4c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b88707f1d0e5c7ad25f5716a6bbd8926e33ca9f/mullvad-api/src/lib.rs#L256)):*
> ```XML
>         ];
> 
>         if env_vars.map(Self::read_var).iter().any(Option::is_some) {
> ```

Nice trick!

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: 23 of 32 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-api/src/lib.rs` line 177 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqbNN4f8MtsZMKXDmFg:-Nqgp1H65d3KDSxYvHC6:b-7mzt8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b88707f1d0e5c7ad25f5716a6bbd8926e33ca9f/mullvad-api/src/lib.rs#L177)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We seem to check if `var != "0"` for other boolean env vars. `false` might be objectively better, but it's inconsistent, so maybe we should stick to 0?
</blockquote></details>

True, it is better to be consistent. Fixed
___
*[`mullvad-api/src/lib.rs` line 256 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqbOjJe6dzjtySmsDAO:-Nqgp4iV6XIuyosNN8yE:b-ucfknh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b88707f1d0e5c7ad25f5716a6bbd8926e33ca9f/mullvad-api/src/lib.rs#L256)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nice trick!
</blockquote></details>

Thanks!
___
*[`mullvad-daemon/src/api.rs` line 247 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqbMpPnC_aXD4o-ybwM:-Nqgp6hn8ulX_JK_xEtb:bh0kgv9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1355a18d16c6b89a45641234a94fb34cc3d97d46/mullvad-daemon/src/api.rs#L247)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Off by one?
</blockquote></details>

This was fixed in a separate PR
___
*[`talpid-future/src/lib.rs` line 4 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqU83Lk-WkMeKFFVg_H:-NqgpB65Ac0MjfEUG53Y:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b43a7fc0e2ac6babef6ae11092084b8f53f7bdb0/talpid-future/src/lib.rs#L4)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: `future_` could probably be removed?
</blockquote></details>

Done
___
*[`test/test-manager/src/tests/access_methods.rs` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqDTG7PDgRHFtOM4UMD:-NqgpDko4QAgrTI6GPrz:bsji3so) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1f44008d0f3287725849bb6c5e0c99e806424fb1/test/test-manager/src/tests/access_methods.rs#L59)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should probably filter on `active` too. Maybe it should also select a random relay to avoid the problem we had earlier.
</blockquote></details>

Solved by using `mullvad-relay-selector`
___
*[`test/test-manager/src/tests/ui.rs` line 167 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqbOLci0AkT-ayonRDl:-NqgpHwY6dnY3A95jaVe:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1355a18d16c6b89a45641234a94fb34cc3d97d46/test/test-manager/src/tests/ui.rs#L167)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We should probably take these from `TEST_CONFIG`. See `get_app_env()`.
</blockquote></details>

Done
___
*[`test/.cargo/config.toml` line 5 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqSWhvl8eGTIB4y_xqN:-NqgpIrtBNJmzCn39te6:btdbqyi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/307ea7ef1df4b0cf0fad6a031412ac7110b3260f/test/.cargo/config.toml#L5)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Awesome. I wonder if we can just use this in the main workspace as well (instead of using `env.sh`).

Is setting `SDKROOT` required for macOS?
</blockquote></details>

No longer relevant

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: 23 of 32 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/tests/ui.rs` line 223 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798#-NqbOQLO9EscabjlhHL0:-Nqgr_sBBeAiQ6eyqSdr:b53ya0e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b88707f1d0e5c7ad25f5716a6bbd8926e33ca9f/test/test-manager/src/tests/ui.rs#L223)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

In my opinion, we should either make sure that the test always cleans up the environment, somehow, or set `must_succeed = true` on it. Otherwise, we get sort of an inconsistent state for any remaining tests.
</blockquote></details>

Done by settings `must_succeed = true`

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r12, 8 of 9 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
