### PR TITLE
Add contributing guidelines and rename license file

### PR DESCRIPTION
**Pull request by faern**
Adding the contributing guidelines. We have agreed on the copyright/legal part. For the other parts, such as code formatting and toolchain compatibility I have mostly written about the backend. If there are more frontend stuff to explain then please give me feedback.

Renamed the license file from `COPYING.md` to `LICENSE.md`. Both are valid names, but the latter is more clear IMO, and there has already been at least one confusion with the old name: #28

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/32)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[CONTRIBUTING.md, line 23 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32#-L2uMkkopfHWkj1sCkDz:-L2uMkkopfHWkj1sCkE-:b-bba2kx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6ac986f68c698ca16c7c5660e2dff609934fc21/CONTRIBUTING.md#L23)):*
> ```Markdown
> 
> While we appreciate your interest in helping us to improve Mullvad VPN, please understand that
> choosing which submitted changes to merge is fully at our discretion, based upon our development
> ```

Isn't it always at the discretion of the maintainer to merge changes or not? It feels a little discouraging to see that we have to communicate that.. But perhaps it's my impression only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32)*

**Comment by pronebird** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[CONTRIBUTING.md, line 23 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32#-L2uMkkopfHWkj1sCkDz:-L2udCPjILwHwbVOUdAw:b3h56bt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6ac986f68c698ca16c7c5660e2dff609934fc21/CONTRIBUTING.md#L23)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Isn't it always at the discretion of the maintainer to merge changes or not? It feels a little discouraging to see that we have to communicate that.. But perhaps it's my impression only.
</blockquote></details>

I don't know, yeah I guess you are right. I'm losing steam from too many discussions. I don't have a clear opinion. If you find someone else who agrees it's already implied and feel this is not needed then we'll remove it.

Ping @simonasker @dmarby. Do you have any opinion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32)*

**Comment by pronebird** [comment]
Just merge it we can refine it later.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32#-:-L2yJZvzehde8oawRM1z:bnucn2g)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/32#-:-L2yJc531N6JSra9M-tL:bnfp4nl)*

**Pull request merged**
