### PR TITLE
Improve custom lists CLI UX

### PR DESCRIPTION
**Pull request by MarkusPettersson98**
This PR overhauls the UX of the custom lists CLI to bring it up on par with other parts of the CLI. It includes a number of changes (and hopefully improvements!):

- [X] Rename `mullvad custom-lists` to `mullvad custom-list`, i.e. "list" in singular.
- [X] Add `mullvad custom-list edit` subcommand for editing the content of a custom list. This was done to distinguish between subcommands such as `mullvad custom-list remove` and `mullvad custom-list delete`. Actions on *all* custom lists are now seperate from actions on *one* custom list.
- [x] Add servers to a custom list by hostname, similiar to the recent [refactor to `mullvad relay` subcommand](https://github.com/mullvad/mullvadvpn-app/pull/4804).
- [X] Prettify the output of listing the content of custom lists. This includes overhauling identation, re-arranging the order of custom list parameters and adding long names to countries and cities. The country code `se` actually maps to `Sweden`, the city code `got` maps to `Gothenburg` etc.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002)* status: all files reviewed, 5 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYv3RY8BmfzVbkL984):*
> cutsom

custom
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYv8752GrrI-V8C6Cc):*
> cutsom

custom
___
*[`mullvad-cli/src/cmds/custom_lists.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYvICq35WedGn9AgGE:-NbYvICq35WedGn9AgGF:b-5mg619) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3da8699049a185dbb329b95479065b1ef86a79d9/mullvad-cli/src/cmds/custom_lists.rs#L26)):*
> ```XML
>         // TODO: Would be cool to provide dynamic auto-completion:
>         // https://github.com/clap-rs/clap/issues/1232
>         /// A custom list. This argument is optional
> ```

I believe you don't need to point out that it's optional, since the help text will make that clear.
___
*[`mullvad-cli/src/cmds/custom_lists.rs` line 160 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYxjp1BUI0PB1oQFnz:-NbYxjp1BUI0PB1oQFo-:b-91iwcv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3da8699049a185dbb329b95479065b1ef86a79d9/mullvad-cli/src/cmds/custom_lists.rs#L160)):*
> ```XML
> 
> /// Metadata struct used for enhancing an instance of
> /// [`GeographicLocationConstraint`] with rich information about the
> ```

It took me a while to understand this. Maybe it could point out that it prints human-readable strings for the country and city codes?
___
*[`mullvad-cli/src/cmds/custom_lists.rs` line 192 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYxwm945YQmHcfbfHK:-NbYxwm945YQmHcfbfHL:bq3zyce) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3da8699049a185dbb329b95479065b1ef86a79d9/mullvad-cli/src/cmds/custom_lists.rs#L192)):*
> city

country

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-cli/src/cmds/custom_lists.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYvICq35WedGn9AgGE:-NbZNmnA48s38KOE1ojf:b82nnuw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3da8699049a185dbb329b95479065b1ef86a79d9/mullvad-cli/src/cmds/custom_lists.rs#L26)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I believe you don't need to point out that it's optional, since the help text will make that clear.
</blockquote></details>

I don't think that the help text makes that clear, if it is not stated in the comment. Let me explain why:

This is the output of `mullvad custom-list list --help`, without explaining that the `NAME` argument is optional:

```bash
$ mullvad custom-list list --help
Show all custom lists or retrieve a specific custom list

Usage: mullvad custom-list list [NAME]

Arguments:
  [NAME]  A custom list
```

The user has to know that, by convention, brackets (`[]`) denote an optional argument. This may or may not be the case, but since there are no required arguments (denoted by angle brackets`<>`) to contrast this optional `NAME` argument, it is a bit hard to tell at a quick glance.

 Since the comment will be part of the help text, the user need not parse that the brackets (`[]`) means that the argument is optional:

```bash
$ mullvad custom-list list --help
Show all custom lists or retrieve a specific custom list

Usage: mullvad custom-list list [NAME]

Arguments:
  [NAME]  A custom list. This argument is optional
```

which I think is convenient. 

My other choice would be to acutally extend the comment, to say something like: 


```bash
$ mullvad custom-list list --help
Show all custom lists or retrieve a specific custom list

Usage: mullvad custom-list list [NAME]

Arguments:
  [NAME]  A custom list. If omitted, all custom lists are shown
```

If you disagree I can shorten the comment to simply say "A custom list", but I just want to put the argument out there for keeping the verbose style comment :blush: 
___
*[`mullvad-cli/src/cmds/custom_lists.rs` line 192 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYxwm945YQmHcfbfHK:-NbZN6Sg-dJsiUO-ovpH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3da8699049a185dbb329b95479065b1ef86a79d9/mullvad-cli/src/cmds/custom_lists.rs#L192)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> city
country
</blockquote></details>

Done.

**Review by MarkusPettersson98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-cli/src/cmds/custom_lists.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002#-NbYvICq35WedGn9AgGE:-NcN2f6o7gw2yywSQbD1:b-qgttks) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3da8699049a185dbb329b95479065b1ef86a79d9/mullvad-cli/src/cmds/custom_lists.rs#L26)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> My other choice would be to acutally extend the comment [...]

That looks better! It implies that the argument is optional but also contains a bit more information. :)
</blockquote></details>

Implemented!

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
