### PR TITLE
Start daemon and management service on main thread

### PR DESCRIPTION
**Pull request by Pururun**
Removed io dispatcher launch of management service and daemon.
Moved the ip address resolving to the daemon.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690)

### CODE REVIEW

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 12 of 12 files at r2, 13 of 13 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 84 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690#-O5SoIFc4AqcGlx7knwf:-O5SoIFc4AqcGlx7knwg:b-s746r3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1af89b893444b2c58312a8199693dca13e9707a/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L84)):*
> ```Kotlin
>         // TODO We should avoid lifecycleScope.launch (current needed due to InetSocketAddress
>         // with intent from API)
>         lifecycleScope.launch(context = Dispatchers.IO) {
> ```

:star2:

**Review by Rawa — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @dlon and @Rawa)

___
*[`mullvad-jni/src/api.rs` line 21 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690#-O5TBfGs-JCweshctKUJ:-O5Y0DL82cFWbcmu7oSK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/17597e115421c309b33759aa206d26c2d0225581/mullvad-jni/src/api.rs#L21)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

String here no longer makes sense.

This becomes infallible with the changes suggested below, but `try_hostname_from_java` may need to be unwrapped, or perhaps you could simply log an error and return with `?`. Depending on how catastrophically you want to fail if a hostname isn't provided.
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690#-:-O5Y227X3GyxSKlYg2QJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6690)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
