### PR TITLE
Enable Daita Support on iOS

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR adds Daita support on iOS, it looks big, but it's only because many files / APIs have been renamed to match more closely what happens behind the scenes, notably :
- Most `PostQuantum*` have been renamed `EphemeralPeer*`
- Only 1 extra test has been written so far `testEphemeralPeerExchangeSuccessWhenDaitaNegotiationStarts`, more are coming
- Daita functions mostly like negotiating a post quantum key, so the architecture remains unchanged

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 9 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadRustRuntime/PacketTunnelProvider+TCPConnection.swift` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Du8s44-mzGrFDc_nR:-O5Du8s50t7A1BcZ24cg:b-8c91yg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadRustRuntime/PacketTunnelProvider%2BTCPConnection.swift#L100)):*
> ```Swift
> ) {
>     guard let rawPostQuantumKeyReceiver else { return }
>     let postQuantumKeyReceiver = Unmanaged<EphemeralPeerReceiver>.fromOpaque(rawPostQuantumKeyReceiver)
> ```

Nit: `emphemeralKeyReceiver`
___
*[`ios/MullvadRustRuntime/PacketTunnelProvider+TCPConnection.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DjN65ER-LRELF13oy:-O5DjN65ER-LRELF13oz:bhri567) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadRustRuntime/PacketTunnelProvider%2BTCPConnection.swift#L110)):*
> ```Swift
>     }
> 
>     // If there is a pre-shared key, an ephemeral peer was negotiated with Post Quantum options
> ```

Is it always true that the lack of a preshared key is daita? I guess it is for now, but what happens if we add new tech that uses the same infrastructure? I think `EphemeralPeer` is a fine collective term to use here, but I wonder if the implementation where the lack of a certain element guarantees one thing or the other.
___
*[`ios/MullvadTypes/Protocols/EphemeralPeerReceiving.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DlkDfAY-Z0FqUEetH:-O5DlkDfAY-Z0FqUEetI:br4t6l7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadTypes/Protocols/EphemeralPeerReceiving.swift#L2)):*
> ```Swift
> //
> //  PostQuantumKeyReceiving.swift
> ```

Nit: EphemeralPeerReceiving
___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Dm1fu9xIIWl_FA0e_:-O5Dm1fu9xIIWl_FA0ea:b-h0i2rl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadVPN/TunnelManager/TunnelState.swift#L55)):*
> ```Swift
>     case connecting(SelectedRelays?, isPostQuantum: Bool)
> 
>     // TODO: Add information here to support Daita ???
> ```

To be continued?
___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Dm-Ir7ff_1R_DRjbu:-O5Dm-Ir7ff_1R_DRjbv:b-h0i2rl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadVPN/TunnelManager/TunnelState.swift#L116)):*
> ```Swift
>             "error state: \(blockedStateReason)"
>         case let .negotiatingEphemeralPeer(tunnelRelays, _):
>             // TODO: Handle Daita and PQ here
> ```

To be continued?
___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DnZoADb3LtlNfBP-I:-O5DnZoADb3LtlNfBP-J:b189ys3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L52)):*
> ```Swift
>             }
> 
>         // TODO: How to Handle Daita here ?
> ```

This part can be delegated to daita tickets related to UI. That should still be noted here I think.
___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DqE1267Iqv8-0vtfm:-O5DqE138ynZicFXIyUR:bw7cc5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L19)):*
> ```Swift
>         case .connecting:
>             "Connecting"
>         // TODO: Handle Daita here ?
> ```

I guess so. We should proably check the `ObservedConnectionState` is daita and/or post quantum is used and return an approriate name.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DrWwQ2kkJQCg2viix:-O5DrWwQ2kkJQCg2viiy:b-wf6prx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPostQuantum.swift#L101)):*
> ```Swift
> 
>             // wireguard-go will only turn on daita for the entry peer,
>             // so pass the daita configuration to the exit peer for consistency
> ```

What's meant here by passing config to exit for consistency? Can't see how the comment reflects the code.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Drjon2GkFKTXpHOI2:-O5Drjon2GkFKTXpHOI3:b-sjf4bl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift#L76)):*
> ```Swift
>             case .switchKey:
>                 return "switchKey"
>             // TODO: Handle Daita here ???
> ```

Perhaps more cases are needed to handle this. We shouldn't just leave the Todo though.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 9 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadRustRuntime/PacketTunnelProvider+TCPConnection.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DjN65ER-LRELF13oy:-O5Hmpu10my3PXhpMxpB:bt5x0dh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadRustRuntime/PacketTunnelProvider%2BTCPConnection.swift#L110)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is it always true that the lack of a preshared key is daita? I guess it is for now, but what happens if we add new tech that uses the same infrastructure? I think `EphemeralPeer` is a fine collective term to use here, but I wonder if the implementation where the lack of a certain element guarantees one thing or the other.
</blockquote></details>

I was debating whether I wanted to add a different FFI that specifies Daita only peers, but would increase a lot the cyclomatic complexity for virtually no benefits.

There cannot be a situation where we get an ephemeral peer that has an invalid preshared key, since the key is attached to the ephemeral peer when we request it.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Dm1fu9xIIWl_FA0e_:-O5HniomBPDSTVM65k84:b-llcrwy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadVPN/TunnelManager/TunnelState.swift#L55)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

To be continued?
</blockquote></details>

Yes, there are a lot of TODO comments that will be fixed with working on the UI.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DrWwQ2kkJQCg2viix:-O5Hnxop4Vh8aAh97MqV:b-4pdai3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPostQuantum.swift#L101)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

What's meant here by passing config to exit for consistency? Can't see how the comment reflects the code.
</blockquote></details>

Oh that's a good catch, I had a previous design where I was passing the Daita configuration in the `ConfigurationBuilder` instead, and that's a relic of that past. I will delete the comment.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 45 of 56 files reviewed, 7 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Drjon2GkFKTXpHOI2:-O5JHyvb0BMaZu2tZZus:b-pwc0qi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift#L76)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Perhaps more cases are needed to handle this. We shouldn't just leave the Todo though.
</blockquote></details>

I think we can safely remove this TODO here :thinking:

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5Dm1fu9xIIWl_FA0e_:-O5mk4gUD1Tf4tytYYnT:b-h0chzl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadVPN/TunnelManager/TunnelState.swift#L55)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Yes, there are a lot of TODO comments that will be fixed with working on the UI.
</blockquote></details>

I think we should address them as such then. Right now it looks like this PR still has TODOs rather than delegating them to another PR.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 52 of 56 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelState+UI.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DnZoADb3LtlNfBP-I:-O5qfK4aBWSS4BdzYIQi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/MullvadVPN/TunnelManager/TunnelState%2BUI.swift#L52)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This part can be delegated to daita tickets related to UI. That should still be noted here I think.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5DqE1267Iqv8-0vtfm:-O5qfQoH1_7Zs1SVBTmC:bxkay7f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62b3c6dccc09378b9091dea8e6d4a5b995fcb8f4/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L19)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I guess so. We should proably check the `ObservedConnectionState` is daita and/or post quantum is used and return an approriate name.
</blockquote></details>

This is used for debugging purposes only, so it should be fine. I've removed the comment, we'll quickly see whether I was wrong to or not :D

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 52 of 56 files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadRustRuntime/PacketTunnelProvider+TCPConnection.swift` line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5NHxZI1tGXAxuEHtmX:-O5s0uorDuguwrImec2_:b3pkke6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51973424cbbaab3b626a5ee90f0d8b92bdebcab7/ios/MullvadRustRuntime/PacketTunnelProvider%2BTCPConnection.swift#L81)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I believe this part should also be updated.
</blockquote></details>

Good catch !
___
*[`ios/MullvadRustRuntime/PacketTunnelProvider+TCPConnection.swift` line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5NINAkBrEShKKqdztC:-O5s1en5-eEIHK5pwicZ:b-sr0340) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51973424cbbaab3b626a5ee90f0d8b92bdebcab7/ios/MullvadRustRuntime/PacketTunnelProvider%2BTCPConnection.swift#L85)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Key exchanging is taking place regardless of weather it's `PQ` or `Daita`. then I believe having `quantum secure` is forbidden.
</blockquote></details>

Yes, but that paragraph is still correct, since we still need to document the PQ only case

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 51 of 56 files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 42 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s4uEBCgl1R38YJ9VU:-O5s4uEBCgl1R38YJ9VV:byncn0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L42)):*
> ```XML
>             let token = runtime.packet_tunnel.tcp_connection.clone();
> 
>             let tokio_handle = match crate::mullvad_ios_runtime() {
> ```

Why move this function here from `mod.rs`?

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 51 of 56 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 142 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s55Ia4JyLrTPE54Q0:-O5s55Ia4JyLrTPE54Q1:bk43jka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L142)):*
> ```XML
>             match Self::ios_tcp_client(self.packet_tunnel.clone()).await {
>                 Ok(result) => result,
> ```

Unnecessary whitespace change.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 51 of 56 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 56 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 51 of 56 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 51 of 56 files reviewed, 9 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 17 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s6Fpk8m4po6BQMPDC:-O5s6Fpk8m4po6BQMPDD:b-3phcxp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L17)):*
> ```
>       "location" : "https://github.com/mullvad/wireguard-apple.git",
>       "state" : {
>         "revision" : "fb9a34f15e47b167866af3257a8dcc9901d9e7c1"
> ```

This is an outdated commit now.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: 51 of 56 files reviewed, 9 unresolved discussions (waiting on @mojganii, @pinkisemils, and @rablador)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 42 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s4uEBCgl1R38YJ9VU:-O5s9DRe3Tv2Zu6DNl1G:b-w8ezp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L42)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Why move this function here from `mod.rs`?
</blockquote></details>

We used to pass the `TokioHandle` as part of `run_post_quantum_psk_exchange` which made clippy complain that we were passing too many parameters, I've moved creating (or getting) the runtime to just before we need it, It should still fail the same way as before if we can't get a runtime .
___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 142 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s55Ia4JyLrTPE54Q0:-O5s9Zk25VjWv09ycJ97:biqyo13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L142)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Unnecessary whitespace change.
</blockquote></details>

We should agree on using a rust formatter then

**Review by rablador — COMMENTED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

**Review by rablador — DISMISSED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 42 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s4uEBCgl1R38YJ9VU:-O5wAyMA-Ip57oTx0qcM:bnxliah) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L42)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We used to pass the `TokioHandle` as part of `run_post_quantum_psk_exchange` which made clippy complain that we were passing too many parameters, I've moved creating (or getting) the runtime to just before we need it, It should still fail the same way as before if we can't get a runtime .
</blockquote></details>

Fair. Interesting that this passed the CI last time. I'd prefer to keep this function free from that call, but if clippy is complaining, then we could also stuff all of the peer exchange args into a struct instead. 
___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 142 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s55Ia4JyLrTPE54Q0:-O5wArK9BjSg1IQx5T8_:b-cpg2q8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L142)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should agree on using a rust formatter then
</blockquote></details>

We are using a rust formatter, and the whitespace is not being introduced by the formatter.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @pinkisemils)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 42 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s4uEBCgl1R38YJ9VU:-O5wn_GS4Kc-MHY2x62W:bkgzfgh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L42)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Fair. Interesting that this passed the CI last time. I'd prefer to keep this function free from that call, but if clippy is complaining, then we could also stuff all of the peer exchange args into a struct instead.
</blockquote></details>

Yes, I'm not super happy about this either. I think if we want to revisit this code in the future, we should take the opportunity to refactor a bit to make it cleaner
___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 142 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s55Ia4JyLrTPE54Q0:-O5wnHv35YrjAKqu9HKX:b-tofcb6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L142)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We are using a rust formatter, and the whitespace is not being introduced by the formatter.
</blockquote></details>

I've ran `cargo fmt` but it didn't change anything. I probably added some extra lines when I was refactoring. I'll remove the extra line.
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 17 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s6Fpk8m4po6BQMPDC:-O5wnp2G6ZRaiAGZO7ax:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L17)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is an outdated commit now.
</blockquote></details>

Done.

**Review by rablador — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`mullvad-ios/src/post_quantum_proxy/ios_runtime.rs` line 42 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673#-O5s4uEBCgl1R38YJ9VU:-O60P6Yc1luYIf7AalNF:b-y3820o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da1fa787c1a044c1f6bf80149e1e3f449da97283/mullvad-ios/src/post_quantum_proxy/ios_runtime.rs#L42)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Yes, I'm not super happy about this either. I think if we want to revisit this code in the future, we should take the opportunity to refactor a bit to make it cleaner
</blockquote></details>

We can stuff the extra parameters in a struct today and move the instantiation of the tokio handle back to where it was before.

**Review by rablador — COMMENTED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6673)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Pull request merged**
