### PR TITLE
Update changelog for android `2024.9-beta1`

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244#-OChJU2cAHsbUxNvokmw:-OChJE-W1ShP0oteX7zr:b1honwe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96c4c75cea8b376e353f10dca2ad0191fe6271b9/android/src/main/play/release-notes/en-US/default.txt#L1)):*
> ```help
> - Fixed a case where the app would freeze.
> ```

nit: suggested rephrasing to clarify a bit `Fixed an issue where the app could freeze (ANR).`



_Code quote:_
```help
a case
```
___
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244#-OChKpuk193TLBR49SXQ:-OChKpuk193TLBR49SXR:bl7v052) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96c4c75cea8b376e353f10dca2ad0191fe6271b9/android/src/main/play/release-notes/en-US/default.txt#L1)):*
> ```help
> - Fixed a case where the app would freeze.
> ```

No mention of EDP? :scream: 
___
*[`android/src/main/play/release-notes/en-US/default.txt` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244#-OChJh4Q2UsyIhvLVQ2w:-OChJh4Q2UsyIhvLVQ2x:b-xripvf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96c4c75cea8b376e353f10dca2ad0191fe6271b9/android/src/main/play/release-notes/en-US/default.txt#L2)):*
> ```help
> - Fixed a case where the app would freeze.
> - Fixed an issue with account expiry notifications not showing. 
> ```

Looks like a trailing space in Reviewable. Also we fixed a related bug with where we didn't handle out-of-time correctly. Maybe we can write something like:
```
Fixed a few issues related to account expiry notifications and the behavior when the account has expired. 
```
___
*[`android/src/main/play/release-notes/en-US/default.txt` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244#-OChJ3S43cJFUyRdB3jb:-OChJ3S43cJFUyRdB3jc:b-pyx549) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/96c4c75cea8b376e353f10dca2ad0191fe6271b9/android/src/main/play/release-notes/en-US/default.txt#L3)):*
> ```help
> - Fixed a case where the app would freeze.
> - Fixed an issue with account expiry notifications not showing. 
> - Improve animations.
> ```

Looks like a bad EOF in Reviewable

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244#-:-OChVBdV20vwaV7kP54T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244#-:-OChWMSZ7Ope7poS79YF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
