### PR TITLE
Upgrade the UX in Daita scenarios

### PR DESCRIPTION
**Pull request by rablador**
After discussing with the stakeholders, and the design team, we want to ship Daita with an improved UX, which will behave as following:

- If the single hop selected location already supports Daita, there is no warning shown when Daita is enabled, it just works
- If the single hop selected location does not support Daita, the "Enable anyway" warning is shown, and if the user accepts, they enter the blocked state.
- If the multihop entry selected location already supports Daita, there is no warning, it just works
- If the multihop entry selected location does not support Daita, the "Enable anyway" warning is shown

The copy that is shown for the warning text is aware of multihop, and will have a different text accordingly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
To more easily test the singlehop scenario you need to turn off the "smart routing" that's behind the debug flags in single hop picker in `RelaySelectorPicker.swift`.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-:-O61RJVE9hSH-KRO2xZZ:burhryc)* status: 0 of 8 files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O66K0Pe9etPjtoHcW56:-O66K0Pe9etPjtoHcW57:bz0irsz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L59)):*
> ```Swift
> 
>         var tunnelSettings = tunnelSettings
>         tunnelSettings.daita = settings
> ```

Is this not mutating the instance variable `tunnelSettings`?
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 227 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O66KA2qC8nMLoa-NyEb:-O66KA362EFWnJH-vR5h:b-n2xgrq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L227)):*
> ```Swift
>         case .daitaSettingIncompatibleWithMultihop:
>             """
>             DAITA isn’t available on the current entry server. After enabling, please go to \
> ```

Should this not be 2 different `NSLocalizedString`s?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O66K0Pe9etPjtoHcW56:-O66LRSMApTq-jlRMYly:be49e7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L59)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this not mutating the instance variable `tunnelSettings`?
</blockquote></details>

No, self.tunnelSettings is a struct, so it'll be copied on assignment.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 227 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O66KA2qC8nMLoa-NyEb:-O66Ma0VE25ITZTP6ur2:b7tl1x8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L227)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this not be 2 different `NSLocalizedString`s?
</blockquote></details>

These strings are used in localized strings in `AlertPresentation` below. I didn't want to make them both `NSLocalizedString` because it bloats the function body somewhat.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O66K0Pe9etPjtoHcW56:-O66NljBDoU0oLCbP0lh:b-bwrb1w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L59)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No, self.tunnelSettings is a struct, so it'll be copied on assignment.
</blockquote></details>

No, I'm wrong.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O66K0Pe9etPjtoHcW56:-O66OCHzEgksxEub8RME:b-r4p4dv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L59)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No, I'm wrong.
</blockquote></details>

No, I'm right. :D

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-:-O6Ksrsb54dYyQ_p9W0T:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils and @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O6Kslk3AF6ViMKc_sst:-O6Kslk3AF6ViMKc_ssu:bp069cz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L61)):*
> ```Swift
>         tunnelSettings.daita = settings
> 
>         let selectedRelays = try? tunnelManager.selectRelays(tunnelSettings: tunnelSettings)
> ```

We're starting to add quite some logic in that interactor, I think it would be nice to have some tests for it.

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-:-O6L-VMj9Japj_hXRwLu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O6Kslk3AF6ViMKc_sst:-O6LMlJq1HN9fTOfWD4_:b-ig1ln0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L61)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We're starting to add quite some logic in that interactor, I think it would be nice to have some tests for it.
</blockquote></details>

Do you want it to be done in this PR? (since it has already been approved by two reviewers)

**Review by buggmagnet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O6Kslk3AF6ViMKc_sst:-O6LU7NDAnGO6b0mooU0:b1qq0br) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L61)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Do you want it to be done in this PR? (since it has already been approved by two reviewers)
</blockquote></details>

We can leave it for another PR since we're bug bashing it tomorrow

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6745#-O6Kslk3AF6ViMKc_sst:-O6LioM20z_ZsQ12_Yts:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/20f11585e7c7c347798c2c05da2e1be8efee66e3/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsInteractor.swift#L61)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can leave it for another PR since we're bug bashing it tomorrow
</blockquote></details>

Done.

**Pull request merged**
