### PR TITLE
Break out generate relay list action

### PR DESCRIPTION
**Pull request by niklasberglund**
Broke out generate relay list into a separate action and use the action in `android-app.yml`. The changes can be tested by running the *Android - Build and test* workflow.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`.github/actions/android-generate-relay-list/action.yml` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995#-O9THDZvEVbpLDTAFqUQ:-O9THDZvEVbpLDTAFqUR:bo1equ2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9662d43bca8119f6df9e1273a3b9aaf41b6d26bc/.github/actions/android-generate-relay-list/action.yml#L1)):*
> ```YAML
> ---
> ```

Path looks a bit weird, maybe this is a github actions kind of thing?

`.github/actions/android-gradle-relay-list/action.yml`
This would be more intuitive to me:
`.github/actions/android-gradle-relay-list.yml`
___
*[`.github/workflows/android-app.yml` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995#-O9TH21d875vdEIlWoeB:-O9TH21d875vdEIlWoeC:bzax8lq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9662d43bca8119f6df9e1273a3b9aaf41b6d26bc/.github/workflows/android-app.yml#L135)):*
> ```YAML
>       - name: Generate relay list
>         if: steps.cache-relay-list.outputs.cache-hit != 'true'
>         uses: ./.github/actions/android-generate-relay-list
> ```

Is `./` prefix necessary?

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995)* status: all files reviewed, 1 unresolved discussion

___
*[`.github/actions/android-generate-relay-list/action.yml` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995#-O9THDZvEVbpLDTAFqUQ:-O9TbjEX6O-QgOB58v55:bj3j07u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9662d43bca8119f6df9e1273a3b9aaf41b6d26bc/.github/actions/android-generate-relay-list/action.yml#L1)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Path looks a bit weird, maybe this is a github actions kind of thing?

`.github/actions/android-gradle-relay-list/action.yml`
This would be more intuitive to me:
`.github/actions/android-gradle-relay-list.yml`
</blockquote></details>

Yes it's the structure GitHub expects. For our actions it will probably be a directory containing only `action.yml`, but an action can bundle other files.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`.github/actions/android-generate-relay-list/action.yml` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995#-O9THDZvEVbpLDTAFqUQ:-O9ToDey4-HGeflmFdrC:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9662d43bca8119f6df9e1273a3b9aaf41b6d26bc/.github/actions/android-generate-relay-list/action.yml#L1)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Yes it's the structure GitHub expects. For our actions it will probably be a directory containing only `action.yml`, but an action can bundle other files.
</blockquote></details>

:+1:

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`.github/workflows/android-app.yml` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995#-O9TH21d875vdEIlWoeB:-O9TtwtQ5TCcVRX6GVgR:bgm2q09) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9662d43bca8119f6df9e1273a3b9aaf41b6d26bc/.github/workflows/android-app.yml#L135)):*
It actually is, but I don't think it makes sense. Without it GitHub fails with:
> "the \`uses' attribute must be a path, a Docker image, or owner/repo@ref"

I think it does a very poor job at identifying paths and paths must start with `/` or `./` I guess.

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6995)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by niklasberglund** [comment]
Closing for now, we might re-evaluate this later

**Pull request closed without merging**
