### PR TITLE
Explain persistent filters in the security document

### PR DESCRIPTION
**Pull request by dlon**
This updates the security document to explain the changes made in #2168.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176)

### CODE REVIEW

**Review by mvd-ows — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[docs/security.md, line 264 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-MJCJMG9-9L7MrnQG5Rc:-MJCJMGABb9rliz5YONw:b-aqowpp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf4db2a20817fab401d2165159399cc859ed804/docs/security.md#L264)):*
> ```Markdown
> The service transitions to the [disconnected] state before exiting (i.e., normally when the OS is
> being shut down). In general, the last firewall policy is maintained when the service exits, and
> lost upon a reboot (except on Windows, cf. below). In other words, if the "Always require VPN"
> ```

what is `cf`?
___
*[docs/security.md, line 271 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-MJCJY3c3oSw5pHsI2hQ:-MJCJY3c3oSw5pHsI2hR:b-fak5io) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf4db2a20817fab401d2165159399cc859ed804/docs/security.md#L271)):*
> ```Markdown
> 
> On Windows, persistent firewall filters may be added when the service exits, in case the service
> wants to continue to enforce a blocking policy. These block any traffic occurring before the
> ```

`These filters block`

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-:-MJCYi3s8H5O6deVKS5z:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @faern and @mvd-ows)

___
*[docs/security.md, line 264 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-MJCJMG9-9L7MrnQG5Rc:-MJCak2iA7RIJCadNALB:b7ax1h2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf4db2a20817fab401d2165159399cc859ed804/docs/security.md#L264)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

what is `cf`?
</blockquote></details>

Compare/see. I've changed it to "see".
___
*[docs/security.md, line 271 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-MJCJY3c3oSw5pHsI2hQ:-MJCatbJ5PwgY_AvUHix:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf4db2a20817fab401d2165159399cc859ed804/docs/security.md#L271)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`These filters block`
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-:-MJCdbZ7722MBszucqao:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mvd-ows — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176#-:-MJR70B5610mOuyZ6GhO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
