### PR TITLE
Build warnings

### PR DESCRIPTION
**Pull request by mojganii**
This PR resolves several build warnings by addressing issues related to `Swiftlint`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792)

### CODE REVIEW

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792)* status: 0 of 12 files reviewed, 1 unresolved discussion

___
*[`ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792#-O6z3s0g4mzMmLDGHrll:-O6z3s0g4mzMmLDGHrlm:bh94wip) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5e6c963cdd5a52f37d1844297844d2f51de3f90/ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift#L22)):*
> ```Swift
> }
> 
> struct ConnectionConfigurationBuilder {
> ```

I thought maybe it's not a bade idea to integrate building WG configuration in one place to have more consistency and control over future development.

**Review by rablador — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792#-O6z3s0g4mzMmLDGHrll:-O6zXxZhD7TvgrrM4NoU:b-rqhyyw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5e6c963cdd5a52f37d1844297844d2f51de3f90/ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift#L22)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I thought maybe it's not a bade idea to integrate building WG configuration in one place to have more consistency and control over future development.
</blockquote></details>

I like it 👍

**Review by buggmagnet — APPROVED** [review]
Great initiative there !!
:lgtm:

> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792#-:-O734IHa3GbxyWC0S64i:bgvrviw)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792#-O731ZoY6U-w2YPAIkEc:-O731ZoY6U-w2YPAIkEd:bpkj8ah) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5e6c963cdd5a52f37d1844297844d2f51de3f90/ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift#L106)):*
> ```Swift
>     let ephemeralPeerNegotiationState: EphemeralPeerNegotiationState
> 
>     var name: String {
> ```

nit
This is only used for debugging purposes, I don't think we need to make this a localised string

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792#-:-O73i2mABJ8h6Wj_z071:bnfp4nl)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)

**Pull request merged**
