### PR TITLE
Update compose scrollbar appearance

### PR DESCRIPTION
**Pull request by Pururun**
- Change color, size and alpha of scrollbar
- Add rounding to scrollbar
- Add onSurfaceVariant color to theme
- Update theme to material v3
- Apply AppTheme to all screens
- Remove CollapsingToolbarTheme

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)

### CODE REVIEW

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)* status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scrollbar.kt` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsGJgt2Kt4AOrVeJTK:-NTsOfaCCLq0wbDWQGAI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86542330959269bd0083248172581561507603e9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scrollbar.kt#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest that we change this to `Code snippet with minor modifications from: https://...`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Theme.kt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsFHn75QeonpliIRos:-NTsOgKlDkVMJ3T5-Q_W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86542330959269bd0083248172581561507603e9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Theme.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be merged with the `Theme.kt` in `net.mullvad.mullvadvpn.compose.theme`?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsH3ZD3RzBeHdf1Bw1:-NTsOhmN1qDKAEMU0dVv:bqfh9ve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86542330959269bd0083248172581561507603e9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The theme `CollapsingToolbarTheme` already seem to be applied within the `AdvancedSettingScreen`. However, it's probably a good idea to place it here rather than within the `AdvancedSettingScreen`, so it would be nice if you can see if something like that is possible.
</blockquote></details>

Decided to remove `CollapsingToolbarTheme ` and replace it with `AppTheme`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Color.kt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsFU4WDtYfR7yIuI7x:-NTsOop-0b8kOi7l_vXL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86542330959269bd0083248172581561507603e9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Color.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There's already a `Color.kt` in `net.mullvad.mullvadvpn.compose.theme`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Color.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsGMgl2J4v8LltJ8b_:-NTsOoKX1VFVwpxUikJH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86542330959269bd0083248172581561507603e9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Color.kt#L5)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

color resources already exist in net.mullvad.mullvadvpn.compose.theme.Color.kt
please add new Colors to that file or use existing ones
</blockquote></details>

Done.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsQ8qrDW9XOCryPrl4:-NTsQ8qrDW9XOCryPrl5:bs6wh1s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a343a6bcf1f4cc1f80fb593814fd69d7c405e13/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt#L21)):*
> ```Kotlin
> 
> @Composable
> fun AppTheme(content: @Composable () -> Unit) {
> ```

Can we apply this in the `DeviceListFragment` as well?



_Code quote:_
```Kotlin
AppTheme
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615#-NTsQ8qrDW9XOCryPrl4:-NTsZs72-tB8qcRLxVXv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a343a6bcf1f4cc1f80fb593814fd69d7c405e13/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt#L21)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we apply this in the `DeviceListFragment` as well?
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
