### PR TITLE
Remove pingable hosts rules

### PR DESCRIPTION
**Pull request by dlon**
Instead, simply permit traffic in the tunnel when it is up. This also starts the pinger after those rules have been set.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 9 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752)* status: 9 of 17 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/firewall/windows.rs, line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752#-Ma3svt0Cpxdqy-7_gWW:-Ma3svt0Cpxdqy-7_gWX:b-9plj5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b2a852d25ba0cfe5bd06bd00f32f6ccdf6314b7/talpid-core/src/firewall/windows.rs#L175)):*
> ```XML
>         let pingable_addresses = pingable_hosts
>             .iter()
>             .map(|ip| widestring_ip(*ip))
> ```

I love the smell of removed code.
___
*[talpid-core/src/tunnel/mod.rs, line 357 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752#-Ma3t1pS362XHrxmHTOX:-Ma3t1pS362XHrxmHTOY:b-wj6j7a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9a18b6c2c65189c2172508d9d4d5681e88c0c9dd/talpid-core/src/tunnel/mod.rs#L357)):*
> ```XML
>         match self {
>             #[cfg(not(target_os = "android"))]
>             InternalTunnelMonitor::OpenVpn(_tun) => None,
> ```

I assume the metadata is not received here because OpenVPN will send it via the callback later, right? It'd be much nicer if the tunnel state machine didn't need to know the difference between OpenVPN and WireGuard here.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 8 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/mod.rs, line 357 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752#-Ma3t1pS362XHrxmHTOX:-Mb_oWb66Zt3v9M7--ED:b-t5yz5n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9a18b6c2c65189c2172508d9d4d5681e88c0c9dd/talpid-core/src/tunnel/mod.rs#L357)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I assume the metadata is not received here because OpenVPN will send it via the callback later, right? It'd be much nicer if the tunnel state machine didn't need to know the difference between OpenVPN and WireGuard here.
</blockquote></details>

Done. I've made it simpler overall.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2752)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
