### PR TITLE
Do not show account revoked banner when on account revoked screen

### PR DESCRIPTION
**Pull request by rablador**
A banner with a blocked state reason (unable to authenticate account) is shown when on the account revoked screen. This is superfluous information.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)

### CODE REVIEW

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531#-NkoKrPx2fayueOyF41s:-NkoKrPx2fayueOyF41t:b-phcfia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a886703d9ca69b37afed5122a65fc4676690843b/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L69)):*
> ```Swift
>     }
> 
>     private func updateLastTunnelError(_ tunnelState: TunnelState) -> Bool {
> ```

the function is doing two responsibilities that makes readability more complex.I suggest export these sort of conditions from your class to make is shorter and more descriptive 



_Code snippet:_
```Swift

fileprivate extension TunnelState {
    var isWaitingForConnectivity : Bool {
        self == .waitingForConnectivity(.noConnection)
    }
    
    var noNetwork : Bool {
        self == .waitingForConnectivity(.noConnection)
    }
    
    var accountIsInvalid : Bool {
        if case let .error(blockedStateReason) = self,
           blockedStateReason == .accountExpired || blockedStateReason == .deviceRevoked {
            return true
        }
        return false
    }
    
}
```
___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 229 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531#-NkoOFxI1epTW5h7crt2:-NkoOFxI1epTW5h7crt3:bgb3z7a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a886703d9ca69b37afed5122a65fc4676690843b/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L229)):*
> ```Swift
>     }
> 
>     private func localizedReasonForBlockedStateError(_ error: BlockedStateReason) -> String {
> ```

I think this part can be common along different type of objects 



_Code snippet:_
```Swift
extension BlockedStateReason : CustomStringConvertible {
    public var description: String {
        let errorString: String
        
        switch self {
        case .outdatedSchema:
            errorString = "Unable to start tunnel connection after update. Please disconnect and reconnect."
        case .noRelaysSatisfyingConstraints:
            errorString = "No servers match your settings, try changing server or other settings."
        case .invalidAccount:
            errorString = "You are logged in with an invalid account number. Please log out and try another one."
        case .deviceRevoked, .deviceLoggedOut:
            errorString = "Unable to authenticate account. Please log out and log back in."
        default:
            errorString = "Unable to start tunnel connection. Please send a problem report."
        }
        
        return NSLocalizedString(
            "BLOCKED_STATE_ERROR_TITLE",
            tableName: "Main",
            value: errorString,
            comment: ""
        )
    }
}
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531#-NkoKrPx2fayueOyF41s:-NktCWy23qd7qENfB4Y3:b-w84trw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a886703d9ca69b37afed5122a65fc4676690843b/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L69)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the function is doing two responsibilities that makes readability more complex.I suggest export these sort of conditions from your class to make is shorter and more descriptive
</blockquote></details>

As was discussed elsewhere we should probably not add concepts such as account validation to TunnelState, but I extracted some of the code to a new function to lower complexity.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 229 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531#-NkoOFxI1epTW5h7crt2:-NktDvRkDTiICjJLrMPO:b-agx1rf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a886703d9ca69b37afed5122a65fc4676690843b/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L229)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think this part can be common along different type of objects
</blockquote></details>

I don't think we need to make these strings generally accessible at this point, since they're only used here anyway. Once we need them elsewhere I agree with your suggestion.

**Review by buggmagnet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531#-NktYP8-0n7wVUqNclgr:-NktYP8-0n7wVUqNclgs:bgxbv5f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45b552d3af773be0a42a843d375741a9cb3e56d1/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L120)):*
> ```Swift
>     }
> 
>     private func tunnelError(from tunnelState: TunnelState) -> BlockedStateReason? {
> ```

Without context, it's impossible to figure out why we do this here.
Can you add a comment that explains why we filter only for `accountExpired` and `deviceRevoked` errors ?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531#-NktYP8-0n7wVUqNclgr:-Nkto38wD-vTgFKPemaf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45b552d3af773be0a42a843d375741a9cb3e56d1/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L120)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Without context, it's impossible to figure out why we do this here.
Can you add a comment that explains why we filter only for `accountExpired` and `deviceRevoked` errors ?
</blockquote></details>

Done.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

**Pull request merged**
