### PR TITLE
Draft PR for Post Quantum tunneling

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR draft shows a potential implementation of how Post Quantum key exchange would work

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774#-Npz3ekeADXrvqUBHtT9:-Npz3ekeADXrvqUBHtTA:bsq5ryr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f08309e06db929919c93f71d656bfee17721877/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L20)):*
> ```Swift
> }
> 
> public enum TunnelQuantumResistance: Codable {
> ```

Quantum resistance isn't a part of obfuscation, right?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774#-Npz1Y6U6t6pmcl9n-7W:-Npz1Y6U6t6pmcl9n-7X:bfrnjyl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f08309e06db929919c93f71d656bfee17721877/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L181)):*
> ```Swift
>         } catch {
>             // TODO: probably enter error state here
>             // TODO: OR just bounce between relays until we manage to connect to a relay ?
> ```

Probably blocked state, right? We don't bounce between relays as fallback in other parts of the app as far as I know.

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

**Review by rablador — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)* status: 17 of 24 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 507 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774#-NqBp9uu5sSXRnLlsg9p:-NqBp9uu5sSXRnLlsg9q:byhye5d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d87a7ce30815e87c533f6bba877841150cf98bd/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L507)):*
> ```Swift
>             "QUANTUM_RESISTANCE_HEADER_LABEL",
>             tableName: "Preferences",
>             value: "Quantum Resistance",
> ```

The value should be "Quantum-resistant tunnel" (to follow what the desktop is doing)
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 160 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774#-NqBpJT93ePJwG_UOCxC:-NqBpJT93ePJwG_UOCxD:b-3ybx1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d87a7ce30815e87c533f6bba877841150cf98bd/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L160)):*
> ```Swift
>                 tableName: "QuantumResistance",
>                 value: """
>                 Text on quantum resistance goes here.
> ```

This text should be
```
This feature makes the WireGuard tunnel resistant to potential attacks from quantum computers.

It does this by performing an extra key exchange using a quantum safe algorithm and mixing the result into WireGuard’s regular encryption. This extra step uses approximately 500 kiB of traffic every time a new tunnel is established.
```
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774#-Npz1Y6U6t6pmcl9n-7W:-NqBprzCBu_wEzkC4fSN:b-wjlia3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f08309e06db929919c93f71d656bfee17721877/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L181)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Probably blocked state, right? We don't bounce between relays as fallback in other parts of the app as far as I know.
</blockquote></details>

Probably, we should see what the desktop does and follow suit if possible

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 7 files at r4, 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

**Review by rablador — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5774)* status: all files reviewed, 2 unresolved discussions

**Pull request closed without merging**
