### PR TITLE
 REST: refactor

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Scope REST API types under `REST` namespace.
2. Make REST client a singleton for simplicity, since we never really need to create more than one instance.
3. Strip code of unnecessary abstractions.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: 0 of 18 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/HTTP.swift, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdFF8T6koS_pdb1yv6:-MjdFF8T6koS_pdb1yv7:b-dly54b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/HTTP.swift#L47)):*
> ```Swift
>     }
> 
>     static func ~= (lhs: Self, rhs: Int) -> Bool {
> ```

FYI this is a partial match operator, basically allowing to match `Int` against `HTTPStatus`, i.e:

```
let myStatus = 200
switch myStatus {
 case HTTPStatus.ok:
    print("Correct!")
 ...
}
```
Useful when bridging against `HTTPURLResponse` that contains `Int` `statusCode`

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: 0 of 18 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/ServerRelaysResponse.swift, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdGfXF4EwIMu4yQ03O:-MjdGfXF4EwIMu4yQ03P:b-kddhqr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/ServerRelaysResponse.swift#L10)):*
> ```Swift
> 
> import Foundation
> import struct Network.IPv4Address
> ```

FYI both `NetworkExtension` and `Network` export types with the same name. So to avoid collisions in the packet tunnel, I only import types we need here.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: 0 of 18 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdHYUoE-P0Nd0lEFNh:-MjdHYUoE-P0Nd0lEFNi:by2p2f9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift#L10)):*
> ```Swift
> 
> import Foundation
> import Security
> ```

FYI this import is needed to make `SecXXX` family of functions available in the scope. Previously we used to have this import in `MullvadRest.swift` and I don't know how but it worked cross-file, although it should not have.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: 0 of 18 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/RESTClient.swift, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdIBbA5x_FxjhpU60v:-MjdIBbA5x_FxjhpU60w:boq4rje) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/RESTClient.swift#L49)):*
> ```Swift
> 
>             return dataTaskPromise(request: request)
>                 .mapError(self.mapNetworkError)
> ```

FYI technically I map `URLError` to `REST.Error` in every REST call, so I could as well move it to the `dataTaskPromise()` to avoid repetition.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/REST/HTTP.swift, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdFF8T6koS_pdb1yv6:-MjeLV1969UES9Rrsg9W:bb94rvn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/HTTP.swift#L47)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI this is a partial match operator, basically allowing to match `Int` against `HTTPStatus`, i.e:

```
let myStatus = 200
switch myStatus {
 case HTTPStatus.ok:
    print("Correct!")
 ...
}
```
Useful when bridging against `HTTPURLResponse` that contains `Int` `statusCode`
</blockquote></details>

What's the difference compared to this one a few lines above
```
    static func == (lhs: Self, rhs: Int) -> Bool {
        return lhs.rawValue == rhs
    }

``` 

Is it just that `~=` is used by the switch-statement?
___
*[ios/MullvadVPN/REST/RESTClient.swift, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjheN_rDWyvcx4HRhmK:-MjheN_s2_dJMxzkQ2DM:b-na5hcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/RESTClient.swift#L322)):*
> ```Swift
>         }
> 
>         private func makeURLRequest(method: HTTPMethod, path: String) -> URLRequest {
> ```

The name makes it sound like the request is performed here. How about something like `createURLRequest`?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/REST/HTTP.swift, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdFF8T6koS_pdb1yv6:-MjhiPSuEtKul8TjHejG:bh86qz1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/HTTP.swift#L47)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

What's the difference compared to this one a few lines above
```
    static func == (lhs: Self, rhs: Int) -> Bool {
        return lhs.rawValue == rhs
    }

``` 

Is it just that `~=` is used by the switch-statement?
</blockquote></details>

Exactly. `~=` is called by `switch` statements, while `==` is used when you compare the `HTTPStatus` against `Int`.
___
*[ios/MullvadVPN/REST/RESTClient.swift, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjheN_rDWyvcx4HRhmK:-MjhjCg8DGBxmPMVGmPQ:b-5m2vs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/RESTClient.swift#L322)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The name makes it sound like the request is performed here. How about something like `createURLRequest`?
</blockquote></details>

`URLRequest` itself is just a containe, it cannot perform networking. 

`make` prefix is commonly used instead of `create` in Swift, so I opt-in to follow the same naming convention. For example `makeIterator()` is used in standard library. There are more cases:

https://developer.apple.com/search/?q=make

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/REST/RESTClient.swift, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjheN_rDWyvcx4HRhmK:-MjhkseR8Bjo9U5VeS4A:bh0fzfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/RESTClient.swift#L322)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`URLRequest` itself is just a containe, it cannot perform networking. 

`make` prefix is commonly used instead of `create` in Swift, so I opt-in to follow the same naming convention. For example `makeIterator()` is used in standard library. There are more cases:

https://developer.apple.com/search/?q=make
</blockquote></details>

Although it's really minor. I have just changed that and pushed the change.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-:-Mjhmje--0ZbdkNxKM7F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/HTTP.swift, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjdFF8T6koS_pdb1yv6:-Mjhmf782snSyFYooCYP:b-6mhyx0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/HTTP.swift#L47)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Exactly. `~=` is called by `switch` statements, while `==` is used when you compare the `HTTPStatus` against `Int`.
</blockquote></details>

Great, thanks!
___
*[ios/MullvadVPN/REST/RESTClient.swift, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjheN_rDWyvcx4HRhmK:-Mjhm76G8HWiadLhFiKR:bbsxpan) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/RESTClient.swift#L322)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Although it's really minor. I have just changed that and pushed the change.
</blockquote></details>

Okay, I think what made me think about this is that "request" is both a noun and a verb. For "Itarator" it's just a noun and can't be interpreted in the same way I interpreted `makeURLRequest`. If it's common to name functions like this I'm fine with it though. I'm fine with either naming so you can pick which one you prefer.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/RESTClient.swift, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2962#-MjheN_rDWyvcx4HRhmK:-Mjhn5VA6r4m7MDrMjh5:bv6j26h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6fddef9815a6f309391bea38b3a4e2820617484/ios/MullvadVPN/REST/RESTClient.swift#L322)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Okay, I think what made me think about this is that "request" is both a noun and a verb. For "Itarator" it's just a noun and can't be interpreted in the same way I interpreted `makeURLRequest`. If it's common to name functions like this I'm fine with it though. I'm fine with either naming so you can pick which one you prefer.
</blockquote></details>

Right. I think both are fine. So let's stick to `create`.

**Pull request merged**
