### PR TITLE
Fix mullvad-api for iOS

### PR DESCRIPTION
**Pull request by dlon**
Also, build mullvad-api in the CI workflow.

Close IOS-950.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7238)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7238)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7238#-:-OCbYTaA0MwrZDwiyNMP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7238)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7238)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
