### PR TITLE
E2E tests: remove cargo dependency

### PR DESCRIPTION
**Pull request by magnus-lindstrom**
# What is introduced with this PR

This commit enables the usage of the dist/ directory, and also adds mullvad-version to it so that test-by-version.sh can operate without rust installed at all.

Also added a /dev/null redirect of a cd output so that one's able to use CDPATH while running the tests.

# Why this is wanted

I would like to be able to run the e2e tests on a VM without having to compile the binaries at all, since that increases the disk size necessary for running the tests. The disk space needed drops by 20-30G this way.

# How to test

1. Build all executables with `scripts/container-run.sh scripts/build.sh`.
2. Clone mullvadvpn-app on a system without rust installed.
3. Copy the dist folder that was created in step 1 to mullvadvpn-app/test/dist
4. Run the end to end tests using test-by-version.sh, which should not fail due to cargo missing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632)

### CODE REVIEW

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

@dlon @Serock3  What do you think?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632#-:-O4PNvwc-joCG0AOO80D:bn5h765)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632#-:-O4PuUe84_-xrKO1GpRH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632)* status: all files reviewed, 2 unresolved discussions (waiting on @magnus-lindstrom)

___
*[`test/test-by-version.sh` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632#-O4PuMmZ6hiaKh8GEZpx:-O4PuMmZ6hiaKh8GEZpy:b-ljmhi3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15e0623c82917720ba5e15373d19bff093fb6c03/test/test-by-version.sh#L17)):*
> ```Shell
>     echo "  - TEST_REPORT : path to save the test results in a structured format"
>     echo "Optional environment variables:"
>     echo "  - TEST_DIST_DIR: Relative path to a directory with prebuilt binaries as produced by scripts/build.sh."
> ```

"Optional environment variables:" is echoed twice :blush:



_Code quote:_
```Shell
    echo "Optional environment variables:"
    echo "  - APP_VERSION: The version of the app to test (defaults to the latest stable release)"
    echo "  - APP_PACKAGE_TO_UPGRADE_FROM: The package version to upgrade from (defaults to none)"
    echo "  - TEST_FILTERS: specifies which tests to run (defaults to all)"
    echo "  - TEST_REPORT : path to save the test results in a structured format"
    echo "Optional environment variables:"
    echo "  - TEST_DIST_DIR: Relative path to a directory with prebuilt binaries as produced by scripts/build.sh."
```
___
*[`test/scripts/test-utils.sh` line 245 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632#-O4Pudb12zy9oZnQuggq:-O4Pudb12zy9oZnQuggr:b-crx5d5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15e0623c82917720ba5e15373d19bff093fb6c03/test/scripts/test-utils.sh#L245)):*
> ```Shell
> 
>         echo "**********************************"
>         echo "* Using test-runner in dist/"
> ```

Replace `dist/` with `$TEST_DIST_DIR` :blush:



_Code quote:_
```Shell
echo "* Using test-runner in dist/"
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632)* status: all files reviewed, 1 unresolved discussion (waiting on @magnus-lindstrom)

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6632#-:-O4QCsnI0N_WyrA8twO9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
