### PR TITLE
Fix long method

### PR DESCRIPTION
**Pull request by Rawa**
This PR splits a bunch of long methods that result in detekt linting issues.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898#-NsCulzu6zP2pS3GnZMe:-NsCulzu6zP2pS3GnZMf:bpu76og) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50804eed5ecc9040ccd73bacfe804229238fc9b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L111)):*
> ```Kotlin
>     val connectViewModel: ConnectViewModel = koinViewModel()
> 
>     val state by connectViewModel.uiState.collectAsStateWithLifecycle()
> ```

I guess this will not be considered a change when we merge that other PR?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898#-NsCuiyP9OQHEfQuFTwU:-NsCuiyP9OQHEfQuFTwV:b-aj0oa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50804eed5ecc9040ccd73bacfe804229238fc9b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L165)):*
> ```Kotlin
> 
> @Composable
> private fun ConnectScreen(
> ```

This would break tests no?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898#-NsCulzu6zP2pS3GnZMe:-NsD534O5NDDalqKzuJY:btqqu5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50804eed5ecc9040ccd73bacfe804229238fc9b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L111)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess this will not be considered a change when we merge that other PR?
</blockquote></details>

Correct.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898#-NsCuiyP9OQHEfQuFTwU:-NsD506NEok94f1qdRRt:bnt8ap7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50804eed5ecc9040ccd73bacfe804229238fc9b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L165)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This would break tests no?
</blockquote></details>

Ah yes, correct. I'll fix it.

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898#-:-NsE7ub_-tzs-LD26wdo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
