### PR TITLE
Refactor to use preview parameter providers

### PR DESCRIPTION
**Pull request by kl**
Change files that have multiple compose previews to use a single preview with preview parameters.

Fixes: DROID-1077, DROID-1081, DROID-1083

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752#-O65hhVE1d9ErCC5C22u:-O65hhVE1d9ErCC5C22v:byfsva3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe484930b1abaaa5ff4164a4ec16d4eb2ce29085/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L89)):*
> ```Kotlin
> @Preview
> @Composable
> private fun PreviewBase(
> ```

I think it would be more in line with rest of views to call the function `PreviewLoginScreen`

**Review by Pururun — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752)* status: all files reviewed, 4 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/LoginUiStateParameterProvider.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752#-O65iLm84Y68YCk6bzHT:-O65iLm94Bj-EJmBpZBv:b-za2wf0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe484930b1abaaa5ff4164a4ec16d4eb2ce29085/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/LoginUiStateParameterProvider.kt#L8)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.compose.state.LoginUiState
> 
> class LoginUiStateParameterProvider : PreviewParameterProvider<LoginUiState> {
> ```

Nit: Should be `LoginUiStatePreviewParameterProvider`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ReportProblemUiStateParameterProvider.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752#-O65iamm-1a9jyrnvqWV:-O65iamn6rNyIglDOfvX:brjcm9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe484930b1abaaa5ff4164a4ec16d4eb2ce29085/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ReportProblemUiStateParameterProvider.kt#L8)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.viewmodel.SendingReportUiState
> 
> class ReportProblemUiStateParameterProvider : PreviewParameterProvider<ReportProblemUiState> {
> ```

Nit: Should be `ReportProblemUiStatePreviewParameterProvider`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/DeviceListUiStateParameterProvider.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752#-O65i7nO2do6e_YzI4My:-O65i7nO2do6e_YzI4Mz:byw859u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe484930b1abaaa5ff4164a4ec16d4eb2ce29085/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/DeviceListUiStateParameterProvider.kt#L8)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.model.GetDeviceListError
> 
> class DeviceListUiStateParameterProvider : PreviewParameterProvider<DeviceListUiState> {
> ```

Nit: Should be be `DeviceListUiStatePreviewParameterProvider`

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752#-:-O66brBt8dRUJ3VW37KW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

**Review by Rawa — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6752#-:-O66dxPL8-EViKZfycgo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
