### PR TITLE
Fix inconsistent spacing between paragraphs

### PR DESCRIPTION
**Pull request by rablador**
A few places in the app has inconsistent spacing between paragraphs. This PR addresses that and creates a common style to share.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422#-O0OkaVNDRsvA-XYGgeT:-O0OkaVNDRsvA-XYGgeU:bm8gx0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed5bd3190d46e2f82383db462ef928b9f55d45d7/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L416)):*
> ```Swift
>             guard let self else { return }
>             router.dismissAll(.primary, animated: true)
>             DispatchQueue.main.async {
> ```

Opportunistically fixed an unrelated bug where logging out from add voucher screen would crash due to doing UI work on background thread.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422#-O0hM2P0DkxPE8UgSuFM:-O0hM2P0DkxPE8UgSuFN:b-rm91pg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f511be6302af0f17e1cb1dd3de727938f32c7f01/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSViewController.swift#L116)):*
> ```Swift
>                 domains or websites known for distributing ads, malware, trackers and more. \
>                 This might cause issues on certain websites, services, and apps.
> ```

I think this new line was intentionally there 

Before


After

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422#-O0hM2P0DkxPE8UgSuFM:-O0hwhBy2g0PIpEUtATm:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f511be6302af0f17e1cb1dd3de727938f32c7f01/ios/MullvadVPN/View%20controllers/VPNSettings/CustomDNSViewController.swift#L116)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think this new line was intentionally there 

Before


After

</blockquote></details>

Fixed

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6422#-:-O0mPrYu33VoxCzwOk-L:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
