### PR TITLE
Simplify JNI interface for Mullvad daemon

### PR DESCRIPTION
**Pull request by dlon**
This reduces the JNI interface for the Mullvad daemon to a start/init function and a stop function. `mullvad-jni` was also refactored.

Fix DROID-1050.
Fix DES-760.

This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
:star: Good job!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-:-O-lFPuOCFxrH2egGe6x:bc1svei)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-lBB227SeBKoJQsPI3:-O-lBB227SeBKoJQsPI4:b67qb6d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/818f00121815954e26886e85628545d0ec2f3c2e/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L46)):*
> ```Kotlin
> 
>     suspend fun shutdown() =
>         withContext(Dispatchers.IO) {
> ```

We should check if `withContext` can be safely removed or not.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-ovGRO7_oRO4AuTvW_:-O-ovGRO7_oRO4AuTvWa:b246til) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L33)):*
> ```Kotlin
>         migrateSplitTunneling.migrate()
> 
>         mullvadDaemonHandle = start(
> ```

Are there any guarantees for the return value that we can assert on the kotlin side? For instance I assume it shouldn't return zero or negative numbers? We might want to wrap the Long in a value class to help with that.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-ovGRO7_oRO4AuTvW_:-O-pUXOjDrP2Goa9KvES:b-cn20g8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are there any guarantees for the return value that we can assert on the kotlin side? For instance I assume it shouldn't return zero or negative numbers? We might want to wrap the Long in a value class to help with that.
</blockquote></details>

@Pururun what do you think about doing something like this? https://github.com/mullvad/mullvadvpn-app/commit/3c7ab1b6ee2e3e2cba8fd298b914685c931e17f1

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-ovGRO7_oRO4AuTvW_:-O-pfLvMD6msoaIAGaAw:b-knkef5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@Pururun what do you think about doing something like this? https://github.com/mullvad/mullvadvpn-app/commit/3c7ab1b6ee2e3e2cba8fd298b914685c931e17f1
</blockquote></details>

The above commit should probably be `require(value != 0)` rather than `require(value > 0)` if we decide to keep it, but we're now looking at removing the handle completely instead

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`mullvad-jni/src/lib.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-pi9cZ9fOTfTvS3Nsr:-O-pi9cZ9fOTfTvS3Nss:b3kl9ky) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/mullvad-jni/src/lib.rs#L26)):*
> ```XML
> const LOG_FILENAME: &str = "daemon.log";
> 
> static DAEMON_CONTEXT: Mutex<Option<DaemonContext>> = Mutex::new(None);
> ```

Nit Would be a nice with a small doc-comment explaining that `DAEMON_CONTEXT` is initialized/deinitialized with `.._init` and `.._shutdown` respectively :blush:



_Code quote:_
```XML
static DAEMON_CONTEXT: Mutex<Option<DaemonContext>> = Mutex::new(None);
```
___
*[`mullvad-jni/src/lib.rs` line 82 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-pkiE58HRlgfcIGYn6:-O-pkiE58HRlgfcIGYn7:b-9165bx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/mullvad-jni/src/lib.rs#L82)):*
> ```XML
>     .map(|daemon| {
>         *ctx = Some(daemon);
>     })
> ```

Nit I don't really like the use of `map` to access the inner value of a `Result` in order to only perform a side-effect. Since we're not transforming the data contained in the `Result` from `start`, I think a plain `match`-statement is more suitable here

```rust
match start(
    env,
    vpnService,
    rpcSocketPath,
    filesDirectory,
    cacheDirectory,
    apiEndpoint,
) {
    Ok(daemon) => {
        *ctx = Some(daemon);
    }
    Err(err) => {
        env.throw(err.to_string())
            .expect("Failed to throw exception");
    }
};
```



_Code quote:_
```XML
    .map(|daemon| {
        *ctx = Some(daemon);
    })
```

**Review by Pururun — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`mullvad-jni/src/lib.rs` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-l1vJaCx5OhK5_Gwy7:-O-pn29P9-rgH4bdoHPW:b-hggpny) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/mullvad-jni/src/lib.rs#L4)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think `HashSet` can safely be removed from `classes.rs`, no? Is it still used on the Android side? @Pururun
</blockquote></details>

I think it is used by the connectivity listener that does some jni communication with the daemon?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @dlon and @MarkusPettersson98)

___
*[`mullvad-jni/src/lib.rs` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-l1vJaCx5OhK5_Gwy7:-O-prQNaC1Os4AhKToJo:b-tq5jyb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/mullvad-jni/src/lib.rs#L4)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think it is used by the connectivity listener that does some jni communication with the daemon?
</blockquote></details>

There is not jni communication using `HashSet` in connectivity listener, so this should be safe to remove.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @dlon, @MarkusPettersson98, and @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-ovGRO7_oRO4AuTvW_:-O-puANE77LB0StKQ6-4:b-2q4isx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The above commit should probably be `require(value != 0)` rather than `require(value > 0)` if we decide to keep it, but we're now looking at removing the handle completely instead
</blockquote></details>

This comment is no longer relevant since we're now going in more of a singleton direction

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @dlon, @MarkusPettersson98, and @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-puylxC9r9zm7ejYtW:-O-puylyCYtZshFh_pPA:b-a4u2x5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L30)):*
> ```Kotlin
>         migrateSplitTunneling.migrate()
> 
>         init(
> ```

nit: I suggest naming something else than `init` since it can be confused with kotlin `init` blocks



_Code quote:_
```Kotlin
init
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 8 of 13 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98 and @Pururun)

___
*[`mullvad-jni/src/lib.rs` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-l1vJaCx5OhK5_Gwy7:-O-psgRh5lVr50TToFQN:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/mullvad-jni/src/lib.rs#L4)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

There is not jni communication using `HashSet` in connectivity listener, so this should be safe to remove.
</blockquote></details>

Removed.
___
*[`mullvad-jni/src/lib.rs` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-oZL3j1QubPSIZN-Z_:-O-q1yaP0hCdLjRMXKhw:ba6dgtd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/mullvad-jni/src/lib.rs#L84)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

IMHO, I think boxing the `DaemonContext` is a concern of this function and not `start`. So if we could both box the `DaemonContext` and turn it into a raw pointer here that would be great :)
</blockquote></details>

Agreed, but no longer relevant since the handle is gone.
___
*[`mullvad-jni/src/lib.rs` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-pi9cZ9fOTfTvS3Nsr:-O-q2S1W6rEWRR5lX6wL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/mullvad-jni/src/lib.rs#L26)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Would be a nice with a small doc-comment explaining that `DAEMON_CONTEXT` is initialized/deinitialized with `.._init` and `.._shutdown` respectively :blush:
</blockquote></details>

Done.
___
*[`mullvad-jni/src/lib.rs` line 82 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-pkiE58HRlgfcIGYn6:-O-psyDU3a7oK_ffzJzO:b-houjfe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/mullvad-jni/src/lib.rs#L82)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit I don't really like the use of `map` to access the inner value of a `Result` in order to only perform a side-effect. Since we're not transforming the data contained in the `Result` from `start`, I think a plain `match`-statement is more suitable here

```rust
match start(
    env,
    vpnService,
    rpcSocketPath,
    filesDirectory,
    cacheDirectory,
    apiEndpoint,
) {
    Ok(daemon) => {
        *ctx = Some(daemon);
    }
    Err(err) => {
        env.throw(err.to_string())
            .expect("Failed to throw exception");
    }
};
```
</blockquote></details>

Done. (Kind of. Doesn't apply anymore.)

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 6 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @dlon, @MarkusPettersson98, and @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-q4lum7nOls_LJf34W:-O-q4lum7nOls_LJf34X:bhtazwg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.service
> ```

Amazing improvement, good job! :star_struck:

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-:-O-q5smdB21_o3rP546P:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-lBB227SeBKoJQsPI3:-O-q5K114lYF7YTC5vaQ:btdbqyi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/818f00121815954e26886e85628545d0ec2f3c2e/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L46)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

We should check if `withContext` can be safely removed or not.
</blockquote></details>

No longer relevant
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 200 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-q5T-n8q8WvO7LGQyF:-O-q5T-n8q8WvO7LGQyG:b-sgy3ic) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ec35723e6fd73781d57224a89abf2cf89da70d8/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L200)):*
> ```Kotlin
> 
>         // Shutting down the daemon gracefully
>         MullvadDaemon.shutdown()
> ```

I think this is fine for now, but we should keep in mind if we find any issues in the future that we might want to wait for the daemon to shutdown before destroying the service.

**Review by albin-mullvad — APPROVED** [review]
Android/Kotlin side looks good to me! :lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-:-O-q7PPeCjgOFx4zMv8v:b-yl9lsw)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt` line 200 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-q5T-n8q8WvO7LGQyF:-O-q64Gl9GCW-aWkH2hk:bflb0nd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ec35723e6fd73781d57224a89abf2cf89da70d8/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L200)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think this is fine for now, but we should keep in mind if we find any issues in the future that we might want to wait for the daemon to shutdown before destroying the service.
</blockquote></details>

Yeah, I think this is fine. Let's focus on testing it thourougly before and after merge. Also worth mentioning is that there are regardless no guarantees that the system will let the `onDestroy` complete if I recall correctly

**Review by Rawa — APPROVED** [review]
:clap: great work! :lgtm: 

> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-:-O083OHw1rM72tk02tIa:bpxdh0e)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-q4lum7nOls_LJf34W:-O082mN45h3iy1V6Raqu:b476zk6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4bd8c53e33ce4c212175a5ea00b7b1407b15739/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Amazing improvement, good job! :star_struck:
</blockquote></details>

Indeed, love it!

**Review by MarkusPettersson98 — APPROVED** [review]
So good! :rocket: :star: :lgtm: 

> Reviewed 2 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-:-O08Cq6v5ygwYqPy6pQ3:b5ishwb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`mullvad-jni/src/lib.rs` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-O-oZL3j1QubPSIZN-Z_:-O08CMeg4fvKButxbeo0:b-j1we20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d88bc09828ad14f485ac55db2e478d1b37842c84/mullvad-jni/src/lib.rs#L84)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Agreed, but no longer relevant since the handle is gone.
</blockquote></details>

:raised_hands:

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @MarkusPettersson98 and @Rawa)

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6385#-:-O09jrXu2HFqHeYg0a10:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
