### PR TITLE
Add Wintun logger

### PR DESCRIPTION
**Pull request by dlon**
Update that passes on Wintun logs to daemon.log. This should make it easier to figure out the cause of some errors.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510#-MUOdFzd89BLzhok941E:-MUOdFzd89BLzhok941F:b30s6ls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79de78cd2275f6eefd180c7eb6d76c02b395d521/talpid-core/src/tunnel/openvpn/mod.rs#L289)):*
> ```XML
> impl<C: OpenVpnBuilder> Drop for OpenVpnMonitor<C> {
>     fn drop(&mut self) {
>         WintunLoggerDropper(());
> ```

This is IMO not a very idiomatic way of dropping something. You create an instance for the sole purpose of having it instantly run its drop glue? Can't you just make the `set_logger` call directly here instead of in the drop for `WintunLoggerDropper`?

With this design you have to use `mem::forget` to actively avoid the drop in another place. Seems like a lot of extra complexity.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510#-MUOdFzd89BLzhok941E:-MUOgcz053BXYKF13mHe:bathh2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79de78cd2275f6eefd180c7eb6d76c02b395d521/talpid-core/src/tunnel/openvpn/mod.rs#L289)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is IMO not a very idiomatic way of dropping something. You create an instance for the sole purpose of having it instantly run its drop glue? Can't you just make the `set_logger` call directly here instead of in the drop for `WintunLoggerDropper`?

With this design you have to use `mem::forget` to actively avoid the drop in another place. Seems like a lot of extra complexity.
</blockquote></details>

I want to make sure that `set_logger(None)` is also called if anything fails early in `OpenVpnMonitor::start`. That is even if `OpenVpnMonitor`'s destructor is never called.

Would it be better to wrap the constructor in another method?

```rust
fn start() -> Result<Monitor> {
    self.start_inner().map_err(|error| {
        set_logger(None);
        error
    })
}
```

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510#-MUOdFzd89BLzhok941E:-MUOn5lO9YP5vF0tgi1s:b-f7p4ux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79de78cd2275f6eefd180c7eb6d76c02b395d521/talpid-core/src/tunnel/openvpn/mod.rs#L289)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I want to make sure that `set_logger(None)` is also called if anything fails early in `OpenVpnMonitor::start`. That is even if `OpenVpnMonitor`'s destructor is never called.

Would it be better to wrap the constructor in another method?

```rust
fn start() -> Result<Monitor> {
    self.start_inner().map_err(|error| {
        set_logger(None);
        error
    })
}
```
</blockquote></details>

Or store the "logger" in the `OpenVpnMonitor`. Then you properly get dropping when the monitor is dropped and you don't have to work around it. Create a `WintunLogger` struct that calls `set_logger` in the constructor and in the drop impl. Then you have properly wrapped the C interface in a structs lifetime. You just need to keep an instance of this `WintunLogger` around for as long as the monitor.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510#-MUOdFzd89BLzhok941E:-MUSfMJg0rTGLPWSALBZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79de78cd2275f6eefd180c7eb6d76c02b395d521/talpid-core/src/tunnel/openvpn/mod.rs#L289)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Or store the "logger" in the `OpenVpnMonitor`. Then you properly get dropping when the monitor is dropped and you don't have to work around it. Create a `WintunLogger` struct that calls `set_logger` in the constructor and in the drop impl. Then you have properly wrapped the C interface in a structs lifetime. You just need to keep an instance of this `WintunLogger` around for as long as the monitor.
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510#-MUOdFzd89BLzhok941E:-MUSlGda0vLFEZ23KJTU:b6x4skj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79de78cd2275f6eefd180c7eb6d76c02b395d521/talpid-core/src/tunnel/openvpn/mod.rs#L289)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is way better IMO! But if you want the RAII pattern I think it would look better to have `WintunDll::activate_logging() -> LoggerHandle` that unsets the logger on drop. This is a bit of a nitpick. But the current way of `WintunLogger::new(handle) -> Self` is more unclear to me. Currently it's like if you had to use mutexes like `MutexGuard::new(mutex)` to be able to lock a mutex.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 289 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510#-MUOdFzd89BLzhok941E:-MUT11Db5qXwvL-_sAmg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79de78cd2275f6eefd180c7eb6d76c02b395d521/talpid-core/src/tunnel/openvpn/mod.rs#L289)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is way better IMO! But if you want the RAII pattern I think it would look better to have `WintunDll::activate_logging() -> LoggerHandle` that unsets the logger on drop. This is a bit of a nitpick. But the current way of `WintunLogger::new(handle) -> Self` is more unclear to me. Currently it's like if you had to use mutexes like `MutexGuard::new(mutex)` to be able to lock a mutex.
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
