### PR TITLE
Prepare android/2024.8-beta2

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/CHANGELOG.md` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073#-OA1ZrlB4Lpfufcr1wQL:-OA1ZrlB4Lpfufcr1wQM:b-j2z1u9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5adf4d6123066f6f6f56ce80a8542e29e9abc81/android/CHANGELOG.md#L30)):*
I suggest rephrasing a bit to avoid anyone misinterpreting it as a permanent connection loss or that it would leak.

> Improve connection stability when roaming while using Shadowsocks.



_Code quote:_
```Markdown
would lead to loss of connection.
```
___
*[`android/src/main/play/release-notes/en-US/default.txt` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073#-OA1aKWw19xS3c_MOz-i:-OA1aKWw19xS3c_MOz-j:b-djva8u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5adf4d6123066f6f6f56ce80a8542e29e9abc81/android/src/main/play/release-notes/en-US/default.txt#L2)):*
I suggest mentioning that result of this for anyone that aren't aware of what MTU is. Perhaps something like this:

> Fix MTU calculation to avoid connectivity issues when using some specific settings.

We could mention also mention which specific setting.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073#-OA1aKWw19xS3c_MOz-i:-OA1gHgz15at1s7ueEZn:b-bzpmv6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5adf4d6123066f6f6f56ce80a8542e29e9abc81/android/src/main/play/release-notes/en-US/default.txt#L2)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest mentioning that result of this for anyone that aren't aware of what MTU is. Perhaps something like this:

> Fix MTU calculation to avoid connectivity issues when using some specific settings.

We could mention also mention which specific setting.
</blockquote></details>

Updated the string to be more clear.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/src/main/play/release-notes/en-US/default.txt` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073#-OA1aKWw19xS3c_MOz-i:-OA1hbcb3OzRnG53nNbk:bajw0ta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5adf4d6123066f6f6f56ce80a8542e29e9abc81/android/src/main/play/release-notes/en-US/default.txt#L2)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Updated the string to be more clear.
</blockquote></details>

Good improvement, but I still think we can clarify a bit further what the impact would be for a user

**Review by Pururun — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
