### PR TITLE
App overhaul

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR is insane but I can't make it shorter.

1. Renames and refactors `JsonRpc-Ipc-ws` to `JsonRpcTransport` – low level transport for JsonRpc backed by Websocket

2. Renames and refactors `IpcFacade` to `DaemonRpc` which leverages `JsonRpcTransport` to talk to `mullvad-daemon`, but provides Facade-like convenience methods for querying daemon.

3. Connection to the daemon is not created automatically anymore, instead we call `.connect()` and wait until connected.

4. Once connected, the `Backend` runs series of calls such as to query current state, *important* registers RPC subscriptions, authenticates with the daemon (once), performs so called 'autologin', queries location/IP and settings.

5. New location/IP are automatically received on state change.

6. Account history is only loaded once upon connecting to daemon and then on logout only, since that's the only two places when user may end up on the login screen. This behavior will be changed later and I am planning to move the fetch into Login component.

7. New JSONRPC transport tests using `mock-websocket` server. This by far looks easier to understand, not ideal but the interface is TDD friendly enough to me.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)

### CODE REVIEW

**Comment by jvff** [comment]
Reviewed 37 of 37 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

---

*[app/app.js, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG6CVjI37o0VAmnn3kt:-LG6CVjI37o0VAmnn3ku:b-cpl49j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae19581b26e2e161a24fe9d232850d616ef630eb/app/app.js#L30)):*
> ```JavaScript
>         resolve(credentials);
>       });
>       ipcRenderer.send('daemon-connection');
> ```

If I understood things correctly, there are two distinct `daemon-connection` messages. One to request the credentials and the other to receive the credentials. Wouldn't it be better to rename the events so they become clearer? Maybe something like `discover-daemon-connection` and `daemon-connection-ready`?

---

*[app/lib/rpc-address-file.js, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG5eqO47fWAlPG8lxxc:-LG5eqO620FBn36B28fC:b-yvuq9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae19581b26e2e161a24fe9d232850d616ef630eb/app/lib/rpc-address-file.js#L12)):*
> ```JavaScript
> const POLL_INTERVAL = 200;
> 
> const appDirectoryName = 'Mullvad VPN';
> ```

Wouldn't it be safer to keep this as `appName` or something in a centralized place?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by pronebird** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @pronebird and @jvff)

---

*[app/app.js, line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG6CVjI37o0VAmnn3kt:-LG9f6lcDhGka-4JLzsW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae19581b26e2e161a24fe9d232850d616ef630eb/app/app.js#L30)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

If I understood things correctly, there are two distinct `daemon-connection` messages. One to request the credentials and the other to receive the credentials. Wouldn't it be better to rename the events so they become clearer? Maybe something like `discover-daemon-connection` and `daemon-connection-ready`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by pronebird** [comment]
Review status: 32 of 40 files reviewed, 2 unresolved discussions (waiting on @jvff and @pronebird)

---

*[app/lib/rpc-address-file.js, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG5eqO47fWAlPG8lxxc:-LG9rKse84cgKW9ZTrKV:bly34y7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae19581b26e2e161a24fe9d232850d616ef630eb/app/lib/rpc-address-file.js#L12)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Wouldn't it be safer to keep this as `appName` or something in a centralized place?
</blockquote></details>

Good point! Electron support a `productName` option in `package.json` which unlike `name` field can contain spaces and any letter casing. It also affects what Electron returns in calls to `app.getName` and `app.getPath`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by pronebird** [comment]
Review status: 32 of 40 files reviewed, 2 unresolved discussions (waiting on @jvff)

---

*[app/main.js, line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG9uyd74QNrSSAarjsk:-LG9uyd8DQM3k4R2OhCZ:bkxj8sc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/338361f43998f4122eee08c053842ad3491c3357/app/main.js#L29)):*
> ```JavaScript
>     this._initLogging();
> 
>     log.info(`Running version ${app.getVersion()}`);
> ```

FYI it returns the version from `package.json` :grin: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by pronebird** [comment]
Review status: 32 of 40 files reviewed, 2 unresolved discussions (waiting on @jvff)

---

*[app/main.js, line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG9vC4-35PCkpy47wWp:-LG9vC40AApE_My685eZ:b-4njl5f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/338361f43998f4122eee08c053842ad3491c3357/app/main.js#L73)):*
> ```JavaScript
>     }
> 
>     log.debug(`Logging to ${this._logFilePath}`);
> ```

FYI Backend outputs the same line, so I thought it would be great to do the same, also for my sanity 

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by pronebird** [comment]
Review status: 32 of 40 files reviewed, 2 unresolved discussions (waiting on @jvff)

---

*[app/main.js, line 87 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG9vL2HAl_3vVt99XAm:-LG9vL2HAl_3vVt99XAn:byuw0h1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/338361f43998f4122eee08c053842ad3491c3357/app/main.js#L87)):*
> ```JavaScript
>       case 'darwin':
>         // macOS: ~/Library/Logs/{appname}
>         return path.join(app.getPath('home'), 'Library/Logs', app.getName());
> ```

FYI `app.getName()` returns `productName` from `package.json`, thus now we have a single place where it's defined. All special paths returned from `app.getPath()` are also affected by this field, so it's great!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by jvff** [comment]
Reviewed 8 of 8 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[app/main.js, line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256#-LG9uyd74QNrSSAarjsk:-LGAIGMSCP5hOBCwonQO:btojbfd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/338361f43998f4122eee08c053842ad3491c3357/app/main.js#L29)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

FYI it returns the version from `package.json` :grin: 
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/256)*

**Pull request merged**
