### PR TITLE
Add 30, 50, 150 and 300 px versions of the icon

### PR DESCRIPTION
**Pull request by faern**
Here comes the resolutions you needed. I wish I could add the svg source file as well. But I have some problem with that at the moment so will do that later. Getting these in asap so it's not blocking you.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/154)

### CODE REVIEW

**Comment by faern** [comment]
Ok, added the SVG as well since I got hold of the correct version. Also squeezed in a 48px version for Windows 7.

The reason all files are changed is because things became inconsistent and I wanted to know what I had commited, so I re-generated all the graphics with:
```bash
for r in 16 30 32 48 50 64 128 150 256 300 512 1024; do
    inkscape -z -e icon.iconset/icon_${r}x${r}.png -w $r -h $r icon-1024.svg;
done
```
More or less. Plus some manual work for the `@2x` files.

**Comment by pinkisemils** [comment]
I've tested out the new images and created a new icon file for windows. Should I commit the file as well? Everything looks good now :ok_hand: 

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/154#-:-LBfT5qi5AfyIUMeNyAI:b-l0skpy)*

**Comment by faern** [comment]
Yeah you can push the new Windows icon file to this PR branch before I merge if you want to. So you don't need a separate PR just for that.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/154#-:-LBp9MZ--B2H3NeDHoPJ:b-2klhl)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/154)*

**Pull request merged**
