### PR TITLE
Add daemon CI job for Windows ARM64

### PR DESCRIPTION
**Pull request by dlon**
This PR doesn't include clippy, since those are (probably) not architecture-dependent, or the `test` workspace for now. It also does not include GUI or full E2E tests.

Close DES-1120

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258)

### CODE REVIEW

**Review by hulthe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`.github/workflows/daemon.yml` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGN4h9Inf1ScWOcYZ:-OCnGN4h9Inf1ScWOcY_:b92inkq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L137)):*
> ```YAML
> 
>       - name: Install Protoc
>         if: ${{ matrix.config.arch == 'x64' }}
> ```

do we not need protoc on arm?
___
*[`.github/workflows/daemon.yml` line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGQn9-ONf4zBJ-XtI:-OCnGQn9-ONf4zBJ-XtJ:bfbtkaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L144)):*
> ```YAML
>       - name: Calculate Windows libraries cache hash
>         if: ${{ matrix.config.arch == 'x64' }}
>         id: windows-modules-hash
> ```

do we not need/want this on arm?
___
*[`.github/workflows/daemon.yml` line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGWZQ90Vugr1Oundf:-OCnGWZQ90Vugr1Oundg:bfbtkaw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L154)):*
> ```YAML
> 
>       - name: Cache Windows libraries
>         if: ${{ matrix.config.arch == 'x64' }}
> ```

do we not need/want this on arm?
___
*[`.github/workflows/daemon.yml` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnG_bI7Lusy6ZpTJE1:-OCnG_bI7Lusy6ZpTJE2:b-b3nhkf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L183)):*
> ```YAML
> 
>       - name: Install msbuild
>         if: ${{ matrix.config.arch == 'x64' }}
> ```

do we not need msbuild on arm?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258)* status: all files reviewed, 4 unresolved discussions (waiting on @hulthe)

___
*[`.github/workflows/daemon.yml` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGN4h9Inf1ScWOcYZ:-OCwM9d05ZzIe1DMSYxm:b-6h0ypp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L137)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

do we not need protoc on arm?
</blockquote></details>

It's installed on the runner, so I figured it was wasteful to keep it. Let's enable it and see if anything breaks.
___
*[`.github/workflows/daemon.yml` line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGQn9-ONf4zBJ-XtI:-OD5TfSnAIFo1GPrcVzk:b-5zz0bi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L144)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

do we not need/want this on arm?
</blockquote></details>

Let's enable it and see if it just works.
___
*[`.github/workflows/daemon.yml` line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGWZQ90Vugr1Oundf:-OD5TjpI444ie1qSHtNd:b-5zz0bi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L154)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

do we not need/want this on arm?
</blockquote></details>

Let's enable it and see if it just works.
___
*[`.github/workflows/daemon.yml` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnG_bI7Lusy6ZpTJE1:-OD5Tlk7DaV3Mbp2dYgO:b-6h0ypp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L183)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

do we not need msbuild on arm?
</blockquote></details>

It's installed on the runner, so I figured it was wasteful to keep it. Let's enable it and see if anything breaks.

**Review by hulthe — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/daemon.yml` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGN4h9Inf1ScWOcYZ:-OD6Q4mv9DQKrQPd1QpS:bezxwqp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L137)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's installed on the runner, so I figured it was wasteful to keep it. Let's enable it and see if anything breaks.
</blockquote></details>

Makes sense. If it cuts down on run time, I'm all for it. Any `if arch` guards here should imo be documented though
___
*[`.github/workflows/daemon.yml` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnG_bI7Lusy6ZpTJE1:-OD6Q1bTDGXah83fukaC:bw8ad1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L183)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's installed on the runner, so I figured it was wasteful to keep it. Let's enable it and see if anything breaks.
</blockquote></details>

:+1:  See my other comment

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.github/workflows/daemon.yml` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnGN4h9Inf1ScWOcYZ:-OD6WlXp65PabeKY2QMT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L137)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Makes sense. If it cuts down on run time, I'm all for it. Any `if arch` guards here should imo be documented though
</blockquote></details>

Done.
___
*[`.github/workflows/daemon.yml` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258#-OCnG_bI7Lusy6ZpTJE1:-OD6WmCL4JAj4f-JKRYH:b-lplrcj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b0100f3461f3fc86c5a671cd840e2e47b98723c/.github/workflows/daemon.yml#L183)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

:+1:  See my other comment
</blockquote></details>

I left it in in this case. This action detects that it is already installed, so it saves no time.

**Pull request merged**
