### PR TITLE
Create universal list adapter

### PR DESCRIPTION
**Pull request by axti**
This PR is about to create universal list adapter. It has DiffUtil instance to handle animations for changes.
Adapter used different list items and introduce flexibility with usage of different list item types.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567)

### CODE REVIEW

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567)* status: all files reviewed, 5 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVazMOWAQrfyV8dTppG:-MVazMOX4Je_mkmW75Oc:bhz5nc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L21)):*
> ```Kotlin
>     var listItemListener: ListItemListener? = null
> 
>     protected var updateCallback: ListUpdateCallback? = null
> ```

When is this initialized?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVawEf774OVXlu1vacA:-MVawEf83PljuVbhQsBz:b-m2nvbu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L39)):*
> ```Kotlin
>                     ListItemData.DOUBLE_ACTION -> TwoActionListItemView(parent.context)
>                     else ->
>                         throw IllegalArgumentException("View type '$viewType' is not supported")
> ```

Nit: I usually put the body of cases that are not on a single line (i.e. `case -> expression`) wrapped around braces `{}` so that it's a bit less risky to add more expressions to the body. But this is an optional precaution :)
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVax33h5W3oxHDnyXOd:-MVax33h5W3oxHDnyXOe:bdjm5bc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L45)):*
> ```Kotlin
> 
>     override fun onBindViewHolder(holder: ViewHolder, position: Int) {
>         (holder.itemView as ListItemView).update(getItem(position))
> ```

Could `update` by chance call the wrong listener (I mean, before it is updated below)?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVawv0TBL4-1D1NO2uw:-MVawv0TBL4-1D1NO2ux:b-qz6foc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L51)):*
> ```Kotlin
>     override fun onViewRecycled(holder: ViewHolder) {
>         super.onViewRecycled(holder)
>         (holder.itemView as ListItemView).listItemListener = null
> ```

Is there any problem if the listener is called after the view was recycled? Maybe it should be set to `null` before calling `super.onViewRecycled(holder)`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVaxw474smeri_JXVPV:-MVaxw474smeri_JXVPW:brdnjjg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L59)):*
> ```Kotlin
>     override fun getItemViewType(position: Int): Int = getItem(position).type
> 
>     override fun getItemId(position: Int): Long = getItem(position).identifier.hashCode().toLong()
> ```

This seems dangerous to me. Two different identifiers could return the same hash (a collision) and become the same ID. I'm not sure what would be the best way to fix it. But I guess there would need some sort of ID generator/tracker :thinking:

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVaxw474smeri_JXVPV:-MVohmzGBQy44-4qBDDx:bcpw7g1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L59)):*
> Could update by chance call the wrong listener (I mean, before it is updated below)?
We can add the ID to data model later if you feel not comfortable, but still it is not preventing you to get a mistake and have same id's.
But this is unlikely to get same hashcode for strings.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVawv0TBL4-1D1NO2uw:-MVoj0zc4Ac2Z_zgjPnn:b-ixomh1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L51)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is there any problem if the listener is called after the view was recycled? Maybe it should be set to `null` before calling `super.onViewRecycled(holder)`?
</blockquote></details>

Can't see any problems.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVax33h5W3oxHDnyXOd:-MVojRfI0keO_XUQcAPd:bpe6phw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L45)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could `update` by chance call the wrong listener (I mean, before it is updated below)?
</blockquote></details>

No, I can't see any use cases when it could happened.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVawEf774OVXlu1vacA:-MVojgkV3GFB4qErqKV8:b-s8cpq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L39)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: I usually put the body of cases that are not on a single line (i.e. `case -> expression`) wrapped around braces `{}` so that it's a bit less risky to add more expressions to the body. But this is an optional precaution :)
</blockquote></details>

I agree with you. Actually it was a single line, but because of the length it is looks like this.

**Comment by axti** [comment]
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MVazMOWAQrfyV8dTppG:-MVojwHFEjUF-XlPrFAt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaf70fe21e76a6137e9d12d5b94d832b4a7456ef/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L21)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

When is this initialized?
</blockquote></details>

Done.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-:-MW5XgcgBC7EGwQ2kAD1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 113 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567#-MW5XWwv1GN-xyh8MUmH:-MW5XWwwBGl4mjRPejfR:bl82xhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2641d5c030436bfbe8ad80909bcb0782b92ea2c1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L113)):*
> ```Kotlin
>             idCounter.decrementAndGet()
>         }
>     }
> ```

Wow, this is a really neat implementation!

**Pull request merged**
