### PR TITLE
Wrap all management service calls in Either

### PR DESCRIPTION
**Pull request by Pururun**
This is so the app will not crash if an error occured.

Added konsist test so that all calls needs to be wrapped in Either.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31Z3J23Xjhi2QeVQq1:-O31Z3J23Xjhi2QeVQq2:b-4juq44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L268)):*
> ```Kotlin
>             .mapLeft(ConnectError::Unknown)
> 
>     suspend fun disconnect(): Either<ConnectError, Boolean> =
> ```

If we believe these can result in errors we should also handle them downstream, right now the new are kind of fail silent. We catch the error but we don't do anything with it. See code below, same goes for some of the others:

```
lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/ConnectionProxy.kt
23:    suspend fun disconnect() = managementService.disconnect()
```
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ManagementServiceTest.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31YciZAYL-ZTxMRuGp:-O31YciZAYL-ZTxMRuGq:byu3vr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ManagementServiceTest.kt#L10)):*
> ```Kotlin
> class ManagementServiceTest {
> 
>     @Test
> ```

Nice test :star:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 4 of 19 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31Z3J23Xjhi2QeVQq1:-O37mhiX4VHnOHzmi0wR:b5zrng3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L268)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If we believe these can result in errors we should also handle them downstream, right now the new are kind of fail silent. We catch the error but we don't do anything with it. See code below, same goes for some of the others:

```
lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/ConnectionProxy.kt
23:    suspend fun disconnect() = managementService.disconnect()
```
</blockquote></details>

Added toast messages for those that made sense and added logs for all calls.
___
*[`android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ManagementServiceTest.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31YciZAYL-ZTxMRuGp:-O37ms1Z62PqpJjMYS27:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ManagementServiceTest.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice test :star:
</blockquote></details>

Done.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31Z3J23Xjhi2QeVQq1:-O3as_ZB-llxZsxc1C2A:b-m8njmb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L268)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added toast messages for those that made sense and added logs for all calls.
</blockquote></details>

Good, the logs will be critical because it will be the only way for us to debug from errors logs. Can we add error logs to every single case were we map to a Unknown error? This will help us expand the Unknown cases and introduce new well-typed errors in the future.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31Z3J23Xjhi2QeVQq1:-O3b2nBD3m7XiuV-J8c1:baa7vcl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L268)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Good, the logs will be critical because it will be the only way for us to debug from errors logs. Can we add error logs to every single case were we map to a Unknown error? This will help us expand the Unknown cases and introduce new well-typed errors in the future.
</blockquote></details>

Added logs for all unkown errors

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 268 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O31Z3J23Xjhi2QeVQq1:-O3b4Q400mCxvqAjOhwS:brv3wx8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ad7cd97bf43c561295b073e6ad75b5c49557c54/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L268)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added logs for all unkown errors
</blockquote></details>

Nice :+1: :lgtm:

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 19 of 20 files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 331 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O3g5V-x9SpQaeLZFMj-:-O3g5V-x9SpQaeLZFMj0:bqujbyh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7aff65e729489aaa35b456187044aa15ba8ae8e9/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L331)):*
> ```Kotlin
>                         LoginAccountError.MaxDevicesReached(accountNumber)
>                     Status.Code.UNAVAILABLE -> LoginAccountError.RpcError
>                     else -> LoginAccountError.Unknown(it)
> ```

Here too
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 531 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O3g4zV7C9q_kIrsouAT:-O3g4zV7C9q_kIrsouAU:bnvrffx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7aff65e729489aaa35b456187044aa15ba8ae8e9/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L531)):*
> ```Kotlin
>                 when (it.status.code) {
>                     Status.Code.ALREADY_EXISTS -> NameAlreadyExists(customList.name)
>                     else -> UnknownCustomListError(it)
> ```

We should log on this unknown case, so we can follow up on it.
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 625 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O3g5C2m5jlvXBKyDpKH:-O3g5C2m5jlvXBKyDpKI:buo9nmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7aff65e729489aaa35b456187044aa15ba8ae8e9/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L625)):*
> ```Kotlin
>                     Status.Code.RESOURCE_EXHAUSTED -> RedeemVoucherError.VoucherAlreadyUsed
>                     Status.Code.UNAVAILABLE -> RedeemVoucherError.RpcError
>                     else -> RedeemVoucherError.Unknown(it)
> ```

Same here

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 5 files at r2, 12 of 14 files at r3, 1 of 1 files at r5, 1 of 1 files at r7, 1 of 38 files at r8, 37 of 37 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 179 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4euhnUASyt_PTjtDDT:-O4euhnV0urAgxGY3CnN:bjb9cq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L179)):*
> ```Kotlin
>                 launch { copyToClipboard(sideEffect.accountNumber, copyTextString) }
>             AccountViewModel.UiSideEffect.GenericError ->
>                 snackbarHostState.showSnackbarImmediately(message = errorString)
> ```

Is this new toast aligned with design? Same question applies to other new toasts
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4etMMoCoWhZarN4UG-:-O4etMMoCoWhZarN4UG0:b-f1ce50) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.daemon.grpc
> ```

Are we sure none of the new error logs contain any sensitive information when we include `it`? E.g. `Logger.e("Disconnect error", it)`
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 716 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4euAAZ1zTyiSMmF5uk:-O4euAAZ1zTyiSMmF5ul:b-8337q0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L716)):*
> ```Kotlin
>     ): Either<TestApiAccessMethodError, Unit> =
>         Either.catch { grpc.testCustomApiAccessMethod(customProxy.fromDomain()) }
>             .onLeft { Logger.e("test custom api access method error", it) }
> ```

nit: `Test`



_Code quote:_
```Kotlin
test
```
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 726 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4euEiNAddqDhiC5kk7:-O4euEiO9FrtIT4eELHj:b-8337q0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L726)):*
> ```Kotlin
>     ): Either<TestApiAccessMethodError, Unit> =
>         Either.catch { grpc.testApiAccessMethodById(apiAccessMethodId.fromDomain()) }
>             .onLeft { Logger.e("test api access method error", it) }
> ```

nit: `Test`



_Code quote:_
```Kotlin
tes
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4etMMoCoWhZarN4UG-:-O4ibDtS3l1pAdEVv3Jt:b-ftlna6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are we sure none of the new error logs contain any sensitive information when we include `it`? E.g. `Logger.e("Disconnect error", it)`
</blockquote></details>

If it is a grpc error it should not contain any sensitive information, but I guess it is possible if it is some other exception?

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 56 of 57 files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 56 of 57 files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4etMMoCoWhZarN4UG-:-O4oEl8gAVCughaZ3awg:b-r55wuy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

If it is a grpc error it should not contain any sensitive information, but I guess it is possible if it is some other exception?
</blockquote></details>

If we can't be certain we should avoid including `it`. Can we make it more specific or skip it? Or perhaps use duplicate log calls: one Logger.e without `it` and one Logger.d with `it` (since the debug level wouldn't be included in release builds)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: 50 of 57 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4etMMoCoWhZarN4UG-:-O4tI75h4NQF_zcoWbSD:b-c3idt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

If we can't be certain we should avoid including `it`. Can we make it more specific or skip it? Or perhaps use duplicate log calls: one Logger.e without `it` and one Logger.d with `it` (since the debug level wouldn't be included in release builds)
</blockquote></details>

Removed all it

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4etMMoCoWhZarN4UG-:-O4tJ1EZ8F1MJkMo5lND:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Removed all it
</blockquote></details>

:thumbsup:

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 179 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4euhnUASyt_PTjtDDT:-O4y8CgA6koqbk0gmS1b:bnbx8ox) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L179)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this new toast aligned with design? Same question applies to other new toasts
</blockquote></details>

It has now been aligned with design. Also created an issue in linear on how we can improve our handling of grpc failures.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-:-O4yAYtG3ASKK9YIA70x:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 179 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500#-O4euhnUASyt_PTjtDDT:-O4yAW8T8kg8DeoQWN1I:bv3euye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1016f28fdab9653ac6bca154506c70887f04fe8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L179)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It has now been aligned with design. Also created an issue in linear on how we can improve our handling of grpc failures.
</blockquote></details>

Perfect! :raised_hands:

**Pull request merged**
