### PR TITLE
Add background tasks

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR adds background relay updates and private key rotation.

**iOS 12:**

Uses background fetch (`UIApplicationDelegate.performFetchWithCompletionHandler`) to update
relays and rotate the private key.

**iOS 13:**

Uses new `BackgroundTasks` framework on iOS 13 or newer.

1. Background refresh task to update relays once an hour.
2. Background processing task for private key rotation.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqG4bW8gKXg35R_92B:-MkqG4bW8gKXg35R_92C:baqrbzd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/AppDelegate.swift#L62)):*
> ```Swift
>         } else {
>             // Set background refresh interval on iOS 12
>             application.setMinimumBackgroundFetchInterval(ApplicationConfiguration.minimumBackgroundFetchInterval)
> ```

FYI On iOS 12, the app has to specify a desired interval for updating the content in background.

Once set, the system wakes up the app periodically and calls to `UIApplicationDelegate.performFetchWithCompletionHandler`.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqHdAsAofj4wWyR_fr:-MkqHdAsAofj4wWyR_fs:b-ki9h3i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/AppDelegate.swift#L58)):*
> ```Swift
>         if #available(iOS 13.0, *) {
>             // Register background tasks on iOS 13
>             RelayCache.Tracker.shared.registerAppRefreshTask()
> ```

FYI On iOS 13 the app can register different types of background tasks:

1. Background processing task, which IIRC gets about 3 minutes of background execution time before the task is terminated.
2. Background app refresh task which is similar to background fetch on iOS 12. It's limited to 30 seconds of background execution before the task is terminated. Unlike background processing tasks, only one such task can be registered per app.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 151 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqK7Lc1oIDkxiMJgJ0:-MkqK7Ld1ZAYyeOmThu0:bsyo486) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/AppDelegate.swift#L151)):*
> ```Swift
>     }
> 
>     func application(_ application: UIApplication, performFetchWithCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
> ```

FYI this method is only called on iOS 12. iOS 13 or newer use background tasks.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 193 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqKqCJ2ZcPchv3bPmY:-MkqKqCJ2ZcPchv3bPmZ:bjxckuu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/AppDelegate.swift#L193)):*
> ```Swift
>     @available(iOS 13.0, *)
>     private func scheduleBackgroundTasks() {
>         if case .finished(let result) = RelayCache.Tracker.shared.scheduleAppRefreshTask().await() {
> ```

FYI using `.await()` here to make sure the app does not lapse into suspended state before registering the background tasks. This should not cause a deadlock since neither of these functions depend on the main thread in any way.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqM2my6C6LAMAjub_u:-MkqM2my6C6LAMAjub_v:b-iii6pa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L122)):*
> ```Swift
>             }
>             .block(on: updateQueue)
>             .requestBackgroundTime(taskName: "RelayCacheTracker.updateRelays")
> ```

FYI makes sure that networking task finishes before the app is suspended.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqMmQr06gGs2y8vtFy:-MkqMmQr06gGs2y8vtFz:b-xn32va) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L322)):*
> ```Swift
>         let scheduleDate = Date(timeIntervalSinceNow: Self.relayUpdateInterval)
> 
>         switch self.submitAppRefreshTask(at: scheduleDate) {
> ```

FYI the way it works that we have to schedule the next refresh task during the task execution.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 1099 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqNPkwAmF1QTtUo7vG:-MkqNPkwAmF1QTtUo7vH:bcr72l1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1099)):*
> ```Swift
>             .storeCancellationToken(in: &cancellationToken)
>             .observe { completion in
>                 if let scheduleDate = self.handlePrivateKeyRotationCompletion(completion: completion) {
> ```

FYI we schedule the next key rotation based on the result of the current key rotation. We don't really have any counter around how many times we attempt to rotate the key.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 1159 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqO7c45FwnLXFZLELR:-MkqO7c45FwnLXFZLELS:b-4ds7zz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1159)):*
> ```Swift
>         case .missingAccount:
>             // Do not retry if logged out.
>             return nil
> ```

FYI What's important that we will not attempt to retry rotating the key if user logged out or if the account was removed from server.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqP7MmCCbOXebNgKbC:-MkqP7MmCCbOXebNgKbD:b-1l9j4l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/AppDelegate.swift#L172)):*
> ```Swift
>                         }
> 
>                         return fetchRelaysResult.backgroundFetchResult.combine(with: rotationResult.backgroundFetchResult)
> ```

FYI on iOS 12, after performing the fetch we have to report the result to the system by calling the `completionHandler` and passing the `UIBackgroundFetchResult` value. 

`UIBackgroundFetchResult` is an `enum` with the following cases:  `.failed,` `.noData`, `.newData`.

The system scheduler then uses the fetch result for organising the background fetch schedule. Very much a black box.

Alright, so since we perform two tasks here (relay updates + private key rotation), I have to deduce the `UIBackgroundFetchResult` based on the result of both of them.

The basic rule I use to combine both results into one is the following:

1. If either is `.failed`, then pass `.failed` to the system
2. If either is `.newData`, then pass .`newData` to the system
3. Otherwise return `.noData` to the system

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 312 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqRoZpA0AG2tofiFb6:-MkqRoZpA0AG2tofiFb7:b-6efm76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L312)):*
> ```Swift
>                 }
> 
>                 task.setTaskCompleted(success: !completion.isCancelled)
> ```

FYI on iOS 13 or newer, the system scheduler only cares if the task is completed or not.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: 0 of 8 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 312 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqRoZpA0AG2tofiFb6:-MkqRtEb8A_607oFITYC:b-gx6bst) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L312)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI on iOS 13 or newer, the system scheduler only cares if the task is completed or not.
</blockquote></details>

FYI in contrast with background fetch on iOS 12, we tell the system if we were able to fetch new data, failed or received no new data.

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkvEESQAd-a9jEKa5Gn:-MkvEESQAd-a9jEKa5Go:b-18zchx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L284)):*
Isn't network connectivity required for this one as well?
> ```
> request.requiresNetworkConnectivity = true
> ```
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 1099 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqNPkwAmF1QTtUo7vG:-MkvEXam5aH3wHN6Ncrv:b-7xe4d4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1099)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI we schedule the next key rotation based on the result of the current key rotation. We don't really have any counter around how many times we attempt to rotate the key.
</blockquote></details>

Why not? It would make sense to have a shorter interval if it failed.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkvEESQAd-a9jEKa5Gn:-MkvHnWb1MH-Bz1hJDYd:b-oxk1oa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L284)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Isn't network connectivity required for this one as well?
> ```
> request.requiresNetworkConnectivity = true
> ```
</blockquote></details>

Unlike `BGProcessingTaskRequest`, `BGAppRefreshTaskRequest` does not expose `requiresNetworkConnectivity` setting, as it probably assumes that network is required to refresh the app contents.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 1099 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqNPkwAmF1QTtUo7vG:-MkvIWq59sMyBhRSwxeh:bvfwng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1099)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Why not? It would make sense to have a shorter interval if it failed.
</blockquote></details>

Not sure what you asking. We use the shorter interval (15 min) see `privateKeyRotationFailureRetryInterval` in case of failure.

**Review by raksooo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-:-MkvWnOx2xMStsME_Fzl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkvEESQAd-a9jEKa5Gn:-MkvWl-J-_cYgaiF_BYi:bk0ezu6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L284)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Unlike `BGProcessingTaskRequest`, `BGAppRefreshTaskRequest` does not expose `requiresNetworkConnectivity` setting, as it probably assumes that network is required to refresh the app contents.
</blockquote></details>

Ah, makes sense!
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 1099 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998#-MkqNPkwAmF1QTtUo7vG:-MkvWevH-war33aioVFQ:b-50ioiu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4153839ac8a2a294e6b194b5fca7b78b50bf4815/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1099)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not sure what you asking. We use the shorter interval (15 min) see `privateKeyRotationFailureRetryInterval` in case of failure. 
</blockquote></details>

Sorry I misread your first comment.

**Pull request merged**
