### PR TITLE
Better build.sh logging

### PR DESCRIPTION
**Pull request by faern**
`build.sh` outputs a lot of text. Most of it is noise. Some of it is interesting some of the time. For example, when I'm looking at build server logs I want to know which branch/version it's currently building. It's also nice to be able to see approximately where in the build process it is. Currently we have ~6 `cargo run`/`cargo build` calls after each other in this script. So seeing some random cargo output does not say much about the overall progress.

Because of this I added some helper functions to log with color. And use those to have some nicer output from the script.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
Feel free to bikeshed the actual format of logging messages or their function names or where the color variables are defined. Improvements and any change that makes the code more Bash idiomatic would be great.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-:-Ms2SoAp99y8xrrbn1X6:b-925yzv)* status: 0 of 1 files reviewed, all discussions resolved

___
*[build.sh, line 119 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms2S_Q47PRszlFodST2:-Ms2S_Q47PRszlFodST3:bsbxrb2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L119)):*
> ```Shell
> fi
> 
> log_header "Building Mullvad VPN $PRODUCT_VERSION"
> ```

I moved this here to have it be printed very early in script execution. One of the first things I want to know is what product version I'm building. With the old placement it was not printed until after generating shell completions and some other possibly time consuming operations.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-:-Ms4dKBF2eMA60mmeaF6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[build.sh, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms4bpA-5VQBT9y2kMBY:-Ms4bpA046xQAuaKaD8b:bsi5ckw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L213)):*
> ```Shell
>     export MULLVAD_ADD_MANIFEST="1"
> 
>     log_header "Building Rust code in release mode using $RUSTC_VERSION$for_target_string"
> ```

It's very unclear what `release mode` is. Is it that we're using stable rust? I assume this will be changed in one of your next PRs?
___
*[build.sh, line 325 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms4bCgh7jQboPK7zd3O:-Ms4bCgh7jQboPK7zd3P:b-70y25c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L325)):*
> ```Shell
> done
> 
> GREEN="32m"
> ```

Maybe it would be nice with a `log_success` function which uses green? Or define all colors at the top?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[build.sh, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms4bpA-5VQBT9y2kMBY:-Ms5JrsfDi8axVs_EJyt:b-we63zg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L213)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

It's very unclear what `release mode` is. Is it that we're using stable rust? I assume this will be changed in one of your next PRs?
</blockquote></details>

It's that we are using `--release`. It has nothing with rust toolchain (stable vs nightly) to do, but rather if compiler optimizations are on or off.

Yes, in a future PR this will be changed to `in $RUST_BUILD_MODE mode using ...` where the variable will be either `release` or `debug`. But these are the words cargo use, so I'm not sure it makes sense to use any other word here. The name of the cargo profiles used are `release` and `debug`. So going away from these words will create other types of confusion IMO.
___
*[build.sh, line 325 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms4bCgh7jQboPK7zd3O:-Ms5JOUP2UhvuQLn2lGF:bp97608) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L325)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Maybe it would be nice with a `log_success` function which uses green? Or define all colors at the top?
</blockquote></details>

I was hesitant towards making a function out of something used only once. And I was also hesitant to declare the variable too far from where it's used. I did not want to pollute the entire script namespace with a bunch of color variables. If we don't want the current solution, I agree that a `log_success` is the best alternative.

I'm also considering a `log_info` that just slightly stands out from the normal text and use it for other echos in the script to make them stand out form the noise produced by all subcommands we call. But I did not agree on a suitable style for said text.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[build.sh, line 325 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms4bCgh7jQboPK7zd3O:-Ms5MgCi7BIbcWXheY-A:b-xy017h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L325)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I was hesitant towards making a function out of something used only once. And I was also hesitant to declare the variable too far from where it's used. I did not want to pollute the entire script namespace with a bunch of color variables. If we don't want the current solution, I agree that a `log_success` is the best alternative.

I'm also considering a `log_info` that just slightly stands out from the normal text and use it for other echos in the script to make them stand out form the noise produced by all subcommands we call. But I did not agree on a suitable style for said text.
</blockquote></details>

Done! I added both `log_success` and `log_info`. Where info is just bold but no special color. I think this looks better.

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[build.sh, line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms4bpA-5VQBT9y2kMBY:-Ms6-UUS3kQ7idLqz6Oi:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f2449fc93c7e25e7d491e033335324650eefb369/build.sh#L213)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's that we are using `--release`. It has nothing with rust toolchain (stable vs nightly) to do, but rather if compiler optimizations are on or off.

Yes, in a future PR this will be changed to `in $RUST_BUILD_MODE mode using ...` where the variable will be either `release` or `debug`. But these are the words cargo use, so I'm not sure it makes sense to use any other word here. The name of the cargo profiles used are `release` and `debug`. So going away from these words will create other types of confusion IMO.
</blockquote></details>

Okay :+1:
___
*[build.sh, line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226#-Ms6--Ti8EIyC6O9GcaO:-Ms6--Ti8EIyC6O9GcaP:bgzxeaz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60c32083b61fcc4cf22eb213b95f94cc7da170cd/build.sh#L109)):*
> ```Shell
> else
>     NPM_PACK_ARGS+=(--no-compression)
>     log_info "!! Development build. Not for general distribution !!"
> ```

Do we want to let "!!" indicate error? If so then we should remove it from here. Or is just to draw attention?

**Pull request merged**
