### PR TITLE
Update README in gui/scripts

### PR DESCRIPTION
**Pull request by raksooo**
This PR updates the readme in `gui/scripts` to reflect the changes made to the localization scripts in https://github.com/mullvad/mullvadvpn-app/pull/6241.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370)

### CODE REVIEW

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/scripts/README.md` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-O-kU-jfDM3MOCogS7pa:-O-kU-jfDM3MOCogS7pb:by2vo9e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023ff389f13c2fc5eb2c7530c98412b1cfd0df7e/gui/scripts/README.md#L17)):*
> ```Markdown
> ### Update translations
> 
> See [../locales/README.md](../locales/README.md) for information about how to handle translations.
> ```

Nit We could skip the `..` when formatting the link

```
See [locales/README.md](../locales/README.md)
```



_Code quote:_
```Markdown
See [../locales/README.md](../locales/README.md) 
```
___
*[`gui/scripts/README.md` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-O-kUkx-18nbrcJjuRQ-:-O-kUkx-18nbrcJjuRQ0:brr5sx2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023ff389f13c2fc5eb2c7530c98412b1cfd0df7e/gui/scripts/README.md#L19)):*
> ```Markdown
> See [../locales/README.md](../locales/README.md) for information about how to handle translations.
> 
> The `/scripts/localization` script is, among other things, calling into `fetch-relay-locations.py`
> ```

Nit Is `/` how we are supposed to refer to the project root in documentation? :blush:
Would it be less clear if we replaced `/scripts/localization` with `scripts/localization`?



_Code quote:_
```Markdown
The `/scripts/localization`
```
___
*[`gui/scripts/README.md` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-O-kUZSYDYepP5G3t8xe:-O-kUZSYDYepP5G3t8xf:b-hzvn92) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023ff389f13c2fc5eb2c7530c98412b1cfd0df7e/gui/scripts/README.md#L24)):*
> ```Markdown
> * `fetch-relay-locations.py` fetches the relay list and extracts all country and city names.
> * `intregrate-relay-locations.py` integrates the fetched relay locations into
> `../locales/relay-locations.pot`.
> ```

Nit Either make this a markdown link, or format it relative to the project root:
```
gui/locales/relay-locations.pot
```



_Code quote:_
```Markdown
../locales/relay-locations.pot
```

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`gui/scripts/README.md` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-O-kU-jfDM3MOCogS7pa:-O0EHNBY3a6pqHIY8oCp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023ff389f13c2fc5eb2c7530c98412b1cfd0df7e/gui/scripts/README.md#L17)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit We could skip the `..` when formatting the link

```
See [locales/README.md](../locales/README.md)
```
</blockquote></details>

Done.
___
*[`gui/scripts/README.md` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-O-kUkx-18nbrcJjuRQ-:-O0EHOUg-ikndeQL-Qmy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023ff389f13c2fc5eb2c7530c98412b1cfd0df7e/gui/scripts/README.md#L19)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Is `/` how we are supposed to refer to the project root in documentation? :blush:
Would it be less clear if we replaced `/scripts/localization` with `scripts/localization`?
</blockquote></details>

Done.
___
*[`gui/scripts/README.md` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-O-kUZSYDYepP5G3t8xe:-O0EHPW9741qR92d09ID:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/023ff389f13c2fc5eb2c7530c98412b1cfd0df7e/gui/scripts/README.md#L24)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Either make this a markdown link, or format it relative to the project root:
```
gui/locales/relay-locations.pot
```
</blockquote></details>

Done.

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-:-O0EUnGhCdvsxL0ELwEW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370#-:-O0EZIPi777vcFmhgMec:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
