### PR TITLE
Fix wireguard mtu selection showing again after closing it

### PR DESCRIPTION
**Pull request by Pururun**
Also made some improvements to the mtu dialog.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeF18dAZOvjp52qAmH:-NdeF18dAZOvjp52qAmI:b-hbc749) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9b81258c9d433c123436d1ffc035427ffbb3aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L38)):*
> ```Kotlin
> @Composable
> fun MtuDialog(
>     mtuValueInitial: String,
> ```

Can we change this to be `Int` or `Int?` easily?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeEU05DjP836f4Pg9h:-NdeEU05DjP836f4Pg9i:b-q0kxbz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9b81258c9d433c123436d1ffc035427ffbb3aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L47)):*
> ```Kotlin
>     val smallPadding = 5.dp
> 
>     val mtuValue = remember { mutableStateOf(mtuValueInitial) }
> ```

Maybe to avoid writing `mtuValue.value`
`var mtuValue by remember { mutableStateOf(mtuValueInitial) }`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeFIZs8B77f9qLevWn:-NdeFIZs8B77f9qLevWo:bo8v9hy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9b81258c9d433c123436d1ffc035427ffbb3aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L135)):*
> ```Kotlin
>                         ),
>                     text = stringResource(R.string.reset_to_default_button),
>                     onClick = { onRestoreDefaultValue() }
> ```

Would it be possible to send the function reference directly?
`onClick = onRestoreDefaultValue`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 150 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeFcpD4yLqCTLDNu6q:-NdeFcpD4yLqCTLDNu6r:b3f9dg2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9b81258c9d433c123436d1ffc035427ffbb3aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L150)):*
> ```Kotlin
>                         ),
>                     text = stringResource(R.string.cancel),
>                     onClick = { onDismiss() }
> ```

Same as a above previous

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeF18dAZOvjp52qAmH:-NdeUzWX3z2mkl7swq7e:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b7520e24aef28f22631b7cbfb8204b34fee708b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L38)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Can we change this to be `Int` or `Int?` easily?
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeEU05DjP836f4Pg9h:-NdeV1TU1Gfl9rVetxEg:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b7520e24aef28f22631b7cbfb8204b34fee708b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L47)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe to avoid writing `mtuValue.value`
`var mtuValue by remember { mutableStateOf(mtuValueInitial) }`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeFIZs8B77f9qLevWn:-NdeV3N33qOrTKgLCuHI:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b7520e24aef28f22631b7cbfb8204b34fee708b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L135)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would it be possible to send the function reference directly?
`onClick = onRestoreDefaultValue`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 150 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-NdeFcpD4yLqCTLDNu6q:-NdeV4g76baMmg1lqOcn:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5b7520e24aef28f22631b7cbfb8204b34fee708b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L150)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same as a above previous
</blockquote></details>

Done

**Review by Rawa — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-:-Ndix1_f012UTcHXMZD0:bg7igkv)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @sabercodic)

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-Ndjkx8l7ZHB5WbMZ55O:-Ndjkx8l7ZHB5WbMZ55P:bq7efnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd84a85327112390b99a1cba145cedeee050928/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L120)):*
> ```Kotlin
>                     isEnabled = isValidMtu,
>                     text = stringResource(R.string.submit_button),
>                     onClick = { onSave(mtu.value.toIntOrNull() ?: 0) }
> ```

Shouldn't this do the same as `onSubmit` above? In that case, it would be nice to unify it.

Also, I'm not sure it makes sense to send `0` if we fail to parse.



_Code quote:_
```Kotlin
onClick = { onSave(mtu.value.toIntOrNull() ?: 0) }
```

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-Ndjkx8l7ZHB5WbMZ55O:-Ndk4_Ja7MC5OktweH1D:b-2v2oi4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fd84a85327112390b99a1cba145cedeee050928/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt#L120)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Shouldn't this do the same as `onSubmit` above? In that case, it would be nice to unify it.

Also, I'm not sure it makes sense to send `0` if we fail to parse.
</blockquote></details>

Yeah stopped it from saving in both places.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102#-:-Ndnkkfh8CxM6t6Nadya:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
