### PR TITLE
Use KeyboardType.Number on Amazon FireStick

### PR DESCRIPTION
**Pull request by kl**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
Looks good! Just two minor comments

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-:-O9pKlks6fo2t9m_UOfd:b-z26hgm)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9pKTf86AUhsHiWh1qi:-O9pKTf86AUhsHiWh1qj:b-u2y4m9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/672e46562d9b57ef7a9165cd37136053f5518713/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L6)):*
> ```Kotlin
> import androidx.compose.ui.text.input.KeyboardType
> 
> fun KeyboardType.Companion.numberPasswordInputType(context: Context): KeyboardType =
> ```

nit: I suggest renaming to `accountNumberKeyboardType` since it might not return a `NumberPassword` type which the function name otherwise could imply



_Code quote:_
```Kotlin
numberPasswordInputType
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9pK40T71K7lVX6rxv7:-O9pK40T71K7lVX6rxv8:b-5t0in3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/672e46562d9b57ef7a9165cd37136053f5518713/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L13)):*
> ```Kotlin
>     }
> 
> // see: https://developer.amazon.com/docs/fire-tv/identify-amazon-fire-tv-devices.html
> ```

nit: we usually start comments (at least in the android code base) with an uppercase character



_Code quote:_
```Kotlin
see:
```

**Review by Pururun — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9pKTf86AUhsHiWh1qi:-O9t2HYY5nbtYHvDQWi1:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/672e46562d9b57ef7a9165cd37136053f5518713/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest renaming to `accountNumberKeyboardType` since it might not return a `NumberPassword` type which the function name otherwise could imply
</blockquote></details>

Fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9pK40T71K7lVX6rxv7:-O9t2MPUCqItlBwBVfah:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/672e46562d9b57ef7a9165cd37136053f5518713/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: we usually start comments (at least in the android code base) with an uppercase character
</blockquote></details>

Fixed

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9t4Gnj8vtTYCu6w86h:-O9t4Gnk2gMTpSBrOYhH:bog95yu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/838e34b495691c46889729953a76b9fd15287ac8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L15)):*
> ```Kotlin
> // See: https://developer.amazon.com/docs/fire-tv/identify-amazon-fire-tv-devices.html
> private fun isFireStick(context: Context): Boolean =
>     context.packageManager.hasSystemFeature("amazon.hardware.fire_tv")
> ```

Is there any other way we could provide this without using context? Would be nice to avoid using `LocalContext.current` if possible.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-:-O9tY4NQ7d3s5v6WMJUh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @ApplicationContext, and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9t4Gnj8vtTYCu6w86h:-O9traTg0-P455FK0XZx:bqifcu2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/838e34b495691c46889729953a76b9fd15287ac8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L15)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is there any other way we could provide this without using context? Would be nice to avoid using `LocalContext.current` if possible.
</blockquote></details>

Should be possible to have Koin to inject components like the PackageManger or application context, right? I know Hilt as built in support for doing that with @ApplicationContext.

So we could inject the application context instead and use that to get to the package manager maybe?

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047#-O9t4Gnj8vtTYCu6w86h:-O9xA6fZ7m__fHVCV55e:b-1bfijf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/838e34b495691c46889729953a76b9fd15287ac8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt#L15)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Should be possible to have Koin to inject components like the PackageManger or application context, right? I know Hilt as built in support for doing that with @ApplicationContext.

So we could inject the application context instead and use that to get to the package manager maybe?
</blockquote></details>

Nah, applicationContext is basically Context. I think this will do for now.

**Review by Rawa — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
