### PR TITLE
Extract Android dependencies to constants

### PR DESCRIPTION
**Pull request by albin-mullvad**
Extracts Android dependency names/versions/repos to Kotlin constants in
source code. The purpose of this change is to minimize duplication,
unify versions and prepare the project to be split into multiple
sub-projects/modules.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[android/buildSrc/src/main/kotlin/Dependencies.kt, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238#-Mso2BSBDQvCihBfv_73:-Mso2BSBDQvCihBfv_74:b-wk1s3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5973cd9c3f726168f136b7bb3e588f79cb9ee35/android/buildSrc/src/main/kotlin/Dependencies.kt#L53)):*
> ```Kotlin
> 
>     object MockK {
>         const val core = "io.mockk:mockk:${Versions.mockk}"
> ```

Will it always be the case that both `io.mockk:mockk` and `io.mock.mockk-android` are always updated in lockstep? Will this be the case for all the dependencies that use a shared version?  I think I'd prefer a slightly more verbose way of specifying the package name and version in the same string just to make it super clear and easy to deduce what version of which dependency is being used.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/buildSrc/src/main/kotlin/Dependencies.kt, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238#-Mso2BSBDQvCihBfv_73:-MsoAdMUC5vynu3FKRAy:b-l7soit) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5973cd9c3f726168f136b7bb3e588f79cb9ee35/android/buildSrc/src/main/kotlin/Dependencies.kt#L53)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Will it always be the case that both `io.mockk:mockk` and `io.mock.mockk-android` are always updated in lockstep? Will this be the case for all the dependencies that use a shared version?  I think I'd prefer a slightly more verbose way of specifying the package name and version in the same string just to make it super clear and easy to deduce what version of which dependency is being used.
</blockquote></details>

I think it's best to default to shared versions, as it's beneficial in terms of compatibility and avoiding classpath conflicts, and add more verbose control in the cases where it's needed. This is also how many in the community does it, even the official samples, as seen below:

https://mockk.io/#gradlemaven-dependency
https://insert-koin.io/docs/quickstart/kotlin/#setup
https://github.com/android/architecture-samples/blob/main/app/build.gradle#L103

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
