### PR TITLE
Update outdated npm packages

### PR DESCRIPTION
**Pull request by hankolsen**
This PR updates a bunch of outdated npm dependencies

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992)* status: 0 of 59 files reviewed, 3 unresolved discussions (waiting on @hankolsen)

___
*[`gui/package.json` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-NDbNd5IBzhtxHx0jX8W:-NDbNd5IBzhtxHx0jX8X:biia5e9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c04208dd0c863999797e01e02a4ff4da8db71dac/gui/package.json#L24)):*
> ```JSON
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-redux": "^8.0.4",
> ```

I think we should hold off on upgrading `react-redux` a bit due to the issues mentioned here: https://socket.dev/npm/package/react-redux
___
*[`gui/package.json` line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-NDbG-Eb8FAuwrCAjYc6:-NDbG-Eb8FAuwrCAjYc7:bcorjsj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c04208dd0c863999797e01e02a4ff4da8db71dac/gui/package.json#L29)):*
> ```JSON
>     "redux": "^4.2.0",
>     "sprintf-js": "^1.1.2",
>     "styled-components": "^5.3.6"
> ```

Upgrading styled-components will require some additional work due to this issue: https://github.com/styled-components/styled-components/issues/3265
One resulting issue is that some icons are the wrong color after going into the split tunneling view on Linux and then back to other views.
___
*[`gui/package.json` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-NDbO43Q2VTHWOa0WtjP:-NDbO43Q2VTHWOa0WtjQ:bv3olys) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c04208dd0c863999797e01e02a4ff4da8db71dac/gui/package.json#L67)):*
> ```JSON
>     "electron-devtools-installer": "^3.2.0",
>     "electron-mocha": "^11.0.2",
>     "electron-notarize": "^1.2.1",
> ```

We will need to test building an app and notarize it.

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992)* status: 0 of 59 files reviewed, 3 unresolved discussions (waiting on @hankolsen and @raksooo)

___
*[`gui/package.json` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-NDbNd5IBzhtxHx0jX8W:-NDc-1gp1z46eZ7XVZeY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c04208dd0c863999797e01e02a4ff4da8db71dac/gui/package.json#L24)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I think we should hold off on upgrading `react-redux` a bit due to the issues mentioned here: https://socket.dev/npm/package/react-redux
</blockquote></details>

Done.
___
*[`gui/package.json` line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-NDbG-Eb8FAuwrCAjYc6:-NDc0kQoDWhhWre9J6Q1:b-hl2vog) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c04208dd0c863999797e01e02a4ff4da8db71dac/gui/package.json#L29)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Upgrading styled-components will require some additional work due to this issue: https://github.com/styled-components/styled-components/issues/3265
One resulting issue is that some icons are the wrong color after going into the split tunneling view on Linux and then back to other views.
</blockquote></details>

Let's move it to another PR

**Review by hankolsen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992)* status: 0 of 65 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/package.json` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-NDbO43Q2VTHWOa0WtjP:-NDl_grpEpCRBGcIqHMQ:b-hfghm4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c04208dd0c863999797e01e02a4ff4da8db71dac/gui/package.json#L67)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We will need to test building an app and notarize it.
</blockquote></details>

Sounds good

**Review by raksooo — APPROVED** [review]
Great work! Everything looks good to me! :lgtm:

> Reviewed 7 of 11 files at r2, 49 of 52 files at r5, 5 of 7 files at r6, 3 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3992#-:-NDmVeXX1Fwy1IETo755:b-dsk18q)* status: 63 of 65 files reviewed, all discussions resolved

**Pull request merged**
