### PR TITLE
Use std LazyLock instead of once_cell Lazy

### PR DESCRIPTION
**Pull request by dlon**
The container needs to be updated to use Rust 1.80 before this can be merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529)

### CODE REVIEW

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529)* status: 0 of 52 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/firewall/linux.rs` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529#-O32rqHY5BUkwR9ca8Ha:-O32rqHY5BUkwR9ca8Hb:bdzpc1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5e78a31851ab8af1533a7ff0f97399f3e5630cc/talpid-core/src/firewall/linux.rs#L62)):*
> ```XML
>     LazyLock::new(|| CString::new("prerouting").unwrap());
> static MANGLE_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("mangle").unwrap());
> static NAT_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("nat").unwrap());
> ```

Nit: I think these uses of `LazyLock` could fairly easily be replaced by swapping to `&CStr`

```rust
static TABLE_NAME: &CStr = c"mullvad";
static IN_CHAIN_NAME: &CStr = c"input";
static OUT_CHAIN_NAME: &CStr = c"output";
static FORWARD_CHAIN_NAME: &CStr = c"forward";
static PREROUTING_CHAIN_NAME: &CStr = c"prerouting";
static MANGLE_CHAIN_NAME: &CStr = c"mangle";
static NAT_CHAIN_NAME: &CStr = c"nat";
```
Might apply for other uses of static `CString`s as well



_Code quote:_
```XML
static TABLE_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("mullvad").unwrap());
static IN_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("input").unwrap());
static OUT_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("output").unwrap());
static FORWARD_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("forward").unwrap());
static PREROUTING_CHAIN_NAME: LazyLock<CString> =
    LazyLock::new(|| CString::new("prerouting").unwrap());
static MANGLE_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("mangle").unwrap());
static NAT_CHAIN_NAME: LazyLock<CString> = LazyLock::new(|| CString::new("nat").unwrap());
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529)* status: 0 of 54 files reviewed, all discussions resolved

___
*[`talpid-core/src/firewall/linux.rs` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529#-O32rqHY5BUkwR9ca8Ha:-O32wQTB6OOZLF05jZD-:b-9lt30u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5e78a31851ab8af1533a7ff0f97399f3e5630cc/talpid-core/src/firewall/linux.rs#L62)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: I think these uses of `LazyLock` could fairly easily be replaced by swapping to `&CStr`

```rust
static TABLE_NAME: &CStr = c"mullvad";
static IN_CHAIN_NAME: &CStr = c"input";
static OUT_CHAIN_NAME: &CStr = c"output";
static FORWARD_CHAIN_NAME: &CStr = c"forward";
static PREROUTING_CHAIN_NAME: &CStr = c"prerouting";
static MANGLE_CHAIN_NAME: &CStr = c"mangle";
static NAT_CHAIN_NAME: &CStr = c"nat";
```
Might apply for other uses of static `CString`s as well
</blockquote></details>

Great idea!

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 27 of 52 files at r1, 31 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-wireguard/src/lib.rs` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529#-O5HSgZq-tw8uDGT7y1y:-O5HSgZq-tw8uDGT7y1z:bkzq0nv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc4f2b48f0fc0d2364ab95da86c50103c00d47/talpid-wireguard/src/lib.rs#L16)):*
> ```XML
> use std::io;
> #[cfg(target_os = "linux")]
> use std::sync::LazyLock;
> ```

Nit The Linux-specific imports could be grouped to reduce visual clutter a bit

```rust
#[cfg(target_os = "linux")]
use std::{env, sync::LazyLock};
#[cfg(windows)]
use std::io;
```



_Code quote:_
```XML
#[cfg(target_os = "linux")]
use std::env;
#[cfg(windows)]
use std::io;
#[cfg(target_os = "linux")]
use std::sync::LazyLock;
```

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6529)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
