### PR TITLE
Replace browser-sync

### PR DESCRIPTION
**Pull request by raksooo**
This PR removes the dependency on `browser-sync` for hotreloading and instead adds a listener on the `SIGUSR1` signal to the main process which triggers a reload of the browser window. Browser-sync has had a lot of vulnerabilities in it's dependency tree so hopefully this change will decrease the amount of future vulnerabilities in our dependency tree.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767#-MahlHVWDFwFfl7y7LDQ:-MahlHVWDFwFfl7y7LDR:bk88gvr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aa1a4605d843431e6331deea23c474ec034965e/gui/src/main/index.ts#L244)):*
> ```XML
>     if (process.env.NODE_ENV === 'development') {
>       process.on('SIGUSR1', () => {
>         console.log(3);
> ```

Left over?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 243 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767#-Mahm1pK-eqU1_tprgXh:-Mahm1pK-eqU1_tprgXi:bs7fur6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aa1a4605d843431e6331deea23c474ec034965e/gui/src/main/index.ts#L243)):*
I like the solution but beware that based on docs this signal is reserved by node.js for starting the debugger.

> 'SIGUSR1' is reserved by Node.js to start the debugger. It's possible to install a listener but doing so might interfere with the debugger.

https://nodejs.org/api/process.html#process_process_kill_pid_signal

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 243 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767#-Mahm1pK-eqU1_tprgXh:-Mai7wYtEW9u6GK40m2u:b17wx6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aa1a4605d843431e6331deea23c474ec034965e/gui/src/main/index.ts#L243)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I like the solution but beware that based on docs this signal is reserved by node.js for starting the debugger.

> 'SIGUSR1' is reserved by Node.js to start the debugger. It's possible to install a listener but doing so might interfere with the debugger.

https://nodejs.org/api/process.html#process_process_kill_pid_signal

</blockquote></details>

Then we'll go with `SIGUSR2`. The documentation says that `SIGUSR2` is used to create a diagnostics report **if diagnostics is enabled**, which it isn't so we should be fine.
___
*[gui/src/main/index.ts, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767#-MahlHVWDFwFfl7y7LDQ:-Mai7q76EJvYep5HHlC1:b-a4wcvi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aa1a4605d843431e6331deea23c474ec034965e/gui/src/main/index.ts#L244)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Left over?
</blockquote></details>

Oops. Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
