### PR TITLE
Don't explicitly pass Tokio runtime handles to async functions or methods

### PR DESCRIPTION
**Pull request by dlon**
Instead, simply use [`Handle::current()`](https://docs.rs/tokio/1.14.0/tokio/runtime/struct.Handle.html#method.current). I decided to only do this for async functions, and not just any function that happens to be called in an async context.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 2429 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHPjKA0gf1omx9aBae:-MpHPjKA0gf1omx9aBaf:b-1rdyed) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/mullvad-daemon/src/lib.rs#L2429)):*
> ```XML
>         let (bypass_tx, mut bypass_rx) = mpsc::channel(1);
>         let daemon_tx = event_sender.to_specialized_sender();
>         runtime.spawn(async move {
> ```

Can't this be just `tokio::spawn` instead? We were already assuming it was running in an async context. And I think that's fine. This change is currently working backwards compared to what the PR is trying to achieve. If you really are afraid of accidentally calling this in a non async context then I prefer that being in the documentation over having to pass extra args like this.

We are obviously already using this in an async context, so why complicate matters?
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHSF8e3bx3PmF1988b:-MpHSF8e3bx3PmF1988c:br5hfi4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/talpid-core/src/tunnel_state_machine/mod.rs#L109)):*
> ```XML
>     #[cfg(target_os = "android")] android_context: AndroidContext,
> ) -> Result<Arc<mpsc::UnboundedSender<TunnelCommand>>, Error> {
>     let runtime = tokio::runtime::Handle::current();
> ```

Nitpick. But it's nicer if variables are declared/initialized where used. Here we use it much further down. If we need to keep this variable, can we declare it just before its use rather than here?
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHRml28htzot-ni4u8:-MpHRml28htzot-ni4u9:b-ikv53f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/talpid-core/src/tunnel_state_machine/mod.rs#L128)):*
> ```XML
>     let weak_command_tx = Arc::downgrade(&command_tx);
>     std::thread::spawn(move || {
>         let state_machine = runtime.block_on(TunnelStateMachine::new(
> ```

We are in an async context -> spawn a regular OS thread -> run an async constructor and finally blocks on a regular non-async `run` method... This is a lot of layers.

Would it be possible to not spawn any OS thread. But instead maybe spawn all this work in an async task and then use `tokio::task::spawn_blocking(state_machine.run())` instead of the other way around?

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[mullvad-daemon/src/lib.rs, line 2429 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHPjKA0gf1omx9aBae:-MpHfNmN5D4qPJdA_BxB:b-18nhh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/mullvad-daemon/src/lib.rs#L2429)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can't this be just `tokio::spawn` instead? We were already assuming it was running in an async context. And I think that's fine. This change is currently working backwards compared to what the PR is trying to achieve. If you really are afraid of accidentally calling this in a non async context then I prefer that being in the documentation over having to pass extra args like this.

We are obviously already using this in an async context, so why complicate matters?
</blockquote></details>

Why `Handle::current().spawn()` instead of `tokio::spawn`? I honestly don't know the difference, but the latter looks and sounds simpler and more direct.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHRml28htzot-ni4u8:-MpHflC862g61ODyrDn7:b-1t18o6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/talpid-core/src/tunnel_state_machine/mod.rs#L128)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We are in an async context -> spawn a regular OS thread -> run an async constructor and finally blocks on a regular non-async `run` method... This is a lot of layers.

Would it be possible to not spawn any OS thread. But instead maybe spawn all this work in an async task and then use `tokio::task::spawn_blocking(state_machine.run())` instead of the other way around?
</blockquote></details>

Wow. This is sooo much better :heart_eyes:

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @faern)

___
*[mullvad-daemon/src/lib.rs, line 2429 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHPjKA0gf1omx9aBae:-MpHfObB4OkS1PWE6L5s:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/mullvad-daemon/src/lib.rs#L2429)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why `Handle::current().spawn()` instead of `tokio::spawn`? I honestly don't know the difference, but the latter looks and sounds simpler and more direct.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 128 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpHRml28htzot-ni4u8:-MpHUnsS2ThBC6czAQlw:b-nh8ru6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62fc8bb07afe558cb5223f50280532fa70ec3100/talpid-core/src/tunnel_state_machine/mod.rs#L128)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Wow. This is sooo much better :heart_eyes: 
</blockquote></details>

Yes! :) I can't remember the original reason for this onion. I think it had something to do with `block_on` being used in a bunch of places inside `TunnelStateMachine::new` (when it wasn't async), but it's no longer a problem.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 8 of 9 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 8 of 9 files reviewed, all discussions resolved

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 9 of 10 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/dns/macos.rs, line 137 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpMoymk4LufcO6vQ6N-:-MpMnV9pEp0G0ENUHC-y:b56tfq8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ebce308b8cb5dcff134931e395131dfa8efa7e6/talpid-core/src/dns/macos.rs#L137)):*
> ```XML
> /// SAFETY: The `SCDynamicStore` can be sent to other threads since it doesn't share mutable state
> /// with anything else.
> unsafe impl Send for DnsMonitor {}
> ```

`Send` can't be implemented directly on `SCDynamicStoreRef`, because `SCDynamicStore` is cloneable, and it doesn't appear to be safe to mutate the store from multiple threads simultaneously. (Correct me if I'm wrong.)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/dns/macos.rs, line 137 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpMoymk4LufcO6vQ6N-:-MpOaOX87a1EE-rW2QZd:b-mmu3jl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ebce308b8cb5dcff134931e395131dfa8efa7e6/talpid-core/src/dns/macos.rs#L137)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`Send` can't be implemented directly on `SCDynamicStoreRef`, because `SCDynamicStore` is cloneable, and it doesn't appear to be safe to mutate the store from multiple threads simultaneously. (Correct me if I'm wrong.)
</blockquote></details>

This is a good point. I hadn't considered the cloneability of `SCDynamicStore`. Gah, unfortunately, one cannot newtype away the cloneability :/

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by faern — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/dns/macos.rs, line 137 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144#-MpMoymk4LufcO6vQ6N-:-MpQPy1_9c6beLFnqFRz:bls6rhq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ebce308b8cb5dcff134931e395131dfa8efa7e6/talpid-core/src/dns/macos.rs#L137)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is a good point. I hadn't considered the cloneability of `SCDynamicStore`. Gah, unfortunately, one cannot newtype away the cloneability :/ 
</blockquote></details>

I don't think it should be wrapped in a mutex, etc., etc. Let's just keep it in mind?

**Pull request merged**
