### PR TITLE
Update to electron 11.4.10

### PR DESCRIPTION
**Pull request by raksooo**
This PR upgrades Electron from 11.2.3 to 11.4.9 which includes the fix for developer tools when loading page from file.

Electron changelogs:
https://github.com/electron/electron/releases/tag/v11.3.0
https://github.com/electron/electron/releases/tag/v11.4.0
https://github.com/electron/electron/releases/tag/v11.4.1
https://github.com/electron/electron/releases/tag/v11.4.2
https://github.com/electron/electron/releases/tag/v11.4.3
https://github.com/electron/electron/releases/tag/v11.4.4
https://github.com/electron/electron/releases/tag/v11.4.5
https://github.com/electron/electron/releases/tag/v11.4.6
https://github.com/electron/electron/releases/tag/v11.4.7
https://github.com/electron/electron/releases/tag/v11.4.8
https://github.com/electron/electron/releases/tag/v11.4.9

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)

### CODE REVIEW

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-:-MduxDrqB-3c3zM41YzY:bnfp4nl)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/redux/store.ts, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-MduxfHJ1HqCuBciJUSl:-MduxfHJ1HqCuBciJUSm:b-x32ngv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26aa613ecf1b2e39b8b4d3c541d721882f4e0ef4/gui/src/renderer/redux/store.ts#L49)):*
> ```XML
>   if (initialState) {
>     // eslint-disable-next-line @typescript-eslint/no-explicit-any
>     return createStore(rootReducer, initialState, (window as any).__REDUX_DEVTOOLS_EXTENSION__?.());
> ```

Maybe assign the result of `__REDUX_DEVTOOLS_EXTENSION__?.()` to a variable and then use it in both branches?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/redux/store.ts, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-MduyEPlEccC2MjXuCmQ:-MduyEPlEccC2MjXuCmR:b-pu7unu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be5c048ae44daaf4122feb13ce11544b82aef9b0/gui/src/renderer/redux/store.ts#L36)):*
> ```XML
> 
> export default function configureStore(initialState?: IReduxState) {
>   const actionCreators = {
> ```

What exactly happened to that part? Does Redux automatically pick up actions now?

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @raksooo)

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
Since `window.isRunningInDevelopment` wasn't set before `createStore()` was called I had to fix that. I've made `preload.ts` retrieve `platform` and `nodeEnv` synchronously to make sure that those are available when the renderer process starts. That required me to change the structure of the `window` object a bit and that's why there are so many changes.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-:-MdvZSStCOXeAN3cYaWF:b12fzc8)* status: 5 of 22 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/renderer/redux/store.ts, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-MduyEPlEccC2MjXuCmQ:-MdvZ3cP4M1fWzChNqvp:bi9cnxe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be5c048ae44daaf4122feb13ce11544b82aef9b0/gui/src/renderer/redux/store.ts#L36)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

What exactly happened to that part? Does Redux automatically pick up actions now?
</blockquote></details>

Nope, my mistake. I've added it back but refactored this a bit. An issue was that `window.isRunningInDevelopment` wasn't set until after this was run so I had to set it in `preload.ts` instead.
___
*[gui/src/renderer/redux/store.ts, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-MduxfHJ1HqCuBciJUSl:-MdvYsSR3kfcdOvFTeat:b-v9ils) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26aa613ecf1b2e39b8b4d3c541d721882f4e0ef4/gui/src/renderer/redux/store.ts#L49)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe assign the result of `__REDUX_DEVTOOLS_EXTENSION__?.()` to a variable and then use it in both branches?
</blockquote></details>

We never pass an initial state so this isn't even needed.

**Review by pronebird — APPROVED** [review]
> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-:-Me4aBUK1NWK2AHiROqT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
I saw that Electron released 11.4.10 so I updated to that version instead.
https://github.com/electron/electron/releases/tag/v11.4.10

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833#-:-Me5pHXT4j3YQ4mxCgWp:bsc172d)* status: 17 of 23 files reviewed, all discussions resolved (waiting on @pronebird)

**Review by pronebird — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2833)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
