### PR TITLE
Implement increased power consumption warning

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352)

### CODE REVIEW

**Review by Pururun — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 424 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352#-OEJ7iTJ0vbTZ71nQ5sP:-OEJ7iTJ0vbTZ71nQ5sQ:b-194n34) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2dd87a2b0eabdf5c5a7bdcfdfe7ac4440ece83da/android/lib/resource/src/main/res/values/strings.xml#L424)):*
> ```XML
>     <string name="open_feature_settings">Open %1$s settings</string>
>     <string name="search">Search</string>
>     <string name="obfuscation_info_shadowsocks_batteryusage">Attention: using Shadowsocks increases battery consumption with heavy data usage.</string>
> ```

Nit: I find this sentence a bit confusing. Should it not be "together with increased data usage". I think just with is not really understandable and heavy also feels a bit weird.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 424 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352#-OEJ7iTJ0vbTZ71nQ5sP:-OEJt8a8EZgzuYjEprCc:bijkm88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2dd87a2b0eabdf5c5a7bdcfdfe7ac4440ece83da/android/lib/resource/src/main/res/values/strings.xml#L424)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Nit: I find this sentence a bit confusing. Should it not be "together with increased data usage". I think just with is not really understandable and heavy also feels a bit weird.
</blockquote></details>

Updated the text.

**Review by Pururun — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 424 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352#-OEJ7iTJ0vbTZ71nQ5sP:-OEJuA-CAWU4VtYL8X7N:boz47zz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2dd87a2b0eabdf5c5a7bdcfdfe7ac4440ece83da/android/lib/resource/src/main/res/values/strings.xml#L424)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Updated the text.
</blockquote></details>

Much better. :)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352#-:-OEJwlWV-FEFWCX_-ppx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
