### PR TITLE
Limit the size of custom list names to 30 graphemes

### PR DESCRIPTION
**Pull request by pinkisemils**
I've gone and added a limitation on the length of the name of a custom list to 30 UTF-8 graphemes. And accidentally also reworked how custom lists are saved. Feel free to dismiss the changes in their entirety because of that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/custom_list.rs` line 129 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141#-Nvg-d7674iQ_dejhJqg:-NvgF1XUD6Ydjol9ZD23:bhfzfnj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3af27d1c0173583b1e70f6f8db32437771b702c3/mullvad-types/src/custom_list.rs#L129)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

How about just using an iterator + `find`?
```
self.check_list_name_unique(&new_list)?;
let current_list = self.custom_lists.iter_mut().find(...).map_err(Error::ListNotFound)?;
```
</blockquote></details>

I think moving that into it's own function is fine, but there's no need to reach for a `let Some(...` binding since we can just use `ok_or`. 
___
*[`mullvad-types/src/custom_list.rs` line 149 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141#-Nvg-5aX5_PTkVF7xtAb:-NvgF9zt3UEJOGvH1aS-:b-tj1rmb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3af27d1c0173583b1e70f6f8db32437771b702c3/mullvad-types/src/custom_list.rs#L149)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should test for equality, no?
</blockquote></details>

Absolutely correct. We could also add some unit tests for this so that my fat fingers don't do any harm.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)* status: 5 of 6 files reviewed, 1 unresolved discussion

___
*[`mullvad-types/src/custom_list.rs` line 149 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141#-Nvg-5aX5_PTkVF7xtAb:-NvgHJoQ0hd2737cvFEo:bxsioba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3af27d1c0173583b1e70f6f8db32437771b702c3/mullvad-types/src/custom_list.rs#L149)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Absolutely correct. We could also add some unit tests for this so that my fat fingers don't do any harm.
</blockquote></details>

We should. But I don't want to force you to write a bunch of tests that should have already existed. :smile:

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-types/src/custom_list.rs` line 149 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141#-Nvg-5aX5_PTkVF7xtAb:-NvgPwGXDnsIkTsYJbZD:b-q62it1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3af27d1c0173583b1e70f6f8db32437771b702c3/mullvad-types/src/custom_list.rs#L149)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We should. But I don't want to force you to write a bunch of tests that should have already existed. :smile:
</blockquote></details>

https://linear.app/mullvad/issue/DES-852/add-unit-tests-for-custom-list-validation-logic-in-the-daemon
Well, now that work at least won't be forgotten by Linear.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by pinkisemils** [comment]
One last change - the source error in `daemon::Error::CustomListError` must be included in it's display, otherwise the user of the CLI won't get a clue as to why `sakdlmflakdsnmfdsaljs dkjgnsadmcalkdsnkasjdngflkdsajnflkcasdnglkjsanfdsaflkjsabgdsa` is not a valid custom list name.

**Pull request merged**
