### PR TITLE
Refresh expiry time

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR adds automatic refresh for account expiration each time Account view appears. This includes the situation if the view is already rendered but the window toggles between visible/hidden. 

There is really not much indication that the account expiration is being refreshed but hopefully that shouldn't matter now as it should happen fast.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)

### CODE REVIEW

**Comment by pinkisemils** [comment]
Reviewed 11 of 11 files at r1.
Review status: 0 of 11 files reviewed, all discussions resolved (waiting on @jvff and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)*

**Comment by jvff** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

---

*[app/redux/account/actions.js, line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209#-LElJc5u6EdG-mqefqg0:-LElJc5w-zOeJl3C1oxi:b-d4cj5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88b42a0e0f50da2ea240d2cda6c680da3a08314c/app/redux/account/actions.js#L108)):*
> ```JavaScript
>   return {
>     type: 'UPDATE_ACCOUNT_EXPIRY',
>     expiry: expiry,
> ```

Can this line be just `expiry,`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)*

**Comment by pronebird** [comment]
Review status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @jvff and @pinkisemils)

---

*[app/redux/account/actions.js, line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209#-LElJc5u6EdG-mqefqg0:-LEnlb_s8Bj00Rc8Pqfb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88b42a0e0f50da2ea240d2cda6c680da3a08314c/app/redux/account/actions.js#L108)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can this line be just `expiry,`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)*

**Comment by pinkisemils** [comment]
Reviewed 2 of 2 files at r2.
Review status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @jvff and @pinkisemils)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)*

**Comment by jvff** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)*

**Pull request merged**
