### PR TITLE
Disable App version cell click on release version

### PR DESCRIPTION
**Pull request by sabercodic**
Disable click and hide external link icon from App version cell on google play version.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
Can you update the changelog as well?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907#-:-N_cFBfD5tvdlsAS5yJv:b-eerxj5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907#-N_cPih19pNebDZlj3Bq):*
I suggest using the same commit message as the new changelog entry



_Code quote:_
```
Disable download page redirection on release version
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907#-N_cPih19pNebDZlj3Bq):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using the same commit message as the new changelog entry
</blockquote></details>

Done.

**Review by albin-mullvad — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
