### PR TITLE
Account tests

### PR DESCRIPTION
**Pull request by jvff**
Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Tests not visible to the user.**

This is the last regression test PR before the state refactor. It contains some commits to refactor some test helper code, and also two tests related to the usage of account tokens.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)

### CODE REVIEW

**Comment by faern** [comment]
Reviewed 4 of 5 files at r1.
Review status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils, @faern, and @jvff)

---

*[mullvad-tests/src/bin/mock_openvpn.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5iY_bA6kzs9n6Bko7:-LG5iY_bA6kzs9n6Bko8:b-ud96qh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/src/bin/mock_openvpn.rs#L17)):*
> ```Rust
> fn main() {
>     let (file, path) = create_args_file();
>     let cloned_path = path.clone();
> ```

I can't see you ever use `path`, so do you need to clone it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Review status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @pinkisemils, @faern, and @jvff)

---

*[mullvad-tests/tests/account.rs, line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5oD_69kUoKyCbQByW:-LG5oD_69kUoKyCbQByX:blwd78t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L25)):*
> ```Rust
>     let account_token = read_account_token(openvpn_args_file).unwrap();
> 
>     assert_eq!(account_token, account);
> ```

`account_token` and `account` are the same thing. It's from the name impossible to distinguish which one was the hardcoded value and which one was read out from the test. I propose naming them `expected_account`, `written_account` or similar.

---

*[mullvad-tests/tests/account.rs, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5oh4N3Al1pYcmU5-r:-LG5oh4N3Al1pYcmU5-s:brfb67o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L45)):*
> ```Rust
>         .unwrap();
> 
>     wait_for_file_to_be_deleted(openvpn_args_file, Duration::from_secs(5));
> ```

Doesn't this create a race condition? The file will be deleted and then re-created as fast as possible. So we won't know if the old file is still there or the new one has been created when we call this function?

A lot of these tests where we watch files seems fragile in that sense. It would feel more deterministic if we could set up watching of the directory the file should be in before we start running all the test code. And then when we want to verify stuff we can check in with the watcher what has happened and in what order exactly. Something like:

```rust
let daemon = DaemonRunner::spawn();
let monitor = path_monitor(daemon.mock_openvpn_args_file());

rpc_client.set_account(first_account);
assert_eq!(monitor.recv_event(), CREATED);
assert_eq!(monitor.recv_event(), WRITTEN);

rpc_client.set_account(second_account);
assert_eq!(monitor.recv_event(), DELETED);
assert_eq!(monitor.recv_event(), CREATED);
assert_eq!(monitor.recv_event(), WRITTEN);

let read_account = read_account_token(...);
assert_eq!(read_account, second_account);
```

---

*[mullvad-tests/tests/account.rs, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5owi37JB07Do2zeZR:-LG5owi4DY11Cf7XGKUv:blup9bp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L47)):*
> ```Rust
>     wait_for_file_to_be_deleted(openvpn_args_file, Duration::from_secs(5));
> 
>     let account_token = read_account_token(openvpn_args_file).unwrap();
> ```

Same as a comment earlier. The name only tells that it holds an account token. In a scope where three variables hold account tokens that become very non descriptive.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by jvff** [comment]
Review status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

---

*[mullvad-tests/src/bin/mock_openvpn.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5iY_bA6kzs9n6Bko7:-LG66UkA2rZaD-oarV7b:bis2hcy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/src/bin/mock_openvpn.rs#L17)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I can't see you ever use `path`, so do you need to clone it?
</blockquote></details>

Done.

Yes, it's used in the last line of the function, but it worked without cloning by explicitly creating a thread-safe reference using `Arc`. Not sure if the extra verbosity was worth it, though.

That said, with the file watch refactor you suggested it became trivial to remove the shared path by creating the watcher instance and moving it instead of the actual path. The change to not clone using `Arc` is still present in one of the commits though.

---

*[mullvad-tests/tests/account.rs, line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5oD_69kUoKyCbQByW:-LG77kgK2ngF-bJSbV2u:b2izfij) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`account_token` and `account` are the same thing. It's from the name impossible to distinguish which one was the hardcoded value and which one was read out from the test. I propose naming them `expected_account`, `written_account` or similar.
</blockquote></details>

Done, but I preferred `specified_account` for the binding to the value specified externally (mocking user input) and `account_token_sent_to_plugin` for the tested binding.

---

*[mullvad-tests/tests/account.rs, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5oh4N3Al1pYcmU5-r:-LG8Sh_C4tvCD55JLWva:b-n9lhxs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L45)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Doesn't this create a race condition? The file will be deleted and then re-created as fast as possible. So we won't know if the old file is still there or the new one has been created when we call this function?

A lot of these tests where we watch files seems fragile in that sense. It would feel more deterministic if we could set up watching of the directory the file should be in before we start running all the test code. And then when we want to verify stuff we can check in with the watcher what has happened and in what order exactly. Something like:

```rust
let daemon = DaemonRunner::spawn();
let monitor = path_monitor(daemon.mock_openvpn_args_file());

rpc_client.set_account(first_account);
assert_eq!(monitor.recv_event(), CREATED);
assert_eq!(monitor.recv_event(), WRITTEN);

rpc_client.set_account(second_account);
assert_eq!(monitor.recv_event(), DELETED);
assert_eq!(monitor.recv_event(), CREATED);
assert_eq!(monitor.recv_event(), WRITTEN);

let read_account = read_account_token(...);
assert_eq!(read_account, second_account);
```
</blockquote></details>

Done. Excellent idea, things become clearer and more deterministic. There is a "verbosity cost", but I think its minimal in the current usages.

The race condition was present before, but there was a small window where it could happen, and even if it did happen, the worst thing that could happen was the test take a little longer (no assertions were made during the wait). However, just as you said, the refactor makes what happens to the file clearer.

---

*[mullvad-tests/tests/account.rs, line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5owi37JB07Do2zeZR:-LG79JSpBwHjrzPoYAnP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L47)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Same as a comment earlier. The name only tells that it holds an account token. In a scope where three variables hold account tokens that become very non descriptive.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Reviewed 3 of 4 files at r2.
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @pinkisemils, @faern, and @jvff)

---

*[mullvad-tests/src/lib.rs, line 116 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9j3fD9hRwT9vlF0aE:-LG9j3fD9hRwT9vlF0aF:b-9cjbmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/src/lib.rs#L116)):*
> ```Rust
>     fn next(&mut self) -> Option<Self::Item> {
>         loop {
>             match self.events.recv_timeout(self.timeout) {
> ```

Isn't the problem here that the timeout is not decreased in the way you had before?
So a call to `PathWatcher::next()` can block forever given that there are other `RawEvents` coming in before `self.timeout`. You likely need some local time remaining counter in the method like you had before?

---

*[mullvad-tests/src/bin/mock_openvpn.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5iY_bA6kzs9n6Bko7:-LG9fb14CQOwyejdXqIW:b7566pz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/src/bin/mock_openvpn.rs#L17)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.

Yes, it's used in the last line of the function, but it worked without cloning by explicitly creating a thread-safe reference using `Arc`. Not sure if the extra verbosity was worth it, though.

That said, with the file watch refactor you suggested it became trivial to remove the shared path by creating the watcher instance and moving it instead of the actual path. The change to not clone using `Arc` is still present in one of the commits though.
</blockquote></details>

Ok, since it was removed it does not matter any more.

But no, I would not have replaced a clone with an `Arc`. Partly because it feels like it would be much more complicated to read, and partly because I'm pretty sure an atomic reference counter is more expensive than a single path clone :)

---

*[mullvad-tests/tests/account.rs, line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5oh4N3Al1pYcmU5-r:-LG9nEPuANndDdeJEg16:b-ifg1sa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/tests/account.rs#L45)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. Excellent idea, things become clearer and more deterministic. There is a "verbosity cost", but I think its minimal in the current usages.

The race condition was present before, but there was a small window where it could happen, and even if it did happen, the worst thing that could happen was the test take a little longer (no assertions were made during the wait). However, just as you said, the refactor makes what happens to the file clearer.
</blockquote></details>

Awesome you liked the idea and implemented it right away. This looks really useful!

---

*[mullvad-tests/tests/account.rs, line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9nl8l8GtOCyN-mHpx:-LG9nl8l8GtOCyN-mHpy:bqm1z2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/tests/account.rs#L68)):*
> ```Rust
> 
>     let _wait_for_args_file =
>         PathWatcher::watch(&args_file_path)?.find(|&event| event == watch_event::CLOSE_WRITE);
> ```

For some of the calls here the file will already be guaranteed to exist. Such as the test above where you explicitly wait for `CLOSE_WRITE` before calling `read_accound_token`. For those cases it would be much faster if this method just had a guard `args_file_path.exists()` around the patch watching code.

And it would make some tests a bit more verbose, but this function very much more do-only-one-thing if it just parsed the account token and the tests were responsible for waiting for the file prior to calling here. Not sure if it's better for readability, mostly noting that there are a lot of helper functions here that does a lot of stuff rather than just what it sounds like they are doing.

---

*[mullvad-tests/tests/connection.rs, line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9ol1MCX-9ywEoEO-N:-LG9ol1MCX-9ywEoEO-O:b-j4nmvy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/tests/connection.rs#L85)):*
> ```Rust
>     assert_eq!(
>         openvpn_args_file_events.next(),
>         Some(watch_event::CLOSE_WRITE)
> ```

This section that checks `CREATE -> WRITE -> ... -> WRITE -> CLOSE_WRITE` is repeated a lot and it feels like a very common pattern, `created_and_written`? So could this maybe become a helper method on the `PathWatcher` or something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Reviewed 1 of 4 files at r2.
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @pinkisemils, @faern, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by jvff** [comment]
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @pinkisemils and @faern)

---

*[mullvad-tests/src/lib.rs, line 116 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9j3fD9hRwT9vlF0aE:-LGAt88X69ZwZ8fxhMBJ:b-kn0usi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/src/lib.rs#L116)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Isn't the problem here that the timeout is not decreased in the way you had before?
So a call to `PathWatcher::next()` can block forever given that there are other `RawEvents` coming in before `self.timeout`. You likely need some local time remaining counter in the method like you had before?
</blockquote></details>

Done. Good catch :)

---

*[mullvad-tests/src/bin/mock_openvpn.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5iY_bA6kzs9n6Bko7:-LGBQ_oM6HHilCLqICkM:b-5hnigr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/src/bin/mock_openvpn.rs#L17)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ok, since it was removed it does not matter any more.

But no, I would not have replaced a clone with an `Arc`. Partly because it feels like it would be much more complicated to read, and partly because I'm pretty sure an atomic reference counter is more expensive than a single path clone :)
</blockquote></details>

Ok, reverted the history to the `clone` version. I actually thought the `Arc` could be faster because the slow atomic operations would be performed on the same thread and hence would not be slow at all, but I forgot that it had to "clone" the contents of the path to the heap anyway (well, move actually, but inside computers there is no move, just clone :) ).

---

*[mullvad-tests/tests/account.rs, line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9nl8l8GtOCyN-mHpx:-LGB9EAV3iqVn2WJxzcM:b-ehyvzj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/tests/account.rs#L68)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

For some of the calls here the file will already be guaranteed to exist. Such as the test above where you explicitly wait for `CLOSE_WRITE` before calling `read_accound_token`. For those cases it would be much faster if this method just had a guard `args_file_path.exists()` around the patch watching code.

And it would make some tests a bit more verbose, but this function very much more do-only-one-thing if it just parsed the account token and the tests were responsible for waiting for the file prior to calling here. Not sure if it's better for readability, mostly noting that there are a lot of helper functions here that does a lot of stuff rather than just what it sounds like they are doing.
</blockquote></details>

Done. Removed the wait step here and moved the one in the connection steps to the parent function (I think now I understood better your suggestion to separate the functions?).

---

*[mullvad-tests/tests/connection.rs, line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9ol1MCX-9ywEoEO-N:-LGB9SSB5ys7NIT0xRi6:b6wboy0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/tests/connection.rs#L85)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This section that checks `CREATE -> WRITE -> ... -> WRITE -> CLOSE_WRITE` is repeated a lot and it feels like a very common pattern, `created_and_written`? So could this maybe become a helper method on the `PathWatcher` or something?
</blockquote></details>

Done. Simplified things a lot.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r3.
Review status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @pinkisemils, @faern, and @jvff)

---

*[mullvad-tests/src/lib.rs, line 112 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPCuUR2D1e3DJ5DWsR:-LGPCuUR2D1e3DJ5DWsS:bk1kn35) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L112)):*
> ```Rust
>     pub fn check_create_write_close_sequence(&mut self) -> bool {
>         if self.next() != Some(watch_event::CREATE) {
>             return false;
> ```

With the `-> bool` approach you are just going to get errors that it expected true, but found false, from the return value of `check_create_write_close_sequence`. Would it not be better to name it `assert_create_write_close(&mut self)` without any return and that does internal assertions? We want to panic anyway since it's tests and I think that might give better error messages.

---

*[mullvad-tests/src/lib.rs, line 180 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPDLXD05yub9tMqp0q:-LGPDLXD05yub9tMqp0r:b67b00u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L180)):*
> ```Rust
>         r#"{
>             "countries": [{
>                 "name": "Sweden",
> ```

Any practical reason you had to change to more "real" mock data?

---

*[mullvad-tests/src/bin/mock_openvpn.rs, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG5iY_bA6kzs9n6Bko7:-LGPCWVNAgfYfrdHLmEs:bu7ghl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ae87e9101ffe654f38877fd22e5f8960c519057c/mullvad-tests/src/bin/mock_openvpn.rs#L17)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Ok, reverted the history to the `clone` version. I actually thought the `Arc` could be faster because the slow atomic operations would be performed on the same thread and hence would not be slow at all, but I forgot that it had to "clone" the contents of the path to the heap anyway (well, move actually, but inside computers there is no move, just clone :) ).
</blockquote></details>

Performance is very much a non issue here. Especially when we compare stuff on the microsecond level like these two things probably are. For tests the readability and correctness is what matters.

If performance was an issue this would likely be such a close call that I would ask for a benchmark before taking a decision anyway :)

---

*[mullvad-tests/tests/account.rs, line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9nl8l8GtOCyN-mHpx:-LGPEDNf4pRvT9qEbQp6:b-xj0o5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/tests/account.rs#L68)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. Removed the wait step here and moved the one in the connection steps to the parent function (I think now I understood better your suggestion to separate the functions?).
</blockquote></details>

Nice :+1: Yeah now `read_account_token` is much more focused and easy to understand on its own.

---

*[mullvad-tests/tests/connection.rs, line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LG9ol1MCX-9ywEoEO-N:-LGPEN_aDoc71xgHB4e3:bx5zu2x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/240ba6103e854e5b235a441aead57e342d2c69b6/mullvad-tests/tests/connection.rs#L85)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. Simplified things a lot.
</blockquote></details>

Sweeet!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @pinkisemils, @faern, and @jvff)

---

*[mullvad-tests/src/lib.rs, line 121 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPFCZn-WHuxDges699:-LGPFCZn-WHuxDges69A:b1pk86i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L121)):*
> ```Rust
> 
>         while let Some(watch_event::WRITE) = event {
>             event = self.next();
> ```

This loop would happily exit if `event == None`. Thus if the sequence of events is `CREATE -> WRITE -> WRITE -> CLOSE_WRITE` but the second `WRITE` came in slower than the timeout then this function would return false. But not where you expect it to, because it would return false on the last line where it expects `Some(CLOSE_WRITE)` but got `None`. If possible to write nicely I think it would be more understandable if the `WRITE` loop panicked on `None` and only exited nicely when `event` is `Some(x)` where `x != WRITE`.

```rust
loop {
    match self.next() {
        Some(watch_event::CLOSE_WRITE) => break,
        event => assert_eq!(event, Some(watch_event::WRITE)),
    }
}
```
Maybe?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r3.
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @pinkisemils, @faern, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 5 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
Review status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by jvff** [comment]
Review status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---

*[mullvad-tests/src/lib.rs, line 112 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPCuUR2D1e3DJ5DWsR:-LGQ9Aj16aS8vKDJFkB4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L112)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

With the `-> bool` approach you are just going to get errors that it expected true, but found false, from the return value of `check_create_write_close_sequence`. Would it not be better to name it `assert_create_write_close(&mut self)` without any return and that does internal assertions? We want to panic anyway since it's tests and I think that might give better error messages.
</blockquote></details>

Done.

---

*[mullvad-tests/src/lib.rs, line 121 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPFCZn-WHuxDges699:-LGQA3t-0HLjHBJ6OdiL:bkg8gih) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L121)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This loop would happily exit if `event == None`. Thus if the sequence of events is `CREATE -> WRITE -> WRITE -> CLOSE_WRITE` but the second `WRITE` came in slower than the timeout then this function would return false. But not where you expect it to, because it would return false on the last line where it expects `Some(CLOSE_WRITE)` but got `None`. If possible to write nicely I think it would be more understandable if the `WRITE` loop panicked on `None` and only exited nicely when `event` is `Some(x)` where `x != WRITE`.

```rust
loop {
    match self.next() {
        Some(watch_event::CLOSE_WRITE) => break,
        event => assert_eq!(event, Some(watch_event::WRITE)),
    }
}
```
Maybe?
</blockquote></details>

Done, but a little differently. I think the event we're truly expecting (after having asserted at least one `WRITE` event) is the final `CLOSE_WRITE` event, so I changed the assertion so that the error becomes clearer.

---

*[mullvad-tests/src/lib.rs, line 180 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPDLXD05yub9tMqp0q:-LGPkN3--OM3WH0Mzyqp:b-acs41d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L180)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Any practical reason you had to change to more "real" mock data?
</blockquote></details>

Yeah, unfortunately the original version had trailing commas, which led to deserialization errors. The tests didn't fail because it would just fall back to downloading the relay list. That worked most of the time, but added test execution time and sometimes the test failed because downloading it took too long.

So I fixed that problem, and then suddenly the tunnel fails to connect because the default relay constraint is to use a relay from Sweden. To fix this problem I had to change the mocked data to have a mock relay in Sweden.

---

*[mullvad-tests/src/lib.rs, line 375 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGRMME94tFOqLAoUK0W:-LGRMME94tFOqLAoUK0X:b-ugywa9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2e55562bb21b987ccab798202a22ce22587f375/mullvad-tests/src/lib.rs#L375)):*
> ```Rust
>         let mut env: HashMap<String, String> = HashMap::new();
> 
>         env.insert("dev".to_owned(), "lo".to_owned());
> ```

I had to change this because otherwise some tests would because the firewall code would complain about the usage of an invalid interface.

---

*[mullvad-tests/tests/connection.rs, line 247 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGRMWmR75G0y5qlA08d:-LGRMWmR75G0y5qlA08e:b7jnsjc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2e55562bb21b987ccab798202a22ce22587f375/mullvad-tests/tests/connection.rs#L247)):*
> ```Rust
> fn assert_state_event(receiver: &mpsc::Receiver<DaemonState>, expected_state: DaemonState) {
>     let received_state = receiver
>         .recv_timeout(Duration::from_secs(3))
> ```

This had to be increased because sometimes setting up the firewall would take long enough for the test to timeout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by pinkisemils** [comment]
Reviewed 3 of 3 files at r4.
Review status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @faern, @pinkisemils, and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r4.
Review status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @faern, @pinkisemils, and @jvff)

---

*[mullvad-tests/src/lib.rs, line 180 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGPDLXD05yub9tMqp0q:-LGUu4Gg1XoHNHa4hEzw:b-a7jufr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ed32e7d34610d7ff8d5956879c6a9b3b742e8b87/mullvad-tests/src/lib.rs#L180)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yeah, unfortunately the original version had trailing commas, which led to deserialization errors. The tests didn't fail because it would just fall back to downloading the relay list. That worked most of the time, but added test execution time and sometimes the test failed because downloading it took too long.

So I fixed that problem, and then suddenly the tunnel fails to connect because the default relay constraint is to use a relay from Sweden. To fix this problem I had to change the mocked data to have a mock relay in Sweden.
</blockquote></details>

I see. Thanks for the explanation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by faern** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[mullvad-tests/tests/connection.rs, line 247 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGRMWmR75G0y5qlA08d:-LGUuSmO4VSfU9wZAVlD:bba1nu6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f2c92cacb926dc9c8907dfd21f791f0352fe7a8/mullvad-tests/tests/connection.rs#L247)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This had to be increased because sometimes setting up the firewall would take long enough for the test to timeout.
</blockquote></details>

On Linux? :open_mouth: That operation should really be instant. Like super fast!

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Comment by jvff** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

---

*[mullvad-tests/tests/connection.rs, line 247 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255#-LGRMWmR75G0y5qlA08d:-LGUvhW3BsTLBoIBmhVb:bsfeeq9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f2c92cacb926dc9c8907dfd21f791f0352fe7a8/mullvad-tests/tests/connection.rs#L247)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

On Linux? :open_mouth: That operation should really be instant. Like super fast!
</blockquote></details>

I think it takes about 100ms here. But this is enough to sometimes exceed the 1 second timeout because on the connecting step this happens after two files are written (one with the credentials for OpenVPN, the other from mock OpenVPN), an RPC connection is set up between the daemon and the mock OpenVPN plugin test code, etc. The timeout doesn't fire frequently, but depending on my Qubes load it happens :/

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)*

**Pull request merged**
