### PR TITLE
Inform the user if they cannot react api.mullvad.net when trying to log in

### PR DESCRIPTION
**Pull request by eriklarko**
This can be reproduced by adding something like `1.1.1.1 api.mullvad.net` to `/etc/hosts`

I also introduce an unknown error type to avoid future similar issues.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/43)

### CODE REVIEW

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 195 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3TNTJHlZpe92IU51Kj:bdte9cy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
> ```JavaScript
> 
>   _rpcErrorToBackendError(e) {
>     const isJsonRpcError = e.code;
> ```

All good except I don't understand this check. It seems that it will never be true since the `e.code` values are negative :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 195 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3TNelg-T_gHr6C0LOm:bwfsg5k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

All good except I don't understand this check. It seems that it will never be true since the `e.code` values are negative :D
</blockquote></details>

Sorry the check is one line below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TNoV3cQWA9Hau7rkM:b-k1ftbi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
> ```JavaScript
>     const isJsonRpcError = e.code;
>     if (isJsonRpcError) {
>       switch(e.code) {
> ```

Switch is missing the default case. I am pretty sure Flow would warn you on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by eriklarko** [comment]
*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TNyisSPgIGp4ILfx2:bam32se) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Switch is missing the default case. I am pretty sure Flow would warn you on this.
</blockquote></details>

That is on purpose as I want the `UNKNOWN_ERROR` return a few lines down to get executed in that case. Flow doesn't warn here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by eriklarko** [comment]
*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TOY9QA-knrgdFE6mh:bmsdl22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

That is on purpose as I want the `UNKNOWN_ERROR` return a few lines down to get executed in that case. Flow doesn't warn here.
</blockquote></details>

I'm always a little torn in these cases, I feel that I should have a `default` case but I don't want to duplicate the error line. Too hard.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TOaYi26Kn3faonpBu:b-z9vdzw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

I'm always a little torn in these cases, I feel that I should have a `default` case but I don't want to duplicate the error line. Too hard.
</blockquote></details>

Maybe you could then get rid of isJsonRpcError check and simply move the check for TimeoutError and UNKNOWN_ERROR stuff into `default` case. This would pretty much be the same logic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TOovmw6EQS-EdliFo:b-5ybxil) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Maybe you could then get rid of isJsonRpcError check and simply move the check for TimeoutError and UNKNOWN_ERROR stuff into `default` case. This would pretty much be the same logic?
</blockquote></details>

i.e:

```
default:
   if (e.name === 'TimeOutError') {
      return new BackendError('COMMUNICATION_FAILURE');
    }
 
    return new BackendError('UNKNOWN_ERROR', e);
```

not sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by eriklarko** [comment]
*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TP5Snx-0M0PNPxBZo:b-nyzar0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

i.e:

```
default:
   if (e.name === 'TimeOutError') {
      return new BackendError('COMMUNICATION_FAILURE');
    }
 
    return new BackendError('UNKNOWN_ERROR', e);
```

not sure.
</blockquote></details>

Hmm, true. It would make it a little less clear that we're dealing with two different error types though. One is the JsonRpc errors and the other type is the Javascript errors that can be thrown for various reasons

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by eriklarko** [comment]
*[app/lib/backend.js, line 197 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNoV3cQWA9Hau7rkL:-L3TPLAuBC0P48u4W28J:b-umlpv1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L197)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Hmm, true. It would make it a little less clear that we're dealing with two different error types though. One is the JsonRpc errors and the other type is the Javascript errors that can be thrown for various reasons
</blockquote></details>

The JsonRpc errors originate from the BE, while the JS errors come from the FE. So it feels like it should be clear that they are different...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 195 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3bXc2VznA9oDYU4iyM:b-17qlv6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Sorry the check is one line below.
</blockquote></details>

Oh snap Javascript is a weird one, I forgot that `if(-200)` is actually `true`.

Can we make this more explicit:

```
if((typeof(e.code) === 'number')) {
  switch(e.code) {
    ...
  }
}
```

Also the present of `.code` does not uniquely identify the JSON RPC error. Can be any custom error.

I'd understand this:

```
const isJsonRpcError = e instanceof JSONRPCError;
```

But simply checking for `code` is not very unique. But then we can't do `instanceof` for Errors in JS because of some quirks with Error inheritance for which we would need a babel plugin to fix it. (https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend) :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 195 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3bfBV0uxnKjZUNn5_v:b-iafrdl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Oh snap Javascript is a weird one, I forgot that `if(-200)` is actually `true`.

Can we make this more explicit:

```
if((typeof(e.code) === 'number')) {
  switch(e.code) {
    ...
  }
}
```

Also the present of `.code` does not uniquely identify the JSON RPC error. Can be any custom error.

I'd understand this:

```
const isJsonRpcError = e instanceof JSONRPCError;
```

But simply checking for `code` is not very unique. But then we can't do `instanceof` for Errors in JS because of some quirks with Error inheritance for which we would need a babel plugin to fix it. (https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend) :)
</blockquote></details>

Not my area really, but why do you handle two distinct error types in the same place if it can be hard to differentiate them? The RPC errors from the BE and any JS error happening during that process must stem from different places?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by eriklarko** [comment]
*[app/lib/backend.js, line 195 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3c-JwgYB2vKdHZ4hQy:b29mgau) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not my area really, but why do you handle two distinct error types in the same place if it can be hard to differentiate them? The RPC errors from the BE and any JS error happening during that process must stem from different places?
</blockquote></details>

Javascript uses exceptions so we have to deal with them, jsonrpc has a different error model and we need to handle that too. 

I'm changing the if statement to `hasOwnProperty` because we're going way off tangent here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by eriklarko** [comment]
*[app/lib/backend.js, line 195 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3c-dsuFLNusRoVTaDT:bw7aiyi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Javascript uses exceptions so we have to deal with them, jsonrpc has a different error model and we need to handle that too. 

I'm changing the if statement to `hasOwnProperty` because we're going way off tangent here
</blockquote></details>

going way off on a tangent* :) Going off tangents seems like a good thing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/lib/backend.js, line 195 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/43#-L3TNTJHlZpe92IU51Ki:-L3dMhQI611bNhtHsaf3:biq3ede) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50390122948e51d57eb63aaa4f8736f7a6aec818/app/lib/backend.js#L195)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I understand we have to handle both, and that they are different. It was kind of the core of my argumnt. I'm not going to get more involved here, just want to explain what I meant:
Since they must stem from different sources it should be possible to hand the two types of errors off to different functions for mapping to `BackendError`.
</blockquote></details>

@faern we can't identify errors without actually checking the error code which is (btw) custom too. Error codes are not unique so that we can handle the error that originates from somewhere else too. 

Eventually we'll put an effort to handle this either with unique error domain IDs or using babel plugin to enable a built-in Error subclasses which instances can be identified with `instanceof` operator.

The current approach that @eriklarko took basically checks the known error codes otherwise wraps a received error into `BackendError` with `UNKNOWN_ERROR` code. 

Most of emitted errors in JS probably don't contain the `code` so it's safe enough to assume that it's only RPC that does this in that context.

It's not ideal but it will do until we invent something better which the language does not provide the proper facilities for.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/43)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/43)*

**Pull request merged**
