### PR TITLE
Refactor `TunConfig` and `TalpidVpnService` and fix duplicate tun configuration

### PR DESCRIPTION
**Pull request by dlon**
This PR refactors how the VPN service is set up on Android and fixes the issue of the VPN service being recreated needlessly.

Some changes:
* Move the ownership of `TunConfig` to `TunProvider`. Previously, the configuration was *partially* owned by `TunProvider`.
* Removed `TalpidVpnService.defaultTunConfig`.
* Split `TunConfig` into an internal type used by the tunnel state machine and a private type that maps to the arguments used by the `VpnService`.

Fix DES-1011.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 17 of 20 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-:-O45CItD6vzLjCNp6B_G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-:-O45PlGO9OJSP0A6Wyfk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 20 files at r1, 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/tunnel_state_machine/connected_state.rs` line 130 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45Z2RVA1GqM27TNbhX:-O45Z2RVA1GqM27TNbhY:b-7k6f8r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11adc05d190254314ca70fc3d8af5892aadc3ad7/talpid-core/src/tunnel_state_machine/connected_state.rs#L130)):*
> ```XML
>             dns_ips
>         }
>     }
> ```

Note that we can drop the `#[allow(unused_variables]` directive.


Also, deploying the `Iterator` trait and `std::iter::once` the code can be simplified a bit further:
```rust
    fn get_dns_servers(&self, shared_values: &SharedTunnelStateValues) -> Vec<IpAddr> {
        use std::iter::{once, Iterator};
        if let Some(ref servers) = shared_values.dns_servers {
            servers.clone()
        } else {
            once(IpAddr::from(self.metadata.ipv4_gateway))
                .chain(self.metadata.ipv6_gateway.map(IpAddr::from))
                .collect()
        }
    }
```

Might not be worth it tho



_Code quote:_
```XML
    #[allow(unused_variables)]
    fn get_dns_servers(&self, shared_values: &SharedTunnelStateValues) -> Vec<IpAddr> {
        #[cfg(not(target_os = "android"))]
        if let Some(ref servers) = shared_values.dns_servers {
            servers.clone()
        } else {
            let mut dns_ips = vec![self.metadata.ipv4_gateway.into()];
            if let Some(ipv6_gateway) = self.metadata.ipv6_gateway {
                dns_ips.push(ipv6_gateway.into());
            };
            dns_ips
        }
        #[cfg(target_os = "android")]
        {
            let mut dns_ips = vec![];
            dns_ips.push(self.metadata.ipv4_gateway.into());
            if let Some(ipv6_gateway) = self.metadata.ipv6_gateway {
                dns_ips.push(ipv6_gateway.into());
            };
            dns_ips
        }
    }
```
___
*[`talpid-tunnel/src/tun_provider/mod.rs` line 68 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45lvmG9HYJGqrNuAg3:-O45lvmG9HYJGqrNuAg4:bsug97c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-tunnel/src/tun_provider/mod.rs#L68)):*
> ```XML
>         }
>         servers
>     }
> ```

Would it make sense to implement this on `TunnelMetadata` as well?



_Code quote:_
```XML
    /// Return a copy of all gateway addresses
    pub fn gateway_ips(&self) -> Vec<IpAddr> {
        let mut servers = vec![self.ipv4_gateway.into()];
        if let Some(gateway) = self.ipv6_gateway {
            servers.push(gateway.into());
        }
        servers
    }
```
___
*[`talpid-tunnel/src/tun_provider/mod.rs` line 89 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45m5WRB0Kh2a1l526Q:-O45m5WRB0Kh2a1l526R:b-qnszdw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-tunnel/src/tun_provider/mod.rs#L89)):*
> ```XML
>         }
>     }
> }
> ```

It's nice that we implement `Default`! Could we also explain how the values are derived? In some cases we could declare/use constants to convey the intent as well, for example using [`Ipv4Addr::UNSPECIFIED`](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#associatedconstant.UNSPECIFIED) & [`Ipv6Addr::UNSPECIFIED`](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html#associatedconstant.UNSPECIFIED)



_Code quote:_
```XML
impl Default for TunConfig {
    fn default() -> Self {
        TunConfig {
            addresses: vec![IpAddr::V4(Ipv4Addr::new(10, 0, 0, 1))],
            mtu: 1380,
            ipv4_gateway: Ipv4Addr::new(10, 64, 0, 1),
            ipv6_gateway: None,
            routes: vec![
                IpNetwork::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), 0)
                    .expect("Invalid IP network prefix for IPv4 address"),
                IpNetwork::new(IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 0)), 0)
                    .expect("Invalid IP network prefix for IPv6 address"),
            ],
            allow_lan: false,
            dns_servers: None,
            excluded_packages: vec![],
        }
    }
}
```
___
*[`talpid-tunnel/src/tun_provider/unix.rs` line 45 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45nvj_5HxHRryrvpoN:-O45nvj_5HxHRryrvpoO:bcfjqyw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-tunnel/src/tun_provider/unix.rs#L45)):*
> ```XML
>     }
> 
>     pub fn get_tun(&mut self) -> Result<UnixTun, Error> {
> ```

To me, it's not that obvious that a `get_` function would have the side effect of creating a new tunnel device. Please add some docs on this, and preferably change the name to something which implies a side effect. E.g. `create_tun`, `open_tun` etc.



_Code quote:_
```XML
    pub fn get_tun(&mut self) -> Result<UnixTun, Error> {
```
___
*[`talpid-types/src/net/mod.rs` line 52 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45r7oKAJAP9opD9eKu:-O45r7oLAe0_LXgg7mc_:biz8c7k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-types/src/net/mod.rs#L52)):*
> ```XML
>         IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xff05, 0, 0, 0, 0, 0, 0, 0), 16).unwrap()),
>     ]
> });
> ```

Should these constants be part of the `talpid-types` crate? At least some of them seem like they are plain business logic of the app. Don't really care that much, just posing the question :blush:



_Code quote:_
```XML
/// When "allow local network" is enabled the app will allow traffic to and from these networks.
pub static ALLOWED_LAN_NETS: Lazy<[IpNetwork; 6]> = Lazy::new(|| {
    [
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(10, 0, 0, 0), 8).unwrap()),
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(172, 16, 0, 0), 12).unwrap()),
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(192, 168, 0, 0), 16).unwrap()),
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(169, 254, 0, 0), 16).unwrap()),
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xfe80, 0, 0, 0, 0, 0, 0, 0), 10).unwrap()),
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xfc00, 0, 0, 0, 0, 0, 0, 0), 7).unwrap()),
    ]
});

/// When "allow local network" is enabled the app will allow traffic to these networks.
pub static ALLOWED_LAN_MULTICAST_NETS: Lazy<[IpNetwork; 8]> = Lazy::new(|| {
    [
        // Local network broadcast. Not routable
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(255, 255, 255, 255), 32).unwrap()),
        // Local subnetwork multicast. Not routable
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(224, 0, 0, 0), 24).unwrap()),
        // Admin-local IPv4 multicast.
        IpNetwork::V4(Ipv4Network::new(Ipv4Addr::new(239, 0, 0, 0), 8).unwrap()),
        // Interface-local IPv6 multicast.
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xff01, 0, 0, 0, 0, 0, 0, 0), 16).unwrap()),
        // Link-local IPv6 multicast. IPv6 equivalent of 224.0.0.0/24
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xff02, 0, 0, 0, 0, 0, 0, 0), 16).unwrap()),
        // Realm-local IPv6 multicast.
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xff03, 0, 0, 0, 0, 0, 0, 0), 16).unwrap()),
        // Admin-local IPv6 multicast.
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xff04, 0, 0, 0, 0, 0, 0, 0), 16).unwrap()),
        // Site-local IPv6 multicast.
        IpNetwork::V6(Ipv6Network::new(Ipv6Addr::new(0xff05, 0, 0, 0, 0, 0, 0, 0), 16).unwrap()),
    ]
});
```
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 141 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45sAR05niHzIcKBPC-:-O45sAR05niHzIcKBPC0:b4vvulg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-wireguard/src/wireguard_go/mod.rs#L141)):*
> ```XML
>             mtu: config.mtu,
>             ..tun_config.clone()
>         };
> ```

Nit: I think this would read more intuitively if there were setter-methods on `TunConfig`. Allows us to potentially hide implementation details of `TunConfig` :shrug: 

```rust
impl TunConfig {
    /// Return a copy of all gateway addresses
    pub fn gateway_ips(&self) -> Vec<IpAddr> {
        let mut servers = vec![self.ipv4_gateway.into()];
        if let Some(gateway) = self.ipv6_gateway {
            servers.push(gateway.into());
        }
        servers
    }


    pub fn set_addresses(&mut self, addresses: impl Iterator<Item = IpAddr>) {
        self.addresses = addresses.into_iter().collect()
    }

    // .. 

    pub fn set_mtu(&mut self, mtu: u16) {
        self.mtu = mtu;
    }
}
```

```rust
    fn get_tunnel(
        tun_provider: Arc<Mutex<TunProvider>>,
        config: &Config,
        routes: impl Iterator<Item = IpNetwork>,
    ) -> Result<(Tun, RawFd)> {
        let mut last_error = None;
        let mut tun_provider = tun_provider.lock().unwrap();

        let tun_config = tun_provider.config_mut();
        tun_config.set_addresses(config.tunnel.addresses.iter().cloned());
        // ..
        tun_config.set_mtu(config.mtu);
```



_Code quote:_
```XML
        let tun_config = tun_provider.config_mut();

        *tun_config = TunConfig {
            addresses: config.tunnel.addresses.clone(),
            ipv4_gateway: config.ipv4_gateway,
            ipv6_gateway: config.ipv6_gateway,
            routes: routes.collect(),
            mtu: config.mtu,
            ..tun_config.clone()
        };
```

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 11 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596)* status: 23 of 24 files reviewed, 3 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`talpid-core/src/tunnel_state_machine/connected_state.rs` line 130 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45Z2RVA1GqM27TNbhX:-O49f6jY-axX4tkuhlOt:b-v5ius6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11adc05d190254314ca70fc3d8af5892aadc3ad7/talpid-core/src/tunnel_state_machine/connected_state.rs#L130)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. (The parts that were still relevant now.)
</blockquote></details>

Very clean! :star_struck: Good job :partying_face: 
___
*[`talpid-tunnel/src/lib.rs` line 72 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O49fYkO9wLH59lBUScF:-O49fYkO9wLH59lBUScG:bmoh2pu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dbfd3c6efceac9fa772db04a011113fc553bd64/talpid-tunnel/src/lib.rs#L72)):*
> ```XML
>         }
>         servers
>     }
> ```

Nit: `servers` is a bit of a misnomer, no? Anyway, it's so self-contained, so it does not matter *at all*



_Code quote:_
```XML
    pub fn gateways(&self) -> Vec<IpAddr> {
        let mut servers = vec![self.ipv4_gateway.into()];
        if let Some(gateway) = self.ipv6_gateway {
            servers.push(gateway.into());
        }
        servers
    }
```
___
*[`talpid-tunnel/src/tun_provider/mod.rs` line 89 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45m5WRB0Kh2a1l526Q:-O49hMzy7ixyJKondWCE:b-1443lk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-tunnel/src/tun_provider/mod.rs#L89)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. I'm not overly happy with the state of this, but I've tried to clarify its purpose.
</blockquote></details>

I think you improved it :blush:
___
*[`talpid-tunnel/src/tun_provider/unix.rs` line 45 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O45nvj_5HxHRryrvpoN:-O49hwN62rfSyQ-JjmuJ:b-j1we20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e3c99f94e27c906593b824ac13c81c1d03e0adf/talpid-tunnel/src/tun_provider/unix.rs#L45)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Agree. Renamed.
</blockquote></details>

:raised_hands: 
___
*[`talpid-tunnel/src/tun_provider/unix.rs` line 33 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-O49ho0PBgjuo6u7-5lU:-O49ho0PBgjuo6u7-5lV:boevzd5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dbfd3c6efceac9fa772db04a011113fc553bd64/talpid-tunnel/src/tun_provider/unix.rs#L33)):*
> ```XML
> 
> impl UnixTunProvider {
>     pub fn new(config: TunConfig) -> Self {
> ```

Nit: This could easily be made `const` :blush:



_Code quote:_
```XML
    pub fn new(config: TunConfig) -> Self {
```

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6596#-:-O4ATY5H9A2vH4KTZ7wf:bnfp4nl)* status: 23 of 24 files reviewed, 3 unresolved discussions (waiting on @dlon and @Pururun)

**Pull request merged**
