### PR TITLE
Change path of RPC connection info file on Windows

### PR DESCRIPTION
**Pull request by jvff**
This PR changes the location of the RPC connection info file on Windows to the common `C:\ProgramData\Mullvad VPN` directory. This should fix some problems relating to the GUI not being able to access the RPC connection info file.

Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user. **Affects only Windows version, which hasn't been publicly released yet.**

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162)

### CODE REVIEW

**Comment by jvff** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[mullvad-ipc-client/src/lib.rs, line 230 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC00Z64EakBuqP9VOV3:-LC00Z64EakBuqP9VOV4:bp4lgl7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b91919877ef8408a4b40b66554ad70439d18ce0/mullvad-ipc-client/src/lib.rs#L230)):*
> ```Rust
>     use super::*;
> 
>     static PRODUCT_NAME: &str = "Mullvad VPN";
> ```

This shouldn't be here. But the problem is, where to put it? My intuition says it should be on a separate crate, possibly `mullvad-types` or something like a `mullvad-common` crate.

Any suggestions?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162)*

**Comment by faern** [comment]
Let's finish discussing paths over at https://reviewable.io/reviews/mullvad/mullvadvpn-app/161#-LC-fl0jBLEQmE7UqFRr before we merge this. So we have a clear goal as to what paths to use.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[mullvad-ipc-client/src/lib.rs, line 230 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC00Z64EakBuqP9VOV3:-LC30K0d187lPLnbspeN:blv54bj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b91919877ef8408a4b40b66554ad70439d18ce0/mullvad-ipc-client/src/lib.rs#L230)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This shouldn't be here. But the problem is, where to put it? My intuition says it should be on a separate crate, possibly `mullvad-types` or something like a `mullvad-common` crate.

Any suggestions?
</blockquote></details>

Take `product_name: &str` as argument to `rpc_file_path`?

Or maybe better to define some very tiny and generic `mullvad-metadata` crate where we can define such top level metadata? We can also move the `APP_INFO` difinition there and try to keep all strings and numbers etc related to the product name, version etc in there?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-:-LC3-kNp1OoGKRsTmHt-:bgdm32e)*

**Comment by jvff** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/main.js, line 92 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC5UMru1OnSI7ij4r8g:-LC5UMs-5Gm7WillvfZd:bb0gag3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1e491335116681f462672af330071b56d690c46/app/main.js#L92)):*
> ```JavaScript
>   },
> 
>   _getSharedDataDirectory: () => {
> ```

I tried to create a single place where the "Mullvad VPN" shared data directory path is built.

---

*[app/main.js, line 194 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC5UmxQ4CgCL8B9wiyX:-LC5UmxQ4CgCL8B9wiyY:b-jcr11t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1e491335116681f462672af330071b56d690c46/app/main.js#L194)):*
> ```JavaScript
>   _startBackend: () => {
>     const rpcAddressFile = appDelegate._getRpcAddressFilePath();
>     const backendIsRunning = fs.existsSync(rpcAddressFile);
> ```

The original version of this line was clearer, but I think this is clear enough and has the advantage of reducing the calls to `_getRpcAddressFilePath`.

---

*[app/main.js, line 259 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC5UrR935wWO7O2OYV3:-LC5UrR935wWO7O2OYV4:b-t2tlz1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1e491335116681f462672af330071b56d690c46/app/main.js#L259)):*
> ```JavaScript
>     }
> 
>     const rpcAddressFile = appDelegate._getRpcAddressFilePath();
> ```

Load the RPC connection information file path in memory once, and pass it to wherever it is needed.

---

*[mullvad-ipc-client/src/lib.rs, line 230 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC00Z64EakBuqP9VOV3:-LC5Tx29B10deSM2lSQW:bnm0lza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1b91919877ef8408a4b40b66554ad70439d18ce0/mullvad-ipc-client/src/lib.rs#L230)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Take `product_name: &str` as argument to `rpc_file_path`?

Or maybe better to define some very tiny and generic `mullvad-metadata` crate where we can define such top level metadata? We can also move the `APP_INFO` difinition there and try to keep all strings and numbers etc related to the product name, version etc in there?
</blockquote></details>

I'm not sure I like having a `product_name` parameter. My fear is that we just duplicate `product_name` on other crates.

I created a new `mullvad-metadata` crate as suggested. It's quite empty for now, but I opened some other discussions on the respective files to maybe see if more stuff should be put there.

---

*[mullvad-metadata/src/lib.rs, line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC5Vk8b5GZuD1CLfn_c:-LC5Vk8e4480tHb_yDxB:brgqmyy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1e491335116681f462672af330071b56d690c46/mullvad-metadata/src/lib.rs#L4)):*
> ```Rust
> 
> use app_dirs::AppInfo;
> ```

Not sure what else can be put in this crate. Suggestions accepted.

One idea would be program paths, but I'm not sure if that's a good idea.

---

*[mullvad-metadata/src/lib.rs, line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC5VQ26BkVxF4fPcVug:-LC5VQ2881lDkiF5PII0:b-t2pizb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1e491335116681f462672af330071b56d690c46/mullvad-metadata/src/lib.rs#L8)):*
> ```Rust
> 
> pub const APP_INFO: AppInfo = AppInfo {
>     name: PRODUCT_NAME,
> ```

I was unsure if this should've been kept as `mullvad-daemon`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162)*

**Comment by faern** [comment]
Reviewed 8 of 9 files at r2.
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[mullvad-metadata/src/lib.rs, line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162#-LC5Vk8b5GZuD1CLfn_c:-LCPo8A7ERbBWwG1pG8q:b-mkybpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1e491335116681f462672af330071b56d690c46/mullvad-metadata/src/lib.rs#L4)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Not sure what else can be put in this crate. Suggestions accepted.

One idea would be program paths, but I'm not sure if that's a good idea.
</blockquote></details>

I don't think we should add stuff just for the sake of adding them. This looks like a good start. If more stuff is added then this PR will grow to contain more refactoring that is not relevant to the title of this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162)*

**Comment by faern** [comment]
Reviewed 1 of 2 files at r1, 1 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162)*

**Comment by pinkisemils** [comment]
Reviewed 1 of 2 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/162)*

**Pull request merged**
