### PR TITLE
Add WireGuardNT driver support

### PR DESCRIPTION
**Pull request by dlon**
This adds support for the [in-kernel WireGuard driver](https://git.zx2c4.com/wireguard-nt/about/) on Windows. It is currently opt in and can be enabled by running `mullvad tunnel wireguard use-wireguard-nt set on`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 0 of 17 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/tunnel/wireguard/logging.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MhwQqxw7SnRVQNolDdB:-MhwQqxw7SnRVQNolDdC:b-6u8bze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/logging.rs#L1)):*
> ```XML
> use parking_lot::Mutex;
> ```

There's no way to provide a context as the logger is global. If this is necessary for the go implementation, though, then this module has to be reworked.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 0 of 17 files reviewed, 2 unresolved discussions

___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MhwRqHW-AE7lc_6Gyxa:-MhwRqHW-AE7lc_6Gyxb:bak8j7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/mod.rs#L112)):*
> ```XML
> lazy_static! {
>     /// Overrides the preference for the kernel module for WireGuard.
>     static ref FORCE_USERSPACE_WIREGUARD: bool = env::var("TALPID_FORCE_USERSPACE_WIREGUARD")
> ```

This should probably be replaced with a CLI option to make it easier to try this out.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 10 of 25 files reviewed, 18 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[dist-assets/windows/installer.nsh, line 237 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5_YEt39GJMTZJCCo-:-MiBMaWJ9uHLMAfIcArE:b8igngm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/dist-assets/windows/installer.nsh#L237)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Argument name. NT is the name of the kernel, this is just too non-specific.

Can you also reword it? At a glance, it's claiming to delete a "pool driver", which is not true.
</blockquote></details>

Will do. As you noted, `delete-pool-driver` comes from the API. I suppose `delete-pool-and-driver` would make more sense, though is still slightly wrong, since the driver is only deleted if it's the only pool.
___
*[dist-assets/windows/installer.nsh, line 1284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5dDAG8dJ4pysBffkp:-Mi6veG30j37GJUXFGeZ:b-4hcqzg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/dist-assets/windows/installer.nsh#L1284)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is the only reference. Is there no configuration needed during setup?
</blockquote></details>

There is not. As with Wintun, the driver is magically installed or updated when a device is created.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi61que6dL7-NxLanMY:-MiBTUXYAvkplE-woHuS:bl44w3y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L171)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Bit of a corner case: You already checked the CIDR value, but this conversion function doesn't have enough information to mask the input?
</blockquote></details>

Good point. The host bits aren't relevant. I don't think an "allowed IP" is even valid if they are non-zero, so they should probably be rejected or zeroed when the instance is constructed.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 455 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi64RCjDKeHrkLshL8y:-Mi6x7NQA6N1aaAhfuQE:bl16osx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L455)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

How would we signal to the user that a reboot is required? Or will Windows do that for us?
</blockquote></details>

In general, Windows will show a notification. But, in practice, rebooting doesn't seem to be required here.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 758 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7TwpwDVlpmxN4Q5dq:-MiB0JlID8penP6lZoMF:bw6rhpm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L758)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I suppose the pubkey is restored from the privkey at some later time?
</blockquote></details>

It must be since it actually works, and the existence of the `WIREGUARD_INTERFACE_HAS_PUBLIC_KEY` flag suggests that it is optional. `get_config` also returns the pubkey afterwards, IIRC. It wouldn't hurt to derive the pubkey here either.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 769 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7U1MlDMoNB9WAa07M:-MiB0l0h81_M8BpKQ4Gc:b61vdaz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L769)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Why aren't you including the PSK from the current peer?
</blockquote></details>

There's no way to set a PSK at the moment, so there is no PSK to include.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 807 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7VZWm47QdQOM6V5WW:-MiB18gkEN84hahZfXsM:b-ujfwi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L807)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Don't we need length validation on contained structs, as well as sanity checks on embedded data?
</blockquote></details>

Yeah, probably. `split_at` should panic if anything is out of range, so it could be worse, but we could recover from any issues.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 832 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7XDl67WPfu3RsGLV_:-MiBJ8LD-iJjMHvrZ40X:b-83gvxr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L832)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Lots of these functions are generic Rust/Windows networking utility functions. Can they be placed at a higher scope?
</blockquote></details>

They could probably be moved to `talpid_core::tunnel::windows`.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 973 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7WMLP1e1T8CnoXHTz:-MiBGU9x-8xxe2NmcbDB:bpj2az2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L973)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Remind me, the reason you have to cast twice is because some Rust validation becomes confused and lets it slide?
</blockquote></details>

In this case, `object` is first cast from `&T` to `*const T`, and then from `*const T` to `*const u8`. In general, you're not allowed to cast `&T` to `*const U`, but casting or coercing it to `*const T` is allowed. A pointer to some type `T` can be cast to a pointer to some other type `U`, though.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 10 of 25 files reviewed, 18 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 807 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7VZWm47QdQOM6V5WW:-MiB_A8g0-Mo5L2m1pS3:bla3lar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L807)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yeah, probably. `split_at` should panic if anything is out of range, so it could be worse, but we could recover from any issues.
</blockquote></details>

*we could handle any error instead of panicking.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 10 of 25 files reviewed, 16 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi13Ybu56UItSCWxVtk:-MiL5ZYF2tji69FSJH9B:bmscbh1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L77)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. It is used by FFI. I don't think that this is really necessary, though. `repr(C)` already implies that the first value is implicitly 0, etc.
</blockquote></details>

Yes, but it's far more obvious to the reader to see the values verbatim.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 10 of 25 files reviewed, 16 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[dist-assets/windows/installer.nsh, line 237 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5_YEt39GJMTZJCCo-:-MiQH1bc45PLnvAJ63kB:baycquq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/dist-assets/windows/installer.nsh#L237)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Will do. As you noted, `delete-pool-driver` comes from the API. I suppose `delete-pool-and-driver` would make more sense, though is still slightly wrong, since the driver is only deleted if it's the only pool.
</blockquote></details>

Yes, the name originally exported is a complete brain fart.

Can you use some combination of `wgnt` and `cleanup`?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 10 of 25 files reviewed, 15 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[dist-assets/windows/installer.nsh, line 1284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5dDAG8dJ4pysBffkp:-MiQI3A92rPlOlFMkh3L:btojbfq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/dist-assets/windows/installer.nsh#L1284)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There is not. As with Wintun, the driver is magically installed or updated when a device is created.
</blockquote></details>

Great.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 10 of 25 files reviewed, 13 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 758 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7TwpwDVlpmxN4Q5dq:-MiQRjxdDpDtMHsiS_0Z:bfo08xu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L758)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It must be since it actually works, and the existence of the `WIREGUARD_INTERFACE_HAS_PUBLIC_KEY` flag suggests that it is optional. `get_config` also returns the pubkey afterwards, IIRC. It wouldn't hurt to derive the pubkey here either.
</blockquote></details>

Alright :-)
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 769 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7U1MlDMoNB9WAa07M:-MiQRZ7ADp2Es34SaJTC:br9uvf1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L769)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There's no way to set a PSK at the moment, so there is no PSK to include.
</blockquote></details>

OK, nice. I realize now that mirroring the C-structure exactly is the better alternative.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 973 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7WMLP1e1T8CnoXHTz:-MiQSwL370B7kebw5-2i:b7ycocv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L973)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

In this case, `object` is first cast from `&T` to `*const T`, and then from `*const T` to `*const u8`. In general, you're not allowed to cast `&T` to `*const U`, but casting or coercing it to `*const T` is allowed. A pointer to some type `T` can be cast to a pointer to some other type `U`.
</blockquote></details>

Aha, thanks, good explanation. I'm somewhat familiar with what you explain, but don't recall seeing it expressed as a double `*const whatever`.

Could there be issues with endianness lurking?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 11 of 25 files reviewed, 13 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[talpid-core/src/tunnel/mod.rs, line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MhwuLOQ6EPsopBXKzn3:-MiRO_ooBxFF5_ypAFVP:brade5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/mod.rs#L136)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Ah yes, the ubiquitous `resource_dir`. Sent to every method, everywhere.

Perhaps there's an alternative design that would simplify all code.
</blockquote></details>

I don't believe this is the PR to fix that issue. But we can at least make it platform-dependent.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 8 of 25 files reviewed, 12 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[dist-assets/windows/installer.nsh, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5ZcWiEXMCZlBkJYyj:-MiexQiSEnOlNGZYD39Z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/dist-assets/windows/installer.nsh#L16)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Name is not specific enough.
</blockquote></details>

Done.
___
*[dist-assets/windows/installer.nsh, line 237 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5_YEt39GJMTZJCCo-:-MiexSWd7iMpOY3B8iwu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/dist-assets/windows/installer.nsh#L237)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Yes, the name originally exported is a complete brain fart.

Can you use some combination of `wgnt` and `cleanup`?
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 384 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7Y2dJAZfmODpITBF5:-MiBLUMnEpLu1tsRIP8h:bldhkg3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L384)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Should this be `u32::from(config.mtu) - 20`?
</blockquote></details>

That seems right. On other platforms, we use a single MTU, so maybe it's already small enough?
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 973 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7WMLP1e1T8CnoXHTz:-MiWj3m_-eXManztjY4Z:bmy5mxs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L973)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Aha, thanks, good explanation. I'm somewhat familiar with what you explain, but don't recall seeing it expressed as a double `*const whatever`.

Could there be issues with endianness lurking?
</blockquote></details>

I don't think so. `SOME_C_STRUCT` will be byte for byte identical, and the endianness should be the same.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 5 of 25 files reviewed, 8 unresolved discussions (waiting on @mvd-ows and @pinkisemils)

___
*[talpid-core/src/tunnel/mod.rs, line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MhwuLOQ6EPsopBXKzn3:-MiBVQB97tMvr5QnGdYb:bce2czw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/mod.rs#L136)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I don't believe this is the PR to fix that issue. But we can at least make it platform-dependent.
</blockquote></details>

`tun_provider` is not used on Windows either. Wouldn't conditional compilation make it a lot messier?
___
*[talpid-core/src/tunnel/wireguard/logging.rs, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5gQo5CZkpiV6CGyrQ:-MifCcnUDD-XM66Ok-lA:b-ilyw22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/logging.rs#L23)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

No need to open/create the file if logging is already initialized.
</blockquote></details>

No longer relevant. (Reverted to logging with a context.)
___
*[talpid-core/src/tunnel/wireguard/logging.rs, line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5sVdy2gji81vRxqi5:-MifCkXa4h5IREfo4Sr7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/logging.rs#L116)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`nt` :-(
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/logging.rs, line 117 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi5t6aIEKLuWr_htP4l:-MifCkid7Bx461uADGXp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/logging.rs#L117)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Type name. Where is this type defined?
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi61que6dL7-NxLanMY:-MifCpuEEnBqXsNYJHTY:b-1p8xye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L171)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Good point. The host bits aren't relevant. I don't think an "allowed IP" is even valid if they are non-zero, so they should probably be rejected or zeroed when the instance is constructed.
</blockquote></details>

Done (in constructor, when possible).
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 807 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7VZWm47QdQOM6V5WW:-MifCwDG2ezxl5QiRqpR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L807)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

*we could handle any error instead of panicking.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 832 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7XDl67WPfu3RsGLV_:-MifCxSl0GjcH3rjzSYd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L832)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

They could probably be moved to `talpid_core::tunnel::windows`.
</blockquote></details>

Done.

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 3 of 5 files at r6, 4 of 10 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 14 of 25 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 384 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7Y2dJAZfmODpITBF5:-MivLo_21rxP3FoDQKK5:b4g7mmn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L384)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

That seems right. On other platforms, we use a single MTU, so maybe it's already small enough?
</blockquote></details>

I dunno. Maybe we have the same issue in several locations.
___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 973 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7WMLP1e1T8CnoXHTz:-MiwllLh8XFR-R1ztysC:b-nfkzvu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L973)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't think so. `SOME_C_STRUCT` will be byte for byte identical, and the endianness should be the same.
</blockquote></details>

OK, great.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 14 of 25 files reviewed, 2 unresolved discussions (waiting on @mvd-ows and @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 384 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7Y2dJAZfmODpITBF5:-MjcdNmA8758p4CScq_-:b83dfoy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L384)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I dunno. Maybe we have the same issue in several locations.
</blockquote></details>

I suggest we use the same MTU for consistency with `wireguard-go`.

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 1 of 10 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 11 of 27 files reviewed, 2 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_nt.rs, line 384 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-Mi7Y2dJAZfmODpITBF5:-MjhUemQ4twzQZIdaTR8:bv56fo0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f00b05c649db99cb9f9c0beb3fa1032297704fe6/talpid-core/src/tunnel/wireguard/wireguard_nt.rs#L384)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I suggest we use the same MTU for consistency with `wireguard-go`.
</blockquote></details>

OK, makes sense.
___
*[windows/libshared/src/libshared/network/interfaceutils.cpp, line 102 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MjhUpekDv2XQx3LhwvI:-MjhUpekDv2XQx3LhwvJ:b5uynkm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d5df7c3a0e532ddd72c87ca51cad9b6c94801ad/windows/libshared/src/libshared/network/interfaceutils.cpp#L102)):*
> ```cpp
> 		row.InterfaceLuid = device;
> 		row.Address = address;
> 		row.DadState = IpDadStatePreferred;
> ```

What's this?

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 11 of 27 files reviewed, 1 unresolved discussion (waiting on @mvd-ows and @pinkisemils)

___
*[windows/libshared/src/libshared/network/interfaceutils.cpp, line 102 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MjhUpekDv2XQx3LhwvI:-MjhjMZN4JoxnxAoRx2X:b-f38bnk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d5df7c3a0e532ddd72c87ca51cad9b6c94801ad/windows/libshared/src/libshared/network/interfaceutils.cpp#L102)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

Disable DAD on win10+, got it.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r2, 4 of 10 files at r9, 2 of 6 files at r10, 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 27 of 28 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 115 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MkflUnp46JPDlQw3Mg8:-MkflUnp46JPDlQw3Mg9:b-h241sy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/675b334e81d6ca21b1b987102203c89e0d1eda79/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L115)):*
> ```XML
>         route_manager: &mut routing::RouteManager,
>     ) -> Result<Self> {
>         let route_callback_handle = route_manager
> ```

This statement must be conditionally compiled on Windows.
___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 171 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MkflOXPDIJH3DKbOGJ3:-MkflOXPDIJH3DKbOGJ4:btiw6np) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/675b334e81d6ca21b1b987102203c89e0d1eda79/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L171)):*
> ```XML
>             handle: Some(handle),
>             _logging_context: logging_context,
>             _route_callback_handle: route_callback_handle,
> ```

This should be conditionally applied.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: 27 of 28 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 115 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MkflUnp46JPDlQw3Mg8:-Mkfpot-E9HQsQ5June1:bu2bd7d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/675b334e81d6ca21b1b987102203c89e0d1eda79/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L115)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This statement must be conditionally compiled on Windows.
</blockquote></details>

That is already the case, as the method is conditionally compiled.
___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 171 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920#-MkflOXPDIJH3DKbOGJ3:-MkfpwyLD-rknkY2s7D-:b2nreh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/675b334e81d6ca21b1b987102203c89e0d1eda79/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L171)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This should be conditionally applied. 
</blockquote></details>

Same as above.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 6 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2920)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
