### PR TITLE
Improve tunnel state error handling

### PR DESCRIPTION
**Pull request by raksooo**
This PR replaces the old error state cause with an enum and updates the Electron app to use the new ErrorState structures.

It also removes a few `await` in the playwright tests since those doesn't seem to be needed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)

### CODE REVIEW

**Review by hankolsen — APPROVED** [review]
> Reviewed 16 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 5 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hankolsen — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hankolsen — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> Reviewed 12 of 23 files at r6, 6 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: 8 of 24 files reviewed, all discussions resolved (waiting on @hankolsen)

**Review by hankolsen — COMMENTED** [review]
> Reviewed 11 of 23 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3965)* status: 8 of 24 files reviewed, all discussions resolved

**Pull request merged**
