### PR TITLE
Simplify ExponentialBackoff

### PR DESCRIPTION
**Pull request by dlon**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)

### CODE REVIEW

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-:-MVXLogI83C5aT3FDvqf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/future_retry.rs, line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXQA1c8KzyxOLxOllm:-MVXQA1d-dig5hYHo5z5:basbyt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L49)):*
> ```XML
> 
> impl ExponentialBackoff {
>     /// Creates a `ExponentialBackoff` with the provided number of milliseconds as a base.
> ```

"number of milliseconds as base" is not correct any longer.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/future_retry.rs, line 70 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXRQ0kE5Pf6aeZFqoo:-MVXRQ0kE5Pf6aeZFqop:b-2l78ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L70)):*
> ```XML
>     /// Returns the value of the delay and advances the next back-off delay.
>     fn next_delay(&mut self) -> Duration {
>         let previous = self.current;
> ```

IMO, this naming is not optimal. At least I would find it more logical if it was:
```rust
let next = self.next;
self.next = {compute next};

return next;
```

The field in the struct contains the **next delay that will be returned**. And the value that we here copy out before modifying is what we will return here, so it's if anything the **current** value and not the **previous** one.
___
*[talpid-core/src/future_retry.rs, line 78 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXR-9u6o4gyj6EN-2m:-MVXR-9u6o4gyj6EN-2n:b-rvh36n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L78)):*
> ```XML
>         if let Some(max_delay) = self.max_delay {
>             if previous > max_delay {
>                 return max_delay;
> ```

Since `self.current` is assigned before this check, it means that if you continue calling this method `self.current` will continue to increase forever, until hitting the max. Not that it hurts maybe, but we could just as well do the `max_delay` check *before* computing `self.current` and as such have it stop computing new delays when hitting the max.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/future_retry.rs, line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXSC_BDCRWEh3GY6Qb:-MVXSC_BDCRWEh3GY6Qc:b-6vrdc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L131)):*
> ```XML
>     #[test]
>     fn test_exponential_backoff() {
>         let mut backoff = ExponentialBackoff::new(Duration::from_secs(2), 2);
> ```

Having both the `initial` and `factor` be the same value is not optimal IMO. Because if the code is ever screwed up so they change place, the test *might* still work. Would be easier to detect such bugs if they were different. Say, the `initial` is 3 seconds or something.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/future_retry.rs, line 78 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXR-9u6o4gyj6EN-2m:-MVXT1BqAbGj6NBYQBPx:b-l3aaiz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L78)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since `self.current` is assigned before this check, it means that if you continue calling this method `self.current` will continue to increase forever, until hitting the max. Not that it hurts maybe, but we could just as well do the `max_delay` check *before* computing `self.current` and as such have it stop computing new delays when hitting the max.
</blockquote></details>

I meant `Duration::MAX`, not `self.max_delay` when I wrote "until hitting the max" :)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/future_retry.rs, line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXQA1c8KzyxOLxOllm:-MV_kpBX1HbJ155NeCWu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L49)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"number of milliseconds as base" is not correct any longer.
</blockquote></details>

Done.
___
*[talpid-core/src/future_retry.rs, line 70 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXRQ0kE5Pf6aeZFqoo:-MV_kyoN9Jba3uQcToaC:b-qu6n94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L70)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

IMO, this naming is not optimal. At least I would find it more logical if it was:
```rust
let next = self.next;
self.next = {compute next};

return next;
```

The field in the struct contains the **next delay that will be returned**. And the value that we here copy out before modifying is what we will return here, so it's if anything the **current** value and not the **previous** one.
</blockquote></details>

Good point. Done.
___
*[talpid-core/src/future_retry.rs, line 78 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXR-9u6o4gyj6EN-2m:-MV_lDQa85E0KT9M9uiD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L78)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I meant `Duration::MAX`, not `self.max_delay` when I wrote "until hitting the max" :)
</blockquote></details>

Done.
___
*[talpid-core/src/future_retry.rs, line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-MVXSC_BDCRWEh3GY6Qb:-MV_lcRQC0BUA8EgrNiy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/053a92462f9ba21136fe9ce76327b6c0a2e48d86/talpid-core/src/future_retry.rs#L131)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Having both the `initial` and `factor` be the same value is not optimal IMO. Because if the code is ever screwed up so they change place, the test *might* still work. Would be easier to detect such bugs if they were different. Say, the `initial` is 3 seconds or something.
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562#-:-MVaDNqm0LV4CldyWX7V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
