### PR TITLE
Add changelog instructions

### PR DESCRIPTION
**Pull request by faern**
I have imagined these format rules for the changelog. But they have not been written anywhere. So everyone has used some other format at at least one occasion. So I felt like writing them down, which can have one of two outcomes:
* We merge this and thus have a written style to follow, makes it easier to keep the file consistent.
* We disagree on the rules and say there are no rules. The changelog will become messy, but I can stop pointing it out in PRs.

Also added a forgotten change entry.

Checklist for a PR:

* [x] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/118)

### CODE REVIEW

**Comment by mvd-ows** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 13 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RVkAg1zIwlObJwMwJ:-L9RVkAg1zIwlObJwMwK:b1prse4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L13)):*
> ```Markdown
> add, fix, increase, force etc.. Not added, fixed, increased, forced etc.
> 
> Line wrap the file at 100 chars.                                              That is over here -> |
> ```

I recently added an entry in the changelog, where i wrapped sooner than 100 chars in order to not have a single, lonely, word on the second line. This is an established practice from type setting texts. If everyone agrees we should use the same rule here, then maybe it should also be spelled out.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by mvd-ows** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 3 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RWLxo7jdPhflOEfu1:-L9RWLxo7jdPhflOEfu2:b1uyfey) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L3)):*
> ```Markdown
> # Changelog
> All changes to the software that can be noticed from the users' perspective should have an entry in
> this file. Except very minor things that will not affect functionality, such as log message changes
> ```

Just a thought, if someone is writing software to parse our log files they would probably be happy to see a log message change highlighted in the changelog. Having said that, I don't actually think we should include this information in the changelog :-)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by mvd-ows** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RWLxo7jdPhflOEfu1:-L9dRCkE3MTgtRxw9R_5:b70vu6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L3)):*
I really don't think anyone should write software that parses our logs. The logs are human facing, not machine facing :)
For people interesting in very detailed changes the git history is always available to them. I think the changelog should be easy to look at as a user of the software and get a feel for what behavior and functionality changes they might expect when upgrading.

The original string here, which is from the http://keepachangelog.com/en/1.0.0/ template says
> All notable changes to this project will be documented in this file.

What I did was just expand this statement into a bit more details. I agree it might not be 100% correct to have it here. But I favored simplicity over exact correctness this time and I don't see how it could hurt :)

---

*[CHANGELOG.md, line 13 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RVkAg1zIwlObJwMwJ:-L9dSLwKBKveYQWVn6lp:b4cts3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L13)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I recently added an entry in the changelog, where i wrapped sooner than 100 chars in order to not have a single, lonely, word on the second line. This is an established practice from type setting texts. If everyone agrees we should use the same rule here, then maybe it should also be spelled out.
</blockquote></details>

I usually don't follow that rule. Never really thought about it actually. So how many words are OK on the next line? Should one just move down one more word so they become two, or what is the rule?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by mvd-ows** [comment]
*[CHANGELOG.md, line 13 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RVkAg1zIwlObJwMwJ:-L9i6HOF39H0dJDOr6Xf:bgxyz4v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L13)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I usually don't follow that rule. Never really thought about it actually. So how many words are OK on the next line? Should one just move down one more word so they become two, or what is the rule?
</blockquote></details>

The rule says to include at least three words on the final line in each paragraph, usually by rewording the text.

"Föräldralösa ord", "horunge" (som också/oftare refererar till en ensam rad på en ny sida).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by mvd-ows** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 13 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RVkAg1zIwlObJwMwJ:-L9igAWu5jKujksI9lii:bbhwqpa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L13)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes, I know about the concept in typography (didn't know the amount of words). Never thought about it in the context of a simple textfile though. Especially since markdown will do the real layouting and this is essentially just "source code" and all typography will be managed by markdown... But that is also an argument against line wrapping at all. However not line wrapping will make the file unreadable in a non-line-wrapping editor.

Do people think we should take care of not having orphaned words?
</blockquote></details>

We need to reach some conclusion without spending too much time here. If people think orphans seriously hinder the readability we can add that, no problem. Otherwise I just wanted to keep the style as simple as possible but with a consistent language.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by mvd-ows** [comment]
*[CHANGELOG.md, line 13 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RVkAg1zIwlObJwMwJ:-L9il5xZEs3_gacsxMOO:b-65eiaa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L13)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We need to reach some conclusion without spending too much time here. If people think orphans seriously hinder the readability we can add that, no problem. Otherwise I just wanted to keep the style as simple as possible but with a consistent language.
</blockquote></details>

It doesn't matter. Let people do whatever they deem most suitable in the given situation.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 49 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9ixGW751PO1F92CUBK:-L9ixGW751PO1F92CUBL:b-tjze1a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3c38bb7e408672991a76430ef9cf0cfa75be2ade/CHANGELOG.md#L49)):*
> ```Markdown
>   account numbers.
> - Fix OpenVPN plugin search directory to be the installation directory.
> - Write and look for RPC address file in global temp directory on Windows.
> ```

Windows version is not released so I thought we don’t need to mention changes that do not affect our users.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9RWLxo7jdPhflOEfu1:-L9izTVA5eyaJK7zLALu:b-gnb8rx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6e8036968bd66d64041402f15710131ebae6aa8/CHANGELOG.md#L3)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I really don't think anyone should write software that parses our logs. The logs are human facing, not machine facing :)
For people interesting in very detailed changes the git history is always available to them. I think the changelog should be easy to look at as a user of the software and get a feel for what behavior and functionality changes they might expect when upgrading.

The original string here, which is from the http://keepachangelog.com/en/1.0.0/ template says
> All notable changes to this project will be documented in this file.

What I did was just expand this statement into a bit more details. I agree it might not be 100% correct to have it here. But I favored simplicity over exact correctness this time and I don't see how it could hurt :)
</blockquote></details>

I am sure changelog can be parsed and the heading can be ignored :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118)*

**Comment by pronebird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-:-L9izlHo7YGhCZzhfYAf:bnfp4nl)*

**Comment by faern** [comment]
We could also say that one should not use abbreviations such as it's and can't, because they are less formal than it is and cannot. But then again I think it gets too complicated. You are free to suggest such changes if you feel like it but I'm going to merge this as is, given that you have both accepted and I think this guide is enforcing enough things to make it readable.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 49 at r2](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-L9ixGW751PO1F92CUBK:-L9jBPlk-pUjzWMZjip3:b-nqh4dl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3c38bb7e408672991a76430ef9cf0cfa75be2ade/CHANGELOG.md#L49)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Windows version is not released so I thought we don’t need to mention changes that do not affect our users.
</blockquote></details>

True. Removing then.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/118#-:-L9jAPrN19EikiOw05uR:b78884x)*

**Pull request merged**
