### PR TITLE
Create a Docker image for building the Android app

### PR DESCRIPTION
**Pull request by jvff**
This PR creates an `android/docker` directory that contains the necessary files to create a Docker image that can be used to build the Android app without needing to configure the environment manually.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **No app changes, so no changelog necessary.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)

### CODE REVIEW

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 0 of 6 files reviewed, 3 unresolved discussions

___
*[android/docker/android-build.sh, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oQUr32OBV-lAi0_d:-Ma4oQUr32OBV-lAi0_e:bfgvizt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L7)):*
> ```Shell
> cp build-apk.sh /tmp/build-apk.sh
> 
> if [ -d wireguard/wireguard-go ]; then
> ```

I had originally written these checks so that the image could build different commits around the time the WireGuard-Go build was being migrated from the binaries repository. Not sure if this is still relevant to keep.
___
*[android/docker/android-build.sh, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oe683bR_GnLi8DR2:-Ma4oe683bR_GnLi8DR3:bvcufph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L37)):*
> ```Shell
> 
>     sed -i -e "s|^ARCHITECTURES=.*$|ARCHITECTURES=\"$ARCHITECTURES\"|" ./build-apk.sh
>     sed -i -e "s|^for arch in .*; do*$|for arch in $GO_ARCHITECTURES; do|" "$WGGO_DIR/build-android.sh"
> ```

This "hijacks" the build scripts to allow changing the target architectures. Maybe it would make more sense to open a separate PR to allow this to be done in the original scripts and to allow simplifying this script?
___
*[android/docker/android-build.sh, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oxsqDVSop99a0tCC:-Ma4oxsqDVSop99a0tCD:b-cintzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L41)):*
> ```Shell
> 
> sed -i -e "s|^./wireguard/build-wireguard-go.sh --android$|./$WGGO_DIR/build-android.sh|" ./build-apk.sh
> sed -i -e 's|^EXTRA_WGGO_ARGS=""$|EXTRA_WGGO_ARGS="--no-docker"|' ./build-apk.sh
> ```

Same for the `--no-docker` flag for the WireGuard-Go build. Maybe it should be exported from the `build-apk.sh` script?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @jvff)

___
*[android/docker/android-build.sh, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oe683bR_GnLi8DR2:-MaDODjY-6T0QxU0a7IJ:b-rv16ic) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L37)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This "hijacks" the build scripts to allow changing the target architectures. Maybe it would make more sense to open a separate PR to allow this to be done in the original scripts and to allow simplifying this script?
</blockquote></details>

I think the original scripts should be  changed rather than hijacking everything here.
___
*[android/docker/android-build.sh, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oxsqDVSop99a0tCC:-MaDK0Sc7zJSsYXcsSS6:b-ltmjd0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L41)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Same for the `--no-docker` flag for the WireGuard-Go build. Maybe it should be exported from the `build-apk.sh` script?
</blockquote></details>

`build-apk.sh` could only set `EXTRA_WGGO_ARGS` if it's not set already.
___
*[android/docker/Dockerfile, line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-MaDoqkPEB6GIAzIjAXu:-MaDoqkQ5gnuwD_TDTnY:b-zhlm9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/Dockerfile#L3)):*
> ```Dockerfile
> FROM debian:10
> 
> RUN apt-get update && apt-get install -y \
> ```

I'll test this out locally and see how well it works.
___
*[android/docker/README.md, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-MaDPAPy0XpIg_ReD4Fy:-MaDPAPy0XpIg_ReD4Fz:ba01tt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/README.md#L49)):*
> ```Markdown
> ```
> 
> To speed up the build, some extra volumes can be used to cache Cargo and Gradle data. The following
> ```

I've been creating `/.android-cargo-home` and `/.android-gradle-cache` in the root of the repository and I just set the `CARGO_HOME_DIR` and the other enviornment variables.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/docker/android-build.sh, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oQUr32OBV-lAi0_d:-MaUrlwn2K5RskDXkEwo:b-wnfmk9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I had originally written these checks so that the image could build different commits around the time the WireGuard-Go build was being migrated from the binaries repository. Not sure if this is still relevant to keep.
</blockquote></details>

Done. Removed.
___
*[android/docker/android-build.sh, line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oe683bR_GnLi8DR2:-MaUrl704UeFMvTq1VlW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L37)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think the original scripts should be  changed rather than hijacking everything here.
</blockquote></details>

Done.
___
*[android/docker/android-build.sh, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-Ma4oxsqDVSop99a0tCC:-MaUrnPX6ArQfmYTQdoA:bxpb9wy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/android-build.sh#L41)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`build-apk.sh` could only set `EXTRA_WGGO_ARGS` if it's not set already.
</blockquote></details>

Done, but I added the `--no-docker` to avoid any issue with passing repeated flags to the WireGuard build script.
___
*[android/docker/README.md, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-MaDPAPy0XpIg_ReD4Fy:-MaUs6h08SpV8lbSetH-:b-ilkjsv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/README.md#L49)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I've been creating `/.android-cargo-home` and `/.android-gradle-cache` in the root of the repository and I just set the `CARGO_HOME_DIR` and the other enviornment variables. 
</blockquote></details>

That's an option I hadn't thought of, I'll add it to the file as well :+1:.

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/docker/README.md, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-MaDPAPy0XpIg_ReD4Fy:-MaUsnIUA4fFsj53uxKZ:b-v31alh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/README.md#L49)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That's an option I hadn't thought of, I'll add it to the file as well :+1:.
</blockquote></details>

Do you have the env. vars. that have to be set?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @jvff and @pinkisemils)

___
*[android/docker/README.md, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-MaDPAPy0XpIg_ReD4Fy:-MaXxKlTAt-qoZPJXVny:b-fi17s9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/README.md#L49)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Do you have the env. vars. that have to be set?
</blockquote></details>

`CARGO_TARGET_DIR=/project/.android-cargo-target`
`CARGO_HOME=/project/.android-cargo-home`
`GRADLE_USER_HOME=/project/.android-gradle-home`

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[android/docker/README.md, line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754#-MaDPAPy0XpIg_ReD4Fy:-MaYd93X-CWg0sB7qpu4:b-m8fmpo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc2e20e671fa8879c87c2982eb8d392523ca39fd/android/docker/README.md#L49)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`CARGO_TARGET_DIR=/project/.android-cargo-target`
`CARGO_HOME=/project/.android-cargo-home`
`GRADLE_USER_HOME=/project/.android-gradle-home`

</blockquote></details>

Done. (I didn't put `CARGO_TARGET_DIR` because it can stay as `./target`, it won't speed up the build if it's different or not).

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2754)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
