### PR TITLE
Upgrade to OpenVPN 2.5

### PR DESCRIPTION
**Pull request by dlon**
This upgrades OpenVPN to version 2.5 and Wintun to 0.9. It also replaces the TAP adapter on Windows with a Wintun adapter.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)

### CODE REVIEW

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 10 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 10 of 28 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[CHANGELOG.md, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVspvlAPxZ4lD6AuF2:-MMVspvlAPxZ4lD6AuF3:b-1q6do2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/CHANGELOG.md#L43)):*
> ```Markdown
> - Randomly select addresses to use for communicating with the API.
> - Bundle a list of API addresses to use instead of assuming that the primary address can be reached.
> - Upgrade OpenVPN from 2.4 to 2.5.
> ```

I saw the min TLS version is now 1.3, should that be mentioned here?
___
*[dist-assets/windows/installer.nsh, line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVtXy25rXWoEauTxjy:-MMVtXy25rXWoEauTxjz:b-8jyjfn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b72f29cd885c2e9c02b27f72cd93683aba253e8d/dist-assets/windows/installer.nsh#L63)):*
> ```NSIS
> 		File "${BUILD_RESOURCES_DIR}\binaries\x86_64-pc-windows-msvc\tap-driver\win8\*"
> 	${Else}
> 		File "${BUILD_RESOURCES_DIR}\binaries\x86_64-pc-windows-msvc\tap-driver\win7\*"
> ```

This removes win7 TAP support, which is a great thing to do! But support will have a fit.
___
*[windows/driverlogic/src/driverlogic.cpp, line 803 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVx32b1alM8hq92EGJ:-MMVx32d8OUEYBPug9kT:bde4uik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L803)):*
> ```cpp
> {
> 	auto wintunPath = GetCurrentModulePath().replace_filename(L"wintun.dll");
> 	auto wintunHandle = LoadLibraryExW(wintunPath.c_str(), nullptr, LOAD_WITH_ALTERED_SEARCH_PATH);
> ```

This flag has a somewhat confusing description. What's the purpose in using it?
___
*[windows/driverlogic/src/driverlogic.cpp, line 807 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVxkHGAKqn3UqZhlmX:-MMVxkHGAKqn3UqZhlmY:bce5g1d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L807)):*
> ```cpp
> 	if (nullptr == wintunHandle)
> 	{
> 		std::wcerr << L"Failed to load wintun.dll: " << GetLastError() << std::endl;
> ```

Are we using stderr now? I thought any output should go to stdout?
___
*[windows/driverlogic/src/driverlogic.cpp, line 816 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVxeCb0tkXb0IlADjF:-MMVxeCdE5otqLy4HARi:b-a7ao3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L816)):*
> ```cpp
> 	const auto WintunDeletePoolDriver = reinterpret_cast<WINTUN_DELETE_POOL_DRIVER_FUNC>(GetProcAddress(wintunHandle, "WintunDeletePoolDriver"));
> 
> 	if (!WintunCreateAdapter || !WintunOpenAdapter || !WintunDeletePoolDriver)
> ```

Check all four function pointers? You could make a class that hides Load/FreeLibrary and provides the function pointers as public members.
___
*[windows/driverlogic/src/driverlogic.cpp, line 935 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVytiZ8vdrIsNL0k8I:-MMVytiZ8vdrIsNL0k8J:bwruype) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L935)):*
> ```cpp
> 	try
> 	{
> 		if (0 == _wcsicmp(argv[1], L"new-device"))
> ```

Why are the next few commands necessary to support? One of the main points of using the wintun DLL is to not have to care about the driver.
___
*[windows/driverlogic/src/wintun.h, line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVzaVKCzQUFWt2rFE6:-MMVzaVKCzQUFWt2rFE7:b-hyfdfy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/wintun.h#L6)):*
> ```objc
>  */
> 
> #pragma once
> ```

I was expecting to see this file in the binaries repo. Separating the DLL and header could lead to issues when either is updated.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 9 of 28 files reviewed, 6 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVtXy25rXWoEauTxjy:-MMWMk7dEjicIzrQkGSD:b-kh4wwr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b72f29cd885c2e9c02b27f72cd93683aba253e8d/dist-assets/windows/installer.nsh#L63)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This removes win7 TAP support, which is a great thing to do! But support will have a fit.
</blockquote></details>

Since there is a persistent adapter, the daemon could be made to detect whether the virtual adapter is a TAP or Wintun adapter and pass the correct arguments to OpenVPN accordingly. For the (hopefully) small number of users who'll have issues with Wintun, they could manually replace the interface with one using either of the TAP drivers.
___
*[windows/driverlogic/src/driverlogic.cpp, line 803 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVx32b1alM8hq92EGJ:-MMWPs4w1BKoNZxwqV8l:b3qyda) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L803)):*
It's being used so that some other DLL called `wintun.dll` is not loaded instead of the one contained in the installer.

I'm not sure how the standard search path option treats absolute paths, but:
> The standard search begins in the calling application's directory, and the alternate search begins in the directory of the executable module that LoadLibraryEx is loading.

https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order
___
*[windows/driverlogic/src/driverlogic.cpp, line 816 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVxeCb0tkXb0IlADjF:-MMWSOi23bkAyb27CAFk:b-fz7dtq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L816)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Check all four function pointers? You could make a class that hides Load/FreeLibrary and provides the function pointers as public members.
</blockquote></details>

Done. I think it would technically be better to also use getters for the members so that they cannot be modified, but it's just unnecessary, in my opinion.
___
*[windows/driverlogic/src/driverlogic.cpp, line 935 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVytiZ8vdrIsNL0k8I:-MMWSqih5FWzlrdp-vUr:b-a802mo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L935)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Why are the next few commands necessary to support? One of the main points of using the wintun DLL is to not have to care about the driver.
</blockquote></details>

As discussed, I'll wait and see what can to be deleted.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 14 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 21 of 28 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[CHANGELOG.md, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVspvlAPxZ4lD6AuF2:-MM_zjlM3_UHXLkHp41G:b-56uajd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/CHANGELOG.md#L43)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I saw the min TLS version is now 1.3, should that be mentioned here?
</blockquote></details>

Yes, but is that true across the board now?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 6 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 26 of 28 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 26 of 28 files reviewed, 7 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[CHANGELOG.md, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVspvlAPxZ4lD6AuF2:-MMtdUNK3jbzB3JQ-zCH:bix86el) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/CHANGELOG.md#L43)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yes, but is that true across the board now? 
</blockquote></details>

It is true across the board for OpenVPN. The `--tls-version-min` has been bumped on all platforms. I think it makes sense to mention, yes.
___
*[CHANGELOG.md, line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMte0E63gCFbrIjsxg8:-MMte0E78ezyO-wV5AQU:bkpol3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a702c965537412305d4320e45ad116a88b33ef18/CHANGELOG.md#L46)):*
> ```Markdown
> - Randomly select addresses to use for communicating with the API.
> - Bundle a list of API addresses to use instead of assuming that the primary address can be reached.
> - Upgrade OpenVPN from 2.4 to 2.5.
> ```

It would be more precise to say we upgrade from `2.4.9`. `2.4.0` and `2.4.9.` is a pretty big difference.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 27 of 28 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[windows/driverlogic/src/driverlogic.cpp, line 803 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVx32b1alM8hq92EGJ:-MMtpKsdCJgMGoeQ3xSE:b-p4jdyg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/driverlogic.cpp#L803)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's being used so that some other DLL called `wintun.dll` is not loaded instead of the one contained in the installer.

I'm not sure how the standard search path option treats absolute paths, but:
> The standard search begins in the calling application's directory, and the alternate search begins in the directory of the executable module that LoadLibraryEx is loading.

https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order
</blockquote></details>

You're specifying a full path so the correct wintun will always be loaded. The flag seems to only affect how dependencies of wintun are resolved, and seem to be correctly applied here. Using the flag, dependencies of wintun will first be searched inside the same folder as wintun resides.
___
*[windows/driverlogic/src/driverlogic.cpp, line 816 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMtqQJf0SJdRPMuazcl:-MMtqQJf0SJdRPMuazcm:b-7hip1v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a702c965537412305d4320e45ad116a88b33ef18/windows/driverlogic/src/driverlogic.cpp#L816)):*
> ```cpp
> 		try
> 		{
> 			createAdapter = reinterpret_cast<WINTUN_CREATE_ADAPTER_FUNC>(getProcAddress("WintunCreateAdapter"));
> ```

May i suggest `GetProcAddressOrThrow`?
___
*[windows/driverlogic/src/driverlogic.cpp, line 843 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMtqpLL8hrqGEQ5rK1Z:-MMtqpLL8hrqGEQ5rK1_:b-ql566j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a702c965537412305d4320e45ad116a88b33ef18/windows/driverlogic/src/driverlogic.cpp#L843)):*
> ```cpp
> private:
> 
> 	FARPROC getProcAddress(const char *procName)
> ```

You could probably template the return type with no negative consequences (code bloat).

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 19 of 26 files reviewed, all discussions resolved (waiting on @mvd-ows and @pinkisemils)

___
*[CHANGELOG.md, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVspvlAPxZ4lD6AuF2:-MMtz0Xg8NIkP7pRYCnx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/CHANGELOG.md#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It is true across the board for OpenVPN. The `--tls-version-min` has been bumped on all platforms. I think it makes sense to mention, yes.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMte0E63gCFbrIjsxg8:-MMtz1Tb8XNJobt3oG1e:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a702c965537412305d4320e45ad116a88b33ef18/CHANGELOG.md#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It would be more precise to say we upgrade from `2.4.9`. `2.4.0` and `2.4.9.` is a pretty big difference.
</blockquote></details>

Done.
___
*[windows/driverlogic/src/driverlogic.cpp, line 816 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMtqQJf0SJdRPMuazcl:-MMtz9oC337lI9wA3g0N:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a702c965537412305d4320e45ad116a88b33ef18/windows/driverlogic/src/driverlogic.cpp#L816)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

May i suggest `GetProcAddressOrThrow`?
</blockquote></details>

Done.
___
*[windows/driverlogic/src/driverlogic.cpp, line 843 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMtqpLL8hrqGEQ5rK1Z:-MMtzCjK3RmQhpt2Vcle:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a702c965537412305d4320e45ad116a88b33ef18/windows/driverlogic/src/driverlogic.cpp#L843)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

You could probably template the return type with no negative consequences (code bloat).
</blockquote></details>

Done.
___
*[windows/driverlogic/src/wintun.h, line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278#-MMVzaVKCzQUFWt2rFE6:-MMu-L9o7WQsSBnJwK1W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e236603178d0e31147f6d146a7d907325f57c7/windows/driverlogic/src/wintun.h#L6)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I was expecting to see this file in the binaries repo. Separating the DLL and header could lead to issues when either is updated.
</blockquote></details>

Done.

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 7 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: 24 of 26 files reviewed, all discussions resolved (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2278)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
