### PR TITLE
Support custom DNS on Linux

### PR DESCRIPTION
**Pull request by dlon**
Allow custom DNS resolvers to be used on Linux. For addresses in private IP ranges, DNS requests are permitted by the firewall on all non-tunnel interfaces. For other addresses, requests are only allowed on the tunnel interface.

Related PRs: #2205, #2188

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)* status: 0 of 14 files reviewed, 2 unresolved discussions

___
*[talpid-core/src/firewall/linux.rs, line 577 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210#-MKPxYY7-xk44M4qj0K1:-MKPxYY8ESUoFFwmEWRR:b-mjukqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022cf57ec7d3a53265c9dff59871c88be04fed78/talpid-core/src/firewall/linux.rs#L577)):*
> ```Rust
> 
>         for resolver in &local_resolvers {
>             self.add_allow_local_dns_rule(&tunnel.interface, protocol, *resolver)?;
> ```

A set can be used instead of individual rules.
___
*[talpid-core/src/firewall/linux.rs, line 617 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210#-MKPxq86ELXIq4EBhYXi:-MKPxq86ELXIq4EBhYXj:bkqt56m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022cf57ec7d3a53265c9dff59871c88be04fed78/talpid-core/src/firewall/linux.rs#L617)):*
> ```Rust
>         host: IpAddr,
>     ) -> Result<()> {
>         let mut allow_rule = Rule::new(&self.out_chain);
> ```

Rules must be added to the input chain as well, in order for this to work without enabling LAN sharing.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)* status: 13 of 15 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/firewall/linux.rs, line 617 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210#-MKZiDA48JhTPVHHGXx6:-MKZiDA48JhTPVHHGXx7:b2vo1iz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/402484f1a183643f9e581712d355f38345d25e8f/talpid-core/src/firewall/linux.rs#L617)):*
> ```Rust
>         host: IpAddr,
>     ) -> Result<()> {
>         enum ChainDirection {
> ```

This seems a bit superfluous, you could just use `Direction::In` enum and simplify the code a bit.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)* status: all files reviewed, 1 unresolved discussion

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)* status: all files reviewed, 1 unresolved discussion

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/firewall/linux.rs, line 617 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210#-MKZiDA48JhTPVHHGXx6:-MKZs71k4lymL6BdkaxR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/402484f1a183643f9e581712d355f38345d25e8f/talpid-core/src/firewall/linux.rs#L617)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This seems a bit superfluous, you could just use `Direction::In` enum and simplify the code a bit.
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
