### PR TITLE
Update circularprogressbar to align with design

### PR DESCRIPTION
**Pull request by Rawa**
Align the CircularProgressIndicators across the app, this PR makes sure:

- We only use our own MullvadCircularProgressIndicators
- They all have round strokecap
- They all have a track color with alpha

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5381)

### CODE REVIEW

**Review by sabercodic — COMMENTED** [review]
> Reviewed 8 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5381)* status: 8 of 17 files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
Are the tint color commits for this PR supposed to be there?

> Reviewed 9 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5381#-:-Ni-eJ7U50V9ft5F9_cd:b-609wgb)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
Nope! Thanks, I've rebased the PR now.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5381#-:-Ni-wFM0CDojyGcFwnDj:b8i5xd7)* status: 8 of 17 files reviewed, all discussions resolved (waiting on @Pururun and @sabercodic)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5381#-:-Ni4Xu6A5xsZbA675L8M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
