### PR TITLE
Remove old scoped route when the default route changes

### PR DESCRIPTION
**Pull request by dlon**
macOS prefers scoped default routes on the same interface as that of the *unscoped* default route. This currently breaks if the scoped route has the wrong gateway. Let's fix this by removing up any scoped routes that we've added ourselves.

Close DES-382.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)* status: 2 of 4 files reviewed, all discussions resolved

___
*[`talpid-routing/src/unix/macos/interface.rs` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224#-Nfz2Tq1-sOavfsn_uFe:-Nfz2Tq1-sOavfsn_uFf:b3na878) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ade2a7627d7008eba0259926a1c86479112a5e1/talpid-routing/src/unix/macos/interface.rs#L159)):*
> ```XML
>                         .map(|s| unsafe { CFType::wrap_under_get_rule(*s) })
>                         .and_then(|s| s.downcast::<CFString>())
>                         .and_then(|ip| ip.to_string().parse().ok())
> ```

We should probably move all of this dict parsing into a separate module, and have an error type so that when this inevitably breaks, we can identify which field was missing or wasn't the expected type.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-routing/src/unix/macos/mod.rs` line 358 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224#-Nfz5ZeyAF9EH_HDQri4:-Nfz5QxPD9jTMIerK_PO:beyvf1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ade2a7627d7008eba0259926a1c86479112a5e1/talpid-routing/src/unix/macos/mod.rs#L358)):*
> ```XML
> 
>         // Update routes using default interface
>         self.apply_non_tunnel_routes().await?;
> ```

NIT: The `;` can be removed here.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Jontified — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, 2 of 4 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-routing/src/unix/macos/interface.rs` line 70 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224#-NfzjfArDEkFKdc0anx_:-NfzjfArDEkFKdc0anxa:b-7jh5e5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ade2a7627d7008eba0259926a1c86479112a5e1/talpid-routing/src/unix/macos/interface.rs#L70)):*
> ```XML
>             .set_gateway_addr(iface.router_ip)
>             .set_interface_index(u16::try_from(index).unwrap());
>         if is_active_interface(&iface.name, family).unwrap_or(true) {
> ```

Document this and log if there is an error
___
*[`talpid-routing/src/unix/macos/mod.rs` line 373 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224#-NfzsDVr30cuC8q4aMFk:-NfzsDVr30cuC8q4aMFl:b-xe7b3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ade2a7627d7008eba0259926a1c86479112a5e1/talpid-routing/src/unix/macos/mod.rs#L373)):*
> ```XML
>     /// If there is no tunnel device, the "best route" is the unscoped default route, whatever it
>     /// is.
>     async fn update_best_default_route(&mut self, family: interface::Family) -> Result<bool> {
> ```

Document bool return value?

**Pull request merged**
