### PR TITLE
Fix potential crash in connection state flow

### PR DESCRIPTION
**Pull request by Pururun**
I am not sure this happens in the actual app, but it is good to prevent future issues.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/util/ManagedChannel.kt` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563#-O3YOMHA0uGMMN5PIifJ:-O3YOMHC38KWdlU56qFA:b-8lten5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2649ec774823d15d91415bf73eeafda2ddb6cbc/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/util/ManagedChannel.kt#L26)):*
> ```Kotlin
>         }
> 
>         awaitClose { cancel() }
> ```

I don't think this should be necessary? `awaitClose` block is called when the flow is cancelled, I believe this block should rather be to used to remove listeners etc.

I believe the problem we faced is that we don't have a way to unregister the `notifyWhenStateChanged` callback. Thus it would invoke `it.resume(...)` and possibly `send(currentState)` on a already cancelled flow.

So I believe the correct solution would be something along the lines of:
```
internal fun ManagedChannel.connectivityFlow(): Flow<ConnectivityState> {
    return callbackFlow {
        var currentState = getState(false)

        while (isActive) {
            // Check that we are active before sending
            send(currentState)
            currentState = suspendCancellableCoroutine {
                notifyWhenStateChanged(currentState) {
                    // If we are cancelled we don't try and invoke the it.resume
                    if (it.isActive) {
                        it.resume(getState(false))
                    }
                }
            }
        }
    }
}
```

Alternatively I believe the callback could possibly be, where lambda is the onCancellation callback:
```
                        it.resume(getState(false), { _ -> })
```

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/util/ManagedChannel.kt` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563#-O3YOMHA0uGMMN5PIifJ:-O3YRV7D92x0w2AFYijf:b4h6w42) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2649ec774823d15d91415bf73eeafda2ddb6cbc/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/util/ManagedChannel.kt#L26)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I don't think this should be necessary? `awaitClose` block is called when the flow is cancelled, I believe this block should rather be to used to remove listeners etc.

I believe the problem we faced is that we don't have a way to unregister the `notifyWhenStateChanged` callback. Thus it would invoke `it.resume(...)` and possibly `send(currentState)` on a already cancelled flow.

So I believe the correct solution would be something along the lines of:
```
internal fun ManagedChannel.connectivityFlow(): Flow<ConnectivityState> {
    return callbackFlow {
        var currentState = getState(false)

        while (isActive) {
            // Check that we are active before sending
            send(currentState)
            currentState = suspendCancellableCoroutine {
                notifyWhenStateChanged(currentState) {
                    // If we are cancelled we don't try and invoke the it.resume
                    if (it.isActive) {
                        it.resume(getState(false))
                    }
                }
            }
        }
    }
}
```

Alternatively I believe the callback could possibly be, where lambda is the onCancellation callback:
```
                        it.resume(getState(false), { _ -> })
```
</blockquote></details>

Clarification: With second alternative I don't believe the `if (it.isActive)` is needed.

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Rawa — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563#-:-O45MVaX6f3dydD6RmzI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
