### PR TITLE
Move background task handling to AppDelegate

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

### Tunnel manager

- `LoadTunnelConfigurationOperation`should properly report issues when attempting to delete settings that cannot be deserialised.
- Add `TunnelManager.State.isLoadedConfiguration` property that indicates whether tunnel manager has finished initialization. This can be later used to determine if `UISceneDelegate` should wait for tunnel manager to complete initialization before showing the UI.
- `ReloadTunnelOperation` and `StopTunnelOperation` should return the `.unsetTunnel` error when tunnel does not exist yet, instead of `.unsetAccount`.
- Key rotation will now return `OperationCompletion<Bool, Error>` where the boolean output indicates whether key rotation happened.
- Extract and simplify background task management into `AppDelegate`. Tunnel manager will internally stored the status of the last key rotation.
- Refreshing VPN tunneel status is now a responsibility of `AppDelegate`. (see `TunnelManager.refreshTunnelStatus`)
- `TunnelManager.State` will simply use `NSLock` instead of trying to guess and assert the `DispatchQueue`. `delegateQueue` is then used to dispatch calls to `delegate`.
- Unite key regeneration and rotation into single `rotatePrivateKey(forceRotate: Bool)` method.
 
### `AddressCache.Tracker`

1. Make it a singleton again due to upcoming migration to `UISceneDelegate` which requires some way to access this class.
2. Switch to `NSLock` instead of `DispatchQueue`. We have very few instance members so it's fine to slap a lock then.
3. Simplify code using block operation. 

### `RelayCache.Tracker`

1. Switch to `NSLock` instead of `DispatchQueue` for simplicity.
2. Store `cachedRelays` in memory instead of parsing them from disk each time. Load relays from disk in `init()`. 
3. Simplify code using block operation.

### Notifications

1. Remove conformance to `NotificationManagerDelegate` from `NotificationController`. Instead `AppDelegate` handles that now.
3. Add shared instance for `NotificationManager` in preparation to `UISceneDelegate`  migration.

### Operations

1. Add `injectCompletion` helper to `InputInjectionBuilder` to be able to inject `OperationCompletion<T, F>` from dependencies.

### Miscellaneous 

1. Simplify conversion from `OperationCompletion<T, F>` to `UIBackgroundFetchResult`.
2.  Improve result collection in background refresh using `TransformOperation`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661)

### CODE REVIEW

**Review by AndreasShortcut — APPROVED** [review]
> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661)* status: all files reviewed, 11 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4b7Snh4MwQFfqgmbp4:-N4b7Snh4MwQFfqgmbp5:b-1c6gtf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AppDelegate.swift#L43)):*
> ```Swift
>     private let operationQueue: AsyncOperationQueue = {
>         let operationQueue = AsyncOperationQueue()
>         operationQueue.maxConcurrentOperationCount = 1
> ```

Could we init with this parameter?
`let operationQueue = AsyncOperationQueue(maxConcurrentOperations: 1)` or something?
___
*[`ios/MullvadVPN/AppDelegate.swift` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4b8JX-0z4SghmZjpKv:-N4b8JX-0z4SghmZjpKw:bz0n9kb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AppDelegate.swift#L70)):*
> ```Swift
>         }
> 
>         // Setup payments handling.
> ```

Can we wrap stuff like this in functions with names that describe what they do, instead of using comments?
___
*[`ios/MullvadVPN/AppDelegate.swift` line 121 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4b9LbL1I3_ePZpuzkR:-N4b9LbL1I3_ePZpuzkS:b-366xdx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AppDelegate.swift#L121)):*
> ```Swift
> 
>             default:
>                 fatalError()
> ```

Would someone running an iPhone / iPad app on MacOS crash here? 
___
*[`ios/MullvadVPN/AppDelegate.swift` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4bBV1F2kNwvNK6vMKK:-N4bBV1F2kNwvNK6vMKL:b-lnk0y0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AppDelegate.swift#L260)):*
> ```Swift
> 
>                 return backgroundFetchResult
> ```

Unintentional blank line?
___
*[`ios/MullvadVPN/AddressCache/AddressCacheTracker.swift` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4fQ40M8HowtDlubtq0:-N4fQ40Q9r1dlh0cP936:b-csvsp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AddressCache/AddressCacheTracker.swift#L101)):*
> ```Swift
>         {
>             let operation = ResultBlockOperation<Bool, Error> { operation in
>                 guard self.nextScheduleDate() <= Date() else {
> ```

I think this is pretty clear, but we could make a Date extension to improve readability a bit. Saw this being used in several places.
```
extension Date {
    static var now: Date { Date() }
}
```
___
*[`ios/MullvadVPN/AddressCache/AddressCacheTracker.swift` line 197 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4faz8H8SjRmMYvAT-_:-N4faz8H8SjRmMYvAT-a:bm2de6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AddressCache/AddressCacheTracker.swift#L197)):*
> ```Swift
> 
>         private func _nextScheduleDate() -> Date {
>             let nextDate = lastFailureAttemptDate.map { date in
> ```

I think this could be simplified to
```
let nextDate = Date(timeInterval: Self.retryInterval,
                    since: lastFailureAttemptDate ?? store.getLastUpdateDate())
```
right?
___
*[`ios/MullvadVPN/AddressCache/AddressCacheTracker.swift` line 204 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4fbFetCCqEjHQukyLm:-N4fbFetCCqEjHQukyLn:b-n3qzsr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AddressCache/AddressCacheTracker.swift#L204)):*
> ```Swift
>             } ?? Date(
>                 timeInterval: Self.updateInterval,
>                 since: store.getLastUpdateDate()
> ```

Maybe not defined in this PR, but perhaps we should just call it `lastUpdateDate()`?
___
*[`ios/MullvadVPN/RelayCache/RelayCacheIO.swift` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4fj097BcKCOVGOKkGv:-N4fj097BcKCOVGOKkGw:b-tv85q6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/RelayCache/RelayCacheIO.swift#L24)):*
> ```Swift
>         )
> 
>         return containerURL?.appendingPathComponent("relays.json")
> ```

Should this be type-safe?
___
*[`ios/MullvadVPN/RelayCache/RelayCacheTracker.swift` line 206 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4frCfzAK1rMylew_Zm:-N4frCfzAK1rMylew_Zn:b-yzwxmf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/RelayCache/RelayCacheTracker.swift#L206)):*
> ```Swift
>             let now = Date()
> 
>             guard let cachedRelays = cachedRelays else {
> ```

I think it's nice to use `self` in these situations for clarity, i.e.
```
guard let cachedRelays = self.cachedRelays else {
```
___
*[`ios/MullvadVPN/TunnelManager/TunnelManagerState.swift` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4fzZ93EE1GYV7X90e1:-N4fzZ93EE1GYV7X90e2:bspjw5d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/TunnelManager/TunnelManagerState.swift#L139)):*
> ```Swift
>                 }
>             }
>             nslock.unlock()
> ```

Could this be deferred?

**Comment by AndreasShortcut** [comment]
*[`ios/MullvadVPN/TunnelManager/TunnelManagerState.swift` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4fzZ93EE1GYV7X90e1:-N5-Wasc-H5e8UsMZlwp:b-naiull) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/TunnelManager/TunnelManagerState.swift#L139)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Functionally it's the same. What's your objection specifically?
</blockquote></details>

It seemed to be the pattern you used in most other places, and I thought it was cleaner

**Comment by AndreasShortcut** [comment]
*[`ios/MullvadVPN/AppDelegate.swift` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4b8JX-0z4SghmZjpKv:-N5-RKZc1-InZzVfhhYf:b-ally2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AppDelegate.swift#L70)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

What's wrong with using comments? It's 3 lines of code that do a one time configuration and not meant to be reused or repeated.
</blockquote></details>

You can leave it if you want. But in my opinion:
- It's easier to read and to understand at a glance what it does, since instead of seeing many lines of code with comments, you just see a few self-explaining calls.
- If you're changing something in a small function, it's easier to see that it won't have any unintended consequences
- In my experience, people often don't read comments or read comments last. And tend to forget to change comments after they change the code relating to it

I also just think it's a good practice to make the code as self-explanatory as possible

**Review by AndreasShortcut — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661)* status: 30 of 31 files reviewed, all discussions resolved (waiting on @AndreasShortcut)

**Review by AndreasShortcut — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661)* status: 29 of 31 files reviewed, all discussions resolved (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4b8JX-0z4SghmZjpKv:-N5-_9h_94l09q9QoPyp:b-44z148) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/AppDelegate.swift#L70)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

You can leave it if you want. But in my opinion:
- It's easier to read and to understand at a glance what it does, since instead of seeing many lines of code with comments, you just see a few self-explaining calls.
- If you're changing something in a small function, it's easier to see that it won't have any unintended consequences
- In my experience, people often don't read comments or read comments last. And tend to forget to change comments after they change the code relating to it

I also just think it's a good practice to make the code as self-explanatory as possible
</blockquote></details>

Alright. Fixed.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManagerState.swift` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661#-N4fzZ93EE1GYV7X90e1:-N5-Yr_G0e_Q8djOK24Y:bw4m5k8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68369105df937e3cf15ba9f844aade17623b818c/ios/MullvadVPN/TunnelManager/TunnelManagerState.swift#L139)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

It seemed to be the pattern you used in most other places, and I thought it was cleaner
</blockquote></details>

Changed to `defer` as per your suggestion.

**Review by AndreasShortcut — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3661)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
