### PR TITLE
Make time intervals more descriptive

### PR DESCRIPTION
**Pull request by rablador**
A lot for time intervals used within the app are represented by TimeInterval, which is Double and measures time in seconds. It would be much better if instead of specifying time in seconds we could pick the unit. For example, the following code is not easy to parse:

`let rotationInterval: TimeInterval = 60 * 60 * 24 * 14`

It could be improved with an extension that would automatically convert between seconds and units that make most sense. For example:

`let rotationInterval: TimeInterval = .hours(24)`

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 3 of 23 files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-Nbn9-FA9OPhMExeOK9W:-Nbn9-FA9OPhMExeOK9X:b-ancatl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift#L84)):*
> ```Swift
> 
>     private func callDidFinishAfterDelay() {
>         DispatchQueue.main.asyncAfter(wallDeadline: .now() + TimeInterval.seconds(1)) { [weak self] in
> ```

Did `.seconds(1)` lead to ambiguous call?

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 6 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 9 of 23 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNScreenshots/SnapshotHelper.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnRP9DBBazjNJBrT9k:-NbnRP9DBBazjNJBrT9l:b-cbccsf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPNScreenshots/SnapshotHelper.swift#L2)):*
> ```Swift
> //
> //  SnapshotHelper.swift
> ```

This file is autogenerated by `fastlane snapshot update`. Please do not modify this file because it will be overwritten anyway.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 14 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: all files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnVqnV9nQVz7taYb_C:-NbnVqnW0tao8A6UqWMs:bp9tegd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift#L16)):*
> ```Swift
> 
> final class AddressCacheTracker {
>     /// Update interval (in seconds).
> ```

"(in seconds)" is no longer relevant 
___
*[`ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnVtjb4jSflaMjA6BC:-NbnVtjb4jSflaMjA6BD:bp9tegd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift#L19)):*
> ```Swift
>     private static let updateInterval: TimeInterval = .days(1)
> 
>     /// Retry interval (in seconds).
> ```

"(in seconds)" is no longer relevant 
___
*[`ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnWQPd0FNrBvS4ijJa:-NbnWQPd0FNrBvS4ijJb:b-nu6i17) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift#L18)):*
> ```Swift
> 
> final class RelayCacheTracker {
>     /// Relay update interval (in seconds).
> ```

"(in seconds)" isn't relevant anylonger.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbscV_jBf6HW095A3n3:-NbscV_k75wCluE-s57n:bqf81oy) (no related file):*
Overall my impression that it makes it easy/low effort code quality improvement. So not against it!

On the other side, extensions pollute global namespace and I think in the future `Duration` will replace all that and so I'd perhaps work towards having a simplified replica of it, with compatible interface with extensions if needed to make it work with timers.

I want to see how others feel about it.

___

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 20 of 23 files reviewed, 5 unresolved discussions (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbscV_jBf6HW095A3n3:-NbtEpH37asYGngPyB-E:b-bnfmsi) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Overall my impression that it makes it easy/low effort code quality improvement. So not against it!

On the other side, extensions pollute global namespace and I think in the future `Duration` will replace all that and so I'd perhaps work towards having a simplified replica of it, with compatible interface with extensions if needed to make it work with timers.

I want to see how others feel about it.
</blockquote></details>

I think a drop-in replacement for a future use of `Duration` brings a compelling argument for a standalone type. Is it worth trying out before having a wider discussion?

___
___
*[`ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnVqnV9nQVz7taYb_C:-NbtP9z65Ibr2I2jivP0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift#L16)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

"(in seconds)" is no longer relevant 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnVtjb4jSflaMjA6BC:-NbtPAMVEmx1ToZ_lsS_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift#L19)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

"(in seconds)" is no longer relevant 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-Nbn9-FA9OPhMExeOK9W:-NbtPCC47laNPhF7HW89:bpk4i3i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift#L84)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Did `.seconds(1)` lead to ambiguous call?
</blockquote></details>

Yes, and according to Slack discussion we should use DispatchTimeInterval here.
___
*[`ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnWQPd0FNrBvS4ijJa:-NbtPMK_552EUYfc3gAL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

"(in seconds)" isn't relevant anylonger.
</blockquote></details>

Done.
___
*[`ios/MullvadVPNScreenshots/SnapshotHelper.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbnRP9DBBazjNJBrT9k:-NbtPNni-I5a7lw-FTwi:b-4hvi0z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a510b3239637ca7adf80004d74d0984208e09f/ios/MullvadVPNScreenshots/SnapshotHelper.swift#L2)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This file is autogenerated by `fastlane snapshot update`. Please do not modify this file because it will be overwritten anyway.
</blockquote></details>

Got it!

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbscV_jBf6HW095A3n3:-NbxWSJ57puaXWuoCzxC:b82oqq2) (no related file):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think a drop-in replacement for a future use of `Duration` brings a compelling argument for a standalone type. Is it worth trying out before having a wider discussion?
</blockquote></details>

Since you came that far, I think it's reasonable to discover how to implement a very simplified version of Duration. This could as well replace `REST.Duration`, two birds one stone.

___

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 20 of 27 files reviewed, 1 unresolved discussion (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbscV_jBf6HW095A3n3:-NbykvN6EDaXMNfjzvS7:bnkerlg) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Since you came that far, I think it's reasonable to discover how to implement a very simplified version of Duration. This could as well replace `REST.Duration`, two birds one stone.
</blockquote></details>

`Duration.swift` had beed added to MullvadTypes as drop-in replacement for upcoming (iOS16) Apple's native Duration type. In `PacketTunnelProvider.swift` you can see it in action as an alternative to TimeInterval extensions. When we get support for native Duration the idea is that this custom class can simply be removed and everything should still work.

___

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 21 of 27 files reviewed, 1 unresolved discussion (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbscV_jBf6HW095A3n3:-NbzZFSWBD_Rq67ygzDN:bgrghnn) (no related file):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`Duration.swift` had beed added to MullvadTypes as drop-in replacement for upcoming (iOS16) Apple's native Duration type. In `PacketTunnelProvider.swift` you can see it in action as an alternative to TimeInterval extensions. When we get support for native Duration the idea is that this custom class can simply be removed and everything should still work.
</blockquote></details>

That looks good :+1: 

___

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 23 of 27 files reviewed, 1 unresolved discussion (waiting on @rablador)

**Review by pronebird — COMMENTED** [review]
> Reviewed 4 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: all files reviewed, 1 unresolved discussion

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 9 of 34 files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadTypes/Duration.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0lvsA65GVUDcdwub:-NcM0lvsA65GVUDcdwuc:bs0gjza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L15)):*
> ```Swift
> /// then be deleted without affecting the rest of the code base.
> public struct Duration {
>     private(set) var components: (seconds: Int64, attoseconds: Int64)
> ```

Unless absolutely required, please make sure to use `Int` instead of `Int64`. It's more portable and by default, the `Int` type is already 64 bits on 64 bits platforms.

```swift
  1> Int.max
$R0: Int = 9223372036854775807
  2> Int64.max
$R1: Int64 = 9223372036854775807

```
___
*[`ios/MullvadTypes/Duration+Extensions.swift` line 34 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0zs1-z4WxdT75iH1:-NcM0zs2AMvTMZwZrYpW:b-vi74gg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration%2BExtensions.swift#L34)):*
> ```Swift
> 
>     public static func duration(from timeInterval: TimeInterval) -> Duration {
>         let milliseconds = (timeInterval * 1000).truncatingRemainder(dividingBy: 1000)
> ```

nit:
I don't think we should have error handling here, it would lead to unexpected results if the call site knowingly decides to go outside the boundaries of `TimeInterval`, and they wouldn't be able to handle errors and / or miscalculations.

IMHO this should be as "dumb" as possible, i.e.  if you put bad stuff in, it outputs bad stuff out.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 9 of 34 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadTypes/Duration.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0lvsA65GVUDcdwub:-NcMQKgXCjILLhDqd-oX:b38fws3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Unless absolutely required, please make sure to use `Int` instead of `Int64`. It's more portable and by default, the `Int` type is already 64 bits on 64 bits platforms.

```swift
  1> Int.max
$R0: Int = 9223372036854775807
  2> Int64.max
$R1: Int64 = 9223372036854775807

```
</blockquote></details>

The native Duration uses Int64, so to ensure compatibility I think we're stuck with it.
___
*[`ios/MullvadTypes/Duration+Extensions.swift` line 34 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0zs1-z4WxdT75iH1:-NcMR36oE_E7cKmM1QHB:bsqgx80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration%2BExtensions.swift#L34)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit:
I don't think we should have error handling here, it would lead to unexpected results if the call site knowingly decides to go outside the boundaries of `TimeInterval`, and they wouldn't be able to handle errors and / or miscalculations.

IMHO this should be as "dumb" as possible, i.e.  if you put bad stuff in, it outputs bad stuff out.
</blockquote></details>

Are you referring to `truncatingRemainder`? I'm not using it to control overflow but rather to get the decimals, ie milliseconds.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 9 of 34 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadTypes/Duration.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcMWerEEKqLBzhKdseP:-NcMWerEEKqLBzhKdseQ:b-riur32) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L14)):*
> ```Swift
> /// drop-in replacement until the app supports iOS16. Ideally this whole file can
> /// then be deleted without affecting the rest of the code base.
> public struct Duration {
> ```

We should be able to declare this `@available(iOS, introduced: 14, obsoleted: 16)` to make it obvious we don't want this past iOS 16.
___
*[`ios/MullvadTypes/Duration.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0lvsA65GVUDcdwub:-NcMW_oD9m66hGuwwnEk:b-o251hq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The native Duration uses Int64, so to ensure compatibility I think we're stuck with it.
</blockquote></details>

Arfh why Apple team, why !!!
___
*[`ios/MullvadTypes/Duration+Extensions.swift` line 34 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0zs1-z4WxdT75iH1:-NcMZNiF7m_WaEhCsEIg:bzf5gzc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration%2BExtensions.swift#L34)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Are you referring to `truncatingRemainder`? I'm not using it to control overflow but rather to get the decimals, ie milliseconds.
</blockquote></details>

Actually, we tested this with @rablador  and it turns out we have a bug here 
```swift
  8> Int((0.9).truncatingRemainder(dividingBy: 1000.0)) 
$R4: Int = 0
  9> Double((0.9).truncatingRemainder(dividingBy: 1000.0)) 
$R5: Double = 0.90000000000000002
```

Otherwise, I agree about the milliseconds, I originally read the code too fast, my apologies.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadTypes/Duration.swift` line 37 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcRQ6cx77MW92ov1035:-NcRQ6cx77MW92ov1036:bwbnjmr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L37)):*
> ```Swift
>         guard timeInterval >= 1 else {
>             let milliseconds = Int(timeInterval.truncatingRemainder(dividingBy: 1000))
>             return "\(milliseconds) ms"
> ```

For log formatting I put unit and measure together, i.e it as "100ms" and "10s" together to keep it compact. But I really have no idea how `Duration` formats things, that's why I said maybe we should have our own `func logFormat() -> String` extension like we have for other types, i.e `Date`

**Review by pronebird — COMMENTED** [review]
Please rebase your PR.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-:-NcRSMND3sqspD7MRxuK:bz10vnu)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 17 of 40 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NbscV_jBf6HW095A3n3:-NcRKNQxD5pt7Ff6NxjV:b3rzal2) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

That looks good :+1:
</blockquote></details>

Currently looking at tests, will update PR shortly.

___
___
*[`ios/MullvadTypes/Duration.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcMWerEEKqLBzhKdseP:-NcSjp7n290GgRU7wZHi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should be able to declare this `@available(iOS, introduced: 14, obsoleted: 16)` to make it obvious we don't want this past iOS 16.
</blockquote></details>

Done.
___
*[`ios/MullvadTypes/Duration.swift` line 37 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcRQ6cx77MW92ov1035:-NcSjq9c6KzKPwG41Rkh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration.swift#L37)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

For log formatting I put unit and measure together, i.e it as "100ms" and "10s" together to keep it compact. But I really have no idea how `Duration` formats things, that's why I said maybe we should have our own `func logFormat() -> String` extension like we have for other types, i.e `Date`
</blockquote></details>

Done.
___
*[`ios/MullvadTypes/Duration+Extensions.swift` line 34 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-NcM0zs1-z4WxdT75iH1:-NcRKuaC-eA5Qgbum4nT:b-7y89o7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d9d11e43dcea0f044a547d6044043e83e242125/ios/MullvadTypes/Duration%2BExtensions.swift#L34)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Actually, we tested this with @rablador  and it turns out we have a bug here 
```swift
  8> Int((0.9).truncatingRemainder(dividingBy: 1000.0)) 
$R4: Int = 0
  9> Double((0.9).truncatingRemainder(dividingBy: 1000.0)) 
$R5: Double = 0.90000000000000002
```

Otherwise, I agree about the milliseconds, I originally read the code too fast, my apologies.
</blockquote></details>

Ah, good catch!

**Review by pronebird — COMMENTED** [review]
> Reviewed 22 of 23 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: 39 of 40 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 444 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-Ncar6U6B5kFHFnNC0GS:-Ncar6U6B5kFHFnNC0GT:b-d2kdxi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3228ef4a242dbb7bf49fcc9be313ca715b8eaba9/ios/PacketTunnel/PacketTunnelProvider.swift#L444)):*
> ```Swift
>         }
> 
>         timer.schedule(wallDeadline: .now() + reconnectionDelay)
> ```

FYI Good catch!

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007#-:-NcarU5e3u4lvf25NWb1:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

**Review by pronebird — COMMENTED** [review]
> Dismissed @buggmagnet from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5007)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
