### PR TITLE
Update flow to 0.66

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

1. This PR upgrades Flow to the most recent v0.66 and migrates all of the annotations.
2. Removes the script that used to add stubs for platform dependent modules on travis
3. All `require()` calls are marked to be ignored by Flow because there is no easy way to fix.

Note that `import * as React from 'react'` is a preferred way to import `React` now since this specific statement also imports Flow annotations, such as `React.Node` that are used quite often to describe `children` etc..

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/66)

### CODE REVIEW

**Comment by pronebird** [comment]
Travis fails because there are some issues with rust compiler. Node.js tests pass.

**Comment by faern** [comment]
Accepted only file not only related to node app. I'm not going to review the JS stuff.

But wow! Do we need to have so many auto-generated files checked in? :O Are those not generated by `yarn install` or similar?

---

Reviewed 1 of 85 files at r1.
Review status: 1 of 82 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/66#-:-L5oE4bLvlN-aK3F7n8s:buifm1f)*

**Comment by eriklarko** [comment]
Awesome! :lgtm:

---

Reviewed 84 of 85 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/66#-:-L5olBjLSaQvbDekbi0k:bfgc9op)*

**Comment by anderklander** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/66#-:-L5rCqew5oTk4J2t-EpQ:bnfp4nl)*

**Comment by pronebird** [comment]
@faern that's a good one. I haven't revisited the flow-typed checkouts yet so maybe we should add a task to review them and see if we can automate them as opposed to having them as a part of repository. I'll do this in a separate PR.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/66#-:-L5rkFU8fjWaRNpIJFMu:b-jqatz7)*

**Pull request merged**
