### PR TITLE
Move forwarding functions for the API client to the api module

### PR DESCRIPTION
**Pull request by dlon**
Yet another tiny PR (continuation of #3556).

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/api.rs` line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557#-N1eLFiZ6m-FqF7MWR4T:-N1eLFiZ6m-FqF7MWR4U:b-rgdljp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8a1c4bf1926fc4f48c33cb84bba8067a43e66c3/mullvad-daemon/src/api.rs#L184)):*
> ```XML
> }
> 
> pub async fn forward_offline_state(
> ```

This function doesn't need to be async.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/api.rs` line 184 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557#-N1eLFiZ6m-FqF7MWR4T:-N1h1nhb4fqF-CuTJ72W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d8a1c4bf1926fc4f48c33cb84bba8067a43e66c3/mullvad-daemon/src/api.rs#L184)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This function doesn't need to be async.
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
