### PR TITLE
Hide the list of cities when there is only one available within the country

### PR DESCRIPTION
**Pull request by pronebird**
A little defect that @mjhomer noticed after a design review.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/26)

### CODE REVIEW

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-:-L2ex40DtgFEDB93cXaf:bnfp4nl)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/SelectLocation.js, line 135 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fG4HB1cWKQQEyqaRy:-L2fJW_kCxr4CVGMPSS7:b99o0dt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa37ed819d9db1c42cc450e18eacf1d32c0dfdd/app/components/SelectLocation.js#L135)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why the `hasActiveRelays` part?
If a country with three cities suddenly have all their servers offline, why should the cities disappear? I feel that this is unrelated. Since in the cases where a city is offline we still show it, so why the special case when all cities are offline?
</blockquote></details>

It's by design and always worked this way. The only difference that this PR adds is that it hides the accordion if there is only one city in the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/SelectLocation.js, line 135 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fG4HB1cWKQQEyqaRy:-L2fKmdlOK2vcTnoVIeU:byq2itd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa37ed819d9db1c42cc450e18eacf1d32c0dfdd/app/components/SelectLocation.js#L135)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

It's by design and always worked this way. The only difference that this PR adds is that it hides the accordion if there is only one city in the list.
</blockquote></details>

If you wish to discuss why UI works this way I think the best candidate is Matt. I can postpone the merge of this PR until then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/SelectLocation.js, line 135 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fG4HB1cWKQQEyqaRy:-L2fPzfhrI7k8bllmbws:b-m6854f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa37ed819d9db1c42cc450e18eacf1d32c0dfdd/app/components/SelectLocation.js#L135)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

If you wish to discuss why UI works this way I think the best candidate is Matt. I can postpone the merge of this PR until then.
</blockquote></details>

I just had a call with Matt and it seems that I didn't get the designs right and implemented the wrong logic. I am fixing this shortly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/components/SelectLocation.js, line 135 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fG4HB1cWKQQEyqaRy:-L2fUQgwUVy8CIvCNfWq:b-y333it) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa37ed819d9db1c42cc450e18eacf1d32c0dfdd/app/components/SelectLocation.js#L135)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I just had a call with Matt and it seems that I didn't get the designs right and implemented the wrong logic. I am fixing this shortly.
</blockquote></details>

That's fixed now. Thanks Linus for spotting this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/components/SelectLocation.js, line 171 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fUm5ZBb8k7sej7sAi:-L2fUm5ZBb8k7sej7sAj:b8226c9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41d9202093c3ac527a2385eca6fbeb4450a91751/app/components/SelectLocation.js#L171)):*
> ```JavaScript
>           </div>
> 
>           { relayCountry.cities.length > 1 && <button type="button" className="select-location__collapse-button" onClick={ handleCollapse }>
> ```

This particular change enables the chevron to expand or collapse the list of cities if there is more than one city available within the country.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by pronebird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/components/SelectLocation.js, line 179 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fUyAWexGi0OV8RrPF:-L2fUyAWexGi0OV8RrPG:b325gta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41d9202093c3ac527a2385eca6fbeb4450a91751/app/components/SelectLocation.js#L179)):*
> ```JavaScript
>         </div>
> 
>         { relayCountry.cities.length > 1 &&
> ```

This change shows the list of cities if there is more than city available within the country. This should effectively undo the previously introduced invalid UI logic that would hide the entire list of cities in the event when all cities go offline.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/components/SelectLocation.js, line 135 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fG4HB1cWKQQEyqaRy:-L2g7emi-7Wz7smkb8QA:b1uxw0n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfa37ed819d9db1c42cc450e18eacf1d32c0dfdd/app/components/SelectLocation.js#L135)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

That's fixed now. Thanks Linus for spotting this.
</blockquote></details>

Great! Good it got sorted out :)

---

*[app/components/SelectLocation.js, line 171 at r2](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26#-L2fUm5ZBb8k7sej7sAi:-L2g85uVywWfLz6daFY2:b95m4h9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41d9202093c3ac527a2385eca6fbeb4450a91751/app/components/SelectLocation.js#L171)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

This particular change enables the chevron to expand or collapse the list of cities if there is more than one city available within the country.
</blockquote></details>

Thanks for explaining!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Comment by faern** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/26)*

**Pull request merged**
