### PR TITLE
Use HTTP caching when requesting relay list

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Tidy up the HTTP status code handling in the Rest API by replacing the `RestResponse` type with `ResponseHandler` protocol and moving the response handling outside of the response types.
2. Add HTTP caching support via ETag. Stored in `CachedRelays` on disk for further cache validation.
3. Add HTTP header and status code types to reuse as constants across the code.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)* status: 0 of 10 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/MullvadRest.swift, line 419 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733#-M_QTsFy840pm54_lA6S:-M_QTsFy840pm54_lA6T:beof8jx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1cd1566b7d92ed829116c71a47fcb154959bac3a/ios/MullvadVPN/MullvadRest.swift#L419)):*
> ```Swift
> 
> struct MullvadRest {
>     let session = URLSession(configuration: .ephemeral)
> ```

FYI Janito suggested to remove the configurability of `URLSession` sometimes ago and really, we never used any other kind of `URLSession` so better drop that extra flexibility and reduce the amount of code.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)* status: 0 of 10 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/MullvadRest.swift, line 684 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733#-M_QV0mR3Pf_KVA9wRRZ:-M_QV0mS8c_BJoFwsG-G:b-n58z19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1cd1566b7d92ed829116c71a47fcb154959bac3a/ios/MullvadVPN/MullvadRest.swift#L684)):*
> ```Swift
>             return self.value(forHTTPHeaderField: HttpHeader.etag)
>         } else {
>             for case let key as String in self.allHeaderFields.keys {
> ```

FYI Finds the value of HTTP header by name using case-insensitive comparator. This is a part of iOS 13 SDK (see the branch above that simply uses the built-in function)

**Review by jvff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/MullvadRest.swift, line 682 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733#-M_QohGp08hKWsmpXfIk:-M_QohGp08hKWsmpXfIl:b-5xpd7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c00ec93eb3abc587b0674f2a3f7d277dfeb4bbdc/ios/MullvadVPN/MullvadRest.swift#L682)):*
> ```Swift
>     func value(forCaseInsensitiveHTTPHeaderField headerField: String) -> String? {
>         if #available(iOS 13.0, *) {
>             return self.value(forHTTPHeaderField: HttpHeader.etag)
> ```

Shouldn't this be `headerField`?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff and @pronebird)

___
*[ios/MullvadVPN/MullvadRest.swift, line 682 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733#-M_QohGp08hKWsmpXfIk:-M_RPv_b1U65iknZQ6d0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c00ec93eb3abc587b0674f2a3f7d277dfeb4bbdc/ios/MullvadVPN/MullvadRest.swift#L682)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Wowza. ok thanks for catching this!. Copy and paste.
</blockquote></details>

Done.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/RelayCache.swift, line 239 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733#-M_QbQqzCpd99Op-K6t6:-M_RQlPG9JTDeZCvjDJu:b-pkbhs3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c00ec93eb3abc587b0674f2a3f7d277dfeb4bbdc/ios/MullvadVPN/RelayCache.swift#L239)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Would it make sense to have three different error messages, to make it easier to diagnose issues? Like:

```
1. Failed to store downloaded relays
2. Failed to update cached relays timestamp
3. Failed to download relays
```
</blockquote></details>

Nice one! Thanks. Done!

**Pull request merged**
