### PR TITLE
GitHub issue template: Tell users to contact support if their request is not app related

### PR DESCRIPTION
**Pull request by MrChocolatine**
Hello Mullvad.

I hope this small suggestion can help regarding the number of non-app related issue you are getting.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5395)

### CODE REVIEW

**Comment by faern** [comment]
Thank you for this contribution! Sadly I doubt it will help much. People dont really read much. But we'll see :)

**Comment by MrChocolatine** [comment]
@faern 

> Thank you for this contribution! Sadly I doubt it will help much. People dont really read much. But we'll see :)

I agree.

But there is a better alternative: GitHub provides issues templates.

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

If you look at the NX repository, you could have a custom entry for non-app related question, giving another "barrier":

- https://github.com/nrwl/nx/issues/new/choose

Here is a quick example from a blank repo I just made:

- https://github.com/MrChocolatine/mullvad_issue_template_test/issues/new/choose
  Note: [the URL is set to your website](https://github.com/MrChocolatine/mullvad_issue_template_test/blob/master/.github/ISSUE_TEMPLATE/config.yml) as `mailto` URIs are not supported.

**Comment by MrChocolatine** [comment]
> But there is a better alternative: GitHub provides issues templates.
> ...

Happy to help and create a quick draft for you if that's something you would be interested in :v: .

**Comment by faern** [comment]
Yes! Partially thanks to your post about it, thank you. I read your examples and githubs documentation and conjured these new forms.

**Comment by MrChocolatine** [comment]
> Yes! Partially thanks to your post about it, thank you. I read your examples and githubs documentation and conjured these new forms.

👍

**Pull request merged**
