### PR TITLE
Add MLLVD-CR-24-03 as known issue of Android

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`docs/known-issues.md` line 242 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCdDD645KP6h_fHYcjs:-OCdFVwZAOfIKMylsWpG:b4o8x74) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ff9c963f7e2fff9bf0b0ada493209c58850d13/docs/known-issues.md#L242)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

@faern We need to set the correct dates.
</blockquote></details>

Maybe we should also add another item for when we confirmed it on Android?

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-:-OChkGbxBrvXTU8FHM-i:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243)* status: all files reviewed, 7 unresolved discussions (waiting on @Rawa)

___
*[`docs/known-issues.md` line 235 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiE59iAACmTWTYaAJP:-OCiE59iAACmTWTYaAJQ:byofcrn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L235)):*
To both make this a bin more formal, and better express what the attacker has to do, I suggest the following text instead:

> This means that any network adjacent attacker (same local network) can figure out the IP address configured on the VPN tunnel interface by sending an ARP request for every private IPv4 address to the device.
___
*[`docs/known-issues.md` line 243 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiF4Ll5nBtAZOCFOs0:-OCiF4Ll5nBtAZOCFOs1:b-fk45x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L243)):*
We say "Android" a lot here. Can we get rid of the last one here?

> All Android devices that we know of are affected, as it is the default behavior of the OS

?
___
*[`docs/known-issues.md` line 243 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiFNucEw9LNqBhJtcW:-OCiFNucEw9LNqBhJtcX:b-ezrzwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L243)):*
The "We've reported ..." sentence reads a bit strange. How about:

> We have reported this issue [upstream to Google], and recommended that they change the kernel parameter to prevent the device from disclosing the VPN tunnel IP to the local network in this way. See the report for more details.
___
*[`docs/known-issues.md` line 246 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiFxgM3KS6iAT80uX6:-OCiFxgM3KS6iAT80uX7:b-hjtjzi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L246)):*
"log in of their account" is a bit strange. I think it might be better with:

> However, users that are worried can log out and back in to the app, as this gives them a new tunnel IP.

?
___
*[`docs/known-issues.md` line 230 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiGJ8T8BexbBphhKd5:-OCiGJ8T8BexbBphhKd6:b-rae307) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L230)):*
> ```Markdown
> [Linux under WSL2 leaking]: https://mullvad.net/en/blog/linux-under-wsl2-can-be-leaking
> 
> ### Android exposes in-tunnel VPN IPs to network adjacent attackers via ARP
> ```

Nit. But for consistency and ease of reading please leave two empty lines before `### headers`.
___
*[`docs/known-issues.md` line 232 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiD14v8MZfkWRoe4uU:-OCiD14v8MZfkWRoe4uV:beqoyhs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L232)):*
> ```Markdown
> ### Android exposes in-tunnel VPN IPs to network adjacent attackers via ARP
> 
> By default the kernel paramter [`arp_ignore`] is set to `0` on Android. This makes the device reply
> ```

s/paramter/parameter/
___
*[`docs/known-issues.md` line 248 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiGRCa2sUq9-LvfFxi:-OCiGRCa2sUq9-LvfFxj:b-4lchsl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L248)):*
> ```Markdown
> user. However, users that are worried can log out and in of their account in order to rotate the IP.
> 
> #### Timeline
> ```

Nit. but for consistency and ease of reading please leave an empty line after this header before the bullet list starts.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243)* status: all files reviewed, 6 unresolved discussions (waiting on @faern)

___
*[`docs/known-issues.md` line 230 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiGJ8T8BexbBphhKd5:-OCiILnNDA5bahS7rTrJ:be74gl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L230)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit. But for consistency and ease of reading please leave two empty lines before `### headers`.
</blockquote></details>

Fixed :+1: 
___
*[`docs/known-issues.md` line 232 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiD14v8MZfkWRoe4uU:-OCiIF6V1K9dQLtJunWC:bdkgtmf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L232)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

s/paramter/parameter/
</blockquote></details>

Nice find.
___
*[`docs/known-issues.md` line 235 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiE59iAACmTWTYaAJP:-OCiIhKt8LucrWyu1sps:b-wghgn2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L235)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

To both make this a bin more formal, and better express what the attacker has to do, I suggest the following text instead:

> This means that any network adjacent attacker (same local network) can figure out the IP address configured on the VPN tunnel interface by sending an ARP request for every private IPv4 address to the device.
</blockquote></details>

Sounds good, fixed.
___
*[`docs/known-issues.md` line 243 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiFNucEw9LNqBhJtcW:-OCiHt2a1RAANJyWSf9E:b7znl9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L243)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The "We've reported ..." sentence reads a bit strange. How about:

> We have reported this issue [upstream to Google], and recommended that they change the kernel parameter to prevent the device from disclosing the VPN tunnel IP to the local network in this way. See the report for more details.
</blockquote></details>

:+1:  Sounds good to me. I like the full clarification of the recommendation as well.
___
*[`docs/known-issues.md` line 243 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiF4Ll5nBtAZOCFOs0:-OCiI8lM2ZnoDkYloJ-1:bam2tqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L243)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We say "Android" a lot here. Can we get rid of the last one here?

> All Android devices that we know of are affected, as it is the default behavior of the OS

?
</blockquote></details>

Yeah, makes sense. Fixed :heavy_check_mark: 
___
*[`docs/known-issues.md` line 246 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243#-OCiFxgM3KS6iAT80uX6:-OCiHbn7Btzw3ugmHD3S:b-jiz9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6baf5e5f9bff7be17848c41eb6f9ef1a41e8c925/docs/known-issues.md#L246)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"log in of their account" is a bit strange. I think it might be better with:

> However, users that are worried can log out and back in to the app, as this gives them a new tunnel IP.

?
</blockquote></details>

:+1: Sounds better. Fixed.

**Pull request merged**
