### PR TITLE
Implement wireguard over shadowsocks

### PR DESCRIPTION
**Pull request by Pururun**
Enables the use of shadowsocks when using wireguard.

This is blocked by:
- [x] ~https://github.com/mullvad/mullvadvpn-app/pull/6661 since we want to use the `InputDialog` added in that PR~
- [x] ~https://github.com/mullvad/mullvadvpn-app/pull/6760 since we require a new version of shadowsocks rust~
- [x] ~https://github.com/mullvad/mullvadvpn-app/pull/6781 since we have an issue with reconnect~

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)

### CODE REVIEW

**Comment by mullmat** [comment]
Design issues found:
* The Shadowsocks custom port has the title `WireGuard custom port`, this should be `Shadowsocks custom port`.

----

Otherwise this looks great design wise 🎉  !

**Comment by Pururun** [comment]
> Design issues found:
> 
>     * The Shadowsocks custom port has the title `WireGuard custom port`, this should be `Shadowsocks custom port`.
> 
> 
> Otherwise this looks great design wise 🎉 !

Thanks, fixed :)

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 62 of 64 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: all files reviewed, 19 unresolved discussions (waiting on @Pururun)

___
*[`android/CHANGELOG.md` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hun4Y2eL9vMt4JYZW:-O5Hun4Y2eL9vMt4JYZX:biolith) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/CHANGELOG.md#L27)):*
> ```Markdown
> ### Added
> - Add support for predictive back.
> - Add wireguard over shadowsocks.
> ```

wireguard -> WireGuard
shadowsocks -> Shadowsocks
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt` line 110 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HvTVy-7uNPuZ1fEeA:-O5HvTVy-7uNPuZ1fEeB:b82h4qp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt#L110)):*
> ```Kotlin
>                 .alpha(
>                     if (isSelected && !isEnabled) AlphaDisabled
>                     else if (isSelected) AlphaVisible else AlphaInvisible
> ```

Maybe a `when` statement would make this more easy to read?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt` line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HwCC_6dfZ-PO0loTq:-O5HwCC_6dfZ-PO0loTr:bbxrdnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt#L51)):*
> ```Kotlin
> @Composable
> fun SelectObfuscationCell(
>     selectedObfuscation: SelectedObfuscation,
> ```

`selectedObfuscation` is a weird name since it is not necessarily selected at all.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hx-FZDnkORjy4GTwP:-O5Hx-FZDnkORjy4GTwQ:b-a0afnw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt#L77)):*
> ```Kotlin
>                     MaterialTheme.colorScheme.selected
>                 } else {
>                     Color.Transparent
> ```

Looks a bit weird to have Transparent here, wouldn't it just make more sense to use `surfaceContainerLow`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt` line 89 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HwoEq-W9-B4T1l3il:-O5HwoEq-W9-B4T1l3im:b-11anpm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt#L89)):*
> ```Kotlin
>         if (port != null) {
>             VerticalDivider(
>                 color = Color.Transparent,
> ```

If visible if it is `Transparent`? :confused:
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt` line 116 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hx_CU2Gq6YWcg2kGS:-O5Hx_CU2Gq6YWcg2kGT:b-tdht1n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt#L116)):*
> ```Kotlin
> 
> @Composable
> private fun Constraint<Port>?.toSubTitle() =
> ```

Do we have to support nullable here? We return null if it is null, so shouldn't be needed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt` line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HxhFN90KIE015rqQn:-O5HxhFN90KIE015rqQo:ban3dlp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt#L29)):*
> ```Kotlin
> fun TwoRowCell(
>     titleText: String,
>     subtitleText: String?,
> ```

I think this is wrong. We should not allow the `subtitleText` to be null. This allows the "TwoRowCell" to become a "OneRowCell" since the subtitle is omitted if it doesn't exist.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hz1PbBzC-DK8jp5c2:-O5Hz1PbBzC-DK8jp5c3:bgvn329) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt#L41)):*
> ```Kotlin
>     isRowEnabled: Boolean = true,
>     endPadding: Dp = Dimens.cellEndPadding,
>     minHeight: Dp = Dimens.cellHeightTwoRows,
> ```

Feels like this composable is starting to blow up with arguments. Is `minHeight` necessary? Shouldn't it always be the same for all TwoRowCells?

Is the `endPadding` really needed to pass externally?

Can isRowEnabled be decided by a nullable `onCellClicked`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HzwCFEGB8_SIpmWjP:-O5HzwCFEGB8_SIpmWjQ:b-okzj03) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt#L71)):*
> ```Kotlin
>         navigateToCustomPortDialog =
>             dropUnlessResumed {
>                 val args =
> ```

Not sure if formatting/readability is the issue here but, we use this `args` directly after once, do we need to declare a `val` for it?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HzmLfCjZCdyUukWrw:-O5HzmLfCjZCdyUukWrx:b93p7gp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt#L73)):*
> ```Kotlin
>                 val args =
>                     CustomPortNavArgs(
>                         title =
> ```

Do we really need to pass the `title`, shouldn't the dialog it self be able to produce this?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt` line 113 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I-cJh9-xic75fxSFU:-O5I-cJh9-xic75fxSFV:b-9mhijh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt#L113)):*
> ```Kotlin
>                     SelectableCell(
>                         title = port.toString(),
>                         isSelected = state.port.hasValue(port),
> ```

Looks weird to be me with `hasValue` can't we use `?.` or similar operator to compare instead?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 243 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I1x-tE-KTccGR3xrb:-O5I1x-tE-KTccGR3xrc:b4d0jux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L243)):*
> ```Kotlin
>                 val args =
>                     CustomPortNavArgs(
>                         title =
> ```

Do we need to pass title as an argument in this case? We should be able to resolve it in the dialog?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 251 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I26SMEAVQJDPKL9Us:-O5I26SMEAVQJDPKL9Ut:b-7qzp79) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L251)):*
> ```Kotlin
>                         allowedPortRanges = state.availablePortRanges,
>                     )
>                 navigator.navigate(CustomPortDestination(args))
> ```

Maybe worth considering changing the destination name from CustomPort to WireguardCustomPort? Since we start to expand to multiple options with ports.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/ShadowsocksSettingsState.kt` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I2hVCAPZM-bW5_D5-:-O5I2hVCAPZM-bW5_D50:bzgis5a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/ShadowsocksSettingsState.kt#L9)):*
> ```Kotlin
> data class ShadowsocksSettingsState(
>     val port: Constraint<Port> = Constraint.Any,
>     val customPort: Port? = null,
> ```

How does customPort and `port` related? There are no restrictions on this type, is it fine to have a port and a custom port?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortExtensions.kt` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I3K5i9Z4M5etL3mU2:-O5I3K5i9Z4M5etL3mU3:b6x4g66) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PortExtensions.kt#L13)):*
> ```Kotlin
>     }
> 
> fun Constraint<Port>.isCustom(presetPorts: List<Int>) =
> ```

This feels a bit weird to me, maybe we should consider rethinking our model to avoid this kind of functions. It feels like there should be a more intuitive way to find out if it is custom or not.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I3gCHB633fFcnAJIe:-O5I3gCHB633fFcnAJIf:b-v9xx1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L51)):*
> ```Kotlin
>     init {
>         viewModelScope.launch {
>             val initialSettings = settingsRepository.settingsUpdates.filterNotNull().first()
> ```

I believe `firstNotNull()` exists.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I42TWDdjJ6Ex6LiZ9:-O5I42TWDdjJ6Ex6LiZA:b-fbld5d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L66)):*
> ```Kotlin
>         viewModelScope.launch {
>             if (port.isCustom(SHADOWSOCKS_PRESET_PORTS)) {
>                 customPort.update { port.getOrNull() }
> ```

Looks weird to me, we set it no matter if we succeed with the `settingsRepository` below, shouldn't we only set it if we are successful?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I4HVZ7SnqTKbE5KB7:-O5I4HVZ7SnqTKbE5KB8:b2nreh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L75)):*
> ```Kotlin
> 
>     fun resetCustomPort() {
>         customPort.update { null }
> ```

Same as above.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedObfuscation.kt` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I1gYU55O7XiXRLlzB:-O5I1gYU55O7XiXRLlzC:b-l79acn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedObfuscation.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.model
> 
> enum class SelectedObfuscation {
> ```

We should consider renaming this class to something else. Since it is not really `SelectedObfuscation` but rather the options available. It doens't store the data if the option is selected or not.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: all files reviewed, 19 unresolved discussions (waiting on @Rawa)

___
*[`android/CHANGELOG.md` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hun4Y2eL9vMt4JYZW:-O5IA-f1574XZukY9aFZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/CHANGELOG.md#L27)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

wireguard -> WireGuard
shadowsocks -> Shadowsocks
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> Reviewed 4 of 64 files at r1, 1 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 50 of 65 files reviewed, 16 unresolved discussions (waiting on @Pururun and @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 8 of 65 files reviewed, 9 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I3gCHB633fFcnAJIe:-O5my_wc6t49KE1vduYL:bgt55sv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L51)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Did not find any for flow.
</blockquote></details>

Correct, doesn't exist! Retract!

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 8 of 65 files reviewed, 9 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 70 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5myp2Z8QyqYzMc5EcR:-O5myp2Z8QyqYzMc5EcS:ba4hq9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5ea6bd79781d52a3303195a9f5f0804a8bc02d9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L70)):*
> ```Kotlin
>                     if (
>                         port is Constraint.Only &&
>                             SHADOWSOCKS_PRESET_PORTS.contains(port.value).not()
> ```

Maybe more clear `port.value !in SHADOWSOCKS_PRESET_PORTS` ?

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 8 of 65 files reviewed, 9 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`android/CHANGELOG.md` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hun4Y2eL9vMt4JYZW:-O5mz8dM2DqjiPA4njrV:boryep7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/CHANGELOG.md#L27)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Wireguard -> WireGuard

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 32 of 65 files reviewed, 12 unresolved discussions (waiting on @dlon and @Rawa)

___
*[`android/CHANGELOG.md` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5Hun4Y2eL9vMt4JYZW:-O5n4J_e073UsOKMaEP0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/CHANGELOG.md#L27)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

nit: Wireguard -> WireGuard
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt` line 66 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5mztl0EUbLXXUY43QF:-O5n7FE_BOeBoCLduEr9:bw7k4lj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5ea6bd79781d52a3303195a9f5f0804a8bc02d9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt#L66)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should we clarify base cell as well?
</blockquote></details>

Not sure, there are cases where we want to enable and disable the cell dynamically and not adjust the onclick.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/WireguardConstant.kt` line 10 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5n-TdcBAZpVekFDR9l:-O5n6CJk5t5qJSaY2B0t:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5ea6bd79781d52a3303195a9f5f0804a8bc02d9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/WireguardConstant.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`PortRange(0..65535)`

Maybe we should consider exposing MIN_VALUE and MAX_VALUE from Port.kt to create this one.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I4HVZ7SnqTKbE5KB7:-O5n6b720fZlMonMi5AG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L75)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt` line 70 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5myp2Z8QyqYzMc5EcR:-O5n6Rxg7nflBqS4IV6h:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5ea6bd79781d52a3303195a9f5f0804a8bc02d9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ShadowsocksSettingsViewModel.kt#L70)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe more clear `port.value !in SHADOWSOCKS_PRESET_PORTS` ?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt` line 103 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5n0807D01eFC6BUK9h:-O5n73ZOB7VqkMVsMp4w:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5ea6bd79781d52a3303195a9f5f0804a8bc02d9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt#L103)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

```
initialPort.getOrNull() !in WIREGUARD_PRESET_PORTS
```
</blockquote></details>

Done.

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 54 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 30 of 66 files reviewed, 12 unresolved discussions (waiting on @dlon and @Pururun)

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 29 of 54 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: all files reviewed, 10 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/WireguardConstant.kt` line 11 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5n8FgmAcZaiiwdoJsD:-O5n8FgmAcZaiiwdoJsE:b-lgfk3q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0069f227e019b6b9e3698ee2f15d0d099b9a93ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/WireguardConstant.kt#L11)):*
> ```Kotlin
> val SHADOWSOCKS_AVAILABLE_PORTS =
>     // Currently we consider all ports to be available
>     listOf(PortRange(IntRange(Port.MIN_VALUE, Port.MAX_VALUE)))
> ```

Port `Port.MIN_VALUE..Port.MAX_VALUE`

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: all files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/WireguardConstant.kt` line 11 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5n8FgmAcZaiiwdoJsD:-O5nAJrA-LcsNKbzGQOl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0069f227e019b6b9e3698ee2f15d0d099b9a93ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/WireguardConstant.kt#L11)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Port `Port.MIN_VALUE..Port.MAX_VALUE`
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 50 of 66 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt` line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HwCC_6dfZ-PO0loTq:-O5qfycL2pkpT1RFDf51:b-om8mxa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectObfuscationCell.kt#L51)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`selectedObfuscation` is a weird name since it is not necessarily selected at all.
</blockquote></details>

Updated naming
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedObfuscation.kt` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I1gYU55O7XiXRLlzB:-O5qg2bi-YKfWsRamTIk:b-y6yup0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedObfuscation.kt#L3)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should consider renaming this class to something else. Since it is not really `SelectedObfuscation` but rather the options available. It doens't store the data if the option is selected or not.
</blockquote></details>

Changed name

**Comment by Pururun** [comment]
Putting this on hold, since we are partially blocked, see description for more details.

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, 14 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 65 of 66 files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 15 files at r8, 37 of 37 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672)* status: 58 of 69 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5HzmLfCjZCdyUukWrw:-O6uyvDO19YWQ_oG9dBy:bswiurm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ShadowsocksSettingsScreen.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we really need to pass the `title`, shouldn't the dialog it self be able to produce this?
</blockquote></details>

Split into two dialogs
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 251 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6672#-O5I26SMEAVQJDPKL9Us:-O6uyy3M2XzpI3FJIsLc:bip6yr0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61323dc1008820caf6131525c2efe19503b43aa4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L251)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe worth considering changing the destination name from CustomPort to WireguardCustomPort? Since we start to expand to multiple options with ports.
</blockquote></details>

Split into two dialogs again.

**Pull request merged**
