### PR TITLE
Break down `TunnelManager`

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR breaks down the `TunnelManager` on multiple `Operation`s. Each `Operation` accepts a `delegate` that implements methods to notify the `TunnelManager` on the operation progress along with providing and updating the shared data such as `TunnelInfo`, `TunnelState`, `TunnelProviderManager`.

`OperationCompletion<Success, Failure>` was added to extend the `Result<Success, Failure>` type with additional state `.cancelled` which is returned when `Operation` was cancelled before being able to complete.

`AppDelegate` also leverages `OperationQueue` to order background asks on iOS < 13 instead of nested calls.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 12 of 25 files at r1, 20 of 20 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/TunnelManager/LoadTunnelOperation.swift, line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuV-7Wm-96jrPLM8Jsv:-MuV-7WnEN2jouk2rTfD:b-gquna5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/LoadTunnelOperation.swift#L16)):*
> ```Swift
> 
>     private let queue: DispatchQueue
>     private let token: String?
> ```

Maybe rename this to `accountToken`?
___
*[ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift, line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVIVAL-BT8XBVdsrlc:-MuVIVAL-BT8XBVdsrld:b58hts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift#L2)):*
> ```Swift
> //
> //  RenegeratePrivateKeyOperation.swift
> ```

This is misspelled. The actual file name is correct though.
___
*[ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift, line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVIbTl1ZL1YEH2V6TZ:-MuVIbTl1ZL1YEH2V6T_:bvitodx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift#L11)):*
> ```Swift
> import Foundation
> 
> class RenegeratePrivateKeyOperation: AsyncOperation {
> ```

Same spelling error here.
___
*[ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift, line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVQ-14DfmysthyXQPR:-MuVQ-155xoO8jlQM2-z:bk992lc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift#L56)):*
> ```Swift
>         case .success(let newTunnelSettings):
>             state.tunnelInfo?.tunnelSettings = newTunnelSettings
>             
> ```

There's a bunch of spaces here.
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 441 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVPAVG8bW_te9lFW_r:-MuVPAVG8bW_te9lFW_s:blbfdhr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5615c124acec08bf62fbad316d7814245edabf5b/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L441)):*
> ```Swift
>     func rotatePrivateKey() -> Result<KeyRotationResult, TunnelManager.Error>.Promise {
>         return Promise.deferred { self.tunnelInfo }
>             .some(or: .missingAccount)
> ```

How is being logged out handled with the new solution?
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 699 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuUyQ9i7QcV6MfqpE_j:-MuUyQ9i7QcV6MfqpE_k:b-ujest) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L699)):*
> ```Swift
> 
>         task.expirationHandler = {
>             // TODO: handle cancellation?
> ```

Is this a todo for this PR or later?

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift, line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVQ-14DfmysthyXQPR:-MuV_uQC77H3xF6T68Sp:b41bo81) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift#L56)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

There's a bunch of spaces here.
</blockquote></details>

That must have been fixed. Could you double check?

**Review by raksooo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294)* status: all files reviewed, 6 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift, line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVQ-14DfmysthyXQPR:-MuVbUHn9P8GDieuA1FG:bkwbb0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift#L56)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

That must have been fixed. Could you double check? 
</blockquote></details>

Ah yes, it was fixed in the last revision :+1:

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294)* status: 25 of 32 files reviewed, 5 unresolved discussions (waiting on @raksooo)

___
*[ios/MullvadVPN/TunnelManager/LoadTunnelOperation.swift, line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuV-7Wm-96jrPLM8Jsv:-MuVsZUh0i2pF32VCpcn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/LoadTunnelOperation.swift#L16)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Maybe rename this to `accountToken`?
</blockquote></details>

Done.
___
*[ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift, line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVIVAL-BT8XBVdsrlc:-MuVtYJ423zi4rJmLOiT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift#L2)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This is misspelled. The actual file name is correct though.
</blockquote></details>

Done.
___
*[ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift, line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVIbTl1ZL1YEH2V6TZ:-MuVt_LJ9azMvLZUSR8f:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/RegenerateTunnelPrivateKeyOperation.swift#L11)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Same spelling error here.
</blockquote></details>

Done.
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 441 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuVPAVG8bW_te9lFW_r:-MuW6RELDrGzjeaLhMxN:b-n8f5hw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5615c124acec08bf62fbad316d7814245edabf5b/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L441)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

How is being logged out handled with the new solution?
</blockquote></details>

We never usually call `setAccount` when logged in, but I think you have a good point and we should combine both `SetAccountOperation` and `UnsetAccountOperation` into one and handle switch between accounts the same way as if the one unset the account first and then set the new one.
___
*[ios/MullvadVPN/TunnelManager/TunnelManager.swift, line 699 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-MuUyQ9i7QcV6MfqpE_j:-MuW6fboAPmAwFffqcNG:b-600eur) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a17c3129d354531e71cfe3a92af9ae898cfb6872/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L699)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Is this a todo for this PR or later?
</blockquote></details>

For later PRs.

**Review by raksooo — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294#-:-MujYKsVDJOR4fCKyhZg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3294)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
