### PR TITLE
Add DAITA into TunnelSettings

### PR DESCRIPTION
**Pull request by mojganii**
This PR integrates `DAITA` settings into the tunnel settings, enhancing configuration flexibility and ensuring seamless DAITA support within the tunnel environment.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 23 of 32 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4Ezheq1Keov63cxvMI:-O4Ezheq1Keov63cxvMJ:b-1oic23) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift#L47)):*
> ```Swift
>                 didUpdateSettings: { [weak self] _, latestTunnelSettings in
>                     guard let self else { return }
>                     if settingsStrategy.shouldReconnectToNewRelay(
> ```

Isn't this used more as a general check for changes in constraints? At least this seems to be the only application at this point. Perhaps `shouldReconnectToNewRelay` should be renamed to `constraintsHaveChanged`or something similar?
___
*[`ios/MullvadSettings/TunnelSettingsV6.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4Emts54abjAO1zHnoj:-O4Emts54abjAO1zHnok:b-yiv9j3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/TunnelSettingsV6.swift#L28)):*
> ```Swift
>     public var tunnelMultihopState: MultihopState
> 
>     /// Whether Multi-hop is enabled.
> ```

"DAITA" instead of multihop

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 21 of 32 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadSettings/DAITASettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4FJd6v45WiEAerDuIh:-O4FJd6v45WiEAerDuIi:b-mi3s64) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/DAITASettings.swift#L16)):*
> ```Swift
>     case off
> 
>     public var isEnabled: Bool {
> ```

Do we really need this for an enum that is a bool value ?
___
*[`ios/MullvadSettings/TunnelSettingsPropagator.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4FBND88p_94IAgKCoH:-O4FBND88p_94IAgKCoI:bnxvgkp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/TunnelSettingsPropagator.swift#L21)):*
> ```Swift
> 
> public class SettingsObserverBlock: SettingsObserver {
>     public typealias DidUpdateSettingsHandler = (SettingsPropagation, LatestTunnelSettings) -> Void
> ```

This looks like a delegate pattern except it's called observer instead. 
Why do we pass a settings handler which you can also subscribe to, when the object (`SettingsObserverBlock`) we are listening to, already gives us an update on the settings ?

From the use I can see, we don't use that argument anywhere, we should remove this.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadSettings/DAITASettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4FJd6v45WiEAerDuIh:-O4FZkwT0lMNhClwJQqG:b-ve81dx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/DAITASettings.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Do we really need this for an enum that is a bool value ?
</blockquote></details>

Could be that we'll have .auto or something in the future as well. Also, it's consistent with multihopState.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)* status: 25 of 33 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4Ezheq1Keov63cxvMI:-O4FdLDTAy10oqJcy9wP:b-sje5fu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift#L47)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Isn't this used more as a general check for changes in constraints? At least this seems to be the only application at this point. Perhaps `shouldReconnectToNewRelay` should be renamed to `constraintsHaveChanged`or something similar?
</blockquote></details>

it's not about the constraints, it's all about whether `reconnecting` to the new relays should be done by some part changing in settings or not. the major responsibility for this part is that forces relaySelector to pick new relay if needed, regardless if it's `ShadowSocks` or `Direct`.
___
*[`ios/MullvadSettings/DAITASettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4FJd6v45WiEAerDuIh:-O4FeOmiCmaNR7lq0nhG:bsabm3k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/DAITASettings.swift#L16)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Could be that we'll have .auto or something in the future as well. Also, it's consistent with multihopState.
</blockquote></details>

yes, it's for consistency. 
___
*[`ios/MullvadSettings/TunnelSettingsPropagator.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4FBND88p_94IAgKCoH:-O4FhI5a-KkBN1MqqOYY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/TunnelSettingsPropagator.swift#L21)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This looks like a delegate pattern except it's called observer instead. 
Why do we pass a settings handler which you can also subscribe to, when the object (`SettingsObserverBlock`) we are listening to, already gives us an update on the settings ?

From the use I can see, we don't use that argument anywhere, we should remove this.
</blockquote></details>

Done.
___
*[`ios/MullvadSettings/TunnelSettingsV6.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4Emts54abjAO1zHnoj:-O4FeXdA1F9CdZG9IZNS:b6zrrk4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/TunnelSettingsV6.swift#L28)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"DAITA" instead of multihop
</blockquote></details>

Good catch!

**Review by rablador — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

**Review by buggmagnet — APPROVED** [review]
> Reviewed 2 of 32 files at r1, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii and @rablador)

___
*[`ios/MullvadSettings/DAITASettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6605#-O4FJd6v45WiEAerDuIh:-O4JxLEU7FVpuYLyQNUf:b-4ktt52) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f449127749702fcce70c5b85e77a72b9a3a5cc12/ios/MullvadSettings/DAITASettings.swift#L16)):*
But that doesn't mean it's a good idea 😭
> Could be that we'll have .auto or something in the future as well.
YAGNI

Anyhow, it's not a big deal.

**Pull request merged**
