### PR TITLE
Split Android project and app module

### PR DESCRIPTION
**Pull request by albin-mullvad**
The purpose of this is to:

* Comply better with the default Android project structure
  (see https://developer.android.com/studio/build).
* Avoid conflicts between project and app dependencies and plugins.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **SKIPPED**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 24 of 438 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198)* status: 24 of 438 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[android/app/build.gradle, line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198#-Mqym7M91Y3p-gRzugmp:-Mqym7M91Y3p-gRzugmq:b-r7r2xp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8e60959f2f5a333b7e3f69913d696e02c4f487d/android/app/build.gradle#L172)):*
> ```Gradle
>     androidTestImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
>     // debugImplementation because LeakCanary should only run in debug builds.
>     // debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.6'
> ```

Must this commented out dependency be here?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 51 of 438 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198)* status: 75 of 438 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 363 of 438 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198)* status: 437 of 438 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/app/build.gradle, line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198#-Mqym7M91Y3p-gRzugmp:-Mr1Jqqd4cXH6UnNvlpd:b-c8nue9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8e60959f2f5a333b7e3f69913d696e02c4f487d/android/app/build.gradle#L172)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Must this commented out dependency be here?
</blockquote></details>

No, I removed it and instead suggest that we do something like in the following commit if we see a need for leak canary:
https://github.com/mullvad/mullvadvpn-app/commit/5eb15a8a1dd88cb524a2ea40e09babb9fb06bb24

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3198#-:-Mr1o2t6AUIgAe3aQCf7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
