### PR TITLE
Fix for failing nightly iOS end to end tests

### PR DESCRIPTION
**Pull request by niklasberglund**
Fixes for `testLogin` and `testCustomDNS` end to end tests failing. This PR removes the "no time account number" which is a persistent account without any time on it, and adds teardown blocks for `testAdBlockingViaDNS` and `testAdBlockingViaDNS` reset state changes that affected other tests.

To test the changes in this PR its easiest to run the GitHub actions workflow `iOS end-to-end tests`. I did a run on this branch at https://github.com/mullvad/mullvadvpn-app/actions/runs/8690296877

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120)

### CODE REVIEW

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120#-Nv_mNwq8vpzf6JkaD0b:-Nv_mNwq8vpzf6JkaD0c:b-fectyg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58f0140d3b9a8d52cd8889d6428c15b8f6000001/ios/MullvadVPNUITests/AccountTests.swift#L61)):*
> ```Swift
>         LoginPage(app)
>             .tapAccountNumberTextField()
>             .enterText(self.hasTimeAccountNumber)
> ```

Nit: Unnecessary `self`

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120#-Nvf4r7hAtv8BKxCrUF_:-Nvf4r7hAtv8BKxCrUFa:bf9jz3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58f0140d3b9a8d52cd8889d6428c15b8f6000001/ios/MullvadVPNUITests/RelayTests.swift#L54)):*
> ```Swift
>                 .tapDNSSettingsCell()
> 
>             DNSSettingsPage(self.app)
> ```

If any of the steps that happens before we enable DNS ad block fails, this will put it in the wrong state for the entirety of the run.
We should be able to guarantee that it's not toggled, but set to the off state here.

I haven't tested that, but something along those lines should be good I think
```swift
    @discardableResult func toggleOffBlockAdsSwitch() -> Self {
        let blockAdsSwitch = app.cells[AccessibilityIdentifier.blockAdvertising]
            .switches[AccessibilityIdentifier.customSwitch]

        guard blockAdsSwitch.value as? String == "0" else { return self }
        blockAdsSwitch.tap()

        return self
    }
```

**Review by niklasberglund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120#-Nvf4r7hAtv8BKxCrUF_:-NvfSNsHB7uxUnjV5KX_:b-92ytcr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58f0140d3b9a8d52cd8889d6428c15b8f6000001/ios/MullvadVPNUITests/RelayTests.swift#L54)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If any of the steps that happens before we enable DNS ad block fails, this will put it in the wrong state for the entirety of the run.
We should be able to guarantee that it's not toggled, but set to the off state here.

I haven't tested that, but something along those lines should be good I think
```swift
    @discardableResult func toggleOffBlockAdsSwitch() -> Self {
        let blockAdsSwitch = app.cells[AccessibilityIdentifier.blockAdvertising]
            .switches[AccessibilityIdentifier.customSwitch]

        guard blockAdsSwitch.value as? String == "0" else { return self }
        blockAdsSwitch.tap()

        return self
    }
```
</blockquote></details>

Have implemented a check and tapping only when the toggle is on in teardown

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120#-:-NvfdoIF9GINrYOkL24G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6120)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

**Pull request merged**
