### PR TITLE
Fix unlabeled buttons in Android app

### PR DESCRIPTION
**Pull request by PatrykMis**
As a long-time blind user of this app on both Android and Windows, I've encountered significant accessibility challenges that I believe need to be addressed. On Android, many buttons are simply read as "button," without conveying any meaningful information. This forces screen reader users like myself to rely on intuition, memory, and sometimes luck, particularly when attempting tasks beyond basic actions like connecting to the VPN.

While there are still many accessibility improvements needed, such as adding proper semantics, roles, and ensuring states are announced correctly, labeling the buttons is a crucial first step. This change will greatly enhance the usability of the app for screen reader users.

If this pull request is merged, I plan to continue working on improving the accessibility of the app, addressing the other aspects mentioned. I'm also open to any suggestions, improvements, reviews, or comments from the community as I work through these changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6897)

### CODE REVIEW

**Comment by albin-mullvad** [comment]
Hi @PatrykMis! Thank you very much for taking the time to improve the accessibility of the app :heart: We'll make sure to review this asap!

**Review by Pururun — CHANGES_REQUESTED** [review]
Very nice work, please just address the translation remark and we can go ahead and merge this.

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6897#-:-O8BXYhI3ACrpag8cyE8:b-da4p2a)* status: all files reviewed, 1 unresolved discussion (waiting on @PatrykMis)

___
*[`gui/locales/pl/messages.po` line 2693 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6897#-O8BZZztCmtCeLYHD3hu:-O8BYNmf6UOSZFiSvKO4:bczbboh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b7086c2340eb65a06169bbbc7522b8b6e8eb5577/gui/locales/pl/messages.po#L2693)):*
> ```pot
> msgstr[3] "%d godzuny temu"
> 
> msgctxt "accessibility"
> ```

Unfortunately we can not accept translations in PRs. See this document for more information: [https://github.com/mullvad/mullvadvpn-app/blob/main/CONTRIBUTING.md#localization--translations](https://github.com/mullvad/mullvadvpn-app/blob/main/CONTRIBUTING.md#localization--translations)

Translations will be added automatically in preparation for the next release.

Please restore this file.

**Comment by PatrykMis** [comment]
I have just removed translations like you've requested, keeping only these strings synced by `translations-converter`.

**Comment by PatrykMis** [comment]
Thank you for the review! I wanted to let you know that I'm unable to resolve and reply to comments directly in Reviewable.io due to its inaccessibility with screen readers. Unfortunately, it doesn't provide the same level of accessibility as GitHub's review system, which I can navigate more effectively.

If possible, I would appreciate it if we could continue the discussion or address feedback directly through GitHub. Thank you for your understanding!

**Comment by Pururun** [comment]
> I have just removed translations like you've requested, keeping only these strings synced by `translations-converter`.

Great!

> Thank you for the review! I wanted to let you know that I'm unable to resolve and reply to comments directly in Reviewable.io due to its inaccessibility with screen readers. Unfortunately, it doesn't provide the same level of accessibility as GitHub's review system, which I can navigate more effectively.
> 
> If possible, I would appreciate it if we could continue the discussion or address feedback directly through GitHub. Thank you for your understanding!

I understand, that 's unfortunate. Will only use Github in the future. :)

**Review by Pururun — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6897)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by PatrykMis** [comment]
Would you like me to rebase this PR?

**Comment by Pururun** [comment]
> Would you like me to rebase this PR?

It is not required, we will handle rebase to main on our side during the merge process.

**Comment by Rawa** [comment]
Merged! Thanks for the contribution @PatrykMis! 🙏

**Pull request merged**
