### PR TITLE
Move android changes to `android/CHANGELOG.md`

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to add a new Android specific `android/CHANGELOG.md` and move all historic changes to it.

TODO:
* [x] Adapt `prepare-release.sh`
* [x] Update repository references to the changelog.
* [x] Add CI job to check the changelog.

TODO after merging:
* [ ] Update internal release documentation.
* [ ] Update F-Droid repository [changelog link](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.mullvad.mullvadvpn.yml#L14) after merging.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`CHANGELOG.md` line 1316 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv2KIMc2bCzeff719OB:-Nv2KIMc2bCzeff719OC:b-yjmb8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9a23de0528cb90ad248863dd70737ab198680fd7/CHANGELOG.md#L1316)):*
> ```Markdown
> 
> #### Windows
> - Upgrade Wintun from 0.9.2 to 0.10.1.
> ```

This needs to stay put :D Prefer leaving some Android entries behind in `CHANGELOG.md` over accidentally pulling in desktop changes to `android/CHANGELOG.md`. Mostly because a changelog is a record of history, it should optimally not see much changes at all for old entries. If changes are needed they should be well motivated. And moving Windows stuff to an Android changelog is not a perfect motivation :joy: 
___
*[`android/CHANGELOG.md` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv2KlpgCTpjJr7SVMmU:-Nv2KlpgCTpjJr7SVMmV:bua36me) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b14818d03fa9844ca23943372037b18ce54290b9/android/CHANGELOG.md#L273)):*
> ```Markdown
> 
> ### Security
> #### Android
> ```

I think we should strip all Android-headers. They are implicit in this new file.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`CHANGELOG.md` line 1316 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv2KIMc2bCzeff719OB:-Nv2QfuJCYrb_64kD70Y:bjndosn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9a23de0528cb90ad248863dd70737ab198680fd7/CHANGELOG.md#L1316)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This needs to stay put :D Prefer leaving some Android entries behind in `CHANGELOG.md` over accidentally pulling in desktop changes to `android/CHANGELOG.md`. Mostly because a changelog is a record of history, it should optimally not see much changes at all for old entries. If changes are needed they should be well motivated. And moving Windows stuff to an Android changelog is not a perfect motivation :joy:
</blockquote></details>

Yes, makes sense. Automatically moved everything belonging to an android header, but there are a few changes that clearly doesn't belong to an android release in this specific release. Moved those back now, so please have another look.
___
*[`android/CHANGELOG.md` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv2KlpgCTpjJr7SVMmU:-Nv2QYVS9O1bsEKmdwVI:b-22euun) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b14818d03fa9844ca23943372037b18ce54290b9/android/CHANGELOG.md#L273)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should strip all Android-headers. They are implicit in this new file.
</blockquote></details>

Yeah, thought of that as well :thumbsup:

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`android/CHANGELOG.md` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv2KlpgCTpjJr7SVMmU:-Nv2SsdP0x0Qyzio01u5:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b14818d03fa9844ca23943372037b18ce54290b9/android/CHANGELOG.md#L273)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yeah, thought of that as well :thumbsup:
</blockquote></details>

Done!

**Review by raksooo — APPROVED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @faern)

**Review by Rawa — APPROVED** [review]

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv5xoBC8jZKxEthNqjE):*
Nit: Would IMO be nice if you squashed this commit before merging. So the entries never move and move back. Maybe you already planned on that, just wanted to point it out.
___
*[`CHANGELOG.md` line 942 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv5w9rm09IYQAc3cD73:-Nv5w9rm09IYQAc3cD74:bqa2dn6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ffb966cb380eef50bad349ee1c43d44ca042603/CHANGELOG.md#L942)):*
> ```Markdown
> ### Added
> - Enable isolation of the Electron renderer process to protect against potentially malicious third
>   party dependencies.
> ```

This item seems to be present twice here now

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @faern and @raksooo)

___
*[`-- commits` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv5xoBC8jZKxEthNqjE):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit: Would IMO be nice if you squashed this commit before merging. So the entries never move and move back. Maybe you already planned on that, just wanted to point it out.
</blockquote></details>

Yeah, I plan to squash some or all commits :thumbsup: 
___
*[`CHANGELOG.md` line 942 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv5w9rm09IYQAc3cD73:-Nv6-4JR9-0xd_nuhNV5:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ffb966cb380eef50bad349ee1c43d44ca042603/CHANGELOG.md#L942)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This item seems to be present twice here now
</blockquote></details>

Fixed!

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`.github/workflows/check-changelog.yml` line 29 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv61GSnAwWY5IZGWPtB:-Nv61GSo5KRFsNL5-dJX:b-caahqo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bec6b180d5da29b6c3a58fd975b8392bd85fe4da/.github/workflows/check-changelog.yml#L29)):*
> ```YAML
>         run: |
>           awk 'length($0) > '$LINE_LIMIT' { print NR ": Line exceeds '$LINE_LIMIT' chars: " $0; found=1 } \
>             END { if(found) exit 1 }' android/CHANGELOG.md
> ```

The `awk` is pure magic. Would be nice if we did not have to maintain two copies of it just next to each other. Can I suggest that we instead modify the first job to be something like:

```bash
changelogs=(CHANGELOG.md android/CHANGELOG.md)
for changelog in ${changelogs[@]}; do
    awk ...
done
```

**Review by Pururun — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`.github/workflows/check-changelog.yml` line 29 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098#-Nv61GSnAwWY5IZGWPtB:-Nv66SFS54uNk1qM5x09:bhjze7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bec6b180d5da29b6c3a58fd975b8392bd85fe4da/.github/workflows/check-changelog.yml#L29)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The `awk` is pure magic. Would be nice if we did not have to maintain two copies of it just next to each other. Can I suggest that we instead modify the first job to be something like:

```bash
changelogs=(CHANGELOG.md android/CHANGELOG.md)
for changelog in ${changelogs[@]}; do
    awk ...
done
```
</blockquote></details>

Yeah, that was a bit sloppy! :laughing: I added a matrix instead to make it more transparent in in the CI results. Please have another look!

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
