### PR TITLE
Add support for custom lists

### PR DESCRIPTION
**Pull request by Pururun**
Add support for custom lists and connected actions to the android app.

THIS DOES NOT INCLUDE ANY UI CHANGES. This will come in the next PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 5 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: 5 of 32 files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: 5 of 34 files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 27 of 32 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 8 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/CustomListExtensions.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsNLzF37jwy7gAAzQ6:-NpsNLzG-90uoLqt6yKe:btc45ku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/CustomListExtensions.kt#L6)):*
> ```Kotlin
> 
> fun CustomList.toRelayItemList(relayCountries: List<RelayCountry>): CustomRelayItemList =
>     // return this.items.map { RelayItem(it) }
> ```

Old comment?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsFzYpE57eUqMJBf1H:-NpsFzYq7IqHKyT2KIuQ:b-sv4uyf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L73)):*
> ```Kotlin
> 
> fun List<RelayCountry>.findItemForGeographicLocationConstraint(
>     location: GeographicLocationConstraint
> ```

`constraint` sounds like a better variable name than location, it feels more accurate to the type. What do you think?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 233 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsN_7P-pBFnYJo2ttW:-NpsN_7P-pBFnYJo2ttX:b-61xz7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L233)):*
> ```Kotlin
>                 }
>             }
>             else -> this
> ```

Can we be explicit and enter the other alternatives?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/SelectedLocation.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsGPPr8bxwrNcTe1xA:-NpsGPPr8bxwrNcTe1xB:b-3uljf8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/SelectedLocation.kt#L8)):*
> ```Kotlin
>     val id: String,
>     val name: String,
>     val geographicLocationConstraint: GeographicLocationConstraint?
> ```

I'm a bit confused by the naming here. `SelectedLocation`, why does it need a location constraint? Is it the constraint that was used to select this location?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/CustomListsUseCase.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsGoMp0u1C7ksezqJi:-NpsGoMp0u1C7ksezqJj:btfl3jn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/CustomListsUseCase.kt#L6)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.repository.CustomListsRepository
> 
> class CustomListsUseCase(private val customListsRepository: CustomListsRepository) {
> ```

I'm not sure if this UseCase add any value, seems like it just wraps the repository, if this is the case and no other logic is needed we might as well just use the Repository right away.
___
*[`android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Event.kt` line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsLj2V2df1yzX2f_DA:-NpsLj2V2df1yzX2f_DB:b-uozlif) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Event.kt#L68)):*
> ```Kotlin
>     @Parcelize object VpnPermissionRequest : Event()
> 
>     @Parcelize data class CreateCustomListResultEvent(val result: String) : Event()
> ```

`CreateCustomListResult`work be enough, also what does `result` contain? Can we make it more clear? How do we interpret it?
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/CustomListsSettings.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsMPtL8D7AnHA31VIz:-NpsMPtL8D7AnHA31VJ-:bgpwed7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/CustomListsSettings.kt#L6)):*
> ```Kotlin
> import kotlinx.parcelize.Parcelize
> 
> @Parcelize data class CustomListsSettings(val customLists: ArrayList<CustomList>) : Parcelable
> ```

Is `ArrayList` because it is from the daemon? Would be nice if it was List otherwise.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsMovT53J441WW1nW5:-NpsMovT53J441WW1nW6:b-hrb69b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt#L10)):*
> ```Kotlin
>     val relaySettings: RelaySettings,
>     val obfuscationSettings: ObfuscationSettings,
>     val customLists: CustomListsSettings,
> ```

I guess we don't have full control of this structure since it comes from the daemon? It would make more sense otherwise if it just was:

`data class Settings(
  ...
  val customLists: List<CustomList>
  ...
)
`

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/CustomListExtensions.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsNLzF37jwy7gAAzQ6:-Npt4F-m1oZopxE_2zw5:b5a09h0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/CustomListExtensions.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Old comment?
</blockquote></details>

Probably. Fixed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsFzYpE57eUqMJBf1H:-Npt4MIr3ACD4cCEh6v0:b-3yf22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`constraint` sounds like a better variable name than location, it feels more accurate to the type. What do you think?
</blockquote></details>

Sure. Fixed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 233 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsN_7P-pBFnYJo2ttW:-Npt4qBL9YNmSr5jC9ed:bcqt000) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L233)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Can we be explicit and enter the other alternatives?
</blockquote></details>

Added null instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/SelectedLocation.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsGPPr8bxwrNcTe1xA:-Npt4yr15iSH8tBED_1L:bqib1h7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/SelectedLocation.kt#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm a bit confused by the naming here. `SelectedLocation`, why does it need a location constraint? Is it the constraint that was used to select this location?
</blockquote></details>

I think we should discuss this in person.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/CustomListsUseCase.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsGoMp0u1C7ksezqJi:-Npt5MTY9rcEJyvRDbO4:b-4m3a0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/CustomListsUseCase.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm not sure if this UseCase add any value, seems like it just wraps the repository, if this is the case and no other logic is needed we might as well just use the Repository right away.
</blockquote></details>

Yeah it was added when I thought it would be more complex. Will remove.
___
*[`android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Event.kt` line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsLj2V2df1yzX2f_DA:-Npt86eh0-5Qs0q2_CW1:b4bwo21) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Event.kt#L68)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`CreateCustomListResult`work be enough, also what does `result` contain? Can we make it more clear? How do we interpret it?
</blockquote></details>

Yeah agree it is quite redundant to add Event at the end. Will remove. Updated the val to call it `listId` as it is the value returned.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/CustomListsSettings.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsMPtL8D7AnHA31VIz:-Npt5Xf-3eIVOO1rMTe9:briwbgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/CustomListsSettings.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is `ArrayList` because it is from the daemon? Would be nice if it was List otherwise.
</blockquote></details>

Yeah daemon dependency. :/
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsMovT53J441WW1nW5:-Npt5aHl9vSPuWHDpBpF:bauk6s5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I guess we don't have full control of this structure since it comes from the daemon? It would make more sense otherwise if it just was:

`data class Settings(
  ...
  val customLists: List<CustomList>
  ...
)
`
</blockquote></details>

Yeah would just add a lot of unnecessary code to do it like that.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: 11 of 43 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/SelectedLocation.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsGPPr8bxwrNcTe1xA:-NptorWDB5QfIUpR6GLY:b-bedyju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/SelectedLocation.kt#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I think we should discuss this in person.
</blockquote></details>

Implemented what we discussed, making CustomList implement RelayItem. Please check. :)

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 293 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq1twgl232bt-MVJ5w8:-Nq1twgl232bt-MVJ5w9:b-nh3wge) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30f4c2aaf1982561fcfc156a40a215fb261e05c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L293)):*
> ```Kotlin
>                     }
>                 }
>                 else -> {}
> ```

Preferably we should be explicit here:

`RelayItem.CustomList, RelayItem.Relay -> {}`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 284 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq1uuM68EyNh5ik8vPH:-Nq1uuM68EyNh5ik8vPI:b-xqulth) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30f4c2aaf1982561fcfc156a40a215fb261e05c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L284)):*
> ```Kotlin
>                 is RelayItem.City -> relayListState.selectedItem.location.countryCode
>                 is RelayItem.Relay -> relayListState.selectedItem.location.countryCode
>                 else -> null
> ```

Same here, lets avoid `else`. 

We could also make it an extension function or property:

```
fun RelayListState.RelayList.indexOfSelectedRelayItem(): Int {
    if(selectedItem == null) {
        return -1
    }
    countries.indexOfFirst { relayCountry ->
        relayCountry.location.location.country ==
            when (relayListState.selectedItem) {
                is RelayItem.CustomList -> null
                is RelayItem.Country -> relayListState.selectedItem.code
                is RelayItem.City -> relayListState.selectedItem.location.countryCode
                is RelayItem.Relay -> relayListState.selectedItem.location.countryCode
                null -> null
    }
}
   ```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItem.kt` line 79 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq1wYvFEOjU8_yAzrKo:-Nq1wYvFEOjU8_yAzrKp:bqj0b0d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30f4c2aaf1982561fcfc156a40a215fb261e05c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItem.kt#L79)):*
> ```Kotlin
>         }
>     }
> }
> ```

Looks really good! Nice work! :clap: I'm a little bit against having `expanded` here but since it does not introduce it as a new concept I think we can consider that in another PR. 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq1wrs77IY85m1YF2pA:-Nq1wrs77IY85m1YF2pB:b-3aclb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30f4c2aaf1982561fcfc156a40a215fb261e05c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt#L12)):*
> ```Kotlin
>         is RelayItem.CustomList -> LocationConstraint.CustomList(id)
>     }
> }
> ```

Nice :star_struck: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt` line 233 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsN_7P-pBFnYJo2ttW:-Nq1x49i5f3adnnovSpW:bcv502w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt#L233)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added null instead.
</blockquote></details>

Nice :+1: 
___
*[`android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Event.kt` line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-NpsLj2V2df1yzX2f_DA:-Nq1xOmCBrJg6u3m3rSy:bn5yapm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e48c9d9cafe16265f8485f37deefa1f457400115/android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Event.kt#L68)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yeah agree it is quite redundant to add Event at the end. Will remove. Updated the val to call it `listId` as it is the value returned.
</blockquote></details>

Great :+1: much more clear!

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 293 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq1twgl232bt-MVJ5w8:-Nq2UGKeExXFbMDE_KGx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30f4c2aaf1982561fcfc156a40a215fb261e05c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L293)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Preferably we should be explicit here:

`RelayItem.CustomList, RelayItem.Relay -> {}`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 284 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq1uuM68EyNh5ik8vPH:-Nq2VH-D3xiO7kvu16r5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30f4c2aaf1982561fcfc156a40a215fb261e05c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L284)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same here, lets avoid `else`. 

We could also make it an extension function or property:

```
fun RelayListState.RelayList.indexOfSelectedRelayItem(): Int {
    if(selectedItem == null) {
        return -1
    }
    countries.indexOfFirst { relayCountry ->
        relayCountry.location.location.country ==
            when (relayListState.selectedItem) {
                is RelayItem.CustomList -> null
                is RelayItem.Country -> relayListState.selectedItem.code
                is RelayItem.City -> relayListState.selectedItem.location.countryCode
                is RelayItem.Relay -> relayListState.selectedItem.location.countryCode
                null -> null
    }
}
   ```
</blockquote></details>

Done.

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 281 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq3-IEl8gb0R6n-bpFR:-Nq3-IEl8gb0R6n-bpFS:b-vb45as) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e39e458ef19a20e08a8f0efa3190993f98128cce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L281)):*
> ```Kotlin
> }
> 
> private fun RelayListState.RelayList.indexOfSelectedRelayItem(selectedItem: RelayItem?): Int =
> ```

Nitpicking, `indexOfRelayItem(item: RelayItem?)` selection really has nothing to do with it at this level. Soooorrrii :dagger:

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 281 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq3-IEl8gb0R6n-bpFR:-Nq3-nU59gcfGGFILQjP:bae1eby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e39e458ef19a20e08a8f0efa3190993f98128cce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L281)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nitpicking, `indexOfRelayItem(item: RelayItem?)` selection really has nothing to do with it at this level. Soooorrrii :dagger:
</blockquote></details>

or rather just `indexOf()` relayItem is sort of already described in argument

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 281 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq3-IEl8gb0R6n-bpFR:-Nq311bR6_UC5ETDWIya:b6k6uys) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e39e458ef19a20e08a8f0efa3190993f98128cce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L281)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

or rather just `indexOf()` relayItem is sort of already described in argument
</blockquote></details>

Clarification, we can remove `selectedItem` since it already exists in `RelayList`

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: 42 of 43 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 281 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737#-Nq3-IEl8gb0R6n-bpFR:-Nq4iDBD2hi6D3FWeNAO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e39e458ef19a20e08a8f0efa3190993f98128cce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L281)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Clarification, we can remove `selectedItem` since it already exists in `RelayList`
</blockquote></details>

Done.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5737)* status: 42 of 43 files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Pull request merged**
