### PR TITLE
Force the right color profile to be used

### PR DESCRIPTION
**Pull request by dlon**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`gui/src/main/index.ts` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631#-N3ZFu678abRIZHwaP1s:-N3ZFu678abRIZHwaP1t:b-m7vti4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/415fa09204c818dbf65d8a53631c5900124eab8d/gui/src/main/index.ts#L273)):*
> ```XML
>   public run() {
>     // Remove window animations to combat window flickering when opening window. Can be removed when
>     // this issue has been resolved: https://github.com/electron/electron/issues/12130
> ```

It looks like this comment applies to both `app.commandLine.appendSwitch` statements now. Please move this around so it's apparent what code is for what workaround.
___
*[`gui/src/main/index.ts` line 276 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631#-N3ZFaIl7ZqnJiVeSjVC:-N3ZFaIl7ZqnJiVeSjVD:bgp9f0n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/415fa09204c818dbf65d8a53631c5900124eab8d/gui/src/main/index.ts#L276)):*
> ```XML
>     if (process.platform === 'win32') {
>       app.commandLine.appendSwitch('wm-window-animations-disabled');
>       app.commandLine.appendSwitch('force-color-profile', 'srgb');
> ```

Since this is a workaround it's not obvious from the code itself why it's here or needed. Please add a comment explaining that it makes the colors display correctly on machines with strange color profiles on their monitors.

Also add a changelog entry.

**Review by pronebird — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

___
*[`gui/src/main/index.ts` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631#-N3ZFu678abRIZHwaP1s:-N3_WJGB9BYIBYT8Ehzi:bngtnqr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/415fa09204c818dbf65d8a53631c5900124eab8d/gui/src/main/index.ts#L273)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It looks like this comment applies to both `app.commandLine.appendSwitch` statements now. Please move this around so it's apparent what code is for what workaround.
</blockquote></details>

I made it independent of OS. I don't see why we would want to force this only on Windows, assuming it's a good idea at all.
___
*[`gui/src/main/index.ts` line 276 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631#-N3ZFaIl7ZqnJiVeSjVC:-N3_WJ8jAnoMtZDcOJ7n:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/415fa09204c818dbf65d8a53631c5900124eab8d/gui/src/main/index.ts#L276)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since this is a workaround it's not obvious from the code itself why it's here or needed. Please add a comment explaining that it makes the colors display correctly on machines with strange color profiles on their monitors.

Also add a changelog entry.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @pronebird)

___
*[`gui/src/main/index.ts` line 273 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631#-N3ZFu678abRIZHwaP1s:-N3cQdBn0GUc4z4Jc_eo:b-5h6qpg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/415fa09204c818dbf65d8a53631c5900124eab8d/gui/src/main/index.ts#L273)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I made it independent of OS. I don't see why we would want to force this only on Windows, assuming it's a good idea at all.
</blockquote></details>

Sounds good to me. In at least [one instance](https://github.com/electron/electron/issues/10732#issuecomment-390658490) this has been an issue for someone on Linux, and the same flag fixed it, so why not.

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631#-:-N3cTTLrArewakLwJ_-m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
