### PR TITLE
Update compose to 1.7.0-beta3

### PR DESCRIPTION
**Pull request by Pururun**
Also updates the following plugins and libraries:

`kotlinCompilerExtensionVersion` -> 1.5.14
`appcompat` -> 1.7.0
`compose-material3` -> 1.3.0-beta03
`kotlin` -> 1.9.24
`ksp` -> 1.0.20
`grpc` -> 1.64.0

This is to fix the app crashing on release builds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6393)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6393#-:-O-q2Q4Z979SPMmqNup5:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6393)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6393#-:-O0DrGE12ZfDlVyCJEpg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
