### PR TITLE
Add command line switch for force display of changes dialog

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds a command line switch (`--show-changes`) that shows the changes dialog on start.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/Changelog.tsx` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592#-N2HA5Kn1fEr-H8M5Chk:-N2HA5Ko1WTNhn3ovHSJ:bq09gi6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5ab6e2898f0212109386edee9bb627001e23f817/gui/src/renderer/components/Changelog.tsx#L41)):*
> ```XML
> 
>   const visible =
>     forceShowChanges ||
> ```

Probably need to reset `forceShowChanges` after dismissing the modal?

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`gui/src/renderer/components/Changelog.tsx` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592#-N2HA5Kn1fEr-H8M5Chk:-N2HChzP2T6MNOhuSCGo:b-2vpwzj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5ab6e2898f0212109386edee9bb627001e23f817/gui/src/renderer/components/Changelog.tsx#L41)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably need to reset `forceShowChanges` after dismissing the modal?
</blockquote></details>

The primary use case for this is to make it possible to preview the dialog before building a release and for that purpose it's not necessary to dismiss it. We opted for this solution to make it as simple as possible.

**Review by pronebird — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`gui/src/renderer/components/Changelog.tsx` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592#-N2R9h007OoMPyw2yESb:-N2R9h007OoMPyw2yESc:bn8fpi2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7ef0929dc76fe858a33be7945c87e27af8e5e1e/gui/src/renderer/components/Changelog.tsx#L42)):*
> ```XML
>   const { setDisplayedChangelog } = useAppContext();
> 
>   const [forceShowChanges, , stopForceShowChanges] = useBoolean(initialForceShowChanges);
> ```

Double comma, `, , stopForceShowChanges`

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
