### PR TITLE
Fix app installation location on macOS

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

This PR updates `electron-builder` to the latest and disables the existing app installation lookup, instead sticks to the fixed installation location in `/Applications/Mullvad VPN.app`

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239)

### CODE REVIEW

**Comment by faern** [comment]
I have not tested it on the macbook yet. But the change looks nice!

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239#-:-LFs8O9d9Z67ZctW4ae8:b-krvbeh)*

**Comment by pronebird** [comment]
Is it a green light to merge this or you just share you feeling about it? :thinking: 

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239#-:-LFsCc7RCOdg3hQ1x7No:b-h0h7ka)*

**Comment by pronebird** [comment]
/you/your/

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239#-:-LFsCir89Nje-AN0Oaes:bb2dwiq)*

**Comment by faern** [comment]
If you have tested it locally and it seems to work, then merge! And I'll build an internal release from master tomorrow and give out to some people! :lgtm: 

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239#-:-LFsD-KqCnqyWSVhw9sY:b5ith3s)*

**Comment by pronebird** [comment]
I tested it when I worked on the original PR for electron-builder but I'd double check. :)

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239#-:-LFsDHIO7SdbiOEKKX0F:bdxsnxe)*

**Comment by pronebird** [comment]
Double checked - works like a charm! :tada: 

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/239#-:-LFsL-lu4ne9uyLHM9s5:b-v19nko)*

**Pull request merged**
