### PR TITLE
Add android themed icon

### LINKED ISSUE #3935: [Feature Request] Add themed icon support for Android 13
## Issue report

Operating system: Android 13

App version: 2022.1

### Issue description

Add support for Android 13's Material You themed icons. This would require reusing the monochrome icon already being used in the notification tray for an adaptive icon. Here is some more information about Adaptive Icons.

[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR adds a themed icon to the android app.

See documentation regarding themed icons here:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

Moved sdk bump to: #3956
Closes #3935

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3952)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3952)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by sabercodic** [comment]
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3952#-NCdOZLX75tMWPcBbDYX:-NCdOZLX75tMWPcBbDYY:bxczy2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a1263696ec9400cd4dc86ab07c1d28325f0b6b8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L17)):*
> ```Kotlin
>     }
> 
>     fun VpnService.Builder.setMeteredIfSupported(isMetered: Boolean) {
> ```

I suggest define extension methods outside of the object scope, it can be in same file

**Review by sabercodic — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 2 of 2 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3952)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3952)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3952#-NCdOZLX75tMWPcBbDYX:-NCtYeh1ExowDRoEjfp1:b9wqy0i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a1263696ec9400cd4dc86ab07c1d28325f0b6b8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L17)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

I suggest define extension methods outside of the object scope, it can be in same file
</blockquote></details>

This was moved to another PR and has been resolved :slightly_smiling_face:

**Pull request merged**
