### PR TITLE
Increase the touch target for the cross button in the banner view

### PR DESCRIPTION
**Pull request by mojganii**
Increase the touch target with margin

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVZEyFW3xmR3QyjCzJh:b-oc4bo0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
> ```Swift
> import UIKit
> 
> final class IncreasedMarginTapAreaButton: UIButton {
> ```

We already have `HeaderBarButton` doing the same thing, although not with a customisable margin. Perhaps we could consolidate that class and this new one to something generalised. Since 44 is usually the desired touch area size, we could let the class decide the extra margin by itself. Eg.:



_Code snippet:_
```Swift
let x = max(44 - frame.width, 0) * 0.5
let y = max(44 - frame.height, 0) * 0.5

return bounds.insetBy(dx: -x, dy: -y).contains(point)
```

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVZId78CfjcpyI0KfBc:buzi1s4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We already have `HeaderBarButton` doing the same thing, although not with a customisable margin. Perhaps we could consolidate that class and this new one to something generalised. Since 44 is usually the desired touch area size, we could let the class decide the extra margin by itself. Eg.:
</blockquote></details>

I think it's not good idea to make the class depend on 44.but we can remove margin property and take the hit-able size and then calculate this with formula.what do you think?

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVZQpx10ydksswWpKCN:b-a0yv17) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think it's not good idea to make the class depend on 44.but we can remove margin property and take the hit-able size and then calculate this with formula.what do you think?
</blockquote></details>

Not sure I follow. Can you provide an example?

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVZcqoA2TuxRCIucKT0:b-m0rvt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not sure I follow. Can you provide an example?
</blockquote></details>

```
final class IncreasedMarginTapAreaButton: UIButton {
    var tapAreaSize: CGSize = .zero

    init(tapAreaSize: CGSize) {
        super.init(frame: .zero)
        self.tapAreaSize = tapAreaSize
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
        self.tapAreaSize = .zero
    }

    override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        let frameSize = bounds.size
        let dx = max(tapAreaSize.width - bounds.width,0) * 0.5
        let dy = max(tapAreaSize.height - bounds.height,0) * 0.5
        return bounds.insetBy(dx: -dx, dy: -dy).contains(point)
    }
}

```

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVZeFB52kBH-1gtc8Ns:bzhn6a5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

```
final class IncreasedMarginTapAreaButton: UIButton {
    var tapAreaSize: CGSize = .zero

    init(tapAreaSize: CGSize) {
        super.init(frame: .zero)
        self.tapAreaSize = tapAreaSize
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
        self.tapAreaSize = .zero
    }

    override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        let frameSize = bounds.size
        let dx = max(tapAreaSize.width - bounds.width,0) * 0.5
        let dy = max(tapAreaSize.height - bounds.height,0) * 0.5
        return bounds.insetBy(dx: -dx, dy: -dy).contains(point)
    }
}

```
</blockquote></details>

Ah, sorry, got it. This does force us to specify a tappable area size though, which may be cumbersome if the button is already larger than eg. 44. I think we should at least have a default value if we go this route.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 711 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZnOcG9AtUOAVq4vKe:-NVZnOcG9AtUOAVq4vKf:b-stbzhr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L711)):*
> ```Swift
>         switch deviceState {
>         case let .loggedIn(accountData, _):
>             let showsDeviceInfo = previousDeviceState != .loggedOut
> ```

Not sure why you had to close the PR from before, instead of continuing to work in it.  

I have to leave the same comment twice now.

The following transition is possible if account data is being updated:

`loggedOut` -> `loggedIn` -> `loggedIn`

In that case this heuristics will fail and show the device info before user clicked on (x) close button in notification.
___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVZl_M3CO1XhLvXcpNS:b6e43yz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Ah, sorry, got it. This does force us to specify a tappable area size though, which may be cumbersome if the button is already larger than eg. 44. I think we should at least have a default value if we go this route.
</blockquote></details>

`tapAreaSize` will always be `(44, 44)` and I don't see it changing to anything else unless Apple change guidelines in which case we'll change the constant.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 711 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZnOcG9AtUOAVq4vKe:-NVcVqk_7qQXUqoa0miJ:b44akk6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L711)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not sure why you had to close the PR from before, instead of continuing to work in it.  

I have to leave the same comment twice now.

The following transition is possible if account data is being updated:

`loggedOut` -> `loggedIn` -> `loggedIn`

In that case this heuristics will fail and show the device info before user clicked on (x) close button in notification.
</blockquote></details>

I don't think so it's a good idea to make a function for showing device name.it doesn't have any value added while it's working. but If you think it's necessary I'll do it.
regarding PR,I multiple tried to push my code and I did it but it didn't get updated.sometimes it happens some softwares have a bug.there is some programmer like us behind them 🙃
___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVcVo39D1RrNy_BI0rQ:b-ynqdsu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`tapAreaSize` will always be `(44, 44)` and I don't see it changing to anything else unless Apple change guidelines in which case we'll change the constant.
</blockquote></details>

do you mean we use this class just for `44x44`? like this?

```
 override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        let frameSize = bounds.size
        let dx = max(44 - bounds.width,0) * 0.5
        let dy = max(44 - bounds.height,0) * 0.5
        return bounds.insetBy(dx: -dx, dy: -dy).contains(point)
    }
```

**Review by pronebird — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 711 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZnOcG9AtUOAVq4vKe:-NVd5jsXCHQ9hDeN9fir:b-kfs1ob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L711)):*
> I don't think so it's a good idea to make a function for showing device name.it doesn't have any value added while it's working. but If you think it's necessary I'll do it.

I've created a separate card to better describe what I think should be done and keep this PR focused on other changes.

> regarding PR,I multiple tried to push my code and I did it but it didn't get updated.sometimes it happens some softwares have a bug.there is some programmer like us behind them 🙃

I see.
___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVZEyFW3xmR3QyjCzJg:-NVd0Ei92Kb1TyhLshWf:b-5gg9mb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do you mean we use this class just for `44x44`? like this?

```
 override func point(inside point: CGPoint, with event: UIEvent?) -> Bool {
        let frameSize = bounds.size
        let dx = max(44 - bounds.width,0) * 0.5
        let dy = max(44 - bounds.height,0) * 0.5
        return bounds.insetBy(dx: -dx, dy: -dy).contains(point)
    }
```
</blockquote></details>

Exactly. I think that based on guidelines the touch area should be at least 44x44 large for finger to comfortably hit it. Can be larger if the button itself is larger. So we could simply ensure that at least 44x44 is available and if it is larger than it's ok. Our use case is that the buttons are as small as 16x16 or 18x18 and it's hard to tap them.

In regards of naming things, I'd suggest to avoid using "margin" as it may be confused with layout margins and instead focus on other three keywords: extended touch area. Or something akin to this.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVe0Sxj-adOg8fVEmnF:-NVe0Sxj-adOg8fVEmnG:bwnyrg4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
> ```Swift
> import UIKit
> 
> final class IncreasedMarginTapAreaButton: UIButton {
> ```

`HeaderBarButton` can be replaced in favor of your custom type since we basically override point(inside) in there in order to produce large enough touch area (i.e 44x44)

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVe0Sxj-adOg8fVEmnF:-NVe0wIe3JbRi6fojfPU:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/692d128c7c36c2052db98f5f56a0e93d723ceb7d/ios/MullvadVPN/Views/IncreasedMarginTapAreaButton.swift#L11)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`HeaderBarButton` can be replaced in favor of your custom type since we basically override point(inside) in there in order to produce large enough touch area (i.e 44x44)
</blockquote></details>

+1

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Views/IncreasedTapAreaButton.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVmdOID3icWzmkYyCha:-NVmdOID3icWzmkYyChb:b-tqh5dp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa99b13b6d2c7111976fb554c59c9fa7afb85344/ios/MullvadVPN/Views/IncreasedTapAreaButton.swift#L11)):*
> ```Swift
> import UIKit
> 
> final class SquareHitButton: UIButton {
> ```

The name is mismatching the file name, let's make sure they're in sync

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Views/IncreasedTapAreaButton.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVmdOID3icWzmkYyCha:-NVnWkiy-qzQ4rEKii-8:b-7ci3sj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa99b13b6d2c7111976fb554c59c9fa7afb85344/ios/MullvadVPN/Views/IncreasedTapAreaButton.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The name is mismatching the file name, let's make sure they're in sync
</blockquote></details>

+1
Also, I actually prefer the orignal name, or something similar like `Increased/ExtendedTapAreaButton`.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Views/IncreasedTapAreaButton.swift` line 11 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NVmdOID3icWzmkYyCha:-NW1W-CX0jNCiHRK_SJj:b4l0q1m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa99b13b6d2c7111976fb554c59c9fa7afb85344/ios/MullvadVPN/Views/IncreasedTapAreaButton.swift#L11)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

+1
Also, I actually prefer the orignal name, or something similar like `Increased/ExtendedTapAreaButton`.
</blockquote></details>

Agree with both of you.
___
*[`ios/MullvadVPN/Views/IncreasedTapAreaButton.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NW1UuF-2pu7eJ2Bn12V:-NW1UuF-2pu7eJ2Bn12W:b-6l0e2e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa99b13b6d2c7111976fb554c59c9fa7afb85344/ios/MullvadVPN/Views/IncreasedTapAreaButton.swift#L18)):*
> ```Swift
>         let maxWidth = max(defaultSize, width)
>         let margin = (maxWidth - width) * 0.5
>         return bounds.insetBy(dx: -margin, dy: -margin).contains(point)
> ```

`dy` is derived from `dx` which makes assumption that the button is square. Instead we should perhaps calculate `dy` separate as in your original example which should make this subclass a bit more flexible in regards of whether the graphics inside of it is rectangular or ideal square.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Views/IncreasedTapAreaButton.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693#-NW1UuF-2pu7eJ2Bn12V:-NW1wAM55I8ftF4O-w4T:bbj5x19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa99b13b6d2c7111976fb554c59c9fa7afb85344/ios/MullvadVPN/Views/IncreasedTapAreaButton.swift#L18)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do you mean consider the calculation of dx & dy separately?
</blockquote></details>

Yeah I think so. If the image inside is rectangular than we might accidentally increase the hit area even more, i.e if the button is 22pt long but 44pt tall then the vertical touch area would be about `44 + 22`.

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 6 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by rablador — COMMENTED** [review]
> Reviewed 3 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4693)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
