### PR TITLE
Fix DeadObjectException on connecting to the relay

### PR DESCRIPTION
**Pull request by sabercodic**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
I suggest splitting this one into three separate commits, one for each file.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-:-NHURhwp2IuGFsmbhd85:bnxjjd9)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 91 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NHUQsVyDBYVkni_yNCm:-NHUQsVyDBYVkni_yNCn:bxa0zzo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6997e5d0db120e4f3912f0a1ce232abdc4392639/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L91)):*
> ```Kotlin
>     }
> 
>     @Synchronized
> ```

Is this part of fixing the crash? Otherwise I suggest skipping it as it makes it harder to review and understand the actual bugfixes. Same applies for other occurrances in this commit.



_Code quote:_
```Kotlin
Synchronized
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NHUS_Io2IbyaBY-fwy1:-NHUS_Io2IbyaBY-fwy2:bvqi0tl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6997e5d0db120e4f3912f0a1ce232abdc4392639/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt#L41)):*
> ```Kotlin
>                 connection.send(Request.Connect.message)
>             } catch (ex: DeadObjectException) {
>                 // inform main controller to recreate connection thread
> ```

Regarding this and other identical comments, can it be handled using the `ServiceConnection` callbacks? Also, would be good to add logs saying something like:
```
Log.e("mullvad", "Unable to send message over dead service connection")
```



_Code quote:_
```Kotlin
// inform main controller to recreate connection thread
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 3 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqBXJL6ESspgu41ZAD):*
I suggest changing to: `Fix crash on initial messenger events`



_Code quote:_
```
Fix crash on send initial events to Daemon service listener
```
___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqBdMHEYioWq3k9xsN):*
I suggest changing to: `Fix crash on device messenger communication`



_Code quote:_
```
using user apis through Daemon
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqC4Rz6hSS8uBHmDBQ:-NIqBrm33yMmzKy5aaw8:bqcmoal) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1decce7d81fc3657a9264b107635ac2a4de0c45c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L97)):*
> ```Kotlin
>             for ((id, listener) in listeners) {
>                 if (!trySendEventToListener(event.message, listener)) {
>                     listeners.remove(id)
> ```

Was there an issue with the way the collection were handled previously? Doesn't seem very safe to modify the collection while iterating over it.



_Code quote:_
```Kotlin
listeners.remove(id)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 153 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqFL3BEbygq6WFVHMj:-NIqFL3BEbygq6WFVHMk:b-2rmp4k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1decce7d81fc3657a9264b107635ac2a4de0c45c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L153)):*
> ```Kotlin
>             if (isSendEventsFailed) {
>                 listeners.remove(listenerId)
>             }
> ```

Can `any` be used here to simplify things?

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/any.html



_Code quote:_
```Kotlin
            var isSendEventsFailed = false
            initialEvents.forEach { event ->
                isSendEventsFailed =
                    isSendEventsFailed or !trySendEventToListener(event.message, listener)
            }
            if (isSendEventsFailed) {
                listeners.remove(listenerId)
            }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NHUS_Io2IbyaBY-fwy1:-NIq96uC5JvoOtHgedFt:b7te3y2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6997e5d0db120e4f3912f0a1ce232abdc4392639/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt#L41)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

is it ok create extension function 'Messenger.trySend' to use instead of 'Messenger.send' for Messenger class?
</blockquote></details>

Sounds like a good idea given the current implementation. Perhaps with the following signature to automatically log any errors? In that case I think it shouldn't have a default value as it should be clear to any function callers.

`fun Messenger.trySend(message: Message, logErrors: Boolean): Boolean`

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqC4Rz6hSS8uBHmDBQ:-NJ5tbUd5gI3v4LFzJK6:bq4hyfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1decce7d81fc3657a9264b107635ac2a4de0c45c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L97)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My original comment still applies here. Was there a problem with how `deadListeners` were collected and later removed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 153 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqFL3BEbygq6WFVHMj:-NJ5rzky-uSuMqNDqUDm:b-nbmdei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1decce7d81fc3657a9264b107635ac2a4de0c45c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L153)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I suggest changing to `all` instead of `any` that I previously suggest. Also, storing the result in a variable (`val`) will probably improve readability.

Something like:
```
val didSuccessfullySendAllMessages = initialEvents.all { /* */ }

if (didSuccessfullySendAllMessages.not()) {
  listeners.remove(listenerId)
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 178 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5sf2e1w7UDkbpRtTR:-NJ5sf2e1w7UDkbpRtTS:b-b98cmb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L178)):*
> ```Kotlin
>     }
> 
>     private fun trySendEventToListener(
> ```

This can be removed now, right?



_Code quote:_
```Kotlin
private fun trySendEventToListener(
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5qmNHDoa89FaL8hxK:-NJ5qmNHDoa89FaL8hxL:b-nwrlbs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt#L12)):*
> ```Kotlin
>         this.send(message)
>         true
>     } catch (ex: DeadObjectException) {
> ```

Should perhaps also catch `RemoteException`



_Code quote:_
```Kotlin
ex: DeadObjectException
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5qZAf-r6VY-XA0xv8:-NJ5qZAgE9biQKkxsRTD:b-eyhfee) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt#L14)):*
> ```Kotlin
>     } catch (ex: DeadObjectException) {
>         if (logErrors) {
>             Log.e("Mullvad", ex.toString())
> ```

Change to lowercase `m`



_Code quote:_
```Kotlin
M
```

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5qZAf-r6VY-XA0xv8:-NJ6EWQL0Dk7Efdru-Wf:b2tvbgh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt#L14)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to lowercase `m`
</blockquote></details>

Also, we should probably not log the exception itself here. It's probably better to log something like:

```
Log.e("mullvad", "Unable to to send message: message::class.simpleName")
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqC4Rz6hSS8uBHmDBQ:-NJ9c77T1d_gxImqvsuL:bx9p5ng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1decce7d81fc3657a9264b107635ac2a4de0c45c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L97)):*
> listeners.remove(id)
just tried to reduce variables, reverted to old model.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 153 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NIqFL3BEbygq6WFVHMj:-NJ9bJpr9fX6E6DyO7g-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1decce7d81fc3657a9264b107635ac2a4de0c45c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L153)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing to `all` instead of `any` that I previously suggest. Also, storing the result in a variable (`val`) will probably improve readability.

Something like:
```
val didSuccessfullySendAllMessages = initialEvents.all { /* */ }

if (didSuccessfullySendAllMessages.not()) {
  listeners.remove(listenerId)
}
```

</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt` line 178 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5sf2e1w7UDkbpRtTR:-NJ9_zlO9AGMepnPOooW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt#L178)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This can be removed now, right?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5qmNHDoa89FaL8hxK:-NJ9_beH4tO5RQuvJxFy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt#L12)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should perhaps also catch `RemoteException`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5qZAf-r6VY-XA0xv8:-NJ9_c2_9hueIx5Jac7W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt#L14)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Also, we should probably not log the exception itself here. It's probably better to log something like:

```
Log.e("mullvad", "Unable to to send message: message::class.simpleName")
``` 
</blockquote></details>

Done.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158#-NJ5qZAf-r6VY-XA0xv8:-NJ9rSBkCoUSV-IgrkqM:b-q5tlii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d81776c86c0fb4962d790c9e80ac616e9cbdb5fd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt#L14)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The log message comment has not been addressed. As an improvement to my last comment, I also suggest making the extension function `Event` specific, as it can improve the logging (if using `simpleName` as suggested).

```
fun Messenger.trySendEvent(event: Event, logErrors: Boolean): Boolean
```

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
