### PR TITLE
Migrate login screen to compose

### PR DESCRIPTION
**Pull request by Rawa**
Convert login screen to compose

Also fixes theme colors, adds AccountToken to Model and account visual transformation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: all files reviewed, 8 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 115 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NeliUTP2PmBvaUYAtiV:-NeliUTQ68Oc98TuQZgw:b29n3w5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L115)):*
> ```Kotlin
>         val scrollState = rememberScrollState()
> 
>         Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
> ```

Just curious, why was this changed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NelinzdBPNp4XI-GvHP:-NelinzdBPNp4XI-GvHQ:b4hbkbd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L101)):*
> ```Kotlin
>         statusBarColor = MaterialTheme.colorScheme.primary,
>         navigationBarColor = MaterialTheme.colorScheme.background,
>         iconTintColor = MaterialTheme.colorScheme.onPrimary.copy(alpha = AlphaTopBar),
> ```

Should we user overlay here as you proposed somewhere else?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NeljIHI3JnfOnuE5Xj5:-NeljIHI3JnfOnuE5Xj6:bguhipf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L105)):*
> ```Kotlin
>         onAccountClicked = null
>     ) {
>         Column(modifier = Modifier.fillMaxSize().background(MaterialTheme.colorScheme.primary)) {
> ```

Have you tested this on very small screens, the xml file had a scrollview and since this is not scrollable, it might break?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/LoginFragment.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NelkFnt5rddgkBW-Ihf:-NelkFnu2nQr8m29zFbC:bseobl4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/LoginFragment.kt#L45)):*
> ```Kotlin
>                 AppTheme {
>                     val loginUiState by vm.uiState.collectAsState()
>                     LaunchedEffect(Unit) {
> ```

I don't think we have decided on a standard in regards to actions, but fwiw how it has been done in other screens is that the collect is inside the screen and are referred to as view actions and not side effects, which I guess might be confusing since it's the same name as the function in compose.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-Nell13LEwoyTf51JC5j:-Nell13LEwoyTf51JC5k:b-jrunlj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt#L30)):*
> ```Kotlin
> private const val MINIMUM_LOADING_SPINNER_TIME_MILLIS = 500L
> 
> sealed interface LoginSideEffect {
> ```

Just a personal preference but I don't think this should be in the ViewModel file but its own separate file.
Also see previous comment in regards to naming.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NellumwBi18IAsPGeBH:-NellumwBi18IAsPGeBI:bt27vak) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L54)):*
> ```Kotlin
>     @Test
>     fun testDefaultState() =
>         runTest(UnconfinedTestDispatcher()) {
> ```

I think if you set `@get:Rule val testCoroutineRule \= TestCoroutineRule()` at the top of the test class you don't need to specify `UnconfinedTestDispatcher()` for every test.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NellUCA1TWaoWicr3cH:-NellUCA1TWaoWicr3cI:b9vwpum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L60)):*
> ```Kotlin
>     @Test
>     fun testCreateAccount() =
>         runTest(UnconfinedTestDispatcher()) {
> ```

Now this was not in the previous file, but it would be nice to split it up in steps of "Arrange", "Act" and "Assert". See other view model test files for an example.
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-Nelm_F04Wb4GrYnXFl5:-Nelm_F04Wb4GrYnXFl6:bf3bfrg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72419399e916783862aad86749214b596509cc02/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L27)):*
> ```Kotlin
>         headlineSmall =
>             TextStyle(
>                 color = MullvadWhite,
> ```

Really nice that you removed the colors here.
I did that in some other more experimental PR and as far as I remember this hade some unintended side effects in VpnSettingsScreen or somewhere. Have you checked for this?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: all files reviewed, 8 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-Nell13LEwoyTf51JC5j:-NeltYB0C34SqTaDsAhr:bl11ojl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt#L30)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Just a personal preference but I don't think this should be in the ViewModel file but its own separate file.
Also see previous comment in regards to naming.
</blockquote></details>

My mistake, actions were inside the view model file in other cases so ignore that.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NellUCA1TWaoWicr3cH:-NenFeHC2H8xeEZmMKF3:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt#L60)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess it could be clarified even more with comments like `// Arrange` but not super important.
</blockquote></details>

Fixed
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-Nelm_F04Wb4GrYnXFl5:-NenFgI1Dz801ibHVMZg:bl2gkm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72419399e916783862aad86749214b596509cc02/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L27)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Just a reminder to fix the issues we discovered in the design meeting.
</blockquote></details>

Fixed the ones we saw, settings and split tunneling :+1: https://github.com/mullvad/mullvadvpn-app/pull/5164/commits/c4a6e91f8685477a1ca300ae934e6436f3dbb94a#diff-783f2fb929c3c90fc8a4580133499504be9229defc67d9de43127b60110de78b

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-:-NeqwHXg8jOhk4YChQB5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-Nelm_F04Wb4GrYnXFl5:-NeqwEHy8s7H9dYK5sO5:bb70w76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72419399e916783862aad86749214b596509cc02/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt#L27)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Fixed the ones we saw, settings and split tunneling :+1: https://github.com/mullvad/mullvadvpn-app/pull/5164/commits/c4a6e91f8685477a1ca300ae934e6436f3dbb94a#diff-783f2fb929c3c90fc8a4580133499504be9229defc67d9de43127b60110de78b
</blockquote></details>

Nice

**Review by sabercodic — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: all files reviewed, 4 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 165 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesBGeD2y_7bvSqfyZi:-NesBGeD2y_7bvSqfyZj:b6jxeho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L165)):*
> ```Kotlin
>                                 top = Dimens.mediumPadding
>                             )
>                             .size(Dimens.progressIndicatorSize)
> ```

Is it related to this task? it is better to do it in different PR if it is unrelated
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 96 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesF2seARjUvX99LJoG:-NesF2seARjUvX99LJoH:b-154urb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L96)):*
> ```Kotlin
>     onDeleteHistoryClick: () -> Unit = {},
>     onAccountNumberChange: (String) -> Unit = {},
>     onSettingsClick: () -> Unit = {},
> ```

App crashes when I click on Settings (if you click on text field and then click on settings)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 148 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesFl6j5Hv6D90Qldyk:-NesFl6j5Hv6D90Qldyl:bjquptk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L148)):*
> ```Kotlin
>                             modifier =
>                                 Modifier.size(Dimens.progressIndicatorSize)
>                                     .testTag(CIRCULAR_PROGRESS_INDICATOR),
> ```

same as before
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/AccountTokenVisualTransformation.kt` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesI_er40gCU_dyY_V5:-NesI_er40gCU_dyY_V6:bo6m9v4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/AccountTokenVisualTransformation.kt#L20)):*
> ```Kotlin
>         object : OffsetMapping {
>             override fun originalToTransformed(offset: Int): Int =
>                 offset + (offset - 1) / ACCOUNT_TOKEN_CHUNK_SIZE
> ```

this will prevent user from change cursor to the end of input after adding 2 space(10 character)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: 20 of 27 files reviewed, 4 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 96 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesF2seARjUvX99LJoG:-NewGQnJ2ve9HzOtL2Rg:b-t9vqd4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L96)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

App crashes when I click on Settings (if you click on text field and then click on settings)
</blockquote></details>

Fixed with menuAchor being conditionally added! :pray: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/AccountTokenVisualTransformation.kt` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesI_er40gCU_dyY_V5:-NevsaNX5_hV1LUTThIG:b-kkqlyk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/AccountTokenVisualTransformation.kt#L20)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

this will prevent user from change cursor to the end of input after adding 2 space(10 character)
</blockquote></details>

Good catch! Should be working now :)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 165 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesBGeD2y_7bvSqfyZi:-NevhxaoAZ3AfxOmFjqS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L165)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Is it related to this task? it is better to do it in different PR if it is unrelated
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt` line 148 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NesFl6j5Hv6D90Qldyk:-Nevi36QCn3I_2cgrKsp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a217c7cca8b3ef75da83ba71f7e7776c0ea3979e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt#L148)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done.

**Review by sabercodic — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: 24 of 27 files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 260 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NfAt9ZD9iB384Gv7b70:-NfAt9ZD9iB384Gv7b71:btk0jz2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d18d0bb2ce5231265b48862b60d1b0b5a9aa13a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L260)):*
> ```Kotlin
>                     Image(
>                         painter = painterResource(id = R.drawable.icon_fail),
>                         contentDescription = null,
> ```

It is better to add content description for icons
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 263 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NfAtHvLBuEDkecHhoqO:-NfAtHvLBuEDkecHhoqP:bayubjg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d18d0bb2ce5231265b48862b60d1b0b5a9aa13a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L263)):*
> ```Kotlin
>                         contentScale = ContentScale.Inside
>                     )
>                 }
> ```

just suggestion, it will be good to add some comment here to explain why there is no icon (just empty big box) sometimes

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: 24 of 27 files reviewed, 2 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 260 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NfAt9ZD9iB384Gv7b70:-NfBPmv9DPYZpFfTAChz:b-66439l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d18d0bb2ce5231265b48862b60d1b0b5a9aa13a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L260)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

It is better to add content description for icons
</blockquote></details>

I didn't feel that it added anything for the user in this case since the text below will say, "Login failed" or "Logged in", but I can add them if you feel they make sense.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 263 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NfAtHvLBuEDkecHhoqO:-NfBQloR9xvyKk3brddz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d18d0bb2ce5231265b48862b60d1b0b5a9aa13a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L263)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

just suggestion, it will be good to add some comment here to explain why there is no icon (just empty big box) sometimes
</blockquote></details>

Done.

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: 24 of 27 files reviewed, 2 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 260 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NfAt9ZD9iB384Gv7b70:-NfBTUHtDjD_bYuFTTsu:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d18d0bb2ce5231265b48862b60d1b0b5a9aa13a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L260)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I didn't feel that it added anything for the user in this case since the text below will say, "Login failed" or "Logged in", but I can add them if you feel they make sense.
</blockquote></details>

Done

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: 25 of 27 files reviewed, 1 unresolved discussion (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 131 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-NfBUJbI3CNQDhupy0rU:-NfF-5HN7qX7o6H0nmQ6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32a1e06fd2c52ec0626fac70c99cedc27dc0e9c5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L131)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Just suggestion, we use uiState instead of state in most of screens, it will be better if we do same here
</blockquote></details>

Done.

**Review by sabercodic — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5164#-:-NfGpwvoB8wnY-g50Pvj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
