### PR TITLE
Base android docker image on desktop image

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to base the Android docker image on the updated desktop image (#3986).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/docker/Dockerfile` line 41 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTSfX-ceyxZpZQfH7:-NEuTSfX-ceyxZpZQfH8:be53qvq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L41)):*
> ```Dockerfile
>     CC_i686_linux_android=${NDK_TOOLCHAIN_DIR}/i686-linux-android21-clang \
>     CC_aarch64_linux_android=${NDK_TOOLCHAIN_DIR}/aarch64-linux-android21-clang \
>     CC_armv7_linux_androideabi=${NDK_TOOLCHAIN_DIR}/armv7a-linux-androideabi21-clang
> ```

Did you try removing these OR the cargo config file? We said we should experiment to see if we can avoid duplicating this compiler/archiver config.
___
*[`android/docker/Dockerfile` line 59 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTA1JBkzR-FNpRVon:-NEuTA1JBkzR-FNpRVoo:b-bm83zx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L59)):*
> ```Dockerfile
>     add-apt-repository -y https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ && \
>     apt-get update && \
>     apt-get install -y adoptopenjdk-8-hotspot && \
> ```

Does it not make sense to join this with the `apt-get update && apt-get install` above? First adding the repository and then doing a single update and install? Or do you think it's cleaner to separate it what it's about? Joining them would reduce the dockerfile instruction count by a bunch.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`android/docker/Dockerfile` line 41 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTSfX-ceyxZpZQfH7:-NEuVeMD5BZdR9HMjzr6:bbc5gy8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L41)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Did you try removing these OR the cargo config file? We said we should experiment to see if we can avoid duplicating this compiler/archiver config.
</blockquote></details>

No, didn't experiment with it. I would prefer to handle that as a separate task/PR so that we can start using this image asap. What do you think about that?
___
*[`android/docker/Dockerfile` line 59 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTA1JBkzR-FNpRVon:-NEuVJcI9NUEWaSR1Nrz:bxz64w5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L59)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does it not make sense to join this with the `apt-get update && apt-get install` above? First adding the repository and then doing a single update and install? Or do you think it's cleaner to separate it what it's about? Joining them would reduce the dockerfile instruction count by a bunch.
</blockquote></details>

We'll replace this soon with Java 11 so I suggest we keep it for now.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/docker/Dockerfile` line 41 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTSfX-ceyxZpZQfH7:-NEuokxP2bs58kyMdyqq:byhpglu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L41)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

No, didn't experiment with it. I would prefer to handle that as a separate task/PR so that we can start using this image asap. What do you think about that?
</blockquote></details>

Ok. I just meant try to remove these lines and see if something blows up, not like spend a lot of time investigating if we can work around it.
___
*[`android/docker/Dockerfile` line 59 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTA1JBkzR-FNpRVon:-NEuocUJD5vRpXDCeo7V:b9cgmz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L59)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We'll replace this soon with Java 11 so I suggest we keep it for now.
</blockquote></details>

Ok! Makes sense.
___
*[`android/docker/Dockerfile` line 10 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuoRQ9-Co5tPSzWdHE:-NEuoRQ9-Co5tPSzWdHF:b-pjseak) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c7ce86132fc67d85d3768bc8cba81b5c58e5331/android/docker/Dockerfile#L10)):*
> ```Dockerfile
> #     -v /path/to/container_cache/gradle:/root/.gradle:Z \
> #     -v .:/build:Z \
> #     mullvadvpn-app-build-android ./build-apk.sh --dev-build --no-docker
> ```

This command must be executed from the repo root. But the above `podman build` should as it's written now be executed from `/android/docker`. Maybe rewrite the `podman build` command to `podman build android/docker` so they can be executed from the same directory?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`android/docker/Dockerfile` line 41 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTSfX-ceyxZpZQfH7:-NEv13kZ5FArEZYihs8b:bcqmdv5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L41)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ok. I just meant try to remove these lines and see if something blows up, not like spend a lot of time investigating if we can work around it.
</blockquote></details>

Alright :thumbsup: Actually seems like the `ENV` vars might be unnecessary :thinking: I pushed a commit without them but will investigate further.

Specified in the build instructions as well, so we might want to update those:
https://github.com/mullvad/mullvadvpn-app/blob/master/android/BuildInstructions.md#install-rust-android-targets
___
*[`android/docker/Dockerfile` line 10 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuoRQ9-Co5tPSzWdHE:-NEv-_B13WXZPMgtn1dJ:b-trfrc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c7ce86132fc67d85d3768bc8cba81b5c58e5331/android/docker/Dockerfile#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This command must be executed from the repo root. But the above `podman build` should as it's written now be executed from `/android/docker`. Maybe rewrite the `podman build` command to `podman build android/docker` so they can be executed from the same directory?
</blockquote></details>

Good point! I've changed to `/path/to/repository_root` to match the cache examples.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/docker/Dockerfile` line 41 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NEuTSfX-ceyxZpZQfH7:-NF8CV_W5m0IFD8Wev7O:b-ra0xjj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6d4aed4afdde666ea5bfb5be60d6a9cc1ae30cf/android/docker/Dockerfile#L41)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Alright :thumbsup: Actually seems like the `ENV` vars might be unnecessary :thinking: I pushed a commit without them but will investigate further.

Specified in the build instructions as well, so we might want to update those:
https://github.com/mullvad/mullvadvpn-app/blob/master/android/BuildInstructions.md#install-rust-android-targets
</blockquote></details>

:partying_face:

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 3 files at r3, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @faern)

___
*[`android/docker/Dockerfile` line 38 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NF8T9wnC13MX147n3Xz:-NF8T9woA6H15dPOKbc3:b-ergtwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1665530dd9a38e50a1da2fd8ae8bf9e34aa625d8/android/docker/Dockerfile#L38)):*
> ```Dockerfile
> 
> # NDK and checksum from: https://github.com/android/ndk/wiki/Unsupported-Downloads
> ENV NDK_VERSION=r20b \
> ```

It should be noted that when updating the NDK version, the toolchain path should be updated in `cargo-config.toml` too.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

___
*[`android/docker/Dockerfile` line 38 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NF8T9wnC13MX147n3Xz:-NF8Tavc9_1R0I4RI3R3:b-3xcd1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1665530dd9a38e50a1da2fd8ae8bf9e34aa625d8/android/docker/Dockerfile#L38)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It should be noted that when updating the NDK version, the toolchain path should be updated in `cargo-config.toml` too. 
</blockquote></details>

Good point, I'll see if we can improve that :thumbsup:

**Review by faern — APPROVED** [review]
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @faern and @pinkisemils)

___
*[`android/docker/Dockerfile` line 38 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064#-NF8T9wnC13MX147n3Xz:-NF8z8RP3t-z7ozrtoQV:b-57v87t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1665530dd9a38e50a1da2fd8ae8bf9e34aa625d8/android/docker/Dockerfile#L38)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think the paths might still need to be updated since they include a reference to the ABI version, if I understand it correctly, I'm referring to the `21` of `$NDK_TOOLCHAIN_DIR/i686-linux-android21-clang`.
</blockquote></details>

I managed to get it working by only setting ENV vars and also made sure to set the api/minSdkLevel value in a nicer way. Please have a look!

**Review by faern — COMMENTED** [review]
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4064)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
