### PR TITLE
Update ndk to version 27b

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837#-:-O7Y0TV_DQIO1nnUu2Fu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/build.gradle.kts` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837#-O7Y-c2G4JyuDIhIoFnp:-O7Y-c2G4JyuDIhIoFnq:b4a1noz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b306291782ad0631d6529edede2025eb7562e38/android/app/build.gradle.kts#L36)):*
> ```Kotlin
>     namespace = "net.mullvad.mullvadvpn"
>     compileSdk = Versions.compileSdkVersion
>     buildToolsVersion = Versions.buildToolsVersion
> ```

If we are to update the agp version would this still be required?

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/build.gradle.kts` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837#-O7Y-c2G4JyuDIhIoFnp:-O7YIK2NBOsd2hsNTtJH:b-ebyi0z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/42fd62433542596bf79974111213a8b2cc78cf69/android/app/build.gradle.kts#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

If we are to update the agp version would this still be required?
</blockquote></details>

According to https://developer.android.com/build/releases/gradle-plugin#compatibility

The 8.6.1 release still has the default of `34.0.0`, so if we don't specify it that will be used.

**Review by Pururun — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/build.gradle.kts` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837#-O7Y-c2G4JyuDIhIoFnp:-O7YiClq7GbSKyDD3Loh:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/42fd62433542596bf79974111213a8b2cc78cf69/android/app/build.gradle.kts#L36)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

According to https://developer.android.com/build/releases/gradle-plugin#compatibility

The 8.6.1 release still has the default of `34.0.0`, so if we don't specify it that will be used.
</blockquote></details>

:+1:

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 22 of 23 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837#-O7ZRkVOCwFYLX1YrcuY):*
nit: reminder to squash



_Code quote:_
```
Fix sdk
```

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837#-:-O7Z_NV35VNUBAsdKWdQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
