### PR TITLE
Add IAN TCP connections

### PR DESCRIPTION
**Pull request by pinkisemils**
Due to :apple: :hammer: , we can't just use regular sockets to reach hosts inside the tunnel from the packet tunnel process. With these changes, we integrate the recent additions to `wireguard-apple` to use userspace networking  stack to send TCP packets back and forth through the tunnel without asking for Apple's permission. 

These changes also provide some general improvements to `mullvad-ios`, and asynchronize the ephemeral peer exchange pipelines, making them wait to start a new negotiation until after the tunnel has been reconfigured. Previously, the peer exchange connection was initiated before the tunnel was reconfigured, causing many a slowdown and instability.

There is a peculiarity - due to how we'd prefer not to link two whole tokio runtimes, the FFI for the TCP connections is exposed via function pointers to rust. Ideally, we'd be able to produce a static Rust library that weak links against all the rust dependencies it needs (as they'd be provided by `mullvad-ios` at link time), and link this into the packet tunnel executable - alas, linker plumbing requires levels of willpower this weak willed magpie cannot maintain given all the other changes.

Bear in mind, the TMP commits will be dropped before merging to main, they are there to aid with testing and development.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 6 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 6 of 27 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODje1un90ex8AKgnZ46:-ODje1uo6_F8AGNZ86YB:b-69u4f8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs#L14)):*
> ```XML
> };
> 
> const GRPC_HOST_CSTR: &'static CStr = unsafe { CStr::from_ptr(GRPC_HOST_PTR) };
> ```

You could use a `CStr` literal here.
___
*[`mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjgY-j3wnoD8qs-zPF:-ODjgY-j3wnoD8qs-zPG:b-v5hb47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs#L38)):*
> ```XML
>                 // CODE STENCH:
>                 // Swift can call this function from a tokio context. That *will* crash.
>                 // context.
> ```

"context."?
___
*[`mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjeHvfELwhY1xy26Lw:-ODjeHvfELwhY1xy26Lx:b-8xv1rv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs#L106)):*
> ```XML
>                 async move {
>                     provider
>                         .connect(&GRPC_HOST_CSTR)
> ```

Nit: Pointless `&`.
___
*[`mullvad-ios/src/ephemeral_peer_proxy/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjiCJ--VMhzRSLGXVr:-ODjiCJ01sDYepOp-_5H:bhax0yk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/mod.rs#L37)):*
> ```XML
> // This is safe as long as the PacketTunnel class outlives the instance of the PacketTunnelBridge,
> // and thus the ephemeral peer exchange. Since the peer exchange takes place in the packet tunnel
> // process on iOS, it is certain _enough_ this will be the case.
> ```

I'm not sure this belongs here. Seems like whoever constructs a `PacketTunnelBridge` should have to promise that `packet_tunnel` will outlive it.
___
*[`mullvad-ios/src/ephemeral_peer_proxy/mod.rs` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjh5eS7S9y1-4EIPid:-ODjgtJN8sR5GzBbVmDS:b-xuirbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/mod.rs#L38)):*
> ```XML
> // and thus the ephemeral peer exchange. Since the peer exchange takes place in the packet tunnel
> // process on iOS, it is certain _enough_ this will be the case.
> // It is safe to implement Send for PacketTunnelBridge because the packet_tunnel
> ```

Should this line be removed?

**Review by dlon — COMMENTED** [review]
> Reviewed 3 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 9 of 27 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 9 of 27 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-ios/src/ephemeral_peer_proxy/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjiCJ--VMhzRSLGXVr:-ODjo9XH5yUxCejze01Y:b8q1ym4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/mod.rs#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'm not sure this belongs here. Seems like whoever constructs a `PacketTunnelBridge` should have to promise that `packet_tunnel` will outlive it.
</blockquote></details>

And (somewhat unrelatedly) point out (at the FFI boundary?) that whatever function is passed `packet_tunnel` may be called from different threads.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 10 of 27 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-ios/src/ephemeral_peer_proxy/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjiCJ--VMhzRSLGXVr:-ODjpOZG1nEVCplNmPs7:buz23sh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/mod.rs#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

And (somewhat unrelatedly) point out (at the FFI boundary?) that whatever function is passed `packet_tunnel` may be called from different threads.
</blockquote></details>

Then you could simply state here that the caller has promised that it is sendable.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 10 of 27 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-ios/src/ephemeral_peer_proxy/ios_tcp_connection.rs` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjpo0yBIdOJB1FyGe6:-ODjpo0yBIdOJB1FyGe7:b-otnw5s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/ios_tcp_connection.rs#L39)):*
> ```XML
> 
> impl WgTcpConnectionFuncs {
>     pub fn open(&self, tunnel_handle: i32, address: *const u8, timeout: u64) -> i32 {
> ```

I don't think this is actually safe at all. You could assign anything to the public function pointers, and dereference anything here.

A suggestion is to wrap `WgTcpConnectionFuncs` in another type, make it private, add an unsafe constructor that takes `WgTcpConnectionFuncs` and state as a precondition that the function pointers must be `'static` and valid.

Or simply make them unsafe.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 6 of 29 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-ios/src/ephemeral_peer_proxy/ios_tcp_connection.rs` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODjpo0yBIdOJB1FyGe6:-ODlCJ9TCoRQYQ7X1dwf:bff2kr0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/ios_tcp_connection.rs#L39)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't think this is actually safe at all. You could assign anything to the public function pointers, and dereference anything here.

A suggestion is to wrap `WgTcpConnectionFuncs` in another type, make it private, add an unsafe constructor that takes `WgTcpConnectionFuncs` and state as a precondition that the function pointers must be `'static` and valid.

Or simply make them unsafe.
</blockquote></details>

The public visibility is needed for cbindgen to add those fields to the header file. This does remain inherently unsafe, so I have marked them unsafe now.

**Review by dlon — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 12 of 29 files reviewed, all discussions resolved

**Comment by pinkisemils** [comment]
Lints and tests have now all been fixed, I believe this is ready for the final review now.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 22 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-:-OE-orHp88pG-s1snjxc:bnfp4nl)* status: 16 of 36 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[`mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-ODexCGX-jtXiJrN_eRe:-ODexCGX-jtXiJrN_eRf:btcgywq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edaf51e5a559112b9547359717a02fc80de1c1f9/mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs#L36)):*
> ```XML
>             if let Some(task) = inner.task.take() {
>                 task.abort();
>                 // CODE STENCH:
> ```

nit
I've been toying with the idea that we could have our own global executor on the swift side that is used to create an async runtime context for exchanging things with rust.

In theory, that would let us do cool things like control which execution context to use when doing FFI, and potentially have a clean way to call `async` functions across FFI, but at this point, I'd need to spend time grinding my teeth on it to see if it's viable, or even doable.

**Review by dlon — COMMENTED** [review]
> Reviewed 12 of 20 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 29 of 36 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 28 of 36 files reviewed, 2 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @dlon)

___
*[`ios/MullvadTypes/Protocols/EphemeralPeerReceiver.swift` line 33 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-OEIuWmA578P8vSIRiQj:-OEJ4twg0YeN0EaPssM3:buu1v8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4761d2694124d07849e1fde49b3b6c56b92f649a/ios/MullvadTypes/Protocols/EphemeralPeerReceiver.swift#L33)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Is there a reason to use semaphores rather than running the key reception on a serial `DispatchQueue`?
</blockquote></details>

I did it this way to wait for an asynchronous task to finish from a blocking call. I'll gladly improve this if you have a good suggestion :slightly_smiling_face: I do not feel like this is an ideal solution, in fact it feels a bit fragile now.

**Review by dlon — COMMENTED** [review]
lgtm

> Reviewed 3 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-:-OENtMqn6jf65zV-ggWO:bb7k0qh)* status: 24 of 36 files reviewed, 2 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @pinkisemils)

**Review by rablador — COMMENTED** [review]
> Reviewed 13 of 27 files at r1, 1 of 6 files at r2, 12 of 20 files at r3, 1 of 1 files at r4, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @pinkisemils)

___
*[`ios/MullvadTypes/Promise.swift` line 51 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-OEOB54ACoJ9lDU0_Pbg:-OEOB54ACoJ9lDU0_Pbh:bldru9n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5dd7c1c6de4b107419c8fb9dbbb111dc0150169e/ios/MullvadTypes/Promise.swift#L51)):*
> ```Swift
> }
> 
> public struct OneshotChannel {
> ```

This struct should be documented I think.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: 35 of 36 files reviewed, 2 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @rablador)

___
*[`ios/MullvadTypes/Promise.swift` line 51 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289#-OEOB54ACoJ9lDU0_Pbg:-OEPe2dG-H0G-qZ_9OEo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5dd7c1c6de4b107419c8fb9dbbb111dc0150169e/ios/MullvadTypes/Promise.swift#L51)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This struct should be documented I think.
</blockquote></details>

Done.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7289)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

**Pull request merged**
