### PR TITLE
Update the select location view

### PR DESCRIPTION
**Pull request by rablador**
When smart routing and multihop are enabled, the entry selection view should be updated to explain to the user that they cannot change an entry location when DAITA is on and Direct only is off.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950)

### CODE REVIEW

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/DAITASettings.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950#-O9J359LAuEuoj7J-Hcv:-O9J359N9fVnkcbAA6Vq:b-qy5o1w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0cf098500425bc99348a6d05a21b7983b565456/ios/MullvadSettings/DAITASettings.swift#L43)):*
> ```Swift
>     public let directOnlyState: DirectOnlyState
> 
>     public var shouldDoAutomaticRouting: Bool {
> ```

We should remove this to avoid confusion
___
*[`ios/MullvadVPN/Coordinators/LocationCoordinator.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950#-O9J7Ysj59eSTkBERO_D:-O9J7Ysj59eSTkBERO_E:bc5nvpl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0cf098500425bc99348a6d05a21b7983b565456/ios/MullvadVPN/Coordinators/LocationCoordinator.swift#L58)):*
> ```Swift
>         super.init()
> 
>         addTunnelObserver()
> ```

Is there a specific reason why we don't do this in `start` instead ?
`init` is only ever called once, but `start` will be called as many times as this coordinator starts, which seems like a code smell to me.

**Review by mojganii — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950#-:-O9JS4neEZGSSVqznDOl:bnfp4nl)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/DAITASettings.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950#-O9JRH3U82dUMH8qQ59n:-O9JRH3U82dUMH8qQ59o:bb1fr5f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a0cf098500425bc99348a6d05a21b7983b565456/ios/MullvadSettings/DAITASettings.swift#L47)):*
> ```Swift
>     }
> 
>     public var shouldDoDirectOnly: Bool {
> ```

nit : `isDirectOnly`

**Review by buggmagnet — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950#-:-O9Kbg3x0wNHdMGFzJnR:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950#-:-O9UUnwI2qKXC2uLXiJu:bnfp4nl)* status: 5 of 17 files reviewed, 3 unresolved discussions (waiting on @mojganii)

**Pull request merged**
