### PR TITLE
Print same-ip message on each connect

### PR DESCRIPTION
**Pull request by pronebird**
This PR ensures that same-ip message is printed on each connect by exposing tun addresses over `ConnectionState`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5277)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
Would it not be far simpler to have these changes be added right before the call to `adapter.update` and `adapter.start`  in `WgAdapter.swift`? 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5277#-:-NgYZ4hF1COP5a8WKvtS:b-5xk0cf)* status: 0 of 3 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
It would be simpler, but logically, does logging same-ip fall into the domain of concern of `WgAdapter`?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5277#-:-NgYjYeb-lOXqQyfnXat:bu03o0f)* status: 0 of 3 files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
Updated for simplicity as per your suggestion.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5277#-:-NgYuXd31v98ipledVGT:bdwn0a8)* status: 0 of 4 files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
A good rule of thumb is to log it whenever a new config is passed to WireGuard, and this seems to fit the bill. The change is smaller, and ultimately, this logging is likely to be removed before the end of the year anyway.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5277#-:-NgZRyK-BgI8yRvWgbBv:b-jaytwq)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
