### PR TITLE
reusing existing connection for requests

### PR DESCRIPTION
**Pull request by mojganii**
This pull request optimizes performance by enabling the reuse of the current connection, eliminating the necessity for a new connection with each incoming request. However, exceptions are made in cases such as request failures or modifications to the active configuration by other processes (e.g., Packet tunnel, UI part).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoXNBsrASY8QIEQDgsC:-NoXNBsrASY8QIEQDgsD:buwkzmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8da7d998271890a68ae648596df89cfbe90b0ead/ios/MullvadSettings/AccessMethodRepository.swift#L35)):*
> ```Swift
>     }
> 
>     public var accessMethods: [PersistentAccessMethod] {
> ```

Can't we use `fetchAll` directly instead since it's already public.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoXNBsrASY8QIEQDgsC:-Nok_9YX5h0DvQ7jTU4d:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8da7d998271890a68ae648596df89cfbe90b0ead/ios/MullvadSettings/AccessMethodRepository.swift#L35)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can't we use `fetchAll` directly instead since it's already public.
</blockquote></details>

Done.

**Review by rablador — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqGlgG4doMIZ2MDtyl:-NoqGlgG4doMIZ2MDtym:bn3xwhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L13)):*
> ```Swift
> import MullvadSettings
> 
> class AccessMethodIterator {
> ```

nit
It just occured to me that this is named `Iterator` but doesn't implement the `Iterator` protocol, which is a misleading name.
Not a big deal, but we should be better at naming things in the future
___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 50 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqHByV9yCELWIZH-Z0:-NoqHByW8yw3LxdFLHfy:b-h1qack) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L50)):*
> ```Swift
>         } else {
>             /// When `firstIndex` is `nil`, that means the current configuration is not valid anymore
>             /// Invalidating cache by replacing the `current`  to the next enabled access method
> ```

nit
There 2 spaces in `current  to` 
___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqHrErD9HdUQvOjisi:-NoqHrErD9HdUQvOjisj:b-qlrwz6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L62)):*
> ```Swift
> 
>     func pick() -> PersistentAccessMethod {
>         if enabledConfigurations.isEmpty {
> ```

Given that `enabledConfigurations` is really
```swift
dataSource.fetchAll().filter { $0.isEnabled }
```

we're calling this at best once, at worst 3 times every time we call `pick()`, which would be really bad if `dataSource` is a huge array to filter.

Suggestion 
```swift
    func pick() -> PersistentAccessMethod {
        let configurations = enabledConfigurations
        if configurations.isEmpty {
            /// Returning `directAccess` when all methods are disabled
            return dataSource.directAccess
        } else {
            /// Picking the next `Enabled` configuration in order they are added
            /// And starting from the beginning when it reaches end
            let circularIndex = index % configurations.count
            return configurations[circularIndex]
        }
    }
```
___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 63 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqHP4Z5AI55Y8n7om7:-NoqHP4_4xUgyNGd4j-Z:bm6bf5x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L63)):*
> ```Swift
>     func pick() -> PersistentAccessMethod {
>         if enabledConfigurations.isEmpty {
>             /// Returning  `Default` strategy  when  all is disabled
> ```

nit
there are 2 spaces in `Returning  Default`

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqGlgG4doMIZ2MDtyl:-NoqQ0KR8UkJSzdMWZw_:b-n0s8c6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
It just occured to me that this is named `Iterator` but doesn't implement the `Iterator` protocol, which is a misleading name.
Not a big deal, but we should be better at naming things in the future
</blockquote></details>

do you have any suggestion? how about `AccessMethodRotator`?
___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 50 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqHByV9yCELWIZH-Z0:-NoqQSbiBjiFTJvemOEH:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L50)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
There 2 spaces in `current  to`
</blockquote></details>

Done
___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqHrErD9HdUQvOjisi:-NoqSZAC8XX6-GOgTIt-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L62)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Given that `enabledConfigurations` is really
```swift
dataSource.fetchAll().filter { $0.isEnabled }
```

we're calling this at best once, at worst 3 times every time we call `pick()`, which would be really bad if `dataSource` is a huge array to filter.

Suggestion 
```swift
    func pick() -> PersistentAccessMethod {
        let configurations = enabledConfigurations
        if configurations.isEmpty {
            /// Returning `directAccess` when all methods are disabled
            return dataSource.directAccess
        } else {
            /// Picking the next `Enabled` configuration in order they are added
            /// And starting from the beginning when it reaches end
            let circularIndex = index % configurations.count
            return configurations[circularIndex]
        }
    }
```
</blockquote></details>

Done.
___
*[`ios/MullvadREST/Transport/AccessMethodIterator.swift` line 63 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704#-NoqHP4Z5AI55Y8n7om7:-NoqTe9V6jatfOFA68lN:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9052ac0f43ff00c17a91377923771b5621adbde7/ios/MullvadREST/Transport/AccessMethodIterator.swift#L63)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
there are 2 spaces in `Returning  Default`
</blockquote></details>

Done

**Review by buggmagnet — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
