### PR TITLE
Add logging to connectivity listener

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334#-:-ODuWKut9u_-RC-q23R2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334#-ODuhOVs4pLjtRhYcYjv:-ODuhOVs4pLjtRhYcYjw:b-f0tc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5fbf532d8b67ea3e92d79783ed850cdcf1f6230/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt#L72)):*
> ```Kotlin
>                 when (event) {
>                     is NetworkEvent.Available -> {
>                         Logger.d("Network available ${event.network}")
> ```

What exactly would `network` print? Could it be considered sensitive?

**Review by Rawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334#-ODuhOVs4pLjtRhYcYjv:-ODuijLW4bfSWAw0Xm-z:bl7j7rv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5fbf532d8b67ea3e92d79783ed850cdcf1f6230/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt#L72)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What exactly would `network` print? Could it be considered sensitive?
</blockquote></details>

It will be the `netId`, an integer representing the network. For each new network it will increment from the previous. 

It will help us distinguish between multiple networks during a roaming between different networks.

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334#-:-ODv9X4p-tiMLfOLpNqJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334#-:-ODvA2HvA-ZNRwYbdran:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334#-ODuhOVs4pLjtRhYcYjv:-ODv9iuE76sSUaV7atox:b-r2uc4n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d5fbf532d8b67ea3e92d79783ed850cdcf1f6230/android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt#L72)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It will be the `netId`, an integer representing the network. For each new network it will increment from the previous. 

It will help us distinguish between multiple networks during a roaming between different networks.
</blockquote></details>

Alright, sounds good to include since it doesn't seem like much of a privacy concern

**Pull request merged**
