### PR TITLE
Add check for empty play purchase payment token

### PR DESCRIPTION
**Pull request by Pururun**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269#-OD6UUdBBF_yVuFlh6Mb:-OD6UUdBBF_yVuFlh6Mc:bxy8rd1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aee97d02c5707b75ba997205d3ae91e0d1f4cb2/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L157)):*
> ```Kotlin
> 
>     private suspend fun initialisePurchase() =
>         playPurchaseRepository.initializePlayPurchase().flatMap {
> ```

Just noticed when reading this code,`initialise`/`initialize`. We use both american and british english. I'll leave it up to you if you want to fix it in this PR.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269#-OD6UUdBBF_yVuFlh6Mb:-OD6VUku98Om96x2KXlw:b-70qc7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aee97d02c5707b75ba997205d3ae91e0d1f4cb2/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L157)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Just noticed when reading this code,`initialise`/`initialize`. We use both american and british english. I'll leave it up to you if you want to fix it in this PR.
</blockquote></details>

We are using `initialize` everywhere else so will switch to that.

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
