### PR TITLE
Device desktop UI

### PR DESCRIPTION
**Pull request by raksooo**
This PR makes all the UI changes required for handling devices. This includes:
* Removing everyting related to WireGuard key handling
* Adding view for revoking other devices
* Adding view for when current device has been revoked
* Adding confirmation dialog when logging out if there are ports connected to the device

Other changes/refactoring is:
* Escape key binding being ignored on some pages
* Improving the base route logic
* Prevent transitioning to "new" view when the path was set to the same as before.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 5 of 37 files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 5 of 37 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 694 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW0N1VEhrv7mrYyELS:-MwW0N1VEhrv7mrYyELT:b7ronxd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/app.tsx#L694)):*
> ```XML
>       const loginState = this.reduxStore.getState().account.status;
>       const deviceRevoked = loginState.type === 'none' && loginState.deviceRevoked;
>       return this.deviceConfig?.accountToken || deviceRevoked ? RoutePath.main : RoutePath.login;
> ```

I may not understand this right, but if device is revoked, we probably want to show the `login` path and `main`?

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 5 of 37 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 694 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW0N1VEhrv7mrYyELS:-MwW0he16ma8UdDSnRzJ:bl1teqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/app.tsx#L694)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I may not understand this right, but if device is revoked, we probably want to show the `login` path and `main`?
</blockquote></details>

`login` path and _not_ `main`

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 6 of 37 files reviewed, 2 unresolved discussions (waiting on @raksooo)

**Review by pronebird — COMMENTED** [review]
> Reviewed 9 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 15 of 37 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/ipc-schema.ts, line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW2CmyEa-ONTMId_5a:-MwW2CmyEa-ONTMId_5b:b6dyp2u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/shared/ipc-schema.ts#L172)):*
> ```XML
>     '': notifyRenderer<IAccountData | undefined>(),
>     device: notifyRenderer<IDeviceEvent>(),
>     devices: notifyRenderer<IDevice[]>(),
> ```

Nit: slight inconsistence you use `Array<IDevice>` and/or `IDevice[]` way of expressing array type. I don't have a specific preference, but just noticed that.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 16 of 37 files reviewed, 3 unresolved discussions (waiting on @raksooo)

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 36 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 20 of 37 files reviewed, 5 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/Account.tsx, line 138 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW4okJ2GZ4Z5uQtnAu:-MwW4okJ2GZ4Z5uQtnAv:btc7e4e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/components/Account.tsx#L138)):*
> ```XML
>   }
> 
>   private renderLoguotDialog() {
> ```

Typo in the word `Logout`, o and u flipped.
___
*[gui/src/renderer/components/Account.tsx, line 184 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW4tHUBdAbWFIB9_c0:-MwW4tHV3UscW1gnxtE1:b-ueoday) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/components/Account.tsx#L184)):*
> ```XML
>   }
> 
>   private onTryLogoout = async () => {
> ```

Typo in `Logout` double O

**Review by pronebird — COMMENTED** [review]
> Reviewed 14 of 36 files at r1, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: all files reviewed, 5 unresolved discussions (waiting on @raksooo)

**Review by pronebird — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-:-MwW6iKA65kEn-8wev1X:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 33 of 37 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/main/daemon-rpc.ts, line 515 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwVygSM-JJnpOvvQffv:-MwWwuWF3WGDo2AX3ia1:bisx8hu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/main/daemon-rpc.ts#L515)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not sure I understand, the return signature is `Promise<DeviceConfig>`, how does `tsc` handle this? Perhaps you meant to return `Promise<DeviceConfig | undefined>`?
</blockquote></details>

The definition of `DeviceConfig` looks like this:
```
export type DeviceConfig =
  | undefined
  | {
      accountToken: AccountToken;
      device?: IDevice;
    };
```

It don't remember exactly why I implemented it like that but I suspect it's because it could be `undefined` anywhere and it felt unnecessary to declare it everywhere. But I can see how this is confusing. Would you prefer if `| undefined` was added everywhere instead?
___
*[gui/src/renderer/app.tsx, line 694 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW0N1VEhrv7mrYyELS:-MwWyMflCQ8TZ5jyvTg1:b-97x74u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/app.tsx#L694)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`login` path and _not_ `main`
</blockquote></details>

Yeah, I made the too-many-devices view part of the main view. But I now see that it should really be part of the login view. I'll fix this!
___
*[gui/src/renderer/components/Account.tsx, line 138 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW4okJ2GZ4Z5uQtnAu:-MwWxcyl85rcC7z2A1Mz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/components/Account.tsx#L138)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Typo in the word `Logout`, o and u flipped.
</blockquote></details>

Done.
___
*[gui/src/renderer/components/Account.tsx, line 184 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW4tHUBdAbWFIB9_c0:-MwWxiz10NEotYGBlZb1:bgioy8q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/components/Account.tsx#L184)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Typo in `Logout` double O
</blockquote></details>

Why did I mispell `Logout` this much? :laughing: Done.
___
*[gui/src/shared/ipc-schema.ts, line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW2CmyEa-ONTMId_5a:-MwWy3Ps97tu0TQDJOqW:b-qu6n94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/shared/ipc-schema.ts#L172)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: slight inconsistence you use `Array<IDevice>` and/or `IDevice[]` way of expressing array type. I don't have a specific preference, but just noticed that.
</blockquote></details>

Good point. Done.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 29 of 37 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/renderer/app.tsx, line 694 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwW0N1VEhrv7mrYyELS:-Mw_rvmeARioBXg20Qb5:b-2s2lji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/renderer/app.tsx#L694)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Yeah, I made the too-many-devices view part of the main view. But I now see that it should really be part of the login view. I'll fix this!
</blockquote></details>

Done. I gave it it's own path instead.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 29 of 37 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

___
*[gui/src/main/daemon-rpc.ts, line 515 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwVygSM-JJnpOvvQffv:-Mw_ud-b2VYvcnRa9rft:b-lhs5gm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/main/daemon-rpc.ts#L515)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The definition of `DeviceConfig` looks like this:
```
export type DeviceConfig =
  | undefined
  | {
      accountToken: AccountToken;
      device?: IDevice;
    };
```

It don't remember exactly why I implemented it like that but I suspect it's because it could be `undefined` anywhere and it felt unnecessary to declare it everywhere. But I can see how this is confusing. Would you prefer if `| undefined` was added everywhere instead?
</blockquote></details>

A little odd for a type to be `undefined` as well. Perhaps if it's too much work to add `| undefined` elsewhere, the one could make a union type that lists both, which would perhaps add clarity, unless, of course, `undefined` is a legit device configuration, which I suppose it's not :-)

```
type MaybeDeviceConfig = DeviceConfig | undefined;

type DeviceConfig = { 
  accountToken: AccountToken; 
  device?: IDevice; 
};
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 5 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 34 of 37 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 31 of 37 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/daemon-rpc.ts, line 515 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwVygSM-JJnpOvvQffv:-MwakkePBauovqX-tY8x:bcrs755) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b78fa0284c6acd7bd1681160ba76055b5b0096f9/gui/src/main/daemon-rpc.ts#L515)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

A little odd for a type to be `undefined` as well. Perhaps if it's too much work to add `| undefined` elsewhere, the one could make a union type that lists both, which would perhaps add clarity, unless, of course, `undefined` is a legit device configuration, which I suppose it's not :-)

```
type MaybeDeviceConfig = DeviceConfig | undefined;

type DeviceConfig = { 
  accountToken: AccountToken; 
  device?: IDevice; 
};
```
</blockquote></details>

It wasn't used in that many places so I added `undefined` where it was used instead. Done :+1:

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 34 of 37 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/redux/account/actions.ts, line 110 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwfGGaA3ZRTJT1gITcJ:-MwfGGaB4zRND7aQaPVp:b-1pllde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3927bc0df483c1298a2521248b5147c2ff00e59e/gui/src/renderer/redux/account/actions.ts#L110)):*
> ```XML
> }
> 
> function loggedIn(deviceConfig: NonNullable<IDeviceConfig>): ILoggedInAction {
> ```

How's `NonNullable<IDeviceConfig>` different from simply using `IDeviceConfig`? I suppose you don't have to use `NonNullable` here since `IDeviceConfig` is not optional.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 34 of 37 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/redux/account/actions.ts, line 175 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwfGPid2ZqzO6Woiyth:-MwfGPid2ZqzO6Woiyti:brhumzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3927bc0df483c1298a2521248b5147c2ff00e59e/gui/src/renderer/redux/account/actions.ts#L175)):*
> ```XML
> }
> 
> function accountCreated(deviceConfig: NonNullable<IDeviceConfig>, expiry: string): IAccountCreated {
> ```

Same here.

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: 34 of 37 files reviewed, 3 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/shared/ipc-schema.ts, line 57 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364#-MwfH9J0ARgW9wRrmInW:-MwfH9J0ARgW9wRrmInX:bpbrfk4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3927bc0df483c1298a2521248b5147c2ff00e59e/gui/src/shared/ipc-schema.ts#L57)):*
> ```XML
>   tunnelState: TunnelState;
>   settings: ISettings;
>   deviceConfig: IDeviceConfig | undefined;
> ```

Perhaps `deviceConfig?: IDeviceConfig`? That's what you use elsewhere but I am not sure about significance.

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3364)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
