### PR TITLE
Rename `mullvad-rpc` to `mullvad-api`

### PR DESCRIPTION
**Pull request by dlon**
As above. `mullvad-api` is a more informative name than `mullvad-rpc`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434)* status: 0 of 37 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434#-Mylq999CAM-xAJX4flW:-Mylq999CAM-xAJX4flX:bh311p1) (no related file):*
I suppose `mullvad_api::MullvadRpcRuntime` should be renamed as well. Maybe to `MullvadApiRuntime`, or simply `Runtime`?

---

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @dlon)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434#-Mylq999CAM-xAJX4flW:-MyltLxO-HIvsCBowz2C:bvef77l) (no related file):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I suppose `mullvad_api::MullvadRpcRuntime` should be renamed as well. Maybe to `MullvadApiRuntime`, or simply `Runtime`?
</blockquote></details>

IMO: `MullvadApiRuntime` to lessen the confusion with Tokio's `Runtime`.

---

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 8 of 37 files at r1, 3 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434)* status: 11 of 37 files reviewed, all discussions resolved

___
*[mullvad-api/Cargo.toml, line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434#-MyqI0L57AiSUjW0eKst:-MyqI0L57AiSUjW0eKsu:bebluic) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c133d9804b0eeaaf253a55b2c4ff747a7d89d732/mullvad-api/Cargo.toml#L5)):*
> ```TOML
> version = "0.1.0"
> authors = ["Mullvad VPN"]
> description = "Mullvad VPN RPC clients. Providing an interface to query our infrastructure for information."
> ```

This could be `Mullvad VPN API clients.` I guess.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3434)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
