### PR TITLE
Reduce flakiness of `test_ui_tunnel_settings`

### PR DESCRIPTION
**Pull request by Serock3**
Fixes a bug where `test_ui_tunnel_settings` failed on macOS since it has IPv6 enabled by default, which caused the parsing of the outbound IP to fail. 

The PR also sets the "LowLatency" custom list for the test, since it connects multiple times with different settings, including multihop and OpenVPN, and thus is highly dependent on connection stability.

CI job which ran the test 10 times in a row: https://github.com/mullvad/mullvadvpn-app/actions/runs/11838399382.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`test/test-manager/src/tests/ui.rs` line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166#-OBfQG4c0ooArSsbKTV0:-OBfQG4c0ooArSsbKTV1:b-kucbqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c0ecba1b3cfdc83cd3b5c4148e24c81818af1e5/test/test-manager/src/tests/ui.rs#L108)):*
> ```XML
>             .build(),
>     )
>     .await?;
> ```

:pick: The `LowLatency` list won't apply for the OpenVPN connection as is, right?



_Code quote:_
```XML
    // NOTE: This test connects multiple times using various settings, some of which may cauase a
    // significant increase in connection time, e.g. multihop and OpenVPN. For this reason, it is
    // preferable to only target low latency servers.
    use helpers::custom_lists::LowLatency;

    // tunnel-state.spec precondition: a single WireGuard relay should be selected
    log::info!("Select WireGuard relay");
    let entry = helpers::constrain_to_relay(
        &mut mullvad_client,
        RelayQueryBuilder::new()
            .wireguard()
            .location(LowLatency)
            .build(),
    )
    .await?;
```
___
*[`mullvad-relay-selector/src/relay_selector/matcher.rs` line 251 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166#-OBfPsyI8RD0Eg-YQojJ:-OBfPsyI8RD0Eg-YQojK:b-al951q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c0ecba1b3cfdc83cd3b5c4148e24c81818af1e5/mullvad-relay-selector/src/relay_selector/matcher.rs#L251)):*
> ```XML
>                         log::warn!("Resolved non-existent custom list with id {list_id:?}");
>                         ResolvedLocationConstraint(vec![])
>                     }),
> ```

Why shouldn't we print the custom list ID?



_Code quote:_
```XML
                    .unwrap_or_else(|| {
                        log::warn!("Resolved non-existent custom list with id {list_id:?}");
                        ResolvedLocationConstraint(vec![])
                    }),
```
___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166#-OBfPMdv1uAmt94a-SYn:-OBfPMdw0xhKh7-TqOKc:b8z1c0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c0ecba1b3cfdc83cd3b5c4148e24c81818af1e5/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L38)):*
> ```XML
>   const relay = page.getByTestId('hostname-line');
>   const inIp = page.locator(':text("In") + span');
>   const outIp = page.locator(':text("Out") + div > span').first();
> ```

:pick: Is it obvious why `first` is called here? Is it because there could be multiple "Out IPs", and that the first one is the IPv4 address? If so, would it make sense to leave a small comment here? :blush:



_Code quote:_
```XML
const outIp = page.locator(':text("Out") + div > span').first();
```

**Review by MarkusPettersson98 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)* status: all files reviewed, 2 unresolved discussions (waiting on @Serock3)

**Review by MarkusPettersson98 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

**Review by Serock3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`test/test-manager/src/tests/ui.rs` line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166#-OBfQG4c0ooArSsbKTV0:-OBfUvpECLDfu7D6qCA8:bpddq6w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c0ecba1b3cfdc83cd3b5c4148e24c81818af1e5/test/test-manager/src/tests/ui.rs#L108)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: The `LowLatency` list won't apply for the OpenVPN connection as is, right?
</blockquote></details>

I think it will, even though it is not obvious!
___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166#-OBfPMdv1uAmt94a-SYn:-OBfV4yU9i9lKnRR0Ohw:b-n2bw9a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c0ecba1b3cfdc83cd3b5c4148e24c81818af1e5/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L38)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: Is it obvious why `first` is called here? Is it because there could be multiple "Out IPs", and that the first one is the IPv4 address? If so, would it make sense to leave a small comment here? :blush:
</blockquote></details>

Note at all! Good catch, I added a comment :)

**Review by MarkusPettersson98 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
