### PR TITLE
Clean up dialogs

### PR DESCRIPTION
**Pull request by Pururun**
Clean up task:
- Moved all infodialogs into their own package ot make the dialog package.
- Made some more dialogs use `DeleteConfirmationDialog`
- Renamed `DeleteConfirmationDialog` to `NegativeConfirmationDialog`
- Added support for `AnnotatedString` to `NegativeConfirmationDialog`
- Removed `HtmlText` as the last instance where it was used was replaced with `AnnotatedString`
- Added InputDialog and made all input dialogs except redeem voucher dialog use it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)

### CODE REVIEW

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 17 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)* status: 17 of 25 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661#-O4uQi0w7LwtGnSbNB6z):*
typo: `dialogs`



_Code quote:_
```
dialog
```

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 3 of 25 files at r1, 22 of 22 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661#-O60HWmP34jTvoJMUakN:-O60HWmP34jTvoJMUakO:b-rmc9xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0efa5e6b80d8c58e4a723f4a69b5dbfc895a5cfa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt#L50)):*
> ```Kotlin
> fun NegativeConfirmationDialog(
>     message: String,
>     messageStyle: TextStyle? = null,
> ```

Shouldn't these be the same for all NegativeConfrimationDialog? Or when do we change the message style? I saw the NoEmail for error report seems to have a different style.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt` line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661#-O60IGno3aoOksT9a7UX:-O60IGno3aoOksT9a7UY:b-8h6ee1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0efa5e6b80d8c58e4a723f4a69b5dbfc895a5cfa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt#L51)):*
> ```Kotlin
>     message: String,
>     messageStyle: TextStyle? = null,
>     errorMessage: String?,
> ```

Maybe null as default? Then we don't have to define it on the call side if it does not have a message.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)* status: 16 of 25 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661#-O60HWmP34jTvoJMUakN:-O65WGhc1LYHt0XW9rfN:b-sq20bq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0efa5e6b80d8c58e4a723f4a69b5dbfc895a5cfa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt#L50)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Shouldn't these be the same for all NegativeConfrimationDialog? Or when do we change the message style? I saw the NoEmail for error report seems to have a different style.
</blockquote></details>

It is used by `NoEmail` and `RemoveDevice`. In the case of no email it is because the text is quite long, in the case of remove device it is because it has some text that is bold so the normal text needs to be non-bold.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt` line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661#-O60IGno3aoOksT9a7UX:-O65WGK3Bc5mz5NaoONR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0efa5e6b80d8c58e4a723f4a69b5dbfc895a5cfa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt#L51)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe null as default? Then we don't have to define it on the call side if it does not have a message.
</blockquote></details>

Done.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)* status: 16 of 26 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661#-O60HWmP34jTvoJMUakN:-O6L8PKq2UDR4KDqzbQg:buz3634) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0efa5e6b80d8c58e4a723f4a69b5dbfc895a5cfa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/NegativeConfirmationDialog.kt#L50)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It is used by `NoEmail` and `RemoveDevice`. In the case of no email it is because the text is quite long, in the case of remove device it is because it has some text that is bold so the normal text needs to be non-bold.
</blockquote></details>

I tested a few different configuration for this and I think we should keep it as is and then look into it again when we look into fonts and text styles.

**Review by Rawa — APPROVED** [review]
> Reviewed 8 of 9 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Rawa — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6661)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
