### PR TITLE
Add toggle button for split tunneling

### PR DESCRIPTION
**Pull request by MaryamShaghaghi**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5554)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5554)* status: all files reviewed, 1 unresolved discussion (waiting on @MaryamShaghaghi)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5554#-NlNL5g37JdJ4w0uXJ10:-NlNL5g4AveOaVZ7kPuv:b-t1fg41) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7fe0fa4cc11745e1a9f7c7d5689abe3153382ac/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L85)):*
> ```Kotlin
>     }
> 
>     fun onShowAppList(show: Boolean) {
> ```

This should be changed to `enableSplitTunneling` or something similar.

**Review by MaryamShaghaghi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5554)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5554#-NlNL5g37JdJ4w0uXJ10:-NlRzKY53cwitFKo6vvG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7fe0fa4cc11745e1a9f7c7d5689abe3153382ac/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L85)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be changed to `enableSplitTunneling` or something similar.
</blockquote></details>

Done.

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5554#-:-Nlggmsh0EqDu3JQR52b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Pururun** [comment]
Opened a new PR with the same commits here, just adjusted for compose navigation: https://github.com/mullvad/mullvadvpn-app/pull/5554

**Pull request closed without merging**
