### PR TITLE
Bump to K2

### PR DESCRIPTION
**Pull request by Rawa**
This PR aims to bump to K2. For now we wait with KSP2 since there are blocking issues in other projects. 

https://github.com/raamcosta/compose-destinations/pull/643
https://github.com/raamcosta/compose-destinations/issues/545

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397)

### CODE REVIEW

**Comment by Rawa** [comment]
Once PR #6393 is merged, we also should bump compose destinations to "2.1.0-beta09"

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 2 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397)* status: 40 of 73 files reviewed, 1 unresolved discussion (waiting on @Rawa)

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397)* status: 38 of 73 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397#-O0Em6Yw0JnjUf8jPo9p:-O0NCJns09udw6PRLzWa:be74gl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2150d26e21d20221232ed35709cc4427f7e14a9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L141)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As discussed we need a plan for how to handle this case. We should either fix/restore it as part of this PR or as another PR or issue that we work on soon. Would be nice to move all of these `onlyIfResumed` diffs to a separate commit for a better git history.
</blockquote></details>

Fixed :+1: 
___
*[`android/gradle/verification-metadata.xml` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397#-O0Egie69aHkb7aXrtdR:-O0NCP4bBU5MlmKzVQJ-:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af62cd113726a67b35a2ef6cc5103dacdc643148/android/gradle/verification-metadata.xml#L66)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please move the changes to this file into a separate commit called `Update gradle lockfile`. That makes it easier to track things. Also easier to handle since commits that modify this file needs to be signed.
</blockquote></details>

Fixed

**Review by albin-mullvad — APPROVED** [review]
:lgtm: :rocket: 

> Reviewed 22 of 71 files at r1, 8 of 10 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397#-:-O0NZSoLDbK0ayk9X_IN:byykejp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6397)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
