### PR TITLE
Fix flaky actor tests

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR fixes the test that was always broken on the CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)

### CODE REVIEW

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447#-NjhAVRd8GTYQbEOzM4L:-NjhAVRd8GTYQbEOzM4M:b8z3xbl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/937cc43218ba9288f2cafcd5bfe2e400207d0087/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L322)):*
> ```Swift
>         await fulfillment(of: [connectingStateExpectation], timeout: 1)
> 
>         stateSink = await actor.$observedState
> ```

cannot tackle the problem with this?



_Code snippet:_
```Swift
 func testCannotEnterErrorStateWhenStopping() async throws {
        let actor = PacketTunnelActor.mock()

        let initialStateExpectation = expectation(description: "Initial state")
        let connectingStateExpectation = expectation(description: "Connecting state")
        let disconnectedStateExpectation = expectation(description: "Disconnected state")
        let errorStateExpectation = expectation(description: "Should not enter error state")
        errorStateExpectation.isInverted = true

        stateSink = await actor.$observedState
            .receive(on: DispatchQueue.main)
            .sink { newState in
                switch newState {
                case .initial:
                    initialStateExpectation.fulfill()
                case .connecting:
                    connectingStateExpectation.fulfill()
                case .error:
                    errorStateExpectation.fulfill()
                case .disconnected:
                    disconnectedStateExpectation.fulfill()
                default:
                    break
                }
            }
        actor.start(options: launchOptions)
        actor.stop()
        actor.setErrorState(reason: .readSettings)

        await fulfillment(
            of: [
                initialStateExpectation,
                connectingStateExpectation,
                disconnectedStateExpectation,
                errorStateExpectation,
            ],
            timeout: 1,
            enforceOrder: true
        )
```

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447#-NjhAVRd8GTYQbEOzM4L:-NjhDvmrDefEsg7bw5Qy:b-tsj9u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/937cc43218ba9288f2cafcd5bfe2e400207d0087/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L322)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

cannot tackle the problem with this?
</blockquote></details>

or something like this:



_Code snippet:_
```Swift
 func testCannotEnterErrorStateWhenStopping() async throws {
        let actor = PacketTunnelActor.mock()

        let connectingStateExpectation = expectation(description: "Connecting state")
        let disconnectedStateExpectation = expectation(description: "Disconnected state")
        let errorStateExpectation = expectation(description: "Should not enter error state")
        errorStateExpectation.isInverted = true

        stateSink = await actor.$observedState
            .receive(on: DispatchQueue.main)
            .sink { newState in
                switch newState {
                case .connecting:
                    connectingStateExpectation.fulfill()
                case .error:
                    errorStateExpectation.fulfill()
                case .disconnected:
                    disconnectedStateExpectation.fulfill()
                default:
                    break
                }
            }
        actor.start(options: launchOptions)
        actor.stop()
        actor.setErrorState(reason: .readSettings)

        await fulfillment(
            of: [
                connectingStateExpectation,
                disconnectedStateExpectation,
            ],
            timeout: 1,
            enforceOrder: true
        )

        await fulfillment(of: [errorStateExpectation], timeout: Duration.milliseconds(100).timeInterval)
    }
```

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447#-NjhAVRd8GTYQbEOzM4L:-NjhH0a_9GJtajNzA7wF:bwjlxw6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/937cc43218ba9288f2cafcd5bfe2e400207d0087/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L322)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

or something like this:
</blockquote></details>

Unfortunately not. The comment I wrote above this tests explain why we cannot do
```swift
actor.start(options: launchOptions)
actor.stop
```

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447#-NjhAVRd8GTYQbEOzM4L:-NjhHl3d8B3Lu9379Wxy:b-g06mcx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/937cc43218ba9288f2cafcd5bfe2e400207d0087/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L322)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Unfortunately not. The comment I wrote above this tests explain why we cannot do
```swift
actor.start(options: launchOptions)
actor.stop
```
</blockquote></details>

Well, not above the test, but at the start of the function rather

**Review by mojganii — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447#-NjhAVRd8GTYQbEOzM4L:-NjhKhs92yaspfZeTlC6:b-vnbodo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/937cc43218ba9288f2cafcd5bfe2e400207d0087/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L322)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Well, not above the test, but at the start of the function rather
</blockquote></details>

I read the comment at the first glance but the way we are writing test doesn't make sense to me.we have a sequential events that should be called in order.by the way I think if we cannot call start and stop continuously.maybe there is a catch  that should be fixed.
I tried to run test multiple times with the second code snippet,and it passess.have ypu tried the second code before?

**Review by mojganii — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift` line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447#-NjhAVRd8GTYQbEOzM4L:-NjhVAa07yIfGHHYmmnC:bf3sinz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/937cc43218ba9288f2cafcd5bfe2e400207d0087/ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift#L322)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I read the comment at the first glance but the way we are writing test doesn't make sense to me.we have a sequential events that should be called in order.by the way I think if we cannot call start and stop continuously.maybe there is a catch  that should be fixed.
I tried to run test multiple times with the second code snippet,and it passess.have ypu tried the second code before?
</blockquote></details>

talked on Slack

**Pull request merged**
