### PR TITLE
Add CLI support for applying settings patches

### PR DESCRIPTION
**Pull request by dlon**
This adds a command `mullvad import-settings` for applying patches to the settings. It takes a positional argument that should bet set either to a path (for reading from a file) or `-` (from stdin).

Currently, only changes to relay overrides are recognized. Changes to other settings are unrecognized/rejected by the daemon.

Here is an example of a valid patch:

```bash
$ mullvad import-settings -
{
  "relay_overrides": [
    {
      "hostname": "se-got-wg-001",
      "ipv4_addr_in": "1.2.3.4"
    }
  ]
}
```

Related: #5410

Fixes DES-445

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435)

### CODE REVIEW

**Review by MarkusPettersson98 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`mullvad-cli/src/main.rs` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDe6Rm4AYCQVy0k_va:-NjDe6Rn13LMDi40baZv:b-37512o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/main.rs#L140)):*
> ```XML
>     ImportSettings {
>         /// File to read from. If this is "-", read from standard input
>         file: String,
> ```

It would be great if this pattern of reading either from file or from `stdin` could be expressed at the type level, much like https://docs.rs/clap-stdin/latest/clap_stdin/struct.FileOrStdin.html. What do you think?



_Code quote:_
```XML
file: String
```
___
*[`mullvad-cli/src/cmds/import_settings.rs` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDeqZ76PJ7kgLklISE:-NjDeqZ76PJ7kgLklISF:bj4f01y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/cmds/import_settings.rs#L47)):*
> ```XML
> 
> /// Read until EOF or until newline when the last pair of braces has been closed
> fn read_settings_from_reader(mut reader: impl BufRead) -> Result<String> {
> ```

I don't feel too comfortable hand-rolling this JSON-parser in this fashion. Is there no way `serde` could be used to work with structured data instead? :blush: 



_Code quote:_
```XML
read_settings_from_reader
```
___
*[`mullvad-cli/src/cmds/import_settings.rs` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjH2BIz4ihVayL4ntjn:-NjH2BIz4ihVayL4ntjo:b-jgb13v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/cmds/import_settings.rs#L52)):*
> ```XML
>     let mut was_open = false;
>     let mut close_after_newline = false;
>     let mut brace_count = 0;
> ```

Keeping track of braces and making sure that they are balanced is suitably done using a stack (`Vec`), pushing & popping braces as you go. Checking for balance is just checking if the stack is empty :blush:



_Code quote:_
```XML
let mut brace_count = 0;
```
___
*[`mullvad-daemon/src/lib.rs` line 353 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDfFw73poAV-e9DE4B:-NjDfFw73poAV-e9DE4C:b-a2cgs0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/lib.rs#L353)):*
> ```XML
>     VerifyPlayPurchase(ResponseTx<(), Error>, PlayPurchase),
>     /// Patch the settings using a blob of JSON settings
>     ApplyJsonSettings(ResponseTx<(), settings::patch::Error>, String),
> ```

Could we guarantee that this blob is well-formed by defining some appropriate type?:)



_Code quote:_
```XML
String
```
___
*[`mullvad-daemon/src/settings/patch.rs` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjH4Gmx-fe9UpizYfKJ:-NjH4Gmx-fe9UpizYfKK:b6yf64m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/settings/patch.rs#L56)):*
> ```XML
>             | Error::DeserializePatched(_) => Status::invalid_argument(error.to_string()),
>             Error::Settings(error) => Status::from(error),
>             error => Status::unknown(error.to_string()),
> ```

Could the named variable `error` be expanded to the currently-not-covered constructors`Error::SerializeSettings(_) | Error::RecursionLimit`? If `Error` ever was to change, it would be nice to trigger a compiler-error here



_Code quote:_
```XML
error
```
___
*[`mullvad-daemon/src/settings/patch.rs` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjH83s9BdYuO7JJkeFt:-NjH83s9BdYuO7JJkeFu:b-mhtt8k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/settings/patch.rs#L172)):*
> ```XML
>             "existing overrides should be array",
>         ));
>     };
> ```

You can apply the same pattern of calling `ok_or(Error::InvalidOrMissingValue(..))`, as is done below

```rust
    let patch_array = patch.as_array().ok_or(Error::InvalidOrMissingValue(
        "relay overrides must be array",
    ))?;
    let current_array = current_settings
        .as_array()
        .ok_or(Error::InvalidOrMissingValue(
            "existing overrides should be array",
        ))?;
```



_Code quote:_
```XML
    let Some(patch_array) = patch.as_array() else {
        return Err(Error::InvalidOrMissingValue(
            "relay overrides must be array",
        ));
    };

    let Some(current_array) = current_settings.as_array() else {
        return Err(Error::InvalidOrMissingValue(
            "existing overrides should be array",
        ));
    };
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435)* status: all files reviewed, 6 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-cli/src/cmds/import_settings.rs` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDeqZ76PJ7kgLklISE:-NjHcjLLBEX-AEVqiZZt:b-8j7ao5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/cmds/import_settings.rs#L47)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I don't feel too comfortable hand-rolling this JSON-parser in this fashion. Is there no way `serde` could be used to work with structured data instead? :blush:
</blockquote></details>

We're not really parsing anything here. We're just figuring out when to stop reading from stdin.
___
*[`mullvad-cli/src/cmds/import_settings.rs` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjH2BIz4ihVayL4ntjn:-NjHcf7_6zb6VfAPdfA2:b-ahj7vk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/cmds/import_settings.rs#L52)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Keeping track of braces and making sure that they are balanced is suitably done using a stack (`Vec`), pushing & popping braces as you go. Checking for balance is just checking if the stack is empty :blush:
</blockquote></details>

Done. (Used solution from AFK discussion.)
___
*[`mullvad-daemon/src/lib.rs` line 353 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDfFw73poAV-e9DE4B:-NjHM_3_A_HxE9s6FSJY:bxgye9v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/lib.rs#L353)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Could we guarantee that this blob is well-formed by defining some appropriate type?:)
</blockquote></details>

The function is supposed to allow clients to feed *any string* to the daemon. It's up to the daemon to handle all of the parsing.
___
*[`mullvad-daemon/src/settings/patch.rs` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjH4Gmx-fe9UpizYfKJ:-NjHcQDZ2kS8p8so9i2G:bctpdcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/settings/patch.rs#L56)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Could the named variable `error` be expanded to the currently-not-covered constructors`Error::SerializeSettings(_) | Error::RecursionLimit`? If `Error` ever was to change, it would be nice to trigger a compiler-error here
</blockquote></details>

Makes sense. Done.
___
*[`mullvad-daemon/src/settings/patch.rs` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjH83s9BdYuO7JJkeFt:-NjHcVEw8sbi4YXy_4V1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/settings/patch.rs#L172)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

You can apply the same pattern of calling `ok_or(Error::InvalidOrMissingValue(..))`, as is done below

```rust
    let patch_array = patch.as_array().ok_or(Error::InvalidOrMissingValue(
        "relay overrides must be array",
    ))?;
    let current_array = current_settings
        .as_array()
        .ok_or(Error::InvalidOrMissingValue(
            "existing overrides should be array",
        ))?;
```
</blockquote></details>

Done.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-cli/src/main.rs` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDe6Rm4AYCQVy0k_va:-NjMKmgY8XXTMscQB9kd:bd1rr6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/main.rs#L140)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

It would be great if this pattern of reading either from file or from `stdin` could be expressed at the type level, much like https://docs.rs/clap-stdin/latest/clap_stdin/struct.FileOrStdin.html. What do you think?
</blockquote></details>

That does look nicer! But given how simple it is, and that we only use it once, it's probably not worth it? We also cannot just use that crate because it doesn't terminate when it's received a complete json string

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-:-NjNE500AhoONyAq6qWB:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-cli/src/main.rs` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDe6Rm4AYCQVy0k_va:-NjNCaHm9kED0sHHxej9:b3zslfi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/main.rs#L140)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

That does look nicer! But given how simple it is, and that we only use it once, it's probably not worth it? We also cannot just use that crate because it doesn't terminate when it's received a complete json string
</blockquote></details>

If we do it twice, I definitely think it's worth it. But for now this is okay :blush: 
___
*[`mullvad-cli/src/cmds/import_settings.rs` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDeqZ76PJ7kgLklISE:-NjNAxFF0qy-Lzv4oiPm:b-dpl6uh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-cli/src/cmds/import_settings.rs#L47)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We're not really parsing anything here. We're just figuring out when to stop reading from stdin.
</blockquote></details>

Got that after out talk AFK, so I feel pleased with this.
___
*[`mullvad-daemon/src/lib.rs` line 353 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-NjDfFw73poAV-e9DE4B:-NjNBoY7B3QF47CU_Zgo:b-6wchmc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/210962431621d5dd87af5cb20b4c54431ab42a95/mullvad-daemon/src/lib.rs#L353)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The function is supposed to allow clients to feed *any string* to the daemon. It's up to the daemon to handle all of the parsing.
</blockquote></details>

That's fair

**Review by Jontified — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435#-:-NjN_Wdc04Z09crCkVcl:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

**Pull request merged**
