### PR TITLE
Add a staging configuration that automatically targets the staging environment

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR creates a staging environment. The API endpoint and IP are now hardcoded in the `Api.xcconfig` file.
The API endpoint and IP address are now loaded and stored in the `Info.plist` files of both the packet tunnel and the main host application.

In order to use the staging environment, In Xcode go to the following menu :
Product > Scheme > Edit Scheme 
In the `Run` section, select the `Staging` environment 

Screenshot 2024-01-11 at 09 55 36

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 

If you want to test this PR
- Copy the `Api.xcconfig.template` file and replace the values with the API endpoint, and the staging endpoint.
- Delete the application from your device
- Select the `Staging` build scheme
- Install the application

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)

### CODE REVIEW

**Comment by buggmagnet** [comment]
Looks like I forgot about GH CI, will fix soon

**Review by pinkisemils — COMMENTED** [review]
Works like a charm. :lgtm: 

> Reviewed 4 of 10 files at r1, 8 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677#-:-Nny15hB1xRV2gjCsFH7:b-5peipc)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Review by rablador — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6443 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677#-NnsymGX-RWs0sa7cray:-Nny4KJU9K1ndwSpZo6G:b-ba7jdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6cf9d47e7d17c80570bfaba85e454cf848e4f5d/ios/MullvadVPN.xcodeproj/project.pbxproj#L6443)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could we also change the _fake release_ schema to be a build configuration? Then we have less schemas, which I see as only a good thing. And the only thing that's different for the fake release is that the debug flag is *not* set.
</blockquote></details>

Sounds good to me

**Review by rablador — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6975 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677#-NoCCXd6706EMPyDraiX:-NoCCXd6706EMPyDraiY:bp8tqur) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb4cfb3ae68fe85b14667cc1a7ba09b3eb2be4f0/ios/MullvadVPN.xcodeproj/project.pbxproj#L6975)):*
> ```
> 			isa = XCBuildConfiguration;
> 			buildSettings = {
> 				ALWAYS_SEARCH_USER_PATHS = NO;
> ```

Can this be inherited from other the base config?

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6975 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677#-NoCCXd6706EMPyDraiX:-NoCMXEWDb7I9kMb0JX2:b-ra7c2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb4cfb3ae68fe85b14667cc1a7ba09b3eb2be4f0/ios/MullvadVPN.xcodeproj/project.pbxproj#L6975)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Can this be inherited from other the base config?
</blockquote></details>

According to [the documentation](https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project/), we should be able to use `$(inherited)` to do that.
Any setting we find in [this list](https://developer.apple.com/documentation/xcode/build-settings-reference) should be overridable via `xcconfig` files

**Review by rablador — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
:lgtm:, still :) 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5677#-:-NoMi5Ql7BxuVL8guzVR:bk1gn3o)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
