### PR TITLE
Wireup controller delegates

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Wire up delegates for `LoginViewController`, `ConnectViewController` and `SelectLocationViewController`.
2. Move relay constraints fetching and updating into `AppDelegate`
3. Handle `RelayCache` updates in `AppDelegate`
4. Overall consoldiate the view controller management in `AppDelegate`. Move showing the account controller for expired accounts after login from `ConnectViewController` to `AppDelegate`.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)* status: 0 of 6 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/ConsentViewController.swift, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-MZrlCSr4bIhj_9LaUSz:-MZrlCSr4bIhj_9LaUT-:b91jwvk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d72abef52e0b0b38297bf3e11656817e78bfb6a/ios/MullvadVPN/ConsentViewController.swift#L22)):*
> ```Swift
>     }
> 
>     var preferredHeaderBarPresentation: HeaderBarPresentation {
> ```

FYI My bad, `HeaderBarPresentation` was added much later, so I reversed the change to make `master` build and run with no issues.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)* status: 0 of 6 files reviewed, all discussions resolved

___
*[ios/MullvadVPN.xcodeproj/project.pbxproj, line 882 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-MZrlMK3DMYp4W_BEKWH:-MZrlMK3DMYp4W_BEKWI:b-1brzp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d72abef52e0b0b38297bf3e11656817e78bfb6a/ios/MullvadVPN.xcodeproj/project.pbxproj#L882)):*
> ```
> 			buildActionMask = 2147483647;
> 			files = (
> 				58D9AF6B2501111800B6FAB5 /* ConnectViewController.xib in Resources */,
> ```

FYI: Left over, the file was removed long ago.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)* status: 0 of 6 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppDelegate.swift, line 264 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-MZrm-r68Ek80HUvCf5F:-MZrm-r68Ek80HUvCf5G:b-k6m4kp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c70dd1236083d0778fad4fd50c2b0ec0170f6a7/ios/MullvadVPN/AppDelegate.swift#L264)):*
> ```Swift
>             return [.portrait]
>         default:
>             return controller.supportedInterfaceOrientations
> ```

FYI just to avoid `fatalError()`. We never enter this code path anyway.

**Review by jvff — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)* status: 4 of 6 files reviewed, all discussions resolved

**Review by jvff — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)* status: 5 of 6 files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-:-MZsO7vHD0IGCJ_0_aTQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/AppDelegate.swift, line 418 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-MZsNXipEwHLYdGnlhWZ:-MZsNXipEwHLYdGnlhW_:b6idxu4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3a0236984f9374b24c4de932ea80e8b36d6694e/ios/MullvadVPN/AppDelegate.swift#L418)):*
> ```Swift
>             }
>         }
>     }
> ```

Nit: Not sure if this helps, but the completion of `connectTunnel` and `disconnectTunnel` seem similar enough that they could maybe be a separate method `handleTunnelState(successMessage, errorMessage)`. Just an idea :sweat_smile:

**Comment by axti** [comment]
___
*[ios/MullvadVPN/AppDelegate.swift, line 418 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-MZsNXipEwHLYdGnlhWZ:-MZvOv_v2JlAPduMZGm6:badjoxg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3a0236984f9374b24c4de932ea80e8b36d6694e/ios/MullvadVPN/AppDelegate.swift#L418)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Not sure if this helps, but the completion of `connectTunnel` and `disconnectTunnel` seem similar enough that they could maybe be a separate method `handleTunnelState(successMessage, errorMessage)`. Just an idea :sweat_smile: 
</blockquote></details>

The call inside .failure is looks same, but with different params.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @axti and @jvff)

___
*[ios/MullvadVPN/AppDelegate.swift, line 418 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721#-MZsNXipEwHLYdGnlhWZ:-MZvj-zn19N3DmDmDI8D:b-qccvuo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3a0236984f9374b24c4de932ea80e8b36d6694e/ios/MullvadVPN/AppDelegate.swift#L418)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

The call inside .failure is looks same, but with different params.
</blockquote></details>

Good spot! Extracted the `UIAlertController` into a method.

**Pull request merged**
