### PR TITLE
Fix shellcheck recommendations in build.sh

### PR DESCRIPTION
**Pull request by raksooo**
This PR makes some changes to the build-script that was recommended by `shellcheck` and a few other improvements. I've added comments with links that explain the changes.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667)

### CODE REVIEW

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667)* status: 0 of 1 files reviewed, all discussions resolved

___
*[build.sh, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFhh54502MOpa8SYeU:-MYFhh54502MOpa8SYeV:bvr6db2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L16)):*
> ```Shell
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> cd "$SCRIPT_DIR"
> RUSTC_VERSION=$(rustc +stable --version)
> ```

https://github.com/koalaman/shellcheck/wiki/SC2006
___
*[build.sh, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFhW4fDAVztQHvhmp_:-MYFhW4fDAVztQHvhmpa:b39dz2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L21)):*
> ```Shell
> 
> CARGO_ARGS=()
> NPM_PACK_ARGS=()
> ```

https://github.com/koalaman/shellcheck/wiki/SC2086#exceptions
___
*[build.sh, line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFiHOUEUFQpTLY5aUr:-MYFiHOUEUFQpTLY5aUs:b-3v0k5g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L34)):*
> ```Shell
>     fi
> 
>     if [[ "$(uname -s)" == "Darwin" || "$(uname -s)" == "MINGW"* ]]; then
> ```

Not suggested by shellcheck. Suggested by @faern .
___
*[build.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFiP4W2Vmg-2udbjs4:-MYFiP4W2Vmg-2udbjs5:b-9z42nh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L46)):*
> ```Shell
>             export CSC_KEY_PASSWORD
>         fi
>         # MacOS: This needs to be set to 'true' to activate signing, even when CSC_LINK is set.
> ```

Just correcting spelling
___
*[build.sh, line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFhqi8-Xh7uNBhskPZ:-MYFhqi8-Xh7uNBhskP_:bvr6e8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L93)):*
> ```Shell
>                 -du "https://github.com/mullvad/mullvadvpn-app#readme" \
>                 -f "$CERT_FILE" \
>                 -p "$CERT_PASSPHRASE" "$binary"
> ```

https://github.com/koalaman/shellcheck/wiki/SC2181
___
*[build.sh, line 121 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFhv0d6e1JFRGvD1lB:-MYFhv0d6e1JFRGvD1lC:bvr6dhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L121)):*
> ```Shell
> echo "Updating version in metadata files..."
> cp Cargo.lock Cargo.lock.bak
> ./version-metadata.sh inject "$PRODUCT_VERSION" --desktop
> ```

https://github.com/koalaman/shellcheck/wiki/SC2086
___
*[build.sh, line 236 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFi75x1RwJS-tnavAn:-MYFi75x1RwJS-tnavAo:bvr6dhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L236)):*
> ```Shell
> popd
> 
> SEMVER_VERSION=$(echo "$PRODUCT_VERSION" | sed -Ee 's/($|-.*)/.0\1/g')
> ```

https://github.com/koalaman/shellcheck/wiki/SC2086
___
*[build.sh, line 237 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFi4RY9UmDr1XNMnN8:-MYFi4RY9UmDr1XNMnN9:bvr6euw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L237)):*
> ```Shell
> 
> SEMVER_VERSION=$(echo "$PRODUCT_VERSION" | sed -Ee 's/($|-.*)/.0\1/g')
> for semver_path in dist/*"$SEMVER_VERSION"*; do
> ```

https://github.com/koalaman/shellcheck/wiki/SC2231
___
*[build.sh, line 238 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFi8oa1fPy4aLcAA_t:-MYFi8oa1fPy4aLcAA_u:bvr6dhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L238)):*
> ```Shell
> SEMVER_VERSION=$(echo "$PRODUCT_VERSION" | sed -Ee 's/($|-.*)/.0\1/g')
> for semver_path in dist/*"$SEMVER_VERSION"*; do
>     product_path=$(echo "$semver_path" | sed -Ee "s/$SEMVER_VERSION/$PRODUCT_VERSION/g")
> ```

https://github.com/koalaman/shellcheck/wiki/SC2086
___
*[build.sh, line 240 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFi9htELEwng5JoaxT:-MYFi9hu95FaUfQHEk6s:bvr6dhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L240)):*
> ```Shell
>     product_path=$(echo "$semver_path" | sed -Ee "s/$SEMVER_VERSION/$PRODUCT_VERSION/g")
>     echo "Moving $semver_path -> $product_path"
>     mv "$semver_path" "$product_path"
> ```

https://github.com/koalaman/shellcheck/wiki/SC2086

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[build.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFiP4W2Vmg-2udbjs4:-MYJpOKABPi4-vCx2OEO:beskbm6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L46)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Just correcting spelling
</blockquote></details>

To be nitpicky is it not `macOS`? Even the English wikipedia page starts with lower case `m` in the title.
___
*[build.sh, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYJpg6v8yAZVUNM-lRL:-MYJpg6v8yAZVUNM-lRM:bocyfls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L61)):*
> ```Shell
> else
>     BUILD_MODE="dev"
>     NPM_PACK_ARGS+=(--no-compression)
> ```

Very nice to not have to know that this is the first place the args list is used, but it's defined empty before and we always just add to it :+1:
___
*[build.sh, line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYJqUy_DryKXmW9pr9K:-MYJqUy_DryKXmW9pr9L:b-5hpul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L81)):*
> ```Shell
> fi
> 
> sign_win() {
> ```

Since this is just a cleanup PR I feel I can be nitpicky. This script was written before most of our bash coding guidelines were in place. We prefer to use the `function` keyword on functions: https://github.com/mullvad/coding-guidelines/blob/master/bash.md#functions

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[build.sh, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYFiP4W2Vmg-2udbjs4:-MYKvJEV8hLznkqFYBEZ:b-pkzycw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

To be nitpicky is it not `macOS`? Even the English wikipedia page starts with lower case `m` in the title.
</blockquote></details>

Yes, fixed.
___
*[build.sh, line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-MYJqUy_DryKXmW9pr9K:-MYKvVUxEsckY9aRjA_I:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2d478bbecae2e7f2fb1db8ee3d319cc71e78f4b/build.sh#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since this is just a cleanup PR I feel I can be nitpicky. This script was written before most of our bash coding guidelines were in place. We prefer to use the `function` keyword on functions: https://github.com/mullvad/coding-guidelines/blob/master/bash.md#functions
</blockquote></details>

Done.

**Review by faern — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667#-:-MYKvtSADqdrUkepfZTi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
