### PR TITLE
Add tray support on Windows

### PR DESCRIPTION
**Pull request by pronebird**
Checklist for a PR:

* [X] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.

No changes to CHANGELOG since windows version is not published yet.

This PR:

1. Updates Electron to 1.8.3
2. Adds support for tray icon on Windows
3. Patches the RPC file owner check. We discovered that currently when running under admin the owner for rpc file is reported to be `Builtin/Administrators`. This may change after we introduce services.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/90)

### CODE REVIEW

**Comment by jvff** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/main.js, line 310 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90#-L6vgBkytsq_9iJmuOUK:-L6vgBkytsq_9iJmuOUL:b635c8l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37eaaec1293fe3748ff11877e666062c041338f3/app/main.js#L310)):*
> ```JavaScript
>       });
> 
>         // make the window visible on all workspaces
> ```

Might look better if the comment is aligned with the line below it.

---

*[app/main.js, line 416 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90#-L6vgi4cvarfo9mZnrN8:-L6vgi4cvarfo9mZnrN9:b-equjbf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37eaaec1293fe3748ff11877e666062c041338f3/app/main.js#L416)):*
> ```JavaScript
>     case 'win32': {
>       // taskbar occupies some part of the screen excluded from work area
>       const primaryDisplay = electron.screen.getPrimaryDisplay();
> ```

Does this also work with "auto-hide" and/or third-party taskbars?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90)*

**Comment by eriklarko** [comment]
Good job Andrei! :lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/90#-:-L6wfkc155BCxpQnYR-c:blrougb)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/main.js, line 310 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90#-L6vgBkytsq_9iJmuOUK:-L7-2ufIvoM0jDaXX-cM:b-809z95) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37eaaec1293fe3748ff11877e666062c041338f3/app/main.js#L310)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Might look better if the comment is aligned with the line below it.
</blockquote></details>

Wow lint didn't catch this. I am surprised. Thanks for pointing that out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90)*

**Comment by pronebird** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/main.js, line 416 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90#-L6vgi4cvarfo9mZnrN8:-L7-7-bxv4n7O4H1Z0oy:b-s3heht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37eaaec1293fe3748ff11877e666062c041338f3/app/main.js#L416)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Does this also work with "auto-hide" and/or third-party taskbars?
</blockquote></details>

That's a good point, I technically handle that but I am not sure if that shrinks the workarea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90)*

**Comment by jvff** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[app/main.js, line 416 at r1](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90#-L6vgi4cvarfo9mZnrN8:-L7-KphAQIms66n5Elkb:bt08jqf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37eaaec1293fe3748ff11877e666062c041338f3/app/main.js#L416)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

That's a good point, I technically handle that but I am not sure if that shrinks the workarea.
</blockquote></details>

The code works as expected. Except when the taskbar auto-hides I center the window on screen, we may want to change that. But there are many small things like this that we need to fix and I have no idea at this point what the right behavior is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/mullvadvpn-app/90)*

**Comment by jvff** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/main.js, line 416 at r1](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/90#-L6vgi4cvarfo9mZnrN8:-L7-NRTu0rMOSsF_5Ot4:bj6wzt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/37eaaec1293fe3748ff11877e666062c041338f3/app/main.js#L416)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

The code works as expected. Except when the taskbar auto-hides I center the window on screen, we may want to change that. But there are many small things like this that we need to fix and I have no idea at this point what the right behavior is.
</blockquote></details>

Agreed, postpone the fine-tuning for later, with more discussion on the expected behavior.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/mullvadvpn-app/90)*

**Pull request merged**
