### PR TITLE
Fix end to end test build script

### PR DESCRIPTION
**Pull request by buggmagnet**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910)

### CODE REVIEW

**Review by niklasberglund — CHANGES_REQUESTED** [review]
The end to end tests README also mention `rustup target install` instead of `add` https://github.com/mullvad/mullvadvpn-app/blob/main/ios/MullvadVPNUITests/README.md#set-up-of-runner-environment

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910#-:-NsN49eGDlmHkCG4oRkZ:b4306la)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910#-NsN1aaZAg6Jp6M3olJl:-NsN1aaZAg6Jp6M3olJm:bgrdtww) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c6c854bb8790c36c9631769b4cb127c2018ca9d/.github/workflows/ios-end-to-end-tests.yml#L33)):*
> ```YAML
> 
>       - name: Configure Rust
>         run: rustup target install aarch64-apple-ios aarch64-apple-ios-sim
> ```

The fix is good but I started thinking if we should remove the Rust and Go setup actions, what do you think? Because its a self-hosted runner installed dependencies are persistent. Rust and Go are already installed manually https://github.com/mullvad/mullvadvpn-app/blob/main/ios/MullvadVPNUITests/README.md#set-up-of-runner-environment so don't have to attempt to install them here. Its easier to maintain version numbers of dependencies when its specified in the workflow file rather than manually installed on the computer though. We could also remove the manual steps from the README.

**Review by buggmagnet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910#-NsN1aaZAg6Jp6M3olJl:-NsN5x6U16kQS_PB6IEf:b-qleijq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c6c854bb8790c36c9631769b4cb127c2018ca9d/.github/workflows/ios-end-to-end-tests.yml#L33)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

The fix is good but I started thinking if we should remove the Rust and Go setup actions, what do you think? Because its a self-hosted runner installed dependencies are persistent. Rust and Go are already installed manually https://github.com/mullvad/mullvadvpn-app/blob/main/ios/MullvadVPNUITests/README.md#set-up-of-runner-environment so don't have to attempt to install them here. Its easier to maintain version numbers of dependencies when its specified in the workflow file rather than manually installed on the computer though. We could also remove the manual steps from the README.
</blockquote></details>

We can do that in a separate PR

**Review by niklasberglund — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910#-:-NsNBtMT82oWSLyLU6ON:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910#-NsN1aaZAg6Jp6M3olJl:-NsNBr98E2BQQ6Zt4GKl:b-xi16tv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c6c854bb8790c36c9631769b4cb127c2018ca9d/.github/workflows/ios-end-to-end-tests.yml#L33)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can do that in a separate PR
</blockquote></details>

Yes, sounds good 👍

**Review by niklasberglund — COMMENTED** [review]
`xcodebuild` is failing with error code 65. I did a test run from this branch https://github.com/mullvad/mullvadvpn-app/actions/runs/8185722159

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910#-:-NsNChwt9ktB1_eronzQ:b1qu8dv)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

**Pull request merged**
