### PR TITLE
Clamp tunnel MTU after obfuscation overhead adjustment

### PR DESCRIPTION
**Pull request by dlon**
Fix DES-1354.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046)

### CODE REVIEW

**Review by hulthe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-wireguard/src/lib.rs` line 1112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046#-O9sKN47DHwXQbEZeKDF:-O9sKN47DHwXQbEZeKDG:bnkifi2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795f1632a5030aaf31e4cf5910848bd1f90b5fab/talpid-wireguard/src/lib.rs#L1112)):*
> ```XML
> 
> #[cfg(not(any(target_os = "linux", target_os = "windows")))]
> async fn get_desired_mtu(params: &TunnelParameters) -> u16 {
> ```

These are cfg-gated on `linux || windows` but they are called from a function that's gated on `android`, i.e. it's bork on macos

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hulthe)

___
*[`talpid-wireguard/src/lib.rs` line 1112 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046#-O9sKN47DHwXQbEZeKDF:-O9sMUOr8krU7-jNmqaC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795f1632a5030aaf31e4cf5910848bd1f90b5fab/talpid-wireguard/src/lib.rs#L1112)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

These are cfg-gated on `linux || windows` but they are called from a function that's gated on `android`, i.e. it's bork on macos
</blockquote></details>

Done.

**Review by hulthe — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by hulthe — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
