### PR TITLE
Install/update split tunnel driver on demand

### PR DESCRIPTION
**Pull request by dlon**
This PR updates the daemon to check whether the driver service needs to be installed each time it starts. Previously, this was handled in the installer.

Improvements:

* The main purpose of the PR is increased robustness. It fixes issues caused by other software (or users) removing, stopping, or installing incompatible versions of the driver/service.
* Easier to maintain, as more things are handled in Rust instead of NSIS script.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 2 of 17 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA7zwiF1PhTBZQXcyk8:-NA7zwiF1PhTBZQXcyk9:b-4h5tgd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76be40610ca1171ef64b6ca6a4562ef4d1761d58/talpid-core/src/split_tunnel/windows/service.rs#L25)):*
> ```XML
> 
> const SPLIT_TUNNEL_SERVICE: &[u8] =
>     b"m\0u\0l\0l\0v\0a\0d\0-\0s\0p\0l\0i\0t\0-\0t\0u\0n\0n\0e\0l\0\0\0";
> ```

Would using `widestrings` here be too cumbersome?
___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA8-lC4EFsQXrhyoSuM:-NA8-lC4EFsQXrhyoSuN:b-x4pegq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76be40610ca1171ef64b6ca6a4562ef4d1761d58/talpid-core/src/split_tunnel/windows/service.rs#L106)):*
> ```XML
>             };
>         }
>     };
> ```

This could be an instance method for `ScopedServiceHandle`, no? Or would it then be `STDriverServiceHandle`?



_Code quote:_
```XML
    let service = unsafe {
        OpenServiceW(
            scm.0,
            PCWSTR(SPLIT_TUNNEL_SERVICE as *const _ as *const u16),
            SERVICE_ALL_ACCESS,
        )
        .map(ScopedServiceHandle)
    };

    let service = match service {
        Ok(service) => service,
        Err(error) => {
            return if error.code() == ERROR_SERVICE_DOES_NOT_EXIST.to_hresult() {
                // TODO: could be marked for deletion
                unsafe { install_driver(scm.0, &expected_syspath) }
            } else {
                Err(Error::OpenServiceHandle(windows::core::Error::from(error)))
            };
        }
    };
```
___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA8-zAb2A6uC6ZMaqYn:-NA8-zAb2A6uC6ZMaqYo:b-6rz3up) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76be40610ca1171ef64b6ca6a4562ef4d1761d58/talpid-core/src/split_tunnel/windows/service.rs#L142)):*
> ```XML
>     DeleteService(service);
> 
>     // TODO: handle error
> ```

This and the above are pretty serious TODOs - if the daemon fails to remove the device, what can it possibly do here?
___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA80Bpw43hUAiDtFJVs:-NA80Bpw43hUAiDtFJVt:b-jwvtp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76be40610ca1171ef64b6ca6a4562ef4d1761d58/talpid-core/src/split_tunnel/windows/service.rs#L215)):*
> ```XML
> }
> 
> unsafe fn get_driver_binpath(service: SC_HANDLE) -> Result<OsString, Error> {
> ```

Would most of these functions need to be outright `unsafe` if the inputs (namely, `SC_HANDLE`) was wrapped in a type that'd always guarantee a valid handle to the expected service? If yes, then these should be reworked to then contain the unsafe code in smaller blocks here. 

In general, we should *always* be trying to use the smallest possible unsafe blocks.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 10 of 17 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 12 of 17 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA80Bpw43hUAiDtFJVs:-NA82ycv6zlb_NdeX9Ei:b-qbyg05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76be40610ca1171ef64b6ca6a4562ef4d1761d58/talpid-core/src/split_tunnel/windows/service.rs#L215)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would most of these functions need to be outright `unsafe` if the inputs (namely, `SC_HANDLE`) was wrapped in a type that'd always guarantee a valid handle to the expected service? If yes, then these should be reworked to then contain the unsafe code in smaller blocks here. 

In general, we should *always* be trying to use the smallest possible unsafe blocks.
</blockquote></details>

Reviewing commit-by-commit is hard.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 13 of 17 files reviewed, all discussions resolved (waiting on @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 78 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA872iN2aC0YRAeVUQm:-NA872iN2aC0YRAeVUQn:bmp8zqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/879b1c0a63d9f7647cd91d37a698769c80765040/talpid-core/src/split_tunnel/windows/service.rs#L78)):*
> ```XML
>                     if io_error.raw_os_error() == Some(ERROR_SERVICE_DOES_NOT_EXIST as i32) =>
>                 {
>                     // TODO: could be marked for deletion
> ```

Should the code here wait until it gets deleted before installing again?

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 78 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA872iN2aC0YRAeVUQm:-NA8jP8sAM_II3vrF7Rw:b2yo0k1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/879b1c0a63d9f7647cd91d37a698769c80765040/talpid-core/src/split_tunnel/windows/service.rs#L78)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should the code here wait until it gets deleted before installing again?
</blockquote></details>

If this happens, you're likely going to have to reboot. So I'm not sure if there is much one can do.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 78 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA872iN2aC0YRAeVUQm:-NAE0YFM9DUCb7wO-QQs:brj84us) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/879b1c0a63d9f7647cd91d37a698769c80765040/talpid-core/src/split_tunnel/windows/service.rs#L78)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think if you're in that situation (e.g., if the service gets stuck), you're often going to have to reboot. So I'm not sure if there is much one can do.
</blockquote></details>

Would bubbling this error up to the user be practical?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/service.rs` line 78 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NA872iN2aC0YRAeVUQm:-NAJ6MpzCo5sfuf1cny5:bsfvxz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/879b1c0a63d9f7647cd91d37a698769c80765040/talpid-core/src/split_tunnel/windows/service.rs#L78)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would bubbling this error up to the user be practical?
</blockquote></details>

The daemon will fail to init if this fails anyway, so we have no way of doing that. I think it would make sense to make split tunneling fully optional, but that requires making some large changes that I won't make here.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r8, 11 of 11 files at r9, 4 of 4 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`dist-assets/windows/installer.nsh` line 1082 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NAK7F1NE8wAVKKUL56V:-NAK7F1NE8wAVKKUL56W:b-y0atjl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddf6a89532e76b2581625e0d0797d347b0526e31/dist-assets/windows/installer.nsh#L1082)):*
> ```NSIS
> 
> 	${If} $R0 != 0
> 		Goto customRemoveFiles_abort
> ```

This `if` block should be moved up to the `StopAndDeleteService`. I take no credit for finding this, this is all on you.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`dist-assets/windows/installer.nsh` line 1082 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767#-NAK7F1NE8wAVKKUL56V:-NAKPn8q-BPoY0IuJ-XS:bv4z9yh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddf6a89532e76b2581625e0d0797d347b0526e31/dist-assets/windows/installer.nsh#L1082)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This `if` block should be moved up to the `StopAndDeleteService`. I take no credit for finding this, this is all on you.
</blockquote></details>

I realized you were right that `$R0` should be checked again. So I did that as well.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3767)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
