### PR TITLE
Improve Purchase api verification

### PR DESCRIPTION
**Pull request by Pururun**
1) Add exponential back off for purchase verification
2) Add purchase verification after a purchase flow has failed

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)

### CODE REVIEW

**Review by sabercodic — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NkL9Dig3JHS7svxm8w4:-NkL9Dih--0wrO3pfx33:b-elfmec) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94b35d594053e8aea6974195565188751d01e892/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L57)):*
> ```Kotlin
>                 backOffDelayFactor = VERIFICATION_BACK_OFF_FACTOR
>             ) {
>                 it is VerificationResult.Error
> ```

Does it work on both VerificationError and BillingError?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NkL9Dig3JHS7svxm8w4:-NkPcIaIA0oIpVegP4Sf:b-y1q6wr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94b35d594053e8aea6974195565188751d01e892/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt#L57)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Does it work on both VerificationError and BillingError?
</blockquote></details>

The idea is that it will retry on both billing error (unable to retrieve any purchase from Google) or VerificationError (unable to verify with our api).

**Review by sabercodic — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 138 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NkUd6n1-1jLQUxMFGl7:-NkUd6n1-1jLQUxMFGl8:b-731qvs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94b35d594053e8aea6974195565188751d01e892/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L138)):*
> ```Kotlin
> 
> @Suppress("UNCHECKED_CAST")
> suspend inline fun <T> Flow<T>.retryWhen(
> ```

Can we go with better naming here?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 138 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NkUd6n1-1jLQUxMFGl7:-NkZwMF4Ae3usJJ_kXl2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94b35d594053e8aea6974195565188751d01e892/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L138)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Can we go with better naming here?
</blockquote></details>

Done.

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 152 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-Nk_rUen9TYEKEXIMNTw:-Nk_rUen9TYEKEXIMNTx:b-9q9lhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65993f5a5ef20f10e77259f8781f3fc597c355ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L152)):*
> ```Kotlin
>         }
>         .retryWhen { cause, attempt ->
>             if (attempt < maxAttempts) {
> ```

Small detail that I think makes it a bit more readable, we should early terminate if it is possible. E.g in this case:

```
if(attempt >= maxAttemps) {
   return false
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 154 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-Nk_oT5P3JdoMKtCwOMP:-Nk_oT5P3JdoMKtCwOMQ:bg22xh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65993f5a5ef20f10e77259f8781f3fc597c355ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L154)):*
> ```Kotlin
>             if (attempt < maxAttempts) {
>                 delay(backOffDelay)
>                 backOffDelay *= backOffDelayFactor
> ```

Suggestion: We simply calculate this value every single time, then we don't have to bother modifying the `var`. 

```
fun Long.pow(exponent: Int): Long = toDouble().pow(exponent).toLong()
initialBackOffDelay * backOffDelayFactor.pow(attempt)
```

Start of the function would be more clear as well:
```
): Flow<T> = map {
```

**Review by sabercodic — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by sabercodic — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-:-Nk_tC4A0_HFfWwHTlqj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 154 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-Nk_oT5P3JdoMKtCwOMP:-NknrisP9s9ZemFYcPfL:b-k3pv94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65993f5a5ef20f10e77259f8781f3fc597c355ce/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L154)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Suggestion: We simply calculate this value every single time, then we don't have to bother modifying the `var`. 

```
fun Long.pow(exponent: Int): Long = toDouble().pow(exponent).toLong()
initialBackOffDelay * backOffDelayFactor.pow(attempt)
```

Start of the function would be more clear as well:
```
): Flow<T> = map {
```
</blockquote></details>

nice :+1: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 144 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NknrlEd401zBiPVRg9r:-NknrlEd401zBiPVRg9s:b-pzu2pu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/082578aed5914f580ba4a1a7f811a03c9e8a85b7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L144)):*
> ```Kotlin
>     crossinline predicate: (T) -> Boolean,
> ): Flow<T> =
>     this.map {
> ```

Do we need this? Shouldn't it be possible to remove?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 144 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NknrlEd401zBiPVRg9r:-NkoUqBD94ug2hAt__cG:b-e2y4no) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/082578aed5914f580ba4a1a7f811a03c9e8a85b7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L144)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we need this? Shouldn't it be possible to remove?
</blockquote></details>

Not sure I follow what should be removed?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt` line 144 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512#-NknrlEd401zBiPVRg9r:-NkorYDN-HmVmAUbdBgp:btlapqg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/082578aed5914f580ba4a1a7f811a03c9e8a85b7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt#L144)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`this.map` -> `map`, sorry it wasn't very clear that i meant the keyword `this` ^^
</blockquote></details>

Ah yes, that could be removed. Done

**Pull request merged**
