### PR TITLE
storing custom list into settings

### PR DESCRIPTION
**Pull request by mojganii**
Storing custom lists in settings enhances the app's ability to access user preferences for relay connections.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadSettings/CustomList.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq26NYJ6wlef96UEs-b:-Nq26NYJ6wlef96UEs-c:b-vr2k4j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadSettings/CustomList.swift#L15)):*
> ```Swift
>     public let id: UUID
>     public var name: String
>     public var list: [RelayLocation] = []
> ```

How do we know the heirarchy here? A custom list can have nested items, eg:



_Code snippet:_
```Swift
[
   Country,
   Country: [
      City: [
         Relay: {}
      ],
      City: [
         Relay: {},
         Relay: {}
      ]
   ]
]
```
___
*[`ios/MullvadSettings/CustomListRepository.swift` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq29sDVAtsKavEnkwDE:-Nq29sDVAtsKavEnkwDF:b-tft1ms) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadSettings/CustomListRepository.swift#L51)):*
> ```Swift
>             }
>         } catch {
>             throw error
> ```

Nit: If all we do is rethrow the error I think we can remove the do-catch. Alternatively we can add a logger message as well and keep it.
___
*[`ios/MullvadSettings/CustomListRepositoryProtocol.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq2CBW5-xVwyB6uHCHH:-Nq2CBW5-xVwyB6uHCHI:br0pi9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadSettings/CustomListRepositoryProtocol.swift#L20)):*
> ```Swift
>     func update(_ list: CustomList)
> 
>     /// Delete custom list  by id.
> ```

Nit: Extra spacing here and in a few texts below.
___
*[`ios/MullvadVPNTests/CustomListRepositoryTests.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq2E9Ys707clddntycx:-Nq2E9Ys707clddntycy:b-7tv2hg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadVPNTests/CustomListRepositoryTests.swift#L66)):*
> ```Swift
>     }
> 
>     func testFetchingAllCustomList() throws {
> ```

Nit: Maybe we could add more than one list here to check that it works with multiple lists.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/CustomList.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq26NYJ6wlef96UEs-b:-Nq7CBIF2EUuOrfseMlQ:b-kwwbe2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadSettings/CustomList.swift#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

How do we know the heirarchy here? A custom list can have nested items, eg:
</blockquote></details>

in the current code `LocationDataSource` is passing `RelayLocation` to tunnel manager to set matched relay for connecting and when user expands the the node it's looking for children.hence It means it's enough to have access to hierarchy 
___
*[`ios/MullvadSettings/CustomListRepository.swift` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq29sDVAtsKavEnkwDE:-Nq7DImP7KtNPqmMrK0x:b-urkklp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadSettings/CustomListRepository.swift#L51)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: If all we do is rethrow the error I think we can remove the do-catch. Alternatively we can add a logger message as well and keep it.
</blockquote></details>

the error should be shown in the UI; therefore, it needs to be thrown to be caught by the presentation layer.
___
*[`ios/MullvadSettings/CustomListRepositoryProtocol.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq2CBW5-xVwyB6uHCHH:-Nq7EuFG6mKA3PPNc4D1:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadSettings/CustomListRepositoryProtocol.swift#L20)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Extra spacing here and in a few texts below.
</blockquote></details>

Done
___
*[`ios/MullvadVPNTests/CustomListRepositoryTests.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq2E9Ys707clddntycx:-Nq7En4R6mC7yf8XWAGK:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2bab4b39027c5945f8ccd5bfd6c23717bc5f67f/ios/MullvadVPNTests/CustomListRepositoryTests.swift#L66)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Maybe we could add more than one list here to check that it works with multiple lists.
</blockquote></details>

Done

**Review by rablador — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by acb-mv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8GZ4W8bLT0uqR8EzL:-Nq8GZ4W8bLT0uqR8EzM:bo1t9iq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadSettings/CustomListRepository.swift#L26)):*
> ```Swift
> 
> public struct CustomListRepository: CustomListRepositoryProtocol {
>     public var publisher: AnyPublisher<[CustomList], Never> {
> ```

I don't think we need a publisher at this point, since we don't know yet how the repository will interact with the rest of the code. If needed, we can add one later and make use of it then.

**Review by buggmagnet — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8MM9B-9c5a_W8CrIm:-Nq8MM9B-9c5a_W8CrIn:b-u6uxqp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadSettings/CustomListRepository.swift#L20)):*
> ```Swift
>         switch self {
>         case .duplicateName:
>             "Name is already taken."
> ```

If this is a user facing error, let's localize it
___
*[`ios/MullvadSettings/CustomListRepository.swift` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8GZ4W8bLT0uqR8EzL:-Nq8RjO86cknUc5Pyopb:buj12n6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadSettings/CustomListRepository.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I don't think we need a publisher at this point, since we don't know yet how the repository will interact with the rest of the code. If needed, we can add one later and make use of it then.
</blockquote></details>

I agree with @rablador, can we make it work without Combine here ?
We had some challenges when building API Access methods because of Combine, so I'd like to avoid future pain if we can avoid it, unless you feel it will make upcoming development much easier to manage.
___
*[`ios/MullvadVPNTests/CustomListRepositoryTests.swift` line 40 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8R1JF3qYlSGjZid_e:-Nq8R1JF3qYlSGjZid_f:b-kq2x6t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadVPNTests/CustomListRepositoryTests.swift#L40)):*
> ```Swift
> 
>     func testAddingCustomList() throws {
>         let name = "Netflix"
> ```

nit
I think we can rename this `customListName` to make it even more explicit.

Same with `item` below, we could name it `customList`

I like some of the examples by the way, I think it's nice that they represent how a user would use the API like in `testFetchingAllCustomList` :thumbsup:

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8MM9B-9c5a_W8CrIm:-Nq8iZ79BC1lMulDIFGf:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadSettings/CustomListRepository.swift#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If this is a user facing error, let's localize it
</blockquote></details>

done
___
*[`ios/MullvadSettings/CustomListRepository.swift` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8GZ4W8bLT0uqR8EzL:-Nq8iN9qB9LgF62RQzFb:bofxmd6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadSettings/CustomListRepository.swift#L26)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I agree with @rablador, can we make it work without Combine here ?
We had some challenges when building API Access methods because of Combine, so I'd like to avoid future pain if we can avoid it, unless you feel it will make upcoming development much easier to manage.
</blockquote></details>

Let's keep it for UI I would remove that if I saw I don't need that anymore. at the moment it's more likely to need that

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782#-Nq8GZ4W8bLT0uqR8EzL:-NqDQUY-5QgYy4JWdg5n:bv6pgzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/66e3c8a5e3ccc2acd7b4ea313d26ea69612cada6/ios/MullvadSettings/CustomListRepository.swift#L26)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Let's keep it for UI I would remove that if I saw I don't need that anymore. at the moment it's more likely to need that
</blockquote></details>

I don't think we should keep things around in anticipation that we might need it. Better to add when we actually have evidence that we do.

**Review by rablador — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Pull request merged**
