### PR TITLE
Skip sending account expiry missing events when failing to fetch

### PR DESCRIPTION
**Pull request by sabercodic**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)

### CODE REVIEW

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 164 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NiiHrVUB-idzhkYFGob:-NiiHrVUB-idzhkYFGoc:bpkpmtp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8870de88e6d5673d39ca1f969817a5670505abcc/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L164)):*
> ```Kotlin
>             when (result) {
>                 is GetAccountDataResult.Ok ->
>                     AccountExpiry.Available(result.accountData.expiry.parseAsDateTime()!!)
> ```

Is the intention to crash if the date parsing fails? Would probably be nice to avoid crashing the service if possible, since that would also kill the tunnel.



_Code quote:_
```Kotlin
parseAsDateTime()!
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 164 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NiiHrVUB-idzhkYFGob:-Nj7CsqM8GiXITNrTYfp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8870de88e6d5673d39ca1f969817a5670505abcc/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L164)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is the intention to crash if the date parsing fails? Would probably be nice to avoid crashing the service if possible, since that would also kill the tunnel.
</blockquote></details>

Done.

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 164 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NiiHrVUB-idzhkYFGob:-Nj7OhmcBJzJdvVDXY1T:b-zhw5ow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8870de88e6d5673d39ca1f969817a5670505abcc/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L164)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I suggest making it a bit more compact. Perhaps something like this:

```
result.accountData.expiry.parseAsDateTime()?.let { AccountExpiry.Available(it) }
```

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH8HL543gTVoqRqgR4:-NjHZUCw4Jlq4DwskbrX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L77)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Looking at this there is a lot of chaining of `let`not sure if we can make it it a more clear way e.g

``` 
cachedAccountToken?.let {
    fetchAccountExpiry(it)
}?.let {
    accountExpiry = result
}
```
Alternatively I think this might be more clean:
```
val token = cachedAccountToken ?: return
val newAccountExpiry = fetchAccountExpiry(token) ?: return
accountExpiry = newAccountExpiry
```
</blockquote></details>

Done.

**Review by sabercodic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjHfcTPEABp8DMAUtuP):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I realized now that this commit message is a bit misleading. We're not really caching it for a specific screen, but rather for use throughout the app. I suggesting changing the message to just`Cache account expiry in vpn service`
</blockquote></details>

Done.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH8HL543gTVoqRqgR4:-NjHyW-j7lzn94rXQXw9:bxvvok7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L77)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Isn't the idea to also returned the cached value when it can't be fetched? :thinking:
</blockquote></details>

Returning account expiry will happen somewhere else after completion of this block
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 164 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH9HjnC_iKmXjNcIlS:-NjHyxAKAo00GWCPqTeL:b-7pvwig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L164)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As we discussed, using `!!` comes with a certain risk so we'll create a separate issue to look into this further. 

@Rawa please create an issue and share here :pray:
</blockquote></details>

great

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 164 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH9HjnC_iKmXjNcIlS:-NjHzfTe4veXUpN2LVAW:bhdbvqo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L164)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

great
</blockquote></details>

I've created the issue here now :) https://linear.app/mullvad/issue/DROID-491/treat-expirydatepaiduntil-as-non-nullable

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH8HL543gTVoqRqgR4:-NjHzm8v5bVKOW7HpmF9:b-xa1dk1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L77)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Returning account expiry will happen somewhere else after completion of this block
</blockquote></details>

Much more create :+1:

**Review by Rawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH8HL543gTVoqRqgR4:-NjHzy4S1amxdBgiZxJT:brp228y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L77)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Much more create :+1:
</blockquote></details>

Clear*

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-:-NjI8Se4EucA4our1vqE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt` line 77 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-NjH8HL543gTVoqRqgR4:-NjI87HC5bJaj_cQlzT9:bfle0xq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b10351e79cbc8bb97e102d87443ca9683843385/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L77)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Clear*
</blockquote></details>

@sabercodic ah, I see, it's via `onAccountExpiryChange`, right? Not very obvious/easy to follow the existing code, but not a problem to address in this PR

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-:-NjIFS3515DsFhcpKz8t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
Since we're not really adding any caching functionality the commit message and PR title is a bit misleading. This PR makes sure we're not sending `Missing` events when we fail to fetch the expiry. I suggest changing the commit message and PR title to something like: `Skip sending account expiry missing events when failing to fetch`

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401#-:-NjIM8lU34bYb1fSGikX:bmn6nj)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
