### PR TITLE
Add custom bridge settings to Electron app

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds a custom bridge option to the select location view and also allows editing the custom bridge. It uses the same form as the API access methods (except for the "name" field).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100)

### CODE REVIEW

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100)* status: 0 of 35 files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`-- commits` line 41 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv6A7J0EwKJ30GACQKD):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Refactor* :smile:
</blockquote></details>

Done.
___
*[`gui/src/config.json` line 20 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv6E-py8abh_N-C0-kM:-NvCbSpqEq-055EvQFbF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b30494fecc8569346421c1d5dcdc539e89273773/gui/src/config.json#L20)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This expected value is `0.9`, right? :blush:
```json
"white90": "rgba(255, 255, 255, 0.9)",
```
</blockquote></details>

Done.
___
*[`gui/src/main/daemon-rpc.ts` line 1248 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv63cYH4fM9gSZpSNJ8:-NvCch_1D_hr5rHzdcIb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/474f86ad519ac941c1990a526c06d70243c31fcb/gui/src/main/daemon-rpc.ts#L1248)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Why do we have to check `hasCustom` if `getCustom` returns `CustomProxy | undefined`? :blush:

Also, we should be able to get rid of the non-null assertion through some type-narrowing:
```typescript
const getCustomResult = bridgeSettings.getCustom(); // Find a better name for this temporary variable
const custom = getCustomResult ? convertFromCustomProxy(getCustomResult) : undefined;
```
</blockquote></details>

Done.
___
*[`gui/src/main/daemon-rpc.ts` line 1852 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv62yK8-mrA8WGXkvWX:-NvCcjc7BwgWEFYnkryj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/474f86ad519ac941c1990a526c06d70243c31fcb/gui/src/main/daemon-rpc.ts#L1852)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Move this comment to the invocation of `filter` :blush:
</blockquote></details>

Done.
___
*[`gui/src/main/settings.ts` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv5q0Uo4EL11nPYRZqs:-NvCdQcY0pBdRfFy2ztY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4065f00b23fed709b95481373afa310f4c8a4eab/gui/src/main/settings.ts#L47)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

The comment and the code are correct, but they don't _really_ align. I suggest changing either the comment, the code or both to make it easier to correlate the two.

For example, updating both the comment and the code:
```js
// Reset bridge constraints to `any` when the state is set to auto or off, and normal bridges are used
if ((bridgeState === 'auto' || bridgeState === 'off') && this.bridgeSettings.type === 'normal') {
```
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/EditApiAccessMethod.tsx` line 48 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv6AGV2-E8JHYioF0o1:-NvCdwSM4MVeOr8iqDOV:b-ld4dlz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1592bf324a53eddd1d65ace914460f1bd3ae1faf/gui/src/renderer/components/EditApiAccessMethod.tsx#L48)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit Is this still an 'ugly' way of iterating over all access methods? :wink:
</blockquote></details>

You're right, I'm happy with this solution :) Done.
___
*[`gui/src/renderer/components/EditCustomBridge.tsx` line 18 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv6B0alAk_BPZk8BhM5:-NvCe9wE9vu8J5jgkcft:b-fnhtd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cdb2ef45010b69272a12fa1ddde32bf828ef065c/gui/src/renderer/components/EditCustomBridge.tsx#L18)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit These imports can be merged:

```typescript
import { SmallButton, SmallButtonColor } from './SmallButton';
```
</blockquote></details>

I thought our linter would catch and fix stuff like this :O  Done.
___
*[`gui/src/renderer/components/EditCustomBridge.tsx` line 23 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv6BZGGDkrV8SoKNsfW:-NvCeTVFC2P5XA1MXO3F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cdb2ef45010b69272a12fa1ddde32bf828ef065c/gui/src/renderer/components/EditCustomBridge.tsx#L23)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit This can be compressed:
```typescript
<CustomBridgeForm />
```
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/EditCustomBridge.tsx` line 38 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv6C8ZM6rVpa_DSxB1A:-NvCepPQ-ZQH9KaDmsmM:bip76a4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cdb2ef45010b69272a12fa1ddde32bf828ef065c/gui/src/renderer/components/EditCustomBridge.tsx#L38)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I feel like this could do with a small comment: 
```typescript
// If there exists custom bridge settings, we should prompt the user to add a custom bridge. 
// Otherwise, we should prompt them to edit the existing custom bridge settings.
  const title =
    bridgeSettings.custom === undefined
      ? messages.pgettext('custom-bridge', 'Add custom bridge')
      : messages.pgettext('custom-bridge', 'Edit custom bridge');
```
.. or something along those lines
</blockquote></details>

Done (although I reversed it).
___
*[`gui/src/renderer/redux/settings/reducers.ts` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv5ro-OCeETVUdRILmQ:-NvCjfgH8KV_1QIWz2q7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02406aaac963e4ada38f2b3efc18f290c8f16477/gui/src/renderer/redux/settings/reducers.ts#L47)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I assume that both `providers` and `ownership` represent a constraint, where the empty list and `Ownership.any` does not filter any bridges? I know that barely any other values in this file are documented, but it would be nice to clarify what `providers` and `ownership` are in `NormalBridgeSettingsRedux`, since their types does not capture their intent imo :blush:
</blockquote></details>

Done.

**Review by raksooo — COMMENTED** [review]
> Reviewed 1 of 1 files at r38.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100)* status: 0 of 35 files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

**Review by MarkusPettersson98 — APPROVED** [review]
:lgtm:

> Reviewed 35 of 35 files at r19, 2 of 2 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, 3 of 3 files at r23, 3 of 3 files at r24, 3 of 3 files at r25, 2 of 2 files at r26, 2 of 2 files at r27, 1 of 1 files at r28, 2 of 2 files at r29, 1 of 1 files at r30, 4 of 4 files at r31, 2 of 2 files at r32, 4 of 4 files at r33, 4 of 4 files at r34, 1 of 1 files at r35, 1 of 1 files at r36, 1 of 1 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-:-NvCthY1CXPNVQM0e5Xl:bnfp4nl)* status: 34 of 35 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[`gui/src/renderer/redux/settings/reducers.ts` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-Nv5ro-OCeETVUdRILmQ:-NvCrbgv9gQb6IbWI4Bq:b5aawa4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/02406aaac963e4ada38f2b3efc18f290c8f16477/gui/src/renderer/redux/settings/reducers.ts#L47)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I inlined the comments as JSDoc comments for you - nicely done :thumbsup:

**Review by raksooo — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 35 files at r19.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100#-:-NvCtt0t4RtUQo8a1ipJ:bnfp4nl)* status: 34 of 35 files reviewed, all discussions resolved

**Review by raksooo — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100)* status: 34 of 35 files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r38, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6100)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
