### PR TITLE
MUL22-02 for Windows - maintain blocking firewall rules during system shutdown.

### PR DESCRIPTION
**Pull request by dlon**
Previously, the daemon did keep blocking rules after exit if auto-connect was enabled. This means that there's a small leak window on shutdown if auto-connect (and always require VPN) is disabled. This PR changes the behavior of the daemon to always block on exit if the system is shutting down instead.

Related: #3940.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/lib.rs` line 2165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942#-NCPkVE33-L5B74QR6y0:-NCPkVE33-L5B74QR6y1:bp7151q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/912d4127e44491c81473220ad440685886484eeb/mullvad-daemon/src/lib.rs#L2165)):*
> ```XML
>         // shutdown.
>         #[cfg(windows)]
>         if keep_fw_rules && *self.target_state == TargetState::Secured {
> ```

This should be an `keep_fw_rules && (*self.target_state == TargetState::Secured || self.settings.auto_connect)`. And the `keep_fw_rules` should be renamed to signify that the boolean indicates whether the system is being shut down or not.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/lib.rs` line 2165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942#-NCPkVE33-L5B74QR6y0:-NCQ1HHr-IrIgTUzZn2Y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/912d4127e44491c81473220ad440685886484eeb/mullvad-daemon/src/lib.rs#L2165)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This should be an `keep_fw_rules && (*self.target_state == TargetState::Secured || self.settings.auto_connect)`. And the `keep_fw_rules` should be renamed to signify that the boolean indicates whether the system is being shut down or not.
</blockquote></details>

Done.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[`mullvad-daemon/src/lib.rs` line 303 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942#-NCQ2kyo4eSm6o-DPyap:-NCQ2kyo4eSm6o-DPyaq:b1u5s0d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e1a7916444e15af5095acd08ebf10c6db06e1b4/mullvad-daemon/src/lib.rs#L303)):*
> ```XML
>     Command(DaemonCommand),
>     /// Daemon shutdown triggered by a signal, ctrl-c or similar.
>     TriggerShutdown(bool),
> ```

The docs should explain what the boolean value means.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/lib.rs` line 303 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942#-NCQ2kyo4eSm6o-DPyap:-NCQ82nF5pXv7Ozcxeae:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e1a7916444e15af5095acd08ebf10c6db06e1b4/mullvad-daemon/src/lib.rs#L303)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The docs should explain what the boolean value means.
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/system_service.rs` line 200 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942#-NCQBGQs9MILUmPbsevo:-NCQBGQs9MILUmPbsevp:bucurbu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ddc3002f17513ca77506d5406cd044465e76690/mullvad-daemon/src/system_service.rs#L200)):*
> ```XML
>     persistent_service_status: PersistentServiceStatus,
>     shutdown_handle: DaemonShutdownHandle,
>     should_restart: Arc<AtomicBool>,
> ```

I think this field, and possibly it's siblings, could do with a docstring.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/system_service.rs` line 200 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942#-NCQBGQs9MILUmPbsevo:-NCQIGElD2sfmgibBSn6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ddc3002f17513ca77506d5406cd044465e76690/mullvad-daemon/src/system_service.rs#L200)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think this field, and possibly it's siblings, could do with a docstring.
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
