### PR TITLE
Add spacing tokens and use in settings view

### PR DESCRIPTION
**Pull request by olmoh**
Adds spacing tokens based on design foundations and updates the settings view to use these

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)

### CODE REVIEW

**Review by raksooo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 4 of 7 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)* status: all files reviewed, 3 unresolved discussions (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC988152hM0hNrV_lCV:-OC988152hM0hNrV_lCW:b-xbs4qy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx#L9)):*
> ```XML
> export const Container = styled.div({
>   flex: 0,
>   margin: `${spacings.spacing3} ${spacings.spacing5} ${spacings.spacing4}`,
> ```

I looked around a bit in the designs, and it looks like the default horizontal view margin is `spacing5`. Maybe we should split it up into two variables, one for horizontal view margin and one for vertical? Then we could use the horizontal one here. What do you think?
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SettingsStyles.tsx` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC91YTU-wGhhQyOCeVl:-OC91YTU-wGhhQyOCeVm:b-fx08i3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/SettingsStyles.tsx#L12)):*
> ```XML
> 
> export const StyledQuitButton = styled(AppButton.RedButton)({
>   margin: `0 ${measurements.viewMargin}`,
> ```

I'm a bit unsure about using `viewMargin` as marginTop since that corresponds to the outer margin of the view. What do you think about using `viewMargin` for the bottom margin and the corresponding spacing value for `marginTop`? If we ever want to change the view margin without changing the margin between the button and the settings cells it would be easier to accomplish that.
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC908cs6hRBU4R39MWV:-OC908cs6hRBU4R39MWW:b54w4vl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx#L54)):*
> ```XML
>   flex: 0,
>   padding: measurements.viewMargin,
>   [`${SettingsContent} &`]: {
> ```

I think you want `&&` here since applying styles to `&` can lead to unintended behavior.

**Review by olmoh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)* status: 7 of 28 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC908cs6hRBU4R39MWV:-OCCvR6162RmLB7CX-8u:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx#L54)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I think you want `&&` here since applying styles to `&` can lead to unintended behavior.
</blockquote></details>

Done.
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC988152hM0hNrV_lCV:-OCCvVBB133kF0dCA9J8:b861tvk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx#L9)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I looked around a bit in the designs, and it looks like the default horizontal view margin is `spacing5`. Maybe we should split it up into two variables, one for horizontal view margin and one for vertical? Then we could use the horizontal one here. What do you think?
</blockquote></details>

Good idea, I split up view margin into a horizontal and a vertical variant and changed all uses of it so the horizontal is only used on horizontal spacing.

**Review by raksooo — COMMENTED** [review]
> Reviewed 17 of 21 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)* status: all files reviewed, 1 unresolved discussion (waiting on @olmoh)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC908cs6hRBU4R39MWV:-OCIUBsuBiGSxrH8Z557:b-a9ohj3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx#L54)):*
<details><summary><i>Previously, olmoh (Oliver Mohlin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great! :+1:
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OC988152hM0hNrV_lCV:-OCJV_C88Nc-v0yXPvKc:bdtx8r6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2fdfd8eb0781cbea74ed005dfd070262332dc01d/desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx#L9)):*
<details><summary><i>Previously, olmoh (Oliver Mohlin) wrote…</i></summary><blockquote>

Good idea, I split up view margin into a horizontal and a vertical variant and changed all uses of it so the horizontal is only used on horizontal spacing.
</blockquote></details>

Nice work!
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx` line 59 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OCIUmDc8u6J-t7jGZKR:-OCIUmDc8u6J-t7jGZKS:b-bbuaxi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cefb9c4d8c08f160da13c907484208147400cfb0/desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx#L59)):*
> ```XML
> });
> 
> export const ButtonStack = styled.div({
> ```

Nothing to fix now, but just a thought for later. We already have a component in `AppButton.tsx` called `ButtonGroup`. Maybe we could alignt these. That one shouldn't be needed when we have this one. But we don't need to replace all uses of that one now unless you want to.
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Launch.tsx` line 31 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OCITzVo8Ri8O9Qc2IOW:-OCITzVo8Ri8O9Qc2IOX:bifwt4b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cefb9c4d8c08f160da13c907484208147400cfb0/desktop/packages/mullvad-vpn/src/renderer/components/Launch.tsx#L31)):*
> ```XML
> const StyledFooter = styled(Footer)({
>   backgroundColor: colors.blue,
>   padding: `0 14px ${spacings.spacing6}`,
> ```

Don't we want the vertical view margin here? And since it is extending `Footer` which already has padding bottom set to `verticalViewMargin` we shouldn't need to set it at all :)

**Review by olmoh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Launch.tsx` line 31 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OCITzVo8Ri8O9Qc2IOW:-OCXFbLP6BRmA0wDbzy1:b-bzzisa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cefb9c4d8c08f160da13c907484208147400cfb0/desktop/packages/mullvad-vpn/src/renderer/components/Launch.tsx#L31)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Don't we want the vertical view margin here? And since it is extending `Footer` which already has padding bottom set to `verticalViewMargin` we shouldn't need to set it at all :)
</blockquote></details>

Good catch, should be fixed now :)
___
*[`desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx` line 59 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200#-OCIUmDc8u6J-t7jGZKR:-OCXFvDp0-tEnvrF8heJ:bytbt99) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cefb9c4d8c08f160da13c907484208147400cfb0/desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx#L59)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Nothing to fix now, but just a thought for later. We already have a component in `AppButton.tsx` called `ButtonGroup`. Maybe we could alignt these. That one shouldn't be needed when we have this one. But we don't need to replace all uses of that one now unless you want to.
</blockquote></details>

Yeah that sounds like something we want to do, made some changes regarding the stack that will be in the next spacing PR. So, probably easier to do that change there.

**Review by raksooo — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by raksooo — APPROVED** [review]
> Reviewed 22 of 22 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7200)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
