### PR TITLE
Add DAITA support to the android app

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to add DAITA support to the Android app.

The PR is mostly ready to be reviewed, however there are some minor remaining work TODO:
- [x] ~~Improve and clean up changes to the `wireguard-go-rs` build.~~ (done in separate PR)
- [x] ~~Fix failing clippy and udeps actions. These might be fixed by the item above.~~ (done in separate PR)
- [x] Add daita filter chip.
- [x] Add daita confirmation dialog.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)

### CODE REVIEW

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 71 of 71 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NBdCT0OuoDeS8txR7:-O5NBdCT0OuoDeS8txR8:b-gjmyf5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L508)):*
> ```Kotlin
>                 Spacer(modifier = Modifier.height(Dimens.cellLabelVerticalPadding))
>                 HeaderSwitchComposeCell(
>                     title = "DAITA",
> ```

Should be an untranslatable string resource I think?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 510 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NBuFZ1PLyepD_l0VM:-O5NBuFZ1PLyepD_l0VN:b-jkkr0h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L510)):*
> ```Kotlin
>                     title = "DAITA",
>                     isToggled = state.isDaitaEnabled,
>                     isEnabled = true,
> ```

Is true by default so not needed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NCLZO4j5ivmEefh83:-O5NCLZO4j5ivmEefh84:b-s3w3o3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L143)):*
> ```Kotlin
>                     add(FilterChip.Provider(providerCountFilter))
>                 }
>                 if (settings?.tunnelOptions?.wireguard?.daita == true) {
> ```

Maybe a bit nice with some kind of extension function like `Settings.hasDaita(): Boolean` ?

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 51 of 71 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5N8dKv9gHmJ-_tR9Rj:-O5N8dKv9gHmJ-_tR9Rk:b8favrw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L508)):*
> ```Kotlin
>                 Spacer(modifier = Modifier.height(Dimens.cellLabelVerticalPadding))
>                 HeaderSwitchComposeCell(
>                     title = "DAITA",
> ```

Should be resource?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5N96Pd0khl2LDLQZNY:-O5N96Pd0khl2LDLQZNZ:b18ocli) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt#L73)):*
> ```Kotlin
> }
> 
> fun RelayItem.Location.Country.applyFilters(
> ```

Should we call it just `filter`? With `applyFilters` it sounds like we apply a filter to a Country, thus that it would be added on top of the country.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/DaitaSettings.kt` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NC-pn90I_gcZkG7wN:-O5NC-pn90I_gcZkG7wO:bfoz3wb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/DaitaSettings.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.model
> 
> enum class DaitaSettings {
> ```

If we only have On/Off, we should make this a Boolean.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NDz7Z-kWWyXyTsrWG:-O5NDz7Z-kWWyXyTsrWH:bvsbpqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt#L7)):*
> ```Kotlin
> import java.io.FileOutputStream
> 
> class AssetToFilesDirExtractor(val context: Context) {
> ```

Do we even need to have this instance? We should be able to just make it a function right? Maybe it can also be and extension function on Context if just plan to use it within the scope of a Context.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NCfaQ0izHJYheUAJ3:-O5NCfaQ0izHJYheUAJ4:b6qcvjf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt#L8)):*
> ```Kotlin
> 
> class AssetToFilesDirExtractor(val context: Context) {
>     fun extract(assetName: String, overwriteFileIfAssetMoreRecent: Boolean = false) {
> ```

Do we ever user anything else than true? Is the flag needed?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: 58 of 74 files reviewed, 7 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5N8dKv9gHmJ-_tR9Rj:-O5NkiiW-0bU4l8CoI3_:bkl2fbe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L508)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should be resource?
</blockquote></details>

Fixed! :thumbsup: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NBdCT0OuoDeS8txR7:-O5NkkKTDYeaAObca3lI:bkl2fbe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L508)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should be an untranslatable string resource I think?
</blockquote></details>

Fixed! :thumbsup: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 510 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NBuFZ1PLyepD_l0VM:-O5NktMd4CkFBv0ELTLu:b169no0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L510)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is true by default so not needed
</blockquote></details>

This was copy pasta from other toggles were we also seem to explicitly set it, but removed it from this one now
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5N96Pd0khl2LDLQZNY:-O5NlUWa9TWogRk1gkVa:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should we call it just `filter`? With `applyFilters` it sounds like we apply a filter to a Country, thus that it would be added on top of the country.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NCLZO4j5ivmEefh83:-O5NmNwW35u84YSX1Nhw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt#L143)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe a bit nice with some kind of extension function like `Settings.hasDaita(): Boolean` ?
</blockquote></details>

Done.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/DaitaSettings.kt` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NC-pn90I_gcZkG7wN:-O5NmZhKBIduLFomWBhd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/DaitaSettings.kt#L3)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If we only have On/Off, we should make this a Boolean.
</blockquote></details>

Done.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt` line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NDz7Z-kWWyXyTsrWG:-O5NrtSe67hX29DVkW3f:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we even need to have this instance? We should be able to just make it a function right? Maybe it can also be and extension function on Context if just plan to use it within the scope of a Context.
</blockquote></details>

Done.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5NCfaQ0izHJYheUAJ3:-O5NrsaA1KqRaJI6gnTP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/abe1286756e1cc01c0c7f3f300ca1e90f07b51f1/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/AssetToFilesDirExtractor.kt#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we ever user anything else than true? Is the flag needed?
</blockquote></details>

Done.

**Review by Pururun — DISMISSED** [review]
> Reviewed 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 182 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SEMeE2ImV4c77DU04:-O5SEMeE2ImV4c77DU05:bo77y0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L182)):*
> ```Kotlin
>     }
> 
>     daitaConfirmationDialogResult.OnNavResultValue { doEnableDaita ->
> ```

I wonder if we should move this code to the dialog to not increase the complexity of `VpnSettings`

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 1 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DaitaConfirmationDialog.kt` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SCGB154kuXL8Jf3yO:-O5SCGB154kuXL8Jf3yP:bmuiuqp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DaitaConfirmationDialog.kt#L48)):*
> ```Kotlin
>                 modifier = Modifier.fillMaxWidth().height(Dimens.dialogIconHeight),
>                 painter = painterResource(id = R.drawable.icon_alert),
>                 contentDescription = "",
> ```

`contentDescription = null,` seems more reasonable than `""`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 521 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SEkbs3N2JGJDVxnRe:-O5SEkbs3N2JGJDVxnRf:bp2musp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L521)):*
> ```Kotlin
>                     title = stringResource(id = R.string.daita),
>                     isToggled = state.isDaitaEnabled,
>                     onCellClicked = { newValueIsEnable ->
> ```

Name is pretty weird `newValudIsEnable`, I think it is fine that it is just `enable`, it is implicit that it is the new value.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: 73 of 75 files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DaitaConfirmationDialog.kt` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SCGB154kuXL8Jf3yO:-O5SL8Jt0VLIY4AdM5OW:brj51u0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DaitaConfirmationDialog.kt#L48)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`contentDescription = null,` seems more reasonable than `""`
</blockquote></details>

Done! Copy pasta artifact, so we might want to clean that up in other places as well
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 182 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SEMeE2ImV4c77DU04:-O5SLRb--OKD_kWdHZmN:b-98d631) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L182)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I wonder if we should move this code to the dialog to not increase the complexity of `VpnSettings`
</blockquote></details>

Went with the other approach at first, but felt like way too much boiler plate for such a trivial call where the result is always either to cancel or just call a single vm function (always with `true` as an argument). Me and David discussed it and agreed to go with this approach for now, but we said that we might want to eventually take a step back and restructure some parts of the vpn settings screen. Does that sound OK?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 521 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SEkbs3N2JGJDVxnRe:-O5SLQCj3nSvc4NxWQGm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L521)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Name is pretty weird `newValudIsEnable`, I think it is fine that it is just `enable`, it is implicit that it is the new value.
</blockquote></details>

Done.

**Comment by albin-mullvad** [comment]
Rebased on #6701 which we aim to merge first.

**Review by Rawa — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: 18 of 77 files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 32 of 35 files at r3, 21 of 25 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-:-O5XWLjj-jo7rxS3LaKf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt` line 182 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5SEMeE2ImV4c77DU04:-O5XTalTDutPgL_PWO52:b40qlla) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/123d5612f15d4edbc57ec376f4c05322fb1c0712/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt#L182)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Went with the other approach at first, but felt like way too much boiler plate for such a trivial call where the result is always either to cancel or just call a single vm function (always with `true` as an argument). Me and David discussed it and agreed to go with this approach for now, but we said that we might want to eventually take a step back and restructure some parts of the vpn settings screen. Does that sound OK?
</blockquote></details>

Sounds ok!

**Review by Pururun — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — DISMISSED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — COMMENTED** [review]
> Reviewed 2 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 11 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5mOj-aA8vSl001QOtk):*
I guess this commit should be squashed before we merge?

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: 77 of 78 files reviewed, all discussions resolved (waiting on @Pururun)

___
*[`-- commits` line 11 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5mOj-aA8vSl001QOtk):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess this commit should be squashed before we merge?
</blockquote></details>

Done

**Review by Pururun — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-:-O5mr3CQ6BRnGC7Md66z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by MarkusPettersson98 — COMMENTED** [review]
> Reviewed 2 of 71 files at r1, 1 of 35 files at r3, 3 of 6 files at r5, 1 of 3 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt` line 67 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5qxPDF3p1CY_VBtzDy:-O5qxPDF3p1CY_VBtzDz:botjg39) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5072fe8ceac02b83b9ac3d23e058e2b33cf1d13/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt#L67)):*
> ```Kotlin
>         border =
>             FilterChipDefaults.filterChipBorder(
>                 borderColor = borderColor,
> ```

Should probably set `disabledBorderColor` as well since it is transparent.

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt` line 75 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5r-HwP5uWVZL-l1vve:-O5r-HwP5uWVZL-l1vvf:biao5ou) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5072fe8ceac02b83b9ac3d23e058e2b33cf1d13/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt#L75)):*
> ```Kotlin
>         label = { Text(text = text, style = MaterialTheme.typography.labelMedium) },
>         trailingIcon = {
>             if (enabled) {
> ```

Trailing icon takes nullable composable, so emitting a empty composable count result in some unexpected padding to be added. If we don't have a icon we should not emit any lambda at all.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: 75 of 78 files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98, @Pururun, and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt` line 67 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5qxPDF3p1CY_VBtzDy:-O63DJUh3LtP57hy7tV1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5072fe8ceac02b83b9ac3d23e058e2b33cf1d13/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt#L67)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should probably set `disabledBorderColor` as well since it is transparent.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt` line 75 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-O5r-HwP5uWVZL-l1vve:-O63DKK1-01HUq2zsyls:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5072fe8ceac02b83b9ac3d23e058e2b33cf1d13/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt#L75)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Trailing icon takes nullable composable, so emitting a empty composable count result in some unexpected padding to be added. If we don't have a icon we should not emit any lambda at all.
</blockquote></details>

Done.

**Review by Rawa — APPROVED** [review]
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6684#-:-O66W8oD1TUqlC8VJWVH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
