### PR TITLE
LoginViewController: add delegate

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Extend `LoginViewControllerDelegate` to move the `Account` interactions outside of controller. This will later be leveraged by `AppDelegate` to perform additional actions upon successful log in.
2. Add on-screen keyboard return key handler on iPad

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651)

### CODE REVIEW

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651)* status: 0 of 1 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/LoginViewController.swift, line 229 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651#-MXrZwdtBf5Gs5VlNSVO:-MXrZwdtBf5Gs5VlNSVP:b-7q6sx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/454c60a1f1e5b8089af04fbc8becb5d855cf982a/ios/MullvadVPN/LoginViewController.swift#L229)):*
> ```Swift
>             // Navigate to the main view after 1s delay
>             DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
>                 self.rootContainerController?.setEnableSettingsButton(true)
> ```

FYI The settings button in the header will be enabled/disabled from `AppDelegate` in the follow up PR.

**Review by jvff — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651#-:-MXsj2xsE5eknfiXDdBA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651#-MXsj4uHByKTHge-M9sT:-MXsj4uHByKTHge-M9sU:b-ggcecr) (no related file):*
One question: this PR doesn't seem to include the update to the `LoginViewControllerDelegate` implementation, does that mean that with the PR in its current state it won't be possible to log in anymore?

---

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651#-MXsj4uHByKTHge-M9sT:-MY4HVTg49TO_oJvN82m:bsp5g2i) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

One question: this PR doesn't seem to include the update to the `LoginViewControllerDelegate` implementation, does that mean that with the PR in its current state it won't be possible to log in anymore?
</blockquote></details>

Correct. The thing is that the iPad support brings a lot of new code on board so it would be time consuming to make master work with each PR I submit as I am breaking down the larger work onto smaller PRs.

---

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
