### PR TITLE
Ensure log file sizes stay below a certain threshold

### PR DESCRIPTION
**Pull request by rablador**
We should limit log files to not be larger than a certain threshold (currently 16kB) when writing to disk. If limit is exceeded, create a new file with a "_<partial count>" suffix and keep writing to it instead. Repeat if necessary.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
Will look at creating tests shortly.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-:-NvpJt8bBAlHhCzkG0cP:b35v7li)* status: 0 of 13 files reviewed, all discussions resolved

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadLogging/Date+LogFormat.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NvpEhiFD2Yjfo36Hw9u:-NvpEhiFD2Yjfo36Hw9v:bdpkc6t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/890163db3b5b1accfcdc6b6174ea848964aaedd9/ios/MullvadLogging/Date%2BLogFormat.swift#L13)):*
> ```Swift
> extension Date {
>     public var logFormatted: String {
>         logFileFormatted.replacingOccurrences(of: "T", with: " ")
> ```

we are doing some string manipulation in `Date` extension that has nothing to do with that.Moreover,  the using formatter is much more sensible to me instead of replacing.



_Code snippet:_
```Swift
let formatter = DateFormatter()
formatter.dateFormat = "dd/MM/yyyy HH:mm:ss"
return formatter.string(from: self)
```
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NvpL86FBwqA0i4gYlmS:-NvpL86FBwqA0i4gYlmT:b40ohl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/890163db3b5b1accfcdc6b6174ea848964aaedd9/ios/MullvadLogging/LogFileOutputStream.swift#L101)):*
> ```Swift
> 
>         guard partialFileSizeCounter <= ApplicationConfiguration.logMaximumFileSize else {
>             try fileHandle.close()
> ```

nit : for having more readability I suggest to put this scope of the file in another function which is called `writeInNewFile` or something like that
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NvpLneC60uHILS8zemY:-NvpLneC60uHILS8zemZ:b-mm8j68) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/890163db3b5b1accfcdc6b6174ea848964aaedd9/ios/MullvadLogging/LogFileOutputStream.swift#L196)):*
> ```Swift
>     }
> 
>     private func incrementFileName(partialFileCounter: Int) throws -> URL {
> ```

we have the `partialFileCounter` as a global value, there is no need to pass it to function. the name of functions doesn't make sense the return value is a file url for new file.



_Code snippet:_
```Swift
    private func newFileUrl() throws -> URL {
        if let url = URL(string: baseFileURL.relativePath + "_\(self.partialFileNameCounter).log") {
            return url
        } else {
            throw POSIXError(POSIXErrorCode(rawValue: 2)!) // "No such file or directory"
        }
    }
```

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadLogging/Date+LogFormat.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NvpEhiFD2Yjfo36Hw9u:-NvqelGs5LpLmHO066N-:b4hco86) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/890163db3b5b1accfcdc6b6174ea848964aaedd9/ios/MullvadLogging/Date%2BLogFormat.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we are doing some string manipulation in `Date` extension that has nothing to do with that.Moreover,  the using formatter is much more sensible to me instead of replacing.
</blockquote></details>

Alright, I'll revert the change and apply locale and timezone instead.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NvpL86FBwqA0i4gYlmS:-NvqeY4s5iORZbPFfEX3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/890163db3b5b1accfcdc6b6174ea848964aaedd9/ios/MullvadLogging/LogFileOutputStream.swift#L101)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : for having more readability I suggest to put this scope of the file in another function which is called `writeInNewFile` or something like that
</blockquote></details>

Done.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NvpLneC60uHILS8zemY:-NvqdlDc6MRWmOfEku3l:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/890163db3b5b1accfcdc6b6174ea848964aaedd9/ios/MullvadLogging/LogFileOutputStream.swift#L196)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we have the `partialFileCounter` as a global value, there is no need to pass it to function. the name of functions doesn't make sense the return value is a file url for new file.
</blockquote></details>

Done.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3jCq_7xH-b2AzBbi2:-Nw3jCq_7xH-b2AzBbi3:b-hgsg3d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L109)):*
> ```Swift
> 
>         // Rotate file if threshold has been met, then rerun the write operation.
>         guard partialFileSizeCounter <= fileSizeLimit else {
> ```

There is a caveat here. If the incoming data chunks themselves are larger than `fileSizeLimit`, no logs will be written at all. AND many many new log files will be created.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: 15 of 16 files reviewed, 11 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3mSjgCyCbbSLXPdgy:-Nw3mSjgCyCbbSLXPdgz:b-qeg67n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L106)):*
> ```Swift
> 
>     private func write(fileHandle: FileHandle, data: Data) throws {
>         partialFileSizeCounter += UInt64(data.count)
> ```

This isn't correct.
We should only increase the `partialFileSizeCounter` with the number of bytes written (returned by `Darwin.write`)

Otherwise, we'll have a mismatch when we fail to write below.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 118 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3iX1O3VQBoY_djLRN:-Nw3iX1O3VQBoY_djLRO:b5v7u3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L118)):*
> ```Swift
>             guard let ptr = buffer.baseAddress else { return 0 }
> 
>             return Darwin.write(fileHandle.fileDescriptor, ptr, buffer.count)
> ```

nit
The small downside of this is that we can't easily test scenarios where we have to `bufferData` 
Fortunately, the data we buffer is way lower than a maximum file size, so we shouldn't have any scenario where we end up
in a loop where we can't write to a new file because there is too much buffered data. 
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 127 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3kqpT22ZWTGci0dt9:-Nw3kqpT22ZWTGci0dtA:b-rnr0jx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L127)):*
> ```Swift
>     }
> 
>     fileprivate func rotateFile(handle: FileHandle, data: Data) throws {
> ```

That `data` parameter is not used
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 213 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3WEfkE5Ue3CSqFrj4:-Nw3WEfkE5Ue3CSqFrj5:b-qb4sw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L213)):*
> ```Swift
>             return url
>         } else {
>             throw POSIXError(POSIXErrorCode(rawValue: 2)!) // "No such file or directory"
> ```

`throw POSIXError(.ENOENT)`
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6504 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3cOpiA3My5mujmLYs:-Nw3cOpiA3My5mujmLYt:b-qy4f1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPN.xcodeproj/project.pbxproj#L6504)):*
> ```
> 				PRODUCT_NAME = "$(TARGET_NAME)";
> 				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
> 				SWIFT_STRICT_CONCURRENCY = minimal;
> ```

Did you mean to check this in ?
___
*[`ios/MullvadVPNTests/LoggingTests.swift` line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3czQA1lQ8kJUn31Wt:-Nw3czQA1lQ8kJUn31Wu:b-gxdnx0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LoggingTests.swift#L37)):*
> ```Swift
>         sync()
> 
>         let contents = String(decoding: (try? Data(contentsOf: fileURL)) ?? Data(), as: UTF8.self)
> ```

`let contents = try XCTUnwrap(String(contentsOf: fileURL))` is much easier to read (we also need to mark the test as `throws` 
Same for the test below 
___
*[`ios/MullvadVPNTests/LogRotationTests.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3eYmJ3c3NRAhK2y7d:-Nw3eYmJ3c3NRAhK2y7e:bnogvz2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LogRotationTests.swift#L35)):*
> ```Swift
>         let logChunkSize = 20
> 
>         let exptectedLogCount = Int(ceil(Double(totalLogTestSize) / Double(totalLogSizeLimit)))
> ```

`exptectedLogCount` -> `expectedLogCount`
___
*[`ios/MullvadVPNTests/LogRotationTests.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3himVCLxhkyCmYL7g:-Nw3himVCLxhkyCmYL7h:bvcfy50) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LogRotationTests.swift#L138)):*
> ```Swift
> extension LogRotationTests {
>     private func stringOfSize(_ size: Int) -> String {
>         String(repeating: " ", count: size)
> ```

nit
if you look at the files generated during the tests, it just looks like empty space, that's quite fun !
But it's not a big deal

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: 15 of 16 files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3mSjgCyCbbSLXPdgy:-Nw46aHf-irmTgTAUFBO:blzmu3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L106)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This isn't correct.
We should only increase the `partialFileSizeCounter` with the number of bytes written (returned by `Darwin.write`)

Otherwise, we'll have a mismatch when we fail to write below.
</blockquote></details>

You're right, I moved the counter to the bottom. We should, however, still check for size limitation before attempting to write, so introduced a temporary prediction for that instead.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 118 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3iX1O3VQBoY_djLRN:-Nw46eb77AiPSBJly6gj:b-36nf6l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L118)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
The small downside of this is that we can't easily test scenarios where we have to `bufferData` 
Fortunately, the data we buffer is way lower than a maximum file size, so we shouldn't have any scenario where we end up
in a loop where we can't write to a new file because there is too much buffered data.
</blockquote></details>

Yes, in realty this should not be a problem, but it still feels iffy that we could end up with in a bad state if not configured properly.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 127 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3kqpT22ZWTGci0dt9:-Nw49C5G2r8LR-c_Stga:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L127)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That `data` parameter is not used
</blockquote></details>

Done.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 213 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3WEfkE5Ue3CSqFrj4:-Nw49HOi9_3S3_frZtxJ:b8nksgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L213)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`throw POSIXError(.ENOENT)`
</blockquote></details>

That's what I wanted, yes :)
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6504 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3cOpiA3My5mujmLYs:-Nw49MnCCa397UgkyX7D:br6s1v7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPN.xcodeproj/project.pbxproj#L6504)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Did you mean to check this in ?
</blockquote></details>

Nope...
___
*[`ios/MullvadVPNTests/LoggingTests.swift` line 37 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3czQA1lQ8kJUn31Wt:-Nw4A02e3RH6XDmBihHq:b3sb5nz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LoggingTests.swift#L37)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`let contents = try XCTUnwrap(String(contentsOf: fileURL))` is much easier to read (we also need to mark the test as `throws` 
Same for the test below
</blockquote></details>

Didn't want to intrude too much on the existing code, just fix the lint error. But let's change it now that it's been pointed out.
___
*[`ios/MullvadVPNTests/LogRotationTests.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3eYmJ3c3NRAhK2y7d:-Nw4AUTZ8LiEVaRcf-JK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LogRotationTests.swift#L35)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`exptectedLogCount` -> `expectedLogCount`
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/LogRotationTests.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3himVCLxhkyCmYL7g:-Nw4AWNBCtI1e-8-rSue:b-ycwiiv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LogRotationTests.swift#L138)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
if you look at the files generated during the tests, it just looks like empty space, that's quite fun !
But it's not a big deal
</blockquote></details>

Felt like the most secure way to generate one byte per character. But I guess I could go with an "a" or something.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: 12 of 16 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3jCq_7xH-b2AzBbi2:-Nw3lKPM85mnmdnaSIUT:b-n97lsq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L109)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

There is a caveat here. If the incoming data chunks themselves are larger than `fileSizeLimit`, no logs will be written at all. AND many many new log files will be created.
</blockquote></details>

Can't we truncate the incoming data into different smaller chunks and write them in different files throughs a loop if the data size is bigger the limit?



_Code snippet:_
```Swift
    fileprivate func rotateFile(handle: FileHandle, data: Data) throws {
        var limit = fileSizeLimit
        var offset: UInt64 = 0

        let size = UInt64(data.count)

        while offset < data.count {
            try handle.close()
            state = .closed
            fileURL = try incrementFileName()
            limit = offset + limit < size ? limit : (size - offset)
            write(String(data: data[Data.Index(offset) ..< Data.Index(offset + limit)], encoding: encoding) ?? "")
            offset += limit
        }

        partialFileSizeCounter = 0
    }
```

**Review by acb-mv — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPNTests/LogRotationTests.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3himVCLxhkyCmYL7g:-NwJRFf90ZpJL5Y_yEz-:b-wer2aq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LogRotationTests.swift#L138)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Felt like the most secure way to generate one byte per character. But I guess I could go with an "a" or something.
</blockquote></details>

If you want a sequence that's less featureless, you could do something like 

```
(0..<size).map { "\($0%10)" }.joined(separator: '')
```
which gives you `0123456789012...`, or something similar.

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: all files reviewed, 10 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3jCq_7xH-b2AzBbi2:-NwK49ya3upzCL9URRBs:b-p5lxro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L109)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Can't we truncate the incoming data into different smaller chunks and write them in different files throughs a loop if the data size is bigger the limit?
</blockquote></details>

`write()` calls to an async queue, so the while loop here gets interweaved with calls from the re-queued items as well as the current item being processed. Perhaps we can do something of similar logic though. What do @acb-mv or @buggmagnet think? Worth the extra effort?
___
*[`ios/MullvadVPNTests/LogRotationTests.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3himVCLxhkyCmYL7g:-NwJsb4X4WfZo-_hHV4S:b-rqhyyw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadVPNTests/LogRotationTests.swift#L138)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

If you want a sequence that's less featureless, you could do something like 

```
(0..<size).map { "\($0%10)" }.joined(separator: '')
```
which gives you `0123456789012...`, or something similar.
</blockquote></details>

I like it 👍

**Review by buggmagnet — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv, @mojganii, and @rablador)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3jCq_7xH-b2AzBbi2:-Nwcfgyy4p_6yEEyDl4I:bgko8o7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L109)):*
> If the incoming data chunks themselves are larger than `fileSizeLimit`, no logs will be written at all. AND many many new log files will be created.

You are technically correct, but it's not a realistic problem to solve IMHO, 128k data to write is a truckload of data, especially given that we control most of the data written to the log files.

I would say in that case, throw an error and drop all the data. We shouldn't make this more complicated than it already is.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nwcdd-T-yacH_eg94fv:-Nwcdd-T-yacH_eg94fw:b6tvt98) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2091c4353ecd16076f3a74a86565a95c4fcc3a42/ios/MullvadLogging/LogFileOutputStream.swift#L78)):*
> ```Swift
>     }
> 
>     private func writeNoQueue(_ string: String) {
> ```

nit
Everytime I read this method name, I'm confused because it's only ever called from the dispatch queue we have here. 
Can we rename this `writeOnQueue` instead ?

Also we should sprinkle some `dispatchPrecondition(condition: .onQueue(queue))` in every function that is called on the queue to help get more contextual information as to what happens where IMHO
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6539 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NwcgUvh7wkJOcuYVmM4:-NwcgUvh7wkJOcuYVmM5:bsdq4t0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2091c4353ecd16076f3a74a86565a95c4fcc3a42/ios/MullvadVPN.xcodeproj/project.pbxproj#L6539)):*
> ```
> 				PRODUCT_BUNDLE_IDENTIFIER = "$(APPLICATION_IDENTIFIER)";
> 				PRODUCT_NAME = "$(TARGET_NAME)";
> 				SUPPORTED_PLATFORMS = "iphoneos iphonesimulator";
> ```

What about these changes, did you mean to check them in ?

**Review by rablador — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 109 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nw3jCq_7xH-b2AzBbi2:-Nwcxk-e87MPSYKf__O_:bqrl0yv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fbccb8ed957621783d0c80ca245a3b16a50a0f/ios/MullvadLogging/LogFileOutputStream.swift#L109)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> If the incoming data chunks themselves are larger than `fileSizeLimit`, no logs will be written at all. AND many many new log files will be created.

You are technically correct, but it's not a realistic problem to solve IMHO, 128k data to write is a truckload of data, especially given that we control most of the data written to the log files.

I would say in that case, throw an error and drop all the data. We shouldn't make this more complicated than it already is.
</blockquote></details>

I think you're right. If we throw an error, the data will be buffered (and trimmed), thus solving the immediate problem of chunk size being too large. It doesn't really fix anything, but it handles deviations gracefully, which is good enough I think.
___
*[`ios/MullvadLogging/LogFileOutputStream.swift` line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-Nwcdd-T-yacH_eg94fv:-Nwcu_lc2aR5EwKAx0pS:b-ne7w75) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2091c4353ecd16076f3a74a86565a95c4fcc3a42/ios/MullvadLogging/LogFileOutputStream.swift#L78)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Everytime I read this method name, I'm confused because it's only ever called from the dispatch queue we have here. 
Can we rename this `writeOnQueue` instead ?

Also we should sprinkle some `dispatchPrecondition(condition: .onQueue(queue))` in every function that is called on the queue to help get more contextual information as to what happens where IMHO
</blockquote></details>

Added a `dispatchPrecondition` to `write(fileHandle: FileHandle, data: Data)` since that's were the actual writing happens. We can end up there either directly from a function call or indirectly from a timer call.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6539 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-NwcgUvh7wkJOcuYVmM4:-NwckaC18OaDzfMojkAh:b-wngnuj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2091c4353ecd16076f3a74a86565a95c4fcc3a42/ios/MullvadVPN.xcodeproj/project.pbxproj#L6539)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

What about these changes, did you mean to check them in ?
</blockquote></details>

The changes you see are probably between revisions where I either messed up or restored the mess. If you compare first and last revision there will be no changes here.

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151#-:-NxCErAaEyaoimskBxNk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Pull request merged**
