### PR TITLE
Add tunnel state GUI tests

### PR DESCRIPTION
**Pull request by raksooo**
This PR adds tests of the UI for different settings configurations (tunnel protocol, transport protocol, port, multihop, bridge mode, quantum resistant tunnels etc.).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783)

### CODE REVIEW

**Review by hankolsen — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXidYwB0-KRNjDAYpq4:-NXidYwC-AIQ2MCj07BE:b-vs5ozf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L56)):*
> ```XML
>   await expect(outIp).toBeVisible();
> 
>   const ipResponse = await fetch('https://am.i.mullvad.net/ip');
> ```

We probably shouldn't hardcode this, because we'll probably want to use staging here. Should we either pass in the URL or the expected exit hostname here?
___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXig-HqD_-ioDKgiK4x:-NXig-HqD_-ioDKgiK4y:b-uzykm0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L81)):*
> ```XML
>   const inData = page.locator(':text("In") + span');
> 
>   await expect(inData).toContainText(new RegExp('UDP$'));
> ```

Maybe we should set obfuscation to `off` explicitly first? If it's auto, obfuscation just might be enabled if it cannot connect on the first couple of attempts.
___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXiekYOAO5DWi2mDa3x:-NXiekYOAO5DWi2mDa3y:btl33aj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L103)):*
> ```XML
> 
>   await expect(inData).toContainText(new RegExp(':[0-9]+'));
>   await expect(inData).toContainText(new RegExp('UDP$'));
> ```

If there are multiple connection attempts, this test could fail. Maybe we should accept TCP here as well.

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXidYwB0-KRNjDAYpq4:-NXihZt06QHti18s4IAI:bmljs1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L56)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We probably shouldn't hardcode this, because we'll probably want to use staging here. Should we either pass in the URL or the expected exit hostname here?
</blockquote></details>

Maybe we have to pass in the URL since the exit IP can vary.

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dlon and @hankolsen)

___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXidYwB0-KRNjDAYpq4:-NXiqJRy9OzR1ooCxFJY:b-38nis0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L56)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe we have to pass in the URL since the exit IP can vary.
</blockquote></details>

I've now added it as an env-variable.
___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXig-HqD_-ioDKgiK4x:-NXiqOkt5luTMTSX6d0y:b1a77qn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L81)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe we should set obfuscation to `off` explicitly first? If it's auto, obfuscation just might be enabled if it cannot connect on the first couple of attempts.
</blockquote></details>

Good idea! I moved it down to check this after turning it off again.
___
*[`gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts` line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783#-NXiekYOAO5DWi2mDa3x:-NXiqTNkDMiFrfgRto_B:b-4k0685) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0cda0b5c7a09a02bd6eb07f632aa578276bfd5a9/gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts#L103)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If there are multiple connection attempts, this test could fail. Maybe we should accept TCP here as well.
</blockquote></details>

Good point! Done.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4783)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
