### PR TITLE
Update split tunnel driver to 1.2.0.0

### PR DESCRIPTION
**Pull request by mvd-ows**
New driver version + new file locations in the binaries submodule.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[CHANGELOG.md, line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255#-MtCbMVz05SM1QSzFBRC:-MtCbMVz05SM1QSzFBRD:bjvhldv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/428b5687e8c4ad6d449240043b36dba46c30953f/CHANGELOG.md#L64)):*
> ```Markdown
>   Wintun.
> - Increase firewall transaction timeout from 2 to 5 seconds.
> - Update split tunnel driver to 1.2.0.0.
> ```

The firewall filter fix probably deserves its own changelog entry as well.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[CHANGELOG.md, line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255#-MtCbMVz05SM1QSzFBRC:-MtCee9kD5Jv4WqniGgG:br8n7u3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/428b5687e8c4ad6d449240043b36dba46c30953f/CHANGELOG.md#L64)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The firewall filter fix probably deserves its own changelog entry as well.
</blockquote></details>

That's a good point. But how can we apply this consistently? I don't think we want to always duplicate the driver changelog verbatim?

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[CHANGELOG.md, line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255#-MtCbMVz05SM1QSzFBRC:-MtChLCI5U_PfUYdPAkx:b-g923kf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/428b5687e8c4ad6d449240043b36dba46c30953f/CHANGELOG.md#L64)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

That's a good point. But how can we apply this consistently? I don't think we want to always duplicate the driver changelog verbatim?
</blockquote></details>

Maybe this one should only contain the most important changes, and only details that users will care about. In this case, "Allow firewall filters added by other software to block traffic for excluded apps", or something like that.

**Review by mvd-ows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dlon)

___
*[CHANGELOG.md, line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255#-MtCbMVz05SM1QSzFBRC:-MtErKvFBymqgxg-kuim:bu8ir3d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/428b5687e8c4ad6d449240043b36dba46c30953f/CHANGELOG.md#L64)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe this one should only contain the most important changes, and only details that users will care about. In this case, "Allow firewall filters added by other software to block traffic for excluded apps", or something like that.
</blockquote></details>

Done. Text OK?

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255#-:-MtF1RKW-LpIsUZ-8lUp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
