### PR TITLE
Block traffic before the network is up on Linux

### PR DESCRIPTION
**Pull request by pinkisemils**
There have been reported leaks that happen due to the daemon starting too late. These changes address this leak window in two ways:
- the daemon may now be started before the networking daemons start
- a new systemd unit that is started before `basic.target` is added that will setup blocking rules is added. 

To support the daemon starting sooner, it must now wait for the network managmenet services to be started to manage DNS, so some new DBus code has been added to do that via RPCs and signals with systemd.

To support blocking traffic during early boot, the daemon now has a new argument for this exact purpose - the daemon will start, initialize the firewall to a blocked state and exit. 

In addition to the changes above, the daemon's unit file is changed so that the resource directory is set explicitly via an environment variable, the `/opt/` mountpoint is listed as a dependency, and the daemon unit is listed as  a dependency of some known network management services. The early boot blocking unit is listed as a dependency of the daemon and the `basic.target` - this ensures it's ran before any of the networking services have started. To ensure that the dameon binary and the unit files are accessible during early boot, they have been moved to `/usr/...`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)

### CODE REVIEW

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`dist-assets/linux/mullvad-early-boot-blocking.service` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6RSW5zXle3Ky9qTs:-NBM6RSX9JSS4ewofYxN:b-b96vwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/mullvad-early-boot-blocking.service#L1)):*
> ```desktop
> # Systemd service unit file to block all traffic during early boot.
> ```

This file is very similar to the one above. I suppose only one of them should be in the PR?

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/early_boot_firewall.rs` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM8FWA1sllEXGik8_I:-NBM8FWA1sllEXGik8_J:bwsg0pq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/mullvad-daemon/src/early_boot_firewall.rs#L30)):*
> ```XML
>             endpoint: talpid_types::net::Endpoint {
>                 address: (std::net::Ipv4Addr::LOCALHOST, 0).into(),
>                 protocol: talpid_types::net::TransportProtocol::Tcp,
> ```

Seems a bit hackish to allow `127.0.0.1:0/TCP`. At the very least this needs a comment explaining itself. And the best would of course be to restructure stuff a bit to not need it at all.

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 7 of 18 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[`dist-assets/linux/before-install.sh` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6W7y9YEuBkdPJ-1Q:-NBM6W7y9YEuBkdPJ-1R:b-xibyj6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/before-install.sh#L9)):*
> ```Shell
>         systemctl stop mullvad-daemon.service
>         systemctl disable mullvad-daemon.service
>         systemctl stop mullvad-early-boot-blocking.service || true
> ```

Should this not be unconditional (on `mullvad-daemon` running)? `systemctl status` above will only return 0 if `mullvad-daemon` is running.
___
*[`dist-assets/linux/mullvad-early-boot-block.service` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM8YND1kPTOpb7X1yX:-NBM8YND1kPTOpb7X1yY:btsi6c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/mullvad-early-boot-block.service#L1)):*
> ```desktop
> # Systemd service unit file to block all traffic during early boot.
> ```

This is never used.
___
*[`talpid-dbus/src/systemd/mod.rs` line 122 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBIwIr98d-RzRuBMYyO:-NBIwIr98d-RzRuBMYyP:b19uyq7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/talpid-dbus/src/systemd/mod.rs#L122)):*
> ```XML
>                 move |job_finished: JobRemovedSignal, _connection, _message| {
>                     if job_finished.primary_name == unit_name {
>                         println!(
> ```

Use `log` or remove this.
___
*[`talpid-dbus/src/systemd/mod.rs` line 167 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBIwaOW4Hf42bcsgDlw:-NBIwaOW4Hf42bcsgDlx:b19uyq7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/talpid-dbus/src/systemd/mod.rs#L167)):*
> ```XML
>                 .map(Unit::is_active)
>                 .map(|is_active| {
>                     println!("Only checking if unit is active after not receiving a signal about it - {is_active}");
> ```

Use `log` or remove this.

**Review by dlon — COMMENTED** [review]
> Reviewed 4 of 18 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 7 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`CHANGELOG.md` line 39 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMiWKG-anl3KAih50e:-NBMiWKG-anl3KAih50f:bi60ful) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aea93b6121a5e8eb92e6e231bba13d9ec946ff7e/CHANGELOG.md#L39)):*
> Add

I also think it should be slightly more descriptive. "Block network traffic on boot before the daemon starts"?
___
*[`dist-assets/linux/mullvad-daemon.service` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMixZS7LBE-9Lw8KiF:-NBMixZS7LBE-9Lw8KiG:b3amx82) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aea93b6121a5e8eb92e6e231bba13d9ec946ff7e/dist-assets/linux/mullvad-daemon.service#L7)):*
> ```desktop
> Description=Mullvad VPN daemon
> Before=network-online.target
> After=mullvad-early-boot-blocking.service
> ```

Should these not be added back now?

```
After=network-online.target
After=NetworkManager.service
After=systemd-resolved.service
```

**Review by dlon — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 6 unresolved discussions (waiting on @faern and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: 21 of 25 files reviewed, 6 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[`dist-assets/linux/before-install.sh` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6W7y9YEuBkdPJ-1Q:-NBMhaTW7BkqFYq-huJB:byidqur) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/before-install.sh#L9)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this not be unconditional (on `mullvad-daemon` running)? `systemctl status` above will only return 0 if `mullvad-daemon` is running.
</blockquote></details>

Really, due to the short-lived nature of the blocking unit, this line should be removed in it's entirety - the unit runs in less than a second and must only run once during bootup.
___
*[`dist-assets/linux/mullvad-daemon.service` line 7 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMixZS7LBE-9Lw8KiF:-NBN6DLz0EvD6UM26jEL:bb77ucv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aea93b6121a5e8eb92e6e231bba13d9ec946ff7e/dist-assets/linux/mullvad-daemon.service#L7)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should these not be added back now?

```
After=network-online.target
After=NetworkManager.service
After=systemd-resolved.service
```
</blockquote></details>

Yep.
___
*[`dist-assets/linux/mullvad-early-boot-blocking.service` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6RSW5zXle3Ky9qTs:-NBN6BzY9-R-ZeRvdl3E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/mullvad-early-boot-blocking.service#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This file is very similar to the one above. I suppose only one of them should be in the PR?
</blockquote></details>

Done.
___
*[`dist-assets/linux/post-transaction.sh` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMEpuRBBgDiLRNry_N:-NBMi07DAdYoHhTLXS8U:bcsq3wo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/post-transaction.sh#L8)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Would it make sense to check whether the daemon is running in `early-boot` instead? That way, it never hurts if the blocking unit is somehow started after the daemon.
</blockquote></details>

That way lies race conditions, unfortunately. The daemon only _needs_ to be enabled if it _isn't_ enabled. 
___
*[`mullvad-daemon/src/early_boot_firewall.rs` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM8FWA1sllEXGik8_I:-NBN3Lhw3oF7TeazJ2Bl:bkscgv1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/mullvad-daemon/src/early_boot_firewall.rs#L30)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The allowed endpoint should probably be optional.
</blockquote></details>

Making it optional seems to be the correct thing to do here.

**Review by dlon — APPROVED** [review]
> Reviewed 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`CHANGELOG.md` line 39 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBNRvrf3rwt66sVxmpx:-NBNRvrf3rwt66sVxmpy:b8ncvou) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d3ff1b6862df76bb429867f4037e1885897950cc/CHANGELOG.md#L39)):*
> ```Markdown
> - GUI: Add electron flags to run Wayland native if in a compositor/desktop known to work well
> - Add support for Linux ARM64.
> - Added traffic blocking during early boot, before the daemon starts.
> ```

This should definitely be under `### Security`. And mention it stops potential leaks happening when systemd starts our daemon late.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`talpid-core/src/dns/linux/network_manager.rs` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMHoy7AW0n1r_1OmR1:-NBOflZR-xONOWgIm_my:bqg2xzr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/talpid-core/src/dns/linux/network_manager.rs#L32)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Echoing what was said elsewhere: Can this not just rely on systemd to ensure that NetworkManager is running here?
</blockquote></details>

Just because it's running doesn't necessarily mean it's working in a way that's usable by our daemon. Just because the service is running doesn't imply it's managing DNS too, unfortunately.

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`dist-assets/linux/before-install.sh` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6W7y9YEuBkdPJ-1Q:-NBR3TrCCQx2enyr5Kmr:b9jjohr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/before-install.sh#L9)):*
If I understand this description of `oneshot` from the man page correctly, the service is considered to be up forever once started:

> Behavior of oneshot is similar to simple; however, the service manager will consider the unit up after the main process exits.
___
*[`dist-assets/linux/post-transaction.sh` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMEpuRBBgDiLRNry_N:-NBR0opT7wd6sqrvH8nr:b-o4yvku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/post-transaction.sh#L8)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

That way lies race conditions, unfortunately. The daemon only _needs_ to be enabled if it _isn't_ enabled. 
</blockquote></details>

Couldn't `mullvad-daemon --initialize-early-boot-firewall` check if the UDS exists, like the daemon in general does if you try to launch another instance of it?

But it's not important since it only matters if the services are launched in the wrong order.
___
*[`talpid-core/src/dns/linux/network_manager.rs` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMHoy7AW0n1r_1OmR1:-NBR0JnR2l7b4pgGrVZj:b-hiphrd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/talpid-core/src/dns/linux/network_manager.rs#L32)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Just because it's running doesn't necessarily mean it's working in a way that's usable by our daemon. Just because the service is running doesn't imply it's managing DNS too, unfortunately.
</blockquote></details>

This is good. I meant to submit the comment before the `systemd` module was removed, so it's moot.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`CHANGELOG.md` line 94 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBq8Is10c1sH7EQGGa5:-NBq8Is10c1sH7EQGGa6:bueuuwj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/574888b96aec575a0d71056c434543cf7eab3ca7/CHANGELOG.md#L94)):*
> ```Markdown
> ### Security
> #### Linux
> - Added traffic blocking during early boot, before the daemon starts, to prevent leaks in the case
> ```

This belongs under `Unreleased`.
___
*[`dist-assets/linux/before-install.sh` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6W7y9YEuBkdPJ-1Q:-NBq9qYs0PAqHYR4os1i:bzdpqga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/before-install.sh#L9)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The unit will be in an _active_ state, but it only has to be activated once, but it doesn't imply that the service will continue running. 
</blockquote></details>

Got it. I suppose you could remove this, unless `systemctl enable ...` will fail if you do.
___
*[`dist-assets/linux/post-transaction.sh` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBMEpuRBBgDiLRNry_N:-NBq9cEDBm5Td4TE1fKH:b-rf09q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/post-transaction.sh#L8)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The daemon could well be starting up and not yet created the UDS when the early boot unit would be executing. It'd work out if the early boot unit was to create the UDS to force all subsequent daemon instances to wait on it, but that would be messy since currently the daemon (rightfully IMO) shuts down if the control UDS already exists.
</blockquote></details>

That's fair.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: 23 of 25 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`CHANGELOG.md` line 94 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBq8Is10c1sH7EQGGa5:-NBqFrXPC1muGOoz7tZH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/574888b96aec575a0d71056c434543cf7eab3ca7/CHANGELOG.md#L94)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This belongs under `Unreleased`.
</blockquote></details>

Done.
___
*[`dist-assets/linux/before-install.sh` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904#-NBM6W7y9YEuBkdPJ-1Q:-NBqFIJ517nPIuD3WIQ1:b-g5q17r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e62ec75d6bdccc3e037150efcf5bf5a41467aef/dist-assets/linux/before-install.sh#L9)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Got it. I suppose you could remove this, unless `systemctl enable ...` will fail if you do.
</blockquote></details>

It shouldn't fail, so I have removed this.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3904)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
