### PR TITLE
Unblock device manager

### PR DESCRIPTION
**Pull request by pinkisemils**
The device manager is slightly refactored to have a single API call future be used at any one time for the purposes of logging in, validation and key rotation which won't block the device manager actor. This fixes a deadlock in the daemon and allows for a more consistent state of the device manager. I've also done some small refactoring by putting most of the API code into it's own module, and de-asyncronified functions which don't actually await any futures within them.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: 3 of 6 files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device/service.rs, line 388 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-SntVn-lGNVhZIIriG:-N-SntVoCLL_IpCz3-Yd:b-ltfxz0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb0da5c135ac0b6d6265b921ba93ad4267a44b7d/mullvad-daemon/src/device/service.rs#L388)):*
> ```XML
>         Ok(_) => false,
>         Err(error) => {
>             if let RestError::ApiError(status, code) = error {
> ```

All of our retry logic for long-running requests is pretty ad hoc. I wonder if we could just in general never retry whenever there's a valid HTTP response, or at least when it's not a `5xx` code. We could maybe even just use `should_retry`.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/device/service.rs, line 388 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-SntVn-lGNVhZIIriG:-N-TSlyfBLdRgEA4TOqI:b-153bh2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb0da5c135ac0b6d6265b921ba93ad4267a44b7d/mullvad-daemon/src/device/service.rs#L388)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

All of our retry logic for long-running requests is pretty ad hoc. I wonder if we could just in general never retry whenever there's a valid HTTP response, or at least when it's not a `5xx` code. We could maybe even just use `should_retry`.
</blockquote></details>

I think we could make it a trait and have a type that fits most (all?) use cases? Looking at the API crate as it is today, it definitely looks like I've done a poor job coming up with abstractions, specifically I'm referring to the many functions that take more than 3 arguments.

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: all files reviewed, 13 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device/api.rs, line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XEr8N0rY2U0qpG98J:-N-XEr8N0rY2U0qpG98K:b-h56ts5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b354d241bb1305367d38b54cfed8f7a95c27cc8/mullvad-daemon/src/device/api.rs#L68)):*
> ```XML
>         match self.current_call.as_mut() {
>             Some(mut call) => {
>                 let result = Pin::new(&mut call).poll(cx);
> ```

Nit: Why `&mut`? Isn't this already a mutable reference?
___
*[mullvad-daemon/src/device/api.rs, line 105 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XJnsG71lh2YN31-oJ:-N-XJnsG71lh2YN31-oK:but38a3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b354d241bb1305367d38b54cfed8f7a95c27cc8/mullvad-daemon/src/device/api.rs#L105)):*
> ```XML
>             Login(call, tx) => {
>                 futures::pin_mut!(call);
>                 if let std::task::Poll::Ready(response) = call.poll(cx) {
> ```

Nit: I think you could just `Pin::new(call)` here (and below) and remove the `pin_mut!`, since `call` implements `Unpin`.
___
*[mullvad-daemon/src/device/mod.rs, line 411 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-TVU6M8wHyau5OPTc3:-N-XPQR72kfgGPrMFVeq:by354ry) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0b9bfe585d37ef1b3421fc3c682ccebe823308/mullvad-daemon/src/device/mod.rs#L411)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this be a panic?
</blockquote></details>

Arguably, yes. It will be easier to catch bugs in this code if it is not overly defensive.
___
*[mullvad-daemon/src/device/mod.rs, line 471 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-TVRt5AlMXi8Uy6NJu:-N-XPVns2GW0lKC4DRHS:b-dhsu9a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0b9bfe585d37ef1b3421fc3c682ccebe823308/mullvad-daemon/src/device/mod.rs#L471)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this be a panic?
</blockquote></details>

See the answer above.
___
*[mullvad-daemon/src/device/mod.rs, line 130 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XOsHZD030oO4xWqz4:-N-XOsHZD030oO4xWqz5:b17whov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L130)):*
> ```XML
>     /// The device was not found remotely and was removed from the cache.
>     Removed,
>     /// Failed to reach the API
> ```

This could be removed.
___
*[mullvad-daemon/src/device/mod.rs, line 295 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XQSXEDDByq0b_9Aso:-N-XQSXEDDByq0b_9Asp:bnf91ro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L295)):*
> ```XML
>                             let _ = tx.send(self.set(InnerDeviceEvent::Login(data)).await);
>                         }
>                         Some(AccountManagerCommand::GetData(tx)) => {
> ```

This will not be handled correctly by the "migration event" handler in the daemon now. That code does not use the "device manager", so its request is not aborted. Perhaps it should just give up if `GetData` fails for any reason.
___
*[mullvad-daemon/src/device/mod.rs, line 297 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XhH8_Aq6JTSKWYteE:-N-XhH8_Aq6JTSKWYteF:bg43bzo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L297)):*
> ```XML
>                         Some(AccountManagerCommand::GetData(tx)) => {
>                             if current_api_call.is_logging_in() {
>                                 let _ = tx.send(Err(Error::AccountChange));
> ```

If tunnel parameters are generated while a new account is being logged in to, the TSM will transition to the error state, but the daemon will automatically reconnect once the "device event" is sent, I think. Is this correct?
___
*[mullvad-daemon/src/device/mod.rs, line 321 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xj5D630d0ZBm0-PDP:-N-Xj5D630d0ZBm0-PDQ:bv0asxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L321)):*
> ```XML
>                         }
>                         Some(AccountManagerCommand::SetRotationInterval(interval, tx)) => {
>                             self.rotation_interval = interval;
> ```

`current_api_call` must be cleared if the background rotation task is currently running, so that it's restarted.
___
*[mullvad-daemon/src/device/mod.rs, line 426 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XoTtSDMFqOn8NswWx:-N-XoTtSDMFqOn8NswWy:b2brpk2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L426)):*
> ```XML
>                         Ok(_) => {
>                             Self::drain_requests(&mut self.validation_requests, || {
>                                 Ok(ValidationResult::Valid)
> ```

It looks like `ValidationResult::Updated` is never used anymore. It does seem like we no longer need it, but, if so, the variant should be removed.
___
*[mullvad-daemon/src/device/mod.rs, line 443 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XpBPN860cLBB3Gg93:-N-XpBPN860cLBB3Gg94:bvtkze1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L443)):*
> ```XML
>             }
>             Err(Error::InvalidDevice) => {
>                 self.invalidate_current_data(|| Error::InvalidDevice).await;
> ```

A device being "revoked" is not an error, in my opinion. Maybe you could drain the validation requests with `Ok(ValidationResult::Revoked))` for the closure before invalidating the data?

If you do think that it's simpler/better for it to be an error, then `on_update_device` in the daemon must be updated to handle this outcome. Also, the variant should be removed.
___
*[mullvad-daemon/src/device/mod.rs, line 567 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xv8pdD2oaKe8_xXHl:-N-Xv8pdD2oaKe8_xXHm:bz19l4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L567)):*
> ```XML
> 
>             tokio::spawn(async move {
>                 let _ = tokio::time::timeout(LOGOUT_TIMEOUT, logout_call).await;
> ```

This seems incorrect. If this short interval elapses, the logout task is supposed to continue to run in the background (and probably give up after some number of attempts).
___
*[mullvad-daemon/src/device/mod.rs, line 658 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XlBPi4viWHu5YFk0R:-N-XlBPi4viWHu5YFk0S:bq4pqja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L658)):*
> ```XML
> 
>     fn validation_call(&self) -> Result<impl Future<Output = Result<Device, Error>>, Error> {
>         let old_data = self.data.clone().ok_or(Error::NoDevice)?;
> ```

Nit: This could obtain a reference with `self.data.as_ref().ok_or(...)?` instead of cloning everything.
___
*[mullvad-daemon/src/device/service.rs, line 388 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-SntVn-lGNVhZIIriG:-N-XtAez2xaRLrDnznAo:b-6tzlsp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb0da5c135ac0b6d6265b921ba93ad4267a44b7d/mullvad-daemon/src/device/service.rs#L388)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think we could make it a trait and have a type that fits most (all?) use cases? Looking at the API crate as it is today, it definitely looks like I've done a poor job coming up with abstractions, specifically I'm referring to the many functions that take more than 3 arguments.
</blockquote></details>

That seems like a good idea, but probably out of scope for this PR.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: all files reviewed, 13 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device/mod.rs, line 643 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xz3s3EbwDYfZulP-z:-N-Xz3s3EbwDYfZulP0-:b-f425co) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L643)):*
> ```XML
>                 time_until_next_rotation.as_secs(),
>             );
>             talpid_time::sleep(time_until_next_rotation).await
> ```

We're kind of trusting that the initial realtime clock is correct here. Do you think that the terrible recheck-at-short-intervals approach would work better? But I'm not sure how precise it needs to be. Besides, the task is restarted once in a while.

Side-note: Testing will be a bit confusing now, as changing the time won't have an effect on its own. :P

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/device/mod.rs, line 297 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XhH8_Aq6JTSKWYteE:-N-bbzll3PD2M3wvXhq1:b-v2ez8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L297)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If tunnel parameters are generated while a new account is being logged in to, the TSM will transition to the error state, but the daemon will automatically reconnect once the "device event" is sent, I think. Is this correct?
</blockquote></details>

You're correct, let's just give old data and then notify users of new data when it does arrive.
___
*[mullvad-daemon/src/device/mod.rs, line 321 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xj5D630d0ZBm0-PDP:-N-bc68204XBEWkN_jTZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L321)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`current_api_call` must be cleared if the background rotation task is currently running, so that it's restarted.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device/mod.rs, line 426 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XoTtSDMFqOn8NswWx:-N-bceyOCAJPzg-JJo9V:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L426)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It looks like `ValidationResult::Updated` is never used anymore. It does seem like we no longer need it, but, if so, the variant should be removed.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device/mod.rs, line 443 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XpBPN860cLBB3Gg93:-N-bcfbm-CPAsoDgI4Dx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L443)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

A device being "revoked" is not an error, in my opinion. Maybe you could drain the validation requests with `Ok(ValidationResult::Revoked))` for the closure before invalidating the data?

If you do think that it's simpler/better for it to be an error, then `on_update_device` in the daemon must be updated to handle this outcome. Also, the variant should be removed.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device/mod.rs, line 567 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xv8pdD2oaKe8_xXHl:-N-bcgnw8a5JwF5Nw1JH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L567)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This seems incorrect. If this short interval elapses, the logout task is supposed to continue to run in the background (and probably give up after some number of attempts).
</blockquote></details>

Done.
___
*[mullvad-daemon/src/device/mod.rs, line 643 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xz3s3EbwDYfZulP-z:-N-YM8DV4-RpQwXiRKln:bz7ces8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L643)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We're kind of trusting that the initial realtime clock is correct here. Do you think that the terrible recheck-at-short-intervals approach would work better? But I'm not sure how precise it needs to be. Besides, the task is restarted once in a while.

Side-note: Testing will be a bit confusing now, as changing the time won't have an effect on its own. :P
</blockquote></details>

I generally test by changing the RFC3389 directly.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/device/mod.rs, line 295 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-XQSXEDDByq0b_9Aso:-N-beOdt4eDLTk-IZ_8M:bazdt6u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L295)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This will not be handled correctly by the "migration event" handler in the daemon now. That code does not use the "device manager", so its request is not aborted. Perhaps it should just give up if `GetData` fails for any reason.
</blockquote></details>

I've simplified it so that `GetData` always returns data.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/device/mod.rs, line 321 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xj5D630d0ZBm0-PDP:-N-blW64-F7ttmHWqlsU:b-i4qhvh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L321)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is ok, but couldn't you simply clear the api call since it will be set after the `select` anyway? Or do you find that less readable?
___
*[mullvad-daemon/src/device/mod.rs, line 567 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xv8pdD2oaKe8_xXHl:-N-bluiQ4hZV3VwOG_R1:biaxddv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L567)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I might be missing something here, but I think that this could be far simpler:

```rust
tokio::spawn(async move {
    let timeout = tokio::time::timeout(LOGOUT_TIMEOUT, logout_call).await;
    let _ = tx.send(Ok(());
    if timeout.is_err() {
        tokio::spawn(logout_call);
    }
});
```

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/device/mod.rs, line 567 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xv8pdD2oaKe8_xXHl:-N-bnhjD3DKQltx4QhmG:b-6s4lls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L567)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I might be missing something here, but I think that this could be far simpler:

```rust
tokio::spawn(async move {
    let timeout = tokio::time::timeout(LOGOUT_TIMEOUT, logout_call).await;
    let _ = tx.send(Ok(());
    if timeout.is_err() {
        tokio::spawn(logout_call);
    }
});
```
</blockquote></details>

(Without transferring ownership.)

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/device/mod.rs, line 553 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-cXXQ35sIx59aiU34B:-N-cXXQ35sIx59aiU34C:b-uelws9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36f47596fdd534024cb7e0b4c9f6473a2ab05a82/mullvad-daemon/src/device/mod.rs#L553)):*
> ```XML
> 
>     async fn logout(&mut self, tx: ResponseTx<()>) {
>         self.data_requests = vec![];
> ```

Will `GetDataAfterLogin` return `AccountManagerDown` here?

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mullvad-daemon/src/device/mod.rs, line 321 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xj5D630d0ZBm0-PDP:-N00SRJU4bVliDOCvNX7:b-tgbyh9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L321)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is ok, but couldn't you simply clear the api call since it will be set after the `select` anyway? Or do you find that less readable?
</blockquote></details>

Fair point, I've changed it to be simpler now.
___
*[mullvad-daemon/src/device/mod.rs, line 567 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-Xv8pdD2oaKe8_xXHl:-N00Ew_D2Y_YoyDKuWDP:bjx8vzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf8f1302834beb1cc14394d7f2ce9a1d42bd0c71/mullvad-daemon/src/device/mod.rs#L567)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

(Without transferring ownership.)
</blockquote></details>

`tokio::time::timeout()` takes ownership of the future, so a new logout call would have to be spawned after the first one times out, which I think is not ideal.
___
*[mullvad-daemon/src/device/mod.rs, line 553 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-N-cXXQ35sIx59aiU34B:-N00EWDfB9Cx3fS8PYoi:bb77ufg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36f47596fdd534024cb7e0b4c9f6473a2ab05a82/mullvad-daemon/src/device/mod.rs#L553)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Will `GetDataAfterLogin` return `AccountManagerDown` here?
</blockquote></details>

Yes.

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497#-:-N00hhubCjyA9J3Jk_lx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3497)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
