### PR TITLE
Update copyrights & minor refactoring

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Update copyright notice in `PacketTunnelSettingsGenerator.swift`.
1. Extract the `AnyIPEndpoint` into a separate file.
1. Implement `CustomStringConvertible` on `IPEndpoint<T>` (IPv4: `"<IP>:<PORT>"`, IPv6: "[<IP>]:<PORT>") & remove `AnyIPEndpoint+Wireguard.swift` file.
1. Removed unused options from hex formatter
1. Use `UInt32` constants.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2114)

### CODE REVIEW

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2114#-:-MHCCRNJ7cSmq2u48uxN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
Removed unused options in Data -> Hex formatter.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2114#-:-MHCDObz8BZHSQv2SRlJ:b3pkd06)* status: 6 of 7 files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2114)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — COMMENTED** [review]
Ugh sorry for that. After discussion on Slack I had to put back the use of UInt32 constants in my code. Haha I think it's better this way.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2114#-:-MHG40_O9aRSJxfCCv6Y:bx5oeo4)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @jvff)

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2114#-:-MHGPtw1BVkHuS8HnE_i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
