### PR TITLE
Extract the main content view

### PR DESCRIPTION
**Pull request by pronebird**
Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [X] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Extract the user interface from `ConnectViewController` into a `ConnectMainView`.
2. Fix layout margins in RootContainer to account for the system safeAreaInsets, which previously caused the content view to be offset by 20pt below the header bar (which is the exact size of a status bar on my iPhone device)
3. Use fixed dimensions in the `DisconnectSplitButton` to avoid the infinite layout loop.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593)

### CODE REVIEW

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593#-:-MWBRcjr3ncvaBOPum5W:bnfp4nl)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/ConnectMainContentView.swift, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593#-MW6FQxCBG029wm6pjTQ:-MW6FQxDEDY6ysLcQmaY:buhi6q2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d46076276dd3c9629a1a3873475f3dac2a866a31/ios/MullvadVPN/ConnectMainContentView.swift#L19)):*
> ```Swift
> 
>     lazy var secureLabel: UILabel = {
>         let textLabel = UILabel()
> ```

Nit: Part of me itches to suggest to have a `makeBoldTextLabel(ofSize)` helper method to get the common code of the three cases, but another part thinks it's already readable as is :sweat_smile:

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[ios/MullvadVPN/ConnectViewController.swift, line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593#-MWBS2M01ESnqAs-Sk7S:-MWBS2M01ESnqAs-Sk7T:brytcd9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d46076276dd3c9629a1a3873475f3dac2a866a31/ios/MullvadVPN/ConnectViewController.swift#L58)):*
> ```Swift
> 
>         mainContentView.selectLocationButton.accessibilityIdentifier = "SelectLocationButton"
>         mainContentView.splitDisconnectButton.primaryButton.accessibilityIdentifier = "DisconnectButton"
> ```

Nit: Shouldn't this be in the `ConnectMainContentView`?
___
*[ios/MullvadVPN/ConnectViewController.swift, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593#-MWBWMZIC3WWyhXyD5Qr:-MWBWMZJ6Kl9pmkA2gzv:b-q2vaom) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d46076276dd3c9629a1a3873475f3dac2a866a31/ios/MullvadVPN/ConnectViewController.swift#L126)):*
> ```Swift
>     // MARK: - Private
> 
>     private func updateUserInterfaceForTunnelStateChange() {
> ```

FYI: Nice improvement in this function! :tada:

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff and @pronebird)

___
*[ios/MullvadVPN/ConnectViewController.swift, line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593#-MWBS2M01ESnqAs-Sk7S:-MWO7Z6Z8vR8J0zM8P5r:b-q5xsov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d46076276dd3c9629a1a3873475f3dac2a866a31/ios/MullvadVPN/ConnectViewController.swift#L58)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Shouldn't this be in the `ConnectMainContentView`?
</blockquote></details>

Good idea. Fixed.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[ios/MullvadVPN/ConnectMainContentView.swift, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593#-MW6FQxCBG029wm6pjTQ:-MWO4s1I4Taew47aJKAA:b8szdsp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d46076276dd3c9629a1a3873475f3dac2a866a31/ios/MullvadVPN/ConnectMainContentView.swift#L19)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Part of me itches to suggest to have a `makeBoldTextLabel(ofSize)` helper method to get the common code of the three cases, but another part thinks it's already readable as is :sweat_smile: 
</blockquote></details>

That's not that bad of a suggestion. Fixed.

**Review by jvff — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2593)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
