### PR TITLE
Set CVE suppression expiration to 2023-05-01

### PR DESCRIPTION
**Pull request by albin-mullvad**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214)

### CODE REVIEW

**Review by sabercodic — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by faern — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/e2e/e2e-suppression.xml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214#-NJBBkrq0DlwRNWlwnwj:-NJBBkrq0DlwRNWlwnwk:b-dsyn3b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c50040a46ccb9eaf31c143f6b41c318dbba5e24/android/e2e/e2e-suppression.xml#L9)):*
> ```XML
>     <suppress>
>         <notes><![CDATA[
>         This CVE is a false positive as the description refers to a GO library (github.com/containers/storage).
> ```

Can't we have both the notes and an `until` date? Or did you feel both was not needed? I feel like the note could help. When we revisit this in ~6 months the note can help us evaluate if the supression is still valid or not I guess.

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`android/e2e/e2e-suppression.xml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214#-NJBBkrq0DlwRNWlwnwj:-NJBCxOzCJLguktV9_2j:b-v9z09i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c50040a46ccb9eaf31c143f6b41c318dbba5e24/android/e2e/e2e-suppression.xml#L9)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can't we have both the notes and an `until` date? Or did you feel both was not needed? I feel like the note could help. When we revisit this in ~6 months the note can help us evaluate if the supression is still valid or not I guess.
</blockquote></details>

I'm not sure that I follow :thinking: Two suppressions were removed in a separate commit of the PR, as they were no longer needed. That's likely due to things getting fixed upstream.

**Review by faern — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/e2e/e2e-suppression.xml` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214#-NJBBkrq0DlwRNWlwnwj:-NJBP18X-YkSrhiMfuzP:b-4oezh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c50040a46ccb9eaf31c143f6b41c318dbba5e24/android/e2e/e2e-suppression.xml#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm not sure that I follow :thinking: Two suppressions were removed in a separate commit of the PR, as they were no longer needed. That's likely due to things getting fixed upstream.
</blockquote></details>

Aha. It's just me doing sloppy reading. I read it as `notes` was removed, CVE kept, `until` added. Don't mind me :lgtm:

**Pull request merged**
