### PR TITLE
Introduce PacketTunnelCore framework IOS-219

### PR DESCRIPTION
**Pull request by pronebird**
This PR introduces a new framework called PacketTunnelCore which currently includes TunnelMonitor and Pinger along with WgStats struct. The reason for introduction is because it's impossible to test PacketTunnel directly, but also because we rely on C headers to provide (packed) structs for IPV4 header and ICMP packet used by Pinger, which makes it difficult to go around that in any other way.

More detailed change log:

- Move TunnelMonitor, Pinger, WgStats into new framework
- Add TunnelMonitorProtocol, TunnelDeviceInfoProtocol, PingerProtocol protocols to improve testing/mocking
- Rework TunnelMonitor and Pinger to use block-based event handler instead of delegate
- Drop Objective-C bridging header from PacketTunnel
- Add tests for Pinger

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)

### CODE REVIEW

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelPathObserver.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnPBpE8i_qharvzqlx:-NbnPBpFD-APIhgusuI9:b-dkofs4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/PacketTunnelPathObserver.swift#L31)):*
> ```Swift
>             }
>         }
>         return observation ?? EmptyDefaultPathObservation()
> ```

What happens to the observing party if an empty pathobservation is returned? I could not find any code that would make it evident to the observer that nothing is ever going to be emitted.
___
*[`ios/PacketTunnel/WgAdapterDeviceInfo.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbn04wIBhLtMETdfPIn:-Nbn04wIBhLtMETdfPIo:b-3bwqr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/WgAdapterDeviceInfo.swift#L78)):*
> ```Swift
> }
> 
> @inline(__always) private func parseValue(_ prefixKey: String, in line: String) -> UInt64? {
> ```

I know this is old code, but is the optimisation needed here? I'm have no previous experience with `@inline`, but it seems to be generally cautioned against.
___
*[`ios/PacketTunnelCore/Pinger/Pinger.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnVWP163CHC_KaGzkg:-NbnVWP2-UdGU5tWva4-:b92dd47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnelCore/Pinger/Pinger.swift#L29)):*
> ```Swift
>     public var onReply: ((PingerReply) -> Void)? {
>         get {
>             stateLock.withLock {
> ```

withLock is nice 👍

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelPathObserver.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnPBpE8i_qharvzqlx:-NbsIgHUCWmFISWp0sqM:bfa1m6w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/PacketTunnelPathObserver.swift#L31)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

What happens to the observing party if an empty pathobservation is returned? I could not find any code that would make it evident to the observer that nothing is ever going to be emitted.
</blockquote></details>

If an instance of `NEPacketTunnelProvider` is released then the program is heading for termination. This is more of an edge case and I don't think we should handle it in any special way.
___
*[`ios/PacketTunnel/WgAdapterDeviceInfo.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbn04wIBhLtMETdfPIn:-NbsQH4yBebBReraSj2e:bo3lda2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/WgAdapterDeviceInfo.swift#L78)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I know this is old code, but is the optimisation needed here? I'm have no previous experience with `@inline`, but it seems to be generally cautioned against.
</blockquote></details>

It depends how you look at it. This code runs every second so I favored larger binary size vs. function call overhead at the time.
___
*[`ios/PacketTunnelCore/Pinger/Pinger.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnVWP163CHC_KaGzkg:-NbsJ-oM7Jc-C1n7VIKs:b-e9siz8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnelCore/Pinger/Pinger.swift#L29)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

withLock is nice 👍
</blockquote></details>

Yeah. This is new.

**Review by rablador — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelPathObserver.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnPBpE8i_qharvzqlx:-NbsfKrD7vjWrxZFTYPA:bxssdk3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/PacketTunnelPathObserver.swift#L31)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

If an instance of `NEPacketTunnelProvider` is released then the program is heading for termination. This is more of an edge case and I don't think we should handle it in any special way.
</blockquote></details>

Alright, but maybe this could be documented so that `EmptyDefaultPathObservation` doesn't look like a normally viable option?
___
*[`ios/PacketTunnel/WgAdapterDeviceInfo.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbn04wIBhLtMETdfPIn:-NbsfhV055bTitHG0oW0:bwr8kbj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/WgAdapterDeviceInfo.swift#L78)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It depends how you look at it. This code runs every second so I favored larger binary size vs. function call overhead at the time.
</blockquote></details>

That seems fair, as long as it's intentionally used for specific cases.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: 18 of 21 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelPathObserver.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnPBpE8i_qharvzqlx:-NbtRngH2BJZidLr431b:bdgmkt5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/PacketTunnelPathObserver.swift#L31)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Alright, but maybe this could be documented so that `EmptyDefaultPathObservation` doesn't look like a normally viable option?
</blockquote></details>

I reworked observer to hold `NSKeyValueObservation` internally and documented that `NEPacketTunnelProvider` should exist throughout the lifetime of network extension .
___
*[`ios/PacketTunnel/WgAdapterDeviceInfo.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbn04wIBhLtMETdfPIn:-NbtNgHb8mj3Jg2_O5MJ:bkdrszb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/WgAdapterDeviceInfo.swift#L78)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

That seems fair, as long as it's intentionally used for specific cases.
</blockquote></details>

That was intentional choice. The alternative would be to inline `parseValue()` manually, which would result in some code duplication, `@inline(__always)` should do this automatically for me.

```diff
@@ -55,10 +55,13 @@ private extension WgStats {
         var bytesReceived: UInt64?
         var bytesSent: UInt64?
 
+        let rxBytesKey = "rx_bytes="
+        let txBytesKey = "tx_bytes="
+
         string.enumerateLines { line, stop in
-            if bytesReceived == nil, let value = parseValue("rx_bytes=", in: line) {
+            if bytesReceived == nil, line.hasPrefix(rxBytesKey), let value = UInt64(line.dropFirst(rxBytesKey.count)) {
                 bytesReceived = value
-            } else if bytesSent == nil, let value = parseValue("tx_bytes=", in: line) {
+            } else if bytesSent == nil, line.hasPrefix(txBytesKey), let value = UInt64(line.dropFirst(txBytesKey.count)) {
                 bytesSent = value
             }
 
```

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelPathObserver.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-NbnPBpE8i_qharvzqlx:-NbtcIbQAjwtT8Rh9XI0:bamilfe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/PacketTunnelPathObserver.swift#L31)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I reworked observer to hold `NSKeyValueObservation` internally and documented that `NEPacketTunnelProvider` should exist throughout the lifetime of network extension .
</blockquote></details>

Better, both in terms of scoping start/stop inside the class as well as never returning something that shouldn't work.
___
*[`ios/PacketTunnel/WgAdapterDeviceInfo.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbn04wIBhLtMETdfPIn:-Nbtc6uT6CC-4YmcgOUf:b-wcxy6k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3832c7a692af8eb2f96c0c2b1cf133f98bbded4d/ios/PacketTunnel/WgAdapterDeviceInfo.swift#L78)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

That was intentional choice. The alternative would be to inline `parseValue()` manually, which would result in some code duplication, `@inline(__always)` should do this automatically for me.

```diff
@@ -55,10 +55,13 @@ private extension WgStats {
         var bytesReceived: UInt64?
         var bytesSent: UInt64?
 
+        let rxBytesKey = "rx_bytes="
+        let txBytesKey = "tx_bytes="
+
         string.enumerateLines { line, stop in
-            if bytesReceived == nil, let value = parseValue("rx_bytes=", in: line) {
+            if bytesReceived == nil, line.hasPrefix(rxBytesKey), let value = UInt64(line.dropFirst(rxBytesKey.count)) {
                 bytesReceived = value
-            } else if bytesSent == nil, let value = parseValue("tx_bytes=", in: line) {
+            } else if bytesSent == nil, line.hasPrefix(txBytesKey), let value = UInt64(line.dropLast(txBytesKey.count)) {
                 bytesSent = value
             }
 
```
</blockquote></details>

Yeah, I think it's fine. Resolved 👍
___
*[`ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift` line 373 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbtck4S0aiUcm_yqqVK:-Nbtck4S0aiUcm_yqqVL:b-sp2exo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/18bc5a050b0d4d7b2c4f14eab79378b546a97456/ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift#L373)):*
> ```Swift
> 
>     private func removeDefaultPathObserver() {
>         guard isObservingDefaultPath else { return }
> ```

I don't mind having a guard here, but nothing really happens if we try to stop an uninitialised observer, right? This is runtime effiecient maybe, but more state to handle.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift` line 373 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbtck4S0aiUcm_yqqVK:-NbxTQ4jC-UHEOMsg3gw:b-89i3mp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/18bc5a050b0d4d7b2c4f14eab79378b546a97456/ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift#L373)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I don't mind having a guard here, but nothing really happens if we try to stop an uninitialised observer, right? This is runtime effiecient maybe, but more state to handle.
</blockquote></details>

I think this codepath could be triggered in succession and therefore this guard prevents logging the same statement twice.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift` line 373 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008#-Nbtck4S0aiUcm_yqqVK:-NbxjFn89iVy2u5TkUJX:b-56mwkq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/18bc5a050b0d4d7b2c4f14eab79378b546a97456/ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift#L373)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think this codepath could be triggered in succession and therefore this guard prevents logging the same statement twice.
</blockquote></details>

Alright, let's keep it in.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5008)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
