### PR TITLE
Update in app expiry notifications over time

### PR DESCRIPTION
**Pull request by kl**
Changes the in app account expiry notifications to a flow that emits at the starts of the notification threshold (currently 3 days before expiry), and then emits every time the notification update duration is passed (currently 1 day). 

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851)* status: all files reviewed, 5 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O86-Uzm9tRLs30zx6l0:-O86-Uzm9tRLs30zx6l1:b-aczvym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt#L26)):*
> ```Kotlin
> 
> fun Period.isNegative() =
>     normalizedStandard().let {
> ```

Would any of these work instead?
```
    normalizedStandard().toStandardSeconds() < 0
```
or
```
    normalizedStandard().toStandardDuration().millis < 0
```
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O864_s2-4wUz_MfUw7o:-O864_s2-4wUz_MfUw7p:bvcn8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L14)):*
> ```Kotlin
>     tickStart: Duration,
>     updateInterval: (expiry: DateTime) -> Duration,
> ): Flow<Period> = flow {
> ```

Since I'm a bit senile, remind me, why did we say Period instead of Duration? 
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O863yxqB5Pz2jdAJQuW:-O863yxqB5Pz2jdAJQuX:btlcl81) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L41)):*
> ```Kotlin
>     var delayCount = calculateDelaysNeeded(expiry.millisFromNow(), currentUpdateInterval)
> 
>     while (delayCount > 0) {
> ```

I haven't fully thought this through, but it feels like it should work to make use of the `do {} while loop` https://kotlinlang.org/docs/control-flow.html#while-loops

```
    do {
        // emit()
        // newUpdate interval
        // calulate new delay
        // evaluate hasAnotherEmission
    } while(hasAnotherEmission)
    emit(Period.ZERO)
```

Then we should be able to remove these lines:
```
   // Always emit at start of flow.
    emit(Period(DateTime.now(), expiry))

    // Delay until the next update interval.
    delay(expiry.millisFromNow() % currentUpdateInterval)

    var delayCount = calculateDelaysNeeded(expiry.millisFromNow(), currentUpdateInterval)
```
whilst making the code more readable.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O861t-D8qnDe3ErHa68:-O861t-D8qnDe3ErHa69:b-7uv9i3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L64)):*
> ```Kotlin
> // Note that the returned delays may add upp to less than the remaining time, for example
> // if we have 100ms remaining and currentUpdateIntervalMillis is 40ms this function will return 2.
> private fun calculateDelaysNeeded(millisUntilExpiry: Long, currentUpdateIntervalMillis: Long): Int {
> ```

Shouldn't be a problem but we should consider to return `Long` since we are diving with `Long` to avoid any overflow.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O861TnH3Lw9ceyd3mZy:-O861TnI7DZGGrv4xhJs:b-x9vb6l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L68)):*
> ```Kotlin
>         0
>     } else {
>         (millisUntilExpiry / currentUpdateIntervalMillis).toInt()
> ```

This is `floorDiv` I believe.

**Review by Pururun — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851)* status: all files reviewed, 6 unresolved discussions (waiting on @kl)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryInAppNotificationUseCaseTest.kt` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O8GUlsT3H6Xk97TjTX2:-O8GUlsT3H6Xk97TjTX3:bz7fr7l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryInAppNotificationUseCaseTest.kt#L57)):*
> ```Kotlin
>     @Test
>     fun `initial state should be empty`() = runTest {
>         // Arrange, Act, Assert
> ```

This comment is kind of useless, so I think it should be either removed into `test { }` or removed.

**Review by kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851)* status: 7 of 16 files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O86-Uzm9tRLs30zx6l0:-O8G6gs7-_iPH2kAzh5E:by2b6gg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt#L26)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would any of these work instead?
```
    normalizedStandard().toStandardSeconds() < 0
```
or
```
    normalizedStandard().toStandardDuration().millis < 0
```
</blockquote></details>

No but we can do this instead ```fun Period.isNegative() = toStandardDuration().millis < 0```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryInAppNotificationUseCaseTest.kt` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O8GUlsT3H6Xk97TjTX2:-O8GoYQn9TI4o0PFxwz9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryInAppNotificationUseCaseTest.kt#L57)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This comment is kind of useless, so I think it should be either removed into `test { }` or removed.
</blockquote></details>

Done.
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O864_s2-4wUz_MfUw7o:-O8G3LOv3fklxo9cufHI:b7ja4z1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Since I'm a bit senile, remind me, why did we say Period instead of Duration?
</blockquote></details>

Period is used here 
```
fun Resources.getExpiryQuantityString(accountExpiry: Period): String {
    return if (accountExpiry.isNegative() || accountExpiry == Period.ZERO) {
        getString(R.string.out_of_time)
    } else if (accountExpiry.years > 0) {
        getRemainingText(this, R.plurals.years_left, accountExpiry.years)
    } else if (accountExpiry.months >= 3) {
        getRemainingText(this, R.plurals.months_left, accountExpiry.months)
    } else if (accountExpiry.months > 0 || accountExpiry.days >= 1) {
        getRemainingText(this, R.plurals.days_left, accountExpiry.days)
    } else {
        getString(R.string.less_than_a_day_left)
    }
}
```
because Duration doesn't have methods to convert to years or months
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O861TnH3Lw9ceyd3mZy:-O8G8FNd8qmBnPEtPZul:b-q0iioe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L68)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This is `floorDiv` I believe.
</blockquote></details>

Looks like floorDiv can return negative numbers, but we can do this instead: 
```
private fun calculateDelaysNeeded(millisUntilExpiry: Long, currentUpdateIntervalMillis: Long): Long =
    millisUntilExpiry.coerceAtLeast(0) / currentUpdateIntervalMillis
```

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad, @kl, and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O86-Uzm9tRLs30zx6l0:-O8HEP8WBImz6H8UWmPW:bkk71f6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/ResourcesExtensions.kt#L26)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

No but we can do this instead ```fun Period.isNegative() = toStandardDuration().millis < 0```
</blockquote></details>

:raised_hands: Very nice!
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O864_s2-4wUz_MfUw7o:-O8HEhOv4z5-H9BwB-Kv:bao0u35) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L14)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Period is used here 
```
fun Resources.getExpiryQuantityString(accountExpiry: Period): String {
    return if (accountExpiry.isNegative() || accountExpiry == Period.ZERO) {
        getString(R.string.out_of_time)
    } else if (accountExpiry.years > 0) {
        getRemainingText(this, R.plurals.years_left, accountExpiry.years)
    } else if (accountExpiry.months >= 3) {
        getRemainingText(this, R.plurals.months_left, accountExpiry.months)
    } else if (accountExpiry.months > 0 || accountExpiry.days >= 1) {
        getRemainingText(this, R.plurals.days_left, accountExpiry.days)
    } else {
        getString(R.string.less_than_a_day_left)
    }
}
```
because Duration doesn't have methods to convert to years or months
</blockquote></details>

Ah, yes. no `toStandardMonth()` or `toStandardYear()`. Kind of sucks, I guess we could add it ourselves as extension functions but it would be a bit less accurate. I'm fine with Period. @Pururun @albin-mullvad do you have any opinion about this? 
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O863yxqB5Pz2jdAJQuW:-O8HFYwZA7H3-bbvfBsb:b-rmjc2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L41)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I haven't fully thought this through, but it feels like it should work to make use of the `do {} while loop` https://kotlinlang.org/docs/control-flow.html#while-loops

```
    do {
        // emit()
        // newUpdate interval
        // calulate new delay
        // evaluate hasAnotherEmission
    } while(hasAnotherEmission)
    emit(Period.ZERO)
```

Then we should be able to remove these lines:
```
   // Always emit at start of flow.
    emit(Period(DateTime.now(), expiry))

    // Delay until the next update interval.
    delay(expiry.millisFromNow() % currentUpdateInterval)

    var delayCount = calculateDelaysNeeded(expiry.millisFromNow(), currentUpdateInterval)
```
whilst making the code more readable.
</blockquote></details>

Discussed offline. :clap: 
___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt` line 68 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-O861TnH3Lw9ceyd3mZy:-O8HFmo41Yn1ZZVyUjWw:b-j84sen) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d843c60872a09d0b67df564eae85c38b859bdef/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt#L68)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Looks like floorDiv can return negative numbers, but we can do this instead: 
```
private fun calculateDelaysNeeded(millisUntilExpiry: Long, currentUpdateIntervalMillis: Long): Long =
    millisUntilExpiry.coerceAtLeast(0) / currentUpdateIntervalMillis
```
</blockquote></details>

Looks good to me :+1:

**Review by Rawa — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-:-O8HL34K33ApYdaj1gcr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
Just remember to squash commits

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6851#-:-O8M0jWo3SsettEGuKP9:bvokujg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
