### PR TITLE
Refactor buttons to use UIButton.Configuration

### PR DESCRIPTION
**Pull request by mojganii**
This PR refactors the buttons to use UIButton.Configuration for their configuration.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)

### CODE REVIEW

**Review by rablador — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/Login/AccountInputGroupView.swift` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8_nWw_CO6YcHO9Pj_Y:-O8_nWw_CO6YcHO9Pj_Z:b-qbdce1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/973ed386057485298f06bb63d68edd2f699b1e29/ios/MullvadVPN/View%20controllers/Login/AccountInputGroupView.swift#L111)):*
> ```Swift
>         config.contentInsets = UIMetrics.textFieldMargins.toDirectionalInsets
>         config.baseForegroundColor = .AccountTextField.NormalState.textColor
>         button.configuration = config
> ```

Nit: I think we should either add all available configurations (including eg.`title`) or just the one that is deprecated. Title color isn't deprecated and can be left out if we want to.
___
*[`ios/MullvadVPN/Views/CustomButton.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8_qCCn9tEHDBP3xYIV:-O8_qCCn9tEHDBP3xYIW:b1wykki) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0e32a2114752c7fc55b71c9f065613ff777f7cd0/ios/MullvadVPN/Views/CustomButton.swift#L43)):*
> ```Swift
>             return UIColor.AppButton.normalTitleColor
>         case .disabled:
>             return UIColor.AppButton.disabledTitleColor.withAlphaComponent(0.5)
> ```

Is this ok to remove? This color has a value of 1.0 alpha and without the 0.5 it is the same color as `.highlightedTitleColor`.

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Login/AccountInputGroupView.swift` line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8_nWw_CO6YcHO9Pj_Y:-O8acvo47nZ--DyY7IrF:b-osvfpq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/973ed386057485298f06bb63d68edd2f699b1e29/ios/MullvadVPN/View%20controllers/Login/AccountInputGroupView.swift#L111)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: I think we should either add all available configurations (including eg.`title`) or just the one that is deprecated. Title color isn't deprecated and can be left out if we want to.
</blockquote></details>

Good catch! 
we have to put all together in configuration. 
___
*[`ios/MullvadVPN/Views/CustomButton.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8_qCCn9tEHDBP3xYIV:-O8ap-B49UcfRIeJxecV:b-99qt1p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0e32a2114752c7fc55b71c9f065613ff777f7cd0/ios/MullvadVPN/Views/CustomButton.swift#L43)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is this ok to remove? This color has a value of 1.0 alpha and without the 0.5 it is the same color as `.highlightedTitleColor`.
</blockquote></details>

it's correct both have the same value but we are using them separately in the code. so I suggest to not let them mix up when it's supposed to have different style for different states.

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by buggmagnet — CHANGES_REQUESTED** [review]
It looks like the reconnect button is gone 

> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-:-O8f-Hir-_trUAHZNYSM:b-2ftw8c)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/InAppPurchaseButton.swift` line 78 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8ex6Z_CkFQ5Y2sSJFa:-O8ex6Z_CkFQ5Y2sSJFb:b-p0fod1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06d2f5b68d2a6b4c725172e6297fc9422e5691c1/ios/MullvadVPN/Views/InAppPurchaseButton.swift#L78)):*
> ```Swift
>     }
> 
>     private func getActivityIndicatorRect(forContentRect contentRect: CGRect) -> CGRect {
> ```

nit
There's no need to add a `get` prefix here, the name of the function follows convention and Apple's guidelines

**Review by rablador — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @mojganii)

**Review by rablador — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Views/AppButton.swift` line 109 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8uhOlrBPq5tL8TZnjZ:-O8uhOlrBPq5tL8TZnj_:b-p8dr4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Views/AppButton.swift#L109)):*
> ```Swift
>         imageAlignment = .trailing
>         titleAlignment = .leading
>         isHighlighted = false
> ```

This attribute is `false` by default.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Extensions/CGSize+Helpers.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8uwor72uN7DAuPEhmE:-O8uwor72uN7DAuPEhmF:b-vv1whz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Extensions/CGSize%2BHelpers.swift#L13)):*
> ```Swift
> extension CGSize {
>     // Function to deduct insets from CGSize
>     func deducting(insets: NSDirectionalEdgeInsets) -> CGSize {
> ```

nit
It's deducting offsets from a `NSDirectionalEdgeInsets` 
___
*[`ios/MullvadVPN/Extensions/CGSize+Helpers.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8ux5mF6E5a3EOIc_UJ:-O8ux5mF6E5a3EOIc_UK:b-1ric0z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Extensions/CGSize%2BHelpers.swift#L14)):*
> ```Swift
>     // Function to deduct insets from CGSize
>     func deducting(insets: NSDirectionalEdgeInsets) -> CGSize {
>         let newWidth = self.width - (insets.leading + insets.trailing)
> ```

not need for self here and below
___
*[`ios/MullvadVPN/Extensions/UIImage+Helpers.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8uxE696rjAOZKzU-pW:-O8uxE696rjAOZKzU-pX:b-cfr67v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Extensions/UIImage%2BHelpers.swift#L14)):*
> ```Swift
>     // Function to resize image while keeping aspect ratio
>     func resizeImage(targetSize: CGSize) -> UIImage {
>         let widthRatio = targetSize.width / self.size.width
> ```

no need for self here and below

**Review by mojganii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Extensions/CGSize+Helpers.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8ux5mF6E5a3EOIc_UJ:-O8vmC1c3Pl0i6g3_s52:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Extensions/CGSize%2BHelpers.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

not need for self here and below
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Extensions/UIImage+Helpers.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8uxE696rjAOZKzU-pW:-O8vmqRS0OEGKJf5YS1q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Extensions/UIImage%2BHelpers.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

no need for self here and below
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Views/AppButton.swift` line 109 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8uhOlrBPq5tL8TZnjZ:-O8vn276ASpWXsGA7_7H:b-n50mn8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3674be3a5bfb9a6c3ae03d344ebd980571406320/ios/MullvadVPN/Views/AppButton.swift#L109)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This attribute is `false` by default.
</blockquote></details>

true. I've forgotten to remove that.
___
*[`ios/MullvadVPN/Views/InAppPurchaseButton.swift` line 78 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-O8ex6Z_CkFQ5Y2sSJFa:-O8q8YWb9fmL-tH3HJFF:b-gxztt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06d2f5b68d2a6b4c725172e6297fc9422e5691c1/ios/MullvadVPN/Views/InAppPurchaseButton.swift#L78)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
There's no need to add a `get` prefix here, the name of the function follows convention and Apple's guidelines
</blockquote></details>

Fair enough!

**Review by rablador — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928#-:-O9JPsvgBbXuJsFsW5r0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6928)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

**Pull request merged**
