### PR TITLE
Fix SplitTunnelingScreen and SplitTunnelingCell

### PR DESCRIPTION
**Pull request by Pururun**
- Use BaseCell as base for SplitTunnelingCell
- Make sizes and margins more in line with design
- Use new HeaderCell instead of BaseCell in SplitTunnelingScreen
- Use items with divider instead of padding in the cell

See image below for comparison:

Screenshot 2024-01-31 at 11 51 49

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742#-:-NpeQdwBCLloeN8VHZ8c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742#-NpsElBaDK82yufLl_hN:-NpsElBaDK82yufLl_hO:b24oi9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d8e0296c513b7b43e2a30107fda85183af7e452/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L9)):*
> ```Kotlin
>     val accountRowMinHeight: Dp = 48.dp,
>     val accountRowSpacing: Dp = 24.dp,
>     val addIconSize: Dp = 18.dp,
> ```

Looks very small, have we verified this with Material guide lines/Design team?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742#-NpsElBaDK82yufLl_hN:-Npsco5ZCPSuoUyK43Jp:b-6p4xq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d8e0296c513b7b43e2a30107fda85183af7e452/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L9)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Looks very small, have we verified this with Material guide lines/Design team?
</blockquote></details>

This was verified with the design team, but if you check the material 3 guide lines it seems that it should be 24dp:
https://m3.material.io/components/lists/specs

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742#-NpsElBaDK82yufLl_hN:-Npsf3hiAvCzmwopklTU:bkktkkl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d8e0296c513b7b43e2a30107fda85183af7e452/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L9)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This was verified with the design team, but if you check the material 3 guide lines it seems that it should be 24dp:
https://m3.material.io/components/lists/specs
</blockquote></details>

After discussion with design we are changing it to 24dp for now.

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm: good work! :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5742#-:-Npsfj3mBemeIam6Nh9U:b9ppmhf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
