### PR TITLE
Refactor type conversions for gRPC types in `mullvad-management-interface`

### PR DESCRIPTION
**Pull request by dlon**
Changes:

* Implement `TryFrom` from the gRPC type to `GeoIpLocation`
* Implement `TryFrom` from the gRPC type to `TunnelEndpoint`
* Implement `TryFrom` from the gRPC type to `TunnelState`
* Add `Providers::into_vec`
* Split `types` to mirror the organization in `{mullvad,talpid}-types`.
* Etc.

This makes it easier for clients to convert types back to the corresponding types in `mullvad_types` and `talpid_types`.

The PR also refactors the CLI to use these types.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-management-interface/src/types.rs` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014#-NE5HnTlE-5q0ivKV0pQ:-NE5HnTlE-5q0ivKV0pR:bonlh09) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21ac1cfc7a713db919e452656303ea435bd2f4e8/mullvad-management-interface/src/types.rs#L55)):*
> ```XML
>             country: geoip.country,
>             city: match geoip.city {
>                 city if city.is_empty() => None,
> ```

Maybe a nit-pick, but this match statement is replicated ad nauseum and could be easily be factored out.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)* status: 1 of 22 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-management-interface/src/types.rs` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014#-NE5HnTlE-5q0ivKV0pQ:-NEBEVkXB5JMDmYbWMWO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21ac1cfc7a713db919e452656303ea435bd2f4e8/mullvad-management-interface/src/types.rs#L55)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Maybe a nit-pick, but this match statement is replicated ad nauseum and could be easily be factored out.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)* status: 1 of 22 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`mullvad-management-interface/src/types/conversions/mod.rs` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014#-NEBQDn5CumJqQFaGRpg:-NEBQDn672xAJsvSgxck:b-bcmhmf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ac095dc8db5e72c0acdb9fbe6351a8c7a7d1622/mullvad-management-interface/src/types/conversions/mod.rs#L26)):*
> ```XML
>     }
>     let mut public_key = [0; 32];
>     public_key.copy_from_slice(&bytes[..32]);
> ```

I see at least two places in this new code where we construct wg keys (private + public) by checking the length and then converting to array. Things like this can maybe be lifted out to helper functions to reduce duplication?

Secondly. I think a cleaner way than 1) check len 2) create array 3) copy to array, would be to directly make use of `<[u8; 32]>::try_from(..).map_err(..)` to convert and error handle in one (pretty readable) statement. We did this here: https://github.com/mullvad/mullvadvpn-app/blob/512eb4d1949b1979d6a8a95e44f506de3a7b654b/talpid-tunnel-config-client/src/lib.rs#L81-L85.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 12 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)* status: 13 of 22 files reviewed, 1 unresolved discussion (waiting on @dlon)

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)* status: 12 of 22 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[`mullvad-management-interface/src/types/conversions/mod.rs` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014#-NEBQDn5CumJqQFaGRpg:-NELlosaB5bXtmoFu1bO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ac095dc8db5e72c0acdb9fbe6351a8c7a7d1622/mullvad-management-interface/src/types/conversions/mod.rs#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I see at least two places in this new code where we construct wg keys (private + public) by checking the length and then converting to array. Things like this can maybe be lifted out to helper functions to reduce duplication?

Secondly. I think a cleaner way than 1) check len 2) create array 3) copy to array, would be to directly make use of `<[u8; 32]>::try_from(..).map_err(..)` to convert and error handle in one (pretty readable) statement. We did this here: https://github.com/mullvad/mullvadvpn-app/blob/512eb4d1949b1979d6a8a95e44f506de3a7b654b/talpid-tunnel-config-client/src/lib.rs#L81-L85. 
</blockquote></details>

Done.

**Review by pinkisemils — APPROVED** [review]
> Reviewed 8 of 21 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4014)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
