### PR TITLE
Windows installer

### PR DESCRIPTION
**Pull request by mvd-ows**
This should give us one branch less to keep track of.

The reference to WINDNS is disabled until that component is available on master.

When building make sure you update the Electron-builder config to again reference WINDNS. Also merge `windows-dns` and `windns-integration` into your working tree.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[.cargo/config, line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtnJ5rDGuealbQCNq4:-LBtnJ5rDGuealbQCNq5:b-laekvj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/.cargo/config#L2)):*
> ```
> [target.x86_64-pc-windows-msvc]
> rustflags = ["-Ctarget-feature=+crt-static"]
> ```

I thought we merged this back when we got the wfpctl module merged. But I guess not.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pinkisemils** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LBtvxfe7Xht-foEtGir:b-ymyg5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
> ```JavaScript
>     }
>   
>     const backendIsRunning = appDelegate._rpcAddressFileExists();
> ```

Maybe we should leave a comment here that this code is only relevant for MacOS now?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LBuEIodB8COYDFB8bin:b-u37ia9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Maybe we should leave a comment here that this code is only relevant for MacOS now?
</blockquote></details>

We have an if-guarding calling `_startBackend` in the callsite. Maybe we should try to be consistent so we don't have some platform specific things where it's called and some as early returns?

And yes, soon all of this will be gone as we can probably run as a service on macOS fairly soon as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.cargo/config, line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtnJ5rDGuealbQCNq4:-LD0DyqRE61lgb3cwrfJ:bn4tdtz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/.cargo/config#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I thought we merged this back when we got the wfpctl module merged. But I guess not.
</blockquote></details>

Hmm that would have made sense yes, but I think this didn't come up before I started looking at the installer. I could of course have made the same change on the WFPCTL branch but I guess I just forgot about it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LD0EXQ-6o51y4UlVIaj:b-wghpuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We have an if-guarding calling `_startBackend` in the callsite. Maybe we should try to be consistent so we don't have some platform specific things where it's called and some as early returns?

And yes, soon all of this will be gone as we can probably run as a service on macOS fairly soon as well.
</blockquote></details>

What's the status of this? Do i need to change/comment it? Will a rebase of the code be enough?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LD0cdlpCo-IomeYwGk1:b974qwo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What's the status of this? Do i need to change/comment it? Will a rebase of the code be enough?
</blockquote></details>

All of the `_startBackend` code has been jettisoned since we are now running the daemon as a system service on all platforms.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LDbSgSm2oMP2NUyblvE:b-lcz44v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

All of the `_startBackend` code has been jettisoned since we are now running the daemon as a system service on all platforms.
</blockquote></details>

_startBackend seems to be gone after a rebase.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pronebird** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LDcEwOWCY3Gkz0BkLpb:byv73u8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

_startBackend seems to be gone after a rebase.
</blockquote></details>

I am not sure what's going on here, but if we have something for macOS here we should have a separate `case 'darwin'` to match against the platform and return the appropriate value.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pronebird** [comment]
I tested this work today and it worked flawlessly.

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-:-LDcFEL-7kMepXLEwRKd:b1p99u1)*

**Comment by pronebird** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LDcJFL--OwzVYVcKQo4:bfcq8zg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I am not sure what's going on here, but if we have something for macOS here we should have a separate `case 'darwin'` to match against the platform and return the appropriate value.
</blockquote></details>

Ah I get it now, Windows is an exception here, other platforms still use `/tmp`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
*[app/main.js, line 180 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LBtvxfd2URuoDyNhP3L:-LDedNRp-vMcynFDAohL:b-5sptgj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ddb15932dac2b5bd8c37b9170d8cfbf1c5af2f25/app/main.js#L180)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Ah I get it now, Windows is an exception here, other platforms still use `/tmp`.
</blockquote></details>

I've rebased this branch many times since it was first created. At this point `app/main.js` should be the same as on master, which it is, I just verified. So any changes from what it used to look like are not mine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pronebird** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Would it be possible to move `dist-assets/installer.nsh` into `dist-assets/windows/installer.nsh` or similar? The other platform specific packaging files are in separate subdirectories and just `installer.nsh` does not convey it's Windows related..

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-:-LDumkTE3JFilX4Js_1z:bp9ufxu)*

**Comment by pronebird** [comment]
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LDvqaP16_xvoGKU8WyD:bi24ttg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
> ```YAML
>       
> win:
>   "target": [
> ```

Is that right syntax for YML files? Looks like JSON to me...

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LDvtKsH1X-rSoHS1hmx:b-atl1xq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Is that right syntax for YML files? Looks like JSON to me...
</blockquote></details>

Yeah, these are the only quoted keys.. And the only part using `[]` for a list instead of rows just starting with `-`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
@faern Good idea, but I don't think that change will be supported. I haven't told Electron-Builder to look for the file in this location, I believe the relative path is hardcoded.

---







*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-:-LE9hfro1K6SYkD4ud-8:b-j3p59b)*

**Comment by mvd-ows** [comment]
*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9hTOu7ormSKZgEHss:b-id0t5z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yeah, these are the only quoted keys.. And the only part using `[]` for a list instead of rows just starting with `-`.
</blockquote></details>

It's not clear whether you want this changed in some way? I copied it from the manual, then removed the entry for x32 when we decided it won't be needed at the onset.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9iV3U0SZVyeSaz5Vt:b-a4d01j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

It's not clear whether you want this changed in some way? I copied it from the manual, then removed the entry for x32 when we decided it won't be needed at the onset.
</blockquote></details>

You copied JSON but we use YML config. So it has to be converted to proper YML I think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pronebird** [comment]
@mvd-ows the nsis configuration from electron-builder.yml seems to contain that path:

```
include: dist-assets/installer.nsh
```

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-:-LE9ikLj9i_WiW2cEz77:b6z0pjq)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9rEuhDv7zXrE-85Dt:b-5ndf31) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Something like this:

```
win:
  target:
  - target: nsis
    arch:
    - x64
```
</blockquote></details>

The layout in general is strang. There is a target entry under the target entry etc. But if I directly convert your JSON into YML I get:
```yml
win:
  target:
    - target:
      - target: nsis
      arch:
        - x64
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Yeah, should likely be possible to change the default path that electron-builder looks in.

This fails on formatting on Travis. But that is likely just because this is based off of a very old master. After rebasing it will likely just work.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-:-LE9s_ei8Pe4O8Ag8nP7:bl5x0fu)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9tQxg-hUgOxj5BCg-:b-6666p4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The layout in general is strang. There is a target entry under the target entry etc. But if I directly convert your JSON into YML I get:
```yml
win:
  target:
    - target:
      - target: nsis
      arch:
        - x64
```
</blockquote></details>

Linus you seem to have an extra `target`.

See: https://www.electron.build/configuration/target#targetconfiguration

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9vu5XArsJBnnur95P:b4sd8sf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

Linus you seem to have an extra `target`.

See: https://www.electron.build/configuration/target#targetconfiguration
</blockquote></details>

Exactly. I have the same amount as Odd's JSON has. And also the same amount as the link you posted. Two levels of targets :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9wCYf1a1p6mtwO46Z:b-n3j0px) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Exactly. I have the same amount as Odd's JSON has. And also the same amount as the link you posted. Two levels of targets :)
</blockquote></details>

Whaaaat. I have three? I'm sure some reviewable root inserted that. I probably read my config a billion times before posting it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by pronebird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9wFie8_Gg3U1ETcuq:b722iyu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Whaaaat. I have three? I'm sure some reviewable root inserted that. I probably read my config a billion times before posting it.
</blockquote></details>

I see three `target` in your YAML that you posted here. Anyway, it should be two...

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by faern** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9wQMy00CcpMdjnCT0:bvmt3hk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I see three `target` in your YAML that you posted here. Anyway, it should be two...
</blockquote></details>

Anyway, yours has a problem that the list is not indented. So new try:
```yml
win:
  target:
    - target: nsis
      arch:
        - x64
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
*[electron-builder.yml, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-LDvqaP16_xvoGKU8WyC:-LE9x24S0MWf7xZwa_OA:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/671be2af40e39e52e228617a5d01088b43e01ff0/electron-builder.yml#L60)):*
<details><summary><i>Previously, pronebird (Andrei Mihailov) wrote…</i></summary><blockquote>

I did mine with https://www.json2yaml.com to be fair.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158)*

**Comment by mvd-ows** [comment]
Right, there was actually a configurable reference to `installer.nsh`. I've moved the file and updated the reference.

---







*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/158#-:-LE9x79_AefgX1fmHjUu:b-2wqeo5)*

**Pull request merged**
