### PR TITLE
Show popup when enabling custom dns server

### PR DESCRIPTION
**Pull request by Rawa**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5332)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5332#-:-NhaIBOjCDzojP_90L86:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by chremb — COMMENTED** [review]
t

**Review by chremb — COMMENTED** [review]
t

**Review by chremb — COMMENTED** [review]
nicenesd thx

**Review by chremb — COMMENTED** [review]
y

**Review by chremb — COMMENTED** [review]
g

**Pull request merged**
