### PR TITLE
Migrate out of time view to compose

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175)

### CODE REVIEW

**Review by Rawa — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nerl2k51ESdgutOMjJK:-Nerl2k51ESdgutOMjJL:b91wwzx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt#L46)):*
> ```Kotlin
>         isEnabled = isEnabled,
>     ) {
>         Box(modifier = Modifier.fillMaxSize()) {
> ```

If we use box layout here we need to account for the Image afterwards, I believe if there is a slim screen or a long button text it will overlap with the image. Since we know the size of the image I guess we could compensate for it in a way like this, another alternative would possibly be to use a constraintlayout:
```
    ActionButton(
        onClick = onClick,
        colors = colors,
        modifier = modifier,
        isEnabled = isEnabled,
    ) {
        Text(
            text = text,
            textAlign = TextAlign.Center,
            style = MaterialTheme.typography.bodyMedium,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
            modifier = Modifier.padding(start = 24.dp).weight(1f)
        )
        Image(
            painter = painterResource(id = R.drawable.icon_extlink),
            contentDescription = null,
            modifier =
                Modifier.padding(horizontal = Dimens.smallPadding)
                    .alpha(if (isEnabled) AlphaVisible else AlphaDisabled)
        )
    }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt` line 103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nero0QF2UW015HIacAJ:-Nero0QF2UW015HIacAK:bwtouqj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt#L103)):*
> ```Kotlin
>             when (viewAction) {
>                 is OutOfTimeViewModel.ViewAction.OpenAccountView ->
>                     context.openAccountPageInBrowser(viewAction.token)
> ```

Is it possible to avoid using `context` and instead use something more Compose native? Saw this one:
https://stackoverflow.com/a/69103918/1724097
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nerox2O3_sT-3Yme3dm:-Nerox2O3_sT-3Yme3dn:bh0urwy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt#L32)):*
> ```Kotlin
>                     val state = vm.uiState.collectAsState().value
>                     OutOfTimeScreen(
>                         showSitePayment = BuildTypes.RELEASE != BuildConfig.BUILD_TYPE,
> ```

We should adapt this to the IS_PLAY flag @albin-mullvad is looking to add.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-NerpW3LCAr4q-uycPxv:-NerpW3MAZZLCWr5lo9-:b-l3z3e7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L59)):*
> ```Kotlin
>             accountRepository.accountExpiryState.collectLatest { accountExpiry ->
>                 accountExpiry.date()?.let { expiry ->
>                     val tomorrow = DateTime.now().plusHours(20)
> ```

Any reason why we add 20h to the expiry? Can we avoid it? Shouldn't `expiry.isAfter(DateTime.now())` be enough?

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nerl2k51ESdgutOMjJK:-Nes3C345cyi5wDRIxWA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt#L46)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If we use box layout here we need to account for the Image afterwards, I believe if there is a slim screen or a long button text it will overlap with the image. Since we know the size of the image I guess we could compensate for it in a way like this, another alternative would possibly be to use a constraintlayout:
```
    ActionButton(
        onClick = onClick,
        colors = colors,
        modifier = modifier,
        isEnabled = isEnabled,
    ) {
        Text(
            text = text,
            textAlign = TextAlign.Center,
            style = MaterialTheme.typography.bodyMedium,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
            modifier = Modifier.padding(start = 24.dp).weight(1f)
        )
        Image(
            painter = painterResource(id = R.drawable.icon_extlink),
            contentDescription = null,
            modifier =
                Modifier.padding(horizontal = Dimens.smallPadding)
                    .alpha(if (isEnabled) AlphaVisible else AlphaDisabled)
        )
    }
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt` line 103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nero0QF2UW015HIacAJ:-NerzyGM9JMYBhI244Sm:bums38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt#L103)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is it possible to avoid using `context` and instead use something more Compose native? Saw this one:
https://stackoverflow.com/a/69103918/1724097
</blockquote></details>

I tried to use that, but since we we need to get the string from resources at least for me I needed to add some more code that made it kinda not as elegant.

Sort of like this:
```
val uriHandler \= LocalUriHandler.current  
val accountPath \= stringResource(id = R.string.account\_url) + "?token=%s"  
LaunchedEffect(key1 = Unit) {  
viewActions.collect { viewAction \->  
when (viewAction) {  
is OutOfTimeViewModel.ViewAction.OpenAccountView \->  
uriHandler.openUri(String.format(viewAction.token, accountPath))  
OutOfTimeViewModel.ViewAction.OpenConnectScreen \-> openConnectScreen()  
}  
}  
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nerox2O3_sT-3Yme3dm:-Nes-XGj3jItDy0x2VFf:bd9o6qi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt#L32)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should adapt this to the IS_PLAY flag @albin-mullvad is looking to add.
</blockquote></details>

Yes, hopefully he will merge that soon. :)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-NerpW3LCAr4q-uycPxv:-Nes-_e38jQW6-erYG3c:bktv98) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L59)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Any reason why we add 20h to the expiry? Can we avoid it? Shouldn't `expiry.isAfter(DateTime.now())` be enough?
</blockquote></details>

The reason we have that is because if the user time is not set correctly, I guess if they are travelling or something, this function can fail pretty badly. It was set to 24 hours before but that was causing issues with one-day vouchers so I changed it to 20 instead.

The long term plan is to do something similar to what we have on desktop, where it needs to changed from the default value, but I would probably do that in another PR.

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nerox2O3_sT-3Yme3dm:-NestQEOES78x_wxiKxX:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt#L32)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes, hopefully he will merge that soon. :)
</blockquote></details>

Done

**Review by Rawa — CHANGES_REQUESTED** [review]
Great work! :+1: 

> Reviewed 5 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-:-NevdwDGDm1Cf20PrALX:bmqixtq)* status: 3 of 18 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt` line 103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nero0QF2UW015HIacAJ:-Neva0gDCo1Pk7UsXxU5:b-yktwzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt#L103)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I tried to use that, but since we we need to get the string from resources at least for me I needed to add some more code that made it kinda not as elegant.

Sort of like this:
```
val uriHandler \= LocalUriHandler.current  
val accountPath \= stringResource(id = R.string.account\_url) + "?token=%s"  
LaunchedEffect(key1 = Unit) {  
viewActions.collect { viewAction \->  
when (viewAction) {  
is OutOfTimeViewModel.ViewAction.OpenAccountView \->  
uriHandler.openUri(String.format(viewAction.token, accountPath))  
OutOfTimeViewModel.ViewAction.OpenConnectScreen \-> openConnectScreen()  
}  
}  
}
```
</blockquote></details>

Yeah I see what you mean, maybe we break some of it out as a lambda? I Believe this should work:

```
@Composable
fun createLaunchUrlHook(uri: String): () -> Unit {
    val uriHandler = LocalUriHandler.current
    return { uriHandler.openUri(uri) }
}

@Composable
private fun MyScreenWithLaunch(uri: String) {
    val launchUrlHook = createLaunchUrlHook(uri = uri)
    LaunchedEffect(Unit) {
        launchUrlHook()
    }
}
```

It is not the nicest but it would get rid of the context.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-NerpW3LCAr4q-uycPxv:-NevcsL8EHtH0adSMyfJ:b-ppmav4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L59)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

The reason we have that is because if the user time is not set correctly, I guess if they are travelling or something, this function can fail pretty badly. It was set to 24 hours before but that was causing issues with one-day vouchers so I changed it to 20 instead.

The long term plan is to do something similar to what we have on desktop, where it needs to changed from the default value, but I would probably do that in another PR.
</blockquote></details>

I see, yeah sounds like another PR.

**Review by sabercodic — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

**Review by albin-mullvad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-Nerox2O3_sT-3Yme3dm:-New6s_dDbDzKVGcRgrx:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f18a438f7239bdbf2ee87e537a52d2be36349c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt#L32)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

:thumbsup:

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5175#-:-NfFK_Fb3IDmdPCPYoM5:bnfp4nl)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @sabercodic)

**Pull request merged**
