### PR TITLE
Drop ios 12 support

### PR DESCRIPTION
**Pull request by sajacl**
Changed minimum support to iOS 13,
Removed all checks for iOS 13,
Removed all extra functions for supporting iOS 12.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 22 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: 22 of 30 files reviewed, 1 unresolved discussion (waiting on @sajacl)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCtgE7n3ftZXIvB-3Wg:-NCtgE7n3ftZXIvB-3Wh:b-bkeh8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a559433814a8fd9a0493ffb1e91759ef815b5a/ios/MullvadVPN/AppDelegate.swift#L52)):*
> ```Swift
>         } else {
>             application.setMinimumBackgroundFetchInterval(
>                 ApplicationConfiguration.minimumBackgroundFetchInterval
> ```

You can remove `minimumBackgroundFetchInterval` from `ApplicationConfiguration` too since we don't need it any longer.

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: 23 of 30 files reviewed, 1 unresolved discussion (waiting on @sajacl)

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 3 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: 26 of 30 files reviewed, 4 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SpinnerActivityIndicatorView.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCthPyAAAmqejpvDP2y:-NCthPyB2IMnyGf6VNLw:bim373j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f815f31568bde66dfbaa6d3fa6f963900cfffb6/ios/MullvadVPN/SpinnerActivityIndicatorView.swift#L107)):*
> ```Swift
> 
>     private func registerSceneActivationObserver() {
>         let name: NSNotification.Name = UIScene.willEnterForegroundNotification
> ```

Remove variables and use them direction in `addObserver()` call below.
___
*[`ios/MullvadVPN/UIFont+Monospaced.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCthw8X3nrJqP7mMKA4:-NCthw8X3nrJqP7mMKA5:b-lulpbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f815f31568bde66dfbaa6d3fa6f963900cfffb6/ios/MullvadVPN/UIFont%2BMonospaced.swift#L14)):*
> ```Swift
>     class func backport_monospacedSystemFont(ofSize size: CGFloat, weight: UIFont.Weight) -> UIFont
>     {
>         UIFont.monospacedSystemFont(ofSize: size, weight: weight)
> ```

Please use explicit `return` when possible.
___
*[`ios/MullvadVPN/UIImage+TintColor.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCti79C5qBdNT0mXGEW:-NCti79C5qBdNT0mXGEX:b-t98uo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f815f31568bde66dfbaa6d3fa6f963900cfffb6/ios/MullvadVPN/UIImage%2BTintColor.swift#L11)):*
> ```Swift
> import UIKit
> 
> extension UIImage {
> ```

Delete this file and use `withTintColor()` directly where it's used since both `backport_` calls call into `withTintColor()` which is available since iOS 13.

**Comment by sajacl** [comment]
> > Reviewed 22 of 30 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)_ status: 22 of 30 files reviewed, 1 unresolved discussion (waiting on @sajacl)
> 
> _[`ios/MullvadVPN/AppDelegate.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCtgE7n3ftZXIvB-3Wg:-NCtgE7n3ftZXIvB-3Wh:b-bkeh8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a559433814a8fd9a0493ffb1e91759ef815b5a/ios/MullvadVPN/AppDelegate.swift#L52)):_
> 
> > ```swift
> >         } else {
> >             application.setMinimumBackgroundFetchInterval(
> >                 ApplicationConfiguration.minimumBackgroundFetchInterval
> > ```
> 
> You can remove `minimumBackgroundFetchInterval` from `ApplicationConfiguration` too since we don't need it any longer.

Has been removed already.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 4 of 30 files at r1, 1 of 6 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: 21 of 32 files reviewed, 4 unresolved discussions (waiting on @pronebird and @sajacl)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCtgE7n3ftZXIvB-3Wg:-NCtmSPI8MsJPgFfcECj:b-ucwqys) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a559433814a8fd9a0493ffb1e91759ef815b5a/ios/MullvadVPN/AppDelegate.swift#L52)):*
<details><summary><i>Previously, sajacl (Sajad Vishkai) wrote…</i></summary><blockquote>

Has been removed already.
</blockquote></details>

I don't see `minimumBackgroundFetchInterval` being removed from `ApplicationConfiguration.swift`. Did you forget to push changes?
___
*[`ios/MullvadVPN/UIFont+Monospaced.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCthw8X3nrJqP7mMKA4:-NCtm-G-8tdAWzOktVfh:bz8ds0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f815f31568bde66dfbaa6d3fa6f963900cfffb6/ios/MullvadVPN/UIFont%2BMonospaced.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please use explicit `return` when possible.
</blockquote></details>

Actually I realized, maybe we should use `UIFont.monospacedSystemFont()` directly where needed and remove this extension.
___
*[`ios/MullvadVPN/REST/HTTP.swift` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962#-NCtm7HtDKJ1iZF_TD9H:-NCtm7HtDKJ1iZF_TD9I:b9p7v4a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3f815f31568bde66dfbaa6d3fa6f963900cfffb6/ios/MullvadVPN/REST/HTTP.swift#L54)):*
> ```Swift
> extension HTTPURLResponse {
>     func value(forCaseInsensitiveHTTPHeaderField headerField: String) -> String? {
>         value(forHTTPHeaderField: headerField)
> ```

Remove this extension and use `value(forHTTPHeaderField:..)` directly where needed.

**Review by pronebird — COMMENTED** [review]
> Reviewed 3 of 6 files at r2, 3 of 6 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: 30 of 32 files reviewed, 2 unresolved discussions (waiting on @pronebird and @sajacl)

**Review by pronebird — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3962)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
