### PR TITLE
Improve app versioning (nicer parsing, less file modifications and bash)

### PR DESCRIPTION
**Pull request by faern**
* Make all rust crates fetch the product version from `mullvad_version::VERSION` instead of relying on `build.sh` to inject it into their `Cargo.toml`
* Make the electron frontend fetch the product version with `mullvad-version` instead of relying on `build.sh` injecting it
* Make the Android app fetch the product version with `mullvad-version` instead of relying on `build-apk.sh` injecting it
* Make `build-windows-modules.sh` update `version.h` by itself instead of relying on `build.sh` injecting it. This is still something we can improve. I would love to get rid of the version parsing in this script also!
* Set all rust, node, C++ project versions to just `0.0.0` (because they will fetch the correct version during build)
* Update `prepare-release.sh` to only inject versions into `dist-assets/(android|desktop)-product-version.txt` (the new single source of truth for the product version)

We now store the version of the product in a single place, one for desktop and one for android. All subprojects pick that version up and append relevant development suffixes (git hash etc) as needed. All version parsing and computation is isolated to just `mullvad-version` (except a little bit in `build-windows-modules.sh`. I hope we can fix that later, but let's not scope creep this even more)

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)

### CODE REVIEW

**Review by dlon — CHANGES_REQUESTED** [review]
> Reviewed 36 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 36 of 37 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-daemon/src/version_check.rs` line 304 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDSqLOK4ZYqpWZ395vz:-NDSqLOK4ZYqpWZ395w-:beptnud) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a83ad1f6a7965b40e290b0a7698ab8eecae110f/mullvad-daemon/src/version_check.rs#L304)):*
> ```XML
>         show_beta: bool,
>     ) -> Option<String> {
>         if !*IS_DEV_BUILD {
> ```

This function is not used by dev builds, but it's causing the CI to fail. Previously, the CI did not add a dev suffix to the version string, so `None` was not returned here. I think we should just remove the condition.

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 36 of 37 files reviewed, all discussions resolved

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 32 of 37 files at r1, 1 of 1 files at r2, 1 of 5 files at r3, 8 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 38 of 41 files reviewed, all discussions resolved (waiting on @dlon and @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 3 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
`prepare-release.sh` should probably not commit toml files anymore.

> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-:-NDWy1Hn0KCHuwk7w6N_:b-ktito3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`talpid-openvpn-plugin/build.rs` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDWyjRy8sYQamEt0fq5:-NDWyjRy8sYQamEt0fq6:bl6p514) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67a8cf7cd4a3173b72822e71fb24eeb03a069148/talpid-openvpn-plugin/build.rs#L14)):*
> ```XML
>     {
>         let mut res = winres::WindowsResource::new();
>         res.set("ProductVersion", mullvad_version);
> ```

Missing a thing. Should this crate even share the Mullvad version?

**Review by dlon — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 35 of 49 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @pinkisemils)

___
*[`gui/tasks/distribution.js` line 432 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDhgOPX0lJajtB_klA9:-NDhgOPX0lJajtB_klAA:b-t8mwkx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/398da22b60d491a10591b9ba7dc9cd59d8e9bb47/gui/tasks/distribution.js#L432)):*
> ```JavaScript
> function productVersion(args) {
>   const command = `cargo run -q --bin mullvad-version ${args ?? ''}`;
>   return execSync(command, { encoding: 'utf-8' }).trim();
> ```

There's another function which might be useful here: `execFileSync`. The name is a bit misleading but I think it does pretty much the same thing but lets you provide arguments as an array. Could be used like this:
```
execFileSync('cargo', ['run', '-q', '--bin', 'mullvad-version', ...args]).trim();
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 3 files at r8, 1 of 6 files at r9, 6 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 43 of 49 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @pinkisemils)

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 43 of 54 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[`talpid-openvpn-plugin/build.rs` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDWyjRy8sYQamEt0fq5:-NDi3g5vAdvSE3toJj7w:bee961l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67a8cf7cd4a3173b72822e71fb24eeb03a069148/talpid-openvpn-plugin/build.rs#L14)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Missing a thing. Should this crate even share the Mullvad version?
</blockquote></details>

It's a DLL that is part of our product. But yeah I dunno. I'd love to get rid of version management from `version.h` which will affect `winfw.dll`. So if we do one maybe we can do both? The difference is that it does not really cost us much complexity to version `talpid-openvpn-plugin.dll`, it costs us more hacks to version `winfw.dll`.

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 3 files at r8, 2 of 9 files at r10, 7 of 8 files at r11, 1 of 2 files at r12, 2 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[`build-windows-modules.sh` line 36 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlWwJF-cTQnJ1lYOBf:-NDlWwJF-cTQnJ1lYOBg:blkatya) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/build-windows-modules.sh#L36)):*
> ```Shell
> 
>     cp dist-assets/windows/version.h dist-assets/windows/version.h.bak
>     cat <<EOF > dist-assets/windows/version.h
> ```

Maybe we should move this stuff to the projects' `PreBuildEvent`s. Then we could add `version.h` to `.gitignore`.
___
*[`build-windows-modules.sh` line 116 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlVV-NBCWZm0J2Ly9C:-NDlVV-NBCWZm0J2Ly9D:be374ca) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/build-windows-modules.sh#L116)):*
> ```Shell
> 
> function main {
>     inject_version
> ```

Could `trap` be run after `inject_version` instead?
___
*[`mullvad-version/build.rs` line 18 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlXbSP1GflAWjhZeUG:-NDlXbSP1GflAWjhZeUH:bua6gta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/mullvad-version/build.rs#L18)):*
> ```XML
> impl Target {
>     pub fn current_target() -> Self {
>         println!("cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS");
> ```

Nit, but isn't it weird for `current_target` to have a side effect like this?

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, 1 of 2 files at r6, 1 of 2 files at r7, 3 of 3 files at r8, 1 of 6 files at r9, 5 of 9 files at r10, 6 of 8 files at r11, 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[`dist-assets/windows/version.h` line 4 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDm6CrX5HdhC3vGJAaa:-NDm6CrX5HdhC3vGJAab:b-8jcjkh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/dist-assets/windows/version.h#L4)):*
> ```objc
> #define MINOR_VERSION 0
> #define PATCH_VERSION 0
> #define PRODUCT_VERSION "0.0.0"
> ```

With `gcc`, it's possible to just pass arguments to the compiler to define these constants, could we not do something similar with msvc?
___
*[`mullvad-version/build.rs` line 18 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlXbSP1GflAWjhZeUG:-NDm6kIaChvL7g78mHuL:b6ogqns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/mullvad-version/build.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why is it weird? If we did not have this statement and you run `build.sh` and `build-apk.sh` after each other one of them would get the wrong `mullvad_version::VERSION`, right?
</blockquote></details>

We're arguing for moving the `println`es out into a function like `set_cargo_env_vars(&self)`.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[`build-windows-modules.sh` line 116 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlVV-NBCWZm0J2Ly9C:-NDm6pBlB3p-EeKF76d4:b-atey9x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/build-windows-modules.sh#L116)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What's the benefit? We have been running it before modifying any file everywhere else (the places that are now removed). To make sure there is no point in the code where a script exit could leave the files modified on disk.
</blockquote></details>

With the change above about removing `version.h` this becomes a non-issue.

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[`build-windows-modules.sh` line 36 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlWwJF-cTQnJ1lYOBf:-NDmGJwQEZe_Nq45AD8K:bptwk8s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/build-windows-modules.sh#L36)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Adding it to gitignore and removing it from the repo is a good idea either way! Because why "version" a file that is just zeroes!
</blockquote></details>

Without `version.h`, the projects cannot be built directly in Visual Studio, which is sometimes useful.
___
*[`dist-assets/windows/version.h` line 4 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDm6CrX5HdhC3vGJAaa:-NDmGuON9n2M9wV4S2Zn:bh42hy2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/dist-assets/windows/version.h#L4)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

With `gcc`, it's possible to just pass arguments to the compiler to define these constants, could we not do something similar with msvc?
</blockquote></details>

We could pass them in as env vars, but as far as I know, we'd need to output a header file to include in the resource files regardless.
___
*[`mullvad-version/build.rs` line 18 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlXbSP1GflAWjhZeUG:-NDmE4onExOsOY6gdu-G:bsbcxc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/mullvad-version/build.rs#L18)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We're arguing for moving the `println`es out into a function like `set_cargo_env_vars(&self)`. 
</blockquote></details>

What @pinkisemils said is what I meant. I should have been clearer. :stuck_out_tongue:

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`mullvad-version/build.rs` line 18 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlXbSP1GflAWjhZeUG:-NDmKa5_4avLX6tRe4q3:b-opx0nz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/mullvad-version/build.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I get what you mean! But it also sounds strange to separate them so far apart. The only time we need to print it is after calling `current_target`. If this build script is somehow invoked without ever inspecting the variable, then it also does not need to be reran when it changes.
</blockquote></details>

I could argue that we could have a `fn env_var_and_mark_important(var: &str) -> Option<String>` that fetches the value and prints this to cargo.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 50 of 55 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`gui/tasks/distribution.js` line 432 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDhgOPX0lJajtB_klA9:-NDmP-6C8BrPlxVgbfpA:b-107ffy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/398da22b60d491a10591b9ba7dc9cd59d8e9bb47/gui/tasks/distribution.js#L432)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

There's another function which might be useful here: `execFileSync`. The name is a bit misleading but I think it does pretty much the same thing but lets you provide arguments as an array. Could be used like this:
```
execFileSync('cargo', ['run', '-q', '--bin', 'mullvad-version', ...args]).trim();
```
</blockquote></details>

Nice. Fixed. Well, the callsites actually became a bit uglier IMO, but you judge that better.

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 50 of 55 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[`android/app/build.gradle.kts` line 32 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlgODk5TikbwukoxHV:-NDlgODl1yXHVahXvMit:bmhm2z7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/android/app/build.gradle.kts#L32)):*
> ```Kotlin
>         targetSdkVersion(Versions.Android.targetSdkVersion)
>         versionCode = generateVersionCode()
>         versionName = generateVersionName()
> ```

Perhaps it would be nice to add some override or fallback for the version code/name?



_Code quote:_
```Kotlin
        versionCode = generateVersionCode()
        versionName = generateVersionName()
```

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 50 of 55 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @dlon, and @pinkisemils)

___
*[`android/app/build.gradle.kts` line 32 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlgODk5TikbwukoxHV:-NDmTImsCbN8x1SZuMig:b-9ny55o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/android/app/build.gradle.kts#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps it would be nice to add some override or fallback for the version code/name?
</blockquote></details>

As discussed AFK: Yes, let's do this. So our build pipeline(s) don't need to have Rust etc.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 50 of 55 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @dlon, and @pinkisemils)

___
*[`talpid-openvpn-plugin/build.rs` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDWyjRy8sYQamEt0fq5:-NDmVnJz620mTsGZH7rL:b-ddh5st) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67a8cf7cd4a3173b72822e71fb24eeb03a069148/talpid-openvpn-plugin/build.rs#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's a DLL that is part of our product. But yeah I dunno. I'd love to get rid of version management from `version.h` which will affect `winfw.dll`. So if we do one maybe we can do both? The difference is that it does not really cost us much complexity to version `talpid-openvpn-plugin.dll`, it costs us more hacks to version `winfw.dll`.
</blockquote></details>

IMO, if we put effort into making `winfw.dll` have a nice looking version, it does not hurt to also have `talpid-openvpn-plugin.dll` have that. My opinion is that we can keep this.

**Review by dlon — COMMENTED** [review]
> Reviewed 2 of 5 files at r15, 1 of 1 files at r16, 2 of 6 files at r17, 2 of 6 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 55 of 59 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`mullvad-version/build.rs` line 18 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlXbSP1GflAWjhZeUG:-NDm_l3PBb1I-1HnkN9I:b-qs98i0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/mullvad-version/build.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I could argue that we could have a `fn env_var_and_mark_important(var: &str) -> Option<String>` that fetches the value and prints this to cargo.
</blockquote></details>

I think it's alright to leave this as is.

**Review by faern — COMMENTED** [review]
> Reviewed 4 of 6 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 55 of 59 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @faern)

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 54 of 59 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 6 files at r9, 3 of 9 files at r10, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 58 of 59 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @faern)

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 58 of 59 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`android/app/build.gradle.kts` line 32 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989#-NDlgODk5TikbwukoxHV:-NE-tCG9E9twbef68LRs:bhr7gcv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1ada7e509112705e91a0836e2d9fcd7fd6a6de2b/android/app/build.gradle.kts#L32)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As discussed AFK: Yes, let's do this. So our build pipeline(s) don't need to have Rust etc.
</blockquote></details>

As a separate PR, right? It's not blocking GH actions atm.

**Review by faern — COMMENTED** [review]
> Reviewed 4 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 58 of 59 files reviewed, 1 unresolved discussion

**Review by raksooo — APPROVED** [review]
> Reviewed 1 of 5 files at r15, 2 of 6 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 58 of 59 files reviewed, 1 unresolved discussion

**Review by albin-mullvad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: 58 of 59 files reviewed, all discussions resolved (waiting on @faern)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 24 of 37 files at r1, 1 of 1 files at r2, 3 of 5 files at r3, 6 of 11 files at r4, 1 of 2 files at r6, 5 of 8 files at r11, 1 of 2 files at r13, 1 of 1 files at r14, 2 of 5 files at r15, 1 of 1 files at r16, 1 of 6 files at r17, 2 of 6 files at r18, 1 of 1 files at r19, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3989)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
