### PR TITLE
Use collectAsStateWithLifecycle

### PR DESCRIPTION
**Pull request by Rawa**
Use `collectAsStateWithLifecycle`, and ensure all uses `state` as variable name instead of `uiState`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889)

### CODE REVIEW

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889#-:-Ns82Wp23wwLzjnKSGl8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
Looks good, just a small thought since this PR does two things that is easy to miss in a future feature, do we want to add some konsist check for using collectAsLifecycle and that we want to call the state `state` and not `uiState`?

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889#-:-NsCtaVO2pC0_-sdPbYf:bp9kf9)* status: 24 of 31 files reviewed, all discussions resolved (waiting on @albin-mullvad)

**Review by albin-mullvad — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
Both of those makes sense imo. Should be quite straight forward to add, right? I would say we go ahead and add those :rocket: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889#-:-NsCwlqJ4iPRUIn_3Lsg:b-fojtg7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889#-:-NsDD-FY9m-3Udv2vLzo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5889#-:-NsDQER_396GZAU9QRUn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
