### PR TITLE
Add relay ownership enum to relay constraints

### PR DESCRIPTION
**Pull request by Pururun**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336#-:-NhCQfaM5uWXf8DCpnt1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336#-:-NhQOWw11YtUNdlU2H6_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sabercodic — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336#-:-NhQRrSHBURj9bXsaUNK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
