### PR TITLE
Unify account number naming

### PR DESCRIPTION
**Pull request by albin-mullvad**
This PR aims to unify the "account number" naming within the code base. Rather than using a mix of "account number" and "account token" throughout the Android code base, this PR aims to make sure we **konsist**ently use  "account number". It also includes a test to ensure this convention is followed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6333)

### CODE REVIEW

**Review by Pururun — APPROVED** [review]
:lgtm:

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6333#-:-O--yhtX6gJrC5dJeh4a:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — COMMENTED** [review]
LGTM, should we also change the proto file? because there it is still account_token? It would require work with desktop team though.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6333#-:-O-06c6j56LC2p5Jr4Ko:b-lwadqq)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Rawa — APPROVED** [review]
> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6333)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — COMMENTED** [review]
Yes, there's a separate issue for desktop: https://linear.app/mullvad/issue/DES-1029

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6333#-:-O-0HLil0_RNSgqDFZQL:b430rjl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
