### PR TITLE
Update android editorconfig to the latest from ktfmt repository

### PR DESCRIPTION
**Pull request by Pururun**
This adds the changes from this commit:
https://github.com/facebook/ktfmt/commit/45e78e23eff0697666ca2f9a3535118ff1b13dba

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163)

### CODE REVIEW

**Review by Rawa — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by albin-mullvad — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163#-:-Nw3yV_r1ln1GrRxR6Q8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163#-Nw3yPDE19M3_CIZu4R6):*
What happened here!? :laughing: 



_Code quote:_
```
Update endroid ditorconfig to the latest from ktmfmt repository
```

**Review by albin-mullvad — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

**Review by Pururun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163#-Nw3yPDE19M3_CIZu4R6):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What happened here!? :laughing:
</blockquote></details>

Ehm no idea. Fixed.

**Review by albin-mullvad — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6163#-:-Nw5QJgX3sFFEkIDL_TE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
