### PR TITLE
Replace Electron Log

### PR DESCRIPTION
**Pull request by raksooo**
This PR contains a logging implementation to replace `electron-log`. In contrast to `electron-log` it works well over the Electron IPC which is required for the future move to a sandboxed renderer.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)

### CODE REVIEW

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 8 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 8 of 31 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 273 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-Vl91DtM6USXl3A0v:-MR-Vl91DtM6USXl3A0w:bpku2yt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/index.ts#L273)):*
> ```XML
>     const rendererLogPath = getRendererLogPath();
> 
>     this.rendererLog = new Logger();
> ```

Does it have to be created if we don't use it in development? Maybe move this inside of `if` block below?

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 31 files at r1, 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 10 of 31 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/logging.ts, line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-_oLk0I9yQ3YtXAU6:-MR-_oLk0I9yQ3YtXAU7:b-zh45co) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L49)):*
> ```XML
> 
> export function createLoggingDirectory(): void {
>   fs.mkdirSync(getLogDirectoryDir(), { recursive: true });
> ```

Nice I didn't know `recursive` was supported! :+1: 
___
*[gui/src/main/logging.ts, line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-aBNv9g2A5UakC1dW:-MR-aBNv9g2A5UakC1dX:bdd3el0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L64)):*
> ```XML
>   if (exists) {
>     const backupFilePath = getBackupFilePath(filePath);
>     fs.renameSync(filePath, backupFilePath);
> ```

Probably throws an error. Not sure it's important, but the caller has to account for that I suppose.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 10 of 31 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/logging.ts, line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-a_xG5jQ9s2-ma6Ao:-MR-a_xG5jQ9s2-ma6Ap:b-ivucf4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L61)):*
> ```XML
> 
> export function backupLogFile(filePath: string): boolean {
>   const exists = fileExists(filePath);
> ```

Since fs.accessSync can throw too, you could probably just wrap everything in `try`, i.e:

```
try {
    fs.accessSync(...)
    fs.renameSync(...)
   return true
} catch {
    throw error // rethrow
}
```

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 10 of 31 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/logging.ts, line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-b1NDAHm4LDM_LkHg:-MR-b1NDAHm4LDM_LkHh:bwx4dcd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L73)):*
> ```XML
>   const backupFilePath = getBackupFilePath(filePath);
>   if (!backupLogFile(filePath) && fileExists(backupFilePath)) {
>     fs.unlinkSync(backupFilePath);
> ```

Probably can throw an error too? To me it seems like all `*Sync` methods throw errors, while async counterparts return an error as an argument in a given callback.

**Review by pronebird — COMMENTED** [review]
> Reviewed 12 of 31 files at r1, 3 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 25 of 31 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/ipc-event-channel.ts, line 187 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-bVbB90ilageOWYUu:-MR-bVbB90ilageOWYUv:bgmj805) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/ipc-event-channel.ts#L187)):*
> ```XML
>   },
>   logging: {
>     log: send<{ level: LogLevelNames; message: string }>(),
> ```

You could probably add a type, i.e:

```
interface LogEntry {
  level: LogLevelNames;
  message: String;
}
```

**Review by pronebird — COMMENTED** [review]
> Reviewed 2 of 31 files at r1, 3 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 30 of 31 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging-types.ts, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-c5EHEASSoS2YqRw5:-MR-c5EHEASSoS2YqRw6:b-6x98jc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/logging-types.ts#L9)):*
> ```XML
> 
> export interface ILogOutput {
>   write: (level: LogLevel, message: string) => void;
> ```

Why fields as opposed to functions?

```
interface ILogOutput {
  write(level: LogLevel, message: string): void;
  dispose(): void;
}
```

**Review by pronebird — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging-types.ts, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-cR5cDiTKKdQGkaIS:-MR-cR5cDiTKKdQGkaIT:b4dt02i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/logging-types.ts#L17)):*
> ```XML
> }
> 
> export const LogLevels: { [K in LogLevelNames]: LogLevel<K> } = {
> ```

Maybe we could do the same as outlined in documentation for TypeScript: 
https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time

**Review by pronebird — COMMENTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging-types.ts, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-cR5cDiTKKdQGkaIS:-MR-jZDW2acaXJxg3FoH:bqmoalf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/logging-types.ts#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we could do the same as outlined in documentation for TypeScript: 
https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time




</blockquote></details>

or I guess if you want the name to be static for performance reasons, then leave it as is.

**Review by pronebird — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/logging-types.ts, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-cR5cDiTKKdQGkaIS:-MR-jqA48JaNgikW_Jwe:byzpu5f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/logging-types.ts#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

or I guess if you want the name to be static for performance reasons, then leave it as is.
</blockquote></details>

However the key and name duplicate each other and for enums TypeScript generates the way to obtain the key name by value, i.e: `LogLevel[0]`

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 24 of 31 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 273 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-Vl91DtM6USXl3A0v:-MR-u569EDqT7QFRJG-9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/index.ts#L273)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does it have to be created if we don't use it in development? Maybe move this inside of `if` block below?
</blockquote></details>

Done.
___
*[gui/src/main/logging.ts, line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-a_xG5jQ9s2-ma6Ao:-MR-uBNP6qMnSZTWvI4r:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L61)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Since fs.accessSync can throw too, you could probably just wrap everything in `try`, i.e:

```
try {
    fs.accessSync(...)
    fs.renameSync(...)
   return true
} catch {
    throw error // rethrow
}
```
</blockquote></details>

Done.
___
*[gui/src/main/logging.ts, line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-aBNv9g2A5UakC1dW:-MR-uHaf6l7KSJD2pu4Z:b-ve3nnl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L64)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably throws an error. Not sure it's important, but the caller has to account for that I suppose.
</blockquote></details>

I've now all `fs` calls in try-catch.
___
*[gui/src/main/logging.ts, line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-b1NDAHm4LDM_LkHg:-MR-uRoD1dqivZpgM1ci:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/main/logging.ts#L73)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably can throw an error too? To me it seems like all `*Sync` methods throw errors, while async counterparts return an error as an argument in a given callback.
</blockquote></details>

Done.
___
*[gui/src/shared/ipc-event-channel.ts, line 187 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-bVbB90ilageOWYUu:-MR-uTaQAeVzAEQwqGWH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/ipc-event-channel.ts#L187)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could probably add a type, i.e:

```
interface LogEntry {
  level: LogLevelNames;
  message: String;
}
```
</blockquote></details>

Done.
___
*[gui/src/shared/logging-types.ts, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-c5EHEASSoS2YqRw5:-MR-uUUu0IB2mseQTTA1:b2d4v1o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/logging-types.ts#L9)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why fields as opposed to functions?

```
interface ILogOutput {
  write(level: LogLevel, message: string): void;
  dispose(): void;
}
```
</blockquote></details>

I've now changed this.
___
*[gui/src/shared/logging-types.ts, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR-cR5cDiTKKdQGkaIS:-MR-ue-5CDvODGm7RqoI:b-ibgyjm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56abe3eafecde426ba4b1a171c4fb6ca9eb94371/gui/src/shared/logging-types.ts#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

However the key and name duplicate each other and for enums TypeScript generates the way to obtain the key name by value, i.e: `LogLevel[0]`
</blockquote></details>

Since the changes this morning the object is no longer needed and I switched it to just use an enum. Done.

**Review by pronebird — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/shared/logging.ts, line 50 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR0-HY38rgbMLsFy24d:-MR0-HY38rgbMLsFy24e:b5304pe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4fd97dad1fa4f58fe9bce5ab503d897924aa48b2/gui/src/shared/logging.ts#L50)):*
> ```XML
>   }
> 
>   protected abstract writeImpl(level: LogLevel, message: string): void;
> ```

Another approach would be to handle level filtering in `Logger` & make `level` public. Then we don't have to have two methods, i.e `write` and `writeImpl`, i.e:

```
outputs.filter(o => level <= o.level).forEach(o => o.write(level, message))
```

**Review by pronebird — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

**Review by raksooo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: 27 of 31 files reviewed, all discussions resolved (waiting on @pronebird)

___
*[gui/src/shared/logging.ts, line 50 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-MR0-HY38rgbMLsFy24d:-MR0dK2gAaGE0d3OnDY3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4fd97dad1fa4f58fe9bce5ab503d897924aa48b2/gui/src/shared/logging.ts#L50)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Another approach would be to handle level filtering in `Logger` & make `level` public. Then we don't have to have two methods, i.e `write` and `writeImpl`, i.e:

```
outputs.filter(o => level <= o.level).forEach(o => o.write(level, message))
```
</blockquote></details>

Done.

**Review by pronebird — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pronebird — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2390#-:-MR4vxCIBx2IsciM3gy3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
