### PR TITLE
Fix VPN settings not being persisted

### PR DESCRIPTION
**Pull request by rablador**
- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6772)

### CODE REVIEW

**Review by pinkisemils — COMMENTED** [review]
I fail to see how the changes in code affect the behavior, so I will hold off from approving this.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6772#-:-O6M7f_dEiTloWs8SCmD:bfoeyw3)* status: 0 of 1 files reviewed, all discussions resolved

**Review by rablador — COMMENTED** [review]
The settings for quantum and obfuscation are assigned to a var before the viewmodel is updated. Those old values are then passed to the delegate rather then the actual updated settings.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6772#-:-O6MAcmE6Xi-63s5Gr-d:b9itww7)* status: 0 of 1 files reviewed, all discussions resolved

**Review by pinkisemils — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6772#-:-O6PhOUr3o7P_najKD5U:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @buggmagnet)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6772)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
