### PR TITLE
Stop pushing WireGuard keys for invalid account tokens

### PR DESCRIPTION
**Pull request by dlon**
If the API returned an invalid account error, the daemon would try to push a new key after a while. The maximum delay was 1 hour. This has been fixed. The code has been refactored in general as well.

Main changes:
* Stop trying to push a WireGuard key if the account token is invalid. It will stop after the first failed attempt.
* Increase the maximum retry delay for the initial key push from 1 hour to 1 day.
* Use exponential backoff for retrying automatic key rotation (instead of always retrying after 15 minutes).

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 0 of 2 files reviewed, all discussions resolved

___
*[mullvad-daemon/src/wireguard.rs, line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVLvd9ECPZDAZaZQX4q:-MVLvd9FAg9fT1o8bLQx:b-4w2ok4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L158)):*
> ```XML
>     fn should_retry(error: &RestError) -> bool {
>         if let RestError::ApiError(status, code) = &error {
>             *status != mullvad_rpc::StatusCode::UNAUTHORIZED
> ```

This checks the HTTP status only. Is it necessary to check if `code == INVALID_AUTH` or `code == INVALID_ACCOUNT` as well?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 0 of 2 files reviewed, all discussions resolved

___
*[mullvad-daemon/src/wireguard.rs, line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVLvd9ECPZDAZaZQX4q:-MVMEXJ38EPk32MMQfBp:b7zddhe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L158)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This checks the HTTP status only. Is it necessary to check if `code == INVALID_AUTH` or `code == INVALID_ACCOUNT` as well?
</blockquote></details>

Let's say the API has a regression where it starts returning `INVALID_AUTH`. Let's say they fix it pretty soon after... Then we don't want a number of apps to have semi-permanently disabled their key rotation. So yeah, probably makes sense to only disable the key rotation on `INVALID_ACCOUNT` I guess :thinking:

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-daemon/src/wireguard.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVMKm1W-hszxzKFP6Ss:-MVMMTnH14DmoaSjb9nW:bc0dm0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L379)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why do you need to clone it here. It does not look like you use the original `account_token` after this point in the code. So can't you just hand over the `account_token` ownership to the closure? Same for the other cloned variables here
</blockquote></details>

Oh. Wait. All of this is inside a loop. I see now. Could maybe use some refactoring to make that more obvious. A bit too long method with a bit too much indentation levels IMO

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-daemon/src/wireguard.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVMKm1W-hszxzKFP6Ss:-MVMMa0_9cquPMOsaJZj:b-a2fz8v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L379)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Oh. Wait. All of this is inside a loop. I see now. Could maybe use some refactoring to make that more obvious. A bit too long method with a bit too much indentation levels IMO
</blockquote></details>

Exactly. Actually, I could get rid of some copies, since only `old_key` will change. If the account token changes, `create_automatic_rotation` is aborted. But I don't know if it's any more readable.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVMKm1W-hszxzKFP6Ss:-MVMOtB02vc-dPW_mVHq:b-le8aa1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L379)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Oh. Wait. All of this is inside a loop. I see now. Could maybe use some refactoring to make that more obvious. A bit too long method with a bit too much indentation levels IMO
</blockquote></details>

The body could be moved into a separate function.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVLvd9ECPZDAZaZQX4q:-MVMUz2I-RZte4mhySNF:b8ynkyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L158)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Let's say the API has a regression where it starts returning `INVALID_AUTH`. Let's say they fix it pretty soon after... Then we don't want a number of apps to have semi-permanently disabled their key rotation. So yeah, probably makes sense to only disable the key rotation on `INVALID_ACCOUNT` I guess :thinking: 
</blockquote></details>

What if we start receiving `INVALID_ACCOUNT` because of a bug in the API?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVLvd9ECPZDAZaZQX4q:-MVMf0l98d07ZPB4ogbJ:b8gx0yq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L158)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What if we start receiving `INVALID_ACCOUNT` because of a bug in the API? 
</blockquote></details>

That can also happen of course. Maybe of equal probability as the other one. If true, we would get rid of 50% of the risk by checking on `INVALID_ACCOUNT` instead of all of `UNAUTHORIZED`. And the code becomes more clear what failure it is we are trying to pinpoint with this function.

Later when the infrastructure will prune app keys that are not rotated this will be self healing anyway. Because the key will eventually be deleted on the servers. The app will fail to connect and will check the key and then upload a new one as it detects it has been evicted.

But this thread is not a blocker IMO. Fairly minor and will likely be revisited soon when we change the key management fundamentally.

**Review by faern — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVMKm1W-hszxzKFP6Ss:-MVQaeuK4RCfGOr0Eddq:b9ujck) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L379)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I mean the body of the loop.
</blockquote></details>

Yeah, that would probably help readability.

**Review by pinkisemils — APPROVED** [review]
Reviewable won't show me the comments anymore because I mistakenly resolved gone discussion.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-:-MVQnbht89DFFR2BB-w9:b-ahicxg)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVWjvra2aWJEyoAb-Pk:-MVWjvra2aWJEyoAb-Pl:byn2w2d) (no related file):*
The body has been moved out of the loop.

---
___
*[mullvad-daemon/src/wireguard.rs, line 379 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVMKm1W-hszxzKFP6Ss:-MVRHUv26-7lX8VgeP-P:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L379)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yeah, that would probably help readability.
</blockquote></details>

Done.

**Review by faern — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVWonJPDPrb9XiKWqcU:-MVWonJPDPrb9XiKWqcV:b-ypqtb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1913295a6215445c95f057b3c77200b98352de70/mullvad-daemon/src/wireguard.rs#L27)):*
> ```XML
> 
> const EXPONENTIAL_BACKOFF_ROTATION_RETRY_BASE_MS: u64 = 60;
> const EXPONENTIAL_BACKOFF_ROTATION_RETRY_FACTOR: u64 = 1000;
> ```

`Duration` implements `Mul<u32>`. So you can store the base time as a `Duration` instead of less specifically typed integer.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 158 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVLvd9ECPZDAZaZQX4q:-MVbHOu53Z8dwDZavnW1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/624099385d0719c84cd2b3b4024a1aa71f5bd1d4/mullvad-daemon/src/wireguard.rs#L158)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

That can also happen of course. Maybe of equal probability as the other one. If true, we would get rid of 50% of the risk by checking on `INVALID_ACCOUNT` instead of all of `UNAUTHORIZED`. And the code becomes more clear what failure it is we are trying to pinpoint with this function.

Later when the infrastructure will prune app keys that are not rotated this will be self healing anyway. Because the key will eventually be deleted on the servers. The app will fail to connect and will check the key and then upload a new one as it detects it has been evicted.

But this thread is not a blocker IMO. Fairly minor and will likely be revisited soon when we change the key management fundamentally.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/wireguard.rs, line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554#-MVWonJPDPrb9XiKWqcU:-MVbHNy3E1XIFRq2M_EH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1913295a6215445c95f057b3c77200b98352de70/mullvad-daemon/src/wireguard.rs#L27)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`Duration` implements `Mul<u32>`. So you can store the base time as a `Duration` instead of less specifically typed integer.
</blockquote></details>

Done.

**Review by faern — COMMENTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @pinkisemils)

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
