### PR TITLE
Improve API access

### PR DESCRIPTION
**Pull request by dlon**
This PR makes a number of changes to how the API is reached:

When the daemon is first run, it reads `api-ip-address.txt` from the resources directory, shuffles it, and outputs a cache file in the "user cache"* directory. It starts by using a random endpoint. When the daemon is started and a cache file already exists, it initially uses the first address in this cache and shuffles the other addresses.

If the daemon fails to reach the API, it selects the next address in the cache and outputs a new cache file, storing the selected address on top, so that it is the first to be used by daemon, `mullvad-setup`, or the problem report tool. This makes it likelier that a working endpoint will keep being used when it is eventually found.

An `allow_endpoint` option was added to the firewall, which specifies an endpoint that should be accessible even when the tunnel state machine is in the connecting or error state**. This is initialized to the current API endpoint, and whenever the daemon receives a new API address from the cache, it sets `allow_endpoint` to the new address.

\* "User cache" is a new directory that is readable but not writable by all users. On Linux and Android, it is identical to the cache path, e.g. `/var/cache/mullvad-vpn` on Linux. On Windows, it is `C:\ProgramData\Mullvad VPN`. On macOS, it is `/Users/Shared/mullvad-vpn`.

\*\* On Android, the API is reachable from the error state but not while connecting. This is because it uses routing to block the internet rather than a firewall, and changing the routes seems to require reconnecting. It also lets you reach anything on the API IP, not just using the specific protocol and port.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 0 of 42 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaG0DoB_per0yEtjeG:-MOaG0Dp4pd5j-lLdWxK:b-g1plrc) (no related file):*
The GUI needs to be updated as well. It currently prevents you from verifying the WireGuard key when blocked, and possibly other things too. But this is out of scope for the PR.

---
___
*[mullvad-paths/src/cache.rs, line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaJLxI2CURRYRtMgCZ:-MOaJLxI2CURRYRtMgC_:b1edcsr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-paths/src/cache.rs#L38)):*
> ```Rust
> 
> /// Creates and returns a cache directory that is readable by all users.
> pub fn user_cache_dir() -> Result<PathBuf> {
> ```

Unless it's too much of a hassle, maybe the entire cache directory should be migrated instead. It already is readable by all on Android and Linux, and we don't store anything there that is especially sensitive.
___
*[mullvad-paths/src/cache.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaJ2zMCdPzABwi5EFg:-MOaJ2zMCdPzABwi5EFh:b-d9japb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-paths/src/cache.rs#L54)):*
> ```Rust
>     #[cfg(target_os = "macos")]
>     {
>         Ok(std::path::Path::new("/Users/Shared").join(crate::PRODUCT_NAME))
> ```

I don't know if this is the best place to store this. `/Library/Application Support/` might make more sense.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 11 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 11 of 42 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[dist-assets/pkg-scripts/preinstall, line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaRNFl1HbR6czpghIZ:-MOaRNFl1HbR6czpghI_:b2yrbeg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/dist-assets/pkg-scripts/preinstall#L83)):*
> ```
> # There is a risk that they're incompatible with the format this version wants
> rm "$NEW_CACHE_DIR/relays.json" || true
> # Old API IP cache
> ```

We should probably add a card to remove this in 6-12 months.
___
*[mullvad-rpc/src/address_cache.rs, line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOfXJh-6hJVfaZwmemt:-MOfXJh-6hJVfaZwmemu:bp8cv3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5329f5a02913ea67f63e53e3eb45a846907bd081/mullvad-rpc/src/address_cache.rs#L71)):*
> ```Rust
>     }
> 
>     pub fn register_failure(&self, failed_addr: SocketAddr, err: &dyn std::error::Error) {
> ```

What's the issue with resgistering failure via the failed socket address? It's simpler and makes `tried_current` obsolete, no?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 11 of 42 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-rpc/src/address_cache.rs, line 177 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOfY-xz62whwSjKqj5d:-MOfY-xz62whwSjKqj5e:b-gpv65v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-rpc/src/address_cache.rs#L177)):*
> ```Rust
> 
>     async fn save_to_disk(&self) -> io::Result<()> {
>         let write_path = if let Some(write_path) = self.write_path.as_ref() {
> ```

This could be a bit leaner if it was a match statement. 
```rust
let write_path = match self.write_path.as_ref() {
    Some(write_path) => write_path,
    None => return Ok(());
};
```

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 9 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 20 of 42 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/tun_provider/android/mod.rs, line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOgYss70iclHZmj2Tp5:-MOgYss82GSuLCnv8c11:bnkgrmj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/talpid-core/src/tunnel/tun_provider/android/mod.rs#L142)):*
> ```Rust
>         self.prepare_tun_config(&mut config);
>         self.prepare_tun_config_for_allowed_endpoint(&mut config);
>         self.get_tun(config).map(|_| ())
> ```

Usually a `let _ = self.get_tun(config)?; Ok(())` is preferred over `.map(|_| ())`

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 15 of 42 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/address_cache.rs, line 177 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOfY-xz62whwSjKqj5d:-MOglCiMAxhFBSj5sKGL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-rpc/src/address_cache.rs#L177)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This could be a bit leaner if it was a match statement. 
```rust
let write_path = match self.write_path.as_ref() {
    Some(write_path) => write_path,
    None => return Ok(());
};
```
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/tun_provider/android/mod.rs, line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOgYss70iclHZmj2Tp5:-MOglEz36cRyZrVUYSXS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/talpid-core/src/tunnel/tun_provider/android/mod.rs#L142)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Usually a `let _ = self.get_tun(config)?; Ok(())` is preferred over `.map(|_| ())`
</blockquote></details>

Done.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 3 of 42 files at r1, 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 18 of 42 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 196 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOgunl46lvxe2MI3fHU:-MOgunl46lvxe2MI3fHV:b-ewynws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/talpid-core/src/tunnel_state_machine/connected_state.rs#L196)):*
> ```Rust
>             }
>             Some(TunnelCommand::AllowEndpoint(endpoint, tx)) => {
>                 let _ = shared_values.set_allow_endpoint(endpoint);
> ```

This no longer applies the change to the firewall. Hard to know if it should be done as a method on `shared_values`.

**Review by mvd-ows — CHANGES_REQUESTED** [review]
> Reviewed 12 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 30 of 42 files reviewed, 9 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[windows/winfw/src/winfw/fwcontext.h, line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjrGGqDzPFQF7Iw0rQ:-MOjrGGr-Axl5_gdtf61:by4ym6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/fwcontext.h#L24)):*
> ```objc
> 		uint32_t timeout,
> 		const WinFwSettings &settings,
> 		const std::optional<WinFwEndpoint> &allowEndpoint
> ```

I strongly disapprove of the name `allowEndpoint`. It sounds like a boolean variable. And does not indicate what/why the endpoint is.
___
*[windows/winfw/src/winfw/fwcontext.cpp, line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjtrWPDq7Ivlq_qEa0:-MOjtrWPDq7Ivlq_qEa1:b-x4n7ab) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/fwcontext.cpp#L47)):*
> ```cpp
> }
> 
> baseline::PermitEndpoint::Protocol TranslateEndpointProtocol(WinFwProtocol protocol)
> ```

If you update the rules (this one and the one referenced above), you can have them use the `WinFwProtocol` type directly and avoid these conversions.

That would be less flexible of course, but could maybe be used as a base line?
___
*[windows/winfw/src/winfw/winfw.cpp, line 166 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOk0N1T94RkPxufqxbK:-MOk0N1T94RkPxufqxbL:b-89ncbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/winfw.cpp#L166)):*
> ```cpp
> 		g_logSinkContext = logSinkContext;
> 
> 		g_fwContext = new FwContext(timeout_ms, *settings, allowEndpoint != nullptr ? std::make_optional(*allowEndpoint) : std::nullopt);
> ```

Maybe hide this inside `MakeOptionalEndpoint()`? Especially since the pattern repeats.
___
*[windows/winfw/src/winfw/rules/baseline/permitendpoint.cpp, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjiLwS1ScbKZ_ns73B:-MOjiLwT2XZOnAfH-HOs:basgwux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/rules/baseline/permitendpoint.cpp#L33)):*
> ```cpp
> }
> 
> const GUID &InboundLayerFromIp(const wfp::IpAddress &ip)
> ```

Not used and not likely to become used?
___
*[windows/winfw/src/winfw/rules/baseline/permitendpoint.cpp, line 82 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjp7ek0aCrAoZidIc5:-MOjp7el-v6OC018irBi:b-l83dkt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/rules/baseline/permitendpoint.cpp#L82)):*
> ```cpp
> 
> 	filterBuilder
> 		.key(MullvadGuids::Filter_Baseline_PermitEndpoint())
> ```

Since this uses a unique key, it can only be installed once. It won't be possible to reuse this rule if some other endpoint also needs to be permitted.

Would it not then make sense to conceptualize the specific endpoint we're working with, and make the code more explicit?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 30 of 42 files reviewed, 9 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 196 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOgunl46lvxe2MI3fHU:-MOk82ZfA6-u0EDnZGnS:bfcp523) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/talpid-core/src/tunnel_state_machine/connected_state.rs#L196)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This no longer applies the change to the firewall. Hard to know if it should be done as a method on `shared_values`.
</blockquote></details>

It makes no difference in this state

**Review by pinkisemils — APPROVED** [review]
> Reviewed 2 of 42 files at r1, 10 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon)

___
*[mullvad-paths/src/cache.rs, line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaJLxI2CURRYRtMgCZ:-MOlKUCV-hMthqvu4wkb:b99mmbu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-paths/src/cache.rs#L38)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Unless it's too much of a hassle, maybe the entire cache directory should be migrated instead. It already is readable by all on Android and Linux, and we don't store anything there that is especially sensitive.
</blockquote></details>

Maybe it should, but that should be a different PR and a different discussion.
___
*[mullvad-paths/src/cache.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaJ2zMCdPzABwi5EFg:-MOlSEaM64STB9UpUGht:bso9gbx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-paths/src/cache.rs#L54)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't know if this is the best place to store this. `/Library/Application Support/` might make more sense.
</blockquote></details>

`/Users/Shared` seems like an OK place to store things. But if you do store things here, make sure to update the README, there's a table which lists all the paths our application will use. And of course, the uninstall scripts have to be aware as to remove this, but I see `uninstall_macos.sh` has already been updated.
___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 196 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOgunl46lvxe2MI3fHU:-MOkizoM-ed25tZb8NKe:b-sdaxof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/talpid-core/src/tunnel_state_machine/connected_state.rs#L196)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It makes no difference in this state
</blockquote></details>

Argh, yes, you are correct.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon)

___
*[mullvad-paths/src/cache.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOaJ2zMCdPzABwi5EFg:-MOlUhLSBmUB73Yjat4f:bd93ch2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/47e524195028a571db83ef40851b2c55491accfd/mullvad-paths/src/cache.rs#L54)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`/Users/Shared` seems like an OK place to store things. But if you do store things here, make sure to update the README, there's a table which lists all the paths our application will use. And of course, the uninstall scripts have to be aware as to remove this, but I see `uninstall_macos.sh` has already been updated.
</blockquote></details>

`/Library/Caches` might fit a bit better though.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[windows/winfw/src/winfw/fwcontext.h, line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjrGGqDzPFQF7Iw0rQ:-MOpUBXV5QFvcAqJwkYe:b-8x6h85) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/fwcontext.h#L24)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I strongly disapprove of the name `allowEndpoint`. It sounds like a boolean variable. And does not indicate what/why the endpoint is.
</blockquote></details>

Would `allowedEndpoint` as being the endpoint that is allowed to be reached be better? `allowListedEndpoint` ?

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[windows/winfw/src/winfw/fwcontext.h, line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjrGGqDzPFQF7Iw0rQ:-MOpWgm85HfW-vmv20zE:b-59nav) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/fwcontext.h#L24)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would `allowedEndpoint` as being the endpoint that is allowed to be reached be better? `allowListedEndpoint` ?
</blockquote></details>

I've renamed it to `allowedEndpoint` (but not yet pushed the changes).

**Review by mvd-ows — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[windows/winfw/src/winfw/fwcontext.h, line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjrGGqDzPFQF7Iw0rQ:-MOpV2S13mp_dJ5VkxpZ:bdjddhd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/fwcontext.h#L24)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would `allowedEndpoint` as being the endpoint that is allowed to be reached be better? `allowListedEndpoint` ?
</blockquote></details>

`allowedEndpoint` I would say is marginally better. I was hoping to see something more specific, e.g `apiEndpoint` or `apiServer`.

David explained that the layers of code above also don't know what the endpoint is. I'm sure there's a good reason for that.

But now every time someone reads this code they have to remember that `allowEndpoint` means `API server` and that, since it's the API server, it's OK to access it in the blocked state.

**Review by dlon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 18 of 44 files reviewed, 3 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[windows/winfw/src/winfw/fwcontext.cpp, line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOjtrWPDq7Ivlq_qEa0:-MOpbs7o-ZsD8b2IKQv9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/fwcontext.cpp#L47)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

If you update the rules (this one and the one referenced above), you can have them use the `WinFwProtocol` type directly and avoid these conversions.

That would be less flexible of course, but could maybe be used as a base line?
</blockquote></details>

Done.
___
*[windows/winfw/src/winfw/winfw.cpp, line 166 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356#-MOk0N1T94RkPxufqxbK:-MOpbtJuAtUPO11-de24:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2713462e5ce76847c36c5905d171b39aa25b2ef2/windows/winfw/src/winfw/winfw.cpp#L166)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Maybe hide this inside `MakeOptionalEndpoint()`? Especially since the pattern repeats.
</blockquote></details>

Done.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 17 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 35 of 44 files reviewed, 3 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 36 of 44 files reviewed, 3 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

**Review by mvd-ows — COMMENTED** [review]
> Reviewed 7 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 43 of 44 files reviewed, 3 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: 43 of 44 files reviewed, 2 unresolved discussions (waiting on @dlon and @mvd-ows)

**Review by mvd-ows — APPROVED** [review]
> Reviewed 1 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2356)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

**Pull request merged**
